### ISSUE TITLE
Damp Rag звучит как стеклянный стакан

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#10005]
#### Подробное описание проблемы
Тряпка при перемещении рукой на стол издаёт "дзынь", как стакан.
#### Что должно было произойти
Тряпка не стакан
#### Что произошло на самом деле
Тряпка стакан и в неё можно наливать (!)
#### Как повторить
зайти в игру и нажать тряпкой на стол

**Comment by Tap0r** [comment]
Коробки с соком и молоком тоже. Железное ведро тоже.

**Comment by Tap0r** [comment]
То что тряпка стакан это фича, а не баг. Надо звук добавить для них

**Comment by Rahmanio** [comment]
<details>
шиза
![Screenshot_2354](https://user-images.githubusercontent.com/67812445/188707706-ac958449-07d1-4b91-a30a-889be2fef598.png)

</details>
дубликат #9763
