### ISSUE TITLE
Сайт таукиты сломался

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#10004]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/45365635/188696755-0d286bcd-8133-4250-b6d5-783ea893df66.png)

#### Что должно было произойти
Я не нашел скрин нормальной разметки
#### Что произошло на самом деле
Вот это
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/45365635/188697327-57e11d53-9d38-408f-b36c-f65bc82a5f98.png)

**Comment by BunkyFly** [comment]
Пиши киборгу в дисе, а не сюда южул

**Comment by KIBORG04** [comment]
Пишите в оперу или воласу, или в репозиторий хаба
