### ISSUE TITLE
Табуретка багует дип фраер

### ISSUE THREAD

**Issue by YulianR** [TauCetiStation/TauCetiClassic#1003]

**Comment by Dennok** [comment]
при попытке всунуть в руку другому человеку тоде багаетса и падает на пол. При этом вроде и у человека в руке она.

**Comment by Damirrus1** [comment]
Это все странный механ табуретки, которую каким-то чудным образом нельзя кинуть дальше, чем на 1 тайл

**Comment by igigin** [comment]
#1993
