### ISSUE TITLE
фичастая тряпка

### ISSUE THREAD

**Issue by BlankCringe** [TauCetiStation/TauCetiClassic#10031]
#### Подробное описание проблемы
У тряпки бармена звуки стакана
#### Что должно было произойти
У тряпки нет звуков

#### Что произошло на самом деле
Стекло тряпка
#### Как повторить
Положить тряпку на стол
#### Дополнительная информация:
Зачем тряпке вообще вмещать в себя реагенты если с этим ничего нельзя сделать?

**Comment by MrBite** [comment]
Тряпка вмещает в себя реагенты не просто так. Заливаешь в тряпку реагент,целишься на рот и кликаешь по кукле. Получается бюджетный гипоспрей
