### ISSUE TITLE
Вкалывание чипа скилов не повышает скилы

### ISSUE THREAD

**Issue by Fluffy-510** [TauCetiStation/TauCetiClassic#10049]
#### Подробное описание проблемы
После вкалывания чипа скилов сами скилы не повысились
#### Что должно было произойти
Чип вкололи, скилы куклы повысились
#### Что произошло на самом деле
Чип вкололи, скилы остались прежними 
#### Как повторить
Попросить главу (ГП) повысить вам скилы и пройти чиповизацию 
#### Дополнительная информация:
В обоих случаях я был научным ассистентом, в обоих просил повысить скилы на РИПЛИ, в обоих случаях скилы не изменились(даже в скилл панель).
Ps Первый раз был около 2 месяцев назад, а второй вчера.

**Comment by BunkyFly** [comment]
@Dushess0

**Comment by LoTaRk-FroG** [comment]
Как я понял, скилл повышается, но в скиллс меню не отображается.

**Comment by Dushess0** [comment]
Оно повышает скилы, скилы полученые от импланта не отображаются в skill panel

**Comment by Rahmanio** [comment]
> Оно повышает скилы, скилы полученые от импланта не отображаются в skill panel

Игрок говорит что скиллы не повысились и в игре, на практике, помимо скилл панели. И этому есть подтверждения в игре, не в первый раз жалуются. Я не знаю что делают игроки, но сам механ видимо неочевиден, лучше добавить отображение скиллов, полученных от импланта.

**Comment by Fluffy-510** [comment]
Я подозреваю что это был скилл ишью, так как в самой игре не поковыряв кусачками/ не начав проводить операцию сразу не поймёшь получил скилы или нет, если бы игрока оповещало что его скилы выросли, то было бы понятней и проще
Я думаю этот «баг» надо закрыть
