### ISSUE TITLE
Спам бессмысленных сообщений при стрельбе кинетиком

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#10075]
#### Подробное описание проблемы
При стрельбе кинетиком происходит спам бессмысленых сообщений. Так же при стрельбе в упор к породе производиться неприятный звук.
#### Что должно было произойти
You fire the proto-kinetic accelerator!
#### Что произошло на самом деле
В чате пишется
You fire the proto-kinetic accelerator!
The phoron crystals is hit by a full strength kinetic force, without leaving a mark! x7
The kinetic explosion is hit by a full strength kinetic force, without leaving a mark!

Видно что удар идёт даже по kinetic explosion.
#### Как повторить
Пострелять из кинетика на астероиде.

**Comment by BiQndy** [comment]
реально фигня неприятная

**Comment by volas** [comment]
#9835

вроде пофикшено
