### ISSUE TITLE
У решетки только 1 состояние

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#10078]
#### Подробное описание проблемы
У grillов пропали промежуточные состояния
#### Что должно было произойти
Решетка может быть целой, немного сломанной, почти полностью сломанной и уничтоженной
#### Что произошло на самом деле
Решетка есть или её нет

**Comment by volas** [comment]
#9835

**Comment by kalazus** [comment]
Повторить не получилось, у нас и раньше были только состояния: целое, немного сломанное (в 4 вариантах), сломанное

**Comment by simb11** [comment]
это касается только гриллов, которые раундстартом должны быть раздолбаны.
