### ISSUE TITLE
Некорректная работа подноса

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1008]
#### Подробное описание проблемы
~Не рабочий рецепт конфеты.~ Сломанный поднос.
~Конфету "Taffy" на вики не возможно создать из за компонента в виде соли. Машина отказывается принимать соль.~
Поднос не отдает предметы которые под себя "взял" даже если его кидать и что-либо еще.

#### Что должно было произойти
~Соль должна иметь возможность попасть в машину что бы приготовить конфету.~
Поднос должен давать возможность забирать то что на нем лежит.
#### Что произошло на самом деле
~Рецепт сломан и сделать конфету невозможно.~
Взять предметы из под подноса невозможно.
#### Как повторить
~Попытаться сделать конфету по репепту.~
На тайл с подносом положить вещь и взять поднос.
#### Дополнительная информация:
Уже лет 100 прошло с этим подносом а его так и не починили.

**Comment by Damirrus1** [comment]
SUGAR - это не соль

**Comment by Avatar4** [comment]
> 5 units of Sugar, 5 units of SALT, 5 units of Water

**Comment by Skippeer12** [comment]
Поднос это фича, которую никто не будет фиксить, найди ассистента и смачно вреж ему подносом, профит

**Comment by SpaiR** [comment]
@Avatar4 **ОДИН ИШЬЮ - ОДИН БАГ, БЛЕАТЬ!**

**Comment by Skippeer12** [comment]
Не баг, а фича.

**Comment by Motzord** [comment]
Да, он является актуальным для текущей версии билда
