### ISSUE TITLE
Блоб не ломает канистры с газом

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#10084]
#### Подробное описание проблемы
Блоб теперь не ломает канистры с газом, вместо этого канистры просто исчезают, без выпускания газа в атмосферу
#### Что должно было произойти
Канистра ломается, газ выходит.
#### Что произошло на самом деле
Канистра с газом просто исчезает
#### Как повторить
Сломать блобом канистру
#### Дополнительная информация:
Возможно из-за полной разрушаемости.

**Comment by arygal** [comment]
фича

**Comment by notkripton** [comment]
фича

**Comment by Akellazp** [comment]
хуича

**Comment by volas** [comment]
#9835
