### ISSUE TITLE
Закрытые шкафчики нельзя сломать 

### ISSUE THREAD

**Issue by RONSI7** [TauCetiStation/TauCetiClassic#10099]
#### Подробное описание проблемы
Закрытые шкафчики нельзя сломать. Прожимая по закрытому шкафчику, каким либо предметом, на интенте харм ты его или откроешь, если он без замка, или в чат придёт сообщение "Access denied", если он с замком.
#### Что должно было произойти
Ты ломаешь закрытый шкафчик ломом.
#### Что произошло на самом деле
Открываешь или пытаешься его открыть.
#### Как повторить
Взять что-то в руку и попытаться ударить на харме закрытый шкафчик.

**Comment by KIBORG04** [comment]
Не по форме

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/9835
