### ISSUE TITLE
Больше нельзя кататься на стуле

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#10094]
#### Подробное описание проблемы
После какого-то фикса мувемента стало невозможным кататься на стуле. 
#### Что должно было произойти
Катаюсь. 
#### Что произошло на самом деле
Катаюсь через пулл. 
#### Как повторить
Сесть на стул с колёсиками.

**Comment by notkripton** [comment]
Пофикшено, ждите обновления билда. (ишуй можно закрывать)
