### ISSUE TITLE
Суперскорость при грабе

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#10092]
#### Подробное описание проблемы
Когда одна кукла берет в первый граб другую и они вместе бегут в одну сторону, то развивают суперскорость.
#### Что должно было произойти
Скорость не должна увеличиваться, а возможно даже и падать.
#### Как повторить
Один берет в первый граб другого, и если они бегут в одну сторону скорость обоих резко увеличивается

**Comment by RONSI7** [comment]
Суперскорость развивается еще при простом пуле куклы, если та не замедлена по каким либо причинам. Это даже работает если куклу пулить на каталке.

**Comment by notkripton** [comment]
Баг повторить не получилось. Скинь видео-пример.

**Comment by Chip11-n** [comment]
Подтверждаю граб. Берёшь 2-10 человек, каждый из которых грабает друг-друга в две руки, идёте в одну сторону и бегаете быстрее генки, ведь каждый делает свой отдельный шаг.
