### ISSUE TITLE
Rack разбирается на table parts.

### ISSUE THREAD

**Issue by RONSI7** [TauCetiStation/TauCetiClassic#10104]
#### Подробное описание проблемы
Если разобрать гаечным ключом rack, то на выходе мы получим table parts.
#### Что должно было произойти
Разбирая rack мы получаем rack parts.
#### Что произошло на самом деле
Разобрав rack, получаем table parts.
#### Как повторить
Взять в руки wrench, кликнуть им на rack.

**Comment by Pirsnya** [comment]
может я не прав но 
```
/obj/structure/rack/attackby(obj/item/weapon/W, mob/user)
	if (iswrench(W))
		new /obj/item/weapon/rack_parts( src.loc )
		playsound(src, 'sound/items/Ratchet.ogg', VOL_EFFECTS_MASTER)
		qdel(src)
		return
```
разве не здесь смысл того что это должно быть именно rack а не table?

**Comment by Pirsnya** [comment]
Видимо опять @kalazus всё сломал!
