### ISSUE TITLE
[Proposal] Подгрузка разных астероидов.

### ISSUE THREAD

**Issue by Tap0r** [TauCetiStation/TauCetiClassic#10101]
#### Подробное описание проблемы
Надо астероиды чтоб разные для разных карт грузить можно было, чтобы круто было.
#### Что должно было произойти
На Прометее свой крутой астероид.
#### Что произошло на самом деле
Там боксовский астероид.
#### Дополнительная информация:
шахтёры страдают бегают в другой конец карты, а если будет прометеевский астероид на прометее, то будет норм, там второй док для шахтошаттла на станции будет и вообще шахтёрам с археологам кайфовое будет.

**Comment by volas** [comment]
Решается вхардкоживанием нового параметра ``config.minetype`` и добавлением подгрузки сюда, по примеру как у обычного астеройда:

https://github.com/TauCetiStation/TauCetiClassic/blob/57652a78c56dbcc809b633acc4aba2123e17293c/code/controllers/subsystem/mapping.dm#L222-L227

опционально можно еще добавить ``minetype = "random asteroid"``, который бы pick-ал один из двух.

**Comment by Venngedi** [comment]
#10492 Можно закрыть.
