### ISSUE TITLE
[bug] Исчезающие провода при отрезании

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#10114]
#### Подробное описание проблемы
Режешь провод и он исчезает.
#### Что должно было произойти
Кусочек провода должен появится.
#### Что произошло на самом деле
Проваливается в нуллспейс.
#### Как повторить
Отрезать провод. Может связано с разрушаемостью?
#### Дополнительная информация:
Issue reported from  Round ID: 54528 (Tau Ceti Classic (RU))
Testmerges: ```#9784 #9835 #9889 #9988 #10001 #10057 #10058 ```
Reporting client version: 514.1575

**Comment by kalazus** [comment]
Смешно, что об этом сообщили через 10 дней после начала тма.
