### ISSUE TITLE
[Proposal] Убрать разрушение труб, скрабберов, вентиляций от температуры

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#10117]
В связи с введением полной разрушаемости различные трубы, скрабберы и т.п. уничтожаются от температур в районе 1500 градусов, что выглядит очень странно и неудобно, невозможно пользоваться сжигателем, нельзя поджигать форон в РнД в специальной для этого камере. Предлагаю полностью убрать разрушение труб от высокой температуры. Возможно имеет смысл также сильно повысить устойчивость пласталевых стен и фороновых стекол к температуре.

**Comment by kalazus** [comment]
Вроде уже нет, добавлял всем атмос штукам неуязвимость.

**Comment by F0xiq** [comment]
Будем смотреть, только что в раунде форон уничтожил все трубы, возможно исправление ещё не на сервере.

**Comment by Fenriros** [comment]
МОжет сделать спец трубы? =)

**Comment by kalazus** [comment]
Уже убрано, можно закрывать. Забыл наверное добавить номер пропосала.
