### ISSUE TITLE
Легкий способ краша в один клик

### ISSUE THREAD

**Issue by NinjaPikachuska** [TauCetiStation/TauCetiClassic#10124]
#### Подробное описание проблемы
Для краша нам понадобится:
 - Ручка
 - Бумажка
 - Жертва

Берем ручку и пишем на бумажке следующее (чем больше, тем лучше): <details>[bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh][bh]</details> 
Показываем эту бумажку кому угодну. Итог: вылет.
#### Что должно было произойти
Счастливые игроки, хороший билд
#### Что произошло на самом деле
https://forum.taucetistation.org/t/banhammer-german-tzo-primenenie-zapretnogo-zaklinaniya-oslo-bus/35708
#### Как повторить
Поиграть на тау ките.
#### Дополнительная информация:
Меня забуллили этой бумажкой 😔

**Comment by KatoMarika** [comment]
Пофикшено #10127
