### ISSUE TITLE
Культисты могут злоупотреблять переименованием зон

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#10146]
#### Подробное описание проблемы
культисты могут менять название зоны и ставить захват зоны, а экипаж как дебилы будут искать отдел POPROBYITE NAITI STATUYO YEBU или чё-то такое
#### Что должно было произойти
Наверное культяпки не могут ставить захват в переименованных или новых зонах
#### Что произошло на самом деле
Могут

**Comment by KIBORG04** [comment]
Вроде лёгкое, нужно во всех анноунсах вместо `area.name` сделать `initial(area.name)`
