### ISSUE TITLE
[Proposal] Добавить в культ роль Нар-си

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#10143]
#### Подробное описание проблемы
Предлагается выпилить из культа роль Хайбрингер и заменить его 1 игроком-богом. Большой проблемой культа является его тотальная не командная игра, отсутствие слаженности и тд, я предлагаю это решить добавлением некого культо-ИИ, который будет выполнять текущие функции хайбрингера + другие, типа исследований, менеджмент ресурсов, координации, уничтожение всех на станции.

Я предлагаю реализацию идеи в таком виде:
 - Это будет некая камера ИИ, которая может видеть либо только от глаз культистов, либо всю карту. 
 - Возможно, сделать в начале раунда некую процедуру превращения какого-то культиста в нар-си, чтобы избежать смаллгев и тех, кто не хочет.
 - Свои микро-фичи по коммуникации с отдельным экипажем станции
 - Возможность давать временные задания культистам, можно сделать каким-то maptext'ом на экране, может какую-то доску заданий простую, вызываемую по экшен-кнопку.
 - Возможно, сделать возможность ставить точки интереса, как приказы в стратегиях. Это может быть какой-нибудь спрайт мечей видимый культистам, находящимся на станции, который будет обозначать атаку на бриг, например
 - Сделать какие-то АоЕ баффы, например с той же механикой приказов.
 - Беспрепятственное строительство в зоне культа
 - Улучшенный менеджмент фавора и пиети, мб какими-то логами расходов, мб какой-то кап трат на культиста, может вообще ничего не делать.

**Comment by simb11** [comment]
мне это напоминает хайвмайнд с тгмц, там это местный полуматериальный ИИ ксенов, который занимается постройкой, менеджментом улучшений, микробаффами алиенов и ещё может выдавать обжективы ксенам, вместе с метками, текстом и всяким таким.
если интересно, можете посмотреть чё там.

**Comment by Chip11-n** [comment]
Идейно действительно напоминает хайвмайнд с ТГМС, однако есть альтернатива куда более близкая и проще в реализации: маркер клокворка с ТГ. Базово, он умел раздавать приказы, видеть карту, телепортироваться к своим, а также активировать постройки своего культа, призывать всех в одно место (надо бы открыть этот ПР уже). Создавался он путём особой постройки на "небесах" по центру базы, где давалось два варианта: стать маркером, предложить роль гостам.

**Comment by KIBORG04** [comment]
Первый раз слышу, но я смотрел скорее в сторону божеств с бея, но они щас выпилены отовсюду из-за багов и мертвго кодера

**Comment by AndroBetel** [comment]
надо добавить огромного культомеха который пиздит культей за неповиновение и которого можно на минуту ритуалом призвать на стейшен
