### ISSUE TITLE
Хлак не может бить людей.

### ISSUE THREAD

**Issue by Ro2tCrab** [TauCetiStation/TauCetiClassic#10150]
#### Подробное описание проблемы
Халк тупо не может ударить кого-то
#### Что должно было произойти
RIP AND TEAR UNTIL IT DONE.
#### Что произошло на самом деле
*хнык* Помогите! Меня избивает клоун гудком.
#### Как повторить
Взять любого халка.
#### Дополнительная информация:
-

**Comment by Bullethole** [comment]
интент менял?
