### ISSUE TITLE
На свалке пропала тьма

### ISSUE THREAD

**Issue by Lexakr** [TauCetiStation/TauCetiClassic#10158]
#### Подробное описание проблемы
На свалке вообще нет тьмы, даже тайлы скал освещены
#### Что должно было произойти
Мрак ночной

**Comment by Pirsnya** [comment]
В ВВ находишь переменную dynamic lighting или как-то так, масс модифаем выключаешь и включаешь ( на турфе ), так с каждым там где не работает свет
