### ISSUE TITLE
Бедные игроки вынуждены менторить ради чатика для избранных

### ISSUE THREAD

**Issue by dearprincesscelestia** [TauCetiStation/TauCetiClassic#1016]
#### Подробное описание проблемы
Доступ к внутреннему чату, не доступному большинству игроков, но доступному  группе игроков-друзей, неизбежно сопряжен со статусом ментора.

#### Что должно было произойти
Игроки должны иметь возможность создать канал, доступный им и выбранным ими игрокам для того, чтобы здороваться только с теми, с кем хочется, обходить мут ООС и постить смишнявки, не вызывая подозрений в коопе (потому что виден также админам) и не выполняя ненавистную им неоплачиваемую работу, о которой они даже и не просили. 

#### Что произошло на самом деле
![image](https://cloud.githubusercontent.com/assets/18510817/21940849/262ee068-d9d7-11e6-960d-d5f8a62f9e82.png)
![image](https://cloud.githubusercontent.com/assets/18510817/21940853/2a60bbc0-d9d7-11e6-813b-9429ccdddb59.png)
![image](https://cloud.githubusercontent.com/assets/18510817/21940856/2d154782-d9d7-11e6-8cc8-17f3c150482d.png)
![image](https://cloud.githubusercontent.com/assets/18510817/21940860/3090d4f8-d9d7-11e6-8aab-023b5fd8959d.png)
> Однако в чем смысл не давать переговаривать людям которые занимаются общим делом? Конечно кооп по менторхелпу это слишком, но убрать эффект так сказать "близости" менторов, это все равно что вырезать себе мозг. Вы просто сделаете менторов аутистами боргами своими охуенными фиксами.

> Это тоже самое что нанять на работу человека отвечающего на вопросы людей и не платить ему зарплаты

> Но ведь берут тебя даже если ты не хочешь, а любая работа должна оплачиватся.
#### Как повторить
Получить возможность просмотра менторхелпа, ждать раунда с большим количеством менторов, указать на гитхабе, выслушать менторов

#### Дополнительная информация:
Возможные пути решения:
1. Убрать у менторов возможность задавать вопросы в менторхелп (не знаешь чего-то - вон из профессии, НЕ ЗНАЕШЬ ЧЕГО-ТО - ВОН ИЗ ПРОФЕССИИ, ВООООООНННННННН!!!1! пишите заявку на дементорство, как я).
2. Убрать у менторов ссылку на нике отвечающего ментора в менторхелпе, чтобы отвечать можно было только игроку, задавшему вопрос.
3. Добавить возможность нементорам точно так же организовать внутренний чатик только для своих, не выолняя ненавистные менторские обязанности

**Comment by igigin** [comment]
Так они там с педалями коопят, пустить их всех под колёса анпедала.

**Comment by dearprincesscelestia** [comment]
И это тоже. Вообще отрезать админам менторхелп. Хочешь менторить за админа - подаешь заявку и на админа, и на ментора.

**Comment by skvazarb** [comment]
Итого: вернуть менторам старый мхелп и добавить возможность его отключения в преференсах.

**Comment by igigin** [comment]
Нет, я просто запрещу менторам в него писать.

**Comment by Avatar4** [comment]
>не знаешь чего-то - вон из профессии, пишите заявку на дементорство, как я
>НЕ ЗНАЕШЬ ЧЕГО-ТО - ВОН ИЗ ПРОФЕССИИ.
>ВООООООНННННННН!!!1!
Дядя, вам лечиться надо.
>и вообще все еще илитка.
О боже, игроки ЧАТЯТСЯ. Какой ужоссс!! Они не пользуются флудилкой в новом слаке и теперь засоряют мне чат! Убить, уничтожить!
По моему у вас явно какие-то проблемы с восприятием помощи. Менторство - в первую очередь обязывает лишь одним: Отвечать на вопросы других таких же игроков по возможности. Однако в чем смысл не давать переговаривать людям которые занимаются общим делом? Конечно кооп по менторхелпу это слишком, но убрать эффект так сказать "близости" менторов, это все равно что вырезать себе мозг. Вы просто сделаете менторов аутистами боргами своими охуенными фиксами. Можете добавить мут менторов как возможную меру, но не перебарщивайте со своим хейтом.
Некоторых из нас просто пригласили помочь и мы согласились. Но нахер тогда скажите помогать если всех менторов начнут дудосить за то что они скажут "привет" в ментрохелп? Вы немного рискуете вообще остаться без помощников. Во всяком случае, мне кажется что вы перебарщиваете.

**Comment by skvazarb** [comment]
>Можете добавить мут менторов как возможную меру

Уже есть

**Comment by Avatar4** [comment]
Ну так в чем проблема? Творят хуйню - мутайте, и все. Не понимаю к чему тут Целестии творить батхерд. Я так подозреваю, что это личная обидка.

**Comment by YulianR** [comment]
И убрать звук менторхелпа для админов, ибо не для админов

**Comment by Tankred0** [comment]
Псевдоилитизм, на самом деле решается пермамутами, которые игигил давно обещал.

**Comment by igigin** [comment]
Только они оставят бедного ментора и без пмок, а зачем он тогда ментор?

**Comment by Lancer411** [comment]
Илитизм псевдо только со стороны.

**Comment by Tankred0** [comment]
А дать возможность им только отвечать есть?

**Comment by Skippeer12** [comment]
ООС любят мутить
Как и АХ и МХ. Вообще менторы не нужны
Переложить всю работу пора на педаль, хочешь помогать иди в педаль, а если не берут то не лезь.

**Comment by dearprincesscelestia** [comment]
Если ООС под мутом, то ментор должен, как и все остальные игроки, обходиться без "привет". Потому что менторы - это не какой-то высший сорт игроков.

**Comment by Skippeer12** [comment]
Но ведь он выше, потому как знает как работает механ в игре.

Это тоже самое что нанять на работу человека отвечающего на вопросы людей и не платить ему зарплаты, у всех есть привелегии, так устроен мир, привыкай,

**Comment by dearprincesscelestia** [comment]
Ментор - дело добровольное. Не хочешь - не ментори. А за привелегиями идите на форум.

**Comment by Skippeer12** [comment]
Но ведь берут тебя даже если ты не хочешь, а любая работа должна оплачиватся.
Если хочешь чтобы работу делали, дай людям что-то взамен, что-то стоящое.

**Comment by dearprincesscelestia** [comment]
Не хочешь - не ментори, в чем проблема?

**Comment by StrikS** [comment]
Не нравятся видеть, что менторы болтают в менторхелпе? Не ментори.

**Comment by dearprincesscelestia** [comment]
Но ведь не отнимают ментора, хотя заявление третий день лежит. Если официальная позиция такова, что менторы не чтобы менторить, а чтобы быть илиткой - пусть меня снимают.

**Comment by StrikS** [comment]
Освободите Кукиза от обязанности менторить, видите, человек страдает. Даже срач развел.

**Comment by Avatar4** [comment]
У человека какая-то проблема на псевдоилитизм где любой может назвать кого-то говном.

**Comment by dearprincesscelestia** [comment]
В фонд цитат.

**Comment by igigin** [comment]
>Творят хуйню - мутайте

>решается пермамутами

>добавить мут менторов

Вот вы тут такие предлагаете мутить всех и каждого, но как только фактически делают один общий и вечный мут, чтобы облегчить педалям работу, так сразу "не то, мы не просили, лицо себе выпили".

>берут тебя даже если ты не хочешь

Просто говоришь нет, если не хочешь и никуда тебя не берут.

>Но нахер тогда скажите помогать если всех менторов начнут дудосить за то что они скажут "привет" в ментрохелп?

То есть помогать егрокам, не говоря своим друзяшкам "привет", менторы не в состоянии?

Напомню, что оставил я мхелп открытым для вопросов менторов (хотя мне сразу говорили закрыть, да и я так думал) только потому, что понадеялся на их какую-то ответственность и благонадёжность и Куршан сказал, что если болтовня будет, то её будут пресекать.
Ни того, ни другого нет, но теперь вот выбегают и кричат, что без привилегий работать не будем, оставьте чатики, добавьте гибов, дайте спавн и ещё пытаются убедить, что это не илитизм и всё такое.

**Comment by Avatar4** [comment]
Но все таки, я за то что бы убрать звук у педалей когда спрашивают в менторхелп. Или же заменить звук у них и допустим оставить если спрашивают в менторхелп а менторов самих нет.

**Comment by igigin** [comment]
Собственно, если ты глянешь внутрь ПРа, то заметишь там в описании, что звук я убрал.

**Comment by dearprincesscelestia** [comment]
После изучения реакции жертв сложившейся ситуации, выкатываю другое решение, которое должно устроить всех - кроме, разумеется, псевдоилиты, но ее же у нас тут нигде нет, верно, Аватарч, Штрикш и Шкиппер?

**Comment by Udokun** [comment]
Зачем такие сложности? Легче просто выгонять менторов за превышение "должностных" полномочий.

**Comment by dearprincesscelestia** [comment]
Выгоняй.
