### ISSUE TITLE
У новых фотокамер нет зума.

### ISSUE THREAD

**Issue by RONSI7** [TauCetiStation/TauCetiClassic#10160]
#### Подробное описание проблемы
У новых фотокамер нет вот этого:
![Screenshot_9](https://user-images.githubusercontent.com/80349675/192969621-6ef403e7-0907-487f-94ad-ff591d2e37d1.png)
Из-за чего я не могу сделать такое фото:
![Screenshot_11](https://user-images.githubusercontent.com/80349675/192969961-2a373f14-a71c-4569-869d-2d28a4daa73a.png)
И такое фото:
![Screenshot_12](https://user-images.githubusercontent.com/80349675/192970016-c1ca4732-66be-42a7-8211-5f46604f2fe1.png)
Могу делать только такие:
![Screenshot_10](https://user-images.githubusercontent.com/80349675/192970178-a7811ed6-3487-452f-ac44-b0f09cd82566.png)

#### Что должно было произойти
Я могу сделать все три вида фотографий показанных выше. 
#### Что произошло на самом деле
Я могу сделать только один вид фотографий.
#### Как повторить
Играть в нынешний билд.

**Comment by DarthSidiousPalpatine** [comment]
Альтклик, всё работает, прямо сейчас в раунде жёстко делаю три тысячи фотографий разных размеров.

**Comment by KIBORG04** [comment]
Неочевидный механ, дааа, но не баг

**Comment by RONSI7** [comment]
> Альтклик, всё работает, прямо сейчас в раунде жёстко делаю три тысячи фотографий разных размеров.

Может стоит вернуть настройку зума через ПКМ, что бы неочевидное было более очевидным. Ну и с линзами тоже самое сделать.

**Comment by DarthSidiousPalpatine** [comment]
> > Альтклик, всё работает, прямо сейчас в раунде жёстко делаю три тысячи фотографий разных размеров.
> 
> Может стоит вернуть настройку зума через ПКМ, что бы неочевидное было более очевидным. Ну и с линзами тоже самое сделать.

Нет

**Comment by RONSI7** [comment]
> > > Альтклик, всё работает, прямо сейчас в раунде жёстко делаю три тысячи фотографий разных размеров.
> > 
> > 
> > Может стоит вернуть настройку зума через ПКМ, что бы неочевидное было более очевидным. Ну и с линзами тоже самое сделать.
> 
> Нет

Почему, в чем проблема?
