### ISSUE TITLE
Линзы невозможно снять с фотокамеры.

### ISSUE THREAD

**Issue by RONSI7** [TauCetiStation/TauCetiClassic#10162]
#### Подробное описание проблемы
Если вставить линзу в фотокамеру, то ты ее уже не снимешь.
#### Что должно было произойти
Я могу в любой момент снять линзу и вставить другую если нужно.
#### Что произошло на самом деле
Я ношу с собой несколько фотокамер для каждой линзы.
#### Как повторить
Играть в нынешний билд.

**Comment by DarthSidiousPalpatine** [comment]
Контролклик, всё работает. Прямо сейчас в раунде жёстко вставляю и вытаскиваю линзы из фотика

**Comment by KIBORG04** [comment]
Кто эти хоткеи придумал? Может ещё и фотик не запуллить?

**Comment by RONSI7** [comment]
Да блинб, я ведь тоже проверял на кнопки, но вот про Альт не подумал.
