### ISSUE TITLE
Невозможность подобрать ресурсы в mining satchel за борга

### ISSUE THREAD

**Issue by Classical-User** [TauCetiStation/TauCetiClassic#10174]
#### Подробное описание проблемы
Взял в начале раунда борга, выбрал модуль шахтёра, после прохода через телепорт оказался на астероиде, начал копать переключив бур не в безопасный режим для ускорения, далее выпали ресурсы, выбрал mining satchel в используемые иконки, нажал mining satchel на руду, написалось в текстовой окне что руда подобралась "You put everything into Mining Satchel.", но руда осталась на полу, повторное нажатие на руду ничем не помогло. Так же не работал автоподбор руды. Администратор вселился в меня, повторил те же действия, бесчетно.
#### Что должно было произойти
Помещение руды в мешок
#### Что произошло на самом деле
Руда осталась на полу
#### Дополнительная информация:
Issue reported from  Round ID: 54744 (Tau Ceti Classic (RU))
Testmerges: ```#9784 #9988 #10071 #10127 #10102 ```
Reporting client version: 514.1588

**Comment by Mercurialaste** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/10102
