### ISSUE TITLE
Шторку отделяющую полкана и рекса от экипажа можно сломать

### ISSUE THREAD

**Issue by splifin2** [TauCetiStation/TauCetiClassic#10172]
#### Что должно было произойти
Экипаж не может сломать шторку, полкан и рекс не кромсают экипаж
#### Что произошло на самом деле
Экипаж ломает шторку, полкан и рекс кромсают экипаж
#### Как повторить
Попытаться сломать шторку
#### Дополнительная информация:
#54736

**Comment by kalazus** [comment]
Фича конца раунда

**Comment by volas** [comment]
всё хорошо, если собаки по желанию, кто захотел - залез. У людей горит, если их выпускают, и несколько раз уже фиксили разные абузы. Они слишком грифозны.

**Comment by UsadoSmokk** [comment]
Зачем добавили разрушаемость, если эту разрушаемость везде вырезают, кринж
