### ISSUE TITLE
Мит спайки с которых можно грифонить людей

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1017]
#### Подробное описание проблемы
Весящие люди на мит спайках могут бить кулаком, дизармить, стрелять, потому что по механу они сидят на стуле.
#### Что должно было произойти
Они должны висеть там без возможности взаимодействия с миром(кроме резиста)
#### Что произошло на самом деле
Они берут лазур который валяется рядом и стреляют тебе лицо, либо забивают тебя кулаками до смерти.
#### Как повторить
Повешать человка на крюки и дать ему оружие

**Comment by Skyrull** [comment]
Не баг а фича

**Comment by DeadOberst** [comment]
Есть же наручники.

**Comment by Dennok** [comment]
Жаль чела на митспиках нельзя оперировать.
