### ISSUE TITLE
[Proposal] Уменьшить время каста ритуала Клоуноконверсия

### ISSUE THREAD

**Issue by Slegarrr** [TauCetiStation/TauCetiClassic#10179]
#### Подробное описание проблемы
Время каста - почти 2 минуты.
![image](https://user-images.githubusercontent.com/106635472/193431569-672fdb9f-ecee-45f3-9659-fef73b70daed.png)
Это по сути РП замена Божественного Приглашения у которого каст всего 40 секунд и при этом, для которого не нужно даже брать никаких аспектов.
![image](https://user-images.githubusercontent.com/106635472/193431580-01d28555-fa18-493c-ada7-ec1bb5b1ba17.png)
Более того, у реально полезного Возвышения время каста - 50 секунд и там нужен всего 1 аспект.
![image](https://user-images.githubusercontent.com/106635472/193431588-c9f61f4c-a514-4bcf-9cd7-3a9c4477d2d3.png)
Игроку приходится жертвовать двумя аспектами ради "РП" ритуала и при этом, тратить уйму времени у алтаря. К примеру, чтобы пригласить 5 человек нужно потратить почти 10 минут времени. Предлагаю уменьшить время каста до 40 секунд, как у Божественного Приглашения, так как игрок уже заплатил аспектами за отличие от бесплатного Приглашения.

**Comment by Sakuya-Izayoi** [comment]
не надо делать пропосал суть которого просто изменить одно число в коде. можешь прямо в веб-редакторе это сделать.

**Comment by Slegarrr** [comment]
Ну меня в ишью отправили, с меня взятки гладки. Как это можно сделать, куда залазить?

**Comment by Sakuya-Izayoi** [comment]
#rnd канал в дискорде
