### ISSUE TITLE
Баг с абузом мехов против турелей 

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#10198]
#### Подробное описание проблемы

Есть проблема что начиная от КеК Экипажа до Нюки у которых есть мехи, часто любят абузить, по итогу что происходит, что с аплоудом, что со спутником, меховоды или бурят стенку или выламывают шлюз и меняют спокойно законы или выносят ИИ на спутнике полностью безнаказанно.

#### Что должно было произойти

Турели делают пиу пиу и ломают мехов 

#### Что произошло на самом деле

Не делают пиу пиу и ломают в итоге беззащитного ИИ

#### Как повторить

Вломиться в мехе на спутник или в аплоуд.

#### Дополнительная информация:
-

**Comment by Deahaka** [comment]
Когда был старый спутник, в моего меха стреляли турельки. С чего бы этому поменяться?

**Comment by Chip11-n** [comment]
Подтверждаю баг. В меня в мехе турели не палили

**Comment by pro100kotah** [comment]
Да у меня только что раунд был. Синдикат. Для чего-то первым делом штурмует спутник. Я им так сильно не понравился... В итоге просто в одном мехе выбивает укрепленные стены и проходят в ядро. Турели по мехам не стреляют. Мех спокойно ломает ядро. :roflanpominki:

**Comment by Bullethole** [comment]
Кнопочки нажимает на дамаг мехов или уже вообще отупели? два года назад спутник вообе через телесало водородными бомбами бомбили, никто не ныл, а тут блин, видите ли, мехам не дамагают

**Comment by KIBORG04** [comment]
ЕСЛИ БАГ РЕАЛЬНО ВАС БЕСИТ, ТО САМИ СТАВЬТЕ ПОД НЕГО ЛАЙКИ(ПАЛЕЦ ВВЕРХ) И ПРОСИТЕ СВОИХ ДРУЗЕЙ ЭТО С ДЕЛАТЬ. 

ТАКИЕ ИШУИ ПОПАДАЮТ В ТОП ИШУЕВ И ПОКАЗЫВАЮТ САМОЕ КАПЕЦКИЕ БАГИ

**Comment by pro100kotah** [comment]
> Кнопочки нажимает на дамаг мехов или уже вообще отупели? два года назад спутник вообе через телесало водородными бомбами бомбили, никто не ныл, а тут блин, видите ли, мехам не дамагают

Кого-то порвало. Вот и играй в свою прошлую сосаку двухлетней давности. По тебе и видно, что ты не заходил более в нее. В настройках турелей нет больше такой функции. Они буквально никак не будут стрелять по мехам, как бы ты не тужился с красной рожей.

**Comment by ssbugman** [comment]
Так выходит борг или дрон тоже может безнаказанно вынести ИИ раз настройку зачем-то убрали?

**Comment by AzzyDreemurr13** [comment]
> Так выходит борг или дрон тоже может безнаказанно вынести ИИ раз настройку зачем-то убрали?

Прикол в том что есть отдельный пункт огонь по синтетическим единицам который можно включить только на территории спутника.

И оно ебет как борготу так и Дронов, а мехов ни какой из доступных пунктов турели не ебут

**Comment by kiVts** [comment]
🥳
