### ISSUE TITLE
из 3 граба нельзя выбраться

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#10206]
#### Подробное описание проблемы
человек в 3 грабе становится stunned и это проходит только после того, как жертву отпустят, из-за чего тот никак не может самостоятельно выбраться из захвата
#### Что должно было произойти
нажимая на резист можно вырваться из захвата 
#### Что произошло на самом деле
не можно
#### Как повторить
позволить себя взять в 3 граб и попытаться вырваться из рук того, кто вас схватил
#### Дополнительная информация:
это появилось совсем недавно

**Comment by Vysserath1** [comment]
По-хорошему скорость выбирания из граба должна быть привязана к комбат скиллу. Толстому ГП явно труднее будет, чем СБшнику с черным поясом по дзюдо

**Comment by RONSI7** [comment]
Лучше будет, если скорость вырывания из захвата будет зависеть от уровня мускулатуры куклы. Чем сильнее твоя кукла, тем быстрее она вырвется из захвата и наоборот, чем ты сильнее своей жертвы, тем дольше ты будешь держать ее в захвате.

**Comment by pro100kotah** [comment]
Раньше с каким-то шансом можно было пушнуть чувака, что держит тебя в грабе. Чем дольше он тебя держал, тем скорее всего бы ты выбрался пушем. Теперь граб это 100% стан.

**Comment by BlankCringe** [comment]
А серьёзно? в грабе больше нельзя пушить? кринжанул...

**Comment by Deahaka** [comment]
Это реальность... Из 3-го граба нельзя выпушить чела.

**Comment by pro100kotah** [comment]
Кринж...

**Comment by Motzord** [comment]
Более того в третьем грабе накладывается пермостан, нельзя даже швырнуть флешку под ноги или попытаться прирезать террориста.

**Comment by Fenriros** [comment]
А я думал это я анробаст, оказывается баг

**Comment by Deahaka** [comment]
В етолксе випо начал рассказывать про свои отличные истории с захватом заложника и я подумал, что отсутствие пермастана в третьем грабе как раз делает практически возможным механореализацию такой ситуации на первом сервере.
Тогда может оставить как есть и не фиксить? Какие у кого мысли?

**Comment by Chip11-n** [comment]
В таком случае, может дать возможность резистаться хотя бы при движении? А если стоит, то кидать прогрессбар условно на 30 секунд? В любом случае, ты можешь заломать заложника, что бы он не резистался, а сейчас этот механизм бесполезен

**Comment by Deahaka** [comment]
Как ты его заломаешь в стоячем положении?

**Comment by Mercurialaste** [comment]
> Как ты его заломаешь в стоячем положении?

Прижимать к земле, третий граб интент пуш и на куклу.

**Comment by Deahaka** [comment]
Я сказал. В стоячем. Положении.

**Comment by Mercurialaste** [comment]
> Как ты его заломаешь в стоячем положении?

Можешь ещё раз пояснить суть вопроса?

**Comment by Chip11-n** [comment]
Там есть особые взаимодействия с куклой у тебя в заломе. Как закрыть рот, только заставить человека блевать, проверить кость, и вот, заломать, нанеся голоурон.

**Comment by Deahaka** [comment]
Нужно чтобы между преступником и копами было что-то, куда вторые стрелять не станут. И как думаешь если заложник окажется на полу, то что мешает копу шмальнуть электрод

**Comment by Mercurialaste** [comment]
> Нужно чтобы между преступником и копами было что-то, куда вторые стрелять не станут. И как думаешь если заложник окажется на полу, то что мешает копу шмальнуть электрод

И что будет? Сейчас чтобы вырвать кого-то из граба, достаточно просто на куклу в грабе нажать пулл и оттащить от того кто держит. 
И да, прижимание к земле не перемещает куклу на землю, насколько я помню, просто кидает болеурон.

**Comment by Deahaka** [comment]
То есть норм если преступник убьёт заложника. Ок.
