### ISSUE TITLE
Многозадачность сломалась

### ISSUE THREAD

**Issue by arygal** [TauCetiStation/TauCetiClassic#10228]
#### Подробное описание проблемы
Квирк многозадачность не работает
#### Что должно было произойти
Работаю двумя руками
#### Что произошло на самом деле
Работаю 1 рукой и как работа 1 рукой завершается - работа в 2 руке прерывается.
#### Как повторить
Зайти в игру и выполнить действия обоими руками (Например закручивать машинерию)
#### Дополнительная информация:
Также это поломало очередь действий для персонажей без скиллов. Например: за учёного набрать железа в бикер. После выполнения первого действия - все запланированные действия отменяться

**Comment by Deahaka** [comment]
Кто займётся - уберите у fumbling накладывание busy. Это не нужно никому.

**Comment by arygal** [comment]
Кто то починил вроде работает
