### ISSUE TITLE
[Предложение] Авто-клонирование людей.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1022]
Добавить машине для клонирования  способность клонировать автоматически, мертвых сканированых людей без помощи персонала (только при Т4 деталях.)

Вот ПР с ТГ: https://github.com/tgstation/tgstation/pull/2131

**Comment by Raschert0** [comment]
Но ведь есть такое. Только, скорее всего, оно сломано. Но оно есть. Там даже кнопка автопроцесса в интерфейсе есть

**Comment by P-20** [comment]
>Но ведь есть такое. Только, скорее всего, оно сломано. Но оно есть. Там даже кнопка автопроцесса в интерфейсе есть
Сейчас есть автосканирование без помощи персонала, а речь идет о автоклонировании.

**Comment by Raschert0** [comment]
Нет, оно должно автоклонить, но, видимо, это сломано
