### ISSUE TITLE
Глухота

### ISSUE THREAD

**Issue by arygal** [TauCetiStation/TauCetiClassic#10229]
#### Подробное описание проблемы
Если попасть под большое количество флешек \ х.о.н.к.-ов - можно оглохнуть на весь раунд.
#### Что должно было произойти
Когда ты уже глухой - ты не можешь оглохнуть сильнее.
#### Что произошло на самом деле
Глухой на весь раунд.
#### Как повторить
Попасть под несколько гудков Х.О.Н.К-а \ или под кластерную гранату с флешками.
#### Дополнительная информация:
От кластеров флешек:

```
if(M.ear_damage >= 15)
		to_chat(M, "<span class='warning'>Your ears start to ring badly!</span>")
		if(!banglet && !(istype(src , /obj/item/weapon/grenade/clusterbuster)))
			if(prob(M.ear_damage - 5))
				to_chat(M, "<span class='warning'>You can't hear anything!</span>")
				M.sdisabilities |= DEAF
```
От хонкербласта:
`M.ear_deaf += 30`

**Comment by flying-george** [comment]
О, это так то копия, но ты конкретную причину указал, мне впадлу было. Т.е. надо просто починить Ауризин, хоть он и сейчас работает

**Comment by arygal** [comment]
> 

Ауризин не починит после кластеров там глухота из трейтов вешается. И вообще если судить по коду и по ощущениям то он нормально работает.
