### ISSUE TITLE
Инженерный юнит не может работать с пласталью.

### ISSUE THREAD

**Issue by ZER0-In** [TauCetiStation/TauCetiClassic#10235]
#### Подробное описание проблемы
Нельзя чинить укрепленные стены. Ставь обычные. Вот бы еще можно было загружать автолат материалами, чтобы можно было печатать Airlock и air arlarm платы, лампочки, плату для АПЦ... 
#### Что должно было произойти
Можно чинить укрепленные стены. Можно загружать автолат.
#### Что произошло на самом деле
Ничего.
#### Как повторить
Попытаться взять в гриппер пласталь, стекло, металл.

**Comment by Deahaka** [comment]
Смешной конечно ишуй.
Борги имеют бесконечные материалы из воздуха - а давайте их можно будет пихать в автолат. При том, что вообще и сейчас вполне себе можно, ставя стёкла, ломая и ложа осколки в автолат, либо крафтя столы и разбирая их гаечным ключом. Только вот чтобы абузить надо хуман рядом.
А починка укреп стен подозрительно связана с их постройкой, а это = застройка спутника укрепками или другие очень неприятные вещи (и обычная стена пока является одной из этих неприятностей, но на неё хотя бы не нужен арсенал инструментов, а достаточно одной сварки).

Вобщем, хз что тут сказать. Нежелание делать дерьмо на боргах, возможно, не привело бы к текущим нерфам, но видимо синто-лобби создано, чтобы себя разрушить.

**Comment by Venngedi** [comment]
#12209
