### ISSUE TITLE
Научный юнит не может подбирать artificial bluespace crystal для телесайнса.

### ISSUE THREAD

**Issue by ZER0-In** [TauCetiStation/TauCetiClassic#10234]
#### Подробное описание проблемы
Не может подбирать кристалл для консоли телесайнса.
#### Что должно было произойти
Может, загружает в консоль.
#### Что произошло на самом деле
Не может, не загружает в консоль.
#### Как повторить
Взять кристалл за научного юнита.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/57403011/196005533-95a7897c-500d-4239-a1bc-6ae1933498a4.png)

**Comment by Follint** [comment]
А еще научный юнит не может взаимодействовать с обычными баками газа, хотя баллоны в них может загрузить.

**Comment by AzzyDreemurr13** [comment]
> А еще научный юнит не может взаимодействовать с обычными баками газа, хотя баллоны в них может загрузить.

Ну тоже самое на инже борге, в соло на борге ты сингу без помощи не запустишь
