### ISSUE TITLE
Пропало QoL для хранилищ предметов

### ISSUE THREAD

**Issue by INwirstD** [TauCetiStation/TauCetiClassic#10244]
#### Подробное описание проблемы
Раньше, при перетягивании свободной рукой, любого хранилища предметов(рюкзак, ящик, коробка и тд.) на тайл опустошал его, с некоторой задержкой и прогрессбаром, вываливая все предметы из сумки на тайл. Сейчас это перестало работать
#### Что должно было произойти
При перетягивании, например, сумки на тайл достаются все предметы с сумки на пол.
#### Что произошло на самом деле
Ничего не произошло

**Comment by Mercurialaste** [comment]
Переключи интент на хелп

**Comment by INwirstD** [comment]
Неа. Вообще не работает ни на каком.

**Comment by Sakuya-Izayoi** [comment]
Нужно больше информации. У меня на сендбоксе работает.

**Comment by INwirstD** [comment]
Странно вообщем, в предыдущем раунде не работало, теперь работает. Закрываю тогда
