### ISSUE TITLE
Возвышенный культа не понимает обычную речь. 

### ISSUE THREAD

**Issue by SkLepP** [TauCetiStation/TauCetiClassic#10247]
#### Подробное описание проблемы
Возвышенный культа не понимает обычную речь. В том числе обычную речь культистов
#### Что должно было произойти
Возвышенный культа понимает обычную речь. В том числе обычную речь культистов
#### Что произошло на самом деле
Возвышенный культа не понимает обычную речь. В том числе обычную речь культистов
#### Как повторить
Зайти за возвышенного культа и посмотреть, как кто-то говорит

**Comment by Deahaka** [comment]
универсал_спикер может ему достаточно поставить?

**Comment by KIBORG04** [comment]
Вроде да
