### ISSUE TITLE
Eminence не взаимодействует с объектами культа

### ISSUE THREAD

**Issue by kalazus** [TauCetiStation/TauCetiClassic#10250]
#### Подробное описание проблемы
Взаимодействия eminence с кузницей/алтарем/столом исследований ничего не делают.

#### Что должно было произойти
Взаимодействует как культист

#### Что произошло на самом деле
Котики

#### Как повторить
Зайти за eminence

**Comment by Deahaka** [comment]
null.holy_role() написал Энерти.
Это госто-еминем. Нет маенда писало в плеер панельке. Собственно и роли нет и книгой пользоваться не даёт.

**Comment by Deahaka** [comment]
Runtime meows, "Зафиксирована аномалия #242 при клике по "использовать том"

**Comment by Chip11-n** [comment]
Ты же был ГОСТом и стал возвышенным, да?

**Comment by kalazus** [comment]
Если правильно понял, на культистве в эминенса просто не работает, а на призраке в эминенса выдаёт котов.

**Comment by Deahaka** [comment]
Работало, когда я становился еминемом из куклы точно. Но это было вчера или позавчера. Сегодня может что-то особенное.

**Comment by Deahaka** [comment]
#34 строка для кузни рантайм
#53 строка для стола исследований
алтарь не пускал рантаймы, столы пыток тоже.

> Ты же был гостом и стал возвышенным, да?

Да
