### ISSUE TITLE
неправильное описание возвышенного культа

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#10251]
#### Подробное описание проблемы
в описании-экзмайне написано что он типа главный в культе РАТВАРА
#### Что должно было произойти
он главный в культе крови или нар си
#### Что произошло на самом деле
он главный в культе ратвара некого
#### Как повторить
проэкзмайнить еминенса

**Comment by KIBORG04** [comment]
Это расширение лора вы не понимаете
