### ISSUE TITLE
Хамелеон скин генок для гигачадов. Юзлесс штука.

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#10254]
#### Подробное описание проблемы
Потрать 2 очка на инвиз генки, чтобы этот инвиз не работал.
#### Что должно было произойти
Генка в инвизе, ее не видно
#### Что произошло на самом деле
Генку видно
#### Как повторить
Посмотреть на генку в инвизе в медхудах, худах сб, миксед худах.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/57403011/197248024-adf972b8-4b99-4a8c-8005-295f643a43ea.png)

**Comment by Deahaka** [comment]
Кто возьмётся, нужно убрать тоже самое для абдукторов

**Comment by kalazus** [comment]
"невидимость" абдуктора это багоюз, который просто не чинят очень долго

**Comment by simb11** [comment]
невидимость абдукторов давно пофиксили

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-golosovanie-apdejt-genokradov/36786/42

**Comment by arygal** [comment]
Потыкал на локалочке - бага не обнаружил.  Генка видит худы на себе когда она в инвизе, но сторонние наблюдатели, даже с админским комбохудом не видят её.

**Comment by Slegarrr** [comment]
> Потыкал на локалочке - бага не обнаружил. Генка видит худы на себе когда она в инвизе, но сторонние наблюдатели, даже с админским комбохудом не видят её.

А почему я его обнаружил?
![image](https://user-images.githubusercontent.com/106635472/222694110-f0583157-2d0c-4316-a543-9b87c2de4e68.png)

**Comment by arygal** [comment]
Вообщем это какя-то рассистская хрень - унатхи и таяране не видят, люди и скреллы видят. Пойду искать причину или решение.

**Comment by Slegarrr** [comment]
> Вообщем это какя-то рассистская хрень - унатхи и таяране не видят, люди и скреллы видят. Пойду искать причину или решение.

Воксы и дионы тоже видят.
