### ISSUE TITLE
БД библиотеки поехала

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#10259]
#### Подробное описание проблемы
1. Номера книг идут не в порядке возрастания
2. Диапазон перечисленных номеров на странице поиска книг ( от 110 - до 121, например) похерился. Типичный пример: ОТ 2201 - ДО 489
#### Что должно было произойти
1. Номера книг от самого меньшего к самому большему, требуется упорядоченность
2. С нумерацией, по идее, и диапазон сам пофиксится
#### Что произошло на самом деле
Нехорошее
#### Как повторить
Залезть в 4 опцию в компьютере библиотекаря и поскроллить сколько-нибудь.
#### Дополнительная информация:
шпасите библиотеку пока она не отмерла

**Comment by KIBORG04** [comment]
А еще все ID в блокнотах тау-крекеров с ссылками на ЕРП-книги похерятся

**Comment by pro100kotah** [comment]
Оно и к лучшему. Как минимум только ради этого стоит браться за это дело.

**Comment by volas** [comment]
оно так и должно работать
