### ISSUE TITLE
У улучшенных инструментов меняется размер при смене режима

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#10266]
#### Подробное описание проблемы
У дрели и клешней меняется размер при переключении режимов
#### Что должно было произойти
размер не меняется
#### Что произошло на самом деле
размер меняется

**Comment by Deahaka** [comment]
Надо переписать их как хирургические инструменты. Типо компоненты "используется как отвёртка" и наложить на нужные вещи. Сейчас это работает тупо как удаление текущей вещи и спавна в руке новой другого типа

**Comment by Deahaka** [comment]
Починено через квалити чеки?
