### ISSUE TITLE
Из нестов алиенов невозможно выбраться

### ISSUE THREAD

**Issue by IlinMihail** [TauCetiStation/TauCetiClassic#10288]
#### Подробное описание проблемы
Из нестов алиенов нельзя выбраться, при нажатии на резист появляется прогресс бар на одну десятую секунды, после чего исчезает

#### Что должно было произойти
Можно выйти из неста если есть время

#### Что произошло на самом деле
Нельзя

#### Как повторить
Поиграть в игру

**Comment by BlankCringe** [comment]
так был бы кринж если бы можно было выходить, как людей тогда в гнезде держать, разбивать череп? если тебя поймали то жди помощи или умирай и плоди ксеносов
