### ISSUE TITLE
[Proposal] Херовое автозаполнение нюки

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#10291]
#### Подробное описание проблемы
В нюку не при фул онлайне СБ порезано в колличестве, потому что их как будто специально набрало в нюку. Если на сервере ~50 человек и в ПДА <4 СБшника, значит щас нюка и она не встретит никакого сопротивления там, откуда оно должно идти.
Зато в реву у нас 12 СБшников когда никого убивать не надо.
#### Что должно было произойти
Нюкеров не может быть больше чем СБшников на станции 
ИЛИ преф на СБ автоматически вычёркивает из кандидатов на нюку 
ИЛИ сбшники набираются в нюку самые последние, если все остальные не хотят в нюку/забанены.
#### Что произошло на самом деле
Весёлая нарезка экипажа. Нюка на 3 офицера. Нюка на 1-го офицера. Нюка на 0 офицеров. И их не остановить благодаря бафу на пушки, броники, аптеки, скиллам и имуннитету к почти всему что есть у экипажа (последнее по-умному фиксится в #9942).
#### Как повторить
Зайти на сервер.

**Comment by KIBORG04** [comment]
скилл ишуй

**Comment by Deahaka** [comment]
Блин дубликат https://github.com/TauCetiStation/TauCetiClassic/issues/2184
