### ISSUE TITLE
[Proposal] Сделать шлюзы шаттла неразрушаемыми

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#10297]
#### Подробное описание проблемы
Уже не раз вижу как какие-то не очень умные игроки за минуту до конца раунда решают пострелять в шлюз чтобы сделать дырку. Не понимаю прикола, предлагаю сделать их неразрушаемыми для всего, кроме там сингулярности или взрыва.

**Comment by Rumpiturs** [comment]
Будут делать дырку в шатле.

**Comment by Deahaka** [comment]
в шаттле нельзя сделать дырку

**Comment by kalazus** [comment]
В шатле есть почти обычное стекло, которое не так и сложно сломать.

**Comment by Deahaka** [comment]
Стекло которое никто не ломает кроме карпов и нюки ок? Пусть останется

**Comment by kalazus** [comment]
Я про то, что это равноценные действия. Если решают сломать дверь, то пусть получают от админов.

**Comment by Deahaka** [comment]
Админы не справляются. Что делать будем?

**Comment by Deahaka** [comment]
Вроде перестали так делать
