### ISSUE TITLE
[Proposal] С помощью педалей можно получить бесконечный хайперзин

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#10299]
#### Подробное описание проблемы
Спустя одну минуту дроча левой кнопки мыши мы получаем возможность бегать в почти всех ригах без замедления.
#### Что должно было произойти
Это или сложнее, или дольше, или бафф от качалки не такой большой
#### Что произошло на самом деле
Одну минутку покликал по педалям и получил возможность бегать без замедления ригов

**Comment by DarthSidiousPalpatine** [comment]
Там бафф всего-ничего. И не минуту надо тыкать.

**Comment by simb11** [comment]
Да какой всего ничего, после велотренажера можно бегать в сбшном риге без замедления. И ладно, обманул, две или три минуты надо кликать

**Comment by Deahaka** [comment]
Норм баф, хайперзин ничё не решает а игроку польза.
