### ISSUE TITLE
ПОНЧИК АЛЕРТ.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1030]
#### Подробное описание проблемы
У ЕРТ в коробке для пончиков НЕТ ПОНЧИКОВ!!1!
#### Что должно было произойти
Все пончики должны быть на месте.
#### Что произошло на самом деле
Вместо пончиков там пустота. А на спрайте коробки с пончиками они есть!
#### Как повторить
Посмотреть в коробку с пончиками у ЕРТ.
#### Дополнительная информация:
http://imgur.com/a/n9iqk

**Comment by dearprincesscelestia** [comment]
Добавить туда записку "Спасибо, вкусные пончики. С любовью, синдикоты" вместо пончиков.

**Comment by StrikS** [comment]
Съели!

P.S. Специально проверил, действительно нет пончиков!

**Comment by Dennok** [comment]
Это все голодные кодеры.
