### ISSUE TITLE
Нереальные лаги с открытой вкладкой статуса или хардсьюта

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#10300]
#### Подробное описание проблемы
Вкладка статус, если используется баллон, и хардсьют заставляют игру нереальн лагать из-за постоянных обновлений.
#### Что должно было произойти
всё ок
#### Что произошло на самом деле
нереальные лаги с этими вкладками
#### Как повторить
Открыть вкладку хардсьют или статус имея подключенный к маске баллон и побегать

**Comment by simb11** [comment]
ошибся, из-за вкладки с МОДУЛЯМИ хардсьюта лаги

**Comment by KIBORG04** [comment]
Бьонд ишуй с статус панелью и очень частным обновлением информации в ней

**Comment by KIBORG04** [comment]
Мы 515, видимо закрываю
