### ISSUE TITLE
Не виден таймер до прибытия шаттла эвакуации/трансфера.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1031]
#### Подробное описание проблемы
Из-за кастомных надписей/Ред Алерта/Биохазарда не видно таймер до прибытия шаттла на дисплее(если шаттл летит)
#### Что должно было произойти
Хотя бы на половине (или хоть в отбытии) дисплеях должно отображатся время до прибытия шаттла.
#### Что произошло на самом деле
![451](https://cloud.githubusercontent.com/assets/18488106/22128275/71dcf998-dea8-11e6-8c12-79036b3c7e25.png)

#### Как повторить
Вызвать шаттл и включить на дисплеях  Ред Алерт/Биохазард/Кастомны слова

**Comment by StrikS** [comment]
Ну хоть кто-то этот ишью написал

**Comment by Dennok** [comment]
Ващет у глав на пда можно именять режим мониторов, и там есть режим таймера.

**Comment by StrikS** [comment]
И он не работает при тревоге почему-то, а точнее вообще.

**Comment by RichardJones1** [comment]
Нужно проверить, могут ли главы менять его во время тревоги

**Comment by hitsedesen** [comment]
Не воспроизводится. Дисплеи отображают то что выбрано в `Set Status Display`, в том числе время до прибытия шаттла при красном коде.

**Comment by Motzord** [comment]
Не является багом, так как отображение ETA врубается через ПДА (как и прочие бесполезные значки)
