### ISSUE TITLE
[Proposal] Добавим самодельный алкоголь

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#10321]
#### Идея
На раздумывания об этом меня подтолкнула и такая мысль, что обычным гражданским профессиям не хватает ещё чего-нибудь затейливого в плане возможностей.
Кто же должен варить шмурдяк?
![image](https://user-images.githubusercontent.com/96499407/199786036-0e7b0c64-7882-4a64-8372-ab0a30169c73.png)

Тут методом исключения получается: бармен не занимается варкой алкоголя, он его только продаёт клиенту. Повар уже имеет кучу инструментов для готовки, ему нужен реворк машинерии, чтобы она жрать давала, если ты случайно влил 5 водички в тесто, а не выдавала угли. А ботаник получается свободен.
Зачастую гидропоник, решивший разнообразить себе социалочку уходит в амброзию или клоунские бананы, изредка пытаясь достать тот самый блюспейс томат. Варка пива или кваса не звучит плохо в этом плане (а что говорить о самогоне или медовухе!).

#### Особенности
В процессе обдумывания концепта было изучено не менее десятка статей в интернете и были опрошены опытные самогоноварители, было найдено несколько прадедских вещей в билде на эту тему, был осмотрен ТГ-билд на эту тему.
Было допущено несколько неточностей, например: 
1. Вся фруктоза и сахароза была упрощена до нового реагента (условно синтетического сахара теперь).
2. Все дрожжи и другие источники спирта были упрощены до универсального ензюма (фермента).
3. Пряности и добавки, по типу изюма, солода или кислот нет.
4. Особенности приготовления не реализованы: игривое вино, сладкая ненастоянная текила без спирта, фильтрация, время готовки, влияние температур, запахов и скисание.
### Содержание собственно пропосола:
Основной контент вдохновлён ПРом на Эрисе: https://github.com/discordia-space/CEV-Eris/pull/3589
Собственно, добавляются компоненты из Вальгаллы из которых можно будет тоже варить напитки, а главное варить самогонку.
![image](https://user-images.githubusercontent.com/96499407/199791903-c4907577-757c-4b9c-b451-5c51e51f2c37.png)
Помните такие? Выглядеть они скорее всего будут не так, но название и особенности сохранят.

В ботанику добавляем 2 новые машинерии:
Бочка ферментирования (работает как кухонная машинерия), Самогонный аппарат (с контролем температуры, надо кодить)
Первую можно попробовать "портировать" с ТГ https://github.com/tgstation/tgstation/pull/38977, а второе уже надо подумать.

Бармену добавляем реагенты в его раздатчик алкоголя (открыто только в премиум режиме):
1. Адельхайд (сладкий)
2. Экстракт Бронсона (горький)
3. Паундеред Дельта (кислый, ядовит в больших кол-вах)
4. Фланерпайд (острый)
5. Кармотрин (синтетический этанол условно)

Добавляем новые рецепты для бочки:
Текила: 10 Адельхайд, 5 ензюмов, 10 Кармотрин
Вино: 5 Адельхайд, 20 виноградного сока (2 банки из автомата)
UPD: 5 Адельхайд, 5 ензюмов, 15 виноградного сока (половина банки из автомата)
Пиво: 5 Адельхайд, 5 ензюм, 5 Экстракт Бронсона, 10 воды
Квас: 5 Адельхайд, 5 ензюм, 5 Паундеред Дельта, 10 воды

Выход: 25 ед (в стакане, так должна работать кухонная машинерия). Настаивание в течении нескольких минут, чтобы был ценен. Неправильное приготовление: Брага с этанолом
Панелька выглядит как обычный кухонный аппарат. Есть кнопка Start и eject

Новые рецепты для самогонного аппарата:
Самогон (синтетический условно, в билде есть другой Moonshine): 5 Адельхайд, 5 ензюм, 5 Фланерпрайд, 10 воды
Острый вкус.
Чача: 5 Адельхайд, 5 ензюм, 5 вина, 10 воды
Горький, острый вкус, крепкая.

Выход 25 ед. Надо контролировать температуру в течении ~1 минуты, иначе выйдет Сивуха (Hooch). Контроль это нажимать плюсики и минусики на панельке, либо, если это возможно, крутить комфорку как на газовой плите, чтобы скорость набора температуры была не больше 1 градус/тик. При 85 - 90 градусах нужно нажать стоп. Вариант сделать ползунок "качество ферментизации", чтобы получить удачно нужно не дать упасть ниже 75% из-за скорости температуры. Другой показатель это температура в градусах "завершённость приготовления" в виде численного показателя. Панелька таймера для красоты с начала старта, Кнопка Старт, кнопка Стоп.

Опционально реализовать смеси алкоголя с другими реагентами, как например пиво со льдом:
Чача + газировка = головная боль
Чача + апельсиновый сок = слабее алкоголь
Чача + вино = крепче алкоголь

**Comment by Pivo24** [comment]
Реквестирую заменить рецепт пива на тот что из вальгаллы

Засчитаю как полноценную отсылку

**Comment by Vysserath1** [comment]
В химии есть рецепт самогона из спирта и топлива)))

**Comment by Deahaka** [comment]
Пара дней раздумий привела меня к выводу, что это никому не нужно будет.
Обычно, у нас ассоциируют всё домашнее с вкусным, родным, любимым, а синтетическое с говном, химозностью и отвращением.
Варка синтетического пива, синтетического самогона, синтетического вина не создат никаких аутентичных тем, которые есть сейчас, разговоров про то, что это натуральное, полезное или без добавок. Если и нужно делать, то только из нутриментов и сахара/мёда/патоки, никак не из синтетического усластителя.
Но сама идея мне пришла, когда я нашёл ПР на Эрисе и захотел коктейли оттуда, с теми же реагентами, как в оригинальной игре. На это я как-то натянул нужду ботанику получать эти реагенты и делать из них "настоящее" синтетическое бухло.
Можно было бы реализовать на обычный вариант варки из растений, но мне это не нужно, хочется впилить то, что не влезет.
