### ISSUE TITLE
Рантайм связанный с биржей, но скорее всего дело в проке NormalDistr(), который она использует.

### ISSUE THREAD

**Issue by ZVee** [TauCetiStation/TauCetiClassic#1033]
#### Подробное описание проблемы
```
runtime error: log(0) is not computable
proc name: NormalDistr (/proc/NormalDistr)
  source file: maths.dm,79
  usr: (src)
  src: null
  call stack:
NormalDistr(0, 1)
Specific & Specific (/datum/stock): fluctuate()
Specific & Specific (/datum/stock): process()
/datum/stockMarket (/datum/stockMarket): process(20)
Objects (/datum/subsystem/objects): fire(0)
Master (/datum/controller/master): process()
```
#### Как повторить
Попросить рандом сролить 0 (шутки шутками, но из лога явно видно, что ему не нравится 0).
#### Дополнительная информация:
Редкий - по крайней мере для меня, и по той простой причине, что за месяц многократных подъемов локального сервера, рантайм засветился всего один раз. Но в чем точно уверен, это никак не связано с теми тестами которые мною проводились.

Скорее всего дело даже не в бирже, а ошибка в самом проке `NormalDistr()`, меня смущает что там `rand()` от `0` и до `n`, поэтому и рантайм редкий.

Бежать сломя голову и выпилить 0 наверно не стоит, лучше взвесить и углубиться в это дело по возможности. Еще как вариант - сравнить с ТГ, возможно они другой прок используют, но это тоже убежать от проблемы, а может действительно прок неправильно когда-то написали.

**Comment by igigin** [comment]
@Raschert0 Беги чинить свои логарифмы.

```
runtime error: log(0) is not computable
proc name: NormalDistr (/proc/NormalDistr)
  source file: maths.dm,79
  usr: (src)
  src: null
  call stack:
NormalDistr(0, 1)
Wood (/datum/stock): fluctuate()
Wood (/datum/stock): process()
/datum/stockMarket (/datum/stockMarket): process(20)
Objects (/datum/subsystem/objects): fire(0)
Master (/datum/controller/master): process()
```
