### ISSUE TITLE
Очки диагностики показывают минимальный уровень хп меха

### ISSUE THREAD

**Issue by Fluffy-510** [TauCetiStation/TauCetiClassic#10346]
#### Подробное описание проблемы
После ремонта меха, хп которого упало достаточно сильно чтобы уменьшилась полоска хп над мехом, полоска не восстанавливается.
#### Что должно было произойти
Повредил мех, полоска уменьшилась, починил мех, полоска восстановилась
#### Что произошло на самом деле
Повредил мех, затыкиваешь сваркой его, полоска хп не восстанавливается, снова затыкиваешь, смотришь в чат: «Nothing to fix x18»
#### Как повторить
Выше

**Comment by Mercurialaste** [comment]
Попробуй поменять батарейку.

**Comment by Fluffy-510** [comment]
> Попробуй поменять батарейку.

Не помогает.
Поломал мех:
<img width="240" alt="2022-11-12_14-27-42" src="https://user-images.githubusercontent.com/109436132/201535542-04e78d9c-7c8e-4c5f-bf9b-ff3ba200b406.png">
Починил мех:
<img width="179" alt="2022-11-12_14-28-02" src="https://user-images.githubusercontent.com/109436132/201535556-fe898d38-c0b7-4e77-86f9-11d0fc4b362e.png">
Вытащил батарейку:
<img width="201" alt="2022-11-12_14-28-29" src="https://user-images.githubusercontent.com/109436132/201535577-76b52625-b899-4ef1-9286-37f35de42ba6.png">
Вставил батарейку:
<img width="159" alt="2022-11-12_14-28-56" src="https://user-images.githubusercontent.com/109436132/201535600-90f43fc1-884a-4831-a63b-62b34f47f339.png">

**Comment by KIBORG04** [comment]
Полоска хп не обновляется при починке, здесь достаточно одну функцию в нужное место тыкнуть и все
