### ISSUE TITLE
[Спрайтинг] Ведро имеет старый спрайт в руке и на голове.

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#1034]
#### Подробное описание проблемы
В руке и на голове спрайт нового ведра отображается старым спрайтом.
#### Что должно было произойти
Спрайт должен был быть дорисован во всех областях его применения.
#### Что произошло на самом деле
Ведро меняет вид и цвет.
#### Как повторить
Возьмите ведро в руку, лапу, наденьте на голову.
#### Дополнительная информация:
Это как [Предложение], хотелось бы, чтобы спрайт был чуть побольше в размерах тайла.

**Comment by WatlerJe** [comment]
Фикс уже как неделю/две отправлен кодерастам, ждем ПРа.

Делать спрайт еще больше не считаю целесообразным.

**Comment by Raschert0** [comment]
#980
