### ISSUE TITLE
можно проходить сквозь Containment Field

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#10356]
#### Подробное описание проблемы
можно спокойно перешагнуть через Containment Field
#### Что должно было произойти
бдыщ удар током при попытке перейти поле
#### Что произошло на самом деле
спокойно перешагнул сквозь поле

**Comment by pro100kotah** [comment]
Блинблять, а как повторить почему не сказал? :nedovolen:
