### ISSUE TITLE
Гильзы(и не только) нельзя поднять мусорным пакетом.

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#1035]
#### Подробное описание проблемы
Не все маленькие предметы можно засунуть в мешок нажатием мешка на предмет.
#### Что должно было произойти
Мелкие вещи должны были подняться мешком для мусора.
#### Что произошло на самом деле
При нажатии ничего не происходит.
#### Как повторить
Возьмите мусорный пакет и попробуйте поднять кучу гильз.

**Comment by P-20** [comment]
Гильзы можно ложить в мусорный пакет, у тебя он точно не переполнен был?

**Comment by Damirrus1** [comment]
Я же писал, что нельзя их подбирать, а вы мне чот втирали.

**Comment by DeadOberst** [comment]
Чтоб подобрать гильзы мусорным мешком нужно кликать на какой-нибудь другой предмет. Бумажку или прочий мусор.

**Comment by Dennok** [comment]
небось еще пол
