### ISSUE TITLE
[Proposal] Добавить симуляцию квантовой физики

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#10351]
#### Подробное описание проблемы
Почему нет симуляции всяких там квантов кварков фотонов, когда у нас все работает на блюспейсе? Почему так нереалистично

![image](https://user-images.githubusercontent.com/26389417/201418010-7f689320-23eb-48a5-8058-4af67249b820.png)

![image](https://user-images.githubusercontent.com/26389417/201418094-015695c8-af0f-43fb-8ba0-6eff073f0618.png)

А так же, весь объективный мир построен с учетом всех мировых физических констант, у нас же в сске в коде очень мало их используется, а не все.

https://ru.wikipedia.org/wiki/Фундаментальные_физические_постоянные

https://en.wikipedia.org/wiki/List_of_mathematical_constants

**Comment by Deahaka** [comment]
Тебе термоядерного синтеза мало?
