### ISSUE TITLE
Консоль голозначков не работает

### ISSUE THREAD

**Issue by Pimap3** [TauCetiStation/TauCetiClassic#10357]
#### Подробное описание проблемы
Консоль голозначков показывает обычные камеры
#### Что должно было произойти
Консоль голозначков показывает активные бейджики
#### Что произошло на самом деле
Консоль голозначков показывает........Общую сеть камер станции??
#### Как повторить
Откройте консоль голозначков

**Comment by simb11** [comment]
абсолютно все консоли показывают общую сеть камер

**Comment by KIBORG04** [comment]
Мб ревертнуть надо.

https://github.com/TauCetiStation/TauCetiClassic/pull/10231

**Comment by kalazus** [comment]
Скорее всего, там же нету проверки на то, всунутая ли там плата или базовая.

**Comment by pro100kotah** [comment]
> Мб ревертнуть надо.
> 
> #10231

Все еще актуально. Консоли пока не работают.
