### ISSUE TITLE
[Proposal] Удалить у эминема ТОМ.

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#10386]
#### Подробное описание проблемы
Имбалансная вещь, позволяющая спасать культистов из любой ситуации (нарисовать руну в карцере), строить стены перед лицом СБ, а так же ломать стены перед лицом сб.

**Comment by Deahaka** [comment]
Если это всё он не должен уметь, то у меня вопрос нахуй он вообще нужен. Либо выпиливать либо закрывать эту темку с пометкой "скилл ишшуй".
Строить он должен в захваченных зонах по той же причине, почему он и в раю это должен делать. Единственное что нужно поиграться с таймерами, чтобы он не срал стенами, которые трудно ломать. Только пилоны и двери допустим раз в 10 секунд, а стену раз в минуту (условные цифры)

**Comment by Ro2tCrab** [comment]
> #### Подробное описание проблемы
> 
> Имбалансная вещь, позволяющая спасать культистов из любой ситуации (нарисовать руну в карцере), строить стены перед лицом СБ, а так же ломать стены перед лицом сб.

Cтроить он уже разучился и рисование рун не так уж тяжело изучить.

**Comment by Ro2tCrab** [comment]
Главная сила культа - талисманы, строительство везде + улучшенный том и культ Тьмы.

**Comment by KIBORG04** [comment]
Он нужен не для тактики, а для стратегии. Не для робаста, а для плана

**Comment by Deahaka** [comment]
А можно конкретно, а не какими-то абстрактными понятиями?

**Comment by KIBORG04** [comment]
Если сложно сопоставить с игрой, то попробуй найти мой ишуй на добавление нарси

**Comment by Ro2tCrab** [comment]
> Он нужен не для тактики, а для стратегии. Не для робаста, а для плана
Робаст Возвышенного проходил через постройки, которые он более не может ставить вне своей зоны.
Руны же в карцере можно создать и с помощью запоминания рун и с робастом это никак не связанно

**Comment by KIBORG04** [comment]
Одно дело тратить время и ресурсы на запоминание, а другое с 0й секунды мочь их ставить где угодно

**Comment by Ro2tCrab** [comment]
> Одно дело тратить время и ресурсы на запоминание, а другое с 0й секунды мочь их ставить где угодно

Эти "ресурсы" можно добыть обычной проклятой водой и сделать за 10 минут. Это уже давно перешло в рамки Мета-Тактики культа. Сделай всё правильно и у тебя будет все исследования и ритуалы менее чем за 30 минут.

**Comment by KIBORG04** [comment]
Ну так, пусть делают. То кто не делает, не должен получить плюсы тех, кто делает.

**Comment by Deahaka** [comment]
С 0 секунды культисты в карцер не попадают. А к тому времени, когда попадают, легко представить изученное запоминание.
Если это имба то нерфите запоминание, а тогда уже эминенса.

Мне больше не нравится то, что возвышенный может наглеть и скидывать посреди офицеров руны, а раньше ещё и постройки. Было бы неплохо, чтобы в пределах видимости других людей нельзя было вообще ничего, что палит эминема и культ скидывать. На камерное наблюдение пофиг.

**Comment by Ro2tCrab** [comment]
Возвышенный обречён быть сломанным и абузным...
Или бесполезным.
