### ISSUE TITLE
Реальность не может выдержать обмен телами возвышенного и выкидывает игрока в лобби.

### ISSUE THREAD

**Issue by Ro2tCrab** [TauCetiStation/TauCetiClassic#10385]
#### Подробное описание проблемы
Возвышенный делает обмен телами с и улетает в лобби.
#### Что должно было произойти
Честно? Ничего.
#### Что произошло на самом деле
Игрок улетает в лобби.
#### Как повторить
Ритуал обмена телами.
#### Дополнительная информация:
-

**Comment by Ro2tCrab** [comment]
Там просто в лобби выкидывает игрока

**Comment by KIBORG04** [comment]
Любой моб для обмена? Оно раньше не крашило

**Comment by Ro2tCrab** [comment]
Тут конкретно возвышенный.

**Comment by Ro2tCrab** [comment]
Остальные мобы работают нормально

**Comment by KIBORG04** [comment]
Возвышенный на алтаре или проводит ритуал?

**Comment by Ro2tCrab** [comment]
Проводит ритуал сам.

**Comment by KIBORG04** [comment]
@Chip11-n Разберешься?

**Comment by Chip11-n** [comment]
Гляну
