### ISSUE TITLE
[Proposal] Соображения баланса портала культа после новых апдейтов

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#10390]
#### Подробное описание проблемы
# Ивентовый портал би лайк
![0000000000000000](https://user-images.githubusercontent.com/96499407/202571967-478aa0d3-5b4a-4b28-b06f-632c5660d6c1.png)
![0000000000000000000000000000000000](https://user-images.githubusercontent.com/96499407/202571984-5c5b7d26-5fd6-4cb4-ac37-9fe21bfeff0d.png)
![1a1a1a](https://user-images.githubusercontent.com/96499407/202572045-44b0d5dd-9d53-4df6-a93f-438dbcdb08c4.png)
![2ф2фф2ф](https://user-images.githubusercontent.com/96499407/202572131-b4d2f20f-2090-483f-b6c4-f991465ef04e.png)
Не осталось ни одного живого не ССД чела на карте, кроме святоши-тритора который решил закоопится с констрактами поделав ещё больше дыр.

Я не призываю бежать нерфить потому что имба, но после обновления пилонов спавн портала с 4-мя такими во первых выглядит внушительно, а во вторых без оперативного вмешательства СБ расширится до космоса обязательно и заразгермит там всё.

**Comment by KIBORG04** [comment]
Считай, что как блоб.

**Comment by LoTaRk-FroG** [comment]
> Может стоит тогда его в Major класс отнести? Почему у нас вообще полноценные антаги спавнятся где-то, кроме мажора?

Это не полноценный антаг, у них нет целей, ограниченная зона перемещения, нет всяких приколов культа по типу запоминания рун и т. д.
