### ISSUE TITLE
Сломалось замедление ригов

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#10407]
#### Подробное описание проблемы
Риг учёных и РД стал сильно замедлять, похоже замедление рига с батарейкой стало таким же, как и без батарейки. Насчет других ригов сказать не могу, заметил на ригах учёных, Риг был без магбутсов, если это важно.
#### Что должно было произойти
Риг не должен так сильно замедлять.
#### Что произошло на самом деле
Риг замедляет так, как будто он без батарейки.
#### Как повторить
Одеть риг учёных и походить.

**Comment by Mercurialaste** [comment]
Это со всеми ригами сейчас так.
Чтобы оно починилось, нужно тупо вставить и переключить магбутсы.

**Comment by F0xiq** [comment]
Я так и думал, только вот риги ученых единственные кажется, к которым магбутсы по какой-то причине не прилагаются.

**Comment by kalazus** [comment]
Не нашёл где #10307 сломал Риги, зато зашёл весёлую строчку
```dm
slowdown = boots.slowdown_off
```
А не, нашёл:
```dm
if(!offline)
	slowdown = offline_slowdown
```
И как мейнтейнеры такое пропустили...
