### ISSUE TITLE
Сломан UI монитор состояния экипажа. 

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#10404]
#### Подробное описание проблемы
Что не день, а что-нибудь да поломают. Теперь UI бесцветный.
#### Что должно было произойти
UI монитора в медбее работает нормально.
#### Что произошло на самом деле
Дальтонизм
#### Как повторить
Посмотреть в консоль в медбее или в ручной монитор.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/57403011/202924645-eea4f7ab-b41c-4352-ac3d-8de28bc9f869.png)

**Comment by KIBORG04** [comment]
Я незнаю почему оно сломано, мы ничего такого не мержили

**Comment by pro100kotah** [comment]
> Я незнаю почему оно сломано, мы ничего такого не мержили

После грузторга поломалось. Может что-то там?

**Comment by KIBORG04** [comment]
ок, после рестарта бага не должно быть
