### ISSUE TITLE
Борги не могут ломать баррикады, бить блоба.

### ISSUE THREAD

**Issue by qqqZXzz123** [TauCetiStation/TauCetiClassic#10400]
#### Подробное описание проблемы
После какого то обновления борги стали неспособны ударить блоба, деревянные баррикады, и возможно ещё что-то.
#### Что должно было произойти
Борг бьёт блоба и ломает баррикады.
#### Что произошло на самом деле
Немощный борг ничего сделать не может.
#### Как повторить
Попытаться сломать деревянную баррикаду или ударить блоба.

**Comment by Chip11-n** [comment]
Если не ошибаюсь, первые сообщения т проблеме появились после мержа аттак чейнов

**Comment by kalazus** [comment]
Надо просто бить на харме. Да, не так приятно у блогов менять интент, но не супер сложно.

**Comment by Mercurialaste** [comment]
> Надо просто бить на харме. Да, не так приятно у боргов менять интент, но не супер сложно.

Уверен? Из того что я проверял, борг просто не бьет.
Шлюзы, стекла и тд.

**Comment by Ro2tCrab** [comment]
> Надо просто бить на харме. Да, не так приятно у боргов менять интент, но не супер сложно.

Даже интент может не спасти.

Тот же синди-бот не мог сломать баррикаду Лазерным мечём.

**Comment by pro100kotah** [comment]
> Надо просто бить на харме. Да, не так приятно у боргов менять интент, но не супер сложно.

Раньше так было, до того как что-то поломали. Теперь же, уже больше месяца борги не могут ничего бить из предметов. Даже стекло не могут сломать. А это раздражает на инжеборге, когда тебе нужно что-нибудь перестроить. Еще речарджеры нельзя никак переносить.

**Comment by VasyaPupkin120** [comment]
дрон на харме сваркой не может ломать стекла
