### ISSUE TITLE
[Proposal] Раундстартовый ивент на сломанные шлюзы не должен ломать аирлоки в космос

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#10409]
#### Подробное описание проблемы
Сейчас раундстартовый ивент на сломанные шлюзы периодически ломает шлюзы в космос, из-за чего воздух выдувается вплоть до мостика, постоянно умирают люди из-за этого, выглядит слишком уж грифозно для раундстарта. Было бы хорошо, чтобы external airlock не ломались бы.
#### Что должно было произойти
Клоун забегает на мостик через сломанные шлюзы и хонкает на всю станцию,
#### Что произошло на самом деле
Пару человек, как минимум, помирают раундстартом от разгермы.

**Comment by KIBORG04** [comment]
Фича
