### ISSUE TITLE
[Proposal] Вернуть КД на point to

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#10402]
#### Подробное описание проблемы
Поинт ту плодит миллион сущностей в единицу времени. Мышь может заспамить поинт ту хумана и его выбесить, это капец вообще. Или может бегать 3 дебила и спамить людей этими кликами и это еще и чат засирает.

**Comment by Deahaka** [comment]
Дайте еминенсу поинт ту, который видит культист. Без этого капец как неудобно что-то показать челу

**Comment by KIBORG04** [comment]
сделай ишуй

**Comment by Deahaka** [comment]
А насчёт ишуя: сделай таблицу сколько производится поинт-ту, кто чаще всего этим занимается, насколько это загружает сервер.

**Comment by AndroBetel** [comment]
лучше запретить мышам и прочей неразумной живности делать поинт ту

**Comment by AndroBetel** [comment]
лучше запретить мышам и прочей неразумной живности делать поинт ту
