### ISSUE TITLE
Crew Manifest UI опять сломался.

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#10420]
#### Подробное описание проблемы
Сломалось отображение состояние экипажа
#### Что должно было произойти
Работает.
#### Что произошло на самом деле
Работает неправильно.
#### Как повторить
Зайти в игру.
#### Дополнительная информация:
Сломался опять. Теперь же после мержа русской озвучки на анонсы.
![image](https://user-images.githubusercontent.com/57403011/203852869-72774e34-6cad-453b-8c0d-9e40b55c4fd1.png)

**Comment by LudwigVonChesterfield** [comment]
#10076
