### ISSUE TITLE
[Предложение]Скафандр в каждый дом

### ISSUE THREAD

**Issue by Kurshan** [TauCetiStation/TauCetiClassic#1043]
Суть следующая: У нас сейчас стоит самопальный беевский атмос, да, он превосходен, позволяя ощутить на себе всю прелесть перепадов давления с последующей потерей сознания. К нему нет никаких претензий, он у нас сейчас такой, каким должен быть, ни меньше, ни больше. Претензия скорее к доминации антагонистов посредством тотальной разгерметизации станции, из-за чего Абсолютное(!) большинство персонала в лучшем случае останется в своём уютном отсеке до конца раунда, а в худшем просто умрёт от скуки/разгермы/кары тех самых антагонистов. На бее решили эту проблему просто поставив в каждый экстренный шкафчик (который по идее и так предназначается для тех самых разгерм, а иначе, зачем там аптечка от асфиксии?) по скафандру.

   Поэтому предлагаю сделать то же самое. Я уже предвкушаю, что мне на это ответят любители хардкора, что это оказуаливает игру, что это даст пространство всяким ПГшникам воевать, ведь только разгерма их может сдерживать. И всё так, только эти возгласы, я более чем уверен, буду слышать от хоть и хороших людей, но всё же не играющих (или играющих крайне редко) за обычный персонал (киборги, инженегры не в счёт). Я как никто знаю, как у нас это устроено, что большинство мейнтейнеров или же кодеров не играют, это полностью ваш выбор и я не смею упрекать вас в этом. Но давайте попробуем вспомним, что у нас все скафандры централизированы в ЕВА, И по мелочевке в инженерном отсеке, казалось бы. ВЕДЬ ТАК МНОГО РИГОВ, пускай достают, всё бы так, если бы не те самые набеги антагонистов на эти хранилища или созданные преграды в виде тех же разгерм, (тут ещё можно вспомнить, что не у каждого есть доступ к этим двум отсекам). В итоге, обычный ассистент Вася Пупкин по какой-то непонятной для него ситуации умирает, захватывающий геймплей не спорю, но это если вы наблюдаете за его смертью, ему почему-то не шибко понравилось, а потому что у него не было даже шанса оценить это происшествие и проникнуться им, ведь где-то там далеко рвануло, а он здесь, сидел себе в баре/качалочке, никого не трогав, раз и смерть. Teh END. У нас всегда политика была нацелена на то, что если космонавты и должны умирать, то зачастую по своей инициативе (ключево слово, зачастую), а это просто тот же молчаливый выпил, никак иначе это не назовёшь.

К слову, почему это на космической станции, не предусмотрена временное решение проблемы разгермы для персонала? Сколько бы вы не кричали о том, что НТ ПЛОХИЕ, никому не надо терять рабов, пускай и таких тупых.

Тем более, я уверяю вас, смерти от разгерм будут, и их будет не мало, я же не предлагаю на каждый квадратный тайтл расставить эти самые скафандры, что из них можно будет построить собственный дом. Нет, основная идея в децентрализации этих самых скафандров. Чтобы можно было добраться ЧУТОЧКУ БЛИЖЕ, нежели до ЕВА, если ты, например, в церкви. 

По поводу Пгшников и ролей. Набеги на ролей и так совершаются, станет ли их больше? Вероятно, да. Только вот знаете, если рольки не хотят уделить внимание обычному персоналу, то зачем они тогда вообще нужны? Рольки нужны для увеселения экипажа, а не его полного игнорирования ради гринтекста, пускай даже это веселье будет выражаться в нашинковывании тушек свинцом, это всяко интереснее, нежели просто помереть на месте от случайной разгермы. Благо, у антагонистов СРЕДСТВ БОЛЕЕ ЧЕМ ДОСТАТОЧНО для этого, так что обычный персонал в этих бичеригах не будет представлять серьёзную опасность. Если же антаги допустят получение экипажем оружия - их проблемы, ничьи больше. 

Ну и да, Ишью сделано чтобы оценить, сколько будет ЗА и ПРОТИВ. Мне не составит труда самому сделать ПР, здесь же я просто ожидаю лицензию на этот самый ПР.

**Comment by P-20** [comment]
Тогда нужно усилить меры наказаний, любителям побегать в ригах да и вообще сидеть в них.
Ибо при любом оповещении о биоугрозе космонавтики бегут за ригами в оправдание что "ета лучшая защита от бактерий", так же любят и просто ходить в ригах без особой причины особенно инженеры, когда станция в порядке, ну и офицеры, ибо риги неплохо защищают от различного вида оружия. Поэтому нужно ввести протокол, согласно которому лишь при определенных условиях можно было бы одевать скафандры, а такие ящики должны быть запечатаны, и открыты лишь в случае необходимости. Чтобы если офицеры видят кого-то в скафандре без веской причины, они могли приравнять это к нарушению закона и провести арест.

**Comment by igigin** [comment]
Я всегда был за обе крайности: либо добавить кучу картонных скафандров в каждый синий шкаф, либо выпилить все скафандры кроме инженегров и им тоже оставить лишь парочку.

К тому же, можно сделать картонным только защиту от низких давлений и при наступлении на тайл спесса, хуман рипнется.

**Comment by P-20** [comment]
Тогда нужно выпилить дополнительные инженерные скафандры из ЕВА, и вместо них картонные скафы для космонавтов. Инженерные скафандры и без того есть в инженерном отсеке в количистве 5 единици + риг СЕ

**Comment by Kurshan** [comment]
Бичериги - я подразумеваю тот самый риг со значением slowdown = 3. Для тех кто не в курсе, ЭТО ПРОСТО ДОХРЕНА. Показатели же защиты на них будут нулевыми. Так что космонавты сами не захотят бегать в них или особо рембовать, ибо от одного выстрела они порвутся и сами понимаете.

**Comment by igigin** [comment]
>Инженерные скафандры и без того есть в инженерном отсеке в количестве 5 единиц

Но ведь атмориги не инженерные. Да и потом, если у нас на каждом углу скафандр, то зачем экономить на инжирах?

**Comment by P-20** [comment]
Вот именно что не инженерные, но каждый инженер старается взять риг атмосника из ЕВА, ведь он "моднее"

**Comment by igigin** [comment]
Скафандры не виноваты в том, что их пытаются надеть всякие малогеи.

**Comment by Tankred0** [comment]
Идея здравая, я уже кстати давно предлагал распихать экстренные, вакуумно упакованные софтсьюты.
По принципу взял коробочку, дёрнул за ниточку, получил шлем и нательный скаф с нулевой защитой. Жутко не удобный, мешковатый и совсем не модный, но спасающий при разгерме.
У нас к слову для этого всё есть, не так давно Кукиз влил огромное количество именно софтсьютов на любой вкус и цвет, которые почти нигде не используются.

Хороший ход распихать их по отделам и коридорам, логичная мера от компании которая не любит терпеть убытки.

**Comment by igigin** [comment]
Я всё же считаю, что нужны именно прессур сьюты, чтобы в них по спессу не бегали.

**Comment by Tankred0** [comment]
Ну, просто кукизовы скафандры такие красивые....но они почти не используются...

**Comment by igigin** [comment]
Недавно кстати отвергли спрайт СК-1 от Вальтера, потому что он не для спесса и вообще дириликт.

**Comment by Raschert0** [comment]
Ну а чем отличается прессур сьюит от обычного скафандра? Точнее, чем он МОЖЕТ отличатся? Что такого особенного в тайле спесса, что он прям разрывает прессур сьюит, хотя рядом есть тайл плитки с таким же давлением и на нём всё окей?

**Comment by igigin** [comment]
Спроси у капитана и его брони.

**Comment by Raschert0** [comment]
А спрайт Вальтера не отвергли, просто мне лень его на дереликт замапить (ну и времени не было)

**Comment by igigin** [comment]
Но на дереликте его никто не увидит и даже госты редко.

**Comment by Raschert0** [comment]
Но ему там самое место

**Comment by igigin** [comment]
Как и тебе.

**Comment by Kurshan** [comment]
НТ закупила огромную партию дешёвых ригов у космо-русских, идеально же.

**Comment by dearprincesscelestia** [comment]
> Ну а чем отличается прессур сьюит от обычного скафандра? Точнее, чем он МОЖЕТ отличатся? Что такого особенного в тайле спесса, что он прям разрывает прессур сьюит, хотя рядом есть тайл плитки с таким же давлением и на нём всё окей?


Примерно вот этим:

http://www.space.com/images/i/000/000/414/original/LLM-why-are-space-suits-orange-100601-02.jpg

И да, максимальный слоудан и никакой защиты. Только от давления. Я давно за.

**Comment by Udokun** [comment]
Только сегодня разглядывал спрайты скафандров от людей и подумал в очередной раз, что в ЕВА очень мало скафандров для такой большой станции(как и шлюпок на Титанике). Хотел сделать предложение в ишью, а тут уже работает Куршан. В принципе идея отличная, по ОТ(Охране труда) СИЗ(Средства индивидуальной защиты) должны быть в каждом отсеке крупном отсеке. Запихивать их в каждый шкаф не надо, СИЗ в коридоре пускай по-прежнему остаются в ЕВА, но количество их там определённо надо увеличить. Из ЕВА желательно убрать все сторонние скафандры(охранные, атмосферные, медицинские). Вместо них расставить "капсулы" с гражданскими, а сторонние перенести в основные отделы(бриг, медбей, карго) в некий встроенный в стену шкаф возле огнетушителей. Чтобы не было проблем с беспричинным изъятием людьми скафандров, можно добавить в наш КАД(кнопка у глав в кабинетах) функцию разблокировки этих самых шкафов.

**Comment by dearprincesscelestia** [comment]
Но зачем гражданские скафандры в ЕВА - отсеке про выход в космас? Зачем нам гражданские в космасе?

**Comment by Lancer411** [comment]
Поддерживаю добавление замедляющих, но доступных скафандров с защитой от давления для экипажа.

**Comment by P-20** [comment]
В мое время во время разгерм бегали в файерсьюитах.
>Нерфы они везде

**Comment by Lancer411** [comment]
Фаерсьюты сейчас не очень полезны от пожаров. Пожар убивает жарой и давлением, а защита от давления в фаерсьюте позволяла его использовать как риг почти без существенных ограничений.

**Comment by Udokun** [comment]
Насчёт EVA сглупил, да. Всегда считал, что там содержатся предметы для экстренных ситуаций.

Всё хорошо, но зачем резать скорость? Защиту у таких скафандров логично убрать, но скорость совсем загубит геймплей. Гражданские скафандры как никак легче бронированных СБшных, а скорость будет черепашья.

**Comment by dearprincesscelestia** [comment]
Чтобы на всех налезали по идее/чтобы не набигали в них по механу.

**Comment by P-20** [comment]
Какой геймплей алло, они нужны чтобы спастись от разгермы. Если у них будет скорость то космонавтики будут набегать в них и ралеплеить

**Comment by Udokun** [comment]
Набегать на ролек имея нулевую защиту тоже самое, что набегать голым. Один выстрел в этот скафандр и человек умирает из-за своей тупости и разгерметизации.

**Comment by Lancer411** [comment]
А еще он просто не успевает в них добежать.

**Comment by dearprincesscelestia** [comment]
Но ведь защита не нужна для успешного набега, у клоуна вон никакой защиты нет, а есть кожура.

**Comment by skvazarb** [comment]
Этим скафандрам самое место в ящиках поставках для карго, а не в шкафах где ими будут пользоваться мимоассистенты для своих черных дел.

**Comment by Tankred0** [comment]
Мимо ассистенов будут пиздить сбшники и педали за использование скафов для своих чёрных дел.

**Comment by skvazarb** [comment]
>Мимо ассистенов будут пиздить сбшники и педали за использование скафов для своих чёрных дел.

Я ровно с таким же ризоном могу предложить легализовать летал для всего экипажа на станции.

**Comment by dearprincesscelestia** [comment]
А какое черное дело можно сделать с мешком, который защищает от разгерм, но в который не входят магбутсы?

**Comment by Tankred0** [comment]
Леголизовать летал это жи охуенно, Амбиент как то делал такой ивент. Грифозников реально стало меньше.

**Comment by skvazarb** [comment]
Если в него входит защита от радиации, то всё совсем очевидно. Если нет, то проблема отсутствия магбутсов обходится сразу несколькими способами абуза механа и самый очевидный вариант - устраивать как раз те самые разгерметизации. Это нас возвращает к вопросу о необходимости таких скафандров. Гулять по разгерметизированной станции в общем случае в них всё еще не получится из-за бросков, а сидеть в своем отсеке можно, как правило, и без него, потому что створки защищают всех достаточно сообразительных, чтобы их не открывать.

**Comment by dearprincesscelestia** [comment]
> Если в него входит защита от радиации, то всё совсем очевидно.

Но ведь нет.
>  Если нет, то проблема отсутствия магбутсов обходится сразу несколькими способами абуза механа и самый очевидный вариант - устраивать как раз те самые разгерметизации. 

Поподробнее (буду абузить (нет)). Кроме стула ничего в голову не приходит.

**Comment by dearprincesscelestia** [comment]
Вообще контрпредложение.

Тонких скафандров сделать везде, но мало (и под доступом?)

Но. Сделать тонкие, незащищающие СПАСАТЕЛЬНЫЕ ПУЗЫРИ. С механом смирительной рубашки. И их сделать как раз чтобы на каждого. Первый успевший запаковывает остальных и оттаскивает в безопасное место.

**Comment by skvazarb** [comment]
>Но ведь нет.

Надел скафандр, вышел в космос и набежал на условную оружейную.

>Поподробнее (буду абузить (нет)). Кроме стула ничего в голову не приходит.

Самое простое - офисные стулья или инвалидная коляска. На них и ездить можно. В более общем случае все контейнеры, в которых могут мобы находиться, и все объекты к которым можно пристегнуться.

Против костюмов, которые защищают только от давления, но в космосе не держат радиацию, существенных аргументов, конечно, нет. Но и польза от них под вопросом.

**Comment by dearprincesscelestia** [comment]
> Надел скафандр, вышел в космос и набежал на условную оружейную.

И умер от радиации - потому что но ведь нет.

> Самое простое - офисные стулья или инвалидная коляска. На них и ездить можно. В более общем случае все контейнеры, в которых могут мобы находиться, и все объекты к которым можно пристегнуться.

Насколько я помню, все шлюзы в космас в публичных и относительно публичных зонах у нас с окнами, так что такой финт ушами будет замечен заранее. А людей около шлюза в принципе стоит подозревать в плохом. Это точно проблема?

> Против костюмов, которые защищают только от давления, но в космосе не держат радиацию, существенных аргументов, конечно, нет. Но и польза от них под вопросом.

Но ведь они нужны именно не в космосе. Дешевая (сравнительно) защита от разгермы и есть дешевая (сравнительно) защита от разгермы.

**Comment by YulianR** [comment]
Вставьте ск-1 гагарина в каждый отсек по две штуки, пусть от радиации не защищает, как по канону, пусть будет дешевая защита от гуляющих по станции разгерм.

**Comment by skvazarb** [comment]
Если скафандры не рвутся с первого удара, то это слишком имба и в них точно можно бегать разгермы устраивать или проще набегать на всех подряд. А если рвутся, то в перспективе проблема с экипажем, разносящим разгерметизации по станции, может только усугубится, так как у них создается ложное ощущение безопасности и они мало того что сами помрут от первого броска об стену, так еще и разгермы начнут еще больше наносить. Проблема небольшая, но все-таки ее стоит отметить в обсуждении.

**Comment by dearprincesscelestia** [comment]
>  А если рвутся, то в перспективе проблема с экипажем, разносящим разгерметизации по станции, может только усугубится, так как у них создается ложное ощущение безопасности и они мало того что сами помрут от первого броска об стену, так еще и разгермы начнут еще больше наносить.

Мне кажется, это плюс.

**Comment by skvazarb** [comment]
>Мне кажется, это плюс.

Тогда под предлогом уменьшения количества смертей, их может стать только больше.

**Comment by Raschert0** [comment]
`Примерно вот этим:

http://www.space.com/images/i/000/000/414/original/LLM-why-are-space-suits-orange-100601-02.jpg

http://3.bp.blogspot.com/_-zOrAL1V5Jg/TCcuLKlFnSI/AAAAAAAAFV0/oJxsVZh6FsM/s640/800px-Constellation_spacesuit.png` В
Эй, я не о "давление низкое, но оно есть". Я о "БЛЯДЬ, МЫ В СПЕЙСЕ, ТУТ ВАКУУМ, ШПАСИТЕ". Чем в такой ситуации они отличаются? Те, что ты скинул, кстати, от вакуума не спасут

**Comment by dearprincesscelestia** [comment]
> Тогда под предлогом уменьшения количества смертей, их может стать только больше.

Никто не говорил, что есхот - идеал комической станцеи.

**Comment by Uvash** [comment]
Тогда нужно болтирование повреждённых отсеков как на Луне.
 Идея по мне выдавать сублимированные скафандры всем кажется странной, а вот герметичный мешок для трупов вполне возможно. Что бы в случаи появления разгерма ты мог быстро спрятаться в него и ждать прихода спасателей (смерти). 
Возможно скафандры ассистентов можно запихнуть в шкафчики с кислородом, но их тогда понерфить нужно будет в плане защиты от радиации. А так же разнерфать пожарные костюмы. Возможно их вообще перевести в скафандры, да бы на них появлялись дыры от пуль и прочего.

**Comment by dearprincesscelestia** [comment]
Если пожарный костюм превращать в скафандр - тогда нерфать доступ.

**Comment by Tankred0** [comment]
Мешки только занерфали, что бы в них нельзя было спастись от разгермы и поездки по мусору.

**Comment by Uvash** [comment]
А он и так занерфлен. Ибо большая их часть лежит в техтонелях. А защиты от радиации я не предполагал.

**Comment by dearprincesscelestia** [comment]
Техтоннели - вотчина самой грифозной части экипажа.

**Comment by dearprincesscelestia** [comment]
http://www.astronautix.com/r/rescueball.html

**Comment by Uvash** [comment]
Ну и разница, оденет он пресс сьют (скаф ассистента) из шкафчика в прибытии или же оденет его в техах? Возможно спас мешки будут прозрачными, да бы можно было определить кто в них и быстро спасти или добить.

**Comment by dearprincesscelestia** [comment]
Ну, если пожарный костюм не будет защищать от берна, то никакой. Вопрос - зачем он будет нужен.

**Comment by Uvash** [comment]
Гетто версия атмосферного рига. В космос не выйти но вот пожар и следующий за ним разгерм поможет пережить (потушить)

**Comment by dearprincesscelestia** [comment]
Значит, нерфать доступ.

**Comment by Skippeer12** [comment]
А можно просто спавнить хуманов на станцию с блюспейс капсулой (конечно будет другое название и призывать умеет только прешур сьют, как у капитана, без способности выйти в спейса, но сиденим на тайле станции)
Это же намного проще и логичнее чем пихать их в каждый ящик.

**Comment by dearprincesscelestia** [comment]
Или так.

**Comment by WallShrabnic** [comment]
Уже и на форуме эту идею обсуждали, в итоге зашли в тупик. Распишу по полочкам.
1. Спас мешки - идея хорошая, но возникают два вопроса - будет ли запас кислорода внутри и будут ли они многоразовые, иначе - смотрите на стазис мешки. Вообще, главный минус данной идеи - не соснуть от роли не поможет скорее всего
2. Скафы в шкафчиках не лучшая идея - у наших игроков есть причычка тащить любое барахло к себе, в итоге скафов когда они будут нужны просто не останется. Другая сторона - можно не успеть добежать и надеть скаф
3. Идея шкипура. Я за всеми руками и ногами, ибо дешёвый скаф без хождения по космосу - это то, что нужно всяким поварам и барменам и частным глазам.

**Comment by dearprincesscelestia** [comment]
А еще можно поставить атмос с тг.

**Comment by Zmey25** [comment]
>  Вообще, главный минус данной идеи - не соснуть от роли не поможет скорее всего
Цель этих мешков не защищать от ролек, а давать чуть больше свободы во время полной жопы

**Comment by WallShrabnic** [comment]
Во время полной жопы шансы выживания всяких гражданских стремятся к нулю

**Comment by igigin** [comment]
Его и хотят хоть и слегка, но поднять.

**Comment by dearprincesscelestia** [comment]
Поправочка - поднять там, где нет сколь угодно серьезных событий. Под пулями, во взрывах, пожарах и на сквозняке они все еще будут мереть аки мухи, и это вряд ли стоит исправлять. Ну разве чтобы всякие любители банировать имели повод побанировать.

**Comment by Uvash** [comment]
Ну я по этому и предлагал мешок для трупов (самоспасатель) Так они (экипаж) будет тихо мирно лежать в этих мешках. Ну возможно ещё ползать как тараканы ...

**Comment by dearprincesscelestia** [comment]
Надувной шарик и перекатываться как тараканы.

**Comment by dearprincesscelestia** [comment]
(Желтый).

**Comment by DeadOberst** [comment]
Капитану нужен нормальный скафандр, а каждому главе в кабинет личный скафандр. Ну разве что кроме хопа.

**Comment by StrikS** [comment]
Но ведь не нужен

**Comment by DeadOberst** [comment]
А, кстати. 
Толстые будут страдать или смогут натянуть на себя эту резинку?

**Comment by dearprincesscelestia** [comment]
> Капитану нужен нормальный скафандр, а каждому главе в кабинет личный скафандр. Ну разве что кроме хопа.

Перед капитаном толпа инженеров должна все герметизировать и стелить ковры. Вот еще, в скафандр залезать.

**Comment by igigin** [comment]
Но как тогда за капитана рембовать?

**Comment by dearprincesscelestia** [comment]
Перед капитаном толпа шитсеков должна всех расстреливать и заковывать. Вот еще, рембовать чем-то кроме чейн оф комманд.
