### ISSUE TITLE
[Proposal] Сохранять в статистику последнюю фразу человека перед смертью

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#10443]
Сохранять в статистику последнюю фразу человека перед смертью.

Почему? Потому что смешно

**Comment by Chip11-n** [comment]
А ещё сделать статистику сколько из них будет "И-иды ты на... "

**Comment by KIBORG04** [comment]
Чем чаще будете дохнуть, тем больше данных, тем лучше их можно проанализировать. Например, цепочки Маркова (вроде так названа штука)

**Comment by LoTaRk-FroG** [comment]
Уже есть, стоит закрыть.
