### ISSUE TITLE
Телекомы опять отключаются после Grid Check

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1044]
#### Подробное описание проблемы
Телекомуникационный спутник отключается и не включается обратно после Grid Check.
#### Что должно было произойти
Он не должен отключатся вовсе
#### Что произошло на самом деле
Отключился.
#### Как повторить
Включить Automated Grid Check.
#### Дополнительная информация:
![5125](https://cloud.githubusercontent.com/assets/18488106/22209964/e5812604-e190-11e6-8f6f-72675cc88331.png)

**Comment by igigin** [comment]
Так пофиксилось или нет?

**Comment by Kurshan** [comment]
Предполагаю, что да, потому как я последний раз видел, энергия тратилась как раз уже после ВОЗВРАЩЕНИЯ энергии на весь стейшон (а у меня в тот момент они не были включены в список). Но тут лучше подождать, пока оно ещё раз сработает и посмотреть ингейм (ведь затриггерить в ручную нам всем лень, да и не работает)

**Comment by Dennok** [comment]
судя по прайтам смес полный, но выключен. Грид чек после возвращения заряжает смесы на 100% но не возвращает настройки(смесы оффнуты.)

**Comment by Dennok** [comment]
вроде у нас вообще нет такого понятия как смес защищенный от грид чека, только апц.

**Comment by Skippeer12** [comment]
Там не только смес выключает, но и полностью садит АПЦ.

**Comment by Kurshan** [comment]
Таки пофикшено. Можно закрывать
