### ISSUE TITLE
Стол пыток культиста пропадает, есть на него кого-то положить

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#10470]
#### Подробное описание проблемы
Стол пыток культиста пропадает, есть на него кого-то положить

Скорее всего, баг появился после ПРа на стройку хирургических столов, так как пытки = хирурга стол

#### Что должно было произойти
не пропасть

#### Что произошло на самом деле
Пропал

#### Как повторить
Положить человека на стол

**Comment by Mercurialaste** [comment]
Пофикшено, забыл указать в пре.
