### ISSUE TITLE
Особка на голема-тестовика с квирком полноты делает торс невидимым

### ISSUE THREAD

**Issue by muWander** [TauCetiStation/TauCetiClassic#10475]
#### Подробное описание проблемы
https://github.com/TauCetiStation/TauCetiClassic/pull/10425 вместе с квирком полноты делает толстого персонажа големом, а спрайта големской "одежды" для толстых нет, и вообще они NO_FAT
#### Что должно было произойти
Големы не должны быть с лишним весом
#### Что произошло на самом деле
а с особкой это возможно
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/39914744/205499021-cfdad9e0-aa4c-4909-a4f1-9699a21e34aa.png)

**Comment by 23as23as** [comment]
это был я, адамантид 467, там не просто невидимое, через торс невидимый можно пол потрогать

**Comment by TryXAH** [comment]
О, это же он по идее и простреливается насквозь...
