### ISSUE TITLE
Удаляется стекло шаттла нюки 

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#10497]
#### Подробное описание проблемы
При перелете шаттла нюки с места на место, в случае, если на месте стекла шаттла заспавнилась трава/деревья с зимней карты, стекло удалится и вернется только после перелета в зону синди.
#### Что должно было произойти
Стекло остается, деревья и трава — нет
#### Что произошло на самом деле
Стекло исчезло, деревья и трава остались.
#### Как повторить
Полетать на шаттле нюке в зимнюю карту. 
#### Дополнительная информация:

https://user-images.githubusercontent.com/90282587/206894514-9742b16a-d0dc-4e10-b910-d7c48aeb9288.mp4

**Comment by kalazus** [comment]
На боксе неправильная зона справа от спутника, если скопировать на неё другую, то видно что она меньше чем должна быть. Ровно на 1 пиксель.

**Comment by kalazus** [comment]
И слева от спутника неправильная... Вроде потерян 1 пиксель на правой части (она не симметричная)
