### ISSUE TITLE
Engineering Camera Monitor показывает камеры тюремки брига.

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#105]
Originally reported by: **Фаря . (Bitbucket: [FiregunnZ](http://bitbucket.org/FiregunnZ), GitHub: Unknown)**

----------------------------------------

Код перепутали видимо. Работает как терминал в приемной брига, хотя должен показывать инженерных боргов и дронов.

----------------------------------------
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/105

**Comment by SpaiR** [comment]
Пофикшено где-то там.
