### ISSUE TITLE
Слепые зоны у ИИ.

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#1052]
#### Подробное описание проблемы
У ИИ по станции есть несколько слепых зон в важных отсеках.
#### Что должно было произойти
ИИ должен иметь возможность видеть что происходит на его станции
#### Что произошло на самом деле
ИИ не смог открыть двери по запросу и вообще ничего не увидел.
#### Как повторить
Зайти за ИИ и проверить некоторые зоны. 
#### Дополнительная информация:
http://imgur.com/a/mLMqU

**Comment by Uvash** [comment]
Ну напротив казарм иксрей камера... Не знаю кто и зачем её туда воткнул

**Comment by dearprincesscelestia** [comment]
> ИИ должен иметь возможность видеть что происходит на его станции

Но ведь нет. Точно так же, как не все костюмы должны быть в третьем режиме круглые сутки даже у законопослушных крюмемберов, точно так же, как нельзя сажать за мыло розового цвета.

**Comment by Udokun** [comment]
К слову о слепых зонах. 
![75b757a5a3b144529de1b5c68e7cb8ca](https://cloud.githubusercontent.com/assets/24526545/22374331/d8b9a5da-e4b6-11e6-9dd9-c044f407a818.png)

**Comment by Smalltasty** [comment]
Некоторые слепые зоны можно обойти, открыв двери. С той же вирусологией и ксенобиологией канает. 
Для всего остального есть инженеры и автолат

**Comment by DeadOberst** [comment]
С вирусологией уже давно такое не работает.
Без доступа врача никого не пропустить через центральную дверь.

Собственно, это и есть самый критичный участок.

**Comment by dearprincesscelestia** [comment]
> Мне кажется, что
а) упражняться в телепатии - контрпродуктивно, и зовите маппера.
б) вне зависимости от того, намеренно или нет, надо оценить результат, нравится он или нет.

> Если не задумывалось и не нужно - убрать.
Задумывалось и нужно - оставить.
В остальных случаях - нужны аргументы серьезнее телепатии, тебелинезнати и рассуждениях о философском значении ИИ в нашей жизни.

Собственно, по своему опыту могу сказать, что в ситуациях "ИИ, открой" - "вас нет на камерах" особого фана нет. А вот скриншот удокуна выше - абсолютно нормально.
