### ISSUE TITLE
Серная кислота на Прометее

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#10549]
#### Подробное описание проблемы
Раздатчик серной кислоты в робототехнике на Прометее стоит неправильно. Раздатчик занимает собой тайл, поэтому на всех других картах он поставлен на столы или другие машины. На Прометее же он стоит на пустом тайле, тем самым блокирует путь.

**Comment by Mercurialaste** [comment]
@Tap0r Пофикшено?

**Comment by Tap0r** [comment]
Да в новогоднем, но пусть висит, т.к новогодний пр в тме, после него отдельный сделаюти там укажу этот как клосед

**Comment by Venngedi** [comment]
#10492
