### ISSUE TITLE
Ваншот мина культа. 

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#10545]
#### Подробное описание проблемы
Культист может накидать на тайл 50 книг и они будут убивать любого наступившего. 
#### Что должно было произойти
У культа нет ваншот мины. 
#### Что произошло на самом деле
Ю фил а терибл пейн вен ю степ зис x50
Ю сайз ап анд фалл лимп, юр айс дед анд лайфлесс. 
#### Как повторить
Положить на пол за культиста 50 книг.

**Comment by KIBORG04** [comment]
Фича
