### ISSUE TITLE
Плазма не разряжается от ЭМИ

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#10547]
#### Подробное описание проблемы
Магазины для плазмы не разряжаются от ЭМИ.
#### Что должно было произойти
ЭМИ разряжает батарейку внутри магазина.
#### Что произошло на самом деле
ЭМИ не делает ничего.
#### Как повторить
Подвергнуть ЭМИ плазменное оружие или его магазин.
#### Дополнительная информация:
хз, баг или фича такая.

**Comment by AndroBetel** [comment]
это фича
