### ISSUE TITLE
Эсенция смотрит своими глазами через генокрада

### ISSUE THREAD

**Issue by Fluffy-510** [TauCetiStation/TauCetiClassic#10559]
#### Подробное описание проблемы
Эсенция может осматривать вещи с логами типо её кукла где-то рядом
#### Что должно было произойти
эсенция осматривает кого-то, логов о том что она смотрит нету
#### Что произошло на самом деле
эсенция осматривает кого-то, есть логи что ОНА смотрит
#### Как повторить
быть съеденым генокрадом и начать осматривать вещи

**Comment by pro100kotah** [comment]
Звучит страшно и пугающе
