### ISSUE TITLE
Сломанный форс шаттла

### ISSUE THREAD

**Issue by NeOchenLord** [TauCetiStation/TauCetiClassic#10557]
#### Подробное описание проблемы

Мне, тритору с задачей на хайджек, не получилось зафорсить шаттл для раннего отлёта.

#### Что должно было произойти

Я тыкаю тремя картами по консоли шаттла и активирую ранний вылет.

#### Что произошло на самом деле

Я тыкнул аж 4 картами и мне продолжало говорить, что требуется еще 1 авторизация.

#### Как повторить

Попробовать форсануть шаттл??

#### Дополнительная информация:

Round #56590

**Comment by Deahaka** [comment]
Карты могли быть бракованными. Нужны уникальные имена на картах.

**Comment by NeOchenLord** [comment]
Карты без имён но с доступом не подходят разве? Вроде раньше работали🤨
