### ISSUE TITLE
Все toy нельзя нормально кинуть 

### ISSUE THREAD

**Issue by Fluffy-510** [TauCetiStation/TauCetiClassic#10555]
#### Подробное описание проблемы
Нельзя кинуть все игрушки дальше чем под ноги.
#### Что должно было произойти
Кинул пушистого кота на стол 
#### Что произошло на самом деле
Кидаешь игрушку на стол, а она кидается под ноги
#### Как повторить
кинуть

**Comment by Deahaka** [comment]
@DarthSidiousPalpatine , твой выход

**Comment by DarthSidiousPalpatine** [comment]
Дратути. Да, мой косяк, я забыл прописать запрет на кидание только игрушке Сингулярности, случайно, прописал запрет на кидание любой игрушке вообще. Бывает, собсна.
