### ISSUE TITLE
Спрайто-проблемы с оторваными руками на куклах

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1057]
#### Подробное описание проблемы
Правая оторваная рука отображается не корректно.
#### Что должно было произойти
Её недолжно быть.
#### Что произошло на самом деле
А она есть.
#### Как повторить
Оторвать правую руку на кукле.
#### Дополнительная информация:
![44552](https://cloud.githubusercontent.com/assets/18488106/22354497/483c5774-e42e-11e6-98b1-75a445eedad1.png)

**Comment by igigin** [comment]
Дубль два #767.
