### ISSUE TITLE
Ребаланс цены поверфиста [Proposal]

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#10596]
#### Подробное описание проблемы
После ребаланса поверфиста он стал крайне бестолковым. В первом режиме он фактически наносит один сильный удар, удар послабее, а дальше становится бесполезным. Второй и третий режимы работают просто на один удар. При этом цена как была 8 тк, так и осталась, что выглядит чрезмерно завышено. Красная цена этому оружию 3 тк.

**Comment by Chip11-n** [comment]
Станится ли человек? Голова взрывается от удара? Если да, то цена оправдана

**Comment by F0xiq** [comment]
В общем то не станит, даже предметы не выпадают из рук, в третьем режиме гибает незащищенную голову, но это режим ровно на один удар. Да и шлем защитит даже в третьем режиме, как и каска.

**Comment by TryXAH** [comment]
Поверфист даже до ребаланса был хуже есворда по всем показателям, а стоил больше. 
Цену действительно нужно снижать хотя бы до 5

**Comment by simb11** [comment]
а мне кажется нужно не менять цену в аплинке, а понизить затраты газа для удара

**Comment by TryXAH** [comment]
Так он своих 8 тк вообще никак не оправдывает. За такие деньги и револьвер взять можно

**Comment by LoTaRk-FroG** [comment]
Я бы поднял цену до 10-12 тк и заменил газ на батарейку или еще че-то (не особо высокое потребление, где около 1000 за удар). Или вообще сделать его бесконечным и цену 14 тк.
