### ISSUE TITLE
Резист

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#106]
Originally reported by: **Anonymous**

---

Нужно бы починить давно уже сломанный резист, а именно, резист не дает сопротивляться раздеванию, тоесть пишется, что Петр резистает, но карта с него, например, все-равно снимается

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/106

**Comment by Skippeer12** [comment]
Куршан это починил, теперь при резисте например наручники нельзя нацепить на человека, со сниманием одежки не проверял.
