### ISSUE TITLE
Воуты снимают фокус на игру

### ISSUE THREAD

**Issue by 4310V343k** [TauCetiStation/TauCetiClassic#10619]
#### Подробное описание проблемы
Воуты каждую секунду при обновлении переключают фокус на игру, из-за чего написать что-то в say или ooc нереально
#### Что должно было произойти
Какие-то интерфейсы не должны влиять на игру настолько
#### Что произошло на самом деле
Убила генка потому что не успел крикнуть в общий из-за воута
#### Как повторить
Включить воут, попытаться что-то сказать через "T"/"O"/"F3"/"F2"
#### Дополнительная информация:
Если воуты сделать на тгуи, то проблем не будет
Ещё вроде как модальные окна имеют возможность возвращать фокус на предыдущее активное окно

**Comment by AirBlack** [comment]
Очень бесит когда пишешь кому-нибудь ПМку либо просто текст в дедчат, открывается окошечко с позитронным мозгом, ты жмешь пробел и выбирается "да хочу в моск". Я так пару раз мозг сломал что пришлось новый спавнить.

**Comment by BasiaBelov** [comment]
На самом деле, с воутами не очень сложно решить проблему. Просто убрать функцию вывода окошка. Пускай те люди, что хотят голосовать нажмут на это голосование, чтобы окошко открылось.
Насчёт передачи предметов, предложений в вступление в секту и той же позитронки на гостах я не знаю...
