### ISSUE TITLE
Пропавшие инхенды у флаффов

### ISSUE THREAD

**Issue by PersyFOX** [TauCetiStation/TauCetiClassic#10615]
#### Подробное описание проблемы
inhands на флаффах отвалились и больше не показываются. Так же когда заполняешь окошко с флаффом на одобрение, в окошке предпросмотра флафф не будет показываться вообще пока из dmi файла с флаффом не уберешь инхенды. Перепроверял старые флаффы которые делал, через скачку билда, через sandbox сервер посредством VV, через стандартный сервер где могут принять флафф. Инхендов флаффов нет нигде из перечисленного

#### Что должно было произойти
Спрайт inhand флаффа должен быть виден в раунде ибо он есть в dmi файле
#### Что произошло на самом деле
Отсутствие спрайтов инхендов флаффа
#### Дополнительная информация:
Видел багрепорт уже о инхендах, похоже что проблемы афигеть как связаны. Спасите флаффодела!

**Comment by Deahaka** [comment]
#10496 ?
