### ISSUE TITLE
В результатах раунда цель ОБР всегда выполнена

### ISSUE THREAD

**Issue by Riverz1** [TauCetiStation/TauCetiClassic#10624]
#### Подробное описание проблемы
В конце раунда, в окне с результатами у ОБР всегда выполнена их цель в независимости от итогов смены.
#### Что должно было произойти
Результаты должны менятся в зависмости от выполнения цели.
#### Что произошло на самом деле
Результаты всегда показывают выполнение цели ОБР.
#### Как повторить
Заспаунить ОБР и взорвать нюку.

**Comment by KIBORG04** [comment]
фича
