### ISSUE TITLE
Из стиральной машины и желтого мелка можно сделать из любых перчаток изоляционные

### ISSUE THREAD

**Issue by Riverz1** [TauCetiStation/TauCetiClassic#10629]
#### Подробное описание проблемы
Если засунуть например латексные перчатки и желтый селок стиралку, мы полкчим желтые изоляционные перчатки, вернее только их название, свойств они, как я понял не приобретают.
#### Что должно было произойти
Должны были получиться желтые перчатки
#### Что произошло на самом деле
Получились изоляшки
#### Как повторить
Засунуть желтый мелок и любые перчатки.

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/blob/84d22e9558fc8de80f0da6223a7176d3da2f52ac/code/game/machinery/washing_machine.dm#L31

https://github.com/TauCetiStation/TauCetiClassic/blob/e39cb93aaa57724f69b06844d5343424e3d92921/code/modules/clothing/gloves/color.dm#L1

А еще можно тайп переименовать у изолок на нормальный

**Comment by ViDLiathan** [comment]
Фича, ассистухам выдавать

**Comment by TheLone1y** [comment]
Вау можно засунуть мелок мима и получить белые перчатки втф!!!!!
