### ISSUE TITLE
Шлемы отряда смерти не защищает глаза от работы со сваркой

### ISSUE THREAD

**Issue by Riverz1** [TauCetiStation/TauCetiClassic#10625]
#### Подробное описание проблемы
При работе со сваркой, шлем отряда смерти не защищает глаза.
#### Что должно было произойти
Шлем должен был защитить глаза от работы со сваркой.
#### Что произошло на самом деле
Шлем не защитил глаза от работы со сваркой.
#### Как повторить
Взять сварку и попробыать что-то сделать ею в шлеме отряда смерти.

**Comment by KIBORG04** [comment]
кто сказал что должен

**Comment by KIBORG04** [comment]
пока не скажешь - закрыто

**Comment by Riverz1** [comment]
Элитный риг отряда смерти не должен защищать от сварки? What?

**Comment by KIBORG04** [comment]
отряд смерти должен чето варить?

**Comment by Riverz1** [comment]
Кнч, разобрать стену, починить мех, зашита есть у всех костюмоа кроме евроса наверное, блин и это ЭЛИТНЫЙ ОТРЯД.

**Comment by KIBORG04** [comment]
им же не дают инструментов

**Comment by Riverz1** [comment]
И что? На станции нету чтоль?

**Comment by KIBORG04** [comment]
ну так... значит их цель ломать стены сишкой, пульсачем, а не сваркой

**Comment by Riverz1** [comment]
У элит отряда нюки тоже нету инструментов, но их риг защищает.

**Comment by Riverz1** [comment]
Ты пульсачом мех чинить будешь?

**Comment by simb11** [comment]
может термалы нужно выключать перед тем как работать со сваркой

**Comment by Riverz1** [comment]
Эт влияет?

**Comment by simb11** [comment]
д

**Comment by Riverz1** [comment]
Хмм.. это такой механ или баг?

**Comment by simb11** [comment]
фича очевидно
