### ISSUE TITLE
Монитор крю не видит экипаж на других слоях

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#10636]
#### Подробное описание проблемы
Монитор крю (любой, стационарный или ручной) не может отслеживать состояние датчиков здоровья космонавта если тот находится на другом слое.
#### Что должно было произойти
Монитор крю должен отслеживать данные по челу на любом слое. 
#### Что произошло на самом деле
Шахтеры и археологи отправляются в госты ждать респавна ибо о их смерти никому неизвестно.
#### Как повторить
На станции. Единственный вариант при котором можно отследить состояние - это явится непосредственно на астероид с ручным монитором.
#### Дополнительная информация:
Трекер не выдает на каком слое находится кукла, что как бы нормально.
![image](https://user-images.githubusercontent.com/19796920/214063744-050a206d-ca3f-44f3-ad80-bdfcfecda065.png)
![image](https://user-images.githubusercontent.com/19796920/214063952-a23a6d19-b112-4f42-b838-0bb6220d9bbe.png)

**Comment by NikMaestro** [comment]
Фича

**Comment by KIBORG04** [comment]
фича

**Comment by Deahaka** [comment]
Вряд-ли это не потому, что грузится всего одна карта наноуи и на ней координаты всех выставляются

**Comment by WatlerJe** [comment]
Фича гавно - переделывай
