### ISSUE TITLE
Откат #10154 и #10286 или make miners great again [Proposal]

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#10638]
#### Подробное описание проблемы
Поиграл последний месяц исключительно на шахтере и извлек несколько крайне грустных уроков: балансдепа не существует (факт в общем-то известный и до этого, просто лишнее подтверждение), а ещё то, что существуют люди, не понимающие как работает какая-нибудь профессия, пытаются что-то менять в ней.
Конкретно речь про ПРы [BiQndy](https://github.com/BiQndy) и [simb11](https://github.com/simb11) за номерами #10154 и #10286 соответственно.
Первый видимо предполагался как баф кинетика и резонатора, и если резонатор стал относительно юзабельным (вопрос обороны им от фауны так и не решен), то с первым произошел полный провал и совершенно непонятный нерф, раньше за 2500 шахтерских очков получал топовый кинетик, то теперь даже два улучшения на перезарядку по 2250 каждый (в сумме 4500) всё ещё оставляют его хуже, чем был старый кинетик (то есть платишь больше, а эффект хуже чем был?!), все другие улучшения на кинетик имеют минимальное влияние на геймплей шахтера: два модуля повышения урона, да приятно, чуть быстрее убьешь голиафа, но это совершенно не влияет ни на что, два модуля на радиус совершенно бесмысленно ставить, так как даже монстра в четвертом радиусе не всегда видно. Плюсом повысились цены практически на всё в шахтерском вендомате по какой причине и почему совершенно непонятно, может быть логика была такая что: ты выбрал профессию шахтера, то должен страдать и вообще не появляться на станции и никак не участвовать в раунде.
Со вторым ПРом вообще смешно: во-первых изучение каттера входит в ту категорий изучений РнД, которое никогда не изучается в первую очередь(кто работал в РнД, тот знает, что на это изучение почти никогда не хватает очков), а во-вторых им невозможно копать руду, так как заряд его настолько быстро кончается, что приходится носить по 4 каттера. Про сомнительную эффективность емагнутого каттера можно не говорить даже (однозарядный лазер, который иногда сможет сломать пласталевую стену, это видимо какая-то шутка, сравните с емагнутым пирометром). Как должен работать хороший каттер можно посмотреть на каком-нибудь ТГ или парадайзах: заправка плазмой, пробивание породы. То что есть сейчас это жалкое подобие, не эффективное, требующее обязательного наличия bag of holding. Старый каттер был хотя бы хорош как бесконечная сварка, новый лишен даже этого функционала.

#### Что произошло на самом деле
Ты шахтер - страдай, ты никто и вообще не человек.
#### Как повторить
Поиграть на шахтере.
#### Дополнительная информация:
Лучше бы выпилили сингулярных мобов с астероида, адекватных мер борьбы с ними нет. И вообще игра должна приносить удовольствие, а не превращать раунд в унылое копание астероида. Есть же примеры хороших ПРов, тот же сапер в ящиках, мелочь, но помогает отвлечься от рутины.

**Comment by TryXAH** [comment]
Это конечно все так, молодец, да. Расписал по фактам.
Однако от этого никто не пошевелится. Чтобы добиться что-то, нужно самому лезть и фиксить

**Comment by pro100kotah** [comment]
Я не знаю каким образом ты сапер в плюсы запихнул. Я shaft miner enjoyer. 40к минуток только на шахтере. И этот сапер какая-то хуйня. Если раньше ты рандомом и легким пересчетом мог вскрыть ящик и получить годну тему, то щас ты играешь в ебаный сапер и получаешь трусы, пока пару минут тратишь на отгадывание точек с минами. В итоге со старого ящика первый, второй и третий тир они смешали все вместе. Так что сейчас этот сапер дрочить даже смысла нет, потому что в общей сумме в ящике много хлама и зачастую падает он. Дак еще и сапер не всегда удобный попадается. Тыкаешь первую кнопку, у тебя 1. Тыкаешь вторую рядом или наугад - ящик сломан и уже идет чистить тебе ебало. 
Вернуть бы старую механику с мультитулом и суммой трех чисел. Сапер это троллинг шахтеров. Типо вот вы дрочите свои камни на астероиде всю смену, на, дрочите теперь еще и сапер. А чтобы ресурсы из плавильни вытащить мы вам еще косынку добавим. Пиздец

**Comment by pro100kotah** [comment]
А резонатор тема. Им я доволен. Появился смысл его брать вообще. И звук приятный его работы. Правда, чтобы им фауну убивать нужно придрочиться и то не всех сможешь валить, но как минимум только для добычи тема хорошая. Насчет плазма каттеров - мне понравилась переделка Симбаки. Правда я никогда, что до, что после не считал плазма каттер за плазма каттер. Если до он был просто сваркой, то сейчас это быстрая сварка на пару выстрелов, которая еще и укрепу снести может. Никто ими не копает.

**Comment by BiQndy** [comment]
> Сложилось ощущение, что повышением дроча автор лишь хотел превратить работу шахтеров в отдельную игру.

Отчасти это правда, я не хотел, конечно, их бытие превращать в неиграбельную скучную фигню, я просто хотел сделать немногим больше контента на астероид этими модулями. Ослабил бафы от них потому что посчитал, что если  взять два загрейженых на фулл кинетика то они смогут выносить всё и вся. Немного повысил цены на некоторые предметы в шахтомате по причине того, что сейчас ресурсы падают в большем обьеме, чем раньше, из за того, что у многих инструментов щас может быть дроп минералов больше 100%, следовательно, и поинтов больше фармится. В принципе, могу откатить этот механ с модулями до истоков, если всё так плохо.

**Comment by Riverz1** [comment]
Сапер лучше чем дрочь в циферки, ведь дрочь в циферки перешёл ещё в боллее глубокий дрочь в калькукляторе. Режим сапера мне больше понравился, хоть и сейчас имба шмокти из ящиков гораздо сложнее вытащить, но вы в курсе что помимо ящиков есть комнаты 3 на 3 где есть похожий шмот? А по поводу дроча на шахте, там на изи все вкачать за минут можно, не вижу проблемы, мне и 12 хватает где-то, ведь кинетик все-равно только на шахте юзабелен. Мне нравятся оба ПРа

**Comment by Riverz1** [comment]
Хотя если даже брать все выше сказанное, почему-то до сих пор не в игре, не на вики нету объяснений по поводу апгрейдов кинетика и да, апргейды оч слабые, хоть с ними хоть без играй, толку мало будет.

**Comment by DarthSidiousPalpatine** [comment]
> 

Никто ничего не мешал, иди нахер

**Comment by DarthSidiousPalpatine** [comment]
Все виды лута были сохранены и остались отдельно.

Единственная проблема что, видимо, попадается чаще простой сапёр. Вот и выходит что всё просто.

**Comment by Riverz1** [comment]
Я бы объеденил два модулья апгрейд в 1 и разделил бы их на 2 класса и поставил бы цену в 4000 кредитов где-то, где 1 апгрейд класс шахтера, 2 апгрейд класс охотника. В классе шахтера быстрая перезарядка и болбшая добыча, а в классе охотника большой радиус и большой дамаг.

**Comment by BiQndy** [comment]
> Я бы объеденил два модулья апгрейд в 1 и разделил бы их на 2 класса и поставил бы цену в 4000 кредитов где-то, где 1 апгрейд класс шахтера, 2 апгрейд класс охотника. В классе шахтера быстрая перезарядка и болбшая добыча, а в классе охотника большой радиус и большой дамаг.

норм идея

**Comment by Riverz1** [comment]
Насчет сингулурных мобов, про то-что их убить сложно, эт от части првда, но все возможно их убитт, дайте какую-то кртую штуку после их смерти и все, например (ядерный сингулярный ректор какой-нибудь, который можно юзать как батарейку, но она сама заряжается и имеет большой заряд, но это уже мои мечты)

**Comment by Riverz1** [comment]
> 

Только пж добавте инфу на вики и в игру объяснялки какие-то

**Comment by pro100kotah** [comment]
Сингулярные мобы очень сложны для новичков, разве что. Их убивать на самом деле не слишком сложно. Разве что убивать василиска сингулярного почти анрил, если ты унатх или хуман. В особенности унатх. Без стабилизатора температуры тебе каюк. Ну и без магбутов тоже. Ну, а вот сингулярный голиаф с притягиванием своих же щупалец тоже морока.
Насчет нового контента для шахтеров, хотелось бы новых мобов увидеть или новые заброшенные отделы шахты, хотя это больше к мапдепу. Я очень рад, тому что ты решил заняться контентом шахты, но лучше уж что-то добавить, чем переделывать то что есть, удлиняя процесс работы на шахте. Мы вроде стараемся как можно дальше от афк гейминга уйти. А шахта итак побольшей части со станцией почти не контактирует кроме РнД и карго и то, если это не новички. Новички же там на всю смену в этой шахте пропадают, если не умирают вовсе.
Вот хотелось бы дроп какой-нибудь с сингулярных мобов, который можно было бы использовать или сдавать в РнД. Помимо мобов можно добавить нового снаряжения. Идей можно украсть с того же ТГ или придумать.

Насчет реверта ПРа с кинетиками, этот же ПР затрагивает резонатор? Резонатор хорош, слов нет. Насчет кинетиков, я бы посоветовал вернуть возможность прокачать его до той же степени, каким он был раньше. Сейчас с двумя модификаторами на скорость он медленнее чем был. Даже сейчас я эти кинетики теперь не качаю. Просто со стоковыми фармлю, ресурсы в карго и там заказываем молот. До конца смены работаю молотом и все, а кинетик просто как оружие против мобов. Так что не думаю, что стоит отказываться от этого ПРа.

**Comment by pro100kotah** [comment]
Просто работа шахтера это не то место, где стоит замедлять геймплей. Он итак не особо интересный, ибо ты всю смену бьешь камни и собираешь руду. Эту скуку разбавляет фауна и добыча всяких шмоток. А также псевдопрогресс, когда ты в шахт-о-мате себе снаряжение покупаешь. Поэтому я не особо заценил ухудшение основного инструмента шахтеров.
