### ISSUE TITLE
Лазерг таг оставляет дыры в стенах

### ISSUE THREAD

**Issue by Riverz1** [TauCetiStation/TauCetiClassic#10649]
#### Подробное описание проблемы
При стрельбе из лазер таг по стенам, остаются отверстия.
#### Что должно было произойти
Отверстия не должны были появится.
#### Что произошло на самом деле
Отверстия появились
#### Как повторить
Выстрелить в стену лазер таг ганом.
#### Дополнительная информация:
Лучше вообще всему лазерному оружию такую возможность убрать как по мне, потому что отверстия от огнестрла, а пушки лазерные.

**Comment by Sakuya-Izayoi** [comment]
Duplicate of #9644

**Comment by Riverz1** [comment]
Дубликат
