### ISSUE TITLE
Блобернауты  падают от разгерм

### ISSUE THREAD

**Issue by Riverz1** [TauCetiStation/TauCetiClassic#10648]
#### Подробное описание проблемы
При больших разгермах блобернауты не могут двигаться из-за разгермы и просто стоят на месте.
#### Что должно было произойти
Блобернаут не должен падать от разгермы.
#### Что произошло на самом деле
Блобернаут упал от разгермы.
#### Как повторить
Зайти за блобернаута и сделать разгерму.

**Comment by Deahaka** [comment]
Дубликат, где-то я делал уже ишуй

**Comment by Riverz1** [comment]
Найди, я по названию блобернаут ниче не нашел

**Comment by pro100kotah** [comment]
Дубликат

> Найди, я по названию блобернаут ниче не нашел

https://github.com/TauCetiStation/TauCetiClassic/issues/10225

**Comment by Riverz1** [comment]
Дубликат
