### ISSUE TITLE
[Proposal] Нет диспенсера китов на аванпосте ксеноархеолога

### ISSUE THREAD

**Issue by VRCHarbor** [TauCetiStation/TauCetiClassic#10655]
#### Подробное описание проблемы

Нет диспенсера китов на аванпосте ксеноархеолога, когда последний есть на шахтерском

Поставить надо бы а не на станцию кататься и в ЕВУ проситься или у шахтеров вымаливать

**Comment by NikMaestro** [comment]
К шахтёрам добавить археолог киты и всё, шахтёры есть - плакоешь и просишь, шахтёров нет - прорываешься и берёшь.

**Comment by pro100kotah** [comment]
Пиздец вы че удумали. Шахтеры будут ломиться к археологам за кинетиками, а те в свою очередь на аванпост шахтеров за китами ригов?
