### ISSUE TITLE
Лазерные лучи не проходдят сквозь надувные стены/двери

### ISSUE THREAD

**Issue by Raschert0** [TauCetiStation/TauCetiClassic#1065]
#### Подробное описание проблемы
Лазерные лучи не проходят сквозь надувные двери/стены. Вместо этого они разрывают их
#### Что должно было произойти
Лазерные лучи, теоретически, должны проходить сквозь стены/окна
#### Что произошло на самом деле
Стена лопнула
#### Как повторить
Поставить надувную стену
Выстрелить "сквозь" неё из лазера

**Comment by Zmey25** [comment]
Почему лазер должен проходить сквозь надувную, почти не прозрачную дверь?

**Comment by Raschert0** [comment]
Потому что она прозрачная

**Comment by igigin** [comment]
Надо чтобы её прожигало.

**Comment by WallShrabnic** [comment]
Её с нескольких выстрелов прожигает, дверь уничтожается

**Comment by Lancer411** [comment]
Думаю что не баг. Стенка плавится и лопается, так как не совсем прозрачна. Все логично.

**Comment by dearprincesscelestia** [comment]
Но пропускать тоже должно, просто слабее, ведь прозрачность есть.
 Но это уже технологически сложнее?
