### ISSUE TITLE
На те же грабли или возвращение бага мапы, который исправили.

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#10654]
#### Подробное описание проблемы
Вот кто занимался ремапом бокса и напортачил там всяким, можно же было хотя бы работать с последней, актуальной картой? Только пофиксили тему с вентиляциями спутника под столом, когда все кто вылезает из нее и встает на стол - становится неузявимым к турелям. Вентиляции перенесли - алилуя. Проходит время и их обратно загоняют под стол.
#### Что должно было произойти
Вентиляций нет под столом. Не происходит баг с игроками на столах, по которым не стреляют турели.
#### Что произошло на самом деле
Любой кто вылезает из вентиляции встает прямо на стол и турели его не трогают из-за бага с турелями и столами, который не могут исправить.
#### Как повторить
Зайти на сервер с последней актуальной картой бокса без гирлянд.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/57403011/215154422-ea63244c-d4ed-493e-8429-76e00c70718d.png)

**Comment by KIBORG04** [comment]
пофикшено хер знает в каком ПРе от СГТдевидсона
