### ISSUE TITLE
Выстрелы по шлюзу могут ударить тебя током с расстояния.

### ISSUE THREAD

**Issue by ZER0-In** [TauCetiStation/TauCetiClassic#10660]
#### Подробное описание проблемы
Если стрелять по шлюзу, пытаясь его сломать, либо просто попасть по нему, когда тот наэлектризован, то тебя может ударить током с любого расстояния.
#### Что должно было произойти
Стреляешь по шлюзу и тебя не бьет током за 5км от него.
#### Что произошло на самом деле
Стреляешь по шлюзу глоком или лазганом, чтобы его снести - тебя бьет током. Как тут работает логика - непонятно.
#### Как повторить
Стрелять точно в шлюз, а не по направлению к нему. С каким-то шансом можно получить разряд по себе.
#### Дополнительная информация:
Происходит не часто, но бывает встречается в раундах и вызывает вопросы.

**Comment by arygal** [comment]
Всё ещё актуально
