### ISSUE TITLE
Не полноценное отсутствие рук.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1067]
#### Подробное описание проблемы
У безруких персонажей есть некоторые значительные и не очень баги:
1) Если в настройках поставить что у вас нет полностью рук - на спрайте правой руки будет отсутствовать только ладонь (а еще там кровавое пятно будто руку оторвали. Бинты что ли завезти).
2) На безруких персонажей можно надеть наручник, но раньше они дропались при попытке надеть наручники.
3) Безрукий персонаж все еще может поднимать табуретки.
4) Может снимать вещи с другого перса (хотя сам не считаю это багом, но можно было бы замедлить допустим время если у тебя нет рук).
5) И не совсем баг но - персонаж не может вообще ни в какие интенты. То есть, он мог бы дизармить или бить еще ногами и это было бы логично.

#### Что должно было произойти
1) Спрайты отсутствия рук должны быть нормальными (и желательно с перебинтованными концами).
2) Наручники должны дропаться при надевании их на безрукого или однорукого персонажа.
3) Не должен поднимать табуретки.
4) Замедлить время раздевания или убрать таковую возможность.
5) Должен уметь пиздить быдло-капитанов ногами или хотя бы задизармить долбоеба с еганом.

#### Что произошло на самом деле
Выше.

#### Как повторить
1) Зайти за безрукого в раунд.
2) Надеть наручники на безрукого.
3) Перетащить табуретку на персонажа (я делал это в перма-бриге).
4) Раздеть кого-нибудь без рук.
5) Попробовать покликать на другого персонажа разными интентами без рук.

**Comment by Avatar4** [comment]
Не видел что шкипур уже запостил про ломанный спрайт.

**Comment by dearprincesscelestia** [comment]
> Замедлить время раздевания или убрать таковую возможность

ЗУБАМИ.

**Comment by igigin** [comment]
>То есть, он мог бы дизармить или бить еще ногами и это было бы логично.

Головой.

**Comment by igigin** [comment]
Первая часть почти дубль три
#1057
#767 
Но тут есть ещё дополнение. Потому открытым оставлю.

**Comment by Skippeer12** [comment]
Шел 2017 год, спрайты с рукой всё ещё не пофиксили.

Зато пермамуты есть и баны на мышей.
