### ISSUE TITLE
Пакетик с уликами ворует спрайты!

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#1069]
#### Подробное описание проблемы
В очередной раз билд-кладовка флафа Круасана дал сбой.
#### Что должно было произойти
Все должно работать как надо!
#### Что произошло на самом деле
https://gyazo.com/e437b034045424a19cca76fe654f812a
#### Как повторить
Зайти за криминалиста/детектива, получить задание на расследование, найти улику и положить ее в пакетик.
#### Дополнительная информация:
Лучше еще сами проверьте, ибо у меня оно работает именно так.

**Comment by igigin** [comment]
Спрайты он не ворует, их просто не видно под ui рук. Наверняка проблема со слоями всякими после параллакса. У `core sampler` тоже сломалось, офк.
