### ISSUE TITLE
Люди могут в кошачий язык с движениями хвостами

### ISSUE THREAD

**Issue by ghost** [TauCetiStation/TauCetiClassic#1070]
#### Подробное описание проблемы
Если пройти в вайт на котов, выбрать в чарсетапе ноун ленгвиж Siik'tajr (:y) и заговорить на нем, то персонаж будет эмоутить движения ущами и хвостами

Natalie Rosensteel waves their tail about.
Natalie Rosensteel mrowls, "А я могу хвостом двигать?"
Natalie Rosensteel flicks their right ear.
Natalie Rosensteel mrowls, "МОгу, не зря растила"

#### Что должно было произойти
1) Этот язык нельзя выбрать, если ты не тоера.
2) Этот язык можно выбрать, но эмоутов нет, а тоерам видно твои реплики с искажениями.
#### Что произошло на самом деле
Ты шпрехаешь не хуже тоеры
#### Как повторить
Получить вайт на котов любым незаконным способом, сделать человека со знанием Силк'тажра, поговорить на нем.
#### Дополнительная информация:
Отсутствует.

**Comment by Avatar4** [comment]
Тогда еще уберите возможность таярам говорить на своем языке в радио. Или искаженным его что ли сделайте.

**Comment by dearprincesscelestia** [comment]
Он искажается по радио.

**Comment by igigin** [comment]
Убрать таяр. Я всё верно понял?

**Comment by skvazarb** [comment]
Неправильно. Убрать всех ксеносов.

**Comment by dearprincesscelestia** [comment]
Вот теперь правильно.

**Comment by Skippeer12** [comment]
Уже не могут. Закрывайте.
