### ISSUE TITLE
Алиумы.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1071]
#### Подробное описание проблемы
1) Трава не распространяется под разные объекты типа столов, шкафов, обычных дверей и некоторых тайлов на которых стоит одностороннее стекло.
2) Если грабать животных, то на втором грабе они дропаются и невозможно их проглотить (а еще спрайт квины после этого отъезжал).
3) Если посадить траву на строение алиумов (лежанку или двери), то их не будет видно.
4) Нельзя самому брать неигровых лицехватов что бы всаживать в лицо.
5) Хуманы которые кравлят под резиной - фактически невидимы.
#### Что должно было произойти
1) Трава должна распространяться везде кроме стен и цельных стекол (или сделать как раньше что бы на стены тоже).
2) Животных должна быть возможность сожрать.
3) Объекты должны быть видны не зависимо от травы.
4) Алиумы должны иметь возможность хватать лицехватов.
5) Посадить резины и лежанки и покравлить под ними.
#### Дополнительная информация:
Играл за квину.

**Comment by Kurshan** [comment]
И ещё немного инфы.
Если алиумская дверь на GLOVING WEED. спрайт теряется.
GLOVING WEED не GLOVING.
Задержка у хантеров просто критически малая, делая их просто неубиваемые за счет мобильности.
У Квины нет возможности заюзать консоли вызовов шаттла (того же майнинга).
Столы! Хуманы беззащитны против алиенов, даже если попытаются сделать укрепления, то поймут всю тщетность бытия, когда очередной ксенос просто пройдёт сквозь или же просто одним кликом удалит стол. На маринадах этот вопрос решался добавлением АШПИ столам.

**Comment by Lancer411** [comment]
1) Не хватает прогресс-баров на этапе заражения.
2) Не хватает прогресс-бара на этапе взросления ларвы.
3)  Процесс заражения крайне длительный, его бы ускорить раза в два. Так как нужно чтобы цель была обездвижена, ее вряд-ли успеют спасти и хирургия не поможет при заражении.
4) Возможно не хватает способа заражить людей напрямую. Нужно чтобы лицехваты могли по старинке использоваться как метательное оружие.
5) Можно за ларву прибаклить себя и больше не встать.
6) Можно выкинуть кнопку действия "кусать" будучи ларвой в теле жертвы, потеряв возможность выбраться наружу.

**Comment by Raschert0** [comment]
Ещё не помешало бы добавить возможность сентинелам изменять направление полёта в космосе путём выстреливания нейротоксином.

**Comment by Avatar4** [comment]
Еще забыл: Кнопка для отпускания пула отсутствует.
За королеву я мог управлять в космосе с помощью нейротоксина (хотя пришлось раза 3 выстрелить). У тебя скорее было дело в том, что сила разгермы не давала тебе полететь назад. Тоже самое с космонавтиками спустившими себя в шлюз и кидающими предметами но все равно улетают в спейс.

**Comment by SpaiR** [comment]
**ОДИН**, СУКА, РЕПОРТ - **ОДИН** БАГ
Серьёзно, такие репорты не удобно фиксить, просматривать, ссылаться, закрывать. Если знаешь несколько багов, но которые объекденены одной темой, то можешь их несколько штук подряд зарепортить и вставить, например, [ALIEN]. Сборная солянка не нужна.
