### ISSUE TITLE
Дрель

### ISSUE THREAD

**Issue by DarkFurrSss** [TauCetiStation/TauCetiClassic#10727]
#### Подробное описание проблемы
Дрель в режиме "Ключ" не выполняет свою работу при сборке меха
#### Что должно было произойти
Дрель-"Ключ" должен закрутить в самом начале детали меха
#### Что произошло на самом деле
Не закрутил
#### Как повторить
Начать собирать меха и попытаться скрутить детали дрелью в режиме "Ключ"
#### Дополнительная информация:
В остальных работах дрель работает куда медленнее первоначальных инструментов, Мб это и фича
Issue reported from  Round ID: 57486 (Tau Ceti Classic (RU))
Testmerges: ```#10496 #10436 #8435 ```
Reporting client version: 514.1589

**Comment by DarkFurrSss** [comment]
Дополню - вообще не может ручная дрель участвовать в сборке меха, как и "Клешни жизни"

**Comment by LudwigVonChesterfield** [comment]
#10702

**Comment by Mercurialaste** [comment]
Аэаааэ… Ладно, в любом случае думал через свитч сделать. Странно что не рабоает.

**Comment by Mercurialaste** [comment]
```
list("key"=/obj/item/weapon/weldingtool,
							"backkey"=/obj/item/weapon/wrench,
							"desc"="External armor is wrenched."),
					 //2
					 list("key"=/obj/item/weapon/wrench,
					 		"backkey"=/obj/item/weapon/crowbar,
					 		"desc"="External armor is installed."),
					 //3
					 list("key"=/obj/item/mecha_parts/part/durand_armour,
					 		"backkey"=/obj/item/weapon/weldingtool,
					 		"desc"="Internal armor is welded."),
					 //4
					 list("key"=/obj/item/weapon/weldingtool,
					 		"backkey"=/obj/item/weapon/wrench,
					 		"desc"="Internal armor is wrenched"),
					 //5
					 list("key"=/obj/item/weapon/wrench,
					 		"backkey"=/obj/item/weapon/crowbar,
					 		"desc"="Internal armor is installed"),
					 //6
					 list("key"=/obj/item/stack/sheet/metal,
					 		"backkey"=/obj/item/weapon/screwdriver,
					 		"desc"="Advanced capacitor is secured"),
	```
