### ISSUE TITLE
Не выполняются действия

### ISSUE THREAD

**Issue by Elite1323** [TauCetiStation/TauCetiClassic#10731]
#### Подробное описание проблемы
При игре не выполняются действия с пингом в 49  не поднимаются предметы , когда я был на блобе я перенес ядро и проверил 2 раза что я его перенес на 100%  после того как сломали мое прошлое меня выкинуло в госты

#### Что должно было произойти
При перенесении ядра и разрушения старого тебя не должно ,,убивать,,

#### Что произошло на самом деле
Убило и выкинуло в госты.

#### Как повторить
-

#### Дополнительная информация:
Issue reported from  Round ID: 57499 (Tau Ceti Classic (RU))
Testmerges: ```#10496 #10436 #8435 ```
Reporting client version: 514.1589

**Comment by KIBORG04** [comment]
че
