### ISSUE TITLE
Исчез мгновенный респавн у жертв генокрадов

### ISSUE THREAD

**Issue by Leprekeoner** [TauCetiStation/TauCetiClassic#10743]
#### Подробное описание проблемы
-
#### Что должно было произойти
мгновенный респавн
#### Что произошло на самом деле
нету
#### Как повторить
-
#### Дополнительная информация:
-

**Comment by KIBORG04** [comment]
А должен быть?

**Comment by Leprekeoner** [comment]
раньше был

**Comment by KIBORG04** [comment]
Мгновенный респавн ни у кого не должен быть. Где есть - баг.
