### ISSUE TITLE
Дюп ресурсов через голодек

### ISSUE THREAD

**Issue by INwirstD** [TauCetiStation/TauCetiClassic#10750]
#### Подробное описание проблемы
Активируя голодек, можно бесконечно собирать дерево и металл, если ломать объекты. Перезапускаем голодек и снова фармим ресурсы.
#### Что должно было произойти
Объекты в голодеке не настоящие
#### Что произошло на самом деле
Можно бесконечно дюпать металл, дерево.
#### Как повторить
Активировать любую голограмму с объектами в голодеке и ломать столы\стулья\деревья, например, топором или горелкой
#### Дополнительная информация:
Issue reported from  Round ID: 57558 (Tau Ceti Classic II (RU))
Testmerges: ```#10496 #10436 #8435 ```
Reporting client version: 514.1589

**Comment by volas** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/9640
