### ISSUE TITLE
Сломаны размеры предметов

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#10757]
#### Подробное описание проблемы
Сломались толи размеры анализатора и пульверизатора, толи ещё что-то.
#### Что должно было произойти
Анализатор можно положить в тулбелт, пульверизатор в рюкзак
#### Что произошло на самом деле
Ни анализатор, ни пульверизатор не лезут даже в Bag of Holding

**Comment by Mercurialaste** [comment]
Название предметов…

**Comment by F0xiq** [comment]
Analyzer, Space Cleaner

**Comment by F0xiq** [comment]
Вероятно тут всё и сломалось #10568 из-за нового флага CANT_BE_INSERTED

**Comment by Mintt69** [comment]
> 

syringe

**Comment by simb11** [comment]
пофиксил, после обновления сервера всё должно работать как надо

**Comment by F0xiq** [comment]
Да, больше проблем не замечено
