### ISSUE TITLE
Сканера

### ISSUE THREAD

**Issue by DarkFurrSss** [TauCetiStation/TauCetiClassic#10759]
#### Подробное описание проблемы
Сканер не лезет в рюкзак и в пояс с инструментами
#### Что должно было произойти
он должен был туда влезть (Хотя бы в сумку, размер tiny)
#### Что произошло на самом деле
Не лезет
#### Как повторить
Попытаться убрать сканер воздуха в сумку/пояс
#### Дополнительная информация:
Еще слышал что такое же со шприцами и ремнями медиков
Issue reported from  Round ID: 57594 (Tau Ceti Classic (RU))
Testmerges: ```#10568 #10436 #8435 ```
Reporting client version: 514.1589

**Comment by DarkFurrSss** [comment]
The scientist satchel cannot hold the analyzer.
The tool-belt cannot hold the analyzer.
а в карман лезет как влитой

**Comment by Mercurialaste** [comment]
Бля… Почему ночью все ломается… Ещё днем все было норм.

**Comment by DarkFurrSss** [comment]
И судя по всему многое так поломалось

**Comment by LoTaRk-FroG** [comment]
#10757 можно закрывать.
