### ISSUE TITLE
[Proposal] Реворкнуть Телесало

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#10763]
Телесало. Зачем нужны эти формулки, когда каждый третий кодер сделал калькулятор? Зачем нужно тратить время на повторения одной и той же фигни с калькулятором из раунда в раунд, когда интерес в том как ты заюзаешь портал, а не как ты его откроешь?

Предлагаю:
- Убрать фигню с формулками, в интерфейса просто можно вписать координаты куда нужен портал.
- Заставить телесало жрать ещё большее энергии, как компенсацию во-первых, а во-вторых для возможного побуждения завлекания игроков в игровую ситуацию "ученый сожрал всё электричество".
- Калибрацию порталов завязать на научные очки, к примеру. После каждых трёх полётов необходима калибровка. Калибровка означает что будешь попадать в пределах 1 блока, но если доплатишь ещё научных очков, то на 1 запуск будешь без погрешностей.

**Comment by Mercurialaste** [comment]
Без двигателя, телесало и так жрет много.

Упростить телесало для геймплея, а не дроча, круто.

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-duhoty-telenauki-i-varianty-ispravleniya/40283/3

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/voprosy-k-administraczii/5430/1897

**Comment by LudwigVonChesterfield** [comment]
Ну телесало реворкнули, пускай и не как я хотел. Наверное закрою.
