### ISSUE TITLE
Десворды не разрушают

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#10767]
#### Подробное описание проблемы
Десворд больше не дамажит окружение (автоматы, машины, стекла, компы)
#### Что должно было произойти
Десворд выламывает стекла, шлюзы и автоматы.
#### Что произошло на самом деле
Десворд бьет как плюшевый меч.
#### Как повторить
Взять десворд и попытаться побить что-то.
#### Дополнительная информация:
Другие мили штуки ломают все как надо, десворд нарубает людей также как и раньше. Симбака наделал делов.

**Comment by Deahaka** [comment]
Всё двуручное оружие перестало наносить урон. Виновники уже оповещены.
