### ISSUE TITLE
[Proposal] Дать всем игрокам админку

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#10765]
#### Подробное описание проблемы
Если у всех будет админка и каждый может друг друга забанить, то все будут вести себя хорошо и прилежно. Будет доброта, а все мудаки друг друга перебанят.

**Comment by LudwigVonChesterfield** [comment]
контрпропозал: забрать админку у всех

**Comment by Venngedi** [comment]
Мне на это число страшно даже смотреть. Прости, Киборг
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/3e2b84da-d431-41b1-b12c-5a2499c89d0d)

**Comment by KIBORG04** [comment]
Норм, закрыл 2 ПРа и теперь все типа ок!
