### ISSUE TITLE
В мусоре можно найти шадовлингские глаза

### ISSUE THREAD

**Issue by ghost** [TauCetiStation/TauCetiClassic#1077]
#### Подробное описание проблемы
Глаза тенелинга можно откопать в мусорной куче с одеждой
#### Что должно было произойти
Глаза тенелинга нельзя найти в мусоре
#### Что произошло на самом деле
Глаза шадовлинга можн найти в мусорке
#### Как повторить
Копать мусор, надеяться на лучшее
#### Дополнительная информация:
![12](https://cloud.githubusercontent.com/assets/20542000/22468422/6a5ec32e-e7f2-11e6-92d2-8a1baa5890ab.png)

**Comment by Skyrull** [comment]
А еще подтип без спрайта:
![default](https://cloud.githubusercontent.com/assets/20542000/22468631/363d1720-e7f3-11e6-99b2-4d2a4c18d9cc.png)

**Comment by Lancer411** [comment]
:+1:

**Comment by dearprincesscelestia** [comment]
Вынули глаза да выкинули, не баг.

**Comment by Avatar4** [comment]
А они светятся если надеть? Если да - то фичаж

**Comment by StrikS** [comment]
Антимета же, астафте

**Comment by RichardJones1** [comment]
Этого бага больше нет
