### ISSUE TITLE
[Proposal] ГрузТорг в Каждый Дом

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#10797]
ГрузТорг, он есть. Но им никто не пользуется, от части потому-что не знают.

Консоли заказов, они есть. Но ими пользуются в основном чтобы давать анонсы.

Предлагаю заменить консоли заказов на "консоли ГрузТорга", которые открывали бы ту же менюшку что и в ПДА. Прикол в том что про ПДА все знают и не думают в нём тыкать на новые кнопки, а так будет целая новая консолька в которую интересно как минимум один раз тыкнуть узнать зачем она нужна.

Очевидно механ анонсов надо куда-то перенести, и я предлагаю перенести его в кейкард девайсы которыми главы поднимают код до красного.

**Comment by DarthSidiousPalpatine** [comment]
Я бы предложил их удалить вообще, эти консольки. А анонсы бы передал в ПДА глав отдельной менюшкой.

**Comment by TryXAH** [comment]
Вообще, я гусеву предлагал свой механ с механом консолек как то подвязать, или просто консольки прокачать в что-то улучшенное, но ему консольки не нравятся, да

**Comment by PersyFOX** [comment]
Лучше бы консоль заказов самого карго в эти консоли запихнуть

**Comment by LudwigVonChesterfield** [comment]
Если будут консоли ГрузТорга консоль заказов карго внешнюю поменять на её. Пускай каргонцы заказывают товары для магазина и выставляют их...
