### ISSUE TITLE
Высасывание жизни и талисман

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#10794]
#### Подробное описание проблемы
Если засунуть в талисман культа ритуал высасывания жизни, при живом теле на активированном столе пыток, ничего не произойдет, может появится рантайм максимум.
#### Что должно было произойти
Живое тело на алтаре, высасывание жизни в талисмане — портативная хилка.
#### Что произошло на самом деле
Рантайм, урон, можно прожимать без кд вплоть до собственного крита/смерти. 
#### Как повторить
Засунуть в талисман ритуал по высасыванию жизни, положить живое тело на алтарь.
#### Дополнительная информация:
—

**Comment by LoTaRk-FroG** [comment]
#10112
