### ISSUE TITLE
Линзы СПУ не чинятся

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#10809]
#### Подробное описание проблемы
Камеры (линзы) спу не чинятся специальной операцией.
#### Что должно было произойти
Ура ремонт.
#### Что произошло на самом деле
Откручиваешь панель камер, чинишь камеры, а затем, вместо закрутки панели, панель начинает опять откручиваться и камеры не чинятся.
#### Как повторить
Попробовать починить слепого СПУ.

**Comment by pro100kotah** [comment]
Там с починкой СПУ вообще полный пиздец. Нужно как-то заняться этим с головой. Ибо компоненты в груди чинятся через раз и не чинятся нанопастой.

**Comment by LoTaRk-FroG** [comment]
> Там с починкой СПУ вообще полный пиздец. Нужно как-то заняться этим с головой. Ибо компоненты в груди чинятся через раз и не чинятся нанопастой.

Всё остальное вроде норм работает.
