### ISSUE TITLE
Конструкты, которым не за чем жить

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#10824]
#### Подробное описание проблемы
У конструктов, что появляются как замена обычной аномалии на портал, нет цели существования. 
#### Что должно было произойти
Цель есть и ради этой цели выбираются методы и средства.
#### Что произошло на самом деле
Цели нет. Делай что хочешь, но если убьешь мимокрокодилов или будешь убивать по своей инициативе в больших количествах, получишь бан.
#### Как повторить
Зайти как конструкт культа из аномалии и начать убивать.

#### Дополнительная информация:

Issue reported from  Round ID: 57763 (Tau Ceti Classic (RU))
Testmerges: ```#10779 #10699 #10568 #10436 ```
Reporting client version: 514.1589

**Comment by DarkFurrSss** [comment]
Ну в некоторой степени это открывает возможности действовать по желанию. Или резать/бить, или в мирную общаться. А вот про наказание за действия конструктом странно...

**Comment by KIBORG04** [comment]
И где тут баг? То что вас забанили за гриф всех на станции и всей станции впринципе оправдано. Сделай пропосал лучше и напиши свои идеи как это исправить
