### ISSUE TITLE
Инструменты, армблейд, харм и борги.

### ISSUE THREAD

**Issue by Afavertov** [TauCetiStation/TauCetiClassic#10826]
#### Подробное описание проблемы
Если пытаться застукать борга инструментом на харме(включенная сварка, лом и т.д), то ему будет побоку. Ты будешь пытаться ЧИНИТЬ борга. На харме. Особый абсурд это приобретает, когда у тебя в руках лопата или легендарная финка-НКВД от генокрадских мастеров. Они оба считаются ломами и в итоге борга ФИЗИЧЕСКИ нельзя даже тронуть армблейдом. Ну вот никак, хоть усрись, ведь "The cover is locked and cannot be opened".

#### Что должно было произойти
Инструменты на хелпе - помогают боргику. На харме - ломают боргика.

#### Что произошло на самом деле
Инструменты на хелпе - помогают боргику. Инструменты на харме - помогают боргику.

#### Как повторить
Попытаться постукать борга армблейдом или инструментом.

**Comment by AzzyDreemurr13** [comment]
ахаха, я даже не знали о фиче, теперь знаем, синткооплобби благодарит
