### ISSUE TITLE
заблокированный кодовый сейф открывается альт-кликом

### ISSUE THREAD

**Issue by muWander** [TauCetiStation/TauCetiClassic#10845]
#### Подробное описание проблемы
alt + клик на настенный кодовый сейф (как за картиной у капитана, в кабинетах глав етц) открывает его инвентарь и позволяет взаимодействовать с содержимым, забирать/класть вещи даже если сейф заперт
#### Дополнительная информация:
перетаскивание не забаговано

**Comment by Naroke** [comment]
Закрывайте

Исправлено в #13914
