### ISSUE TITLE
ГП Борг, или баги о которых никто не догадывался до игры как ГП борг на сервис модуле

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#10846]
#### Подробное описание проблемы
1) Факс и Борг
ГП Борг умеет писать Факсы на цк и всё такое.

2) Выдача доступа на ГП Борге (ака сервис модуль)

По какой-то причине если ты Борг или ИИ ты доступ можешь выдавать по 1й кнопке, то есть ты не можешь как ГП прокликать 6 кнопочек чтобы выдать полный доступ не меняя профу. А приходится каждый выдавать отдельно доступ.

#### Что должно было произойти
1) Факс
Засунуть отчёт в факс, вставить карту капитана или другого либо Главы. Отправить факс. Вытащить бумажку из факса

2) Выдача доступа 
Вставить Карту ГП или Капитана

На ИИ или Борге есть кнопки выдачи доступа на весь отдел как если бы это делал ГП 

#### Что произошло на самом деле
1)Факс
Никто не рассчитывал увидеть ГП Борга, но оказалось что он не может по какой-то причине из факса вытащить вставленную бумажку, в итоге если писать отчёты часто, то без человека все 3 факса на станции забиты бумагой :bad: 

2) Выдача Доступа 
Приходится тыкать каждую по 1-й или выдать сразу должность Кэпа.

#### Как повторить

1) Факс
Сервисный модуль, взять карту капитана или другого главы, сделать отчёт, вставить карту и отчёт в факс, отправить и достать карту, но не достать бумагу от туда 

2) Выдача Доступов
Выше сказано

**Comment by DarkFurrSss** [comment]
Как плюшка - борг может еще аннонсы делать. Раньше любил боргом ГПшить

**Comment by Mercurialaste** [comment]
А где баг?

**Comment by AzzyDreemurr13** [comment]
> А где баг?

Прости за слова, Мерк не тупи, я выписал 2 бага связанные с этим боргом,  попробуй на локалке или сандбоксе так сделать

**Comment by Mercurialaste** [comment]
Ну, а баг где?

**Comment by DarkFurrSss** [comment]
> Ну, а баг где?

(Даже мне не понятно, это шутка с попыткой придраться, или реальное непонимание)

Борг не может вынуть бумажку из факса (Странно, я вроде вынимал) + отсутствие скиллов на... Ну, командования
