### ISSUE TITLE
Очень нужно обновить NanoUI

### ISSUE THREAD

**Issue by StrikS** [TauCetiStation/TauCetiClassic#1085]
#### Подробное описание проблемы
http://imgur.com/a/7lrB8 It's awesome

#### Дополнительная информация:
https://github.com/PolarisSS13/Polaris/pull/2218

**Comment by StrikS** [comment]
Нит, я к этому не готов. Нужен ветеран кода. Игил пора и тебе сделать фичу, а не нерф.

**Comment by Raschert0** [comment]
Кто предложил, тот и делает :3

**Comment by StrikS** [comment]
Нет, ты!

**Comment by ZVee** [comment]
[Стоит все таки передумать](https://github.com/tgstation/tgstation/issues/16702), (по сей день ругаюсь на то, что притащили гунчат). В итоге похерим билд совсем и даже никакая оптимизация не спасет. Это как на какой-нибудь там скайрим, фол, ксп или еще что из такого - натянуть модов под 400 и плеваться что оно все ужасно работает. Может вот [тут](https://github.com/d3athrow/vgstation13/issues/11221) что-нибудь сообразят, но там пока тихо.
