### ISSUE TITLE
Тулбокс замедляет юзера! 

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#10852]
#### Подробное описание проблемы
Тулбокс после обновлений стал замедлять юзера хуже чем что угодно.
#### Что должно было произойти
Легендарное оружие ассистентов не мешает воевать
#### Что произошло на самом деле
Человек с тулбоксом = черепаха
#### Как повторить
Зайти на сервер

**Comment by pro100kotah** [comment]
Гений!

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-golosovanie-tulboksnye-vojny-vozvrashhenie-dzhedaya-pr-na-podhode/39266/1
