### ISSUE TITLE
в с20р не вставляются магазины с особыми пулями

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#10866]
#### Подробное описание проблемы
в с20р не заряжаются магазины с ХП, ХВ и ИМП пулями
#### Что должно было произойти
всё ок
#### Что произошло на самом деле
всё не ок
#### Как повторить
попытаться вставить magazine (.45 HV) в с20р

**Comment by AndroBetel** [comment]
факин щит
