### ISSUE TITLE
Ручка синди

### ISSUE THREAD

**Issue by DarkFurrSss** [TauCetiStation/TauCetiClassic#10886]
#### Подробное описание проблемы
Боргов нельзя бить ручкой-ножом синди
#### Что должно было произойти
удар
#### Что произошло на самом деле
нема
#### Как повторить
ударить борга
#### Дополнительная информация:
Обожаю сливаться из-за багов

Issue reported from  Round ID: 57896 (Tau Ceti Classic (RU))
Testmerges: ```#10779 #10661 #10659 #9410 ```
Reporting client version: 514.1589

**Comment by Chip11-n** [comment]
Сюда же топоры с их способностью к открыванию люков боргам.
