### ISSUE TITLE
Баны ролей антагонистов оказывают влияние на роли не антагонистов

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#10881]
#### Подробное описание проблемы
Бан на антагов, также банит дронов и мышей.
#### Что должно было произойти
Не банит.
#### Что произошло на самом деле
Банит.
#### Как повторить
Получить бан на антагов.
#### Дополнительная информация:
Issue reported from  Round ID: 57882 (Tau Ceti Classic (RU))
Testmerges: ```#10779 #10661 #10659 #9410 ```
Reporting client version: 514.1589

**Comment by KIBORG04** [comment]
фича
