### ISSUE TITLE
GONNA DROP ALL IN 11 SEC'Z!

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#1089]
#### Подробное описание проблемы
Представьте как это https://i.gyazo.com/add47ab08da69d9673b99dcd1eb36619.png
или даже это https://i.gyazo.com/fc071b24413867470af0e582ee39863a.png

В реалиях нашей очень реалистичной, очень роял плейной станции, все эти технологические чуда можно снять... за 11 секунд (вместе с трусами).

#### Что должно было произойти
Ну не знаю, со скорость движения рук в 0,16 м/с человеку должно просто сломать кисти рук или в локтях... нахуй.
#### Что произошло на самом деле
Руки как и сами космонавты остаются целыми! 
Спецназовец олдскульного дедсада полностью одеватся за 46 секунд (если мы будем игнорировать, то что он надевает трусы в конце, а шлем в начале). 
На то чтобы надеть и снять риг/скафандр обычному юзеру требуется 10 с. 
Если же снимает кто-то другой то на ВСЮ одежду уходит 11 с. на скафандр 1,75-2 с.

И того разница между одеванием и сторонним раздеванием составляет 76.09%
https://www.youtube.com/watch?v=2uh2YSqsFU0
#### Как повторить
Провести опыты описанные выше, использовать листок бумаги, карандаш и таймер.

#### Дополнительная информация:
Я предлагаю радикально бороться с этим недоразумением, а именно портировать с ТГ систему раздевания кукл.

**Comment by Skippeer12** [comment]
Сначала добавили возможности спастить от разгермы, распихав по всей станции скафандры.

А теперь будем нерфить скорость их нацепления на тушку.

Нерфоцирк ещё никогда небыл таким забавным.

На скринах то эксо-скелетный скафандр из Мертвого Космоса.


Если нерфить, так давайте сделаем так, чтобы без помощи ###  кооп дружка нацепить его нельзя было.

**Comment by ZVee** [comment]
Шкиппер видимо любит, когда с него вещи лысый снимает раз в 10 быстрее, чем если Шкиппер это будет делать сам с себя :D

**Comment by ZVee** [comment]
Осторожно! Стена текста ожидает вас ниже, гражадане!

Ладно, не буду ждать дальнейшего развития - на самом деле тут у нас пример того, как не стоит репортить баги или составлять реквесты.
Содержание рассчитано явно не на широкую публику, а может это просто мои заморочки, но лично я понял примерно спустя час и серьезно ситуацию спасла доп. инфа - без нее наверно по сей час для меня этот реквест оставался бы загадкой и считаю, что на самом деле - все кроме доп. инфы можно удалить и будет в разы понятнее.
В первую очередь, надо составлять во имя понятности для всех и в особенности думать о том, чтобы "кодерам" которые за это возьмутся за просьбу/баг репорт - было понятно что делать (а то они такие, могут таааакое накодить если поймут как-то по своему), а уж потом добавлять юмор, если он уместен.
Подводя итог - Шкиппер подумал что речь идет про надевание/снимание предметов с себя, а я (зве наверно тупой) вообще ничего не понял изначально, и наверно еще есть или будут люди за кадром.

В общем перевожу как сам понял - речь идет про раздевание **чужих** кукол посредством меню-списка (инвентарь), когда мы можем прокликать каждый слот со скоростью которую позволит интернет/руки и раздеть полностью одетого игрока за менее чем "11" секунд исхода из описания (но истину расскажет только сам Вальтер - если мой перевод окажется таки неверен).

**Comment by WatlerJe** [comment]
Еще раз, для особо тупых: 
Ты надеваешь скафандр/риг на СВОЮ куклу за 10 секунд ровно, но с твой куклы другой игрок снимает этот же самый скафандр за 2 секунды.

Да Зве, ты все понял правильно, просто в дальнейшем всяких Шкипперов не слушай.

**Comment by RichardJones1** [comment]
Нужен фидбек

**Comment by Sakuya-Izayoi** [comment]
Не нужен

**Comment by EdlerN** [comment]
Да какой вам фидбек? Снять трусы через риг в условиях открытого космоса за 10 секунд? Да легче легкого! Только никто никак не притянет какую-нибудь вменяемую систему сюда.
