### ISSUE TITLE
Fatboy slim and bootz in tail!

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#1091]
#### Подробное описание проблемы
Слои и спрайты шмоток:

Проблема слоев у жирных кукол, правая/левая рука видна сквозь пузо:
https://i.gyazo.com/a96c6828ef6ae7f3a4913b6de9880e28.png
(Так же видны куски мяса)
Новые хвосты у лизардов стали толще и ниже, но теперь обувь с высоким берцем накладывается поверх хвоста:
https://i.gyazo.com/720243267229062f4be7a030948fdd22.png
https://i.gyazo.com/4fee2506eee13f8e187e9021f89707b5.png
https://i.gyazo.com/5b498c03bed979486d812f10eff8d869.png

Апдейт уборщика прошел, но форму жирным забыли запилить, обычный вариант использует старый спрайт, кэжуал вариант юзает новый:
https://gyazo.com/92941f1ed8ee7887080904fc73121746

#### Что должно было произойти
Все должно смотреться элегантно и эстетично.

#### Что произошло на самом деле
Читай выше.

#### Как повторить
Написать квенту на лизарда
отстоять в очереди на прием месяц
убедится что твои литературные навыки полное гавно
получить вайт на ксеноса, зайти в эСэС на Тау Сети
потратить два часа на создание чара и заполнение рекордсов
войти в игру за уборщика с дефолтной жирнотой
попробовать надеть обрезанные воркбуты, джекбуты или даже калоши. 
@ https://www.youtube.com/watch?v=OGp9P6QvMjY

#### Дополнительная информация:
Наверное всему виной механ сборки кукол из частей тела. Надо это фиксить ибо при отрезании рук/ног, на спрайтах кукл в профиль, все выглядит еще хуже.

**Comment by dearprincesscelestia** [comment]
> Наверное всему виной механ сборки кукол из частей тела. Надо это фиксить ибо при отрезании рук/ног, на спрайтах кукл в профиль, все выглядит еще хуже.

Да. Респрайт хуманов когда?

**Comment by WatlerJe** [comment]
Если респрайтить кукол, то респрайтить всю одежду, снарягу и вообще много-много работы. Если у тебя есть идеи как и во что переделать хуманов, то предлагай, попробуем.

**Comment by dearprincesscelestia** [comment]
Ну так все то же: сначала грохнуть весь тот флаффовый и неиспользуемый никогда, даже в хваленых ивентах, хлам. И на этом этапе загвоздка, хех.

**Comment by WatlerJe** [comment]
Теперь же флаф можно раскопать и обмазаться гавном которого нету у других.

**Comment by dearprincesscelestia** [comment]
Ага. При этом Монтелесто ругается как сапожник, когда убирает хардкодом флафф без спрайтов в исключения, потому что его тоже дофига.

**Comment by Avatar4** [comment]
А на трапо-таярах "закатание" униформы уборщика выглядит так, будто расстегнут воротник и видно лифак. Но мне нравится.

**Comment by dearprincesscelestia** [comment]
Зачем тоерам белье?

**Comment by RichardJones1** [comment]
Да, это та ещё проблема

**Comment by RichardJones1** [comment]
Я пересмотрел ишью - баг с хвостом и ботинками пофиксили, с униформой тоже, а баг с отображением сбоку есть в других ишью
