### ISSUE TITLE
Монстры научились бить на расстояние.

### ISSUE THREAD

**Issue by DarkDragos** [TauCetiStation/TauCetiClassic#10912]
#### Подробное описание проблемы
Все враждебные НПС монстры при нападение бьют на расстояние слабым уроном.
#### Что должно было произойти
Монстры ближнего боя не бьют на расстояние.
#### Что произошло на самом деле
Монстры ближнего боя бьет на расстояние.
#### Как повторить
Заставить напасть на себя любого монстра ближнего боя.

**Comment by KIBORG04** [comment]
вроде уже пофикшено ждите рестарт
