### ISSUE TITLE
Интенты борга меняются вместе с выбором манипулятора, через кнопки "1,2,3".

### ISSUE THREAD

**Issue by DarkFurrSss** [TauCetiStation/TauCetiClassic#10928]
#### Подробное описание проблемы
Интенты боргов зависят от клавиш 1 2 3 как и выбор "руки"
#### Что должно было произойти
не меняется интент
#### Что произошло на самом деле
меняется
#### Как повторить
быть боргом и МиНяТь РуКи

**Comment by DarkFurrSss** [comment]
> у меня не переключаются ![proof](https://camo.githubusercontent.com/4eaac54ec2ac767df139eef1a63f3114ae3d48879881a6b90036f7a483b80005/68747470733a2f2f63646e2e75706c6f61642e73797374656d732f75706c6f6164732f6874384f3979716c2e676966) [ ![proof](https://camo.githubusercontent.com/4eaac54ec2ac767df139eef1a63f3114ae3d48879881a6b90036f7a483b80005/68747470733a2f2f63646e2e75706c6f61642e73797374656d732f75706c6f6164732f6874384f3979716c2e676966) ](https://camo.githubusercontent.com/4eaac54ec2ac767df139eef1a63f3114ae3d48879881a6b90036f7a483b80005/68747470733a2f2f63646e2e75706c6f61642e73797374656d732f75706c6f6164732f6874384f3979716c2e676966) [ ](https://camo.githubusercontent.com/4eaac54ec2ac767df139eef1a63f3114ae3d48879881a6b90036f7a483b80005/68747470733a2f2f63646e2e75706c6f61642e73797374656d732f75706c6f6164732f6874384f3979716c2e676966)

хм... Это было раунд назад на первом. Мб я прожал какую то комбинация клавиш... Т.к. попутно не мог взаимодействовать со включенным крио медотсека

**Comment by NikMaestro** [comment]
Нормальный же нёрф, зачем убирать фичу

**Comment by DarkFurrSss** [comment]
сейчас снова подобная проблема, и это не сочетание клавиш...

**Comment by DarkFurrSss** [comment]
Это происходит каждый раунд и жутко бесит. Спросил в менторку, с таким багом и остальные некоторые бегают

**Comment by Deahaka** [comment]
4-кой меняются интенты. Мдааа и это менторы? Разогнать всех нахрен

**Comment by kalazus** [comment]
Просто снимите с боргов хоткеи на выбор рук. Их можно спокойно менять на x и shift-x. Это нормально не починить, так как хоткеи выбора интента теперь у мобов.

**Comment by LudwigVonChesterfield** [comment]
Если делать как сказать @kalazus то заодно пожалуйста почините что если иметь 3 предмета в трее, и дроппнуть второй предмет, то переключение на X/Shift X не работает

**Comment by DarkFurrSss** [comment]
> 4-кой меняются интенты. Мдааа и это менторы? Разогнать всех нахрен

как бы и 1 и 2 и 3 меняются. Вместе с набором вещей, и я это написал
![image](https://user-images.githubusercontent.com/92409383/224826379-601c1b3d-0238-46c9-92fd-0a0620665f74.png)

**Comment by DarkFurrSss** [comment]
А вот и меняются...

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-dlya-ohrenitelnyh-idej/3470/6140
