### ISSUE TITLE
Не работают голосования.

### ISSUE THREAD

**Issue by INwirstD** [TauCetiStation/TauCetiClassic#10970]
#### Подробное описание проблемы
Любые голосования не работают. Кнопки вызова не кликабельны.
#### Что должно было произойти
Можно вызвать голосование
#### Что произошло на самом деле
Кнопки в окне с vote не нажимаются 
#### Дополнительная информация:
Issue reported from  Round ID: 58095 (Tau Ceti Classic (RU))
Testmerges: ```#10868 #10659 ```
Reporting client version: 514.1589

**Comment by DarkFurrSss** [comment]
> Я скоро пойду выпиливаться

Не выпиливайся, пили других.
Там таймер на голосование не прошел?
