### ISSUE TITLE
Двойной есворд из катсолов пиратов.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1098]
#### Подробное описание проблемы
Можно сделать двойной триторский есворд из катлосов пиратов
#### Что должно было произойти
Пираты не должны уметь делать двойные мечи из сабель.
#### Что произошло на самом деле
Они могут
#### Как повторить
Взять две сабли и соединить в одну. (спрайт есворда прилагается)
#### Дополнительная информация:
Куршан почини!

**Comment by StrikS** [comment]
Просто оставлю это тут, фор фан. 
http://ru.starwars.wikia.com/wiki/Парные_световые_мечи

**Comment by Avatar4** [comment]
Я бы оставил как небольшую контр-меру против ебаных лазуров из окна. Жаль только против дробовиков мечи бесполезны абсолютно.

**Comment by dearprincesscelestia** [comment]
Лучше сделать специальный двойной етаган.

**Comment by WallShrabnic** [comment]
Не баг, а фича
