### ISSUE TITLE
Пилоны?

### ISSUE THREAD

**Issue by arygal** [TauCetiStation/TauCetiClassic#10995]
#### Подробное описание проблемы
Раунд старт ивент на пилоны в техах не стреляет в упор. 
#### Что должно было произойти
Пиу пиу 
#### Что произошло на самом деле
The charged pylon nuzzles Curly Mens x3
#### Как повторить
Подойти к пилону в упор
#### Дополнительная информация:
Возможно связан с https://github.com/TauCetiStation/TauCetiClassic/issues/10985.

**Comment by KIBORG04** [comment]
Не связан. Вроде потому что у пилонов нет мили демеджа, и по задумке они должны всегда стрелять.
