### ISSUE TITLE
Патроны... Что?

### ISSUE THREAD

**Issue by DarkFurrSss** [TauCetiStation/TauCetiClassic#11012]
#### Подробное описание проблемы
Это патроны на глок. Первые два - резина, вторые - летал
![image](https://user-images.githubusercontent.com/92409383/225081709-b1d7a2b4-98a6-4fa0-970e-8a9c3c545c13.png)
Сами патроны, если вытащить, невидимы
#### Что должно было произойти
Нормальные магазины и патроны
#### Что произошло на самом деле
Уже описано
#### Как повторить
Играть в сс

**Comment by AndroBetel** [comment]
только что пофиксилось

**Comment by DarkFurrSss** [comment]
> только что пофиксилось

Нифига

**Comment by LudwigVonChesterfield** [comment]
#11011
