### ISSUE TITLE
Новый способ крашить людей!

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#11015]
#### Подробное описание проблемы
Новый способ крашить людям игру через бумажки.
#### Что должно было произойти
нет способа
#### Что произошло на самом деле
есть
#### Как повторить
[block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block][block] 
И так до посинения.
#### Дополнительная информация:
Issue reported from  Round ID: 58168 (Tau Ceti Classic (RU))
Testmerges: ```#10779 #10868 #10875 #10897 #10918 #10971 ```
Reporting client version: 514.1589

**Comment by volas** [comment]
От пермы тебя этот репорт уже не спасёт. Но если починишь bb-коды (см. в сторону https://github.com/TauCetiStation/TauCetiClassic/issues/10134), то может быть обойдешься лёгким испугом.

**Comment by Mercurialaste** [comment]
😭

**Comment by Mercurialaste** [comment]
> От пермы тебя этот репорт уже не спасёт. Но если починишь bb-коды (см. в сторону #10134), то может быть обойдешься лёгким испугом.

Мне приходило в голову просто поставить общее ограничение по символам, это ведь должно быть легче?...

**Comment by volas** [comment]
оно уже есть

**Comment by Mercurialaste** [comment]
Видимо, слишком большое "ограничение"?

**Comment by volas** [comment]
нет, и проблема не в нем...

**Comment by Mercurialaste** [comment]
😔
