### ISSUE TITLE
Смайлы в ИЦ

### ISSUE THREAD

**Issue by Shudyn** [TauCetiStation/TauCetiClassic#1102]
#### Подробное описание проблемы
Можно спамить смайлами In-character(ик)

#### Что должно было произойти
Смайлы не должны отображаться
#### Что произошло на самом деле
Смайлы отображаются. Люди говорят картинками.
#### Как повторить
Написать :смайлнейм: в чате в ик
#### Дополнительная информация:
StopThisAbusePls

**Comment by Raschert0** [comment]
Можно и гиперлинки в общий канал говорить. Но за это бан

**Comment by volas** [comment]
Аналогично со скобочками, кстати
