### ISSUE TITLE
[Bug] Не работает корзина Грузторга

### ISSUE THREAD

**Issue by Wizic** [TauCetiStation/TauCetiClassic#11042]
#### Подробное описание проблемы
При заказе товара появляется накладная, товар исчезает из списка вещей, но не добавляется в корзину. Покупатель не может разблокировать товар.
#### Что должно было произойти
Товар добавлен в корзину. Имеется возможность разблокировать посылку при вручении.
#### Что произошло на самом деле
Товар не добавлен в корзину. Не имеется возможность разблокировать посылку при вручении.
#### Как повторить
Заказать товар.
#### Дополнительная информация:
-

**Comment by DarthSidiousPalpatine** [comment]
Ясно не повторяется без доп. инфы. Ну кек, получается.
