### ISSUE TITLE
Разгерметизация или отсутствие кислорода в стеклянном коридоре между отсеками на аванпосте шахтеров.

### ISSUE THREAD

**Issue by Aritboy** [TauCetiStation/TauCetiClassic#11059]
#### Дополнительная информация:
Issue reported from  Round ID: 58221 (Tau Ceti Classic (RU))
Testmerges: ```#10979 #10978 #10918 #10876 #10875 ```
Reporting client version: 514.1589

Несколько раундом подряд появляется разгерметизация или отсутствие кислорода в стеклянном коридоре между отсеками на аванпосте шахтеров

**Comment by Pirsnya** [comment]
там кстати странно, что даже если через рестор эир пополнять, то он куда-то уходит, хотя дыр нет

**Comment by volas** [comment]
Пофикшено, со следующего раунда будет скорее всего на сервере

**Comment by kalazus** [comment]
> Пофикшено, со следующего раунда будет скорее всего на сервере

А пуш сделал? Изменений вроде не видно в пре.

**Comment by volas** [comment]
я докидываю другие патчи, сейчас закончу и поставлю обновление
