### ISSUE TITLE
Новые окна построены по-другому? 

### ISSUE THREAD

**Issue by NeOchenLord** [TauCetiStation/TauCetiClassic#11058]
#### Подробное описание проблемы

Новым окнам Вальтера похую что их разбили и они не создают разгерму.

#### Что должно было произойти

Окно разбилось. Воздух вышел. Аварийная створка закрылась.

#### Что произошло на самом деле

Окно разбилось. Воздух не вышел. Нет ни разгермы, ни атмосферной тревоги.

#### Как повторить

Сломать окно??

#### Дополнительная информация:

#58220

**Comment by volas** [comment]
fixed
