### ISSUE TITLE
Шаттл на астероид разгерметизирован

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#11055]
#### Подробное описание проблемы
Шаттл на астероид разгерметизирован, при открывании дверей воздух высасывается из прибытия
#### Что должно было произойти
На шаттле астероида есть атмосфера

**Comment by volas** [comment]
Пофикшено, было проблемой https://github.com/TauCetiStation/TauCetiClassic/pull/9501
