### ISSUE TITLE
/datum/browser не удаляется при закрытии окна.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#11068]
#### Подробное описание проблемы

Браузеры при закрытии окна должны удаляться, и чиститься из всяких списков. Но похоже нигде не вызывается Destroy браузера

#### Что должно было произойти

Браузер закрылся после нажатия на крестик, client.browsers очистился от айдишки браузера

#### Что произошло на самом деле

Окно закрыто но браузер остаётся висеть у клиента и ссылаться на него

#### Как повторить

1. Взять карго таггер
2. Открыть окно
3. Закрыть окно
4. View Variables -> client -> browsers
5. Убедиться что браузер не удалился.

#### Дополнительная информация:

![image](https://user-images.githubusercontent.com/17705613/226141220-ddc17719-dcd9-4f49-b0da-7f6fe6c57d81.png)

**Comment by LudwigVonChesterfield** [comment]
Возможно стоит заинвестигейтить `/proc/onclose` и необходимость его использования везде где эти браузеры открываются

**Comment by volas** [comment]
это тогда еще и проблема дестроя хьюманов (еще одна)
