### ISSUE TITLE
Окна на велосити можно открутить

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#11060]
#### Подробное описание проблемы
https://github.com/TauCetiStation/TauCetiClassic/pull/10978

![image](https://user-images.githubusercontent.com/26389417/226123814-77a3688f-b0a7-4b93-92f7-52313046c30d.png)

![image](https://user-images.githubusercontent.com/26389417/226123817-b71e2053-83b5-4122-9da9-6a184f0aef29.png)

#### Что должно было произойти
Игроки не проникают на цк

#### Что произошло на самом деле
Иргоки абузят

#### Как повторить
Если алгоритм не изменился, то отвертка+лом+отвертка

**Comment by SiveanBen** [comment]
Они просто нажатием лома удаляются, даже отвёртка не нужна

**Comment by SiveanBen** [comment]
Если у вас есть лом и способ жить в космосе то вы можете попасть на любой объект цк слоя. 
![image](https://user-images.githubusercontent.com/110115599/226131058-c52aff63-1d32-43cb-b080-b4869452d360.png)

**Comment by volas** [comment]
fixed in [`9a9cf28` (#10978)](https://github.com/TauCetiStation/TauCetiClassic/pull/10978/commits/9a9cf282419f32e4a06df6d77e85efb914b9592e)
