### ISSUE TITLE
Карго сломался;

### ISSUE THREAD

**Issue by QWxiZX** [TauCetiStation/TauCetiClassic#11065]
#### Подробное описание проблемы
Аккаунты не создались или каким-то образом удалились, я не знаю.
Но это привело в полную недееспособность карго и миллион, который у нас был, оказался неприменим.
Груз также перестал давать деньги.
Зарплаты при этом были в порядке.

Дополнительное предложение: создать систему, в которой можно привязать аккаунты к отделам, даже если они удалены каким-то образом.

![image](https://user-images.githubusercontent.com/70110199/226132627-1f8a43ef-babd-4bf7-a96b-9e2d6ba5dabc.png)
![image](https://user-images.githubusercontent.com/70110199/226132623-80c8d2d0-ff19-4756-9f9c-1637a0bc0467.png)

Как можно видеть, нет ни одного аккаунта НТ.

Причем, аккаунт NSS Exodus метафизически существует.
![image](https://user-images.githubusercontent.com/70110199/226133853-3aca7aa8-3236-470c-98bf-d1c56c5d8376.png)
И с него метафизически можно снимать деньги и начислять обратно с помощью создания новых аккаунтов.
#### Что должно было произойти
карго работает
#### Что произошло на самом деле
не
#### Как повторить
не знаю, смотрите реплей
#### Дополнительная информация:
Issue reported from  Round ID: 58225 (Tau Ceti Classic (RU))
Testmerges: ```#10979 #10978 #10918 #10876 #10875 ```
Reporting client version: 514.1583

**Comment by QWxiZX** [comment]
@LudwigVonChesterfield, раунд если что прямо сейчас идет, можешь сам зайти и глянуть.

**Comment by LudwigVonChesterfield** [comment]
это что-то очень мемное у меня такого на локалке с актуальным билдом нет...

будем считать что бьёнд глитч, космический бит флип...

**Comment by LudwigVonChesterfield** [comment]
мне говорили что ишуй ещё есть
