### ISSUE TITLE
Под новыми окнами не спавнится пол репликаторов

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#11064]
#### Подробное описание проблемы

если за репликатора разбирать новые окна - не появится форсфилд пол, будет космос. таким образом потенциально можно разгермить

#### Что должно было произойти

при разборе окна появляется форсфилд стена, при разборе турфа пол

#### Что произошло на самом деле

появилась стена но не пол

#### Как повторить

за репликатора разобрать стену

#### Дополнительная информация:

я ещё не чекал, но как я понимаю стёкла сделали турфами? если так то это объясняет почему не спавнится пол

**Comment by LudwigVonChesterfield** [comment]
#10978 

Это ломает баланс режим очень сильно.

**Comment by volas** [comment]
Не турфами, и я фиксил там конфликт после мержа https://github.com/TauCetiStation/TauCetiClassic/pull/10978/commits/0a06a53c6157984e042280e5b5df9d55abc994d8

ищу, где еще проблема
