### ISSUE TITLE
Новые окна убивают шахтеров

### ISSUE THREAD

**Issue by Slavik2001** [TauCetiStation/TauCetiClassic#11063]
#### Подробное описание проблемы
После введения новых окон нашел баг на аванпосте шахтеров, а именно в коридоре-переходе на вторую часть аванпоста
#### Что должно было произойти
Просто проходишь без каких либо проблем
#### Что произошло на самом деле
При открытии шлюза тебя сдувает, требует воздуха и давит давление
#### Как повторить
Зайти на шахтерский аванпост и открыть шлюзы в коридор на другую часть аванпоста
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/123300305/226125960-8eb14b7d-f27b-464c-8e07-8ab4fa37047e.png)
Issue reported from  Round ID: 58223 (Tau Ceti Classic (RU))
Testmerges: ```#10979 #10978 #10918 #10876 #10875 ```
Reporting client version: 514.1589

**Comment by volas** [comment]
fixed in [`4b3b9ba` (#10978)](https://github.com/TauCetiStation/TauCetiClassic/pull/10978/commits/4b3b9bad3a5884c5db0e530cad9a630147629c59)
