### ISSUE TITLE
Защитные двери и Шаттеры не показываются поверх из-за новых текстур стекл

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#11076]
#### Подробное описание проблемы
Шаттеры такие как у капитана, гп и так далее на новых окнах не отображаются поверх.

#### Что должно было произойти
Должны отображаться, а для ИИ не ломать синтетический мозг и понять закрыты они или нет.

#### Что произошло на самом деле

Можно понять только по свету ( смотрите внимательно)

(Офис Кэпа)
Так они открыты:
![image](https://user-images.githubusercontent.com/74739991/226178596-07e8bcca-de94-4653-b66e-b22bf0a9082b.png)
Так они закрыты:
![image](https://user-images.githubusercontent.com/74739991/226178565-2350d2f6-6190-4a9d-8175-f9eed8a57cc9.png)

(Офис ГП)
Открыты:
![image](https://user-images.githubusercontent.com/74739991/226178748-e9151997-f1fd-4168-b635-b40e692fe373.png)
Закрыты:
![image](https://user-images.githubusercontent.com/74739991/226178709-a4d7c49d-b853-4e86-a76f-dd2672e9acf5.png)

А также в Офисе АВД и Мостик

Мостик

Открыты:
![image](https://user-images.githubusercontent.com/74739991/226183492-d9c31026-09cd-4ace-ba57-73d55c4ee873.png)
Закрыты:
![image](https://user-images.githubusercontent.com/74739991/226183455-03e850e0-7686-48c0-9df5-096545510177.png)

АВДшная
Открыты:
![image](https://user-images.githubusercontent.com/74739991/226182594-8447d0e4-fd52-4078-a14f-b3f6a5d63149.png)

Закрыты:
![image](https://user-images.githubusercontent.com/74739991/226182562-5ff441a8-fdf3-4bba-9633-3d89ce78e47e.png)

#### Как повторить

Жмякать на кнопку закрыть/открыть шаттеры (в особенности если это делать на ИИ)

#### Дополнительная информация:
Раунд: #58239
![image](https://user-images.githubusercontent.com/74739991/226178794-a264b254-0782-47e7-ba78-43bdafcaf184.png)

**Comment by volas** [comment]
Если поднять фаеры над окнами, то в случае разгермы вся станция будет в скучных желтых дверях. Возможно нужны новые фаердоры, которые мы могли бы комфортно разместить над окнами, и которые бы не скрывал, что это окна...

Сейчас немного твикнул слои и прозрачность в [`df5ef9b` (#10978)](https://github.com/TauCetiStation/TauCetiClassic/pull/10978/commits/df5ef9b38d340e053fab4de95fefb11ec1035532)

![Скриншот 2023-03-19 18 59 01](https://user-images.githubusercontent.com/4064061/226188367-a8f2807a-0486-4774-bcf9-1993e4d88f9d.png)

**Comment by DarthSidiousPalpatine** [comment]
Имеджин сделать нормальное отображение оверлеев и слоёв окна, ставив шаттерсы над окном но под подоконником или просто под окном но над решёткой, эх...

**Comment by volas** [comment]
Под стеклом (как на скрине выше) оно странно смотрится с точки зрения физики. Но у нас и раньше так было, так что пока ок. 

Ну и не хотелось бы отменять работу по сокращению количества объектов и оверлеев.

**Comment by AzzyDreemurr13** [comment]
Ну так как фактически эту тему с горе пополам решили.. то могу сделать так
