### ISSUE TITLE
Смешной абуз счета ЦК

### ISSUE THREAD

**Issue by NinjaPikachuska** [TauCetiStation/TauCetiClassic#11077]
#### Подробное описание проблемы
С консоли ГП можно получить доступ к ЦК счету, на котором очень много денег
![image](https://user-images.githubusercontent.com/89906909/226185995-243da5e4-7849-4a7c-b4ca-600b78f0d623.png)
![image](https://user-images.githubusercontent.com/89906909/226186324-b8c24201-9e0e-442a-90b3-853743fcd758.png)

#### Что должно было произойти
Нормальный раунд с репликаторами
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/89906909/226186063-4ee435d1-fc42-43c5-b801-e8b3c0e9690b.png)
![image](https://user-images.githubusercontent.com/89906909/226186087-ae5f1242-71c4-4460-9b4d-8800e0fd9ed6.png)
![image](https://user-images.githubusercontent.com/89906909/226186140-4109e5d7-18e6-4d2a-9f23-185141a4326f.png)
#### Как повторить
Перевести все деньги со счета ЦК на счет станции, создать новый счет с этими деньгами.
#### Дополнительная информация:
Людук опять все сломал 😔

**Comment by QWxiZX** [comment]
Это я открыл! 
 _довольный собой улыбается_

**Comment by QWxiZX** [comment]
![image](https://user-images.githubusercontent.com/70110199/226186951-c1835dfc-079d-4d2b-b51f-0a254a84d426.png)
