### ISSUE TITLE
Сломана система насыщения

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#11098]
#### Подробное описание проблемы
Сломана система насыщения едой, можно обожраться едой до серого индикатора и минут через 5 насыщение сброситься до желтого
#### Что произошло на самом деле
Ешь как не в себя, толку никакого, постоянный голод
#### Как повторить
Сложно сказать как воспроизвести, подозреваю повторяется, если раундстартом сразу желтое насыщение.

**Comment by DarthSidiousPalpatine** [comment]
Просто теперь худеют даже когда просто стоят. По времени теперь голодными становятся, а не как раньше - от ходьбы или боли.

Ну и автор ПРа не рассчитал нормально. (Автор не я, не бейте)

**Comment by Deahaka** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/10922

**Comment by Deahaka** [comment]
За 30 минут полоска голода опустилась только с зелёного до жёлтого. Видимо проблема не в обновлении голода, а только в качках.

**Comment by Deahaka** [comment]
Вроде как не актуально
