### ISSUE TITLE
персонажи ОЧЕНЬ быстро голодают

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#11103]
#### Подробное описание проблемы
Куклы невероятно быстро голодают
#### Что должно было произойти
Куклы голодают с нормальной скорость
#### Что произошло на самом деле
Каждые 5 минут кукла просит еды
#### Как повторить
поиграйте на сервере я хз

**Comment by Deahaka** [comment]
Спросите Гусева. Он сказал вручную всё считал поэтому ошибок быть не может.

**Comment by DarthSidiousPalpatine** [comment]
> Спросите Гусева. Он сказал вручную всё считал поэтому ошибок быть не может.

чего блять, ЭТО НЕ МОЙ ПР, АЛО АЛО, Сам со своим детищем разбирайся.

**Comment by KandreyKandrey** [comment]
> на сендбоксе уходит 15 нутришена за 5 минут, я хз много это или мало

Кукла спавнится с нутришеном от 250 до 450

**Comment by KandreyKandrey** [comment]
с расходом 15 нутришена за 5 минут, кукла только к концу раунда должна проголодаться

**Comment by UsadoSmokk** [comment]
помимо всего прочего, вроде как травмы повышают голод, либо оно так совпадает постоянно(боле-урон в том числе)
заметил это играя на воксах, ибо попить горячий шокод на вариант так как сахар, колоть тоже влияет на муд, остается только быстро кликать еду без маски, но прикол в том, что тут шанс травануться 50 процентов и если антитоксина под ругой нет, скорее всего ты траванешься и твой перекус пойдет нахуй, из-за урона.

**Comment by pro100kotah** [comment]
> помимо всего прочего, вроде как травмы повышают голод, либо оно так совпадает постоянно(боле-урон в том числе) заметил это играя на воксах, ибо попить горячий шокод на вариант так как сахар, колоть тоже влияет на муд, остается только быстро кликать еду без маски, но прикол в том, что тут шанс травануться 50 процентов и если антитоксина под ругой нет, скорее всего ты траванешься и твой перекус пойдет нахуй, из-за урона.

Да, это так. Пусть блять сделают хоть что-то с едой воксов. Какой-то мудак стелснерфом снес инжекторы и с того момента воксы питаются только через шприцы. А потом второй не хороший человек решил понерфить инъекции шприцов в себя из-за чего жрешь - не жрешь, муд все равно один и тот же из-за кучи дебаффов, а экран ебанутой поносной расцветки.

**Comment by Deahaka** [comment]
Хотя если мы смотрим на воксов как на расу на которой игроки должны страдать и проходить испытания где они не обязаны выйти из ситуаций в плюсе, то тогда проблемы нет и ничего фиксить не надо

**Comment by INwirstD** [comment]
Щас из раунда вот такая ситуация. Шахтёр накачал ноги и у него нутрименты улетают примерно в 10 раз быстрее, чем у не накаченной куклы. Итого, у него за 5 минут ушла почти половину нутриментов.

**Comment by Deahaka** [comment]
вроде не актуально
