### ISSUE TITLE
У дион не отрастают конечности

### ISSUE THREAD

**Issue by Slegarrr** [TauCetiStation/TauCetiClassic#11108]
#### Подробное описание проблемы
При потере конечностей или головы появляется текст что они отрастают, но они не отрастают на практике (раньше работало)
#### Что должно было произойти
Конечности и голова должны вырастать заново
#### Что произошло на самом деле
Конечности или голова не отрастают
#### Как повторить
Потерять конечность или голову
#### Дополнительная информация:
Issue reported from  Round ID: 58306 (Tau Ceti Classic (RU))
Testmerges: ```#10875 #10876 #10918 #10978 #10979 #11034 #11083 #11093 ```
Reporting client version: 514.1589

**Comment by Deahaka** [comment]
Древний баг
