### ISSUE TITLE
 thin window нельзя прикрутить к полу

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#11116]
#### Подробное описание проблемы
одинарное окно, ака thin window нельзя прикрутить к полу
#### Что должно было произойти
нажал отверткой по стеклу и его нельзя двигать
#### Что произошло на самом деле
нажал отверткой по стеклу и ничё не случилось
#### Как повторить
потыкайте отверткой по thin window

**Comment by volas** [comment]
Это старый код, который никак не изменялся. В случае обычного стекла - просто отверткой, в случае реинфорсед - отверткой, ломом, отверткой. Какая логика за этим я не знаю, и я их механики сейчас не трогаю.
