### ISSUE TITLE
Снова новые автоматы, снова проблемы.

### ISSUE THREAD

**Issue by Slavik2001** [TauCetiStation/TauCetiClassic#11119]
#### Подробное описание проблемы
При ЗАМЕНЕ НОВЫМИ прямо с карго саплями автомат выдает товар только 1 штуку
#### Что должно было произойти
Должен быть полный автомат(25 сигарет, 6 вкусняшек там гдедошики и т.д.)
#### Что произошло на самом деле
При замене там всего товара по 1
#### Как повторить
Разберите автомат, выкиньте старые сапли и установите новые прямо с карго и закрутите
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/123300305/227542051-0915067f-f526-4c27-be26-75cab565d617.png)
Issue reported from  Round ID: 58327 (Tau Ceti Classic (RU))
Testmerges: ```#10918 #10978 #10979 #11034 #11083 #11117 ```
Reporting client version: 514.1589

**Comment by LudwigVonChesterfield** [comment]
#10918

**Comment by DarthSidiousPalpatine** [comment]
Удалите это, я ещё когда ПР существовал это давно пофиксил.
