### ISSUE TITLE
[Proposal] Реверт ПРа с удалением вендоматов и жратвы из них до лучших времен

### ISSUE THREAD

**Issue by Lexakr** [TauCetiStation/TauCetiClassic#11115]
#### Подробное описание проблемы
Удаление части вендоматов и выпил почти всей жратвы из них раундстартовой ебет игроков просто, блин, потому что. Никакой мотивации каргонцам идти и рестокать эти вендинги нет. Никаких сроков, когда Гисев закодит остальную часть (которая по идее будет не ебать игроков, а помогать им) тоже нет. Трудности с поиском еды - есть. Кайфа и смысла бегать по станции тыкать все подряд вендинги в поисках еды - полный брэд
https://github.com/TauCetiStation/TauCetiClassic/pull/10436
https://github.com/TauCetiStation/TauCetiClassic/pull/10805

**Comment by Deahaka** [comment]
Я возможно борщу с рекламой, но вот этот ПР решает абсолютно все проблемы для игроков с автоматами, карго, поварами, сахаром и другим чем угодно возможно навсегда: 
https://github.com/TauCetiStation/TauCetiClassic/pull/10895

**Comment by F0xiq** [comment]
Поддерживаю, цензурных слов нет, чтобы описать ситуацию с вендоматами, едой и сломанной системой голода.

**Comment by volas** [comment]
#11122
