### ISSUE TITLE
#СпэйсПруфНужен (Нужен спейспруф как у капитанского армора для дедсквада.)

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1113]
#### Подробное описание проблемы
Выйти в броне дедсквада в разгерметизированое помещение@Умереть.
#### Что должно было произойти
Дедсквад не должен умирать от разгерметизации.
#### Что произошло на самом деле
Соснули
#### Как повторить
Поиграть за дедсквад.
#### Дополнительная информация:

![](http://image.prntscr.com/image/f8be5bbbf23340bb8020ee7e85d5cd1b.png)

**Comment by raduser** [comment]
Это фича дедов, у них не скафандры, а броня.

**Comment by Skippeer12** [comment]
Пластмассовый мир победил

**Comment by Olt1771** [comment]
Я пожалуй оставлю это тут http://prntscr.com/e4w6tz (раньше они имели 10 минут спэйспруфа)

**Comment by sovok4** [comment]
Нужно просто перестать посылать дедов в разгерму. Для этого есть ЕРТ.

**Comment by igigin** [comment]
Спейспруф не нужен, но нужен флаг `STOPS_PRESSUREDMAGE` или `STOPS_LOWPRESSUREDMAGE`.
Иначе деды не нужны, у нас в любом случае, где их можно послать, есть разгерма.

**Comment by Shudyn** [comment]
Лучшие бойцы Нанотразен@не дали защиту от низких давлений@умирают от 40-50 кпа

**Comment by Lancer411** [comment]
Ну так они опасны даже для нанотрасен, так их устраняют.
