### ISSUE TITLE
Алиум-баги. Опять.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1114]
#### Подробное описание проблемы
1. В трубе не видно количества людей.
2. Лярвы не растут быстрее на траве, хотя должны были.
3. Нет возможности растворить вентиляцию.
4. Одисей может спиздить Квину.
5. Люди внутри алиумов могут бить их руками. А так же, при передвижении в трубе с хуманом в животе, тебя постоянно спамит: Хуман ин йоар стомач чо то там.
6. Скафандры абсолютно не восприимчивы к нейротоксину.
7. Высокая температура - слишком имба. Достаточно один раз прыснуть огнеметом в логово алиумов или в закрытое помещение, как все алиумы получают не прекращающийся дамаг даже если стоят на траве. И это работает за километры даже если сделать разгерму.
8. Прогресс вырастания лярвы в носителе не работает.
9. Нельзя заварить скраберы.
#### Что должно было произойти
1. Будучи в трубе, алиумы должны видеть хуманов как сквозь стены.
2. У лярвы на траве должно заполняться 2 или 3 тика в секунду.
3. Должна быть функция у дронов, защитников и квины - растворить вентиляцию.
4. Одисей не должен уметь собирать алиумов.
5. Без острого предмета, люди не должны иметь возможности избивать алиума которых их поглотил.
6. Люди надевшие скафандры, должны падать после двух или трех попаданий нейротоксином. Абсолютную невосприимчивость должны лишь иметь костюмы биологической защиты (да и то сомневаюсь, все таки это почти что кислота).
7. У алиумов нет никаких возможностей следить за температурой кроме внезапной иконки горения твоего пердака. Повышение температуры надо либо нерфать во время алиумо-раундов, либо сделать алиумам меньшую восприимчивость к огню.
8. Прогресс стоит на месте. Неизвестно сколько нужно ждать прежде чем ты вырастешь.
9. Скраберы нужно уметь заваривать.

**Comment by Skippeer12** [comment]
4. С руки много дамага не будет. Но вот если у них есть балон, то тебя гибнет. Тут всё ок же.

**Comment by Uvash** [comment]
2 Не слышал о такой фиче. А точно нужно?
5 Не баг, а фича. Следи за тем, что ты ешь.
6 Скафандр защищает от биологии и прочего. Биосьют только от биологии. Возможно с добавлением плевков кислотой алиумам, кислота не будет растворять биосьюты (а может будет, надо закодить а потом смотреть).
8 Вроде прогресс отображается сменой иконки.

**Comment by Avatar4** [comment]
2. Лярвы растут очень МЕДЛЕННО. Если спалят допустим хуманы - то у них не будет никаких шансов считай. Лично я думаю - нужно. Может у других есть свое мнение на этот счет.

**Comment by igigin** [comment]
>Одисей не должен уметь собирать алиумов

Квину может и нет, а других почему не должен?

**Comment by dearprincesscelestia** [comment]
Других должен, по запросу ученых. И Одиссей теперь медсай мех.

> С руки много дамага не будет. Но вот если у них есть балон, то тебя гибнет. Тут всё ок же.

Тогда живых людей из разгермы не добить, если все снимать, что может урон нанести. Да и когда раздеваешь человека за хантера, помимо маски-шапки в улье, очень сильное чувство, что что-то делаешь не так. 

Можно руки им отгрызать.

**Comment by Avatar4** [comment]
Раньше только квина могла раздевать (или это было на маринах?).

**Comment by SpaiR** [comment]
точно такое же дерьмо как и в #1071
