### ISSUE TITLE
[Task] Byond 515 compatibility

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#11140]
https://www.byond.com/forum/post/2828780

Потребуется много изменений, так что в этот раз можно было бы постепенно и заранее начать.

Для референса:
* https://github.com/tgstation/tgstation/pull/71161 (Желательно разбить на отдельные PR-ы)
* https://github.com/tgstation/tgstation/pull/71333
* ???

**Comment by KIBORG04** [comment]
https://github.com/tgstation/tgstation/pull/75835

**Comment by volas** [comment]
забавное, но уже пофикшено в следующей версии https://www.byond.com/forum/post/2872856

спасибо всем первопроходцам, кто собирает все шишки вместо нас

**Comment by KIBORG04** [comment]
Не работает тгуи чат и статус панель на 515 билде тау киты
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/26389417/50b5fd5a-54be-4205-abd1-02f50605718e)

**Comment by KIBORG04** [comment]
По моему наблюдение, версия билда не влияет на это. То есть, я на 515 клиенте заходил и на сервер 514, и на сервер 515, но тгуи чат так же не грузился, а верб панель ломалась.

**Comment by KIBORG04** [comment]
Ура!
