### ISSUE TITLE
[Предложение] Прикрутите уже какой либо значек в худах для мусорщиков.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1115]
Смотрите на название.

**Comment by igigin** [comment]
Так принесите спрайт иконки - прикрутим.

**Comment by omejka** [comment]
<a href="http://c2n.me/3HgR7RM"><img src="http://c2n.me/3HgR7RM.png" alt="Screenshot_24"/></a>
Как вам лопата?Ничего другого туда не поместится.

**Comment by Skippeer12** [comment]
@omejka А криминалистам худ сворганишь?

**Comment by omejka** [comment]
@Skippeer12 
АВД:
<a href="http://c2n.me/3HgUMgo"><img src="http://c2n.me/3HgUMgo.png" alt="avd"/></a>
Криминалист,допустим:
<a href="http://c2n.me/3HgUMrw"><img src="http://c2n.me/3HgUMrw.png" alt="lrim"/></a>
Или повернуть нормально,да

**Comment by dearprincesscelestia** [comment]
Криминалист топ.
