### ISSUE TITLE
CМ ломает гены СПУ, которых у СПУ нет

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#11158]
#### Подробное описание проблемы
СМ вызывает шизу у СПУ. Каким образом? Непонятно.
У СПУ нет шизы или же психоза.
#### Что произошло на самом деле
Есть.
#### Как повторить
Посмотреть на СМ.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/57403011/228332301-58c01183-ad6c-48c5-8be8-5492b3a19d5b.png)

![image](https://user-images.githubusercontent.com/57403011/228332870-fb74a513-3037-459b-9341-1cc4c4ba3625.png)

**Comment by arygal** [comment]
А разве это не фича? Вроде там временная шиза накладывается, не генетическая(как от приёма наркотиков) , но тут я могу быть не прав.

**Comment by Mercurialaste** [comment]
Это не гены, а психоз. Попробуй за СПУ посмотреть на СМ без мезонок.

**Comment by pro100kotah** [comment]
> Это не гены, а психоз. Попробуй за СПУ посмотреть на СМ без мезонок.

В любом случае это странно. Каким образом психоз может быть у СПУ.

**Comment by Mercurialaste** [comment]
> > Это не гены, а психоз. Попробуй за СПУ посмотреть на СМ без мезонок.
> 
> В любом случае это странно. Каким образом психоз может быть у СПУ.

Добавь исключение.
