### ISSUE TITLE
[Предложение]Нормальные кандалы.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1116]
Предлагаю сделать кандалы не снимающимися как электропак, или же сделать время снятия как на наручниках. Можно использовать механ капкана к примеру.
Зачем? Что бы иметь возможность выводить заключенных на исправительные работы и не рисковать его побегом.

**Comment by Lancer411** [comment]
Для начала нужно ввести исправительные работы.

**Comment by igigin** [comment]
Там некий Жамесмор собирался когда-то делать рабские ошейники. Суть была та же, только лучше. Но ему вроде как не хватало спрайтов.

**Comment by Avatar4** [comment]
Ставишь заключенному овердохуительный срок, заключенный охуевает, предлагаешь что бы он убрал некоторое дерьмо и отпустишь, ???, PROFIT!
