### ISSUE TITLE
Раундстартовая монетка в кошельке имеет неправильный спрайт

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#11161]
#### Подробное описание проблемы
Все раундстартовые монетки в кошельках (которые в дормах) имеют неправильный спрайт маленькой монетки. Если вытащить её из кошелька и положить обратно всё нормализуется.
![coin](https://user-images.githubusercontent.com/113668462/228466036-da609b8a-a9a6-4c95-bbde-e1dd81fda699.jpg)
Левая монетка на изображении уже была в кошельке, правая была положена в кошелек.

**Comment by volas** [comment]
какие-то гонки на инициализации
