### ISSUE TITLE
Цвет проводов?

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#1117]
#### Подробное описание проблемы
На станции провода разных расцветок, но при прокладывании, они всегда одного цвета(красный)
Я прокладываю синие провода, но они имеют красный цвет.

#### Что должно было произойти
Все провода на станции в таком случае должны иметь либо красный цвет, либо при прокладке они должны иметь цвет, который отображается на мотке проводов.

#### Что произошло на самом деле
Я прокладываю желтые,синие, провода, но они имеют красный цвет.

#### Как повторить
Взять провода любой расцветки и применить.

**Comment by Dennok** [comment]
Ага. Сломалей цвета проводов,  снова, опять.

**Comment by Dennok** [comment]
Причем давно уже.

**Comment by igigin** [comment]
Насколько я помню, цвета перестали совпадать ещё в где-то в 2014 году, а всегда красными они стали как фикс рандомному цвету (такой себе фикс).
