### ISSUE TITLE
Фаердоры над шлюзами

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#11174]
#### Подробное описание проблемы

Emergency Shutter теперь рисуются поверх шлюзов, шаттеров

#### Что должно было произойти

Должны рисоваться под шлюзами, шаттерами

#### Дополнительная информация:

#10978

**Comment by AzzyDreemurr13** [comment]
Это было сделано из-за проблем у ИИ. 

Я писал об этой проблеме #11076 ,в итоге Волас пока поднял, чтобы отображалось поверх, до тех пор пока красивее не придумают

**Comment by volas** [comment]
Это можно поправить, но кто-то вроде даже говорил что полезно, нужно ли?

**Comment by DarthSidiousPalpatine** [comment]
> Это можно поправить, но кто-то вроде даже говорил что полезно, нужно ли?

раньше через окошко шлюза видно было фаердор. Вот если бы оно также как с окном работало, эх... Что сначала ты открываешь фаердор а потом сам шлюз по тыку, но фаердор всё также под шлюзом отображается.

**Comment by Deahaka** [comment]
Не вижу ничего полезного в баге

**Comment by volas** [comment]
пофикшено в [`f578b38` (#10978)](https://github.com/TauCetiStation/TauCetiClassic/pull/10978/commits/f578b3800f2656f9554750d6cecaa2f343a15157)
