### ISSUE TITLE
[Proposal] Апгрейднуть говорящие предметы до цепей Маркова

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#11175]
#### Подробное описание проблемы
Сейчас говорящие предметы работают просто по 1 рандомному слову + рандомное слово, которое встречалось после этого лова. 
https://github.com/TauCetiStation/TauCetiClassic/blob/ac2292245447293510417a72366b247c78f2af2c/code/datums/components/talking_atom.dm#L47
![image](https://user-images.githubusercontent.com/26389417/228956387-bc4f862c-331e-4681-a5af-f4937d833722.png)

Текущий алгоритм не отбрасывает знаки препинания и из-за этого генерируемые предложения выглядят странно и глупо с точками в центре предложения. 
```
 the katana reverberates, "И пройти регистрацию, а второй - сдать оружие и третий. уведомляло о прибытии вашем. приписана за кораблем и у вас два пути. первый - сдать."
 Ancient box reverberates, "Забрать клувню! он вам не уведомляло о прибытии вашем. и забрать клувню! о прибытии вашем. да не уведомляло о прибытии."
```
### Плюсы
Если внедрить цепи маркова, то предмет сможет в раунде говорить намного более осмысленные фразы. А если сделать обучение предметов еще и с межраундовым сохранением прогресса, то через раундов так 5 тысяч, предметы будут говорить нереально осмысленно!

**Comment by LudwigVonChesterfield** [comment]
но доктор, это и есть цепь Маркова

**Comment by KIBORG04** [comment]
Ну, как бы да, но ведь нет коэффициентов веса для перехода от одного слова к другому

**Comment by DarthSidiousPalpatine** [comment]
Что если сделать ИИ-борга в библиотеку которому скормить всю вики таукеки и чтобы он отвечал на вопросы :dovolen:

**Comment by KIBORG04** [comment]
Пофиг
