### ISSUE TITLE
багованный щит-зеркало

### ISSUE THREAD

**Issue by BlankCringe** [TauCetiStation/TauCetiClassic#11179]
#### Подробное описание проблемы
Щит зеркало культа можно призвать только 1 раз за меч
#### Что должно было произойти
Я могу призвать щит зеркало держа меч в руке когда хочу, либо щит зеркало должен остаться на земле после дропа
#### Что произошло на самом деле
Щит зеркало пропадает после дропа и чтобы вызвать новое-нужен новый меч,
#### Как повторить
Дропнуть щит зеркало, попробовать призвать новое тем же мечом культа.

**Comment by Naroke** [comment]
Там вроде делей стоит большой между призывом нового щита, примерно секунд 20, наверное.

**Comment by Deahaka** [comment]
Проверь если ты дропнул щит, при клике на меч, через условно минут 5-10, не появится щит в руке, то значит баг. В иной ситуации типо баланс или хз для чего?

**Comment by KIBORG04** [comment]
```
AddComponent(/datum/component/self_effect, shield_type, "#51106bff", CALLBACK(src, .proc/only_cultists), 2 MINUTE, 30 SECONDS, 2 MINUTE)

/datum/component/self_effect/Initialize(_effect_type, _outline_color, datum/callback/_can_callback, _recharge_time = 0, _recharge_time_after_del = 0, _time_to_del)
```
Кд 2 минуты. Если юзаешь 2 минуты, то кд 30 сек. Автор темки вроде не понимает как работает механика, бага быть не должно
