### ISSUE TITLE
сорванный плакат позволяет вступить в реву

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#11176]
#### Подробное описание проблемы
если сорвать со стены рев плакат то он не перестаёт работать
#### Что должно было произойти
с помощью сорванного плака нельзя конвертиться в реву
#### Что произошло на самом деле
можно
#### Как повторить
повесить на стену революционный плакат, сорвать его и попытаться использовать его с целью конверта

**Comment by DarthSidiousPalpatine** [comment]
-Товарищ Петров, я не могу вступить в реву, у вас плакат сорвали!
-Но ты же коммунист?
**"Would you like to join revolution?"**

**Comment by DarthSidiousPalpatine** [comment]
Видимо, пофиксили или что-то. Повесил плакат - работает, сорвал - не работает.
В общем, бага нет, можете удалять ишуй.

**Comment by Deahaka** [comment]
#11231
