### ISSUE TITLE
Предметы на прилавке центрятця

### ISSUE THREAD

**Issue by Rolt146** [TauCetiStation/TauCetiClassic#11184]
#### Подробное описание проблемы
Я хочу красиво разложить товары по столу, что бы на одном столике был как можно более расширеный ассортимент(см верхний столик), а они все собираются в одну кучку (см столик пониже)
![Скриншот 31-03-2023 203203](https://user-images.githubusercontent.com/62613651/229190026-d3b4373f-1040-474e-a416-827d7f4f087c.jpg)

#### Что должно было произойти
Я красиво раставляю предметы на одном столике, клиент видет разнообразие и рад
#### Что произошло на самом деле
Спрайты предметов наслаиваются друг на друга, клиент грустит, ведь он видет какофонию или вообще один предмет, который скорее всего ему не нужен
#### Как повторить
Наклеить бирку на товар, поместить в угол торгового столика предмет, С грустью наблюдать, как он центриться в середину стола

**Comment by volas** [comment]
Если только прилавков, то может где-то тут https://github.com/TauCetiStation/TauCetiClassic/pull/10915#discussion_r1132490559

Если и у обычных столов - траблы компоненты, скорее всего.

**Comment by LudwigVonChesterfield** [comment]
#10915
