### ISSUE TITLE
Створки в капитанской ниже окон

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#11182]
#### Подробное описание проблемы

в капитанской есть shutters которые закрываются по кнопке, но их не видно из-за новых стёкол

#10978

**Comment by volas** [comment]
У нас целых 3 вида разных опускающихся створок?..

**Comment by volas** [comment]
Поправил в [`db30e08` (#10978)](https://github.com/TauCetiStation/TauCetiClassic/pull/10978/commits/db30e08c74a600e0601c9147c0d5f719f9c29d52)

Но еще заметил, что из-за анимации переход у поддоров выглядит дерганно, это оставлю для отдельного PR-а.
