### ISSUE TITLE
[Proposal] Позволить квине ломать укреп стены

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#11181]
Сейчас люди могут в условном рнд застроиться укреп стенами и ксеноморфы им ничего никогда уже не сделают.

Предлагаю позволить квине ломать укреп стены чтобы такая стратка не работала...

Или не знаю. позволить им как-то фороном выкуривать людей которые так забарикадируются.

**Comment by AzzyDreemurr13** [comment]
Бредятина, сейчас все олени, тупо в одного ломают все Крит системы, РнД ломают все сервера и более РнД нет смысла быть в РнД ибо 1 олень вынес всё и также сломал связь
