### ISSUE TITLE
Шатл велосити. Возвращение домой или как спастись от ядерного взрыва. (Предложение)

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#1118]
#### Подробное описание проблемы
У нас запрещена эвакуация,бегство,гриф и прочие непотребства на Велосити(Транзитная станция). Но почему тогда со станции присутствует возможность вернуться туда? Предлагаю взять систему карго шатла, в котором люди могут прибывать на станцию, а обратно - нет. Проверка на живых существ. Если на шатле есть живое существо - запуска не будет.

#### Что должно было произойти
На шатле велосити нельзя вернуться обратно.
#### Что произошло на самом деле
На шатле можно вернуться.
#### Как повторить
Сесть в шатл, и активировать процедуру перелета.

**Comment by Raneman** [comment]
Вдобавок взрывайте астероид.

**Comment by Lancer411** [comment]
Прячешься в шкафу с кислородными масками@никто не может попасть на станцию.

**Comment by dearprincesscelestia** [comment]
Прячешь апатика там.

А вообще нюкеры же не екепаш взрывают, а стейшон и диск заодно в карман кладут.

**Comment by Raneman** [comment]
Выпилите вместе с нюкой.

**Comment by Skippeer12** [comment]
Можно будет обхводить с помощью ИИ или борготы.

Так как карго шаттл отлетает мгновенно, а этому нужно время на собратся.

**Comment by Lancer411** [comment]
Ну нет, можно сделать что отправление не происходит, если есть люди на борту, а последовательность запуска никто не мешает запустить.

**Comment by dearprincesscelestia** [comment]
Да, и как только челвоек делает шаг с тайла шаттла, тот запускается, и тебя высасывает в вакуум.

**Comment by Lancer411** [comment]
Автоматика - сила.

**Comment by Raneman** [comment]
Вроде на ТГ или где там, я не помню, можно выбирать место спауна.
Прикрутить то же самое, но без выбора места, а чтобы до 12:20 спаунило на велосити, а после — у криокамер. Решит кучу логический проблем, как например те обезумевшие госты, которые с воплями радости респаунятся на велосити и улетают на туго разъёбаную станцию с красным кодом и кишками на полу чтобы скончаться от очевидной разгермы на выходе из шаттла, вместо того чтобы улететь домой и не умирать.

**Comment by Raschert0** [comment]
Чем вас не устраивает решение в моём ПРе? И нет, не 

> как только челвоек делает шаг с тайла шаттла, тот запускается, и тебя высасывает в вакуум.

так как
>этому нужно время на собратся

И нет, не
>Можно будет обхводить с помощью ИИ или борготы.

Так как он вообще не будет летать со станции через ту консоль, которая на нём. Консоль на шаттле для полёта к станции. Консоль на Велосити для полёта к Велосити.

**Comment by Raneman** [comment]
Попросил кооподружка заспауниться и пригать шаттл до велосити.

**Comment by dearprincesscelestia** [comment]
Поставить на шаттле крутящиеся двери в одном направлении.

**Comment by Raneman** [comment]
Отправлять космонавтиков на безысход в специальных ящиках с дырочками для дыхания одноразовыми капсулами.

**Comment by dearprincesscelestia** [comment]
По космосу.
