### ISSUE TITLE
Непробиваемый Общак или Разгермы Балоном?

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#11194]
#### Подробное описание проблемы

После того как убрали одинарные стеклышки поставив везде фултайл произошёл цунгцванг.

Либо мы повышаем порог урона чтобы нельзя было укрепки ломать балоном, и делаем побег из общака невозможным:

![image](https://user-images.githubusercontent.com/17705613/229291930-8e33a474-49af-47ed-82f5-2b3827fce72c.png)

Либо мы понижаем порог урона и любой дурачек может разгермить до космоса всего-лишь балоном из кармашка:

![image](https://user-images.githubusercontent.com/17705613/229291939-c35131bb-0e85-4936-ad1e-4dd317908855.png)

#### Что должно было произойти

Я могу сбежать из общака табуреткой, но не могу разгермить станцию балоном из кармана.

#### Что произошло на самом деле

в текущей реализации я могу сбежать из общака табуреткой и могу разгермить станцию балоном

#### Дополнительная информация:

https://github.com/TauCetiStation/TauCetiClassic/pull/10978

**Comment by LudwigVonChesterfield** [comment]
Вероятно нужно повозвращать "неукрепленные" стёкла туда где это уместно.

Но для этого нужны отличия в спрайте иначе будет грустно.

Раньше отличие было между фуллтайл стеклом и четырьмя маленькими.

**Comment by Mercurialaste** [comment]
> ибо мы повышаем порог урона чтобы нельзя было укрепки ломать балоном, и делаем побег из общака невозможным:

побег из общака возможен, нужно только, бумажно подумать.

**Comment by LudwigVonChesterfield** [comment]
![image](https://user-images.githubusercontent.com/17705613/229297889-1a5e306f-87bb-4ccf-8d2d-788354a16e3f.png)

**Comment by volas** [comment]
Думаю не актуально, где нужно расставили обычные окна.

> в текущей реализации я могу сбежать из общака табуреткой и могу разгермить станцию балоном

как и задумано, есть минимальный порог для урона который по необходимости можно твикнуть, но я в текущем не вижу проблем. Расковырять слабым оружием потребует много времени.
