### ISSUE TITLE
Зачем Убрали Быструю Разборку В Незащищенные Отделы?

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#11198]
#### Подробное описание проблемы

Разбор тонкоокон был очень быстрым - три клика, один ПКМ и окно разобрано. В итоге проникновение во всякие ботаники, кухни вообще не было проблемой.

Теперь все окна на станции укреплены до немогу и разбирать их очень долго. Проникать в условную ботанику занимает столько же усилий сколько и в бриг.

#### Что должно было произойти

В бриг сложнее чем в ботанику

#### Что произошло на самом деле

Монопенисуально

#### Дополнительная информация:

#10978

**Comment by volas** [comment]
> Разбор тонкоокон был очень быстрым - три клика, один ПКМ и окно разобрано. В итоге проникновение во всякие ботаники, кухни вообще не было проблемой.

не совсем правда, зависит от скиллов. И со скиллами сейчас разборка так же быстрая.

**Comment by volas** [comment]
На примере реинфорсед, было три вызова ``handle_fumbling`` (лом, отвертка, лом) со скилом инженера ``SKILL_TASK_EASY``. СЕ и инженеры скипнут, остальные будут в do_after. + умножить на 2/4, если это мультиобъектное окно.

Сейчас это один ``handle_fumbling`` с требованиями как и раньше (СЕ и инженеры всё так же скипнут), + добавлен лом.use_tool(src, user, 40) - что бы у инженеров и СЕ была хоть какая-то задержка действия и прогрессбар (и он всё равно будет не 40, а сократится от скилла), и в качестве компенсации за количество необходимых кликов в прошлом (раньше нужно было тыкать отверткой/ломом несколько раз, теперь нет).

Грид в обоих случаях не изменился, а подоконник разбирать не обязательно, его можно перелезть.

Я думаю, проблемы тут нет. Или я её не вижу.
