### ISSUE TITLE
Почему в игре про космос нельзя вылететь в космос

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#11199]
#### Подробное описание проблемы

Делей между атмосом и закрытие пожарной створки обуславливал что ты можешь вылететь в космос если сломать окно.

Теперь из-за рамы это невозможно.

А ведь люди жалуются на казуальность ТГ атмоса, хотя наш атмос теперь жёско оказуалили.

@UDaV73rus приглашаю тебя написать за что ты полюбил тау киту и смешную историю с клоуном.

#### Что должно было произойти

Я выпадаю в космос и плачу

#### Что произошло на самом деле

У всего экипажа теперь есть подушка безопасности которую раньше выдавали только главам

#### Дополнительная информация:

#10978

**Comment by DarthSidiousPalpatine** [comment]
Сделайте механ чтобы и над столом и над рамой можно было пролететь от порыва ветра.

**Comment by ssbugman** [comment]
В чем вообще логика того что простой квадрат рамы вокруг окна не дает вылететь в космос? Звучит как абсурдный баг.

**Comment by LudwigVonChesterfield** [comment]
![image](https://user-images.githubusercontent.com/17705613/229357703-4b9b10b4-fe38-499b-9f44-1e473d7aa3c5.png)

![image](https://user-images.githubusercontent.com/17705613/229357711-65a62709-ba2f-4eee-a1dc-13c3d1279dc4.png)

**Comment by volas** [comment]
это баг, подтверждаю
