### ISSUE TITLE
Быстрое снятие стекла с монолитного окна

### ISSUE THREAD

**Issue by D3kr0s** [TauCetiStation/TauCetiClassic#11207]
#### Подробное описание проблемы
Быстрый разбор стекла монолитного окна двумя нажатиями лома.
#### Что должно было произойти
Слой стекла должен убираться в соответствии с таймером.
#### Что произошло на самом деле
Слой стекла был убран сразу же.
#### Как повторить
Двойной клик ломом по монолитному окну.
#### Дополнительная информация:
Issue reported from  Round ID: 58481 (Tau Ceti Classic (RU))
Testmerges: ```#11082 #11083 #11117 #11122 #11186 #11188 #11193 ```
Reporting client version: 514.1589

**Comment by Chip11-n** [comment]
Также, можно просто сдвинуться, прервав дуафтер, или начать разбирать другие стекла, снимая моментально.
