### ISSUE TITLE
ИИ и культо-магия.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1121]
#### Подробное описание проблемы
За ИИ не видно нарисованные культом руны.
#### Что должно было произойти
Руны или пятна крови вместо них должны быть видны.
#### Что произошло на самом деле
Не видно вообще никаких рун.
#### Как повторить
Нарисовать культистом разные руны (в том числе и стен), зайти за ИИ и посмотреть видно ли руны.
#### Дополнительная информация:
Нет, он их не прятал. Даже телепорт юзал на изи.

**Comment by Kurshan** [comment]
Однозначная фича

**Comment by P-20** [comment]
Даже на вики сказано, что синтеты а в особенности ИИ не видит рун.

**Comment by Raschert0** [comment]
>Искусственный интеллект, злейший враг скрытных культистов, он не должен иметь шансов вас обнаружить. К счастью, он видит руны, как обычную кровь.

**Comment by Avatar4** [comment]
Но так дело в то что он и КРОВИ  не видит.

**Comment by Skippeer12** [comment]
ИИ не видет ничего, там просто пусто.
А вот борги видят руны как хуманы.

**Comment by Kurshan** [comment]
#1670
