### ISSUE TITLE
[Proposal] Adrenaline Rush

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#11229]
Одна из проблем системы настроения - негативные дебаффы не учитывают обстоятельства куклы. Человек может подхватить дебафф от голода и грязной одежды во время ожесточенной перестрелки за жизнь. Мы не можем угадывать такие обстоятельства через код, но мы могли бы дать такую возможность юзеру.

Дать кнопку "Adrenaline Rush" (можно какой-нибудь ctrl+click по иконке муда), которую можно использовать **только один раз** за раунд, и которая добавляет кратковременный хороший бонус:

```
/datum/mood_event/adrenaline_rush
	description = "<span class='nicegreen'>I need to concentrate on my situation!</span>"
	mood_change = 15 // может больше
	timeout = 15 MINUTES
```

кнопка должна так же бустить/обновлять текущий spirit, что бы сразу убрать дебаффы. По окончанию бонуса, мы (опционально) можем добавить небольшой, но долгий дебафф за использование (откат).

Подобное поможет юзеру отыграть ситуацию без палок в колеса от муда, если этим банально нету времени заниматься. 15 минут должно быть достаточно, что бы либо окончательно помереть, либо справится с обстоятельствами и привести себя в порядок.

Могут абузить не по назначению, но с лимитом 1 за раунд это не так страшно (юзер сам себя накажет, если использует раньше времени).

Я предлагаю сделать эту возможность дефолтной и доступной всем для муда, но мы могли бы и добавить это в качестве квирка в сетапе персонажа за -1 очко. Альтернативно, если это будет доступно для всех, и не будет спрятано за квирком, для хард-рпшеров можно было бы добавить квирк с +1 очком, отключающим эту особенность.

**Comment by volas** [comment]
@LudwigVonChesterfield интересно твоё мнение. 

Если добавить - то больше не будет проблемой показывать все муд ивенты юзеру, ничего не скрывая.

**Comment by TryXAH** [comment]
Мне кажется, 15 минут слишком много. Нельзя сделать два заряда по 7 минут, без кулдауна, чтоб в случае чего можно было использовать два раза подряд?

**Comment by volas** [comment]
оно должно тригерить мгновенное обновление spirit-а, иначе человек будет ходить с фильтром и ждать хз сколько, пока этот бонус подействует. Но сбрасывать таким образом spirit дважды за раунд - уже может быть будет абузивно, потому что после как бонус закончится и муд опять скатится пройдет еще хз сколько времени, юзер потенциально сможет эвейдить муд почти весь раунд.

**Comment by TryXAH** [comment]
В таком случае, сразу после использования можно накидывать супер негатив муд по типу "устал" или "использовал второе дыхание", который скидывает позитивный муд до уровня наложения фильтра

**Comment by volas** [comment]
> супер негатив муд

дебафф если делать, то имхо небольшой. Иначе юзер мог успеть постираться, вкусно покушать, посидеть в туалете, а всё будет без толку из-за отката.

**Comment by TryXAH** [comment]
> Иначе юзер мог успеть

Мне кажется, когда будут использовать такой адреналин, это не та ситуация, в которой он особо занимается повышением муда. 
Но сам дебафф должен быть недолгим, и заглушаемым привычным действием почти полностью. Почти - чтобы все таки какой никакой минус к муду был

**Comment by volas** [comment]
> Мне кажется, когда будут использовать такой адреналин, это не та ситуация, в которой он особо занимается повышением муда.

кнопка именно для того, что бы он мог успеть поправить свою ситуацию, если муд выскочит в неожиданный момент. Мы не предполагаем, что юзер будет константно ходить с плохим мудом, и дважды за раунд отключать его для перестрелок.

**Comment by AndroBetel** [comment]
это же воля с лайфвеба

**Comment by TryXAH** [comment]
> кнопка именно для того, что бы он мог успеть поправить свою ситуацию, если муд выскочит в неожиданный момент

Я про то, что два заряда поменьше вместо одного большого не подходят, так как с ними можно будет абузить хороший муд весь раунд.
Это как то можно забалансить, чтобы и два заряда можно было использовать по назначению, и муд абузить не получилось бы

**Comment by LudwigVonChesterfield** [comment]
Хорошая идея если нормально забалансить,

я против только реализации в виде ещё одной кнопки на интерфейс

можно чтобы при осмотре своего муда была кнопка в чатике вида ААААААААА

**Comment by pro100kotah** [comment]
Вообще эта тема звучит довольно интересно. Но все же полигон для абуза невероятный. Как минимум боль можно будет частично ивейдить, когда тот дает огромный дебафф муду "Я в агонии", "Чувствую себя, как будто умру с минуты на минуту" и т.д. А так получил его и скинул своим адриком. Голоурон это не обнулит, но скинет сопутствующий дебафф. Что-то похожее на дешевый триторский адрик. Только болеурон не снимает.

И все также интересно вот что, это получается просто бафф в каком-то значений, который может перебиться кучей отрицательных? Или он полностью нивелирует дебаффы муда и ничто не сможет его снизить целые 15 минут? Если второе, то это звучит слишком.
