### ISSUE TITLE
Костюмы не защищают от ударов тока

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#11228]
#### Подробное описание проблемы
Риги, аблятив и ТД не защищают от ударов тока
#### Что должно было произойти
Защищают
#### Что произошло на самом деле
НЕ защищают
#### Как повторить
Надеть инженерный риг и удариться об наэлектрилизированную дверь

**Comment by pro100kotah** [comment]
Риги инженерные еще ладно. Про атмосферные подумать нужно, вряд ли им это нужно. Но абелятив тут причем. Он тебя вряд ли заземляет или изолирует. Он же тупо лазеры рефлектит, грубо говоря зеркало.

**Comment by simb11** [comment]
потому что защита от тазеров и защита от тока эт одно и тож
