### ISSUE TITLE
Специальное ведро для швабры уборщика можно бесконечно пытаться наполнить

### ISSUE THREAD

**Issue by Fluffy-510** [TauCetiStation/TauCetiClassic#11232]
#### Подробное описание проблемы
Желтое ведро уборщика будет впитывать воду, которую в него вливают, до бесконечности, не смотря на то что больше воды хранить не может
#### Что должно было произойти
Когда воды в ведре уборщика максимум, в него больше нельзя залить воды

#### Что произошло на самом деле
Ведро уборщика полное? А в него можно вливать и вливать воды до бесконечности
#### Как повторить
Заполнять водой ведро уборщика

**Comment by volas** [comment]
Лимитки из ведра воды "надо просто добавить ..." через...

**Comment by Fluffy-510** [comment]
Я про то что ведро уборщика может хранить там 70 юнитов или сколько там, а в него можно всё вливать и вливать воду, опустощяя контейнер в никуда, но как было в ведре уборщика 70 юнитов, так и их будет 70

**Comment by DarthSidiousPalpatine** [comment]
Заполняю водой ведро уборщика а оно перестаёт заполняться и пишет что ведро полное.
Ну и воды в ведре 100 юнитов, а не 70.
В общем бага нет, закрывайте.

**Comment by Deahaka** [comment]
Я набирал ведро поставленное на тележке и всё работало как должно было, Гусев потестил ведро без тележки, как я понял, так что нужно больше подробностей как получить баг

**Comment by Fluffy-510** [comment]
> Я набирал ведро поставленное на тележке и всё работало как должно было, Гусев потестил ведро без тележки, как я понял, так что нужно больше подробностей как получить баг

На видео у меня получилось бесконечно заполнять желтое ведро в тачке уборщика:

https://user-images.githubusercontent.com/109436132/230909975-5a4a0356-535a-4905-b755-3b04f9083fb4.mp4

**Comment by Fluffy-510** [comment]
Это получается фича? Непрактичная и странная какая-то

**Comment by DarthSidiousPalpatine** [comment]
ты можешь выливать ведро на что угодно в том числе на людей

**Comment by Fluffy-510** [comment]
аааааа, теперь понял
Получается бага нет
Хотя нет, есть
Воды под тачкой нету
Но это ,наверное ,другое
