### ISSUE TITLE
Перетянул интеркомы на... Чтоооо?

### ISSUE THREAD

**Issue by DarkFurrSss** [TauCetiStation/TauCetiClassic#11261]
#### Подробное описание проблемы
При перетягивании интеркома на настенные камеры... Он смещается!
![image](https://user-images.githubusercontent.com/92409383/230798598-aa130205-313e-4164-887a-2a1aec472f61.png)

#### Что должно было произойти
Не перетянуться
#### Что произошло на самом деле
Перетянулся
#### Как повторить
Перетянуть интерком на настенные камеры
#### Дополнительная информация:
Что?
Issue reported from  Round ID: 58602 (Tau Ceti Classic (RU))
Testmerges: ```#11193 #11246 #11250 ```
Reporting client version: 514.1589

**Comment by volas** [comment]
Если проблема правда в clickplace, то меня интересует, при чем тут камеры

**Comment by DarthSidiousPalpatine** [comment]
![image](https://user-images.githubusercontent.com/21008918/230937760-8c886196-0b9c-4126-ab93-802cc1f96ded.png)
Давайте посмотрим на картинку и на картинку в посте.

Знаете как я её получил? Я поставил шкаф на место чуть правее и перетянул на него интерком.
После чего шкаф перетянул опять левее. На камеру нельзя ничего перетянуть. Я пробовал.
Конец.
