### ISSUE TITLE
Наноуи мапа бокса старая

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#11274]
#### Подробное описание проблемы
Наноуи мапа бокса старая

https://github.com/TauCetiStation/TauCetiClassic/blob/master/nano/images/nanomap_exodus_1.png

#### Что должно было произойти
Новая

#### Что произошло на самом деле
старая

**Comment by LudwigVonChesterfield** [comment]
чтобы это было "Good First Issue" думаю стоит тут расписать как эту карту обновлять @KIBORG04
