### ISSUE TITLE
Сломанные слоты в куче мусора

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1129]
#### Подробное описание проблемы
При осмотре кучи мусора, ячейки помещенных в них предметов - уходят вниз а не вправо. Из за этого экран отдаляется.
#### Что должно было произойти
Ячейки должны идти вправо.
#### Что произошло на самом деле
Ячейки идут вниз.
#### Как повторить
Осмотреть несколько куч мусора.
#### Дополнительная информация:
http://imgur.com/a/RxKhY

**Comment by Kurshan** [comment]
Уже пофикшено, осталось дождаться апдейта

**Comment by igigin** [comment]
#1109.
