### ISSUE TITLE
Конструкты не могут  point to

### ISSUE THREAD

**Issue by Fluffy-510** [TauCetiStation/TauCetiClassic#11293]
#### Подробное описание проблемы
поинт ту не работает
#### Что должно было произойти
работает, как было когда-то
#### Что произошло на самом деле
нельзя тыкать во что-либо
#### Как повторить
попытаться указать за конструкта на что-либо
#### Дополнительная информация:
Виновато удаление возможности указывать мышам?

**Comment by Fluffy-510** [comment]
tweak: Мыши больше не могут показывать пальцем.
Нет, это баг

**Comment by KIBORG04** [comment]
Нет, это фича, но может конструктам вернуть поинт ту
