### ISSUE TITLE
Корявые спрайты женщин

### ISSUE THREAD

**Issue by LiLJard** [TauCetiStation/TauCetiClassic#11298]
#### Подробное описание проблемы
Какая-то халтура со спрайтами женщин в результате которой через берцы и комбезы просвечивают носки, чулки и тд
#### Что должно было произойти
Наверное такого быть не должно
#### Что произошло на самом деле
Произошло вот такое 
![image](https://user-images.githubusercontent.com/77955747/232241401-294e6e04-cd91-45da-b0cd-3adccda2f78c.png)
![image](https://user-images.githubusercontent.com/77955747/232241437-ea655386-edde-4862-9f37-e9d4e9def8f0.png)

#### Как повторить
Зайти на сервак и посмотреть внимательно на корявые спрайты баб
#### Дополнительная информация:
Двенадцатилетних пиздюков вы обманете огромными нарисованными жопами но меня нет

**Comment by pro100kotah** [comment]
Предлагаю решение. Нужно удалить баб и оставить только мужиков.
