### ISSUE TITLE
Изолирующие перчатки не изолируют

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#11299]
#### Подробное описание проблемы
Если обмотать изолирующие перчатки проводами, то они потеряют изоляционные свойства. 
#### Что должно было произойти
Бегаешь со стангловсами и игноришь электрифицированные шлюзы. 
#### Что произошло на самом деле
Получаешь удар током и жидко пернув помираешь. 
#### Как повторить
Обмотать изолирующие перчатки проводами и получить удар током.

**Comment by AndroBetel** [comment]
не баг
