### ISSUE TITLE
Отзыв и баг о консоли с освещением

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#11317]
#### Подробное описание проблемы
https://github.com/TauCetiStation/TauCetiClassic/pull/11312

Отзыв и баг. Фича прикольная, можно на ИИ немного побаловаться, однако жаль что пока только на Исходе и цветное освещение только в баре. 

(Предложение хотя бы малф/тритор ИИ добавить возможность временное отключения освещения на станции)

А насчет бага, невозможно сменить цвет освещения у ночного режима, там кнопка связалась почему-то на основное освещение

#### Что должно было произойти
Я могу настроить освещение для ночного режима

#### Что произошло на самом деле
настраивает только для обычного режима

#### Как повторить
Побыть на ИИ и полапать консоль на исходе

#### Дополнительная информация:
Issue reported from  Round ID: 58792 (Tau Ceti Classic (RU))
Testmerges: ```#11312 #11310 ```
Reporting client version: 514.1589

**Comment by DarkFurrSss** [comment]
Было бы прикольно дать ИИ некоторые настройки в глобальном формате (Отключение света, перегруз, настройка Аир-алярм и т.п.), дабы хоть чуть чуть дать могущества ИИ, кроме как "Я создан для открывания шлюзов"

**Comment by volas** [comment]
Прикол в том, что ИИ по задумке вообще не должен был иметь доступа, а оказывается он есть... 

Вся идея помещения консоли в аплоад - чтобы один человек за всю станцию не решал, какой свет поставить. В аплоад главы ходят парой.

Пока не буду отбирать, так и быть.

**Comment by volas** [comment]
> А насчет бага, невозможно сменить цвет освещения у ночного режима, там кнопка связалась почему-то на основное освещение

Такого не вижу, меняется то что нужно. Единственный момент - после изменения настроек требуется прожать Sync APC, им нужно подтянуть новые настройки и обновить свет.

**Comment by AzzyDreemurr13** [comment]
> Такого не вижу, меняется то что нужно

Смотри, там в панели можно выбрать какого типа света сделать определенный Режим.

Default -> там стоит обычное полное освещение 
Night Mode -> стоит освещение софт

Для обеих режимов есть кнопка изменить тип освещения при включенном режиме, у обычного да она работает, НО если пытаться менять для ночного режима, то там меняется именно только основное освещение, а ночное освещение не даёт. 

Либо ты добавил лишнюю кнопку либо ты добавил кнопку которая привязана к основному освещению

(Днём зайду, сделаю скрин и покажу что имею ввиду, если сейчас не поймёшь)

**Comment by volas** [comment]
понял

**Comment by AzzyDreemurr13** [comment]
> Вся идея помещения консоли в аплоад - чтобы один человек за всю станцию не решал, какой свет поставить. В аплоад главы ходят парой.

Прикол в том, что Главам зачастую будет тогда вообще пофиг и лень на эту консоль, им проще всегда будет при активном ИИ, что-то попросить менять, чем лишний раз лезть в аплоуд, вызывать подозрения у остальных глав и сб. Поэтому здесь, лучше не убирать у ИИ доступ, просто главное, чтобы ИИ сам не заигрывался со светом сильно и не Игнорировал глав.
