### ISSUE TITLE
Снаряды летят в трубы/провода при стрельбе по ним

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#1132]
#### Подробное описание проблемы
Пули, лазоры и прочие прожектайлы летят в трубы/провода, если кликнуть по ним, что заметно ухудшает ведение боя в техах.
#### Что должно было произойти
Снаряды летят над трубами/проводами/прочим.
#### Что произошло на самом деле
Снаряды летят прямо в трубы.
#### Как повторить
Взять лазор/автомат/штуку, которая стреляет и кликнуть на трубу/провод.

**Comment by Dennok** [comment]
Вечные проблемы стрельбы.

**Comment by Dennok** [comment]
Когда уже сделают глобально чтоб стрельбы брала целью гет турф вместо кликнутого обжекта?
?

**Comment by Raschert0** [comment]
И тогда, Деннок, ти никогда не попадёшь в лежащего

**Comment by Dennok** [comment]
Вот блин, не дали стелсобаф пропихнуть.
