### ISSUE TITLE
Дух, труп, вечное заключение

### ISSUE THREAD

**Issue by DarkFurrSss** [TauCetiStation/TauCetiClassic#11324]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/92409383/233803477-ab66266a-7c91-477e-95e8-b3f668ccf911.png)
Точно не понял причин, но если смотреть за игроком и его в это время положат в морг - экран приобретет эффект слепоты и не даст смещать экран. Сама кукла госта двигается, но вот экран так и остается на контейнере морга
#### Что должно было произойти
Слепоты нет, гост летиииииииит
#### Что произошло на самом деле
~~Дух заключен вместе с трупом~~ Экран госта остается запертым вместе с трупиком в контейнере морга
#### Как повторить
Следить за игроком будучи гостом, пока его не положат в контейнер морга
#### Дополнительная информация:
Телепотрация в любом проявлении (Про админскую не знаю) не помогает твоему экрану. Лишь спавн за кого-либо
Issue reported from  Round ID: 58818 (Tau Ceti Classic (RU))
Testmerges: ```#11310 #11314 ```
Reporting client version: 514.1589

**Comment by Follint** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/9550
https://github.com/TauCetiStation/TauCetiClassic/issues/7041
https://github.com/TauCetiStation/TauCetiClassic/issues/4401
https://github.com/TauCetiStation/TauCetiClassic/issues/3233
Старый ишуй.

**Comment by DarkFurrSss** [comment]
Лишь лучше намекает насколько оперативно решаются баги..

**Comment by volas** [comment]
С точки зрения мейнтейнеров это просто не критичный баг, который легко пофиксить даже начинающему кодеру.

https://github.com/TauCetiStation/TauCetiClassic/issues/3233#issuecomment-466768284

**Comment by volas** [comment]
конкретно смотреть
```
/obj/structure/morgue/proc/close()
	if (connected)
		for(var/atom/movable/A in connected.loc)
```

**Comment by DarkFurrSss** [comment]
> С точки зрения мейнтейнеров это просто не критичный баг, который легко пофиксить даже начинающему кодеру.
> 
> [#3233 (comment)](https://github.com/TauCetiStation/TauCetiClassic/issues/3233#issuecomment-466768284)

И этот баг стоит с 19 года...
