### ISSUE TITLE
Нюка едет и тикает

### ISSUE THREAD

**Issue by Slavik2001** [TauCetiStation/TauCetiClassic#11340]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/123300305/234611539-6d59e3aa-6df3-4d81-9831-e80e92f6631e.png)
![image](https://user-images.githubusercontent.com/123300305/234611635-428091fb-a827-4f7a-841e-92af7957a04b.png)
#### Что должно было произойти
Бомба должна была остаться в бриге и не иметь возможности двигаться.
#### Что произошло на самом деле
Нюкер после активации отключил якорь и вынес бомбу из брига, после катал по космосу до самого взрыва
#### Как повторить
![image](https://user-images.githubusercontent.com/123300305/234613539-aafa6495-a992-4ec7-9674-917d16158d67.png)
Мое мнение - Зайти за нюку активировать бомбу, но при этом не вырубать окно бомбы или же во время активации вырубить якорь и продолжить активацию
#### Дополнительная информация:
Как по мне эту можно взять как фичу если в таком случае нельзя будет вытащить диск, то есть 2 варианта активации.
1 - врубить бомбу, вытащить диск и забрать его на базу, но при это отнять возможность перетягивать бомбу
2 - врубить бомбу, залочить диск в бомбе если решат ее передвигать
Если мои руки дойдут, после лени и тому подобного, может быть сам закодю :dovolen:
Issue reported from  Round ID: 58876 (Tau Ceti Classic (RU))
Testmerges: ```#11272 #11292 #11310 #11314 #11334 ```
Reporting client version: 514.1589

**Comment by Slavik2001** [comment]
Хотя это скорее узнать фича это или нет

**Comment by pro100kotah** [comment]
> Хотя это скорее узнать фича это или нет

Очевидно, что это не фича. Ведь тут целый механ с блокировкой бомбы на одном тайле есть. Который обходится здесь через баг. Но было бы неплохо сделать это фичей, как ты и предложил:

> залочить диск в бомбе если решат ее передвигать
