### ISSUE TITLE
чтобы снять все деньги с чужой карты нужно всего лишь...

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#11343]
#### Подробное описание проблемы
Можно через ПДА узнать номер чужого аккаунта, после ввести сей номер в АТМ и снять деньги, спасибо нулевой защите на банковском аккаунте)
#### Что должно было произойти
Наверное нужно знать пароль или собственно владеть картой для того чтобы вывести деньги
#### Что произошло на самом деле
можн снять все деньги с любого аккаунта
#### Как повторить
в описании сказано, разве что уточню, что узнаётся номер через опцию SEND MONEY в манифесте

**Comment by arygal** [comment]
Так можно ID карты у ГП оформлять чужие

**Comment by muWander** [comment]
так людук же делал мемы для этого.. или недоделал

**Comment by LudwigVonChesterfield** [comment]
Нужно повысить секьюрность всех аккаунтов до хотя бы "необходимо знать пароль".

Пароль можно стягивать из мемов.

**Comment by KandreyKandrey** [comment]
Что мешает раундстартом ставить 1 уровень защиты (номер счёта и пинкод требует) или 2 (карта, пинкод, номер счёта) ?

**Comment by LudwigVonChesterfield** [comment]
почему я должен раундстартом каждый раунд делать одно и то же действие которое очевидно нужно по дефолту

**Comment by KandreyKandrey** [comment]
я про это и говорю, вот тут 1(2) вместо 0 поставить

![изображение](https://user-images.githubusercontent.com/126669846/234975701-e441d16f-68b2-4141-821d-900b7932386c.png)

**Comment by LudwigVonChesterfield** [comment]
да, именно так и нужно. уровень 1 поставить
