### ISSUE TITLE
Маковые венки не создаются

### ISSUE THREAD

**Issue by Classical-User** [TauCetiStation/TauCetiClassic#11341]
#### Подробное описание проблемы
При крафте макового венка, исчезают провода и мак, без создания венка.
#### Что должно было произойти
Венок с маком, собственной персоной!
#### Что произошло на самом деле
Анигиляция проводов и мака.
#### Как повторить
Попытаться скрафтить.

**Comment by DarthSidiousPalpatine** [comment]
Почему когда ПР делает не Гисев, то его можно не тестить :dovolen:
