### ISSUE TITLE
[Proposal] Чёрный Экран После Смерти

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#11356]
https://forum.taucetistation.org/t/pamyat-klonicheskaya-ne-nuzhna/39122

почитал вот эту темку и обнаружил что никто почему-то не предложил...

После смертей которые можно нивелировать реанимацией или клонированием накидывать игроку на 3-4 минуты чёрный экран/пелену, не позволять гостаться, и слышать что-либо.

Решит 90% проблем с памятью клонов.

**Comment by AndroBetel** [comment]
в той темке игорькам не нравится не то, что госты видят все, а то, что ты заклонишься и тыкнешь пальцем в убийцу

предложенная тобой штука повлияет только если убийца будет носить сменную одежду и после убийства переоденется, но делать это иногда сложно и палевно

**Comment by LudwigVonChesterfield** [comment]
я не против чтобы триторов наказывали за то что они ведут себя как нюкеры а не как триторы

**Comment by DarthSidiousPalpatine** [comment]
> в той темке игорькам не нравится не то, что госты видят все, а то, что ты заклонишься и тыкнешь пальцем в убийцу
> 
> предложенная тобой штука повлияет только если убийца будет носить сменную одежду и после убийства переоденется, но делать это иногда сложно и палевно

сменную одежду, маску и без id, когда идёшь по коридору и каждый встречный поперечный points to unknown ТЫ КТО СНЯЛ МАСКУ, офицеры сразу тазер :dovolen:

**Comment by pro100kotah** [comment]
В чем проблема просто на уровне правил запретить людям помнить последние пару минут жизни или то что связано с его смертью. Убийцу, место и т.д. До вас это правило придумали уже и в других местах NLR называется. Зачем то, что можно логично и адекватно ограничить правилами - пытаться ограничить механом. То же правило грифа, были гении пытавшиеся ограничить механом. Это же ебаный абсурд.

**Comment by simb11** [comment]
мы стремимся к миру без правил и админов
