### ISSUE TITLE
Интенты борга меняются вместе с выбором манипулятора, через кнопки "1,2,3".

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#11355]
#### Подробное описание проблемы
У борга три слота под манипуляторы, которые переключаются кнопками "1, 2, 3". Интенты можно было переключать тыкая мышкой или на кнопку "4" по часовой. Сейчас же при выборе манипулятора выставляется интент вместе с ним. Взял пилу во втором слоте - интент синий. Взял скальпель в первом - интент зеленый. В третьем - желтый. Мешает, постоянно, делаешь операцию, переключаешь слот и вот ты уже не оперируешь, а рубишь пациента пилой, потому что у тебя по-идиотски интент переключился.
#### Что должно было произойти
Выбор интентов не работает как у хумана через кнопки "1, 2, 3, 4". Кнопки отвечают за манипуляторы и их слоты.
#### Что произошло на самом деле
Интент меняется с выбором манипулятора.
#### Как повторить
Поиграть в игру.
#### Дополнительная информация:
Очень вероятно, что эта темка дубликат. Потому что проблемы боргов фиксят месяцами. Последний критический баг фиксился 4 месяца.

**Comment by pro100kotah** [comment]
Пришить бы им выбор интента через CTRL+Циферки: "1, 2, 3, 4". Либо вернуть старый, очень топорный метод через выбор по часовой стрелке.

**Comment by KandreyKandrey** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/10928

**Comment by pro100kotah** [comment]
Ха-ха. Этому багу скоро второй месяц

**Comment by pro100kotah** [comment]
> Возьми и почини. Никто тебе баги не обязан чинить.

Брух. Теперь перечитай какую кринжатину ты высрал. Давай я не буду тебе объяснять очевидные вещи, так как не хочу тратить на тебя время.
