### ISSUE TITLE
Лярва не может вылезти из зараженного хумана

### ISSUE THREAD

**Issue by SkLepP** [TauCetiStation/TauCetiClassic#11363]
#### Подробное описание проблемы
Лярва не может вылезти из зараженного хумана после созревания
#### Что должно было произойти
Лярва должна суметь прогрызть хумана и вырваться из него
#### Что произошло на самом деле
Лярва не может вылезти из зараженного хумана после созревания

#### Как повторить
Заразить лицехватом хумана и попытаться выраваться после созревания
#### Дополнительная информация:
р

**Comment by LudwigVonChesterfield** [comment]
#11272 
@simb11 

Уже пофикшено?

**Comment by simb11** [comment]
нет ещё

**Comment by simb11** [comment]
после обновления билда должно починиться
