### ISSUE TITLE
[Proposal] Нерф особки на брейнрот

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#11361]
#### Подробное описание проблемы
Особка накидывает слишком большой дамаг мозгу из-за чего персонаж который заспавнился на велосити просто не может улететь на станцию, так как у куклы не хватает мозгов нажать кнопку для полета.
![image](https://user-images.githubusercontent.com/19796920/235358382-e447808d-a099-47d9-bc34-56b18de36bbe.png)

В связи с этим предлагаю снизить дамаг с этой особки на половину.

**Comment by GiantSpider527** [comment]
про ролл данной особки игроки забывают после 1 похода в медбей

**Comment by LudwigVonChesterfield** [comment]
думаю скорее надо чтобы она не выпадала лейтджоинам, потому-что у них нет возможности позвать кого-то помочь.

**Comment by Deahaka** [comment]
Не актуально, пофикшено
