### ISSUE TITLE
Урон от оружия увеличился в два раза

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#11369]
#### Подробное описание проблемы
ПР #11272 в тестмерже сломал урон от оружия, не тестировал всё, но лазеры точно наносят в два раза больше урона. Статистика выстрела из обычного лазера по кукле:
#### Что должно было произойти
Без ПРа
Analyzing Results for Unknown:
  Overall Status: 60% healthy
  Key: Suffocation/Toxin/Burns/Brute
  Damage Specifics: 0 - 0 - 40 - 0
Body Temperature: 36.4281°C (97.5706°F)
Localized Damage, Brute/Burn:
  Chest: 0  - 40
#### Что произошло на самом деле
С ПРом
Analyzing Results for the unknown:
  Overall Status: 20% healthy
  Key: Suffocation/Toxin/Burns/Brute
  Damage Specifics: 0 - 0 - 80 - 0
Body Temperature: 25.1535°C (77.2762°F)
Localized Damage, Brute/Burn:
  Chest: 0  - 80

**Comment by AndroBetel** [comment]
да все правда, у левольвера и калаша тоже в два раза больше урона

**Comment by muWander** [comment]
РП урон

**Comment by SiveanBen** [comment]
У плазменого дробовика 200 урона по голому телу, симбака гений, я поддерживаю его убийство билда, или чё это ваще такое

**Comment by SiveanBen** [comment]
И ещё смешное, хос в дермалку получает 30 урона в голову от лазера, и 12.7 в тело
