### ISSUE TITLE
[Bug] Маяк полигона

### ISSUE THREAD

**Issue by nxrdcity** [TauCetiStation/TauCetiClassic#11376]
#### Подробное описание проблемы
После подрыва лимиток на полигоне не выписывает через маячок в логах поинты. Камера полигона показывает космос, арматуру и маячок в центре. Начисление поинтов на консоль лабы также не происходит.

#### Что должно было произойти
Нормальный подрыв лимиток и начисление поинтов на консоль лабы.

#### Что произошло на самом деле
РНД без поинтов и разработок.

#### Как повторить
Сделать лимитки -> запустить на полигон -> взорвать их.

#### Дополнительная информация:
димдрим ответил на пмку: Маячок забаговал похоже. / Так и есть, на админские бомбы он тоже не реагирует.

**Comment by Deahaka** [comment]
Надо сделать фичей #9323

**Comment by Mercurialaste** [comment]
повторить не удалось

**Comment by KIBORG04** [comment]
Мб связано с кодер-ивентом на новые взрывы. Ивент кончился. Если ещё раз будет багулина, то переоткрою
