### ISSUE TITLE
[Proposal] Механ очков детектива

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#11373]
Детектив заходит на место преступления, включает свои очки и они в отсеке где стоит детектив показывают ему следы оставленные кем-угодно.

![imgonline-com-ua-Black-White-0JjxpVh3KDi](https://user-images.githubusercontent.com/96499407/235849265-d0c404fb-7d2c-430e-a562-9e9d218b77eb.jpg)
<details>
<summary>
Как это сделать?
</summary>
Создаём подсистему, которая будет хранить "улики". Она спустя какие-то пары минут будет удалять старые следы, но продолжать записывать новые.
Когда нуарные очки включаются, они начинают видеть атом-худы обьектов в одной зоне (если нельзя то во всех), как угодно можно через цикл или другие способы. Ориентир это как шахтёры видят руду, как ИИ видит наэлектризованные шлюзы.
Куклы при своих действиях типо Move(), pickup(), attackby(), attack_hand() и многих других добавляют на предметы или турфы компоненты с их текстовой и другой информацией. Компонента слушает экзамайн-сигнал и имеет проверку на носителя нуарных очков. Если проходит, то выдаёт информацию юзеру.
Информация записывается в момент создания компоненты. Пока идея делать кучу проверок и на каждую своё описание компоненты, что-то типо:

![0000000000000000000000000000000000](https://user-images.githubusercontent.com/96499407/235851836-59f052d3-30cc-4562-a469-19f5856eb65a.png)

и так далее
</details>

**Comment by pro100kotah** [comment]
Бля, ахуенно. Ставлю класс и пять звездочек одноклассников.

**Comment by Deahaka** [comment]
Надо было думать о том зачем оно надо.
