### ISSUE TITLE
[Proposal] Баланс тулбокса. Потерянное поколение.

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#11391]
### Подробное описание проблемы
Тулбокс потерял своё сакральное применение в виде оружия ближнего боя и теперь является не более чем рюкзаком который нельзя надеть на спину (говном). Это не интересно. О тулбоксе слагают легенды, в честь тулбокса называют современные чемпионаты по робасту, тулбоксам придумывают фичи для создания чего-то большего чем спрайт синей коробки, но мы в этом не участвуем.
### Как изменить ситуацию?
Давайте увеличим привлекательность тулбокса как оружия ближнего боя. Но в условиях когда нужно конкурировать с намного более выгодными соперниками (огнетушитель, копьё, станпрод, бутылка, острое/режущее оружие, станбатон, лазерный и культисткий мечи) увеличением урона ситуацию практически не изменить никогда. Остаётся либо нивелировать его недостатки (создать не интуитивно понятную фичу что тулбокс не замедляет и возможно всё таки добавить ещё урона), создав по сути копию огнетушителя, либо дать ультимативный эффект от удара.

**Какие могут быть эффекты от удара?**
Это может быть статус-эффект (оглушение, ослабление, сон, боль), эффект откидывания, конфуз как у флешера, сопутствующий урон на части тела/органы, а может быть это накидывание какого-нибудь эффекта (трейта)! Разберём какой нам лучше всего подходит:
1. Оглушение, ослабление, сон, боль - механики создающие стратегию стан-ту-вин; уже используются в станпроде, бутылке, станбатоне и во всех высокодамажащих предметах.
2. Откидывание - механика оказывающая неимоверный эффект на жертву, который кроме как "ублюдским" назвать невозможно; дезориентирует, станит и к тому же делает недоступным контроль позиции в файте кукле. Бесбольные биты с ТГ = хуета.
3. Конфуз как у флешера - механика оказывающая неимоверный эффект на неподготовленную жертву. Неподготовленную это ту, которая никогда не охотилась на генокрадов в раунде с ними, не играла на борге или не играла на кадете в полицейского. В остальных же случаях это всё нивелируется простыми доступными всем действиями, а также химией, которой балуются боевые космонавты. Тулбокс не станет оружием ассистентов, которые хотят подраться не со смолгеями в баре, так как против другого противника эффект будет с высокой вероятностью не ультимативным.
4. Сопутствующий урон на части тела/органы - равносильно увеличению урона, а также имеет потенциал быть крайне нереспектабельным для всех игроков, которые от пары ударов получат слепоту/скоропостижную смерть от сердца/брейндамаг.
5. Накидывание эффекта через трейт. На этом остановимся дольше всего, ведь эффект трейтом можно выдумать интересный и почти какой захочешь. Например, это может быть Клямзи как у клоуна. Неуклюжесть которая будет накидываться навсегда это не смешно, а вот если на время (!!!), то уже обещает быть смешным.

### Собственно идея
Каждый удар тулбокса навешивает на цель временный трейт неуклюжести (сделать статус эффектом что-ли как-то?). Время навешивания изначально думал секунд 5, но возможно 4 будет в самый раз. Неуклюжесть делает ответный удар от оппонента маловероятным, что позволяет бороться с любым видом оружия, но только в ближнем бою. Бороться с этим можно не подпуская врага с тулбоксом к себе, а если подпустил - отбежать от него за время действия эффекта и ответить.

Вот так просто можно создать оружие которое сможет конкурировать с любым другим, но которое не использует механики оглушения или ему подобные, давая оппонентам пользователя время на реакцию и шанс выйти победителем в дуэли.

### Обсуждение
[Было проведено на форуме день назад](https://forum.taucetistation.org/t/obsuzhdenie-golosovanie-tulboksnye-vojny-vozvrashhenie-dzhedaya-pr-na-podhode/39266), но возможно у кого-то есть ещё хороших мыслей, так что буду следить.

**Comment by pro100kotah** [comment]
Блять, да дайте вы тулбоксу высокий шанс кнока и все. У нас кнок итак занерфлен броней, условного ГСБ ты так просто не кнокнешь. Или какого-нибудь ЕРТшника с нюкером, потому что из-за переработки дефа от мили, кнок теперь так не пробьется. (Вспоминаем мемы, где нюкер мог получить кнок от удара картонной коробкой). И все. Пусть дерутся между собой. Все еще будет хорошим оружием среди обычного кекипажа. Петушитель - прошлый век. Бутылка тоже. Тулбокс - вот оно. Тулбокс будет также силен и популярен, как ранее о нем слагали легенды.

**Comment by LudwigVonChesterfield** [comment]
я не знаю что это заявка в админа или аппеляция к перме

но я ЗА.
