### ISSUE TITLE
Механическая кисть, которую оторвало ударом тока от двери, вечно чинится проводами, хотя её нет

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#114]
Originally reported by: **Yulian Reptile (Bitbucket: [YulianR](http://bitbucket.org/YulianR), GitHub: Unknown)**

---

Так вышло, что протезы пиздецки забагованные. Один из багов - при ударе током одна из кистей механических дамажится на 30 берн дамага, причем она отваливается. В итоге хуман бегает в болевом крите с не проходящим дамагом в отсутствующей кисти. 
Фиксится проводами, однако рука как была оторвана, так и остается.

~~Рука должна дамажиться, но не отрываться.~~
Рука не должна чинится проводами, так как ЕЁ НЕТ.

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/114

**Comment by Raschert0** [comment]
Сегодня повторилось. Человеку оторвало робокисть (рука осталась на месте). Рука чинилась проводами, но не восстанавливалась (что логично)

**Comment by Skippeer12** [comment]
Всё уже давно починили, а закрыть забыли.
![image](https://user-images.githubusercontent.com/18488106/35792770-65c4dec4-0a57-11e8-8cd3-89f7cf9f61d4.png)
Билд на котором это проверялось без нового механа от Куршана, но даже там нет этого бага.
