### ISSUE TITLE
Неправильный стык стен с окном

### ISSUE THREAD

**Issue by NinjaPikachuska** [TauCetiStation/TauCetiClassic#11405]
#### Подробное описание проблемы
Тайтл
#### Что должно было произойти
Все красиво, гладко и нет страшного угла
#### Что произошло на самом деле
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/89906909/a49378d0-9fb9-4f2c-b330-c5dacdb4e4df)

#### Как повторить
Зайти на прометей/построить такую конструкцию

**Comment by KatoMarika** [comment]
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/18484142/969a4488-207d-4915-9ab1-0e3fe683538c)
Старый спрайт, на новом потеряло актуальность.
