### ISSUE TITLE
Контузия ушей forever and ever.

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#1142]
#### Подробное описание проблемы
БАХ! Позади тебя лопается танкер с топливом, а через минуту подкидывают светошумовую. Результат - ты оглох навечно! Никакие игровые методы не способны вернуть тебе слух. Такие дела.

#### Что должно было произойти
Обычно контузия проходит и ты приходишь в норму.

#### Что произошло на самом деле
Читай выше.

#### Как повторить
Бахнуть на соседнем тайле от себя танкер, потом подкинуть флешку.

#### Дополнительная информация:
Все было прекрасно и ничуть не больно.

**Comment by WallShrabnic** [comment]
Это фича же

**Comment by Kurshan** [comment]
Игровая условность же. У нас и после нескольких маслин можно посидеть в меде и пойти воевать как ни в чем не бывало. Бей-система и там довольно хардкорна.

**Comment by P-20** [comment]
@WallShrabnic , не оставляйте бессмысленных комментариев, во избежание блокировки в данном репозитории. Это первое и последнее предупреждение.

**Comment by WatlerJe** [comment]
Если это есть фича, то должны быть законные методы ее лечения. Как мне известно операцию по восстановления слуха в бэймеде провести нельзя.

**Comment by ZVee** [comment]
Есть метод и он всего один. Касательно пермапотери слуха - действительно фича, просто словить ее крайне проблематично в общем-то, если конечно там не завезли флешкомет в повседневный оборот.

**Comment by ZVee** [comment]
Таки ошибся, даже "в том секретном месте меда" не снять это дело, т.к то секретное место снимает лишь дамаг, а как болезнь - не умеет.
Так что да, надо бы или химию какую прикрутить (слишком легкий и мобильный метод для редкой вещи), или "в том секретном месте меда" или в хирургию добавить. Последнее наверно былоб интереснее всего.

**Comment by Lancer411** [comment]
Тут только перидаксону добавлять хил взорвавшихся барабанных перепонок.
Если урона больше 25 единиц на уши пришло, то это перманентная глухота. Для этого нужно чтобы под ногами/в руках одновременно 4-5 флешек жахнуло.

**Comment by Skippeer12** [comment]
Я пытался повторить как описано в баг-репорте. Взорвал фуелтанк, потом флешку. Контузия проходит через минуту или две.
![image](https://user-images.githubusercontent.com/18488106/35794849-ed1b14ee-0a5f-11e8-8689-3795b49e9fee.png)

**Comment by WatlerJe** [comment]
Братан я хуй знает

**Comment by Motzord** [comment]
Ишью можно закрывать, закоден волшебный реагент лечащий уши
