### ISSUE TITLE
Неправильный рецепт крафта у повязки на руку

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#11447]
#### Подробное описание проблемы
В рецепте повязки указан мелок и ткань, но для крафта требуется баллончик с краской
#### Что должно было произойти
СОЗДАНИЕ
#### Что произошло на самом деле
Требуется другой предмет
#### Как повторить
Следовать рецепту крафта 
#### Дополнительная информация:
Исправьте описание рецепта, требование или сделайте возможным оба варианта

**Comment by AgRevol** [comment]
Бамп. Может добавить гуд ферст ишью?
