### ISSUE TITLE
проблемы станции-выживача

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#11448]
Проблемы исполнения:
1. То, что в редакторе выглядит как дорожка из крови
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/44546836/e4a66bd8-db80-4154-b0bb-2414af1de36a)
В игре выглядит вот так (почеркушки кровью)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/44546836/2dbb0fde-f05c-4845-844b-86bd856ccfda)

2. Карпы, которые должны быть большими мертвыми рыбами, выглядят вот так: 
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/44546836/496b19c8-852c-4f85-a82a-4cb40d1d21f8)

Проблемы концепции:
1. Оружие добыть очень и очень легко. Тебе буквально ничего не нужно делать, чтобы залутать прокачанный еган и тяжелый скафандр (с защитой от мили в 75!!!!), чтобы потом нагнуть туповатых ксеносов, умирающих с трех выстрелов лазером.
2. Большинству игроков не хочется выживать на станции, аутируя в строительство - этим, в принципе, можно и на локалке заниматься, или же на Исходе. Те, кому не хочется выживать - летят на станцию и в раунде появляется непонятный чел в боевой броне и с арсеналом в жопе. По хорошему его СБ должно арестовать, но их одежда под скафандром похожа на форму других профессий и их частенько игнорируют. 
3. Выбор имени - это просто пиздец. Я лично считаю это проблемой и во всех других случаях (ОБР, нюка, засланник во время банд), но тут этот вопрос имеет легкий ответ. LCR (чё это значит вообще?) - станция НТ, имена должны быть как у обычных сотрудников, и всяких Нагибаторов228 в должности Старшего Медика быть не должно. Поэтому лучше генерить случайных кукол. 

Мои мюсли. На правильность их не претендую, но хотя бы баги с исполнением стоит пофиксить.

**Comment by LudwigVonChesterfield** [comment]
было бы круто если бы улететь со станции было бы сложно по тем или иным причинам.

**Comment by Tap0r** [comment]
> Оружие добыть очень и очень легко. Тебе буквально ничего не нужно делать, чтобы залутать прокачанный еган и тяжелый скафандр (с защитой от мили в 75!!!!), чтобы потом нагнуть туповатых ксеносов, умирающих с трех выстрелов лазером.

Я писал несколько раз и симбаке и не только ему, а в целом. Что идеальный концепт это некая метроидвания. Чтобы челикам не был доступен весь комплекс сразу, а только небольшая часть и их задача бы состояла в поиске инструментов для открытия следующих секций. Типо ломом открывать обесточенные шлюзы. Некоторые шлюзы на болтах, поэтому нужно питание подать и пульт управления или отвертку с кусачками раздобыть. И тд и тп. И оружие в идеале должно находиться ими в конце пути, когда они уже восстановили электропитание и открыли большинство зон, где противников нет.

**Comment by volas** [comment]
мне нравится идея метроидвании, в финале это мог бы быть гейтвей с возможностью запуска (потому что шаттлы сложно), и рация с частотой станции попросить станцию включить свой. ~~Потом выпилить телесаенс и/или добавить овермап, что бы это имело смысл.~~
