### ISSUE TITLE
Врачи стартуют раунд без аптечек

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#11451]
#### Подробное описание проблемы
Парамедики начинают раунд без красных аптечек, врачи без белых
#### Что должно было произойти
Аптечка при старте раунда
#### Что произошло на самом деле
Пустые лапки
#### Как повторить
Начать раунд за врача
#### Дополнительная информация:
Врачи на велосити спавняться с аптечками нормально

**Comment by Naroke** [comment]
Пускай это будет фичей. Повысится необходимость в складе меда и в карго, если аптечек на склад не завезли. Ничего плохого я не вижу

**Comment by ViDLiathan** [comment]
Отвратительные у вас фичи.

**Comment by simb11** [comment]
должно починиться после обновления сервера

**Comment by ViDLiathan** [comment]
> должно починиться после обновления сервера

Какого именно? Всё ещё нет раундстартовых аптечек
