### ISSUE TITLE
Нет Мудлета Одиночества

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#11463]
#### Подробное описание проблемы

В игре есть система поощряющая игроков время от времени разговаривать друг с другом. По задумке если дольше 5-и минут ни с кем не говорил - становится чутка грустно, а если дольше 10-и минут - совсем одиноко.

Но эта система не работает и вот почему:

https://github.com/TauCetiStation/TauCetiClassic/blob/c0e1e87090f2d27c485186c68ec0a2ff2520ccc1/code/modules/mob/living/carbon/human/say.dm#L11

здесь делает первый вызов, он должен засетаппить изначальный 5-и минутный таймер.

https://github.com/TauCetiStation/TauCetiClassic/blob/c0e1e87090f2d27c485186c68ec0a2ff2520ccc1/code/modules/mob/living/carbon/human/say.dm#L67

здесь мы проверяем по сути изменился ли статус. но так как у нас уже стоит SOCIALSTATE_NORMAL (1) и мы ставим SOCIALSTATE_NORMAL (1) эта проверка не прокает, из-за чего set_social_status не вызывается, из-за чего не появляется таймер одиночества.

В итоге куклы одиночество не испытывают, хотя должны были бы.

#### Что должно было произойти

Через 5 минут без разговоров кукле грустно, через 10 очень грустно

#### Что произошло на самом деле

Этот мудлет не появляется так как система не рабоает

#### Как повторить

1. Заспавнить куклу
2. Подождать 5 минут (или поменять в коде чтобы меньше)
3. Убедиться что мудлета нет.

Бонус, как проверить что вы пофиксили баг:

1. Заспавнить куклу
2. Подождать 5 минут
3. Убедиться что мудлет есть
4. Заспавнить ещё одну куклу, сказать фразу
5. Убедиться что мудлет пропал

**Comment by pro100kotah** [comment]
Ну и слава богу, что он не работает. Вырезать бы вообще эту систему ухудшения и улучшения настроения от одиночества. Не понимаю почему игрокули топят за то, чтобы играть с обоссанным фильтром на экране.
