### ISSUE TITLE
Иконки алиумов

### ISSUE THREAD

**Issue by MrFoxik** [TauCetiStation/TauCetiClassic#1147]
#### Подробное описание проблемы
Баг иконок за развивающегося внутри хумана грудолома.
#### Что должно было произойти
Иконки должны идти стабильно, иметь нормальную последовательность.
#### Что произошло на самом деле
Иконки накладывались друг на друга, рандомно прыгали от только что зараженного к выеданию груди.
#### Как повторить
Заразить за лицехвата тело и наблюдать приступы рандома.

**Comment by RichardJones1** [comment]
Нужен тестовый фидбек

**Comment by T6751** [comment]
Думаю уже не актуально
