### ISSUE TITLE
Закрашенные Краской Камеры Не Включаются

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#11473]
#### Подробное описание проблемы

Камеры которые обилил из спрея краской не включаются спустя какое-то время, а должны.

#### Что должно было произойти

1. На камеру пшикают краской
2. Камера выключается потому-что закрашена
3. Через какое-то время краска сползает
4. Камера включается снова

#### Что произошло на самом деле

1. На камеру пшикают краской
2. Камера больше не включается

#### Дополнительная информация:

Я бы предложил чтобы они закрашивались на любое число от 5-и до 10-и минут.

**Comment by Deahaka** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/10157

Задумывалось и используется как средство борьбы с камерами, при этом чинится 3-мя кликами хим-машины, двумя кликами любого инженера, дрона или инженерного борга.

Не совсем понимаю почему должно быть на время, кроме того что так было раньше для краски из ведра (а баллончик ничего не делал). Краска из ведра не закрывает обзор, а только меняет цвет камеры.

Закрою так как не баг.
