### ISSUE TITLE
Проблемы с ГРАФОНИЕМ (Нюковским)

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1148]
#### Подробное описание проблемы
Графоний сломан. Портится разрешение экрана, за алиума не могу двигаться, все мартышки на ресёрч аутпосте передохли, хотя не должны
#### Что должно было произойти
Разрешение не изменятся, на уровне астероидов тоже не должно быть смертей
#### Что произошло на самом деле
Разрешение изменилось, мартышки умерли, двигаться не могу (но жив)
#### Как повторить
Во время взрыва нюки находится на астероиде
#### Дополнительная информация:
Там ещё высветилось You managed to survive
http://i.imgur.com/JjaSQJA.png
http://i.imgur.com/slBb6W7.png

**Comment by Skippeer12** [comment]
Мартышки не подохли, а просто упали.
Так же и ты, ты можешь хагать в таком положении и делать другие действия в которых не задействована ходьба.

Фиксить же не надо, рестарт через 60 секунд же, же.

**Comment by P-20** [comment]
Сейчас бы нюкеров на их базе, волной от взрыва кнокало

**Comment by Skippeer12** [comment]
Тут кто-то костыль прикрутили. Всех мобов привязывает к невидимой кровате.
![image](https://user-images.githubusercontent.com/18488106/35795065-a1782f30-0a60-11e8-9dec-cb86b98a7f02.png)
