### ISSUE TITLE
Psychiatrist's jumpsuit не имеет спрайта для толстых.

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#1149]
#### Подробное описание проблемы
Толстый психиатр спавниться голым, без ИД карты и ПДА,
#### Что должно было произойти
Психиатр с ожирением должен спавниться в одежде
#### Что произошло на самом деле
На жирном теле только халатик.
#### Как повторить
Зайти за толстого психиатра конечно же (ну или психолога).
#### Дополнительная информация:
У мима вместо спрайта одежды в полоску серая униформа, как и у поварской, если выбрать Roll Down

**Comment by omejka** [comment]
Вот
[http://www.filedropper.com/psychs_1](URL)

**Comment by omejka** [comment]
Вот
<a href="http://imgur.com/1DFyJvo"><img src="http://i.imgur.com/1DFyJvo.png" title="source: imgur.com" /></a>
[Скачать](http://www.filedropper.com/psychs_1)
