### ISSUE TITLE
Отсутствует пульсач для мехов в фабрикаторе

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1150]
#### Подробное описание проблемы
Невозможно собрать пульсач в фабрикаторе, его нет даже на топовых техах
#### Что должно было произойти
Пульсач есть и его можно повесить на меха
#### Что произошло на самом деле
Пульсача нету
#### Как повторить
Исследовать всё на максимум, обновить фабрикаторы в роботике и страдать
#### Дополнительная информация:
N/A

**Comment by Skippeer12** [comment]
Он есть.

**Comment by Olt1771** [comment]
Он есть. Кодеры не палите

**Comment by JamsMor** [comment]
Прости нас, Олт, мы всё проебали...

**Comment by WallShrabnic** [comment]
Мне даже удалось один раз с него пострелять, но больше я его не видел

**Comment by WallShrabnic** [comment]
Он таки есть
