### ISSUE TITLE
Игрушечный даблсворд не игрушечный

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#11501]
#### Подробное описание проблемы
Игрушечный даблсворд блокирует и отражает лазеры.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/57403011/a57e73aa-ae21-4a47-b592-52d09290edd0)
#### Что должно было произойти
Игрушечный даблсворд вообще не защищает от лазеров и не блокирует удары в мили.
#### Что произошло на самом деле
Игрушечный даблсворд работает как настоящий, но только не дамажит.
#### Как повторить
Взять даблсворд без урона, включить его, впитать лазер.
#### Дополнительная информация:
#59488 конец раунда.

**Comment by KIBORG04** [comment]
У нас нет игрушечного дабл есворда

**Comment by ViDLiathan** [comment]
Разве это не обычный даблесворд, который педально сделали без урона? Фичи с отражением и сваркой дверей всё равно остаются.

**Comment by KIBORG04** [comment]
Лан, тогда закрою
