### ISSUE TITLE
[Proposal] Способ получения дюралевых семян.

### ISSUE THREAD

**Issue by qqqZXzz123** [TauCetiStation/TauCetiClassic#11513]
Семена Durathread(дюралевая нить) добавили, но способ их получения неизвестен.

Нужно добавить durathread в экзотические семена, чтобы можно было заказать их в карго.

**Comment by TryXAH** [comment]
> но способ их получения неизвестен

Вроде все уже знают, что из пшеницы мутирует. Но в карго можно и добавить, почему бы и нет

**Comment by LudwigVonChesterfield** [comment]
лан
