### ISSUE TITLE
[Proposal] Акции карго

### ISSUE THREAD

**Issue by Naroke** [TauCetiStation/TauCetiClassic#11521]
Добавить возможность продавать аккаунту карго аккаунту карго акции  и с него же покупать эти самые акции. Как мне кажется, это повысит важность отдела карго в качестве инструмента для заработка, ведь можно в начале смены купить несколько акций, что повысит начальный бюджет отдела, а после получать деньги с этих самых акций. Возможно грузчики с КМами перестанут сразу продавать ящики со склада в надежде на получение начального бюджета.

**Comment by LudwigVonChesterfield** [comment]
научили как такое делать?

Если да, расскажи всем! Такая возможность в игре есть просто она неудобная и незадокументированная

**Comment by Mercurialaste** [comment]
Мне кажется, Тау испортило Людука.
