### ISSUE TITLE
Проблемы с апц.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1152]
#### Подробное описание проблемы
Если построить новый отсек полностью в космосе, назначить зону и поставить апц - консоли и шлюзы не будут работать. Только свет от ламп (которых тогда еще не было) судя по описанию апц работал. С помощью педальной магии, мне починили это говно, но все же попросили написать сюда.
#### Что должно было произойти
После назначении зоны, апц должно ловить все шлюзы, консоли и лампы в радиусе зоны.
#### Что произошло на самом деле
Консоли и шлюзы не работали.
#### Как повторить
Построить мини-отсек в космосе, назначить зону с помощью блюпринта, поставить любую консоль, шлюзы и апц. Посмотреть как работает.
#### Дополнительная информация:
http://imgur.com/a/arM4e

**Comment by Dennok** [comment]
Эх. ещеб инфу как это починили.

**Comment by Kurshan** [comment]
там референс на зону у АПЦ неправильный стоит. А у новой зоны референс на АПЦ просто в null'e

**Comment by Dennok** [comment]
.ясненько, проблемы коннекта апц и зоны.

**Comment by Dennok** [comment]
DA DA DAA Avata4 походу апц поставил ДО того как построил зону.

**Comment by Skippeer12** [comment]
Не знаю как, но новые зоны через чертежи работают как когда.

#893

**Comment by Avatar4** [comment]
Может двери были открыты в спейс и посчитало будто зона уходит и в спейс?

**Comment by Dennok** [comment]
Невозможно, оно не пропишет зону если она слишом большая или имеет границу с спэйсом.
могу посоветовтать только строить все только после прописи зоны. Граници с спейсом закрыть стеклянной панелью.

**Comment by Avatar4** [comment]
Или построить сначала внешние шлюзы - прописать зону и затем делать остальное.
