### ISSUE TITLE
Лог Экзамайна выводится ПОСЛЕ сообщения о том что ты осмотрел

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#11530]
#### Подробное описание проблемы

см. название

#### Что должно было произойти

Player осматривает что-то.

This is что-то

#### Что произошло на самом деле

This is что-то

Player осматривает что-то.

#### Дополнительная информация:

чат же должен быть в хронологическом порядке, сначала осмотрел, потом увидел.

**Comment by muWander** [comment]
мне кажется нынешний вариант неплох, так как экзамайн особенно людей занимает много места в чате и на маленьких мониторах не растянув чат можно не увидеть эту строчку если она перенесется вверх, а фидбек игроку важен

**Comment by TEXH4Pb** [comment]
> мне кажется нынешний вариант неплох, так как экзамайн особенно людей занимает много места в чате и на маленьких мониторах не растянув чат можно не увидеть эту строчку если она перенесется вверх, а фидбек игроку важен

Да, очень важно узнать о том, что ТЫ только что осмотрел то, результат экзамайна чего тебе и так только что выдало.

**Comment by Textolite** [comment]
Хорошо, когда на тебе очки. И твой взгляд на предметы видят окружающие.

**Comment by AzzyDreemurr13** [comment]
Людвик, ты всё ещё думаешь, что стоит, чтобы экзаменейт был выше?

Я согласен с теми, кто говорил выше, что это не то чтобы бы баг.

Я бы сказал, что здесь на вкус и цвет, товарищей нет.

**P.s.**
(Я бы закрыл это ишуй, не настолько критично, чтобы менять и вешать как первый ишуй. Если по факту, тут нет смысла фиксить)

**Comment by DarthSidiousPalpatine** [comment]
> Хорошо, когда на тебе очки. И твой взгляд на предметы видят окружающие.

Ты головой на предмет крутишь прост

**Comment by Udokun** [comment]
Замержили, закройте ишью.
