### ISSUE TITLE
У боргов сломана возможность пришивать ноги хуманлобби

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#11539]
#### Подробное описание проблемы
Борг после взорвавшегося офицера в бриге, достает ногу и не может пришить ее офицеру обратно
#### Что должно было произойти
Борг может пришить ногу офицеру и тот может уйти со своей ногой
#### Что произошло на самом деле
Борг не может ибо по какой-то причине пила отказывается отрубать отрубок ноги офицера и продолжать далее операцию
#### Как повторить
оторвать конечность кукле и попытаться обратно пришить конечность за борга
#### Дополнительная информация:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/f7f644e1-6e9b-44b3-98b2-c294f2b0a784)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/225acf4a-6d8a-4435-b1b9-723840bba2ad)

Issue reported from  Round ID: 59629 (Tau Ceti Classic (RU))
Testmerges: ```#10434 #11272 #11483 ```
Reporting client version: 514.1589

**Comment by Mercurialaste** [comment]
а ты снять с него униформу не думал?

**Comment by Mercurialaste** [comment]
*(Бтв, бага нет, как минимум на садне повторить не удалось. Хотя судя по скрину, просто не сняли униформу для проведения операции.)*

**Comment by AndroBetel** [comment]
оп нуб
