### ISSUE TITLE
[Предложение]: F2

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1155]
У меня самое охуенное предложение на всей Тау-Ките. ПОМЕНЯЙТЕ ХОТКЕИ ООСА. Пожалуйста! Переложите его на F10 что бы уже НАВЕРНЯКА. 1000 игроков бывают схватывают приступ долбоеба и прожимают F2 вместо F3 и выдают фразу вроде "Traitor says: "Ну я короче снес бошку офицера в техах рнд" или что-то типа этого.
Прошу! Подумайте!!1

**Comment by DeadOberst** [comment]
Эх.

**Comment by StrikS** [comment]
Приорити: критикал.

**Comment by dearprincesscelestia** [comment]
Пожалуйста да.

**Comment by Avatar4** [comment]
И еще хоткеи для общения на языке свое расы :peka:

**Comment by ZVee** [comment]
Раскрываю очень тайную фичу - если замутить себе ООЦ (не всмысле педально, а preferences>Show/Hide OOC, то в него также нельзя и писать. Тоже самое и с ЛООЦ. Минус очевидный, но вполне равноценный обмен, чтобы случайно потом от педалей по шапке за мимочат не получать.

Так что можно считать что тема resolved в той или иной степени.

**Comment by Avatar4** [comment]
Ты действительно думаешь что кто-то закрывает себе ООС? И судя по желанию остальных, это более чем востребовательная функция.

**Comment by igigin** [comment]
>Ты действительно думаешь что кто-то закрывает себе ООС?

Но ведь закрывают.

**Comment by ZVee** [comment]
>Ты действительно думаешь что кто-то закрывает себе ООС?

Суть не в этом, а в том что это отключает тебе функцию писать что либо в ООЦ, минус в том что ты его и видеть перестаешь, но если не хочешь мазать из-за того что не заметил как нажал ф2 вместо ф3 - то решение есть.
