### ISSUE TITLE
У парамедов есть доступ к автолату карго но не конвееру

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#11566]
Доступ парамедов в "карго" обусловлен якобы тем что они спасают трупики с конвеера.

Но есть одна беда, к конвееру они не могут подойти, а к автолату чтобы воровать работу у каргонцев могут.

Рекомендую поменять доступы на шлюзах таким образом, чтобы парамедик не мог подойти к карго автолату, но мог к конвееру.

**Comment by LudwigVonChesterfield** [comment]
к автолату точно не по задумке доступ, может я не прав и это не на всех картах такая проблема или это было следствиями конкретного раунда.

**Comment by Mercurialaste** [comment]
Bruh. Вообще, мне даже интересно что парамед может себе напечатать только в карго, чтобы туда врываться.
А так, можно просто сам автолат перенести в док или на склад. Или как предлагал Зеро, вообще удалить.

**Comment by ViDLiathan** [comment]
Окружите автолат стеклом и дверцу сделайте

**Comment by pro100kotah** [comment]
> Окружите автолат стеклом и дверцу сделайте

Да ее же просто сломают...

**Comment by ViDLiathan** [comment]
ВАУ
