### ISSUE TITLE
Маулер не может попасть в цель, если она стоит в радиусе двух тайлов от него.

### ISSUE THREAD

**Issue by Nerevrin** [TauCetiStation/TauCetiClassic#1156]
#### Подробное описание проблемы
Маулер получает пиздюль от болонеров и рембачей и может отвечать только ракетами.
#### Что должно было произойти
Маулер должен убивать неугодных и в мили зоне.
#### Что произошло на самом деле
Маулер не убивает неугодных в мили зоне.
#### Как повторить
Сесть в маулера, попробовать попасть в цель на соседних тайлах или в цель, которая в двух тайлах от него.
#### Дополнительная информация:
Может и на других мехах так, не уверен.

**Comment by Avatar4** [comment]
Надо было хармом бить просто.

**Comment by Raschert0** [comment]
Уточню, что на расстоянии 1 м он сопокойно давит рукой болонеров.

**Comment by Olt1771** [comment]
Напомню что пулемет сломан и не наносит урона от слова совсем, так что пофиксите(даже тот что печатается)

**Comment by Kurshan** [comment]
#1572
