### ISSUE TITLE
Не работает емаг у синдиборга

### ISSUE THREAD

**Issue by Shudyn** [TauCetiStation/TauCetiClassic#1158]
#### Подробное описание проблемы
Нигде не работает емаг у синдиборга
#### Что должно было произойти
Емаг борга должен взламывать как и обычный емаг у трейторов
#### Что произошло на самом деле
Емаг борга ни на чем не работает.
#### Как повторить
Взять синдиборга, выбрать модуль емага, попробовать юзнуть на шлюзе или чем-то другом
#### Дополнительная информация:
Столько времени прошло с его добавления, а емаг еще не пофиксили :peka:

**Comment by ZVee** [comment]
>Столько времени прошло с его добавления, а емаг еще не пофиксили :peka:

Сча подзатыльник дам, потому что его уже фиксили, причем не так уж и давно.

---
Видимо опять чтот сломали.

>Емаг борга ни на чем не работает.

Врун, только что при тестах успешно емагнул локер, бипски, борга и скорее всего еще много что можно, а вот на дверях не пашет, да. Мне лень проверять весь список.

**Comment by SpaiR** [comment]
На дверях просто первым вызывается борговское взаимодействие. Нужно учитывать активные предметы в руках или перевести это взаимодействие на режим.

**Comment by Kurshan** [comment]
#2028
