### ISSUE TITLE
Не герметичные окна в зоне резервуаров атмоса

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#11593]
#### Подробное описание проблемы
Если переустановить окна в резервуарах атмоса, они навсегда перестанут быть герметичны и будут выпускать любой газ в пустоту.
#### Что должно было произойти
Окна герметичны и газ не исчезает.
#### Что произошло на самом деле
Окна не герметичны и газ уходит в бесконечное ничто.
#### Как повторить
Разобрать и собрать окна в резервуарах атмоса.
#### Дополнительная информация:
#59823

**Comment by Venngedi** [comment]
#11646
