### ISSUE TITLE
[Proposal] Газетный канал для станционных анноунсов

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#11605]
Часто так, что игроки, заходя в середине раунда не знают каких-то особых распоряжений от глав в раунде.
Было бы здорово все станционные оповещения записывать в специальный канал и любой космонавтик мог бы прочитать все анноунсы от глав и цк.

**Comment by AzzyDreemurr13** [comment]
Кстати говоря, видел такое на пару серверах, удобная вещь, газета называется "Station Time" и там все анонсы которые были сделаны, прикольная вещь.

Надеюсь, лайков соберёт, чтобы её сделали на Тау

**Comment by AzzyDreemurr13** [comment]
Кстати говоря, видел такое на пару серверах, удобная вещь, газета называется "Station Time" и там все анонсы которые были сделаны, прикольная вещь.

Надеюсь, лайков соберёт, чтобы её сделали на Тау
