### ISSUE TITLE
мобы бьют дважды

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#11608]
#### Подробное описание проблемы
симпл-мобы бьют дважды, нанося в два раза больше урона (иногда по разным конечностям?)
#### Что должно было произойти
один раз
#### Что произошло на самом деле
два!
#### Как повторить
быть покусанным карпом
#### Дополнительная информация:
#11544

**Comment by Naroke** [comment]
Лол, можно вполовину уменьшить урон. Вот вам и новый костыль

**Comment by pro100kotah** [comment]
> Лол, можно вполовину уменьшить урон. Вот вам и новый костыль

Думаю больше мороки будет каждому симпл-мобу вручную снижать цифры урона в два раза
