### ISSUE TITLE
Ходим по столам как по бульвару

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#11613]
#### Подробное описание проблемы
В раунде указаном ниже, случилась странная фигня, что на столы и тому подобным предметам, можно просто пробегать по полу
#### Что должно было произойти
должен перетянуть перса на стол чтобы залезть
#### Что произошло на самом деле
Перс идет по столам как по бульвару и уебывается об стеклянные столы
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/1f44150a-ba6d-4a9a-8bf8-1010e3e05fa9)

#### Как повторить
а хуй его знает, это была хрень у пол кек экипажа

#### Дополнительная информация:
Issue reported from  Round ID: 59910 (Tau Ceti Classic (RU))
Testmerges: ```#10434 #11272 #11464 #11571 #11597 #11604 ```
Reporting client version: 514.1589

**Comment by AndroBetel** [comment]
мб из-за ивента про выключение гравитации происходит

**Comment by ViDLiathan** [comment]
Случается из-за разгерметизаций, взрывов или смертей. Что-то похожее происходило со мной с неделю назад, но я не уверен что точно произошло.

**Comment by AzzyDreemurr13** [comment]
> мб из-за ивента про выключение гравитации происходит

Режим блоба был, я вот не помню только прям вначале было или после того те кто были у блоба и когда там появилась дыра, всех опрокинуло и я начал замечать эту фигню на мостике и то как несколько раз случайно уебывался об стеклянные столы ....



> А, было триллион яблок в одной клетке и случилась разгерма. И после пролагов случилась такая штука.

какие еще триллион яблок в одной клетке? ._.

**Comment by volas** [comment]
Могло бы быть из-за залипшего трейта в https://github.com/TauCetiStation/TauCetiClassic/pull/11226, но нужно понять, при каких условиях он мог залипнуть

**Comment by volas** [comment]
закрою в пользу #11613, там есть более конкретный способ воспроизведения
