### ISSUE TITLE
Диагонали терроризируют броски

### ISSUE THREAD

**Issue by NinjaPikachuska** [TauCetiStation/TauCetiClassic#11628]
#### Подробное описание проблемы
![dreamseeker_bdBHXozqh9](https://github.com/TauCetiStation/TauCetiClassic/assets/89906909/ea7172d9-343e-4f11-8537-bf3f201c00fb)
Бросок по диагонали сходит с ума
#### Что должно было произойти
Бола просто врезается
#### Что произошло на самом деле
Бола переходит в суперпозицию, находясь и на ноге, и на полу
#### Как повторить
Сделать все как на гифке

**Comment by pro100kotah** [comment]
Давняя фигня. Правда она бесполезная и бола после взаимодействия пропадает, когда игрок снимает ее с себя.
Кстати, так криво вроде еще работают метательный ножи и звездочки. Надо бы проверить.

**Comment by pro100kotah** [comment]
Ебать, пиздец, че я нашел. Короче да. Метательные работают также и забудь про мои слова о боле. Она дублируется как и метательные вещи. Пока их не вынуть или не снять.
По итогу можно одним метательным кидаться бесконечно и он застревать не будет. 

Но я нашел более лютый баг:


![testgif](https://github.com/TauCetiStation/TauCetiClassic/assets/57403011/d55bee05-7fc5-40aa-8a0d-d9fa1814d6f5)

**Comment by Oz1Es** [comment]
жесть, это фича проста, никакие не баги, те кто кодили специально сделали такую фичу, вы теперь не просто игроки тау, вы избранные

**Comment by volas** [comment]
Это что-то недавнее может, не связанное с диагональным движением? Движение давно ввели, чтоб только сейчас заметить баг.

**Comment by AzzyDreemurr13** [comment]
Тестировали с Зеро, это лютая штука. Без разницы какой риг, хотю Дип страйк,  ОБР, Дедов, если использовать метательный нож оно в стан и за 5 секунд разбирает тебя до 1 фрага
