### ISSUE TITLE
Синди шлем в боевом режиме защищает от разгермы

### ISSUE THREAD

**Issue by Leprekeoner** [TauCetiStation/TauCetiClassic#11629]
#### Что должно было произойти
Синди шлем в боевом режиме не защищает от разгермы
#### Что произошло на самом деле
Синди шлем в боевом режиме защищает от разгермы
#### Как повторить
Носить синди шлем в боевом режиме в разгерме

**Comment by Oz1Es** [comment]
спасибо, теперь я всегда буду переключать шлем в боевой режим когда я буду нюкером!!!
