### ISSUE TITLE
[Proposal] Сушилка для растений в ботанике 

### ISSUE THREAD

**Issue by Smartcookie912** [TauCetiStation/TauCetiClassic#11648]
Добавить с других билдов возможность высушивать растения в сушилке (крафтится из деревянных досок) и заворачивать их в обёрточную бумагу для самокруток (добавить  в сигаретный торговый автомат, либо просто в обёрточную бумагу) или  набивать в трубку. При курение вещества из самокрутки будут постепенно передаваться в организм (кроме нутриенов). Так же можно добавить семена табака.

**Comment by Deahaka** [comment]
Курение вредно, сервер за здоровый образ жизни

**Comment by Smartcookie912** [comment]
Никому не интересно
