### ISSUE TITLE
[Proposal] Немедленный откат переводов!

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#11656]
#### Подробное описание ситуации
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/aa313c47-a525-44ea-be21-4f468cb64a2b)

Бася ливнул с дискорда со словами "пока".

#### Что произошло на самом деле
Никто не удержит от ревёрта переводов. "Поак поак" нот гуд
#### Как, повторите
Создать ветку, зайти в консоль любого редактора кода и написать git revert `2310f3` <= Вставьте номер указанный при мерже ПРа в самом низу, принять изменения и заливать на гитхаб не медля!

**Comment by DarthSidiousPalpatine** [comment]
Полностью согласен. Нужно ревертнуть все переводы и сформировать костяк из четырёх переводчиков, которые будут иметь хоть какое-то доверие и организацию в дискорде...

Волас, всё херня, давай по-новой!

**Comment by maleyvich** [comment]
а гусев в этот костяк входить не будет 👍

**Comment by DarthSidiousPalpatine** [comment]
> а гусев в этот костяк входить не будет 👍

Ой-ой-ой, малевич вот это ты уел, ну-ну.
Абсолютно похуй, где я писал про то что я буду переводчиком?
Выберите самых нормальных по каким-нибудь критериям, мне похуй, главное чтобы не перевод Баси, это гуглпереводчикринж.

**Comment by Deahaka** [comment]
Фак, это была акция на несколько часов!

**Comment by LudwigVonChesterfield** [comment]
открой обратно хорошее предлоджение

**Comment by LudwigVonChesterfield** [comment]
и темку на форуме и темку

**Comment by AzzyDreemurr13** [comment]
Троллинг зашёл слишком далеко, если Бася перестанет переводить, то я займусь этим 🐐

**Comment by DarthSidiousPalpatine** [comment]
> я займусь этим 🐐

А можно, пожалуйста, не трогать перевод тем, кто не может ничего переводить? Вы задрали своим охлаждённым траханьем, углепластик. Фаргус мёртв и в наше время можно банально выучить язык за полгода-год и блять нормально переводить. Особенно если буквально использовать обычный словарь чтобы узнавать значение неизвестных тебе слов.

**Comment by AzzyDreemurr13** [comment]
> А можно, пожалуйста, не трогать перевод тем, кто не может ничего переводить?

Мы не в начале 2000, где на перевод все забивали + новичкам проще. 

(А что касательно меня, то я в другой соц сети помогаю с переводом на русский от корректировки перевода до перевода статьей)

Просто, чтобы не ныли, по хорошему надо сделать полный крупный перевод интерфейса и всех деталей.
