### ISSUE TITLE
airborn trait issue or something

### ISSUE THREAD

**Issue by daedrowe** [TauCetiStation/TauCetiClassic#11669]
#### Подробное описание проблемы
можно пролетать над столами/стеллажами/подоконниками и т.д. без гена карлика в нормальной атмосфере после того, как куклу откинуло репульсом/силовым полем

#### Что должно было произойти
кукла не должна пролетать над препятствиями после откидывания
#### Что произошло на самом деле
кукла пролетает над препятствиями после откидывания

#### Как повторить
ударится об поле

#### Дополнительная информация:
Issue reported from  Round ID: 60046 (Tau Ceti Classic (RU))
Testmerges: ```#10434 #11514 #11640 #11647 ```
Reporting client version: 514.1589

**Comment by volas** [comment]
По тесту выяснилось, что виноваты магбутсы. Где-то контроллер глючит.

**Comment by volas** [comment]
хотя, магбутсы не при чем, оно просто рандомно глючит и атом остаётся в процессинге контроллера.

Может быть связано с #11628
