### ISSUE TITLE
Обезьяны вновь лишились метаболизма

### ISSUE THREAD

**Issue by Naroke** [TauCetiStation/TauCetiClassic#11667]
#### Подробное описание проблемы
Метаболизм у макак вновь пропал, из-за чего вирусологии снова требуются уже куклы
#### Что должно было произойти
макаки метаболизируют радий и выводят антитела
#### Что произошло на самом деле
макаки не метаболизируют радий(так ещё и не заражаются вирусами)
#### Как повторить
попробовать вывести антитела в вирусологии с использованием мартышек
#### Дополнительная информация:
Issue reported from  Round ID: 60045 (Tau Ceti Classic (RU))
Testmerges: ```#10434 #11514 #11640 #11647 ```
Reporting client version: 514.1589

**Comment by kalazus** [comment]
Только что на сэндбоксе вывел антитела из мартышки. ТМы не трогали метаболизм. Вероятно скилл ишшуе, там шанс 5% на выработку антител с тика, так что нужно ждать ~40 секунд.

**Comment by Naroke** [comment]
Хз, я вколол 30 юнитов радия, а она после этой "терапии" даже выжила. По-моему это должно значить то, что радий она не метаболизировала. Да и к тому-же, после того, как я взял у неё кровь, в центрифуге вирус не отображался
