### ISSUE TITLE
Баги атмоса. Краник. Valve.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#1167]
#### Подробное описание проблемы
1)Краник при закрытии удаляет пайп_нэт"ы куделем. Предположительно задумывалась как тригер пересборки пайпнетов, но у пайпнета не прописан Destroy().
2)При подсоединении коннектора к кранику, он не работает. 
#### Что должно было произойти
Работать нормально.
#### Что произошло на самом деле
В итоге получаем трубу без пайпнета.
#### Как повторить
Закрыть краник.
#### Дополнительная информация:
1)Какрываем краник, и в ВВ видим что ничего не изменилось, причина - то что кудель не моментально удаляет.http://i.imgur.com/mLhM4ac.png
ждем некоторое время и ввидим что информация обновилась. старая сеть была удалена. Закачивающия помпа сгенерировала новый пайпнет. а в левой части генерировать пайпнет было нечему, в итоге труба, кран, помпа без пайпнета.http://i.imgur.com/uMECIhn.png
2) На фото открытый краник у которому подсоеденены два разных пайпнета. Открытый краник не должен иметь два разных пайпнета.http://i.imgur.com/xPvd52z.png

**Comment by Dennok** [comment]
Правда иногда оно всежа работает.

**Comment by SpaiR** [comment]
@Dennok ты там дестрой для атмосовой машинерии фиксил, этот ишью ещё актуален?

**Comment by Dennok** [comment]
Да, это пофикшено.
