### ISSUE TITLE
Шкаф БЩ сломан

### ISSUE THREAD

**Issue by Slavik2001** [TauCetiStation/TauCetiClassic#11695]
#### Подробное описание проблемы
Шкаф БЩ который с замком стоит на общем и ничем не защищен. А вот его второй шкаф без замка имеет требование доступа, но замка нет, поэтому нет
#### Что должно было произойти
Запрос доступа в шкаф снаряги БЩ
#### Что произошло на самом деле
Голый мужик зашел и открыл шкаф снаряги БЩ
#### Как повторить
Зайти в раунд и дойти до шкафа БЩ
#### Дополнительная информация:
У меня навернулся ГитГУИ и я не могу залить фикс, извеняйте. Пока разбираюсь с ГитГУИ
P.S.: Нужно просто зайти в code/game/objects/structures/ctates_lockers/closets/secure/security.dm и там перенести строку 430 на 448

Issue reported from  Round ID: 60128 (Tau Ceti Classic (RU))
Testmerges: ```#10434 #11514 ```
Reporting client version: 514.1589

**Comment by AzzyDreemurr13** [comment]
Сейчас посмотрю
