### ISSUE TITLE
[Task] Добавить цели некоторым гост ролям.

### ISSUE THREAD

**Issue by DanteTrue** [TauCetiStation/TauCetiClassic#11709]
#### Подробное описание проблемы

Необходимо добавить ролям из рандом ивентов цели:

Рандом ивент - "Конструкты культа" из портала. Все конструкты из ивента должны получить перманентную цель: "Охраняйте портал, и не подпускайте к нему никого, кто может ему навредить. Портал - ваша связь с богом что породил вас. Если его уничтожат, любая ваша деятельность должна прекратиться." Данная цель, должна появляться, при заходе игрока на роль. Желательно так, чтобы она выделялась в чате, и не могла быть проигнорирована.

Рандом ивент - "Шейды" (не призванные магом) должны получить перманентную цель:  “Вы злые духи, питающиеся негативными эмоциями живых людей. Мертвые люди эмоций не испытывают, поэтому вам запрещено убивать” Данная цель, должна появляться, при заходе игрока на роль. Желательно так, чтобы она выделялась в чате, и не могла быть проигнорирована.

**Comment by DanteTrue** [comment]
Это не баг, а таск. И я понятия не имею как менять лэйблы.

**Comment by Oz1Es** [comment]
а смысл тогда констрактов, нафига им защищать портал если их призвали ну точно не чтобы защищать портал

**Comment by Lexakr** [comment]
Ну можн удалить тогда их или занерфить, в текущем виде говно говна, когда оставленный без внимания гений на джаггернауте сносит пол станции в соло, как будто там армия культа поработала

**Comment by Deahaka** [comment]
> Ну можн удалить тогда их или занерфить, в текущем виде говно говна, когда оставленный без внимания гений на джаггернауте сносит пол станции в соло, как будто там армия культа поработала

https://github.com/TauCetiStation/TauCetiClassic/issues/10390

**Comment by Lexakr** [comment]
> 

Только там как то тухло все и тихо, а нерф через добавление целей это простое решение чтобы заткнуть дыру здесь и сейчас

**Comment by Deahaka** [comment]
всмысле тухло, там написано что конструкты это как блоб, всё.

**Comment by Lexakr** [comment]
> всмысле тухло, там написано что конструкты это как блоб, всё.

Ну эти черти как ломали космос и все вокруг, так и ломают. С небольшой поправкой на громкие баны, после которых не так часто борзеют

**Comment by Pirsnya** [comment]
Чё по порталу культа

**Comment by Pirsnya** [comment]
Мне кажется для культ портала норм сделано напоминание чтобы не распускали руки

**Comment by DanteTrue** [comment]
Товарищи кодеры, случаи бесоёбства с ивентовыми конструктами из портала продолжаются. Запилите им уже цели.

**Comment by Pirsnya** [comment]
bump

**Comment by Pirsnya** [comment]
bump

**Comment by Pirsnya** [comment]
bam

**Comment by Deahaka** [comment]
Лайки повышают видимость ишуя для кодеров, каждую неделю в рнд закрепляется топ залайканных ишуев. Думай

**Comment by Pirsnya** [comment]
> Лайки повышают видимость ишуя для кодеров, каждую неделю в рнд закрепляется топ залайканных ишуев. Думай

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/35347896/f4350ca2-0cac-44be-a9f7-a7c63d37c704)
Думай х2

**Comment by Pirsnya** [comment]
bom

**Comment by DanteTrue** [comment]
Бампаю хоть каждую неделю.
