### ISSUE TITLE
Проблема со значками при езде на мехе

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1172]
#### Подробное описание проблемы
Значок нехватки кислорода не появился при езде по космосу с выключенной подачей в кабину
#### Что должно было произойти
Предупреждать надо было
#### Что произошло на самом деле
Ничего, о нехватке кислорода узнал по шкале здоровья, в итоге порвал лёгкие и соснул
#### Как повторить
Уехать на мехе без включённого балона в спейс
#### Дополнительная информация:
N/A

**Comment by RichardJones1** [comment]
Не уверен, но скорее всего да

**Comment by KatoMarika** [comment]
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/18484142/e24798fd-18b5-44dc-af5b-3961411d0423)
Вроде как пофикшено, можно закрывать.
