### ISSUE TITLE
Имплантация скелетов

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#11726]
#### Подробное описание проблемы
Скелетам можно поставить имплант(майндшилд точно, другие не проверял)
#### Что должно было произойти
Скелету некуда ставить имплант
#### Что произошло на самом деле
Скелет чипирован с потёкшим мозгом(что?)
#### Как повторить
Чипироваться за скелета

**Comment by ViDLiathan** [comment]
Ещё скелеты наследуют генетические болезни

**Comment by Tolerantboy** [comment]
Имплант вставляется в кость, в чём проблема
