### ISSUE TITLE
Джукс в другой зоне.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1173]
#### Подробное описание проблемы
Если переставить джукс из бара в другое место и врубить, музыка будет слышна и в баре и в месте где она играет.
#### Что должно было произойти
Музыка должна играть только на той территории где она поставлена.
#### Что произошло на самом деле
Она играет на первоначальной и второй.
#### Как повторить
Переставить джукс в другую зону и проверить.

**Comment by TEXH4Pb** [comment]
@KIBORG04 можно закрывать, пофикшено в #8039
