### ISSUE TITLE
В баре перманентно невозможно находится по эстетическим причинам

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#11733]
#### Подробное описание проблемы
В баре перманентно включён каждый раунд тёмно-синий фильтр. Люди уже не хотят сидеть в этом баре, та и на самом деле даже остаться больше чем на 5 секунд не хочется никому, сколько я наблюдал в гостах.
#### Что должно было произойти
Думаешь щас зайду в бар, увижу там самых социально активных игроков на сервере, посидишь с приятной музыкой и в комфортных условиях...
#### Что произошло на самом деле
![1a1a2s2s](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/3ea4df47-90a4-4a9a-8eb3-9bfdad6ef475)

#### Как повторить
Зайти в игру...
#### Дополнительная информация:
Хочу чтобы стоял нормальный свет по умолчанию, а бармен мог ставить ублюдский только если ему хочется. Проигнорили в дискорде, но может тут уже игнорить пора перестать @volas ?

**Comment by Deahaka** [comment]
да-да-да, онлайн только вырастет!!

**Comment by volas** [comment]
Первый раз слышу, что кому-то не нравится свет в баре. И эмоционально бросаться слапами и обвинениями - очень круто, отлично настраивает собеседника на диалог.

**Comment by Deahaka** [comment]
Это опять тот самый момент когда добавляется контентик, потом ставится самое худшее что может быть, казалось бы для ТМа, но потом оказывается что это изначально так и было задумано быть навсегда... Не нравится такое, совсем-совсем.

**Comment by volas** [comment]
Я тебя не понимаю, но фидбек принят. Посмотрим, что другие скажут.

**Comment by DarthSidiousPalpatine** [comment]
> Я тебя не понимаю, но фидбек принят. Посмотрим, что другие скажут.

Цвета кринж, имхо. Хочется цветов под дикий запад, под неоновый киберпанк и пр. А на деле включаешь и там две проблемы:
а) недостаточная насыщенность света, по итогу всё во тьме нафиг.
б) Свет из коридора смешивается со светом бара. Если повесить занавески то норм.

**Comment by volas** [comment]
> Хочется цветов под дикий запад, под неоновый киберпанк и пр. 

Можешь добавить, я писал подробности в https://github.com/TauCetiStation/TauCetiClassic/pull/11312

Во вкладке дебага есть отдельный верб для подбора параметров. Я лишь подготовил фундамент, а изменять уже (надеюсь) другим людям.

**Comment by Tobyyyan** [comment]
Нужно чтобы лампочки с кухни и коридора не мешали просто + добавить большую охватываемость света, вместо черного данжена.

**Comment by AzzyDreemurr13** [comment]
Или просто добавить в бар возможность включения затемнение окон и крафт этих самых окон ....

**Comment by PersyFOX** [comment]
Разве нельзя поменять через АПЦ?

**Comment by TRISAGI0N** [comment]
Боже, забаньте уже дехаку
