### ISSUE TITLE
Мышки могут открыть контейнер

### ISSUE THREAD

**Issue by Rolt146** [TauCetiStation/TauCetiClassic#11754]
#### Подробное описание проблемы
Мышка может открыть коробку, рюкзак, сумку и скушать оттуда нямку
#### Что должно было произойти
Повар положил еду в ланчбоксы и доволен, клиент получает нямку
#### Что произошло на самом деле
Мышка нагло все скушала с коробок и сумок ботаника, повар повесился
#### Как повторить
За мышку перетащить спрайт контейнера на себя и кликать по еде

**Comment by ViDLiathan** [comment]
Опять крысы грифонят

**Comment by Oz1Es** [comment]
мышка просто якобы залезает в коробочку и всё жрёт, поэтому надо передавать еду в спец чемоданах с кодом

**Comment by pro100kotah** [comment]
Фича

**Comment by Chip11-n** [comment]
Фича же

**Comment by Venngedi** [comment]
Фича
