### ISSUE TITLE
Рантайм телепорта гостов

### ISSUE THREAD

**Issue by PersyFOX** [TauCetiStation/TauCetiClassic#11755]
#### Подробное описание проблемы
Невозможность телепортации призраков
#### Что должно было произойти
Призрак телепортируется через Ghost-> teleport
#### Что произошло на самом деле
No area available для любой зоны и спавн рантайма
#### Дополнительная информация:
Issue reported from  Round ID: 60274 (Tau Ceti Classic (RU))
Testmerges: ```#10434 #11514 #11594 #11698 ```
Reporting client version: 514.1589

**Comment by AndroBetel** [comment]
это я в раунде сломал
