### ISSUE TITLE
Все импланты трейтора перестали работать.

### ISSUE THREAD

**Issue by Slegarrr** [TauCetiStation/TauCetiClassic#11760]
#### Подробное описание проблемы
При покупке и инжекте импланта в себя (любого) или кого-то другого, он не появляется в теле. Нету кнопки активации импланта и через сканнер его тоже не видно.
#### Что должно было произойти
Имплант должен появится в кукле , так же как и кнопка его активации.
#### Что произошло на самом деле
После инжекта ничего не происходит.
#### Как повторить
Вколоть имплант кукле в sandbox 
#### Дополнительная информация:
Кто-то писал, что импланты абдукторов так же не работают. Так что возможно проблема не только в "трейторских".

**Comment by BlankCringe** [comment]
Не работают только те что активируются по кнопке, эмпланты с активацией по эмоуту или слову все ещё работают, исправь

**Comment by volas** [comment]
должно быть пофикшено
