### ISSUE TITLE
Эминем не может использовать том

### ISSUE THREAD

**Issue by Riverz1** [TauCetiStation/TauCetiClassic#11765]
#### Подробное описание проблемы
При игре за Эминема нельзя использовать том, как для построек, так и для рисования рун
#### Что должно было произойти
При нажатии использовать том открыться панель с постройкой конструкций или рисование рун
#### Что произошло на самом деле
При нажатии использовать том, ничего не произошло
#### Как повторить
Зайти за Эминема и использовать том

**Comment by volas** [comment]
Должно быть пофикшено
