### ISSUE TITLE
ХоСовское трап-платье имеет неправильный спрайт

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#1178]
#### Подробное описание проблемы
http://prnt.sc/ea8prv
Колготки(?) на спрайте ХоСовского платья отсутствуют на виде сбоку
#### Что должно было произойти
Колготки у ХоСовского платья должны (или не должны) присутстовать во всех проекциях
#### Что произошло на самом деле
Колготок в боковой проекции нет
#### Как повторить
Надеть ХоСовское платье

**Comment by StrikS** [comment]
Это галоши же :peka:

**Comment by omejka** [comment]
Вальтер не может доделать даже свои мыльные спрайты охохо
<a href="http://imgur.com/uL9Xpal"><img src="http://i.imgur.com/uL9Xpal.png" title="source: imgur.com" /></a>
http://www.filedropper.com/hosfs

**Comment by WatlerJe** [comment]
носите чулки, че проблема чтоль?

**Comment by igigin** [comment]
#1802
