### ISSUE TITLE
волас бимбы заруинил

### ISSUE THREAD

**Issue by BlankCringe** [TauCetiStation/TauCetiClassic#11788]
#### Подробное описание проблемы
ну я по гайдику дедов делаю бимбы РНДшные, а взрыва 51 нет
#### Что должно было произойти
взрыв 51 8 раз, с каждой бомбы по взрыву
#### Что произошло на самом деле
взрывы стали гораздо слабее, большинство бомб со старых рецептов теперь создаёт взрыв 27 уровня,на некоторые из взрывов кинетик сканер полигона вообще не реагирует если взрывать несколько бомб сразу
#### Как повторить
сделать бомбы обычным методом, взорвать их на полигоне, посмотреть на уровень взрыва и поплакать

**Comment by Chip11-n** [comment]
Они не взрываются? Они взрываются плохо? Взрываешься ты? Взрывается РнД? Мемчики конечно хорошо, но информации бы побольше.

**Comment by maleyvich** [comment]
это просто курс на тг и выпил очков с бомбочек а вы о чем подумали?

**Comment by Deahaka** [comment]
Волас красава воплощает мою мечту об РнД где бомбы не единственное что влияет на игру учёного!

**Comment by maleyvich** [comment]
> Волас красава воплощает мою мечту об РнД где бомбы не единственное что влияет на игру учёного!

это курс на тг дехака там тоже бомбочки делают ради грифа

**Comment by Mercurialaste** [comment]
слабые
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/90282587/8a0afc86-2d7a-480e-bb7b-3cba6c6ddad7)

**Comment by BlankCringe** [comment]
> слабые ![image](https://user-images.githubusercontent.com/90282587/256466825-8a0afc86-2d7a-480e-bb7b-3cba6c6ddad7.png)
ну ты объясни как это работает, тогда и будешь говорить что проблем нет

**Comment by volas** [comment]
> взрывы стали гораздо слабее, большинство бомб со старых рецептов теперь создаёт взрыв 27 уровня

кап с одного взрыва всегда был около 27, возможно для бомб применялся не правильно, или где-то был баг. Нужно будет разобраться.

> на некоторые из взрывов кинетик сканер полигона вообще не реагирует если взрывать несколько бомб сразу

если честно, не в курсе, зачем взрывать сразу. Но сейчас посмотрел, у танков нету или потерялась реакция на взрывы, и они возможно реагируют на взрывы как обычные итемы с удалением (т.е. взрыв одного удаляет другие)

**Comment by volas** [comment]
если быть точным, то 14, но он применялся по разному. И бомбы реагировали вообще не от капа, а от сложенного абстрактного значения в попугаях.

**Comment by Deahaka** [comment]
Волас прав. Это расчёт маячка, а не код бомбы

**Comment by volas** [comment]
Я нашел, случился откат https://github.com/TauCetiStation/TauCetiClassic/pull/3883/files

в том ПР-е возможно увеличивалась сила взрыва уже после применения капа, но еще до создания взрыва.

Сейчас кап применяется глобально в сабсистеме взрывов, при создании самого взрыва. Плюс я с клампом не разобрался.

**Comment by volas** [comment]
Сами взрывы сейчас относительно разрушительнее стали, так что вместо отдельного капа будет проще бустануть очки научки

**Comment by TRISAGI0N** [comment]
![изображение](https://github.com/TauCetiStation/TauCetiClassic/assets/127397187/40558acf-588c-4cb7-a114-3e1c90e40d1d)
ничё не знаю

**Comment by volas** [comment]
> если честно, не в курсе, зачем взрывать сразу. Но сейчас посмотрел, у танков нету или потерялась реакция на взрывы, и они возможно реагируют на взрывы как обычные итемы с удалением (т.е. взрыв одного удаляет другие)

залил экспериментальный фикс, скажите если оно не работает и бомбы всё еще взрываются не все. В целом, я позже создам обсуждение на форуме по этому поводу, потому что это как-то не правильно.

**Comment by pro100kotah** [comment]
> > если честно, не в курсе, зачем взрывать сразу. Но сейчас посмотрел, у танков нету или потерялась реакция на взрывы, и они возможно реагируют на взрывы как обычные итемы с удалением (т.е. взрыв одного удаляет другие)
> 
> залил экспериментальный фикс, скажите если оно не работает и бомбы всё еще взрываются не все. В целом, я позже создам обсуждение на форуме по этому поводу, потому что это как-то не правильно.

#60375 раунд после фикса. Но не знаю бы ли рест. Пока все также. 27 уровень и взрываются не все.

**Comment by volas** [comment]
27 уровень так и останется капом, 51 - это было багованное значение, уникальное для бомб и не имеющее смысла. В качестве компенсации увеличено количество очков в два раза, итого за лимитки 27 сейчас получается вроде даже чуть больше, чем за 51 в прошлом.

Взрыв нескольких бомб тоже поправил.
