### ISSUE TITLE
Фаербол мага с НОВЫМИ взрывами сломался

### ISSUE THREAD

**Issue by Slavik2001** [TauCetiStation/TauCetiClassic#11805]
#### Подробное описание проблемы
После мержа ПРа Воласа на новые взрывы, фаербол мага апнулся... Просто посмотрите скрины...
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/123300305/143fce62-69bb-4fa6-851a-7dcd94968da2)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/123300305/b18968b7-9f45-4672-950e-b847641c0bd2)
#### Что должно было произойти
С старыми взрывами, фаербол прилетал в куклу, делал небольшой взрыв(его было недостаточно чтобы уничтожить обшивку под плиткой), поджигал, вводил в сон
#### Что произошло на самом деле
С новыми взрывами... Куклу тупо гибает и под ней пропадает пол что приводит к разгерме...
#### Как повторить
Зайти за мага, взять фаербол, кинуть в куклу
#### Дополнительная информация:
Issue reported from  Round ID: 60418 (Tau Ceti Classic (RU))
Testmerges: ```#11256 #11792 #11514 #10434 #11551 #11594 ```
Reporting client version: 514.1589

**Comment by maleyvich** [comment]
опять фаербол поломался несите новый

**Comment by Deahaka** [comment]
Как по мне норм

**Comment by Slavik2001** [comment]
Фаербол сгорел на работе.
Мне тоже прикольно когда я смотрю на новый фаербол. Гибнуть неприятеля чтобы ТОЧНО отправить его в мед, а после он уже без вещей думал надо ему это или нет. Но проблема в том что ты делаешь разгерму... Она же в свою очередь вредит тебе: урон, падение(отключение некоторых спелов)+ты можешь навредить/убить невинных из-за чего у админов будут претензии к тебе...

**Comment by Kiromaka** [comment]
Это просто бафф мага, фича

**Comment by Doom1Drake** [comment]
Подствольные гранаты дрозда вызывают такой же эффект: гибают и ломают пол. При взрыве фуелтанка от попадания нульрода так же уничтожается пол, хотя при подрыве через игнитер такого не происходит. Взрывы крутые, но разгерм стало намного больше, пол стал картонным и рвется от всего.

**Comment by pro100kotah** [comment]
А еще фуелтанки делают разгермы.

**Comment by volas** [comment]
Придется некоторое время еще вылавливать такие взрывы. Изменился алгоритм взрыва, и теперь взрывы, которые были настроены ломать пол - реально его ломают. Раньше это просто не работало из-за особенностей алгоритма.

Пофиксил всё что написали, если будут еще дырки которых раньше не было - пишите багрепорты.
