### ISSUE TITLE
Зарплата 0 у криминалиста

### ISSUE THREAD

**Issue by Seached0** [TauCetiStation/TauCetiClassic#11803]
#### Подробное описание проблемы
Отсутствие зарплаты у криминалиста.
#### Что должно было произойти
У криминалиста имеется зарплата.
#### Что произошло на самом деле
У криминалиста в КПК числится Salary: 0. 
#### Как повторить
Зайти за криминалиста в раунд.

**Comment by KandreyKandrey** [comment]
Существует раундстартовый ивент, который берёт 2 случайных игроков и меняет местами их зарплаты (скорее всего в этот раз выпал криминалист и тестовик)

**Comment by Seached0** [comment]
> Существует раундстартовый ивент, который берёт 2 случайных игроков и меняет местами их зарплаты (скорее всего в этот раз выпал криминалист и тестовик)

Такое уже 5 раунд подряд.

**Comment by Seached0** [comment]
Подожду пока тестмержи поменяются, если проблема продолжится, то займусь возможно сам.

**Comment by Seached0** [comment]
Отбой, проблема решилась.
