### ISSUE TITLE
Репликатор может съесть сингулярность

### ISSUE THREAD

**Issue by Kiromaka** [TauCetiStation/TauCetiClassic#11804]
#### Подробное описание проблемы
Репликатор съел сингулярность
#### Что должно было произойти
Репликатор должен был стать кормом сингулярности
#### Что произошло на самом деле
Сингулярность стала кормом репликатора
#### Как повторить
Съесть сингулярность за репликатора
#### Дополнительная информация:
Точной последовательности действия не ясны, репликатор был не я, опять же если хотите точно все узнать id раунда прикреплен к issue 
Issue reported from  Round ID: 60408 (Tau Ceti Classic (RU))
Testmerges: ```#11256 #11792 #11514 #10434 #11551 #11594 ```
Reporting client version: 514.1583

**Comment by LudwigVonChesterfield** [comment]
фича. там даже особое взаимодействие если скушать её

**Comment by Kiromaka** [comment]
> фича. там даже особое взаимодействие если скушать её

короче проеб который замазали под фичу, я так и понял

**Comment by LudwigVonChesterfield** [comment]
определенно нет

синга по сути мешает репликам делать свою работу сжирая станцию за них, поэтому у них есть опция сожрать её.

**Comment by Kiromaka** [comment]
> определенно нет
> 
> синга по сути мешает репликам делать свою работу сжирая станцию за них, поэтому у них есть опция сожрать её.

репликам нужна энергия, избавляться от двигла руинит и экипажу и репликам, странные у вас фичи

**Comment by LudwigVonChesterfield** [comment]
у репликов литерали есть свои генераторы для таких ситуаций

**Comment by Kiromaka** [comment]
> 

оказывается синга просто исчезает если врезается в труп репликатора, ахуеть фича

**Comment by LudwigVonChesterfield** [comment]
просто держу в курсе это не баг я это осознанно кодил.

если тут пропозал чтобы это так не работало, распишу почему плохая идея.

**Comment by Kiromaka** [comment]
> просто держу в курсе это не баг я это осознанно кодил.
> 
> если тут пропозал чтобы это так не работало, распишу почему плохая идея.

Ну чисто фактически это странно, с точки зрения механа и мира, я не против такого потому что выпускать сингу раз в 20 хуже. Но сам факт пропадание синги потому что к ней подошел реплик удивителен. И в тоже время есть одна проблема - если синга улетит когда не станции реплики, то вместо стандартных последствий улета синги с большой вероятностью она просто пропадет об случайного репликатора.

**Comment by LudwigVonChesterfield** [comment]
Да, в этом и смысл, чтобы люди не побеждали репликов сингой.

С точки зрения "лора" репликаторы фундаментально волшебные, появляются изниоткуда, и каким-то образом вникуда жрут абсолютно всё. Думаю не тяжело сказать что у сингулярности особое поведение с блюспейс-материалов кристаллов репликаторов из-за чего она и исчезает! 

Или какой-то другой бред, это уже проблема исключительно креативности лородела.

**Comment by Mercurialaste** [comment]
Как представитель лордепа, подтверждаю, это моя проблема и она обязательно будет решена, спасибо, что оставили ваш отзыв.

**Comment by KIBORG04** [comment]
Фича
