### ISSUE TITLE
[Proposal] Ломание баков блобом и репликаторами

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#11812]
Эти рольки не страдают от эестремальной температуры и поэтому частенько они ломают бак с фороном, который практически сразу загорается, а затем вся станция с температурой в градусов триста. И начинается для ролек изи мод.
Предлагаю бакам с фороном, сломаннные блобом и его миньонами, а так же репликаторами, не позволять выпускать этот самый газ в атмосферу. Иначе случается skill issue у всей станции и лёгкая победа у наглых ролек.

**Comment by maleyvich** [comment]
курс на душку антагов становится все больше аморальным

**Comment by Deahaka** [comment]
страшно это говорить, но проиграли в игре победили на гитхабе... :С
