### ISSUE TITLE
Мины гибают ржака смеяка

### ISSUE THREAD

**Issue by Tap0r** [TauCetiStation/TauCetiClassic#11813]
#### Подробное описание проблемы
Видимо после реворка взрывов мины начали гибать тех кто на них наступает
#### Что должно было произойти
Бобо, но с возможностью вернуться в раунд через клонерку/реанимацию.
#### Что произошло на самом деле
Гиб
#### Как повторить
Поставить мину и встать на неё?
#### Дополнительная информация:
раунд в котором я это увидел #60439 ещё идет я злодей жду бана.
Также протестил на песке 
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/88531962/8f9f276f-fcf2-4a66-a012-52500b200433)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/88531962/0d66b994-a398-4493-8b7f-3496b6631638)
Оба вида гибают

**Comment by AzzyDreemurr13** [comment]
Ну собственно... Вьетнам...

О боже, Джонни, ОНИ ПО ВСЮДУ

**Comment by AzzyDreemurr13** [comment]
А если серьезно, что-то Волас на куралесил со своими взрывами #11792

**Comment by volas** [comment]
Придется некоторое время еще вылавливать такие взрывы. Изменился алгоритм взрыва, и теперь взрывы, которые были настроены ломать пол - реально его ломают. Раньше это просто не работало из-за особенностей алгоритма.

Пофиксил, если будут еще дырки которых раньше не было - пишите багрепорты.
