### ISSUE TITLE
мессенджер боргов и ИИ

### ISSUE THREAD

**Issue by BlankCringe** [TauCetiStation/TauCetiClassic#11811]
#### Подробное описание проблемы
Борги могут отправлять сообщения на ПДА даже с вытянутой батарейкой, ИИ могут отправлять сообщения на ПДА находясь на интел карте даже если им вырубить связь с неё.
#### Что должно было произойти
Борги без питания, взаимодействие с миром не представляется возможным, ИИ заглушили связь-ИИн е может её использовать.
#### Что произошло на самом деле
ИИ пишет на ПДА как ни в чём не бывало, борги тоже.
#### Как повторить
Переместить ИИ на интел карту, выключить ему связь в настройках интел карты, просить ии написать вам на пда, с похожее с боргами но с вытянутой батарейкой

**Comment by DarkFurrSss** [comment]
Труп борга (Не тот, который требуется перезапускать, но который уже отключен) имеет те же проблемы (Или плюшки? Если со стороны борга)

**Comment by AzzyDreemurr13** [comment]
Не баг

Ибо:

1. Научись читать логи, когда ты на борге и из тебя вытаскивают батарейку. Пишется, (примерно) "Turning on emergency power"
Тем самым, у борга пока его полностью не сломают, есть всегда запасное питание, чтобы подать сигнал о помощи на ПДА.

2. По поводу ИИ тоже самое, если он без питания. На интел карте у него всё отключается, если отключить связь.

Итог:
Учимся, читать логи в чате на борге/Ии и учимся наживать на кнопку отключения связи для ИИ.

**Comment by AzzyDreemurr13** [comment]
> Труп борга

Я знаю, что если в момент убийства тебя ты успеешь прожать допустим письмо на ПДА ИИ, то может повезти и сообщение отправиться на ПДА, даже когда тебя вынесли в 0

**Comment by AzzyDreemurr13** [comment]
А так если ИИ отключили от питания/вытащили батарейку, то это вообще не баг лол.

**Comment by AzzyDreemurr13** [comment]
> кстати полная хрень нужно исправить

Насчёт того , что иногда боргу везёт, что может писать после смерти, то да
