### ISSUE TITLE
Paper bin не дает бумагу-копирку и вызывает рантайма

### ISSUE THREAD

**Issue by KatoMarika** [TauCetiStation/TauCetiClassic#11824]
#### Подробное описание проблемы
При попытке взять бумагу-копирку из пачки с бумаг пишет "You take  out of the the paper bin" и ничего не выдает. При использовании несколько раз вылезает Рантайм.
#### Что должно было произойти
Должно дать бумагу-копирку и не появляется Рантайм.
#### Что произошло на самом деле
Не дало бумагу копирку и появился Рантайм.
#### Как повторить
Зайти на станцию, использовать Paper bin, выбрать копирку. 
#### Дополнительная информация:
Runtime мяукает, "Зафиксирована аномалия #1509. Пожалуйста, отойдите подальше."

**Comment by AgRevol** [comment]
Айди раунда дай сразу

**Comment by KatoMarika** [comment]
60468

**Comment by AndroBetel** [comment]
блять я же тестил

**Comment by AzzyDreemurr13** [comment]
@KIBORG04 , фикс #11826  то замержили, а Ишуй не закрыли
