### ISSUE TITLE
Слепота пропадает при перезаходе

### ISSUE THREAD

**Issue by Kurshan** [TauCetiStation/TauCetiClassic#1183]
#### Подробное описание проблемы
Слепота полностью пропадает при перезаходе, независимо от состояния нынешнего моба, будь он в шкафу, ослеплён или с повязкой на глазах. Затрагивает как частичную слепоту, так и всю.
#### Что должно было произойти
Слепота должна была остаться
#### Что произошло на самом деле
Слепота пропала
#### Как повторить
Перезайти в игру.

**Comment by Dennok** [comment]
Время кастплеить Иллидана.
