### ISSUE TITLE
взрывы слишком крутые

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#11833]
#### Подробное описание проблемы
взрывы, которые не ломали пол раньше и не разгермили полстанции - теперь ломают пол и разгермят полстанции 
#### Список
фаербол мага, взрывная мина, фуелтанк, граната из подствольника, взрыв консолей рнд при обжективе (будет дополняться)

**Comment by volas** [comment]
> фаербол мага, взрывная мина, фуелтанк, граната из подствольника

конкретно взрывы пофикшены, но у плитки есть свойство ломаться с некоторым шансом при втором уровне урона. Надо это менять тогда.

**Comment by AndroBetel** [comment]
думаю, можно использовать просто во всех этих случаях light explosion или как оно там называется
