### ISSUE TITLE
[Proposal] Удалить Box station из ротации на неопределенное время

### ISSUE THREAD

**Issue by KatoMarika** [TauCetiStation/TauCetiClassic#11844]
#### Подробное описание проблемы
Бокс стейшион присутствует в ротации, игроки из-за этого не хотят пробовать новое, выходить из зоны комфорта. 
#### Что должно было произойти
Игроки должны пробовать новые карты, расширять границы созднания, чакры и далее по списку. 
#### Что произошло на самом деле
В коробку уперлись и говорят что развитие для лохов.
#### Как повторить
Запустить голосование на смену карты в конце раунда. 
#### Дополнительная информация:
Зачем делать новые карты и делать было вообще функционал для этого?

**Comment by Zandwitch23** [comment]
Игроки ничего никому не должны. Подождал бы хоть недельку, а лучше месяц. Сейчас не так уж и много игроков на сервере играють, чтобы начинать относиться к ним как к стаду баранов. Лучше поспрашивай что не так.

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/boxstation/40389/1

**Comment by BartNixon** [comment]
Лудук еще в конце мая предложил адекватное решение:

> Предлагаю следующий вариант переделки который учтёт большую часть пожеланий:
> карты надо сгруппировать, и вес менять не только карте, но и группе. чтобы люди не обходили низкий вес бокса голосованием за зимний бокс. то есть если текущая карта бокс, в голосовании вес понизится и на бокс и на зимний бокс - понижение веса надо стакать. условно если два раза бокс подряд - -10% к весу, если три - 20% и так далее, до какого-то порога. Порог нужен чтобы ПОДАВЛЯЮЩИМ большинством (условно 90% проголосовавших) все равно можно было ставить текущую карту.
> Думаю в таком варианте возражений ни у кого быть не может, и если так сделать то можно будет замержить на постоянку как вариант приследующий подталкивание игроков пробовать другие карты.

https://github.com/TauCetiStation/TauCetiClassic/pull/11438#pullrequestreview-1446758925

Если так сделать, не нужно ничего вырезать или удалять, игроки которые любят бокс его получат, вместе с разнообразием прочих карт, и возможностью выбирать между теми которые лучше проработаны.

**Comment by Ambassadoing** [comment]
Не трогайте бокс, гады! Единственная нормальная карта, от которой я более-менее знаю что ожидать и могу быть почти уверен, что не столкнусь с какой-нибудь тупой недоработкой или отсутствием какой-то новой фичи. Другие, думаю, считают аналогично.

**Comment by Tap0r** [comment]
почему пропосал мне кажется это баг
