### ISSUE TITLE
У игровых мобов Пропадают Худы при перезаходе

### ISSUE THREAD

**Issue by Kurshan** [TauCetiStation/TauCetiClassic#1184]
#### Подробное описание проблемы
При перезаходе у мобов пропадают отображаемые им Худы. Зачастую с проблемой сталкиваются Шедоулинги/их Треллы (не видят своих). Конструкты культистов (не видят своих культистов). Рева, Генг.
#### Что должно было произойти
При перезаходе Худы должны корректно отображаться
#### Что произошло на самом деле
При перезаходе Худы не отображаются
#### Как повторить
Попробовать перезайти в игру
#### Дополнительная информация:
-

**Comment by P-20** [comment]
>>>> https://github.com/TauCetiStation/TauCetiClassic/issues/984

**Comment by Kurshan** [comment]
У нас была договоренность со Зве, это просто напоминалка ему же, отстаньте.

**Comment by Motzord** [comment]
Возможно исправлено Пром с апдейтом худов
