### ISSUE TITLE
Проблемы дельты

### ISSUE THREAD

**Issue by Chip11-n** [TauCetiStation/TauCetiClassic#11855]
#### Подробное описание проблемы
1) Две одинаковых консоли. Одна из них посреди отсека.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/50750952/ea40ef82-cdf2-464f-9cc3-5721544f2399)

2) Нет раздатчика кислоты, как и в РнД

3) Токсинная без окошка защитного, что приводит к зафорониванию всей станции.

4) В бриге, у типо доков шаттла на каторгу, нет болтов.

#### Дополнительная информация:

На том же боксе есть окно в токсинной, где нету створки. Когда форон выбивает окно - он улетает в космос.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/50750952/09f53935-3cb2-4a83-be34-ea458e90067b)

**Comment by Deahaka** [comment]
пофикшено кстати
