### ISSUE TITLE
[Пропозал]Иконки профессий для каждой подпрофы ассистента

### ISSUE THREAD

**Issue by omejka** [TauCetiStation/TauCetiClassic#1186]
Так же закинул измененную иконку парамедика.
Для репортера и официанта два варианта иконки,прикрутите какую хотите.
<a href="http://imgur.com/DffhCAz"><img src="http://i.imgur.com/DffhCAz.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/W9DwR0D"><img src="http://i.imgur.com/W9DwR0D.png" title="source: imgur.com" /></a>

[Тык](http://www.filedropper.com/hud_3)

**Comment by dearprincesscelestia** [comment]
Официант с вилками и репортер с фотоаппаратом лучше. Я так понимаю, ПР ты не делаешь из-за выбора?

**Comment by omejka** [comment]
я просто не шарю в гите и мне лень разбираться

**Comment by Kurshan** [comment]
Там немношк код надо пошатать. Так что жди.
