### ISSUE TITLE
При получении роли игрок остается в лобби.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#1187]
#### Подробное описание проблемы
После определения режима и игроков с ролями. Все игроки получившие роль, или же некоторые, остаются в лобби. Но им показывается что они получили роль, а так же задание. 
#### Что должно было произойти
Игрок должен был  заспавниться в раунде, не оставаясь в лобби.
#### Что произошло на самом деле
Игрок остался в лобби, но получил свою роль.
#### Как повторить
С каким-то шансом игрок остается в лобби получив задание, это случается довольно часто, но выяснить причину и потоврить, не предоставляется возможным, за неделю это было в количестве двух раз, замечено мною. При режиме Шадоулинги - оба остались в лобби. Режим генокрады - один из трех, остался в лобби.

**Comment by dearprincesscelestia** [comment]
0. Был ли подобный баг у ролей, которые спавнятся вне станции (нюкеры, пираты, абдукторы)?

Если нет, то этот комментарий можно игнорировать. Если да, то:

1. Стоит ли у незаспавненных ролек "Вернуться в лобби, если выбранные профессии недоступны"?

Если нет, то этот комментарий можно игнорировать. Если да, то:

2. Настроены ли были хоть какие-нибудь профессии у незаспавненных ролей ("Быть ассистентом: да" или "Быть ассистентом: нет" вместе с хотя бы одной профессией с ненулевым приоритетом)?

Если нет, то, возможно, проблема в том, что раздача антагонистов не учитывает возможность спавна профессией. Если да, то:

3. Была ли свободна хотя бы одна из профессий, которые стояли в настройках незаспавненных ролей?

Если нет, то, возможно, проблема все же в том, что раздача антагонистов не учитывает возможность спавна профессией. Если да, то моя теория неверна.

**Comment by P-20** [comment]
0. Нет
1. Да
2. Нет
3. -
Если у игрока выставлено возвращение в лобби, и не выставлен приоритет ни на одну/несколько профессий, его возвращает в лобби с ролью трейтора/шадоулинга/генокрада/культиста/ревера/гангера, но в случае выпадения роли, не требующей профессии, его спавнит на данной роли и все в порядке. И, даже если приоритет на одну из профессий выставлен, и она занята, его может все равно вернуть в лобби с ролью(требует подтверждение). Вроде как, раньше не показывало получение роли если игрок остался в лобби(требует подтверждения).

**Comment by RichardJones1** [comment]
Да, выше расписано, как

**Comment by volas** [comment]
Скорее всего связанно с алтернейт опшинс, но я не понимаю, где именно проблема

https://github.com/TauCetiStation/TauCetiClassic/blob/524acdc4d2f2c33265f11dcf7aa126cf0a0bc8cb/code/controllers/subsystem/ticker.dm#L222-L224

Мы сначала выдаём профы, а уже потом роли, и не вижу, что бы оно могло отрабатывать параллельно...

Если кто-то из админов с +дебуг в игре поймает момент, нужно посмотреть в Job Debug лог (доступен в секретс при включении дебуг вербс)

**Comment by OfficerSoftheart** [comment]
@volas 
```
Job Debug info.
--------------------------------------------------------------------------------
Running DO
DO, Len: 2
DO, Running Assistant Check 1
Running FOC, Job: /datum/job/assistant, Level: 3, Flag:
AC1, Candidates: 0
DO, AC1 end
DO, Running Head Check
Running FOC, Job: /datum/job/captain, Level: 1, Flag:
Running FOC, Job: /datum/job/hop, Level: 1, Flag:
Running FOC, Job: /datum/job/hos, Level: 1, Flag:
Running FOC, Job: /datum/job/chief_engineer, Level: 1, Flag:
Running FOC, Job: /datum/job/rd, Level: 1, Flag:
Running FOC, Job: /datum/job/cmo, Level: 1, Flag:
Running FOC, Job: /datum/job/captain, Level: 2, Flag:
Running FOC, Job: /datum/job/hop, Level: 2, Flag:
Running FOC, Job: /datum/job/hos, Level: 2, Flag:
Running FOC, Job: /datum/job/chief_engineer, Level: 2, Flag:
Running FOC, Job: /datum/job/rd, Level: 2, Flag:
Running FOC, Job: /datum/job/cmo, Level: 2, Flag:
Running FOC, Job: /datum/job/captain, Level: 3, Flag:
Running FOC, Job: /datum/job/hop, Level: 3, Flag:
Running FOC, Job: /datum/job/hos, Level: 3, Flag:
Running FOC, Job: /datum/job/chief_engineer, Level: 3, Flag:
Running FOC, Job: /datum/job/rd, Level: 3, Flag:
Running FOC, Job: /datum/job/cmo, Level: 3, Flag:
DO, Head Check end
DO, Running AI Check
DO, AI Check end
DO, Running Standard Check
Running FOC, Job: /datum/job/captain, Level: 1, Flag:
Running FOC, Job: /datum/job/hop, Level: 1, Flag:
Running FOC, Job: /datum/job/hos, Level: 1, Flag:
Running FOC, Job: /datum/job/chief_engineer, Level: 1, Flag:
Running FOC, Job: /datum/job/rd, Level: 1, Flag:
Running FOC, Job: /datum/job/cmo, Level: 1, Flag:
DO pass, Player: Softheart, Level:1, Job:Quartermaster
Running AR, Player: Softheart, Rank: Quartermaster, LJ: 0
Player: Softheart is now Rank: Quartermaster, JCP:0, JPL:1
Running FOC, Job: /datum/job/captain, Level: 2, Flag:
Running FOC, Job: /datum/job/hop, Level: 2, Flag:
Running FOC, Job: /datum/job/hos, Level: 2, Flag:
Running FOC, Job: /datum/job/chief_engineer, Level: 2, Flag:
Running FOC, Job: /datum/job/rd, Level: 2, Flag:
Running FOC, Job: /datum/job/cmo, Level: 2, Flag:
Running FOC, Job: /datum/job/captain, Level: 3, Flag:
Running FOC, Job: /datum/job/hop, Level: 3, Flag:
Running FOC, Job: /datum/job/hos, Level: 3, Flag:
Running FOC, Job: /datum/job/chief_engineer, Level: 3, Flag:
Running FOC, Job: /datum/job/rd, Level: 3, Flag:
Running FOC, Job: /datum/job/cmo, Level: 3, Flag:
DO, Standard Check end
DO, Running AC2
*******
 
job: Test Subject, current_positions: 0, total_positions: -1
job: Captain, current_positions: 0, total_positions: 1
job: Head of Personnel, current_positions: 0, total_positions: 1
job: Quartermaster, current_positions: 1, total_positions: 1
job: Cargo Technician, current_positions: 0, total_positions: 2
job: Shaft Miner, current_positions: 0, total_positions: 3
job: Recycler, current_positions: 0, total_positions: 2
job: Bartender, current_positions: 0, total_positions: 1
job: Chef, current_positions: 0, total_positions: 1
job: Botanist, current_positions: 0, total_positions: 3
job: Janitor, current_positions: 0, total_positions: 1
job: Barber, current_positions: 0, total_positions: 1
job: Librarian, current_positions: 0, total_positions: 1
job: Internal Affairs Agent, current_positions: 0, total_positions: 2
job: Clown, current_positions: 0, total_positions: 1
job: Mime, current_positions: 0, total_positions: 1
job: Chaplain, current_positions: 0, total_positions: 1
job: Chief Engineer, current_positions: 0, total_positions: 1
job: Station Engineer, current_positions: 0, total_positions: 5
job: Atmospheric Technician, current_positions: 0, total_positions: 3
job: Technical Assistant, current_positions: 0, total_positions: 3
job: Chief Medical Officer, current_positions: 0, total_positions: 1
job: Medical Doctor, current_positions: 0, total_positions: 4
job: Paramedic, current_positions: 0, total_positions: 2
job: Chemist, current_positions: 0, total_positions: 2
job: Geneticist, current_positions: 0, total_positions: 2
job: Virologist, current_positions: 0, total_positions: 1
job: Psychiatrist, current_positions: 0, total_positions: 1
job: Medical Intern, current_positions: 0, total_positions: 3
job: Research Director, current_positions: 0, total_positions: 1
job: Scientist, current_positions: 0, total_positions: 3
job: Xenoarchaeologist, current_positions: 0, total_positions: 3
job: Xenobiologist, current_positions: 0, total_positions: 2
job: Roboticist, current_positions: 0, total_positions: 2
job: Research Assistant, current_positions: 0, total_positions: 3
job: Head of Security, current_positions: 0, total_positions: 1
job: Warden, current_positions: 0, total_positions: 1
job: Detective, current_positions: 0, total_positions: 1
job: Security Officer, current_positions: 0, total_positions: 5
job: Forensic Technician, current_positions: 0, total_positions: 1
job: Security Cadet, current_positions: 0, total_positions: 3
job: AI, current_positions: 0, total_positions: 0
job: Cyborg, current_positions: 0, total_positions: 0

```

**Comment by Belfogor** [comment]
@volas Бытует мнение, что подобное возникает из-за 
![image](https://user-images.githubusercontent.com/12851693/65448362-49912400-de41-11e9-8935-624c0209cb2f.png)

**Comment by GreyGunner** [comment]
Ого... а так можно было что ли

**Comment by ZVee** [comment]
>Мы сначала выдаём профы, а уже потом роли, и не вижу, что бы оно могло отрабатывать параллельно...

Это не совсем так, некоторые режимы назначают роли до `SSjob.DivideOccupations()` т.е в `can_start()` перебивая заранее `assigned_role` чтобы `DivideOccupations` их игнорировал, например таже нюка. А режимы которым требуется в дополнение к профе докинуть роль, и игроков которые пытаются фармить роли выставлением всех проф на 0 и возвращением в лобби - попросту грифонят систему.

Еще кстати не используется фича с тем, что `DivideOccupations` умеет возвращать TRUE/FALSE, правда шанс что будет `unassigned == 0` крайне мал. Но можно что-нибудь туда закинуть еще.
