### ISSUE TITLE
[Task] Floor update_icon

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#11873]
У пола есть забавный прок
https://github.com/TauCetiStation/TauCetiClassic/blob/4dc744f7ca7571ef56f4b42d92e52163e54208e4/code/game/turfs/simulated/floor.dm#L155

который стоило бы аннигилировать в пользу отдельных апдейтов саптипов, но среди прочего и во что я случайно вляпался, это

https://github.com/TauCetiStation/TauCetiClassic/blob/4dc744f7ca7571ef56f4b42d92e52163e54208e4/code/game/turfs/simulated/floor.dm#L159-L161

сброс иконстейта любых плиток в ``icon_plating``, при том, что мы нигде кроме астеройда не указываем этот самый ``icon_plating``. 

Я не представляю, в чем была задумка. Сейчас если что-то вызовет плитке update_icon - её стейт сбросится до дефолтного. А вызывать может, например, ``floor/grass`` для тайлов вокруг. Зачем он это делает - это тоже хороший вопрос.

В общем нужно провести ревизию, посмотреть где и как оно вообще используется, и почистить так, чтоб ничего не сломалось.

**Comment by Mercurialaste** [comment]
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/90282587/94ce7216-2851-4886-bfa6-98960d940a8e)

**Comment by volas** [comment]
Я стал чуть лучше понимать этот код, в моем случае проблема была всё же в не заданном ``icon_regular_floor`` и тупом хардкоде "особенных" стейтов в ``list/icons_to_ignore_at_floor_init``.
