### ISSUE TITLE
[Proposal] Специализированные вещи в аплинке

### ISSUE THREAD

**Issue by maleyvich** [TauCetiStation/TauCetiClassic#11886]
#### Подробное описание проблемы

перенести с тг возможность закупать в аплинке трейторов, вещи специфичные для роли агента и расширить эту механику, позволяя покупать только определенные вещи антагам

пример: медик сможет закупать только яды и хирургический дуффельбаг (ещё что-то накинуть)
учёный сможет купить всякие технологические штуки
каргошник сможет купить ОРУЖИЕ
детектив и криминалист ограничений иметь не будут

**Comment by Deahaka** [comment]
Нет, это плохо

**Comment by Tobyyyan** [comment]
Мета мета мета, зная, что только медик может купить что-то, не нужно будет гадать, кто совершил преступление

**Comment by maleyvich** [comment]
> Мета мета мета, зная, что только медик может купить что-то, не нужно будет гадать, кто совершил преступление

на смене может быть много врачей / детектив и криминалист по задумке не имеют ограничений (незнаю это лишь предложение такое)

**Comment by KIBORG04** [comment]
Хуита

**Comment by maleyvich** [comment]
ладно
