### ISSUE TITLE
[Proposal] Увеличение необходимого кол-ва игроков для Stroechka

### ISSUE THREAD

**Issue by KatoMarika** [TauCetiStation/TauCetiClassic#11898]
#### Подробное описание проблемы
Строечка не появляется в ночных раундах из-за высокого онлайна до конца раунда
#### Что должно было произойти
Строечка в ночных раундах при низком онлайне
#### Что произошло на самом деле
Нет строички в ночных раундах
#### Как повторить
В раунде на 50 человек начать воут на карту, не увидеть там СТРОЕЧКА, пикнуть что угодно, пойти спать оставив 15 человек, половина из которых в обсерве и не получить СТРОЕЧКА
#### Дополнительная информация:
Согласно информации из конфигов которые можно скачать текущее появление стройки: 10 игроков. Предлагаю поднять как до Фалкона (25) или 20.

**Comment by Tap0r** [comment]
Там нету такого количества шкафов лута профессий, в принципе места, чтобы оно на 20 человек работало. Хотите строечку идите на третий второй сервер. 

Можно как альтернативу сделать строечку для большего онлайна.

**Comment by KatoMarika** [comment]
Так у нас не все играющие = весь онлайн, нужно учитывать это. Особенно ближе к 12 ночи по МСК

**Comment by Kiromaka** [comment]
> 

Ну так это строечка, голый побегаешь потом сошьёшь себе одежду
