### ISSUE TITLE
Потерянный спрайт пушки

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#11921]
#### Подробное описание проблемы
/obj/item/weapon/gun/energy/laser/scatter
Нет скина у оружия
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/d7839d26-70fb-418f-9e85-ac422755ca1a)
#### Что должно было произойти
Скин у пушки
#### Что произошло на самом деле
Скина нет, а пушка стреляющая 3-мя лазерами есть
#### Дополнительная информация:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/274def91-9a67-418a-b037-c34f6a9a140f)

**Comment by Kiromaka** [comment]
Ее вообще можно не на локалке получить ?  Если да, то думаю можно поставить спрайт лазер-пушки и добавить тег на рисование спрайта.
