### ISSUE TITLE
IPC очень хотят спать.

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#11947]
#### Подробное описание проблемы
СПУ хотят спать из-за воздействия артефакта.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/57403011/df5fe71a-717d-4f2b-872b-62517e91182e)

#### Что должно было произойти
СПУ не хотят есть и спать?
#### Что произошло на самом деле
СПУ - это органики на минималках.
#### Как повторить
Притащить артефакт с шахты.
#### Дополнительная информация:
#60737

**Comment by Kiromaka** [comment]
фича, добавлять артефакту проверку на species долго, и вобще добавит 0.0000001сек задержки
