### ISSUE TITLE
Генокрады и их баги

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1195]
#### Подробное описание проблемы

Криво работают способности: ~~Стелс от ИИ,~~ стазиз, армблэйд-кувалда-хлыст. Эпенефрин овердоз.(скорее всего у флэшменда тот же баг что у стазиса

#### Что должно было произойти

армлэйд-хлыст-кувалда: скинуться наручники, возможность заспавнить в обоих руках эти вещи
~~Стелс от ИИ- должен давать инвиз от ИИ~~
Эпенефрин овердоз: НЕ ДОЛЖЕН УБИВАТЬ ТЕБЯ(а накидывает 20 синаптизина)
Стазис(флэшменд) должны регенить скальпель порезы

#### Что произошло на самом деле

армлэйд-хлыст-кувалда: наручники не спадают, нельзя заспавнить в двух руках
~~Стелс от ИИ- даёт только невозможность тебя затрэкать(юзлесс)~~
Эпенефрин овердоз: юзнул-соснул
Стазис(флэшменд): НЕ ЗАРЕГЕНИЛО ПОРЕЗЫ ОТ СКАЛЬПЕЛЯ ЛЕЖИШЬ В ГОЛОКРИТЕ ВЕСЬ СРАНЫЙ РАУНД

#### Как повторить

Зайти за геноеда и использовать выше указанное

#### Дополнительная информация:

Так-же флэшменд по идее должен регенить кости\перелом т.к. он аналог стазиса

Согорела жопа от стазиса

**Comment by sovok4** [comment]
>Стелс от ИИ- должен давать инвиз от ИИ

nyet nyet nyet стелс от ИИ делает невозможным выслеживание через Track camera и следование камеры ИИ за генокрадом.

**Comment by Raschert0** [comment]
>Эпенефрин овердоз: НЕ ДОЛЖЕН УБИВАТЬ ТЕБЯ(а накидывает 20 синаптизина)
Так и задумано

**Comment by Olt1771** [comment]
Читаем описание и понимаем что когда то кто то сломал абилку http://prntscr.com/edcqzs

Тот же самый случай с пулемётом у мехов, мне рьяно доказывают что он резиновый, но когда я пришёл в сску он стрелял нормально по 20 брута, потом его сломали

**Comment by sovok4** [comment]
Ну, читаем описание: "Обнаруживать жизненные формы на камерах". Ну так _Трэк виз камера_ их и не обнаруживает. Но картинка-то идет.

**Comment by Raschert0** [comment]
@Olt1771 http://prntscr.com/edcw1r

**Comment by ZVee** [comment]
>Стелс от ИИ- должен давать инвиз от ИИ

Нет, не должен. Существует две версии камуфляжа - бей и тг. На бее камуфляж всегда блочил только трекинг, ТГ - на текущий момент дает инвиз. Если вспомнить чей у нас билд, не трудно сделать вывод.

https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/mob/mob_defines.dm#L205 - смотрим эту строку, читаем к ней справа коммент. Недостаточно доказательств? Делаем поиск по этой переменной в билде и изучаем где оно используется.

**Comment by Raschert0** [comment]
Поменял немного текст ишью

**Comment by Kurshan** [comment]
Флешменд ни черта не стазис. Там от функционала стазиса где-то 5%-10%

**Comment by Dennok** [comment]
Флешменд же регенит только мясо.

**Comment by Raschert0** [comment]
Ну, в описании на вики, ЕМНИП, написано что-то в духе "Как стазис, но вы не падаете замертво"
