### ISSUE TITLE
Лава-пол не соответствует по палитре новой плитке

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#11957]
#### Подробное описание проблемы
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/26389417/3f189c7e-255f-4363-a721-e8aefc8872e7)

#### Что должно было произойти
Сливается
как тут
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/26389417/65288ef3-d796-4d1e-a85b-7bf0eeba4eba)

#### Что произошло на самом деле
Видно, что не сливается

**Comment by volas** [comment]
Можешь еще приложить как было?

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/11928
