### ISSUE TITLE
Фидбек по свету #11943

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#11958]
#### Подробное описание проблемы
Фидбек по #11943

#### Что должно было произойти
-
#### Что произошло на самом деле

Скрин от @AndroBetel
ЦК, выход/вход на шаттл эвака/экипажа. Пересвет
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/94216189-918b-4ecd-b521-081a92fd1225)
Мехи ОБР, Недосветлил
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/ead11273-ab58-4b97-8997-96023acfbd10)
Шаттл на ЦК сильно пересветлен
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/9db2dad0-c145-45e4-947b-a10f627d08c7)
ОБР недосветлено
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/a2bb8df9-c942-4651-a842-214358fa3ff5)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/678abde0-10ad-48f5-9031-1a706810f984)
А аванпосты у шахтеров половина светлая, половина темнная
У науч тоже самое.

#### Как повторить
-
#### Дополнительная информация:
-

**Comment by Doom1Drake** [comment]
Смотрю в камеры, вижу вот такое, да
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/98335138/9fee3e86-0b59-4938-ae8b-43c9d5e711ce)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/98335138/d86baa62-fbbf-4bb6-a90a-c2bf000f0072)

**Comment by NikMaestro** [comment]
Нет чтобы насрать на форум, нееет мы будет срать на гитхаб.
