### ISSUE TITLE
АдматовоГолемо проблемы

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1196]
#### Подробное описание проблемы

Голем является человек в арморе голема

#### Что должно было произойти

Всё с точностью да наоборот ниже указанного

#### Что произошло на самом деле

Голем должен быть отдельной рассой, лучше всего с частичной механикой СПУ.

Голему можно оторвать конечности, голем получает голоурон, голем умирает от кровотечения

#### Как повторить

Создать голема и начать его резать

**Comment by WallShrabnic** [comment]
Я не понял, големы же не люди и не должны умирать от кровотечения. А ты считаешь это багом. Или ты перепутал второй и третий пункты?

**Comment by Olt1771** [comment]
Да напутал пункты

**Comment by Olt1771** [comment]
Точно ещё и проблема в том что големов хагами не поднять вообще, тоже нужно пофиксить(если его кнокнуло разгермой)

**Comment by Raschert0** [comment]
Но с хагами всё как и планировалось
