### ISSUE TITLE
Выстрел тазера с новым освещением вырви глаза

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#11962]
#### Подробное описание проблемы
Тазер на фоне остальных выстрелов слишком яркий, прям вырви глаза себе.

#### Что должно было произойти
Тазер не настолько светлый и глаза не хочется вырывать
#### Что произошло на самом деле
Без Пнв
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/5aadcd02-0495-4a84-81d6-19b80868804f)
С ПнВ
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/c100bcfe-4a89-4d1c-9a66-98d618b8efd8)

#### Как повторить
-
#### Дополнительная информация:
#11943

**Comment by DarkFurrSss** [comment]
Та нормально вроде. Тазер и должен быть по сути своей ярким

**Comment by DarkFurrSss** [comment]
Выглядит классно
