### ISSUE TITLE
Рюкзак с увеличенной емкостью

### ISSUE THREAD

**Issue by QWxiZ** [TauCetiStation/TauCetiClassic#11975]
#### Дополнительная информация:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/143294254/19618fb0-742a-457b-a15a-95d971ae2539)
Заспавнился на детективе с особкой, имел флафф и дофига вещей в лодауте

**Comment by Slavik2001** [comment]
Так емкость же не увеличена. Просто тебе было выдано раундстартовое снаряжение детектива+лодаут+особка не изменяя ее емкость. Ты сможешь спокойно вытащить вещи, но засунуть обратно не сможешь пока не будет больше свободного места.

Если ты имеешь ввиду баг что вещи выдаются даже сверх лимита, то как по мне это не баг. Можешь уточнить как бы ты хотел это видеть?

**Comment by QWxiZ** [comment]
> интерфейс буквально налезает на кнопки, а затем улетает за экран
> не баг



> Так емкость же не увеличена.

Я так просто лаконично ишшуй назвал.



> Можешь уточнить как бы ты хотел это видеть?

Лучше под жопу космонавта, чем так криво; а вообще, у нас в звездом созвездии таукита есть такая отличная вещь, как plastic bag, и можно сделать загруженного космонавтика, у которого в руках два пакета из пятерочки и один на поясе - тогда точно места хватит.
