### ISSUE TITLE
Create Command Report частично сломан

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#11977]
#### Подробное описание проблемы
Ломается после ~5 и более создания аннонсов
#### Что должно было произойти
Не должен ломаться
#### Что произошло на самом деле
Кнопка просто перестаёт быть кликабельной, а если кликать, то появляется рантайм
#### Как повторить
Создавать анонсы пока не сломается
#### Дополнительная информация:
Раунд 60803 сломался примерно на часе игры

**Comment by Pirsnya** [comment]
`Cannot read null.mob in code/modules/admin/secrets/secrets_menu.dm:23 :`

**Comment by Pirsnya** [comment]
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/35347896/ee569bc6-8734-43e7-a41a-0ea76d18866e)

**Comment by volas** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/6367

я хз, почему 
https://github.com/TauCetiStation/TauCetiClassic/blob/087146c42c9ccf5d1bb8a0fe2fef549f6d9b34f6/code/modules/admin/secrets/secrets_menu.dm#L3

находится по такому меню, оно не должно иметь отношения к панели секретов и это просто какой-то враппер для анонсов.

я хз, почему оно инициализируется как лист
https://github.com/TauCetiStation/TauCetiClassic/blob/087146c42c9ccf5d1bb8a0fe2fef549f6d9b34f6/code/modules/admin/secrets.dm#L4
(и вообще в панели секретсов)

в общем где-то плохой код

**Comment by atik1n** [comment]
@volas, собственно после прочтения всего этого бреда, что я писал:

> находится по такому пути, оно не должно иметь отношения к панели секретов и это просто какой-то враппер для анонсов.

Это делалось, как большой бойлерплейт, если ещё какие-то секреты будут перенесены на тгуи, например я тогда подумывал и скорее всего скоро буду переносить факс педальный на него.

> мы отпачковываем ЕЩЕ один датум для анонсов

Собственно наследуем.

Беру ету штуку на себя, посмотрю что там, вообще непонятно, почему всплыло только сейчас.

**Comment by volas** [comment]
> Это делалось, как большой бойлерплейт, если ещё какие-то секреты будут перенесены на тгуи, например я тогда подумывал и скорее всего скоро буду переносить факс педальный на него.

он не нужен и его надо удалить, это враппер над враппером (тгюи) без особой на то необходимости

**Comment by atik1n** [comment]
> > Это делалось, как большой бойлерплейт, если ещё какие-то секреты будут перенесены на тгуи, например я тогда подумывал и скорее всего скоро буду переносить факс педальный на него.
> 
> он не нужен и его надо удалить, это враппер над враппером (тгюи) без особой на то необходимости

Тогда для каждого нового секрета на тгуи надо будет делать отдельно переменную и заново делать все эти врапперы. Лично мне тогда и сейчас это кажется не очень удобным.

**Comment by volas** [comment]
Я не думаю, title/name не нужны, оно должно быть просто в шаблоне и ты не используешь тот же самый шаблон для других целей. holder - тоже скорее всего лишнее, если есть ссылка на клиента уже и проще с него взять, чем хранить ссылку на датум, который может устареть/удалиться и про которую этот датум не знает. Сам клиент - если нужно, но это можно на уровне датума интерфейса решать

**Comment by atik1n** [comment]
Я вот об этом:
```dm
	if(!holder.secrets_menu["custom_announce"])
		holder.secrets_menu["custom_announce"] = new /datum/secrets_menu/custom_announce(usr.client)
	holder.secrets_menu["custom_announce"].interact()
``` 

Этот лист нужен чтобы не создавать отдельно в холдере переменную под каждый божий тгуи секретиков

**Comment by volas** [comment]
их не обязательно хранить в холдере

**Comment by atik1n** [comment]
> их не обязательно хранить в холдере

Разве это не необходимо для того, чтобы сохранять стейт? 🤨

**Comment by volas** [comment]
пока ты окно не закроешь, оно никуда не убежит

**Comment by atik1n** [comment]
> пока ты окно не закроешь, оно никуда не убежит

Так я про то, что это сделано чтобы сохранять стейт как раз между закрытиями окна, сохранять то, что ты уже выбирал, сохранять то, что ты уже писал и тд. Для анонсов и факсов и прочих других потенциальных секретов это удобно, для этого оно и хранится в холдере.

**Comment by volas** [comment]
ну и сохраняй тогда только этот датум, зачем тебе остальные секреты то?

**Comment by atik1n** [comment]
> ну и сохраняй тогда только этот датум, зачем тебе остальные секреты то?

Так как раз для того, что если в будущем (с) это будет изменяться и захотят добавить, то тогда придётся перепиливать.
Не логично сразу всё сделать готовым для этого, а не делать всё так, что полумера?

В том числе я же и буду делать скоро факс и он тоже должен будет сохранять стейт. Поэтому зачем сейчас выпиливать функционал, а потом добавлять?

Я в ПРе с фиксом пофикшу эту проблему, а это не вижу смысла выпиливать.
