### ISSUE TITLE
Искры открывают шаттл эвакуации

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#11984]
#### Подробное описание проблемы
Искры от флешбенга почему-то открывают двери на шаттле
#### Что должно было произойти
Разгермы не должно быть, искры должны просто ударится в дверь
#### Что произошло на самом деле
Искры открывают закрытые двери как ни в чём не бывало
#### Как повторить
запустить шаттл и кинуть флешбенг
#### Дополнительная информация:
раунд 60812

**Comment by arygal** [comment]
Это так же касается обычных дверей и голограммы ИИ.

**Comment by Oz1Es** [comment]
всё что похоже на искры воспроизводит открытие, и фигня мага при джаунте тоже

**Comment by Kiromaka** [comment]
Уже было несколько похожих обсуждений, надо удалять старые искры и менять на эфект вместо ентити. Я конечно этого делать не буду.
