### ISSUE TITLE
Нелетающий мусор.

### ISSUE THREAD

**Issue by DctrMM** [TauCetiStation/TauCetiClassic#1199]
#### Подробное описание проблемы
Мусор не долетает до точки назначения
#### Что должно было произойти
Мусор должен быть на конце конвейера
#### Что произошло на самом деле
Он не вылетает из трубы
#### Как повторить
Зайти за любую профессию связанную с конвейером, кинуть мусор в трубу, придти в карго.
#### Дополнительная информация:
http://prntscr.com/edypjw

**Comment by Avatar4** [comment]
Если точнее, то disposal outlet сломались все.

**Comment by DctrMM** [comment]
У меня есть догадки, что все это сломано из-за новой анимации броска
