### ISSUE TITLE
Борги и канистры.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1200]
#### Подробное описание проблемы
Киборги не могут выпускать из канистр воздух.
#### Что должно было произойти
Киборги должны уметь выпускать воздух что бы герметизировать помещение или сжигать экипаж.
#### Что произошло на самом деле
Они не могут.
#### Как повторить
Попробовать выпустить воздух из канистры боргом.
#### Дополнительная информация:
Нет не фича. Борг может настроить питание станции - но не может ее герметизировать. В чем логика?

**Comment by ZVee** [comment]
Где-то уже был такой ищю, 

>Борг может настроить питание станции - но не может ее герметизировать.

Вперед, "аиралярмы" в боргораспоряжении которые дают доступ к скрабберам и вентам. А канистры - требуют более сложной манипуляции.

**Comment by ZVee** [comment]
А вот он #581, причем там название верное, а у тебя просто какое-то "борги и канистры" - что может говорить о многом но ничего конкретного, и да, можно было туда написать, не нужно на гите плодить дубликаты, на нем есть сортировки по любым изменениям, дашборд со всеми последними сообщениями и прочие функции.

Ладно, я разжую эту тему, т.к в той все равно ответ пошел тогда в конфу и до гита не добрался:

Для начала предложу всем боргам пожаловаться на вот эту штуку!
![gdf543](https://cloud.githubusercontent.com/assets/8426718/23378155/13005be8-fd3b-11e6-9b07-3e5b502094d7.png)
Ну как же так, ее не дают вертеть! Караул! Ну вообще борг с ключем должен уметь решить эту проблему.

Давайте ка вспомним на минутку, с чем вообще полноценно взаимодействуют борги? С тем, что имеет какое-никакое но, удаленное управление, т.е вероятно с той техникой, в которой есть какой-то радио модуль (привет И.И). Потом вспомним с чем не очень полноценно - у каждого из боргов есть определенный набор инструментов, дающий доступ к тем или иным функциям, не больше и не меньше, и даже имея ряд инструментов - они все еще не заменяют полноценно экипаж.

И да, это дело когда-то обсуждалось, а канистры можно еще расстрелять тритоборгом из лазера например (это про сжечь экипаж), может еще какие методы повреждения работают. На момент если пойдут примеры в защиту канистр где окажется, что объект_пример тоже имеет такой недочет - бойтесь фиксов!
