### ISSUE TITLE
Призыв Нар-Си в 99 случаев не работает

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#12001]
#### Подробное описание проблемы
Нажимаешь призвать нар-си, а пишет что людей мало возле алтаря
#### Что должно было произойти
Людей не мало, весь культ возле алтаря
#### Что произошло на самом деле
Пишет что людей мало
#### Как повторить
Попробовать призвать нар-си, стояло 7 человек. Человек утверждает, что бесконечно нажимал на кнопку призыва и призыв прокнул
#### Дополнительная информация:
мб дубликат, но вроде не увидел ишуя
Issue reported from  Round ID: 60848 (Tau Ceti Classic (RU))
Testmerges: ```#11939# 11967```
Reporting client version: 515.1614

**Comment by KIBORG04** [comment]
Написал бы хотя бы, че им в чат высирается. Я специально везде писал разные сообщения в чат, но выглядит так, будто ничего сломаться не может
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/26389417/0d09c353-576b-44db-8f52-e95e1ec1323d)

**Comment by KIBORG04** [comment]
Ладно, мб AOG.mobs_around как-то неправильно срабатывает, если телепортироваться через руну, сразу к алтарю. Если поставить новый алтарь, то они всех опять видит. Но это лишь моя теория
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/26389417/3235bbee-f838-4819-9ad9-04846200fad4)

**Comment by Chip11-n** [comment]
Не теория. Если выйти за пределы и зайти обратно или пересоздать алтарь, то всё работает

**Comment by Slavik2001** [comment]
У меня часто в раундах за культяпку помогало тупо делитнуть алтарь, поставить новый и провести ритуал

**Comment by Kiromaka** [comment]
> Не теория. Если выйти за пределы и зайти обратно или пересоздать алтарь, то всё работает

Это баг byonda, фиксить думаю не выйдет. Если подойти к алтарю при помощи ТП, Блинка или любого способа кроме прямого подхода ( если поставить новый алтарь в кучу людей тоже не будет работать пока не подойдут и отойдут) Алтарь просто не видит кукол рядом с ним. Ну и ты правильно сказал, просто подойти и отойти надо.
