### ISSUE TITLE
Неактуальная большая аптека у нюкеров

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1201]
Заменить все баночки с  нюкпилюерскойс  в большой  аптечке, на соответствующие комбатинжекторы. В связи с тем что роли по большей части воюют в безвоздушном пространстве. И как то неудобно получать разрыв легких, будет проще сделать аналоги комбатинжекторов по 100 кубов с соответствующими надписями на них: дирмалин, бикаридин, антитоксин (забыл что то там). Думаю суть все поняли.

В попытке написать расстворяйте в комбат инжекторе(фича да) то есть 1 момент, там от силы 5 10 кубов расстворится изза набитости до краев комбата.

**Comment by Smalltasty** [comment]
> В попытке написать расстворяйте в комбат инжекторе(фича да) то есть 1 момент, там от силы 5 10 кубов расстворится изза набитости до краев комбата.

Сам-то понял, что ты там написал?

**Comment by Kurshan** [comment]
Было сложно, но я понял. ПЕРЕВОД с механоёбского:
Если вы изволите мне предложить решение сей проблемы растворением медикаментов в комбат инжекторе, что, в свою очередь, является очередной фичей, то спешу вас расстроить т.к. в процессе вы потеряете львиную часть растворяемых медикаментов, что является неэффективным использованием довольно ограниченных ресурсов.

**Comment by dearprincesscelestia** [comment]
Проспортал вдогонку: сделать актуалли комбакт енжекторн, в котором пятьдесят кубов циандиа, чтобы использовать в качестве оружия вдогонку.

**Comment by Smalltasty** [comment]
Так он предлагает инжекторы на 100 единиц, почему там вдруг таблетки растворяться не должны? 
Предположим, что осталось 5 единиц препарата, а добавление таблетки (на максимум 50 кубов) должна дополнить как надо, про 
> там от силы 5 10 кубов расстворится 
вот это вот мне непонятно чет.

**Comment by Raschert0** [comment]
Короче, Тасти, берёшь иньектор на 100 юнитов с 95 ед. чего-либо. Берёшь таблетку на 50 ед. ещё чего-либо. Пытаешься запихнуть таблетку в иньектор. Получаешь полные иньектор на 100 ед. и ещё 45 ед. испаряются в воздухе

**Comment by Smalltasty** [comment]
А зачем пихать таблетку в 95 единиц, если, имея голову в нужном месте, ты будешь делать это, максимум, в полупустом инжекторе? 
А так, даже в бикере такое происходит, зачем об этом упоминать вообще?

**Comment by Kurshan** [comment]
> А зачем пихать таблетку в 95 единиц, если, имея голову в нужном месте, ты будешь делать это, максимум, в полупустом инжекторе?
А так, даже в бикере такое происходит, зачем об этом упоминать вообще

https://www.youtube.com/watch?v=gqqm9CMKrA4 (он тоже)

**Comment by dearprincesscelestia** [comment]
Ну мало ли какой нюкер не знает, что конбатинжекторн берет только пятьдесят кубов, а не сто.

**Comment by Olt1771** [comment]
Инжекторы на 100 т.к. там 7 таблеток на 15-25 кубов в зависимость от препарата, в связи с этим мы теряем при переводе в инжекторы часть медикаментов. А по поводу таблеток, ты не особо умный нюкер, не юзаешь комбатинжектор. Получил урон в разгерме, а таблеточку съешь=порвать легкие(у пиратесов тоже самое). По этому и предлагаю инъекторы на 100 с потерей части медикаментов.

**Comment by WallShrabnic** [comment]
Короче, достаёшь таблетку, суёшь в карман (слот слева от рук) БЫСТРО СНИМАЕШЬ ШЛЕМ И МАСКУ, заглатываешь таблетку и нацепляешь шлем обратно. Профет

**Comment by Raschert0** [comment]
И получаешь ты, Шрабник, разрыв лёгких.

**Comment by WallShrabnic** [comment]
Если всё быстро сделать - не получишь

**Comment by Dennok** [comment]
Если успеть между life()"ми

**Comment by Raschert0** [comment]
Тут как повезёт, Деннок прав.

**Comment by Skippeer12** [comment]
![image](https://user-images.githubusercontent.com/18488106/35795305-6fde57c8-0a61-11e8-93d1-d35b1a591657.png)

Done! Игигил закрывай
