### ISSUE TITLE
Телепатическое открытие Surgeon Tray

### ISSUE THREAD

**Issue by QWxiZ** [TauCetiStation/TauCetiClassic#12016]
#### Дополнительная информация:
стоишь в 10 метрах от surgeon tray
@
перетягиваешь на себя
@ 
видишь содержимое
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/143294254/fe931406-4f4d-4dfe-b102-fb41f86269c3)

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/143294254/4d966cc1-d9ab-41c6-8bae-6b72770e6ba8)

**Comment by Kiromaka** [comment]
разве дальность использования не хардкод предметов ? щас волас поставит good first issue.
