### ISSUE TITLE
Проседание частоты кадров

### ISSUE THREAD

**Issue by Dimsh04** [TauCetiStation/TauCetiClassic#12037]
#### Подробное описание проблемы
Лаги/фризы/потеря частоты кадров при попадании в куклу
#### Что должно было произойти
Всё круто, классно, при попадании в куклу предмета/прожектайла/лазера нет фризов/лагов/потери частоты кадров.
#### Что произошло на самом деле
После попадания в куклу начинает дико провисать игра.
#### Как повторить
Стрельнуть по кукле на которой играешь, бросить предмет.
#### Дополнительная информация:
Issue reported from  Round ID: 60913 (Tau Ceti Classic (RU))
Testmerges: ```#11939# 11967```
Reporting client version: 514.1589
Есть вероятность, что это мои дрова уже не вывозят минимальный порог тау киты, хдд.

**Comment by volas** [comment]
у нас было много абстрактных жалоб, но это первый раз, когда кто-то зарепортил с подробностями наконец. Если кто сталкивался - можете написать свой опыт.

**Comment by KIBORG04** [comment]
> Reporting client version: 514.1589

Пусть еще 515 поставит

**Comment by Kiromaka** [comment]
Такое трудно повторить, может если в виртуалке запустить )

**Comment by Chip11-n** [comment]
Встречал такое на своём старом ноутбуке. Появляется в первую очередь при попадании лазера в персонажа, а также при варке без очков. Опытным путём на локалке выяснил, что причиной проблем лично у меня были блюр фильтры.

**Comment by Kiromaka** [comment]
> Встречал такое на своём старом ноутбуке. Появляется в первую очередь при попадании лазера в персонажа, а также при варке без очков. Опытным путём на локалке выяснил, что причиной проблем лично у меня были блюр фильтры.

Когда проверял, щас фильтров стало еще больше, видимо тау сети больше не для пентиумов.

**Comment by volas** [comment]
https://github.com/TauCetiStation/TauCetiClassic/blob/7a584a5cc773804ec668dc3d4b4788688ed71fe6/code/modules/mob/living/living.dm#L411-L420

Значения тут вроде не большие, только что фильтра два. Единственное что, кажется они из лайфа моба каждый тик могут перенакладываться, даже если значения те же.

**Comment by AmnyamNyam** [comment]
Такая же проблема. У меня в целом немного фризит временами (может из-за плохого вай-фая), но когда в куклу что-то прилетает, то начинаются кротковременные подвисания на 0.5-1 секунду.
