### ISSUE TITLE
Гитхаб Бот сходит с ума

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#12034]
#### Подробное описание проблемы
Пытался поднять тему в РнД канале, никак не отреагировали мейнторы на это. @volas , @KIBORG04 @SpaiR 
В последнее время когда выкладываешь ПРы/новые коммиты то ГитХаб Бот сходит с ума по картам и выдает ошибки. Ругается чаще всего по проверке на Строечку и Прометей на 100%, ругается на обе карты, реже на Гамму. Бокс и Фалкон никогда не ругается.

#### Что должно было произойти
Гитхаб Бот не орёт и не присылает на почту (или просто не делает красным) карты которые никак не были затронуты в коде. 

#### Что произошло на самом деле
Орёт, на Строечку и Прометей, и редко на Гамму, хотя эти карты никак не трогали 

#### Как повторить
Раз в 5-10 коммитов или при выкладывании ПРа орет на эти карты. Хотя их не трогали.

**Comment by volas** [comment]
Локально он тоже воспроизводится через раз, если следить за ``total_runtimes``.

**Comment by Kiromaka** [comment]
Обновление issue - бетель убил бота 😭💀
