### ISSUE TITLE
Анестезия не работает (?)

### ISSUE THREAD

**Issue by maleyvich** [TauCetiStation/TauCetiClassic#12036]
#### Подробное описание проблемы
На протяжении всего раунда анестезия в меде не работала.
#### Что должно было произойти
Анестезия усыпляет пациентов
#### Что произошло на самом деле
Анестезия не усыпила пациента, в следствии чего начался кошмар
#### Как повторить
алгоритм неизвестен
#### Дополнительная информация:
Issue reported from  Round ID: 60911 (Tau Ceti Classic (RU))
Testmerges: ```#11939# 11967```
Reporting client version: 515.1614

**Comment by maleyvich** [comment]
> Проблемы с лёгкими были?

нет, да и сомневаюсь что у пятерых человек подряд были проблемы с лёгкими даже если предположить такое.
на них к слову даже слип токсин не работал, очень странно

что заметил: если подключать баллон вручную, типо нацепить его и через менюшку включить - чел заснёт, думаю надо покопаться в самой машинке

**Comment by Kiromaka** [comment]
> Ну.. тут тогда кому-то с доступом к реплеям, надо смотреть, что произошло.
Видимо серверная багулина, рантаймы у каждого пациента). Слишком редкий баг чтобы реплей смотреть

**Comment by maleyvich** [comment]
получается баг был всего на один раунд... закрываю ишуй тогда
