### ISSUE TITLE
Странности фотоаппарата

### ISSUE THREAD

**Issue by DarkSauron71** [TauCetiStation/TauCetiClassic#1204]
#### Подробное описание проблемы
Если фоткать фотоаппаратом, то некоторые вещи не изображены на фотке (Наверно фотик из иного измерения, ну либо станция.)
#### Что должно было произойти
На фото должно изображаться всё, что видно персонажу.
#### Что произошло на самом деле
На фото не изображаются различные хранилища для итемов (Шкафчики, локеры ну и ящики), вотер танк.
#### Как повторить
Зайти в ССку и скатать. Взять фотоаппарат и сфоткать любой шкаф, либо вотер танк.
#### Дополнительная информация:
А ну ещё рэки в ЕВА не изображается на фото.

**Comment by ZVee** [comment]
Насколько мне известно о проблеме фотика - починить полностью его невозможно. В бъенде попросту нет возможности узнать например - есть ли у иконки 4 дира, сколько фрэймов и так далее.

**Comment by dearprincesscelestia** [comment]
https://github.com/Baystation12/Baystation12/pull/5814

У бейцов есть что-то такое, но сильно подозреваю, что это капля в море фотобагов.

**Comment by Skippeer12** [comment]
#2328

**Comment by Skippeer12** [comment]
#2021

**Comment by LudwigVonChesterfield** [comment]
#2544

**Comment by LudwigVonChesterfield** [comment]
Пока не утащим с ТГ, да.

**Comment by RichardJones1** [comment]
![image](https://user-images.githubusercontent.com/39438947/56315649-4b0b4180-6169-11e9-8aa6-5e2b16a545e6.png)

**Comment by LudwigVonChesterfield** [comment]
#3415
