### ISSUE TITLE
Брифкейс в рюкзаке

### ISSUE THREAD

**Issue by splifin2** [TauCetiStation/TauCetiClassic#12048]
#### Подробное описание проблемы
Брифкейс спавнит в рюкзаке, из-за чего его можно использовать как дополнительное хранилище предметов
#### Что должно было произойти
Брифкейс спавнит в руках
#### Что произошло на самом деле
Брифкейс спавнит в рюкзаке
#### Как повторить
Брифкейс в лодауте взять.

**Comment by Kiromaka** [comment]
фича для умных

**Comment by TRISAGI0N** [comment]
фича для тех кто знает что такое лоадауты

**Comment by TRISAGI0N** [comment]
то есть для умных
