### ISSUE TITLE
C4 который невозможно снять.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#1206]
#### Подробное описание проблемы
Если нацепить на одетого человека, в  одежде, риге и т.п. C4, то при снятии одежды он остается на теле. Но как?! 

#### Что должно было произойти
Если С4 нацеплен не на голого человека, он должен сниматься вместе с одеждой.
#### Что произошло на самом деле
На человека в одежде, риге установили С4, и снимая одежду, взрывчатка магическим образом остается, и даже если одеть одежду обратно, она поверх нее.
#### Как повторить
Нацепить на одетого человека С4, попробовать ее снять.

**Comment by WatlerJe** [comment]
Так это же фича
