### ISSUE TITLE
Некорректное наложение искр на сломанной повернутой двери.

### ISSUE THREAD

**Issue by KatoMarika** [TauCetiStation/TauCetiClassic#12085]
#### Подробное описание проблемы
Если сломать дверь, то искры пойдут там, словно дверь не повернута.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/18484142/63eed4a5-3288-41a7-b228-1985d2ab5e72)

#### Что должно было произойти
Искры должны были повернуться с дверью.
#### Что произошло на самом деле
Искры остались на месте.
#### Как повторить
Пострелять в дверь или использовать на нее емаг.

**Comment by Kiromaka** [comment]
двери повертели ( а оверлей не добавили
