### ISSUE TITLE
[PRIORITE CRITICAL] Неверное отображение смайлов :khleb: :kot:

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1208]
#### Подробное описание проблемы

Напутаны спрайты :khleb: :kot:

#### Что должно было произойти

При вводе должны отображаться верные смайлы

#### Что произошло на самом деле

Неверное отображение смайлов

#### Как повторить

Ввести :khleb: :kot:

**Comment by dearprincesscelestia** [comment]
Все там правильно стоит.

**Comment by igigin** [comment]
Славный механобоб Ольт не смог.
