### ISSUE TITLE
ИИ не хочет вайпаться

### ISSUE THREAD

**Issue by StrikS** [TauCetiStation/TauCetiClassic#1209]
#### Подробное описание проблемы
После нажатия вайп коре ии не вайпается.
![image](https://cloud.githubusercontent.com/assets/15943769/23572667/718708ba-0092-11e7-8ce7-a945ab1a7301.png)
Кроме того:
![image](https://cloud.githubusercontent.com/assets/15943769/23572698/b80a286c-0092-11e7-9446-fe5a1635cabc.png)

#### Дополнительная информация:
Обычный раунд за ИИ, в щитспавне не участвовал, дверьми не жевал.

**Comment by Kurshan** [comment]
Насколько помню, такое только у триторов. И да. Это самый часторепортируемый баг.
https://github.com/TauCetiStation/TauCetiClassic/issues/744
https://github.com/TauCetiStation/TauCetiClassic/issues/540
https://github.com/TauCetiStation/TauCetiClassic/issues/535
