### ISSUE TITLE
Атмос.

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#121]
Originally reported by: **Belfogor (Bitbucket: [Belfogor](http://bitbucket.org/Belfogor), GitHub: [Belfogor](http://github.com/Belfogor))**

---

Атмос криво "перетекает" через наружные, красные шлюзы. Точнее вообще ничего не происходит, при условие что оба шлюза открыты. Хотя если честно не могу утверждать что это касается всех шлюзов, баг был замечен только в отбытие. 

На снимке хорошо видно. в отбытие давление куда ниже чем на челноке, но за все время что челнок был пришвартован к станции давление и близко не выровнялось. 

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/121

**Comment by Raschert0** [comment]
#1025
