### ISSUE TITLE
Игра бесконечно ищет импостеров.

### ISSUE THREAD

**Issue by WhaleNotPower** [TauCetiStation/TauCetiClassic#12135]
#### Подробное описание проблемы
На станции с 8 сотрудниками, половина из них это некие "Imposters", которым игра продолжает накидывать еще целей.
#### Что должно было произойти
Игра фиксирует количество антаг ролей от количества сотрудников на станции
#### Что произошло на самом деле
Игра не фиксирует количество антаг ролей и продолжает накидывать импостеров всем кому не лень или дублируя цели уже существующим антагонистам. 
#### Как повторить
Зайти в раунд с Imposter
#### Дополнительная информация:
Issue reported from  Round ID: 61076 (Tau Ceti Classic (RU))
Testmerges: ```#12116# 12134```
Reporting client version: 514.1589

**Comment by Venngedi** [comment]
#12850
