### ISSUE TITLE
Откатывайте  или фиксите уже импостеров

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#12137]
#### Подробное описание проблемы
Импостеры сломали падение ролек даже без префоф
#### Что должно было произойти
Челу без рольки ничего не падает.

#### Что произошло на самом деле
Упало
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/75d99e2c-b68a-453b-8671-668554ca8c5e)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/7d9c91ad-30de-4947-b5cb-edc3ee326241)

#### Как повторить
Рандом от импостеров
#### Дополнительная информация:
Issue reported from  Round ID: 61077 (Tau Ceti Classic (RU))
Testmerges: ```#12116# 12134```
Reporting client version: 514.1589

**Comment by AirBlack** [comment]
бэд ищюй дескрипшон закрывай ишюй

**Comment by Deahaka** [comment]
Фича
