### ISSUE TITLE
[Proposal] Удалить режим импостеров.

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#12140]
#### Подробное описание проблемы
Неиграбельная хуйня. Багованная херня. Выдает импосторки мышам, блобам блять и так далее. Так еще и выдает эти роли даже тем, у кого роли антагов отключены. Но и этого было мало, тебе импостер может выпасть несколько раз за раунд, поэтому к концу раунда может быть до 20 целек. Которые нужно выполнить не имея ничего из набора триторов.

Короче кал ебаный, я не понимаю, почему его обратно в ротацию вернули.

Вместо ИнТеРеСнЫх СиТуАцИй получили бред на станции, где каждый член персонала импостер и капитан бегает вырезает экипаж, а также робустит офицеров плеткой.

**Comment by Deahaka** [comment]
Никто не обязывает, считай это "кастомными целями от админа".

**Comment by Deahaka** [comment]
Этот ишуй ещё актуален? Если я злобный бот пристаю к вам, напишите комментарий.

**Comment by Deahaka** [comment]
Это впечатление, которое вы сами строите. Не нужно никаких слов, просто играйте как обычно. Вам ничего не мешает, баги не крашат сервер и не вызывают котов по всей станции. Мелочь пофиксится чуть попозже.

**Comment by volas** [comment]
Со вчерашнего дня импостеры выключены из сервера, вернуться после фиксов #12138

**Comment by Deahaka** [comment]
Полагаю, пофикшено
