### ISSUE TITLE
Автотриторам дважды выдаются кодовые слова и соратники

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#12146]
#### Подробное описание проблемы
Автотриторам дважды выдаются их кодовые слова и соратники.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/90282587/3a5f5f80-ba21-4985-bc9a-172651a84224)

#### Что должно было произойти
Выдаются единожды.
#### Что произошло на самом деле
Выдались дважды.
#### Как повторить
Получить автотритора?
#### Дополнительная информация:
Report round: #61091

**Comment by Deahaka** [comment]
Должно быть пофикшено
