### ISSUE TITLE
Малфовские апц.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1215]
#### Подробное описание проблемы
Апц взломанные малфом никак не починить. Даже не разбить огнетушителем.
#### Что должно было произойти
Малфовские апц можно деактивировать пересобрав их.
#### Что произошло на самом деле
Чем только по нем не кликай - а в результате ты атакуешь апц вещью и даже не можешь сломать.
#### Как повторить
Зайти малфом - взломать одно апц. Зайти инженером - попытаться починить.

**Comment by Raschert0** [comment]
Разве у них закрытая крышка? Точно нельзя открыть ломом или снять крышку отвёрткой? Просто я их пересобирал за дрона, но не помню, нужно ли было разблокировать

**Comment by Avatar4** [comment]
Я пробовал всеми инструментами, пда с картой, огнетушителем. Нихуя. Даже разблокировать апц не мог.

**Comment by Dennok** [comment]
Да, открыть взломанный апц невозможно за человека. За синтета возможно можно открыть крышку, и разобрать.

**Comment by P-20** [comment]
Взломаные не малфом АПЦ можно разбить и разобрать.
Вломаные же малфом, устойчивы к любым повреждениям кроме взрыва. Поэтому чтобы их разобрать либо просите лимитку в РнД, либо по общему каналу просить  сифор

**Comment by Skippeer12** [comment]
#275 -> Enjoy your stay
