### ISSUE TITLE
Полностью сломанные СПУ

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1216]
#### Подробное описание проблемы

После видать последнего фикса, окончательно были сломаны СПУ и "ребаланс" их сделал тотальна уничтожаемыми что не позволяет им жить вовсе(это отступление)

СПУ при получении любого урона в 75 на сундук(chest) инстантно гибаются. До "ребаланса" СПУ получал удвоенный бёрн урон и 1/10 урон от брута (то есть по сути он получал мизер от любого огнестрела то есть в 10 раз меньше чем кукла людей). В итоге СПУ при выстрела с лазура в чест гибается, при попадании с револьвера гибается, умирает от 4 ударов балоном в чест(любыми предметами из тулбокса). Брут у него увеличился в 2 раза(может больше не ясно).

А так же он всё ещё имеет возможность задыхаться когда он в крите(уберите гаспы когда он в крите).

И СПУ всё так же получает не ясным образом голоурон

#### Что должно было произойти

СПУ не должно гибать от попаданий в чест любыми типами урона. Он должен получать удвоенный урон от бёрна и 1\3-5 от брута

#### Что произошло на самом деле

СПУ гибает от 75 брута\бёрна в чест. Он имеет Гаспы когда в крите. И он не ясным образом получает голоурон

#### Как повторить

Зайти на сервер, заспавнить СПУ стрельнуть\ударить\порезать чест. Закинуть СПУ в крит. Наносить голоуронон оружием

#### Дополнительная информация:

Возможно человек с мех конечностями так же гибается, но это не точно(не тестил).
И есть теория что именно держащая часть(чест при отлёте ведь она если получает 75 брута отлетает) то все закреплённые конечности отпадают

**Comment by ZVee** [comment]
Ничего не обещаю насчет прочности, но всякие "гаспы" и голоурон уйдет.

**Comment by Dennok** [comment]
Ура, может голоурон с протезированных частей еще уйдет?

**Comment by ZVee** [comment]
С самих скорее всего (если они считаются в общий пул), а вот может еще быть момент такой - например протез выдрало очень жестко и повредило частично сокет в который и вставлялся протез, а это уже может соседствовать с живой плотью и менять все в корне. Но это так, мысли в слух.

**Comment by Olt1771** [comment]
О на гитхабе разбанили, так вот это изза самих мех конечностей, что при определенном колве они отваливаются(а чест и гроин не должны отпадать)

**Comment by Avatar4** [comment]
Не баг а фича. Прикрутите остальным ксеносам.

**Comment by Dennok** [comment]
>протез выдрало очень жестко и повредило частично сокет в который и вставлялся протез. 
Да это интересная идея, но если ее реализовывать то надо много чего продумать.
Да и вообще, есть ведь такая штука как переползающий урон ведь. можно через него реализовать.
