### ISSUE TITLE
Репликаторы могут бесконечно есть ковер на Гамме

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#12166]
#### Подробное описание проблемы
Репликаторы могут бесконечно есть ковер на карте Гамма, в прибытии, получая бесконечные ресурсы.
#### Что должно было произойти
Ковер съедается как стандартная плитка

**Comment by AgRevol** [comment]
Какой это ковер? Проблема существует только на гамме?

**Comment by Pirsnya** [comment]
> Какой это ковер? Проблема существует только на гамме?

Там где вроде заброшенная библиотека есть ковер

**Comment by F0xiq** [comment]
Ковер прямо в прибытии, под шаттлом, проблема замечена только на гамме.

**Comment by KatoMarika** [comment]
На локалке проверил, и не только на Гамме повторилось, видимо общая проблема ковров.

**Comment by volas** [comment]
стоило сразу обратить моё внимание, все же знали что я полы тем летом рефакторил
