### ISSUE TITLE
Хвосты у лизардов (некорректный спрайт хвостов).

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#1218]
#### Подробное описание проблемы
Спрайт хвоста съехал на пиксель, так же эта проблем наблюдается у малой разгрузки на три слота.
#### Что должно было произойти
Все должно выглядеть нормально.
#### Что произошло на самом деле
Спрайты двигаются сами по себе.
#### Как повторить
Зайти в ССку и поиграть.
#### Дополнительная информация:
Возможно хвосты отъезжают после того как егрок снимет и наденет костюм который его убирает. Но с разгрузкой это уже давно.

**Comment by Raneman** [comment]
с оверлеями на части причесок та же херня. ну, на тех прическах на которых есть оверлеи.

**Comment by ZVee** [comment]
Можно скрины под увеличительным? Т.к я не заметил смещений когда тестил, либо точное название (парочку) вещей из-за которых происходит.

**Comment by WatlerJe** [comment]
https://i.gyazo.com/1c20ead70f4162fb0869bb256d5b4fd3.png

**Comment by ZVee** [comment]
Я нашел виновника - https://github.com/TauCetiStation/TauCetiClassic/pull/952
