### ISSUE TITLE
плохой перевод взаимодействий с самодельным арбалетом

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#12193]
#### Подробное описание проблемы
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/84613249/49a43bf8-bf0e-423c-964d-b66a5acfb468)
#### Что должно было произойти
перевода, наверное, нет или в нём не используются ссылки на названия объектов
#### Что произошло на самом деле
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/84613249/49a43bf8-bf0e-423c-964d-b66a5acfb468)
#### Дополнительная информация:
и что сука обидно его описание не перевели
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/84613249/2a81c03c-30af-48e6-b45c-cc29abc81d8c)

**Comment by Kiromaka** [comment]
Фича наших переводов ). Объекты мы не переводим, а в переводе ссылка на название объекта. Можно заменить ссылку на прямое упоминание арбалета. Короче @AzzyDreemurr13  иди фикси

**Comment by Kiromaka** [comment]
https://www.youtube.com/watch?v=3W40tBACFbI
