### ISSUE TITLE
Раскраска карты невозможна!

### ISSUE THREAD

**Issue by Rumpiturs** [TauCetiStation/TauCetiClassic#12194]
#### Подробное описание проблемы
ID painter должен красить карты но этого не происходит так как карта с 64x64 становиться 32x32 идёт выбор покраски покраска завершается карта становиться нужного цвета- карта спустя 5 секунд становится 64x64 и возвращается в свою  оригинальную версию либо засунуть в рюкзак,пда и т.д карта возвращается в свою  оригинальную версию.
#### Что должно было произойти
Покрасил карту 
#### Что произошло на самом деле
Покрасил карту и она вернулась в свою  оригинальную версию
#### Как повторить
Покрасить карту 
#### Дополнительная информация:
Issue reported from  Round ID: 61163 (Tau Ceti Classic (RU))
Testmerges: ```#12186# 12116# 11994```
Reporting client version: 514.1589

**Comment by AirBlack** [comment]
ишью оформлен пониебом а прокомментировал его андертейлоеб боргоплеер, пожалуйста кто нибудь нормальный и кого мама любит пересоздайте ишюй
