### ISSUE TITLE
зомби и гуманоиды с геном халка не удаляют шлюз когда его выламывают

### ISSUE THREAD

**Issue by muWander** [TauCetiStation/TauCetiClassic#12213]
#### Подробное описание проблемы
шлюз не удаляется
#### Что должно было произойти
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/39914744/ba5586eb-2ed6-4483-9b9f-34f39d237cf1)

#### Что произошло на самом деле
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/39914744/f653a3dc-214d-441a-8504-7705f035f3e7)

#### Дополнительная информация:
https://github.com/TauCetiStation/TauCetiClassic/pull/11971 сломал прок door_rupture

**Comment by Oz1Es** [comment]
если шлюз на болтах он не выносится и спавнит сломанный шлюж
