### ISSUE TITLE
Камеры СПУ

### ISSUE THREAD

**Issue by QWxiZ** [TauCetiStation/TauCetiClassic#12219]
#### Подробное описание проблемы
У СПУ камеры находятся в торсе
Однако ломаются они когда бьют СПУ по голове
При этом если головы у СПУ нет то у него работают камеры

**Comment by AirBlack** [comment]
я фиксил уже такое что органы не удаляются но там случился конфуз со скелетами, которые умирали при отлетании башки т.к.. абстрактный мозг в башке, мне было лень фиксить, можешь найти под моим авторством закрытый пр или ща сюда скину

**Comment by AirBlack** [comment]
вот этот [!9756](https://github.com/TauCetiStation/TauCetiClassic/pull/9756)

**Comment by pro100kotah** [comment]
Он хотел, чтобы СПУ не слепнули при ударе по голове, но сделал хуже. Теперь СПУ без головы вообще ничего не будут видеть. Lmao.

**Comment by Mercurialaste** [comment]
> Он хотел, чтобы СПУ не слепнули при ударе по голове, но сделал хуже. Теперь СПУ без головы вообще ничего не будут видеть. Lmao.

он ничего не хотел



> #### Что должно было произойти
> #### Что произошло на самом деле
> #### Как повторить
> #### Дополнительная информация:

**Comment by QWxiZX** [comment]
> Он хотел, чтобы СПУ не слепнули при ударе по голове, но сделал хуже. Теперь СПУ без головы вообще ничего не будут видеть. Lmao.

М? Нет, я примерно такой фикс и хотел.
