### ISSUE TITLE
Примерил евросвет к нашему билду.

### ISSUE THREAD

**Issue by ZVee** [TauCetiStation/TauCetiClassic#1221]
(Т.к это рассматривалось раньше как порт, да в принципе сейчас тоже, по этой причине здесь и создаю).

Коротко о минусах:
1) Параллакс скорее всего несовместим, можно конечно рассмотреть его самую старую версию - это когда был один слой, но не факт. В чем отличие многослойного параллакса от однослойного? Разные звезды движутся с разной скоростью. Возможно это и решаемо например отвязыванием от плейнов, но я лишь быстро_примерял, так что задача о том, как это решить - не стояла. Стоит иметь ввиду что есть вероятность отказа от этой фичи с портированием этого.

2) Свет от космоса как реализован именно у нас вероятно невозможен. Есть вариант полной подсветки космоса как это было на старых версиях когда-то, либо полная темень за окном. Мне на самом деле нравятся тени на космосе, т.е когда нет разницы - в помещении без света находишься или в космосе (да, это не реалистично, да, надо брать в космос мезоны, фонари, найтвижен и прочие гаджеты, однако это совсем иная атмосфера и вовсе не такая ужасная как кажется, но это мое мнение).

3) Дальность (почти минус). С механом на данный момент и без перепланировки в очередной раз ламп на стенах и в помещениях - возвращаемся в ту ситуацию, когда впервые был принесен текущий свет с мягкими тенями, т.е на станции довольно темно, потому что лампы могут максимум освещать примерно на 5+ турфов и это хардкод-ограничение во имя производительности у них. В принципе решаемо, но лучше не стоит. Можно просто "плотность ламп на квадратный метр" повысить. Хотя Молесто вроде бы такая атмосфера понравилась, но я бы все равно сделал более менее вменяемо в коридорах, чем эта темень в коридорах что явилась на глаза. Даже моя версия "темной станции" на фоне этой кажется адекватной.

О плюсах:
1) Тени. Кто видел свет европы, поймет о чем речь.
2) Фонари или источники света с поддержкой направленного луча.

О неизвестном:
1) Вопрос производительности пока не ясен, по ощущениям в плюсы отнес бы, а по цифрам в профайлере - нет, однако я и не сравнивал с текущим, так что это впечатление в целом ничего еще не говорит, к тому же накинул фактически сверху почти ничего не делая в самом билде толком, поэтому тем более сложно ответить на этот вопрос. А еще, этот свет отвязан от контроллера, и он - контроллер служит лишь для инициализации нужного при старте сервера, что тоже меняет все в корне.

О сравнении света европы со светом европы (а точнее, о том, какой он был изначально и каким стал сейчас).
1) Очевидно что его серьезно переработали и оптимизировали.
2) Дальность раньше была без ограничений (образно), что давало конечно более оптимальное распределение источников света. Те же фонари с направленным светом освещали приличную площадь перед игроком, а сейчас - тускловатая лампочка которая создает впечатление игры в хоррор (все не настолько плохо, как описано, но разница серьезная).

**Comment by ZVee** [comment]
Насчет фонариков:
Вот довольно [старый превью](https://dl.dropboxusercontent.com/u/73967379/ss13/fl_old.webm) - другого ничего не осталось с тех времен в общем-то, но думаю охват и так виден.
А вот [текущий в полной тьме](https://dl.dropboxusercontent.com/u/73967379/ss13/fl_cur.webm).

**Comment by ZVee** [comment]
Поднял сегодня вопросы производительности:
Тг-свет в 1.8~ раза быстрее нашего, а европа в 4~ раза медленнее нашего.
Вывод прост - все еще не комфортная производительность, однако это лучше, чем было в любом случае у них, только вот ни ТГ и ни мы не можем позволить себе такой свет, а они (европа) по кое каким выясненным в ходе причинам себе могут :D, в принципе.

**Comment by Kurshan** [comment]
Хоть бы сказал, человек-размышления, что за причины то?

**Comment by ZVee** [comment]
Так ответ же выше - свет для нас в 4 раза медленнее, а если обновление с ТГ стянуть, все 8.

**Comment by SpaiR** [comment]
>а если обновление с ТГ стянуть, все 8.
в моём ПРе этот момент делается, если что

**Comment by Kurshan** [comment]
Я спрашивал про вот этот момент:
> а они (европа) по кое каким выясненным в ходе причинам себе могут :D

Чё за причины то?

**Comment by ZVee** [comment]
Есть версия - что они из билда повыпиливали всякого разного, но я не знаю как на самом деле, одно что мне точно известно - запустив их локалку - цпу в простое 0-3, запустив ТГ - 10-22, запустив наш - 9-12. И ежели при онлайне у них картина тоже будет показывать такую разница - то очевидно, что на освободившийся кислород - им позволительно держать такую роскошь. Но такой низкий цпу в простое говорит только о том, что у них фоновые процессы ничем не заняты - возможно реализация иная, а может действительно там нечему процесситься..
