### ISSUE TITLE
А денег то нет

### ISSUE THREAD

**Issue by Thirteenalex** [TauCetiStation/TauCetiClassic#12210]
#### Подробное описание проблемы
Деньги не пришли на счет карго
#### Что должно было произойти
счет карго должен был обновится
#### Что произошло на самом деле
товар ушел деньги не пришли
#### Как повторить
отправить что-то на цк через карго
#### Дополнительная информация:
Issue reported from  Round ID: 61196 (Tau Ceti Classic (RU))
Testmerges: ```#11994# 12116# 12182# 12186# 12191```
Reporting client version: 514.1589

**Comment by AirBlack** [comment]
такое было недавно и я думал то ли нас педали душат, то ли ИИ сбойный решил затролить экипаж и удалить все счета. По отчету с ГПшной консоли счетов видно было как будто все аккаунты отделов удалили, остался только акк ЦК. Собственно счет карго тоже удалился из-за чего не приходил бабос. Я бы поставил тэг критично т.к. если это реально баг, он целый отдел приводит в непригодность.

**Comment by Oz1Es** [comment]
аирблек прав такое не впервые и педали в шоке и не знают что это такое

**Comment by QWxiZ** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/11065
