### ISSUE TITLE
Священник не может эффективно бороться с культом

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1223]
#### Подробное описание проблемы
Во время режима "Культ" священник не может эффективно противостоять антагонистам
#### Что должно было произойти
Священник должен быть одной из центральных личностей данного режима. Возможно, невосприимчивость к большинству рун и способностей
#### Что произошло на самом деле
Решают ОБР или СБ, и дробовики. Культисты отвечают скрытыми конвертами и вызовами Нар-Си в конце раунда. Священника обычно станят и выкидывают в космос
#### Как повторить
Поиграть в режим
#### Дополнительная информация:
Куршан, плез

**Comment by dearprincesscelestia** [comment]
Но тогда священника будут болонировать и тыкать станпалкой, вся разница, нет?

**Comment by WallShrabnic** [comment]
В ответ можно задизармить жопой. А бладбойл никак не задизармишь

**Comment by dearprincesscelestia** [comment]
Ну не знаю, сколько не помню культы с моим участием, толпу культистов не задизармишь, если там не лолкульт в духе "давайте конвертнем чеплейна)))0 чет не выходит((9((". А пока толпы культистов нет, у священника ер-пе причин рулить режимом как бы тоже и нет - у экипажа нет оснований верить в его вопли, если не считать всяких "вы обвиняетесь в культизме за подозрительную книжку" и "я в книжке читал что на космической станции грин как-то не послушали священника и не выжил никто".

**Comment by Kurshan** [comment]
Никто не знает о фичах священника прост, их не очень много, (а может они уже и не работают, хотя должны), но там есть, и я не только про обращение в исконно-правильную веру.

**Comment by WallShrabnic** [comment]
Здесь я к тому, что в большинстве культораундов священника станят и выкидывают через драйвер в церкви. 

Алсо, годный священник может падебить даже стелсокульт

**Comment by dearprincesscelestia** [comment]
А если культомагия не будет работать на него,  почему его должны перестать станить и выкидывать через драйвер?

**Comment by dearprincesscelestia** [comment]
А-а!

**Comment by Avatar4** [comment]
Верните священнику периодическую подслушку мертвых.

**Comment by WallShrabnic** [comment]
Я думаю что можно закрыть, священника апнули
