### ISSUE TITLE
[Proposal] Убрать выпадение импостера когда отключены префы

### ISSUE THREAD

**Issue by Leprekeoner** [TauCetiStation/TauCetiClassic#12252]
#### Подробное описание проблемы
Мне упал импостер когда у меня был отключен преф на него
#### Что должно было произойти
Не должен падать
#### Что произошло на самом деле
Упал

**Comment by Deahaka** [comment]
Нужно больше информации. Скриншоты, айди раунда, время, вид префов в сетапе персонажа.

**Comment by Deahaka** [comment]
А хотя я уже кажется нашёл где это могло произойти, после апдейта на сервере починится

**Comment by Leprekeoner** [comment]
Раунд 61306. Играл за СБ, убрал в начале раунда преф на импостера через кнопку Toggle SpecialRole Candidacy, через несколько минут все равно упал импостер.

**Comment by Mercurialaste** [comment]
А ты изменения сохранил?

**Comment by Leprekeoner** [comment]
Не сохранял, я когда раунд уже начался отключил.
