### ISSUE TITLE
[Task] удалить возможность просчитывать координаты в теленауке

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#12258]
#### Подробное описание проблемы
Из-за необходимости каких-то вычурных схем для путешествия по точным координатам появляется всё больше пользователей, которые используют стороннее обеспечение для игры в теленауку, что нарушает правила сервера.
#### Что должно было произойти
1. Теленаука упрощена до такого состояния чтобы ничего кроме выбора желаемых координат и нажатия кнопки открытия портала не надо было делать.
2. Убрать возможность телепортироваться по точным координатам через калибровки и всякие калькуляторы данных GPS маячков. Пусть портал будет открываться всегда в рандомной точке вокруг места назначения указанного параметрами в консоли.
#### Что произошло на самом деле
https://forum.taucetistation.org/t/gajd-po-telenauke-dlya-prodvinutyh/40984
и куча каких-то калькуляторов от того же человека и ещё 3-х других. Желание даркволтера накодить похищение каких-то данных пользователя ради полной хуйни такой как убрать смещение на 2 тайла при телепорте
#### Как повторить
Открыть глаза, ничего не делать с проблемой.

**Comment by Polotos** [comment]
Из за таких как ты и удалили сложные интегралки на тг которые делали приколы

**Comment by Deahaka** [comment]
Щас сделаем чтобы кто-то пофиксил в приоритете

**Comment by Kiromaka** [comment]
Бедный дарквотер

**Comment by LudwigVonChesterfield** [comment]
#10763 

> Я посвятил один раунд на то чтобы попрыгать в телесало и к концу раунда без использований калькуляторов и формул смог открывать порталы примерно туда, куда и хотел. И я не вижу где тут нужны формулы или калькуляторы, о которых плееры из рнд и ещё мейнтейнеры постоянно ведут обсуждения. Может оставляем телесало и заставляем удалить все калькуляторы под угрозой бана чтобы решить "проблему теленауки"?

:raised_eyebrow:

**Comment by Deahaka** [comment]
> 🤨

Идея забанить всех негодяев не была реализована админами, я согласен на удар по загадочности моей теленауки ради спасения себя от кражи данных.

**Comment by Deahaka** [comment]
Upd. Людук в дискорде убедил что даркрвота не закодил ничего что пообещал и что пока это лишь очередная охранительная идея. Проснусь когда всё загорится
