### ISSUE TITLE
Апгрейд генетики ломает клонирование людей (блюспейс/Т4 детали).

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1226]
#### Подробное описание проблемы
Апгрейд генетики блюспейс частями клонирует человека настолько быстро - что он умирает. 
#### Что должно было произойти
Генетика должна клонировать человека так, что бы у него не было бешенного ген урона и он доживал до крио.
#### Что произошло на самом деле
Не успел человек клонироваться - как он сдох.
#### Как повторить
Полностью апгрейднуть оборудование в генетике и попытаться клонировать чувака.
#### Дополнительная информация:
Я 6 или 7 раз клонировал одного и того же человека. После того как сделали обратно старые части - он продолжал быстро клонироваться. Реанимировать его было невозможно. Даже когда удалили старые машины и заспавнили новые. Однако остальные клонировались нормально.

**Comment by Olt1771** [comment]
Я полагаю что кое кто прописывал команду на суицид при клонировании(когда ты клонируешься ты же в крите)

**Comment by WallShrabnic** [comment]
Так можно?

**Comment by dearprincesscelestia** [comment]
Да, succumb.

**Comment by SpaiR** [comment]
>Я 6 или 7 раз клонировал **одного и того же человека**

> Однако **остальные** клонировались нормально.

так какой вердикт?

**Comment by Avatar4** [comment]
Суть в том, что после даун-грейда хуман которого я пытался клонировать все еще был сломан а остальные начали клонироваться по старому

**Comment by SpaiR** [comment]
А до даунгрейда другие как клонились?

**Comment by Avatar4** [comment]
Других на тот момент не было.
