### ISSUE TITLE
Сбегающая Тесла

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1227]
#### Подробное описание проблемы

Тесла сбегает на включённом двигателе при 0

#### Что должно было произойти

Тесла не должна сбегать при выставлении двигателя на 0

#### Что произошло на самом деле

Тесла сбежала

#### Как повторить

Запустить теслу на 4 эммитерах и поставить двигло включённым на 0

#### Дополнительная информация:

Видать из-за нового контролера

**Comment by WallShrabnic** [comment]
Как уже было замечено, теперь для нормальной работы в нулевом режиме надо ставить 8 емиттеров

**Comment by Raschert0** [comment]
Как уже было замечено, это уже пофикшено (наверное)

**Comment by SpaiR** [comment]
При закрытии не написал, но вот.

>теперь, если всё сделать как сказано на вики, то поле будет стабильно удерживать теслу с 5 шарами. для того, чтобы получить лучший результат нужно или генератор контролировать, или эмиттеры добавлять, или ещё что-нибудь
