### ISSUE TITLE
Радиация поломалась.

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#12287]
#### Подробное описание проблемы
Чет поломало радиацию. Она жарит там, где не должна. Жарит то, чего жарить не может. Некоторые риги, а практически все пробиваются радиацией. Инженеры настраивающие двигло жарятся в космосе. Люди в ригах на обшивке жарятся радиацией. Все жарятся радиацией.
#### Что должно было произойти
Радиация работает нормально
#### Что произошло на самом деле
#61387
#### Как повторить
Играть в игру
#### Дополнительная информация:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/57403011/11472f0e-b157-48f8-9a47-1f836c4a2214)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/57403011/697fca66-49ee-4cdb-a71c-f214b65a8573)

**Comment by pro100kotah** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/12286

**Comment by Slavik2001** [comment]
Было только в этом раунде. Как мне сказали педали то выпал твой аспект на ВЕЛИКИЙ радиационный фон. Ну а за куклу я отыгрывал что не знаю почему, просто пробивает.

**Comment by simb11** [comment]
фича #12228

**Comment by pro100kotah** [comment]
Хуича. Она жарит везде за тайлами станции. Даже если там комнатку построишь.

**Comment by Kiromaka** [comment]
> Хуича. Она жарит везде за тайлами станции. Даже если там комнатку построишь.

в этом и фича

**Comment by pro100kotah** [comment]
> > Хуича. Она жарит везде за тайлами станции. Даже если там комнатку построишь.
> 
> в этом и фича

Хуича. Которая логикой никак не объясняется. То есть ровно такая же конструкция в слое станции радиацией не пробивается, но стоит ей выйти чуть на тайл за эту мнимую зону, которая указана в коде - все, пизда.

Вместо того, чтобы сделать нормальный код с проверками, а не хуйню завязанную на слоях - получаем запупу, которая не позволяет тебе нормально перемещаться. Сделать говно и называть фичей - не есть гуд. Можно же переделать нормально эту ""фичу"", которая будет жарить только в тайлах открытого космоса. Либо просто значения увеличить, которые уже привязаны к механу радейки на открытых тайлах.

Что за хуйню сделали по итогу.

**Comment by Kiromaka** [comment]
> > > Хуича. Она жарит везде за тайлами станции. Даже если там комнатку построишь.
> > 
> > 
> > в этом и фича
> 
> Хуича. Которая логикой никак не объясняется. То есть ровно такая же конструкция в слое станции радиацией не пробивается, но стоит ей выйти чуть на тайл за эту мнимую зону, которая указана в коде - все, пизда.
> 
> Вместо того, чтобы сделать нормальный код с проверками, а не хуйню завязанную на слоях - получаем запупу, которая не позволяет тебе нормально перемещаться. Сделать говно и называть фичей - не есть гуд. Можно же переделать нормально эту ""фичу"", которая будет жарить только в тайлах открытого космоса. Либо просто значения увеличить, которые уже привязаны к механу радейки на открытых тайлах.
> 
> Что за хуйню сделали по итогу.

Условности, станция расчитана на космический радиационный фон и защищена свинцом. А твой космический высер из 4 стенок - сделан и метала, пойду ка я прыгну в прыгну в реактор
![фвыфвыф](https://github.com/TauCetiStation/TauCetiClassic/assets/74469991/de970e03-99ea-48cc-845c-94b4cceddd13)

**Comment by Kiromaka** [comment]
починил кста
