### ISSUE TITLE
[Task] Повороты Firedoor-ов

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#12290]
После последнего обновления спрайтов дверей, у разных поддоров и фаердорах появились направления. На карте их по большей части докрутили в https://github.com/TauCetiStation/TauCetiClassic/pull/12079, кроме фаердоров. 

Нужно пройтись по всем ``/obj/machinery/door/firedoor`` и повернуть на восток (Dir = 4) те, которые требуются (можно смотреть по направлению стен/окон). 

Кроме того, нужны небольшие адаптации - надо избавиться от угловых окон в спейсе, например на мостике бокса. Иначе фаердоры там не развернуть красиво.

Пример:
![Tau Ceti Station 2023-10-20 094140](https://github.com/TauCetiStation/TauCetiClassic/assets/4064061/5ac26a04-af8e-444b-a77b-4e85e44a0b53)

Для мапперов, чтоб облегчить работу и не заниматься пиксельхантингом, можно открыть ``code/game/machinery/doors/firedoor.dm`` и внести следующие временные изменения:
```
	icon_state = "door_closed"
	layer = 50
```
Так все спрятанные фаердоры будут сразу винды в мапредакторе. После поворотов можно вернуть обратно.

Прогресс:
  - [ ] Бокс
  - [ ] Дельта
  - [ ] Фалькон
  - [x] Гамма #12183
  - [ ] Прометей
  - [ ] Стройка

**Comment by KatoMarika** [comment]
[Task] забыт в названии.
