### ISSUE TITLE
Лечение мага не работает

### ISSUE THREAD

**Issue by muWander** [TauCetiStation/TauCetiClassic#12305]
#### Подробное описание проблемы
Заклинание должно использоваться при атаке предметом-заклинанием, этого не происходит
#### Что произошло на самом деле
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/39914744/3ffb6452-3259-4109-a5bf-2616ddc1f1b1)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/39914744/061d18c2-42cf-4c5e-a125-f4d27ccb2910)
на других тоже не работает
#### Дополнительная информация:
это уже примерно неделю

**Comment by muWander** [comment]
> там какой-то супер баг нельзя только вплотную лечить зато на любой дистанции - можно

а как себя лечить на дистанции?

**Comment by KIBORG04** [comment]
А на каком интенте?

**Comment by Tobyyyan** [comment]
> А на каком интенте?

На любом
