### ISSUE TITLE
Дисплеи карго не показывают время прибытия каргошаттла

### ISSUE THREAD

**Issue by raduser** [TauCetiStation/TauCetiClassic#1231]
#### Подробное описание проблемы
Дисплеи карго не показывают время прибытия каргошаттла, они вообще вроде ничего не показывают.
#### Что должно было произойти
Дисплеи карго должны показывать время прибытия шаттла карго.
#### Что произошло на самом деле
Дисплеи карго ничего не показали.
#### Как повторить
Вызвать шаттл карго к станции и посмотреть на дисплеи.

**Comment by Raschert0** [comment]
http://prntscr.com/eisn5j
http://prntscr.com/eisnf3

**Comment by raduser** [comment]
Странно, у меня не работали в раунде.

**Comment by raduser** [comment]
Возможно рандомный баг.
