### ISSUE TITLE
неправильный свет у flare

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#12312]
#### Подробное описание проблемы
огонь у активированного flare имеет белый цвет, а не красный
#### Что должно было произойти
горит красным светом
#### Что произошло на самом деле
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/84613249/e56b976d-5116-4478-829c-e00376eecef5)

#### Как повторить
активировать флейр на сервере тау сети
#### Дополнительная информация:
Issue reported from  Round ID: 61453 (Tau Ceti Classic (RU))
Testmerges: ```#11926# 12198# 12200# 12228```
Reporting client version: 514.1589

**Comment by Kiromaka** [comment]
Фальшфейер может гореть и белым , дым отдельная хим реакция не влияющея на цвет фаера. Короче хоть это баг, фиксить не обязательно, скажем что фича.
https://ru.wikipedia.org/wiki/Фальшфейер
