### ISSUE TITLE
Двигатель на шаттле-дереликте развернуло

### ISSUE THREAD

**Issue by Slavik2001** [TauCetiStation/TauCetiClassic#12314]
#### Подробное описание проблемы
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/123300305/b3c63cbe-cfc5-4192-9a5c-b29e0f97ac43)

#### Что должно было произойти
2 двигателя направленных в 1 сторону
#### Что произошло на самом деле
1 двигатель направлен в нужную сторону, второй... Фиг знает куда
#### Как повторить
Найти дереликт с шаттлом быстрой доставки еды
#### Дополнительная информация:
Если не баг, а фича, то окей(типо двигатель вышел из строя и его развернуло так что шаттл разбился)
Issue reported from  Round ID: 61455 (Tau Ceti Classic (RU))
Testmerges: ```#11926# 12198# 12200# 12228```
Reporting client version: 514.1589

**Comment by AndroBetel** [comment]
фича, посмотри его описание

**Comment by Slavik2001** [comment]
Мне просто показалось что у него не был развернут, да и он сам довольно целый не считая носовой части
