### ISSUE TITLE
Неправильное название станции в описании портрета

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#12313]
#### Подробное описание проблемы
В описании портера главы всегда пишется что персонаж является капитаном/главой персонала/главой охраны станции Исход
#### Что должно было произойти
Портрет Ivan Ivanow, главы станции [Русское название станции].
#### Что произошло на самом деле
Портрет Ivan Ivanow, главы станции Исход.
#### Как повторить
осмотреть portrait
#### Дополнительная информация:
Issue reported from  Round ID: 61455 (Tau Ceti Classic (RU))
Testmerges: ```#11926# 12198# 12200# 12228```
Reporting client version: 514.1589

**Comment by QWxiZX** [comment]
Удалите другие карты и все
