### ISSUE TITLE
Объявление о блобе происходит раньше, чем появится блоб

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#12322]
#### Подробное описание проблемы
Объявление  о пятом уровне биоугрозы появляется раньше, чем лопается блоб. (Раундстартовый блоб)
#### Что должно было произойти
Объявление должно происходить когда появляется блоб.

**Comment by Deahaka** [comment]
Специально так закодили

**Comment by Mercurialaste** [comment]
Зря не прилагаешь раунд к ишшую. 
И это не баг, просто время перехода от стадии к стадии у мыши выпало максимальным, из-за чего анонс сработал раньше чем блоб вылупился. 
Обычно хотя бы одной мыши везет и она блобируется раньше анонса.

В том же случае, получилось что блобу нужно было 16.5~ минут на то, чтобы вылупится.

**Comment by pro100kotah** [comment]
В режиме блобов один может вылупиться раньше другого. Из-за чего для первого это вылупление раньше анонса, а для второго после.

**Comment by Kiromaka** [comment]
требуется "not a bug"
