### ISSUE TITLE
Свет мешает жить

### ISSUE THREAD

**Issue by DarkFurrSss** [TauCetiStation/TauCetiClassic#12325]
#### Подробное описание проблемы
Эта фигулинка не дает закрывать шкафчики
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/92409383/4409084b-618a-4c59-8846-5b1c838fdcd2)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/92409383/a089e5d0-1f91-40ac-82cf-bfc60f13ecda)

#### Что должно было произойти
Свет не имеет физических параметров как предмет
#### Что произошло на самом деле
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/92409383/f24a103a-0862-4460-8d65-09b1dd6134d5)

#### Как повторить
Закрыть шкаф под лампой
#### Дополнительная информация:
да
Issue reported from  Round ID: 61483 (Tau Ceti Classic (RU))
Testmerges: ```#11926# 12198# 12200# 12228```
Reporting client version: 515.1619

**Comment by DarthSidiousPalpatine** [comment]
Эм нет.

**Comment by DarkFurrSss** [comment]
Эм, да

> Эм нет.

**Comment by DarkFurrSss** [comment]
Проверь в атмосе гаммы, мб и другая невидимая штука мешала шкафчику с униформой закрыться

**Comment by DarthSidiousPalpatine** [comment]
Я уже лечу к тебе гостом, стой на месте.

**Comment by DarthSidiousPalpatine** [comment]
Ишуй закрыть надо, кринж и всё работает.
