### ISSUE TITLE
Оверлей холодильника исчезает, если открутить его панель

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#12354]
#### Подробное описание проблемы
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/90282587/fd782497-177c-456a-901f-3d4e220d4722)

#### Что должно было произойти
Оверлей не исчезает.
#### Что произошло на самом деле
Исчез.
#### Как повторить
Использовать отвертку на холодильник.
#### Дополнительная информация:
Issue reported from  Round ID: 61520 (Tau Ceti Classic (RU))
Testmerges: ```#12198# 12228# 12304```
Reporting client version: 514.1589

**Comment by Pirsnya** [comment]
фича

**Comment by Deahaka** [comment]
Ты сам это и добавил))))
