### ISSUE TITLE
Легальный ВХ или же стеклянные fire doors

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#12356]
#### Подробное описание проблемы
@volas , отзыв по ПРу  #12291
На шлюзах где нет стекл, после использования стеклянных fire doors, через этот шлюз видно с обоих сторон. 
#### Что должно было произойти
1. Стеклянного fire doors, не должно было быть на шлюзе где нет стекла
2. Даже если аварийный шлюз стеклянный, то из-за того что обычный шлюз без стекла, через него не должно, что либо быть видно.

#### Что произошло на самом деле
Легальный ВХ, правда в котором ты видишь других, как и другие видят тебя
![IMG_20231028_140009_324](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/37d28ee5-94b8-4e0f-ade2-31451e965211)

#### Как повторить
Выше указано как

#### Дополнительная информация:
На втором сервере нашли это, Box Station - техи по западной стороне ЕВЫ (где ещё рядом мостик и бар)

**Comment by DarthSidiousPalpatine** [comment]
А ещё в каморке бармена.

**Comment by KatoMarika** [comment]
Наблюдается еще интересность, пока на локалке смотрел гирлянды. 

1. Изначальный вид не трогая дверь. 

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/18484142/831dd695-aa9a-4c99-b49d-ea3c8e61cdd3)

2.  После того как открыл и закрыл дверь. 

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/18484142/0083920e-7628-4f67-a6a4-22755bb2438a)
