### ISSUE TITLE
Инжекторы генетиков можно использовать бесконечное количество раз

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1236]
#### Подробное описание проблемы

Можно использовать инжектор monkey>human бесконечно

#### Что должно было произойти

Один раз юзнул, шприц пропал

#### Что произошло на самом деле

При использовании шприц не пропадаем и можно использовать сколько угодно раз

#### Как повторить

Взять инжектор с СЕ из макаки в человека и при использовании на макаку, сразу же прятать куда либо в слоты или кинуть/выкинуть

#### Дополнительная информация:

Почитать про составление багрепортов

**Comment by SpaiR** [comment]
Ночью и не такое можно делать.

**Comment by ZVee** [comment]
Более чем уверен, что это и была та самая непонятная причина рантайма на инжекторы. Код не смотрел, но наверно удаление предмета стоит не на сам предмет, а на руку - но не знаю, лишь предположение.
