### ISSUE TITLE
Зомби сломаны.

### ISSUE THREAD

**Issue by maleyvich** [TauCetiStation/TauCetiClassic#12375]
#### Подробное описание проблемы
Щитспавн в виде зомбей ВООБЩЕ не работает. Регенерации у трупов нет, роли зараженных не выдаются, первые зараженные становятся слепыми перед первым превращением
#### Что должно было произойти
Зомби регенирируют после смерти, щитспавн работает стабильно
#### Что произошло на самом деле
всё плохо
#### Как повторить
защитспавнить зомби
#### Дополнительная информация:
 #61567 - Round ID

**Comment by Deahaka** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/12300

**Comment by Deahaka** [comment]
Новые подробности. Походу это работает только если ты умираешь по воле вируса, а не по какой-либо иной причине.

**Comment by maleyvich** [comment]
неактуально
