### ISSUE TITLE
выключатель света офиса криминалиста вмонтирован в одну стену с АПЦ

### ISSUE THREAD

**Issue by hwat1204** [TauCetiStation/TauCetiClassic#12378]
#### Подробное описание проблемы

В офисе криминалиста выключатель света находится на одном тайле стены с АПЦ из-за чего использовать его возможно лишь через Alt Клик

#### Что должно было произойти

Выключатель весит рядом и можно включать и выключать свет

#### Что произошло на самом деле

Джамшут вмонтировал выключатель в электрощиток , насяльника

#### Как повторить

зайти за криминалиста

#### Дополнительная информация:

справа и сверху от АПЦ голая стена, выключатель можно перенести на неё рядом со шкафом с вещами.

**Comment by Kiromaka** [comment]
На какой карте ?

**Comment by volas** [comment]
бокс
