### ISSUE TITLE
Абзу таргет спеллов всех ролей(не ролей)

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1238]
#### Подробное описание проблемы

Можно юзать абилку овер 1000 раз на несколько персонажей

#### Что должно было произойти

1 таргет за кд

#### Что произошло на самом деле

Юзнуть абилку на всех в полезрения 100000000000раз

#### Как повторить

Берём перса с таргет спелом/абилкой, например вокса. Создаём миллион кукол рядом с собой, без остановки зажимаем кнопку на спелл 1000000000 окон с спелом и таргетами в нём, станим кнокаем, оглушаем, трэлим ит.д.

**Comment by Kurshan** [comment]
Не смог повторить, либо я идиот, либо описание не то, либо баг уже пофикшен.

**Comment by Dennok** [comment]
Да, такое много где было. Например с вендоматом и картой шахтеров, можно было понаоткрывать тучу окошек, и завалить станцию скафандрами. но это пофиксили.
Вообще спеллы через меню выбора это не очень.

**Comment by Kurshan** [comment]
Касается только липа воксов, который уже пофиксил при возвращении воксоты.
