### ISSUE TITLE
Абуз телепорта из мехов через небо и аллаха

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1239]
#### Подробное описание проблемы

Можно делать ТП аут откуда угодно если если залез с меха с каталки

#### Что должно было произойти

Вылез с меха без ТП

#### Что произошло на самом деле

Телепортнулся в любую точку где была твоя каталка ескейпнувшись от опасности

#### Как повторить

Строится 2 меха, на 1 ставим гравипульту. На второй залазим с каталки, убегаем мехом(примечание нельзя двигать каталку любыми методами) кроме как выстрелом из гравипульты в режиме отталкивания, как только каталка отталкнётся вы вернётесь в креслокаталку.

**Comment by Kurshan** [comment]
Не смог повторить, либо я идиот, либо описание не то, либо баг уже пофикшен.

**Comment by Dennok** [comment]
Хм, интересный баг. Вроде уже писали про залезания в мехов буклед мобов.

**Comment by SpaiR** [comment]
#1015

**Comment by SpaiR** [comment]
@Olt1771 чёж ты не зарепортил баги, которые ты абзузил два или три года назад? всем ведь так интересно искать проблему, которую уже давно исправили
