### ISSUE TITLE
Стафф оф аниматион и тандердом

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1240]
#### Подробное описание проблемы

Стафф оф аниматион может оживлять голомечи с полным уроном

#### Что должно было произойти

Оживил мечи, они наносят голоурон

#### Что произошло на самом деле

Мечи порубили в капусту всех зашедших в их поле зрения 

#### Как повторить

Активировать за мага тандердом, на голодеке включить все энерго-голо-мечи, оживить, наслаждаться мясорубкой

**Comment by Avatar4** [comment]
Добавлю так же что оживление всяких крошечных предметов тоже имба. Как если оживить окурки и все такое.

**Comment by Dennok** [comment]
Уххххх!!! Фичииии.
