### ISSUE TITLE
хоткей E (английская) плохо работает

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#12400]
#### Что должно было произойти
стандартный хоткей e (английская) или у (русская) кладёт предмет в рюкзак.
#### Что произошло на самом деле
стандартный хоткей E (английская) или у (русская) кладёт предмет в другую руку, а не в рюкзак.

### Шаги воспроизведения

Я просто взял предмет в руку и попытался положить его в рюкзак (то есть, когда все слоты карманов, одежды заполнены и инвентарь рюкзака открыт) с помощью хоткея

### Дополнительная информация:

Issue reported from  Round ID: 61629 (Tau Ceti Classic (RU))
Testmerges: ```#12310# 12381# 12383# 12386```
Reporting client version: 514.1589

**Comment by KIBORG04** [comment]
Вот оно где вылезло.. щас ревертну
