### ISSUE TITLE
Потеря робоконечности и её восстановление

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1241]
#### Подробное описание проблемы

Если ты потерял кисть/стопу робоконечности то можно отрубить оставшуюся часть голеностоп/предплечье и выпадет целая роборука

#### Что должно было произойти

Выпало голеностоп/предплечье роботизированное

#### Что произошло на самом деле

Выпала целая робоконечнсть

#### Как повторить

Потерять робо-кисть/стопу, положить пациента на каталку/стол/операционный стол и отрубить оставшуюся часть конечности

**Comment by KuzyXD** [comment]
Нужен фидбек из-за #3726

**Comment by Alexofp** [comment]
Разделения на кисть/плечо уже давно нет, сейчас всё точно выпадает корректно
