### ISSUE TITLE
Админопроблемы с банами

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#12410]
#### Что должно было произойти
При выдаче бана через PP человека банит и кикает
#### Что произошло на самом деле
При выдаче бана через РР человека банит, но не кикает (с недавних пор)

### Дополнительная информация:

Issue reported from  Round ID: 61674 (Tau Ceti Classic (RU))
Testmerges: ```#12310# 12381# 12383# 12386```
Reporting client version: 515.1619

**Comment by Pirsnya** [comment]
могу предположить что связано с https://github.com/TauCetiStation/TauCetiClassic/commit/2e17119f7741516ae04d2f1a6e9764644ac61c97#diff-4857dcdfe9b01e80714fe69b52e75de2e457e213a7d747b983bdfa8b0e872ce8

**Comment by volas** [comment]
Проблема была в анонсере банов на родственные сервера, который делал Export(), который сломался в одной из предыдущих версий бьенда. Я проморгал этот момент и как-то из-за других известных проблем мы отложили обновление сервера, и случился нештатный залип прока бана, не доходящего до кика клиента.

Пока отключу анонсеры, при первой возможности обновлю сервера.
