### ISSUE TITLE
Блюспейскресталлы и 2 слой(слой ролей ЦК и т.д.)

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1242]
#### Подробное описание проблемы

Можно абузя Блюспейскресталлы пробраться на нюкобазу/пирато-базу своровать ДаркГикаса у ЦК и т.д. всё что находится на ЦК

#### Что должно было произойти

The BluespaceCristal blowup in your arm.

#### Что произошло на самом деле

Напал на нюкеров до их вылета. Украл ДаркГикаса и всю эквипу ЕРт, своровал корову пиратов

#### Как повторить

Используя блюспэйс кристаллы на велосити удачно телепортироваться за её пределы и лететь на базы ролей с тулбелтом

**Comment by Dennok** [comment]
Уххххххх!!!!!!! ФИчи изза тебя выпиливают!!!!
