### ISSUE TITLE
Тенелинго проблема

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1243]
#### Подробное описание проблемы

Есть 1 бесполезная способность, т.к. армор у линга не ломается и не имеет какого либо армора, восстановить хитин

#### Что должно было произойти

При восстановлении хитина, починится армор, после чего армор имеет повышенную защиту от пуль лазуров и ещё чего либо.

#### Что произошло на самом деле

Армора на тенелинге нет и в связи с этим нет никакого толку от абилки

#### Как повторить

Всё выше указанное с антагонистом Shadowling

#### Дополнительная информация:

Я там репортил баг о тенелинге с костями прицепите к нему

**Comment by Dennok** [comment]
У него эта абила для регена вещей после клонирования.

**Comment by WallShrabnic** [comment]
Вот только после клонирования тенелинг все абилки теряет
