### ISSUE TITLE
проблемы крови и её совместимости

### ISSUE THREAD

**Issue by NinjaPikachuska** [TauCetiStation/TauCetiClassic#12442]
#### Что должно было произойти
группа крови должна выглядеть вот так вот
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/89906909/a1b02537-27e3-4a5e-8bd4-7d0f47509127)
совместимость крови работает

#### Что произошло на самом деле
группа крови выглядит вот так вот
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/89906909/377bae74-5046-40a7-b640-6ef877689ac0)
совместимость работает через жопу

### Шаги воспроизведения

- зайти за сохраненную куклу со старой кровью
- попробовать залить себе новую кровь из вендомата

### Дополнительная информация:

совместимость дружит только со старой кровью которая сохранилась в префах игроках
https://github.com/TauCetiStation/TauCetiClassic/blob/0a6812dd46be650e3e17eff37a530e6f17c2f2ab/code/modules/organs/blood.dm#L468-L488

если кто-то возьмется - не забудьте еще из сохранений поубирать старую/новую кровь

**Comment by pro100kotah** [comment]
Почините кровь, бля. Там любая группа токсинов накидывает.
