### ISSUE TITLE
Один риг, сотня космонавтов в нём

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1244]
#### Подробное описание проблемы

Один риг, может надеть сотня космонавтов

#### Что должно было произойти

Один риг, один космонавт 

#### Что произошло на самом деле

Сколько космонавтов успело, столько и одело

#### Как повторить

В течении 10 секунд одевания рига, его можно передавать и остальным космонавтам пока тот надеётся. В итоге сколько космонавтов успели его передать столько и одели, эдакий дюп рига

**Comment by Smalltasty** [comment]
А если их снимать, то они будут плодиться? А если в космос выйти, они будут считаться как риги и защищать? И даже включать магбутсы/шлем можно? Или это чисто визуально?

**Comment by Olt1771** [comment]
Всё работает как риг, но остаётся 1 риг, при снятии всеми космонавтами

**Comment by Avatar4** [comment]
Оставьте, прошу. Фича же!

**Comment by RichardJones1** [comment]
Думаю да
