### ISSUE TITLE
Проблема сифора

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1245]
#### Подробное описание проблемы

Сифор не наносит урон сразу же после взрыва если он на космонавте

#### Что должно было произойти

Взрыв>мгновенный гиб/урон

#### Что произошло на самом деле

Сифор рванул когда космонавт в бомбсъюте/риге космонавт не получил урон 

#### Как повторить

Одеть риг/бомб съют, находиться в большом корридоре/космосе и до столкновения с объектом вы не получите урона. То есть в космосе если будет дико везти, ты будешь на сверхзвуковой скорости летать по слоям и жить, до первого объекта

**Comment by ZVee** [comment]
Ну вообще, у ригов и особенно бомб съюта (иммун) есть параметр защиты от взрывов, так что то, что сифор не убивает в ригах и тем более съюте - норма.
А лепить сифор на тушку которая может бегать - не очень, тем более если введем снятие сифора при свободных руках.

Единственное - можно наверно успеть за 10 секунд нацепить бобм съют/риг и не гибнуться с сифора - но это в каком-то смысле фича, хотя от нее бы избавиться.

**Comment by Olt1771** [comment]
Зве там то бомбсьют не 100% защиты имеет ты как минимум теряешь одну конечность, как максимум гиб, даже если ты в бомб сьюте. Всё зависит от прока на конечность

**Comment by ZVee** [comment]
>bomb = 100

Вот это означает иммун, если его нет - баг.

**Comment by Dennok** [comment]
А бомбсют покрывает все тело?

**Comment by ZVee** [comment]
>А бомбсют покрывает все тело?

Вот кстати возможно в этом и дело, но где он защиту дает - там иммун.

**Comment by Lancer411** [comment]
Ладони и ступни не закрывает.
