### ISSUE TITLE
БлюспейсБагОфХодинг и 1 строчка инвентаря

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1246]
#### Подробное описание проблемы

Всего 1 слой вещей в бесконечной сумке оф холдинг

#### Что должно было произойти

Иметься несколько слоёв как в мусорном мешочке оф холдинг

#### Что произошло на самом деле

Одна строка, от которой по большей части нет смысла, да и ещё дебафф на телепорты

#### Как повторить

Надеть блюспэйс баг оф холдинг, положить семь вещей. Зайти на ТГ/ВГ билд и начать рыдать

**Comment by Shudyn** [comment]
Смысл, когда можно положить в него семь сумок, в семь сумок положить по семь коробок. В итоге, считаем количество слотов. 7х7х7=343. 343 слота, Карл. И вам мало?

**Comment by Olt1771** [comment]
Была бы система Тг что можно брать вещи из хранилищ в рюкзаке, то ок. А то ужасно много гемороя, да и по сути слишком большой дебафф в соотношении с тем что даёт сумка

**Comment by WallShrabnic** [comment]
Положить в Баг оф холдинг другой Баг оф холдинг peka
