### ISSUE TITLE
У геноедов иконки сломались

### ISSUE THREAD

**Issue by Oz1Es** [TauCetiStation/TauCetiClassic#12464]
#### Что должно было произойти

иконки есть, не надо искать нужную способку в вкладке changeling

#### Что произошло на самом деле

иконок нет, игорёк растроился что надо будет искать способность в вкладке changeling

### Шаги воспроизведения

1. (В моём случае ласт резорт) жмёшь ласт резорт, потом откладываешь яйца в трупе
2. Перерождаешься, очеловечиваешься, а иконок нема

### Дополнительная информация:

мне сказали сюда обратиться

**Comment by muWander** [comment]
алсо кнопки абилок-стингов не работают
