### ISSUE TITLE
Спавн менюшка поломана(снова)

### ISSUE THREAD

**Issue by Kiromaka** [TauCetiStation/TauCetiClassic#12468]
### Описание
Сломано спавн меню - пока я увидел только Агента прослушки
#### Что должно было произойти
Не это
#### Что произошло на самом деле
![фывфывфы](https://github.com/TauCetiStation/TauCetiClassic/assets/74469991/305b1860-861a-48bf-bc80-dd405771b0d1)

### Шаги воспроизведения

Покликать на "Появится" 432 раза

**Comment by volas** [comment]
агент то заспавнился?
