### ISSUE TITLE
[Proposal] No Headshot

### ISSUE THREAD

**Issue by Kiromaka** [TauCetiStation/TauCetiClassic#12477]
### Описание

Добавить антагам и существам - ( которые не могут носить броню) встроенный шлем, для защиты от oneshot еганом на "нелетале".

Ну или хоть как то пофиксить ваншот ШЛов. 

Lost in game, went on github

**Comment by arygal** [comment]
фича

**Comment by simb11** [comment]
еган не ваншотит, всего хорошего
