### ISSUE TITLE
[Proposal] Выплеснуть реагенты можно только на харм интенте.

### ISSUE THREAD

**Issue by ZER0-In** [TauCetiStation/TauCetiClassic#12490]
### Описание

  Не знаю, почему только у нас это сделано, но на любых других проектах выливание жидкости или реагента из бикера сделано только на харм интенте. Из-за чего пролить что-то случайно можно лишь изредка и по тупости.
  Раздражает даже не то, что ты случайно мисскликнул куда-то не туда и весь реагент вылился и теперь ты сидишь в зафороненной химии. А то, что пока ты суешь из диспенсера в раздатчик, иногда приходится пиксельхантить, сука, чтобы не пролить НА АВТОМАТ жидкость. Хотя поидее это вообще работать не должно, он любой бикер должен принимать сразу в себя. Думаю многие игроки на химиках с этим сталкивались, когда ты быстро варишь лекарства и при тыке НЕ закрытым бикером на раздатчик, бикер просто выплескивал реагент прямо на него, вместо того чтобы вставиться.

**Comment by Deahaka** [comment]
А давайте выпустить форон из канистры в отсек можно только на харм интенте?

=С

**Comment by Naroke** [comment]
Почему бы просто не закрывать бикер, если ничего из него не переливаешь?

**Comment by pro100kotah** [comment]
> Почему бы просто не закрывать бикер, если ничего из него не переливаешь?

Потому что это дрочево. Когда ты помещаешь бикер в раздатчик, бикер не должен проливаться на раздатчик. Это дебилизм.
