### ISSUE TITLE
Вещи, помещенные в Compressed Implant, не дают гринтекста.

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#1249]
#### Подробное описание проблемы
Хранилище триторского импланта не считается частью куклы.
#### Что должно было произойти
Хитрый тритор должен был получить гринтекст.
#### Что произошло на самом деле
Ролька зафэйлилась.
#### Как повторить
Быть тритором с заданием на кражу чего-либо, вколоть себе Compressed Implant и поместить в него украденную вещь. Улететь на шаттле.

**Comment by ZVee** [comment]
Там по моему фэйлы и не только из-за этого могут быть, однако эта тема очень спорная - компрессед имплант фактически дает 100% защиту от любого обыска и мне кажется это былоб слишком.

**Comment by DeadOberst** [comment]
Имплант могут спалить и вытащить врачи, так что все нормально.

**Comment by P-20** [comment]
Достаешь вещь за несколько секунд до прилета на ЦК. Гринтекст.

**Comment by Olt1771** [comment]
Ещё разгрузка, вот!111!!

**Comment by CryptoKisik** [comment]
Фича же.

**Comment by Dennok** [comment]
Таки бага. Еще не дает грин за вещи в халате.

**Comment by dred1792** [comment]
Тут проблема в проке `get_contents()`, который лежит в `code/modules/mob/living/living.dm`
@ZVee, ты вот мобов шатаешь, будешь это фиксить? Я как понял, суть в том, что вышеупомянутые предметы не входят в категорию storage, так как даже педальная команда check_contents (которая тоже на этом проке работает) не высвечивает эти предметы.

**Comment by ZVee** [comment]
Я не считаю это багом, т.к против стелсо-протаскивания чего либо на ЦК. У нас и так обысков на шаттлах не бывает почти, народ улетает в том что со станции взяли (планировал кстати ввести запрет входа на шаттл с вещами с ЦК поставив некую скан систему как это на бее с мехами было реализовано в свое время). Поэтому это хранилище вообще сомнительная фича, хотя, неплохой способ миновать обыски на самой станции или утянуть в крыло общего заключения мимо глаз что-нибудь.

Вот убедите меня в том что мои взгляды неверны - тогда сам даже исправлю.

**Comment by dred1792** [comment]
Предметы в халатах и разгрузках тоже гринтекста не дают, вот.

**Comment by ZVee** [comment]
Это погляжу, т.к там надо карманы слота "униформ" превратить в карманы, а не переменные как сейчас.

**Comment by P-20** [comment]
Тут забыли добавить что не засчитывает вещь в разгрузке,халате,если она находится в теле человека
