### ISSUE TITLE
Аугментация зрения у научных боргов.

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#125]
Originally reported by: **13 (Bitbucket: [shadence](http://bitbucket.org/shadence), GitHub: [shadence](http://github.com/shadence))**

---

Научный борг может стать ксеноархеологом, но ему не дали шахтерский сенсор. Как копать то, что не видит?

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/125

**Comment by Lancer411** [comment]
Возможно стоит расширить способности научных боргов, добавить им автопотрошитель слизней и шахтерский сканер. Все равно ксеноархеология это не та профессия, где замещение людей кому-то мешает.
