### ISSUE TITLE
В аплоаде нет АПЦ.

### ISSUE THREAD

**Issue by QWxiZ** [TauCetiStation/TauCetiClassic#12506]
#### Что должно было произойти
Аплоад логично работает на АПЦ.
#### Что произошло на самом деле
Бесконечная энергия изнеоткуда, абузь сколько хочешь.

### Шаги воспроизведения
зайди на бокс
открой глаза

**Comment by Kiromaka** [comment]
реально нету 👀

**Comment by Kiromaka** [comment]
а на дельте есть :dovolen:

**Comment by arygal** [comment]
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/73737464/f99d4225-4728-443b-89cd-3786cc0bb23e)
Тут было АПЦ. Тот кто ставил консоль для ламп его того...

**Comment by volas** [comment]
тогда наверно я сломал, но я не понимаю, каким образом оно тогда работает

**Comment by Fenriros** [comment]
Все думали что победили малфа, удалив режим... но оказывается, малф давно победил.
