### ISSUE TITLE
Культо ТП 

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1251]
#### Подробное описание проблемы

Руна телепорта у культистов с ужасно маленьким шансом может телепортировать на координаты 0, 0, 2(по идее на эти)

#### Что должно было произойти

Работать телепорт или же не смог сделать ТП

#### Что произошло на самом деле

Попал на координаты 0,0,2 застрял

#### Как повторить

Телепортироваться, но скорее всего не выйдет

**Comment by Kurshan** [comment]
>Телепортироваться, но скорее всего не выйдет
Da

**Comment by Olt1771** [comment]
Возможно что то повлияло, например тогда руны деды начали вытирать, мэйби ето

**Comment by Dennok** [comment]
Лол, даа... если кудельнуло руну и не сразу удалило могло к ней тпшнуть. Надо добавиь или проверку на куделед в тп или переделать тп.

**Comment by Kurshan** [comment]
#1670
