### ISSUE TITLE
Двойной сенсор удаляется

### ISSUE THREAD

**Issue by Slavik2001** [TauCetiStation/TauCetiClassic#12542]
#### Что должно было произойти
Отсоединить 2 сенсора и получить каждый на руку или на полу
#### Что произошло на самом деле
Делит 2 соединённых сенсоров

### Шаги воспроизведения

1. Взял первый сенсор
2. Взять второй сенсор
3. Тыкнуть первым по второму, чтобы их соединить
4. Тыкнуть по полученному детищу
5. Делит

### Дополнительная информация:

Issue reported from  Round ID: 61929 (Tau Ceti Classic (RU))
Testmerges: ```#12467# 12520# 12525```
Reporting client version: 514.1589

**Comment by pro100kotah** [comment]
Также и с другими деталями. Например мышеловку с игнайтером. При попытке взвести собранный инструмент без тыка по ней отверткой - игнайтер соединенный с мышеловкой просто делитается.
