### ISSUE TITLE
Спам проджектайла

### ISSUE THREAD

**Issue by Classical-User** [TauCetiStation/TauCetiClassic#12544]
#### Что должно было произойти
Ничего
#### Что произошло на самом деле
Спам машина проджектайла в звуках и логах

### Дополнительная информация:

Issue reported from  Round ID: 61930, 61931 (Tau Ceti Classic (RU))
Testmerges: ```#12467# 12520# 12525```
Reporting client version: 514.1589
![муха](https://github.com/TauCetiStation/TauCetiClassic/assets/114824435/19dc0377-68bb-439c-957a-9557a6e41cc5)

**Comment by kalazus** [comment]
Да, нужно убрать сообщение для тестового проджектайла
