### ISSUE TITLE
Клонирование СПУ

### ISSUE THREAD

**Issue by sovok4** [TauCetiStation/TauCetiClassic#1254]
#### Подробное описание проблемы
Мертвого СПУ можно клонировать в стандартной клономашине.
#### Что должно было произойти
Клономашина не должна клонировать робота.
#### Что произошло на самом деле
Клономашина клонирует робота.
#### Как повторить
Загрифонить СПУ. Клонировать.
#### Дополнительная информация:
Привязать бы к тем другим багам
https://github.com/TauCetiStation/TauCetiClassic/issues/1216

**Comment by Miracler112** [comment]
Попробую исправить это и сделать так, что СПУ можно будет вернуть с помощью операции по приделыванию всех её частей к телу (ну и куда без нанопасты) если таки осилю

**Comment by Kurshan** [comment]
Зве тут мобов решил глобально рефакторнуть, так что смысл?

**Comment by ZVee** [comment]
@Miracler112 - 
![da54fsdfsd3](https://cloud.githubusercontent.com/assets/8426718/24079729/a64d753c-0c97-11e7-8bd0-996b29ae0e92.png) - вот эта "штука" вовсе не статус некого личного дневника, а самое что ни на есть прямое обозначение того, что этот (ПР, репорт и тому подобное), закреплен за кем-то (может быть несколько людей). В таких случаях надо не "я попробую сделать", а "можно мне взяться?", дабы потом не вышел курьез.

Но отвечая на вопрос - в этот раз не передам. У меня там все равно пол билда будет вспахано и разрешу по ходу все то, что на мне сейчас висит (ну или большую часть).

(Остальным мэйнтейнерам - вы там не играйтесь с ассигнами, у них все таки конкретная цель (речь про нано, и на будущее).

(Остальным-остальным - можно просить тех у кого есть доступ прикреплять за вами те или иные репорты или отписываться в самом репорте - что вы беретесь за него. Надо для того, чтобы было видно всем на гите и несколько человек случайно не брались за одно и тоже. Только если просите такое - не пропадайте, и если не можете довести до конца - сообщайте об этом).
