### ISSUE TITLE
Баг возрождения животного

### ISSUE THREAD

**Issue by Slavik2001** [TauCetiStation/TauCetiClassic#12579]
#### Что должно было произойти
Возрожение животного с тем ХП которое у него было
#### Что произошло на самом деле
Возрождение симпл моба с увеличение его макс ХП и отхилом до фулла

### Шаги воспроизведения

Культ
Труп симпл моба(пример - ксеноморф из техов)
Возрождение животного
Обмен разумом
Убить моба с разумом игрока
Возрождение животного
Убить ещё раз 
Возрождение животного
Профит - 4к ХП у симпл моба, без боли, замедления и т.д.

### Дополнительная информация:

Issue reported from  Round ID: 62014 (Tau Ceti Classic (RU))
Testmerges: ```#12494```
Reporting client version: 514.1589

**Comment by Kiromaka** [comment]
Наверно, стоит возвращать старое хп при смерти моба, или просто вырезать говнофичу.
