### ISSUE TITLE
[Proposal] Balance? fix 2

### ISSUE THREAD

**Issue by Kiromaka** [TauCetiStation/TauCetiClassic#12578]
### Описание

Добавить чек на carbon или human ритуалу майндсвапа.

**Comment by KIBORG04** [comment]
Куда чек кому чек зачем чек???? Если не опишешь, я просто закрою.

**Comment by Kiromaka** [comment]
> Куда чек кому чек зачем чек???? Если не опишешь, я просто закрою.

Сейчас майндсвап культа позволяет вселится в любое существо, это not good. На примере совмещения майндсвапа и возрождения моба.
Стоит добавить проверку на принадлежность существа к carbon или human(хуйня), а то можно даже в собаку с ЦК вселится, хотя, если ты пофиксишь возрождение животного, то надобность отпадет, не учитывая ситуаций с уникальными модами типо собак, которые на станцию и не попадут.
