### ISSUE TITLE
Balance? Fix

### ISSUE THREAD

**Issue by Kiromaka** [TauCetiStation/TauCetiClassic#12577]
### Описание

Ритуал воскрешения животного увеличивает хп моба, это надо вырезать.

### Шаги воспроизведения

Примеры -
Ресаем несколько раз симпл моба
Делаем майндсвап
Вы бессмертны.

### Дополнительная информация:

Issue reported from  Round ID: 62014 (Tau Ceti Classic (RU))
Testmerges: ```#12494```
Reporting client version: 514.1589

**Comment by KIBORG04** [comment]
В пользу его https://github.com/TauCetiStation/TauCetiClassic/issues/12579
