### ISSUE TITLE
Кривоватый перевод местоимений Нар-си

### ISSUE THREAD

**Issue by hwat1204** [TauCetiStation/TauCetiClassic#12589]
#### Что должно было произойти

Служи ей!

#### Что произошло на самом деле

Служи Ему!

### Шаги воспроизведения

1: Произвести ритуал обращение

2: прочитать местоимение

3: оскорбиться.

### Дополнительная информация:

возможны и другие ошибки перевода связанный с Нар-си, но я думаю мы все согласны что лучше делать всё по канону ( ну и потому что r34 арты с Фем Нар-си должны стать каноном)

**Comment by KIBORG04** [comment]
Это не баг, если надо, то открывай пропосал. 

"Служи Ему" означает служить богу, а слово "бог" в мужском роде и не изменяется.
