### ISSUE TITLE
Ненаказуемый брейнрот AKA проблема с логированием сообщений в say от эссенций генокрада

### ISSUE THREAD

**Issue by Gort133** [TauCetiStation/TauCetiClassic#12586]
#### Что должно было произойти
Генокрад дает эссенции право говорить за нее
Эссенция говорит за генокрада и в логах пишется сикей эссенции 
Эссенция пишет что-то что нарушает правила и получает бан
#### Что произошло на самом деле
Генокрад дает эссенции право говорить за нее
Эссенция говорит за генокрада и в логах пишется сикей ГЕНОКРАДА(если точнее - того, у кого на данный момент право управлять куклой)
Эссенция пишет что-то что нарушает правила и фиг поймешь она ли это писала.

### Дополнительная информация:

Issue reported from  Round ID: 62038 (Tau Ceti Classic (RU))
Testmerges: ```#12494```
Reporting client version: 514.1589

**Comment by Kiromaka** [comment]
Эсенции вырезать надо, после трупа генки остаются трупы эсенций, еще баги + этот. От нее смысла ноль, игрокам ничего не дает, экспирианс лучше если нажать ghost - смысл от этих багованных эсенций ?

**Comment by Slavik2001** [comment]
Максимум зачем эсенция, чтобы та общалась с остальными генками пока руль мертв. Я так 1 генку спас от гиббера и позвал других генок.

**Comment by pro100kotah** [comment]
Вообще с этими эссенциями реально очень много багов и проблем. Та же передача управления. Нужно как-то тотально все переделать. Если проблемы критические, то временно вывести эссенции из игры. Так как за них все равно никто не сидит. После пожирания 90% игроков просто гостается/ливает/заходит за нового моба.

**Comment by AirBlack** [comment]
эссенциям же дает инста респавн при госте вроде(раньше точно давало), да и что я давал управление эссенциям когда не хотел играть, что мне давали управление, совсем вырезать плохая идея т.к. нет ничего более постоянного чем временное решение и мб за них потом никто не тронется в будущем просто учитывая отток игроков
