### ISSUE TITLE
Нет возможности как либо вернуть СПУ

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1259]
#### Подробное описание проблемы

Все играбельные рассы имеют возможность вернуться в игру

#### Что должно было произойти

МОжно создать новое тело, с помощью некой "батарейки" или платы как у борготы, ребутнуть СПУ
 
#### Что произошло на самом деле

Тебя бьют за любые возможности вернуть СПУ в игру

#### Как повторить

Повторений нет #Зве_Помоги_СПУ

#### Дополнительная информация:
#СПУ_ЖИВИ

**Comment by Dennok** [comment]
Давно пора добавить возможность заказать тело спу в карго к которому можно былобы приделать позитронку.

**Comment by Dennok** [comment]
Или добавить возможность строительства, имея нужные технологии.

**Comment by ZVee** [comment]
Я не думаю что СПУ должны возвращаться в игру (У каждого "ксеноса" свои плюсы и минусы) - инфа вся в мозге, а если его уничтожают (сейчас он умереть типа может что некорректно конечно) - можно считать гейм овер в этом раунде. Касательно заказа запчастей - вспомним на минуточку бэк и чего боятся СПУ больше всего и почему.

**Comment by Olt1771** [comment]
Ну соль в том что на новобее можно собирать СПУ. Да-да-да мы не новобей. Но это как то не то что всех можно клонировать, дидоны после смерти в мелкую дидону с возможностью вырасти.

СПУ умирают от всего так что да, было бы неплохо дать возможность их восстановить

**Comment by ZVee** [comment]
Ну, у нас может быть свое мнение и взгляд отличный от других билдов и не обязательно следовать или делать так, как это у других.

Я могу немного обрадовать так же по поводу СПУ - считаю что они не должны "умирать" даже если голова расстанется с телом, до тех пор, пока корпус защищающий мозг цел или пока кто-то не подойдет и не начнет дубасить уже саму голову например. Т.е СПУ должны быть в разы более живучи чем это есть на текущий момент, однако эта живучесть вовсе не означает, что СПУ нельзя искусственным способом быстро вывести из игры. А еще возможно могут обладать защитой от электромагнитного излучения, если уж не полной, то точно повышенной, чем любая другая техника, а это еще больше объяснялоб, почему они настолько дорогие - что в карго их попросту нет смысла вставлять, но в этом минус - обычные протезы не должны быть совместимы с их телом - т.е потеря чего либо - билет в один конец, либо они должны получать дебафы - если им ставят что-то левое и возможно иметь возможность все еще хоть что-то, да "скрафтить" родное для них.

Как то так, это лишь часть моего виденья о том, какие должны быть СПУ.

**Comment by Raschert0** [comment]
Когда какой-то механоабузер пишет "проспорал", я так и представляю, что он проспорил и получил бна.

**Comment by omejka** [comment]
Сделайте чтоб голова СПУ жила и разговаривала и ее можно было приварить обратно операцией,и чтоб всякие гроины не отлетали,только руки-ноги

**Comment by sovok4** [comment]
Имба, контрить СПУ только сифорнув голову. Пусть тогда голова живет, пока у неё аккумулятор не сядет. А потом рип.

**Comment by dearprincesscelestia** [comment]
Разве у них позитронка в голове, а не корпусе? Вроде же голова бесполезный телевизор.

**Comment by sovok4** [comment]
Без головы, однако, они не живут.

**Comment by dearprincesscelestia** [comment]
Ну, это надо править. Если, конечно, про позитронку в пузе у нас в беке, а не у каких-нибудь бейцов.

**Comment by omejka** [comment]
А голова бы ломалась от 3ех ударов огнетушителем по ней,гибаясь на дербс,как от синтетов

**Comment by Olt1771** [comment]
Уравнение механоёба. ТЫ кодер . Да-Нет. Да-механоёб. Нет-вы юзаете фичи и баги механа. Да-механоёб. 
Адресовано сиру Расчуру ящуру

**Comment by Avatar4** [comment]
СПУ, это по сути синтетики. Охуенно разумные машины которые дошли до того - что основали целую расу. Но сейчас они ущербнее любого борга по сути. Я думаю, такие машины вымерли бы от своего собственного невезения. Их нужно либо стабилизировать, либо убрать вообще в коробку где может через миллионы лет их наконец починят.

**Comment by dearprincesscelestia** [comment]
АПЦ - это борги, которые себя выкупили, делов-то. Одни вымрут - другие выкупятся.

**Comment by WallShrabnic** [comment]
> СПУ, это по сути синтетики. Охуенно разумные машины которые дошли до того - что основали целую расу. Но сейчас они ущербнее любого борга по сути. Я думаю, такие машины вымерли бы от своего собственного невезения. Их нужно либо стабилизировать, либо убрать вообще в коробку где может через миллионы лет их наконец починят.

Кто-то не читал бэк

**Comment by Avatar4** [comment]
Зачем мне читать бэк той расы за которую я не играю? А тем более презираю?

**Comment by dearprincesscelestia** [comment]
Зачем рассуждать о том, что не читаешь, за что не играешь и что презираешь?

**Comment by Avatar4** [comment]
Зачем спрашивать зачем когда зачем ведь зачем?
