### ISSUE TITLE
[Proposal] Добавить на Tau Ceti II лок оос при старте раунде

### ISSUE THREAD

**Issue by Tenderloyn** [TauCetiStation/TauCetiClassic#12609]
### Описание

Чтобы не случались прецеденты нарушения правил

**Comment by Venngedi** [comment]
Эти несколько человек хотя бы могут поболтать в чате, а не тихо заниматься работкой и ломать шлюзы в важные отсеки.
![Old](https://ss13stats.skullnet.me/server/b47fea6387d853344542f4a10ebe0fffcb30b17a4ec3a3f4eabab83ceadf547a/weekly)
На сервере большую часть времени стоит расширенный режим, а значит никакой меты в OOC чате нет.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/4527d8e0-720b-4ac1-95a9-dcf6b006b2c8)
Это не спасёт режим от раскрытия раньше времени (напомню, что кроме трейтора и эксты там ничего нет), а только сильно навредит игрокам. С атмосферой лоупоп раундов можешь сам ознакомиться: https://forum.taucetistation.org/t/banhammer-boeviki-na-stanczii/38290/8.

**Comment by Venngedi** [comment]
Сейчас OOC включен и на 1-ом сервере. Не актуально
