### ISSUE TITLE
Имба дефибы некотрятся

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1263]
#### Подробное описание проблемы

Дефибы не контрятся

#### Что должно было произойти

Дефибы не пробивают риги/армор

#### Что произошло на самом деле

Они пробивают, игнорируя даже небо, даже аллаха

#### Как повторить

Взять дефибы и жахнуть парня в фул обвесе, понять что ты герой

#### Дополнительная информация:

Давно пора было это сделать

**Comment by Shudyn** [comment]
Но все забыли, что дефибы нужно заряжать и требуют энергию.
А вот настоящая имба, это полис батон из ПШШШШШШШШ, который станит за удар на полчаса и не требует энергии.

**Comment by Olt1771** [comment]
Эх сейчас бы щит БЛОЧИЛ ВСЁ

**Comment by Uvash** [comment]
Действительно, дефибрилятор изменяет состояние пациента напрямую.
https://github.com/TauCetiStation/TauCetiClassic/blob/c53db5a352e2d5095a2f33f52a5ee4cc347afddc/code/game/objects/items/weapons/defibrillator.dm#L90

**Comment by Kurshan** [comment]
#1721
