### ISSUE TITLE
Когда на видеокамерах висит статус, невозможно взаимодействовать с проводами.

### ISSUE THREAD

**Issue by ZVee** [TauCetiStation/TauCetiClassic#1265]
#### Подробное описание проблемы
Думаю проблема в нехватке is_operational_topic(), т.к родительский не совсем подходит для взаимодействия с проводами и рассчитан больше на интерфейсы.
#### Что должно было произойти
Например, обрезаться провода.
#### Что произошло на самом деле
Когда зона обесточена (видимо это на камеры передается), взаимодействие с проводами видеокамер становится недоступным, но это не обязательно источник, стат может и по другим причинам измениться.
#### Как повторить
Можно насильно stat переменную пошатать, зону обесточить, способов думаю полно.
#### Дополнительная информация:
Мысли не совсем по теме, но, может камеры без энергии должны переставать работать вовсе? Это не про неверную работу, а про доведение до ума механа видеокамер, что фактически к ребалансу геймплея зависящего от них. Хотя думаю, в них какие-нибудь там батарейки которые без источника подпитки могут вечность работать, так что не суть.

**Comment by Raschert0** [comment]
> Мысли не совсем по теме, но, может камеры без энергии должны переставать работать вовсе? 

Только после того, как кто-то сделает для ИИ видимость всей машинерии без камер.

А так да, проблема в питании

**Comment by ZVee** [comment]
>Только после того, как кто-то сделает для ИИ видимость всей машинерии без камер.

Во всей машинерии установили камеры или в смысле машинерию видно сквозь ПШШ без видимости окружающей среды?

**Comment by Dennok** [comment]
Второе, ктот опоказывал.

**Comment by Raschert0** [comment]
Да, второе

**Comment by SpaiR** [comment]
Думаю я перенесу датум для проводов, у них свой отдельный топик.
#559
