### ISSUE TITLE
У перечницы пропадает спрайт при опустошении

### ISSUE THREAD

**Issue by AirBlack** [TauCetiStation/TauCetiClassic#12682]
#### Что должно было произойти
Перечница не меняет спрайт когда пуста
#### Что произошло на самом деле
Перечница становится невидимой при полном опустошении

### Шаги воспроизведения

1. Опустошить перечницу(я готовил супер байт бургеры поэтому использовал много перца)
2. Посмотреть на перечницу

### Дополнительная информация:

Issue reported from  Round ID: 62367 (Tau Ceti Classic (RU))
Testmerges: ```#12580# 12640# 12648# 12656```
Reporting client version: 515.1614
Раунд еще идет, но кроме факта того, что я готовил супер байт бургеры, я ничего не протек

**Comment by Udokun** [comment]
Закройте.
