### ISSUE TITLE
Решетки защищают сингу от метеоров.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1268]
Все таки не баг, но я бы сказал критично. Я уже не первый раз вижу как при метеоритном шторе - один метеорит залетевший в поле - вырубает или уничтожает его. В итоге, всю станцию пожирает синга или тесла.
Серьезно, это уже происходит не первый раз.
Эту проблему возможно решили бы двойные или тройные решетки южнее от полей (если метеор не пролетает сквозь них).

**Comment by dred1792** [comment]
Не царское это дело, генератор защитного поля разворачивать.

**Comment by igigin** [comment]
И правильно залетает. Надо добавить, чтобы парочка метеоров всегда туда целилась.

**Comment by dearprincesscelestia** [comment]
Двигатель и так же в разобранном состоянии, может, в таком случае вручную решетки ставить? Благо есть где.

**Comment by ZVee** [comment]
>Не царское это дело, генератор защитного поля разворачивать.

Могу предложить решение ситуации на примере этого - надо увеличить паузу с момента объявления о метеоритах до начала самой бомбардировки настолько, чтобы у инженеров было достаточно времени на поднятие щита, т.к мне кажется, что это одно из основных назначений использования их, а не для блокировки отсеков или еще каких иных целей направленных игроками, против игроков.
~Ну и заодно повысить их количество.~

**Comment by dred1792** [comment]
Их там итак 2, плюсом в карго заказать можно, если не ошибаюст.

**Comment by ZVee** [comment]
Немного не понял к чему про количество и заказы, просто у инженеров возможно не хватает времени на то, чтобы бросить дела, добежать до инженерного (это если нет препятствий на пути) и потом развернуть еще и щит с правильными настройками.

**Comment by igigin** [comment]
В целом согласен. Время надо дать дополнительное и можно сделать насыщенней метеоритный пояс, чтобы аутисты страдали.

**Comment by dred1792** [comment]
Я тоже немного не понял к чему я это написал. XD
А так да, неплохо бы увеличить отсрочку перед бомбёжкой.

**Comment by Raschert0** [comment]
Ну, если дать им больше времени, то и метеоров тоже пусть получают больше

**Comment by ZVee** [comment]
Насчет кол.ва - не спроста перечеркнул, кто таки решит это добавить - должен отдать полный отчет того, к чему это приведет и что после этого обычно следует. Хотя если инженеру умудряться покрыть огромную площадь после которой народ не побежит шаттл вызывать, то может и годно будет. Так же важно вопрос потребления энергии рассмотреть (если речь про несколько одновременно) - никогда особо не лазал в щиты, и не знаю сколько они могут сжирать в худшем случае и покроет ли генератор расходы.

**Comment by Raschert0** [comment]
Ну, скафандры у космонавтов теперь в шаговой доступности и время, чтобы уйти в центральную часть станции, у них будет

**Comment by Uvash** [comment]
А может вспомним щиты с православной Луны? Т.е. есть некоторые конденсаторы энергии (а-ля смесы) в инженерном, некоторое количество эмиттеров по станции, и кнопка для включения всего этого цирка на мостике. Из-за того что на луне была великая и ужасная материя, а энергия вырабатывалась из ТЭГов, то продержать щиты не тратя заряд из конденсаторов было достаточно сложной задачей (но возможной).  В итоге в случаи наступления ивента с метеоритами, можно было просто врубить щиты и спокойно переждать его.

 У нас же в инженерном щиты, которые не очень годятся для прикрытия станции по трём причинам.
- 1 Они типа "пузырь" (читай выдают квадрат, как следствие блокируют техи и кусок медбея)
- 2 В них нельзя закачать много энергии из-за того что машинерия поддерживает их от части (даёт собрать но не апгрейдить. И то вроде собранные щиты не работают. Но это нужно проверять).
- 3 Узкая специализация. Из-за размеров прочность самого поля достаточно низкая, против метеоритов его ещё хватает, а вот против оружия уже нет. (А вот в те далёкие времена, когда их ещё не пофиксили щиты при силе поля 4 нельзя было пробить лазером или огнестрелом).

 Так что что бы щиты ныне достаточно интересная, но в практике бесполезная вещь. Возможно добавлению актуальности поспособствуют следующие вещи:
 - 1 Замена одного из двух щитов в инженерном с типа "пузырь" на "покрытие" (читай накрывают тайлы космоса рядом с полом/стенами. Если кто-то решиться мапить, то учесть что он будет перекрывать лучи эмиттеров)
 - 2 Поддержка апгрейдов из РнД/множественное подключение конденсаторов к 1 щиту.
 - 3 Пометка пола в инженрном отсеке, в оптимальном месте.

**Comment by Dennok** [comment]
Еще можно добавить то что можно портировать специальные разрушители щита, которые можно поставтиь около шлюзов. И предположительно оноло техже эмиттеров.
