### ISSUE TITLE
Спрайт наушника исчезает, если положить что-то во второй слот уха

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#12683]
#### Что должно было произойти
Спрайт наушника на месте
#### Что произошло на самом деле
Не

### Шаги воспроизведения

1. Надеть наушник со спрайтом (как у блющилда, например).
2. Положить что-то во второй слот уха (другой наушник или ручку).

**Comment by ZER0-In** [comment]
Походу спрайты проебаны
