### ISSUE TITLE
Дюп металла

### ISSUE THREAD

**Issue by KarpinTi** [TauCetiStation/TauCetiClassic#12691]
#### Что должно было произойти
После разбора ящика (стоимость создания 2 металла) осадок в соответствующую цену или ниже
#### Что произошло на самом деле
После разбора ящика (стоимость 2 металла) падает 3 металла, из 2 новый ящик и так далее повышая количество металла

### Шаги воспроизведения

1. найти 2 металла и сварку
2. из 2 металла сделать железный шкаф
3. разобрать шкаф сваркой
4. подобрать 3 металла
5. повторить

### Дополнительная информация:

Issue reported from Tau Ceti Classic Sandbox
Testmerges: ```#12580# 12640# 12648# 12656```
Reporting client version: 514.1583

**Comment by Oz1Es** [comment]
такое можно сделать и на голо, берёшь лазер и стреляешь по столам
