### ISSUE TITLE
Детонаторы пропадают в никуда

### ISSUE THREAD

**Issue by R0bicod** [TauCetiStation/TauCetiClassic#12701]
#### Что должно было произойти
1.Разбираешь гранату(например)
2.Тычешь отвёрткой по детонатору
3.Активатор(сигналер например) и игнайтер разделенны
#### Что произошло на самом деле
1.Разбираешь гранату
2.Тычешь отвёрткой по детонатору
3.Активатор и игнайтер пропадают в никуда

### Дополнительная информация:

![2024-01-09_15-47-24](https://github.com/TauCetiStation/TauCetiClassic/assets/110482220/97dc23d6-3cf4-4bb9-84e9-2d1f21ab7c83)

**Comment by ZER0-In** [comment]
Дополнение к:
https://github.com/TauCetiStation/TauCetiClassic/issues/12542
