### ISSUE TITLE
2 блоба на  30 человек

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#12707]
#### Что должно было произойти
1 блоб на 30 человек
#### Что произошло на самом деле
2 блоба на 30 человек

### Шаги воспроизведения

1. запустить режим блоб в 30 человек

### Дополнительная информация:

max_roles = max(round(num_players/PLAYER_PER_BLOB_CORE, 1), 1)
в раунде было где-то 28-30 человек и заспавнилось два блоба
айди 62427

**Comment by Chip11-n** [comment]
Выбираем: скилл ишуе или щитспавн ишуе?
