### ISSUE TITLE
билд нельзя скачать

### ISSUE THREAD

**Issue by LeoGames2023** [TauCetiStation/TauCetiClassic#12703]
### Описание

я скачал zip архив открываю ошибка при распаковке тоже ошибка(неожиданный конец архива)

**Comment by Dominig12** [comment]
А у тебя памяти достаточно на компе?

**Comment by Dominig12** [comment]
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/24685276/8a93df55-bf17-4327-aa2d-a724dc331756)
Не воспроизводится

**Comment by 4310V343k** [comment]
Скачивание репозитория от нас не зависит, за помощью можно обратиться в поддержу GitHub или дискорд сервера
