### ISSUE TITLE
Баг с привязкой к вещам.

### ISSUE THREAD

**Issue by psebash** [TauCetiStation/TauCetiClassic#1271]
#### Подробное описание проблемы
Когда ты привязан к чему-то, что нельзя двигать, и тебя телепортирует, то взаимодействовать с тобой не могут.
#### Что должно было произойти
Должен отвязаться от предмета, другие могут взаимодействовать с тобой.
#### Что произошло на самом деле
Остался привязанным к той же вещи, но уже в новом месте. Отвязать хумана невозможно.
#### Как повторить
Зайти за абдуктора, привязать к кровати/стулу, который не движется, телепортировать, попробовать сдвинуть.

**Comment by Raschert0** [comment]
#1331
