### ISSUE TITLE
СЕ,РД,Капитан ИИ и борги не имеют доступа к ИИ дверям на спутнике ИИ

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1272]
#### Подробное описание проблемы

Нет доступа Глав и синтетиков к стеклянным дверям Ai Core Door на спутнике ИИ

#### Что должно было произойти

Иметься доступ

#### Что произошло на самом деле

Его нет

#### Как повторить

Зайти за выше указанных ролей и попробвать

#### Дополнительная информация:

Там три таких двери 1 у основного ИИ и две под доп ядра

**Comment by DeadOberst** [comment]
Кстати, у ЕРТ доступ к этим дверцам есть.
