### ISSUE TITLE
Маппер забыл добавить отсек с запчастями, для восстановления телекомов

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1273]
#### Подробное описание проблемы

Нет деталей для телекомов

#### Что должно было произойти

Они должны быть

#### Что произошло на самом деле

Их нет

#### Как повторить

Взглянуть на старую карту!

#### Дополнительная информация:

О пасхалках и комнате отдыха с автоматами не забудь

**Comment by Lancer411** [comment]
Кто будет фиксить, не забудьте обнулить у этих запчастей и запчастей в самих телекомах техлвл. :peka:

**Comment by Dennok** [comment]
Смысла нет пока нет ресов. А как ресов нет то смысла нет.

**Comment by Olt1771** [comment]
Пока кто то будет идти за этими деталями я апну на такой же уровень который есть у этих деталей :peka:
