### ISSUE TITLE
Из третьего граба и кроваток нельзя выбраться.

### ISSUE THREAD

**Issue by ZER0-In** [TauCetiStation/TauCetiClassic#12737]
#### Что должно было произойти
Можно выбраться
#### Что произошло на самом деле
Нельзя

### Шаги воспроизведения

Попасть в граб или кроватку

### Дополнительная информация:

https://github.com/TauCetiStation/TauCetiClassic/issues/10353

**Comment by Deahaka** [comment]
Дубликат закреплён в ишуе

**Comment by ZER0-In** [comment]
> Дубликат закреплён в ишуе

Ну так займись им

**Comment by Kiromaka** [comment]
Из кроватки можно встать, просто поломанная хуйня. 
Рест рест брэйк клик по кроватки брэйк, короче спамим кнопками которые могут поднять, слишком давно не играл, чтобы дать реальный способ.

**Comment by Deahaka** [comment]
Я и занялся. Фича

**Comment by Kiromaka** [comment]
А, ну еще любой повторный стан спасает, в том числе слипы, софт криты.(вроде)
