### ISSUE TITLE
Еган съедает заряд

### ISSUE THREAD

**Issue by psebash** [TauCetiStation/TauCetiClassic#1274]
#### Подробное описание проблемы
У нас в руках еган. Если кликать быстро, то в чат выйдет мессага что еган к выстрелу не готов и пропадает один заряд.
#### Что должно было произойти
Заряд не должен был пропасть
#### Что произошло на самом деле
Он пропал
#### Как повторить
Достаем еган и начинаем быстро клацать.
#### Дополнительная информация:
20 выстрелов в режиме тазера? Это ж имба. Станит он с трех. Просто подумайте.

**Comment by ZVee** [comment]
Судя по всему, сломали из-за переноса вот этого - https://github.com/TauCetiStation/TauCetiClassic/commit/09615bd8d5a57786645089ccc18a0fa0be698d7d#diff-46250b1454503719009a5850364bd7b8L109
