### ISSUE TITLE
Баг с деталями для генетики

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1275]
#### Подробное описание проблемы

С Т4 деталями(с остальными не тестировал) после 8-10 раз резко подскакивает уровень радиации у куклы.

#### Что должно было произойти

Радиация не должна была резко подскочить

#### Что произошло на самом деле

Радиация прыгнула до отметки в 20

#### Как повторить

Создать куклу, засунуть в ДНК подифаер с т4 делями, начать жать любой блок раз 10 и наблюдать как подскакивает уровень радиации

**Comment by Avatar4** [comment]
Улучшенная генетика вообще вся багнутая.

**Comment by ZVee** [comment]
Посмотрел код, работает как и задумано. Могу проспойлерить если уж очень нужен ответ.

**Comment by Raschert0** [comment]
К слову, я думаю, что всё же баг, хоть в коде и написано иначе

**Comment by ZVee** [comment]
> я думаю, что всё же баг

Даже знаю от чего такие мысли, но рекомендую еще раз посмотреть и еще раз задуматься (надеюсь мы об одном и том же).

**Comment by Raschert0** [comment]
Да, об одном и том же. Не вижу причины, по которой оно должно работать именно так.

**Comment by ZVee** [comment]
Это нормально, большинство когда посмотрят - подумают, "что за бред! они перепутали операторы...", однако суть вовсе не в формуле, коде или еще чем-то, а в идее что ли. Не знаю, может и не удачно намекаю, тут только если сразу раскрою полностью мысли.

**Comment by Raschert0** [comment]
Да, идея так себе - ведь досттаочно просто заменить ПШШШ и не заменять ПШШШШ, чтобы полчить плюшки без дебаффов. И это неправильно by design

**Comment by ZVee** [comment]
А вот это ты верно подметил, косяк разве что в неверной переменной и там должна она быть на радиацию (правда это уже другого репорта стоит). А в остальном - все как и задумано.

**Comment by Skippeer12** [comment]
#545
