### ISSUE TITLE
[Proposal] Починить Раскладку

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#12754]
### Описание

> Пожалуйста, переключитесь на английскую раскладку и кликните сюда, чтобы исправить хоткеи коммуникаций.

Я не знаю какая магия нас обязывает держаться за этот костыль, но я заплачу 50 американских долларов герою который нас от него освободит. Свяжитесь со мной через дискорд lud.uk

Если проблема в том что всем лень прописать ассоциацию английской кнопки с русской, надеюсь это подтолкнёт к решению.

Если проблема глубже и настолько глубокая что вообще никак нельзя пофиксить пожалуйста отпишитесь (но я помню что даже &#255 с горем по полам фиксили а не делали это проблемой игрока)

**Comment by muWander** [comment]
https://github.com/ss220-space/TerraGov-Marine-Corps/pull/1 можно отсюда стащить костыль
