### ISSUE TITLE
"Заявить" - занять первым.

### ISSUE THREAD

**Issue by Kiromaka** [TauCetiStation/TauCetiClassic#12762]
#### Что должно было произойти
Нажатие кнопки "заявить" на мидраунда, должно рандомить из нажавших.
#### Что произошло на самом деле
Нажать "заявить" может только 1/2 человека, первый получает роль.

### Шаги воспроизведения

Спавнер меню мидраундс

### Дополнительная информация:

Это вроде давно уже, типо ФИЧА ?

**Comment by Chip11-n** [comment]
Я даже не знаю, несколько дней назад при мне было 4 заявленных на 1 позицию.

**Comment by volas** [comment]
может просто таймер в тот момент сработал и роли раскидало? Или по таймеру спавнер стал не актуален.

отображение еще может где-то факапить из-за слипов в процессе спавна персонажа, но это должно редко случаться.

**Comment by Kiromaka** [comment]
> может просто таймер в тот момент сработал и роли раскидало? Или по таймеру спавнер стал не актуален.
> 
> отображение еще может где-то факапить из-за слипов в процессе спавна персонажа, но это должно редко случаться.

Не, там лон опс с нулевой был, просто первые 2 успели нажать, остальные не могут.
Думаю дело в лимите, но зачем он нужен для "заявки". И вообще для мидраундов.

**Comment by volas** [comment]
> так и задумывалось по дефолту ставить лимит на регистрацию?

не уверен, возможно флаг по дефолту должен был быть TRUE...
