### ISSUE TITLE
Клонирование трупов генок

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1276]
#### Подробное описание проблемы
Трупы убитых генками можно клонировать
#### Что должно было произойти
Трупы убитых генками нельзя клонировать, как и клонировать тела хасков (но это для другого ишью)
#### Что произошло на самом деле
Труп клонировали, на станции появилось два одинаковых человека
#### Как повторить
Попытаться клонировать тело убитого генокрадом
#### Дополнительная информация:
N/A

**Comment by volas** [comment]
На самом деле так и было задуманно. Хотя решение спорное.

**Comment by WallShrabnic** [comment]
В чейнджлоге где-то написано, что убрали возможность клонирования убиенных генками

**Comment by ZVee** [comment]
>В чейнджлоге где-то написано, что убрали возможность клонирования убиенных генками

Было такое, на первых страницах, но потом мы снова изменили, тайно. Все это во времена закрытого билда.

**Comment by ZVee** [comment]
Кстати, если клонирование вдруг стало работать без апгрэйда клонера - то вот это баг и надо чинить.
