### ISSUE TITLE
Захват зоны за культ сбрасывает прирост фавора от обскурума

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#12760]
#### Что должно было произойти
Захват зон не сбрасывает прирост фавора у культа с аспектом на тьму и политыми тайлами в темноте.
#### Что произошло на самом деле
Захват любой зоны сбрасывает прирост фавора от политых техов за культ с обскурумом.

### Шаги воспроизведения

1. Берем обскурум в аспектах
2. Поливаем теха проклятой водой, видим прирост фавора например +30
3. Захватываем комнатку, прирост сбросился

### Дополнительная информация:

Крайне простой способ испортить жизнь культу, просто тыкнуть захват зону и у культа теперь нет прироста фавора

**Comment by Deahaka** [comment]
Дубликат https://github.com/TauCetiStation/TauCetiClassic/issues/9202
