### ISSUE TITLE
Баги и улучшения хасков

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1277]
#### Подробное описание проблемы
Хаски - тела подвергнутые долгому нахождению в спейсе и/или большому бёрн урону.
Описание с ТГ - This has either happened by extreme heat (fire), extreme cold (space) or liquid suckification (changeling sucked their juices/DNA out). Not a nice thing to witness at first, but you get used to it. У нас есть несколько проблем с ними:
1. Неадекватный предел урона, в некоторых случаях удаётся реанимировать подвергнутого хаскизации и он останется уродом до конца раунда.
2. Неадекватное превращение: иногда можно вытащить труп из спейса, начать заматывать в бинты и тело станет хаском. Часто после возникает проблема 1
3.Тела хасков можно клонировать. На официальной вики ТГ ( Да, мы не они) сказано, что без улучшений тело хаска нельзя клонировать, но работает трюк с мартышкой
#### Что должно было произойти
1. Адекватный порог урона
2. Тело превращается при наборе определённого урона
3. Клонировать нельзя
#### Что произошло на самом деле
1. См. описание проблемы
2. Аналогично
3. Аналогично
#### Как повторить
Поработать в медбее некоторое время
#### Дополнительная информация:
https://tgstation13.org/wiki/Guide_to_genetics#Hark.21_A_Husk.21

**Comment by ZVee** [comment]
>На официальной вики ТГ

Ну и что? У нас между прочим **бей**, на который накатили в той или иной мере ТГ (причем мобов это касается меньше всего) и по немного остальных билдов.

Ну, хаск у нас появляется по такой формуле - ((100 - total_burn) < -100) && stat == DEAD) - т.е тело должно быть мертво и на нем более 200 ожога, далее уже как само обновление вызовется, возможно оно не всегда вызывает как надо, а бинты могут например форсить.


>Клонировать нельзя

У нас это намеренно можно (однако там должно быть соблюдено одно маленькое условие), т.к нам на деле все равно как у других, и мы можем свой замок строить.


В целом, погляжу на это когда дойду.

**Comment by dearprincesscelestia** [comment]
Нужна просто возможность сделать пересадку кожи.

**Comment by omejka** [comment]
Или в крио с помощью какого-нибудь хемекота

**Comment by Dennok** [comment]
Можно попробовать дна инжектором. Возиожно даже с собственной дна

**Comment by FelixRuin** [comment]
сейчас хаски лечатся передозом дермалином, так что, кажется, теперь проблема менее критична

**Comment by FelixRuin** [comment]
... мне надо бисать в личку чтоб закрывали в пры? или как это делается. исправлено в пре https://github.com/TauCetiStation/TauCetiClassic/pull/3186

**Comment by volas** [comment]
можно просто тут слапать например ``@TauCetiStation/collaborators``
