### ISSUE TITLE
Из ЛВАПы можно стрелять,держа ее одной рукой.

### ISSUE THREAD

**Issue by omejka** [TauCetiStation/TauCetiClassic#1278]
#### Подробное описание проблемы
Из охуенно длиной и мощной пушки,так еще и с зумом,можно стрелять с одной руки
#### Что должно было произойти
Для зума\стрельбы винтовку надо взять в две руки,как пилу.
#### Что произошло на самом деле
Палишь из рифлы по-македонски
#### Как повторить
взять лвапу в руку,стрельнуть
#### Дополнительная информация:
Ну там даже на спрайте в руках он держит ее обеими руками

**Comment by omejka** [comment]
Щас прибегут всякие олты и скажут,что так и должно быть,но вы ему не верьте

**Comment by Raschert0** [comment]
Прибегу я и скажу, что так и должно быть, так как у Лвапы нету отдачи

**Comment by Dennok** [comment]
Raschert0 это Olt CONFIRMED

**Comment by omejka** [comment]
У тебя есть длинная такая хуевина.В ней всякие линзы,батареи,металлический корпус и прочее и прочее,а ты держишь все это одной рукой,так еще и палишь короче

**Comment by Dennok** [comment]
У насже не люди а терминаторы, ты че. Они и миниган и лвапу и саву одной рукой удержат.

**Comment by omejka** [comment]
Пилу таки нужно брать в обе руки,ПТР-нет

**Comment by CryptoKisik** [comment]
ПТР не нужно брать в 2 руки, ибо он заряжается одним патроном (баланс).
А лвапа - фича. В ней всего-то три выстрела. Вот единственная фигня, которую стоит пофиксить,что можно зумить из лвапы, а стрелять из лазергана в другой руке.

**Comment by Kilkalestia** [comment]
А пофиксить это можно как раз двойной хваткой :peka:

**Comment by Skippeer12** [comment]
Это всё спрайт виноват, раньше было лучше.

**Comment by WatlerJe** [comment]
Раньше действительно было лучше, ну... раньше когда спрайта в руке вообще не было и мощнейший залп прилетал из руки куклы. 
Алсо я еще в то время реквестировал двойной граб таких валын, а после маринадов так вообще мастхэв.
