### ISSUE TITLE
Вендомат повелителя гастрита

### ISSUE THREAD

**Issue by SiveanBen** [TauCetiStation/TauCetiClassic#12797]
#### Что должно было произойти
Сунули в вендомат пустую пачку горячего рамена, получили полный горячий рамен.

#### Что произошло на самом деле
Сунули в вендомат пустую пачку горячего рамена, получили полный горячий рамен и полный обычный рамен.

### Шаги воспроизведения

Покупаем острый рамен, жрём, открываем вендомат отвёрткой, суём пустую пачку в вендомат, получаем там +1 острый рамен, и +1 обычный рамен.

### Дополнительная информация:

Issue reported from  Round ID: 62677 (Tau Ceti Classic (RU))
Testmerges: ```#12663# 12684# 12757# 12763```
Reporting client version: 514.1589

**Comment by LudwigVonChesterfield** [comment]
#9139
