### ISSUE TITLE
Катание двух мобов на 20 кусках мыла крашит сервер.

### ISSUE THREAD

**Issue by Shudyn** [TauCetiStation/TauCetiClassic#1279]
#### Подробное описание проблемы
Заходим за ящера. Берем шкаф, берем ~20 штук мыла(больше - лучше), берем шкаф, берем двух ассистентов.
Засовываем мыло и ассистентов шкаф и как можно быстрее открываем и закрываем шкаф.
Профит, ящеры кинули под сервер мыло и он крашнулся.

#### Что должно было произойти
Сервер не должен крашиться
#### Что произошло на самом деле
Сервер крашнулся, но восстановился и продолжил работу с того же места.
#### Как повторить
Заходим за ящера. Берем шкаф, берем ~20 штук мыла(больше - лучше), берем шкаф, берем двух ассистентов.
Засовываем мыло и ассистентов шкаф и как можно быстрее открываем и закрываем шкаф.
Профит, ящеры кинули под сервер мыло и он крашнулся.
#### Дополнительная информация:
Убираете один способ краша, ящеры находят другой. 
Лучше не фиксить краши, а удалить ящеров, там и баги все пропадут.

**Comment by ZVee** [comment]
Я все же надеюсь, что у нас кликеры бросят использовать, иначе придется стелсово автобан подсунуть без права на разбан (т.е бот будет банить как за прокси открытые). Речь не про абузы, а вообще вне зависимости от причины их использования.

**Comment by WallShrabnic** [comment]
У меня мышка иногда прокликивает два раза или когда резист прожимаю, приходится насиловать бедную кнопку - я бан что ли за это получу?

**Comment by Skippeer12** [comment]
У нас тут тик лаг (или как оно там называется(если оно за это вообще отвечает)) толи большой толи маленький и из-за этого надо прокликивать на предмет несколько раз чтобы взять его.

**Comment by ZVee** [comment]
Почти, тик лаг тут не причем, у нас стоит фоновая задержка почти на все клики, другие билды давно переделали этот момент, поэтому у них управление отзывчивое, а у нас - кажется как будто какие-то непонятные лаги, а на деле просто пауза между кликами.

**Comment by omejka** [comment]
Почему бы не переделать,если вы уже взялись за всякие рефакторы?

**Comment by ZVee** [comment]
Слишком много всего задеть надо, фактически все то, что связанно с кликами и надо еще каждый уголок просмотреть ну и плюс по билду ориентироваться. Учитывая что у нас тут на энтузиазме пилят все, то это слегка меняет все дело в корне, но если уж говорить о донате, думаю он там бы исчислялся неплохой такой европейской зарплатой :D. Так что тут если только кого-то припрет этим заняться.

**Comment by SpaiR** [comment]
эффект подскальзывания теперь работает иначе https://github.com/TauCetiStation/TauCetiClassic/pull/1262 повторить описанные в ишью действия стало практически невозможно
