### ISSUE TITLE
[Proposal] Дать повару немного скилла в химию

### ISSUE THREAD

**Issue by AirBlack** [TauCetiStation/TauCetiClassic#12801]
### Описание

У повара есть гриндер на кухне и Condiment Pro(тот же химмастер но с другими бутылками) в мясорубке. Только вот скиллов на использование их нет, поэтому любые взаимодействия с ними это *hmm и длинный делей. 

Было бы неплохо добавить какой-нибудь маленький скилл химии дабы пользоваться машинерией этой без задержек.

**Comment by Slavik2001** [comment]
Бармен

**Comment by Deahaka** [comment]
Да нахуй вообще скилы эти...

**Comment by AirBlack** [comment]
> Бармен

кондимастер и гриндер не у бармена

**Comment by AirBlack** [comment]
я долбаеб, скилл есть, я просто забыл что в том раунде я был ассистентом которого устроили шеф поваром, закрываю
