### ISSUE TITLE
АВД - бесполезный элемент.

### ISSUE THREAD

**Issue by psebash** [TauCetiStation/TauCetiClassic#1281]
#### Подробное описание проблемы
Сейчас АВД - второй адвокат, только с доступом к факсу. Это агент с ЦК, который наравне с офицером может быть в опасности, ведь на ревах/нюках выпиливают в первую очередь, но у него даже нет примитивных средств защиты. 
#### Что должно было произойти
У него должна быть кобура с пистолетом. Доступ в мед, техи(агент жы).
#### Что произошло на самом деле
Этого всего нет
#### Как повторить
Зайти за АВД и понять что он бесполезен
#### Дополнительная информация:
ИРЛ у всех оперуполномоченных есть валына, почему у ИМПЛАНТИРОВАННОГО агента корпорации ее нет?

**Comment by Kurshan** [comment]
У меня только один вопрос, а почему он не должен быть вторым адвокатом?
*Тут где-то должны быть возгласы про ХоПа без импланта и бла-бла-бла. нет, спасибо.*

**Comment by Shudyn** [comment]
АВД нужен, только чтобы позвать шаттл/ЕРТ и все. Чисто РПшная профа, как и адвокаты и тому подобные.
У АВД есть имплант, но нет пушечки, а у Хопа нет импланта, но есть пушечка. Fix it pls

**Comment by sovok4** [comment]
Единственное, что действительно стоит осуществить - это доступ на мостик.

**Comment by igigin** [comment]
О, опять крики, что не дали валын.

Надо добавить ещё и ассистентам маслиномётов, чтобы не о чем кричать было.

**Comment by StrikS** [comment]
Все нормально с АВД,  в компенсацию за имплант его одели лучшие модельеры Таукиты, даже кейс понтовый подсунули. :peka:
Единственной неплохой идеей, по моему мнению, является выдача доступа на мостик.

**Comment by ZVee** [comment]
Вы опять ищите везде полезное и везде плюсы, уберите это из головы уже наконец. Должно быть что-то и вообще без цели какой либо, полезности или давать сплошные минусы и разочарование.

**Comment by StrikS** [comment]
Нет спасибо, мне моей жизни достаточно. :peka:
Игры должны приносить удовольствие.

**Comment by ZVee** [comment]
Удивлю - но есть те, кому нравится выше перечисленное мной и это дает больше удовольствия - чем это уже приевшееся и многими повторяемое "игры должны приносить _подставь_вариант_". Поэтому это все индивидуальное.

Считаю что у нас достаточно полезных проф и не очень полезных, нормальный баланс в общем.

**Comment by ZVee** [comment]
>почему у ИМПЛАНТИРОВАННОГО агента корпорации ее нет?

Потому что он наряду с гражданскими, но если уж так надо - можно сходить в бриг и попросить туже флешку (у хопа кстати планировали еган забрать или заменить на тазер, все забываем). В общем да, это не настолько проблема.

>Доступ в мед, техи(агент жы).

Что он там забыл?

>ИРЛ у всех оперуполномоченных

Это его когда уже успели приравнять к ним?

**Comment by StrikS** [comment]
>Удивлю - но есть те, кому нравится выше перечисленное мной и это дает больше удовольствия

А я то думаю чего к хопу идут только расширять доступ, а срезать никто, наверное просто лень. :peka:.

**Comment by ZVee** [comment]
>А я то думаю чего к хопу идут только расширять доступ, а срезать никто, наверное просто лень.

Вот это ты конечно настолько мимо написал, что мне даже интересно стало, как так надо выдумать не по теме текста на который отвечал.

**Comment by dearprincesscelestia** [comment]
М-м-м, класс. Предложения уровня "как я без ствола и бункера ролеплеить буду".

Канцелярская крыса теперь оперуполномоченный потому что инпламт стоит и повезло не сжечь мозг. Вкалываешь бухгалтеру инпламт, который шепчет, что капитан - величайший человек, и бухгалтер сразу умеет стрелять из лвапы с одной руки, так что ли?

В конце концов, идешь и просишь емаг в летальном режиме и фуласкет, если твое ер пе сильнее капитанского. А если капитан решает меряться аксцессом, а не ерпе - у тебя есть факс.

Касательно мостика: с одной стороны, там есть консоль связи с цека, поэтому агенту можно бы и ходить туда. 
С другой, там есть консоль связи с цека, которая является ультимейт желанной целью в куче ситуаций, и давать доступ незащищенному бюрократу, который стрелять не умеет и которого всякий норовит обидеть - класс. И второе перевешивает первое, а если использовать второе, чтобы выпросить и доступ на мостик, и ствол, чтобы доступ на мостик охранять, то чет как-то знаете, нет.

В общем, пропозал уровня мемов из оока, а еще мы выяснили, что штрикс павергеймер.

**Comment by Skippeer12** [comment]
Доступ в конференц зал глав и на мостик, флешка, доступ в командный канал вместо щиткуритронского.

**Comment by dearprincesscelestia** [comment]
Вот про канал хорошо и правильно.

**Comment by Raneman** [comment]
Подробное описание проблемы

Сейчас научперсонал - вторые инженеры, только с доступом к лимикам. Это лутшие учоные с ЦК, которые наравне с капитаносом являются целью существования станции, но на ревах/нюках их выпиливают, а у них него даже нет примитивных средств защиты.

Что должно было произойти

У рнд сразу должны быть адвансед энергетические пищали. Доступ в мед, техи(учоный жы).

Что произошло на самом деле

Этого всего нет

Как повторить

Зайти за саентиста и понять что он бесполезен

Дополнительная информация:

ИРЛ у всех саентистов есть мегавалыны и боевые человекоподобные мехи, почему у ЛУЧШИХ УЧОНЫХ КОПРОРАЦИИ их нет?

**Comment by dearprincesscelestia** [comment]
>  Это лутшие учоные с ЦК, которые наравне с капитаносом являются целью существования станции, но на ревах/нюках они выпиливают капитаноса, первыми присоединяясь к реве, и умирают от дубинок шитсеков.

Чуть фикс.

**Comment by RichardJones1** [comment]
По поводу доступа на мостик - нет, потому что карта АВД станет желанной добычей каждого ассистента. Да и зачем? А вот базовый доступ во все отделы нужен, дабы следить за соблюдением протоколов/работой сотрудников.

По поводу доступа в командный канал - идея хорошая, хотя стоит оставить доступ и в канал СБ.

По поводу оружия:
#2712

**Comment by RichardJones1** [comment]
Иииии, наконец то можно закрыть данный пропозал. Права АВД были подняты в данном ПРе:  #2894
Идея с доступом в главный канал и базовым во все отделы там реализована.

По поводу выдачи пушки АВД - никогда, ибо АВД - не исполнительный элемент, его задача следить за работой экипажа и докладывать на ЦК, ни в коем случае не стрелять. Флешку ему дал, потому что несмотря ни на что АВД всё таки важнон для корпорации лицо.

Всё, что можно было реализовать реализовал, остальное - полный абсурд. Закрываю.
