### ISSUE TITLE
[Proposal] Проблема с целью на мясо корги

### ISSUE THREAD

**Issue by QWxiZ** [TauCetiStation/TauCetiClassic#12817]
### Описание

У триторов есть простейшая цель, которая не подразумевает собой никаких телодвижений. Единственное, что нужно тритору сделать - подойти в карго, заказать там корги (цена на него небольшая - буквально две зарплаты инженера) и разделать его ближайшей стиральной машинкой. И все, что за это может получить тритор - 5 минут срока за "жестокое обращение с животными", которое даже не подразумевает конфискацию цели - то есть мяса..

Теперь вопрос.
А нахрена синдикату мясо случайного корги из магазина? Они что, сами не могут купить собаку?
А со стороны баланса? Действительно ли такая легкая цель имеет место быть? 

Предложение - уточнить, что мясо должно быть Яна.

**Comment by LudwigVonChesterfield** [comment]
думаю когда-то это и было мясо Яна.
