### ISSUE TITLE
Видимость труб сломалось после #12812

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#12826]
#### Что должно было произойти
Всё красиво
#### Что произошло на самом деле
Трубы зажили своей жизнью после тестмержа #12812 (@volas)
Пример сломавшихся труб.
Велосити:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/a0b4de9b-baef-418a-81b9-c3f5a3eb6227)\
Бокс ботаника:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/acf40c22-f89c-46e8-aa9d-61aa4f251c97)
Бокс мусоросжигатель:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/9aac8e0a-8fbb-4b24-a181-cfe31a12ffb5)
Бокс солнечные панели у отбытия(что-то с проводкой и трубами криво)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/0713d5d1-e94b-481e-88cd-959835d04bd1)
Астероид Науч:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/7ff18e4a-972c-4c33-94f4-44b3e8109f9b)

**Comment by volas** [comment]
visible трубы над стенами сейчас ожидаемо, а то что некоторая плитка не скрывает - это баг, да

**Comment by volas** [comment]
мусоросжигатель - маперы втф, кто додумался оутлет в стену вставлять

**Comment by volas** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/12812/commits/03ed42a36067c0b47f8569bf30c6e9391589086e

над стенами - когда-нибудь потом, после https://github.com/TauCetiStation/TauCetiClassic/issues/12824
