### ISSUE TITLE
Сломанные шедоулинги

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1282]
#### Подробное описание проблемы
1. Я за ШД заспавнился без одежды и абилок, точнее без ночного видения и крутых ШДшных термалов. Более того, я мог ( и мне пришлость) носить НОРМАЛЬНУЮ одежду как белый человек (гы)
2. Не появилось окошко для возвышения
3. При восстановлении хитина появлялись дополнительные окна для глаз, но они не работали
4. Когда для решения второй проблемы меня переделали шедуолингом (удалили антага и дали), то выпало три комплекта одежды ШД
#### Что должно было произойти
1. Нормальный спавн одежды
2. Возвышение
3. Восстановление хитина восстанавливает одежду ШД
4. Тут даже не знаю
#### Что произошло на самом деле
См. выше
#### Как повторить
Получить рольку ШД
#### Дополнительная информация:
http://imgur.com/wPWtVq9

**Comment by Shudyn** [comment]
На самом деле добавили нового ксеноса-антидиону, ты просто не шаришь.
Вообще, надо попробовать переродиться без одежды, мб из-за этого проблема, что не снялась старая, в итоге хитина и глаз нет.

**Comment by WallShrabnic** [comment]
При перерождении вся одежда снялась, тащем-та. Когда педали забрали и вернули шедоу, то при перерождении выпало три набора хитиновой брони, которую надеть нельзя и он невидима

**Comment by WallShrabnic** [comment]
Проверил на локалке, та же проблема. Вы убили моих шедоулингов

**Comment by ZVee** [comment]
@Kurshan  - https://github.com/TauCetiStation/TauCetiClassic/pull/1207/files#diff-bd8addc57db9e395a3207b90acedec2dR224 - из-за этого как минимум пострадали шедоулинги, как максимум - все те, кто носят/зависимы от абстрактных вещей. Правда не знаю, тобой ли это добавлено, но на тебе цепочка обрывается, предположу, что у тебя влиты были изменения прямо в коммит-синхронизацию и если это так - то не надо в будущем так делать, синхронизация должна содержать только разрешения конфликтов и саму синхронизацию.

**Comment by P-20** [comment]
Да, это Куршан добавлял если память не изменяет, вместе с фиксами генок

**Comment by Kurshan** [comment]
Чет короч, нужен отдельный битовый флаг на нодроп.  Сегодня на АБСТРАКТЕ и так много всякого, Ибо попытка их объеденить их как-то не увенчалась успехом. Займусь этим в ближайшее время.

**Comment by ZVee** [comment]
А как прок equip_to_slot() взаимосвязан с выкидыванием предмета на землю? Именно для этого NODROP и нужен и да, он у нас есть - называется canremove и содержится как переменная но работает на снятие из слотов одежды - т.е на руки он не дописан насколько я помню.
