### ISSUE TITLE
Дюп шклянок.

### ISSUE THREAD

**Issue by psebash** [TauCetiStation/TauCetiClassic#1284]
#### Подробное описание проблемы
При разборе слипера выпадает шклянка. Когда собираешь его назад шклянка в нем уже есть. Улавливаете смысл?
#### Что должно было произойти
При сборе шклянка не должна появиться внутри слипера опять
#### Что произошло на самом деле
Она появилась
#### Как повторить
Разобрать слипер на части, посмотреть на выпавшую шклянку, отодвинуть в сторону, собрать слипер, достать еще одну.

**Comment by Dennok** [comment]
Скорее она не должна выпадать, хотя ее вроде можно кнопкой вынуть, тогда да, новый построенный слипер не должен ее иметь.
