### ISSUE TITLE
Выпилите амогусов

### ISSUE THREAD

**Issue by Ke-nt0** [TauCetiStation/TauCetiClassic#12845]
#### Что должно было произойти
При единственном офицере на станции ему гарантировано не выпадет роль амогуса
#### Что произошло на самом деле
Ему выпала роль и он устроил смешную нарезку глав. 

### Шаги воспроизведения

1. Зайти на сервер в ожидании интересного раунда 2. Дождаться выпадения амогусов 3. Получить удовольствие от честного и сбалансированного режима

### Дополнительная информация:

Пожалуйста, выпилите амогусов. Я искренне не понимаю, как за вирусолога засунуть в колбу голову ГСБ, офицера и украсть ИИ без ИИ на станции и без аплинка.

**Comment by Deahaka** [comment]
Skill Issue

**Comment by Kiromaka** [comment]
Амогусы хуйня, но не по причинам описанной в пропузале.

24 часа на исправления.

**Comment by ZER0-In** [comment]
Жесть, козлик теперь тиранит даже на гитхабе.

**Comment by Venngedi** [comment]
#12850
