### ISSUE TITLE
В окошке настройки персонажа можно выбрать корпорацию

### ISSUE THREAD

**Issue by Raneman** [TauCetiStation/TauCetiClassic#1285]
#### Подробное описание проблемы
При настройке ролеплейного персонажа есть поле "Faction". В нем можно очень неролеплейно выбрать фракцию.

#### Что должно было произойти
На станции должны работать только сотрудники самой-самой лучшей корпорации в мире.

#### Что произошло на самом деле
Всякий космосброд оскверняет станцию своим присутствием и ссыт в лифтах.

#### Как повторить
Открыть окно настройки персонажа, убедиться что поле "Faction" кликабельно и содержит целую тонну фракций-ноунеймов.

#### Дополнительная информация:
Хайль НТ

**Comment by ZVee** [comment]
А вот это тот самый случай, когда есть смысл просто кинуть ссылку - https://baystation12.net/lore/Section-3

**Comment by dearprincesscelestia** [comment]
1. Пишешь туда "Синдикат Куберсан Мородерс", и тебя можно легально грефонить.
2. ????????
3. ПРОФИТ

**Comment by Shudyn** [comment]
Давно пора тырить беебэк, там и много, и красиво, не то что у нас, что хрен знает что и когда. Самим игрокам необходимо все додумывать для РэПэ.

Наш бэк состоит из дыр, еще пары дыр и немного текста.

**Comment by dearprincesscelestia** [comment]
> Самим игрокам необходимо все додумывать для РэПэ.

Но ведь это плюс. А беекбек куда-то не туда ползет, со своим "синдиката никогда не было".

**Comment by Shudyn** [comment]
> Но ведь это плюс. А беекбек куда-то не туда ползет, со своим "синдиката никогда не было".
Вместе с этим образуется куча несостыковок, к тому же.
Да и к чему полностью копировать его? Просто взять весь, переделать под наш. Все же хоть что-то будет, а не то, что у нас, которое сложно назвать бэком.

Фекшн можно не убирать, если посмотреть, что делать с бэком.

**Comment by Raneman** [comment]
> надо бы уже давно точку поставить в вопросе бека и лора
Галакси ньюз, сегодняшний выпуск:
"Капитан казнил АВД за то что тот был секретным агентом Нанотразен!"
"КСН Исход переименован в КС Безысход!"
"Организация Синдикат (запрещена на территории Галактики Млечного Пути) взрывает вообще всех без разбору!"
"ЕРТ перестреляли друг друга из-за политических разногласий ещё до подлёта к станции!"
"Корпоративный шпионаж процветает — учоный Петя украл у учоного Вити новейшие технологии прямо из протолата!"
"Во время пиратского налёта ИИ запутался в своих законах о том кому можно быть на станции, а кому нельзя, словил необрабатываемое исключение и убил вообще всех"
