### ISSUE TITLE
На плазме стоит надпись "форон", испорчен цвет плазмы

### ISSUE THREAD

**Issue by ghost** [TauCetiStation/TauCetiClassic#1286]
#### Подробное описание проблемы
1. Плазма повсюду называется "форон".
2. Плазма фиолетового цвета.
#### Что должно было произойти
1. Плазма или нигде не называется фороном, или в тех полутора местах, где было написано "био-токсин".
2. В коде сгорания нет комментариев о каком-то новом элементе, с учетом того, что плазма при сгорании дает це о два, а не оксид волшебния.
3. Плазма оранжевого цвета.
#### Что произошло на самом деле
1. Плазма называется фороном почти везде.
2. В коде какая-то антинаучная (что терпимо) неконсистентная (что ужасно) ересь.
3. Плазма фиолетового цвета.
#### Как повторить
Зайти на сервер, проэкзаминить кучу плазмавещей.
#### Дополнительная информация:
Тлетворное влияние новобеебека.

**Comment by ZVee** [comment]
Нет уж, добить остатки названий и все. Не надо снова назад. К тому же плазма явно не должна летать почти безобидно по станции в виде какого-то газа, и обычно ассоциация идет с мощнейшим явлением разрушительной энергии, так что уж лучше пусть форон.

**Comment by dearprincesscelestia** [comment]
Но ведь в том и дело, это всегда было идиотское название от журналистов, которое вошло в массы, а официально был биотоксин.

Ну и оксид форония вместо цеодва тоже ты напишешь в атмосферку?

**Comment by dearprincesscelestia** [comment]
А, это же еще не все.

**Comment by WallShrabnic** [comment]
Це О Два углекислый газ дурачёк

**Comment by dearprincesscelestia** [comment]
О Два кислород дурачка, и что? Или комментарий лишь бы оставить комментарий?

**Comment by Raneman** [comment]
ФОРОН

**Comment by Shudyn** [comment]
Даже в беке для таких написали, что 

> О переименовании плазмы в форон:
Никто не знает, как так получилось. Когда ученые описывали в отчетах токсичность нового вещества, бюрократы сразу присвоили ему название токсинов. Позже ученые говорили про добычу в экстремальных условиях и что-то про четвертое агрегатное состояние, и опять бюрократы так и записали - плазма. Ужасная ошибка.
И только сейчас, спустя пол века после открытия этого вещества, под напором нескольких поколений Галактического Союза Ученых и Исследователей бюрократический аппарат сдался и, наконец, справедливость восторжествовала.
После поданной 1034 по счету апелляции, обоснованной в 12 томах, Галактическое Бюро Наименований приняло поправку о переименовании "Плазмы", известной так же как "Токсины", в "Форон" (хотя некоторые ученые уверены в том, что бюро просто наконец то соизволило прочитать первоначальное обоснование первой апелляции в 32 страницах).
Научный мир ликует. Правда, теперь им предстоит еще добиться возвращения старого названия четвертому агрегатному состоянию, но это уже совсем другая история.

**Comment by dearprincesscelestia** [comment]
Переименовать ионизированный газ в форон.

**Comment by jarezzz** [comment]
Так форон больше смахивает на какое-то йобовое органическое соединение, так что при сгорании СО2

**Comment by dearprincesscelestia** [comment]
Оно и есть. Но в коде почему-то на полном серьезе был комментарий про А ЧТО ЕСЛИ ФОРОНИЙ ЕТО ТАКОЙ-ТО ЕЛЕМЕНТ ММ

**Comment by StrikS** [comment]
Да какая разница как он называется? Главное чтобы грифонил космонавтиков и горел хорошо. А фиолетовый цвет хорошо смотрится, это я как человек с фиолетовой пони на аватарке говорю.

**Comment by Motzord** [comment]
Можно закрывать?

**Comment by LudwigVonChesterfield** [comment]
Да в принципе да, вон есть пропозал на решение(который никому не нужен)
