### ISSUE TITLE
[топ пропозал] Три ИИ.

### ISSUE THREAD

**Issue by dearprincesscelestia** [TauCetiStation/TauCetiClassic#1287]
#### Подробное описание предложения
Увеличить число слотов для ИИ до трех.
#### Что сможет произойти
Оперативная реакция на крики "ИИ ДВЕРЬ", веселье.
#### Что происходит сейчас
Телектуальная система даже на процент не пользуется своими ресурсами
#### Как реализовать сейчас
1. В фан панели, что ли, есть кнопка.
2. Собрать еще два ИИ.
#### Дополнительная информация:
Давайте попробуем.

**Comment by ZVee** [comment]
Тут скорее проблема в 3-х "обсервах" по станции которые все палят, у ролек которые вынуждены и так играть в стелс, шансы еще более уменьшатся. Да и игровой метод уже есть, а кнопка - слишком халявная и само собой на нее будут набегать. Лучше лэйтджойн боргам ввести - вот этого реально не хватает.
Но в целом не знаю, давать на постоянную основу...

**Comment by dearprincesscelestia** [comment]
Ну, даже один ИИ в принципе не должен палить рольки, пока не прикажут, у нас даже в рекомендациях было вон: http://tauceti.ru/wiki/AI#.D0.A7.D1.82.D0.BE_.D1.81.D0.BB.D0.B5.D0.B4.D1.83.D0.B5.D1.82_.D0.B4.D0.B5.D0.BB.D0.B0.D1.82.D1.8C_.D0.98.D0.98

**Comment by ZVee** [comment]
Так я не про это, вот каков шанс забежать в обще обозреваемый отсек при одном и при трех + мимо пробегающих людей и иногда глядящих по камерам офицеров, ну например к хопу и просто отсечь ему голову прям там на виду с коридора и уйти потом?

**Comment by dearprincesscelestia** [comment]
> + мимо пробегающих людей и иногда глядящих по камерам офицеров

Из этой оговорки следует, что ненамного больше, я думаю, выигрыш от трех ИИ куда выше, чем проигрыш, - тут и обучать ИИ спокойно могут другие два, и можно отыгрывать одну личность втроем, и не дожидаться ухода другого ИИ в обсерве и конца своего респавна.

Плюс давайте будем честными. У нас один-то есть не всегда, так что три ИИ если и будут, то когда онлайн большой.

**Comment by ZVee** [comment]
Но ведь есть игровой метод и ничего не мешает построить дополнительных при том же большом онлайне. А еще - представим такую ситуацию - рольки выпилили И.И., он отсиделся до своего респавна и зашел снова... А так - только если его построят, однако это можно предотвратить.

**Comment by dearprincesscelestia** [comment]
Проблема с респавном стоит. Поэтому неплохо бы, если бы корпусы уже стояли.
А решать игровым методом проблему не очень логичной роли довольно странно, это как считать, что авд у нас оперуполномоченный и при этом бегать к хопу говорить "сер я же опер упал намоченный дайте мне бункер и ствол".

**Comment by ZVee** [comment]
Так мы у хопа ствол заберем, так что не отговорка (просто это давно было обсуждено, но например я забываю карту поправить, а остальные наверно в целом уже забыли про этом, и нет, это не шутка).

Проблема кнопки в том - что она дает слишком простой и не контролируемый доступ.

**Comment by Kilkalestia** [comment]
А как вы себе Малфа представляете с тремя ИИшками на старте?

**Comment by dearprincesscelestia** [comment]
> Так мы у хопа ствол заберем
Но разговор был про агента, а не хопа, хоп там для доступа в оружейку и бункер онли. Можно на хоса заменить или на кепа, у них тоже пушки отнимем и аксесс по станции?
> Проблема кнопки в том - что она дает слишком простой и не контролируемый доступ.
Там же можно в настройках онлайн слоты убрать. 

В конце концов, если будет хуже, уберем.

**Comment by ZVee** [comment]
>Но разговор был про агента, а не хопа, хоп там для доступа в оружейку

>и при этом бегать к хопу говорить "сер я же опер упал намоченный дайте мне бункер и ствол".

Но ведь сам привел этот пример, тем самым с подвигнул на него ответить и я читаю предложения от начала и до конца. Поэтому чтобы не выходило в диалоге разветвлений - надо очень конкретно быть в теме и не вилять на сторону, даже если очень хочется, по крайней мере со мной.

Мы тут ИИ и кнопку обсуждаем, значит все должно быть только про ИИ и кнопку и о плюсах и минусах этого, только надо правильно понять - "должно быть только про о". А если не делать этого - тема обычно во флуд превращается и уже все в итоге обсуждают совсем левое.

**Comment by Kilkalestia** [comment]
>Очень интрижно. Надо вычислять, какой из ИИ сломан и не врет.

То есть только один из них будет сломан? А боргота со старта кому подчиняться будет и как Малфу избавиться от явных помех в виде ещё двух ядер?

**Comment by dearprincesscelestia** [comment]
Проще на самом деле найти кого-нибудь, кто понимает как тебя, так и меня, потому что я тоже воспринимаю слова про отнять у хопа пушку как виляние почему-то, на лицо проблема коммуникации.

> А боргота со старта кому подчиняться будет и как Малфу избавиться от явных помех в виде ещё двух ядер?
Я думаю, боргов привязывать к малфу, чтобы минимально изменить баланс, и прописать им перед законами, что другие ИИ не знают о неполадке и бинарный канал небезопасен.

**Comment by Skippeer12** [comment]
Кто-то уже пытался портировать ИИ с новобея (или мне кажется), но вообщем там он хорошо реализован, правда раунды с ним занимают достаточно много времени на прокачку всяких скиллов помимо взлома АПЦ, которые нельзя починить.
Да и если хочешь больше чем одно ядро, просто просишь собирать эти самые ядра у ученых, после чего гостаешься и потом уже можно будет зайти за этот неактивный кусок метала другому человеку. Продолжаешь до потери пульса.
Да и зачем что-то делать, если это уже реализовано и тебе стоит всего лишь попросить.

**Comment by dearprincesscelestia** [comment]
Чтобы попробовать смены с потенциально тремя ИИ и собрать понимание, как это реально отразится.

**Comment by WallShrabnic** [comment]
Два нормальных ИИ со старта спалят сломанного и выпилят его

**Comment by dearprincesscelestia** [comment]
Это серьезная проблема, да, как малфу действовать, если изначально он не может открыто писать в бинарный канал. Возможно, больше будет зависеть от боргов малфа и их умения понимать намеки.

**Comment by Kilkalestia** [comment]
Во-первых да, у малфа отпадает возможность кооперации с борготой, а во-вторых малф будет тут же обнаружен через консоль РД другими ИИ.

**Comment by dearprincesscelestia** [comment]
М-м-м. Но делать всех ИИ малфами - наверное, слишком.

Добавить закон о непричинении вреда малфу и нераскрытии малфа - слишком искусственное ограничение.

Спавнить только один ИИ при малфе?

**Comment by Miracler112** [comment]
Всё равно, что сказать "Ей посмотрите, у нас малф, потому что другие ИИ неожиданно не появились" По мне так вся эта идея лишняя, если нужны будут другие ядра, то их могут построить вручную. А брать нового ИИ из гостоты это идея так себе, либо зайдет тот, кто на нем совершенно не умеет сидеть и будет намеренно всё портить, либо как всегда никто и не зайдет по сути.

**Comment by Raneman** [comment]
> Это серьезная проблема, да, как малфу действовать, если изначально он не может открыто писать в бинарный канал. 
и где проблема?
пусть пишет. а что такого.
если один напишет в 145.7 о том что ВОН ТОТ ДРУГОЙ ПРОГРАММА — МАЛЬФ, то и малф может написать то же самое, а единственная угроза малфу — космонавтики, так что пусть там соревнуются в обвинялках, а когда начнётся сам кипиш то уж плевать кто, код дельта, робастим обоих ИИ

**Comment by dearprincesscelestia** [comment]
>  А брать нового ИИ из гостоты это идея так себе

Брать нового ИИ из задеклерившихся же, вместе с основным.

> если один напишет в 145.7 о том что ВОН ТОТ ДРУГОЙ ПРОГРАММА — МАЛЬФ, то и малф может написать то же самое, а единственная угроза малфу — космонавтики, так что пусть там 

Проблема в том, что два ИИ против одного сомнений не оставят. А два малфа на одного не - не жирновато ли?

**Comment by Raneman** [comment]
два малфа на одного нормального кокрастыке самый смак будет, друг друга-то напрямую они не могут выпиливать, разве только борготой, но при этом эпатажном ходе экипаж может ЧТО-ТО ЗАПОДОЗРИТЬ

**Comment by dearprincesscelestia** [comment]
Тогда им надо будет механ, что победить может только один, что довольно странно, если ИИ самоуничтожается в конце.

**Comment by Shudyn** [comment]
Космонавты, лишь завидев синие АПЦ пойдут выпиливать и выкидывать в космос всех трех ИИ.
Вариант с одним малфом из трех ИИ вполне уместен, однако, единственной проблемой являются борги. Есть два варианта развития: с добавлением фичи, когда с начала раунда все борги подвластны немалфам, а самому малфу необходимо их взламывать, либо, оставить все как есть, разделяя всех боргов на малфа и немалфа. Вообще так-то, судя по законам, ИИ не могут вредить другим ИИ и боргам, так как это собственность НТ, да и очень дорогая. В их интересах будет минимизировать потери и разговаривать только с адекватными космонавтами, типа РД и СЕ, которые смогут что-то решить без применения силы, а то ведь в итоге законы будут нарушаться, что они не сохраняют имущество.

**Comment by dearprincesscelestia** [comment]
Это очень оптимистичный вариант. Было бы хорошо, если оно так развернется, но я сомневаюсь, что это будет хотя бы в половине случаев. Я, правда, не в состоянии чисто по времени смотреть за большей частью ИИ на сервере.

**Comment by StrikS** [comment]
Оба пропозала решаются просто просьбой педалей сделать 3 ИИ или дать тебе коробочку емагов. И порыв "давайте попробуем" будет удовлетворен.
