### ISSUE TITLE
Прослушка всех частот

### ISSUE THREAD

**Issue by QWxiZ** [TauCetiStation/TauCetiClassic#12872]
#### Что должно было произойти
Я вытащил из наушника ключ синдиката, надел его обратно и ПЕРЕСТАЛ слышать командный канал. Я на всякий случай даже СЖЕГ старый наушник и взял НОВЫЙ и поэтому я ПЕРЕСТАЛ слышать командный канал.
#### Что произошло на самом деле
А вот нихрена. Я вытащил ключ синдиката из наушника - я продолжаю слышать прослушку, только теперь без (Interecepted) в скобочках. Я сжег наушник и взял другой - все равно слышу, независимо от того, какой ношу. Только при этом не могу говорить в него на запретные частоты.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/143294254/f0f9bcc4-99b1-4e23-910f-e98e36e5c29c)

### Шаги воспроизведения

1. Купить прослушку [важно отметить, что моя прослушка была из набора тритора, который за 30 ТК].
2. Походить с ней.
3. Вытащить прослушку.
4. Сжечь чип прослушки.
5. Сжечь старый наушник.
6. Взять новый.
7. Услышать то, что не должен.

### Дополнительная информация:

Issue reported from  Round ID: 62874 (Tau Ceti Classic (RU))
Testmerges: ```#12408# 12676# 12830```
Reporting client version: 514.1589

**Comment by F0xiq** [comment]
Это не баг, у тебя от интелкарты c ИИ прослушка идёт, тоже замечал такое, вроде наушник не покупал, а коммандный слышу.

**Comment by QWxiZX** [comment]
Ох, это из-за вшитой в тело интелкарты с ИИ? Тогда ладно, извините, неловко получается. Неожиданный механ, впрочем.
