### ISSUE TITLE
[топ пропозал] Бесконечный емаг

### ISSUE THREAD

**Issue by dearprincesscelestia** [TauCetiStation/TauCetiClassic#1288]
#### Подробное описание предложения
Убрать лимит использований с емага. Возможно, поднять цену.
#### Что сможет произойти
Емаг будут использовать, чтобы фаниться и пробовать всякое.
#### Что происходит сейчас
1. Емаг используют практически исключительно для получения более удобного доступа
#### Как реализовать сейчас
Через ВВ.
#### Дополнительная информация:
Давно пора.

**Comment by dearprincesscelestia** [comment]
Да, мне лень ждать анфриза и делать ПР, у меня и так по глупости висит ПР в мастерветке, и спрайты для другого, и я боюсь запутаться.

**Comment by ZVee** [comment]
Слишком халявная открывашка будет, и цена не спасет. Есть вон дебаггер у пиратов (который можно дать всем остальным) и есть дуалки.

**Comment by dearprincesscelestia** [comment]
Дебаггер и дуалки не ломают бипского, не печатают культотомы, не позволяют заказать помаду и постеры в карго и так далее.

Альтпропозал - чтобы юзесы снимались при емаганьи дверей и шкафов онли.

**Comment by ZVee** [comment]
Потому что у нас прок емага не отрефакторен и везде стоит копипаста из-за которой чтоб хотя бы можно было в легкую выдавать любому предмету эффект емага - надо 1/3 билда перерыть.

**Comment by dearprincesscelestia** [comment]
Собственно, дуалсворд - это емаг только для дверей+дамаг.
А емаг будет емагом для всего, но без дамага. Баланс цен соответсвенно подправить, нет?

**Comment by WallShrabnic** [comment]
Сделать дополнительный емаг, который только с машинерией реагирует, а с дверьми и шкафами нет и имеет бесконечное использование

**Comment by dearprincesscelestia** [comment]
Или так.

**Comment by dearprincesscelestia** [comment]
А, еще чтобы кусачками по карте делалась сломанная карта со спрайтом емага, но это я точно когда-нибудь самостоятельно сделаю.

**Comment by ZVee** [comment]
Ну вы же понимаете что это приведет к тому - что купивший емаг, может пойти и просто емагать все налево и направо, задумайтесь о последствиях и инженерах - которым в какой-то момент надоест бегать и чинить в очередной раз все емагнутые консоли на станции и будут требовать шаттл. А может вам нравилось бегать по синим АПЦ при малфе и чинить их то тут то там? Некоторая техника теряет доступы, а это значит.. Ну в общем, фантазируйте.

**Comment by dearprincesscelestia** [comment]
Да, понимаем. Чем больше у рольки способа вредить и приводить к шаттлу, не убивая - тем лучше.

**Comment by ZVee** [comment]
Ну и получите в итоге то, что мы открутим кодом консоли вызова шаттла и воуты и оставим только на усмотрение педалей через факт там. Во вам весело будет после разрушений и поломок.

**Comment by dearprincesscelestia** [comment]
1. Зачем откручивать?
2. Какая разница, через консоль улетать при разрушениях и поломках или через факс?
3. Раунд с разрушениями и поломками веселее, чем без.

**Comment by ZVee** [comment]
Потому что если переиначить это предложение, то звучит оно следующим образом: а давайте введем предмет который позволит нарушать ~нулевое~ первое правило, ведь именно к этому он и дает в первую очередь доступ. К тому же если тебе уж так надо еще емага - можешь купить еще и зарядов там довольно много чтобы выполнить свою цель.

**Comment by dearprincesscelestia** [comment]
>  а давайте введем предмет который позволит нарушать нулевое первое правило

> можешь купить еще и зарядов там довольно много чтобы выполнить свою цель.

Ау. Мне емаг нужен, чтобы делать движ на станции, а не взломать десять дверей или шкафов.

**Comment by ZVee** [comment]
>Мне

А о других не подумал? А о том что вас, ролек, несколько? А о мимо-людях в рольках?

**Comment by dearprincesscelestia** [comment]
> можешь 
> можешь 
> можешь 
Какое предложение, такой ответ.

**Comment by ZVee** [comment]
Какой собеседник, такие и диалоги с ним, от тебя обычно шутеечки, флуд, несерьезное отношение ко всему, ересь в сообщениях чата игровых, а на гите этого терпеть долго не будем и просто молча тереть в след. раз начнем. Поэтому вот ответ такого рода как этот последний пост - не оставляй больше на гите, если нечего написать подходя серьезно к обсуждению.

**Comment by dearprincesscelestia** [comment]
Хорошо, тогда так:
> К тому же если тебе уж так надо еще емага - можешь купить еще и зарядов там довольно много чтобы выполнить свою цель.
См. текст пропозала, проблема именно в том, что емага хватает исключительно на выполнить цель.

Я могу попросить впоследствии не использовать "нет ты" как также не способствующее серьезному обсуждению?

**Comment by ZVee** [comment]
Посмотри, почти все предложения не содержат форму обращения к конкретному лицу, да и в целом стараюсь именно так их составлять, но когда мне начинает казаться, что собеседник думает только о личной выгоде, мои предложения меняются.

А так да, но к любым предложениям надо подходить как к работе и быть готовым вести долгий диалог который затронет все мелочи, ситуации, плюсы и минусы, дабы потом если уж и жалет, что это что-то ввели - было более комфортно.

В данном случае, у меня задача склонить к тому, чтобы от предложения последовал отказ, но если таки его нет - значит человек продумал все те мелочи, которые возникли у меня в голове. А в голове у меня обычно шахматная война, но всю ее не вываливаю за раз и слежу за реакцией на ответы описывая ситуации.

---

Вспомнил, есть же карта агента (ее ведь не убрали из покупки?), вот она и может стать бесконечным емагом (причем который не оставляем поломок), но для этого надо постараться.

Предвижу ответ вида - емаг же ломает в этом и суть, ну, можно ввести тогда предмет с бесконечным кол.вом заряда и который ломает (но не открывает и не дает доступа).

**Comment by dearprincesscelestia** [comment]
Емаг без поломок и одновременно измение имени и должности и сканирование доступа? Это не слишком ли хорошо, учитывая, что нюкеры с ним стартуют?

**Comment by ZVee** [comment]
Не имел ввиду склеивать карту агента с емагом (правильно понял тебя? если нет, то вот мысли еще), а то, что этот предмет почти никто не покупает, а ведь он несет функцию копирования доступа:
* Можно с ним пробраться в капитанскую используя емаг и снять доступ (обычно тырят карту, а тут ее можно не тронуть и это как минимум возможно заставит думать игроков расследующих взлом иначе, а еще ты не палишься с этой картой учитывая ее функционал переименования (она же все еще выглядит как обычная, ну та что в аплинке? Хотя можно в ПДА засунуть еще).
* Можно подкараулить апатика и снять доступ (но это рандом дикий и апатик может не с тем доступом оказаться).
* Можно главу со парапеном поймать где-нибудь в техах и снять карту для копирования и положить обратно что дает по сути ситуацию того, что с жертвой ничего не произошло, а значит и доносить нечего (ну или придумай свой вариант как можно поймать главу чтобы скопировать доступ).

Есть еще вариант насчет емага - заменить заряды шансом.
* Емаг стартует с переменной шанса на поломку в виде 0, с каждым юзом мы прибавляем по единичке например и это число и будет тем процентом, с которым ты рискуешь потерять емаг.
* Емаг стартует с постоянным шансом на поломку, скажем 10%.

**Comment by dearprincesscelestia** [comment]
М-м-м, беда в том, что агенткард вместо емага опять остается для доступа онли, просто чуть гибче (Да, в аплинке она выглядит как карта на станции), емаг все так же слишком ограничен для того, чтобы применять его не для доступа, вариант безобидно гадить по мелочи все еще не вариант - себе дороже.

**Comment by dearprincesscelestia** [comment]
Сейчас пришло в голову:

> Предвижу ответ вида - емаг же ломает в этом и суть, ну, можно ввести тогда предмет с бесконечным кол.вом заряда и который ломает (но не открывает и не дает доступа).
Если ломание это не ломание дверей в нерабочее состояние, а именно те эффекты от емага вроде бипски, агрящегося на всех, рабов-АПЦ и так далее, то вот же он: https://github.com/TauCetiStation/TauCetiClassic/issues/1288#issuecomment-288322772

И да, это тоже вариант. И вполне хороший.
Сначала показалось, что там агенткард-как-емаг-который-не-ломает - в смысле, открывает двери, не ломая их.

**Comment by ZVee** [comment]
Если увеличить кол.во зарядов раза в полтора от текущих например? Это решает проблему или суть идеи о бесконечных зарядах в том, чтобы творить хаос по всей станции?

Просто реально боюсь, что у нас в итоге каждый раунд с рольками у которых емаги, превратится в какие-нибудь непотребства, да те же открытые аирлоки настежь по всей станции и хорошо, если разгерм не появится.

**Comment by dearprincesscelestia** [comment]
Тогда вариант с дополнительным емагом без дверей и шкафов, чтобы аирлоки не ломали/емагом, тратящим заряды только на двери и шкафы.

**Comment by Skippeer12** [comment]
Лучше бы вместо переделываения старых вещей под новый лад, добавили новые вещи с вашей механикой.
Тот же дебагер можно было бы добавить в аплинк и сделать его дороже обычного емага.

**Comment by dearprincesscelestia** [comment]
> Лучше бы вместо переделывания старых вещей под новый лад,

Но ведь бесконечный емаг - это кокрастыке старый лад.

**Comment by Skippeer12** [comment]
Ну ведь не спроста забрали у него эту бесконечность.
Карта, открывающая двери без дебафов, взламывающая всё до чего может дотянутся космонавт без того же дебафа. Даже банальной задержки на использования нет.

Дебагер в этом плане лучше, там и задержа и тот же взлом, и то чего ты так сильно желаешь, бесконечность.

**Comment by dearprincesscelestia** [comment]
Дебаггер может взломать АПЦ? Бипского? Консоль связи с синдикатом? Консоль шаттла?

**Comment by ZVee** [comment]
>Дебаггер может взломать АПЦ? Бипского? Консоль связи с синдикатом? Консоль шаттла?

Я ведь уже ответил на этот вопрос, что сможет, но для этого надо рефакторнуть код емага и отвязать хардкод от предмета /obj/item/weapon/card/emag из-за которого и невозможно выдать эффект ничему другому. Поэтому причине дебаггер и вышел именно таким, а не полноценной заменой емагу, т.к мне было лень рефакторить тогда код.

**Comment by dearprincesscelestia** [comment]
Это был очень тонкий вопрос Шикпперу, чтобы натолкнуть его ход мыслей на то, что позволяет текущая ситуация и что не позволяет (и что неплохо бы прочесть предыдущие комментарии).

**Comment by ZVee** [comment]
А, ну тогда извиняюсь, но в общем да, тут как бы тут проблема кода у нас, которую мы постоянно решаем. И да, кстати, дебаггер бы подошел к разрешению этого пропазала?

**Comment by dearprincesscelestia** [comment]
Ну, мне довелось смотреть, как устроен код емага, потому что первая моя мысль была "сделать отдельный счетчик, чтобы ломать бипских можно было тысячами, а двери  и ящики с пушками как сейчас", и мне стало грустно. Поэтому предлагать рефакторить дебаггер я не считаю себя вправе. Но технически - скорее всего да, там разве что контрметагейм с "да у него какая-то карточка поломанная, офицер, вы дурак что ли, отпускайте" перестанет работать.

**Comment by dearprincesscelestia** [comment]
С другой стороны. Как раз ограниченный емаг можно пронести под носом, если не использовать на глазах, а неограниченный дебаггер явно нелегальщина - все правильно.

**Comment by conartist11** [comment]
Почему вообще поднимается тема емага-люди хотят весёлых и интересных антагов. 
Определяемся с назначением емага. Либо >открыть кабинет и шкаф отсутствующего СМО/СЕ, взять штаны, улететь/стабильно каждый раз открывать три двери в капитанскую и брать фулацесс после которого все емаги, дебаггеры, красные тулбоксы-устаревшие технологии. Либо >уникальное антаговзаимодействие с миром, всякие взломанные бипски бегают, находишь чем заняться людям, а не инженер и детектив уже уставшие от этого дерьма молча закручивают дверь в телепортную и берут отпечатки и идут дальше гулять. (Ещё надо постепенно прикручивать больше емагабельных вещей, да)
3)Аргументы против-не очень. Два-три раунда минимум было за историю сски со старым емагом и это только у нас, описанных проблем не возникало, расписывать каждой опровержение конечно мм, двадцать страниц флуда выйдет. Конечно емаг всё равно выбрасывался и заменялся на золотой билет на шоколадную фабрику и пранки с ним устраивали полтора человека и героин на камеру но тут проблема в умах, а не в коде, над этим уже работают. 
б) отдельный пранк емаг
плюсы-не лучший, но всё же способ дать игроку понять что карточка не только на двери работает и что нужно какое-т овеселье наверное ещё. Можете ужесточать серьёзный огрызок для дверей как хотите тогда, перейдут на отвёртку с кусачками или с4 в капитанскую. 
минусы-какое-то наказание для игрока за что что он хорошее дело хотел-то, в антага в духе антагов а не в машину для магбутов в шкафу. ТК лишние отбирают, подают как опцию для дурака и нечто опциональное, экипаж серьёзно не воспринимает, коллеги смеются, тычут пальцем, разнообразный манящий арсенал из аплинка на глазах становится ещё менее доступным.
Силы ещё в этот обмылок вкладывать, пилить, заделаете месиво как емаг сейчас и не избавимся потом. 
Эпилог. Подход к игре неправильный вообще, прежде всего опять же у нас не балансы имба кто победит а антаги смешные бегают активно пакостят, экипаж реагирует, взаимодействует. Одно для другого служит дабы создать лучший експериенс, не наоборот. Шутеек и флуда не боюсь, потрёте, как дискуссию закончите всё равно.  Вы сами вон не то обсуждаете, да

**Comment by Olt1771** [comment]
Я просто читаю коммиты и охуеваю, один охуеннее другого. Ты о балансе подумал, ты продумываешь что будешь делать НЕ ТОЛЬКО ты, а другие егроки? Ты же думаешь сугубо о себе.

**Comment by jarezzz** [comment]
Только хотел написать про Ольта и бесконечный емаг...
