### ISSUE TITLE
[дисакашон] На станции произошла эскалация вооружения при конфликтах

### ISSUE THREAD

**Issue by dearprincesscelestia** [TauCetiStation/TauCetiClassic#1289]
#### Подробное описание проблемы (проблемы?)
На станции слишком легко достать убийственное оружие (мне кажется), слишком много огнестрельного оружия и источников его получения в принципе, слишком мало отличия между отдельными видами.
#### Что должно было произойти (как мне кажется)
Смерть - да, часть игры, рольки - да, могут убить, и с ними могут вступить в смертный бой, но большая часть смертей происходит в результате импровизации.
#### Что произошло на самом деле
У нас есть автоматы в оружейке, ЛВАПы в карго, полная мусорка пушек, нюкеры с противотанковыми винтовками и пулеметами.
#### Как повторить
Наблюдать за развитием станции несколько лет.

**Comment by WallShrabnic** [comment]
Достань мне оружие за уборщика

**Comment by dearprincesscelestia** [comment]
В техтоннеле мусор @ просишь лопату @ везение @ пушки. Но вопрос в том - нам правда нужны ЛВАПы у шитсеков?

**Comment by WallShrabnic** [comment]
И да, на станции не так уж и много оружия в мирное время, только в оружейке, а всякие ревы и объявления войны в расчёт не берем. И всё оружие имеет уникальные признаки и фичи

**Comment by dearprincesscelestia** [comment]
Ну я вот с трудом вижу последнее. Может, кто-нибудь расскажет, какая у какой пушки ниша?

**Comment by WallShrabnic** [comment]
>Если человек дурак, то это надолго

**Comment by dearprincesscelestia** [comment]
Классно. Видимо, под уникальными признаками и фичами понимался все же спрайт и чутка другие цифры.

**Comment by Dennok** [comment]
А еще снайперка нюкеров стреляент через стены, и окна, дамажа их конешно, но простреливая. И вообщето в основном это винтовка против мехов, она убивает пилота меха.
А так то да, разные циферки, сложности ображения, кол-во патронов, дамаг, тип атаки.
А что ты хотел?
Предложи какие отдельные фичи для разных оружий ты можешь придумать?

**Comment by igigin** [comment]
Выпилить весь бриг со всей этой охранной чушью.

**Comment by Dennok** [comment]
Тагда уж давай сделаем станцию в один большой квадратный отсек, а в центре будет сидеть кэп с кепганом.

**Comment by igigin** [comment]
Почему квадратный?

**Comment by dearprincesscelestia** [comment]
Если свосем-совсем спрашивать меня, то там будет вообще целых различия и три пушки:
Размер: дробовик (не лезет в сумку) и все остальное (обрез входит во все остальное, все остальное лезет в сумку).
Тип оружия: энергетическое (еган, два режима) и баллистическое (револьвер и дробовик, какие патроны сунешь, такие и есть).
В патроны сделать там дорогие пробивающие стены снаряды, дешевые пластиковые и так далее, дробовику вон тоже разные уже есть.

Но на такое разумеется никто тут не пойдет (к сожалению). а с Куршаном на днях подняли вопрос об автоматах, он очень хочет спрайтов, а пушек у нас реально много, Вальтер не притронулся и к половине, а я вон вообще считаю, что их и столько сколько есть не нужно - это так, экскурс в причины ишшуе-дискашшена.

**Comment by Dennok** [comment]
Хм, разные типы патронов это да, идея. Хотя для обычного огнесмтрела есть резина и обычные патроны. Накодить еще 5 видов,
А потом еще накодить оружие судьи дреда, которое будет юзать все типы патронов.

**Comment by dearprincesscelestia** [comment]
Ну так оставить два калибра: дробовиковый и пистолетовый, и каждому типы. Размер магазина вон тоже сделать фичей, портировать с теге очереди можно.

**Comment by Miracler112** [comment]
Я хотел было опять написать что-то отрицательное, но вы подали мне идею для модификаторов разного гана. Худы, приклады, модули и всё в таком духе

**Comment by Dennok** [comment]
Для автомата нужен отдельный калибр. Также можно сделать чтоб нюкеры юзали еще 3й калибр.
Ну или взять идею из Шэдов Рана, там все оружие юзает универсальные магазины, какоето больше какоето меньше.

**Comment by dearprincesscelestia** [comment]
А нужен ли? Пистолет-пулемет сделать с пулями как у пистолета, и все.

**Comment by Skippeer12** [comment]
Проблема пушек в том, что автоматы и пистолеты сейчас по механике одинаковые, только спрайт другой, урон и количество боезапаса.

А всего то стоит автоматам добавить  автоматический огонь, огонь очередью.
А на счёт того что оружие достать легко, такое себе. Пойди в техи@ЕСЛИ ТЕБЕ ПОВЕЗЕЛ@Стреляй.
Ну а что делать если не повезло?
Сейчас есть два способа достать оружие, карго и РнД.
Но в карго оно закрыто в ящике, для которого нужен доступ либо офицера либо главы.
А в РнД нужны ресурсы, которые никто, никогда не принесет.

**Comment by dearprincesscelestia** [comment]
> Но в карго оно закрыто в ящике, для которого нужен доступ либо офицера либо главы.

Либо кинетический акселератор, который есть в карго. Либо лопата. Причем последним способом можно достать прямо-таки любую пушку.

**Comment by Skippeer12** [comment]
Про акселераторы знали единицы, до каких то там пор.

Аутировать в мусорк?
Тот же вопрос, а если не повезет? Так даже если и повезет, не факт что пушка не ёбнет у тебя в руках.

Ну а если тебе уже робастят каждый раз этим оружием из карго и РнД, то есть вариант и он очень прост.
Возвращаешь локбоксы с ТГ.

**Comment by SpaiR** [comment]
>Форум (общение) — **место** (площадка) **для общения и споров** людей **на различные темы жизни**; также — собственно сам процесс общения. ©Википедия

Вам для дискашнов отдельную площадку выделили, специально для этих дискашнов предназначенную. Вот там их и проводите. На гите обсуждаются конкретные вопросы по билду, а не концептуальные мысли на тему того, какой должен быть геймплей.

**Comment by dearprincesscelestia** [comment]
>  Ну а если тебе уже робастят каждый раз этим оружием из карго и РнД, то есть вариант и он очень прост.
> Возвращаешь локбоксы с ТГ.

И это ничего не меняет, потому что у нас все еще много пушек сомнительной разницы в игре не про пушки
