### ISSUE TITLE
Газ риперов Нар-Си не работает

### ISSUE THREAD

**Issue by raduser** [TauCetiStation/TauCetiClassic#1290]
#### Подробное описание проблемы
Паралитический газ риперов должен укладывать существ, даже если у них включен интернал. Но этого не происходит.
#### Что должно было произойти
Он должен парализовать существ.
#### Что произошло на самом деле
Не парализует.
#### Как повторить
Зайти за рипера и пустить газ.

**Comment by Dennok** [comment]
А почему он должен парализовать даже если включен интернал?

**Comment by raduser** [comment]
Потому что такова была задумка.
Молекулы газа нар-си настолько малы, что просачиваются через поры в дыхательной маске и парализуют моба.
А если серьезно, то на это пофег, главное, что газ не работает. Вообще, я подумал, что надо бы их апнуть, ибо слабоваты.

**Comment by StrikS** [comment]
У них бесконечный спавн из Нарси. Куда сильнее то? И бегут все к отбытию, чтобы грифонить экипаж. В 3ем спокойно кладут космонавтика в риге.

**Comment by Dennok** [comment]
Главная проблема риперов- спавн в запертом помещении.

**Comment by StrikS** [comment]
Ее нет, гост и снова клик по Нарси, а она всегда движется от цели к цели.

**Comment by dearprincesscelestia** [comment]
Пусть разъедает маски же.

**Comment by raduser** [comment]
А газ-то работает, видимо мне ночью приснилось, что он не работает.
