### ISSUE TITLE
Полное пропадание зрения во сне или исполнение мечты Людука?

### ISSUE THREAD

**Issue by maleyvich** [TauCetiStation/TauCetiClassic#12905]
#### Что должно было произойти
во сне хоть чето видно
#### Что произошло на самом деле
полностью чёрный экран...

### Шаги воспроизведения

1. Нажать IC -> Sleep
2. Вуаля, ПОЛНОСТЬЮ чёрный экран.

### Дополнительная информация:

Issue reported from  Round ID: 62972 (Tau Ceti Classic (RU))
Testmerges: ```#12891# 12408# 12676# 12835# 12837# 12839# 12893```
Reporting client version: 515.1630

**Comment by Slavik2001** [comment]
Фича :D

**Comment by ZER0-In** [comment]
Не надо такой фичи D:

**Comment by volas** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/12891/commits/bf2851e9e1c458f2367d6eb512b34e0f627b9296

прости, людук
