### ISSUE TITLE
Шахтерские мезонки не работают как мезонки

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#12906]
#### Что должно было произойти
Шахтерские мезонки просвечивают скалы на астероиде
#### Что произошло на самом деле
Шахтерские мезонки не просвечивают скалы на астероиде.

### Дополнительная информация:

Вероятно из-за #12891

**Comment by Slavik2001** [comment]
> Что-то ПР Волоса много наломал дров
Ожидаемо, учитывая на что был нацелен тот ПР

**Comment by volas** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/12891/commits/07f5321f4710f2e84f70525057e0e3af6c91dfff
