### ISSUE TITLE
Navigation Beacon unexisted icon issue

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#12922]
#### Что должно было произойти
https://github.com/TauCetiStation/TauCetiClassic/blame/87e4ec91dcaecdde013674827b8b8df7b26e3d4e/code/game/machinery/navbeacon.dm#L55
и https://github.com/TauCetiStation/TauCetiClassic/commits/master/icons/obj/objects.dmi должны давать картинку
#### Что произошло на самом деле
![aastoroid](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/91e038f6-139f-4e35-bab0-4547226b1f1f)

### Шаги воспроизведения

1. Зайти на сервер
2. ПКМ-нуть место где стоит навигейшен бекон.

### Дополнительная информация:

Кто будет фиксить, обновите спрайт до TG-шного заодно https://github.com/tgstation/tgstation/pull/74603

**Comment by KatoMarika** [comment]
Пофикшено в #13417
