### ISSUE TITLE
Подскользнулся об мыло на столе

### ISSUE THREAD

**Issue by psebash** [TauCetiStation/TauCetiClassic#1292]
#### Подробное описание проблемы
Кравлю такой под столом и скольжу по мылу, которое на столе
#### Что должно было произойти
Не должен скользить
#### Что произошло на самом деле
Скользил
#### Как повторить
Положить мыло на стол и закравлить под этот тайл

**Comment by omejka** [comment]
Не шарю в коде,но мне кажется это будет сложно зафиксить
>корридоры полностью в мыле
>извилистый мост,состоящий из столов
>идешь на walk чтобы не оступиться и не упасть на мыло

**Comment by Lancer411** [comment]
Если слой моба ниже слоя мыла, то не скользим на мыле. Можно кравлить под мылом.

**Comment by psebash** [comment]
Еще раз затестил, все верно, если слой моба ниже слоя мыла, то все равно скольжу
