### ISSUE TITLE
Пикетный знаки больше не отображаются в руках

### ISSUE THREAD

**Issue by hwat1204** [TauCetiStation/TauCetiClassic#12930]
#### Что должно было произойти

в руках космонавтика торчит заметный постер
#### Что произошло на самом деле

Ничего не видно

### Шаги воспроизведения

1: сделать пикетный знак

2: взять в руки

**Comment by KIBORG04** [comment]
Критический баг

**Comment by KIBORG04** [comment]
@NinjaPikachuska Почему такое могло произойти?
