### ISSUE TITLE
Паук (мертвый) не виден на фото

### ISSUE THREAD

**Issue by dimelion** [TauCetiStation/TauCetiClassic#1293]
#### Подробное описание проблемы
При снятии снимка с фотоопората, и при просмотре оного, пишется о наличии снятого обьекта (паука), но не видно модельки
#### Что должно было произойти
Сфотографировал паука (мертвого), посмотрел на фото, увидел паука
#### Что произошло на самом деле
Сфотографировал паука (мертвого) посмотрел на фото, не увидел паука
#### Как повторить
Сфотографировать мертвого паука, посмотреть фото
#### Дополнительная информация:
Лог о пауке при просмотре фото выходит, но самого паука на фото нет

**Comment by igigin** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/1204
