### ISSUE TITLE
Неправильные инвр иконки дискет.

### ISSUE THREAD

**Issue by ZER0-In** [TauCetiStation/TauCetiClassic#12938]
#### Что произошло на самом деле
Раундстартом имеют стандарт фуллтайл спрайт, пока не потрогаешь.
(Маленькие дискеты, те, что потрогали, большая - раундстартом).
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/57403011/00d10ebe-847f-403c-a06b-66d407ac0c59)

**Comment by ZER0-In** [comment]
спрайт лабел
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/57403011/25ee1f3f-cfe2-4d6a-94d7-76067f602427)

**Comment by Slavik2001** [comment]
А... Да, знаю, решу.
