### ISSUE TITLE
BIG диски

### ISSUE THREAD

**Issue by Classical-User** [TauCetiStation/TauCetiClassic#12943]
#### Что должно было произойти
Диски нормального размера
#### Что произошло на самом деле
Диски изначально не нормального размера

### Шаги воспроизведения

Мои предположения что это раундстартовый баг, так как после взятия и переложения дисков они становятся нормальными:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/114824435/97d9a923-af4d-4806-b51f-146a8e943716)

### Дополнительная информация:

Issue reported from  Round ID: 63075 (Tau Ceti Classic (RU))
Testmerges: ```#12408# 12823# 12836# 12887# 12914# 12919```
Reporting client version: 515.1633

**Comment by Slavik2001** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/12938

Дубль, знаю, исправлю
