### ISSUE TITLE
Не отображается спрайт компьютера по отсылке гробов на дереликте

### ISSUE THREAD

**Issue by jarezzz** [TauCetiStation/TauCetiClassic#1294]
#### Подробное описание проблемы
Компьютер есть, а спрайта нет
https://puu.sh/uWZEB/dcd5247789.png
#### Что должно было произойти
Должен был быть виден компьютер
#### Что произошло на самом деле
Спрайт не видно
#### Как повторить
Прилететь на Дереликт в церковь

**Comment by Dennok** [comment]
Еще проблема у компа створок синдиката на шаттле.
