### ISSUE TITLE
Освещение

### ISSUE THREAD

**Issue by Morkleb** [TauCetiStation/TauCetiClassic#12953]
### Описание

По словам одного админа было переработано освещение, теперь для таяр некоторые участки на станции при переходе на ночное зрение становятся абсолютно черными и непроницаемыми для зрения.

### Шаги воспроизведения

1 - Зайти таярой в теха или на астероиде в тёмный участок с выключенным освещением.
2 - Убедиться что свет поломан.

### Дополнительная информация:

![Desktop Screenshot 2024 03 14 - 16 12 18 72](https://github.com/TauCetiStation/TauCetiClassic/assets/110617703/8492af8f-fd3d-41ab-9554-f5e6a99862c1)

**Comment by volas** [comment]
это сейчас? я это фиксил, странно

**Comment by Morkleb** [comment]
Прошлый раунд.
