### ISSUE TITLE
Перелезание через закрытые шлюзы хуманами с мутацией халка убивает их

### ISSUE THREAD

**Issue by Kurshan** [TauCetiStation/TauCetiClassic#1295]
#### Подробное описание проблемы
При форсировании халком шлюза при "прыжке" он умирает
#### Что должно было произойти
Халк не должен умирать
#### Что произошло на самом деле
Халк умер
#### Как повторить
Попытаться открыть шлюз
#### Дополнительная информация:
throw_at с недавнего времени наносит дамаг в зависимости от скорости полёта 5 * throw_speed. Подозреваю (на самом деле более чем уверен), что значение скорости установлено достаточно большое. Кто-то должен заменить этот прок на forceMove

**Comment by Dennok** [comment]
при форсмуве он будет тпшитса. Может убрать перепрыгивание, а чтоб он держал дверь открытой пока он не отойдет?

**Comment by ZVee** [comment]
ФорсМув или любой другой метод простой смены локации не подойдет, "бросок" тут служил для физического перемещения - если на точке выхода кто-то или что-то мешает, то халк в это что-то влетит и останется либо между дверьми в итоге, либо даже через двери не пройдет, если и там стена вдруг окажется.
Так что тут надо на движение заменять и делать наверно теперь костыль в виде пары гет_степов (нам нужно два турфа пройти - дверь и турф за ней)/ степов или еще чего, ну или с броском что-то делать.

**Comment by Avatar4** [comment]
Так вот что со мной однажды случилось! К слову, при мутации халка с помощью магии, происходит такая же хуйня: Отрывает руки/ноги, наносит охуенный дамаг и мгновенно убивает. Однако сработало не сразу.
