### ISSUE TITLE
ЕЩЁ ОДНА ПРОБЛЕМА РЕПЛИКАТОРОВ: Ковры дают бесконечное количество ресурсов

### ISSUE THREAD

**Issue by hwat1204** [TauCetiStation/TauCetiClassic#12969]
#### Что должно было произойти

репликатор способен поглотить ковёр как обычную плитку

#### Что произошло на самом деле

ковёр можно поглощать бесконечно

### Шаги воспроизведения

1: стать репликатором

2: начать поглощать ковёр

**Comment by volas** [comment]
закрываю в пользу того ишью, починил в https://github.com/TauCetiStation/TauCetiClassic/pull/12984
