### ISSUE TITLE
Не работает особка где спавнишься зеком раундстартом

### ISSUE THREAD

**Issue by Leprekeoner** [TauCetiStation/TauCetiClassic#12966]
#### Что должно было произойти
Спавн зеком раундстартом
#### Что произошло на самом деле
Мне выпала особка на зека раундстартом, я выбрал ассистента и прожал реди, но стал обычным ассистентом

### Шаги воспроизведения

Получить особку на зека, нажать реди

### Дополнительная информация:

Issue reported from  Round ID: 63131 (Tau Ceti Classic (RU))
Testmerges: ```#12408# 12823# 12836# 12887# 12914# 12919# 12950```
Reporting client version: 515.1632

**Comment by Leprekeoner** [comment]
Не баг, надо подопытного выбрать. Закрываю.

**Comment by KIBORG04** [comment]
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/26389417/1730ff3c-c823-4676-a2e8-f3b3488c0d76)

Кто такой подопытный, если написано "Test Subject" ?
