### ISSUE TITLE
Заменить/пофиксить химические раздатчики в химии

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1299]
#### Подробное описание проблемы
Химические раздатчики в химии не являются машинерией (их нельзя улучшить), при этом у учёных в фабрикаторе плат есть  Portable Chem Dispencer, который можно свободно улучшать и получать дополнительные реагенты
#### Что должно было произойти
Возможность улучшить раздатчик в химии и получить доп. реагенты, чтобы сварить ~кифоторин~ меднаноботов
#### Что произошло на самом деле
Нельзя улучшить (по крайней мере, с помощью Bluspace RPED)
#### Как повторить
Попытаться помочь химику за учёного
#### Дополнительная информация:
N/A

**Comment by Dennok** [comment]
Так задумано.Было.Когдато.

**Comment by Raschert0** [comment]
Они по выбору реагентов лишь немного уступают портативному с Т4 деталями. И доступны с начала раунда. Так какой результат должен быть от их улучшения?

**Comment by Shudyn** [comment]
У нас химические машины из энергии собирают вещества. Портативный на то и портативный, что можно переносить, а это стационарный. Соответственно, переносить этот будет нельзя, но и вещества должны быть посложнее при улучшении. Там уже сразу , допустим, на т4 клонксадон уже должен быть, оксикодон. На т2 добавить какой-нибудь инапровалин или диловен.
Чтобы было проще распределить химикаты, можно считать по количеству преобразований.

**Comment by Dennok** [comment]
Портануть гкнохимию, там можно сразу смеси делать.
