### ISSUE TITLE
Невидимая створка в комнату с алтарем.

### ISSUE THREAD

**Issue by ZER0-In** [TauCetiStation/TauCetiClassic#13015]
### Шаги воспроизведения

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/57403011/e4ecadc5-d030-4c5d-bc19-7a38b5e7354d)

**Comment by LudwigVonChesterfield** [comment]
они все невидимые пока не откроют

**Comment by MarcusFrei** [comment]
Я знаю в чем баг, когда срабатывает ивент на сломанные шлюзы, эти жалюзи алтаря тоже считаются за двери и они ломаются
