### ISSUE TITLE
!!Копьем нельзя разрезать пиццу!!

### ISSUE THREAD

**Issue by ZER0-In** [TauCetiStation/TauCetiClassic#13017]
#### Что должно было произойти
Можно. Ведь даже шприцом можно порезать пиццу.
#### Что произошло на самом деле
Нельзя...

### Шаги воспроизведения

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/57403011/879b6121-b262-4564-9911-374be5113ee5)

**Comment by LudwigVonChesterfield** [comment]
баг в том что шприцом можно

копьё же колящее а не режущее.

**Comment by ZER0-In** [comment]
> баг в том что шприцом можно
> 
> копьё же колящее а не режущее.

Ну просто я посчитал то, что раз осколком можно разрезать, то почему бы и наконечником копья - нет? Если там все настолько замудрено, то можно ниче не менять.
