### ISSUE TITLE
[Bug] Пропал фолов за "глазом" ИИ из обсерва и орбита 

### ISSUE THREAD

**Issue by Smalltasty** [TauCetiStation/TauCetiClassic#1301]
#### Подробное описание проблемы
Уже нельзя фоловить глаз ИИ (AI Eye), только ядро. Обзервить тоже. На моба прыгнуть, так его вообще нет. Только ядро и есть. 
#### Что должно было произойти
В списке обзерва/орбита должно быть помимо %AI_NAME% еще и %AI_NAME% (AI Eye), дабы смотреть, куда смотрит ИИ. 
#### Что произошло на самом деле
Мы просто наблюдаем за статичным ядром. 
#### Как повторить
В гостах побудьте и посмотрите список Орбита/Обсерва 
#### Дополнительная информация:
Раньше было, а теперь нету. SLOMALEY.

**Comment by P-20** [comment]
Можно обзервить, как только ИИ скажет слово, можно заорбитить его глаз, либо вручную найти его глаз и опять таки заорбитить, но проще через последнюю сказаную ИИ фразу.

**Comment by Skippeer12** [comment]
"Некоторые сервера" = Тау Сетия.
Да и раньше небыло, вроде как у педалей есть только такая фича на фолоув.
Ну и как сказал тот что сверху.

**Comment by StrikS** [comment]
Нет, у нас вроде была.

**Comment by Zmey25** [comment]
Была, да сплыла
