### ISSUE TITLE
Random Chat Messages Are Lost

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#13025]
#### Что должно было произойти

Все отправленные сообщения в чат успешно приходят адрессату

#### Что произошло на самом деле

Приходят, но не все

### Шаги воспроизведения

1. Играть на сервере
2. Активно общаться в ИК чат
3. Наблюдать как некоторые сообщения не появляются в чате, иногда только для тебя, но другие видят

### Дополнительная информация:

Рунчат в таких случаях обычно видим, по нему можно понять что сообщения таки было отправлено но не показывается в чате

**Comment by Deahaka** [comment]
на ТГ не смогли пофиксить и добавили систему проверяющую наличие сообщения после отправки. Странно это

**Comment by LudwigVonChesterfield** [comment]
https://github.com/tgstation/tgstation/pull/79479

**Comment by LudwigVonChesterfield** [comment]
Решение есть.
