### ISSUE TITLE
Яно проблемы.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1303]
#### Подробное описание проблемы
Если выйти из тела Яна после того как зашел в него, то невозможно будет зайти обратно.
#### Что должно было произойти
Должно работать как с мышами превысив кулдаун на 15-30 минут ради того что бы не палили рольки и тд.
#### Что произошло на самом деле
Living and available Ian not found.
#### Как повторить
Зайти за Яна, выйти из тела и попытаться войти обратно.

**Comment by ZVee** [comment]
Так и задумано, зайдя - играй до конца. Информации о том - стоит ли заходить или нет - полно у гостов.
