### ISSUE TITLE
Зарядка батарей через вендомат

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#13031]
#### Что должно было произойти
Разряженные батарейки нельзя вставить в инженерный вендомат
или
Вставить можно, но они не заряжаются там.
#### Что произошло на самом деле
Можно вставить разряженную батарейку в вендомат и вытащить её уже заряженную

### Шаги воспроизведения

Вытащить с инженерного вендомата батарейки
Разрядить их (в СМЕСе например)
Вставить обратно в вендомат
Вытащить и снова использовать

**Comment by Pirsnya** [comment]
нееееееееееееееееееееееееееееееееееееееТ

**Comment by LudwigVonChesterfield** [comment]
#9139
