### ISSUE TITLE
[Bug] Использование С4 на объектах сломано

### ISSUE THREAD

**Issue by Djekke** [TauCetiStation/TauCetiClassic#1304]
#### Подробное описание проблемы
Использование с4 на объектах сломано, стабильный взрыв размером 2 независимо от объекта, привязка к месту неправильная (если объект к которому идет привязка передвинули)
#### Что должно было произойти
Если приделать с4 к объекту который можно брать в руки, то его можно использовать как гранату.
Если приделать к фуелтанку с4 и подвинуть его, то взрыв будет на месте где его оставить.
Если прикрепить на человека в бомбсьюте с4, то если его модельку не разорвет, то изображение с4 должно пропасть.
#### Что произошло на самом деле
Если ставить с4 на объект, который держишь в руках - взрыв будет в руке независимо от того куда потом деть с4.
Если поставить с4 на фуелтанк и подвинуть его, то взрыв с4 будет в месте, где прикреплял его + взрыв фуелтанка там где его оставишь.
Если прикрепить на человека в бомбсьюте с4, то если его модельку не разорвет, то изображение с4 останется на модельке навсегда.
#### Как повторить
Совершить все вышеперечисленное и посмотреть
#### Дополнительная информация:
`...
else if(isobj(target) )
			location = target.loc
...`
Привязка идет к местоположению объекта в месте постановки с4, а не к самому объекту
`...
	if(isobj(target))
		qdel(target)
...`
При взрыве объект просто удаляется, несмотря на то. что это за объект.
А если это что-то взрывоопасное? (с4, портативный фуелтанк (хотя он сейчас вообще не взрывается), бомба на фороне (не проверял))

**Comment by JamsMor** [comment]
Сам спрайт C4 остаётся на обьекте?
