### ISSUE TITLE
Не работает rolldown на tacticool turtleneck

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#13055]
#### Что должно было произойти
работает rolldown на tacticool turtleneck
#### Что произошло на самом деле
не работает rolldown на tacticool turtleneck

### Шаги воспроизведения

1. Одеть tacticool turtleneck
2. Попытаться подвернуть воротник
3. Разочароваться

**Comment by Kiromaka** [comment]
Должно выдавать - You cannot roll down the uniform! 
Потому, что You cannot roll down the uniform!
Не баг... наверное.

**Comment by Kiromaka** [comment]
А вообще... тертлнека два. Один можно, другой нельзя.
