### ISSUE TITLE
Деревянные двери не проводят атмос

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1305]
#### Подробное описание проблемы
Деревянные двери не проводят атмос
#### Что должно было произойти
Они проводят, как и другие двери
#### Что произошло на самом деле
Они не проводят атмос, и их можно использовать в качестве шлюза
#### Как повторить
Снести стекло, поставить деревянную дверь, наслаждаться
#### Дополнительная информация:
N/A

**Comment by ZVee** [comment]
Там проки Open() и Close() пятилетней давности которые оверрайднуты без вызова родителя, а в родителе висит важный прок update_nearby_tiles() которого нет в деревянной. Это касается и mineral_door/resin. Если уж с копипастой лень разбираться, то хотяб добавить недостающий прок в эти 4 места.

**Comment by Skippeer12** [comment]
Двери алиумов лучше оставить такие какие они сейчас, а то выпилы разгерметизацией будут ещё жёстче.

**Comment by Djekke** [comment]
А может сделать, чтобы все эти двери (деревянные, из металлов и подобные) не блокировали атмос вообще? Ибо это все таки просто двери, а не айрлоки. С другой стороны, именно алиумные могут быть герметичными.
