### ISSUE TITLE
Autolathe сильно лагает при попытке открыть UI

### ISSUE THREAD

**Issue by Ro2tCrab** [TauCetiStation/TauCetiClassic#13061]
#### Что должно было произойти
Как минимум что бы автолат не открывал категорию ALL, убивая игроков на слабых ПК.
#### Что произошло на самом деле
Каждый обречённый падает в SSD или немного пролагивает, позволяя схватить глупца в третий граб.

### Шаги воспроизведения

Открывайте автолат, в зависимости от версии Windows (приколы с Internet Explorer) и мощности ПК - получите лаги.

### Дополнительная информация:

Шаг первый : Найдите глупца со слабым-средним ПК.
Шаг второй : Заставьте использовать автолат.
Шаг третий : Разрядите всю обойму ему в череп, ибо лаги приковали его к месту.

**Comment by Ro2tCrab** [comment]
Можно временно решить убрав категорию ALL

**Comment by Ro2tCrab** [comment]
Так же актуально для алтаря культа и капеллана в целом

**Comment by maleyvich** [comment]
нет проблем с алтарем насчёт автолата давняя известная проблема может быть решат переходом на тгуи

**Comment by Ro2tCrab** [comment]
> нет проблем с алтарем насчёт автолата давняя известная проблема может быть решат переходом на тгуи

Автолат это TGUI уже.

С алтарём проблемы есть. Конкретно алтарь культа чаще всего имеет это проблему

**Comment by maleyvich** [comment]
> > нет проблем с алтарем насчёт автолата давняя известная проблема может быть решат переходом на тгуи
> 
> Автолат это TGUI уже.
> 
> С алтарём проблемы есть. Конкретно алтарь культа чаще всего имеет это проблему

с алтарем никогда проблем не было а насчёт автолата можно и нужно на тг подсмотреть он у них норм работает

**Comment by Ro2tCrab** [comment]
> с алтарем никогда проблем не было а насчёт автолата можно и нужно на тг подсмотреть он у них норм работает

Опять же. Проблема с алтарём есть.
Этот вопрос сильно зависит от игрока к игроку.
Один ты не можешь сказать есть ли эта проблема или нет.

**Comment by Ro2tCrab** [comment]
У остальных проблемы с алтарём в виде секундных лагов

**Comment by Oz1Es** [comment]
> У остальных проблемы с алтарём в виде секундных лагов

ну как минимум алтарь находится в не общедоступном месте, а если призыв то в любом случае несколько секунд не слишком много решает, и он не убивает компы игорьков революционеров
