### ISSUE TITLE
cqc повара не работает в холодильнике

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#13078]
#### Что должно было произойти
мгновенный красный захват работает в морозилке с гиббером
#### Что произошло на самом деле
не работает

### Шаги воспроизведения

будучи поваром попытаться грабнуть существо в морозилке у кухни

**Comment by Deahaka** [comment]
Там гибалки, не надо там повару буйствовать. Если надо, то перенесёт сам на кухню или инженера позовёт.

**Comment by LudwigVonChesterfield** [comment]
@simb11 даже если это не баг, оформи как пропоузал

**Comment by Deahaka** [comment]
Не пропозал, не баг, it's over
