### ISSUE TITLE
кривой перевод коробок с патронами (магазинов, спидлоадеров и подобного)

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#13086]
#### Что должно было произойти
"Вы вытаскиваете патрон из магазина (9мм)"
#### Что произошло на самом деле
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/84613249/b4838892-8887-43a2-8d37-cc7093cb2c6f)

### Шаги воспроизведения

1. Найти магазин/коробку с пулями/спидлоадер/etc
2. Использовать найденный предмет (кликнуть по предмету когда он находится в активной руке)
3. Посмотреть в чат

**Comment by Kiromaka** [comment]
Это не баг, просто их не переводили. 
https://github.com/TauCetiStation/TauCetiClassic/blob/ba213cd5e9309591142a0662cc12a13fb4a2dcec/code/modules/projectiles/ammunition/magazines.dm#L198

**Comment by simb11** [comment]
Тогда зачем вы переводили (ещё и неправильно) этот лог?

**Comment by Kiromaka** [comment]
> Тогда зачем вы переводили (ещё и неправильно) этот лог?

Лог родительский, вроде.
