### ISSUE TITLE
Крафт укреплённого стола сломан

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#13124]
#### Что должно было произойти
При клике прутьями по деталям обычного стола появляются детали укреп. стола
#### Что произошло на самом деле
При клике прутьями по деталям обычного стола ничего не происходит, даже сообщения в чат нет

### Шаги воспроизведения

Создать детали стола
Кликнуть по деталям стола прутьями

### Дополнительная информация:

Возможно дело в том что тайп стола объявляется дважды
в code\defines\obj\weapon.dm и code\game\objects\items\weapons\table_rack_parts.dm

Issue reported from  Round ID: 63874 (Tau Ceti Classic (RU))
Testmerges: ```#12954# 13092```
Reporting client version: 515.1633

**Comment by AirBlack** [comment]
ну ты дурак не ожидал что ты у меня будешь копировать баги просто наглый плагиат моего оформленного бага тебе вот не стыдно потом маме в глаза смотреть? особенно своей
