### ISSUE TITLE
find brains регариует на СПУ

### ISSUE THREAD

**Issue by PirogSema** [TauCetiStation/TauCetiClassic#13131]
#### Что должно было произойти
поисковик у зомбаков игнорит спу

#### Что произошло на самом деле
![изображение](https://github.com/TauCetiStation/TauCetiClassic/assets/22032604/1a3538d3-f800-437f-ac1b-7997472f9ebc)

### Шаги воспроизведения

1. создать спу
2. юзнуть у зомби абилку find brains

### Дополнительная информация:

Issue reported from  Round ID: 63893 (Tau Ceti Classic (RU))
Testmerges: ```#13092```
Reporting client version: 515.1639

**Comment by AirBlack** [comment]
мб это был особковый СПУ с ММИ и мозгом внутри ММИ?

**Comment by PirogSema** [comment]
> мб это был особковый СПУ с ММИ и мозгом внутри ММИ?

уже не помню, но вроде это был вайтлистовый СПУ
(а может ли оно реагировать на кошку на голове)
