### ISSUE TITLE
Телепорт не работает после сборки.

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#13148]
#### Что должно было произойти
После сборки всех компонентов консоль должна видеть хаб и работать.
#### Что произошло на самом деле
Консоль не видит хаб, при копировании данных с хаба в мультитул, дальнейшее перенесение данных в консоль невозможно.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/19796920/08fd783a-a4c0-4dd0-9dcb-e5406c7e212d)

**Comment by volas** [comment]
там какой-то не очевидный шаг с кусачками был, может оно https://github.com/TauCetiStation/TauCetiClassic/issues/7043
