### ISSUE TITLE
Офицер Робуст на велосити стал невидимым

### ISSUE THREAD

**Issue by hwat1204** [TauCetiStation/TauCetiClassic#13158]
### Описание

Мартышка на велосити, после обновления спрайтов обезьян, Officer Robust, не получил свои личный новый спрайт. результат - мартышка стала невидимой. требуется это исправить, нарисовав ему новый спрайт. Просто оденьте костюм на новый спрайт monke и дело с концом.

**Comment by maleyvich** [comment]
@WatlerJe

**Comment by KatoMarika** [comment]
Исправлено еще при тест мерже в #13143, просьба закрыть
