### ISSUE TITLE
Handshake по основной ссылке и белый экран по Релей МСК

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#13153]
#### Что должно было произойти
Стабильный запуск игры без проблем как на других серверах
#### Что произошло на самом деле
По основной ссылке: Handshake 
По мск релей: белый экран и ничего больше
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/be080c9f-07ce-4d93-8fd5-175164ba7874)

#### Интересное наблюдение
Только с рестартом сервера все проблемы исчезают (но не всегда, но только это помогает)
Методы как: очистка КЭШа, снос бьонда, переустановка версий бьонда, перезапуск и отключение ПК не работают. 

Issue reported from  Round ID: 63971 (Tau Ceti Classic (RU))
Testmerges: ```#13092# 13102# 13143```
Reporting client version: 515.1631 (пробовал еще на 16.36, 16.39 и 16.40 версии запускаться)
Оператор домашнего интернета: Билайн

**Comment by AirBlack** [comment]
билайн спасает сервер от вахтерства козла, как им задонатить чтоб у козла никогда ниче не работало?
