### ISSUE TITLE
[ADMIN] Player notes

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#13162]
#### Что должно было произойти
При просмотре нотесов они отображаются по порядку
#### Что произошло на самом деле
При просмотре нотесов в некоторых случаях они отображаются по непонятной причине некорректно, перепутавшись.
![Untitled](https://github.com/TauCetiStation/TauCetiClassic/assets/35347896/2d773d0f-100e-4fa2-9010-5a57f20f5e75)
Здесь можно заметить, что время совершенно разное, но ниже нотес идёт аж на 4 года моложе, чем тот, что выше.

### Дополнительная информация:

Issue reported from  Round ID: 64009 (Tau Ceti Classic (RU))
Testmerges: ```#13146# 13102# 13008```
Reporting client version: 514.1589

**Comment by volas** [comment]
обязательно еще укажи, если это нотес, или бан. Баны - не нотесы, но их зачем-то запихали в эту таблицу
