### ISSUE TITLE
Электро и повер перчатки не дают использовать Хелп интент.

### ISSUE THREAD

**Issue by ZER0-In** [TauCetiStation/TauCetiClassic#13184]
#### Что должно было произойти
Поднимаешь человека.
#### Что произошло на самом деле
На хелп интенте в электроперчатках и поверперчатках триторов/нюки нельзя поднять человека. Медик нюки в этих перчатках не может хелп интентом поднять сокомандника и просто тыкается в него без какого-либо эффекта. Также с инсулами на батарейках.

**Comment by Slavik2001** [comment]
Ну и тоже самое с боксерскими перчатками

**Comment by Permyack** [comment]
А должна ли такая возможность вообще существовать, если считается, что перчатки таки бьются током?
Ладно, если бы перчатки выключались и тогда это быо бы проблемой.
Но разве это актуально для всех видов перчаток?

**Comment by ZER0-In** [comment]
> А должна ли такая возможность вообще существовать, если считается, что перчатки таки бьются током? Ладно, если бы перчатки выключались и тогда это быо бы проблемой. Но разве это актуально для всех видов перчаток?

Блять. Они не дают жать хелпинтент в любом виде. Даже в разряженном и выключенном.

**Comment by Permyack** [comment]
> Даже в разряженном и выключенном.

Стоило уточнить об этом для большей подробности.

**Comment by AndroBetel** [comment]
#13228
