### ISSUE TITLE
Ротация карт [Proposal] 

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#13187]
### Описание

Ввиду боязни выхода из зоны комфорта игроки или же просто не желая знакомиться с новыми картами ввиду лени, чаще всего голосуют за дефолтный бокс который стар как и сам билд.
В связи с этим предлагается следующее: После окончания раунда автоматически создается голосование за следующую карту при котором уже сыгранная карта исключается из воута.

**Comment by simb11** [comment]
уже обсуждалось в #11438 , было решено сделать систему с уменьшением голосов

**Comment by WatlerJe** [comment]
Система работает плохо, ибо все равно выбирают бокс.

**Comment by simb11** [comment]
всё работает как нужно, если большинство хочет играть на боксе - пусть играет, ради этого даже коэффициенты меняли в #12351

**Comment by WatlerJe** [comment]
Если нужно чтобы игроки пикали бокс из раза в раз, то да, работает как часы.

**Comment by WatlerJe** [comment]
И с какого хуя ты закрыл это предложение. То что когда-то там решили, не означает, что решили навсегда.

**Comment by simb11** [comment]
ладно, пусть ещё один открытый бесполезный пропосал лежит на гите

**Comment by WatlerJe** [comment]
Бесполезный здесь только ты

**Comment by volas** [comment]
Мы можем откатить или еще подкорректировать вес из #12351, до того патча часто выбирали другую карту кроме бокса.

**Comment by ZER0-In** [comment]
> Мы можем откатить или еще подкорректировать вес из #12351, до того патча часто выбирали другую карту кроме бокса.

Там та же Дельта не особо играбельна, а работа над ней ведется медленно. Либо вообще прекратилась. У нас только три карты играбельны: Гамма, Бокс, Прометей.
Фалькон для слишком малого онлайна.

Тут очевидно, почему люди берут бокс. Если форсить людей играть на какой-нибудь дельте, то не удивительно, что люди будут ливать. Даже, если после Дельты карту снова сменить на бокс, это не вернет номинальный прайм сервера по числу игроков.

**Comment by volas** [comment]
какие проблемы на дельте? у неё единственной сейчас живой мапер, если не считать бокс

**Comment by Chip11-n** [comment]
Есть вариант еще воспользоваться опытом других серверов и изменять не вес голоса, а переносить количество голосов из одного раунда в другой, а при выборе карты - обнулять.

К примеру:
В 1 раунде выбрали бокс, за гамму проголосовало 7 человек
Во 2 раунде голоса предыдущего раунда плюсуются к нынешнему, т.е. будут условно 6+7 голосов. Таким образом, карты рано или поздно будут меняться.

Правда вопрос, будет ли кто это кодить?

**Comment by Kiromaka** [comment]
Зачем забирать у людей право выбора.

Радуйтесь, что у нас не как на ТГ - где додики, которые ливают, голосуют за NorthStar перед выходом, чтобы другие страдали.

**Comment by Tap0r** [comment]
> какие проблемы на дельте? у неё единственной сейчас живой мапер, если не считать бокс

а че, я жив вобще-то реально, даже в игру играю обалдеть это когда такое было

**Comment by AgRevol** [comment]
> какие проблемы на дельте? у неё единственной сейчас живой мапер, если не считать бокс

Клевета!

А вообще у дельты очень много проблем, начиная от структуры отсеков заканчивая наполнением отсеков. Дельта - карта под другой онлайн и билд, у нас она не практичная и не привычная. Раньше ещё была проблема сырости но не следил, не буду говорить. Как игрок - она очень не интуитивная.

По-поводу ПРа: менять карты нужно, но форсить людей не стоит. К сожалению на сервере не столько онлайна чтобы указывать как играть. Возможно, стоит вернуть влияние коэфициентов но с меньшим весом.

**Comment by WatlerJe** [comment]
> Зачем забирать у людей право выбора.
> 
> Радуйтесь, что у нас не как на ТГ - где додики, которые ливают, голосуют за NorthStar перед выходом, чтобы другие страдали.

А еще на ТГ... вот у них-то вообще пиздец, а у нас пиздец тоже но не такой пиздец и вообще вы радоваться должны, что у нас вот такой пиздец, а не как у них пиздец!

Право выбора которое ограничивается выбором одной и той же карты из раза в раз. Эти люди выбирают не карту, они выбирают ничего не менять, потому что это безопасно и не надо думать над новым, они выбирают не развиваться, а оставаться на месте и вследствие деградировать.

**Comment by Deahaka** [comment]
Киромака прав, системы ТГ и даже СМов легко подвержены влиянию троллей и каких-то маргиналов, голосующих за не популярные ни в каких кругах карты.

**Comment by WatlerJe** [comment]
> Киромака прав, системы ТГ и даже СМов легко подвержены влиянию троллей и каких-то маргиналов, голосующих за не популярные ни в каких кругах карты.

Ну да, как сейчас за бокс.

**Comment by KatoMarika** [comment]
Если я усну и проснусь через сто лет и меня спросят, что сейчас происходит на Тау Сети, я отвечу: пытаются избавиться от бокса и ненавидят респрайты
