### ISSUE TITLE
Бандана не может изменить свой слот при переключении

### ISSUE THREAD

**Issue by Permyack** [TauCetiStation/TauCetiClassic#13200]
#### Что должно было произойти
Бандана должна была изменить свой слот
#### Что произошло на самом деле
Бандана не изменяет свой слот

### Шаги воспроизведения

1. Возьмите бандану в руки
2. Переключите бандану
3. Не профит, ведь вы не можете носить её на голове.

### Дополнительная информация:

Это очень древний микробаг. Он не является чем-то критичным, но он довольно глупый.
Вы можете сделать так, чтобы бандана была визуально на вашей голове или на лице? Да, вы можете.
Вы можете изменить слот банданы при этом? Нет, вы не можете.

**Comment by AndroBetel** [comment]
не баг
