### ISSUE TITLE
пиво контрит сон

### ISSUE THREAD

**Issue by 4310V343k** [TauCetiStation/TauCetiClassic#13219]
#### Что должно было произойти

от алкоголя хочется спать

#### Что произошло на самом деле

любой алкоголь с adj_sleepy = 0 [полностью снимает sleep](https://github.com/TauCetiStation/TauCetiClassic/blame/23cac351999e1b289057fd184fffd89fae7ed6e4/code/modules/reagents/reagent_types/Chemistry-Drinks.dm#L739)

### Шаги воспроизведения

1. выпить пива
2. включить баллон с анестетиком
3. спим - не спим - спим - не спим

**Comment by maleyvich** [comment]
пивка для рывка
