### ISSUE TITLE
[Bug] Отсутствие securityHUD иконок у подпрофессий.

### ISSUE THREAD

**Issue by Djekke** [TauCetiStation/TauCetiClassic#1321]
#### Подробное описание проблемы
У подпрофессий нету securityHUD иконок.
#### Что должно было произойти
У всех подпроф должна быть иконка их родителя.
#### Что произошло на самом деле
Видя человека в securityHUD с подпрофой (Аномалист например) у него не отображается иконка.
#### Как повторить
Посмотреть на людей с подпрофами используя securityHUD.
#### Дополнительная информация:
Все подпрофы не проверял, но часто замечал в игре.

**Comment by omejka** [comment]
Это все курошен сломал,хотя я давал ему иконки для всех подпроф
или не всех :^)

**Comment by SpaiR** [comment]
Ты давал ему, если не ошибаюсь, для подарок ассистентов. А аномалисты это ученые.

**Comment by omejka** [comment]
Нарисовал и для инженеров,и для медиков,и для ученых 
Может они его просто не устроили

**Comment by Skippeer12** [comment]
Сегодня бегал в худе охраны и видел подпрофу технического ассистента, там был серый гаечный ключ вот
Может ему просто ЭМИ сломали худы?

**Comment by Djekke** [comment]
Такие подпрофы:
Chef - [Cook]
Botanist - [Hydroponicist]
Librarian - [Journalist]
Chaplain - [Counselor]
Station Engineer - [Maintenance Technician], [Engine Technician], [Electrician]
Medical Doctor - [Surgeon], ...
Надеюсь продолжать список не надо?

**Comment by omejka** [comment]
![image](https://cloud.githubusercontent.com/assets/20469702/24590939/0ed15e80-17ff-11e7-8a7a-4b73c6da831a.png)

**Comment by igigin** [comment]
>Нарисовал и для инженеров,и для медиков,и для ученых

Но скидывал то ты только ассистентов и каргоменов.

Хотя тут скорее виноваты мейнтейнеры, т.к. прогляделя момент, что кто-то там, добавив подпрофы ассистентов, совершенно забыл, что в других профах тоже есть подпрофы.

**Comment by omejka** [comment]
лично курешену кидал

**Comment by SpaiR** [comment]
> лично курешену кидал

Ну так скинь их сюда, чтобы их не только куршан мог залить

**Comment by Kurshan** [comment]
Но ведь не кидал, а завыезживался: Я не знаю че там рисовать, пускай так будет.
Косяк с моей стороны, но лишние заслуги мне прописывать не надо, мне их и так хватает.

**Comment by DeadOberst** [comment]
Вики обновить не забудьте.

**Comment by omejka** [comment]
Скину сегодня,нашел орхив
Куршан признал,что ебался в глаза
Лох

**Comment by omejka** [comment]
http://www.filedropper.com/missinghud
там (вроде) все,кроме иконки каковота патолоджист
забавно,что иконка мехатроник инженера,которую я докинул спустя час,после основного архива,как инстафикс,в билде есть
