### ISSUE TITLE
Эммитеры работают без тока на святом духе

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#13261]
#### Что должно было произойти
Эммитер требует провод с током под собой для работы
#### Что произошло на самом деле
Эммитер работает без тока в проводе, да и вообще без провода

### Шаги воспроизведения

1. Прикрутить и приварить эммитер где угодно, можно на станции, можно в космосе.
2. Проложить один тайл провода под ним (необходимо для запуска эммитера)
3. Запустить эммитер, он начнет работать, хотя в проводе тока нет (можно проверить мультитулом, провод будет not powered)
4. Обрезать провод под эммитером, он всё так же будет вечно работать.

**Comment by Deahaka** [comment]
На аккумуляторах

**Comment by Pirsnya** [comment]
Где-то был уже багрепорт на эту тему, но я не смог его найти, вроде там сошлись на том что нужно чет с кодом энергии делать. Эммитер, кстати, работает даже в космосе без питания, без привязки к зоне, если не ошибаюсь.
