### ISSUE TITLE
Кулдаун респавна после нажатия OBSERVE

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#13269]
#### Что должно было произойти
После нажатия OBSERVE ты выходишь в госты с КД на респавн в 30 минут
#### Что произошло на самом деле
После нажатия OBSERVE ты можешь зайти в позитронку, начекав режим заранее. Либо бери борга сразу, либо жди 30 минут.

### Шаги воспроизведения

нажать observe в лобби

**Comment by AirBlack** [comment]
as intended, напиши пропозал чтобы позитронка в спавнер меню добавлялась, там контроля больше

**Comment by ZER0-In** [comment]
В целом это уже правило метагейма. Которое вы стараетесь пофиксить кодом. В целом можно, почему бы и нет. Но тогда что получается, умершие игроки в раундах должны 30 минут ждать возможности зайти в позитронку?

А если им дать возможность сразу после смерти в позитронку заходить, тогда они че не смогут спалить режим и зайти в борга? Они же ничем от спектаторов не отличаются в гостах.

В общем сомнительное решение, которое мало на что повлияет.

**Comment by Pirsnya** [comment]
> А если им дать возможность сразу после смерти в позитронку заходить, тогда они че не смогут спалить режим и зайти в борга? Они же ничем от спектаторов не отличаются в гостах.


Зачем тогда вообще нужен кд на ревайв если так рассуждать?

**Comment by TgT4** [comment]
а если ты хочешь в борга но опоздал к началу раунда?
в лобби приглашения в позитронку не выдаёт

**Comment by Gort133** [comment]
ПИИ тоже спалить режим может и назваться АНТИНЮК допустим. Агент прослушки тоже может там назвать себя АНТИКУЛЬТ ндаааааа

**Comment by Pirsnya** [comment]
Ребята согласен идея хуйня будем банить
