### ISSUE TITLE
АПЦ в дормах не заряжаются

### ISSUE THREAD

**Issue by Slavik2001** [TauCetiStation/TauCetiClassic#13275]
#### Что должно было произойти
Заряжаются дормы
#### Что произошло на самом деле
НЕ заряжаются дормы

@ka

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/123300305/bab49e7d-5cec-4c63-9cb4-f35a5476758b)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/123300305/b41873f9-eda1-418b-b180-33bbff3e51e1)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/123300305/04edb56d-228d-44c0-ac6b-af43fb97adb4)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/123300305/a34d7ba3-6ee8-4889-a49b-47f2911183f5)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/123300305/4d082ab4-8adc-48c3-a23c-5a82906ad88c)

### Шаги воспроизведения

Сделать подачу энергии на станцию
Ждать

### Дополнительная информация:

Issue reported from  Round ID: 64288 (Tau Ceti Classic (RU))
Testmerges: ```#13008```
Reporting client version: 515.1641

**Comment by KatoMarika** [comment]
Пофикшено в #13260

**Comment by Slavik2001** [comment]
Оно уже замержено, но я сейчас в раунде и они не заряжаются.
Не обновили сервак?

**Comment by KatoMarika** [comment]
После рестарта обновится.

**Comment by Slavik2001** [comment]
Окей, после рестарта проверю и потом закрою, если пофикшено
