### ISSUE TITLE
Мезонки показывают комбатлоги сквозь стены

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#13300]
#### Что должно было произойти
С мезонками нельзя видеть комбат логи сквозь стены (как кто-то в кого-то стреляет и как кто-то кого-то бьёт)
#### Что произошло на самом деле
С мезонками можно видеть комбат логи сквозь стены (как кто-то в кого-то стреляет и как кто-то кого-то бьёт)

### Шаги воспроизведения

Экипировать мезонки.
Понаблюдать за стрельбой/избиением из-за стены.

### Дополнительная информация:

Issue reported from  Round ID: 64358 (Tau Ceti Classic (RU))
Testmerges: ```#13182# 13271# 13280```
Reporting client version: 515.1640

**Comment by Deahaka** [comment]
Дубликат https://github.com/TauCetiStation/TauCetiClassic/issues/8999
