### ISSUE TITLE
С особкой на СПУ видишь себя как рандомную машинерию

### ISSUE THREAD

**Issue by AirBlack** [TauCetiStation/TauCetiClassic#13312]
#### Что должно было произойти
Выглядишь как СПУ
#### Что произошло на самом деле
![image](https://github.com/user-attachments/assets/a60a13c8-fd48-4e16-ad68-ef571afbb2bf)
я джукбокс

### Шаги воспроизведения

1. Получить особку на СПУ
2. Зайти в раунд
3. Ты машинерия блин

### Дополнительная информация:

При перезаходе починилось. Наверняка связано с #13209

**Comment by DarthSidiousPalpatine** [comment]
АХахха, боже, баг года.

**Comment by Tap0r** [comment]
я нашел почему это 
![image](https://github.com/user-attachments/assets/f9a689bf-38a6-447d-9815-d89ce391df19)
ща фикс залью

**Comment by Tap0r** [comment]
самый че прикол что почему-то если раундстартом заходишь такого нету и не было когда я тестил. То есть оно именно в сет_спешиес всплывает каким-то хуем
