### ISSUE TITLE
Не работает обращение зоны за  Harvester 

### ISSUE THREAD

**Issue by Riverz1** [TauCetiStation/TauCetiClassic#13337]
#### Что должно было произойти
При нажатии обратить зону зона вокруг должна была обратиться
#### Что произошло на самом деле
Ничего не произошло

### Шаги воспроизведения

1. Заспаунить ивент портал культа
2. Зайти за харвеста
3. Попробовать обратить зону

**Comment by Chip11-n** [comment]
Есть бан на культ и/или антагов?

**Comment by Riverz1** [comment]
> Есть бан на культ и/или антагов?

Точно у меня же бан на антагов
