### ISSUE TITLE
Имбовые нефизические космоциклы

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1333]
#### Подробное описание проблемы
Мотоциклы пиратов давят людей.
#### Что должно было произойти
Мотоциклы пиратов должны отталкивать людей.
#### Что произошло на самом деле
Непонятно как мотоцикл задавил космонавта.
#### Как повторить
Переехать космонавта на космобайке.
#### Дополнительная информация:
По ебучему физону мотоцикл должен отталкивать космонавтов. Давить не на чем, космос пустой, пола нет. Надо нерфить имбы.

**Comment by Kurshan** [comment]
У вас двадэ головного мозга. Но да, пиратов надо выпиливать как режим.

**Comment by Forrya** [comment]
Ебучая неконтрящаяся в космосе имба. Надо исправлять.

**Comment by ZVee** [comment]
Ну будет он толкать (с тем же уроном) и кнокать (удар же сильный), что изменится? Более того, в этом случае еще начнет работать урон от столкновения с тем, во что космонавт влетит будучи запущенным на ракетной тяге после столкновения и в итоге еще имбовее станет, можно космонавтов на другой слой отправлять такими ударами и в дырявых ригах.

А так в целом - байки такие - чтобы с пиратами не воевали в космосе открытом, однако если байк угонят, все может обернуться с точностью наоборот.

**Comment by Uvash** [comment]
Так-то в космосе с пиратами можно было бы воевать на мехе. Но во-первых у пиратов есть 556НЛ, которое нивелирует данное преимущество.  А во-вторых у нас джетпак для мехов закоментирован.

**Comment by omejka** [comment]
>закрывать ишуесы за мат
Мультиакк мурмиллы,точно говорю
Они слишком надолго кнокают,так еще и риги на тряпки рвут.Снизить время кнека и всо.

**Comment by P-20** [comment]
Убивают пираты на мотоциклах. >Гитхаб "Книга жалоб и предложений", поможет вам. Главное проявлять агрессию, мерзкие пираты на своих супер-байках убивают беззащитных людей которые вышли в космос чтобы сражаться с пиратами, пишу это предложение потому что и сам оказался повержен ими. С такими темпами пираты будут приезжать на космосамокатах, и угрожать станции игрушечными пистолетиками, или же переделать байки в танки, чтобы они стреляли, а если ты кого-то давишь, его просто гибало

**Comment by TungstenOctopus** [comment]
Да даватя это еще норма, а вот то, что байк полностью блять от попаданий по пирату защищает - вот это пиздец.

**Comment by Lancer411** [comment]
У байка ограниченное ХП, они нужны для того, чтобы за пиратами не лезли в космос охотиться.

**Comment by Kurshan** [comment]
А28 чтобы ваншотить киборгов и мехов. Фултон чтобы не таскать хлам у себя в рюкзаке. Йобасумки для тысячи вундервафль и патронов. Йобарипли с вау освещением на 80 тайтлов чтобы не заблудиться. Покемоны чтобы отвлекать. Сабли чтобы добивать. Дебаггеры чтобы емагать без ограничений. Сабли для добивания несогласных. Список сидеть неплохо продолжить, но хочется спросить, зачем напихано столько вещей в один режим? Творческое начало, эксперименты? Это можно понять, но вот что не могу, почему все и сразу скомкано в одном режиме? Про статистику не надо рассказывать. То, что ваши имбалансные вещи позволяют не задумываться о какой-либо сплочённости и тактике, делают свое дело и просто наглеют, поэтому лузают. Дайте мне сквад из людей, который мало-мальски умеет читать чат и слушать остальных и я гарантирую, никакие деды, ерт, джедаи не смогут что-либо противопоставить (если не писать им циферки офк)

**Comment by omejka** [comment]
Оставить йобасумки,байки и аирсофт валыны пейратам
Вернуть птиц,дать им деббагеры,покеболы,раскладные софтсьюты для хостаджей и разрешить пиздошить людей до крита,дать свой ковчег
Кода выпадает режим,выпадают либо пейраты,либа птицы,50 на 50

**Comment by rasl1410** [comment]
Форри соснул вчера от пейрата на байке и пошел писать ишью.

А вообще да. Верните Воксов, ну пожалуйста.

**Comment by Skippeer12** [comment]
Проблема пиратов в том, что они выпадают при 15 диклерах, а теперь давайте посчитаем
15-6=9
Девять хуманов должны противостоять шести пиратам, которые кнокают их в космосе, на станции, на мехах, на аллахе!
И не факт что эти девять хуманов будут офицерами, варденами, ХоСами и капитанами.
Так что выполучаем, пираты которые кнокают везде без особых проблем и экипаж которому по правилам сервера запрещено робастить и вообще брать пушки.

**Comment by ZVee** [comment]
>Проблема пиратов в том, что они выпадают при 15 диклерах.

Когда у нас игроки будут заходить для того чтобы играть минуя кнопку обсерва и деклериться до начала раунда, тогда и не будет таких низких необходимых параметров, потому что расчет идет на то, что кто-то зайдет после начала раунда, кто-то в обсервах полетает и тоже влетит в раунд там хотя бы в виде борга через позитронку. Единственное что можно - это подсчитывать игроков на сервере вне зависимости что они там в лобби делают.
А если мы будем спавнить пиратов от деклеров - тогда может выйти так, что попадет в раунд скажем 2 пирата, потому что было 12 человек на момент запуска раунда, а потом окажется через 10 минут что в игре на станции бегает уже человек 30 против которых эти 2 пирата должны что-то сделать.

**Comment by Skippeer12** [comment]
>человек 30 против которых эти 2 пирата должны что-то сделать.

Ну бан на обсервер, на мышку вам просто так запилил? Если обсерверы заходят чтобы спалить режим, а после используют мышку для респавна, то надо таких джобками закидывать на соответствующие вещи.

**Comment by ZVee** [comment]
Речи про это вообще нету в тексте, и если уж на то пошло - речь была про легальный респавн.

**Comment by Skippeer12** [comment]
>легальный респавн.

Ну тридцать минут смотреть, как пираты делают разгерметизацию по станции, а потом зайти чтобы их подебить - не реально.
Пираты прилетают минут за пять после начала спавна.
За двадцать пять минут можно награбить достаточно барахла чтобы быть гринтектстовым.
Но пираты обычно проигрывают из-за того что не успевают награбить сколько нужно, а всё потому что некоторые пираты забывают достать ключи из байка или включить балон или ботинки. (серьезно сделайте уже макрос на включение встроенных ботинок в риге)
И вот получается что когда пиратов шесть штук на девятку персонала то это избиение младенца который даже рукой махнуть в сторону противника не может.

**Comment by ZVee** [comment]
И все таки не на том заострил внимание, речь про игроков которые зашли в раунд несколько позже чем он начался, это могут быть и те кто деклер не ставил по какой-то причине сразу, это могут быть те кто зашел на сервер позже и не был в онлайне на момент начала. Но да, суть в том, что от деклеров плясать плохо, нужно что-то, что от них не зависит.

>как пираты делают разгерметизацию по станции

Насколько я знаю - у нас таких пиратов наказывали совсем недавно, только без понятия практикуют ли это постоянно.

>то это избиение младенца который даже рукой махнуть в сторону противника не может.

Когда увижу Шкиппера, который вооруженный до зубов прибежит на место преступления, увидит что незнакомый ему ассистент и вообще человек который еще и насолил, на прицеле у тритора - ничего из себя особо серьезного не представляющий и Шкиппер положит на пол все оружие и скажет: "бери меня в заложники, а вон этого ассистента отпусти" - тогда будем говорить на такие темы. Но думаю это не произойдет, потому что кое кто стыдиться поддаваться и на удар в лицо обязательно ответит тем же но уже топором, а не молча уйдет с оскалив зубы и забив на инцидент. Одно дело РЛ, а другое игра и ролеплей и не надо свою личность вкладывать в куклу и делать те же самые поступки тогда, когда этого делать как раз не надо (между прочим, об этом в "том самом месте" кстати говорится, но все наверно или не читали или забыли давно это "правило").

А по теме этоц цитаты - если отталкиваться от деклеров - все вполне может быть с точностью до наоборот, и решения кроме как проверки вообще всех игроков на сервере текущих без учета деклеров - не вижу в данный момент.

>За двадцать пять минут можно награбить достаточно барахла чтобы быть гринтектстовым.

О гринтексте думают только те, кого это волнует, на деле - проиграл ты или выиграл - это просто некий результат или статистика в раунде, не более и не менее, с тем же подходом сделаем показ этих данных только для администраторов и возможно самих игроков у которых была цель, дабы третьи лица ничего не знали.
Кстати, никто не мешает вместо грабежа - пойти захватить станцию и диктовать условия и забить вообще на задание, но в связи с некоторыми обстоятельствами - сделать такое крайне сложно.

**Comment by Skippeer12** [comment]
>Насколько я знаю - у нас таких пиратов наказывали

Наказание изредка бывают очень разные (как никак зависит от администратора в данный момент)
Иногда при одном прите делающим разгерметизацию в каждом отсеке в который он смог попасть наказывают всех ингейм, присылая какого-нибудь Ольта на мехе.
А иногда наказывают лично, но суть от этого не меняется, потому что раунд уже к тому времени будет не играбелен.
>О гринтексте думают только те, кого это волнует, на деле - проиграл ты или выиграл - это просто некий результат или статистика в раунде.

Отличный подход, но жаль его не все разделяют и как правило остальные игроки замечают лишь три вещи, насколько ты был "гринтекстовым" на сколько ты проиграл и на сколько ты испортил раунд для них.

>Шкиппер положит на пол все оружие и скажет: "бери меня в заложники, а вон этого ассистента отпусти"

Был у меня такой раунд с теми же самыми пиратами, был у меня заложник, был он главой.
Договорились на чесный обмен, один мой целый и невредимый и один их также целый и не вредимый.
В итоге всё закончилось плачевно, расстреляли сначала заложника, а потом и меня.
Ну и после этого момента, стало ясно что никто и никогда (наверное) не будет торговаться, они скорее повыпиливают друг друга, чем сложат оружие и поговорят. Прям сюжет для вестерна.

Ну и всё это перешло не туда куда надо, да и не тут это надо обсуждать. А этот "Пропозал" лучше закрыть и оставить так как есть.
