### ISSUE TITLE
Если сесть на стул, консоль не открывается

### ISSUE THREAD

**Issue by ThePunisher95** [TauCetiStation/TauCetiClassic#1336]
#### Подробное описание проблемы
Если забаклить себя на стул, то консолька не откроется.

#### Что должно было произойти
Консоль должа была открыться.
#### Что произошло на самом деле
Консоль сука не открывается.
#### Как повторить
Присяд на стул и тыкай на консоль
#### Дополнительная информация:
Ну реально древний баг, а так и не пофиксили. Вот хочется по рпешить, садишься такой на стул в приёмной брига, чтобы за камерами посидеть, а хуй там был. Собственно та же проблема и с пианино.

**Comment by omejka** [comment]
Персонаж поворачивается в сторону камеры,на которую смотрит
Даже зве не починит,имхоу

**Comment by SpaiR** [comment]
Баги других билдов нужно в других местах репортить. Конкретно этот баг у нас давно пофикшен. Баклись до посинения, взаимодействовать с конолью сможешь без проблем.
