### ISSUE TITLE
 universal painter не красит укреп стены

### ISSUE THREAD

**Issue by KatoMarika** [TauCetiStation/TauCetiClassic#13363]
#### Что должно было произойти
 universal painter должен покрасить укреп стены
#### Что произошло на самом деле
Несмотря на выбор цвета - не красит. 

### Шаги воспроизведения

 universal painter в руки, подойти к укрепке, выбрать цвет, увидеть что ничего не произошло.

**Comment by volas** [comment]
это были ведь стены что на станции?

**Comment by KatoMarika** [comment]
Конечно
