### ISSUE TITLE
Дюп вещей в вентомате

### ISSUE THREAD

**Issue by QWxiZ** [TauCetiStation/TauCetiClassic#13371]
#### Что должно было произойти
не дюпается
#### Что произошло на самом деле
дюпается

https://github.com/user-attachments/assets/e1c370eb-9d5b-4b53-a4bf-41c37d58d136

### Шаги воспроизведения

1. Кликать как ебанутый в вендомате на вещь.
2. Дюпается.

**Comment by Tap0r** [comment]
приду домой пофикшу
