### ISSUE TITLE
[Проупозал]Отдельные атмосонепроводящие двери для алиенов

### ISSUE THREAD

**Issue by omejka** [TauCetiStation/TauCetiClassic#1337]
Теперь,вроде как,через двери аналиенов проходят всякие разгермы
Предлагаю добавить всяким дронам и квинам конструкт непроводящей двери
Попробую нарисовать спруйт,позже скину сюда

**Comment by SpaiR** [comment]
Вроде как сначала нужно в игру играть, а потом пропозалы строчить. Не пропускают они воздух, как и раньше. Причём механизм "непропускания" даже улучшился по сравнению с тем, что было.
