### ISSUE TITLE
Проблемы научного аванпоста

### ISSUE THREAD

**Issue by Naroke** [TauCetiStation/TauCetiClassic#13387]
#### Что должно было произойти
Все стены одного цвета, под окнами ничего нет
#### Что произошло на самом деле
Рядом с комнатой мусоросброса стоит синяя стена, хотя весь аванпост фиолетового цвета. Там же под окном стоит укреплённая стена

### Шаги воспроизведения

Прилететь на научный аванпост. Найти мусор. Выбросить его. Посмотреть в окно рядом с мусоросбросом. Ничего не увидеть из-за стены.

### Дополнительная информация:

Issue reported from  Round ID: 64521 (Tau Ceti Classic (RU))
Testmerges: ```#13179# 13182# 13271# 13301# 13375```
Reporting client version: 515.1642

**Comment by Riverz1** [comment]
А я быстрее)
