### ISSUE TITLE
Указ возвышенного культа встать, показывает с турелью квины.

### ISSUE THREAD

**Issue by Risraivyn** [TauCetiStation/TauCetiClassic#13382]
#### Что должно было произойти
Обычный флаг.
#### Что произошло на самом деле
![image](https://github.com/user-attachments/assets/ba647d35-97c5-4aab-91dd-9ea1ed429f85)
![i1mage](https://github.com/user-attachments/assets/bdbe6950-2ad7-424c-84e3-4d9da0088fee)

### Шаги воспроизведения

Быть духом культа, приказать культам встать.

**Comment by LudwigVonChesterfield** [comment]
#13235
