### ISSUE TITLE
Конфеты из торгового автомата нельзя использовать на кухне.

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#1338]
#### Подробное описание проблемы
Candy купленная в торговом автомате не может использоваться в candy machine, хотя имеет тот же спрайт и описание, что и приготовленная вручную.
#### Что должно было произойти
Ленивый повар смог использовать конфету из автомата.
#### Что произошло на самом деле
You have no idea what you can cook with this the candy.
#### Как повторить
Купить конфету в автомате и сравнить с такой же собственного производства.

**Comment by Dennok** [comment]
Это защита от пиратов.
