### ISSUE TITLE
РД и ученые не имеют доступа в хранилище плат.

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#1339]
#### Подробное описание проблемы
Глава исследований не имеет доступа в хранилище плат.
#### Что должно было произойти
РД должен был зайти в хранилище плат без проблем.
#### Что произошло на самом деле
Дверь директору не открылась, ИИ открывать не хотел, ему пришлось искать робототехника, у которого доступ туда есть.
#### Как повторить
Проверить доступ "Technical Storage" у РД, ученых и робототехника

**Comment by Dennok** [comment]
Ученым нет, но вот РД надо.

**Comment by SpaiR** [comment]
Обсудили, сказали, что учёные лутали хранилище плат, а РД - первый, кто это делал. Поэтому, вроде как там и было задумано.

По итогу решили, что нужно для полноты картины забрать доступ и у робототехников, чтобы никому обидно не было.

**Comment by DeadOberst** [comment]
Но ведь станция научная.

**Comment by igigin** [comment]
>Но ведь станция научная

Ну раз научная, то всем ученым фуллаксесс теперь выдадут.

>запретить использовать до ЧП и поставить двери на болты

Так зачем, если и так хорошо. А для особых случаев у вас есть всякие хопокапитаны.

**Comment by DeadOberst** [comment]
Как бы то ни было, считаю что РД доступ нужно вернуть.

**Comment by WallShrabnic** [comment]
Зачем РД и учёным доступ в хранилище плат, когда есть отличный конструктор этих самых плат под боком?

**Comment by Skippeer12** [comment]
>Зачем РД и учёным доступ в хранилище плат, когда есть отличный конструктор этих самых плат под боком?

Ну например для того чтобы взять плату для РнД если его сломают, протолат например.
Ну и в хранилище не хватает деталей для машинерии.

**Comment by StrikS** [comment]
Шобы тырить платы и сразу повышать уровни исследований! Элементарно же.

**Comment by igigin** [comment]
>если его сломают, протолат например.

А с каких пор у нас ученые всякие ремонтом машинерии занимаются?

**Comment by Skippeer12** [comment]
>А с каких пор у нас ученые всякие ремонтом машинерии занимаются?

С тез самых, с которых сами её строят.

>Шобы тырить платы и сразу повышать уровни исследований!

Бегать по станции чтобы поднять научку, такое себе занятие.

**Comment by dred1792** [comment]
Ну, если я не ошибаюсь, то при наличии ресурсов научку можно поднять даже не покидая отсека.

**Comment by Skippeer12** [comment]
Без них тоже.

**Comment by igigin** [comment]
>С тех самых, с которых сами её строят.

Ну пускай тогда и двери взламывают.

**Comment by dred1792** [comment]
Уровни исследований для открытия плат РнД просто смешны. Вот абсолютно ничего не мешает в самом начале раунда сделать набор запасных.

**Comment by StrikS** [comment]
Только вот исследование это неинтересная рутина и с этого бы стоило начать. Кодить я это конечно не буду...

**Comment by dred1792** [comment]
Ну, тогда можно не заходить за учёного и не париться насчёт отсутствия доступа в хранилище плат, в чём проблема?

**Comment by Uvash** [comment]
Тогда уж положите туда детальки для телекомов и запас не большой т2 деталей

**Comment by P-20** [comment]
Туда нужен доступ лишь ради двух пар изоляционных перчаток, и доступ туда должен быть только у роботистов, они  при желании могут печатать и пополнять платы на складе. А то хотите сделать, чтобы РД, ученые и роботисты бежали лутать две пары перчаток.

**Comment by Skippeer12** [comment]
Не знаю где ты там увидел две пары перчаток, всегда была одна.
Ну и толку от тех плат, если без деталей ты её не соберешь.

Да и у РД должен быть повышен доступ, не только в хранилище плат, но и базовый доступ в мед.блок, генетику.
Ну и вообще всем главам выдать базовый доступ в мед.блок. А то прям вообще не комильфо.

**Comment by CryptoKisik** [comment]
Очень странно, что роботех имеет доступ, который не имеет РД. Выглядит достаточно забавно. Как начальник, он должен контролировать все действия своих подчиненных. А тут роботех ушел в хранилище плат и сидит, режет жертв и емагает роботов. А РД то попасть туда не может.

**Comment by WallShrabnic** [comment]
Так заберите доступ у роботеха

**Comment by igigin** [comment]
>Так заберите доступ у роботеха

Так ведь так и сделаем:

>По итогу решили, что нужно для полноты картины забрать доступ и у робототехников
