### ISSUE TITLE
Слиперы на начало раунда не имеют колб для диализа.

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#1340]
#### Подробное описание проблемы
В слиперах нет больших колб на старте.
#### Что должно было произойти
Слиперы должны быть как раньше с большой колбой.
#### Что произошло на самом деле
Слиперы в медбее, на астероиде и шаттлах ролек не укомплектованы для диализа. 
#### Как повторить
Получить обдолбавшегося пациента. Выкачивать из него все дерьмо в бумажные стаканчики.
#### Дополнительная информация:
Фиксы дюпов это хорошо, но никто никогда не позаботится о больших колбах заранее, особенно на астероиде.

**Comment by SpaiR** [comment]
Так и задумано, вставляйте колбу заранее.

**Comment by DeadOberst** [comment]
Слишком хардкорно для наших космонавтиков. Верните как было.
Нерфоцирк не нужен.

**Comment by ZVee** [comment]
Тем кто фиксил дюп. колб, должны были их перенести в initialize() и удостовериться что он не срабатывает больше никогда, кроме запуска сервера.

**Comment by SpaiR** [comment]
Так то логично, что колбы нет изначально, так что не видел и не вижу в этом ничего плохого. Сэйм щит, что и жаловаться на неподключённое крио.

**Comment by ZVee** [comment]
Слегка путаешь - в крио то колбы есть со старта раунда (кстати, возможно тоже дюпаются).

**Comment by dred1792** [comment]
Они рядом так-то лежат, а не в крио.

**Comment by Dennok** [comment]
Почему не сделали чтоб колба была нужна для постройки слипера?

**Comment by Dennok** [comment]
Кстати, есть колбы в хранилище медецинском, целая коробочка, правда только по 100. но темнеменее.

**Comment by SpaiR** [comment]
> в крио то колбы есть со старта 

Крио, если я всё правильно помню, нужно к охладителю подключать, настраивать его. Я про это говорил и приводил как пример того, что итсокей, что не везде всё всегда готовое.

Другой пример: сразу запущенная синга/тесла или сразу настроенные соляры. Степень сравнения хоть и разная, но суть одинаковая.

**Comment by dred1792** [comment]
По 50, если быть точным. А колбы по 100 в автолате сделать можно.

**Comment by ZVee** [comment]
А, точно, забыл что лежат рядом.

> Почему не сделали чтоб колба была нужна для постройки слипера?

Это слегка глупо с точки зрения дизайна.

**Comment by Dennok** [comment]
А для протолата, и печатного станка для плат не глупо?

**Comment by Dennok** [comment]
Хотя там ненльзя вынуть колбу, поэтому вероятно логтично что можно построить и без колбы.

**Comment by ZVee** [comment]
В этом и суть, если машина может работать без такого-то предмета - значит требовать его при постройке необязательно. Собственно стакан требуется только для диализа, и слипер без него может работать во всех остальных случаях.

**Comment by DeadOberst** [comment]
Никакой проблемы с колбами в построенном слиппере.
Проблемы будут с отсутствующими колбами во всех стартовых слиперах. Делать диализ колбами по 50 - то еще извращение.

**Comment by Dennok** [comment]
Пффф, попробуй делать диализ мензурками.

**Comment by dred1792** [comment]
Зайти в соседний отдел за колбами на 100 религия не позволяет?

**Comment by Dennok** [comment]
А ролькам достаточно прост онамаппить, ну и на шахтерку.

**Comment by DeadOberst** [comment]
Ясно.

Если все так просто, почему ученым выдали раздатчик кислоты?

**Comment by ZVee** [comment]
>Если все так просто, почему ученым выдали раздатчик кислоты?

Претензия на самом деле такая себе. Это было уже довольно давно и у нас мнение может меняться постоянно, тогда дали - сегодня решим что надо отнять и отнимем. Т.е любое изменение которое было когда-то сделано - совсем не означает что так будет всегда, те же тазеры внезапно могут снова стать теми какими были изначально и таких ситуаций может быть море.

**Comment by Skippeer12** [comment]
Шахтеры будут страдать.

**Comment by CryptoKisik** [comment]
Шахтеры не будут по причине того, что у них есть автолат в Карго. Заспавнился, экипировался, взял колбу и пошел на шахтерку. А вот на счет всей темы. Все же, стоит добавить. Не раз было, когда ты просишь Карго или РНД дать тебе пару стеклянных колб по 100, а они посылают тебя или игнорируют.
