### ISSUE TITLE
[Proposal]  Гипоспрей QoL

### ISSUE THREAD

**Issue by NeOchenLord** [TauCetiStation/TauCetiClassic#13413]
### Описание

Играя на СМО, очень удобно иметь склянки с разнообразными препаратами и в зависимости от ситуации заливать их по мере необходимости в гипоспрей, чтобы мгновенно администрировать лекарства даже сквозь риги.

Единственная проблема этой тактики - то, что приходится отдельно брать каждую склянку и тыкать ей по гипоспрею, чтобы налить туда препарат. Обычный шприц, в свою очередь, способен сам доставать жидкости из баночек, поэтому в шприц возможно в пару кликов набрать микс из 3 лекарств.

Мое предложение - дать возможность нажать гипоспреем по контейнеру с жидкостью чтобы забрать немного жидкости (5 юнитов за клик). Дополнительно, можно добавить переключатель на сам гипоспрей чтобы можно было как шприцом ещё и выливать жидкости в склянку, без необходимости вкалывать всё живой кукле.

**Comment by ZER0-In** [comment]
Не дубликат? Это вроде пару раз предлагали. Но каждый раз отказывались такое реализовывать по надуманным причинам.
