### ISSUE TITLE
Ксеносы не могут в родные языки будучи пиратами

### ISSUE THREAD

**Issue by CryptoKisik** [TauCetiStation/TauCetiClassic#1343]
#### Подробное описание проблемы
Ксеносы, которые стали ролью "пират" не могут в свои языки.

#### Что должно было произойти
Ксеносы должны мочь в свой язык, будучи пиратом
#### Что произошло на самом деле
Ксенос не может в свой язык. Не может говорить и не понимает.
#### Как повторить
Стать пиратом будучи ксеносом
#### Дополнительная информация:
Тестировалось будучи кисиком.

**Comment by ZVee** [comment]
Хм, вероятно мой давний просчет, однако пираты должны были форситься людьми, а ксеносы лишь подразумевались как будущее расширение, так что кроме людей в текущем виде режима там быть никого не должно.

**Comment by CryptoKisik** [comment]
Как вариант. Возможно связано с тем, что люди спавнятся лысыми и голыми. Тобишь в стандартной, не настроенной кукле. И в этой кукле имеется язык пиратов. 
Что правда, не тестил знание языков пирата, если при эклере ты выбирал персонажа со знанием языка ксеносов.

**Comment by ZVee** [comment]
Нет, как раз люди спавнятся от настроек персонажа из префов по дефолту, а языки насильно обнуляются режимом и выдается гуттер, потому что расчет был только на людей.

**Comment by Kurshan** [comment]
Пираты дед
