### ISSUE TITLE
Не работает ИВЛ "рот-в-рот", пока кукла еще жива.

### ISSUE THREAD

**Issue by ZER0-In** [TauCetiStation/TauCetiClassic#13436]
#### Что произошло
Когда чел задыхается и вот-вот умрет, а у тебя нет медицины, казалось бы его можно спасти проведя ИВЛ "рот-в-рот". Но прицелившись на рот куклы, хелп интентом ты пытаешься разбудить куклу. Из-за чего она умирает. НО ЗАТО У ТРУПА ЭТО РАБОТАЕТ.

**Comment by Oz1Es** [comment]
прост это было придумано для некрофилов

**Comment by Danistans2** [comment]
Можно пошаманить вот здеся с условием проверки

```
/mob/living/carbon/human/helpReaction(mob/living/carbon/human/attacker, show_message = TRUE)
	var/target_zone = attacker.get_targetzone()
	var/obj/item/organ/internal/heart/Heart = organs_by_name[O_HEART]
	if(health < (config.health_threshold_crit - 30) && target_zone == O_MOUTH)
		INVOKE_ASYNC(src, PROC_REF(perform_av), attacker)
		return TRUE
	if(Heart && Heart.parent_bodypart == target_zone && Heart.heart_status != HEART_NORMAL)
		INVOKE_ASYNC(src, PROC_REF(perform_cpr), attacker)
		return TRUE
	if(attacker != src || !apply_pressure(attacker, target_zone))
		if(target_zone == O_MOUTH && attacker == src)
			attacker.force_vomit(src)
		else
			help_shake_act(attacker)
	return TRUE
```

Путь:
code/modules/mob/living/carbon/human/human_attackhand.dm

**Comment by DarthSidiousPalpatine** [comment]
Так как бы:
![image](https://github.com/user-attachments/assets/a420fe82-0674-474e-afaa-c41860f4aba4)
Работает когда в крите, по идее?
А хотя зачем там -30. Уберите -30 и будет работать точно ток в крите.

**Comment by Danistans2** [comment]
> Так как бы: ![image](https://private-user-images.githubusercontent.com/21008918/358837492-a420fe82-0674-474e-afaa-c41860f4aba4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODc4NDQsIm5iZiI6MTcyMzg4NzU0NCwicGF0aCI6Ii8yMTAwODkxOC8zNTg4Mzc0OTItYTQyMGZlODItMDY3NC00NzRlLWFmYWEtYzQxODYwZjRhYmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDA5MzkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMDg2YjEzYzAwNWY0NjljNDVjMjE1YWMzMWQ3YTc5NjdlY2FkNTk5ODRhOGMzNGIzYjNhYTJlMzAxYWE0Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L7uGiPDm_ZzKo9_mEz3XCCTkW9WWRCbzVu209s20F4o) Работает когда в крите, по идее? А хотя зачем там -30. Уберите -30 и будет работать точно ток в крите.

Ща протестю, как раз дриммейкер открытый

**Comment by DarthSidiousPalpatine** [comment]
Просто если выдать работу не только в крите - то будет конфликтовать с пальцами в рот для тошнения
