### ISSUE TITLE
Баг при использовании железы слайма на игроках.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#1344]
#### Подробное описание проблемы
Если всадить игроку железу слайма, и после того как его тело распадется на три части, убить разумного слайма, то игрок сможет общаться, и разговаривать с игроками, хотя при экзамайне он мертв, и у него на слайме миллион урона всех видов.

#### Что должно было произойти
Он должен был умереть, и не общаться с персоналом

#### Что произошло на самом деле
Слайм говорил как живой, хотя не мог двигаться и был мертв.

#### Как повторить
Применить на человека железу слаймов, подождать пока его гибнет и он распадется на три слайма, убить разумного слайма, смотреть как он разговаривает за труп слайма.

#### Дополнительная информация:
Вроде как работает, лишь пока слайм-игрок не размножится еще раз.

**Comment by Raschert0** [comment]
Нужно бы ещё проверить на слаймоигроках, которые через экстракт. Что-то мне подсказывает, что там так же

**Comment by Motzord** [comment]
Чем-то пофикшено ибо не воспроизводится

**Comment by Deahaka** [comment]
Возможно рефактор сей-кода от воласа помог
