### ISSUE TITLE
залезание в стены с помощью подоконника 

### ISSUE THREAD

**Issue by KatoMarika** [TauCetiStation/TauCetiClassic#13465]
#### Что должно было произойти
Невозможно построить стену в одном тайле с подоконником/невозможно залезть в стену на одном тайле с подоконником. 
#### Что произошло на самом деле
![image](https://github.com/user-attachments/assets/c81b1342-a6a1-4498-a911-5753312e5357)
![image](https://github.com/user-attachments/assets/497619e9-8e01-4a10-8f92-8263e0bdd842)

**Comment by Oz1Es** [comment]
такое и с ящиками

**Comment by Oz1Es** [comment]
такое со всеми предметами на которые можно себя перетащить и перенести

**Comment by volas** [comment]
Подоконники работают как надо, проблема в стене и подоконниках на одном тайле - такое не должно происходить. Лучше репортнуть именно эту проблему и как так получилось.
