### ISSUE TITLE
Комбат белт имеет спрайт обычного пояса на кукле.

### ISSUE THREAD

**Issue by CryptoKisik** [TauCetiStation/TauCetiClassic#1347]
#### Подробное описание проблемы
У комбат белта нюкеров спрайт обычного инженерного пояса. Желтенький.
#### Что должно было произойти
Одевая комбат пояс ты должен быть кровавокраный, как дедсадовец, только нюкер.
#### Что произошло на самом деле
Ты кровавокрасный, с желтым поясом.
#### Как повторить
Одеть комбат пояс.

**Comment by Kurshan** [comment]
Пофиксил уже у себя в одном из Пр-ов. Если кто не забудет, заасигните это на меня.

**Comment by CryptoKisik** [comment]
Возможно еще не замержили. Просто вчера будучи в нюке лишний раз удостоверился. Но, если пофикшено, прошу закрыть.

**Comment by dearprincesscelestia** [comment]
Печь идет про ПР из будущего.
