### ISSUE TITLE
РП рева не РП

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1348]
#### Подробное описание проблемы
При РП реве по идее экипаж-революционеры должны взять станцию под контроль и удержать ее. После выпила глав вызывают шаттл и все летят на ЦК.
#### Что должно было произойти
Революционеры должны остаться на станции и удержать ее. На ЦК за убийство глав и захват станции их должны выпилить. 
#### Что произошло на самом деле
Революционеры захватили станцию, убили глав и свалили на шаттле на ЦК.
#### Как повторить
Ждать выпад рп ревы.
#### Дополнительная информация:
Предлагаю при реве чутка менять задачи.
Например:
1) Взять станцию под свой полный контроль.
2) Запустить специальное устройство\написать на емагнутой коммуникаторке новым хозяином.
3) На станции к концу раунда должны оставаться более 50% активных живых работников.
Так РП рева действительно будет РП.

**Comment by Raneman** [comment]
> Так РП рева действительно будет РП.
хах
хааааахахахахаха
