### ISSUE TITLE
Мезонки видят действия за пределами видимости

### ISSUE THREAD

**Issue by Seached0** [TauCetiStation/TauCetiClassic#13497]
#### Что должно было произойти
Мезонки не дают тебе знать что взял/на кого посмотрел/кого ударил персонаж за стеной
#### Что произошло на самом деле
![image](https://github.com/user-attachments/assets/70eea3c9-ec6f-4ba5-8e12-32d8aab40c26)
![image](https://github.com/user-attachments/assets/b64af218-9129-49f1-9bd1-f8eda54b9f44)

### Шаги воспроизведения

1. Надеть мезонки
2. Активировать их
3. Подождать пока кто-то на кого-то посмотрит/положит в рюкзак/толкнёт за стеной

### Дополнительная информация:

Issue reported from  Round ID: 64775 (Tau Ceti Classic (RU))
Testmerges: ```#13310# 13428# 13481# 13488```
Reporting client version: 515.1642

**Comment by Deahaka** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/8999
