### ISSUE TITLE
[Proposal] Переделать мусорку в мусоро-сжигателе.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1349]
Вот вам немного рассуждения на тему этого пропозала, мусоро-сжигатель, должен сжигать мусор ведь так?

Но чтобы вкинуть в камеру сжигания мусор (котов например) нужно открывать его через шлюзовую систему (которая там не идеальная и вообще) и когда ты открываешь этот шлюз для закидывания туда мусора, тебя высасывает в вакуум (где ты благополучно умираешь).

Предлагаю переделать мусорку в мусоро-сжигателе и чтобы она ввела не в космос, а в саму камеру для сжигания.
Вот как оно выглядит сейчас.
![41](https://cloud.githubusercontent.com/assets/18488106/24725903/0c461bc2-1a59-11e7-9bf6-c06c5b735881.png)

Вот как (я бы хотел) должно выглядеть.
![default](https://cloud.githubusercontent.com/assets/18488106/24726366/cdcc0cc4-1a5a-11e7-9c62-3816838e9d8e.png)

**Comment by CryptoKisik** [comment]
Тогда стоит добавить возможность сжигать вещи до пепла. Учитывая градус и интенсивность горения, от тела или же любого пластикового (и даже металлического) предмета должны оставаться лишь воспоминания.

**Comment by dearprincesscelestia** [comment]
И, возможно, добавить туда отдельную конвейерную ленту в карго на сортировочную?

**Comment by Skippeer12** [comment]
Ну вы это, далеко не забегайте, надо сначала переделать мусорку для начала.

**Comment by WallShrabnic** [comment]
У нас сжигание нормально не работает, а так хоть есть шанс невозврата
