### ISSUE TITLE
Сломалась Гамма

### ISSUE THREAD

**Issue by F0xiq** [TauCetiStation/TauCetiClassic#13554]
### Описание

Что-то сломалось на зимней Гамме (на обычной не смотрел)
![Шахтерская](https://github.com/user-attachments/assets/04b101d8-f341-42fe-93d4-93353340d775)

**Comment by Tap0r** [comment]
это торговцы

**Comment by Tap0r** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/13391/commits/090c2ea30c12a99d538880728c4812fecf0c9fb7
залил фикс, обновите тм и норм буде или замержте уже похуй там отдельными потом прчиками проще допилить будет
