### ISSUE TITLE
Фороновая дверь из менералов потеряла анимацию открытия

### ISSUE THREAD

**Issue by omejka** [TauCetiStation/TauCetiClassic#1357]
#### Подробное описание проблемы
Дверь из форона потеряли анимацию открытия
#### Что должно было произойти
Анимаци должна была проигрыватся
#### Что произошло на самом деле
Дверь мгновенно открывается
#### Как повторить
Построить дверь,открыть,заметить отсутствие анимации

**Comment by Raschert0** [comment]
Нет, это скажу я.
А точнее скажу, что у меня не получилось повторить баг

**Comment by SpaiR** [comment]
>Спаир опять скажет,што надо в игру играть и все уже зарепортилипофиксиликоко,да?

Ты дурак?

**Comment by omejka** [comment]
Да че ты(

**Comment by omejka** [comment]
Да ну што ты(
2

**Comment by ZVee** [comment]
Проверил все двери - с кликами все хорошо, а вот анимация у фороновых действительно умерла. А с кликами плохо у нее - потому что анимации нет и кажется что надо миллион раз нажимать, а на деле дверь "за кадром" уже открывается в этот момент.

**Comment by omejka** [comment]
Суть в том,что когда я пропознул двери аналиенов,ты сказал что они не проводят атмос,надо в игру играть мда
Как-будто алиены у нас каждый день как режим выпадают
А прочитав о дверях тут,увидел,что вы написали что их непроницаймость это баг и все,

**Comment by ZVee** [comment]
Суть в том, что Спаир тебе тогда довольно по делу ответил хоть и в такой форме - мы их оставили не пропускаемыми, но был исправлен баг состояния в котором они могут внезапно начать это делать.
Но в целом да, эти двери не задумывались такими.
Мог бы вначале в чате узнать как обстоит дело с текущей работой, а потом без дезинфы создавать пропозал если в этом была необходимость. И вот тут в ищу - "Двери из минералов потеряли анимацию открытия" - но при этом "не тестил" - так и писал бы тогда только про форон, ну или пометку ниже  - возможно сломались и другие.

**Comment by WallShrabnic** [comment]
Jesus Christ, Marie, это мИнералы
