### ISSUE TITLE
Нет спрайта огня на человечке

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#13583]
#### Что должно было произойти
На персонаже, когда он горит, появляется спрайт горящего огня
#### Что произошло на самом деле
На горящем персе нет оверлея огня

### Шаги воспроизведения

Поджечь персонажа (любым способом)

### Дополнительная информация:

Issue reported from  Round ID: 65236 (Tau Ceti Classic (RU))
Testmerges: ```#13348# 13541```
Reporting client version: 515.1640

**Comment by volas** [comment]
дежурное сообщение с удивлением по поводу как и когда это сломали

**Comment by simb11** [comment]
только сегодня (в раунде 65236) заметил

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/livaem-pochemu/44058/182
