### ISSUE TITLE
Взрослая лярва

### ISSUE THREAD

**Issue by DarkFurrSss** [TauCetiStation/TauCetiClassic#13640]
#### Что должно было произойти
Взрослая сахарная лярва (Что не мотылек) может надеть наушник
#### Что произошло на самом деле
Взрослая сахарная лярва (Что не мотылек) не может надеть наушник

### Шаги воспроизведения

1. Зайти за купленную в карго сахарную лярву (Что не мотылек)
2. Попытаться надеть наушник

### Дополнительная информация:

мб было какое-то нововведение что нельзя теперь надевать наушник, но выглядит это странно
Issue reported from  Round ID: 65487 (Tau Ceti Classic (RU))
Testmerges: ```No test merges```
Reporting client version: 515.1644

**Comment by Deahaka** [comment]
Особенности строения тела!
