### ISSUE TITLE
Зоны бронежилета.

### ISSUE THREAD

**Issue by psebash** [TauCetiStation/TauCetiClassic#1365]
#### Подробное описание проблемы
Когда на хумане находится бронежилет, то он защищает от укола все части тела, ниже головы (аля риг)
#### Что должно было произойти
Он должен защищать от укола только зону честа
#### Что произошло на самом деле
От уколов защищено все тело, ниже головы
#### Как повторить
Надеть на кого-нибудь бронежилет и попытаться уколоть в руку/ногу
#### Дополнительная информация:
N/A

**Comment by omejka** [comment]
Ну это же будет значить,что любой мимохуй со шприцом хлорки сможет ввести  офицеру смертельную дозу за один клик!!!!!!

**Comment by Lancer411** [comment]
Если полным шприцем на харме колоть, то вводится случайное количество кубиков, но не больше 10.

**Comment by Raschert0** [comment]
Какая разница сколько, если этого всё равно будет достаточно, чтобы жертва заснула за несколько секунд

**Comment by Skippeer12** [comment]
Кстати из-за этого и не работает ручка тритора.

**Comment by RichardJones1** [comment]
Руки и ноги защищены только у riot suit и брони маринов. У остальных только грудак и гроин. Закрываю ишью.
