### ISSUE TITLE
Космобайки и пираты в крите.

### ISSUE THREAD

**Issue by CryptoKisik** [TauCetiStation/TauCetiClassic#1372]
#### Подробное описание проблемы
Если пират (возможно и любой хуман) слетел с байка в крит, то он может моментально на него залезть, продолжая кататься. Однако он не сможет никого задавить и не сможет самостоятельно слезть.
#### Что должно было произойти
Человечек должен лежать рядом с байком.
#### Что произошло на самом деле
Человек в крите(возможно в простом стане) вернулся на байк и поехал.
#### Как повторить
Сбить с байка лвапой или нашпиговать тазером/резиной.
#### Дополнительная информация:
Сегодня так же получилось, что когда я сбил пирата лвапой, тот залез на байк и поехал. Однако спрайт человека остался на месте, а байк уехал. И стреляя по самому спрайту пирата - я его убил. Хотя в этот же момент байк гонял по спейсу.

**Comment by Forrya** [comment]
Просто убрать пиратов как режим.

**Comment by StrikS** [comment]
Форе дай возможность он и нюцку уберет, оставив только эксту. Нет, спасибо.
