### ISSUE TITLE
Нет миниатюрок из ДнД.

### ISSUE THREAD

**Issue by BornToKill2** [TauCetiStation/TauCetiClassic#1375]
#### Подробное описание проблемы
В чайные раунды, особенно в эксту, нужно коротать время, ДнД самое подходящее.
#### Что должно было произойти
Я должен был собрать группу, пойти в библиотеку, и играть.
#### Что произошло на самом деле
Там не было миниатюрок.
#### Как повторить
Никак.
#### Дополнительная информация:
Добавьте плес.

**Comment by Shudyn** [comment]
Что такое миниатюрки?

**Comment by WallShrabnic** [comment]
Вся суть аутистов в одном ишью - мы не хотим в интересные ситуации, мы хотим коротать время! К слову, минитюарки уже есть, закрывай ишью

**Comment by igigin** [comment]
Время коротать с ДнД и всякими миниатюрками можно и вне сски.
