### ISSUE TITLE
Не смог запустить локал. сервак из-за ошибки.

### ISSUE THREAD

**Issue by DarkSauron71** [TauCetiStation/TauCetiClassic#1376]
#### Подробное описание проблемы
Ошибка при создании своего сервера для теста ролек, что бы не портить катки людям на сервере Тау
#### Что должно было произойти
Всё как по гайду без проблем http://tauceti.ru/wiki/Server_Startup
#### Что произошло на самом деле
Ошибка BYOND Error: corrupt headers in world file
#### Как повторить
Нууу, скачать сервер и  попытаться его запустить.
#### Дополнительная информация:
Искал ответ на ошибку, пишут, что битый файл возможно и можно восстановить при помощи софта. Но это не помогло..

**Comment by SpaiR** [comment]
Такие вопросы нужно на форуме спрашивать. Трекер гита не для этого

**Comment by StrikS** [comment]
На https://www.youtube.com/watch?v=3WNqYkW9btA
