### ISSUE TITLE
Телепорт спавненной куклы при начале раунда

### ISSUE THREAD

**Issue by YulianR** [TauCetiStation/TauCetiClassic#1377]
#### Подробное описание проблемы

Если до начала раунда заспавнить хумана через Debug > Spawn, и вселиться в него, то при начале раунда персонажа телепортирует на станцию в ассистентскую, и заносит в крю манифест. Под именем unknown, da.

#### Что должно было произойти

ничего

#### Что произошло на самом деле

то что в первом пункте

#### Как повторить

сделать то, что описано в первом пункте

**Comment by dred1792** [comment]
Чтобы он телепортировался, ему ещё и сикей нужно прописать, если не ошибаюсь.

**Comment by ZVee** [comment]
А зачем до официального старта раунда и обработки определенного ряда вещей влетать в раунд? (Это самый первый вопрос который обычно возникает с педальными проблемами и педалью которая делает то, что как бы не надо и на что игра не задумывалась).

**Comment by TungstenOctopus** [comment]
какая разница зачем, прецедент есть, баг есть, я его зарепортил, вам уже решать достоин ли он внимания или во всем виновата педаль

**Comment by ZVee** [comment]
Ну мыслить должен так репортя баг как педаль - педальная ли это проблема и может ли она возникнуть в обычных условиях? В большинстве случаев баги вызванные неумелым использованием кнопок мы не рассматривает.

**Comment by YulianR** [comment]
Ок, в следующий раз просто скажу о баге в асей

**Comment by Skippeer12** [comment]
Пофикшено. Теперь куклы которые заспавнили при инициализации никуда не спавнит, они остаются на месте.
![image](https://user-images.githubusercontent.com/18488106/35795777-edce96c4-0a62-11e8-94bb-9fb206f960cf.png)
