### ISSUE TITLE
Нет шклянок в слиперах

### ISSUE THREAD

**Issue by psebash** [TauCetiStation/TauCetiClassic#1378]
#### Подробное описание проблемы
В слиперах теперь со старта нет шклянок
#### Что должно было произойти
Они должны быть
#### Что произошло на самом деле
Их нет
#### Как повторить
Попытаться сделать диализ
#### Дополнительная информация:
Кто-то фиксил баг, то что после сбора в нем не должны появляться шклянки, вот после етого все работает не так.

**Comment by Shudyn** [comment]
1000 склянок в медбее валяется. Даже если все истратили, то РнД в двух метрах, за стеной считай.

**Comment by dred1792** [comment]
#1340

**Comment by psebash** [comment]
Это все хорошо,
