### ISSUE TITLE
Рокетлаунчер для мехов не запускает ракеты

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1379]
#### Подробное описание проблемы
Ракетомет при стерльбе не запускает ракеты, а дропает спрайт ракеты с именем item. 
#### Что должно было произойти
Ракеты должны запускаться и взрываться.
#### Что произошло на самом деле
Ракеты не запускаются.
#### Как повторить
Воспользоваться рокетлаунчером.

**Comment by SpaiR** [comment]
@Forrya Просьба читать рекомендации по созданию ишью. Сейчас уже ладно, но в следующий раз обрати внимание:
1. название должно иметь
2. один ишью - один баг
