### ISSUE TITLE
Ящик квартирмейстера потерял несколько вещей.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1380]
#### Подробное описание проблемы
В ящике квартирмейстера отсутствуют такие вещи как, запасной катридж для ПДА, шлем для пожарного костюма(хотя сам костюм там есть), ну и раньше у него вроде там был болон, синий который большой.
#### Что должно было произойти
Вещи должны там быть.
#### Что произошло на самом деле
Космо-коты украли всё.
#### Как повторить
Зайти за квартирмейстера

**Comment by Raschert0** [comment]
Картриджи у него на столе рядом лежат
