### ISSUE TITLE
Клинботы не выполняют никаких действий

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#1381]
#### Подробное описание проблемы
Клинботов  окончательно добили. Они отказываются что-либо делать, просто висят на месте.

#### Что должно было произойти
Они должны были патрулировать/чистить полы. 

#### Что произошло на самом деле
Клинботы рассматривают многогранность плитки пола. 

#### Как повторить
Понаблюдайте за поведением клинботов. 

#### Дополнительная информация:
@rascher

**Comment by Raschert0** [comment]
Что? Я их не трогал же

**Comment by SpaiR** [comment]
Конкретно скажи откуда клинбот запускался.

**Comment by Belfogor** [comment]
Клинбота установили возле входа в роботехнический отдел, в центральном коридоре. Вообщем, с места он не тронулся. Так же видел висящих клинботов возле мед бея, опять таки в том же центральном коридоре. Если ты конечно об этом.
