### ISSUE TITLE
Кривая работа автобанов за варны

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#1382]
#### Подробное описание проблемы

Варн криво работают за последние три варна 3 бана

#### Что должно было произойти

Нормальные страйки по варнам и возможность хоть как то их снять

#### Что произошло на самом деле

Бан каждый варн

#### Как повторить

Заварнить, там с неким шансом идёт баг

**Comment by vanya1996** [comment]
Вот у меня так же, каждый варн даёт бан

**Comment by Skippeer12** [comment]
Почему ещё не закрыли, у админов уже оторбрали этот механ.
