### ISSUE TITLE
Резиновые пули не наносят физический урон. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#1383]
#### Подробное описание проблемы
Резиновые пули перестали наносить физический урон.

#### Что должно было произойти
Они они должны были нанести урон!

#### Дополнительная информация:
(https://github.com/TauCetiStation/TauCetiClassic/blob/5a7266b0247e19df51033c8a3307c99918c2a004/code/modules/projectiles/projectile/bullets.dm#L19)

**Comment by Olt1771** [comment]
Я тебе по секрету скажу, но ето чинить ни кто не будет, ибо детектив при задержании будет фражить людей без армора. Т.к. у нас конченая система повреждений из-за которых после 3 пуль РЕЗИНЫ ту гуфнешься.

**Comment by Shudyn** [comment]
Тогда почему лвапа не прожигает насквозь? Она же мощная. Почему не умирают от 1-2 пуль из пистолета в сундук? ИРЛ же умирают многие от внутренних повреждений.
Просто нужно реворкать оружие и урон вообще.

**Comment by WallShrabnic** [comment]
Реворк не нужен, у нас не лайфвеб
