### ISSUE TITLE
Отвёртка не работает при гетто-операции на голову.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1384]
#### Подробное описание проблемы
Отвёртка при гетто-операции на голову не работает как ретрактор. Вместо этого врачь бьет пациента в глаза.
#### Что должно было произойти
Вместо выкалывания глаз отвёрткой должна проводится одна из ступеней операции.
#### Что произошло на самом деле
Вы выкололи пациенту глаза отвёрткой и не смогли продолжить операцию
#### Как повторить
Попробовать гетто-операцию на голове.

**Comment by ZVee** [comment]
Там этих операций на голову несколько штук, какая из и какой шаг? А вообще, при фэйлах в операции идет атака и это нормально, а еще учитывая шансы при гетто-операциях - забить пациента - дело всегда обычное было, но если там сломан конкретный тип и шаг - нужно больше инфы.

**Comment by P-20** [comment]
Там шанс очень маленький даже на специальном ложе. Из-за инструмента, если же используется обычный стол, то шанс еще меньше. Из-за это все сложно

**Comment by Skippeer12** [comment]
Любая операция на части головы, на глаза, на череп, на гематому.
Отвёртка работает как ретрактор, а после недавних изменений от Штрикса, шанс там минимум 50%, как написано.

И там нет никакой другой информации, ты просто бьешь человека в глаза и там не пишет что у тебя рука соскользнула или ещё что.

**Comment by Skippeer12** [comment]
Вот вам скриншот, делал на операционном столе, кусачки сработали, а отвёртка нет.
![251](https://cloud.githubusercontent.com/assets/18488106/25300267/e6730ad2-2713-11e7-9b77-c6e9eba17545.png)

**Comment by StrikS** [comment]
Я посмотрел в чем проблема, проблема в переопределенном проке /obj/item/weapon/screwdriver/attack. Он игнорирует проверку на стадию операции из прока  /obj/item/proc/attack.

Объяснение для Шкипера: из-за того, что у отвертки есть спецатака ослепления, она игнорирует характерную для всех item'ов проверку на возможность операции данным инструментом.

**Comment by Skippeer12** [comment]
Лучше бы пофиксил. Чем расписывал что сломалось. А ещё лучше выпилить отвёртку и переосмыслить гетто-хирургию в целовм. Где это видано что ломом можно ОТРЕЗАТЬ конечности?

**Comment by StrikS** [comment]
Иди переосмысляй, как принесешь мне табличку альтернативных хирургических инструментов широкой доступности я их введу в игру.
