### ISSUE TITLE
Нет возможности остановить воспроизведение глобального/локального саунда, включенного администраторами.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#1394]
#### Подробное описание проблемы
Если включить любую песню, музыку при помощи Кнопки в админ панели.  Возможности остановить ее кроме как отключить звук, нету. 
#### Что должно было произойти
Должна была быть кнопка - остановить глобальные/локальные звуки включенные администратором.
#### Что произошло на самом деле
Ее нет.
#### Как повторить
На сервере глобально/либо же в режиме Локально, запустить музыку
#### Дополнительная информация:
https://github.com/ParadiseSS13/Paradise/pull/6794

**Comment by ZVee** [comment]
Есть костыльный способ - включить пустой звуковой файл, ну, если вам прямо надо это как-то остановить пока не добавили возможность нормально это делать.

**Comment by Kurshan** [comment]
На Парадайзах так и реализовано, только одной кнопкой.

**Comment by ZVee** [comment]
Отправить нуль в прок и создать себе на жестком пустой файл чтобы костыльно выключать без кнопки проигрывание звука - это совершенно разные вещи.

**Comment by P-20** [comment]
@ZVee только этот костыль не будет работать. У нас музыка накладывается одна на одну, т.е. если зафорсить один звук, а затем еще один,можно и пустой, они будут играть вместе.

**Comment by ZVee** [comment]
А, так вы play local sound кнопку? Ну тогда вам этот порт не поможет. Локальные звуки всегда играют в рандомный канал, а кнопка расчитана на конкретный, т.е 777, т.е это под play server sound кнопку и только. В общем тут больше надо чем порт по ссылке.

**Comment by P-20** [comment]
Ну я вообще, хотел для глобала главное. Локал пускай,он все равно реже используется. А глобально не очень удобно костылем пользоваться, но вполне можно.

**Comment by ZVee** [comment]
Посмотрел глобальные - там вся суть в wait = 1 - из-за этого мой совет с ними таки работать не будет. Эта настройка составляет очередь из звуков, а без нее - можно былоб и костыльно стопить.

А в локал да - лучше ничего длинного не кидать, у него цель иная.

**Comment by Kurshan** [comment]
#1986
