### ISSUE TITLE
Позитронка из борга, появляющийся в начале смены.

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#140]
Originally reported by: **13 (Bitbucket: [shadence](http://bitbucket.org/shadence), GitHub: [shadence](http://github.com/shadence))**

---

Короче говоря, после убийства борга, выпадающая из него позитронка не имеет доступа к бинарному каналу, а также во время разговора получает имя персонажа, который стоит в сетьюпе.
А также будет видеть гостчат, хотя не проверено.

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/140

**Comment by KuzyXD** [comment]
Duplicate of #988
