### ISSUE TITLE
Невозможно манипулировать с проводами на камерах, если в помещение отключено питание.

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#1400]
#### Подробное описание проблемы
Если отключить в помещение (через АПЦ) подачу питания на машинерии (консоли, фабрикаторы и т.д.) невозможно будет манипулировать с проводами на камере. То есть не обрежешь кусачками, не воспользуешься мультитулом. 

#### Что должно было произойти
Я должен был утереть нос этому ИИ.

#### Что произошло на самом деле
Он меня переиграл. 

#### Как повторить
Не попадайтесь и не придется повторять.

**Comment by Raschert0** [comment]
#559
