### ISSUE TITLE
Шедоулинг может использовать карты/гарнитуру/карманы.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1401]
#### Подробное описание проблемы
Переродившийся шедовлинг может использовать карты/гарнитуру/карманы, цепляя их на свой невидемый джампсьют и уши.
#### Что должно было произойти
Шедоулинг должен страдать без карты и наушника с карманами
#### Что произошло на самом деле
Он взял карут капитана и наушник.
#### Как повторить
Поиграть за шедоулинга.
#### Дополнительная информация:
Без того сильный антагонист использует ещё дополнительную мощь чтобы гнобить станцию каждый раунд.

**Comment by Forrya** [comment]
Если они будут хотеть бегать с золотой картой - они и в руках ее тоскать будут.

**Comment by WallShrabnic** [comment]
Наушник не требует джампсьюта

**Comment by Skippeer12** [comment]
Минус один слот в руке
Это тебе не просто так

**Comment by Forrya** [comment]
Прост шанс выпада кеклингов, как и пиратов, нулем сделать. И чинить.

**Comment by WallShrabnic** [comment]
Шедоулинги полностью рабочие, а форя лох

**Comment by LudwigVonChesterfield** [comment]
И пусть простит меня ЗВе.
