### ISSUE TITLE
Баг за борга. Или потеря активного предмета при раздевании.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#1403]
#### Подробное описание проблемы
Если за борга раздевать человека, то если модуль активен, например дубинка, банка,или меч, то эта вещь пытается вложиться в слот человеку. Если слот неподходящий она просто выпадает. И взять ее никак нельзя обратно, а так же восстановить предмет в заряднике невозможно.

#### Что должно было произойти
Предмет не должен был вложиться в руку хуману

#### Что произошло на самом деле
Он выпал и нет возможности его подобрать
#### Как повторить
За любого борга активировать любой модуль-предмет, и при активном модуле раздевать человека.

**Comment by Skippeer12** [comment]
Не знаю как ты умудрился но снимать с хумана вещи активным модулем нельзя. Только если модуль не выбран с хумана можно стягивать вещи.
![image](https://user-images.githubusercontent.com/18488106/35795944-937bec66-0a63-11e8-82b1-4d9bbe1ab9f9.png)

**Comment by P-20** [comment]
Возьми синдиборга и поробуй раздевать лежачего хумана активным есвордом, или автоматом.

**Comment by Skippeer12** [comment]
Ты написал что станбатон тоже сломан.
Но не важно, синдиборгом тоже нельзя снимать одежду активным модулем.
![image](https://user-images.githubusercontent.com/18488106/35808615-0e8d89de-0a8f-11e8-8b26-c3e7635fa06c.png)
