### ISSUE TITLE
Баг с туррелями после их обновления.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#1407]
#### Подробное описание проблемы
 С каким-то шансом сбиваются настройки туррелей, и они не стреляют. Тогда приходится вручную в них все проставлять.

#### Что должно было произойти
Туррели должны запоминать настройки, и после перепадов электричества в сети, работать нормально с прежними настрйоками.
#### Что произошло на самом деле
Туррели с энергией и которые включены стрелять на поражение - ничего не делают.

#### Как повторить
Откачать энергию, и заного подключить. А возможно причина кроется в ином, Ращер наверное знает.
#### Дополнительная информация:
@Raschert0 @Rascher

**Comment by Raschert0** [comment]
После отключения света их нужно выключить/включить. Почему - нужно смотреть и фиксить, да
