### ISSUE TITLE
Баг со снятием ролей путем имплантов лояльности и святой воды.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#1414]
#### Подробное описание проблемы
Если Ревера/Гангера/Нюкера/Культиста 
Имплантировать/Снять роль путем святой воды.
Икона то что он является ролью для союзников не пропадет, она остается.
Когда он уже никак не должен быть ролью, тем более иметь иконку.

#### Что должно было произойти
Иконка должна исчезнуть.
#### Что произошло на самом деле
Она остается.
#### Как повторить
Стать революционером, получить имплант лояльности, иконка революционера остается.

**Comment by ZVee** [comment]
Касательно импланта - из всего перечисленного только рева им снимается и это так и должно быть.

**Comment by igigin** [comment]
>так и должно быть

Но зачем оставлять худ-иконки, если рольки нет?

**Comment by P-20** [comment]
@ZVee гангер разве не должно сниматься?
И да, если революция должна сниматься, то почему иконка остается для других игроков которые уже видели его ролью? А так же я указал что в случае с культистами - это святая вода.

**Comment by igigin** [comment]
Писать абсолютно всё через слеши, особенно учитывая их не равное количество, было странным решением, не добавляет понимания.
А ещё по названию абсолютно не понятно, что ты про худы и иконки, а не про сами роли.

**Comment by ZVee** [comment]
>Но зачем оставлять худ-иконки, если рольки нет?

Так я перечислил все то, что имплант **должен** снимать, и это только рева. Поэтому иконка должна только с ревы пропадать, т.к у других ролей роль то не должна отбираться.
В целом, у нас всегда имплант этот считался больше ролевой составляющей, но для ревы своего рода поблажка дана - правда затруднюсь сказать зачем.

>гангер разве не должно сниматься?

Нет.

**Comment by Raschert0** [comment]
Должно. Имплант защищает от ганга, значит он должен снимать ганг. Ну или гангер должен противиться импланту

**Comment by ZVee** [comment]
> Должно.

Нет, только на выдачу роли разве что, снимают генг другим методом (немного извращенным и фановым) - если интересно, можете его заспойлерить сами.

**Comment by P-20** [comment]
Ситуация. Революционер имплантируется имплантом.
После имплантации другие игроки видят над ним Иконку революционера, и он так же видет свою иконку. Но их иконки уже не отображаются.
Культист, выпил святой воды, снял с себя роль, для него иконка его пропала. Другие культисты видят над ним иконку культиста, хотя им он не является.

**Comment by P-20** [comment]
Роли да, уже нет. Но Иконка остается видимой.

**Comment by ZVee** [comment]
Да с иконками там проблемы, я как раз это в мобах чинить буду как и с худами разбираться в том самом ПРе который готовится - так как это все в планы входило. Ну, а касательно отбирания ролей - все работает как нужно.

**Comment by KIBORG04** [comment]
видимо я пофиксил рефактором худов
