### ISSUE TITLE
Спрайт ботинков перекрывает хвосты

### ISSUE THREAD

**Issue by YulianR** [TauCetiStation/TauCetiClassic#1418]
#### Подробное описание проблемы

![dreamseeker_2017-05-01_13-02-39](https://cloud.githubusercontent.com/assets/6051766/25577423/88e3ce94-2e6e-11e7-8b31-854844ea2a10.png)

#### Что должно было произойти

Собственно, хвост должен быть поверх ботинок

#### Что произошло на самом деле

Хвост залазит в ботинки

#### Как повторить

Надеть за кота или ящера любые ботинки (за ящера джекбутсы и воркбутсы)

**Comment by ZVee** [comment]
В этой #1091 сборной солянке уже репортили, но учитывая что там некорректно составлен репорт и вид названия которые репортам не стоит давать (ведет к дубликатам из-за затруднения поиска и отсутствия ключевых слов по которым можно былоб найти похожие репорты), то стоит оставить оба, т.к там все же и другие проблемы озвучены.

**Comment by YulianR** [comment]
Фикс заливать не надо?

**Comment by ZVee** [comment]
Только если невтерпеж фиксить то, что в ближайшее время и так будет исправлено.
