### ISSUE TITLE
Педальный шаттл отзывается при реве

### ISSUE THREAD

**Issue by SpaiR** [TauCetiStation/TauCetiClassic#1419]
#### Подробное описание проблемы
Педальный шаттл отзывается при реве
#### Что должно было произойти
Педальный шаттл не должен был отзываться
#### Что произошло на самом деле
Педальный шаттл отозвался
#### Как повторить
Вызвать педальный шаттл при реве с живыми лидерами ревы или командующим составом станции
#### Дополнительная информация:
@Raschert0 начинай уже проводить более тщательные тесты своих изменений, пожалуйста, твои без эффектные правки вводят в заблуждение честных админов.

**Comment by ZVee** [comment]
Я ему тогда предлагал сделать игнорирование на педальный вызов шаттла (а точнее false на фэйк рекол выставлять если педально вызывают), но он решил что пофиксит только баг с заданием. Поэтому не уверен что там есть его вина, т.к вроде бы про педальный вызов в ПРе тогда речи не шло.

**Comment by SpaiR** [comment]
Косяк в этом https://github.com/TauCetiStation/TauCetiClassic/pull/1326/files#diff-885b342612f3ce255568751ac4ddff7d
Я без понятия должен он отзываться, не должен. По итогу он отзывается и если раньше об этом хотя бы предупреждалось, теперь даже этого нет. Я конечно могу ошибаться, но всё же я считаю, что было проведено мало тестов из-за чего был сделан ложный вывод, что правок по ссылке выше будет досточно.

**Comment by ZVee** [comment]
Да, в этом плане ошибка (в том что удалили сообщение информирующее о автореколе).

Кто будет править - сделайте так: после подтверждения окна с "are you sure" (ну там где мы подтверждаем что действительно хотим вызвать шаттл) появляется второе окно при условии что фэйк рекол = true - и спрашивается -"хотите ли также отменить авторекол шаттла". Т.е для ролевых моментов должна быть возможность не затронуть автоотзыв шаттла. Думаю это не сильно будет напрягать, т.к эта настройка только при малфе и реве. А еще лучше - в окно с "are you sure" добавлять дополнительно третью кнопку в случае авторекола на true вида - "Yes and disable autorecall". Чтобы по двум окнам не кликать.

Так же хорошо бы в check antagonist добавить еще возможность регулировать эту настройку рядом со временем - что-то вида [время] [auto recall: yes/no]

Но в целом смотрите сами.

**Comment by P-20** [comment]
Аналогично и с малфом

**Comment by P-20** [comment]
В малфе хоть и смотрится логично. Но иногда режим багуется. И малф не может самоуничтожиться. И тогда либо рестарт, либо через шатл.

**Comment by Raschert0** [comment]
Для ревы то окошко не работало, так как оно для обычной, а не рп-ревы
