### ISSUE TITLE
Исчезновение кнопок resist, drop, throw

### ISSUE THREAD

**Issue by Gyaviste** [TauCetiStation/TauCetiClassic#1423]
#### Подробное описание проблемы

После того как кнопки по какой-либо причине кнопки скрываются с вашего экрана, они больше на нём не появляються.

#### Что должно было произойти

Кнопки должны снова появиться

#### Что произошло на самом деле

Кнопки не появились

#### Как повторить

Скрываем кнопки, например, засыпаем, потом просыпаемся - все остальные кнопки появляются а эти три нет.

#### Дополнительная информация:

У меня это произошло несколько раз, но именно тот когда я заметил причину это после анестезии.

**Comment by SpaiR** [comment]
@ZVee посмотришь?

**Comment by ZVee** [comment]
М-м, а кнопка "OOC > Toggle hotkey buttons" случайно не была задета?
