### ISSUE TITLE
Вылетает при игре за ИИ

### ISSUE THREAD

**Issue by ghost** [TauCetiStation/TauCetiClassic#1425]
#### Подробное описание проблемы
При игре за ИИ очень часто наблюдается вылеты клиента. Самый высокий шанс при попытки фолова камерами. Вероятность тем выше, чем больше ИИ совершает действия,(фолов камерами, перемещение обзора и т.д). Данная проблема наблюдается не только у меня 

#### Что должно было произойти
Всё должно отлично работать

#### Что произошло на самом деле
Вылет и перезаход с ожиданием 30 секунд
#### Как повторить
Поиграть за ИИ, активно использовать фолов и двигать камерой
#### Дополнительная информация:
Наверное я некорректно сделал, что приравнял зависания к вылетам, однако собственно это и есть вылет, ибо виснет намертво

**Comment by Skippeer12** [comment]
Тут нужны не версии бульенда и Винды, а характеристики компуктера.
Потому что если вылетает, то всё...

![](http://cs.pikabu.ru/images/big_size_comm/2013-05_1/13674414211007.jpg)

**Comment by nikitosman** [comment]
Вряд-ли это связано с характеристиками компьютера

**Comment by Forrya** [comment]
Подтверждаю. Часто вылетает. Особенно когда камера у енжинерки.
Новут нормальный.

**Comment by Skippeer12** [comment]
Специально попробую сегодня за ИИ поиграть (получит перму) и посмотрим вылетает оно из-за характеристик или же проблема в коде(что мало вероятно).

**Comment by P-20** [comment]
Вылетает да. Очень часто. В особенности вылеты очень часто когда ИИ малф.

**Comment by YulianR** [comment]
Я последние пару дней относительно часто за ии играл, вылетов не заметил

**Comment by WallShrabnic** [comment]
Вылеты рандомны, у меня чаще всего вылетало при нажатии на фразы в чатике

**Comment by nikitosman** [comment]
Не знаю как связаны характеристики компьютера с эти багом, но всё же, напишу:
**Процессор:** Intel Core i5-6600
**Оперативная память:** 8ГБ DDR 3
**Видеокарта:** Nvidia GTX660
**Диск:** SSD Kingston 240GB
Ну вот вроде все основные, думаю ССку должно тянуть

**Comment by Raschert0** [comment]
Ещё не создали видеокарту для игры в ССку!
А так да, баг подтверждаю.

**Comment by StrikS** [comment]
Не от характеристик ПК это зависит скорее всего. Так же наблюдаю иногда вылеты, в основном пролетая инженерку, причем это не вылеты, а зависание клиента. Одно из зависаний произошло когда появилась надпись "Ю ар орбитинг Phoenix". То есть орбичу самого себя.

**Comment by nikitosman** [comment]
Наверное я некорректно сделал, что приравнял зависания к вылетам, однако собственно это и есть вылет, ибо виснет намертво

**Comment by Skippeer12** [comment]
Минут тридцать летал за ИИ по всему стейшону ни разу не зависли и не вылетело.
Зато заметил такой вот баг с оверлеями шлюзов.
![524521](https://cloud.githubusercontent.com/assets/18488106/25640810/c86ff318-2f99-11e7-9cde-e40cb493fa17.png)

**Comment by StrikS** [comment]
Фича

**Comment by Skippeer12** [comment]
Забираю все свои слова назад, за ИИ дичайше вылетает.

**Comment by dearprincesscelestia** [comment]
Дичайше фризит, если смотреть за сингулярностью через камеры за человека. Возможно, связано?

**Comment by ZVee** [comment]
@SpaiR глянешь? Это наверно по твоей части, т.к вероятно "сломали" форсмув - первое что в голову приходит, если мне память не изменяет, мы пришли к выводу что это из-за него было всегда. Хотя тут вопрос - как это давно началось, если все же недавно - то форсмув обновляли, да? Но это только предположение, и ничего более.

**Comment by SpaiR** [comment]
Эм, причём тут форсмув? Вот прок который движет глазом ИИ https://github.com/TauCetiStation/TauCetiClassic/blob/a6b173dc51f36b72369bec1455967412efb62018/code/modules/mob/living/silicon/ai/freelook/eye.dm#L107, который вызывает https://github.com/TauCetiStation/TauCetiClassic/blob/a6b173dc51f36b72369bec1455967412efb62018/code/modules/mob/living/silicon/ai/freelook/eye.dm#L50 Форсмува нигде нет.

**Comment by ZVee** [comment]
Когда вопрос таким образом составляю - это значит что код я даже не смотрел, у нас вылеты раньше были связаны из-за отсутствия или присутствия (не помню, проблема как минимум год назад была) форсмува, поэтому это первое что пришло в голову.

**Comment by SpaiR** [comment]
Из предположений: параллакс. Ну или ещё какое нибудь очередное говно связанной с визуализацией в бьёнде. Есть зацепки на сингу, но это не точно. Как вариант: посмотреть что сделано на других билдах в сфере камеранетов и мувмента глаза ии (у нас всё это очень древнее). Но конечно чётко предположить в чём проблема, лично мне, сложно. Играть за ИИ целый раунд долго, да и не факт что вылетит (недавно чекал, не вылетало). Было бы здорово если бы волонтёры смогли найти прямо 90% или круче вариант действий, когда вылет можно повторить. Это значительно ускорило бы процесс.

**Comment by ZVee** [comment]
Кстати, может из-за версии бъенда еще, 82 последняя "стабильная" - нифига не стабильная, а еще и баг с рывками который надо в коде фиксить судя по всему для этой версии специально (просто видел что у нас ее используют уже). Но речь не конкретно про 82, а в целом, может что с обновами клиента поломалось - как и говорил, вопрос в том, как давно это началось.
Пишу это, чтобы те кто будет пытаться найти причину, имели ввиду версию бъенда которую они используют.

**Comment by volas** [comment]
http://www.byond.com/forum/?post=2294466
И похоже ишью на авроре, https://github.com/Aurorastation/Aurora.3/issues/2331

**Comment by TechCatOther** [comment]
Провел около 15 раундов за ИИ разной продолжительности и все было ок. Есть еще кто-то у кого вылетает на текущей версии?

**Comment by TechCatOther** [comment]
Не воспроизводится на текущей сборке
