### ISSUE TITLE
Невозможно разобрать генератор щита.

### ISSUE THREAD

**Issue by nikitosman** [TauCetiStation/TauCetiClassic#1426]
#### Подробное описание проблемы
Невозможно разобрать генератор щита
![2017-05-02_00-15-27](https://cloud.githubusercontent.com/assets/19156223/25595169/79655b64-2ecc-11e7-9fea-cff6895b31f9.png)

#### Что должно было произойти
Стало бы возможно вытащить все комплектующие, как и с обычными машинами
#### Что произошло на самом деле
Ничего, ни одни инструмент не помогает, ID-карта так же не оказывает эффекта
#### Как повторить
Попробуйте разобрать генератор щита

**Comment by Belfogor** [comment]
Собственно никогда и не предполагалась возможность их разборки и я даже не уверен, нужно ли это?

**Comment by nikitosman** [comment]
Определённо нужно, например для сборки генератора щита корпуса, ну или же просто добавьте обычный генератор щита и генератор щита корпуса в хранилище инженеров

**Comment by Forrya** [comment]
Генератор щита (не быстроевентов педалей, а поля) по мдее должен улучшаться. И соответственно детали должны заменяться.

**Comment by Skippeer12** [comment]
Детали и заменяются, только блюспейс РПЕДом, и вроде конденсатро щита только улучшается.
