### ISSUE TITLE
Некорректная работа взрыва при приеме калия и воды внутрь.

### ISSUE THREAD

**Issue by PavelYo** [TauCetiStation/TauCetiClassic#1429]
#### Подробное описание проблемы
Если выпить калий и воду то вокруг вас как будто бы был взрыв но как он там появился если вы приняли это внутрь? Причем после взрыва персонаж совершенно невредим..ну почти. Его как минимум должно разорвать
#### Что должно было произойти
Персонаж должен либо взрываться либо у него должны быть повреждены внутренние органы а вещи вокруг никак не должны пострадать от взрыва
#### Что произошло на самом деле
Вокруг персонажа все взорвалась а он как будто невредим
#### Как повторить
Выпить большую колбу калия и воды.

**Comment by skvazarb** [comment]
Калий с водой занерфан глобально, аналогичный эффект будет при обычной реакции. Маловероятно, что здесь имеются какие-то отдельные проблемы с реакцией внутри мобов.

**Comment by Skippeer12** [comment]
Его же Расчер зазнерфил ещё и бафнул.

**Comment by skvazarb** [comment]
>Его же Расчер зазнерфил ещё и бафнул.
Да, это я пропустил.
Но сейчас проверил еще раз, реакция внутри мобов всё равно происходит так же как в прочих контейнерах. Сам взрыв не особенно сильный, поэтому и последствия не тяжелые.

**Comment by YulianR** [comment]
Верните состояние до нерфа, ну. Ну или совсем чуть чуть уменьшить, чтоб не гибало при при соотношении 100/100.

**Comment by Raschert0** [comment]
Но как ты выпьешь 100 ед. того и другого, если в пилюле только 50 ед.?

**Comment by skvazarb** [comment]
Я вчитался в текст ишью. Автора, вероятно, не устраивает, что при реакции просто происходит взрыв на тайле где стоит моб. Он предлагает, что взрыва не было, зато было - КРОВЬ КИШКИ ГИБНУЛО. Оно то конечно логичнее, но у нас тут игровые условности и лишний способ казуального гибба скорее не нужен. Предлагаю ничего не менять, в том числе в цифрах силы взрыва, сейчас вполне адекватно. Может дать слегка перебор, 100 на 100 дает взрыв на 12.

**Comment by StrikS** [comment]
Взрыв на тайле происходит слабый для чуловека, от слова совсем. Калиевая бимба 50 x 50. Итог 27 брута честа
https://youtu.be/7sX8sEOHlF4

**Comment by skvazarb** [comment]
Он не какой-то особенно слабый для человека, так у нас вообще взрывы работают. Взорви у себя самоделку в руках, эффект примерно такой же.

**Comment by Archinect** [comment]
Херовенько работает, пусть лучше наносит внутренние повреждения и гибает только при  больших пропорциях. Тогда и логично и по балансу не бьет.
