### ISSUE TITLE
Слепые зоны ИИ в доках.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1432]
#### Подробное описание проблемы
ИИ имеет неприятные слепые зоны в доках, и они очень мешают нормальной блокировке шлюзов.
#### Что должно было произойти
ИИ должен выдить все шлюзы.
#### Что произошло на самом деле
ИИ видит помехи. ИИ горит.
#### Как повторить
Зайти за ИИ.
#### Дополнительная информация:
ИИ не видит крайний шлюз со стороны космоса в первом доке.

![4214](https://cloud.githubusercontent.com/assets/18488106/25726821/9a598f98-312e-11e7-8e45-c27ef9edc843.png)

ИИ не видит весь четвертый док.

![421](https://cloud.githubusercontent.com/assets/18488106/25726837/a93a699c-312e-11e7-8558-47c8f8e9e62c.png)

**Comment by PavelYo** [comment]
В этом даже есть некая логика что бы если сюда приканекчиваются антагонисты и ИИ бы блокировал шлюзы это было бы фигня какая то да и мелочь то такая..

**Comment by YulianR** [comment]
Нет, в этом логики нет, это доки, а не техи, и камеры там быть должны.

**Comment by dearprincesscelestia** [comment]
Вот тут да. У ИИ следует оставить доступ к шлюзам, которые в общем доступе - мало ли что потребуется сделать, может, заразу выдуть, или ассистента-суицидника не выпустить.

**Comment by StrikS** [comment]
Так то четвертый док можно считать за намеренную уязвимость для антагов. Вот первый док это непорядок. 

>заразу выдуть

Есть остальные 3

>ассистента-суицидника не выпустить

Ты так говоришь, как будто это что-то плохое. Естественный отбор. Запомните: персонал и член персонала - два разных понятия. ИИ не обязан заботиться о каждом из вас, он оберегает экипаж от опасности в целом.

**Comment by YulianR** [comment]
Планируют такие ЭНТЕ станцию, и думают: "Так, вот здесь камеру ставить не будем, чтобы пиратам было легче нападать...Так, а здесь в техах поставим, не знаю зачем, ГЫ, ПРОСТО ТАК"

Это охуительные уязвимости из разряда кнопки открывания дверей в бриг с общим доступом (При абсолютно такой же кнопке в меде, у которой блять ДОСТУП ОГРАНИЧЕН (Да, безопасность меда лучше, чем брига). Если что, обрезать камеру занимает меньше секунды каким-нибудь есвордом, который есть у большой части антагов, и две секунды отверткой и кусачками (правда с большим шансом напороться на алерт). Это НЕ ФИЧА, это баг, появившийся при перепиле карты. У антагов итак куча свистелок перделок и имбового оборудования.

**Comment by StrikS** [comment]
В бриге есть с чем выгонять набигаторов, а в меде нет. Тебе ли не знать какой геморой создают мимокрокодилы, когда нужно срочно оказывать помощь пациенту. 
Флешку на полу КПП тоже оставили не просто так.
Да, бывают то, что просто при мапинге забыли убрать, но некоторые были специально оставлены, причем не обязательно для антагов, а для персонала. (Забержать проведать в бриг, взять флешку ослепить обидчика)

**Comment by dearprincesscelestia** [comment]
Мне кажется, что 
а) упражняться в телепатии - контрпродуктивно, и зовите маппера.
б) вне зависимости от того, намеренно или нет, надо оценить результат, нравится он или нет.

Если не задумывалось и не нужно - убрать.
Задумывалось и нужно - оставить.
В остальных случаях - нужны аргументы серьезнее телепатии, тебелинезнати и рассуждениях о философском значении ИИ в нашей жизни.

**Comment by Skippeer12** [comment]
Закрою тогда, потому что #1052.
