### ISSUE TITLE
Синдикатская модель боргов не может использовать емаг.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1435]
#### Подробное описание проблемы
У борга нюкеров сломан емаг и при использовании его на двери/АПЦ/etc. он просто ломается, сразу, при этом не открывает ничего.
#### Что должно было произойти
Емаг должен был открыть дверь/АПЦ/etc..
#### Что произошло на самом деле
Емаг сломался и выпал.
#### Как повторить
Зайти за борга с емагом

**Comment by SpaiR** [comment]
#1158
