### ISSUE TITLE
Исправьте кодировку!

### ISSUE THREAD

**Issue by PavelYo** [TauCetiStation/TauCetiClassic#1436]
#### Подробное описание проблемы
После записи на касету текста на листках каракули вместо русский букв. Еще бывает в заголовке канала новостей тоже каракули вместо нормальных букв. 
#### Что должно было произойти
В записи на касете должны быть русские символы
#### Что произошло на самом деле
Непонятные символы из за неверной кодировки
#### Как повторить
Запишите на диктофон что то и распечатайте

**Comment by Belfogor** [comment]
Сейчас прибегут Спаир со Зве и вставят тебе за заголовок.

**Comment by volas** [comment]
Заголовок ладно, скриншоты бы не помешали. Возможно проблема только у тебя - стоит другая локаль на компьютере или что-то еще.

**Comment by P-20** [comment]
У меня тоже данная проблема была. Она решается локально.

**Comment by SpaiR** [comment]
Проблемы с кодировкой решаются локально.
