### ISSUE TITLE
Расположение проводов в дверях теперь фиксировано, а цвета - рандомны.

### ISSUE THREAD

**Issue by FlameNeko** [TauCetiStation/TauCetiClassic#1437]
_**-> Подробное описание проблемы:**_
Столкнулся с интересной фишкой. Уже который раунд подряд замечаю что тестовые огни находятся на первом месте в списке проводов, не зависимо от цвета. А раньше цвета были фиксированы, а провода отвечающие за разные функции - рандомны.

**-> Что должно было произойти?**

**-> Что произошло на самом деле?**

**-> Как повторить:**
Открутите панельку на двери, пульсаните первый провод. Выключатся тестовые огни.

**-> Дополнительная информация:**

**Comment by skvazarb** [comment]
Совпадение, не воспроизводится.

**Comment by SpaiR** [comment]
![image](https://cloud.githubusercontent.com/assets/12721311/25772647/973f8934-3278-11e7-93f4-8ff0aa299935.png)
