### ISSUE TITLE
Целеуказатель показывает на конец слоя если цель находится на другом слое.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1438]
#### Подробное описание проблемы
Целеуказатель показывает на конец слоя если цель находится на другом слое.
#### Что должно было произойти
Целеуказатель должен показывать знак вопроса если цель на которую он настроен находится на другом слое.
#### Что произошло на самом деле
Он показывает в космос.
#### Как повторить
Взять целеуказатель и настроить его на предмет за слоем.
#### Дополнительная информация:
Больше пропозал чем ишьюс.

**Comment by Belfogor** [comment]
с целеуказателем одни сплошные проблемы. Работает он в лучшем случае раз через раз. Иногда вообще отказывается искать. Обычно просто водит за нос и ведет не заданному предмету/человеку, а к какой-то другой ложной цели. Чаще всего его глючит если цель или предмет, перемещались со слоя на слой. (со слоя станции на слой атсероида к примеру)

**Comment by WallShrabnic** [comment]
У меня он нормально работал, это вы в него не можете (ЭтоБелфу, если чо)

**Comment by skvazarb** [comment]
>У меня он нормально работал, это вы в него не можете (ЭтоБелфу, если чо)

Нормально он работать не может, как минимум, в случае гипосрея, потому что обычно показывает на ближайший автоинжектор из-за особенностей работы locate() в бьенде.

**Comment by skvazarb** [comment]
На самом деле оказалось, что показывается не какой-то край уровня, а координаты x,y объекта, находящегося на другом слое, но на уровне где находится пинпоинтер. И это скорее баг, а не фича, потому что наше перемещение между уровнями предполагает их горизонтальное расположение, а не вертикальное. Наиболее уместным будет в случае если предмет находится на другом слое, отображать неопределенность, да.

**Comment by Forrya** [comment]
Да. Пинпоинтер кепа гипоспрей не видит.

**Comment by omejka** [comment]
Ес,делаем поинпоинтер бесполезным,еси цель находится на ассеройде
Даже с таким фунционалом поинтера умудрился найти инженера,спамящего на все каналы,как оказалось,с дереликта
Полетал по уровням пару десятков минут,но нашел же,ага

**Comment by skvazarb** [comment]
>Ес,делаем поинпоинтер бесполезным,еси цель находится на ассеройде

Наоборот же. Сейчас используя пинпоинтер точно неизвестно, находится ли цель на твоем уровне. А если он будет показывать неопределенность в случае нахождения цели на другом уровне, можно удобно перемещаясь между уровнями искать подходящий.

**Comment by omejka** [comment]
Ладно,тут вы правы,я недодумался до такого
