### ISSUE TITLE
[Проползач] Аварийное освещение

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1439]
#### Подробное описание проблемы
Очень часто при полном П, а именно при потере света или шанса выжить - установке красного кода все выглядит как при синем/зеленом.
#### Что должно было произойти
Предлагаю врубать либо слабое, тускло красное освещение при ред/дельта коде, либо при потере тока что бы подсвечивали на огромную дистанцию тускловатым светом коридоры фаер олярмы.
#### Что произошло на самом деле
Когда ставишь ред код внешне почти никак не заметно. 
#### Как повторить
Врубить ред код, убедиттся что освещение не меняется.
#### Дополнительная информация:
Педали могут спокойно менять освещение на стейшоне. Почему бы при смене кода на красный не менять все освещение на тускло-аварийно-красное?

**Comment by ZVee** [comment]
>Почему бы при смене кода на красный не менять все освещение на тускло-аварийно-красное?

У нас такое уже было и убрали по причине багов в свете, поэтому надо проверять в начале свет, потому возвращать эту фичу.

**Comment by WallShrabnic** [comment]
А ещё маппить аварийные светильники, свет же не с потолка идёт. А вообще, я против этой идеи, красный свет и так глаза режет

**Comment by ZVee** [comment]
Ничего мапить не нужно, у нас свет встраивался прямо в те лампы что уже в коридорах висят, а на бее делали свет из файр алярмов к примеру.

**Comment by Forrya** [comment]
Помню раунд когда педально свет ярко-бирюзовым делали. Это был ад.
А я предлагаю тускло-красным. Хотя все равно тестить надо.
