### ISSUE TITLE
Не работает увеличение радиуса видимости

### ISSUE THREAD

**Issue by YulianR** [TauCetiStation/TauCetiClassic#1444]
#### Подробное описание проблемы

Не работает кнопка Change View Range, как и режим прицеливания у снайперки

#### Дополнительная информация:

BYOND 511.1382

![2017-05-10_14-41-57](https://cloud.githubusercontent.com/assets/6051766/25897139/873157ec-358f-11e7-9bc5-fdf0ff794282.gif)

**Comment by P-20** [comment]
Работает при переключении размера до 32x32

**Comment by YulianR** [comment]
Кстати да, проверил щас кнопки icons - при Stretch to fit - все становится мыльным, но работает. При 64х64 - нет

**Comment by igigin** [comment]
А теперь поставь 64х64, сожми очень сильно окно и подумай почему у тебя показывает не 15 на 15 таелов, а 2 на 3.

**Comment by YulianR** [comment]
Тогда как убрать мыло при Stretch to fit?

**Comment by ZVee** [comment]
Только сейчас заметил этот ищу и да, вижу что закрыт, но вопрос остался:

>Тогда как убрать мыло при Stretch to fit?

Поставить 510, мыло завезлось с 511, но на 510 параллакс не будет поддерживаться, а на 511 соответственно мыло, что вам важнее - уже сами решайте, но проблема со стороны самого бъенда.
