### ISSUE TITLE
Имплант лояльности не препятствует выдаче роли при автотриторе

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1445]
#### Подробное описание проблемы
См. название
#### Что должно было произойти
Человек с имплантом зашёл в игру/находится в раунде - человек не получил роль
#### Что произошло на самом деле
Человек зашёл в игру за ХоСа с имплантом и получил триторку
#### Как повторить
Рандом
#### Дополнительная информация:
N/A

**Comment by Skippeer12** [comment]
Не баг, а фича.

Не хочешь играть за ХоСа тритора, выключай на антагов yes и лови криминальный скам.

**Comment by WallShrabnic** [comment]
Дело не во мне, а в мудаке, которому выпала ролька и он перед самым шаттлом молча меня выпилил. И вообще, Куршан должен был это учесть

**Comment by Skippeer12** [comment]
Ну так чё ты не написал в АХ, это же прямое нарушение правил. Выпиливать людей только чтобы получить гринтекст за 2 минуты до рестарта.

Ну как хотите, не фича, а баг.

**Comment by Archinect** [comment]
Это именно баг, а не фича
