### ISSUE TITLE
Баги у Дионы

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#1446]
#### Подробное описание проблемы
Если отрезать дионе ноги, она всё равно может ходить и текстура меняется на какие-то ноги человека без кожи.
#### Что должно было произойти
Отрубая конечности существам, они должны пропадать.
#### Что произошло на самом деле
Диона спокойно может уйти без ног.
#### Как повторить
Отрежьте ноги дионе, нажмите "Rest" и идите.

**Comment by Shudyn** [comment]
Дидона отрастила ноги. Нормально же.

**Comment by Skippeer12** [comment]
Ваш метод не работает.
![image](https://user-images.githubusercontent.com/18488106/35796362-f7043ac6-0a64-11e8-8ed0-24eb61aff7f3.png)
