### ISSUE TITLE
У охранного борга не коректно работает охранный худ

### ISSUE THREAD

**Issue by kopoba** [TauCetiStation/TauCetiClassic#1447]
#### Подробное описание проблемы
После прохождения процедуры кибернезицаи охранный худ работает некоректно. Не отображает статус ареста на персонале и не дает возможности смотреть секьюрити рекодрс и тому подобное.

#### Что должно было произойти
Борг должен видеть секьюрити статус у персонала и иметь возможность менять его а еще смотреть секьюрити рекордсы.
#### Что произошло на самом деле
Борг с включеным охранным сенсор аугументешн. Не видит иконок секьюрити статуса и не имеет доступа к секьюрити рекодрсам при экзамене человеков.
#### Как повторить
Зайти в раунд пройти процедуру кибернизации выбрать охранный модуль включить сенсор аугументешн в позицию Security
#### Дополнительная информация:
http://i.imgur.com/b0RnT9h.png

![Image of Borg hudt](http://i.imgur.com/b0RnT9h.png)

**Comment by P-20** [comment]
Сюда же и медицинский HUD. Жизненные показатели видны лишь когда у человека включены датчики во второй режим. И нет возможности редактировать медицинские записи.

**Comment by kopoba** [comment]
пофикшено
