### ISSUE TITLE
Отключение бега у киборгов с помощью прицела

### ISSUE THREAD

**Issue by sovok4** [TauCetiStation/TauCetiClassic#1448]
#### Подробное описание проблемы
Тут недавно дети играли в лазертаг и целились в прохожих.
Если тебя берут на прицел, то передвижение автоматически переключается на шаг. Это же оказалось справедливо и для боргов. Только вот переключиться снова на бег борг без педальной помощи не может.
Получается, что есть не совсем честный способ снизить боеспособность любого борга практически до нуля, даже если у тебя есть просто игрушечный пистолет.
#### Что должно было произойти
Ну, не знаю. Наверное борг должен иметь возможность переключаться с шага на бег без педалей.
#### Что произошло на самом деле
Борг не может переключиться с ходьбы на бег без педалей.
#### Как повторить
Взять любую пушку, прицелиться в борга. Походить боргом.

**Comment by Skippeer12** [comment]
RiP ficha.

**Comment by P-20** [comment]
@ZVee глянешь?

**Comment by DieSiege** [comment]
Эту фичу-то за что?

**Comment by ZVee** [comment]
Гляну, скорее всего уберу с небоевых пушек влияние на скорость, но точное решение пока не придумал.

**Comment by Archinect** [comment]
@ZVee, могу втыкнуть переключатель скорости ходьбы борга

**Comment by ZVee** [comment]
@Archinect кнопки со стилизованным спрайтами под боргов разве что, но это такое себе решение. Как минимум, борги вообще не должны реагировать на эту механику, а в идеале - ряд оружия которое это не вызывает, вроде того же лазертага.

**Comment by Archinect** [comment]
@ZVee, если борги не будут реагировать, каждый раз когда их будут брать на прицел, по ним будут стрелять автоматически. Перерабатывать оружие слишком лениво мне, могу либо кнопку запилить (Без спрайта, спрайт ищите сами), либо запретить брать борга на прицел вовсе.

**Comment by ZVee** [comment]
То что баг есть - это конечно плохо, но засунуть кнопку которая будет вообще с левым спрайтом - еще хуже, учитывая что со спрайтами на худе никаких левых вещей или халтуры вроде как нигде нет.

>каждый раз когда их будут брать на прицел, по ним будут стрелять автоматически.

Ну это единственное возможно то, что требует кнопку, однако это не отменяет тот факт, что есть тип оружия, который не должен влиять на мув интенты. Учитывая то, что у нас углов обзора нет, значит персонажи отлично видят с чего в них целятся даже спиной, если это не хамелеон или боевое.

>Перерабатывать оружие слишком лениво мне

С таким подходом лучше тогда не браться вообще, потому что сделав фикс - не гарантия что тебе не придется с ним возиться после открытия ПРа, могут возникнуть вопросы, могут мэйнтейнеры сказать - так не катит, переделывай или вдруг контрибьютинг гайд не прочтешь и.. У нас строго, да.

---

Под итожу - "перепил" оружия это ладно, не суть этого бага, а вот кнопку надо, но без спрайта - однозначно нет.

**Comment by Archinect** [comment]
@ZVee, ну, найди тогда человечка, который нарисует нужный спрайт, а я впилю саму кнопку

**Comment by ZVee** [comment]
Я это сам исправлю, репорт закреплен за мной. Просто как бы если вам прям так срочно это надо пофиксить, то вперед - но только не тяп-ляп. Еслиб худы от балды были нарисованы, то никто не парился по поводу добавлением кнопки без всяких спрайтов, но увы, там сейчас все хорошо, значит и фикс надо тоже делать хорошо.

**Comment by Archinect** [comment]
@ZVee, я не могу закреплять за собой репорты, так как не являюсь тут кодером

**Comment by ZVee** [comment]
Т.к тут проблема в отсутствии спрайта, если речь идет о фиксе через кнопку, то спрайт можно приложить прямо тут на всеобщее обозрение. Смысла передавать репорт без этого нет.

**Comment by AndroBetel** [comment]
неактуально переключение на волк при прицеле удолили
