### ISSUE TITLE
Алиумо-прыжки

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1450]
#### Подробное описание проблемы
Прыжки у хантеров работают некорректно.
#### Что должно было произойти
При нажатии на кнопку прыжка и затем на любой видимый тайл, хантер должен мгновенное лететь к нему сбив на своем пути хумана если таковой есть.
#### Что произошло на самом деле
Прыжок берет какой-то медленный разгон и движется со скоростью обычного бега алиумов. Так же, его прыжку может помешать если клацать на клавиши движения. В итоге, алиум чуть ли не прыгает на месте и легче уже просто задизармить жертву.
#### Как повторить
Попрыгать за хантера и поэкспериментировать.

**Comment by ZVee** [comment]
Касательно движения - работает как задумано на самом деле, чтобы это исправить, придется в прок движения ради одного хантера добавить исключение, поэтому проще вам самим поднять скилл и научиться отжимать движение перед прыжком. Хотя может там есть иное решение.

А второе, меня больше напрягало что с обновлением броска - врезаешься в пол (слишком уж хардкорно).

Скорость тоже была вменяемая насколько помню, если отжимать движение (совсем недавно просто пересекался с этим умением на сервере).

Еще если кто не вкурсе - нужно харм включать, с другим интентом ты не будешь врезаться в жертву и валить.

**Comment by Uvash** [comment]
Раз уж вскрыли тему с прыжками и движением алиумов. 
[https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/mob/living/carbon/alien/humanoid/humanoid.dm#L35](url)
Мне кажется или этот кусок не нормален?

**Comment by Kurshan** [comment]
@Uvash Ну учитывая, что этот участок кода можно переложить на полиморфизм, то почему бы и нет. Только там Зве вдруг (не вдруг) шатал ещё и алиенов, так что это на его совести сейчас.

**Comment by SpaiR** [comment]
Короче, момент такой, что сам по себе вызов `throw_impact` с полом в `throw_at` - it's ok. Здесь скорее использование одного механизма в целях, для которых по идее тот не совсем предназначен. Раньше это работало скорее из-за не до конца проработанной логики броска. 

Поэтому, чтобы решить баг можно сделать костыль и прописать в самом импакте хантеров исключение на пол, но мне это не совсем по нраву. Ещё как вариант унифицированного решения  - подкорректировать механику и добавить в прок броска аргумент типа `mob_jump`, для которого прописать отдельную логику вызова импакта. Но это не отменит факта использования дрели для забивания гвоздей. Самое хорошее решение - механика прыжков. В отдельных случаях, типа этого, она напрашивается. В общем я в раздумьях и не знаю на какой стул сесть. @ZVee это всё связано с мобами, что думаешь?

**Comment by ZVee** [comment]
Я посмотрел это дело, хантеры используют прок throw_impact() и если атом с которым у них произошел этот самый импакт не living, то механ думает что мы влетели во что-то плотное - стену например, думаю можно просто дописать исключение на неплотные атомы или пол туда.

Более того, можно более продвинутый механ в этом случае реализовать, если врезаемся в плотный атом, то ловим стан и прыжок нельзя использовать скажем в течении 10-ти секунд, а если в "пол", то буст скорости (ну это просто пример того, что можно новое поведение броска использовать по особому.
