### ISSUE TITLE
Отсутствует возможность производства плат для фабрикатора шахтеров

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#1451]
#### Подробное описание проблемы
Вся суть в заголовке.

**Comment by Skippeer12** [comment]
Но ведь это сделали для баланса, вернее сделал один человек.

**Comment by Belfogor** [comment]
О каком балансе мы ведем речь, если у нас доступно производство плат для всего оборудования на станции, кроме этой? Как бы там не было. Должна быть доступна возможность строительства фабриката без вмешательства педалей.

**Comment by ZVee** [comment]
>для всего оборудования на станции, кроме этой

"станции" - в этом суть и далеко не "кроме этой" если как раз завезти речь про аутпост, хотя тут конечно наверно больше звучит как придирка, но тем не менее.

В целом на будущее - это все индивидуально надо рассматривать, но если подойти к этому вопросу как "ну это же на станции есть, значит должно быть доступно в массовом производстве" - однозначно нет, и эта логика не работает. Тут уже индивидуально надо решать, а то можно такой лааарец открыть - что потом жалеть долго.

А касательно фабрикатора - не за и не против, т.к не вводил и не имел с ним особо общения. Но задумайтесь, что приносит фабрикатор, и должно ли это быть под рукой, или же пусть люди лучше ходят далеко за контентами того, к чему фабрикатор дает доступ.

**Comment by WallShrabnic** [comment]
Проблема в том, что данный фабрикатор у шахтёров почти не используется, так что это хоть как-то должно решить проблему

**Comment by Zandwitch23** [comment]
Маст хев. Не пользуются потому что далеко. Если броситься в крайность, то при желании с хорошей наукой, минут через двадцать с начала раунда можно наклепать гору ригов, стимпаков, ключи ко всем ящикам и армию ботов для борьбы с мобами. 
p.s. Ну вот, ещё и пластиком с РнД придётся делиться ;\

**Comment by Archinect** [comment]
А я считаю, что Все основные механизмы должны собираться и разбираться без педальной помощи, так как основной аспект сски в том, что это не только РП игрушка, но ещё и песочница, где можно даже собрать Свою станцию с нуля.

**Comment by Skippeer12** [comment]
Ну вы отлично придумали, теперь то РнД будет вас не только с тесла пушки убивать, но и под спидами, с ригом офицеров и сьют патчерами.

Хочешь один фабрикатор? Попроси шахтеров, они два фабрикатора никогда не используют.

**Comment by SpaiR** [comment]
Короче, проголосуйте, кому это интересно, в ПРе #1452 надо оно или нет.

**Comment by Archinect** [comment]
На Каргонию то никто не жалуется, хотя они тоже могут заказывать крутые пушечки.
РнД всё равно имеет страшные виды умерщвления, их опасность должен ограничивать не механ, а отыгрыш. А по факту, один ассистент может выпилить всю Гулагию баллоном и мылом, его ограничивает не механ, а именно отыгрыш и правила.

**Comment by Zandwitch23** [comment]
>Хочешь один фабрикатор? Попроси шахтеров...

Ну не просятъ. Может забывают, а может тоже впадлу заморачиваться. И да, один фабрикатор с шахтёрки лучше бы в карго стоял.
