### ISSUE TITLE
РИГи не защищают от мыла

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1454]
#### Подробное описание проблемы
Риги больше не защищают от подскальзывания на мыле
#### Что должно было произойти
Риги должны их защищать от падения на мыле
#### Что произошло на самом деле
Не защитил, упал и соснул
#### Как повторить
В риге бросить под себя мыло

**Comment by Gyaviste** [comment]
Почему должны? Для этого же есть специальные ботинки

**Comment by WallShrabnic** [comment]
Раньше точно защищал. Я вообще говорю про ситуацию, например с магусом в своём РИГЕ, которого может теперь прокатить любой ассистент. Тоже самое с офицерами, идёшь такой, тебе под ноги падает мыло и ты сосёшь, ad

**Comment by dearprincesscelestia** [comment]
Возможно, защищал со включенными магбутсами. Почему он должен защищать без магбутсов?

**Comment by WallShrabnic** [comment]
Алло, меня пытались за мирномагуса в РИГЕ повалить мылом, когда я шёл в бриг

**Comment by Gyaviste** [comment]
А, ну раз ТЕБЯ пытались повалить, то другое дело, конечно, теперь РИГ должен защищать от мыла

**Comment by dearprincesscelestia** [comment]
> за мирномагуса 

~Вот причина проблемы~
Это не меняет того, что очень странно будет выглядеть такой механизм. Во-первых, нослипы, бахилы и магбутсы - это ограниченный ресурс, их меньше, чем хардсьютов, и доступны они не всем.

Во-вторых, почему ты не должен поскальзываться в тяжелом, жестком костюме? Там наоборот, неплохо бы, если бы еще и труднее вставалось.

А по поводу негативного експириенца - магусу просто сделать предмет "волшебные сандали", который имеет нослип - как по мне - лучшее решение.

**Comment by WallShrabnic** [comment]
Идёшь такой по коридору в фулл броне СБ выносить пиратов/нюку, а ассист бросает тебе под ноги мыло, прижимает к полу, раздевает и оставляет валяться на полу - классный геймплей, da

**Comment by dearprincesscelestia** [comment]
Идешь в бронежилете и с лазер кенноном, а тут ассистент мило бросает под ноги.
Идешь с фулаксессом, а тут ассистент мило бросает под ноги.
Идешь клоуном, а тут ассистент мило бросает под ноги.
Идешь с ролькой, а тут... А, это в самом ишшуе было.

Ситуация одна и та же. Игра не должна отслеживать, согласен ли ты подскальзываться на мыле или нет. Если механ мыла таков, что на нем можно поскользнуться, то исключения должны быть логичными. И тяжелый хардсьют, фулл броня и мешок еганов скорее дрлжны добавлять неустойчивости. И если ты бежишь со всех ног, обвешанный броней и пушечками выносить пиратов/нюку, но не выпросил магбутсов - это не вина мыла, и оно страдать не должно.

А если тебе сам механ мыла не нравится - так и скажи, "уберите подскальзывание на мыле, кожуре, воде и ПДА клоуна, а то я в мирномага не смог".

**Comment by dearprincesscelestia** [comment]
Идешь в бронежилете и с лазер кенноном, а тут ассистент мило бросает под ноги.
Идешь с фулаксессом, а тут ассистент мило бросает под ноги.
Идешь клоуном, а тут ассистент мило бросает под ноги.
Идешь с ролькой, а тут... А, это в самом ишшуе было.

Ситуация одна и та же. Игра не должна отслеживать, согласен ли ты подскальзываться на мыле или нет. Если механ мыла таков, что на нем можно поскользнуться, то исключения должны быть логичными. И тяжелый хардсьют, фулл броня и мешок еганов скорее дрлжны добавлять неустойчивости. И если ты бежишь со всех ног, обвешанный броней и пушечками выносить пиратов/нюку, но не выпросил магбутсов - это не вина мыла, и оно страдать не должно.

А если тебе сам механ мыла не нравится - так и скажи, "уберите подскальзывание на мыле, кожуре, воде и ПДА клоуна, а то я в мирномага не смог"о

**Comment by igigin** [comment]
Не защищали, не защищают и нет никакой логичной причины защищать. Клозед.

**Comment by WallShrabnic** [comment]
Защищали, тащем-то, но ладно, уже всё равно
