### ISSUE TITLE
Багованный армблейд

### ISSUE THREAD

**Issue by Zap-zapper** [TauCetiStation/TauCetiClassic#1456]
#### Подробное описание проблемы
Если ты в наручниках, и ты юзаешь армблейд, тебе пишется что "You can't use armblade whilist restrained!", но наручники при этом испаряются
#### Что должно было произойти
Наручники не должны были испариться
#### Что произошло на самом деле
Наручники испарилисб
#### Как повторить
Наденьте на генку наручники или другие стяжки, и пусть проюзает армблейд

**Comment by ZVee** [comment]
Сообщения не должно быть, а разрезание наручей - недавний ребаланс.

**Comment by Archinect** [comment]
Странный ребаланс, теперь генок только в шкафу заваривать до сожжения?

**Comment by ZVee** [comment]
На самом деле я не знаю зачем это сделали еще и для армблэйда, т.к у генок есть кислота которая и наручники снимает и всякие рубашки со шкафами, хотя кислоту чуть сложнее использовать. Но сделали это еще в феврале, так что вы как-то поздно проснулись.

**Comment by Skippeer12** [comment]
Уже пофиксили, теперь генка может снимать наручники армблейдом.
Призывают тактического игигила.
