### ISSUE TITLE
Куршанский рандом (мисы)

### ISSUE THREAD

**Issue by StrikS** [TauCetiStation/TauCetiClassic#1464]
Зила стоит впритык к меху
![default](https://cloud.githubusercontent.com/assets/15943769/26067036/3cebce5c-39b2-11e7-8a87-07d207a69ba9.png)

**Comment by Skippeer12** [comment]
Потому что если кто-то стоит в притык к меху, то это дорого в один конец, не важно промахнешься ты оружие или нет, тебя панчат кулаком и ты в кноке.

**Comment by Avatar4** [comment]
Если мех додумается харм прожать.

**Comment by YulianR** [comment]
А разве там не стол был между зиллой и мехом?

**Comment by StrikS** [comment]
Нет, Зилла стояла впритык к меху.

**Comment by kopoba** [comment]
Наблюдал такое же явление когда меха стрелял в борга вплотную в космосе. Явный баг же.
