### ISSUE TITLE
Отсутствует возможность убрать останки/кости.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#1478]
#### Подробное описание проблемы
Зачастую, люди умирают оставляя после себя лишь кости, и череп, которые нельзя никак убрать.
Нельзя их и взорвать, используя лимитку, или же С4. Нет способов чтобы убрать их.

#### Что должно было произойти
Кости можно убрать в мешок уборщика, или любым другим способом, который посчитается приемлемым. 

#### Что произошло на самом деле
Их нельзя поднять. Их нельзя уничтожить. Их нельзя убрать. Спрятать. Сложить в шкаф. Они представлены в виде постоянного эффекта.
#### Как повторить
Попытаться убрать останки/remains
#### Дополнительная информация:
/obj/effect/decal/remains/robot
/obj/effect/decal/remains/xeno
/obj/effect/decal/remains/human

**Comment by KuzyXD** [comment]
Клинер заюзай.

**Comment by RichardJones1** [comment]
Их можно таскать после одного из моих ПР-ов. Остальные предложения расписаны в пропозале #2902
