### ISSUE TITLE
Не включается режим TAB

### ISSUE THREAD

**Issue by FuriousGarnet** [TauCetiStation/TauCetiClassic#1482]
#### Подробное описание проблемы
При нажатии на TAB не включается WSAD раскладка. Раньше помогало старое доброе выйти-войти. Но увы, уже не работает.

**Comment by Belfogor** [comment]
У вас случайно не USB клавиатура? Потому что у самого имеется и на ней тоже не работает!

**Comment by FuriousGarnet** [comment]
Не-а. Играю на ноуте

**Comment by Kurshan** [comment]
Попробуйте поставить английскую раскладку по умолчанию и прожать TAB

**Comment by FuriousGarnet** [comment]
Попробую, спасибо. Менял раскладки, но по умолчанию не ставил.

**Comment by FuriousGarnet** [comment]
Поставить раскладку по умолчанию - помогло! Спасбио!
