### ISSUE TITLE
Дюп ресурсов в РнД

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1487]
#### Подробное описание проблемы
В РнД можно дюпать ресурсы
#### Что должно было произойти
Нельзя дюпать
#### Что произошло на самом деле
Ресуцрсы дюпнулись, хоть выход продукта и меньше ста процентов
#### Как повторить
Засовываем нужный ресурс в протолат, И БЫСТРО ЗАСОВЫВАЕМ В Exosuit Fabricator
#### Дополнительная информация:
Привет, шкипа, прости за спаленную фичу

**Comment by Skippeer12** [comment]
![](http://s1.storage.akamai.coub.com/get/b16/p/coub/simple/cw_timeline_pic/555bc521aaf/a085044b4b7e5cba9e862/big_1440445695_image.jpg)
