### ISSUE TITLE
Проблемы с подскальзыванием на ПДА клоуна

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1489]
#### Подробное описание проблемы
Подскальзывание на ПДА клоуна работает по старой механике
#### Что должно было произойти
Вся новая механика подскальзывания работает на ПДА
#### Что произошло на самом деле
Механика не работает, в РИГе нельзя подскальзнуться, можно абузить ящик
#### Как повторить
Эксперименты с ПДА
#### Дополнительная информация:
-2 Фичи за день, Шкипа, я в ударе

**Comment by StrikS** [comment]
Фича
