### ISSUE TITLE
Разговорное облако у безголового Ника.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1493]
#### Подробное описание проблемы
При нажатии на F3, появляется окно say а над персонажем облако что он начал говорить. Но если персонаж без сознания или умер, облако никуда не пропадет.
#### Что должно было произойти
При потере сознания или смерти облако должно исчезать.
#### Что произошло на самом деле
Оно не исчезает.
#### Как повторить
Нажать на ф3, вколоть себе хлорку и уснуть и убедиться что облако на месте или застрелить себя.

**Comment by YulianR** [comment]
Насколько помню, у человека, теряющего сознание, тот же щит.

**Comment by ZVee** [comment]
Это бъендо проблема которому адекватное решение только заставить вас пользоваться (командной) строкой внизу (т.е фактически удалить хоткей Ф3, а точнее он будет вам строку внизу активировать) и писать все сообщения через `say "`.

Мы можем конечно облако отключать при статусах, однако если при смерти это вероятно нормально еще, то вот потеря сознания может длиться секунду, а игрок еще не закрыл окно с инпутом куда он вводит текст и вот-вот что-то напишет, а облако не будет уже сигнализировать о том, что игрок все еще что-то хочет сказать, т.к мы взяли и удалили его из-за отсутствия статуса в актуальный момент.

**Comment by Avatar4** [comment]
Но он же в конечном итоге напишет что-то и облако опять появится при окончании фразы.
К слову, у боргов облако пропадает после того как они начали говорить.

**Comment by igigin** [comment]
>отключать при статусах

Можно же только при смерти отключать.

**Comment by ZVee** [comment]
>Но он же в конечном итоге напишет что-то и облако опять появится при окончании фразы.

Конечно, но мы в итоге получим другой баг на выходе - у игрока открыт сэй, он что-то пишет, но из-за секундного паралича облака над головой уже нет.

>Можно же только при смерти отключать.

Можно, но опять же, представим ситуацию с долгим статусом, например анестезия - хирург работает, а над игроком облачко висит.

Это я к тому, что полностью излечить это никак нельзя вероятно именно с использованием input() и окна вылезающего посреди экрана для ввода текста (можно правда замену инпуту реализовать с использованием скина, но это слегка рекодить этот момент), еще один вариант - дополнительную переменную создать - до запуска инпута сетим ее, после выполнения - ансетим. А везде где с этим связан код, например когда игрок обратно возвращается в сознание в таких местах на основе этой переменной мы возвращаем облако и так далее, но нет полной уверенности, что не упустим что-нибудь, ну и из-за облака - там сям код лепить.

**Comment by SpaiR** [comment]
Может уберём облачко?

**Comment by igigin** [comment]
Ещё кто-то предлагал при статусах отправлять уже написанное в чат, когда-то.

**Comment by ZVee** [comment]
>Может уберём облачко?

Рассматривал такой вариант неоднократно, но облако все таки несет в себе довольно важную информацию показывая то, что игрок вроде как собирается что-то ответить и в общем так и не имею мнения на этот счет по сей день. Вроде и крутая фича, а вроде и проблем от нее много, косметических.

>Ещё кто-то предлагал при статусах отправлять уже написанное в чат, когда-то.

Это как раз реализуется с отказом от input() и использованием нижней строки для написания сообщений через `say "`, т.к мы можем узнать что в данный момент игрок ввел в эту строку и при желании форсить.
А инпут мы никак не можем посреди разрешения ситуации контролировать, мы можем только до него что-то выставить и после него узнать его конечный результат.

У меня была идея высвечивать командную строку когда мы нажимаем F3 и в этом случае для игроков ввод текста фактически останется таким как и был, а не где-то снизу, но, если руки дойдут - попробую вернуться к этой идеи, т.к форсить текст от всяких тазеров или при атаках очень на деле атмосферно и забавно.
