### ISSUE TITLE
Прополизач: луб для головы, растящий волосы

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1499]
Как известно бритва - билет в один конец. 
Надо либо вернуть зеркало, чего вы не сделаете, либо добавить гель-смазку. Юзаешь ее на себя - опа, волосы!
Либо в химию жижку добавлять, либо как в рнд исследуемую.

**Comment by ZVee** [comment]
Ни один из вариантов не вернет вам оригинальную прическу которую вы ставили в преференсах (кроме зеркала, а зеркало - шиш), готовы бегать с не пойми чем на голове (и не факт что еще и с возвратом цвета), но типа волосами?

**Comment by WallShrabnic** [comment]
Превратим станцию в барби

**Comment by ZVee** [comment]
Кстати, если вы там за бритье будете варны кидать и наказывать - у меня руки зачешутся соорудить ПР, который не даст вам редактировать и восстанавливать волосы даже с правами хоста. Шутка это или правда - решать вам.

**Comment by Forrya** [comment]
Ну так есть же Р А С С Ч Е С К А.
Облил жижкой лицо, волосы, тыкнул рассческой - вернул причесон.

**Comment by ZVee** [comment]
Ну так есть же ролевые ситуации которые надо отыгрывать - волосы, это уж ну совсем не та вещь, которая убивает геймплей, вот вам пенальти за то, что любите короткие раунды. Потерпите конец, не умрете. Вот еслиб у нас были десятичасовые раунды, можно былоб поговорить, а так - фигня из-за которой даже не стоит раздувать что либо.

**Comment by Olt1771** [comment]
Волосы можно вернуть (мимомеханоёб)

**Comment by DieSiege** [comment]
И очень даже просто (мимомеханоеб x2)

**Comment by ZVee** [comment]
Конечно можно (хотя была идея замедлить минут на 30 этот процесс при любом восстановлении со словоми рост и возврат), но они хотят аналог зеркала - а это через мой труп разве что, ибо одна из на деле безобидных и чисто косметических фич, не влияющая больше ни на что, а даже скорее обазывающая отыгрывать некоторый иной стиль, а не как обычно.

**Comment by Skippeer12** [comment]
Зве пили фичу, чтобы нельзя было отращивать волосы никаким из доступных средство (даже педальным) заживем, варны за стришку без спросу возрастут. Вива ля Тау Сети!

**Comment by Olt1771** [comment]
Портануть профу барбера(парикмахера). И никаких проблем

**Comment by ZVee** [comment]
>Портануть профу барбера(парикмахера)

Между прочим когда-то давно предлагал - получил ответ, что не нужна и вообще вэйст слота.
Вот пожалуй против парикмахера для разрешения этой ситуации не буду и скорее даже поддерживаю.

**Comment by Forrya** [comment]
Ну как бы если сразу бежать к пшшшш - немного мета. А так всем известное средство будет. 
Но парикмахера либо как подпрофу асиста, либо не знаю что.

**Comment by Kurshan** [comment]
Энд нау ви кэн си, хау скилл систем хэс арайз.

**Comment by ZVee** [comment]
>Ну как бы если сразу бежать к пшшшш - немного мета. А так всем известное средство будет.

А бежать и восстанавливать потерянную "прелесть" - это быть еще большим сами знаете кто, ибо вместо того, чтобы подыграть в сложившийся ситуации, вы пытаетесь ее реверсить (ну, да, она может многократно происходить, но это не отменяет сам факт того, что у нас и так каждый раунд это частое повторение одних и тех же ситуаций, просто вам вкусняшки брать охото, а на остальное вы кладете с высока), причем методами и знаниями, которыми не факт, что ваш персонаж вообще может обладать - "но ведь у генетика можно вернуть волосы" - это мета и вы не знаете вообще что там можно у генетика вернуть и изменить, "но это волосы, ну, на волосы, ну что, ну хоть тут дайте мету поюзать, а?" - губу закатайте.

**Comment by Olt1771** [comment]
Почему все сразу думают генетика? Генетика ета ультимативная возможность во всём, но вот Пшшшш. Вернёт не хуже генетики. И меньше шансов что: вы получите 100 бёрна, дезориентацию, два три перелома или станете мартышкой.

**Comment by Uvash** [comment]
/me представил как экипаж бреет генокрада, а затем охотится на всех лысых....
Если будете делать профу парикмахера, думаю стоит не парикмахерам дать возможность делать только простые причёски...
Думаю ещё стоит при определённой длине волос, запрещать одевать шлем от рига, или сильно урезать обзор в нём. А то СЕ с анимешной причёской до пола, носящая риг выглядит странно.
Кстати а может под это дело в ботанику лук ввести, и что бы им лысину тереть надо было....

**Comment by omejka** [comment]
Костылите скилл барберу,блябуду

**Comment by Kleyrt** [comment]
На гунах есть возможность наращивать волосы, красить. Там даже есть профа парикхмахера. Чем мы хуже?

**Comment by Skippeer12** [comment]
Уже замержили вещи парикмахера. Закрывайте.
