### ISSUE TITLE
Бороды на новых старых прическах

### ISSUE THREAD

**Issue by sovok4** [TauCetiStation/TauCetiClassic#1501]
#### Подробное описание проблемы
Очередная смена палитры причесок не затронула хуманские бороды. Возможно они с самого начала были так прорисованы, но мне кажется, что нет.
#### Что должно было произойти
Борода должна быть мыльно-графонистой, как и прически теперь.
#### Что произошло на самом деле
Черная борода поглощает свет и небесные тела. Серая борода похожа на рыцарский щит, прикрепленный под подбородком. Ну и так далее. Нет деталей, все нарисовано одним цветом.
#### Как повторить
Полистать бороды в редакторе персонажей, поменять цвета.
#### Дополнительная информация:
https://prnt.sc/fanrmh

**Comment by ZVee** [comment]
>Возможно они с самого начала были так прорисованы, но мне кажется, что нет.

Так и было, я не менял ни один спрайт, это был просто откат файла и потом проведенная работа по сортировки и названиям, единственное где спрайты менял - это кото-прически где криво отрезали контур и "головы" СПУ, от которых нужен был только экран, а не вся голова целиком.
