### ISSUE TITLE
Пропажа ЩЕТИНЫ в настройке внешности персонажа

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1502]
#### Подробное описание проблемы
В настройке внешности персонажа нет щетины. Ее убрали. Мой персонаж гладко выбрит.
#### Что должно было произойти
У него должна была остаться щетина, так как он бреется от силы раза два в неделю
#### Что произошло на самом деле
Он гладко выбрит
#### Как повторить
Пытаться сделать персонажа с щетиной
#### Дополнительная информация:
Вчера была, а сегодня пропала

**Comment by igigin** [comment]
#1501.

**Comment by ZVee** [comment]
Тут два варианта - либо слегка подождать, когда я дойду до преференсов и оверлеев и разлочу максимальный контроль цветами (если это не принесет каких-то проблем), что позволит использовать и ТГ, и бей и еще какой-нибудь тип причесок,

либо

попробовать порыться на бее (может у них новые появились бороды, у нас то почти никогда прически никто не заносил и они там поди года эдак 2013-го, несмотря на то, что файл вроде как изменился даже в 2015-ом), либо попробовать подогнать палитру тем бородам, что сейчас в наших файлах прическах оставлены из-за отсутствия этого спрайта в файле до отката, бороды кстати проще всего наверно, нежели прически.
