### ISSUE TITLE
У игрока есть третий глаз на затылке

### ISSUE THREAD

**Issue by PavelYo** [TauCetiStation/TauCetiClassic#1503]
#### Подробное описание проблемы
Мне не нравится то что у игроков есть возможность видедь все вокруг себя ведь в реальной жизни это не так и инода этим пользуются и так и хочется сказать "КАК ТЫ МЕНЯ УВИДЕЛ ЕСЛИ ТЫСПИНОЙ СТОЯЛ И ТЕМБОЛЕЕ Я ОТЫГРЫВАЛ ЧТО ШЕЛ ТИХО"
#### Что должно было произойти
Игроки не должны видеть других игроков зади себя
#### Что произошло на самом деле
Игроки видять все на 360 градусов
#### Как повторить
Ну зайдите в игру..э-эм
#### Дополнительная информация:
Даже если зайти на ру фалаут там будет такая система невидения и мне она очень понравилась советую глянуть.

**Comment by Gyaviste** [comment]
Луфвеб не пройдёт

**Comment by igigin** [comment]
Накидывали уже когда-то углы обзора. Через небольшой промежуток времени основная масса была против, плюс ломались всякие пулы и робуст, и прочая чушь, да и у нас тут не луфвеб короче.

И да, с такой аргументацией вам на форум, наверное, вот
> Мне не нравится
