### ISSUE TITLE
Шлюзы

### ISSUE THREAD

**Issue by Permyack** [TauCetiStation/TauCetiClassic#1504]
#### Подробное описание проблемы
Отсутствие шлюзовой системы в некоторых местах на карте.
#### Что должно было произойти
Каждый шлюз должен иметь функцию запирания двери на болты, функцию закачки/откачки воздуха, кнопки для управления всем этим.
#### Что произошло на самом деле
Беспомощная конструкция, состоящая из двух дверей и не способная защитить от случайного открытия(скорее намеренного).
#### Как повторить
Открыть "шлюз" и убить разгермой половину персонала в отбытии.
#### Дополнительная информация:
В некоторых случаях вполне хватит болтов.

**Comment by WallShrabnic** [comment]
Не баг а фича

**Comment by dearprincesscelestia** [comment]
Насколько я помню, такие недошлюзы - это доки (не предназначены для выхода в спесс, и там выходить в спесс опасно, шаттлом раздавит) и недостроенный шлюз у брига. По большому счету, шлюзам в доках и правда достаточно болтов и проверки на давление с обеих сторон, заказчки-выкачки не нужно.

А полноценные шлюзы - это

1) два у инженерки;
2) один в техах у вирологии;
3) четыре у соляр;

То есть там, где никакого шаттла не планируется.
Остается только недостроенный шлюз у брига, и он вполне может быть таким как есть -
 т.е. недостроенным.

**Comment by igigin** [comment]
Короче так и задумано и править не думаю, что надо.
