### ISSUE TITLE
ОБР и Эскадрон Смерти

### ISSUE THREAD

**Issue by Permyack** [TauCetiStation/TauCetiClassic#1505]
#### Подробное описание проблемы
Эскадрон Смерти вынужден использовать экипировку ОБР и в целом выглядит крайне нелогично. ОБР и ЭС весьма слабы.
#### Что должно было произойти
ЭС должен представлять из себя значительную угрозу и сеять страх на всей станции
ОБР бывает слишком слабым для защиты станции от угрозы
#### Что произошло на самом деле
ЭС отхватывает люлей так-же как и ОБР
#### Как повторить
Взять экипировку ЭС и ОБР и проверить её на пригодность для выполнения задач.
#### Дополнительная информация:
Скафандры и ИКСы(РИГи) слишком слабы перед космосом. Стоит подумать над укреплением хотя бы ригов.

**Comment by dred1792** [comment]
Эти ишью настолько информативны, что я уже вижу тысячи способов их решения. (sarcasm)

**Comment by Permyack** [comment]
Никогда не пользовал гитхабом. Мне показалось проще написать суть темы после создания темы.

**Comment by igigin** [comment]
Если кто-то заспавнил джефсквад и решил, что пульсачей будет мало, то он же может и заспавнить пушечки. Чего в билде точно хватает, так это их. Экипировка дедсада целиком и полностью педальная проблема, как и его вызов, и причины, и уже улетевшие отовсюду шаттлы.

А с ЕРТ всё немного по-другому, но не стоит забывать, что у них в первую очередь мультизадачность, в которую входит и робуст. Опять же, тут вам и дробовики, и лазоры, и гранатомёты. Ну не знаю насколько это мало.

> проверить её на пригодность для выполнения задач

Это хорошо, что ты предлагаешь кому-то там проверить, а не приходишь со сколько-то конкретными проблемами этой экипировки. Так оно явно быстрее решится.

> слишком слабы перед космосом

То есть защиты от спесса теперь уже недостаточно, надо, чтобы пока ты в риге в космосе тебя лечило и оживляло или как?

И спешу напомнить, что есеска не про робуст, вот.

**Comment by Forrya** [comment]
Блин чет ерт и дедсад ну не очень. 
Добавьте их ригам 100% защиту от всего. Они же типа крутые и должны ногебать, но что то неробастные и сосут. И дайте им все спелы генки, мага, кеклинга и аплинк с 1337 телекристаллами каждому. 
Вот тогда ерт/дедсад будут ногебать всех, но это не точно.

**Comment by dearprincesscelestia** [comment]
Не будут, их засифорят.

**Comment by Forrya** [comment]
Тогда предлагаю при вызове ерт и дедсквада гибать всех отстальных егроков, даже гостов.
Хотя и тогда френдли фаером поубивают друг друга.
Соснувший дедсад - проблема дедсада.

**Comment by igigin** [comment]
>предлагаю при вызове ерт и дедсквада гибать всех отстальных егроков

А вот это хорошее предложение, так и сделаем.
