### ISSUE TITLE
Таяры не боятся воду

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1507]
#### Подробное описание проблемы
Таяры не боятся воду
#### Что должно было произойти
Таяры боятся воду как и обычные коты
#### Что произошло на самом деле
Таярам все равно на воду, некоторые даже лезут купаться и бассейны строить
#### Как повторить
Бегать за таярой с огнетушителем и пш пш пш

**Comment by Gyaviste** [comment]
Ну это скорее не в механике дело

**Comment by WallShrabnic** [comment]
С чего бы им бояться воды?

**Comment by Forrya** [comment]
Ну как бы при проверке содержимого тайтла, как если форон - отравление, то вода заставляет скримить и дает дикий голоурон.
А еще нужно закодить носок, и если его надевать на голову таяре то он так смешно будет носиться и врезаться во все.

**Comment by igigin** [comment]
Что вообще? Иди егроков допрашивай почему они воды не боятся, сюда то зачем пришёл?

А вот если бы ишьюс был бы про носок, то получил бы плашку пропозал.

**Comment by dearprincesscelestia** [comment]
Ужас, уже вместо жалоб на неарпи ишшуесы пишут.

Что завтра, ишшуесы на гриф?
