### ISSUE TITLE
Пропозал: носок на голову таярам

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1508]
Суть: добавить носок. При надевании носка на голову таяре он начинает бегать как под алкоголем, ничего не видит и смешно врезается во все, кнокаясь при столкновении. При этом сам таяра носок с головы снять не может.

**Comment by SpaiR** [comment]
http://tauceti.ru/forums/index.php?topic=1574.0

**Comment by dearprincesscelestia** [comment]
Не более нелепая идея, чем наличие тоер в билде вовсе.

**Comment by Flankir** [comment]
А адвайте ассистенты смогут банки из под доктора гибба привязывать тайрам на хвост.

**Comment by P-20** [comment]
@Flankir лучше бы Малфа доделал 😢
