### ISSUE TITLE
Собаки с болевым критом ездят на стуле

### ISSUE THREAD

**Issue by YulianR** [TauCetiStation/TauCetiClassic#1509]
#### Подробное описание проблемы

Собака-ян, сев на стул, не может быть застанен и может дальше рассекать на стуле с обычной скоростью бега (два бага в одном)

#### Что должно было произойти

Собака падает и не может дальше ехать на стуле. Ну  и корость при езде на стуле должна быть медленной как у хумана/вообще нулевой (собака ездит на стуле - что)

#### Как повторить

Найти очередного багоюзера-собаковода и попытаться его словить

**Comment by ZVee** [comment]
Ну почему сразу Ян, уже про големов забыли? А вообще это касается всех мобов.

**Comment by YulianR** [comment]
Ну, этот вопрос стал острее когда добавили управляемую собаку, так что решил написать конкретно про нее ¯\_(ツ)_/¯

**Comment by ZVee** [comment]
Собственно скоро уже расы будут обновляться и вероятно это все уйдет в этот момент, так что тут подождать чу-чуть осталось. Главное не пропустить мне это дело.
