### ISSUE TITLE
Алиены раздевают людей

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1510]
#### Подробное описание проблемы
Алиены легко раздевают людей
#### Что должно было произойти
Алиены не могут раздеть людей. Их лапы не приспособлены к подобным манипуляциям.
#### Что произошло на самом деле
Алиены спокойно сняли все, трусы, наушник, опустошили карманы, сняли противогаз
#### Как повторить
Зайти за алена и раздеть хумана

**Comment by WallShrabnic** [comment]
Пошёл нахуй. Лицеёбы не смогут сесть на лицо, если на нём уже маска

**Comment by Forrya** [comment]
Ну маску ладно. Но вот снимать гарнитуру, шляпу, тапочки и кармашки чистить - жирно пиздец. Нужно что то делать. Как пример оставить восможность раздевать только квине. Или только экзосуит, маску и голову. 
Ибо это уже не улей, а бриг получается.

**Comment by ZVee** [comment]
Насколько мне не изменяет память, у нас лицехваты игнорируют маски и даже прыгают сквозь шлема (что слегка баг) и посему, в раздевании как такового смысла то и нет. Но точно про игнор не ручаюсь сказать, т.к могло и поломаться и измениться, а у меня несколько устарелая информация на сегодняшний день.

**Comment by WallShrabnic** [comment]
Если хуманов не раздевать, то они будут вставать и выпиливать алиумов пушечками/самовыпиливаться чтобы не дать алиумам родиться

**Comment by Forrya** [comment]
ну так а для чего стражи в улье?

**Comment by kopoba** [comment]
Есть у алиумов такая фича как проглотить хьюмана но если сделать это не раздев хьюмана то хьюман гибнет алиума изнутри чемнибудь(неуверен каким оружием это можно сделать). Пологаю что раздевание хьюманов норма либо надо выпилить фичу с гибанем алиенов изнутри.
