### ISSUE TITLE
Прыгающий за карту обсервер

### ISSUE THREAD

**Issue by ghost** [TauCetiStation/TauCetiClassic#1516]
#### Подробное описание проблемы
За обсервера можно прыгать за пределы карты и наблюдать великолепное зрелище - чёрный экран

#### Что должно было произойти
Ничего! При двойном клике по чёрной зоне в краю карты ничего не должно происходить.
#### Что произошло на самом деле
Дабл клик по чёрной зоне на краю карты переносит тебя в лимб (чёрный экран). Любое движение вправо или вверх возвращает тебя из лимба в реальный мир на координаты 0, 0

#### Как повторить
Дабл клик по чёрной полосе на краю карты

#### Дополнительная информация:
Спасибо холду за багрепорт

**Comment by RichardJones1** [comment]
Чёт не воспроизводится
