### ISSUE TITLE
Невидимые артефакты

### ISSUE THREAD

**Issue by Gyaviste** [TauCetiStation/TauCetiClassic#1520]
#### Подробное описание проблемы
При ксеноархораскопках можно откопать пушки, у которых не отображается текстура
#### Что должно было произойти
Текстура должна быть
#### Что произошло на самом деле
Текстуры нет
#### Как повторить
Покопать артефакты
#### Дополнительная информация:
Спасибо KleyrtGame за баг репорт

**Comment by dred1792** [comment]
Знать бы ещё путь этих пушек, который в VV.

**Comment by Gyaviste** [comment]
Там разные есть, сейчас гляну и добавлю

**Comment by Gyaviste** [comment]
Да, путь к удалённому объекту не сохраняется в логах, могу только названия сказать:
- Alien gun
- Strange gun
- Ancient gun

**Comment by P-20** [comment]
Названия генерируются рандомно, вроде как.

**Comment by Kleyrt** [comment]
Они не только без текстур. Они ещё и исчезают, если их положить в рюкзак (как пример). Тобишь, кладёшь в рюкзак пушку - слот занимается. Наводишь - а пушки нету. И не вытащить никак. Только слот занимает. 
Как пример могу привести скриншот. Описание у пушки обычное, как обычно рандомное. 

That's Alien gun. 

A archaic gun made of plasteel, all craftsmanship is of low quality. It is studded with gold and is encircled with bands of duranium.

![p1abv6jitre](https://cloud.githubusercontent.com/assets/22774045/26530399/02600d9a-43dd-11e7-905b-d37085055b54.jpg)


Могу продемонстрировать подобное, ибо мне на них везёт. Вчера 3 подряд выпало. Но продемонстрировать такое смогу только в понедельник, скорее всего ночью. Даже записать могу видео. 
Ну и конечно же хотелось бы, чтобы пофиксили побыстрее. Ибо копаешься, стараешься, а в итоге получаешь фигу. 
(и да, я KleyrtGame, тут просто ник сокращён)

**Comment by Kleyrt** [comment]
Ну и да, скорее всего, у всех пушек выкопанных наблюдается такой баг. Ибо 3 подряд пушки с таким багом. Не думаю, что совпадение.

**Comment by igigin** [comment]
> Они ещё и исчезают, если их положить в рюкзак

Не исчезают, просто ты не можешь выделить что-то у чего нет спрайта. А так, они там есть и ими даже можно пользоваться.

**Comment by dred1792** [comment]
Только у энергетических. У огнестрела тоже была такая проблема, но её ещё 6 мая 2013 пофиксили.

**Comment by Kleyrt** [comment]
@igigin Но из рюкзака не вытащить руками смертного. Поэтому занимают место и мешаются сильно. Всё же, для ксеноархеолога даже один слот важен

**Comment by Kleyrt** [comment]
@dred1792 Если честно - я без понятия, энергетические они или нет. Когда я пытался стрелять - раздавался щелчок, как если стрелять из оружия без патронов/разряженного. Ну а по пустоте не определишь, какая там пушка.

**Comment by Gyaviste** [comment]
По VV энергетическая, но пути не помню.

**Comment by igigin** [comment]
Энивей Дред уже решает проблему.

**Comment by Kleyrt** [comment]
Это хорошо, что решает. Благодарю.

**Comment by dred1792** [comment]
Там у пушек шанс есть появится пустыми. А в тему класса оружия я говорю потому что огнестрел я давным-давно как-то выкапывал.

**Comment by Kleyrt** [comment]
@dred1792 Значит, я очень везучий. Все три, что выпали, были пустыми
