### ISSUE TITLE
Реквест копипаста поведения макак

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1529]
Собсна посмотрев поведение макак на тестовом фтл серве считаю что просто мастхев портировать поведение их на основной сервер. 
Просто представьте вопли офицеров, когда выбитым из их рук оружием макаки будут им же надирать задницы. Мастхев.

**Comment by ZVee** [comment]
У меня контр-реквест тогда - перед портом надо чтобы оптимизировали ИИ мобов в целом, потому что львиную долю нагрузки мы получаем собственно от всяких макак которые просто ходят в рандомную сторону и мобов с астероида, так что более сложные операции будут очень не к месту.

**Comment by WallShrabnic** [comment]
Форря, прекращай, серьёзно, будто вчера Гитку открыл

**Comment by Forrya** [comment]
Это не я. Меня емагнули.

**Comment by Avatar4** [comment]
Там макаки могут тебя задизармить за случайный удар, отобрать огнетушитель, забить тебя им (не давая встать при этом) а потом запихнут тебя в вольер с слаймами (я серьезно). Это не говоря уже о том, что обидев одну макаку, на тебя нападут все.

**Comment by RichardJones1** [comment]
Да
