### ISSUE TITLE
Баг ручного телепортера

### ISSUE THREAD

**Issue by ghost** [TauCetiStation/TauCetiClassic#1530]
#### Подробное описание проблемы
При активации ручного телепортера портал открывается на тайле игрока, из-за чего при любых взаимодействиях с инвентарём предметы перемещаются внутри этого тайла, портал засчитывает что предмет вошёл в тайл и телепортирует его, при этом визуально предмет остаётся в инвентаре. Визуальный баг наличия его в инвентаре исчезает, если подойти к настоящему телепортировавшемуся предмету и подобрать его.

#### Что должно было произойти
Предмет должен был перемещаться по инвентарю

#### Что произошло на самом деле
Предмет улетел на телепорте, оставив за собой визуальный баг.

#### Как повторить
Берём ручной телепортер, включаем, пытаемся, например, надеть очки, очки телепортируются, в руке остаётся их визуальная копия.

#### Дополнительная информация:
Спасибо Sahass123 за найденный баг

**Comment by StrikS** [comment]
Не раз были такие проблемы. Отлично, что нашли и зарепортили.

**Comment by Motzord** [comment]
Не пофикшено
