### ISSUE TITLE
Терминал съедает карту

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#1532]
#### Подробное описание проблемы
Вставил в "Аккаунт аплинк консоль" карту, нажимаю на терминал - не открывается окошко.
#### Что должно было произойти
Окошко должно было открыться.
#### Что произошло на самом деле
Терминал съел карту и достать её нереально, он не поддаётся инструментам.
#### Как повторить
Суньте карту в этот терминал.

**Comment by SpaiR** [comment]
Просьба в следующий раз излагать информацию конкретней. И названия объектов лучше давать на английском, как есть в игре. Лично мне было не очевидно о какой консоли идёт речь и помогла лишь помощь зала.

**Comment by Udokun** [comment]
Account uplink terminal.

**Comment by ZVee** [comment]
А это случайно не наноуи баг? А то только нано любит не открываться по какой-то там неведомой причине.

**Comment by volas** [comment]
Скорее наноюи, проблема давняя, сейчас появится отдельная кнопка для "фикса" (на самом деле тот еще костыль). Я закрою, так как терминал скорее не при делах. Если что, переоткрой.
