### ISSUE TITLE
Прицел на Яне

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#1533]
#### Подробное описание проблемы
Когда кто-то целится на Яна и убирает прицел, метка остаётся.
#### Что должно было произойти
Метка должна была пропасть.
#### Что произошло на самом деле
Она осталась с ним до конца дней.
#### Как повторить
Прицельтесь в собаку

**Comment by Gyaviste** [comment]
То же, например, на слайме. И, вероятно, на прочих животных.
