### ISSUE TITLE
Пропажа солцезащитных очков из лодаута

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1536]
#### Подробное описание проблемы
Из лодаута исчезли солнцезащитные очки
#### Что должно было произойти
Они должн были там остаться
#### Что произошло на самом деле
Их нет
#### Как повторить
Идти настроить лодаут
#### Дополнительная информация:
Сначала щетина, теперь очки...
Без очков мой персонаж выглядит ну так себе, лицом 7/10, а в очках 10/10

**Comment by Kurshan** [comment]
Лоадаут не предназначен для механобонусов, поэтому и убрали.

**Comment by Forrya** [comment]
Добавили бы бюджетные солнцезащитные только со спрайтом обычных. А то все.
