### ISSUE TITLE
Бесконечный генетический инъектор

### ISSUE THREAD

**Issue by sovok4** [TauCetiStation/TauCetiClassic#1537]
#### Подробное описание проблемы
Инъекторы в генетике (одного блока и всех) можно использовать от нескольких раз до бесконечности. Какой-то сработал три раза, прежде чем пропасть, каким-то обколол всех мартышек в генетике и себя, но он не исчезал и, судя по всему, не срабатывал. 
#### Что должно было произойти
Инъектор колется один раз, затем пропадает из руки.
#### Что произошло на самом деле
Иъектором можно колоть до бесконечности, из руки он не пропадает. Его можно выбросить, подобрать, снова обкалываться. При этом, например, инъектор с чистыми генами не вылечил куклу даже после пяти уколов, но каждый укол наносил урон токсинами.
#### Как повторить
Сделать на генетической консоли инъектор (DNA-Injector), обкалываться одним инъектором до посинения.

**Comment by Forrya** [comment]
Если после юза его класть в коробочку в рюкзаке - можно колоть им еще. Вроде как после юза если ты делаешь с ним то, что прерывает действие - хождение, бросание, складывание в сумочку, то он остается.

**Comment by igigin** [comment]
>затем пропадает из руки

Не надо пропадать, надо становиться использованным, бесполезным и пустым.
