### ISSUE TITLE
Проблемы с mashine frame у Дрона.

### ISSUE THREAD

**Issue by Arnagedol** [TauCetiStation/TauCetiClassic#1542]
#### Подробное описание проблемы:
Дрон не может вставить микросхему в machine frame.

#### Что должно было произойти:
При поднятии микросхемы для machine frame (SMES, Cyborg Recharging Station) она должна помещаться в mashine frame для дальнейшей сборки нужного аппарата.

#### Что произошло на самом деле:
Ничего не происходит, поднятие держателем есть, но при нажатии на machine frame ничего не реагирует, плата не устанавливается и из-за этого восстановить станцию не получается.

#### Как повторить:
Разобрать любой machine frame дроном или создать новый имея плату скажем SMES и попробовать вставить плату подняв её магнитным держателем.

#### Дополнительная информация: 
Восстанавливать компьютеры Дрон может, а вот все что связано с machine frame нет.

**Comment by Forrya** [comment]
Смесы не собираются

**Comment by Arnagedol** [comment]
В каком смысле не собираются? 
SMES
1x Circuit board.png SMES Board
1x Capacitor.pngCapacitor
5x Power cell.pngPower cells
5x CableCoils.pngPieces of cable
И Cтация зарядки киборгов
1x Circuit board.png Cyborg Recharger Board
2x Capacitor.pngCapacitors
1x Power cell.pngPower cell
1x Micro Manipulator.pngMicro manipulator

**Comment by Forrya** [comment]
В прямом смысле. СМЕСы не собираются.

**Comment by Arnagedol** [comment]
Разве это нормально? А по поводу зарядников? Я не совсем понимаю твои сообщения, это сделано специально? Если да - то зачем?

**Comment by Forrya** [comment]
Кодирысуки, сборку поломали.

**Comment by T6751** [comment]
актуально. ни за дрона, ни за инжеборга нельзя вставить плату в machine-frame. А если плата вставлена, то нельзя вставить компоненты. Пишет "You cannot add that to the machine!"
