### ISSUE TITLE
Культ нульспейса

### ISSUE THREAD

**Issue by Gyaviste** [TauCetiStation/TauCetiClassic#1543]
#### Подробное описание проблемы
Если призвать культиста когда тот в слипере, то он улетит в нульспейс
#### Что должно было произойти
Культист должен был выпасть из слипера и призваться, или призваться вместе со слипером
#### Что произошло на самом деле
Культист в нульспейсе
#### Как повторить
Кладёте культиста в слипер -> Призываете -> PROFIT

**Comment by WallShrabnic** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/1251
Возможно, связано с этим

**Comment by Kurshan** [comment]
#1670
