### ISSUE TITLE
Невозможность создания имени с циферками в настройке персонажа

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1544]
#### Подробное описание проблемы
Отсутствует возможность использования цифр в имени. Выдает ошибку.
#### Что должно было произойти
Можно создать имя с циферками.
#### Что произошло на самом деле
Оно не принялось.
#### Как повторить
В настройке персонажа попытаться создать имя используя циферки также.

**Comment by Gyaviste** [comment]
Так это специально сделано

**Comment by Forrya** [comment]
У моего СПУ в имени три циферки. 
Мне писать U-DeviatShestDevyat ?

**Comment by Gyaviste** [comment]
Ну так и пиши СПУ
Большинству рас не нужны эти циферки

**Comment by Forrya** [comment]
Екх((9(
