### ISSUE TITLE
Жукбокс сломался

### ISSUE THREAD

**Issue by PavelYo** [TauCetiStation/TauCetiClassic#1550]
#### Подробное описание проблемы
При выборе любого альбома из меню жукбокса после дооолгой загрузки не появляется ни одной песни из альбома а только какая то надпись.
#### Что должно было произойти
После загрузки альбома должна появится музыка.
#### Что произошло на самом деле
Не появилось ни одной музыки в меню.
#### Как повторить
Используйте жукбокс

**Comment by Lancer411** [comment]
@PavelYo Сервер с джуком был недоступен. Сейчас все должно работать.
