### ISSUE TITLE
Обувь не стирается/не чистится

### ISSUE THREAD

**Issue by Ajajumbo123** [TauCetiStation/TauCetiClassic#1551]
#### Подробное описание проблемы
Спрайты ботиночков нельзя отмыть в стиралке или раковине от крови. Точнее снаружи спрайта персонажа все отмывается, а вот сам спрайт предмета в слотах остается окровавленным. 
#### Что должно было произойти
Ботинки должны сверкать
#### Что произошло на самом деле
Они в говне
#### Как повторить
Потопать по кровавым лужам и отправиться мыть бутсы в стиралке или раковине
#### Дополнительная информация:
Клинером ботинки очистить можно

**Comment by LudwigVonChesterfield** [comment]
#5278 

Там более общее.

**Comment by LudwigVonChesterfield** [comment]
Обувь кстати чистится.
