### ISSUE TITLE
Жукбокс слышно там где его не должно быть слышно

### ISSUE THREAD

**Issue by PavelYo** [TauCetiStation/TauCetiClassic#1556]
#### Подробное описание проблемы
Если поставить жукбокс на кухне то его будет слышно в баре, не слышно в комнате с животными за кухней пно почему то слышно в комнате где рубят мартшек.
#### Что должно было произойти
Жукбокс не должен слышаться в баре и в комнате где разделывают мартышек.
#### Что произошло на самом деле
Когда жукбокс играет на кухне его слышно в баре и в комнате..ну вы поняли.
#### Как повторить
Поставьте жукбокс на кухне и включите

**Comment by WallShrabnic** [comment]
Жукбокс транслирует музыку не на расстоянии, а на всю текущую и прошлые зоны. Кажется, это можно зафиксировать только выпилили жукк

**Comment by Avatar4** [comment]
Я об этом уже писал но хз как найти.

**Comment by igigin** [comment]
#1173.
