### ISSUE TITLE
Реквест шмоток клоуна с ТГ

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1558]
На тг у клоуна в автомате есть костюмы КОРГИ и КАРПА. Надо сюда их стаукетить.
Ето же такой простор для ропе будет.
Осистенты в костюмах корги под предводительством Яна толпой болонят петушителями визорда. Ммммммм...

**Comment by Gyaviste** [comment]
На твой ишьюс забьют, ибо пропожал :peka:
