### ISSUE TITLE
Реворк формулы талесаенса

### ISSUE THREAD

**Issue by psebash** [TauCetiStation/TauCetiClassic#1575]
#### Подробное описание проблемы
Как уже всем известно, калькулятор слит на форуме и нужен реворк формулы
#### Что должно было произойти
Калькулятор не должен был слит, только илитка может в талесаенс
#### Что произошло на самом деле
Он слит. В талесаенс может любой смолгей
#### Как повторить
Проверить форум
#### Дополнительная информация:
N/A

**Comment by Gyaviste** [comment]
Но его же будут сливать, пока билд не станет закрытым.

**Comment by Shudyn** [comment]
Нужно просто добавить больше рандома в телесайнс. Погрешность во всем +-100 единиц и потребление энергии 100к в секунду при открытой червоточине. Тогда вот точно не будет такого, что малфу с телесайнса закинули лимитку или кража нюки у нюкеров.

**Comment by ZVee** [comment]
Вам если калькулятор занерфить надо, вы так и скажите - уберу все формулы в конфиги что равноценно закрытости билда. А так, не вижу ничего плохого в нем.

**Comment by DctrMM** [comment]
Лично я видел только двух-трех людей, после слива калькулятора, кто использует калькулятор.

**Comment by Avatar4** [comment]
Нужен ревок педалей.

**Comment by Gyaviste** [comment]
>Нужен ревок педалей.
Пермбаны за калькуляторы
