### ISSUE TITLE
Кравлозач: мейк евакуатион подс грет эгейн

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1577]
Сейчас поды ну не то что бы говно какое то, используются раз в день и то - праздничный.
Выгоды лететь на них не слишком много. Есть шатл, он прямо на цк, да и добрая часть коецов раунда - трансфер, когда улетает только шаттл.
Что я предлагаю что бы кто то сделал?
Сделать поды эвакуации действительно таковыми.
Они должны спасать екипаж. 
Как я представляю идеальный под:
По внешнему виду - та же колбаска.
На фронтальное стекло только консоль добавить о которой расскажу чуть позже.
Интерком перенести на стену.
Добавить шкафчик рядом с интеркомом. В него два бическафандра, куча болончиков желтого цвета, две кирки.
Еще один шкафчик - там пара космоаптечек.
И третий шкафчик - там покушать и вода.
Месте в поде так же два. 

Теперь о компухтере пода:
Поскольку это маленькая капсулка с небольшим двигателем который только выталкивает капсулу в нужном направлении можно сделать для пода настраиваемое направление. Например она может отстреливаться или на астероид, или в далекий космос.
Поскольку под создан что бы спасать жизни запускаться он может простым членом екипажа, но при синем коде и выше.
После выбора направления полета идет оповещение в общий канал, что капсула стартует через тридцать секунд. 
Спустя десять секунд закрываются и болтируется шлюз пода и шлюз со станции к поду.
Через двадцать секунд - запуск.
Самый сок компухтера в том, что он взламываемый.
Например в нем 5 проводов.
Один отвечает за шлюз: открытие и закрытие с болтами.
Второй за оповещение станции о пуске по радио.
Третий за выбор направления.
Четвертый за сброс требований, то есть воздействовав на него мы сможем отстрелить его при грин коде.
А пятый ебашит током.

То есть в случае полной пепы можно за текникал асистота и инженера при грин коде убегать от внезапной нюки.

Так же тритоте задание можно на отстрел подов сделать. Ох уж и вылетит в копеечку НТ замена подов на новые.
Потому что сейчас единственный рабочий эвакуационный под - гроб из церкви. И то к нему скаф нужен нормальный.

**Comment by WallShrabnic** [comment]
Поясню по порядку
> Выгоды лететь на них не слишком много. Есть шатл, он прямо на цк, да и добрая часть коецов раунда - трансфер, когда улетает только шаттл.
Проблема в том, что роли зачастую полтора часа аутируют, в итоге приводит к крю
> Они должны спасать екипаж.
Не в наших реалиях, где разгерма убивает за 15 секунд
> То есть в случае полной пепы можно за текникал асистота и инженера при грин коде убегать от внезапной нюки.
Шаттл шахтёров для кого? И вообще, при внезапной нюке максимум что ты успеешь - соснуть от разгермы. В условиях, когда все техи в разгермах, не так то и просто дойти до пода. И вообще, нюкерам ничего не мешает сломать ту же консоль на поде.

**Comment by Flankir** [comment]
Дело не в том что роли аутируют, просто все что приводит к эвакуации им тупо запрещено.

**Comment by Forrya** [comment]
Ну то есть вот синга сожрала четверть станции. От инженерки до брига дырень. И вот синга развернулась и летит на восток. Екипаж там не может спастись. И их сжирает синга.
А они могли бы забежать все в поды, которых побольше сделать, и сбежать в кексмас.

**Comment by Flankir** [comment]
Да, когда поды не были занерфаны в хлам именно так и происходило при подобном шухере.

**Comment by Forrya** [comment]
Я и хочу что бы спасательные поды именно ими и были.
Не шаттлом #2, а шансом на спасение.

**Comment by WallShrabnic** [comment]
>Шаттл шахтёров для кого?
