### ISSUE TITLE
Боты-уборщики не работают

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1579]
#### Подробное описание проблемы
Боты-уборщики не работают
#### Что должно было произойти
Они должны патрулировать станцию и чистить говно и кровь
#### Что произошло на самом деле
Они отключаются
#### Как повторить
Создать бота уборщика и врубить
#### Дополнительная информация:
Создал 4 бота в коридоре и ноль результата

**Comment by Lexakr** [comment]
Проблема очень надоедливая, ето так

**Comment by igigin** [comment]
Подобный ишьюс уже есть.
#1381
