### ISSUE TITLE
Сломали катание на мыле

### ISSUE THREAD

**Issue by psebash** [TauCetiStation/TauCetiClassic#1581]
#### Подробное описание проблемы
Если тащить кнокнутого игрока пуллом и сбрасывать периодически мыло, то он не поскальзывается
#### Что должно было произойти
Он должен был опять поскользнуться и остаться лежать
#### Что произошло на самом деле
Он не поскользнулся, встал на мыле 
#### Как повторить
Пуллить игрока и выкидывать мыло по дороге
#### Дополнительная информация:
С кожуркой тоже не работает, про пда кловня не знаю

**Comment by ZVee** [comment]
Кнокнутый игрок который поднялся никогда и не поскальзывался на мыле и не должен, если мыло или еще что такого рода было прямо под ним. А вот баго-фича с тем, что можно было без конца ронять лежачего - это слишком фича чтобы ее в какой-то момент не исправили, к тому же этим можно было уронить сервер.
