### ISSUE TITLE
Дверь пода открывается каждому, с любой из сторон. 

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1584]
#### Подробное описание проблемы
Дверь пода во время полета, да и до открывается каждому, с любой из сторон. Заварить ее нельзя, провода обрезать что бы болты опустить - тоже.
#### Что должно было произойти
Дверь пода можно хотя бы заварить.
#### Что произошло на самом деле
При попытке ее заварить она открылась.
#### Как повторить
Зайти в под, тыкать в его дверошлюз включеной горелкой, отверткой.
#### Дополнительная информация:
Мейк подс гриат эгейн плиииииз

**Comment by P-20** [comment]
Достаточно сделать внутри пода кнопку, которая блокирует шлюз.  А то никакой системы безопасности. И во время полета можно вылететь из пода, открыв шлюз.
