### ISSUE TITLE
Экспериментальной горелки нет в протолате.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1585]
#### Подробное описание проблемы
Экспериментальной горелки нет в протолате.
#### Что должно было произойти
Она должна быть.
#### Что произошло на самом деле
Ее нет.
#### Как повторить
Апнуть рнд и проверить.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/19417166/27308755-0fc2952e-5559-11e7-81be-3dfb547b0775.png)

**Comment by igigin** [comment]
Так ты изучил форон, а надо было плазму.
