### ISSUE TITLE
Голиаф-садист с дипломом доктора.

### ISSUE THREAD

**Issue by Zandwitch23** [TauCetiStation/TauCetiClassic#1586]
#### Подробное описание проблемы
По сути получается, что голиаф ведёт себя неестественно. Вполне можно понять его злобу на всё человечество (ещё бы, так засирать астероид пустыми инжекторами и прочим хламом), но не понятно почему он не идёт до последнего?...
#### Что должно было произойти
Голиаф должен месить рожу персонажа пока, тот не умрёт. 
#### Что произошло на самом деле
Голиаф агрится и бьёт персонажа ровно то тех пор, пока второй не потеряет сознание, и потом идёт  гулять дальше.
#### Как повторить
Встать рядом с голиафом.
#### Дополнительная информация:
Как вариант можно сделать так, чтобы голиаф переставал нападать на персонажа, когда тот просто падает на землю (с малой долей вероятности). Так появится фича "притвориться мёртвым".

**Comment by Forrya** [comment]
Все мобы так себя ведут. Что бы притвориться мертвым нажмите слпшшшш.

**Comment by Zandwitch23** [comment]
Ну, тут затрагивается тема конкретно голиафа. Понятно, что это для баланса сделано, чтоб можно было человека успеть спасти и всё такое. Я скорее был за фичу drop dead :пекапрячется:  Но там же скажут "кодить будешь сам". 
>Что бы притвориться мертвым нажмите слпшшшш.

Это ты о чём?

**Comment by Forrya** [comment]
Нажимаешь слип - моб не агрится на тебя.

**Comment by volas** [comment]
С этим, наверно, нужно что-то делать, так что пускай будет открыто
