### ISSUE TITLE
Ломающийся детектор руды руды (ore detector).

### ISSUE THREAD

**Issue by chooryou** [TauCetiStation/TauCetiClassic#1589]
#### Подробное описание проблемы

При попытки просканировать землю ничего не происходит.

#### Что должно было произойти

Должны были появиться результаты сканирования.

#### Что произошло на самом деле

Ничего.

#### Как повторить

Попросить админа заспавнить новый сканер.

#### Дополнительная информация:

Баг происходит если при сканировании двинуться.

**Comment by Uvash** [comment]
Уже пофиксил
