### ISSUE TITLE
Посох лечения

### ISSUE THREAD

**Issue by hitsedesen** [TauCetiStation/TauCetiClassic#1590]
#### Подробное описание проблемы
Когда держишь в руке посох лечения появляется кнопка Switch Gun, при её нажатии ничего не происходит.
#### Что должно было произойти
Кнопки не должно быть.
#### Что произошло на самом деле
Кнопка есть.
#### Как повторить
Взять в руки посох лечения.

**Comment by WallShrabnic** [comment]
Эта кнопка вроде появляется у всего, что связано с оружием, например, у других посохов, или игрушечных пушек
