### ISSUE TITLE
[HIGH PRIORITY PROPOSAL] Проблемы воксов.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#1592]
#### Подробное описание проблемы
1)У воксов настолько древний корабль, что там есть наброски ИИ и роботики. Но шлюзы не просматриваемые, и в них отсутствуют камеры.

2)Из-за балона на спине, они лишаются ранца, который вмещает вещи приличной тяжести(w-3), такие как патроны, стрелы, и многое другое, и они, не влезают в тоолбелт, разгрузку, карман. А так же из-за этого невозможно спрятать оружие. (На поясе = на виду)

3)В алиен дарт гане, насколько заметил отсутствуют медицинские картриджи, там находятся лишь банки с наркотиками. Хотя если не ошибаюсь, у них должен быть ган, непосредственно уже для лечения союзников.

4)У пиратов при спавне всплывал текст о режиме в целом и фултоне, тут можно было бы сделать нечто такое, подробнее расписав основы.

5) Стекла у заключенных/рекрутов и еще во многих местах не сплошные, и их можно легко сломать.

6) В некоторых проходах отсутствует пол.

7)С мостика отсутствует обзор на шлюзы.

8) Присутствует медицинский сканер, но отсутствуют инструменты для операция. В таком случае нужны мешки для трупов, куда можно складывать умирающих воксов

9) Шляпа лидера, которую на шатле должен одеть лидер. Не является шлемом, и не держит космос(под вопросом)

10)У Воксов сверхсветовые двигатели представлены сферой, диаметром более полу-метра, который/е, устанавливаются на носу. Тут же древние нанотрейзановские двигатели на заду.

11) Из-за плохой планировки стен, теряется много пространства на корабле.
(#ВернитеКроваткиКакЖеВоксыСпят)

12) У Воксов нет раций, для общения со станцией.

#### Дополнительная информация:

**Comment by Damirrus1** [comment]
![image](https://user-images.githubusercontent.com/21046015/27356873-90348e08-5629-11e7-8c65-8f95591c9a53.png)
сперли

**Comment by WallShrabnic** [comment]
Для наших реалий можно было бы и воксов обновить, а то они будут сосать по КД из-за хуёвости своей эквипы

**Comment by ZVee** [comment]
>Для наших реалий можно было бы и воксов обновить, а то они будут сосать по КД из-за хуёвости своей эквипы

Очень информативно, особенно на фоне того, когда вокс вчера вытакновал фул еган, и еще после встал. А если речь про дырки, ну, И - информативность

**Comment by CryptoKisik** [comment]
Воксы достаточно сильны. Их огромный минус в отсутствие джетпака. Вот здесь могу предложить заменить баллон на джетпак. Что бы и дышать, и летать.
А так. Броня их достаточно крепка. Вокс вчера выдержал фулл заряд егана и даже не умер. В спесе. И больше скажу. Он жил еще минут 20. А потом его судьба была не известна, но вроде как выжил.

Каков смысл баффать что-то, что достаточно сильно? Если игроки не умеют на этом играть, то стоит это баффать? Ну, давайте баффнем нюку, ведь могут попасть на нее слабые игроки и она соснет. А может сразу выдадим триторам 500 телекристаллов? Ну, что бы они сильные были и не боялись все покупать.

И так далее. Попались слабые игроки. Проиграли. Как и указал выше - проблема в игроках и джетпаке. Больше не вижу.

**Comment by ZVee** [comment]
>У воксов настолько древний корабль, что там есть наброски ИИ и роботики. Но шлюзы не просматриваемые, и в них отсутствуют камеры.

Не так чтобы это на самом деле нужно было, да и не положено по бэку (плюс есть воксы с термалами).

>Из-за балона на спине, они лишаются ранца, который вмещает вещи приличной тяжести(w-3), такие как патроны, стрелы, и многое другое, и они, не влезают в тоолбелт, разгрузку, карман. А так же из-за этого невозможно спрятать оружие. (На поясе = на виду)

Баллон надо на риг цеплять же и если надо снять риг, берешь баллон в руку перед этим. Если другому воксу - надеваешь ему на спину второй предварительно, ну или быстро надеваешь при снятии.

>В алиен дарт гане, насколько заметил отсутствуют медицинские картриджи, там находятся лишь банки с наркотиками. Хотя если не ошибаюсь, у них должен быть ган, непосредственно уже для лечения союзников.

Там вообще-то два дартгана, один медикал - с келотаном, бикардином и диловеном, а второй с спейс драгами, слип токсином и импедризином. Плюс медик спавнится с медикалом, а саботер со вторым.

>В некоторых проходах отсутствует пол.

Это дизайн.

>С мостика отсутствует обзор на шлюзы.

У вас есть как правило два вокса с термалами, и это их работа мне кажется, а для остальных уже неожиданность.

>Присутствует медицинский сканер, но отсутствуют инструменты для операция. В таком случае нужны мешки для трупов, куда можно складывать умирающих воксов

Тулбокс для гетто-хирургии лежит, да, именно гетто-хирургии, либо крадите со станции.

>Шляпа лидера, которую на шатле должен одеть лидер. Не является шлемом, и не держит космос(под вопросом)

Ну ее как бы просто схватить надо, тем более для воксов нет спрайт шляпы и она все равно невидимая на голове.

>У Воксов сверхсветовые двигатели представлены сферой, диаметром более полу-метра, который/е, устанавливаются на носу. Тут же древние нанотрейзановские двигатели на заду.

Это не к кодерам.

>У Воксов нет раций, для общения со станцией.

А кто мешает настроить наушник на 145.1? Единственный минус, придеться использовать :h для общения на "синди-частоте", а не ";", т.к точка с запятой это разговор по настроенной частоте наушника.
