### ISSUE TITLE
Позитронки в мехах не могут использовать оружие

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1595]
#### Подробное описание проблемы
Позитронки в мехах не могут использовать оружие. Спрайт того чем стреляют остается на полу - лазер или пуля.
#### Что должно было произойти
Мех должен стрелять и попадать.
#### Что произошло на самом деле
На полу под мехом спрайтик выстрела
#### Как повторить
Засунуть позитронку в меха
#### Дополнительная информация:
Мех с человеком до этого стрелял нормально

**Comment by Damirrus1** [comment]
![image](https://user-images.githubusercontent.com/21046015/27381897-057fc140-569e-11e7-906c-a711d775acf1.png)

**Comment by Forrya** [comment]
Я вообще хотел у инженерки свастон выстроить, но там гиявице и совок и мне бы песта

**Comment by Gyaviste** [comment]
IC in OOC, ай-ай-ай

**Comment by Forrya** [comment]
Ого ща дамирусу пермачь прилетит за ик в гитхаб

**Comment by P-20** [comment]
>Когда куршан решил зафиксить миссы 
🎖 @Kurshan🥇@Kurshan 🎖

**Comment by Kurshan** [comment]
Подождёте ещё месяц, доберусь и до этого.. :pekapled:

**Comment by Flankir** [comment]
У позитронок не засунутых в борга или ии стоит закон никому не вредить, с какой стати они должны юзать оружие вообще?

**Comment by Gyaviste** [comment]
У позитронок нет законов.

**Comment by Damirrus1** [comment]
est'

**Comment by rasl1410** [comment]
У них нет законов.

**Comment by rasl1410** [comment]
Никогда не было
