### ISSUE TITLE
[Proposal] Понизить вероятность выпадения абдукторов в секрете

### ISSUE THREAD

**Issue by sovok4** [TauCetiStation/TauCetiClassic#1597]
#### Подробное описание проблемы
Каждый раунд абдукторов превращает станцию в хаотичный содом. При этом абдукторы выпадают чаще ламповых триторов. Да я уже даже по генокрадам через раунд скучаю, вот времена-то были. Тихие. Спокойные.
#### Что должно было произойти
Абдукторы не должны выпадать так часто из-за крайней грифозности режима и неспособности наших игроков в адекватность.
#### Что произошло на самом деле
Абдукторы раз в три раунда. Станция в крови, говне, все друг-друга бьют, ахелп разрывается от жалоб.
#### Как повторить
Играть на таусети, "самом грифозном сервере бьенда"

**Comment by CryptoKisik** [comment]
Ну, с тем же успехом будет рева или генки, или нюка. И будет говно. Ну, если не стелс-генки. Или стелс-триторы.
Вся соль в игроках. допустим сегодня были кондукторы, которые украли из хирургии оба фикс-о-вейна, ретракторы и костоправы. В итоге чинить людей было о-о-о-очень тяжело. И приходилось использовать гетто-хирургию. А вообще, кондукторы. самый легкий режим.

**Comment by Uvash** [comment]
Вначале была открытая нюка. Теперь кондукторы...

**Comment by l0lone** [comment]
Проблема не столько в высоком шансе абдукторов, сколько в том, что у людей галочки на большинство ролей не стоит. Сколько не чекаю, у половины игроков только рева на "yes" стоит, а уж культисты и того реже. В итоге это очень сильно влияет на то, какой режим выпадет в секрете.
