### ISSUE TITLE
Супер бесполезная горелка.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1599]
#### Подробное описание проблемы
Горелка которая исследуется в рнд, это всего лишь респрайт горелки из инженерки с 40 единицами заряда топлива которая не может всунуться в пояс а так же не восстанавливает топливо.
#### Что должно было произойти
Она должна помещаться в в пояс с инструментами и восстанавливать топливо.
#### Что произошло на самом деле
Она просто большая и бесполезная горелка.
#### Как повторить
Исследовать в рнд.

**Comment by Avatar4** [comment]
Для сравнения.
http://imgur.com/y4qsywW

**Comment by igigin** [comment]
Это так.

**Comment by Gyaviste** [comment]
Зато она *маленькая*
