### ISSUE TITLE
Бипскай плевал на оружие.

### ISSUE THREAD

**Issue by LuckyAss** [TauCetiStation/TauCetiClassic#1600]
#### Подробное описание проблемы
Бипскай плевал на нюкеров, которые ходят с оружием.
#### Что должно было произойти
Бипскай должен был триггернутся на оружие в руках нюкеров
#### Что произошло на самом деле
Бипскай прошел мимо нюкеров
#### Как повторить
Пройтись мимо бипская с оружием

**Comment by ZVee** [comment]
Включайте бипски режим проверки айди и оружия. Он по дефолту выключен, потому что иначе бипски будет на всех кидаться у кого в руках оружие.

**Comment by LuckyAss** [comment]
Тут дело в другом, он чекает у нюкеров типа доступ, а прочесть не может, из-за чего и не триггерится. Но по АрПи, как по мне, если у человека нет инфы в базе данных, но есть оружие в руках, то бипски должен триггерится.
