### ISSUE TITLE
Стимпаки с чугуном.

### ISSUE THREAD

**Issue by Zandwitch23** [TauCetiStation/TauCetiClassic#1603]
#### Подробное описание проблемы
Stimpack замедляет персонажа, не одетого в риг.
#### Что должно было произойти
Скорость передвижения не должна меняться.
#### Что произошло на самом деле
После использования стимпака появилась боль в суставах, депрессия, возможно мысли о суициде.
#### Как повторить
Использовать стимпак.
#### Дополнительная информация:
Любой стимпак.

**Comment by LuckyAss** [comment]
Вкусив плод химии, называемый гиперцин, я начал медленнее двигаться и больше не могу кататься на кресле как бешеная табуретка.
