### ISSUE TITLE
Чужим можно вскрыть глотку/задушить при использование агрессивных граб хватов

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#1604]
#### Подробное описание проблемы
Если взять чужого в агрессивный граб, то мы получим возможность вскрыть ему горло или задушить.

**Comment by Zandwitch23** [comment]
Да вообще, кхеноморфы не страшные. Нужно активировать наконец вторую челюсть, хвост и кислоту - всё то, собственно, чем страшны алиумы при близком контакте.

**Comment by Tolerantboy** [comment]
Ну, вскрыть горло это еще ладно. Но душение надо пофиксить - им же и в вакууме норм, следовательно они не дышат

**Comment by ZVee** [comment]
Это сейчас они не дышат, а планируются им введение легких которыми ксеноморфы смогут задерживать дыхание примерно на 3-5 минут.

**Comment by Tolerantboy** [comment]
Не помню, чтобы аналиены в фильмах нуждались в кислороде - спокойно ходили по обшивке кораблей/станций. Но у них есть дыхательные трубки на спине и вроде как они действительно чем-то дышат, но не вакуумом же? Так что может они и действительно **временно** могут жить в безвоздушной среде

**Comment by Avatar4** [comment]
Представьте что алиумы это дельфины.

**Comment by RichardJones1** [comment]
Стоп... @volas , разве ты не ввёл им нуждаемость в атмосфере?

**Comment by LudwigVonChesterfield** [comment]
Тут больше нет проблемы.
