### ISSUE TITLE
Добавьте самодельное оружие с тг билда.

### ISSUE THREAD

**Issue by petypukin** [TauCetiStation/TauCetiClassic#1606]
У нас очень мало самодельного оружия, добавьте с тг билда.

**Comment by Forrya** [comment]
Особенно ту самую йоба гаусс пушку ебущую малфа.

**Comment by petypukin** [comment]
Или добавьте самодельное оружие с VG билда, там тоже классное

**Comment by Zandwitch23** [comment]
Поднял палец, но я скорее за новые изобретения. Глянул на других вики в первый раз (если рецепты крафта всё ещё актуальны), так себе, ожидал большего. Самопал же он такой, делаю из того что вижу. А из того что лежит на станции можно сделать, пилять, тонну оружия! Пукин, закинул бы темку на форум для идей, чтоб подробно описывали процесс крафта.

**Comment by petypukin** [comment]
подниму
