### ISSUE TITLE
[Proposal] Random job

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#1617]
#### Подробное описание проблемы
Раунд давно идёт. Вы решаетесь в него зайти. У вас возникает вопрос: Кем умереть на этой станции? Глаза разбегаются от количества доступных профессий. Закрываете глаза и клацаете мышкой на случайную роль. Слишком долго и глупо.
#### Что должно было произойти
Вы жмёте кнопку Random job и вам рандомно присваивается профессия в этом раунде.

**Comment by Skippeer12** [comment]
Заходите за капитана и руините игру~~ ивент~~.

**Comment by Shudyn** [comment]
Берешь таяру, жмешь random job, получаешь капитана и вылетаешь с Есхода без хвоста.
