### ISSUE TITLE
[Proposal] Job request.

### ISSUE THREAD

**Issue by Djekke** [TauCetiStation/TauCetiClassic#1618]
#### Подробное описание проблемы
Добавить возможность педально выставлять запросы на профы

#### Что должно было произойти
Заходит человек в середине раунда, и видит:
Требуются инженеры\медики\сб...
#### Что произошло на самом деле
Количество занятых слотов в профе зачастую не отражает реальной ситуации на станции.

**Comment by Avatar4** [comment]
А все потому что медики не выставляют статусы "Дайз" "ССД" и тд. Хотя при сне оно должно работать автоматически.
Заодно предложу сделать так, что бы при включенных датчиках в случае твоей смерти - писалось в крю что ты мертв.

**Comment by Udokun** [comment]
Давным-давно была речь о том, чтобы дать такую возможность Главе Персонала. Мол, требуются инженеры, включаешь консоль и делаешь официальный запрос на ЦК, а тем, кто ещё не зашёл в раунд показывает, что станции требуется <s>ГЕРОЙ</s> *random job*.
