### ISSUE TITLE
Некорректная работа носилок с котами (и, может быть, иными хвостатыми)

### ISSUE THREAD

**Issue by AnimalRidens** [TauCetiStation/TauCetiClassic#1619]
#### Подробное описание проблемы
Не знаю, является ли это постоянным багом или проявилось под воздействием моих собственных лагов/лагов сервера (если они были) в конкретном раунде, однако считаю должным сообщить о возникшей у меня проблеме.
При игре за парамедика я, погрузив больного таяру на носилки, вознамерился было протащить его до хирургии, однако столкнулся с проблемой: по какой-то причине носилки с кошаком на них категорически отказывались тащиться за мной (использовал Pull). Просто носилки - да, просто кошак - также да, носилки с кошаком - нет. В итоге, медленно и неудобно, тащил его через Grab.
#### Что должно было произойти
После погружения персонажа-таяры на носилки и использования команды Pull на них, они должны были двигаться вслед за воздействующим на них персонажем - так же, как это делают носилки с погруженным на них персонажем-человеком.
#### Что произошло на самом деле
Носилки с погруженным на них таярой оставались недвижимы.
#### Как повторить
Найти больного таяру, погрузить его на носилки, pull-ить - наблюдать за результатом.
#### Дополнительная информация:
Как уже было сказано, не знаю, является ли данная проблема постоянной или частным случаем, и если она постоянна, то распространяется ли она только на котов или на всех хвостатых. В случае, если описанное мной событие имело единичный характер и попытки повторить приведут к нормальному, самому обычному исходу (носилки без проблем поедут за персонажем), прошу принять мои извинения за пустое беспокойство.

**Comment by Skippeer12** [comment]
Эта проблема из-за прожатой кнопки Crawl собственной разработки Тау Сети.

**Comment by igigin** [comment]
Вообще не проблема. Кравлокоты должны страдать.

**Comment by Skippeer12** [comment]
Так проблема не только в кравлокотах.
Каталка не работает со всеми видами ксеносов и людей перед тем как они прожали кравл.

**Comment by Udokun** [comment]
На каталках ещё какая-то тема появилась. Недавно пуллом тащил каталку, а человек разливался кровью так, будто я его лично пуллом тащил.

**Comment by volas** [comment]
добавить сброс кравла при букле к каталке будет скорее всгео достаточно
