### ISSUE TITLE
Обосравшиеся болты шлюзов шатла эвакуации

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1622]
#### Подробное описание проблемы
После отстыковки от станции на шатоле евакуации опускаются болты на всех шлюзах. 
#### Что должно было произойти
Внутри шаттла через шлюзы можно ходить.
#### Что произошло на самом деле
Шлюзы заблокированы опущенными болтами даже после прилета.
#### Как повторить
Вызвать шатол и пройти на борт.

**Comment by igigin** [comment]
#1620.
