### ISSUE TITLE
[Proposal] Вернуть волшебное зеркало

### ISSUE THREAD

**Issue by sovok4** [TauCetiStation/TauCetiClassic#1624]
#### Подробное описание проблемы
Хочешь зачесать себе волосы не налево, а направо. Зеркало не работает. От отчаяния идешь к генетику, получаешь смену внешности, халку и эпилепсию.
#### Что должно было произойти
Зеркало должно позволять менять прическу хотя бы в ограниченном режиме. Десять-пятнадцать стандартных причесок.
#### Что произошло на самом деле
Злые кодеры породили бритвоебов и понерфили зеркало.
#### Как повторить
Научиться кодить. Выпилить зеркало, потому что бритва веселее)))))))
#### Дополнительная информация:
А ещё бритву было бы хорошо использовать только в усиленном грабе.

**Comment by ZVee** [comment]
Так давно ведь предложение было и по моему кто-то даже вроде как побежал это реализовывать, и... Ввести парикмахера. А вот зеркало однозначно не стоит.

**Comment by Skippeer12** [comment]
Закрывайте, вещи парикмахера.
