### ISSUE TITLE
Про По Зал: сделать генетиков подпрофой врачей.

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1626]
Суть в названии. Генетики - подпрофа врача, к врачам плюс два слота, добавить врачам базовый доступ в клонилку.

**Comment by l0lone** [comment]
И уничтожить ещё одну профессию? Генетики стабильно почти в каждом раунде есть. Подобным образом объединять следует только те профессии, которые непопулярны или малополезны.

**Comment by CryptoKisik** [comment]
Нужно портировать генетику. Вот только откуда?

**Comment by WallShrabnic** [comment]
С бея. Там её нет
