### ISSUE TITLE
NERF PLZ: Вортекс аномалия.

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1627]
Она после после появления сразу делает дыры. Законтрить ее почти невозможно.
Пусть она только взрывается. И спустя минуты полторы-две. Но мощнее.

**Comment by igigin** [comment]
Нет.

**Comment by l0lone** [comment]
Так в этом и ее суть же.

**Comment by Forrya** [comment]
Тада ладна.
