### ISSUE TITLE
[Proposal] Стол в приёмной брига

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#1629]
#### Подробное описание проблемы
Чуть ли не каждый раунд всякие малогеи запрыгивают на стол в приёмной брига, нажимают на кнопку и тем самым забегают в бриг, мешая при этом работать СБ.
#### Что должно было произойти
При попытке запрыгнуть на стол им должна шептать совесть, что они не должны этого делать(как у ХоПа)

**Comment by Tolerantboy** [comment]
Как они нажимают кнопку, у них же не должно быть доступа

**Comment by Forrya** [comment]
Так и должно быть. Иначе зачем им вообще КПП и варден?
