### ISSUE TITLE
Ассистенты хакеры с помощью одного нажатия кнопки и карты хопа крадут весь наличный счет.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1634]
#### Подробное описание проблемы
Если зайти в банкомат и нажать на авторизацию без набора пароля или аккаунта - счет авторизуется. Нужно лишь иметь айди карту в слоте с одеждой. Однако, тоже самое можно сделать с чужим счетом если выкрасть чужую карту.
#### Что должно было произойти
Авторизации не должно происходить без ввода аккаунта и пароля.
#### Что произошло на самом деле
Джамесы Морганы крадут мильены с помощью аксуса капитана.
#### Как повторить
Авториизроваться с чужой картой в банкомате.

**Comment by Forrya** [comment]
Ого, аватарЧетыре узнал что можно грабить екипаж.

**Comment by Avatar4** [comment]
Я давно знал но забыл как-то про этот баг

**Comment by YulianR** [comment]
Не баг, просто по дефолту у всех аккаунтов первый уровень безопасности - то есть логиниться можно лишь картой. Уровень можно повысить залогинившись в банкомате.

**Comment by Lexakr** [comment]
Вроде уровни не спасают.. Или не спасали
