### ISSUE TITLE
Тексты, которые печатает игрок (IC, OOC, AHELP т.д т.п) "проглатываются" при отправлении.

### ISSUE THREAD

**Issue by MorJams** [TauCetiStation/TauCetiClassic#1635]
#### Подробное описание проблемы
Когда моб говорит с кем-то, общается в ООЦ, АХЕЛПЕ, АСЭЕ, дедчате и так далее, то при отправлении набранного текста он просто не видит свой же текст. В логах текст есть, облако ВРОДЕ даже появляется, но сам игрок (который набрал текст) не видит этот текст и неизвестно, видит ли этот текст другие.
#### Что должно было произойти
Сообщение должно было быть видимым для того, кто это сообщение написал. (и возможно для всех остальных)
#### Что произошло на самом деле
Ты видишь, что ничего не отправилось, и отправляешь тоже самое сообщение ещё раз, выглядя нелепо.
#### Как повторить
Случается рандомно при отправлении текста.

**Comment by Tolerantboy** [comment]
О, у меня такое было. Так что проблема как минимум не только у тебя

**Comment by RichardJones1** [comment]
После последней обновы чата от воласа мне еще ни разу не встречался этот баг. Возможно причиной также могло стать то, что я поменял IE с 10го на Edge
