### ISSUE TITLE
Нет разгермы от стелскостюма ворксов 

### ISSUE THREAD

**Issue by Vitospre** [TauCetiStation/TauCetiClassic#1637]
#### Подробное описание проблемы
Если активировать стлес костюм воксов и разобрать окно то разгермы не будет. 

#### Что должно было произойти
Разгерма 
#### Что произошло на самом деле
Не было разгермы 
#### Как повторить
Разобрать окно с включенным стелсом 
#### Дополнительная информация:
![screenshot_4](https://user-images.githubusercontent.com/29823420/27765279-1afda378-5eb6-11e7-94e3-06855608051a.png)

**Comment by Forrya** [comment]
Фу разгермоп... А...

**Comment by igigin** [comment]
Разобрал ксенобиологию - всё как описали. Разобрал ближайший техтоннель - разгерма.

**Comment by Avatar4** [comment]
У меня кстати была похожая проблема.
Во время воксов, я был боргом и восстановил окно в стрельбище а потом герметизировал, но забыл закрыть закачку воздуха из вентов и там стало больше воздуха чем нужно. После этого - стабилизировал но пришел офицер и потребовал разобрать окно еще раз что бы он мог вылезти быстро в космос. Однако разгермы не произошло и я спокойно вставил окно обратно.
Возможно, эти баги как-то связаны с воксами.
