### ISSUE TITLE
Бумажки не летают больше чем на один тайтл.

### ISSUE THREAD

**Issue by DctrMM** [TauCetiStation/TauCetiClassic#1638]
#### Подробное описание проблемы
Бумажки не летают больше чем на один тайтл.
#### Что должно было произойти
Они должны долетать до конца экрана/на то место куда ткнули
#### Что произошло на самом деле
Летит один тайтл в сторону конца экрана/того места куда ткнули
#### Как повторить
Кинуть бумажку

**Comment by JamsMor** [comment]
Так это же всегда было и это было фичей, разве нет? Мол бумажка БУМАЖНАЯ и воздух ей трудно преодолевать.
