### ISSUE TITLE
Кобура и ЭМИ

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#1640]
#### Подробное описание проблемы
ЭМИ не разряжает оружие в кобуре
#### Что должно было произойти
ЭМИ должен разряжать все энергетические орудия
#### Что произошло на самом деле
НТ закупает кобуру на основе серебра, поэтому оружие в целости и сохранности
#### Как повторить
Получите выстрел из ионного оружия в табло, потом накажите скам летальным оружием из кобуры

**Comment by Belfogor** [comment]
Ну-с. Там проблема не только в кобуре. Насколько я помню с портфелями такая же история.

**Comment by Udokun** [comment]
Всё энергетическое оружие, которое было у меня в сумке, разрядилось.

**Comment by Tolerantboy** [comment]
Можно представить, что это экранированная кобура, как раз на такой случай
