### ISSUE TITLE
Фармбот и его сломанный интерфейс

### ISSUE THREAD

**Issue by Lexakr** [TauCetiStation/TauCetiClassic#1641]
#### Подробное описание проблемы
У фармбота не открывается интерфейс
#### Как повторить
Создать/заспавнить фармбота
#### Дополнительная информация:
Анлок картой или отверткой не решает проблем, сам бот работает и в него грузятся удобрения

**Comment by Skippeer12** [comment]
Заспавнил фармбота, открыл итрефейс.
![image](https://user-images.githubusercontent.com/18488106/35797135-6d7b3cac-0a67-11e8-85c2-4346dea04102.png)
