### ISSUE TITLE
[Proposal] Рандомизировать спавн серебрянных монеток и прочего в техах

### ISSUE THREAD

**Issue by Lexakr** [TauCetiStation/TauCetiClassic#1645]
#### Подробное описание проблемы
В наших реалиях практически любой раунд начинается с лутания дефолтных нычек с монетками, перчатками и другим интересным шмотом. Почему бы не впилить всему этому добру рандомный спавн, чтобы ассистоте приходилось немного напрягать жопки и искать заветные сокровища?

**Comment by Forrya** [comment]
нет

**Comment by Forrya** [comment]
Ну сделайте тогда спавн изоляционок в техах на всех ассистентов.

**Comment by Lexakr** [comment]
За любого ассистента со старта раунда доступно 3 пары перчаток, 1 из них требует взлома. Всегда есть вариант карго и спавна прчаток в желтых тулбоксах, кстати, этот шанс тож можно поднять
