### ISSUE TITLE
Ошибка спрайта глисты-дионы держащей щит

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1648]
Как то так, там просто прорезь для руки через которую виден пол.

![image](https://user-images.githubusercontent.com/26758765/27870189-e92e659c-61aa-11e7-8d4f-718d2fc0bc7b.png)

**Comment by Tolerantboy** [comment]
Просто используются спрайты человека и там по задумке должна быть держащая щит рука

**Comment by Forrya** [comment]
Просто диона не должна щит держать.
