### ISSUE TITLE
Система вентиляции и мобы в ней.

### ISSUE THREAD

**Issue by psebash** [TauCetiStation/TauCetiClassic#1649]
#### Подробное описание проблемы
Сейчас многие мобы могут пролезть в эту гребаную четырехсантиметровую трубу подачи воздуха, несмотря на их размеры от 30 см.
#### Что должно было произойти
Алиены, мартышки и маленькие люди не должны лазить по вентиляции.
#### Что произошло на самом деле
Альтклик работает на алиенах и мартышках.
#### Как повторить
Зайти за алиена и залезть в вентиляцию
#### Дополнительная информация:
Думаю что оставить можно было бы лявр, нимф и бореров всяких. К скрабберам то же самое относится

**Comment by Skippeer12** [comment]
Спрайто-условности.
Ты думаешь что вентиляционная труба 30см но на самом деле она может достигать метра в диаметра или даже больше.

http://vseotrubax.com/wp-content/uploads/2014/12/%D0%93%D0%BE%D1%84%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%B0%D1%8F-%D0%B2%D0%B5%D0%BD%D1%82%D0%B8%D0%BB%D1%8F%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F-%D1%82%D1%80%D1%83%D0%B1%D0%B0.jpg?x75256

**Comment by Tolerantboy** [comment]
Согласен со Шкиппером, я вот например представляю вентиляционную трубу станции как что-то шириной 50 на 50 сантиметров, куда при желании пролезет ребенок или взрослый тощий человек, если смажется мылом - ведь по станции надо гонять большие объемы воздуха. Правда, если посмотреть на карте или когда труба просвечивается сквозь пол когда ты по ней ползешь или когда ты ее просвечиваешь инженерным Т-сканнером, она действительно выглядит очень узкой и годится только для бюреров, лярв, нимф, слизней и слизней ченджей

**Comment by volas** [comment]
#фича
