### ISSUE TITLE
Рука без кисти не поддается хирургическим манипуляциям. 

### ISSUE THREAD

**Issue by Kilkalestia** [TauCetiStation/TauCetiClassic#1650]
#### Подробное описание проблемы
Если у руки отсутствует кисть или же она заменена на протез, то руку нельзя будет прооперировать. 
#### Что должно было произойти
Рука должна все так же оперироваться с помощью хирургических инструментов независимо от наличия у неё кисти. 
#### Что произошло на самом деле
Человек остался с поломанной костью в руке, ибо новый механ не позволил хирургу провести операцию.
#### Как повторить
Попробовать провести операцию на огрызке руки без кисти.
#### Дополнительная информация:
Скорее всего этот баг относится и к ногам, но никто пока не проверил.

**Comment by Forrya** [comment]
Не пробовала сначала кибернетизировать кисть руки, которую оторвало, а потом руку чинить?

**Comment by wadangel** [comment]
Руку/ногу можно отрезать целиком кликом пилой в хелпе, если перед этим подготовить кисть/ступню к протезированию (скальпель-зажим-расширитель).

**Comment by Kilkalestia** [comment]
Форь, ты чем читаешь-то? 

> Если у руки отсутствует кисть или же она заменена на протез

**Comment by Forrya** [comment]
Ты писал в смысле "заменена после того как ее отрубило"?

**Comment by Kilkalestia** [comment]
Именно

**Comment by skvazarb** [comment]
Не воспроизводится по описанию.
