### ISSUE TITLE
Неисправимое артериальное кровотечение в оторванных конечностях.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#1651]
#### Что должно было произойти
Его не должно быть вообще.
#### Что произошло на самом деле
Возникло неисправимое (по причине отсутствия конечности) артериальное кровотечение.
#### Как повторить
Отрубить кукле руку/ногу и посмотреть на анализатор здоровья. Будет кровь уходить, будет про артериальное писать. А сканер не показывает, т.к. нету конечности.
#### Дополнительная информация:
Точно работает и на руках, и на ногах. Голову не проверял.

**Comment by Raschert0** [comment]
Судя по всему, таки исправлено. Повторить не удалось

**Comment by Raschert0** [comment]
Окей, баг всё ещё актуален. Способ повторения:
- взять  куклу с целой рукой (должна быть и рука и кисть)
- отрезать эту руку (не кисть), например, есвордом
- наблюдать артериальное кровотечение в отрезанной руке
