### ISSUE TITLE
У пистолетов охраны неправильно работают обоймы с летальными патронами.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#1653]
#### Подробное описание проблемы
В пистолет с полной обоймой можно запихнуть другой обойму, прошлая же просто пропадёт.
#### Что должно было произойти
Не должно быть возможности запихнуть обойму, т.к. там уже одна есть.
#### Что произошло на самом деле
Новая обойма вошла, прошлая исчезла.
#### Как повторить
Засунуть в пистолет охраны обойму летальных, потом засунуть либо летальную, либо резину - прошлая обойма просто пропадёт.

**Comment by Belfogor** [comment]
Вы ничего не смыслите в технологиях будущего.
