### ISSUE TITLE
Артериальное кровотичение не убивает людей.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1654]
#### Подробное описание проблемы
В ночном раунде я пришел химиком и понял что ниндзя знатно продырявил всем артерии. В мед бее было 4 пациента у которых в честе было артериальное кровотечение. Но ни один из них не умер так как отметка крови не падала ниже 45-50%.
#### Что должно было произойти
Артериальное кровотечение должно высасывать кровь пока цель не умрет.
#### Как повторить
Покопаться ниндзей в кишочках хумана, перебинтовать и посмотреть на него.
#### Дополнительная информация:
Возможно что передоз инупровалином и бикардином так же перестал работать и не останавливает теперь кровотечение.

**Comment by Tolerantboy** [comment]
Ну, так тыж перебинтовал.

**Comment by Motzord** [comment]
Артериалка убивает. Закрывайте.

**Comment by Motzord** [comment]
Актуально, при отрыве конечности артериалка начинает убавлять совершенно мизерное количество крови уже начиная с 70% и кукла может еще примерно полчаса кайфовать с артерией в груди

**Comment by Motzord** [comment]
Их смешного. Начиная с отметки в 45 процентов, кровь не только перестает утекать но даже регенерирует
![image](https://user-images.githubusercontent.com/45365635/101982715-8764ad00-3c7e-11eb-94ff-006407dcbc2c.png)
