### ISSUE TITLE
Отрезание головы не заставляет душу игрока покинуть голову.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1655]
#### Подробное описание проблемы
При отрезании головы игроку, у него дух переходит в голову. Тем самым, ему остается только гостаться и пришитие головы уже не поможет (наверное).
#### Что должно было произойти
При отрезании головы, игрок должен автоматически гостаться.

**Comment by Tolerantboy** [comment]
1. Не баг, а фича
2. Пришитие головы поможет, при чем брать можно любое тело, не обязательно хозяина.
