### ISSUE TITLE
Некорректный урон от лазерного оружия по конечностям.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#1656]
#### Подробное описание проблемы
Урон от выстрела из лазерного оружия доходит до уровня в 50 ед. бёрна, после чего при последующих выстрелах урон не наносится, только кровь "сжигается". Если долго стрелять, то рано или поздно эта конечность сгорит, но не из-за прохождения порога урона, а из-за критического выстрела (не знаю, как это назвать, но это когда с одного (первого) выстрела конечность сжигает).
#### Что должно было произойти
Попадание в конечность с уроном выше 50 должно её сжигать.
#### Что произошло на самом деле
Урон доходит до 50 бёрна, а потом сжигается только кровь, урона не наносится вообще.
#### Как повторить
Пострелять с любого лазерного оружия по конечности куклы.

**Comment by WallShrabnic** [comment]
При очень больших значениях (при ударе от теслы например) сжигается ВСЯ кровь, но пациент остаётся живым

**Comment by ZVee** [comment]
Так и должно быть - ограничение снято только с головы торса и паха (это то кстати, как и на бее, потому что в общем-то бее механ и есть). Как бы нанеся сколько то урона - представь что там уже фарш, игрок ничего не чувствует и не получает урона, дабы ударяя в "фарш" нельзя было таким образом убить ударов за 20. Хочешь вывести игрока, а не мучить - бей в выше перечисленные 3 части тела.
