### ISSUE TITLE
[Proposal] Выпилить дедстинг.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1657]
Слишком имба. Я не понимаю почему его все еще не убрали. Можно юзать параллельно метая хлыстом всех вокруг. Нет никакого видимого баланса. Если и умудряешься увернуться от имбового хлыста и забить до смерти генку, то все равно вместо него приходит имбовый дедстинг.

**Comment by Forrya** [comment]
Начнем с того, что он стоит много, а закончим тем, что он требует много и легко контрится.

**Comment by Avatar4** [comment]
И закончим тем что он нафиг не нужен а его дороговизна не чувствуется.

**Comment by Forrya** [comment]
Ну так незачем на генку лезть, что за нытье?

**Comment by Avatar4** [comment]
Нытье в том, что это все еще имба, было имбой и будет имбой сколько бы ему цены не давали. С этой хуйней, можно поубивать пол станции не заморачиваясь в техах. Она даже не высвечивается и нормальный персонал не поймет как это контрить.

**Comment by WallShrabnic** [comment]
Я за выпил, но по другим причинам. Дезстинг не вписывается в текущий баланс, ситуаций где он бы был необходим нет. Кроме того, он постоянно провоцирует на метагейство, ибо палится неимоверно, плюс при наличии годного СМО/врача легко вылечить, при отсутствии оных очень тяжело что-либо сделать. Либо ребалансните уже, либо удаляйте

**Comment by DeadOberst** [comment]
Ну вы же из слиперов колбы вынули, вот и имба!

**Comment by P-20** [comment]
@DeadOberst что за мода писать в давно закрытых темах.

**Comment by volas** [comment]
@P-20 что за мода писать в давно закрытых темах.
