### ISSUE TITLE
Киборги стейшона могут манипулировать шаттлом нюкеров

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1658]
#### Подробное описание проблемы
Киборги могут войти спокойно в шаттл нюкеров, в то время как на шаттл воксов уже без доступа не войдешь.
#### Что должно было произойти
Нельзя без специального доступа войти на шаттл нюкеров

**Comment by Forrya** [comment]
Как бы у нюкеров есть возможность опустить бластдоры на мостике и шлюзе шаттла.
Я говорил множество раз - если нюкеры тупые и не умеют обезопасить свой шаттл - их проблемы.
К слову, шлюз без бластдора может любой открыть.

**Comment by Skippeer12** [comment]
Куршан сломал доступ на дверях шлюзов-шаттла нюкеров. Но только шлюзы.

**Comment by Misakiwa** [comment]
У ерт и боргов, тоесть.
