### ISSUE TITLE
Невозможно отрезать голову хирургической пилой в хелпе.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#1660]
#### Подробное описание проблемы
Если кликнуть пилой в хелпе по лежащей на каталке/хирургическом_столе кукле, будет происходить удар, а не отрезание головы. 
#### Что должно было произойти
Голова должна отрезаться.
#### Что произошло на самом деле
По голове бьют пилой.
#### Как повторить
Положить куклу на стол/каталку и попробовать отрезать ей голову в хелпе.
#### Дополнительная информация:
Если уж прямо нужно отрезать голову, то делайте это через тройной граб и перерезание горла скальпелем.

**Comment by Raschert0** [comment]
Хм, я не так давно делал операцию, если не ошибаюсь, по остановке кровотечения, но при этом прицелился в рот. В результате отрезал пациенту голову. Не уверен, была ли там пила, но скорее да, чем нет

**Comment by wadangel** [comment]
@RichardJones1 актуально.

**Comment by LudwigVonChesterfield** [comment]
Прицеливаться на рот жы.

**Comment by FelixRuin** [comment]
![image](https://user-images.githubusercontent.com/31424899/55669614-3504a380-5882-11e9-829e-3e350c6b8c63.png)
всё работает, надо целиться в голову

**Comment by Motzord** [comment]
Все работает, закрывайте
