### ISSUE TITLE
Можно реанимировать людей без головы.

### ISSUE THREAD

**Issue by skvazarb** [TauCetiStation/TauCetiClassic#1664]
#### Подробное описание проблемы
Если мобу превратить голову в пепел лазерным оружием, то его возможно реанимировать и получить живого моба без головы.
#### Что должно было произойти
Никакой реанимации без головы.
#### Что произошло на самом деле
Живые мобы без головы
#### Как повторить

1. Превратить в пепел голову мобу (например, использовался lasercannon)
2. Реанимировать дефибами

#### Дополнительная информация:

**Comment by Avatar4** [comment]
Вместо головы можно мозг один оставить

**Comment by MrFoxik** [comment]
Не баг а фича. Это как курица без головы.

**Comment by volas** [comment]
@Raschert0 ты кстати не смотрел с дефибрилляторами это?

**Comment by Raschert0** [comment]
А, да, должно быть зафикшено

**Comment by Raschert0** [comment]
#1721
