### ISSUE TITLE
Киборг-злодей открывашка дверей

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1665]
1. Сажаешь борга на инвалидную коляску, перед этим лишив его возможности слезть с нее, например вынув батарею.
2. Катишь его перед собой.
3. Все шлюзы открываются перед ним.
4. ???????
5. PROFIT!

**Comment by Skippeer12** [comment]
Ne bug, a feature

**Comment by WallShrabnic** [comment]
Скорее склоняюсь к тому, что это фича
