### ISSUE TITLE
[Proposal] Одноразовые блюпринты.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1667]
В общем, предлагаю ввести такие себе картонки в виде блюпринтов, которые можно будет активировать лишь в новых зонах после чего они пропадают. Около 5 штук в вендоматы в инженерке и в автолат. Постоянно ебашить шкафчик СЕ когда его нет уже немного надоело и каждый раз грозятся тебя побить батоном.

**Comment by Shudyn** [comment]
Модифицировать стейшн и добавлять отсеки же не должен каждый мимоассистент.

**Comment by Avatar4** [comment]
Ну я же говорю про то что бы добавить инженерам в вендомат хотя бы. Потому что пиздить блюпринт тоже не является нормой.

**Comment by WallShrabnic** [comment]
Строительство дополнительных отсеков тоже не норма

**Comment by igigin** [comment]
Внезапно, но блупринты не просто так лежат у СЕ в шкафчике. И ещё внезапней, что шрубник прав.
