### ISSUE TITLE
Фейсхаггеры алиенов пробивают все и вся.

### ISSUE THREAD

**Issue by Ajajumbo123** [TauCetiStation/TauCetiClassic#1668]
#### Подробное описание проблемы
Фейсхагеры алиенов игнорируют риги, скафандры и прочую полностью герметичную одежду, которую они игнорировать не должны. 
#### Что должно было произойти
Фейсхагер должен был прыгнуть и ебнуться об шлемак.
#### Что произошло на самом деле
Фейсхагер не обращает внимания на на многослойную оболочку ригов, а просто телепортируется на лицо, так быть не должно.
#### Как повторить
Надеть риг, найти фейсхагера и дать ему запрыгнуть на себя .

**Comment by Forrya** [comment]
В фильме он если что через шлем заражал.

**Comment by Ajajumbo123** [comment]
Дело не в том, как было в фильме, а в том, что эти штуки собираются в миллионные стаи, а потом из инвиза за два клика кладут абсолютно все и через любую защиту, что ни разу не баланс, над которым тут так усиленно работают. 
Может быть обычный СкАфАнДрЫ КоСмИчЕсКиЕ и не стоит апать против этого, но риги точно надо хотя бы потому, что эти самые риги не каждому доступны.

**Comment by Forrya** [comment]
Количество хагеров ограничено. Подумай над этим.

**Comment by WallShrabnic** [comment]
Если квина не тупая, то не ограничено. Но они прыгают о-о-очень долго, и от них можно легко увернуться если ты не в РИГе или замедлен

**Comment by SpaiR** [comment]
Как сказал Зве, алиены на классике специально не полностью каноничны. В отличии, например, от алиенов на ксеностации.
