### ISSUE TITLE
После того, как из тушки космонавта вылезает алиен, этого самого космонавта нельзя клонировать

### ISSUE THREAD

**Issue by Ajajumbo123** [TauCetiStation/TauCetiClassic#1669]
#### Подробное описание проблемы
Если из тебя вылезли алиенс, то тебя нельзя клонировать, пишет ментал фаилуре, а в тушу вернуться нельзя: пишет ю хев ноу бади. 
#### Что должно было произойти
Туша засовывается в клонилку и клонируется.
#### Что произошло на самом деле
Туша не клонируется, а выдает ментал фаилуре.
#### Как повторить
Попробовать клонировать мертвого космонавта, из которого вылез алиюн.

**Comment by P-20** [comment]
А если реанимировать, после прижигания вспоротой груди, и бинтования, все в порядке, да только 
He is totally catatonic. The stresses of life in deep-space must have been too much for him. Any recovery is unlikely

**Comment by Avatar4** [comment]
А еще есть подозрения, что хумана которого заразили а потом достали лицехвата - нельзя снова заразить.

**Comment by RichardJones1** [comment]
Алиенобаг, который, возможно, имеет место быть

**Comment by WallShrabnic** [comment]
Космонавтика выбрасывает из тела. По идее, так и должно быть, но... Meh
