### ISSUE TITLE
[BUG] Слепые зоны ИИ

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#1671]
#### Подробное описание проблемы
![yvakt-5tsgo6zzc2mh11jq](https://user-images.githubusercontent.com/24526545/28225759-69757fbe-68dc-11e7-9bc9-5ccbfd21df15.png)
![ihn588pbqgmtzm9tbi1o9q](https://user-images.githubusercontent.com/24526545/28225879-c9ad2f76-68dc-11e7-901d-980ebce403dd.png)
![oakygdjwsqosjm5u2llbow](https://user-images.githubusercontent.com/24526545/28225882-c9b32502-68dc-11e7-8513-322055adfa69.png)
![s75nv6e4s-yfb3b-wt8kjg](https://user-images.githubusercontent.com/24526545/28225881-c9b0d63a-68dc-11e7-970f-661b5454a3c0.png)
![sv89lwgmsf2hxwkextopyw](https://user-images.githubusercontent.com/24526545/28225883-c9b40e54-68dc-11e7-9de7-d2ad68fe0da8.png)
![2mjjfl09stcymwjcbuom5g](https://user-images.githubusercontent.com/24526545/28225878-c9ac2f90-68dc-11e7-962b-f7a9f97d3c00.png)
![kjf3ern4tjwfnqo8iug5kw](https://user-images.githubusercontent.com/24526545/28225880-c9ae83ee-68dc-11e7-9f57-73a2d8bb97d1.png)
![nm2swjaesjmilbv3e-agqg](https://user-images.githubusercontent.com/24526545/28225884-c9c9c7ee-68dc-11e7-8335-92974ee03d2d.png)
![8avadastsrmot5aulezgha](https://user-images.githubusercontent.com/24526545/28225885-c9caf902-68dc-11e7-8596-edb0c788ad2e.png)
![qrjbe-ddtjsrtanqoyti3q](https://user-images.githubusercontent.com/24526545/28225887-c9cd1b4c-68dc-11e7-9500-e9ea71d1925f.png)
![vjxc97gct3sejc4wblq54w](https://user-images.githubusercontent.com/24526545/28225888-c9cd8f3c-68dc-11e7-9ad3-ec293436995c.png)
#### Что должно было произойти
ИИ должен видеть эти зоны
#### Что произошло на самом деле
Многие космонавтики наглым образом используют эту слабость
#### Как повторить
Зайдите за ИИ и посмотрите
#### Дополнительная информация:
На последнем скриншоте видно ещё одну проблему, оверлеи видны в слепой зоне, таким образом можно видеть, куда бежит ролька в тех. тоннеле(Грех)

**Comment by Udokun** [comment]
А ещё за ИИ часто вылетает. Я уже четвертый раз перезахожу.

**Comment by P-20** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/1425

**Comment by JamsMor** [comment]
ИМХО, не все слепые зоны на скриншотах это плохо. ИРЛ имеется та же проблема, тащемта.

**Comment by Skippeer12** [comment]
#1052

**Comment by WallShrabnic** [comment]
Чёт проиграл со слепых зон в ТУАЛЕТЕ и ДУШЕВОЙ, где камеры в принципе не должны стоять

**Comment by Udokun** [comment]
Туалет добавлен не потому что ИИ не видит унитазы, а потому что там целого коридора не видно.

**Comment by Raneman** [comment]
Это ужасно.
Ощущается острый недостаток тоталитарного ока, особенно в камере сжигания

**Comment by Udokun** [comment]
Всевидящее Око Саурона негодует.
![all_seeing_eye 1](https://user-images.githubusercontent.com/24526545/28259957-84d42768-6ae1-11e7-948f-57623df6d5df.jpg)
