### ISSUE TITLE
Зум от шахтерской блю спейс сумки для руды.

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1673]
Если наполнить блюспейс шахтерскую сумку рудой полностью и открыть посмотреть что в ней, то появляется зум.

**Comment by FelixRuin** [comment]
![image](https://user-images.githubusercontent.com/31424899/52522444-a0713100-2c96-11e9-8e6b-47c5f3c04f8f.png)
более не работает, закрыть бы

**Comment by RichardJones1** [comment]
Нет, нужно попросить Алексофп дать этой сумке старый инвентарь, я считаю

**Comment by FelixRuin** [comment]
не надо, это именно и создавало баг

**Comment by Motzord** [comment]
Закрывайте
