### ISSUE TITLE
Пулл не прерывается если толкнуть моба.

### ISSUE THREAD

**Issue by skvazarb** [TauCetiStation/TauCetiClassic#1677]
#### Подробное описание проблемы
Можно толкать моба, который тебя пуллит и двигается. Это позволяет двигаться сильно быстрее чем положено.
#### Что должно было произойти
Пулл должен прерываться если толкнуть пуллящего.
#### Что произошло на самом деле
Пулл не прерывается.
#### Как повторить
Моб 1 берет моба 2 пуллом и начинает идти в некотором направлении. Моб 2 двигается в том же направлении. При этом у кого-то интент не на хелпе. В результате оба двигаются выше своей максимальной скорости.
#### Дополнительная информация:
Огромная проблема, злодеи абузят.

**Comment by Kurshan** [comment]
Удваиваю по огромную проблему. Коты-переростки так вообще до скорости нинжи доходят.

**Comment by Forrya** [comment]
Не палите фичи пожалуйста.
