### ISSUE TITLE
Прыжки алиумов выводят из строя боргов

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1682]
#### Подробное описание проблемы
Прыжки хантеров и других алиумов кнокают боргов как если бы это было эми.
#### Что должно было произойти
Борги не должны кнокаться от прыжков алиумов
#### Что произошло на самом деле
Алиум неведомым способом своим прыжком закоротил борга.
#### Дополнительная информация:
Может вы скажете что все так и должно быть, но я не вижу логики в том что бы борг отрубался на несколько секунд от удара алиума. Скорее, он бы въебался об него как в стену по мне.

**Comment by WallShrabnic** [comment]
Скорее, это сделано для баланса, иначе алиены ничего противопоставить синтетикам не смогут. Представь, что они в прыжке валят боргов на пол

**Comment by Avatar4** [comment]
Так а о каком балансе идет речь когда тебя станят на 20 секунд и успевают нанести 20 ударов после которых уже можно гостаться? Алиумы так-то быстрее и проворнее, а у боргов нет ничего кроме болонов и батонов.

**Comment by Forrya** [comment]
Баллистический шок выводит боргов на время из строя.
