### ISSUE TITLE
Ошибка маперов.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1685]
#### Подробное описание проблемы
В карго в скраберах есть одна по дефолту сломанная труба.
#### Что должно было произойти
Сломанной трубы быть не должно.
#### Что произошло на самом деле
Труба сломана.
#### Как повторить
Зайти в игру и откопать трубу как на скриншоте.
#### Дополнительная информация:
На первом скрине то что в игре а на втором как труба идет на устаревшей карте.
http://imgur.com/a/RneSW

**Comment by Udokun** [comment]
А ещё вчера определили при перестройке столовой, что там стоят две пожарные тревоги.

**Comment by Zmey25** [comment]
А еще, в инженерке висит плакат PODS, хотя этих подов там нет уже очень давно.
