### ISSUE TITLE
[Proposal] Автоперезарядка протокинетического акселератора

### ISSUE THREAD

**Issue by kopoba** [TauCetiStation/TauCetiClassic#1686]
Хочештся чтобы он сам перезаряжался. Иначе это какаято боль с закликиванием и елозеньем мышки.

**Comment by Forrya** [comment]
Слишком казуально.

**Comment by kopoba** [comment]
Делаем шахтерам больно а потом удивляемся почему никто не заходит за них. Никакой казуальщины не вижу так то. Копать всеравно придеться также.

**Comment by Zmey25** [comment]
Хоткеи абузь и не насилуй мышку.

**Comment by kopoba** [comment]
Я однорукий боец

**Comment by Skippeer12** [comment]
Абуз хоткеев приводит к заболеванию механом. Вам же дали большой бур! Им и копайте. Просто стоишь и смотришь иногда выгружаешь из его руду.

**Comment by WallShrabnic** [comment]
~~Иногда застреваешь в нём~~

Можно портировать улучшенные вещи шахтёрские с ТОГЕ, но кто будет это кодить?
