### ISSUE TITLE
Гроб вращается при космировании - не комильфо.

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#1688]
#### Подробное описание проблемы
Когда космируешь гроб, его выбрасывает вращением.
#### Что должно было произойти
Как большой объект, он должен вылетать без вращений, ровно.
#### Что произошло на самом деле
Если бы труп в гробу был живой, он бы заблевал весь гроб.
#### Как повторить
Космируйте неверного.

**Comment by WallShrabnic** [comment]
Это особенность текущих контроллеров с ТГ
