### ISSUE TITLE
Очки для сварки не поднимаются, если ты сидишь

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#1690]
#### Подробное описание проблемы
Очки для сварки не поднялись, когда я нажимал на иконку, брал их в руки и кликал на них в руках, даже горячие клавиши применял.
#### Что должно было произойти
Они должны подниматься и опускаться.
#### Что произошло на самом деле
Никакой реакции на клики.
#### Как повторить
Наденьте очки для сварки, сядьте в кресло и пробуйте их поднять.
#### Дополнительная информация:
Возможно такая ерунда со всеми объектами, которые можно активировать.

**Comment by Forrya** [comment]
А еще кароче если ты сидишь на стуле и пытается поднять предмет: ПКМ>пик ап, то ничего не выйдет.

**Comment by FelixRuin** [comment]
всё работает, можно закрывать, пофиксили

**Comment by LudwigVonChesterfield** [comment]
#5167
