### ISSUE TITLE
ИИ не оставляет отпечатков на шлюзах при использовании хоткеев.

### ISSUE THREAD

**Issue by skvazarb** [TauCetiStation/TauCetiClassic#1691]
#### Подробное описание проблемы
Если ИИ взаимодействует с шлюзами через хоткеи (shift+лкм и т.д.), то fingerprintshidden на шлюзе не обновляется.
#### Что должно было произойти
ИИ должны оставлять отпечатки.
#### Что произошло на самом деле
Они не оставляют.
#### Как повторить
За ИИ взаимодействовать с шлюзом через хоткеи и проверить VV.
#### Дополнительная информация:
С остальными синтетами всё в порядке. А ИИ может совершать идеальные преступления без улик для администрации.

**Comment by WallShrabnic** [comment]
Хм, а это ведь способ испоганить логи :thinking:
