### ISSUE TITLE
Спавн артефактов на научном астероидном посту.

### ISSUE THREAD

**Issue by Leshiy-ART** [TauCetiStation/TauCetiClassic#1692]
#### Подробное описание проблемы
Каждый новый раунд, на научном посту астероида происходит спавн артефактов, при этом часто происходит так что артефакт самопроизвольно активируется, вызывая при этом тревоги, ЭМИ-импульсы и прочее. Помимо того что лишние тревоги в начале раунда сбивают с толку, артефакты имеют свойство при длительном воздействии перегружать сервер.
Например сегодняшний утренний раунд, где артефакт излучал форон, в конечном итоге загрузил атмос и на сервере начались фризы. Удаление артефакта и очистка зоны - исправила ситуацию.

#### Что должно было произойти
Спавн артефактов можно оставить, только необходимо запретить им самопроизвольно активироваться. Ибо лишние тревоги нервируют инженерный состав и сбивают с толку, а побочный эффект создает фризы.
#### Дополнительная информация:
Если есть другие варианты решения проблемы - пишите, рассмотрим.

**Comment by Zmey25** [comment]
Можно их в космос поместить на ленту, чтобы достать легко было, когда понадобятся. Но все равно есть шанс, что у него триггер активации это пониженная температура. 
А без них скучно будет тому одному чуваку, что играет за археолога, учитывая, что у нас раундов больше полутора часа не бывает. Пока найдешь новый - команда специально обученных кукинов уже робастает кнопку крю трансфера.

**Comment by WallShrabnic** [comment]
Чёт вспомнил рандомно телепортящий артефакт

**Comment by Skippeer12** [comment]
Там есть комната хранения артефактов, там специальная атмосфера и все остальные триггеры соблюдены чтобы он не работал их можно туда поместить.

**Comment by ZVee** [comment]
Артефакты можете со спокойной душой выпилить с карты. Вернуть их стоит (на карту) только тогда, когда будет переписан и оптимизирован код их эффектов. Поэтому даже не обсуждайте тут иные варианты, без рефактора эффектов в этом нет смысла.

**Comment by WallShrabnic** [comment]
Мммммм, куда проще окончательно выпилить археолога

**Comment by volas** [comment]
#1729
