### ISSUE TITLE
Нельзя поднять диск от нюки, который заспавнился после зажаривания предыдущего

### ISSUE THREAD

**Issue by Raschert0** [TauCetiStation/TauCetiClassic#1693]
#### Подробное описание проблемы
Если зажарить во фритюре диск от нюки, то его новосозданную копию нельзя будет поднять

#### Что должно было произойти
Новый диск должен быть "поднимабельный"

#### Что произошло на самом деле
Диск нельзя было поднять

#### Как повторить
1. Жарим диск от нюки
2. Пытаемся поднять новый диск

#### Дополнительная информация:
Баг был зарепорчен FamousInvisible и мною не проверялся.

**Comment by Belfogor** [comment]
Я уверен, что после этого ишью, должность повара станет куда более популярной.

**Comment by WallShrabnic** [comment]
Сук фичи не пали

**Comment by Skippeer12** [comment]
Миллион фич как удалить диск, все работают и их никогда не найдут. Правда Шрубник?

**Comment by Raschert0** [comment]
Я думаю, предыдущие два комментария можно считать за подтверждение работоспособности бага :pekahiding:

**Comment by volas** [comment]
Сегодня возможно была та самая проблема, его потом даже не удалить.

```
[18:50:54] Runtime in garbage.dm, line 191: /obj/item/weapon/disk/nuclear destroy proc was called multiple times, likely due to a qdel loop in the Destroy logic
proc name: qdel (/proc/qdel)
usr: The syndimouse (volas) (/mob/dead/observer)
usr.loc: The floor (132,134,1) (/turf/simulated/floor)
```
