### ISSUE TITLE
При раздевании человека с любым итемом в руке это не идет в педальные логи(VV)!!!

### ISSUE THREAD

**Issue by Lexakr** [TauCetiStation/TauCetiClassic#1695]
#### Подробное описание проблемы
Если раздевать человека, держа в активной руке любую шмотку, этих логов не будет в педальных логах (ВВ)
#### Что должно было произойти
Должны быть логи раздевания
#### Дополнительная информация:
Адский баг, мешает разбираться во всяких нарушениях, есть ли эти логи в серверных не проверял ввиду недоступности

**Comment by LudwigVonChesterfield** [comment]
думаю не актуально с появлением полной демки раунда.
