### ISSUE TITLE
ИИ видит трупы теленгов сквозь зоны камер.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1699]
#### Подробное описание проблемы
ИИ может увидеть труп теленга где нет камеры. Возможно и живого может, но это не точно (я во всяком случае не видел).
#### Что должно было произойти
Он не должен видеть красные ГЛАЗИЩА.
#### Что произошло на самом деле
Он видит.
#### Дополнительная информация:
Теленг на скрине мертвый: http://imgur.com/a/PmaM4

**Comment by WallShrabnic** [comment]
Это неитолько к тенелингам относится, но и к некоторым другим вещам. Болтам на шлюзах, например

**Comment by RichardJones1** [comment]
Я пофиксил это в #2962
