### ISSUE TITLE
Книга Space Law является ингейм браузером вместо книги с законами.

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#17]
Originally reported by: **lancer411 (Bitbucket: [lancer411](http://bitbucket.org/lancer411), GitHub: [lancer411](http://github.com/lancer411))**

---

См выше.

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/17

**Comment by Misakiwa** [comment]
Так же работает и книга в столовой медбея

**Comment by RichardJones1** [comment]
Уже неактуально, теперь у нас мануалы со статьями на вики.
#2755
