### ISSUE TITLE
Сломался Спрайт

### ISSUE THREAD

**Issue by Vanya0** [TauCetiStation/TauCetiClassic#1704]
#### Подробное описание проблемы
Поломался Спрайт Бабы с федорой
#### Что должно было произойти
Федора должна была Снятся
#### Что произошло на самом деле
![screenshot_4](https://user-images.githubusercontent.com/30750478/28995465-55f80840-79f2-11e7-9ba3-8ff67369025a.jpg)

#### Как повторить
НАдеть Winter coat И тапочки те-Же самые Затем надеть федору И Надеть Колпак от Winter Coat'а
Снять федору И снять Капюшон. Вуаля У вас Баг с бесконечной Шляпой На голове
#### Дополнительная информация:
Баг произошел Случайно и Мне стало не по себе Спрашивал Адмов, НЕ помог даже РЕСПАВН перса.

**Comment by Smalltasty** [comment]
Не респавн, а раздевание, поправлю. Этого оверлея попросту нет в списке, потому убрать его я не смогла. Возможно, проблема с капюшоном этим, там наслойка идет. Регенерейт и дрополл не помогли.

**Comment by Vanya0** [comment]
Блен, Очень печально, Но на ЭТОТ раунд мне придётся ВСЕГДА ходить в Федоре

**Comment by CryptoKisik** [comment]
Хочу добавить, что подобный случай уже был. Не помню подробностей. Но я и другой офицер (не помню его) раздели заключенного. Так-то, все с него снято. Но на голове остался спрайт шлема пожарного.

**Comment by volas** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/171
