### ISSUE TITLE
Дюп камерабага из нюкерского пода

### ISSUE THREAD

**Issue by Raschert0** [TauCetiStation/TauCetiClassic#1709]
#### Подробное описание проблемы
Если раскручивать под отверткой то камерабаг вечно будет из него сыпаться, даже если его нету
#### Что должно было произойти
Камерабаг не должен был выпадать
#### Что произошло на самом деле
БОЛЬШЕ КАМЕРАБАГОВ БОГУ КАМЕРАБАГОВ!
#### Как повторить
1. Берём под нюки
2. Кликаем по нему отвёрткой
#### Дополнительная информация:
За багрепорт спасибо Мираклеру, за баг спасибо @Kurshan

**Comment by Kurshan** [comment]
Этот баг просто сплошная отсылка! камераБАГ, ну вы поняли, да? Ну смешно же!
![-qddl1yo2ke](https://user-images.githubusercontent.com/19510863/29036493-4fe3494e-7ba8-11e7-948c-83b7746d0b57.jpg)
