### ISSUE TITLE
Баг с головными уборами и зимней курткой.

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#171]
Originally reported by: **Skyrull (Bitbucket: [Skyrull](http://bitbucket.org/Skyrull), GitHub: Unknown)**

---

При надевании капюшона зимней куртки вместе с надетым головным убором (например, шлемом, кепкой, и т.д.) и после - снятии капюшона с надетым головным убором, текстура шлема остается на кукле и убрать ее нет возможности (даже если снять сам предмет).

Как получить?
1) Покупаем зимнюю куртку в Клозесмате.
2) Надеваем ее.
3) Надеваем сам шлем.
4) Надеваем капюшон куртки.
5) Снимаем капюшон.
6) Get.

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/171

**Comment by RichardJones1** [comment]
Нет
