### ISSUE TITLE
Спрайты робо-конечностей перепутаны

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1711]
#### Подробное описание проблемы
Правый протез выглядит как левый. Остальные наверное тоже самое.
#### Как повторить
Создать протез в робототехнике.

**Comment by Shudyn** [comment]
Ящеры перепутали схемы протезов в мехфабрикаторах.

**Comment by RichardJones1** [comment]
Я проверил, всё там в порядке...
