### ISSUE TITLE
Стрип гловсы (перчатки) отсавляюсь логи, если одевать предмет на человека. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#1716]
#### Подробное описание проблемы
Короче. Перчатки вора не оставляют для куклы-жертвы, уведомления о снятие вещей. Но если же в этих перчатках попробовать вещь одеть, то лог остается у куклы-жертвы. 

#### Дополнительная информация:
@Kurshan

**Comment by Forrya** [comment]
Суют тебе в руку взведенную гранату а ты такой этого не замечаешь))0)
