### ISSUE TITLE
Перебафаный бронежилет нюкера [нерфплиз]

### ISSUE THREAD

**Issue by sovok4** [TauCetiStation/TauCetiClassic#1717]
#### Подробное описание проблемы
Нюкерский бронежилет, который типа пехотный и некосмический, имеет следующие показатели защиты:

- melee = 50 
- bullet = 70 
- laser = 50 
- energy = 70 
- bomb = 50 
- bio = 0 
- rad = 50

Кроме того, он защищает от нулевого давления и, будучи броней, а не скафандром, не получает повреждений от ближних атак и выстрелов. Следовательно, нарушить защиту от давления у этого костюма невозможно. Приплюсуйте бронезащиту и получите имбу.

По логике, эта броня нужна, чтобы у нюкеров был вариант штурма без разгерм, однако учитывая вышеперечисленное, брать броню и устраивать разгерметизацию по всей станции гораздо выгоднее, ведь твой костюм не рвется, а защитники станции, если сразу не соснут от выстрелов, то помрут от рваных скафандров.

Как сказал производитель, эта броня является по сути респрайтом брони дедсквада, так вот нужен ли такой дедсквад каждую нюку?

#### Что должно было произойти
Девелоперы должны уметь в игровой баланс.
#### Что произошло на самом деле
Девелоперы не могут в игровой баланс.
#### Как повторить
Стать кодером, закодить имбу, дождаться мержа.
#### Дополнительная информация:
Решения предлагаю следующие:
1. Убрать/понерфить защиту от давления
2. Понерфить броню
3. Понерфить скорость передвижения, чтобы нюкер в броне был этиким джаггернаутом, неубиваемым, но жутко медленным.
4. Совместить вышеперечисленные три пункта и сделать легкий бронежилет без защиты от давления и тяжелый со всеми плюшками, но сильным замедлением.

**Comment by Vanya0** [comment]
У меня пригорело уже

**Comment by 241214234343** [comment]
5. не делать ничего и дать нюке побеждать хоть иногда

**Comment by YulianR** [comment]
>броня защищает от нулевого давления

это вообще пушка, я еще вживую не видел это, но чую, это дикий пиздец.

**Comment by WallShrabnic** [comment]
4

**Comment by Skippeer12** [comment]
Убираешь защиту от давления = станционные крысы-химики делают калевою бомбу 100х100 и кидаю её в гейтвей.
Итог все нюкеры трупы войдя на станцию. Отличный боланс, десять боланс~опидоров~ из десяти.

Дайте угадаю с чем служба безопасности идет воевать против нюкеров, с дробовиками, не так ли?

И только попробуй сказать что лазеры против них говнище, потому что те могут взять щиты.

К тому же нюкеров может быть максимум шесть, в то время как персонала с оружием можеть быть в два раза больше (считаю только охрану, ХоСа, капитана, Баттл-ХоПа, ~~АПАЛЧЕНЦЫ~~.)
Проще банить дебилов, которые любят сделать разгерму чтобы пабедить. Одина, две джобки и возможно к нему дойдет.

Если снять защиту от космоса, то половина их экипировки покупаемая за телекристаллы станет бесполезная и не юзабельная. Не то чтобы её кто-то юзал до этого, но ето такое себе балансирование.


~~Где перепиленая карта-планета которую ты обещал, я не чувствую её~~

**Comment by YulianR** [comment]
>Убираешь защиту от давления = станционные крысы-химики делают калевою бомбу 100х100 и кидаю её в гейтвей.

Опять истории про механоебов в стиле "вы просто выпиливать ролей не умеете", заканчивай. 

>с дробовикам

Нет патронов, надо бегать в карго заказывать, а в карго могли потратить деньги, и всякое прочее, это не то же  самое, как если бы они лежали просто в арсенале. Единственное имбовое против нюкеров - м79.

>считаю только охрану, ХоСа, капитана

Пять офицеров, один варден, один дедектив, хос и капитан. Чет не в два раза, но больше. И это только при полном составе охранки, ты забыл, что офицеров может вообще двое быть, или один. 

Ну а насчет нерфа - мне кажется если и нерфить, то можно замедление добавить и все, учитывая сколько у нюкеров различных девайсов и пушечек для выпиливания стейшона - они и так круты, а броняриг все же выглядит как-то странно

**Comment by Skippeer12** [comment]
Я не говорю как НУЖНО делать, я сказал как это будет происходить после убирания защиты от давления. Вместо шести рыл которые будут пытаться делать разгерму, будет 26.

Да извини, прощитался на три рыла. Не 12, а 9-+миллионы цивильных рембо. Проще всего запилить два режима брони, как на том же ТоГе один очень быстрый и защищает от спейса, а второй бронированный и не защищает от спеса. Но этого делать никто не будет, потому что...

М79 единственное оружие с которого вы умеете убивать. Но если ты в соло полезишь на шесть рыл то тебе хана, даже будь у тебя полный арсенал в рюкзаке.

**Comment by WallShrabnic** [comment]
У вас сломался шкипер, увозите

**Comment by Kurshan** [comment]
#1712
