### ISSUE TITLE
Телекоммс траффик контроль не работает

### ISSUE THREAD

**Issue by Zmey25** [TauCetiStation/TauCetiClassic#1719]
#### Подробное описание проблемы
Телекоммс трафик контроль не работает
#### Что должно было произойти
Должен работать и помогать в черных делишках, в прикольных фишках для общего канала
#### Что произошло на самом деле
Отключили
#### Как повторить
Зайти в посмотреть в телекомах
#### Дополнительная информация:
На бее работает, наверное

**Comment by Raschert0** [comment]
Так и задумано. Причина: слишком лагуч

**Comment by DeadOberst** [comment]
Это было в далеком 2015, с тех пор было много лагофиксов. К тому же другие сервера как то живут и не жалуются.
Как на счет того, чтобы вернуть эту крутую фичу? А ведь она вправду крутая. И Ольт ее еще не знает.
