### ISSUE TITLE
Некорректное отображение спрайтов некоторых предметов в мусоре

### ISSUE THREAD

**Issue by Rarf247** [TauCetiStation/TauCetiClassic#1724]
#### Подробное описание проблемы
Существуют некоторые предметы, которые при взятии в руку/перекладывании в рюкзак теряют свой спрайт, вследствие чего их нельзя снять с человека без помощи другого человека, или нельзя вытащить из рюкзака без магии педалей, но при этом, они занимают .
#### Что должно было произойти
Спрайт не должен теряться
#### Что произошло на самом деле
Спрайт теряется
#### Как повторить
Повторить можно на примере предмета old chitinous mass. Найти его в мусоре, взять в руку и положить в рюкзак. Спрайт при перекладывании в рюкзак пропадет.
#### Дополнительная информация:
На первом скрине первый предмет в слоте это и есть old chitinous mass.
![screenshot_5](https://user-images.githubusercontent.com/6348726/29269328-dba2193c-812b-11e7-843c-c5578f431423.png)
![screenshot_6](https://user-images.githubusercontent.com/6348726/29269274-9358e11a-812b-11e7-9f76-07c77eedf379.png)
![123123123](https://user-images.githubusercontent.com/6348726/29269316-c0b28e2c-812b-11e7-90cc-c9c34cc54107.png)

**Comment by SpaiR** [comment]
@Lancer411

**Comment by RichardJones1** [comment]
Единственный способ это пофиксить - поймать момент этого бага и педально посмотреть, какой у него icon_state.
