### ISSUE TITLE
Спрайт грязных ботинок

### ISSUE THREAD

**Issue by Bedlam4eg** [TauCetiStation/TauCetiClassic#1726]
#### Подробное описание проблемы
Спрайт ботинок испачканых ботинок маслом не очищается после стирки
#### Что должно было произойти
ботинки должны били стать чистыми
#### Что произошло на самом деле
после стирки остались грязыми.

**Comment by kopoba** [comment]
было тоже самое только с кровью

**Comment by Lancer411** [comment]
@Bedlam4eg если ботинки старые, то иногда так и должно случаться.

**Comment by volas** [comment]
Дубликат #1551
