### ISSUE TITLE
Джукбокс

### ISSUE THREAD

**Issue by KatoMarika** [TauCetiStation/TauCetiClassic#1727]
#### Подробное описание проблемы
Не работает джукбокс, в нем нет треков. Плей листы переключаются, а треков нет.
#### Что должно было произойти
Веселый карнавал, музыка играет и хоп с еганом на берегу.
#### Что произошло на самом деле
Отсутствующий карнавал. Музыки нет. 
#### Как повторить
Подойти в бар, потыкать в интерфейс джука. Или заспавнить джук и потыкать в него. Или в кафе для глав.

**Comment by Zmey25** [comment]
Наверное, что-то случилось с сервом музыки для джукбокса

**Comment by Skippeer12** [comment]
Вы разгневали Бога Молесту, вот он вам и отключил музыку. Верните его доверие, чтобы слушать её и дальше.

**Comment by SpaiR** [comment]
Проблемы на сервере музыки суть временное явление
