### ISSUE TITLE
Брейн не лечится.

### ISSUE THREAD

**Issue by psebash** [TauCetiStation/TauCetiClassic#1733]
#### Подробное описание проблемы
Когда делаешь реанимацию хумана через мозг пишет что его мозг умер и нельзя снять брейндамаг даже операцией
#### Что должно было произойти
Брейн снимается алкизином/операцией
#### Что произошло на самом деле
Он не снимается, но игрок может все так же функционировать с 'мертвым мозгом'
#### Как повторить
Пересади мозг трупа в тело живого хумана, реанимируй и погляди в сканер. Попробуй сделать операцию или напоить алкизином.
#### Дополнительная информация:
NA

**Comment by WallShrabnic** [comment]
У тебя из ишью непонятно, о чём речь. Брейндамаг вообще не лечится, или он не лечится после пересадки мозга в другое тело?

**Comment by CryptoKisik** [comment]
Шрубник, ты глупый? У него же все ясно описано. Что бы повторить, нужно пересадить мозг трупа в тело живого хумана, реанимировать и посмотреть в сканер. Будет замечено, что мозг мертв. И исцелить мертвый мозг нельзя ни алкизином, ни операцией

**Comment by Motzord** [comment]
Оно пофиксилось само собой
