### ISSUE TITLE
Баг со станами и падениями

### ISSUE THREAD

**Issue by TungstenOctopus** [TauCetiStation/TauCetiClassic#1734]
#### Подробное описание проблемы

Иногда, когда падаешь, например, подскользнувшись, и встаешь после этого, то ты еще несколько секунд не можешь двигаться. 

#### Что должно было произойти

Встаешь и сразу можешь бежать куда хочешь, как раньше

#### Дополнительная информация:

Сломалось это месяц-два назад вроде

**Comment by RichardJones1** [comment]
Стоп, так это баг???? Я думал у нас так работает Weaken

**Comment by FelixRuin** [comment]
тут мысль в том чтоб лежать пока не можешь двигаться
но ты падаешь на пару секунд
а потом ещё пару секунд не можешь двигаться 
и смысл вставать тогда?

**Comment by LudwigVonChesterfield** [comment]
Очень много мест где кроме Weaken-а параллельно накидывается стан, или паралич с большим временем чем Weaken, из-за чего наблюдается подобный эффект. Учитывая что его "специально" накидывали больше, то возможно это by design. :shrug:
