### ISSUE TITLE
Поломанный и униженый ии морально не может использовать хоткеи на шлюзах.

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1736]
#### Подробное описание проблемы
Шифт-клик, контрол-клик и альт-клик не работают.
#### Что должно было произойти
Они должны работать.
#### Что произошло на самом деле
Они не сработали.
#### Как повторить
Не знаю, может попробовать их нажать.
#### Дополнительная информация:
ААААААААААААААААААААААААААААААААААААААААА!!!

**Comment by Avatar4** [comment]
И синтеты возможно тоже

**Comment by Forrya** [comment]
И синтеты тоже, их просто морально опустили.

**Comment by DeadOberst** [comment]
Ну вот, а я думал это нерфоирк. И целый день дезинформенторил. 
Простите меня!
