### ISSUE TITLE
HUG MACHINE

### ISSUE THREAD

**Issue by MrFoxik** [TauCetiStation/TauCetiClassic#1737]
#### Подробное описание проблемы
Предлагаю портировать модуль борга с ТГ - Peacekepeer.
Эта милота умеет: обнимать, создавать печенье, создавать энергетические барьеры, флэш и огнетушитель включен, и есть конфузящий всех людей вокруг рупор. Этож ахуенно.

#### Что должно было произойти
Он должен быть.
#### Что произошло на самом деле
У нас его нет.
#### Как повторить
Спиздить.
#### Дополнительная информация:
Оно милое.

**Comment by Tolerantboy** [comment]
У нас есть бробот и его достаточно. А этот задолбает всех орать в рупор
