### ISSUE TITLE
Бесконечная еда в вирусологии

### ISSUE THREAD

**Issue by Uboaaaaaa** [TauCetiStation/TauCetiClassic#1739]
#### Подробное описание проблемы
Pathogenic incubator в вирусологии бесконечно фармит еду для вируса если вставить в него пустую колбу.
#### Что должно было произойти
Колба пустая = еды нет.
#### Что произошло на самом деле
Бесконечное накапливание единиц еды.
#### Как повторить
Вставьте в инкубатор пустую колбу и наблюдайте.
#### Дополнительная информация:
может это фича?

**Comment by Tolerantboy** [comment]
Разве это не фича? Это же вроде какая-то автономная микробиологическая ферма в которой выращивается эта самая еда

**Comment by Uboaaaaaa** [comment]
нет, вы путаете с Food dispenser (раздатчик еды). в инкубаторе вирус выращивается и мутирует

**Comment by volas** [comment]
Закрыто #1819
