### ISSUE TITLE
кабель при строительстве

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#174]
Originally reported by: **Dennok (Bitbucket: [Dennok](http://bitbucket.org/Dennok), GitHub: [Dennok](http://github.com/Dennok))**

---

При строительстве когда нужен кабель его забирает по одному кусочку (если надо 5 кабль коил то надо 5 раз кликнуть мотком проводов, и отсутствует сообщение о том что добавил кабель).

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/174

**Comment by Dennok** [comment]
Наканецта,

**Comment by Dennok** [comment]
Всегото один год прошел.
