### ISSUE TITLE
Лазерный скальпель перестал выполнять свою функцию.

### ISSUE THREAD

**Issue by CryptoKisik** [TauCetiStation/TauCetiClassic#1740]
#### Подробное описание проблемы
При попытки сделать надрез (во время операции) с использованием лазерным скальпелем, лишь происходит удар хумана.
#### Что должно было произойти
Должен был сделаться надрез.
#### Что произошло на самом деле
Хуман на операционном столе получил удар в место, где должна была проводиться операция.
#### Как повторить
Взять хумана для операции. Положить на стол. Взять скальпель в руку. Попытаться сделать надрез.

**Comment by WallShrabnic** [comment]
Интенты и наличие одежды проверял? Наличие урона?

**Comment by DeadOberst** [comment]
Сколько раз ты проверял?
У т2 скальпеля есть шанс неудачной операции. Без ошибок работает только Т3.
Хотя там, вроде, ошибки только при окончании действия.

**Comment by CryptoKisik** [comment]
Конечно же я глупый. И во время операции я попросту на харме бил человека в одежде, надеясь, что он излечится.

Проверял три раза. Два на голове, один на торсе. Все три раза были простыми ударами. Просто скальпель (который лежит в хирургии) работал на ура. Этот же не начинал действие операции. Он бил.

**Comment by Uvash** [comment]
Скальпели имеют шанс сломаться вроде. Отнёс бы в РнД

**Comment by Avatar4** [comment]
Скальпели Т2 и Т3 это просто говно. Они работают как гетто инструменты, хотя по сути должны быть безопасны. Суть этих скальпелей в том, что после них не надо перекрывать кровь. Именно поэтому скальпель Т2 должен просто резать чуть медленнее обычного скальпеля, Т3 уже быстрее а Т4 очень быстро. Но вместо этого их никто не использует из за того что они наносят больше вреда чем пользы.

**Comment by Skippeer12** [comment]
![](http://img0.joyreactor.cc/pics/post/it-%D0%B1%D0%B0%D0%B3-4010550.gif)

**Comment by Skippeer12** [comment]
Не смог повторить. Все скальпели работают отлично за исключением ускорения. Но крови нет, они нормально режут.
