### ISSUE TITLE
Невозможно сделать укол, держа плащ ХоСа в руке.

### ISSUE THREAD

**Issue by CryptoKisik** [TauCetiStation/TauCetiClassic#1746]
#### Подробное описание проблемы
Если снять с себя плащ ХоСа и держать его в руке, а в тоже время попытаться сделать себе укол в тело из другой руки, получим ошибку, что нет свободного места для укола.
#### Что должно было произойти
Мы должны были уколоть себя.
#### Что произошло на самом деле
Мы не смогли уколоть себя, потому что плащ ХоСа, который находится во второй руке - мешает нам.
#### Как повторить
Взять в одну руку плащ ХоСа, во вторую шприц. Попробовать уколоть себя.
#### Дополнительная информация:
Тестировалось со старым плащем. С другими предметами не проверяли (такими как риг и бронежилет). Так же не проверял, может ли кто-то другой уколоть в этот момент.

**Comment by volas** [comment]
Может кто нибудь еще проверить с другими предметами?
