### ISSUE TITLE
Нельзя повесить наручники или кабельные стяжки на человека за вокса

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1748]
#### Подробное описание проблемы
Невозможно повесить за вокса на человека наручники высвечивается данное сообщение: You need to have a firm grip on Danny Newton before you can put the cable restraints on!
#### Что должно было произойти
Наручники должны были одеться
#### Что произошло на самом деле
Они не оделись
#### Как повторить
За вокса попытаться одеть наручники на человека
#### Дополнительная информация:
Пробовал все способы, второй/третий граб, ничего не сработало, не получил гринтекст из-за этого

**Comment by Skippeer12** [comment]
Всё ведь работает. 
![image](https://user-images.githubusercontent.com/18488106/35797950-ffb30756-0a69-11e8-8b07-31584a372869.png)
![image](https://user-images.githubusercontent.com/18488106/35797983-1d0ed5be-0a6a-11e8-92bb-33f242b35fe6.png)
