### ISSUE TITLE
Полевая хирургия не работает на обычной кровати

### ISSUE THREAD

**Issue by Balphagore** [TauCetiStation/TauCetiClassic#1751]
#### Подробное описание проблемы
На обычной кровати нельзя проводить хирургические манипуляции. Все попытки засчитываются как атака.
#### Что должно было произойти
Хирургические манипуляции должны проводиться на кровати.
#### Что произошло на самом деле
Все попытки сделать надрез на теле пациента, лежащего на кровати, засчитываются как атака. При том что в полевой хирургии возможны 1-2 неудачи, тут можно тыкать его до смертельного исхода, так что вариант банального невезения исключен. 
#### Как повторить
Положить пациента на кровать и попробовать сделать надрез скальпелем.
#### Дополнительная информация:
Операции можно проводить на каталке и даже на обычном железном столе. Если уж на столе можно, то в кровати все должно работать тоже.

**Comment by StrikS** [comment]
А операции можно проводить на кровати профессиональными инструментами?
Вот тебе и ответ.
Участвуют только обычные/хирургические столы и каталки.

**Comment by Balphagore** [comment]
А с чего ты решил, что мой ответ нет? Полевая хирургия на то и полевая хирургия, что об удобствах и правильности в ней и не слышали. Если персонаж лежит горизонтально и не дергается, то почему я не могу, хоть и с грехом пополам, разрезать его и вытащить почку?

**Comment by StrikS** [comment]
Не знаю как там в ИРЛ, надо спросить Дреда, но скорее всего там ищут НЕупругую, ровную поверхность. Может дашь ссылку на случай, когда проводили операцию на кровати?

**Comment by Forrya** [comment]
Кидай его на стол обычный и на нем шинкуй на шаурму.

**Comment by dred1792** [comment]
Таки да, ищут твёрдую и ровную поверхность. О случаях оперирования на мягкой кровати я не слышал, но почему бы и нет, выглядело бы забавно. :)

**Comment by igigin** [comment]
Никто и не задумывал проведение операций в кровати. Не баг, на пропозал тоже не похоже. Закрыто.
