### ISSUE TITLE
Большие окна (на весь тайл) пропускают воду.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1755]
#### Подробное описание проблемы
Если допустить что у нас есть в центре резервуар с водой который закрыт большими окнами, то вода будет вытекать наружу. 
#### Что должно было произойти
Вода не должна вытекать из под таких окон если они закручены.
#### Что произошло на самом деле
Вытекает
#### Как повторить
Построить такой же резервуар с водой.
#### Дополнительная информация:
http://imgur.com/a/m1r07

**Comment by Forrya** [comment]
Ты не думал, что мусорка воду проводит?

**Comment by Avatar4** [comment]
Нет, вода текла со всех стекол пока не поставил обычные.

**Comment by Skippeer12** [comment]
Ну, не знаю как ты там это делал, но оно не протекает.
![image](https://user-images.githubusercontent.com/18488106/35798110-7a8704fa-0a6a-11e8-94a3-173fbab6de02.png)
