### ISSUE TITLE
Алиенхантер-стулокрад

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1757]
#### Подробное описание проблемы
Алиенхантер катаясь на стуле и прыгая все это время получает резист от столкновений. При прыжке в стену или любой другой не роняемый объект алиен не будет падать, а сразу же сможет прыгнуть дальше.
#### Что должно было произойти
При прыжке с положения: кислотные булки на стуле алиен должен переворачиваться и падать со стула.
#### Что произошло на самом деле
Приросший к жопе алиена стул прыгнул вместе с ним.
#### Как повторить
Дождаться когда лолон запустит алиенов, взять алиена, найти стул.

**Comment by volas** [comment]
Скорее всего не хватает проверки на buckled в вербе
