### ISSUE TITLE
Турфы, на которых был блоб, иногда перестают пропускать блоб

### ISSUE THREAD

**Issue by Raschert0** [TauCetiStation/TauCetiClassic#1759]
#### Подробное описание проблемы
Если на какой-то турф, с одной стороны которого есть вакуум, а с другого - нормальное давление, прорастёт блоб, этот турф может перестать пропускать воздух даже после удаления блоба
#### Что должно было произойти
Воздух должен был выйти и устроить разгерму
#### Что произошло на самом деле
Воздух не вышел, хотя ему ничто не мешало
#### Как повторить
1. Сделать блоба
2. Сломать некоторое количество стен в космос (так, чтобы после слома стены воздух не вышел сразу же) и нарастить на их место блоб
3. Уничтожить выросший блоб и посмотреть пропускаемость воздуха. В случае неудачи повторить с начала.

**Comment by volas** [comment]
Видимо после #1659, может блоб не полностью удаляется с турфа
