### ISSUE TITLE
Полицейскую/инженерную ленту нельзя сорвать в наручниках

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#1762]
#### Подробное описание проблемы
В наручниках нельзя сорвать ленту
#### Что должно было произойти
На интенте харм ты должен был сорвать ленту
#### Что произошло на самом деле
Ничего
#### Как повторить
Попробовать хоть как-то пройти через ленту в наручниках

**Comment by WallShrabnic** [comment]
А ещё нельзя двери открывать и взаимодействовать с чем-либо. Сделано, очевидно, для баланса

**Comment by 241214234343** [comment]
Надо вообще сделать, чтобы если на харме человек бежал, то лента бы сама срывалась

**Comment by volas** [comment]
Думаю что фича
