### ISSUE TITLE
Безногие со спавна люди не падают без коляски, а летают

### ISSUE THREAD

**Issue by Heroman3003** [TauCetiStation/TauCetiClassic#1763]
#### Подробное описание проблемы

Люди, которым в настройках персонажа поставили отсутствие ноги спавнятся в коляске. При попытке вылезти из коляски они медленно летают.

#### Что должно было произойти

При попытке вылезания или вытаскивании из коляски инвалид должен падать на пол

#### Что произошло на самом деле

При попытке вылезания или вытаскивания из коляски инвалид "стоит" и может очень медленно "парить" (медленнее чем в коляске)

#### Как повторить

Создать персонажа без ног, заспавниться им и вылезти из коляски

#### Дополнительная информация:

------

**Comment by Forrya** [comment]
Простор для ропе отыгрыша для священника, показывающего силу его господа бога.

**Comment by Tolerantboy** [comment]
Отсутствие ноги или ног? Потому, что если ноги, то он прыгает на одной ноге

**Comment by Skippeer12** [comment]
Уже пофиксили, закрывайте.
