### ISSUE TITLE
Офицеры не могут нормально выйти в космос

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1764]
#### Подробное описание проблемы
У офицеров нет доступа в аирлоки космоса. Из за этого они не могут нормально выйти в космос к примеру во время карпов.
#### Что должно было произойти
У них должен быть доступ для выхода в космос.
#### Что произошло на самом деле
Они кравлят через карго

**Comment by KatoMarika** [comment]
Ну, как только мапфриз спадет, сделаю дополнительный шлюз где-нибудь в доках и который рядом с бригом получит доступ. Этого должно хватить.

**Comment by Avatar4** [comment]
А как в будущем офицеры поймут где есть доступ а где нет? Лучше уже прописать всем шлюзам в космос дополнительный офицерский доступ.

**Comment by KatoMarika** [comment]
Ченжлог в помощь. 
Нет, будут гулять в инжирку через спейс. Оно нужно?

**Comment by Avatar4** [comment]
Можно просто убрать доступ к инженерным шлюзам, благо, там рядом есть обычные. Дело 5 секунд.

**Comment by StrikS** [comment]
Не все так просто.

**Comment by YulianR** [comment]
По техам находится куча шлюзов, к которым почти ни у кого нет доступа.

**Comment by CryptoKisik** [comment]
Я вот чего думаю. Восточнее Брига есть шлюз. Измените у него доступ на офицерский. И пускай он будет.

**Comment by Lancer411** [comment]
Мусоропровод в космос без возможности вернуться для офицеров.

**Comment by Skippeer12** [comment]
You to late, son. #907

**Comment by igigin** [comment]
Полезный шкипер.

**Comment by Avatar4** [comment]
Будто я помню все 1764 ишью.

**Comment by Raschert0** [comment]
@Avatar4 там этот, как его, ну... Ах да, поиск есть

**Comment by igigin** [comment]
Только тут всего 911 ишьюсов было.
