### ISSUE TITLE
Очепятка в criminal status

### ISSUE THREAD

**Issue by Zillouser** [TauCetiStation/TauCetiClassic#1765]
#### Подробное описание проблемы
В criminal status в security console есть несколько статусов, один из них – Parolled, вместо правильного Paroled

**Comment by Raschert0** [comment]
Но ведь это идентичные строки!

**Comment by Zillouser** [comment]
Не понял, при чём здесь строки?

**Comment by Raschert0** [comment]
У тебя в ишью два одинаковых слова Parolled

**Comment by Zmey25** [comment]
Оп, наверное, хотел сказать, что нужно с одной л писать.
