### ISSUE TITLE
Бесконечная заправка Pathogenic Incubator

### ISSUE THREAD

**Issue by Zillouser** [TauCetiStation/TauCetiClassic#1766]
#### Подробное описание проблемы
Если в ставить в Pathogenic Incubator, машину из вирусологии любую подходящую ёмкость, то он начнёт автоматически заполняться Virus food до неизвестных пределов. Если же вставить ёмкость с virus food то он будет высасывать virus food из ёмкости и после окончания начнётся то же самое, только с задержкой.
#### Что должно было произойти
Ничего с пустой ёмкостью. Заполнение машины с ёмкостью с virus food.
#### Что произошло на самом деле
Бесконечное заполнение машины из пустой ёмкости. Из полной ёмкости всё предварительно высасывается и только потом начинает заполняться.
#### Как повторить
Засунуть любую принимаемую машиной ёмкость в Pathogenic Incubator(например vial - пробирку). Засунуть ёмкость с virus food.

**Comment by WallShrabnic** [comment]
Не так давно уже кидали https://github.com/TauCetiStation/TauCetiClassic/issues/1739

**Comment by volas** [comment]
Закрыто #1819
