### ISSUE TITLE
Не ищет РЦД через поинтер.

### ISSUE THREAD

**Issue by DctrMM** [TauCetiStation/TauCetiClassic#1767]
#### Подробное описание проблемы
РЦД не ищется через пин-поинтер капитана.
#### Что должно было произойти
РЦД находится через поинтер, тритор наказывается.
#### Что произошло на самом деле
РЦД не находится через поинтер, никак его не найти.
#### Как повторить
Взять в руки поинтер и врубить поиск на РЦД.
#### Дополнительная информация:
http://prntscr.com/gdcq3v - там даже знака вопроса нет, вообщем что-то сломалось.

**Comment by Motzord** [comment]
Фикс вмержили, но ишью не закрыли
