### ISSUE TITLE
Руна "Вселение призрака" не работает

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1768]
#### Подробное описание проблемы
Руна "Вселение призрака" за культистов не работает.
#### Что должно было произойти
Стоящий на руне культист при ее активации должен вселять гостов в искусственные тела.
#### Что произошло на самом деле
Она не работает

**Comment by igigin** [comment]
Что конкретно ты делал и на каком именно пункте всё пошло не так. Ничего же не ясно из того что ты написал, кроме того, что ты не смог в руну.

**Comment by Avatar4** [comment]
Ну сорян.
Закрылся стенками в отбытии, начертил руну, встал на нее, начал закликивать но никто не заспавнился из гостоты. Судя по тому что Куршан мне написал что не работает, то вся гостота была на тайле со мной и должна была реснуться, но этого не произошло. Все слова были правильными.

**Comment by StrikS** [comment]
Не знаю пофиксили или нет, но меня так призывали без проблем

**Comment by Skippeer12** [comment]
Чтобы призывать гостов нужно чтобы госты находились на руне призыва или орбитили культиста который хочет их призвать. Не баг.

**Comment by Avatar4** [comment]
Его уже пофиксил давно. Закрывайте
