### ISSUE TITLE
Человека под прикрытием (Unknown) может спалить флавор

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1769]
#### Подробное описание проблемы
Человека под прикрытием (Unknown) может спалить флавор
#### Что должно было произойти
Флавор должен исчезать когда человек становится Unknown и появляться если вернул снова свое лицо (свое а не налепил чужую карту).
#### Дополнительная информация:
Спорно конечно и метагейски, но все равно решил сказать на всякий.

**Comment by Tolerantboy** [comment]
А потому надо запилить назад те охрененные флаворы для каждой части тела.
