### ISSUE TITLE
Иллюзия полной коробки

### ISSUE THREAD

**Issue by Tolerantboy** [TauCetiStation/TauCetiClassic#1770]
#### Подробное описание проблемы
Если Ян поест из коробки с пончиками, то спрайт коробки не будет меняться - внешне она все еще будет полной, хотя в ней не хватает пончиков или она вовсе пуста

#### Что должно было произойти
Спрайт коробки должен был меняться, а пончики внешне убывать

#### Что произошло на самом деле
Коробка якобы полная

#### Как повторить
Пикнуть Яна, поесть из коробки с пончиками

**Comment by Forrya** [comment]
Хах, двуноголохи соснули. Четвероногие боги одержали очередную победу!

**Comment by l0lone** [comment]
Зве, как ты смог это допустить?

**Comment by DeadOberst** [comment]
Просто Ян может воровать еду так, чтобы никто не этого не заметил.
