### ISSUE TITLE
Спам приглашениями в реву

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1773]
#### Подробное описание проблемы
У приглашений в реву вроде как нет отката, из-за чего можно спамить приглаениями в революцию. Очень раздражает, плюс есть вероятность промахнутьсяпо кнопке и случайно вступить
#### Что должно было произойти
Откат при отказе хотя бы десять минут
#### Что произошло на самом деле
Спам приглашениями, едва не вступил в реву
#### Как повторить
Стать главревой и нажимать кнопку Rev-Convert

**Comment by Zmey25** [comment]
И с культом тоже самое нужно сделать, меня вчера отвели в угол и спамили приглашениями, даже не объяснив куда именно зовут.

**Comment by CryptoKisik** [comment]
А что мешает тебе отключить вступление в реву?

**Comment by kopoba** [comment]
Нет такого пункта как отключить вступление в реву. Даже если в ролях у тебя все на ноу это не мешает кидать тебе инвайт.

**Comment by CryptoKisik** [comment]
Берешь такой во время игры, открываешь преференсы. Выключаешь вступление в реву. Вуаля. тебе не могут дать приглос. Не надо давать ложную инфу.

**Comment by Motzord** [comment]
fixed
