### ISSUE TITLE
Термит поджигается только от горелки.

### ISSUE THREAD

**Issue by OfGreyBugWaifu** [TauCetiStation/TauCetiClassic#1775]
#### Подробное описание проблемы
Термит, ненесённый на поверхности или стены не поджигается от зажигалок, спичек и зипп - он поджигается только горелкой.
#### Что должно было произойти
Термит должен поджечься от любого огня.
#### Что произошло на самом деле
Термит пожогся только от горелки.
#### Как повторить
Попытаться поджечь термит 
#### Дополнительная информация:
Нету её.

**Comment by Raschert0** [comment]
https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D1%80%D0%BC%D0%B8%D1%82%D0%BD%D0%B0%D1%8F_%D1%81%D0%BC%D0%B5%D1%81%D1%8C
>Смесь поджигают специальным запалом (смесь пероксида бария, магния и натрия)
Окей,, сделаю так, чтобы термит поджигался только с помощью определённой смеси (которую нужно будет поджечь чем-то ещё...)

**Comment by DeadOberst** [comment]
Сейчас бы пользоваться только Википедией для ознакомления с вопросом. Температура воспламенения термита ~800-1200оС. Спичками поджечь не получиться, а вот горелкой вполне возможно.
Вовсе не баг, но дополнительную легковоспламеняющаюся смесь добавить можно. И воспламенение от эмиттеров, пожаров, пульсачей и чего-нибудь ещё.
Но выпиливать горелку точно не стоит.
