### ISSUE TITLE
Соснуть за нюку за 30 секунд.

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1776]
#### Подробное описание проблемы
Нюкер в навороченой штурмовой броне сосет от флешбенга.
#### Что должно было произойти
Он настолько крутой, что ему поебать на флешбенг.
#### Что произошло на самом деле
Нюкер влез из гейтвея, поймал флешбенг, оказался униженым морально соснув не успев сделать и выстрела.
#### Как повторить
Словить флешбенг.

**Comment by Forrya** [comment]
I dead plz nerf

**Comment by igigin** [comment]
Пиши названия и описания нормально, сколько раз тебе говорить.

**Comment by Zmey25** [comment]
Нет, нюкеры не должны бежать на флешбенги. Лучше понерфить задержку гейтвея после анонса до 30-ти секунд. Это бы вас спасло сегодня.

**Comment by Forrya** [comment]
Раньше, в православных, кроваво красных ригах нюкерам было почти плевать на флешбенги. Теперь - нет. Выбегаешь, ловишь флешбенг, на тебя наручники надевают.

**Comment by CryptoKisik** [comment]
Покупайте риги. Что мешает? Это бронежилет и каска на вас. А не полностью закрытый риг.

**Comment by P-20** [comment]
Тут почти полноценный шлем как в риге. Не должно флешить. Из шлема только волосы торчат.

**Comment by sovok4** [comment]
Да, надо пофиксить, чтобы помимо жуткой непробиваемости, устойчивости к давлению и нарушениям герметичности, нюкера в этом костюме нельзя было свалить и флешбенгом. Ещё можно дать нюкеру в этом шлеме возможность гибать взглядом. И устойчивость к станбатону, без этого никак.

**Comment by DeadOberst** [comment]
Сократить время стана к аналогичному у офицеров.

**Comment by WallShrabnic** [comment]
Совок поехал, куршан пофиксил устойчивость к низкому давлению

**Comment by Skippeer12** [comment]
Закрывайте, если не баг фиксить нечего.
