### ISSUE TITLE
Тенелинги могут получать повреждения внутряка но не могут их лечить.

### ISSUE THREAD

**Issue by EdlerN** [TauCetiStation/TauCetiClassic#1778]
#### Подробное описание проблемы
После превращения тенелинг способен отхватывать повреждения органов, но не способен их самостоятельно восстанавливать. К примеру - нахватать из лазеров в лицо до потери зрения, а потом сидеть остаток раунда в техе живым, но ослепшим.
#### Что должно было произойти
Темнота должна восстанавливать все повреждения/Какая-либо из способностей должна лечить внутряк
#### Что произошло на самом деле
Живой, но слепой тенелинг, скучающий в техах.
#### Как повторить
Стать тенелингом, переродиться, нахватать лазеров в лицо до потери зрения, ну либо каким нибудь способом получить другие повреждения органов, уйти в темноту, сидеть инвалидом с полным хп

**Comment by LudwigVonChesterfield** [comment]
У тенелингов осталось только сердце, и то вероятно потому-что говнокодеры прошлого не додумались как сделать чтобы моб без него жил.

Ишуй не актуален.
