### ISSUE TITLE
проблема c инвалидной каталкой

### ISSUE THREAD

**Issue by vay534** [TauCetiStation/TauCetiClassic#1779]
если ты в каталке и её кто то взял всё ты его раб ибо отцепиться ты не можешь , слезть тоже не можешь  и даже если ты задизармиж его жопой он все равно будет держать её и тебе очень повезло если это клоун который решил тебя по бесить но не повезло когда это шедув и ещё меньше когда генокрад  
 
ты должен был слезть, отцепить человека от каталка , задизармив его жопой он должен был её отпустить 

ты в полной власти человека взявшего каталку  и тебе не освободиться без чужой помощи 

сеть в каталку , позвать друга 

человек держащий каталку движется под спидами

**Comment by Forrya** [comment]
Я бы посмотрел как безногий в каталке сопротивляется тому, что его тащат.

**Comment by Avatar4** [comment]
Бери всегда с собой болон и бей ему в гроинг.

**Comment by Tolerantboy** [comment]
Нужно хотя бы возможность спрыгнуть с каталки - ведущий каталку же держит ее, а не сидящего в ней. Какой-то имбы инвалидам это не даст - они станут еще беспомощнее без своего кресла, смогут только медленно ползти, шанс на побег вырастает не намного и то только для хитрожопых и ловких игроков, а у нас не каждый второй такой

**Comment by Smalltasty** [comment]
А если еще и ручек нет, как он культяпками сопротивляться будет? Это ж тоже надо учитывать.
