### ISSUE TITLE
Шлюз на западную сторону астероида поломат

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#1780]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/21046015/29828058-27dd2c72-8cf5-11e7-9dc4-53aa9b7e77b4.png)
Вот этот шлюз сломан и не откачивает/закачивает воздух. Венты горят красным - воздух не откачивается.
#### Что должно было произойти
Венты должны были откачать воздух и открыть шлюз
#### Что произошло на самом деле
Шлюз закрылся, началась процедура откачивания воздуха, воздух не откачивается
#### Как повторить
Нажать кнопку выхода

**Comment by Zmey25** [comment]
Появилось совсем недавно

**Comment by Avatar4** [comment]
Такое уже было и баг вроде как не постоянен. Обычно лечилось закликиванием пятой кнопки (ресет или как-то там).

**Comment by DeadOberst** [comment]
Может дело в баке с воздухом? Если он пуст, то цикл шлюзов будет бесконечным.

**Comment by SpaiR** [comment]
Починено после синхронизации с атмосом бея
