### ISSUE TITLE
Кибер-хорроры и спу

### ISSUE THREAD

**Issue by MrFoxik** [TauCetiStation/TauCetiClassic#1781]
#### Подробное описание проблемы
Насколько я понял - когда в меня бахнули нанитов и я был СПУ - ничего не произошло, как только я улетел на астероид начал мелькать красный текст. Получается что при перелетах у СПУ включается поглощение веществ. Возможно можно абузить для лечения брута и бёрна. При обратном перелете процесс остановился. И вообще, Зве где твой ПР с новыми штуками для СПУ вроде синт-кожи.
#### Что должно было произойти
НИЧЕГО
#### Что произошло на самом деле
Превращение в кибер-хоррора.
#### Как повторить
Полетать за СПУ с нанитами внутри.
#### Дополнительная информация:
Давно нашел этот баг, только один раз ловил, актуально или нет - проверяйте сами.

**Comment by StrikS** [comment]
Киберхорором можно стать если в тебя влили Лечебные Наноботы (Medical Nanobots) в количестве больше 20 кубов. Кроме того, ты потеряешь контроль над тушкой киберхорора, что грустно. 
Да и вообще на СПУ не факт, что подействует.

**Comment by P-20** [comment]
У нас большинство мобов не контролируются без педального вмешательства.
