### ISSUE TITLE
Киборги иногда не получают 0 закон при малфе

### ISSUE THREAD

**Issue by Zmey25** [TauCetiStation/TauCetiClassic#1782]
#### Подробное описание проблемы
Дважды играл за киборга при малфе и не получал нулевой закон, хотя находился в игре в самого начала. Если смотреть законы, то там написано, что вы лояльны к ИИ.
#### Что должно было произойти
Должен быть 0 закон.
#### Что произошло на самом деле
Пол игры не знал, что я антаг или вовсе умирал, потому, что ИИ не доверял мне.
#### Как повторить
Играть за одного из двух киборгов при малфе.

**Comment by P-20** [comment]
Законы порой не выдаются сразу всем боргам, и выдаются спустя какое-то время.
Если есть привязка к ИИ, который малф, и нет нулевого закона, можно написать Администраторам, и они добавят вам закон.

**Comment by Zmey25** [comment]
Только вот в последнем раунде у меня просто не было возможности узнать, что есть малф. Пока он меня не взорвал. Да и я мог бы подумать, что ИИ просто тритор и выпилить его случайно.

**Comment by WallShrabnic** [comment]
ИИ может взломать боргов, и у них прописана лояшьность, а это баг, пишите пока в АХ

**Comment by Zmey25** [comment]
А как узнать, когда писать в ах, а когда нет?

**Comment by Avatar4** [comment]
Короче сейчас посмотрел, на самом деле боргам выдается нулевой закон, просто он не показывается в начале. Если кликнуть на законы то он будет

**Comment by Zmey25** [comment]
Ну значит я особенный, потому, что мне не писало ни в начале, ни законы не добавляло, ни даже не писало, что я малф. Нигде.

**Comment by 4310V343k** [comment]
нет
