### ISSUE TITLE
Ограничение на сохранение логов в чате.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1783]
#### Подробное описание проблемы
В чате ССки раньше отображались все логи, за все раунды которые игрок сыграл не выходя из клиента. После нескольких обнов логи начали просто пропадать из-за других сообщений.
#### Что должно было произойти
Все логи должны сохранятся если игрок не вышел с клиента ССки.
#### Что произошло на самом деле
Старые логи заменяются более новыми.
#### Как повторить
Зайти на сервер Тау Кита Классик и подождать около часа в гостоте. Пытаться сохранить лог и понять что сохраненный лог начинается с середины раунда.
#### Дополнительная информация:
:itsnotok:

**Comment by ZVee** [comment]
Ограничение в 1000 строчек и оно не спроста было сделано и не только у нас. Поэтому по поводу изменения ничего не скажу.

**Comment by Skippeer12** [comment]
Мне не понять зачем это ограничение. Возможно оно забивает кэш или что-то ещё, но ведь это нормальная цена за полноценный лог с раундом в котором произошел не самый лучший момент, в котором ты пострадал и доказать ты это можешь только этим логом.

Сейчас же максимум можно запечатлеть разговор с администратором и то не факт если на сервере сидит 90 человек.

**Comment by WallShrabnic** [comment]
Пик людей на сервере - 50-70 тел, это так, к слову. Вообще, все логи отдельно сохраняются на спец. сервере, оэтому надо в первую очеедь просить педалисов

**Comment by Raschert0** [comment]
Шрабник не в курсе того, что на сервере бывает 90+ игроков.

**Comment by Zmey25** [comment]
Не палится, что не бывает на сервере

**Comment by ZVee** [comment]
>и доказать ты это можешь только этим логом

На деле ваши логи не нужны, точнее, все что из них нужно, это имена. Остальное администратор может легко вынуть и даже отфильтровать, а если знает немного регулярки, то вообще проблем никаких нет с тем, что они в общей кучи. Те логи что вы обычно выкладываете, скорее вероятно для зевак представляют интерес больше, хотя в каком-то смысле конечно они могут ускорить процесс, однако прямо чего-то критического в их отсутствии нет.

Ограничение как минимум раньше ставилось из-за того, что слишком раздутый чат начинал лагать клиенты, и были утечки, не знаю как сейчас. Цену этим ты заплатишь такую - что у тебя просто неиграбельная игра будет в какой-то момент или вовсе все повиснит и в итоге и так весь лог улетит в трубу. Но да, возможно за этот промежуток времени что-то поменялось. Еще кстати раньше прокрутка баговалась если кто помнит, тоже из-за того что чат был без лимита.

**Comment by WallShrabnic** [comment]
Педали для разборок нужна одна строчка логов. Это тоже к слову. Если чисто гипотетически введут бесконечные логи, то я за рольку поймаю шкипера и буду срать ему в логи до тех пор, пока он не вылетит
