### ISSUE TITLE
Spider-bot не может залезть под стол.

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#1784]
#### Подробное описание проблемы
Паук-бот не может быстро попасть под стол, только перетягивая себя на стол и нажимая кнопку hide.
#### Что должно было произойти
Он должен легко прятаться как и прочие мелкие существа.
#### Что произошло на самом деле
Он ударился об стол.
#### Как повторить
Зайдите за паука и попробуйте спрятаться.

**Comment by TechCatOther** [comment]
Все работает, просто нажимаешь hide и будешь ходить под столом
