### ISSUE TITLE
Укусы Яна не идут в аттак-логи

### ISSUE THREAD

**Issue by Raschert0** [TauCetiStation/TauCetiClassic#1786]
#### Подробное описание проблемы
Укусы Яна не идут ни в аттак-логи Яна, ни в аттак-логи того,кого Ян укусил
#### Что должно было произойти
Логи. Должны. Быть
#### Что произошло на самом деле
Их нет.
#### Как повторить
1. Взять Яна и какого-либо другого моба
2. Вселиться в Яна и покусать этого самого второго моба
3. Чекнуть логи

**Comment by LudwigVonChesterfield** [comment]
теперь когда есть демка, не очень актуально

(а ещё это фиксится в комбобоёвке на всех мобов, из-за обобщения проков)
