### ISSUE TITLE
Визуальный баг со взломанными вендоматами

### ISSUE THREAD

**Issue by Lexakr** [TauCetiStation/TauCetiClassic#1791]
#### Подробное описание проблемы
Если взломать любой вендомат мультитулом на контрабанду, то при любом открытии/выдаче контрабандного итема, в вендомате будут стакаться строки с этим итемом 
https://image.prntscr.com/image/kwMwUE7ORkmpcfHzBzvg7w.png
#### Дополнительная информация:
Другие игроки тоже это увидят, если 1 человек провернет это

**Comment by omejka** [comment]
<a href="https://imgur.com/KAoaedn"><img src="https://i.imgur.com/KAoaedn.png" title="source: imgur.com" /></a>

**Comment by LLIkolnik** [comment]
Всегда, кстати, думал что это фича.
