### ISSUE TITLE
Урон от Vox spike thrower не лечится.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1792]
#### Подробное описание проблемы
После того как воксы стреляют своим коплеметателем дамаг от них неизлечивается никакими средствами. Ни химией, ни крио, ни бинтами.
#### Что должно было произойти
Урон должен быть излечим.
#### Что произошло на самом деле
Тебя таскают по всему мед.блоку минут двадцат, а потом кидают в палату от безысходности.
#### Как повторить
Пострелять в куклу с Vox spike thrower и попробовать её излечить.
#### Дополнительная информация:
Прибитых к стене людей можно передвигать в шкафу, но нельзя передвигать без шкафа.

**Comment by wadangel** [comment]
Писал уже. https://github.com/TauCetiStation/TauCetiClassic/issues/1652
Раньше можно было в мешках для трупов тела таскать, сейчас не выходит.
