### ISSUE TITLE
Шлюзы два на два тайла работают очень медлено.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1794]
#### Подробное описание проблемы
При использовании шлюзов на откачку воздуха уходит минуты две чтобы выйти в космос. А чтобы закачать воздух в то же пространство потребуется секунд пять.
#### Что должно было произойти
Шлюз на откачку не должен занимать столько времени.
#### Что произошло на самом деле
Космонавт стоит около двух минут в шлюзе чтобы зайти без разгерметизации на станцию

**Comment by Zmey25** [comment]
Меня тоже это бесит, но зве предупреждал об этом.

**Comment by DeadOberst** [comment]
Not a Bag
Живём, космонавтики. Ждём и живём.

**Comment by Skippeer12** [comment]
Ну если это не баг, ждите десяток аутистов, которые не будут ждать по четыре минуты дабы войти на станцию, а просто форсить шлюзы.

Тогда и шлюзовая система не нужна.

**Comment by Skippeer12** [comment]
#1771
