### ISSUE TITLE
Боргов прибивает к стене

### ISSUE THREAD

**Issue by psebash** [TauCetiStation/TauCetiClassic#1798]
#### Подробное описание проблемы
Воксы прибивают боргов спайками к стене
#### Что должно было произойти
Борги не должны быть прибиты к стене
#### Что произошло на самом деле
Их прибило, приходится делать янк аут
#### Как повторить
Зайти за вокса и пострелять по боргам с алиенгана
#### Дополнительная информация:
na

**Comment by ZVee** [comment]
Прибить можно все, другое дело что сейчас есть баг с тем, что открепить борготу часто невозможно после того как ее прикрепит.

**Comment by Skippeer12** [comment]
Закрывайте.
