### ISSUE TITLE
Новый атмосферный отсек потребляет неимоверное количество энергии.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1799]
#### Подробное описание проблемы
Трубы/помпы/датчики/etc.. потребляют слишком много энергии и без настроеного двигателя выключают атмосферный отсек за минут пять.
#### Что должно было произойти
Они не должны потреблять столько энергии.
#### Что произошло на самом деле
Отсек с жизнеобеспечением умирает за пять минут.
#### Дополнительная информация:
Из-за этого трубы можно использовать как аналог поверсинка для бедных.

**Comment by Raschert0** [comment]
Так и задумано

**Comment by Skippeer12** [comment]
Один отдел не должен жрать 100к энергии когда остальные отделы потребляют всего 5к или меньше.
Вы же там за баланс воюете, где он, я его не чувствую.

**Comment by Raschert0** [comment]
Он потребляет соответственно тому, на какое давление вы его настраиваете

**Comment by Zmey25** [comment]
Хороший атмос и изменения интересные

**Comment by Skippeer12** [comment]
#1771
