### ISSUE TITLE
Если нацепить на трейтора смирительную рубашку и оставить в красной зоне шаттла, то он выполнит задание на "убежать".

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1800]
#### Что должно было произойти
Задание не должно было выполнится.
#### Что произошло на самом деле
Трейтор выполнил задание
#### Как повторить
Связать трейтора смирительной рубашкой и оставить в красной зоне шаттла.
#### Дополнительная информация:

![](https://i.imgur.com/wIeKzOR.png)

**Comment by volas** [comment]
В красной зоне должен быть специальный тип пола ``/turf/simulated/shuttle/floor4``, видимо при очередном ремаппе похерили.
