### ISSUE TITLE
Божества с Бея

### ISSUE THREAD

**Issue by MrFoxik** [TauCetiStation/TauCetiClassic#1801]
#### Подробное описание проблемы
У нас нету этой охуенной вещи
#### Что должно было произойти
Оно очень гибкое по концепции и можно своих божков намутить, я аж протекаю.
#### Что произошло на самом деле
ЕГО НЕТУ.
#### Как повторить
Steal & Dev
#### Дополнительная информация:
https://wiki.baystation12.net/Deity

**Comment by Zmey25** [comment]
Можешь начинать портировать.
