### ISSUE TITLE
Illegal equipment module блокирует законы борга

### ISSUE THREAD

**Issue by EdlerN** [TauCetiStation/TauCetiClassic#1803]
#### Подробное описание проблемы
После установки вышеуказанного модуля в борга, у того отключается синхронизация законов и на него перестает работать аплоад. Более того - борга более невозможно емагнуть. 
#### Что должно было произойти
Модуль должен просто открывать "нестандартное" снаряжение и никак не влиять на законы/емагаемость борга
#### Что произошло на самом деле
Модуль делает борга неуязвимым к емагу, а также любым попыткам смены законов
#### Как повторить
Поставить модуль в борга, попытаться сменить ему законы аплоадом или емагом
#### Дополнительная информация:
Возможно фича, но защита от емага это как-то немного дисбалансно (имхо)

**Comment by WallShrabnic** [comment]
Ничего особо дисбалансного тут не вижу, плата стоит дорого, её практически невозможно получить да вставлять без разрешения начальства нельзя

**Comment by EdlerN** [comment]
Дорогая, да. Единственное что. Но при наличии шахтероборга и более ли менее компетентного РД ее можно сделать минуте на двадцатой или около того.

**Comment by Skippeer12** [comment]
А потом ты или РД получает перму за МетаГейм с телесаенсом и дериликтом.

Синхронизацию с аплоудом можно вернуть, но для этого надо знать роботику совершенно.
