### ISSUE TITLE
Собранные консоли видеокамер имеют доступ ко всем камерам, которые видит консоль на мостике.

### ISSUE THREAD

**Issue by baturinsky** [TauCetiStation/TauCetiClassic#1804]
#### Подробное описание проблемы

Собранная консоль видеокамер (Security Cameras), или даже пересобранная имеющаяся (например, в отделе карго или инженеров) получает доступ почти ко всем камерам. Если тоснее, к тому же набору, что консоль на мостике или в бриге. Даже, если до разборки были видны только камеры в отделе. Достаточно просто отверткой открутить экран и прикрутить его обратно.

**Comment by KatoMarika** [comment]
Такое же наблюдается и у мониторов для наблюдения за тандером.

**Comment by Djekke** [comment]
Да, там при сборке не наследуется нетворк с платы.

**Comment by Chip11-n** [comment]
Чинили
