### ISSUE TITLE
 Gas cooling system охлаждает газы очень медленно.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1807]
#### Подробное описание проблемы
 Gas cooling system охлаждает газы очень медленно. Крио не может нормально заработать очень-очень долго.
#### Что должно было произойти
Охладитель должен быть быстрее в разы.
#### Что произошло на самом деле
Клоны проводят пол часа в крио в начале раунда

**Comment by P-20** [comment]
Так это и должно быть. Хочешь быстрее - молись богу РнД чтобы охладитель улучшили.
Не баг.

**Comment by Avatar4** [comment]
Крио охлаждалось больше ЧАСА! Это определенно баг и его надо фиксить. Или назад атмос менять.

**Comment by Dennok** [comment]
Или к крио канистру сразу охлажденную намаппить.
