### ISSUE TITLE
Дионам удобней в ботинках чем без

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#1808]
Подробное описание проблемы
 
Дионы в ботинках передвигаются быстрее чем без них. Если посмотреть на спрайт, заметно что ноги дион очень "абстрактны", и ветки уходят повсюду, запхнувши всё это в ботинок, дионе казалось-бы должно быть сложнее передвигаться.

Что должно было произойти

Диона без ботинок должна двигаться быстрее(Как к примеру Унатхи, Таяры(Вроде как)).

Что произошло на самом деле

Диона без ботинок двигается медленее.

**Comment by WallShrabnic** [comment]
Не по форме. А так, спорно, ждём комментариев ксеновизора

**Comment by LudwigVonChesterfield** [comment]
Изменил так, что-бы было по форме.

**Comment by SpaiR** [comment]
@sovok4

**Comment by Skippeer12** [comment]
Закрываем или делаем пропозал.
