### ISSUE TITLE
Дионы не могут в Сол

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#1809]
Подробное описание проблемы

Нимфы, накусавшие достаточно людей что-бы понять Всеобщий не могут понять Сол? Если эта проблема касается "баланса", так и ответьте пожалуйста.

Что должно было произойти

Дионы должны понимать Сол

Что произошло на самом деле

Дионы не понимают Сол

**Comment by WallShrabnic** [comment]
Нимфы понимают Сол, по крайней мере раньше

**Comment by LudwigVonChesterfield** [comment]
Нимфы - да, Энты - нет.

**Comment by Skippeer12** [comment]
Сол коммон это стандартный-общий язык людей из солнечной системы, дионам его незачем понимать как и остальным ксеносам.

**Comment by YulianR** [comment]
Имеется ввиду, что нимфы, пожирая кровь ящера, например, начинают понимать ящерский язык, а сожрав кровь человека - сол не понимают, видимо.

**Comment by LudwigVonChesterfield** [comment]
Вот-вот.

**Comment by Skippeer12** [comment]
#2117
