### ISSUE TITLE
Выпилить с карты трубы для тел (из морга и роботики)

### ISSUE THREAD

**Issue by Lexakr** [TauCetiStation/TauCetiClassic#1810]
#### Подробное описание проблемы
Выпилить с карты трубы для тел (из морга и роботики)
#### Что должно было произойти
Трупы в мешках ломают себе кости и получают увечья, поэтому смывать их в пневмотрубы нецелесообразно, как и наличие этих труб

**Comment by WallShrabnic** [comment]
И смысл? Зачастую бросают трупы без мозга, или клонированные, так что это особой погоды не делает. А вообще, благодарите кодеров за эти фичи

**Comment by Lexakr** [comment]
Ну это бред, бросать трупы и калечить их...

**Comment by Zmey25** [comment]
А вдруг трупы напишут в профсоюз имени М.Джексона? Нт на такое пойти не может.

**Comment by Tolerantboy** [comment]
В эти трубы смывают трупы, которые уже прошли аутопсию и уже насрать в каком они виде, хоть в виде фарша. 
Если тебе не пофиг на состояние трупа, то ingame напиши завещание, чтобы твое тело в цельном (если оно таковым было на момент смерти) состоянии отпели в церкви и захоронили

**Comment by KatoMarika** [comment]
Категорически против, попытайтесь вспомнить роботехнику которая была до ввода этих труб. В лучшем случае трупы складировались там же. В худшем была примерно такая картина(Только трупов больше): 
![rzmd97h](https://user-images.githubusercontent.com/18484142/30622740-3a55f460-9dbc-11e7-83b3-1809a2b79306.png)

**Comment by volas** [comment]
#фича
