### ISSUE TITLE
Дроны не могут ползать по вентиляции.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#1823]
#### Подробное описание проблемы
Дроны не могут ползать по вентиляции.
#### Что должно было произойти
Дрон должен был залезть в вентиляцию после альтклика.
#### Что произошло на самом деле
Дрон не залез в вентиляцию после альтклика.
#### Как повторить
Попробовать залезть за дрона в вентиляцию.

**Comment by Zmey25** [comment]
А он раньше мог? У него есть тег для мусорки, вот его способ перемещения по станции.

**Comment by wadangel** [comment]
Да, мог. Никто тегами для мусорки и не пользовался - это слишком долго. А вентиляция - это быстрый и тихий способ перемещения. Не мешаешь экипажу, да и между отсеками с разным давлением/температурой удобно ползать, не нарушая атмосферы.
