### ISSUE TITLE
Из сломанного АПЦ нельзя вытащить батарею (и как следствие разобрать)

### ISSUE THREAD

**Issue by Heroman3003** [TauCetiStation/TauCetiClassic#1831]
#### Подробное описание проблемы
Если АПЦ уничтожен взрывом или водой, то после сноса крышки нельзя вытащить батарею и продолжить его разбирать
#### Что должно было произойти
Батарея должна вытаскиваться
#### Что произошло на самом деле
Батарея не вытаскивается
#### Как повторить
Попытатся вытащить батарею из сломанного АПЦ со снесенной крышкой
#### Дополнительная информация:
С разбором сломанных АПЦ похоже это не единственная проблема, нужно копать глубже

**Comment by Avatar4** [comment]
После того как апц ломалось из него пропадает батарейка. Ты хорошо пробовал ее разбирать просто инструментами?

**Comment by Lexakr** [comment]
Никакой инструмент не прокает

**Comment by WallShrabnic** [comment]
Перед созданием ишью, убедитесь в отсутствии дубликатов
https://github.com/TauCetiStation/TauCetiClassic/issues/275

**Comment by Heroman3003** [comment]
У ишью суть разная. У тех суть в том, что у не-уничтоженного нельзя снести крышку силой. Суть моего что даже у уничтоженного после снятия крышки разбор невозможен.

**Comment by Belfogor** [comment]
Там АПЦ бывают частично уничтожены. Такой АПЦ нужно сломать окончательно. Закликать его чем-нибудь. Сам сталкивался с таким траблом.
