### ISSUE TITLE
нет доступа форонщикам в космос.

### ISSUE THREAD

**Issue by Yel1** [TauCetiStation/TauCetiClassic#1835]
Форонщики часто косячат с бомбами, а т.к. это не шутки, а сраные самые мощные бомбы в игре. Надо бы дать доступ форонщикам из техов на полигон испытаний.
Подробнее на фотке http://picsee.net/upload/2017-09-24/b75b16086c08.png

**Comment by igigin** [comment]
У них там слив есть, доступ в спесс им не нужен.
