### ISSUE TITLE
Всевидящий пИИ в шкафах.

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#184]
Originally reported by: **Фаря . (Bitbucket: [FiregunnZ](http://bitbucket.org/FiregunnZ), GitHub: Unknown)**

---

Находящийся в закрытом шкафу пИИ видит все вокруг без каких либо ограничений, словно шкафчика не существует.

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/184

**Comment by RichardJones1** [comment]
Да

**Comment by KuzyXD** [comment]
Игрокам тоскливо будет играть за пИИшку, если он не будет ничего видеть. Тут нужен логичный реворк всего пИИ. Потому сейчас эта ишью — фича.

**Comment by KuzyXD** [comment]
Я уже работал над этой темой и большинство "крестных отцов" ТауКиты говорят, что пусть останется как есть. Уберите это.
