### ISSUE TITLE
Канистры не позволяют уменьшать давление.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1840]
#### Подробное описание проблемы
Работал форонщиком. Все канистры до единой не позволяли уменьшить давление а только максили его.
#### Что должно было произойти
Должна быть возможность делать давление меньше
#### Что произошло на самом деле
Можно только максимальное давление использовать.

**Comment by ZVee** [comment]
На канистрах выставляется такое давление, которое будет соответствовать внешнему. Если стоит 101 - значит как только снаружи давление будет 101 и выше - канистра перестанет выпускать газ, если стоит 202 - значит не позволит выпустить 202 и выше. Если в этом проблема - то так и со старыми было и всегда.

**Comment by Avatar4** [comment]
То есть, если я захочу теперь в балон накачать не все что есть в канистре а только половину от канистры, то придется откачивать часть газа в канистре? Раньше можно было же поставить давление меньше и выпускать газ медленнее.

**Comment by ZVee** [comment]
>если я захочу теперь в балон накачать не все что есть в канистре а только половину от канистры, то придется откачивать часть газа в канистре?

~Половину от канистры и в баллон? Погоди, а это как? Насколько я помню тему с баллонами (да те же фороновые танки для синги) она была так - мы вставляли в канистру баллон, выставляли на канистре Х давление и баллон наполнялся до отметки этого Х, т.е ставя скажем 500, в баллоне будет 500, ставили максимум, в баллоне было 1013.~

Стоп, вот я счас начал тестить, и только тогда понял, что речь про работу с интерфейсом ,что там не работает уменьшение давления.. Ну тут не знаю чей фэйл, но все же наверно стоило уточнить, что речь про работу интерфейса или приложить скрин...

**Comment by Avatar4** [comment]
Сорян, я думал ты меня понял.
