### ISSUE TITLE
Трубы в отсеке исследовании форона слишком хрупкие.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1841]
#### Подробное описание проблемы
При перекачке газа около 10к температуры по Цельсию, трубы взрываются.
#### Что должно было произойти
Трубы в отсеке форона должны быть более живучими.
#### Что произошло на самом деле
Они взорвались.
#### Как повторить
Смешать две канистры кислорода с канистрой форона, запустить одну из смешанных канистр в печь, поджечь. Затем на обратном выходе поставить пустую канистру и врубить вентиль. Все насосы поставить на максимум.

**Comment by ZVee** [comment]
>При перекачке газа около 10к температуры по Цельсию, трубы взрываются.

Трубы не от температуры взрываются, а при достижении 17+к давления. Можно в принципе замапить топливные, они держат 36к.

**Comment by Avatar4** [comment]
Аа, ясно. Просто сразу выставил давление на передачу 15к сразу.
