### ISSUE TITLE
Бутылка космопива за сервис-борга разбивается окончательно.

### ISSUE THREAD

**Issue by LLIkolnik** [TauCetiStation/TauCetiClassic#1854]

**Comment by DeadOberst** [comment]
Вообще это касается все сломанных модулей, например шприца или флешки.

**Comment by omejka** [comment]
приходите к роботитсу,меняете модуль на тот же самый

**Comment by LLIkolnik** [comment]
Омежка, это РПшно что пиздец.

**Comment by Forrya** [comment]
А борг с самочинящийся бутылкой еще более "рпшный" чем борг чинящийся у робототеха?

**Comment by LLIkolnik** [comment]
Я прошу не самопочинку, а либо не ломающаяся вообще, либо чинящаяся при подзарядке (как ресурсы у инжборга).

**Comment by KatoMarika** [comment]
Если будет впилен #1852, то будет неактуально.

**Comment by Skippeer12** [comment]
Сервис борг это один большой баг. Выпилить! ~~А ещё боргов бюрократов~~

**Comment by volas** [comment]
Так понимаю, в некотором роде решено через #1852 
Если есть еще модули, которые могут сломаться, пишите.
