### ISSUE TITLE
Пинпойтер карго не работает

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1855]
#### Подробное описание проблемы
Пинпойтер карго не может быть настроен ни на одну сигнатуру включая диск.
#### Что должно было произойти
Пинпойтер должен работать как стационарный в кэпской
#### Что произошло на самом деле
Выскакивает сообщение что ничего не работает.
#### Как повторить
Заказать пинпойтер в карго и проверить

**Comment by Raschert0** [comment]
Не баг. Это пинпоинтер для режима мутини
