### ISSUE TITLE
Белый космос.

### ISSUE THREAD

**Issue by KiPakr** [TauCetiStation/TauCetiClassic#1857]
#### Подробное описание проблемы
Космос теперь белый https://prnt.sc/gsmtup
#### Что должно было произойти
Космос должен быть нормальным
#### Что произошло на самом деле
Космос белый.
#### Как повторить
Посмотрите на космос.

**Comment by P-20** [comment]
@KiPakr Нужно почистить Кэш, в параметрах бьенда включить использование графического ПО.
Поставить бета-версию бьенда, зайти на сервер.

**Comment by Leshiy-ART** [comment]
Проблема со стороны клиента.

**Comment by Skippeer12** [comment]
Это происходит когда вы запускаете другие игры не выключая клиент ССки.
После того как поиграл в другую игру, будь добр, перезапусти клиент ССки.

**Comment by volas** [comment]
Не является серверной проблемой, лучше если что писать на форуме http://tauceti.ru/forums/index.php?board=86.0
