### ISSUE TITLE
Не появляются твари в отсеке при случайном ивенте.

### ISSUE THREAD

**Issue by Leshiy-ART** [TauCetiStation/TauCetiClassic#1858]
#### Подробное описание проблемы
Central Command Update
Vermin infestation
Bioscans indicate that spiders have been breeding in technical storage. Clear them out, before this starts to affect productivity.

При случайном ивенте не спавнятся мыши/ящерки/пауки.

#### Что должно было произойти
Должны были заполонить отсек

**Comment by P-20** [comment]
Не помню чтобы у нас должны были спавниться мыши, и ящерки. Но пауки стабильно спавнятся при рандом ивенте. Происходит спавн маленьких пауков, которые через некоторое время взрослеют. Просто нужно подождать.

**Comment by Leshiy-ART** [comment]
При этом оповещении животины должны заспавниться в конкретном отсеке. При мышах или ящерках - заменяет "that spiders have been breeding" на соответствующее. Раньше работало, но с каким-то обновлением сломали.

**Comment by Leshiy-ART** [comment]
Да. Ящерки и мышки не спавнятся до сих пор.
