### ISSUE TITLE
Модуль учёного у боргов.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1861]
#### Подробное описание проблемы
Модуль ученого на борге абсолютно бесполезный. Данный киборг не умеет ни в одну из работ рнд. Поясняю:
1) Для ксенобиологии не хватает рук что бы положить слайма куда-нибудь и вырезать ядро (плюс спрятать ядро в холодильник, измельчить обезьяну и тд.)
2) Для токсинов так же не хватает рук что бы манипулировать маленькими канистрами. А так же киборги не могут открывать большие.
3) Для ксеноархеологии не хватает худа. Может что-нибудь еще.
4) Для телесайнса не хватает gps.
#### Что должно было произойти
Борг должен иметь худ для раскопок, возможность манипулировать слаймами, иметь gps.
#### Что произошло на самом деле
Он полностью бесполезен.
#### Как повторить
Зайти за ученого киборга.
#### Дополнительная информация:
http://prntscr.com/gsw19n

**Comment by omejka** [comment]
борг=\=человек,в этом смысл
ты не должен уметь все

**Comment by Leshiy-ART** [comment]
Этому модулю нужна возможность вырезать мозги людишек и собирать боргов.
Или просто собирать боргов, так как мозги может медборг вырезать.

**Comment by omejka** [comment]
^норм тема,дать взломанному боргу MMI

**Comment by DeadOberst** [comment]
Мне всегда казалось, что специализированный борг должен полностью заменять человека.
Вот на бее научный может исследовать в РнД, таскать ресурсы, открывать и закрывать крышки корпуса, специальным захватом брать батарейки, провода, платы и части мехов и роботов, позитронку и ММИ. В смену законов не может специальным протоколом безопасности. 
Взломанному можно добавить хват для мозгов.

**Comment by Zmey25** [comment]
Было бы классно, если бы киборги смогли бы самовоспроизводиться. При малфе заставили бы людей копать на шахтах и сделали бы станцию синтетов.

**Comment by WallShrabnic** [comment]
> Мне всегда казалось, что специализированный борг должен полностью заменять человека

Как раз не должен. Тем более научный Борг не узкоспециализирован

**Comment by Avatar4** [comment]
> ты не должен уметь все
Я здесь говорю о том что борг не способен делать банальных вещей связанных с его модулем а не ору "ААА ДАЙТЕ КИБОРГАМ РУКИ"

**Comment by Skippeer12** [comment]
Играя не за щиткурити борга ты должен понимать, что подписываешь себе путевку в батхерленд.
Ты будешь ненавидить не только ваншоты с лазура, ЭМИ но и беспомощность, связанную с тем что борг =/= человек.
Такие банальные вещи как, открыть двери без электичества, налить пива в бокал, провести операцию на бесознательном человеке без помощи хуманов, закрыть ящик на котором есть система доступов превращаются в ад.

**Comment by Forrya** [comment]
Лол, всегда считалось, что борги должны не заменять людей, а помогать им.

**Comment by T6751** [comment]
Можно считать решенным, благодаря https://github.com/TauCetiStation/TauCetiClassic/pull/6318 https://github.com/TauCetiStation/TauCetiClassic/pull/6481
