### ISSUE TITLE
Диона с лёгкими

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#1865]
**Подробное описание проблемы**
После пробития трейтором "лёгких" Дионе, начал задыхаться и кашлять кровью.
**Что должно было произойти:** 
Дионы не должны задыхаться в принципе, у растений ведь дыхание по-другому работает.
**Что произошло на самом деле:**
Диона задыхалась и кашляла кровью(???).
**Как повторить:**
Есвордом дионе в печень.
**Дополнительная информация:**
Готов признать что если и это впилить, то может быть проблема баланса, но пусть мне хоть так и скажут.

**Comment by 241214234343** [comment]
если и это впилить, то может быть проблема баланса

**Comment by LudwigVonChesterfield** [comment]
Что-же, вопрос впринципе снят. Но из этого же разряда(Не знаю стоит ли пилить ещё один реквест), эмоуты криков дионы от боли. Если их убрать, то можно чуть забалансить(Типо никто не прибежит на крики дионы, если их нет), да и РоПэшней будет, растения то боли не чувствуют(Что уже реализовано. но эмоуты всеравно есть).

**Comment by Tolerantboy** [comment]
СПУ тоже могут повредить "легкие" (что?) и кричат от боли, кстати. А, ну и еще кашляют кровью. СПУ. Кровью. И кричат. От боли. Синтетические организмы. Роботы.

**Comment by Forrya** [comment]
А еще у спу брейндамаг бывает.

**Comment by LudwigVonChesterfield** [comment]
Брейндамаг объясняется поломкой процессоров, или какая-то такая техно-ересь, не?

**Comment by omejka** [comment]
Просто спу это гнойный респрайт человека и ничего не меняется уже пару лет на нашем билде
