### ISSUE TITLE
ИИ не может включить АПЦ в ядре обратно

### ISSUE THREAD

**Issue by Zap-zapper** [TauCetiStation/TauCetiClassic#1866]
#### Подробное описание проблемы
Когда я зашёл за ИИ - у меня не было питания. ИИ взломал АПЦ, но я не мог нажимать на кнопки.
#### Что должно было произойти
Я должен был нажать кнопку On и включиться
#### Что произошло на самом деле
Ничего
#### Как повторить
Вырубите АПЦ на сателлите за ИИ.

**Comment by P-20** [comment]
Даже если АПЦ выключен, через какое-то время пойдет процесс автоматического взлома АПЦ, и АПЦ автоматически включается, если в нем нет энергии, поэтому и на кнопки не понажимаешь. Вообщем все странно, звучит, и слишком мало информации.
