### ISSUE TITLE
[Bug] Проблема со сканером, которая ломает механ.

### ISSUE THREAD

**Issue by DarkSauron71** [TauCetiStation/TauCetiClassic#1868]
#### Подробное описание проблемы
Когда ты сканером сканируешь открытый объект (шкаф), то предмет в руке кладётся внутрь, но отпечатки не снимаются, и приходится закрывать шкаф, оставляя свои ОТПЕЧАТКИ.
#### Что должно было произойти
Сканер должен был снять отпечатки с открытого шкафчика.
#### Что произошло на самом деле
Сканер из руки кладётся в открытый шкаф.
#### Как повторить
Взять в руки сканер и попытаться снять отпечатки с открытого объекта (шкаф, холодильник)
#### Дополнительная информация:
Было бы хорошо сделать сканирование объектов с зажатой клавишой shift :blush: 
Иначе, любой тритор украв вещь из шкафчика, может оставить его открытым, дабы не нашли его отпечатки пальцев.

**Comment by ZVee** [comment]
>приходится закрывать шкаф, оставляя свои ОТПЕЧАТКИ.

Это никак не влияет, потому что сканнер ловит вообще все отпечатки которые есть и может хранить их неограниченное кол.во и потом эта информация анализируется уже в консоли. И если на шкафе после закрытия только твои - значит никаких других и не было.

**Comment by DarkSauron71** [comment]
Ясно, спасибо.

**Comment by ZVee** [comment]
Сама идея с шифтом или еще каким вариантом все равно хорошая, потому что бывает проблема про сканировать те или иные вещи, которые конфликтуют с "атакой" сканера по чему либо.
Еще можно сделать чтобы сканер имел режим выключения, а при включенном - его нельзя никуда ни положить ни еще что сделать и сканирование имело бы приоритет над любым другим действием.
