### ISSUE TITLE
Шедоулинги.

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#187]
Originally reported by: **HAKCA (Bitbucket: [HAKCA](http://bitbucket.org/HAKCA), GitHub: [HAKCA](http://github.com/HAKCA))**

---

После перезахода в игру, будучи шедоулингом или послушником, исчезают иконки у твоих товарищей. Не понять, кто свой, а кто нет.

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/187

**Comment by skvazarb** [comment]
Неактуально, исправлено в https://github.com/TauCetiStation/TauCetiClassic/commit/6869f402c02ce5e738dc6504560ab5e23f34f1ab.
