### ISSUE TITLE
Инженерная каска не защищает.

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1871]
#### Подробное описание проблемы
Инженерная каска не защищает владельца.
#### Что должно было произойти
Инженерная каска должна защищать голову того, кто ее надел. 
#### Что произошло на самом деле
Мне в голову влетела труба. Труба сломала череп, кровища хлестала, чуть не умер.
#### Как повторить
Надеть каску, слегка нарушить ТБ

**Comment by Avatar4** [comment]
А ты уверен что она тебе влетела не в рот? Слот рта вроде не защищен без стеклышка.

**Comment by Uvash** [comment]
Насколько я помню, тут все удары в глаза/рот перенаправлялись в голову.

**Comment by Forrya** [comment]
Вообще то я там не деднулся. 
ПО РАЛИПЛЕЮ))0) я нагнулся встав раком либо встав на колени и уже так ее откручивая с полу. И она разумеется должна или мне туда где каска пролететь, либо можду ног.

**Comment by ZVee** [comment]
У нас космонавты не умеют моргать и задерживать дыхание, а ты про какой-то там ролеплей. А то тогда при разрезании стены и получении ослепления можно говорить - "я ролеплейно закрыл глаза чтобы не ослепнуть, но меня загрифонил механ!! Пофиксите!!"

А вообще надо глянуть сколько там у каски защиты от мили и может слегка поднять, но надо учитывать с какой скоростью и силой эта труба еще влетела, возможно там апай не апай - а в тебя условно танк выстрелил трубой.

**Comment by Forrya** [comment]
Ну так хотя бы не перелом. А то мне сломало голову, кровища хлестала. А лицо - цело. То есть опять же, попало туда где голову защищает, и либо отрикошетить от каски должна была бы труба, или мимо пролететь.

**Comment by ZVee** [comment]
У нас если промахи не выпилили - то она бы и пролетела мимо тебя даже не задев, еслиб сработал рандом на то, что твой космонавт сам увернулся, в противном случае считается что тебя приложило со всей дури взяв за основу, что условно ты мало того что не увернулся, так еще и получил серьезно по здоровью.

А рикошета у нас нет (кроме аблативки в отношении лазеров) - либо влетело, либо не влетело ну и +- еще понижение урона в зависимости от защищенности там, куда попал урон. Броня у нас в процентах - поэтому если на ней написано 30 - значит она снижает 30%, а если урон от удара вышел скажем там 150 - то даже с вычитом 30-ти, это все равно хватит и на перелом и даже на вероятную потерю головы или еще чего.

Просто не учитываешь что у нас система урона простая, и не будет тебе никаких "хотяб не перелом", это или надо бафать защиту каски от мили до заоболачных там процентов 80, нерфя при этом все или не трогать. Броски у нас обычно от отлетевших предметов имеют некислую силу урона и какой-то там опять же особенной формулы типа веса предмета, его дистанции полета и т.д. и потом там на основе этих данных мы высчитаем урон - скорее всего нет.

Так что я не уверен что это вообще исправимо простым методом, не пересмотрев вообще всю формулу летающих предметов и потом половины билда, чтобы добавить не хватающие им переменные. Но возможно все проще, это чисто предположение в первую очередь.

**Comment by Forrya** [comment]
Каску апнут, или можно закрывать?

**Comment by ZVee** [comment]
Ну только если кто-то возьмет и будет делать. Я просто расписал самый общий вариант почему оно так.
Я же тут не писал ничего про то, что это нельзя переделывать или еще что. Просто было настроение разжевать.

**Comment by Sakuya-Izayoi** [comment]
Каска должна защищать максимум в падающего потолка, но не от трубы под давлением.

**Comment by RichardJones1** [comment]
Надо глянуть защиту каски и мб апнуть

**Comment by pss88** [comment]
armor = list(melee = 30, bullet = 5, laser = 20,energy = 10, bomb = 20, bio = 10, rad = 20)
