### ISSUE TITLE
Проблема со сборкой/разборкой машинерии

### ISSUE THREAD

**Issue by Zap-zapper** [TauCetiStation/TauCetiClassic#1872]
#### Подробное описание проблемы
Когда я собирал СМЕС, он у меня потребовал пять аккумуляторов, один конденсатор и один моток кабеля. Моток кабеля мне не удалось вставить в машину - говорила что "You can't add this to the machine". Несмотря на это, она собралась как только я закрутил всё отвёрткой, несмотря на то что кабель не был добавлен. При разборе, из неё выпали 5 кусочков кабеля. То есть так можно дюпать кабеля.

#### Что должно было произойти
Я должен был смочь вставить туда кабель
#### Что произошло на самом деле
Кабель я вставить не смог, машина собралась без него, при разборе дюпнулись кабеля.
#### Как повторить
Собрать/разобрать СМЕС
#### Дополнительная информация:
Подобная проблема у консоли телепорта. Если её соберёшь и разберёшь, то из неё выпадут её три кристалла. Но вставить сможешь лишь один, ибо "There are not enough ports". При этом, сначала раунда там три кристалла.

**Comment by P-20** [comment]
Ты сам проверяй сперва, чтобы не вводить в заблуждение людей. Все проверил, без проводов никак нельзя собрать смес, а "You can't add this to the machine" потому как ты уже вставил кабель. Про консоль телепорта, в ней нет кристалов, они в хабе. А если ты про консоль телесаенса, то там есть данная проблема.
