### ISSUE TITLE
Бипски унижает синдиборга

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1874]
#### Подробное описание проблемы
Синдиборг был застанен бипски
#### Что должно было произойти
Синдиборг на изи должен разнести бипски.
#### Что произошло на самом деле
Ю хев бин станед бай бипски на пол минуты.
#### Как повторить
Ударить бипски есвордом.

**Comment by DeadOberst** [comment]
Станционные борги вообще никак не могут нанести вред синдиборгу. Считаю это балансом, ибо нечего грифонить станцию без поддержки отряда.

**Comment by Raschert0** [comment]
Да ну? Вполне себе забивал нюкоборга батоном
