### ISSUE TITLE
Костер ущемляет права обычных игроков, но не животных.

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1875]
#### Подробное описание проблемы
Животные не загораются на костре.
#### Что должно было произойти
На костре гореть должны все.
#### Что произошло на самом деле
Животным, например лисам и котам пофигу на костер.
#### Как повторить
Вселиться в лису/кота и пройтись по горящему костру.
#### Дополнительная информация:
А люди-то горят!

**Comment by Lancer411** [comment]
У нас древнейший механ горения мобов, которому подвержены только люди. Так что да, баг.

**Comment by LudwigVonChesterfield** [comment]
Загораются.
