### ISSUE TITLE
Лип воксов грабает боргов

### ISSUE THREAD

**Issue by SkLepP** [TauCetiStation/TauCetiClassic#1876]
#### Подробное описание проблемы
Лип Воксов может хватать боргов

#### Что должно было произойти
Лип Воксов не должен грабать воксов
#### Что произошло на самом деле
Способность воксов грабает боргов
#### Как повторить
Использовать способность воксов на борге

**Comment by omejka** [comment]
Это фича,если их спотом еще и задушить можно,то это точно фича
