### ISSUE TITLE
Превращения дверей.

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#188]
Originally reported by: **Anonymous**

----------------------------------------

Если поставить большую двутайловую дверь, а потом покрасить ее в какой-либо цвет - она превратится в маленькую, однотайловую.

----------------------------------------
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/188

**Comment by SpaiR** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/441
