### ISSUE TITLE
Проблема с падающими предметами.

### ISSUE THREAD

**Issue by DctrMM** [TauCetiStation/TauCetiClassic#1893]
#### Подробное описание проблемы
Предметы которые падают сверху(к примеру тот же мусор) гибали людей.
#### Что должно было произойти
Экран должен был трястись, персонажа под этим предметом должно было гибнуть.
#### Что произошло на самом деле
Экран не трясется, персонаж живой.
#### Как повторить
Взять, подойти к мусорному маяку и вызвать мусор к примеру. Можно через спавн проверить еще.
#### Дополнительная информация:
А теперь еще под мусором ходить можно, и ты как-бы снизу мусора. Даже через крупные кучи.

**Comment by P-20** [comment]
@Lancer411

**Comment by volas** [comment]
Скорее всего связанно с недавним атом_инит

**Comment by Raschert0** [comment]
Пофикшено #1898
