### ISSUE TITLE
Предметы, которые должны быть у игрока в руке при лейтджоине, не прописываются правильно в переменную руки.

### ISSUE THREAD

**Issue by Raschert0** [TauCetiStation/TauCetiClassic#1900]
#### Подробное описание проблемы
![default](https://user-images.githubusercontent.com/11941910/31587250-26465598-b1e7-11e7-99ac-7441dfdde41f.png)
У игрока l_hand=null, но аптечка отображается в левой руке в худе (не отображается на спрайте). Сама по себе при этом она находится в контентсах игрока.
#### Что должно было произойти
r_hand должен был прописаться нормально
#### Как повторить
Понятия не имею. Скорее всего, взять медсестру и попробовать зайти через лейтджоин (не деклерится, а после старта раунда зайти через join game).
#### Дополнительная информация:
Возможно, этот баг больше не повторится, но, я думаю, оставить ишью с ним здесь всё-таки нужно

**Comment by DctrMM** [comment]
Не только предметы лейтджоина, но и вроде как шмотки триторов из аплинка.
