### ISSUE TITLE
TEG отсутствует в заказах карго.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#1905]
#### Подробное описание проблемы
TEG отсутствует в заказах карго.
#### Что должно было произойти
Он должен там быть
#### Что произошло на самом деле
Его нет
#### Как повторить
Посмотреть в заказах карго.
#### Дополнительная информация:
Либо я слепой, либо его там действительно нет

![](https://i.imgur.com/5ixYLqx.png)

**Comment by Lancer411** [comment]
Выпилен при обновлении атмоса.

**Comment by Skippeer12** [comment]
*clap
Зато впилили Раст.
Аплодирую стоя.

**Comment by Raschert0** [comment]
Юзай коллекторы, Люк

**Comment by Skippeer12** [comment]
Отлично, добавили Раст, который нагревает плазму без пожара @ Юзай коллекторы, которые для синги.

**Comment by Raschert0** [comment]
Хм, не, нифига, оно не взаимодействует с коллекторами. Спроси лучше у Зве

**Comment by ZVee** [comment]
Тег выпилен потому что и не работал и фиксить конечно наверно его никто не будет. Коллекторы расту не нужны, реакция с плазмой происходит внутри самого раста, а не снаружи, о каких пожарах речь?

**Comment by Skippeer12** [comment]
Если смотреть зарубежные гайдики, то там он нагревает плазму, которая в свою очередь выкачивается из камеры и идет в ТЕГ.

А как я видел (по скринам) никто так и не понял, что Такомаку нужна плазма, а не воздух для работы, его запускают для личной ачивки. (сколько надо задонатить, чтобы ты пофиксил ТЕГ?)

**Comment by ZVee** [comment]
Токамак это раст, для работы ему не нужна плазма (не пойми неправильно), он ее сам синтезирует в себе когда в него инжектят вещества из топливных стержней.

А причем тут тег и токомак в одном смысле - я не совсем понимаю. Две разные вообще стихии никак не связанные друг с другом.

**Comment by Skippeer12** [comment]
https://www.youtube.com/watch?v=4oXsusx2mn4
(смотреть с 13 минуты)

Вот я тут это углядел.

**Comment by ZVee** [comment]
ВГ-шный скорее всего иной (возможно конечно у нас тоже так можно). у нас инжекторы используются, а там на видео их как раз нету. Наш - это взят с бея, с их торча. И у них тоже тег не используется в комбе с растом.

**Comment by Skippeer12** [comment]
Если ты про топливный инжектор, то он там есть, стоит у консолей.
![image](https://user-images.githubusercontent.com/18488106/31632351-4b7ade0e-b2c5-11e7-8f50-87dd75aa6c72.png)
