### ISSUE TITLE
Пожар, вызванный в следствие поджога топлива, работает некорректно. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#1906]
#### Подробное описание проблемы
Во первых. Пожар не повышает температуру в помещение. Во вторых. Теперь невозможно поджечь лужу разлитого топлива.  Топливо моментально тухнет. 

Я так и не понял как на в данном случае удалось химику удалось зажечь пол брига. Достоверно известно, что использовал он классическую гранату с топливом, а вот повторить его фоукус не удалось. Граната в данном случае была брошена в общем холле брига, где-то около голопада. 
Мало того что топливо проникло сквозь стены, оно еще и не тухло, бесконечно горело, но наносило урон огнем людям находящимся на тайле с пожаром. Потушить удалось лишь огнетушителем, но тухнув, топливо резко понижало температуру окружающей среды. 
![123](https://user-images.githubusercontent.com/12851693/31616996-4691d9d6-b29f-11e7-9b4c-860ba5c49e90.PNG)

Проблемы начались после последнего апдейта, если я не ошибаюсь. 

#### Дополнительная информация:
@ZVee

**Comment by Kernstall** [comment]
Как хорошо, что именно этот химик зашел сюда, иначе вы все сломали бы (или нет). Граната была наполнена напалмом, а не топливом, не знаю откуда у тебя такая инфа. И да, напалм оказался сломан и делал такую штуку в трех случаях из 3.
