### ISSUE TITLE
Копья не собираются.

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1908]
Копья перестали собираться. Зачем мне фича с головой на копье, если я не могу собрать копье?
Перепробованы были все комбинации. Копье собираться отказывалось.

**Comment by Skippeer12** [comment]
Вам же портировали крафт с ТГ, там всё есть. ( но может и нет )

**Comment by Forrya** [comment]
Блин че за тупая система крафта, удолите и верните как было, я не умею в нее. Там даже списка рецептов нет.

**Comment by Skippeer12** [comment]
Берешь в руки вещи для крафта в руки и кликаешь на меню, прокручиваешь его и там всё будет.

**Comment by ZVee** [comment]
>Там даже списка рецептов нет.

Он есть, но включается через Воласа. А по дефолту да, видимость рецептов отключена, если нет ресурсов требуемых для того или иного рецепта. Просто до введения этого меню, тоже нигде не было видно рецепты в игре и надо было или в код лезть, или на вики.

**Comment by Forrya** [comment]
Из за обоссаной системы ТГ-крафта все делать сложнее и непонятнее, но все еще возможно.
