### ISSUE TITLE
[PROPOSAL] Неудобства

### ISSUE THREAD

**Issue by lustiwe** [TauCetiStation/TauCetiClassic#1909]
#### Подробное описание проблемы
При клике в игре на Changelog и дальнейшем клике на «Показать легенду» у метки с удалением и откатом написано "фичь". А ещё при переходе по ссылкам открывается Microsoft Exporer или Edge, а не браузер, установленный по умолчанию.

#### Что должно было произойти
Не должно быть "фичь".
Не должен открывать Explorer или Edge.

#### Что произошло на самом деле
фичь
Explorer или Edge
#### Как повторить
При клике в игре на Changelog и дальнейшем клике на «Показать легенду» у метки с удалением и откатом написано "фичь". А ещё при переходе по ссылкам открывается Microsoft Exporer или Edge, а не браузер, установленный по умолчанию.

#### Дополнительная информация:
ФИЧЬ, серьёзно? Фич же.

**Comment by SpaiR** [comment]
Ещё добавлю. Заголовок "Неудобство" не даёт никакой информации. Имеется ввиду твоё личное неудобство от сидения на стуле? Или неудобство от чтения предложений начинающихся с "ВАЖНО:..."? Ну так такие репорты только к тебе и относятся.

**Comment by volas** [comment]
Решение с ИЕ только одно - удали ИЕ.

**Comment by lustiwe** [comment]
Всем спасибо за помощь.
