### ISSUE TITLE
Протезы перестали отлетать от эми.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1915]
#### Подробное описание проблемы
Протезы у человека перестали отлетать от воздействия эми при сильном уроне на конечность.
#### Что должно было произойти
Все протезы должны отлетать от эми если они сильно повреждены
#### Что произошло на самом деле
Протезы не отлетают.
#### Как повторить
Сделать хумана с протезами, использовать эми гранаты.

**Comment by Forrya** [comment]
А они и не отлетают. Лишь перегорают что ими пользоваться нельзя, и если ты без посторонней помощи себя починишь - чудо.

**Comment by Belfogor** [comment]
Это не баг, а фича. Так что да. Протезы больше не отлетают, но пользоваться ими нельзя.
