### ISSUE TITLE
Взломанные малфом борги потеряли топ шмот

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1919]
#### Подробное описание проблемы
У хакнутых малфом боргов вместо крутых шмоток игрушечные есворды.
#### Что должно было произойти
Должны быть там лазеры, настоящие мечи, имбостанпалки...
#### Что произошло на самом деле
Игрушченый  есворд
#### Как повторить
Малфом хакнуть борга

**Comment by volas** [comment]
хоть на минуту быстрее, но закрою в пользу #1920 - там больше инфы
