### ISSUE TITLE
[Proposal][Bug] Overload Machine малфа - сломанное говно

### ISSUE THREAD

**Issue by Kernstall** [TauCetiStation/TauCetiClassic#1922]
1. В общем-то тут и баг и предложение в одном, просто связаны они друг с другом очень тесно
  a. Косяк в коде позволяет малфу взрывать вообще всю машинерию, от вентиляционных насосов до канистр с газом(Взорвать канистру с фороном, ммм) и совсем уже невероятных вещей. На скрине как раз взрыв насоса.
![scr01](https://user-images.githubusercontent.com/16035287/31942349-b4bfbe9e-b8cd-11e7-9f1c-bb2200d71b3d.jpg)
  б. Как способность overload machine бесполезна как раз из-за списка в тысячу наименований. Найти за достаточное время консоль и взорвать на ней глупого хумана на представляется возможным. Надо бы впилить взрыв консолей через альт+клик или другой хоткей. В общем-то могу и сам закодить оба пункта, но непонятно какую машинерию разрешить взрывать (взрывать апц - топ) и нужен совет, как проверить ии на малфа.

2. Overload machine должен быть удобным и не взрывать канистры

3. Overload machine неудобный и взрывает канистры

4. Зафорсить себе малфа в раунде

**Comment by Zmey25** [comment]
Вообще, раньше малф как раз и мог взрывать на альт клик. Не помню после чего это убрали. Может посмотри в истории.
А еще есть такое, по-моему там тоже эта фича есть, можно только её вырвать оттуда.
https://github.com/TauCetiStation/TauCetiClassic/pull/1774

**Comment by Flankir** [comment]
Насколько я помню, это убрали когда ИИ лишился альт-клика.

**Comment by Skippeer12** [comment]
Альтк+клик использовали не самым лучших образом, по этому был сбор и кодеры вынесли решения что лучше выпилить (проще выпилить чем поничить) но ничего такого. Хотели вроде запилить список только того что видит малф у себя на экране, но так этого и не случилось.

Этот образец старого малфа сам по себе сломан и не играбелен в большинстве случаев, а фичи может и работают но не корректно. Вообщем ждем пока Ращер спасет вас от этого забагованого "говна".
