### ISSUE TITLE
[Proposal]

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#1924]
#### Подробное описание проблемы
Разные профессии Scientist, Xenoarcheologist , Anomalist и Phoron Researcher объединили в одну професиию с выбором тайтла. 

#### Что должно было произойти
Профессии Scientist, Xenoarcheologist , Anomalist и Phoron Researcher должны быть разделены чтобы можно было выбрать несколько из них, так как у них разные доступ и разные цели. Это разные профессии.

#### Что произошло на самом деле
Профессии можно выбрать путём выбора тайтла у одной профессии Scientist, но нельзя выбрать несколько.

**Comment by Zmey25** [comment]
Я правильно понимаю, ты хочешь быть и археологом и форон ресерчером одновременно? Или ты имеешь ввиду, что нужно всех разделить как ксенобиолога?

**Comment by Sakuya-Izayoi** [comment]
> Я правильно понимаю, ты хочешь быть и археологом и форон ресерчером одновременно? Или ты имеешь ввиду, что нужно всех разделить как ксенобиолога?

Второе, разделить всех.

**Comment by Skippeer12** [comment]
Вместо разделения нужно их просто выпилить, а доступ оставить для всех ученых кроме ксенобиолога и робоцыса. Хочешь что бы у тебя на карте было Форон Ресерчёр? Поставь и играйся в бомбы, если после первой бомбы тебе нечего делать то ты можешь пойти аутировать в телесаенс или помочь робоцису с исследованиями.

Разделения ксеноархеолога и аномалиста вообще не понять, один копает, вротой исследует то что первый накопал, если одного из них нет то весь механизм встает, бесполезные разделения ради разделений.

Если коротко, голосую за то чтобы убрать разделения доступа, а крутые названия оставить как это сделано у ассистентов.
