### ISSUE TITLE
Тела после тройного граба не падают на пол

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1930]
#### Подробное описание проблемы
Мертвые тела которые используют для прикрытия, после того как их отпустить стоят на месте.
#### Что должно было произойти
Они должны были упасть
#### Что произошло на самом деле
Они стоят будто живые.
#### Как повторить
Схватить труп в тройной грабб и сделать интент на хелп. Возможно не сразу выйдет
#### Дополнительная информация:
http://prntscr.com/h2ee9u

**Comment by Belfogor** [comment]
Почему вообще мертвые тела можно юзать как живой щит. Как вы себе это представляете.

**Comment by Skippeer12** [comment]
Берешь значит такой тело и обхватываешь его, а другой рукой стреляешь.

Конечно в этом есть минут, твоя скорость передвижения очень страдает из-за этого.

**Comment by Raschert0** [comment]
Не удалось повторить
