### ISSUE TITLE
Неопционально мощные стекла которые на весь тайл.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1934]
#### Подробное описание проблемы
Стекла которые строятся на весь тайл, невозможно фактически разбить обычными средствами. Плюс ко всему, оно должно издавать звук битья по нему и появляться трещины.
#### Что должно было произойти
Стеклу необходимо вернуть звук удара по нему и сделать порог хп в два раза выше чем у одностороннего укрепленного стекла.
#### Что произошло на самом деле
Понадобится 1000 ударов стан-батоном по нему что бы разбить. Если это вообще возможно.
#### Как повторить
Бить балоном, стан-батоном или еще чем-нибудь по стандартному двойному стеклу на стейшоне.

**Comment by Forrya** [comment]
О нет! Двухметровое пуленепробиваемое стекло очень сложно сломать! Как же так?!

**Comment by YulianR** [comment]
Эти стекла крайне ебанутые, можно банально нажать по ним отверткой и сразу бам разгерма

**Comment by Flankir** [comment]
Стоп, народ, а речь об обычном стекле или укрепленном? Это таки две большие разницы и обычное не должно даже близко быть к укрепленному пусть даже оно на весь тайл.

**Comment by Avatar4** [comment]
Обычное стекло нельзя сделать на весь тайл, так что имелось в виду укрепленное, да.

**Comment by igigin** [comment]
>нельзя сделать на весь тайл

Тебе педали запрещают делать обычные на фуллтайл или что? (Если угрожают расправой, то намекни как-нибудь, подай сигнал там, сигнальной ракетой или как-то так).

**Comment by Skippeer12** [comment]
У цельного стекла есть порог урона от корого оно начинает ломатся. А именно 15 брута нужно, чтобы оно начало издавать звуки и давать слабину (трещину).
