### ISSUE TITLE
Не рабочая кнопка выхода в мед бее.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1941]
#### Подробное описание проблемы
Быдло-маперы сломали кнопку выхода на востоке рецепшена мед-бея.
#### Что должно было произойти
Нажатие на кнопку должно открывать двери.
#### Что произошло на самом деле
Она ничего не делает.
#### Как повторить
Нажать на кнопку на востоке выходе из мед-бея.

**Comment by Lexakr** [comment]
Пофикшено в [https://github.com/TauCetiStation/TauCetiClassic/pull/1936](url)

**Comment by Raschert0** [comment]
Указанный выше ПР смержен, проблема неактуальна.
