### ISSUE TITLE
Лавки шаттла велосити

### ISSUE THREAD

**Issue by Camper12345** [TauCetiStation/TauCetiClassic#1942]
#### Подробное описание проблемы
При прилёте шаттла велосити на станцию и, возможно, и на велосити, космонавты, пристёгнутые к лавке, прилипают на пару секунд.
#### Что должно было произойти
Космонавты должны иметь возможность встать с лавки сразу же.
#### Что произошло на самом деле
Космонавты не могут встать с лавок приблизительно секунду.
#### Как повторить
Полететь на шаттле велосити.
#### Дополнительная информация:
Сколько можно уже в шкафу летать? Неужели никто не пытался это исправить? Если это, конечно, не фича, тогда удалите.

**Comment by Lexakr** [comment]
Фича, удоляй

**Comment by Forrya** [comment]
Видимо в самолете ты еще во время посадки отстегиваешься и не дожидаясь полной остановки в окно выпрыгиваешь.

**Comment by Zmey25** [comment]
Так уже двери открылись, а ты еще пару секунд сидишь и тупишь. Я из тех, кто встает сразу, как тухнет лампа "пристегните ремни"

**Comment by YulianR** [comment]
это не фича а гавно

**Comment by Raschert0** [comment]
Так и задумано
