### ISSUE TITLE
Отсутсвуют номер и пин-код от счёта департамента поставок у КМа, если появиться в начале раунда.

### ISSUE THREAD

**Issue by Sokolisk** [TauCetiStation/TauCetiClassic#1945]
#### Подробное описание проблемы
При начале раунда за КМа не пишутся в нотесах номер и пин-код от счёта департамента поставок.
#### Что должно было произойти
Должен был быть номер и пин-код от счёта в записях.
#### Что произошло на самом деле
Данные записи отсутствуют. 
#### Как повторить
Появиться за КМа в начале раунда.
#### Дополнительная информация:
Если зайти через джоин, то все записи будут на месте.

**Comment by Smalltasty** [comment]
Это не только у КМа, у всех глав
