### ISSUE TITLE
[Proposal] Дать дронам мини-огнетушитель

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#1948]
#### Подробное описание проблемы
Я думаю, было бы неплохо добавить техническим дронам мини-огнетушитель (который на 30 юнитов).

**Comment by WallShrabnic** [comment]
Чтобы грифонить людей?

**Comment by Forrya** [comment]
Заправляй чем спреер водой, какие проблемы?

**Comment by Sakuya-Izayoi** [comment]
Спреер не меняет направление движения в космосе.

**Comment by Lancer411** [comment]
Дрону не нужно менять направление движения в космосе, потому что дрону не нужно в космос.
