### ISSUE TITLE
У лежащих трясущихся людей иногда слой становится выше чем у стоящих на них

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#195]
Originally reported by: **Nikolai Raduser (Bitbucket: [raduser](http://bitbucket.org/raduser), GitHub: [raduser](http://github.com/raduser))**

---

Соответственно закрывает их собой.

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/195

**Comment by Gyaviste** [comment]
И у стоящих тоже

**Comment by RichardJones1** [comment]
Это не баг, так работают мобы... Разве что как то закодить, чтобы лежачие мобы всегда были ниже стоячих

**Comment by LudwigVonChesterfield** [comment]
Лежачие мобы на 0.1 слой ниже стоящих. Некоторые взаимодействия с мобом могут привести к тому что у него этот слой сбросится до слоя стоящего. #5223
