### ISSUE TITLE
Как вылечить аутизм ролькам.

### ISSUE THREAD

**Issue by MrFoxik** [TauCetiStation/TauCetiClassic#1957]
#### Подробное описание проблемы
Наши рольки, и наши игроки страдают крайней формой заболевания - аутизмом, и гринтекстом. На Бэйстанции эту проблему решили выпилив Гринтекст, но рольки просто пишут "ну я типа посмотрим как прокатит, низнаю, низнаю" так что я вместе с выпиливанием ролей хочу предложить их ещё и насиловать педально за А У Т И З М. Зачем брать роль если ты не будешь развлекать станцию? 
#### Что должно было произойти
Рольки должны быть годными
#### Что произошло на самом деле
Они аутисты
#### Как повторить
Не удалять гринтекст
#### Дополнительная информация:
ГОСПОДИ ПОЖАЛУЙСТА УДАЛИТЕ GREENTEXT.

**Comment by Skippeer12** [comment]
Как там в этих цитатниках?
Если ты хочешь перемену в будущем — стань этой переменой в настоящем.

Ну так вот, меняйся ты и все последуют за тобой (нет).
Выпил чего-то не решит проблему, дополнительное пинание за то что ты аутист не поможет, потому как ролек попросту не будет, как ксеносов (До реформы про 10к минут). ((Ну там были единицы, всякие совки4 и его мультиакки, быдло-коты, ну и тому подобное, но сказать что они лучше аутистов сложно))

Предлагаю контр-меру, выпилить Фоксика из ССки (пермабаном), чтобы он не страда смотря на этих аутистов.

**Comment by Zmey25** [comment]
На самом деле выпилить грин текст идея хорошая, просто в конце писать какие были цели у ролей. Ну и педалям следить, чтобы за пределы этих целей особо не ходили.
