### ISSUE TITLE
[proposal] Добавить детективу створки.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#1960]
Для большей нуарности, было бы круто если бы у детектива были свои створки или жалюзи. Еще видел в каком-то билде, что окна могли становиться тонированными от чего сквозь них нельзя было видеть с помощью кнопочки.

**Comment by Lexakr** [comment]
У меня была немного безумная идея перенести детектива из брига куда-нибудь на место свободного офиса
