### ISSUE TITLE
Ящики на шаттле припасов могут заспавнится в стене

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#197]
Originally reported by: **volas (Bitbucket: [volas](http://bitbucket.org/volas), GitHub: [volas](http://github.com/volas))**

---

![screen](http://i.imgur.com/OjXLR5T.pngg)

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/197

**Comment by Raschert0** [comment]
По-моему, больше не повторялось
