### ISSUE TITLE
Проползал: добавить нюке шмот.

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1971]
Добавить нюке в синдишмот:
1) Плату для консоли отправления опоаещения от имени цк на станцию, либо одноразовое устройство с тем же функционалом.
2) Устройство заглушки блюспейс связи с цк. ЦК не смогут связаться со станцией, а станция с цк. Они связываются с хакерской станцией синдиката, которая уверяет цк и станцию о том, что все в порядке, перехватывая факсы и сообщения и глуша их.
3)Взломанный факс, который позволит от лица цк писать отчеты на факсы станции.

Собственно, я уверен, что добавив это - нюке будет легче вместо банального ЫЫЫЫЫААА ПИУПИУПИУ ТРАТАТА сиез ап фалс лимф дел лайфлес перейти к интересным ситуациям и устраивать что то стоящее. Интересное для экипажа.

**Comment by Avatar4** [comment]
ИСХОД! Говорит ЦК, сегодня к вам прибудет спец проверка. Принесите им ядерную бомбу и диск. Ни о чем не спрашивайте, они очень нервные. И оставить оружие, да. После этого, идите все по своим делам и не мешайте проверке.
