### ISSUE TITLE
Можно прятаться ниже уровня пола

### ISSUE THREAD

**Issue by Tolerantboy** [TauCetiStation/TauCetiClassic#1977]
#### Подробное описание проблемы
Мышь (а возможно не только мышь, а любое существо могущее в "Hide") может спрятаться под предметом, ниже которого только пол. Например решетка вентиляции. Нет, не заползти В вентиляцию, а спрятаться под самим спрайтом решетки. Или других устройств, которые вмонтированы в пол
http://prntscr.com/h9tesr

#### Что должно было произойти
С включенным HIde такие вещи как решетки вентиляции должны быть по прежнему ниже чем мышь. Например голопроектор ИИ отображается нормально

#### Что произошло на самом деле
Решетка вентиляции висит в полу-метре над землей и мышь может под ней спрятаться

#### Как повторить
Выбрать мышь, залезть под решетку

**Comment by KIBORG04** [comment]
уже нельзя
