### ISSUE TITLE
Шедоулинги стали еще никчемнее.

### ISSUE THREAD

**Issue by SkLepP** [TauCetiStation/TauCetiClassic#1982]
#### Подробное описание проблемы
Голова шедоулинга не держит даже одного попадания из лазера. На один выстрел приходится 36 берна и 70 брейндамага, который никак не вылечить в условиях линга. В итоге он умирает от одного выстрела. А иногда отрывает голову даже с одного выстрела. Но достаточно двух для гарантированного сноса головы. 

#### Что должно было произойти
Шедоу как минимум не должен получать брейндамаг и выдерживать хотя бы выстрела три (как в туловище)

#### Что произошло на самом деле
Шедоу получает брейндамаг сего лишь от одного выстрела в голову и в итоге он слит.

#### Как повторить
Поиграть шедоулингом и соснуть от одного выстрела в голову

#### Дополнительная информация:
Считаю надо балансить.

**Comment by Forrya** [comment]
У шадоулингов есть множество способностей для превентивного удара.
Единственное, что надо сделать - что бы абсолютно весь урон в темноте сам по себе плавно регенился.

**Comment by SkLepP** [comment]
Толку от твоего регена, если у тебя голова отлетает с одного удара и ты падаешь?

**Comment by WallShrabnic** [comment]
Брейндамаг выпилить, остальное балансно, ибо тенелинги текущие - имба

**Comment by Skippeer12** [comment]
Лучше просто выпилить режим, как вы любите.
Оставить только трейторов, нюку и реву, заживем!

**Comment by Motzord** [comment]
Я не уверен что это баг. Можно закрыть?

**Comment by LudwigVonChesterfield** [comment]
У них нет органов, и `brain_mod = 0`
