### ISSUE TITLE
[Proposal] Регулировка капельницы

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#1983]
#### Подробное описание проблемы
Предлагаю сделать так, чтобы на капельнице можно было регулировать подачу жидкостей отвёрткой
#### Что должно было произойти
Капельница должна быть регулируемой
#### Что произошло на самом деле
Жидкость подаётся очень медленно. Настолько медленно, что пиво успевает метаболизироваться до того, как пациент получит эффект опьянения
#### Как повторить
Вставить бутылку с пивом в капельницу и подключить себя.

**Comment by WallShrabnic** [comment]
Кто в здравом уме будет закачивать пиво напрямую в вену?

**Comment by Sakuya-Izayoi** [comment]
Ассистенты.

**Comment by WallShrabnic** [comment]
Пусть они идут лесом, нечего воровать оборудование медбея

**Comment by Sakuya-Izayoi** [comment]
Так капельницу можно в карго заказать, для неё доступ не нужен

**Comment by Kernstall** [comment]
Вы просто не знаете способа бесконечного администрирования пива на ките, поэтому пользуетесь капельницами 20 века

**Comment by Sakuya-Izayoi** [comment]
Кернсталл, может, посвятишь нас в свои знания?

**Comment by Kernstall** [comment]
Я только подскажу, что на китах можно устроить фабрику доктора Менгеле по производству %химикатнейм%
И да, насколько я понял максимальное количество химикатов одного типа ограничено 1000, что немного обидно
![default](https://user-images.githubusercontent.com/16035287/33161710-67458b8c-d036-11e7-9d6f-de66f57f0356.PNG)

**Comment by Flankir** [comment]
Пиво в вену - отличный способ напиться до смерти без малейшего запаха изо рта.=)
