### ISSUE TITLE
Сломанные консоли камер

### ISSUE THREAD

**Issue by Forrya** [TauCetiStation/TauCetiClassic#1984]
#### Подробное описание проблемы
Консолью камер невозможно пользоваться. Начинатся сильные лаги, пинг поднимается в 10-15 раз.
#### Что должно было произойти
Не должно лагать
#### Что произошло на самом деле
Лагало дико
#### Как повторить
Открыть консоль камер
#### Дополнительная информация:
Раньше не лагало.

**Comment by Raschert0** [comment]
1. Проблема только у некоторых клиентов
2. С этим ничего нельзя сделать

**Comment by Forrya** [comment]
Но ведь раньше все нормально было. Проходит время, и она все сильнее лагает. 
Теперь что, не пользоваться ими вообще?

**Comment by Zmey25** [comment]
Давайте поступим как с консолями телекомов, выпилим камеры и дело с концом

**Comment by RichardJones1** [comment]
Скорее всего связано с байондом, так как у меня тоже есть неимоверно лагало, но на слабых компах. Видеокарта мб.
Мне кажется, тут стоит на таком "сломанном" компе зайти на другие билды и глянуть работает ли консоль там. Тогда уже сможем понять, в чем проблема.

**Comment by Raschert0** [comment]
Зависело от версии бьенда. На каких-то лагало, на каких-то - нет

**Comment by RichardJones1** [comment]
Уверен? Я могу ошибаться, но я всегда скачивал последнюю версию бьенда. Короче, тут тестить нужно...
