### ISSUE TITLE
Отсутствует чинитель скафандров в аптечках у нюкеров

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1987]
#### Подробное описание проблемы
См. название
#### Что должно было произойти
Яинитель скафандров просто обязан быть, так как у нюки есть Риги и скафандры
#### Что произошло на самом деле
Их нет
#### Как повторить
Зайти за нюкера
#### Дополнительная информация:
N/A

**Comment by Skippeer12** [comment]
Б - Баланс.
