### ISSUE TITLE
Сломаный поиск слов у культа

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#1988]
#### Подробное описание проблемы
Поиск слов у культа сломан. Можно подставлять любые значения словам, они будут работать. Главное чтобы было вида karazet is hell и так далее, ну вы поняли
#### Что должно было произойти
Классический поиск слов с подбором
#### Что произошло на самом деле
Подставляй любые слова и получай руны на пятой минуте
#### Как повторить
Зайти за культ
#### Дополнительная информация:
Привет

**Comment by Kurshan** [comment]
Если кто-то внятно напишет этот ищью. Я попробую это починить.

**Comment by igigin** [comment]
Что тут непонятного.

1. Заполняешь книгу как хочешь, не волнуясь о реальном положении слов. На скрине просто по порядку, например.
2. Выбираешь руну, в данном случае сакрифайс.
3. Кликаешь на заполненные тобой хелл-блад-джойн, получаешь руну.
4. Читаешь что на ней абсолютно другие слова на самом деле.

![image](https://user-images.githubusercontent.com/17473163/34890037-f6e947a8-f802-11e7-9e5e-9c6b002bf1ce.png)

5. Убеждаешься, что руна всё-таки сакрифайс.

![image](https://user-images.githubusercontent.com/17473163/34890068-186dc49e-f803-11e7-827d-83c134e5df30.png)

6. Наконец-то радуешься отсутствием потери крови при изучении рун.
