### ISSUE TITLE
Миллион и один способ дюпа.

### ISSUE THREAD

**Issue by LLIkolnik** [TauCetiStation/TauCetiClassic#1989]
#### Подробное описание проблемы
Ресурсы можно дюпать. Всё, что нужно - сварка, шлем, два металрода, кусачки и топливо. Из этого можно сделать себе свою станцию, если грамотно располагать ресурсами.
#### Что должно было произойти
Если сломать решётку руками, а потом обрезать остатки кусачками, должно в общей сложности выпасть две палки. Если сделать мультитайл эйрлок, после чего его разварить, из него не должно выпадать появившееся из ниоткуда стекло.
#### Что произошло на самом деле
При перерезании сломанной решётки выпадает два рода, и в общей сложности мы имеем уже три. При разваривании мульитайл эйрлока, из него выпадает стекло. Изначально, стекло не добавлялось. 
#### Как повторить
Берёшь в руки две палки, строишь решётку, затыкиваешь её, после чего перерезаешь останки. Строишь мультитайл эйрлок, развариваешь его. 
#### Дополнительная информация:
Меня терзают сомнения насчёт правильности этого репорта, ведь я мог спокойно абузить. Но не стал.

**Comment by LudwigVonChesterfield** [comment]
А дюп аирлоком то остался.
