### ISSUE TITLE
Логи дамага с броска расходятся с реальностью.

### ISSUE THREAD

**Issue by LLIkolnik** [TauCetiStation/TauCetiClassic#1992]
#### Подробное описание проблемы
В чат пишется о том, что "%human_name% has been hit in the head by the %item_name%", но дамаг проходит по другой, случайной части тела. 
upd. Статистика показала, что "случайной частью тела" в большинстве случаев является chest.
#### Что должно было произойти
Дамаг должен был пройти по части тела выбранной на кукле и описанной в логах.
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/32063181/32990789-4438e068-cd51-11e7-8498-6159f8214d29.png)
#### Как повторить
Заспавнить двух хуманов, зайти за одного, кинуть первым что-то во второго.

**Comment by Skippeer12** [comment]
Проблема чисто в throwing star, они летят в чест, хотя ещё могут попадать в руку... Вообщем проблема в них.

**Comment by LLIkolnik** [comment]
Не-а.
![image](https://user-images.githubusercontent.com/32063181/36734900-aec0de6a-1bf6-11e8-83c4-156cc63ac766.png)

**Comment by KatoMarika** [comment]
Семь лет спустя можно закрыть: 
20 бросков throwing star и около 40 рандомных предметов - не выявил описуемого бага.
