### ISSUE TITLE
ИИ может видеть генок, даже если они вкачали инвиз на камерах

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#1996]
#### Подробное описание проблемы
С помощью худов ИИ может видеть невидимых генокрадоав

#### Что должно было произойти
ИИ не должен видеть генокрадов, со вкачанным скиллом.

#### Что произошло на самом деле
ХУД палит генокрада, даже если у него инвиз.

#### Как повторить
Зайти за генку, вкачать инвиз на камерах. Зайти за ИИ и включить худ, посмотреть на генку.

**Comment by omejka** [comment]
Дубликат-не-баг же
Эта обилка не дает Иишнику трекать тебя через камеры

**Comment by omejka** [comment]
Дубликат-не-баг же
Эта обилка не дает Иишнику трекать тебя через камеры

**Comment by Skippeer12** [comment]
Омежка, там абилку поменяли, она теперь полность скрывает тебя от ИИ, если ты будешь пулить труп при включеной абилке, то ИИ не увидит кто пулит труп

**Comment by Sakuya-Izayoi** [comment]
Тем не менее, если на ХУД навести курсор, то будет видно имя.

**Comment by WallShrabnic** [comment]
Ну, если датчики включены, то фича
