### ISSUE TITLE
Нерабочая механика протезирования

### ISSUE THREAD

**Issue by ProbablyCaptain** [TauCetiStation/TauCetiClassic#2001]
#### Подробное описание проблемы 

При подготовке конечности к протезированию невозможно применить не один хирургический инструмент, а равно как и сам протез, к предполагаемой конечности.

#### Что должно было произойти

Присоединение протеза

#### Что произошло на самом деле

Ничего

#### Как повторить

Попробовать провести протезирование

**Comment by CryptoKisik** [comment]
Только что проверил. Все идеально работает. 
Возможно, ты что-то не так делал. Или укажи более детально, что происходило.

**Comment by ProbablyCaptain** [comment]
Нет, не одета, лежала нормально.
Но всё равно каждый раз при попытке что либо применить к отсутствующей конечности пишет "Wich arm?" и всё.

**Comment by EdlerN** [comment]
А, ну, все там нормально работает, не надо. Для того чтобы протезировать ладошку или пятку или что там еще - нужно сначала подготовить место (скальпель-щипцы-прижигатель) с отсутствующей конечностью в цели, при этом если мы будем пытаться тыкать не тем чем надо нам и будет выдавать вот это вот "Wich arm?". Короче говоря, если вам это выдает - значит вы где-то потерялись в процессе и делаете что-то не то.
