### ISSUE TITLE
Священник овощ без палки.

### ISSUE THREAD

**Issue by MrFoxik** [TauCetiStation/TauCetiClassic#2003]
#### Подробное описание проблемы
Священник не может ничего сделать если культ выкинет палку.
#### Что должно было произойти
Священник должен изгонять одержимость Нар-Си не только с помощью обсидиановой трости, но и с помощью Библии.
#### Что произошло на самом деле
NICHEGO, её просто космировали и он стал овощем.
#### Как повторить
Выкинуть палку в космос
#### Дополнительная информация:
Дайте ему хоть возможность призывать её с огромным кулдауном, а то это пездец, флажок +FUN в виде книжки у культа которую на изи можно призвать и ровным счетом ничего у Священника.  Сделайте это доступным хотя бы во время культа.

**Comment by Kurshan** [comment]
Нет

**Comment by igigin** [comment]
Да, ещё комбат шотган, чтобы при выкидывании библии он смог выгнать культ другим путём.

**Comment by Smalltasty** [comment]
Но ведь у него и так запасные палки есть, чего ты? 
(просто надо знать где их брать)

**Comment by P-20** [comment]
В таком случае проще добавить возможность крафта нулл рода из стержня, святой воды, библии и проверки на профу. Но это уже пропозал будет.

**Comment by Flankir** [comment]
Священник может обратиться к химикам за гранатами со святой водой.

**Comment by CryptoKisik** [comment]
100% священников бегаю молча и тыкают палкой во всех, кого видят, надеясь изгнать культистов. А ты еще говоришь, что бы и палка была у священника в любой момент, в любой точке.
