### ISSUE TITLE
Баги шахтерского модуля

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#201]
Originally reported by: **Nikolai Raduser (Bitbucket: [raduser](http://bitbucket.org/raduser), GitHub: [raduser](http://github.com/raduser))**

---
- Если включить геохуд после мезонок, то эффект мезонок пропадает, если мезонки включить-выключить, то оба эффекта работают вместе;
- ~~При получении повреждений обшивки отключаются модули активированные, если один из этих модулей это мешок для сборки руды, то его не активировать даже после ремонта.~~

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/201

**Comment by ZVee** [comment]
Затер второй пункт, потому что снова пример того - почему плохо репортить даже похожие баги к чему-то одному в один и тот же репорт. Ну и возможно исправится в одном из моих следующих фиксов.
