### ISSUE TITLE
Нельзя закрыть APC

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2012]
#### Подробное описание проблемы
APC нельзя закрыть как после сборки, так и после замены батареи

#### Что должно было произойти
Крышка должна закрываться монтировкой

#### Что произошло на самом деле
Крышка не закрывается, в чат пишет Disconnect wires first

#### Как повторить
Начать сборку APC, после батареи нажать монтировкой по нему

#### Дополнительная информация:
Делал по гайду с вики и по инструкции админов.

**Comment by igigin** [comment]
@Kurshan, твои клики.

**Comment by Smalltasty** [comment]
О починке написано в комментариях [тут](https://github.com/TauCetiStation/TauCetiClassic/pull/2010)
