### ISSUE TITLE
Мелки не рисуют на полу

### ISSUE THREAD

**Issue by Ajajumbo123** [TauCetiStation/TauCetiClassic#2013]
#### Подробное описание проблемы
Мелки не рисуют на полу. Точнее лог рисования есть, а спрайта рисунка на плитках не остается.
#### Что должно было произойти
Спрайт нарисованного должен был появиться на полу.
#### Что произошло на самом деле
Он не появляется.
#### Как повторить
Взять разноцветные мелки у клоуна или из прачечной и попытаться что-либо ими нарисовать.

**Comment by LLIkolnik** [comment]
Таки всё работает как надо. По крайней мере, у меня.

**Comment by Sakuya-Izayoi** [comment]
Так же не работают спрей кены (в т. ч. и генговские)

**Comment by Kurshan** [comment]
#2010
