### ISSUE TITLE
[proposal]Уменьшить яркость доков.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2017]
Предлагаю уменьшить яркость доков что бы подчеркнуть яркость (или мрачность) бара. К примеру, сделать изначально свет там менее ярким, но пересобрав лампу, сделать яркость обычной.
Зачем? А затем что пока ты сидишь лампово в баре, этот свет из доков портит атмосферу. Серьезно, играет нуарная музыка и вы видите это http://prntscr.com/hg3rdz
Есть еще один вариант - сделать тонированные окна в баре, что бы при виде через них - изображение по другую сторону было темнее и нуарнее.

**Comment by Udokun** [comment]
А потом ещё и занизить бар, чтобы вообще всё было чётко.

**Comment by Lexakr** [comment]
Бесплатное включение нуара: огнетушитель+лампочка

**Comment by RichardJones1** [comment]
Сейчас бар изменили, и доки никоим образом не мешают ловить нуар а баре.
