### ISSUE TITLE
Неисправная сборка/замена батареи при работе с АПЦ

### ISSUE THREAD

**Issue by Interl0per1337** [TauCetiStation/TauCetiClassic#2018]
#### Подробное описание проблемы
Если делать с нуля АПЦ - невозможно будет закрыть крышку для завершения сборки, при использовании лома оно будет предлагать вам перерезать провода терминала на тайле под АПЦ.
То же самое будет и во время замены батареи. Невозможно закрыть крышку.

#### Что должно было произойти
После окончания сборки  АПЦ - закрыть крышку ломом, провести картой по АПЦ , включить рубильник, свет есть

#### Что произошло на самом деле
При сборке вы доходите до этапа закрытия ломом - крышка не закрывается - доступа к АПЦ нету - света нету.

#### Как повторить
Попытаться собрать АПЦ в новой зоне, либо разобрать и собрать старый АПЦ.
#### Дополнительная информация:
Если я не написал бы этот дабл-репорт - меня бы гиббнули с помощью тоеры

**Comment by SpaiR** [comment]
#2012
