### ISSUE TITLE
В заказе ящиков с коврами не достаёт самих ковров

### ISSUE THREAD

**Issue by Interl0per1337** [TauCetiStation/TauCetiClassic#2019]
#### Подробное описание проблемы
При заказе в карго ковров - которых по бумагам у нас стандартный стак -50 штук - прибывает лишь один ковёр, очки уходят впустую

#### Что должно было произойти
При заказе ковров в ящике должно быть 50 штук

#### Что произошло на самом деле
По прибытию оказывается что в самом ящике лишь 1 ковёр

#### Как повторить
Пройти в карго, заказать позицию с коврами, подождать прибытия - наблюдать данный баг

**Comment by volas** [comment]
@Sakuya-Izayoi посмотришь?
