### ISSUE TITLE
Баг со сменой КД умений in_hand

### ISSUE THREAD

**Issue by Unforg1v3n** [TauCetiStation/TauCetiClassic#2020]
#### Общее описание:
Все умения, производные от in_hand, не позволяют администрации изменять их charge_max, ибо каждый раз он сбрасывается до стандартного.

#### Что должно было произойти:
Значение charge_max должно было сохраниться и не возвращаться к стандартному раз за разом.

#### Что происходит:
После использования умения, charge_max возвращается до стандартного значения, указанного в умении.

#### Как повторить:
Нужно выдать своему персонажу любое умение in_hand (Lighting Bolt, Fireball, так далее), после чего зайти в него через vv и изменить переменную charge_max на любое другое значение, после чего воспользоваться умением и посмотреть на перезарядку.

#### Дополнительная информация:
Баг может помешать администрации во время щитспавна/ивента или другой деятельности, где нужно будет умение in_hand типа, так же из-за этого нельзя создавать прямо в игре какие-то альтернативы этого умения, изменяя переменные. Вся проблема из-за неудачной механики в самом коде.

**Comment by Kurshan** [comment]
Педальные баги не баги вовсе. Кодеры не обязаны заточивать каждую фичу, чтобы она ещё корректно работала с шатаниями ВВ.
