### ISSUE TITLE
На фотографиях не отображается новый пол в меде.

### ISSUE THREAD

**Issue by Martinelli20120** [TauCetiStation/TauCetiClassic#2021]
#### Подробное описание проблемы
На фотографиях не показывается новый пол в меде
#### Что должно было произойти
Он должен показываться
#### Что произошло на самом деле
Там черный квадрат
#### Как повторить
Сделать фото нового пола
#### Дополнительная информация:
[тык](https://pp.userapi.com/c834400/v834400127/3d173/MGcUbc8BFW8.jpg)

**Comment by Unforg1v3n** [comment]
Хочу добавить, что это не только с полом. Так же не отображаются вещи, как пример: халат ученого. Но не отображаются только в том случае, если они лежат. Если надеты на куклу, то все нормально.

**Comment by Belfogor** [comment]
На фотографиях много чего не отображается. Этот баг древний как сама СС.

**Comment by RichardJones1** [comment]
Давайте не будем множить ишью. Может я не прав, но мне кажется, что делать миллион ишью по этой теме не нужно.
