### ISSUE TITLE
Баг с отображением мед./сб записей в ПДА.

### ISSUE THREAD

**Issue by Azuzyan** [TauCetiStation/TauCetiClassic#2023]
#### Подробное описание проблемы
При попытке открыть запись о конкретном члене экипажа в медицинских/сб записях с ПДА детектива  (не пробовал с другими, нужно уточнять) **сидя при этом** ничего не происходит.
#### Что должно было произойти
Должны открываться записи.
#### Что произошло на самом деле
Ничего.
#### Как повторить
Зайти за детектива (предположительно за любую другую профу имеющую доступ к мед/сб записям), сесть на кресло/стул и попытаться открыть в ПДА запись о любом персонаже.

**Comment by Yaroslavppv** [comment]
Такая проблема только с не двигающимися стульями, которые катаются, работают нормально
