### ISSUE TITLE
Спрайт хвоста таяран сломан, после отрезания ног.

### ISSUE THREAD

**Issue by LLIkolnik** [TauCetiStation/TauCetiClassic#2030]
#### Что должно было произойти
После отрезания ног у таяран должен нормально показываться хвост.
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/32063181/33422812-a862ed24-d5d8-11e7-943d-94a8e265d1ac.png)
#### Как повторить
Отрезать ноги кисику.
#### Дополнительная информация:
(не обращайте внимания на сифор, просто рандомно творил херню на локалке и наткнулся на вот это)

**Comment by RichardJones1** [comment]
Нет, проверил, всё работает нормально
