### ISSUE TITLE
Мыльная граната трейтора не работает

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2031]
#### Подробное описание проблемы
Мыльная граната трейтора не распыляет пену, на которой бы все подскальзывались и не спавнит синдимыло.

#### Что должно было произойти
Все должны подскальзываться на пене и мыле.

#### Что произошло на самом деле
Граната молча исчезает.

#### Как повторить
Купить гранату и запустить

**Comment by Skippeer12** [comment]
Хотелось бы уточнить, что все кластер бенговые гранаты не работают.

**Comment by RichardJones1** [comment]
#2730 пофикшено
