### ISSUE TITLE
Открытые шкафчики можно поставить на один тайл

### ISSUE THREAD

**Issue by KingMuskrat** [TauCetiStation/TauCetiClassic#2037]
#### Подробное описание проблемы
Шкафчики можно перетащить на один тайл когда они открыты. Не закрываются после этого. Возможно так можно сложить неограниченное число шкафчиков.
#### Что должно было произойти
Шкафчик не должен был переместиться.
#### Что произошло на самом деле
Он переместился.
#### Как повторить
Перетащить открытый шкафчик на другой открытый.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/34205667/33523739-f903c594-d81e-11e7-92d6-cc6b87a8b9ce.png)

**Comment by PavelYo** [comment]
Я бы списал это на то, что это просто удобно в некоторых ситуациях хоть и не круто в плане реализма или еще что то такое.

**Comment by igigin** [comment]
А ещё все хуманы могут в один таел встать. И кучу ручек/плиток/чего-угодно в один тайл накидать. Я это к тому, что не вижу ничего плохого в шкафах.

**Comment by KingMuskrat** [comment]
Ну как по мне ручки плитки и хуманы технически могут так и ирл поступит, а вот шкафчики уже маловероятно

**Comment by Avatar4** [comment]
Мне кажется, у некоторых людей уже реализм головного мозга и они просто хотят создать побольше бесполезных ишью что бы людям хотелось еще меньше чинить баги.
