### ISSUE TITLE
Спейсклинер брызгает если положить его в рюкзак

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2039]
#### Подробное описание проблемы
Спейсклинер брызгает если нажать им на рюкзак что бы положить его в него
#### Что должно было произойти
Он не должен брызгать при попытке положить его в рюкзак
#### Что произошло на самом деле
Он брызгнул

**Comment by Zmey25** [comment]
С закрытым клапаном брызгает?

**Comment by volas** [comment]
#2042

**Comment by Avatar4** [comment]
У спейсклинера нет понятия "закрытый". Он всегда брызгает если нажимать им по тайлу и меняет лишь количество выпрыскиваемых препаратов. А огнетушитель можно закрывать.

**Comment by Kurshan** [comment]
#2010
