### ISSUE TITLE
Огнетушитель брызгает если положить его в рюкзак

### ISSUE THREAD

**Issue by PavelYo** [TauCetiStation/TauCetiClassic#2042]
#### Подробное описание проблемы
Огнетушитель брызгает если нажать им на рюкзак что бы положить его в него
#### Что должно было произойти
Он не должен брызгать при попытке положить его в рюкзак
#### Что произошло на самом деле
Он брызнул

**Comment by Sakuya-Izayoi** [comment]
Нет, должен. Если у тебя предохранитель опущен, значит ты, скорее всего, хочешь потушить рюкзак. Если хочешь положить его туда — поднимай предохранитель.

**Comment by PavelYo** [comment]
а если я хочу сразу достать и пшикать, но для этого нужно положить его без предохранителя.

**Comment by Kurshan** [comment]
#2010
