### ISSUE TITLE
[Proposal] Спрятать банку тритора

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2043]
#### Подробное описание проблемы
Ролькохантеры триггерятся на банки с биогелем у триторов.

#### Что должно было произойти
Предлагаю сделать так, чтобы у триторов с заданием на обезглавливание 1 банка доставалась из  аплинка за бесплатно. Последующие платно.

#### Что произошло на самом деле
СБ обыскивают всех подряд, находят у робототехника банку с биогелем и кидают его в бриг.

**Comment by DeadOberst** [comment]
Банка с биогелем не должна быть чем то особенным.
Должна раздаваться из РнД с девизом "Подари своему питомцу вторую жизнь!"

**Comment by Sakuya-Izayoi** [comment]
Да уж, добавить её в РнД не будет лишним. Займусь этим. Но насчёт баночек в аплинках это уже не ко мне.

**Comment by Forrya** [comment]
Но зачем прятать банку в аплинк, если ты можешь ее спрятать сам, в игре?

**Comment by Sakuya-Izayoi** [comment]
Если банка находится на карте, значит её могут найти

**Comment by Filatelele** [comment]
Банка задумывалась как медицинская технология, а не контрабанда, следовательно, пинание дубинкой за банку в рюкзаке - обычный ролькохант. 
Если добавлять банку в рнд - заодно надо положить одну в кабинет смо.

**Comment by Flankir** [comment]
Ну так все потому что надо пинать щитсеков за незаконные обыски, аресты и прочее ролькохантерство

**Comment by Skippeer12** [comment]
Проблема уже решена, и закомичена на в билд, банка больше не является синдикат технолоджи и может быть получена в РнД.
Fixed #2050
