### ISSUE TITLE
Бесконечный подорожник

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2044]
#### Подробное описание проблемы
У подорожника нет спрайта и его можно бесконечно собирать из гидропонной установки

#### Что должно было произойти
Подорожник должен иметь спрайт и собираться нормально

#### Что произошло на самом деле
Подорожник можно бесконечно собирать

#### Как повторить
Вырастить подорожник

**Comment by Dominig12** [comment]
Да, как вернусь с больницы посмотрю

**Comment by Alexofp** [comment]
исправлено в #3570
