### ISSUE TITLE
[Proposal] Перемещение микроволновок, гриндеров, джусеров, диспенсеров с напитками + заправка фармботов

### ISSUE THREAD

**Issue by T9IHT9IKJI9JI** [TauCetiStation/TauCetiClassic#2046]
Предлагаю добавить возможность для СВЧ, гриндеров, джусеров и диспенсеров с напитками перемещения на стол например как с paper bin , который можно перемещать пулом жмакая на пол под столом. Еще стоило бы добавить возможность заправки фармботов, ибо без этой возможности приходится делать новые, но и в то же время присутствует инфа о её количестве.

**Comment by Sakuya-Izayoi** [comment]
1. ФармБоты заправляются
2. Диспенсеры можно открутить гаечным ключом.

**Comment by T9IHT9IKJI9JI** [comment]
1. Нет, при попытке заправить их водой с помощью ведра - они обливаются.
2. Я имел ввиду возможность переносить их на стол, как и соковыжималки с дробилками
