### ISSUE TITLE
Ручные дефибрилляторы не помещаются в портфель

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2051]
#### Подробное описание проблемы
Ручные дефибрилляторы ЕРТ (они же ручные, которые еще делаются в рнд), не могут поместиться в рюкзак.
#### Что должно было произойти
Они должны иметь возможность помещаться в рюкзаке
#### Что произошло на самом деле
Они в них не помещаются
#### Как повторить
Попробовать положить ручные дефибрилляторы в портфель

**Comment by Raschert0** [comment]
Так и было задумано, но если кто-то захочет это изменить - пожалуйста.

**Comment by igigin** [comment]
Фиксед когда-то, компактные вполне лезут в рюкзаки.

**Comment by Skippeer12** [comment]
Не фиксед, речь идет именно о этих дефибах
![image](https://user-images.githubusercontent.com/18488106/36065098-9c0e0d0c-0e9e-11e8-9e11-4b9d3afdb250.png)
