### ISSUE TITLE
Не извлекается батарейка из стационарного бура шахтеров на астероиде 

### ISSUE THREAD

**Issue by Kisique** [TauCetiStation/TauCetiClassic#2052]
Подробное описание проблемы

Из большого бура на астероиде не вытаскивается батарея 

Что должно было произойти

Батарея должна была вытащиться и остаться в руке либо лежать рядом с буром 

Что произошло на самом деле

Батарея не вытаскивается 

Как повторить

Отверткой раскрутить бур, пустой рукой кликнуть на него 

Дополнительная информация:

**Comment by Smalltasty** [comment]
А если нажать на бур, когда он в активной руке?
