### ISSUE TITLE
Шпесс клинер не создаёт тягу

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2053]
#### Подробное описание проблемы
Шпесс клинер не создаёт тягу при использовании

#### Что должно было произойти
Он должен отталкивать людей как минимум в космосе.

#### Что произошло на самом деле
Ничего не делает!

#### Как повторить
Выйти в шпесс с клинером.

**Comment by Avatar4** [comment]
Если уже говорить о тяге, то практически все в космосе нельзя использовать в таком ключе.

**Comment by KuzyXD** [comment]
Я сомневаюсь, что прыска клинера достаточно, чтобы создать такую тягу.
