### ISSUE TITLE
Бипски триггерится на светомеч

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2057]
#### Подробное описание проблемы
Если на карте нет разрешения на оружие, то бипски триггернётся на светомеч

#### Что должно было произойти
Экипаж (в т. ч. и бипски) думают, что световой меч это игрушка.

#### Что произошло на самом деле
Бипски арестовывает людей без разрешения на оружие со светомечём

#### Как повторить
Взять настоящий светомеч и включить его при бипски

**Comment by Yaroslavppv** [comment]
Он и на бластеры с дормов агриться

**Comment by LLIkolnik** [comment]
Фича.
