### ISSUE TITLE
Вечная загрузка приводящая к вылету сервера.

### ISSUE THREAD

**Issue by BamnLaggyTau** [TauCetiStation/TauCetiClassic#2058]
#### Подробное описание проблемы
Загружается некий файл, он не может загружатся, в итоге BYOND вылетает и приходится заходить заново.

#### Что должно было произойти
Я должен был просто нормально играть.
#### Что произошло на самом деле
Когда я выбрал професию, начал загружатся этот файл(см. аттач 1) Я пытался перезаходить, обновил буонд, но в итоге стало только хуже и он даже не загружался(см. аттач 2)
#### Как повторить
Не знаю, возможно не выходить из буонда(или обновить)
#### Дополнительная информация:
Аттачи:1 
![screenshot_8](https://user-images.githubusercontent.com/34418967/33805972-f514b43a-ddd1-11e7-9866-c7ae927f3aa3.png)
2 
![screenshot_1](https://user-images.githubusercontent.com/34418967/33805980-00557fa0-ddd2-11e7-9596-6f7f5510b58d.png)

**Comment by Avatar4** [comment]
Здесь репортят только о глобальных багах а не индивидуальной проблеме. Тебе сюда: http://tauceti.ru/forums/index.php?board=86.0
