### ISSUE TITLE
Шапка дед мороза из вендомата

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#206]
Originally reported by: **Anonymous**

----------------------------------------

Если одеть новогоднюю шапку и зимнею куртку, и потом надеть капюшон, то когда снять шапку она будет отображаться на игроке, так же все шапки будут поверх нее.

----------------------------------------
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/206

**Comment by SpaiR** [comment]
#171
