### ISSUE TITLE
Сломана зарядка ниндзь через провода

### ISSUE THREAD

**Issue by Miracler112** [TauCetiStation/TauCetiClassic#2060]
#### Подробное описание проблемы

После введения новой системы кликов ниндзи потеряли возможность через интеракт заряжать свою батарейку через провода

#### Что должно было произойти

Ниндзи должны заряжать свою батарейку через провода

#### Что произошло на самом деле

Вообще ничего

#### Как повторить

Включите интеракт за ниндзю и попытайтесь зарядиться через провод или любым другим способом

#### Дополнительная информация:

Куршан спаси, порядок наведи

**Comment by Kurshan** [comment]
А сервер то никто не обновлял, в самом ПРе это уже починил.
