### ISSUE TITLE
[proposal] Сделать объявление о местанахождении нюки после ее активирования.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2062]
Предлагаю сделать так, что бы при активации нюки, говорилось место где она активируется.
Почему: Прилетает стелс нюка после часа раунда, хуярит кэпа, забирает диск и ставит его где-нибудь в техах на 3 минуты. Это не есть нормально и вообще пидорство.

**Comment by Sakuya-Izayoi** [comment]
Не по форме, в архив

**Comment by Skippeer12** [comment]
Так же стоит поднять минимальное время для установки до десяти минут, потому как найти её и обезвредить за 3 минуты не есть возможным.

**Comment by Smalltasty** [comment]
Тогда или время, или место. А вообще, отслеживайте вон по пинпоинтеру. Можно ему крафт в рнд добавить, только не такой же как у кепа. 
А время минут до 5, ибо 10 - ту мач. Ее часто находят, по моим наблюдениям.

**Comment by Forrya** [comment]
Предлагаю еще короче что бы в начале раунда с цк объявляли режим и палили ролек, а то блин стелсотриторы аутируют всю смену, а за минуту до отлета шаттла трусы воруют.

**Comment by Skippeer12** [comment]
Так делаешь 10 минут минимальный таеймер и пусть нюкеры не персонал выпиливают, а бомбу дефают от набегов. А то они сначала пытаются выпилить персонал, половина из них делает сосай, а оставшиеся ставят бомбу на 3 минуты и беги форест беги.

**Comment by Uvash** [comment]
Нюкеры активируют бомбу в бриге, а потом утаскивают её в техи.

Лучше сделать, что бы бомба детанировала только при наличии внутри неё диска.
И да, я лично не помню когда её в последний раз успешно разминировали.

**Comment by Skippeer12** [comment]
Во-первых, никто не знает как обезвредить бомбу.
Во-вторых, никто не знает можно ли за офицера или технического ассистента обезвредить бомбу и не получить за это по щам (бан).
В третьих, разгерметизация, слишком много разгерметизации.

**Comment by Uvash** [comment]
> Отсюда теряется вся суть режима, где нюклерам надо забрать этот самый диск, чтобы наказать нерадивых нанотрасен.

Соснюкеры наказывают НТ путём подрыва новейшей научной станции со всем её персоналом и оборудованием. 

И да, если будете делать 10 минутную задержку, то понижайте соснюкерм цены на патроны

**Comment by Flankir** [comment]
То есть по твоему плану персоналу не надо будет даже обезвреживать бомбу, будет достаточно тупо достать из нее диск?

**Comment by FelixRuin** [comment]
кажется, кажется, этот ишус можно закрыть, уже реализовали
