### ISSUE TITLE
После галлюциногенов эффект остается при смерти и гостовании.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2063]
#### Подробное описание проблемы
После смерти от употребления галлюциногенов у гостоты остается эффект.
#### Что должно было произойти
Эффект должен был пропасть.
#### Что произошло на самом деле

![](https://cdn.discordapp.com/attachments/355737082771144705/390243953821220864/unknown.png)

![](https://cdn.discordapp.com/attachments/355737082771144705/390244072272429058/unknown.png)

#### Как повторить
Употребить галлюциногены и умереть.

**Comment by Forrya** [comment]
Такая же параша у умершего нюкоборга с ПнВ, после смерти он включен и госту.

**Comment by Motzord** [comment]
Все еще актуально, так же остается фильтр серого экрана комы. Fix it
