### ISSUE TITLE
Сделайте деконверт трэллам шадоулингов

### ISSUE THREAD

**Issue by MrFoxik** [TauCetiStation/TauCetiClassic#2064]
#### Подробное описание проблемы
У нас мутятся фичи, прокачивается Тень, но никто так и не догадался превратить конверт Шадоулинга из гипноза который нельзя снять, в тот же аналог с парадизов с "засовыванием рук в голову". И вместе с этим запилить деконверт.
#### Что должно было произойти
Деконверт должен быть.
#### Что произошло на самом деле
Его нету.
#### Как повторить
Легко!
#### Дополнительная информация:
nu pozhalyusta

**Comment by Sakuya-Izayoi** [comment]
Афаик, любой деконверт делается нанесением брейндамага
Если это не так, то сделайте, чтобы так было

**Comment by Forrya** [comment]
Плез запелите ето.
