### ISSUE TITLE
Баг с отображением спрайта деструктивного анализатора

### ISSUE THREAD

**Issue by Smalltasty** [TauCetiStation/TauCetiClassic#2065]
#### Подробное описание проблемы
Не обновляется спрайт деструктивного анализатора после разбора листа плазмы

#### Что должно было произойти
Он должен был обновиться и стать пустым

#### Что произошло на самом деле
Но не сделал этого, потому, кажется, что там еще что-то лежит (хотя это не так)

#### Как повторить
Разобрать один листок солид плазмы (нет, форона)

#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/12589405/33980203-3e756808-e0c1-11e7-8609-46d7aae7c5fd.png)

UPD: это работает и с другими материалами. А еще они разбираются по 2 раза, даже если лист там один.

**Comment by Sakuya-Izayoi** [comment]
Так со всеми стакабл предметами.

**Comment by KuzyXD** [comment]
Давно же я пофиксил. Неактуально.
