### ISSUE TITLE
Баг с трубой на тайле в две трубы (не знаю как описать проще)

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2066]
#### Подробное описание проблемы
Пиро-аномалия разбомбила техи, стекла ну и трубы. Принес воздушную трубу. Поставил на тайл где не было синей трубы но красная была цела. Прикрутил и труба поставилась игнорируя две трубы по краям из за чего она поставилась в центр словно там не было труб. Попытался покрасить трубу, починить тайлы вокруг и тд. но счетно. Попобовал открутить другие трубы и вставить и все вышло нормально.
#### Что должно было произойти
Труба должна пристыковаться к трубам рядом в свой слой.
#### Что произошло на самом деле
Она проигнорировала трубы рядом с собой и поставилась по центру.
#### Как повторить
Запустить пиро-аномалию и попытаться починить соединенные трубы.
#### Дополнительная информация:
http://prntscr.com/hnms22

**Comment by Sakuya-Izayoi** [comment]
Вот у меня все чинится.

**Comment by Avatar4** [comment]
Тогда не знаю в чем проблема, может я такой везучий а может аномалия такая аномалия.

**Comment by Skippeer12** [comment]
Это не баг, там в раздатчике труб есть три вида труб.
Одни для откачки воздуха (красные).
Одни для закачки воздуха (синии).
Одни для других целей (серые).
