### ISSUE TITLE
Банки с биогелем нет в РнД.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2067]
#### Подробное описание проблемы
Банки с биогелем нет в РнД.
#### Что должно было произойти
Она должна быть.
#### Что произошло на самом деле
Её вкодили в РнД, но что-то пошло не так.
#### Как повторить
Исследовать в РнД вещи.

**Comment by KuzyXD** [comment]
Эта банка должна быть создаваемой? Разве так?

**Comment by Skippeer12** [comment]
Look here #2055
