### ISSUE TITLE
[Proposal] Расширить возможности гипса.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2069]
Предложение по расширению возможностей гипса из красной аптечки. Чтобы его можно было наложить не только на кисти и ноги, но и на пятки, ладохи, голову, чест, пах.
Чтобы человек не умирал и смог хотя бы как нибудь да двигатся, пока не проведут операцию.

**Comment by Forrya** [comment]
В аптечке не то что гипс, там набор фиксации конечности. 
А как ты представляешь, допустим гипс, на гроине? Гипсовый подгузник? Или на ладошке? Гипсовая варежка? Потом и гипсовый носочек? Гипсовый шлем? Гипсовый нагрудник?

Человек-гипс под химией против горлех марадеур оперативе, смотрите на станциях тоу сети!

**Comment by Skippeer12** [comment]
Такое ощущение, что тебе никогда не ставили гипс. Если у тебя сломан палец тебе не ставят гипс на всю руку.

Гипсованая пах, чест и голова для того чтобы при перемещении у тебя от движения кости не ломались внутрение органы, а так как у нас хирурги скажем так "не очень", то это отличный вариант.

Отличные идея, пойти выпилвать нюку после того как она сломала тебя один раз. Два раза на те же грабли, поздравляю, ты бы получил премию если бы это было в ИРЛ. Но это всего лишь игра, а у нюкеров и так масса способов уничтожить тебя даже если ты в мехе, гипс никак не спасет от оторваной конечности, максимум как я описал выше, он не позволит костям сломать тебя изнутри при перемещении.

**Comment by Forrya** [comment]
Одно дело, если бы под гипсом кости минут за 5-10 сами чинились. Что бы имело смысл отлеживаться с ними.
И зачем тебе с проломленым честом и головой куда то идти? В крайнем случае коляска есть.

**Comment by Skippeer12** [comment]
Во-первых.
Коляска есть, но она существует не для перемещения людей с пробитыми головами и грудаками, а для инвалидов без ног.
Во-вторых.
Она не мешает костям шевелится у тебя в голове или грудаке.
![image](https://user-images.githubusercontent.com/18488106/34051507-90ce852e-e1c7-11e7-8cdb-a599043e5c75.png)
В третьих.
Если ты не знал, то переломы костей и оторваные конечности дают у нас голо-урон, этот самый голо-урон, который не даст тебе встать в лучшем случае, а в худшем кинеть в бесознанку пока тебе не вколят обезбаливающего или не починять кости.
Так как ты не можешь говорить, потому что валяешься в бесознанке из-за голо-крита, ты не можешь сказать медика, что ты всё ещё ждешь.
В лучшем случае тебя кинут возле операционной, в худшем про тебя все забудут, потому как подумают что ти покинул игру.
В четверых.
Иметь возможность самостоятельно перемещаться и не падать каждые три секунды в голо-крит, это очень хорошо. Дойти до шаттла например. 
Без медиков, ты всёравно не сможешь поставить себе гипс (ну сможешь но очень-очень долго, и то есть у тебя переломано две или три конечности) так что на баланс это никак не влияет. Пойдешь воевать опять, соснешь до конца и тебя уже спасут как труп или оставят там лежать.

**Comment by Forrya** [comment]
Хз-хз, последний раз, когда я с пробитыми ребрами  и головой на ней катался - мне нормально было.
