### ISSUE TITLE
Содержание в DNA modifier

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#207]
Originally reported by: **Kopoba (Bitbucket: [kopoba](http://bitbucket.org/kopoba), GitHub: [kopoba](http://github.com/kopoba))**

----------------------------------------

Содержание в DNA modifier не подается ни резисту никому либодругмоу действию. Плохо очень сидишь как селедка в бочь без возмонжостей

----------------------------------------
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/207

**Comment by Lancer411** [comment]
Нельзя выбраться, если на тебе надеты наручники. 
Без наручников можно выбраться резистом.
Возможно суть в том что нельзя снять наручники в днк-модификаторе, но это уже отдельная проблема.
