### ISSUE TITLE
Счетчик генокрадов во время смерти может остановиться

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2071]
#### Подробное описание проблемы
Счетчик генокрада на второй смерти остановился. Что я до этого делал: Соснул от лазеров и пробитого скафа, воскрес, использовал ласт резолв, отложил яйца в трупе, воскрес, сломали череп и чест, забили лазером и кулаками, счетчик остановился.
Комуфляж от ИИ на момент смерти был снят.
#### Что должно было произойти
Счетчик не должен останавливаться даже после смерти.
#### Что произошло на самом деле
Он остановился и мне пол часа отпиливали голову.
#### Как повторить
Без понятия.
#### Дополнительная информация:
Мама, я соснул из за бага!!!!
http://prntscr.com/hnyqxx

**Comment by Avatar4** [comment]
Тут сказали что при смерти счетчик и не восполнялся никогда. Вообще об этом не слышал. По сути генокрады всегда могли ревайвиться если только им не оторвало голову или их не криммировали.

**Comment by Avatar4** [comment]
Стоп, я понял почему я так решил. Раньше реген стазис не стоил вообще ничего а теперь он стоит аж двадцатку. Либо я слепой, либо я этого в чейнджлогах не видел. И еще на вики тоже самое написано что это бесплатно.
![image](https://user-images.githubusercontent.com/19417166/34060199-4e258d52-e1eb-11e7-8aa1-72611c998e54.png)

**Comment by Skippeer12** [comment]
Я поправил. Больше такой проблемы возникать у тебя не будет при прочтении вики.
