### ISSUE TITLE
При экзамайне генокрада с оружием генокрада его не видно.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2072]
#### Подробное описание проблемы
Если экзамайнуть генокрада, который держит щит или любое другое оружие, то его не будет видно на экзамайне.
#### Что должно было произойти
Оружие должно отображатся в руке в которой он его держит
#### Что произошло на самом деле
Генокрад стоит со щитом, но это не видно на экзамайне.
#### Как повторить
Зайти за генокрада, использовать щит, экзаймайнуть себя
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/18488106/34052862-dbe6780a-e1cc-11e7-8d31-0fbb13acfece.png)

**Comment by Kurshan** [comment]
По задумке Зве, всё Абстрактное оружие не предмет вовсе. В случае генокрада, он всё же не держит щиты-мечи, а как бы морфает руку в них.

**Comment by Skippeer12** [comment]
Почему тогда не написать типа что-то этого "Его/Её правая рука выглядит как щит/мечь"
