### ISSUE TITLE
[Proposal] Добавить в армори к ригу большой балон с воздухом.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2079]
Добавить в армори к ригу большой балон с воздухом (Может еще джетпак)

**Comment by Forrya** [comment]
Что мешает брать его из ЕВА?

**Comment by DeadOberst** [comment]
Синди-граната.

**Comment by Forrya** [comment]
Ну так в начале смены брать болон, или из пожарных шкафов лутать.

**Comment by Avatar4** [comment]
Это неудобно и не нужно. Этим скафом в армори пользуются в крайнем случае и бегать в этот момент некогда.

**Comment by Forrya** [comment]
>в начале смены
>некогда
Да-да.
