### ISSUE TITLE
[Proposal] Малфа нельзя подебить

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2081]
#### Подробное описание проблемы
После последнего обновления малфа пропало указание с ЦК о том, что нужно валить малфа. Если малф будет тупо молча ломать апц и захватывать стейшен, то по РП персонал ничего не сможет ему предьявить. Паста из вики:
>При отсутствии неопровержимых доказательств, прямого заявления ИИ или соответствующего сообщения с ЦК, ИИ и Киборги не могут быть признаны враждебными.

#### Что должно было произойти
С ЦК должно приходить сообщение, что нужно вырубать малфа.

#### Что произошло на самом деле
С ЦК идут какие-то непонятные хуеграммы которые не несут никакого смысла.

#### Как повторить
Сыграть за молчаливого малфа

#### Дополнительная информация:
Начинаешь тейковер
@
«Экипаж, игнорируйте это сообщение, ИИ в порядке. Выпейте лучше чаю»

**Comment by Skippeer12** [comment]
Не знаю что вам ещё надо, у вас тут прямая лицензия на гриф ИИ.
![image](https://user-images.githubusercontent.com/18488106/35297485-bd995ce4-0087-11e8-84e2-5af76e3b6074.png)
Не знаю зачем вам старая запись.
