### ISSUE TITLE
Термит потерял спрайт.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2086]
#### Подробное описание проблемы
При сожженнии обычной стены термитом - горение термина не видно.
#### Что должно было произойти
Стена должна гореть
#### Что произошло на самом деле
Горения нет
#### Как повторить
Разлить 5 единиц термина на обычную стену и поджечь горелкой

**Comment by BesumniiChebureck** [comment]
Не актуально
