### ISSUE TITLE
При взломе двери через кабель от ПИИ чат начинает утопать в спаме

### ISSUE THREAD

**Issue by Ajajumbo123** [TauCetiStation/TauCetiClassic#2088]
#### Подробное описание проблемы
При взломе двери через выпадающий от ПИИ кабель чат начинает утопать в спаме от сообщения "the data cabel retracts bact to it's spool"
#### Что должно было произойти
спама не должно быть
#### Что произошло на самом деле
спам есть
#### Как повторить
взять выпадающий кабель от ПИИ и взломать дверь

**Comment by KuzyXD** [comment]
Починено в #3706
