### ISSUE TITLE
Ошибка в сообщении персоналу при введении синего кода 

### ISSUE THREAD

**Issue by Ajajumbo123** [TauCetiStation/TauCetiClassic#2089]
#### Подробное описание проблемы
При введении синего кода персоналу станции приходит оповещение с ошибкой. Собственно им пишет, что "на бору станции" что-то там обнаружено
#### Что должно было произойти
В сообщении не должно быть опечаток, никаких боров, только борты
#### Что произошло на самом деле
Вместо "на борту" пишет на "бору"
#### Как повторить
Ввести синий код, прочитать высветившееся в чате сообщение 
#### Дополнительная информация:
![screenshot_21](https://user-images.githubusercontent.com/21369843/34319005-ae3f2a30-e7e6-11e7-91fc-58352275ff1d.png)

**Comment by Sakuya-Izayoi** [comment]
Не баг

**Comment by DeadOberst** [comment]
Ну зачем?

**Comment by Skippeer12** [comment]
Не баг, а мемас.

**Comment by Ajajumbo123** [comment]
Your memes end here

**Comment by Skippeer12** [comment]
Вам не победить в этой войне за граммотность, сэр ящер, сложите ваше оружие и сдавайтесь и мы пощадим ваши спрайты.

**Comment by Skippeer12** [comment]
Закрывайте, занимает место :peka:

**Comment by igigin** [comment]
Бля, тостер сломался.

**Comment by igigin** [comment]
Хостера продавили сквозь бор, пришлось оградить его бортиками.
