### ISSUE TITLE
переработчики мусора

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#209]
Originally reported by: **Anonymous**

----------------------------------------

Невозможно пересобрать резак мусорных спрессованных кубов. Для сборки требуется манипулятор, который не влезает в механизм.

----------------------------------------
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/209

**Comment by ZVee** [comment]
Стеслофиксанули давно.
