### ISSUE TITLE
Голдграб не приумножает руду 

### ISSUE THREAD

**Issue by Kisique** [TauCetiStation/TauCetiClassic#2090]
**Подробное описание проблемы** 

Если скормить голдграбу руду и убить его, то руда не удваивается
**Что должно было произойти** 
После смерти гомункул должен удваивать скормленную руду

**Что произошло на самом деле**
Руды не становится больше, а даже меньше - выпадает по 5 единиц руды, вместо скормленных например 20 единиц форона и т.д

**Как повторить**
Скормить руду гомункулу 

Дополнительная информация:

**Comment by Skippeer12** [comment]
Не баг, он работает корректно. Но очень специфически, можно закрывать, мейнтейнеры прийдите, порядок наведите.
