### ISSUE TITLE
Абуз диктофона позволяет понимать незнакомые языки.

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#2091]
#### Подробное описание проблемы
Если на диктофон записать реплику особи, которая общается на незнакомом тебе языке, то воспроизведя сказанное на диктофон, или распечатав, ты получишь полноценный перевод, вместо классических обрывков со звездочками. 

#### Что должно было произойти
Человек не владеющим языком, не должен понимать о чем ведется речь, после прослушивания записанной реплики на диктофоне. 

#### Что произошло на самом деле
Недобросовестные игроки абузят этот недочет в механе.

**Comment by Sakuya-Izayoi** [comment]
Фича

**Comment by Skippeer12** [comment]
That's an universal recorder.

A device that can record up to an hour of dialogue and play it back. It automatically translates the content in playback.

**Comment by Tolerantboy** [comment]
В диктофон встроен переводчик

**Comment by Kurshan** [comment]
Народ решил, что фича.
