### ISSUE TITLE
Неиспользованная годнота

### ISSUE THREAD

**Issue by MrFoxik** [TauCetiStation/TauCetiClassic#2092]
Я решил один раз заглянуть в код, скачал я себе Тау Сети, загрузил, открыл и посмотрел на доступные спрайты в коде.
И увидел кучу годноты которую стоит реализовать. Чего стоит ходячий культ-армор, или например человек совмещенный с ядром ИИ, папка с хайвботами тоже интересна, а ведь их там не один спрайт (угадайте какой спавнят в Гейтвее? - проходите, вот вам лэвэл. Если присмотреться, то не только ивентмастеры но и кодеры могут чего выглядеть дохуя интересного. Ну стыдно же что оно не использовано.

**Comment by igigin** [comment]
Не вижу тут никакого конкретного предложения. Пропозал уровня "Сделайте всё хорошо чтобы было.", закрыто.
А так бери и реализуй, никто не мешает же. Что они есть и так все знали.
