### ISSUE TITLE
У воксов на шаттле нет хирургических инструментов.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2096]
#### Подробное описание проблемы
Воксы не имеют хирургических инструментов на своем шаттле.
#### Что должно было произойти
У воксов на шаттле должны быть хирургические инструменты.
#### Что произошло на самом деле
Их нет и воксы делают гетто-сарджери.
#### Как повторить
Зайти за воксов.

**Comment by Smalltasty** [comment]
Ты же вокс - укради!
