### ISSUE TITLE
У воксов на шаттле не улучшен слипер.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2097]
#### Подробное описание проблемы
У воксов на шаттле нет слипера с улучшеными деталями.
#### Что должно было произойти
У воксов должен быть улучшеный слипер.
#### Что произошло на самом деле
Его нет.
#### Как повторить
Зайти за воксов.

**Comment by Smalltasty** [comment]
Почему у них должен быть апгрейжен слипер? И да, укради детали и улучши!
