### ISSUE TITLE
Ремесленники не умеют хилять големов.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2100]
#### Подробное описание проблемы
Ремесленники атакуют вместо того что бы лечить големов.
#### Что должно было произойти
Он должен кликом отхиливать големов.
#### Что произошло на самом деле
Он их атакует.
#### Как повторить
Зайти ремесленником и попытаться отхилить раненных големов культа (духа или джагернаута).
#### Дополнительная информация:
Возможно у ремесленника был прожат харм когда он умер хуманом.

**Comment by Kurshan** [comment]
А это скорее клики сломалей.

**Comment by Sakuya-Izayoi** [comment]
Да-да, если умереть со включенным хармом, то когда ты станешь мобом у тебя тоже будет харм. Сделайте форс хелпа.

**Comment by Kurshan** [comment]
#2010
