### ISSUE TITLE
[Proposal] Губная гармошка не влезает в карман

### ISSUE THREAD

**Issue by LennyPane** [TauCetiStation/TauCetiClassic#2107]
Губная гармошка не влезает в карман, хотя по размерам ИРЛ она очень даже хорошо лежит в кармане, у самого есть губные гармошки.

**Comment by Forrya** [comment]
9мм пистолет не влазит в карман, хотя по размерам ИРЛ он очень хорошо лежит в кармане, у самого есть 9мм пистолеты.
