### ISSUE TITLE
[Proposal] Добавить семян в ксенофлору

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2111]
На астероиде в ксенофлоре нет семян, даже самых обычных. И вместо гидропонных установок там  обычные блин грядки.

**Comment by Skippeer12** [comment]
Оно там только для того, чтобы ты смог вывести какую нибудь ебу с астероида, а так как для этого нужно невероятно много времени и удачи оно весит там мёртвым грузом.

**Comment by Zmey25** [comment]
Все равно спрайты ксенорастений поломаны, шансы достать их из остатков занерфлены, а ксеноархеология забыта и никто ее доделывать не будет.
