### ISSUE TITLE
[Proposal] Дать мехам возможность ходить сквозь чревоточину телесайнса.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2116]
Ученые таким образом смогут быстрее доставить рипли на шахту не проходя всю станцию. А так же, в случае если шахтеров нет совсем - смогут сами накопать руд (с риском быть съеденными).

**Comment by Skippeer12** [comment]
Из-за этого кстати мехи не могут использовать встроенный вормхол генератор.
