### ISSUE TITLE
При отчленении протезированной ладошки/пяточки появляется обычная, а не искусственная.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#2118]
#### Подробное описание проблемы
Если отделить протез, то появится обычная конечность, а не этот протез.
#### Что должно было произойти
Должен появится протез.
#### Что произошло на самом деле
Появилась нормальная отделённая конечность.
#### Как повторить
Попытаться ампутировать искусственную конечность.
#### Дополнительная информация:
Вот у нас есть человек и He has a robot right hand! Если мы cut off Unknown's right hand with the circular saw, то появится не That's a robot right arm (как оно должно быть), а That's a right hand.
_С протезированными целиком конечностями_ (полностью рука, полностью нога) _всё работает нормально_ и появляется робо-рука/нога.

**Comment by WallShrabnic** [comment]
Костцль чтобы нельзя было пришить робо-конечность обратно

**Comment by wadangel** [comment]
Не актуально, закрываю.
