### ISSUE TITLE
Алиенопроблемы [1]: Лицехват не может заразить хумана если тот движется.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2121]
#### Подробное описание проблемы
Если лицехват прыгнет на жертву и начнет заражение и кто-нибудь начнет пулить хумана туда сюда - процесс заражения сбивается.
#### Что должно было произойти
Заражение не должно прерываться если только кто-то не снимет лицехвата с лица.
#### Что произошло на самом деле
Оно прерывается если пулить хумана.
#### Как повторить
Попытаться заразить двигающегося хумана лицехватом.
#### Дополнительная информация:
Конкретно на этом моменте
![image](https://user-images.githubusercontent.com/19417166/34640492-52f0e8b4-f2fc-11e7-85f3-09f6603f07ac.png)

**Comment by LudwigVonChesterfield** [comment]
do_after can_move = TRUE
