### ISSUE TITLE
Алиенопроблемы [2]: Все алиены в вентиляции ничего не видят.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2122]
#### Подробное описание проблемы
Алиены в вентиляции не видят ничего дальше того тайла на котором стоят, будто ослепли или заперты в шкафу.
#### Что должно было произойти
Алиены должны видеть трубы как дроны, куда идут и хуманов рядом. Или же видеть все окружение и выделенные трубы.
#### Что произошло на самом деле
Они ничего не видят и сливаются на раз два.
#### Как повторить
Полазить алиумом в вентиляции.

**Comment by LudwigVonChesterfield** [comment]
но ведь у нас именно так работает венткравл, и даже на других серверах - колониал марины, так же...
