### ISSUE TITLE
[Админопроблемы] Не работает "я" в анонсах 

### ISSUE THREAD

**Issue by Smalltasty** [TauCetiStation/TauCetiClassic#2123]
#### Подробное описание проблемы
Кушается буква "я" в админских анонсах 
#### Что должно было произойти
Она должна была быть на месте 
#### Что произошло на самом деле
Но ее скушало (как и букву после нее) 
#### Как повторить
Впишите "Лучше съешь ещё этих мягких французских булок да выпей чаю"
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/12589405/34642997-16d1a2a8-f336-11e7-8cc1-54d0dd16c031.png)

**Comment by Skippeer12** [comment]
Не знаю создавать ли одтельный ишус под букву "Я".
Отпишу тут если что создам ишусу.
Вообщем если выдавать ачивки, там тоже не работает буква "Я".

**Comment by Avatar4** [comment]
А еще если заполнять секьюрити, мед и прочие рекордсы, то там маленькая "я" заменяется на хрень. Возможно только настройках а не игре.
