### ISSUE TITLE
Некликабельность ссылок в ПМках и асеях

### ISSUE THREAD

**Issue by YulianR** [TauCetiStation/TauCetiClassic#2124]
#### Подробное описание проблемы

Ссылки в выше упомянутых чатах не кликаются, их приходится копировать, выделяя из бегущего чата, и вставлять в браузер

#### Что должно было произойти

нажимаешь на ссылку и она открывается в браузере

#### Как повторить

Кинуть любую ссылку в выше упомянутые чаты

**Comment by Skippeer12** [comment]
Уже вроде пофиксили
![image](https://user-images.githubusercontent.com/18488106/35863447-59429fbe-0b57-11e8-9177-9062d6206a1f.png)

**Comment by Skippeer12** [comment]
Закрывайте
