### ISSUE TITLE
Атмосфера на воксо-шаттле ломается если они начинают его двигать.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2125]
#### Подробное описание проблемы
С начала раунда у воксов на шаттле атмосфера состоит чисто из азота, но по прилете на станцию атмосфера меняется на привычную для людей смесь азота и кислорода.
#### Что должно было произойти
Атмосфера не должна менятся.
#### Что произошло на самом деле
Атмосфера поменялся и воксы начали умирать.
#### Как повторить
Подвигать шаттл воксов.

**Comment by T6751** [comment]
всё ещё актуально

**Comment by Venngedi** [comment]
Теперь с атмосферой на шаттле воксов всё хорошо.
