### ISSUE TITLE
Однорукие могут держать двойной световой меч

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2128]
#### Подробное описание проблемы
Человек/ксенос без рук может держать дабл есворд одной рукой. Подозреваю, что та же проблема с топором
#### Что должно было произойти
Двойной меч нельзя держать одной рукой
#### Что произошло на самом деле
Ассисстент с одной рукой фёрстпушнул, подобрал меч и отрубил голову
#### Как повторить
Взять за однорукого и несколько раз попытаться активировать меч
#### Дополнительная информация:
N/A

**Comment by Avatar4** [comment]
С точки зрения возможностей, не вижу ничего такого если бы однорукий человек орудовал длинным шестом, палкой или двусторонним световым мечем. Скорее фича

**Comment by Tolerantboy** [comment]
Почему нет? 
1. Возьми длинную палку в одну руку. 
2. ???
3. Profit

**Comment by WallShrabnic** [comment]
А теперь возьми здоровенную 2-3 метровую палку в одну руку и попробуй ей поорудовать. И вообще, это скорее всего влияет на Пилу

**Comment by OfGreyBugWaifu** [comment]
Ты полностью уверен, что он им орудует в стойке? Всмысле, топором можно бить одной рукой (~15 урона) или двумя руками (40 урона). Вроде с даблсордом так же.

**Comment by WallShrabnic** [comment]
Специально даже на локалочке тестил. И это проблема двуручного оружия в целом
