### ISSUE TITLE
ИИ видит скрытые руны

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2129]
#### Подробное описание проблемы
ИИ видит скрытые руны (точнее, кровь) (да, скрытые специальной руной)
#### Что должно было произойти
ИИ не может видеть скрытые руны
#### Что произошло на самом деле
ИИ видит скрытые руны. Офицеры набежали, ничего не увидели, убежали ломать ИИ
#### Как повторить
Нарисовать руну. Скрыть руну. Ждать офицеров

**Comment by KIBORG04** [comment]
Я культ удалил
