### ISSUE TITLE
Воксам не дают гринтекст.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2130]
#### Подробное описание проблемы
Воксы выполнили все задания.
#### Что должно было произойти
The Vox Raiders have been wiped out! Major Crew victory!
#### Что произошло на самом деле
Должно быть написано "Воксы победили, вы молодцы, не играйте больше в этот режим."
#### Как повторить
Выполнить все задания за воксов.

![](https://i.imgur.com/N54GyfR.png)

**Comment by Motzord** [comment]
Не актуально
