### ISSUE TITLE
Симптомы вирусов не меняются или меняются с слишком малым шансом

### ISSUE THREAD

**Issue by PavelYo** [TauCetiStation/TauCetiClassic#2131]
#### Подробное описание проблемы
Если пытаться мутировать вирус в инкубаторе, то даже после десяток попыток симптомы вируса не изменятся.
#### Что должно было произойти
симптомы должны измениться хотя бы в 1/5 случаях воздействия радиации на вирус. Я пробовал 10 раз, потом забил йух
#### Что произошло на самом деле
Максимум что изменяется в вирусе это показатель Verosity больше НИЧЕГО и то не всегда.
#### Как повторить
Попытаться в инкубаторе добавить радиации на вирус, и подождать окончания процедуры. После чего просканировать вирус на наличие изменений

**Comment by WallShrabnic** [comment]
Потому что у нас устаревшая недопиленная вирусология

**Comment by Raschert0** [comment]
По-моему, радиация влияет только на вирус, который в стадии роста (хотя я довольно давно пытался делать что-либо в вирусологии)

**Comment by LudwigVonChesterfield** [comment]
#2612
