### ISSUE TITLE
Отрубания голов мечом нинж из инвиза

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2134]
#### Подробное описание проблемы
Нинжа может отрубать головы персоналу своим энергомечом не выходя из инвиза, что делает борьбу с ним практически невозможной
#### Что должно было произойти
Активировал меч/ударил человека - инвиз спадает. Как у стелсовоксов
#### Что произошло на самом деле
Отрубания голов из инвиза
#### Как повторить
За нинжу войти в скрытный режим и пойти выпиливать персонал
#### Дополнительная информация:
Желательно вообще перенести практически всю механику костюма воксов а то это не дело. 

И да, от вскукареков ЭТО НЕ БАГ А ФИЧА я прошу воздержаться

**Comment by Ajajumbo123** [comment]
Жесткий скорее не инвиз, а кнок с первого же удара
Вычислять полностью невидимого противника непосредственно в бою интереснее, но точно не тогда, когда он кидает стан с первой же плюшки. Колоссальный урон и отрубание конечностей - пожалуйста, а стан, означающий неминуемую смерть без возможности контратаки - meeeeeh

**Comment by Uvash** [comment]
Нинжа это роль для выпиливания ролей. Просто нужно убрать режим из ротации.

**Comment by Avatar4** [comment]
Раньше активирование меча выводил нинжу из инвиза. А убрать нужно Уваша

**Comment by WallShrabnic** [comment]
Ажажа, фишка в том, что даже просто вычислить местоположение нинжи в инвизе нельзя, потому что она работает так же как инвизмин

**Comment by Skippeer12** [comment]
Вычесляй нинжу по облачку разговора. :itsok:

Согласен с Увашем, выпилить режим из ротации, потому что нинжа был создан только для того чтобы наказывать жирно-ролей.

**Comment by StrikS** [comment]
Нинзя как одельный режим убог, он редок, и даже если выпадает, то берут какие-то аутисты, которые теряются в космосе и рвут легкие, а поом их заперает ИИ ботами, и они не зная как сделать даже телепорт, сифорят нефултайловое стекло, чтобы металродом разбить то, что осталось от взрыва.

**Comment by OfGreyBugWaifu** [comment]
Хммм...
Если надеть на голову протекшон (шлем офицера, например), то нинзя не убьёт тебя фёрстхитом.
Если вы, сер хотите персоналом драться с нинжой и не надеваете даже бутельбакет - это только ваша вина.

**Comment by WallShrabnic** [comment]
Алло, ящера в полном РИГе кнокает с одного удара, после чего  много аттаклогов голова отлетает нахуй.
