### ISSUE TITLE
Пропажа ID карты в генераторе полей для ксеноархеологов

### ISSUE THREAD

**Issue by Miracler112** [TauCetiStation/TauCetiClassic#2136]
#### Подробное описание проблемы
Когда ксеноархеолог вставляет свою ID карту в генератор полей и снимает блок с него, то после манипуляций с ним иногда случается так, что он снова автоматически блокируется, а ID карта "куда-то пропадает", что делает невозможным попытки её достать снова, кроме педальной магией
#### Что должно было произойти
Карту можно было вытащить
#### Что произошло на самом деле
Карта застряла в генераторе, включилась блокировка, а сама карта либо не достается, либо пропадает вовсе из списка
#### Как повторить
Вставить карту, разблокировать генератор полей, сделать через него манипуляции и закрыть окно. Через некоторое время открыть и увидеть, что генератор заблокирован, а карты нет или её невозможно достать
#### Дополнительная информация:
Баг происходит редко и из раза в раз, бывает всё нормально, бывает каждый раз жалуются на это

**Comment by Kisique** [comment]
Можно не сувать, а открыть меню и просто кликнуть картой по генератору - работать будет и карта не застрянет
