### ISSUE TITLE
Культ хакает книгу на слова с начала раунда.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2146]
#### Подробное описание проблемы
Если в книге рандомно поставить на слова "перевод", то руны будут все равно работать.
#### Что должно было произойти
Руна не должна работать если в книге ты поставил перевод в неправильное слово.
#### Что произошло на самом деле
Руны работают независимо от настоящих слов. К примеру, у слова ire настоящий перевод это hell. Но ire можно выставить и как see и как любой другой перевод и заклинание все еще будет работать.
#### Как повторить
Сверить слова культа в админ панеле; поставить в книге абсолютно другой перевод; попробовать наколдовать с неправильными словами.
#### Дополнительная информация:
Из за этой фичи, скорее всего не работал нормально талисман телепорта.

**Comment by WallShrabnic** [comment]
Еее, дубликат https://github.com/TauCetiStation/TauCetiClassic/issues/1988
