### ISSUE TITLE
Таяра в хуманском шлеме.

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#2147]
#### Подробное описание проблемы
Если модифицировать риг для таяры(только риг, предварительно вставив шлем в риг), то можно надеть хуманский шлем, что не есть гуд.

#### Что должно было произойти
Нельзя надень хуманский шлем.
#### Что произошло на самом деле
Можно надеть хуманский шлем.

#### Как повторить
Вставить хуманский шлем в риг, модифицировать риг, надеть на таяру и кликнуть на кнопку спуска шелма.

**Comment by Pirsnya** [comment]
http://prntscr.com/hzl7j8

**Comment by Miracler112** [comment]
#2155
