### ISSUE TITLE
Протезирование конечностей не работает.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#2149]
#### Подробное описание проблемы
После апдейта куршана с выпилом кистей/ступней https://github.com/TauCetiStation/TauCetiClassic/pull/2113 сдохло протезирование конечностей. Нельзя установить протез руки или ноги.
#### Что должно было произойти
После проведения подготовки культи при установке протеза он должен устанавливаться.
#### Что произошло на самом деле
What right arm? И больше ничего.
#### Как повторить
Попробовать установить протез конечности.

**Comment by StrikS** [comment]
Тоже сталкивался
