### ISSUE TITLE
Ядерный диск ищезает при переносе на уровень спутника.

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#215]
Originally reported by: **Dennok (Bitbucket: [Dennok](http://bitbucket.org/Dennok), GitHub: [Dennok](http://github.com/Dennok))**

---

Было очень не приятно когда за нюку на нюкошатле полетели к спутнику и.... ОПняли что надо лететь обратно и искать дат фкн диск.

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/215

**Comment by Raschert0** [comment]
Спутника нету - нету и бага (ну и да, это задокументированная фича)
