### ISSUE TITLE
Шаттл велосити криво работает.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2150]
#### Подробное описание проблемы
В некоторых случаях, шаттл невозможно прислать из велосити (у меня так было при аномалии энергии). К тому же, стыковочные двери открываются сами по себе пока шаттл летит в космосе. Доступа к панеле дверей у меня не было (ксенобиолог).
![image](https://user-images.githubusercontent.com/19417166/34907347-e6ecf68c-f885-11e7-9a09-452132820bb8.png)

#### Что должно было произойти
Шаттл должен вызываться с велосити всегда.
Шлюзы в космос должны открываться лишь при стыковке.
#### Что произошло на самом деле
Без педального вмешательства порой нельзя вызвать шаттл.
Двери грифонят людей и экипаж улетает в закат.
#### Как повторить
Полетать на шаттле велосити. Активировать аномалию на высасывание энергии.

**Comment by Avatar4** [comment]
Шаттл отбытия так же не закрывает двери на вылете и все летят в космос. Так же при рилете шаттла не открываются шлюзы в космос к шаттлу.

**Comment by volas** [comment]
не актуально, было связанно с мапмержем который клинил теги на карте
