### ISSUE TITLE
Забыли добавить в четвертый шлюз вентеляцию.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2151]
![image](https://user-images.githubusercontent.com/18488106/34908683-460d923c-f89c-11e7-9589-d63a56397f3b.png)

**Comment by Raschert0** [comment]
Он не предназначен для выхода в космос, так я не знаю, как сделать такой шлюз, который бы мог открываться сверху И/ИЛИ снизу.
