### ISSUE TITLE
[Proposal] R-UST aka. TOKAMAK

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#2153]
Короче есть тема предложить всё таки намапить РАСТ, он же ТАКОМАК. Он хорошо выдаёт энергию и прекрасно подойдёт даже в качестве основного двигателя, но не в этом суть.
У нас есть тесла, синга. Предлагаю вместо старой конструкшен ареи и старой роботики попробовать пихнуть реактор РАСТ, посмотреть как оно будет и что. Зачем спросите вы
А вот потому, что если начать его делать, то потребуется как минимум час плюс минус 30 минут, а в это время, как все мы прекрасно знаем, вызывают КРЕ ТРАНХЕР и по сути даже не успеваешь им полюбоваться, поскольку постольку прилетает шатол. Да или вообще можно задействовать техи западные к расту, ему нужны створки в спейц на всякий случай(пепе) 
Рук-во по настройке можно перевести с бея.

**Comment by Pirsnya** [comment]
http://prntscr.com/i0bct3
Поигрался с маппингом, поставил вместо дрон фабрикатора, дрон фабрикатор можно опустить чуть ниже сжигателя или вместо старой роботехники.

**Comment by Smalltasty** [comment]
Ты уверен что все будет хорошо, в рабочем состоянии, не сгорит, не взорвется, не что-то там еще? 

Нюансы, сэр

**Comment by Pirsnya** [comment]
> Ты уверен что все будет хорошо, в рабочем состоянии, не сгорит, не взорвется, не что-то там еще?

Нюансы, сэр
__________
Если перевести книжку с бея и её будут читать, перед тем как настраивать - тогда полностью уверен. Ну или знающие люди, которые не будут читать книгу - настроят, как я, например. Сейчас провожу полевые испытания.

**Comment by Pirsnya** [comment]
В общем целом:

- Имеются камеры, которые можно смотреть с монитора, сидя за стеклом.
- Имеются створки, которые закрывают непосредственно само ядро.
- Имеются створки для чрезвычайной ситуации, а именно перегрев реактора, ведут в космос.
- Имеются створки для закрытия комнаты наблюдения.
- Топливо для инжекторов.
- 25 кусков плазмы для ПАКМАНа
- Один СМЕС для хранения энергии.
- Двойные стёкла для того, чтобы услышать треск первых в случае чего. Местами двойные стены потому шо б-безопасность.
- Фабрикатор дронов чуть-чуть смещён на запад.
- Добавлено руководство по запуску реактора с Бея.


Проверил, реактор исправно работает, запускается.

**Comment by Skippeer12** [comment]
Угадайте кто будет туда телепортироватся и воровать запчасти? :pekahiding:

**Comment by Pirsnya** [comment]
> Угадайте кто будет туда телепортироватся и воровать запчасти? :pekahiding:
> 
> UPD. К тому же, практически все виды топлива нужно просить у администраторов, а это не очень круто. Думаю стоит оставить его в РнД, пока не появится герой и не докодит его до конца.
> 
_____________________
Ну, таки, за это нужно будет наказывать. Знаешь, где стоит РАСТ - везде всё неплохо прижилось. Тритиум вроде уже есть на астероиде. Ну, просто в нём реально нет смысла, ибо полтора часа мозг себе иб, а потом всё бросить и улететь на шаттле.

**Comment by Skippeer12** [comment]
Тритиум не такой уж и бесполезный на данный момент, его можно использовать в пакменах который будет выдвать 1.6+е энергии на максимальных деталях.

Раст на бее больше используется для получения других видов топлева/компонентов, а не просто для получения энергии.

**Comment by Pirsnya** [comment]
Моё дело предложить, как говорится.
Всю пакманы - дело хорошее, но до них сначала нужно добраться.

**Comment by Raschert0** [comment]
@Skippeer12 идёшь в химию, берёшь большую пробирку, заливаешь 70 воды и 30 кислорода, получаешь слиток (huh) дейтерия. Повторять, пока не надоест

**Comment by Pirsnya** [comment]
Я считаю, что попробовать всё таки можно. На пару тройку раундов.

**Comment by Miracler112** [comment]
Если в нем и есть большая необходимость, то проси педалей. Пока что в нем смысла не очень много, а замапят его только тогда, когда он либо приживется с тестами и экипажем, либо тогда, когда в нем возникнет та самая необходимость

**Comment by Pirsnya** [comment]
Просить педалей что? Шаттл отменять? Знаешь, раза 3-4 точно уже строил раст и всё упиралось именно в шаттл. Даже силой 3-4 инженеров(пускай не самых лучших) это происходило более часа. Я не призываю маппить это, я лишь предложил это сделать, а когда - вопрос времени и будет ли вообще. Как аналог тесле или синге, я думаю, что неплохо. Я не понимаю тех, кто ноет кококозачемоннужен унасесть синга
Да, у нас есть даже тесла. Ведь теслу когда сдедали, никто не ныл, ЗАЧЕМ ЖЕ СДЕЛАЛИ ТЕСЛУ, ЕСЛИ ЕСТЬ СИНГА кококо.
Просто внести разнообразие какое-нибудь. Просить педалей что-то делать уже нет нужны, потому что тритиум успешно добывается на астероиде да и платы добавили в РНД(наконец-то), но чтобы их сделать нужен прогресс. Прогресс достигает нормы примерно минут 15-30(в среднем) после начала и следовательно в это время только начнётся производство реактора. Из этого делаем вывод, что делать его в раунде в полтора часа - тупо убийство времени. Вот если бы хотя б оборудование было готовое, тогда уже неплохо.

**Comment by igigin** [comment]
Почему тесла замаплена, а раст нет - потому что тесле нужно минимум изменений на месте синги: пара койлов, заземление, генератор.

Не ныли же про неё (на самом деле ныли), потому что никого и не спрашивали.
А вот почему ты ноешь, что строить долго только раст, а про суперматерию, например, не ноешь, вот это другой вопрос.

Пока что эти двигатели чисто для аутизма. Но можно переделать куски техов так, чтобы не тратить кучу времени на комнату для этих двух или как-то так. Они (техи) всё равно массивны и бесполезны.

**Comment by WallShrabnic** [comment]
Они и должны такими быть
