### ISSUE TITLE
Нерабочее управление шлюзами сжигателя и токсинов

### ISSUE THREAD

**Issue by StrikS** [TauCetiStation/TauCetiClassic#2157]
#### Подробное описание проблемы
Не открывается окно управления шлюзами сжигателя по клику на консоль. Та же история и в отсеке токсинов.

![image](https://user-images.githubusercontent.com/15943769/35005569-a501b9d2-fb15-11e7-8ae1-ecf25bc65c7a.png)

**Comment by Uvash** [comment]
Если мен память не изменяет. Ещё у Дварфа на астероиде не работал шлюз ведущий в коморку дварфа.

**Comment by StrikS** [comment]
@Raschert0 Ты же видел, видел?

**Comment by Raschert0** [comment]
Не знаю в чём ваша проблема. На локалке всё открывается нормально

**Comment by Lexakr** [comment]
Все работает

**Comment by volas** [comment]
думаю не актуально
