### ISSUE TITLE
Magnetic gripper is not operational

### ISSUE THREAD

**Issue by JesusForRent** [TauCetiStation/TauCetiClassic#2160]
#### Подробное описание проблемы
Дроны должны иметь возможность использовать магнетик гриппер, но взятая в него вещь исчезает на веки-вечные.

#### Что должно было произойти
При нажатие кнопки Drop item айтем должен дропнуться

#### Что произошло на самом деле
Он не дропнулся

#### Как повторить
Зайти за дрона и взять что-то гриппером

**Comment by Kisique** [comment]
На гриппер правым кликом и там drop item

**Comment by KuzyXD** [comment]
fixed #3573
