### ISSUE TITLE
[Proposal] Хватит благодарить за донаты

### ISSUE THREAD

**Issue by JesusForRent** [TauCetiStation/TauCetiClassic#2161]
#### Подробное описание проблемы
При каждом новом раунде логи уведомляют донятеров о том, что они очень хорошие люди, что стоило бы добавить возможность выключать.

#### Что должно было произойти
В преференсах можно это отключить

#### Что произошло на самом деле
Вы продолжаете меня благодарить

#### Как повторить
Задонатить

**Comment by StrikS** [comment]
А как это выглядит сейчас?

**Comment by JesusForRent** [comment]
Hello JesusForRent! Thanks for supporting us! You have access to all the additional donator-only features this month.
