### ISSUE TITLE
 [Proposal] Сделать стеклянные клетки разблокируемыми по карте

### ISSUE THREAD

**Issue by Smalltasty** [TauCetiStation/TauCetiClassic#2165]
Пишу это больше для себя, чтобы не забыть воплотить свои грандиозные и не очень идеи. Пока не забыла, надо записать
#### Подробное описание проблемы
Проблемы-то особо и нет, но чтобы разбить стеклянную коробку, надо разбивать стекло
#### Что должно было произойти
Надо бы, чтобы ее можно было бы аккуратно вскрыть
#### Что произошло на самом деле
Но аккуратно не получается
#### Как повторить
Вскрыть клетку у РД или капитана
#### Дополнительная информация:
Жду ваших предложений, если будут идеи

**Comment by Belfogor** [comment]
Добавить в коробку "замок", чтобы можно было его открыть проведя картой. Но для этого придется рисовать новый спрайт или дорисовывать старый.

**Comment by Smalltasty** [comment]
Я думаю, что там просто будет откидываться крышка

**Comment by Tolerantboy** [comment]
Полагаю, это невскрываемое стекло из разряда "Разбейте крышку, чтобы достать/нажать". Но можно было бы запилить, чтобы его можно было аккуратно вскрыть, проделав в нем круглую дырку алмазом. Знаете, как в старых шпионских фильмах/мультфильмах

**Comment by LudwigVonChesterfield** [comment]
При чём самим алмазом, учитывая что алмазных напильников в билде нет.
