### ISSUE TITLE
Нельзя починить сломаный АПЦ.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2166]
#### Подробное описание проблемы
После того как вы успешно снимаете крышку со сломаного АПЦ (взорванного) нужно открутить плату от корпуса, но это не возможно сделать.
#### Что должно было произойти
После клика отвёрткой плата должна была бы открутится от корпуса.
#### Что произошло на самом деле
После клика отвёрткой пишет что нужно закрыть АПЦ сначала.
#### Как повторить
Взорвать АПЦ, снять крышку и попробовать починить
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/18488106/35178558-8c4d720c-fd93-11e7-9ec8-d80b19bfe0d0.png)

**Comment by StrikS** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/275

**Comment by Skippeer12** [comment]
Не понимаю при чем тут коментарий штрикса, если тот ишус совсем про другое.

Но это не важно, я нашел по сюту дубликат этого.
#1831
@igigin Прийди и порядок наведи.
