### ISSUE TITLE
Бабочки генга малость сломаны

### ISSUE THREAD

**Issue by JesusForRent** [TauCetiStation/TauCetiClassic#2167]
#### Подробное описание проблемы
По некоторой причине, Switchblade при третьем грабе не может порезать горло и отрезать голову.

#### Что должно было произойти
У человека отлетает голова

#### Что произошло на самом деле
Ты просто бьешь человека в лицо

#### Как повторить
Взять куклу в третий граб и попытаться порезать ей горло ножом

#### Дополнительная информация:

**Comment by Skippeer12** [comment]
Потому что кто-то забыл добавить считчь блейду шарп один, но думаю это фича, а то бы он застревал при каждом ударе.

**Comment by Avatar4** [comment]
Острый ножик который на самом деле не острый :peka:

**Comment by Dominig12** [comment]
после правки не починилось, сделаю еще одну правку, после чего скорее всего он будет решенным

**Comment by Alexofp** [comment]
Вполне починилось, только что попробовал, всё работает после #3506
