### ISSUE TITLE
Материальная голограмма ИИ

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#2169]
#### Подробное описание проблемы
Теперь голограмма ИИ сбивает пул, а если ты на харме, то она не дает пройти

#### Что должно было произойти
Голограмма не должна никак влиять на окружающий мир
#### Что произошло на самом деле
Голограмма мешает пройти
#### Как повторить
Активировать голограмму ии и попытаться пройти через нее на харме

**Comment by Avatar4** [comment]
А это ты был ИИ? Поскольку, я помню что малфу выдали скилл на материальную голограмму.
