### ISSUE TITLE
Масло на голых ногах

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#2170]
#### Подробное описание проблемы
Испачканные в масле пятки нельзя отмыть.
#### Что должно было произойти
Масло должно было смыться в душе.
#### Что произошло на самом деле
Масло все равно осталось на ногах.
#### Как повторить
Пройтись босиком по маслу в техтоннелях, а потом попробовать отмыть.

**Comment by Pirsnya** [comment]
Ну масло ИРЛ тяжело отмывается и простым душем, порой, не с первого раза сходит.
