### ISSUE TITLE
Люди могут надевать скафандры ксеносов

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#2171]
#### Подробное описание проблемы
Скафандры, предназначенные для ксеносов спокойно надеваются людьми
#### Что должно было произойти
Человек не должен был надеть скафандр для унатхов или скреллов
#### Что произошло на самом деле
Ограничений нет
#### Как повторить
Зайти в ЕВА

**Comment by Avatar4** [comment]
Педали могут вполне безнаказанно творить щит с теми кто их носит, так что для веселья не плохо.

**Comment by igigin** [comment]
Если тут про те, которые в отделе с джетпаками всякими, то они вообще ошибка природы и их давно надо было удалить.

Далее, все хуманские скафандры (не шлема) могут носить скреллы, например, и наоборот. Плюс так как все ваши тояры - обычный респрайт, только с хвостами, рогами, тентаклями, то не вижу проблем хуману без хвостов и рогов уместиться в этих скефендрах.

Тут если что-то и менять/предлагать, то на уровне аболютно всех спессьютов, а это делать скорее всего никто не будет.
