### ISSUE TITLE
[Proposal] Наем и увольнение сотрудников главами отделов

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#2172]
Без главы персонала или капитана другие главы не могут нанять ассистентов или уволить своих сотрудников. Можно пользоваться временным доступом, но это ужасно. Можно отбирать ИД карту, но это так же ужасно.
Предлагаю добавить главам в кабинеты консольки, в которых они могут расширять доступы в пределах своего отдела плюс техтоннели. Оставить возможность кастомного названия должности. Доступы, которых нет у главы, но есть у сотрудника другого отдела отображаются серым и не могут быт сняты или добавлены.
P.S. Завхоз тоже глава.

**Comment by Skippeer12** [comment]
О чем может быть речь, если даже у половины глав нет банального доступа в тех.туннели и мед.блок.

**Comment by AgRevol** [comment]
У половины то есть у РД?

**Comment by RichardJones1** [comment]
А что если поднять максимальный срок выдачи временного доступа в аппаратах для выдачи этого самого доступа с 30 минут до 1 часа? Проблему решит отчасти, но другого решения не вижу - главы будут обузить доступы.
