### ISSUE TITLE
[Proposal] Люди с брейндамагом могут пользоваться оружием

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2173]
#### Подробное описание проблемы
Люди с брейндамагом, которые не могут в консоли и бьются головой о двери, могут в пушечки
#### Что должно было произойти
Оружие не работает/взрывается в руках
#### Что произошло на самом деле
Люди с брейндамагом пользуются внаглую оружием и убивают мирных таяр
#### Как повторить
Пострелять из пушечек при брейндамаге
#### Дополнительная информация:
N/A

**Comment by Avatar4** [comment]
Залетает нюкер, ему прилетает один-два выстрела в голову, нюкер взрывает свой пулемет за хуеву тучу кристалов от одного выстрела.
Пожалуй, не стоит.

**Comment by CryptoKisik** [comment]
От 1-2 выстрелов брейндамага не будет.

**Comment by Avatar4** [comment]
А ты сам проверь.

**Comment by Skippeer12** [comment]
![image](https://user-images.githubusercontent.com/18488106/35279161-f22bc006-0054-11e8-85c2-41d67f3c693f.png)
И это только два выстрела...

**Comment by WallShrabnic** [comment]
Это без учёта брони и кучи других факторов. И я говорил о более высоких значениях

**Comment by Skippeer12** [comment]
![image](https://user-images.githubusercontent.com/18488106/35279487-e5f61fb0-0055-11e8-8312-fc82566126f9.png)
Три выстрела в голову в наступающей броне синдиката.
![image](https://user-images.githubusercontent.com/18488106/35279519-f7991092-0055-11e8-88de-5581699199f9.png)

**Comment by CryptoKisik** [comment]
С таким брэйном ты можешь свободно открывать двери и пользоваться консолями.

**Comment by Skippeer12** [comment]
>С таким брэйном ты можешь свободно открывать двери и пользоваться консолями.

Это уже не просто пропозал, это ломание баланса, который и так сломан. И это только три выстрела, которые я сделал за 1.5 секунды.
