### ISSUE TITLE
Электронная сигарета

### ISSUE THREAD

**Issue by AgRevol** [TauCetiStation/TauCetiClassic#2175]
#### Подробное описание проблемы
В билде есть нормальный айкон стэйт для электронной сигареты, но вместо него используется неправильный ДМИ файл, из-за чего вместо нормального спрайта используется недоспрайт из 4 пикселей.
/obj/item/clothing/mask/fluff/electriccig //CubeJackal: Barry Sharke
    name = "Electronic cigarette"
    desc = "An electronic cigarette. Most of the relief of a real cigarette with none of the side effects. Often used by smokers who are trying to quit the habit."
    icon = 'icons/obj/custom_items.dmi'
    icon_state = "cigon"
    throw_speed = 0.5
    item_state = "ciglit"
    w_class = 1
    body_parts_covered = null
Сам я в код лезть боюсь ибо не до конца разбираюсь в нём, но когда лазил в файлах заметил что у нас таки существует нормальный спрайт и рисовать его нет необходимости.
cigon это, если я правильно понимаю, спрайт который используется во рту куклы, но по какой-то причине тут он используется как айкон стэйт. В билде есть полноценный ciglit который выглядит адекватно и, судя по всему, и должен использоваться в качестве айкон стэйта. 
#### Что должно было произойти
Иконка электронной сигареты должна выглядеть нормально
#### Что произошло на самом деле
Иконка электронной сигареты это 4 пикселя и совершенно неудобна в использовании. Ciglit нигде не используется
#### Как повторить
Взять в лоадауте электронную сигарету
#### Дополнительная информация:
Я слишком слаб в коде и гитхабе чтобы фиксить это самому. Вот.

**Comment by OfGreyBugWaifu** [comment]
*вейпит в дискорде не отключая микрофон*
