### ISSUE TITLE
Ранняя дельта при малфе

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2178]
#### Подробное описание проблемы
Малф включает дельту при 1000 секунд
#### Что должно было произойти
Хотя бы при 600 секундах
#### Что произошло на самом деле
Дельта включилась слишком рано, даже конченный аутист может уничтожить ИИ
#### Как повторить
Поиграть за малфа

**Comment by Pirsnya** [comment]
Так а ты купи отсрочку дельты. Она даётся, насколько я знаю, когда приходит последнее сообщение от ЦентКомма. Там есть интерцепт мессеж, оно задерживает уведомления. Или это не так работает?

**Comment by Skippeer12** [comment]
Без интреспетет месседжа у тебя четыре АПЦ до дельты, а с ним девять. Как я понел, но это не точно.
