### ISSUE TITLE
Биповски агрится на шахтобота с ваучера.

### ISSUE THREAD

**Issue by LLIkolnik** [TauCetiStation/TauCetiClassic#2179]
#### Подробное описание проблемы
Биповски агрится на шахтобота с ваучера и к херам ломает его.
#### Что должно было произойти
Биповски не должен ломать шахтобота. 
#### Что произошло на самом деле
Сабж.
#### Как повторить
Поднести Бипски к шахтоботу.
#### Дополнительная информация:
? ? ?
(я так проебал ваучер)

**Comment by LudwigVonChesterfield** [comment]
#4209
