### ISSUE TITLE
Проблема с доступом к шлюзам в лаборатории токсинов

### ISSUE THREAD

**Issue by Interl0per1337** [TauCetiStation/TauCetiClassic#2181]
#### Подробное описание проблемы

Будучи работником научного отсека ( подпрофа исследователя форона ) - нету доступа к шлюзовой системе камеры сжигания, при попытке открыть шлюз через консоль на стене - пишет Access Denied - то есть нету доступа.

#### Что должно было произойти

Мы подходим к консоли, имея доступ исследователя форона, нажимаем пару кнопок - шлюз открывается, мы настраиваем насосы, закрываем шлюз.

#### Что произошло на самом деле

Нам говорят что у нас нету доступа, со слезами на глазах умоляем глав или инженеров с ИИ помочь нам в настройке насосов.

#### Как повторить

Зайти на подпрофу исследователя форона, пройти в лабораторию, попытаться открыть шлюзовую камеру через консоль.

#### Дополнительная информация:

Возможно - связанно с тем, что у нас теперь такие же консольки на новых шлюзах по всей станции, и туда требуется доступ офицера/медика/инженера - но это проверенно не полностью.

**Comment by igigin** [comment]
#2157

**Comment by Raschert0** [comment]
Не-не, в том ишью писали о проблемах с самим интерфейсом, а не с доступом
