### ISSUE TITLE
Шлюз в сжигателе форонщиков не открывается из-за сломанного доступа.

### ISSUE THREAD

**Issue by LLIkolnik** [TauCetiStation/TauCetiClassic#2182]
#### Подробное описание проблемы
Название.
#### Что должно было произойти
Шлюз должен открываться, форонщик должен включить помпу, сжечь укрепки и получить перму.
#### Что произошло на самом деле
Шлюз не открывается, форонщик ждёт десять тысяч лет, получает лимитку на 1/2/4.
#### Как повторить
Попытаться открыть шлюз в сжигателе.
#### Дополнительная информация:
? ? ?
(я так в раунде поаутировать не смог)

**Comment by igigin** [comment]
#2157
