### ISSUE TITLE
Камеры на мапе. [Proposal]

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#2183]
На станции присутствуют маперский перформанс, в виде камеры напротив камеры.

https://i.gyazo.com/28b9ef8c14ebe0634da1e909b6730349.png

На позициях 1-7 камера стоит напротив камеры, при чем на 3, 4, 7 активируются одновременно и между ними нельзя переключатся.

На позиции 8 стоило бы сместить одну из камер для улучшения обзора, или вовсе убрать.
На позиции 9 (комната с охлаждайкой для крио), нету камеры. 
На позиции 11 не хватает камеры для обзора коридора и входа в гейт.
На позиции 10 камера присутствует только в коридоре, но в самой комнате запуска ее нет.
на позициях 12 и 13 ощущается нехватка камер для отслеживания доков и прибывающего туда транспорта.

**Comment by AgRevol** [comment]
#2263 
Большую часть починил. Остальное нарочно оставил ибо так и задумано (Например 10, 12, 13, 1). 8 не вижу проблемы, если не считать того что они на карте камер расположены очень близко.
