### ISSUE TITLE
[Proposal] Сделать большой шанс получить урон при попытке дизарма человека с оружием.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2185]
Нужно что бы дизармщики получали по руками при попытке задизармить кого-нибудь с станбатоном, мечем, болоном.
Ибо дизарм вооруженного человека если ты не какой-нибудь ассасин, это слишком. Тоже самое на щиты бы желательно (если этого еще нет), но без урона или с обратным дизармом как если бы тебя этим щитом оттолкнули.

**Comment by YulianR** [comment]
А если я ососин

**Comment by Avatar4** [comment]
Ящеры не могут ими быть по дефолту

**Comment by OfGreyBugWaifu** [comment]
Хмм, давайте же не будет считать что ирл с голыми руками с человеком с милишкой разобраться иногда легче, чем без. Не будем считать, что есть специальные стойки с холодным оружием для борьбы с безоружным противником.
Давайте всё вместе забудем что иногда единственная возможность разобраться с ещилдом - это дизарм, что дизарм сам по себе уже сколько патчей подряд нёрфится.
Даже если забыть всё это - мы не сможем забыть что Аватар соснул и полетел делать тему :yoba:
