### ISSUE TITLE
Двери шаттла не закрываются если в них стоит человек.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2188]
#### Подробное описание проблемы
Если при отлете шаттла в дверях шаттла встанет человек, двери шаттла не закроются и заблокируются из за чего загрифонит весь шаттл.
#### Что должно было произойти
Шаттл должен закрыться даже если в них будет объект или субъект.
#### Что произошло на самом деле
Они не закрылись.
#### Как повторить
Призвать шаттл, встать в дверях шаттла, подождать когда он улетит.

**Comment by Skippeer12** [comment]
Но ведь закрылись.
![image](https://user-images.githubusercontent.com/18488106/35846690-55eed760-0b20-11e8-907c-aae58efc4f1f.png)

**Comment by volas** [comment]
проблема относится скорее к #2142

**Comment by Skippeer12** [comment]
Но ведь их откатили.

**Comment by volas** [comment]
пусть висит. Шаттлы пока отложены, но когда-нибудь надеюсь к ним вернёмся
