### ISSUE TITLE
Если маг не может двигатся и прожмет энтернал джаунт он всё ещё не сможет двинутся.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2189]
#### Подробное описание проблемы
Если застанить мага и тот прожмет энтернал джаунт и попытается улететь, то у мага ничего не получится и он останется на месте.
#### Что должно было произойти
Маг должен смочь улететь, потому что ему не нужно находится на ногах чтобы пользоватся способностью перемещения сквозь стены.
#### Что произошло на самом деле
Яросные офицеры охраны застанили мага и ждут пока он на том же месте выйдет из джаунта.
#### Как повторить
Поиграть за мага, словить тазер, уйти в дажунт.

**Comment by Motzord** [comment]
Не актуально

**Comment by LudwigVonChesterfield** [comment]
#5378
