### ISSUE TITLE
Имбовое синтезирование химикатов с десятикратными множителями

### ISSUE THREAD

**Issue by Unforg1v3n** [TauCetiStation/TauCetiClassic#2190]
#### Подробное описание проблемы
Любые химикаты можно получить в огромных дозах, можно сделать из 20 бикардина 200 бикардина (минимум), из 20 перидаксона 200 перидаксона, из 20 форона 200 форона (опять же, 200 - около минимума), а потом из 200 сделать 2000+ и так повторять до бесконечности.
#### Что должно было произойти
Если честно, то сам не знаю.
#### Что произошло на самом деле
Химикаты бесконечно множатся и появляются из ниоткуда, по сути неограниченный запас. Даже из 1 куба можно сделать бесконечность, если поаутировать.
#### Как повторить
Нам нужно: 
1) Хотя бы 1 куб химиката
2) Охлажденное до минимума крио.
3) Любая кукла (например, из генетики)
4) Слипер (диализ)

Инструкция:
1) (опционально) Охладить крио.
2) Засунуть куклу внутрь.
3) Включить крио.
4) Засунуть стакан с химикатами в крио.
5) Подождать до того, как химикаты закончатся.
6) Достать куклу и отнести до слипера.
7) Выкачать тонны полученного из воздуха химиката. Выкачивать до полного исчезновения их до крови, стакан можно носить в химию и создавать бутылочки, и так повторять до полного исчезновения.
8) Повторить шаги 2-7 любое количество раз.
#### Дополнительная информация:
Имбово, если учитывать, что прямо на 5 минуте можно получить 200 кубов плазмы вместо 20 изначальных. И вообще получить хоть бесконечность кубов химиката имея всего один - слишком имбово. Если даже 1 куб карпотоксина будет, то можно будет открывать завод по производству данного химиката.

**Comment by Skippeer12** [comment]
I ded

**Comment by Raschert0** [comment]
Работает как и задумывалось, но пусть уж будет предложением

**Comment by Olt1771** [comment]
Сейчас читаю и смешно, ибо так и задумывалось, второе пока ты будешь пытаться дюпать, я в бесконечном хим деспенсере за два клика сделаю всего в разы больше.
Тот кусок форона на старте чисто физически сложно потратить за раунд, а если потратишь всё ещё есть в инженерке 20 плиток. И да при дюпе кукла отъедет.
О высокоурвневой химии, она имеет настолько сильное пинальти, что при попытке дюпа, она убивает, не могу понять почему не закрыли этот ишью.
Плюс при диалезе ты ещё выкачиваешь кровь и химикаты уходят в трубу при метаболизме.

**Comment by Kernstall** [comment]
Отлично, теперь это официально не баг и угрызений совести за администрирование по кубу лексорина / сб у меня не будет вызывать угрызений совести. На самом деле, об этом никто не знает  и не пользуется, только поэтому это в порядке вещей. Ольт, двести кубов плазмы в крови не вызывают мгновенной смерти, а только постепенное накопление токсинов, что очень просто контрится. Этот способ может казаться сложнее, но на самом деле гораздо проще как из-за пиздеца на станции, так из-за квартимейстеров на инжах, которые в 80 процентах случаев нихуя тебе не собираются давать, у ии вообще шансы нулевые. И если ты не в курсе, то имея один кукурузный початок и крио можно превзойти по взрывной мощи нюку и токсины вместе взятые. 
Теперь о второй стороне, о лечении с помощью крио. Самая опасная здесь вещь - передоз, но, во-первых, анти-токсин в крови позволяет лечить токсичный урон от передоза самим антитоксином + передоз бикаридином/дермалином/и т.д., а во-вторых, трикод вообще не имеет побочных эффектов, поэтому человеков можно кидать в крио со старта игры и заполнять до 1000 кубов трикодом, на полсмены хватит. Есть какая-то опасность сломать передозом органы, но она работает очень поломанно и на практике обычно все обходится благополучно. Надо ли объяснять что случится, если кому-нибудь наконец удастся сварить лекарство для отращивания конечностей/лечебных наноботов. 
Ах да, чуть не забыл, куб лексорина в бикере крио практически нереально отследить, он не отражается в логах, а смерть в крио непонятно от чего это слишком...обыденно. Чтобы расследовать почему это хос с ожогами вдруг умер надо лезть в VV, да и то не факт, что поможет, если вместо условного лексорина в бикере был токсин.
Напоследок, если положить в слипер куклу, накачанную клонексадоном, то можно добиться неплохого фарма синтмяса диализом. У нормального химика после клонексадона, перидаксона и синтмяса плазмы должен оставаться только неприкосновенный запас в пять кубов, уж поверь. Это еще если твой коллега не сольет все в дексалин :peka:

**Comment by Skippeer12** [comment]
Я знаю как пофиксить эту фичу. Мы берем и выпиливаем крио с карты и смотрим как медики пользуются слиперами и майндбрейкерами которые наварили лысые химики за тридцать минут.

Вот это всё что ты написал сверху, кроме выпила с помощью одного отрицательного химиката, ты можешь попытаться повторить и получить с этого профит, но я сразу могу тебе сказать что тебя ждет поражение.

**Comment by Kernstall** [comment]
Никто не говорил про выпил чего бы там ни было, откуда ты вообще это взял. Я о том, что формула %химикатнейм_в_крови% = %химикатнейм_в_крио% * n мягко говоря странная. Если честно, я буду даже рад, если это не станут трогать, просто от своей любви к химии. Телегу я написал затем что не понимаю сверхразума таких фишек с умножением параметров и почему они должны считаться норм. А все, что было выше, я и так опробовал, ну кроме наноботов.

**Comment by AgRevol** [comment]
Зачем чинить то, что не сломано? Абуз этого возможен только на бумаге. На практике это мусор и бесполезно. Ингейм этого тем более никто не делает

**Comment by Kernstall** [comment]
>Абуз этого возможен только на бумаге.

С чего ты взял? Я сам заливал трикод в крио, если хватало времени со старта игры.

**Comment by AgRevol** [comment]
За такие способы убийства, особенно в реву, тебя постукают. А мешать в крио все что лечит это норма, такова задумка. Дюп для повседневного использования бесполезен (особенно трик, лол)

**Comment by Lancer411** [comment]
При помещении в крио, по достижению нужной температуры тела, менять метаболизм у реагентов в крови пациента на reagent_metabolism / n.
При извлечении из крио, возвращать к начальному значению.

**Comment by Kernstall** [comment]
>А мешать в крио все что лечит это норма, такова задумка.

Госпади, да тут речь не о возможности мешать реагенты, а о десятикратном множителе. Ты часто мешал реагенты в крио? Знаешь что случается с теми, кто таки пробовал? Они заливают 20 кубов условного бикаридина, а еще лучше алкизина, ведь он сразу мозг лечит, и справедливо думают, что все будет в порядке. В итоге 10 алкизина превращаются в 100 и поциент закономерно умирает/сидит в крио еще 20 минут, пока врачи думаю чтожеэтоунассломалося и выводят ему токсины/ловит поломку органов. user-friendly mechanic in a nutshell

>За такие способы убийства, особенно в реву, тебя постукают.
 
Это тоже сказка. Мы плюемся и не любим убийства ассистотой в туннелях, но за убийство передозом постукаем, мы так не привыкли играть. Сам же сказал, фича такая. Я не говорю, что так нужно делать каждый раунд, но место этому способу убийства определенно должно найтись, особенно для тиранов, которые любят срываться на медперсонал.

**Comment by AgRevol** [comment]
10алкизина не превратится в сто, о чем ты? Ни разу в крио никто не умирал от передоза. Ни разу

**Comment by Kernstall** [comment]
![image](https://user-images.githubusercontent.com/16035287/37343192-dbd98654-26d7-11e8-8ee8-4fb347272a7e.png)
![image](https://user-images.githubusercontent.com/16035287/37343318-334a9054-26d8-11e8-9427-8f94aeba3789.png)
![image](https://user-images.githubusercontent.com/16035287/37343337-3fc8f6c2-26d8-11e8-9104-728048d744ec.png)
Всего лишь в 12-13 раз. Агреволь, ты наверное не прочитал строчку

>%химикатнейм_в_крови% = %химикатнейм_в_крио% * n

**Comment by Sakuya-Izayoi** [comment]
Братан палю фичу называется метаболизм

**Comment by Kernstall** [comment]
![image](https://user-images.githubusercontent.com/16035287/37343692-5b2488ea-26d9-11e8-95c3-86a51e447b01.png)
Сакура, палю фичу, лысый успевает вывести из организма 10-15 кубов алкизина из 125

**Comment by AgRevol** [comment]
Я лично мешаю всё что лечит в крио и от передоза никто ни разу не умирал ни в крио ни после него.

**Comment by Kernstall** [comment]
Антитоксин нивелирует токс урон от передоза одним-двумя препаратами, возможно добавляешь трикод. Кроме этого, 10 кубов не криоксадона/клонексадона тратятся в крио за секунд 15, так что до второго пациента божественный коктейль вряд ли доходит )

**Comment by Sakuya-Izayoi** [comment]
Бтв, от анти-токсинов тоже ВНЕЗАПНО бывает передоз, только афаик от него умирают внутренние органы вроде печени и почек. Да и вообще, на практике это не применялось никогда и не будет, ибо для жалкого дюпа в игровых условиях во-первых тебе потребуется задействовать РнД, генетику и заморозить работу медбея. Уж намного проще всё это сделать в химии.

**Comment by AgRevol** [comment]
Гетап прав. Это замораживание работу отдела. Легче сделать это в химии. И да, смеси хватает на весь раунд. У меня не один десяток раундов опыта в медбее и смеси работают прекрасно. Дюпать никто не дюпает. Работает - не трогай

**Comment by WallShrabnic** [comment]
Тебе уже расписали, почему все эти дюпы бесполезны, всё равно тот же кифоторин и меднаноботов не задюпаешь, ЕМНИП

**Comment by Kernstall** [comment]
Кстати, вспомнил еще одну `фишку`. Крио лечит даже когда в нее не вставлен бикер. 
Сакура, я писал выше, отказ органов это лотерея, а кататонику из генетики они ни к чему. Кроме того, майнинг перидаксона решает проблему.
А для майнинга благословенного кукурузного масла мне нужна макака бармена(осторожно)/кататоник и свободное крио со слипером

**Comment by WallShrabnic** [comment]
Вашу проблему "решат" ограничением крио исключительно до криоксадона и клонексодона. И вы завоете

**Comment by AgRevol** [comment]
То, что ты называешь тут абузом это чистая теория и ни капли практики. По факту абсолютно бесполезно, бессмысленно и на практике невозможно, ибо медбей почти никогда не простаивает, а тебе нужно парализовать отдел. Это может быть использовано только для дюпа кукурузы. Чёртовой кукурузы, которой, если нужно, можно вырастить столько, что лагать будет. А ещё открою секрет. Чем больше в крио химикатов тем меньше их тратится и тем меньше их вводится в кровь. При трике+делайте+крио+клоне урон от передоза если и появляется (а он - нет) то мгновенно лечится

**Comment by Lancer411** [comment]
Вам лишь бы порассуждать, выше я написал как пофиксить этот ДУП и сохранить эффективность препаратов.

**Comment by Raschert0** [comment]
Что за наркомания? Каким это обоазом 10 кубов химикатов используются за 15 секунд? Без пруфов не поверю

**Comment by Kernstall** [comment]
@Raschert0 Посмотрел код и нашел вот какие строчки в code/modules/atmospheric/machinery/components/unarydevices/cryo.dm 

```var/has_cryo = occupant.reagents.get_reagent_amount("cryoxadone") >= 1
var/has_clonexa = occupant.reagents.get_reagent_amount("clonexadone") >= 1
var/has_cryo_medicine = has_cryo || has_clonexa
if(beaker && !has_cryo_medicine)
      beaker.reagents.trans_to(occupant, 1, 10)
      beaker.reagents.reaction(occupant)
```
Находится в процедуре process() . Получается так, что если в бикере нет ни криоксадона, ни клонексадона, то реагенты из бикера идут в кровь  в десятикратном размере, причем очень быстро, как я и говорил за 15 секунд. Самый сок что в этой процедуре на первый взгляд нигде не трансферятся реагенты, если в бикере есть клонексадон, это вообще в другом месте. То есть если в бикере нет клона, то реагенты улетают мгновенно, если есть, то очень медленно, но все равно в увеличенном количестве

**Comment by Raschert0** [comment]
А, ну окей тогда
