### ISSUE TITLE
Магосвкая способность Heal не отращивает конечности.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2191]
#### Подробное описание проблемы
Если использовать маговскую способность Heal на седьмом уровне она не отращивает конечности при попадании и вообще никак.
#### Что должно было произойти
Она должна была отрастить конечности.
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/18488106/35489020-f0feaa92-0499-11e8-8464-b291bf835a8f.png)

#### Как повторить
Использовать способность Heal на седьмом уровне на безруком человеке.

**Comment by Olt1771** [comment]
А так же лечить внутренние органы, но проблема в том что при кидке ей постоянно мисс и нельзя седьмым уровнем нажать на себя, опять же будет мисс
