### ISSUE TITLE
Энерго-меч должен резать стулья.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2192]
#### Подробное описание проблемы
Если ударить стуло энерго-мечем (есвордом) он его не поломает.
#### Что должно было произойти
Он должен был превратить его в кусок металла.
#### Что произошло на самом деле
Он просто его ударил.
#### Как повторить
Ударить стул энерго-мечем(есвордом)
#### Дополнительная информация:
А столы режет.

**Comment by Leshiy-ART** [comment]
Наркоман. Столы режет потому что они ходить мешают, а стулья тебе чем помешали?!

**Comment by OfGreyBugWaifu** [comment]
Чтобы можно было как Кайло Рен заплакать и начать мебель по станции портить.
