### ISSUE TITLE
Синга притягивает лучи эмитера

### ISSUE THREAD

**Issue by PavelYo** [TauCetiStation/TauCetiClassic#2193]
#### Подробное описание проблемы
Лучи от эмитера притягиваются к синге как обычные предметы.
#### Что должно было произойти
Лучи от эмитеров не должны были притянутся к синге
#### Что произошло на самом деле
Лучи притянулись к синге
#### Как повторить
Запустить двигатель на сингулярности
#### Дополнительная информация:
![default](https://user-images.githubusercontent.com/28385415/35554009-3a76c86e-05ab-11e8-804c-efa92ffb612f.png)

**Comment by Forrya** [comment]
А что не так то?

**Comment by OfGreyBugWaifu** [comment]
То, что при должной удаче синга засосёт столько лучей, что щиты разрядятся.

**Comment by Forrya** [comment]
Никогда не видел, что бы синга именно насосала столько лучей, что бы поля вырубило.

**Comment by Skippeer12** [comment]
Потому что это визуальный баг спрайта. По механу оно попадает.

**Comment by volas** [comment]
довольно древний баг, и вроде бы это уже чинили, а то и не раз...
