### ISSUE TITLE
Админ проблема поиска ВВ

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#2195]
#### Подробное описание проблемы

Не работает поиск 

#### Что должно было произойти

Работает

#### Что произошло на самом деле

Не работает

#### Как повторить

Зайти в ВВ написать что угодно в поиске и строки не пропадут

#### Дополнительная информация:

Когда-то кто то сломал. Пользуйтесь кнтрл+F

Люблю писать ишуры за педалей 👍

**Comment by Skippeer12** [comment]
Но ведь работает, но не у всех.
![image](https://user-images.githubusercontent.com/18488106/35658846-f425fad0-070b-11e8-9870-6b7932ec7b45.png)

**Comment by Olt1771** [comment]
Ну, как я спаршивал у администрации, у большинства это не работает
