### ISSUE TITLE
Нельзя кинуть 6 уровень хила мага

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#2200]
#### Подробное описание проблемы

Нельзя кинуть 6 уровень хила мага

#### Что должно было произойти

Можно кинуть

#### Что произошло на самом деле

Нельзя кинуть

#### Как повторить

Апнуть хил до 6 уровня и попробывать кинуть

**Comment by Skippeer12** [comment]
Его можно кинуть.
![image](https://user-images.githubusercontent.com/18488106/35775659-a023d998-0995-11e8-8167-a8c4fb3731ed.png)

**Comment by Kurshan** [comment]
Не смог повторить на локалке. Да и Шкиппер утверждает это же. Разберитесь там в себе.
