### ISSUE TITLE
[Bug] Баг с камерой ИИ.

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#2205]
#### Подробное описание проблемы
Летая камерой ии очень часто намертво зависает игра. Приходится перезапускать. Из-за чего это проиходит ? А хер его знает. Летаешь и намертво просто виснет, пока не перезайдешь. А ещё, кстати, когда начинаешь игру за ИИ камера остаётся на месте картинки лобби. Приходится жать AI CORE кнопку.

#### Что должно было произойти
Не должно вылетать и игра должна начинаться с ИИ ядра.
#### Что произошло на самом деле
Игра начинается с камеры на Лобби. А если летать камерой по станции, то порой игра намертво виснет.

#### Как повторить
Зайти за ИИ и полетать камерой по станции. ПРОИСХОДИТ ЧАСТО.

**Comment by Smalltasty** [comment]
Вылеты и зависания по большей части происходят из-за самого бульонда и несовершенства кода и оптимизации. А вот насчет места старта - да, проблемка.

**Comment by volas** [comment]
Вылеты за ИИ - проблема бьенда, в 512 версии исправлено. Но мы пока не можем перейти на 512, она не стабильна.

**Comment by Pirsnya** [comment]
Принял, спасибо.

**Comment by Skippeer12** [comment]
#1425
