### ISSUE TITLE
[BUG] Улучшение телепорт станции.

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#2207]
#### Подробное описание проблемы
В общем, если улучшить телепорт станцию, то не открывается портал.
http://prntscr.com/i9nypo
То, что по середине. Там стоят конденсаторы, стоит заменить их на квадратик конденсы, то перестает открываться портал. Возможно, что такая проблема и с Адвансед конденсами и супер конденсами. 

#### Что должно было произойти
Открыться портал.

#### Что произошло на самом деле
Не открывается.

#### Как повторить
Построить телепорт, улучшить телепорт стейшн квадратик конденсаторами.

**Comment by Pirsnya** [comment]
Возможно, что это связано как с моими кривыми руками, так и с кривыми руками других людей, что, как правило, очень часто происходит. По крайней мере я лично своими глазами видел, что при т4 не работал. Сам пробовал и так же безуспешно.

**Comment by Skippeer12** [comment]
Если тебе пишет вот это:
![image](https://user-images.githubusercontent.com/18488106/35775620-f00b1c4c-0994-11e8-83a2-b53675303499.png)
То тебе нужно открыть панель на машинерии которая по середине и кусачками соединить провода.
![image](https://user-images.githubusercontent.com/18488106/35775625-1e705eda-0995-11e8-8596-093435f3506b.png)

**Comment by Pirsnya** [comment]
huh, шпупер был прав, а я довнич.
