### ISSUE TITLE
[Proposal] М-колл

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2208]
Короче, запилить аналого Аколла - Мколл, который будет призывать всех активных менторов в дискорде/рокетчате

**Comment by Avatar4** [comment]
Менторам будет только хуже. В дискорде есть темка "хелп" где отвечают на вопросы.

**Comment by StrikS** [comment]
Шрубник кинется отвечать на вопросы, заходя в игру. А, он не для себя... Нет, спасибо.
