### ISSUE TITLE
Если у вас есть джоббан на вардена вы не можетей зайти за ОБР

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2213]
#### Подробное описание проблемы
Если у вас забанен варден то вас не пускает за ОБР, хотя есть отдельно бан на ОБР.
#### Что должно было произойти
Вас должно пустить в ОБР если у вас нет бана на ОБР.
#### Что произошло на самом деле
You are jobbanned from the emergency reponse team!
#### Как повторить
Получить бан на вардена и попробовать зайти за ОБР.
#### Дополнительная информация:
Где-то это уже обсуджали, не знаю почему не пофиксили.

**Comment by CryptoKisik** [comment]
Бан охранки = бан ОБР. Ну, ОБР же охранка.

**Comment by Raschert0** [comment]
А, да, кстати

**Comment by Skippeer12** [comment]
Это баг, а не фича.
