### ISSUE TITLE
Телепорт в стенку

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2214]
#### Подробное описание проблемы
Маги, тенелинги, нинжы и ещё кто могут телепортироваться в стену
#### Что должно было произойти
Они не могут телепортироваться в стену
#### Что произошло на самом деле
Первое
#### Как повторить
Использовать абилку на пермещение в стену
#### Дополнительная информация:
N/A

**Comment by Motzord** [comment]
fixed

**Comment by LudwigVonChesterfield** [comment]
#4732
