### ISSUE TITLE
Имба-СВУ

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2215]
#### Подробное описание проблемы
СВУ (самодельнре взрывное устройство) взрывает полы и укреплённые стены
#### Что должно было произойти
Они не могут взрывать укрепки и пол
#### Что произошло на самом деле
Они всё ломают, ассистент в скафандре может выпилить малфа
#### Как повторить
Протестировать ВСУ
#### Дополнительная информация:
N/A

**Comment by Skippeer12** [comment]
А теперь попробуй выпилить ИИ за ассистента в скафандре космическом и с СВУшками.
Приложи видео. Или гифку.

**Comment by Avatar4** [comment]
Они далеко не всегда пробивают стены. К тому же, что бы набрать нормальное количество - нужно постараться

**Comment by Skippeer12** [comment]
@Raschert0 Прийди, порядок наведи.
