### ISSUE TITLE
Бегущий маг не может активировать заклятие Stop Time

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2219]
#### Подробное описание проблемы
Маг не может активировать заклятие Stop Time на бегу.
#### Что должно было произойти
Заклятие должно сработать.
#### Что произошло на самом деле
Игра посчитала что оно выполнилось но эффекта не произошло.
#### Как повторить
Активировать заклятие Stop time на бегу.

**Comment by Avatar4** [comment]
Возможно это случайность и маг прожимает как-то еще не готовый спелл из за чего он просто говорит слово а спелл еще не готов. В любом случае, это минор

**Comment by Skippeer12** [comment]
Потому что у спелла стоп тайм есть таймер на прочьтение, если ты двинишься во время этого то спел не успеет скастоватся и всё прийдется делать с начала.

![image](https://user-images.githubusercontent.com/18488106/35800002-4592bb08-0a70-11e8-8474-9c96d1089d2a.png)
