### ISSUE TITLE
Вейп не парит

### ISSUE THREAD

**Issue by PavelYo** [TauCetiStation/TauCetiClassic#2221]
#### Подробное описание проблемы
С новым спрайтом электронной сигареты пропал пар.
#### Что должно было произойти
Должен был периодически идти парок
#### Что произошло на самом деле
Догадайтесь
#### Как повторить
Засунуть электронную сигарету себе в рот

**Comment by volas** [comment]
@TEXH4Pb

**Comment by TEXH4Pb** [comment]
Это не баг, это фича. :pepe:

**Comment by Pirsnya** [comment]
А что если добавить реальный пар от него 🤔  Типа одного эффекта смоука на один тайл. Или такое нельзя?

**Comment by Forrya** [comment]
При нюке ассистенты с вейпами ставят тактическую паровую завесу.

**Comment by Udokun** [comment]
На каком-то сервере есть сигвеи, можно чуть спрайт подрезать и будут у нас ещё и гироскутеры.

**Comment by Tolerantboy** [comment]
У нас же не вейп, а электронная сигарета, которая старомодная, без густого пара, только вкус и запах имеет. Хотя я еще не видел какой ей спрайт нарисовали

**Comment by KiPakr** [comment]
Раньше был пар, так что иди накуй.
