### ISSUE TITLE
фотоаппарат не все предает на фото

### ISSUE THREAD

**Issue by PavelYo** [TauCetiStation/TauCetiClassic#2222]
#### Подробное описание проблемы
В некоторых случаях когда фотографируешь объекты или же кровь, то либо вещи либо пятна, рисунки, кровь, в данном случае стаканы просто магическим образом исчезают с фотографии. http://prntscr.com/iahlqw и не надо говорить что это фича
#### Что должно было произойти
Стаканы должны были передается на фото
#### Что произошло на самом деле
На снимке нету бокалов с напитком
#### Как повторить
Попробовать снять кровь, пятна и какие нибудь вещи.
#### Дополнительная информация:
Это реально заебало. Играя за репортера подрыв задницы из-за подобного говна случается не редко.

**Comment by Skippeer12** [comment]
#1204
