### ISSUE TITLE
Сломанное клонирование и пересадка головы

### ISSUE THREAD

**Issue by Interl0per1337** [TauCetiStation/TauCetiClassic#2226]
#### Подробное описание проблемы
Допустим - мы получаем тело которое нужно клонировать. У нас есть только голова, тело уничтожено. Мы делаем пересадку при помощи куклы - отрезаем ей голову, пришиваем голову с нужным нам мозгом. По итогу кукла с нужным нашим мозгом помещается в камеру клонирования - и успешно проходит сканирование. Но по итогу когда мы открываем списки - мы не видим кнопки, на которую нужно нажать что бы вернуть человека в игру. Мы видим лишь там новый кружок, который появился, и обозначает одно имя. Но его нету. При этом провести повторное сканирование - не является возможным. Ибо имя уже в базе данных.
#### Что должно было произойти
Мы делаем пересадку, после чего сканируем куклу с нужным нам мозгом - получаем по итогу клон человека у которого был этот мозг. Полноценный клон который был до смерти и уничтожения тела.
#### Что произошло на самом деле
Мы получаем баг, при котором мы не можем клонировать тело - но при этом получаем в список имён сканированных дополнительный кружочек, который обозначает что запись сделана.
#### Как повторить
Берем одного человека, отрезаем ему голову, пересаживаем на куклу другого человека - получаем куклу с мозгом нужного нам человека. Тащим его в генетику, пихаем в камеру сканирования, сканируем, получаем баг и невозможность вернуть игрока в игру.
#### Дополнительная информация:

> ![06def012098f368975203a7e22ce93c9](https://user-images.githubusercontent.com/34056816/35945045-dfe8fef0-0c6f-11e8-8a64-e5126a1f99c8.png)

> ![5163b61711afb50f9e4b437f42d59279](https://user-images.githubusercontent.com/34056816/35945050-e576be8e-0c6f-11e8-9fdd-eed21b659424.png)

**Comment by KiPakr** [comment]
А если не голову пересаживать, а сам мозг?

**Comment by Interl0per1337** [comment]
Получается всё ровно точно так же. Как я понял - если у нас не будет тела, которое принадлежало мозгу - или хотя бы достаточно точной копии с помощью введения энизмов уникальных другому телу - то при пересадке мозга будет такой же казус. 

Но тут встаёт проблема, если тело уничтожено, а у нас на руках лишь голова с мозгом человека - то мы ну никак не сможем получить его энизмы, только если он умудрился оставить резервную копию в генетике. Но обычно там просто сканируются в сканере ради клонирования после смерти. И с такой проблемой которую я описал выше - они не сталкиваются.
