### ISSUE TITLE
Спайкфровер воксиков не выключает инвиз

### ISSUE THREAD

**Issue by JesusForRent** [TauCetiStation/TauCetiClassic#2228]
#### Подробное описание проблемы
Насколько я понял, это все-таки не фича и он сломан.

#### Что должно было произойти
Стелсвокс теряет инвиз после выстрела из спайкфровера

#### Что произошло на самом деле
Вокс в инвизе перемалывает армии врага

#### Как повторить
Включить инвиз вокса и выстрелить из спайкфровера

#### Дополнительная информация:
Это должно быть фичей

**Comment by WallShrabnic** [comment]
Тоже самое, к слову, с дротикомётом

**Comment by LudwigVonChesterfield** [comment]
#2271

**Comment by RichardJones1** [comment]
Стоп, так проблема была решена?

**Comment by Alexofp** [comment]
Давно пофикшено
