### ISSUE TITLE
Нельзя двигаться когда стартует/паркуется шатл.

### ISSUE THREAD

**Issue by KiPakr** [TauCetiStation/TauCetiClassic#2229]
#### Подробное описание проблемы
Я говорю про шатл который летит на станцию. Так вот, думаю все знакомы с тем, когда даже если ты пристегнут, то после отправки ты не можешь двигаться или брать вещи и т.к как будто тебя задизармили. И это продолжается ровно столько же, сколько времени лежит игрок если он не пристегнулся. Недавно вроде удаляли это месте с обновлением интерфейса шатла и добовлением кнопочек в доках, но потом это убрали.
#### Что должно было произойти
После старта шатла, если ты пристегнулся , можно двигаться и "отстегивается" от сидений.
#### Что произошло на самом деле
После старта шатла нельзя ничего делать некоторое время
#### Как повторить
Сесть на шатл отправки на станцию и пристегнуться. После того как шатл стартанет попытатся что то сделать (Переложить вещи из карманов, отстегнуться и т.п)
#### Дополнительная информация:
В общем это какой то баян который почему то некто не хочет убирать.

**Comment by Lexakr** [comment]
Not a bug
