### ISSUE TITLE
ТЭГ сломан. Не Находит Циркуляторов.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#223]
Возможно циркуляторы сломаны.

**Comment by Dennok** [comment]
не инициализируетса

**Comment by Uvash** [comment]
Тег нашитспавленный - работает. Присланный с ЦК - нет. У меня есть подозрение, что из-за спавна в коробке, которая на шаттле который на ЦК  котороее чёрт знает где переменная stat при начальной инициализации получает значение НЕТ ЭНЕРГИИ (2) и дальше не открывает интерфейс. Лечится перезагрузкой оборудования в АПЦ. (Врубить затем вырубить оборудование) А вот как фиксить в коде я хз.

**Comment by Lancer411** [comment]
Похоже проблема в том что когда ТЭГ спавнится в ящике, он получает сигнал на обновление питания от зоны, а никакой зоны в ящике нет, из-за чего он считает что света тоже нет.
И выключается. Генератор выключается так-как нет света, да.
