### ISSUE TITLE
В автомате с сигаретами появились невидимые пачки с сигаретами.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2231]
#### Подробное описание проблемы
После тест мержа фуди в автомате с сигаретами появились мятные сигареты у которых нет спрайта.

![](https://cdn.discordapp.com/attachments/401031448963973120/411172033020428289/unknown.png)

**Comment by Skippeer12** [comment]
Мейнтейнер прийди, плашку тест мержа принеси.

**Comment by Lexakr** [comment]
Закройте, ето пофикшено
