### ISSUE TITLE
Дионы делают исскуственное дыхание.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#2233]
#### Подробное описание проблемы
Дионы могут делать исскуственное дыхание.
#### Что должно было произойти
Дионы не должны делать людям исскуственное дыхание.
#### Что произошло на самом деле
Диона-спасатель бегает в кексмасе и откачивает людей рот-в-рот.
#### Как повторить
Взять диону, сделать исскуственное дыхание.
#### Дополнительная информация:
Воксы, с наполненными азотом лёгкими могли-бы травить людей азотом при дыхании.

**Comment by Smalltasty** [comment]
Но ведь азота 78% в воздухе, разве мы им травимся? :hmm:

**Comment by LudwigVonChesterfield** [comment]
а вы дыхании воксов 100% азота :^)

**Comment by Smalltasty** [comment]
Мы страдаем от отсутствия кислорода, а не от присутствия азота
