### ISSUE TITLE
Синди-риг для Дионей

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#2235]
#### Подробное описание проблемы
Диона-нюкер может носить костюм от синди рига но не шлем.
#### Что должно было произойти
Либо Диона не должна мочь надевать костюм.
Либо Диона должна мочь надеть шлем.
#### Что произошло на самом деле
Ни одно из двух вариантов описанных выше.
#### Как повторить
Попробовать за Диону надеть шлем.

**Comment by igigin** [comment]
![image](https://user-images.githubusercontent.com/17473163/36059616-36027064-0e6e-11e8-8582-8179240ce379.png)
Тут только лишнее сообщение про то, что ты закончил надевать риг.

**Comment by LudwigVonChesterfield** [comment]
Простите, похоже в моменте не обратил внимание на то что риг не надевается. Наверное можно закрыть по ненандобности, бага то нет.
