### ISSUE TITLE
ИИ может наблюдать за шедоулингом в зоне без камер.

### ISSUE THREAD

**Issue by Interl0per1337** [TauCetiStation/TauCetiClassic#2242]
#### Подробное описание проблемы
ИИ наблюдает светящийся спрайт шедоулингов даже сквозь помехи в том месте, где нету камер или они отключены. 
#### Что должно было произойти
ИИ увидел как шедоулинг забежал в технические тоннели - и всё. Больше он не должен его никак наблюдать, если только там нету камер.
#### Что произошло на самом деле
ИИ с легкостью "угадывает" местоположение шедоулинга - что очень дико усложняет ему жизнь.
#### Как повторить
Ставим шедоулинга где нету камер у ИИ - желательно глазками на юг - заходим за ИИ, осматриваем то место где оставляли шедоу - вуаля.

**Comment by Skippeer12** [comment]
Там оверлей глаз видно, так что...

**Comment by RichardJones1** [comment]
Закрываю, есть более новое и полное ишью аватара
