### ISSUE TITLE
Обход ксеноограничений

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2245]
#### Подробное описание проблемы
Ксеноограничения можно легко обойти
#### Что должно было произойти
Ксеносы не могут в установленные профы
#### Что произошло на самом деле
Коты-РД
#### Как повторить
Выбрать любую заблокированную профессию ПОСЛЕ начала раунда
#### Дополнительная информация:
Можно было бы это сделать фичей, но всем как всегда

**Comment by Skippeer12** [comment]
Fixed #2246
