### ISSUE TITLE
Оверлей голокарты при выключении остается на экране.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2253]
#### Подробное описание проблемы
После активации голокарты появляется оверлей который через две-три минуты неприрыврного использвания и отключения остается на экране.
#### Что должно было произойти
Оверлей голокарты должен был пропасть после отключения.
#### Что произошло на самом деле
Оверлей голокарты остался после отключения.
#### Как повторить
Включить голокарту и подождать несколько минут а затем выключить.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/18488106/36174774-0486a816-1116-11e8-8ccd-90bdae787ff5.png)

Фиксится перезаходом в игру.

**Comment by RichardJones1** [comment]
Данной фичи уже нет в билде. Мб филат когда нибудь закончит это дело.
