### ISSUE TITLE
Тау Кита и размножение баков с водой

### ISSUE THREAD

**Issue by FatFatFatFat** [TauCetiStation/TauCetiClassic#2256]
#### Подробное описание проблемы
После смерти фарбота оставляет после себя 3 бака с водой , карту , руку грабли , анализатор и лопатку(которая не используется в создании фармбота) 

#### Что должно было произойти
Он должен был оставить после себя только один бак, без лопатки

#### Как повторить
просто убейте фармбота.
#### Дополнительная информация:
![tau ceti station 2018-02-15 230431](https://user-images.githubusercontent.com/36511952/36267624-f6a2bfcc-12a6-11e8-83c8-fb413080c0c9.png)
![tau ceti station 2018-02-15 230835](https://user-images.githubusercontent.com/36511952/36267611-ea5ee722-12a6-11e8-97ba-849681c0820a.png)

**Comment by Smalltasty** [comment]
И да, оно не оставляло лопатку. Оно оставляло грабельки, которые используются при крафте.
