### ISSUE TITLE
Хуманы не могут выставить никакой ксеновский язык.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2265]
#### Подробное описание проблемы
Клятий Куршан, загрифонил хуманов и теперь они не умеют хисать и мяукать.
#### Что должно было произойти
Хуманы должны иметь возможность выставлять любой язык ксеносов(даже котячий с жестами)
#### Что произошло на самом деле
Они не могут этого сделать.
#### Как повторить
![image](https://user-images.githubusercontent.com/18488106/36361864-373d68aa-1538-11e8-85cb-216a5cbf8c48.png)

#### Дополнительная информация:
Зато клятые коты и ящеры могут понимать сол комон, спасибо что живой. I ded.

**Comment by Pirsnya** [comment]
Что за рофл, шкиппер

**Comment by Kurshan** [comment]
Джаст эс планнед
