### ISSUE TITLE
[BUG] SKIPPER INCOMING(Баг на заброшенном шаттле)

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#2266]
#### Подробное описание проблемы
Провода, которые идут пол полом, их как бы нет, и при подключении пакмана он не видит провода, а следовательно не заряжает апц.
http://prntscr.com/igv2xm
#### Что должно было произойти
Пакман должен присоединиться к проводу.

#### Что произошло на самом деле
Не видит провод под полом, ибо это шатл турф и там не может быть провода.
#### Как повторить
Построить пакман и прикрутить на заброшке.

#### Дополнительная информация:
Шкиппер, попробуй впилить СМЕС туда лучше. Может я дурак и не понимаю как в пакманы?

**Comment by DieSiege** [comment]
Провод есть же. СМЕС и пакман там легко можно установить, но с лишними телодвижениями. Снять шаттлотурф и переложить провод на который устанавливаешь машинерию. Сэйм щит с установкой дополнительных СМЕСов на станции бывает.
