### ISSUE TITLE
Госты и клонирование [Proposal]

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#2269]
Играя на вашем замечательном сервере столкнулся с проблемой. 
Игрок не может клонироваться сам если его персонаж уже записан. В результате чего сама запись в клонилке не имеет особого смысла. Даже находясь в базе данных клонера игрок обязан ждать того, чтобы его кто-то клонировал, что порой бывает затруднительно ибо мед состав может быть не в курсе о смерти пациента.

Предлагаю добавить возможность гостам персонажи которых записаны в базу данных клонера, клонироваться самому.

**Comment by LLIkolnik** [comment]
Автоклонер.
ТГ.

**Comment by WallShrabnic** [comment]
Автоклонер уже есть. А вообще, есть импланты уведомления о смерти и это фича

**Comment by Skippeer12** [comment]
> это фича

Фичи тут нет. Автоклонер работает только на 50%, можно только сканировать.

**Comment by WatlerJe** [comment]
Даже с имплантом уведомления вероятность того, что о записи чара кто-то вспомнит крайне мала.
