### ISSUE TITLE
Эмоуты видно из лобби.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#2270]
#### Подробное описание проблемы
Если перевести игру в оконный режим и свернуть-развернуть её, находясь в лобби, будут видны эмоуты.
#### Что должно было произойти
Их не должно быть видно.
#### Что произошло на самом деле
Их видно.
#### Как повторить
Зайти в лобби, перевести игру в оконный режим, свернуть, развернуть.
#### Дополнительная информация:
![](https://i.gyazo.com/245366dc597a4bc90f4b1b1bcffb846b.png)

**Comment by Biniti7** [comment]
Подтверждаю. Зашёл в игру, и наблюдаю следующее: http://prntscr.com/ihb1as
