### ISSUE TITLE
Ремап доков-коков [Proposal]

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#2275]
Считаю нужным поднять вопрос о ремапе доков для шахтерского/научного шаттла на станции и на научной базе. На текущий момент, ввиду отсутствия системы синхронизации шлюзов с летающей маршруткой, ЧП с разгермой участились.

В связи с этим предлагаю сделать вот что:

**Научная база:**
![70b2e87d2d59346348e8cf130b63384c](https://user-images.githubusercontent.com/19796920/36579849-59d19602-1876-11e8-89b1-3edc886da1d7.png)
Сместить трубы на один тайл на север, тем самым освободит площадку для шаттла. 
Сам шаттл сместить до упора на восток и на два тайла на севере. 
Коридор шлюза расширить до двух тайлов и сместить к входному шлюзу шаттла.

**Станция:**
![ae1b9e4eabf5de06d1ee9f81aa9dedd7](https://user-images.githubusercontent.com/19796920/36579882-9fa9e90e-1876-11e8-88e7-0ba50b41f604.png)
Расширить док и расширить шлюз до двух тайлов. Убрать комнату с костюмами аномалистов, костюмы положить рядом с консолью огородив стеклянной дверцей с соответствующим доступом.

Таким образом в связи с увеличением пути и установки дополнительной двери, у шлюза появляется возможность закрыться раньше чем отлетит шаттл, что предполагает недопущения развития разгерметизации в доках

**Comment by LudwigVonChesterfield** [comment]
Ну ремап уже в процессе. Это считается? #2605
