### ISSUE TITLE
Карбоны не могут в ЦПР[Test Feedback]

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#2277]
#### Подробное описание проблемы
Карбоны не могут в ЦПРС

#### Что должно было произойти

Они могут

#### Что произошло на самом деле

Не могут

#### Как повторить

Заспавниться карбоном

#### Дополнительная информация:

#2250

**Comment by LLIkolnik** [comment]
...почему они должны уметь в ЦПР

**Comment by Smalltasty** [comment]
Почему хуманы не должны уметь в искусственное дыхание? 
Все, кто не синтетики - карбоны. Дионы типа тоже карбоны, но они не дышат, потому они не должны уметь в ЦПР. А вот ящуры, коты, жабы и люди - должны.

**Comment by LLIkolnik** [comment]
а, а, понял, понял.

**Comment by Olt1771** [comment]
Закройте пожалуйста, спасибо
