### ISSUE TITLE
генокрады не могут в вентиляцию за макак

### ISSUE THREAD

**Issue by 241214234343** [TauCetiStation/TauCetiClassic#2280]
#### Подробное описание проблемы
при попытке пролезть в вентиляцию за макаку пишет "You can't carry [кукланейм] while ventcrawling!" и не даёт пролезть.
#### Что должно было произойти
что то вообще лень писать блин сами догадаетесь
#### Что произошло на самом деле
тут тоже догадаетесь
#### Как повторить
скушать человека и попытаться пролезть в вентиляцию за макаку
#### Дополнительная информация:
если не кушать человека а сразу пролезть в вентиляцию то возможно такой проблемы не будет

**Comment by DieSiege** [comment]
Чекал это дело и повторил. Если через ВВ удалить все эссенции с тушки - она снова сможет ползать в вентам.
@Kurshan
