### ISSUE TITLE
IT'S TIME TO VOTE(ob) [Proposal]

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#2284]
Предлагаю продлить время воута с 1:30 до 2:00. Полтора часа - катастрофически мало и 99 процентов голосуют, потому что сидят в обзёрве или им не выпала роль. Если народ всегласно требует воут - делать его на полтора часа, а то и раньше(допустим, если на станции 3,14здец). Безумно бесит, когда на станции чистота и порядок и какой-нибудь жмурик жмёт на кнопку Крю Трансфера, а большинство даже поменять голос не может, иногда случается, что мисскликаешь(у меня, допустим, такое очень часто). Я считаю, что стоит вернуть старый тайминг на воут. Полтора часа - мало.

**Comment by WallShrabnic** [comment]
Лол, в раундах и так ничего не происходит, а ты предлагаешь ещё и время увеличивать, иди и строй свой Токомак

**Comment by Pirsnya** [comment]
А что должно происходить? Мясо, кишки, кровь? Ну так иди в ВОВ моды играй, если тебе это нужно.

**Comment by Skippeer12** [comment]
Вы оба не правильно смотрите на проблему и не правильно её пытаетесь решить.

Для начала нужно отобрать у всех гостов возможность воутить, после чего сделать воут исключительно через сервер. Время можно оставить то же.

**Comment by Pirsnya** [comment]
Именно это я хотел здесь увидеть, шкиппер, ты гений.

**Comment by WallShrabnic** [comment]
Шкиппер тоже неправильно смотрит, на данный момент лучшую идею высказал Ольт - разрешить голосовать всем, кто наиграл в раунде 20-30 минут. Иначе нюка/Генки/другой режим будут вырезать станцию под ноль и затягивать раунд на часы

**Comment by StrikS** [comment]
Лол, от этого уходили, а теперь предлагаете вступить снова в это. Всегда те, кто не успел за отведенное время будут недовольны, но заставлять остальных ждать того, что хотят _от силы_ 15% говноедство.
Не стоит забывать про то, что это сессионная игра и полуторачасовой формат является идеальным по затянутости. Бомжи и строители страдают, да. Но тут нужна система сейвлоада, а не удлинение раунда.
Поддерживаю вариант 30 минут стажа игры в раунде для воута. А воут автоматический.

**Comment by Tolerantboy** [comment]
Шкипер, конечно, гений. Прям гениально, когда вся станция мертва, на ней сидит один выживший клоун и ехидно смотрит на бугуртящих мертвецов дэтчата, которые не могут остановить эту робинзонаду

**Comment by Skippeer12** [comment]
Зато вот после таких "робинзонад" будет намного меньше ассистентов которые захотят выпилить рольку и ролеплей с колен подними. Одним выстрелом двух зайцев.

Ролька не выпиливает гражданский персонал, если тот не пытается выпилить её. Конечно же есть исключения из этого, но это либа аутист которого забанят после раунда или же нюка, но там раунд кончается по хотению антагов в любом случае.-

**Comment by Uvash** [comment]
Были раунды и на 2 часа. Даже мне как шахтёру/мусорщику надоедало... 1.5 часа наиболее оптимальный вариант.
Если что лучше тогда воут на антагов сделайте....

**Comment by wadangel** [comment]
Тогда почему бы не отобрать воут у обсервов, оставив его для мертвецов?

**Comment by WallShrabnic** [comment]
Потому что некоторые особо умные после начала раунда сразу идут в крио, да, Пирсня?

**Comment by Pirsnya** [comment]
@WallShrabnic , однако прошу заметить, что воуты кликаю я крайне редко. В основном выхожу, чтобы последить за игрой. Чаще всего это происходит, потому что, как все знают, я люблю в строечку, а иногда строечка бессмысленна :pekabest:

**Comment by WallShrabnic** [comment]
Строечка бессмысленна всегда
