### ISSUE TITLE
FIRELOCK [bug]

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#2286]
#### Подробное описание проблемы
Отсутствие пожарного шлюза.

#### Что должно было произойти
Должен быть.

#### Что произошло на самом деле
Его нет ибо кто-то проебался с ПОВЕРХМАППИНГОМ.

#### Как повторить
Запустите билд.

#### Дополнительная информация:
http://prntscr.com/ijmq4u

**Comment by Skippeer12** [comment]
Тасти уже знает об этом и пытается фиксить. Но спасибо за Ишусу.

**Comment by Smalltasty** [comment]
Я пофикшу это как только Уоллес разберется с тест мержами и апдейтами карты, ибо из-за конфликтов я не могу пока что его вернуть.
