### ISSUE TITLE
Нашивки отделам [Proposal]

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#2291]
В билде присутствуют такие нашивки:
http://prntscr.com/il1gnt
Но найти я мог их только в мусоре и пришел к выводу, что они только там. Предлагаю добавить в каждый отдел по штук 5-10 этих штучек, ибо это удобно.

**Comment by LudwigVonChesterfield** [comment]
Это нашивки для СБшников, чтобы те определялись какой отдел охранять будут, таков был изначальный задум.

**Comment by Skippeer12** [comment]
Ващет, там есть смешание нашивки секурити-РнД или секурити-инжинерка.
А не смешание должны были выдаватся в шакафу, но это фича с бея, а карту никто под это не подготовил.

**Comment by FelixRuin** [comment]
что-то ишус выполнен, но не закрыт
