### ISSUE TITLE
Хедслаг генокрада умеет открывать двери.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2292]
#### Подробное описание проблемы
Хедслаг генокрада убегает на суперскорость по коридору и открывает закрытые двери.
#### Что должно было произойти
Он не смог открыть двери.
#### Что произошло на самом деле
Он открыл двери и убежал.
#### Как повторить
Хедслаг@Дверь
#### Дополнительная информация:
Венты не нужны.

**Comment by StrikS** [comment]
Общего доступа же... вполне нормально, учитывая, что все побегут к ближайшей венте, чтобы его зажопить у неё. А так открыл дверь и отдалился на безопасное расстояние и уже пополз по венте в закрытые отсеки. А вот то, что он таскать людей может, это да... но это уже другой разговор.

**Comment by Skippeer12** [comment]
А теперь расскажи мне, чем отличается хедслаг от борера?
Когда найдешь отличия (придумаешь их) напиши.
А пока ЧЕРВЯКИ не должны открывать двери, даже без доступа.

**Comment by SkLepP** [comment]
Борер имба, которых миллион на станции. Один человек может наспавнить неограниченное количество бореров. Отсюда и урезание статов и возможностей. Единственное что не очень в слагах, так это невозможность лазать под столами и на столах.

**Comment by Skippeer12** [comment]
Значит открывание дверей и сверх звуковая скорость на которой он может пулить шкаф с трупами, чтобы открыть его где-нибудь в техах это очень?

Отличные у вас виденье о балансе сэр.
Борер выпиливается одним попаданием лазера когда в хедслага нужно попасть два раза.

**Comment by StrikS** [comment]
Пул за слага отдельная тема, не надо сюда её примешивать.

**Comment by Uvash** [comment]
Если генокрад обосрался на столько, что его поймали и тащат в крематорий, то это проблемы генокрада.  Двери у нас не реагируют на мышей и бореров, как следствие не должны реагировать и на слага.
