### ISSUE TITLE
[Proposal] вши

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2308]
Предлагаю добавить таяран вшей. Вши должны кусаться, размножаться, вызывать боль и замедлять. Поражают всех здоровых котов в радиусе двух тайлов от кота со вшами. Вычёсываются расчёской или когтями другого кота. Можно убивать ядами из химии.

**Comment by WallShrabnic** [comment]
Сейчас кому-то прилетит бан на гитхаб. @Kurshan @volas @Raschert0  я призываю вас!

**Comment by SpaiR** [comment]
![image](https://user-images.githubusercontent.com/12721311/37050732-b4db8fa4-2185-11e8-9d61-49daf10c9f10.png)

http://tauceti.ru/forums/index.php?topic=1574.0

**Comment by Sakuya-Izayoi** [comment]
Это вы мою замечательную идею сравниваете с флудом?
