### ISSUE TITLE
Не работает кнопку Never for this round в диалоге про диону

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2312]
#### Подробное описание проблемы
Если в диалоговом окне "Someone harvested diona pod..." нажать Never for this round, то предложения не перестанут появляться

#### Что должно было произойти
Не должно больше появляться диалоговых окон.

#### Что произошло на самом деле
НИЧЕГО ХОРОШЕГО

#### Как повторить
Иметь активного госта и попытаться вырастить диону в гидропонике.

**Comment by Belfogor** [comment]
Как альтернатива, можно самостоятельно отключить через преференсы.
