### ISSUE TITLE
[Proposal] Добавить ученым и РД доступ в теха.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2321]
Причина одна - аномалии.

**Comment by WallShrabnic** [comment]
Какие?

**Comment by Sakuya-Izayoi** [comment]
Юзайте теленауку.

**Comment by Skippeer12** [comment]
Зачем нам двери, давайте телепорт использовать, который в узких тех.туннелях не работает. Спасибо.

**Comment by Sakuya-Izayoi** [comment]
Всё прекрасно работает. Просто нехрен ваши калькуляторы использовать для калибровки. А так, по теме, доступ учёных прекрасно сбалансирован, как ролеплейно, так и геймплейно.

**Comment by Skippeer12** [comment]
А играл бы ты больше на ученых, словил бы в теха инженерного пирокластик. Вот тогда бы ты заговорил по другому. Эни вей, это просто чтобы я не забыл это впилить. Я не прошу никого из вас это делать.

**Comment by StrikS** [comment]
Взаимодействие, Шкипер. Ты же про него говорил? 
Пустите Шкипу в теха, а то его любимый РД туда не может...
