### ISSUE TITLE
Сломанные хит эксченджеры не обмениваются температурой

### ISSUE THREAD

**Issue by DieSiege** [TauCetiStation/TauCetiClassic#2326]
#### Подробное описание проблемы
Хотел сделать убербимбу на локалочке со снятым капом, но столкнулся с уберсуперским атмосом Зве. Отличная вещь своего времени Heat Exchanger - сломана. Оно позволяло трубам обмениваться температурой без смешения газов и создания камер сгорания с теплообменным контуром. 
#### Что должно было произойти
Газы в трубах должны были обменяться температурами. Контур сверху должен был обменяться температурой с контуром снизу
![3djhlzxrruccamqwtfp5cg](https://user-images.githubusercontent.com/23117255/37251856-a710ef26-2528-11e8-982e-bed2463105e0.png)
#### Что произошло на самом деле
Температура в самих хит эксчейнджерах оставалась в 20°С. Газы в трубах не обменивались температурой
#### Как повторить
Собрать подобную схему
#### Дополнительная информация:
Тестировал это с почти всеми видами труб. С обычными и теплообменными, помпами, выдача/фильтр и адаптером оно никак не работает. Судя по всему они просто не подключаются с системе.

**Comment by Pirsnya** [comment]
Но  у тебя даже трубы не нагреты

**Comment by Sakuya-Izayoi** [comment]
бтв анализатор газов работает только на элементарных трубах, на остальных девайсах почему-то нет

**Comment by LudwigVonChesterfield** [comment]
#2634
