### ISSUE TITLE
СПУ в главы

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#2335]
#### Подробное описание проблемы
На википедии инфа, что спу могут в главы

#### Что должно было произойти
СПУ должны быть в главах

#### Что произошло на самом деле
СПУ заблокированы в главах недавним ограничением

#### Как повторить
Создать СПУ и попробовать зайти за главу

#### Дополнительная информация:
Обновили вики, обновите механ :pepe:

**Comment by LudwigVonChesterfield** [comment]
Мёрж тости который это фиксить ещё не добавили просто. #2288

**Comment by Skippeer12** [comment]
Кто-то не читает ченж логов. Не круто.
