### ISSUE TITLE
Отвалились спрайты у растений растущих в гидропонных лотках

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#2339]
#### Подробное описание проблемы
У множества растений (не у всех) отвалились спрайты на всех этапах роста. От посадки до сбора урожая. 

#### Что должно было произойти
В гидропонных лотках должны были отображаться растения. 

#### Что произошло на самом деле
Их там нет. 

#### Как повторить
Посадите (к примеру) морковь в гидропонный лоток

#### Дополнительная информация:
Зуб даю, что во всем виновата Тесто.

**Comment by volas** [comment]
Если спрайты там из ``hydroponics/hydroponics.dmi``, то возможно связанно с большим количеством стейтов
