### ISSUE TITLE
Боргу малфа не выдает законы малфа.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2345]
#### Подробное описание проблемы
У борга который в начале раунда появляется вместе с малфом - стандартные законы.
#### Что должно было произойти
У борга должны быть законы малфа и говориться вначале что у него законы как у малфа.
#### Что произошло на самом деле
У него обычные законы.

**Comment by Skippeer12** [comment]
#1782 дубликат.
