### ISSUE TITLE
Нанесение вреда за голограмму малфа не работает.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2346]
#### Подробное описание проблемы
Нанесение вреда за голограмму малфа не работает.
#### Что должно было произойти
При клике за голограмму на космонавта - ему должен наноситься урон.
#### Что произошло на самом деле
Голограмма только преследует тушку персонажа.
#### Как повторить
За малфа активировать функцию нанесения вреда персоналу за голограмму, активировать ее во кладке малфа, кликать за голограмму на хумана

**Comment by Motzord** [comment]
Не актуально(?)

**Comment by LudwigVonChesterfield** [comment]
Возможно Аватар не брал диаграмму карпа
