### ISSUE TITLE
Тазер более не логируется. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#2348]
#### Подробное описание проблемы
Тазер более не логируется. По всей видимости сломали недавно (не более двух недель как).

#### Что должно было произойти
Тазер должен был логироваться. 

#### Что произошло на самом деле
Он не логируется не в ВВ логи, ни в классические атак логи. 

#### Как повторить
Постреляйте в кого-нибудь с тазера

#### Дополнительная информация:
Стоило бы устранить этот баг в кратчайшие сроки. 

![screenshot_2](https://user-images.githubusercontent.com/12851693/37538562-a600e714-2959-11e8-9b0e-9d85317662aa.png)

**Comment by Belfogor** [comment]
Выяснилось, что аналогичная проблема с солью в дробовике.

**Comment by LudwigVonChesterfield** [comment]
Выяснилось, что аналогичная проблема со всем, что не наносит брут/бёрн дамага.
