### ISSUE TITLE
У кондитмент боттле нет проверки на рейндж

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2355]
#### Подробное описание проблемы
У боттле для кондитмент нет проверки на расстояние

#### Что должно было произойти
Боттле для кондитмент можно разливать только в ближайшие контейнеры

#### Что произошло на самом деле
Боттле для кондитмент можно разлить в любой контейнер в пределах видимости

#### Как повторить
Взять бутылку с энзимами, клинуть по пачке муки на другом конце карты

#### Дополнительная информация:
Сука верните энзимы

**Comment by Forrya** [comment]
Не баг, а фича.

**Comment by Sakuya-Izayoi** [comment]
> У чего

That's Condiment Bottle.
