### ISSUE TITLE
Замен разумов между мематической аномалией и носителем сломан.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2360]
#### Подробное описание проблемы
Если мематическая аномалия использует захват разума и если в это время убить тушку человека которого он захватил, то человек не возвращается обратно в свое тело. И ничего не может сделать, ни гостунутся ни прожать респавн, в то время как мематическая аномалия навсегда занимает тело носителя.
#### Что должно было произойти
Мематическая аномалия должна была вернутся оттуда куда пришла и умереть вместо разума тела.
#### Что произошло на самом деле
Мематическая аномалия захватило тело и осталась там жить.
#### Как повторить
Убить человека которого захватила мематическая аномалия.
#### Дополнительная информация:
Выпилите этуй хуйню вообще, господи, отвратительный режим.

![](https://i.imgur.com/NA0rSos.png)

**Comment by KIBORG04** [comment]
Выпилили
