### ISSUE TITLE
Воскрешение генокрадов багается и перестает работать

### ISSUE THREAD

**Issue by Misakiwa** [TauCetiStation/TauCetiClassic#2363]
#### Подробное описание проблемы
Иногда происходит некий баг, в итоге по клику на "регенерейт стазис" ничего не происходит, а кнопка регенерейт не появляется ни при каких обстосятельствах.
Помню, когда-то давно это случалось, меня не могли воскресить даже через админ-консоль.
#### Что должно было произойти
Кнопка "регенерейт" должна была появится и, соответсвенно, я должен был воскреситься.
#### Что произошло на самом деле
Ничего не появилось.
#### Как повторить
Поймать баг за генку.
#### Дополнительная информация:
Противный баг.

**Comment by Skippeer12** [comment]
> Поймать баг за генку.

Это конечно звучит просто, но ты либо пиши подробности что ты делал и после чего это произошло, либо не пиши вообще.

**Comment by Olt1771** [comment]
Да есть такой баг и условия выполнения его не ясны.

**Comment by Skippeer12** [comment]
>Да есть такой баг и условия выполнения его не ясны.

Я знаю лишь один способ, это если ты прожмешь стазис перед тем как тебя сьест другая генка, кнопка регенерейт появится, а восстановить силы ты уже не сможешь.
Но это не баг, оно так и должно работать.

**Comment by Misakiwa** [comment]
Я дрался с сб, сперва нажал стазис, потом отказался, а после Крита уже не смог его прожать.

**Comment by LudwigVonChesterfield** [comment]
#4890
#4009
