### ISSUE TITLE
В операции по удалению имплантов/шрапнели нет возможности выбрать что удалить первым.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2365]
#### Подробное описание проблемы
В моменте где нужно искать имплант/шрапнель нет окошка, где можно выбрать что удалить первым а что оставить.
#### Что должно было произойти
Должно появится окошко, в котором можно выбрать что удалить.
#### Что произошло на самом деле
Окошка нет, удаляется всё в рандомном порядке и приходится доставать даже импланты если шрапнель застряла в месте где был имплант.
#### Как повторить
Провести операцию по удалению шрапнели.

**Comment by Motzord** [comment]
Пофикшено, закрывайте

**Comment by FelixRuin** [comment]
> Пофикшено, закрывайте

чем пофикшено?

**Comment by Motzord** [comment]
> > Пофикшено, закрывайте
> 
> чем пофикшено?

твоим пром

**Comment by FelixRuin** [comment]
> > > Пофикшено, закрывайте
> > 
> > 
> > чем пофикшено?
> 
> твоим пром

лел, я немного так не смог придумать нормального плана действий как переделать всё на более адекватное, поэтому пр закрыт и не замёржен

**Comment by Motzord** [comment]
Пофикшено, теперь аткая возможность есть

**Comment by Motzord** [comment]
Пофикшено, закройте уже это ишью ради бога

**Comment by KIBORG04** [comment]
разве?

**Comment by Sakuya-Izayoi** [comment]
Если пишешь что пофикшено, прикладывай сразу номер ПРа
