### ISSUE TITLE
Тексты высших теленгов видно из лобби

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2367]
#### Подробное описание проблемы
Тексты высших теленгов видно из лобби
#### Что должно было произойти
Их не должно быть видно из лобби
#### Что произошло на самом деле
Их видно из лобби
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/19417166/37729950-0aa96dda-2d47-11e8-8d54-0678ec1de0d7.png)

**Comment by Skippeer12** [comment]
Тут всё окей, это сообщение о конце раунда, наравне с вызовом шаттла или взрывом нюки.

**Comment by WallShrabnic** [comment]
Или вызовом Нар-Си. Тем более, по сути это превращение в бога, ломание четвёртой стены и всё такое

**Comment by KuzyXD** [comment]
Работает как и предполагалось.

**Comment by volas** [comment]
анонсы/шаттлы/прочее кстати не видны сейчас из лобби, если тенелинги туда пробиваются то это баг

**Comment by KuzyXD** [comment]
Проверим.
