### ISSUE TITLE
Аварийная заслонка закрывается быстрее чем персонаж перелазит через стол.

### ISSUE THREAD

**Issue by Elestrin** [TauCetiStation/TauCetiClassic#237]
#### Подробное описание проблемы
Аварийная заслонка при атмосферной тревоге закрывается быстрее чем персонаж перелазит через стол. При атмосферной тревоге невозможно перелезть через стол, если на его тайле есть атмосная аварийная заслонка.
#### Дополнительная информация:
Возможно это - фича.

**Comment by Dennok** [comment]
просто ктото не может в механ и открытие створок А) ломиком Б) когда она закрылась
Вы еще напишите про то что стеклянная дверца слишком разно зак-ся.
