### ISSUE TITLE
Сломанный анализатор здоровья

### ISSUE THREAD

**Issue by Interl0per1337** [TauCetiStation/TauCetiClassic#2370]
#### Подробное описание проблемы
Доктора, которые пытаются анализировать тушки хуманов с помощью ручного медсканера ( Health Analyzer. ) - жалуются на то, что табличка с уроном и внутренними травмами - не показывается в чате. По итогам даже через логи не удается обнаружить использование медсканера - там лишь пустота.
#### Что должно было произойти
Берем сканер в руки, сканируем тушку - получаем данные про сломанные кости, урон, брейндамаг, нехватку крови - и так далее.
#### Что произошло на самом деле
По итогу сканер вообще не применяется на тушку, таблички нету, доктора разочарованы - и идут в большой стационарный сканер.
#### Как повторить
Взять любой анализатор на карте/сделать новый на автолате - попробовать сканировать раненную тушку
#### Дополнительная информация:
Анализаторы здоровья в ПДА всё еще работают, но как известно функционал там довольно урезаный. Так же анализатор здоровья теперь работает в качестве анализатора киборгов - повторить можно примерно так же.

**Comment by LudwigVonChesterfield** [comment]
#2304 

Чисто моя вина, буду смотреть что не так.
