### ISSUE TITLE
Проблемы с новыми парамедиками

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#2376]
#### Подробное описание проблемы
Парамедики спавнятся без части эквипы и как АВД в самому низу списка

#### Что должно было произойти

они должны были заспавнится в медбэе и с эквипой

#### Что произошло на самом деле

Они заспавнили без эквипы и в конце крю манифеста

#### Как повторить

По идее зайти за новых парамедиков

#### Дополнительная информация:
http://prntscr.com/iuttab
Возможно проблема ещё в этом

**Comment by volas** [comment]
Черт знает, проверил стартовый спавн и лейт спавн - в эквипе, вроде всё ок
