### ISSUE TITLE
Анализатор здоровья не показывает урон по частям тела.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#2378]
#### Подробное описание проблемы
Анализатор здоровья не показывает урон по частям тела.
#### Что должно было произойти
Анализатор здоровья должен показывать урон по частям тела.
#### Что произошло на самом деле
Анализатор здоровья не показывает урон по частям тела.
#### Как повторить
Повредить куклу, кликнуть по ней анализатором.
#### Дополнительная информация:
![](https://i.gyazo.com/266084746c065e123d6f00fd1a198ace.png)
![](https://i.gyazo.com/107f02c2f25efd55db6eb04549eaa41f.png)

**Comment by volas** [comment]
Ошибки случаются, относитесь к этому с пониманием
