### ISSUE TITLE
[BUG] Сломанное похищение людей у воксов

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#2381]
#### Подробное описание проблемы
При похищении человека воксами не даётся гринтекст.

#### Что должно было произойти
Должен быть гринтекст.

#### Что произошло на самом деле
Редтекст.

#### Как повторить
Своровать за вокса.

#### Дополнительная информация:
Писал об этом ишшур, но никто не взялся. Может кто-нибудь всё-таки попробует?
http://prntscr.com/ivguys

**Comment by Pirsnya** [comment]
#2141

**Comment by WallShrabnic** [comment]
За создание дубликата надо дать тебе по жопе. Серьёзно, про этот баг знают, повторное ишью не ускорит его решение
