### ISSUE TITLE
Ограждающие ленты создают препятствие мобам, которые не имеют возможности взаимодействовать с ними. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#2382]
#### Подробное описание проблемы
Ограждающие инженерные/офицерские ленточки не редко используются для препятствия мобам, которые не имеют фактической возможности взаимодействовать с ними (допустим черви генокрадов, люди в наручниках, мыши и т.д.). Это эффективный и доступный способ часто абузится игроками. м. 

#### Что должно было произойти
Мелкие мобы должны беспрепятственно проходить сквозь ленты

#### Дополнительная информация:
Фактически тут вся проблема кроется в охуенном механе лент, которая пропускает сквозь себя лишь людей с доступом, что вообще является нелогичным. Можно конечно сделать исключения для определенных мобов, но это будет очередным костылем. Этот баг репорт является одновременно предложением по перепилу этого доисторического говна в человеческий вид.

**Comment by Morair** [comment]
Вообще следует удалить все ленты, они 70% используются чтоб абузить. 
![image](https://user-images.githubusercontent.com/37118270/63129802-f7ebb300-bfd1-11e9-9171-37567e738f2a.png)
