### ISSUE TITLE
Летающие трэи морга

### ISSUE THREAD

**Issue by AgRevol** [TauCetiStation/TauCetiClassic#2384]
#### Подробное описание проблемы
Если открыть "холодильник" морга в случае, если педали активировали отключение гравитации на станции, сам трэй полетит по направлению в ту сторону, в которую он открывается. То есть именно что полетит, как будто его толкнули.
#### Что должно было произойти
Трэй должен был остаться прямо перед холодильником.
#### Что произошло на самом деле
Трэй полетел исследовать противоположную стену.
#### Как повторить
Педально отключить гравитацию на станции и попытаться открыть холодильник морга.
#### Дополнительная информация:
Это мелочь, но для галочки отписался тут. При повторном клике на холодильник, трэй возвращается внутрь как и обычно.

**Comment by T6751** [comment]
Resolved by https://github.com/TauCetiStation/TauCetiClassic/pull/6125
