### ISSUE TITLE
[bug] Поломанная буква Я в некоторых месажах

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#2388]
#### Подробное описание проблемы
В некоторых объявлениях ( пока видел анонс http://prntscr.com/iw80ff и, вроде бы как, так же с ивент инфо(то ето не точно) )

#### Что должно было произойти
Буква Я должна отображаться нормально

#### Что произошло на самом деле
Буква Я пропадает в аннонсах админов

#### Как повторить
Сделать аннонс админа http://prntscr.com/iw80ff

#### Дополнительная информация:
http://prntscr.com/iw81vu

**Comment by Pirsnya** [comment]
#2123

**Comment by Belfogor** [comment]
Буква я так же пропадает при выдачи ачивки. Так при выводе на экран ИИ новых законов. При использование SM сообщений. Если чего еще вспомню, дополню.

**Comment by Sakuya-Izayoi** [comment]
#1528

**Comment by Skippeer12** [comment]
Есть ещё баг с мемасов, если тот пытается писать сообщения через /me то буква "Я" теряется
