### ISSUE TITLE
Карпы не убиваются горелкой.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#2393]
#### Подробное описание проблемы
Если на вас напал карп, то горелкой его невозможно убить.
#### Что должно было произойти
Карп должен умереть от ударов горелкой.
#### Что произошло на самом деле
Он убил хумана.

**Comment by Pirsnya** [comment]
Не баг, а фича.

**Comment by Tolerantboy** [comment]
@Pirsnya С каких пор? Всегда использовали горелку как импровизированный огнемет против карпов
