### ISSUE TITLE
Синтеты видят через инвиз

### ISSUE THREAD

**Issue by JesusForRent** [TauCetiStation/TauCetiClassic#2394]
#### Подробное описание проблемы
Нинжа итак убит в хлам, так его инвиз ни коим образом не помогает против ИИшки и боргов.

#### Что должно было произойти
Нинжа движется незаметно, словно ветер в траве

#### Что произошло на самом деле
Нинжа ловит один тазер от борга и его унижают щитсеки

#### Как повторить
Посмотреть на нинжу за синтета

#### Дополнительная информация:

**Comment by Skippeer12** [comment]
Не баг, а фича.

**Comment by AgRevol** [comment]
Не баг, а фича

**Comment by KuzyXD** [comment]
Ниндзя использует оптический камуфляж, а не расщепляется на атомы, чтобы пропускать тазер.
