### ISSUE TITLE
Шахтерские очки.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#240]
#### Подробное описание проблемы
Шахтерский худ не видит руду:
Уголь, Платину, Водород.
Некоторая руда отображается не коррекно:
Золото и Серебро идут под один значек с Железом.
#### Что должно было произойти
У каждой руды должен быть свой значек.

#### Что произошло на самом деле
А их нет.
#### Как повторить
Берем очки и надеваем.

**Comment by Dennok** [comment]
>Золото и Серебро идут под один значек с Железом.
Эт так было уже давным давно и в общем так задумано. а все потому что это металлы.

**Comment by Dennok** [comment]
А зачем закрыл? Уже можно видеть через очки Уголь, Платину, Водород?

**Comment by Skippeer12** [comment]
Ради угля собственно и писал. А Платину и Водород удобно копать только через большой бур.

**Comment by Dennok** [comment]
Ну. У платини шанс нахождения примерно такойже как и у алмазов
