### ISSUE TITLE
Баг со слепотой дион на руках

### ISSUE THREAD

**Issue by Kernstall** [TauCetiStation/TauCetiClassic#2403]
#### Подробное описание проблемы
Дионы, сидящие на ручках и на голове, слепы и видят только под собой. Если тебя посадили на ручки, когда ты афк, то при возвращении ты будешь видеть все нормально. Думаю, такая же ситуация и с мартыхами/котами/и т.д.

#### Что должно было произойти
Когда диона находится на ручках-она не слепа, когда диона в рюкзаке - слепа.

#### Что произошло на самом деле
Диона оказалась слепа на ручках

#### Как повторить
Уговорить взять себя на ручки

**Comment by DeadOberst** [comment]
Все уже давно все знают #652
