### ISSUE TITLE
Лампы в морге не загораются зеленым светом, если игрок вернулся в своё тело

### ISSUE THREAD

**Issue by Bolzhedor69** [TauCetiStation/TauCetiClassic#2408]
#### Подробное описание проблемы
Лампочки в морге на гробах не горят зеленым, если игрок-гост вернулся в тело
#### Что должно было произойти
Лампы должны гореть зеленым, если игрок вернулся в тело
#### Что произошло на самом деле
Лампы горят красным
#### Как повторить
Засунуть тело с душой игрока в гроб морга

**Comment by Lexakr** [comment]
Удивлю, но у них банально механа такого нет

**Comment by WallShrabnic** [comment]
И не должны, собственно

**Comment by Bolzhedor69** [comment]
На Анимусе было

**Comment by Skippeer12** [comment]
Мы не анимус. Извени.

**Comment by Bolzhedor69** [comment]
Так может, позаимствуем и на наш билд эту особенность? Было бы легче возвращать игроков в раунд

**Comment by Pirsnya** [comment]
Таки да, идея интересная.

**Comment by Raschert0** [comment]
@Bolzhedor69 @Pirsnya ну делайте, чоу
