### ISSUE TITLE
Баг с цветом рисунков мелом

### ISSUE THREAD

**Issue by Bolzhedor69** [TauCetiStation/TauCetiClassic#2409]
#### Подробное описание проблемы
Мелок любого цвета на второй раз рисует белым
#### Что должно было произойти
Должен рисовать своим цветом
#### Что произошло на самом деле
Рисует белым через раз
#### Как повторить
Порисовать мелком

**Comment by RichardJones1** [comment]
Мелки рисуют не белым через раз, а вообще рандомным
