### ISSUE TITLE
Невидимые лежачие лампы

### ISSUE THREAD

**Issue by dimelion** [TauCetiStation/TauCetiClassic#241]
#### Подробное описание проблемы
Если персонажем в лежачем положении снять лампу, то лампа снимется, но сама при этом пропадет, так как на полу или руке ее нет

#### Что должно было произойти
Лампа при снятии должна оказываться на полу, либо вообще не должна сниматься

#### Что произошло на самом деле
В лежачем положении тела лампа снялась и пропала

#### Как повторить
Около лампы в лежачем положении взаимодействовать пустой рукой с текстурой лампы

#### Дополнительная информация:
Подобное действие происходит только с настенными лампами, как обычными так и с люминесцентными лампами

**Comment by Lancer411** [comment]
https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/power/lighting.dm#L549
Нет проверки на то, что лампу можно положить в руку. Если нельзя, то все равно лампа удаляется из патрона.
