### ISSUE TITLE
Какао порошок невозможно сыпать в Кондимастер

### ISSUE THREAD

**Issue by torn223** [TauCetiStation/TauCetiClassic#2412]
Подробное описание проблемы: Какао порошок нельзя сыпать в Кондимастер,хотя он используется для приготовления шоколада.

Что должно было произойти: Какао порошок бы посыпался и я благополучно бы сделал шоколад

Что произошло на самом деле: "Your the beaker contains components unsuitable for cookery"

Как повторить: Попробовать насыпать из мензурки какао порошок.

Дополнительная информация:

**Comment by Bolzhedor69** [comment]
Какао порошок сыпется в микроволновку, чтобы сделать шоколадку, вроде

**Comment by torn223** [comment]
Тогда нужно исправить вики.

**Comment by Lexakr** [comment]
Все ингредиенты просто смешиваются, вики обновил, закрывать можно
