### ISSUE TITLE
[Proposal] Упростить получение ламп для киборга уборщика.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2414]
Киборг уборщик, может набирать лампы только путем перезарядки себя, а это очень долгий процесс. За одну минуту выбивает только где-то две лампы.
Предлагаю:
1) Ускорить зарядку ламп в заряднике.
2) Увеличить начальное количество ламп с 10 до 30.
3) Иметь возможность зарядить оборудование что вставляет лампы - путем нажатия этим оборудованием по лампе или коробке с лампами.

**Comment by Sakuya-Izayoi** [comment]
Есть декомпилятор материи вроде же.
