### ISSUE TITLE
Проблема вывода списка предметов на клетке при помощи Alt+ЛКМ

### ISSUE THREAD

**Issue by Bolzhedor69** [TauCetiStation/TauCetiClassic#2415]
#### Подробное описание проблемы
При клике Alt+ЛКМ не всегда выводит список вещей в правое окошко. Иногда выводит, если попасть, например, на шкаф, но даже так не всегда. На других билдах неважно, на какой предмет на клетке ты кликаешь, Альт+лкм всегда выводит список предметов, лежащих на клетке. Приходится прокликивать сначала клетку, потом какой-нибудь шкаф (если ты открыл шкаф с кучей вещей и хочешь взять что-то), потом прокликивать на предметы. Раньше всё вроде нормально работало, может что-то сломалось?

**Comment by Skippeer12** [comment]
Ну наверное, не знаю. Оно работает но там вкладка открывается возле статуса, если ты до этого на неё не кликал, то придется кликнуть, а если ты переключился на любую другую вкладку то после альт+лкм придется опять её выбрать.
![image](https://user-images.githubusercontent.com/18488106/38175056-308e4b24-35df-11e8-8532-189e38749432.png)

**Comment by Pirsnya** [comment]
Там вроде зависит от того, насколько ты близко стоишь. У меня не работал альт+клик если я стоял далеко, но стоит подойти - как всё прекрасно работает.

**Comment by LudwigVonChesterfield** [comment]
нет, давайте выпилим этот механ
