### ISSUE TITLE
Ломающиеся ХУДы у культы

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2427]
#### Подробное описание проблемы
У культистов ломаются ХУДы, через некоторое время после начала или конверта перестают отображаться иконки
#### Что должно было произойти
Нормальные иконки над персонажами
#### Что произошло на самом деле
ХУДы пропадают
#### Как повторить
Поиграть за культю, истиные причины неизвестны, проблемы не одного меня
#### Дополнительная информация:
https://cdn.discordapp.com/attachments/421241059306110976/430887251078021130/Tau_Ceti_Station_2018-04-03_214339.png
Человек в робе - культист, обсуждали в ЛООС

**Comment by KIBORG04** [comment]
#5971
