### ISSUE TITLE
Невидимые гранаты при стрельбе из гранатомёта

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2428]
#### Подробное описание проблемы
При стрельбе из гранатомёта взведённые гранаты не имеют текстуры, поэтому очень сложно сказать их местоположение (но они бахают)
#### Как повторить
Пострелять из гранатомёта (многозарядного или на мехе)

**Comment by Skippeer12** [comment]
Stop right there criminal scum #1549
