### ISSUE TITLE
Неразборчивый текст в результате повреждения мозга.

### ISSUE THREAD

**Issue by enykey0** [TauCetiStation/TauCetiClassic#2429]
#### Подробное описание проблемы
У меня какое-то повреждение мозга в результате клонирования. 
После которого я не разбираю речь в чате. (понимаю только FUCK, MOTHERFUCKER и т.д.)
Текст который говорится в рацию я понимаю как обычно.
#### Что должно было произойти
По рации я так же не должен разбирать текст.
#### Что произошло на самом деле
По рации текст без искажений.
#### Как повторить
Совершить клонирование с каким-то повреждением мозга.

**Comment by enykey0** [comment]
https://imgur.com/a/cO30T
скриншот.

**Comment by Lancer411** [comment]
У всех окружающих вирус вызывающий синдром туррета.

**Comment by enykey0** [comment]
они при этом друг друга понимают а я нет?

**Comment by Pirsnya** [comment]
Все друг-друга понимают. Просто это выкрики, маты и так далее. Несдержанность, вот.

**Comment by enykey0** [comment]
Даже если и так. Тогда на разговоры по рации это всё равно должно распространяться.

**Comment by igigin** [comment]
Это синдром туррета, все эти маты - автоматические сообщения в say, они не заменяют фразы, т.е. всё намеренно сказанное ты отлично понимаешь, что отлично видно на примере Мэта Джекобса со скриншота и собственно раций.
