### ISSUE TITLE
Нанопаста не работает.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#243]
#### Подробное описание проблемы
Нанопаста не работает. При попытке нанести говорит что повреждений нет хотя они есть
#### Что должно было произойти
Убрать повреждения.
#### Что произошло на самом деле
Ничего.
#### Как повторить
попробовать чинить любые повреждения робоконечности нанопастой.

**Comment by KatoMarika** [comment]
Нанопаста никогда не чинила робоконечности. 
Только для внутренних органов и глаз.

**Comment by Dennok** [comment]
Чинила.

**Comment by ZVee** [comment]
а робоконечность была "открыта" в момент починки?

**Comment by Dennok** [comment]
Да. горелкой починить вышло.

**Comment by Dennok** [comment]
Нет не была.

**Comment by ZVee** [comment]
Я тут просто думаю, зачем это ставили - https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/game/objects/items/stacks/nanopaste.dm#L30

**Comment by Dennok** [comment]
ДУмаю что то надо убрать. Та как я лично ни в тестах ни в коде не нашел способа открыть роболимб та как все операции с ними заблокированы тут https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/surgery/generic.dm#L22
Использовав немного магии и разрезав роболимб до роботизации скальпелем вышло починить лимб.
