### ISSUE TITLE
Проблема с отображением "Red replica helment" на персонаже

### ISSUE THREAD

**Issue by Bolzhedor69** [TauCetiStation/TauCetiClassic#2430]
#### Подробное описание проблемы
Если взломать автомат костюмов в подсобке клоуна, там появится _Red replica suit_ и _Red replica helment_. Красный скафандр надевается нормально, а вот если надеть шлем, то персонаж просто становится лысым. Шлем как-бы надет, в Экземайне вместо шлема зеленый вопросик, шлем нельзя снять самому, потому-что в слоте он не отображается.
#### Что должно было произойти
Корректное отображение предмета на персонаже
#### Что произошло на самом деле
Лысая голова без возможности снять шлем самому
#### Как повторить
Взломать автомат костюмов, выбрать _Red replica helment_ и надеть на голову.
#### Дополнительная информация:
Если купить все шлемы из автомата и по-тихому ходить одевать их на людей, у админов взрывается ахелп

**Comment by Kernstall** [comment]
Больше похоже на фичу

**Comment by Bolzhedor69** [comment]
Ну, теперь прозрачный не только шлем. Иногда костюм тоже.
