### ISSUE TITLE
Сущности генокрада слышат госточат а также видят все эмоуты

### ISSUE THREAD

**Issue by EdlerN** [TauCetiStation/TauCetiClassic#2435]
#### Подробное описание проблемы
Сущности генокрада слушают излияния гостов на тему того как раньше трава была зеленее, видят как где-то на другом слое кто-то гаспает, неплохо палят ерп, а также видят ближайшие эмоуты в нескольки экземплярах (к примеру три десгаспа от пожираемой куклы вместо одного)
#### Что должно было произойти
Сущность видит и слышит то же, что и генокрад
#### Что произошло на самом деле
Сущность имеет доступ к госточату и прочему добру
#### Как повторить
Быть съеденным генкой/съесть кого-то и отдать ему контроль
#### Дополнительная информация:
КУРШАН!

**Comment by DeadOberst** [comment]
https://cdn.discordapp.com/attachments/396500362812456970/432151643606220801/f7de6c62df6f433d.PNG
