### ISSUE TITLE
Space Law показывает браузерную заглушку

### ISSUE THREAD

**Issue by EustaceCS** [TauCetiStation/TauCetiClassic#2440]
Шаги: открыть книгу законов в комнате детективов/юристов.
![1523182308415](https://user-images.githubusercontent.com/29461793/38467504-221d5324-3b42-11e8-92fd-5ddf3e9db23f.jpg)
BYOND 5.0 Public / 511.1385 , Win10, запуск от имени администратора.
Может иметь отношение к #17 .

**Comment by LudwigVonChesterfield** [comment]
>Может иметь отношение к #17.

Оно не может иметь отношение, в этом и заключается "проблема".
