### ISSUE TITLE
Текстура и damp rag

### ISSUE THREAD

**Issue by Architect0r** [TauCetiStation/TauCetiClassic#2445]
#### Подробное описание проблемы
Текстура вещей не обновляется, если очистить их с помощью "damp rag", но если надеть её заново, то текстура чистая. 
#### Что должно было произойти
Вещь должна была очиститься, не одеваясь заново 
#### Что произошло на самом деле
Вещь не очистилась
#### Как повторить
Почистить любую испачканную в крови/машинном масле вещь damp rag'ом.

**Comment by Lexakr** [comment]
Тряпка это как мыло, только у мыла при попытке помыть шмотку, не снимая, мы видим сообщение 
> You need to take that [target.name] off before cleaning it
Хотя предложение занерфить тряпку очень интересное 😸
