### ISSUE TITLE
Спрайт пустой бумаги при имеющемся тексте

### ISSUE THREAD

**Issue by Lexakr** [TauCetiStation/TauCetiClassic#2446]
#### Подробное описание проблемы
На некоторых бумажках (например сканер-репорты, ЦК репорты) отсутствует спрайт с текстом, когда он есть
#### Что должно было произойти
Нормальный спрайт
#### Как повторить
Сделать скан в бодисканнере

**Comment by LudwigVonChesterfield** [comment]
Не проставленые update_icon() вызывают этот баг.
