### ISSUE TITLE
Эквип ксеноархеологов

### ISSUE THREAD

**Issue by lustiwe** [TauCetiStation/TauCetiClassic#245]
#### Подробное описание проблемы

Вылезает множество сообщений когда кладёшь excavation pick set внутрь excavation gear belt, а потом выдаёт ошибку (но всё равно кладётся).
#### Что должно было произойти

Не должно было вылезти много сообщений и ошибки.
#### Что произошло на самом деле

Вылезло множество сообщений когда кладёшь excavation pick set внутрь excavation gear belt, а потом выдаёт ошибку (но всё равно кладётся).
#### Как повторить

Положить excavation pick set внутрь excavation gear belt.
#### Дополнительная информация:

http://puu.sh/orSTn/4097eca50c.png

**Comment by Raschert0** [comment]
Пытаюсь проверить - всё нормально работает

**Comment by Raschert0** [comment]
Не удалось повторить
