### ISSUE TITLE
Нутрименты сломалей

### ISSUE THREAD

**Issue by Kernstall** [TauCetiStation/TauCetiClassic#2450]
#### Подробное описание проблемы
Еда не восполняет сытость

#### Что должно было произойти
Еда восполняет сытость

#### Что произошло на самом деле
Я съел всю поварскую

#### Как повторить
Покушать

#### Дополнительная информация:
Помогите пожалуйста

**Comment by Bolzhedor69** [comment]
Ты либо ел вилкой, либо не подождал некоторое время, чтобы еда переварилась

**Comment by volas** [comment]
проблема была, пофиксили
