### ISSUE TITLE
[Proposal] Сделать ракетницу с ракетами дешевле.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2453]
Ракетница у спец агентов нюки - имеют огромную цену в 35 кристалов. Добавьте к этому еще что каждая ракета стоит еще 10. В результате - ракетница является самой неразумной тратой средств.
Предлагаю снизить цену ракетницы до 25 а сами ракеты по три кристала.

**Comment by Skippeer12** [comment]
Она сейчас сломана и эта поломка идет от спрайтов "гильз" ракеты до механики самой ракеты.

**Comment by Kernstall** [comment]
Жизненно, а еще на Маулер цену снизить нужно, ну серьезно.

**Comment by Belfogor** [comment]
Да там все сломано. А в частности сломаны механы взрыва, которые работают некорректно. Уж не стоит упоминать о непомерной цене реактивного гранатомета. Единственное на то он годен, так это ломать мехи или делать однотайловые дырки.

**Comment by Skippeer12** [comment]
>делать однотайловые дырки.

Взрывается он нормально, но есть некоторые исключение из правил, по типу прямого попадания по шлюзу/кукле.
