### ISSUE TITLE
Проблема с языком у позитронок

### ISSUE THREAD

**Issue by Kernstall** [TauCetiStation/TauCetiClassic#2462]
#### Подробное описание проблемы
Позитронный мозг и видимо мозг в мми может различать язык воксов, хотя checkKnownLanguages у него пустой. Думаю, то же самое с другими экзотическими языками.
#### Что должно было произойти
Позитронки имеют набор понятных им языков и не понимают других.
#### Что произошло на самом деле
Позитронный мозг работает в режиме ультимативного переводчика
#### Как повторить
Стать позитронкой и пообщаться с воксом

**Comment by LudwigVonChesterfield** [comment]
Но ведь позитронный мозг, борги, и пИИ и должны понимать языки всякой ксеноты.

**Comment by Kernstall** [comment]
Во-первых, позитронный мозг не обязательно должен содержать дешифраторов ксеносской речи. Зачем это пихать в базовую начинку, позитронный мозг выполняет другие функции. Во-вторых, борги на текущий момент не понимают даже кошачий/ящериный/жабий. Ну и пустой список известных языков все равно баг, пусть висит
