### ISSUE TITLE
Тандердом для гостов

### ISSUE THREAD

**Issue by Bolzhedor69** [TauCetiStation/TauCetiClassic#2463]
#### Подробное описание 

В баре есть монитор, через который можно следить за камерами Арены. Почему-бы не обьявлять набор в две команды для Арены гостам раз в двадцать минут, например? Госты могли бы себя занять робастом на Тандере, а зрители наблюдали бы за боем через монитор в баре.

**Comment by LudwigVonChesterfield** [comment]
#2439

**Comment by Bolzhedor69** [comment]
я пытался

**Comment by WallShrabnic** [comment]
1. https://github.com/TauCetiStation/TauCetiClassic/pull/2439
2. Нет, гостам тандердом не нужен по причине того, что быстро наскучит
3. Редкие экраны - дань памяти старым временам
