### ISSUE TITLE
9мм обойма из автолата не подходит для пистолета Стечкина

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2464]
#### Подробное описание проблемы
9мм обойма из автолата не подходит для пистолета Стечкина
#### Что должно было произойти
Обойма 9мм из автолата должна подходить Стечину
#### Что произошло на самом деле
Она не подходит
#### Как повторить
Заспавнить с помощью трейтора пистолет Стечкина, взломать автолат и попытаться вставить 9мм обойму из автолата в пистолет.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/19417166/39008644-f0f2b248-4411-11e8-8a13-217cd38bb8f2.png)

**Comment by WallShrabnic** [comment]
Во-первых, не обойма, а магазин
Во-вторых, Стечкин сам по себе нелегален и не факт, что во взломанном автолате будут иметься к нему патроны
В-третьих, пистолет СБ имеет другую модель, не факт что магазин от одного пистолета подойдёт к другому

**Comment by Avatar4** [comment]
Во первых - мне все равно. Я тут не в пунктуационные войны пришел играть.
Во вторых - отдельно пули от магазина из автолата, вставляются в магазин Стечкина. Значит они по идее должны совпадать.
В третьих - у них одинаковые спрайты (за исключением того что повернуты в разные стороны) и описание. В каждом из них по 8 пуль. То бишь, магазины должны совпадать. К тому же, производители делают оружие таким, что бы он был подходящим к стандартам магазина. А в автолата как раз самый распространенный стандарт.

**Comment by Lexakr** [comment]
У стечкина такой же калибр, но сами файлы магазинов разные. Вообще это здраво, ведь иначе любой неглупый тритор сможет печатать себе во взломанном автолате неограниченный боезапас, change my mind

**Comment by Avatar4** [comment]
В таком случае, не глупые триторы будут заказывать орла у которого на пулю меньше и без стелса, но зато есть патроны в автолате и с одного выстрела в ногу офицеру в булепруфе разрывает артерию оставляя шарп. Но вы правы, зачем давать и так слабому Стечкину патроны который и так наносит всего 25 дамага и без застревания в теле.
