### ISSUE TITLE
Питьё из химических склянок [Proposal]

### ISSUE THREAD

**Issue by Bolzhedor69** [TauCetiStation/TauCetiClassic#2468]
#### Подробное описание 
Почему из склянок, сделанных в химии при помощи ХимМастера, нельзя пить? Персонаж просто выплёскивает содержимое склянки себе на лицо.

(Я просто хочу пить из бутыльков как-будто это зелья)

**Comment by WallShrabnic** [comment]
В названии через пробел добавить [Proposal], примеры  https://github.com/TauCetiStation/TauCetiClassic/issues/2453
https://github.com/TauCetiStation/TauCetiClassic/issues/2414

**Comment by Bolzhedor69** [comment]
Но метка не ставится

**Comment by Misakiwa** [comment]
Спереди ставь, необучаемый.

**Comment by WallShrabnic** [comment]
Метка ставится при создании ишью
