### ISSUE TITLE
Доступ в вольер с макаками(медбей генетика)

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#247]
#### Подробное описание проблемы
РД не имеет доступа в вольер с макаками.
Также в клонировальню(хотя это не критично, всетаки это часть смо), и было бы все таки удобнее еслиб РД мог в открытие дверей в коридор медбея со стороны генетики.

**Comment by Belfogor** [comment]
Ну билд же открыт. Ну.

**Comment by Skippeer12** [comment]
РД берет и собирает свою генетику, с макаками и улучшениями.
Мед. Бейс сосет бибу.

**Comment by Dennok** [comment]
я знаю как решить проблему. На астероиде темболее макакокуов дофигища. НО. Мне уже надоело бегать за макакокубами когда рядом есть вольер.

**Comment by KatoMarika** [comment]
Что же ты форму до конца не заполнил.
