### ISSUE TITLE
Предатель ИИ. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#248]
#### Подробное описание проблемы

Трейтор ИИ не получает нулевой закон. Хакнутый борг так же не получает закон, хоть и получает хакнутые модули. 
#### Что должно было произойти

ИИ должны были добавить соответствующий закон, в обратном случае его цели противоречат законам. 
#### Что произошло на самом деле

ИИ не получил закон. 
#### Как повторить

Получить за ИИ трейторку. 
#### Дополнительная информация:

Даже не знаю стоит ли тут что-нибудь писать.

**Comment by Raschert0** [comment]
Хм, вот я сейчас проверяю - есть нулевой закон у ИИ

**Comment by Parterson** [comment]
Недавно был раунд на сервере с тритором-ИИ, у него был нулевой закон.
