### ISSUE TITLE
Дела кухонные или дроп мяса с респрайтов хуманов

### ISSUE THREAD

**Issue by Kernstall** [TauCetiStation/TauCetiClassic#2484]
#### Подробное описание проблемы
Дионеи, Спу, Големы и все, кто наследуется от хумана, оставляют после себя мясо при разделывании, хотя далеко не все должны и далеко не все человеческое.

#### Что должно было произойти
Зависит от фантазии, можно спавнить шестеренки при харвесте спу и семена нимф при харвесте дион

#### Что произошло на самом деле
С спу упало щедрых 3 куска мяса

#### Как повторить
разделать спу на кухне

**Comment by Tolerantboy** [comment]
Можно, чтобы с СПУ сталь или пласталь.
Разобрал СПУ и сделал из него стул - идеальное преступление

**Comment by Kernstall** [comment]
С такими фичами смертность спу драматически повысится

**Comment by Smalltasty** [comment]
занятно. пофиксим-с
