### ISSUE TITLE
Итоговая информация по раунду не выводится при предателях. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#249]
#### Что произошло на самом деле

Ничего
#### Как повторить

Дождитесь окончание смены. 
#### Дополнительная информация:

Неизвестно проявляется ли баг при смешанном режиме.

**Comment by Skippeer12** [comment]
Можно закрывать, вроде починили уже.

**Comment by WallShrabnic** [comment]
Открыто, баг перешёл на мемо

**Comment by Raschert0** [comment]
Мемо выпили из ротации
