### ISSUE TITLE
Отсутсвие доступа у пульта хопа к дверям хопа

### ISSUE THREAD

**Issue by YulianR** [TauCetiStation/TauCetiClassic#2490]
#### Подробное описание проблемы

У цивилиан ремоута (пульта хопа) нет доступа к дверям хопа и мостика.

#### Что должно было произойти

обратное

#### Как повторить

попробовать юзнуть пульт хопа на двери хопа

**Comment by Skippeer12** [comment]
К мостику не должен быть, он есть только у ОБР и капитана.
А вот с офисом таки проблема.
