### ISSUE TITLE
Стекло режет протезированную руку.

### ISSUE THREAD

**Issue by kres9** [TauCetiStation/TauCetiClassic#2496]
#### Подробное описание проблемы
Кусок разбитого стекла, режет механическую руку, как будто у вас нет стоит протез.
#### Что должно было произойти
Металл не должен резать протезы. Кхем.
#### Что произошло на самом деле
Брал стекло рукой, на которой стоял механический протез и руку порезало с текстом: _The shard cuts into your hand!_
#### Как повторить
Какие-то звуки, что стекло в металлической руке начинает сыпаться, или что-то вроде того.

**Comment by RichardJones1** [comment]
Скорее не баг, а пропозал, так как у нас нету такого типа урона, как колющее. 
А вообще, я легко могу представить, как человек с помощью осколка режет провода на руке, свкрывает панели, и тд.
