### ISSUE TITLE
Пожарный топор.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#250]
#### Подробное описание проблемы
При ударе топором по решетке они изчезают без выпадения частей на пол.

#### Что должно было произойти
Должны были выпасть части.
#### Что произошло на самом деле
Они изчезают.
#### Как повторить
Взять топор в две руки и попробовать ударить решетку.
#### Дополнительная информация:
Если бить топором в одной руке, то они выпадают.

**Comment by Dennok** [comment]
Части в смысле прутья?

**Comment by Skippeer12** [comment]
Именно.
