### ISSUE TITLE
[Proposal] Фитнес-отсек ест электроэнергии больше чем половина станции

### ISSUE THREAD

**Issue by RigoSex** [TauCetiStation/TauCetiClassic#2501]
#### Подробное описание проблемы
Высокое энергопотребление самого неважного отсека.

#### Что должно было произойти
Понизить энергопотребление, возможно, пересмотр карты и её передел.

#### Что произошло на самом деле
Потребляет 26килловат энергии.

#### Как повторить
Посмотреть в консоль в инженерке.

#### Дополнительная информация:
Пикрил:
![dreamseeker_2018-05-14_18-44-42](https://user-images.githubusercontent.com/19224346/40008179-610d46d0-57a7-11e8-912e-374a324e7c1d.png)

**Comment by seekin4u** [comment]
Потребление мультитулом прямо под APC измерял?
Велосипеды что ли пассивно так жрут много? :thinking:

**Comment by RigoSex** [comment]
@seekin4u Сейчас измерю мультитулом.
Фитнес-рум это там где бассейн.

**Comment by RigoSex** [comment]
![default](https://user-images.githubusercontent.com/19224346/40009094-b8d1521a-57a9-11e8-9a11-67083253f553.png)

**Comment by RigoSex** [comment]
@seekin4u Мультитул показывает все напряжение в сети...

**Comment by Skippeer12** [comment]
Если ты про комнату с голо-палубой, то это нормально.

**Comment by RigoSex** [comment]
@Skippeer12 А мне кажется потреблять больше чем двигатель - это ненормально. И нереалистично.

**Comment by Skippeer12** [comment]
Если это тебе кажется много, то ты ещё не видел включеные крио-капсулы в мед.блоке.
Мне кажется что проекция голографических вещей с которыми можно взаимодействовать должна жрать довольно таки много энергии.

**Comment by Skippeer12** [comment]
Выключен он и жрет в разы меньше.
![image](https://user-images.githubusercontent.com/18488106/40010169-a70002d6-57ac-11e8-9aa6-fc54cab22e85.png)
Включеный.
![image](https://user-images.githubusercontent.com/18488106/40010214-c4c0e150-57ac-11e8-8e54-edc35b16ef71.png)
