### ISSUE TITLE
Баг или фича? кинетический ускоритель шахтёра

### ISSUE THREAD

**Issue by Hynex** [TauCetiStation/TauCetiClassic#2505]

**Comment by Skippeer12** [comment]
Это работает не только с кинетиком.

**Comment by LudwigVonChesterfield** [comment]
#2570

**Comment by Hynex** [comment]
Месяц назад всё ещё не пофиксили

сб, 9 февр. 2019 г., 9:20 stale[bot] notifications@github.com:
