### ISSUE TITLE
Секьюрити ремоут теперь во всех ящиках хоса

### ISSUE THREAD

**Issue by EdlerN** [TauCetiStation/TauCetiClassic#2506]
#### Подробное описание проблемы
Определенные личности, по всей видимости при добавлении секлайтов, просто закинули в класс объекта ящика хоса пульт от брига
#### Что должно было произойти
Пульт должен существовать в единственном экземпляре
#### Что произошло на самом деле
Любой мусорщик может откопать ящик хоса и получить ключи от оружейки
#### Как повторить
Любым способом заспавнить ящик.
#### Дополнительная информация:
Руки бы оторвать таким кодерам

**Comment by LudwigVonChesterfield** [comment]
Достаточно убрать из кода ящиков, и на карте поставить на тайл с ящиком ремоут.

**Comment by Skippeer12** [comment]
Где же вы были когда их добавили в ящики?
