### ISSUE TITLE
Клики Куршана Аркейн Барраж Мили

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#2507]
#### Подробное описание проблемы

Кликая по кукле аркейн барражем в мили, задержка не ставится.

#### Что должно было произойти

Человек не должен мочь мгновенно закликивать десять раз кого-то аркейн баражжем в мили.

#### Что произошло на самом деле

Тратататататтатата.

#### Как повторить

Маг - аркейн барраж - мили - гроб гроб.

#### Дополнительная информация:

Отсутствует.

**Comment by Sakuya-Izayoi** [comment]
объясни (непонял)

**Comment by LudwigVonChesterfield** [comment]
Если кликать по человеку в мили спеллом "Аркейн Барраж", задержка отсутствует.

**Comment by LudwigVonChesterfield** [comment]
Да, является.

**Comment by LudwigVonChesterfield** [comment]
Как оказалось, это фича.
