### ISSUE TITLE
Тележка мороженщика даёт только шоколадные стаканчики

### ISSUE THREAD

**Issue by EustaceCS** [TauCetiStation/TauCetiClassic#2520]
#### Подробное описание проблемы
Телега мороженщика не выдаёт обычные стаканчики для мороженого, если хоть раз создать в ней шоколадный стаканчик.

#### Как повторить
Заправить тележку мороженщика мукой, сахаром, льдом, молоком.
Прожать Make Waffle Cones.
Прожать Make Chocolate Cones.
Прожать Dispense Waffle Cones.
Прожать Dispense Chocolate Cones.

#### Что должно было произойти
Телега выплюнет один обычный стаканчик и один шоколадный.

#### Что произошло на самом деле
Телега даст только шоколадный стаканчик.

**Comment by Sakuya-Izayoi** [comment]
Can't reproduce

**Comment by EustaceCS** [comment]
> Этот ишью пробыл открытым более полугода. Пожалуйста, сообщите, является ли он актуальным для текущей версии билда?

Здравствуй, бот!

Разбаньте (и всыпьте плетей тому, кто банил), - попробую.
