### ISSUE TITLE
Wooden plank не стакается и из него не собирается крафт

### ISSUE THREAD

**Issue by DeeperCoder** [TauCetiStation/TauCetiClassic#2525]
#### Подробное описание проблемы

Wooden Plank (деревянная дошечка) не стакаются вместе, а остаются всегда по отдельности. А также из дошечек нельзя ничего скрафить. При нажатии на Z или клике курсора на дошечке ничего не происходит.

#### Что должно было произойти

Дошечки должны стакаться в кучу и при нажатии на них открываться должно меню крафта, где можно выбрать что из них делать. Например, деревянный пол.

#### Что произошло на самом деле

Wooden Plank (деревянная дошечка) не стакаются и не открывается меню крафта.

#### Как повторить

Зайти в игре за ботаника. Вырастить дерево. Дерево порубить топором на доски.

#### Дополнительная информация:

![image](https://user-images.githubusercontent.com/17331061/40931097-7131ac2c-6832-11e8-926f-059fb3794cc7.png)

**Comment by LudwigVonChesterfield** [comment]
Если кому интересно, насколько знаю проблема конкретно в досках из ботаники.
