### ISSUE TITLE
Toggle Camera Light у ИИ работает не правильно

### ISSUE THREAD

**Issue by DeeperCoder** [TauCetiStation/TauCetiClassic#2526]
#### Подробное описание проблемы

При включении Toggle Camera Light включается свет камер в комнате над которой находится камера ИИ (глаз ИИ, то что он видит сейчас). Если перейти в другую комнату свет от камер **не появляется**, хотя Toggle Camera Light стоит в статусе "**включен**". 

#### Что должно было произойти

Когда включен Toggle Camera Light свет от камер должен включаться каждый раз, когда глаз ИИ переходит в новую комнату. Свет камер выключается только, если **выключен** Toggle Camera Light, либо глаз ИИ **покинул комнату**.

#### Что произошло на самом деле

Toggle Camera Light сработал только для одной комнаты. Тоггл остается "включен", а света от камер нет.

#### Как повторить

Для наглядности. Зайти в игру за ИИ. Перейти к двум ненужным комнатам (отсекам). В АПЦ комнат выключить свет. Затем включить Toggle Camera Light, находясь в одной из комнат. Затем перейти к обзору другой комнаты с выключенным светом.

**Comment by FelixRuin** [comment]
не баг, свет включается на камере и висит там пока его не выключить, а после уже включить в другой комнате
