### ISSUE TITLE
Дюп боргов. Возвращение 

### ISSUE THREAD

**Issue by D1nastyLost** [TauCetiStation/TauCetiClassic#2529]
**Подробное описание проблемы**
Сегодня в раунде из одного борг-эндоскелетона сделал около 8, тыкая на эндоскелетон позитронкой.

**Что должно было произойти**
Должен получиться один борг с позитронкой внутри.

**Что произошло на самом деле**
На самом деле при клике позитронкой на эндоскелетон появлялся "как бы активный борг" (у которого появилось имя - стандартный борг ***), без позитронки внутри, и сама позитронка дропнулась на пол, а не исчезла.

**Как повторить**
Нужна позитронка и готовый ко вставке мозгов борг - то есть целый эндоскелет(или как это дерьмо называется). Позитронка, еслественно, должна быть активной.
Тыкаем позитронкой на каркас борга - появляется "как бы живой борг", новый каркас борга под ним, и позитронка падает на пол.

**Дополнительная информация:** 

Репорт поступил от игрока в середине мая, руки дошли сейчас, линк на старый репорт прилагаю ( полная копипаста, т.к. все идентично)
https://github.com/TauCetiStation/TauCetiClassic/issues/360

**Comment by seekin4u** [comment]
Уточни какая позитронка была
С гостом внутри или тыкал обычной?

**Comment by seekin4u** [comment]
Кстати в том старом репорте позитронка у меня была со спящим гостом внутри, кажется. Может это что-то решает.

**Comment by D1nastyLost** [comment]
У нас гост был активным. Вопрос решился удалением с переселением в одного из задюпаных боргов.

**Comment by RichardJones1** [comment]
Нужны тесты
