### ISSUE TITLE
Борги и их модули. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#253]
#### Подробное описание проблемы
Если из борга вынуть батарею при имеющихся модулях в активных слотах, то после возвращения батареи обратно  модули которые были активны уже невозможно будет активировать после. Они все так же остаются доступными, но их нельзя переместить в активных слот. Собственно борги так же реагируют на тентякли голифа.

Лечится только пересборкой или сбросом модуля. 
#### Что произошло на самом деле
Shit.
#### Как повторить
Вынуть из борга батарею или подставиться под тентякли голиафа. 

#### Дополнительная информация:
Вероятно флешки и ионки имеют приблизительно такой же эффект

**Comment by ZVee** [comment]
Прикрою, потому что - #234 висит давно.
