### ISSUE TITLE
Оверлей печенек

### ISSUE THREAD

**Issue by Kernstall** [TauCetiStation/TauCetiClassic#2530]
#### Подробное описание проблемы
Оверлей админских печенек чрезвычайно высок, выше оверлея худа, даже неба, даже Аллаха

#### Что должно было произойти
За иконку худа над головой можно вытащить космонавта из-под груды печенек без богомерзкого альт-клика

#### Как повторить
Заспавнить печенье

#### Дополнительная информация:
Долой админский произвол!

**Comment by Skippeer12** [comment]
Не баг, а фича.

Спавнить печеньки через прей - себя не уважать, ведь сделали самую отличную вещь, которой можно сразу решить все вопросы. Спасибо Молесто, за фичу спавна с небес.

**Comment by LudwigVonChesterfield** [comment]
Да, является.

**Comment by T6751** [comment]
@LudwigVonChesterfield вроде бы сейчас всё ок с печеньем, дело закрыто?
![image](https://user-images.githubusercontent.com/66636084/84140455-5484f680-aa5a-11ea-85e0-d584f34addf3.png)

**Comment by LudwigVonChesterfield** [comment]
@T6751 Ты через прей спавнил?

**Comment by T6751** [comment]
@LudwigVonChesterfield да
