### ISSUE TITLE
Портативный генератор поля сломан.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2532]
#### Подробное описание проблемы
Портативный генератор поля (который прикрепляется к полу и вокруг себя образует поле) перестал работать.
#### Что должно было произойти
Должна появиться панель активации.
#### Что произошло на самом деле
Ее нет.
#### Как повторить
Прикрутить к полу гаечным ключом и рядом с ним панель от машины тоже прикрутить. Нажать на генератор.

**Comment by RichardJones1** [comment]
Я вот видел, что он работает... Много раз. Нужен фидбек.

**Comment by igigin** [comment]
@RichardJones1 Плашка test feedback проставлялась для ишью основанных на ПРах в состоянии тест мержа. Лучше сделай новую.

**Comment by RichardJones1** [comment]
> @RichardJones1 Плашка test feedback проставлялась для ишью основанных на ПРах в состоянии тест мержа. Лучше сделай новую.

Спасибо, что написал. Я предполагал, что она служит немного для другого, но увидел её на некоторых ишью и решил, что так можно использовать. Переговорю с воласом тогда на счёт новой.
