### ISSUE TITLE
Невозможно заменить руку СПУ

### ISSUE THREAD

**Issue by Garrysman232** [TauCetiStation/TauCetiClassic#2533]
#### Подробное описание проблемы
Нет возможности заменить СПУ руку как таковую 
#### Что должно было произойти
Возможность оперировать инструментами: Отвертка, лом и т.д

#### Что произошло на самом деле
"What left arm?"
#### Как повторить
Найти СПУ без руки
#### Дополнительная информация:
Пол станции пыталось вставить руку в СПУ, но не получилось ни у кого

**Comment by LudwigVonChesterfield** [comment]
Она и так есть, вы просто порядка проведения операции не знаете. Для пришития руки - кусачки - гаечный ключ - рука.
