### ISSUE TITLE
The hydroponics tray has Cocao Tree planted.

### ISSUE THREAD

**Issue by EustaceCS** [TauCetiStation/TauCetiClassic#2535]
EMERGENCY ASAP КТТС

#### Подробное описание проблемы
Опечатка в названии какао-пальмы, торчащей из гидропонического чана.

#### Что должно было произойти
сообщение
The hydroponics tray has Cocoa Tree planted.

#### Что произошло на самом деле
сообщение
The hydroponics tray has Cocao Tree planted.

#### Как повторить
зайти ботаником в ботаническую
взять из раздатчика семян семечко какао
посадить семечко в ванночку
кликнуть на ванночку

#### Дополнительная информация:
https://github.com/TauCetiStation/TauCetiClassic/blob/d9f5bf94ab549fdbd7bd60300b057c95247e5d51/code/defines/obj/hydro.dm#L1095
Я не знаю, где там above есть пояснение, что дерево именно сосао. Поиск по файлам только этот стринг показывает.

**Comment by Kernstall** [comment]
Зачем пилить ишью, если можно просто поменять?) Оно же тут навсегда останется

**Comment by EustaceCS** [comment]
Благодарю за заботу, но я вряд ли когда-нибудь смогу включить свои похождения по гитхабу в портфолио.
Руки не из того места-с, да.

**Comment by seekin4u** [comment]
Зачем пилить ишью, если ты знаешь в чем причина и можешь исправить ПУЛЛОМ? 🤔

**Comment by EustaceCS** [comment]
Ай, кого я обманываю.
Всё равно рано или поздно это случится.
Принимайте.
