### ISSUE TITLE
Терминал видим через стену

### ISSUE THREAD

**Issue by TermService** [TauCetiStation/TauCetiClassic#2536]
#### Подробное описание проблемы
Терминал не должно быть
#### Что должно было произойти
он виден!
#### Что произошло на самом деле
его не должно быть
#### Как повторить
погулять около стеночки 
#### Дополнительная информация:
![screenshot_51](https://user-images.githubusercontent.com/18397924/41342910-fe1b6342-6f05-11e8-8cdf-54370daa98f9.png)
![screenshot_52](https://user-images.githubusercontent.com/18397924/41342911-fe3e2c7e-6f05-11e8-85e7-67ce64501c8a.png)
![screenshot_50](https://user-images.githubusercontent.com/18397924/41342912-fe68cfba-6f05-11e8-8ce5-587cde9bfc12.png)

**Comment by Skippeer12** [comment]
Быдло-маппинг™
