### ISSUE TITLE
Фотоаппарат не фотографирует меч культистов

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2544]
#### Подробное описание проблемы
Фотоаппарат не фотографирует меч культистов
#### Что должно было произойти
Должен фотографировать
#### Что произошло на самом деле
Меча на фото нет

**Comment by RichardJones1** [comment]
На локалке всё работает. Этот закрываю, но ишью про странности фотоаппарата всё еще актуален
