### ISSUE TITLE
При многочисленном спаме флешером белый экран ослепления не проходим

### ISSUE THREAD

**Issue by FamousInvisible** [TauCetiStation/TauCetiClassic#2547]
#### Подробное описание проблемы
Многочисленное вызывает вероятность того, что эффект "белого экрана" не спадет. Помогает только переподключение
#### Что должно было произойти
Белый экран должен был исчезнуть
#### Что произошло на самом деле
Белый экран остался до перезахода
#### Как повторить
Множественно ослепить моба с игроком флешером

**Comment by Kernstall** [comment]
И как такое повторить на локалке? Бульонд клонировать?

**Comment by WallShrabnic** [comment]
Раньше это срабатывало при броске слипокалипсиса

**Comment by LudwigVonChesterfield** [comment]
Да, является.

**Comment by FamousInvisible** [comment]
Поднимаю
