### ISSUE TITLE
Реджув ломает кровати

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2550]
#### Подробное описание проблемы
Если реджувнуть кататоника на каталке, то она багнется. Человека можно будет спуллить, положить в крио, морг, куда угодно, но при перемещении каталки он телепортируется к ней. 

#### Что должно было произойти
Каталка должна функционировать нормально.

#### Что произошло на самом деле
Каталку нельзя сложить, опустить, при перемещении она телепортирует к себе тело.

#### Как повторить
Взять куклу без игрока, положить на каталку, реджувнуть.

#### Дополнительная информация:
Фиксится делитом (каталки).

**Comment by WallShrabnic** [comment]
Хмм, а сработает ли этот баг с реджувом генки и ядром хайвлорда? :hmm:

**Comment by Belfogor** [comment]
Ну это очевидно. Поскольку в ВВ моба остается отсылка к объекту, к которому он прикреплен. Нужно было в ручную дочистить все отслыки, в твоем случае, к каталке. Я бы не назвал это багом.

**Comment by Sakuya-Izayoi** [comment]
> Я то думал о педальном
о педальном и идёт

**Comment by RichardJones1** [comment]
Добавить в реджув проверку на то забаклен ли моб, перед тем как поднимать его. Разбакл, если да.

**Comment by volas** [comment]
^ fixed
