### ISSUE TITLE
Сломанный хлыст генокрада

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2551]
#### Подробное описание проблемы
Хлыст генокрада ничего не делает в интентах хелп и дизарм
#### Что должно было произойти
		if(I_DISARM)
			if(prob(65))
				LE.weaken = 2.5
		else
			LE.agony = 15
Судя по этим двум кускам кода, дизарм должен заставлять моба падать, хелп - испытывать боль
#### Что произошло на самом деле
Ничего, только сообщение о попадании хлыста
#### Как повторить
Попытаться использовать хлыст на хелпе или дизарме
#### Дополнительная информация:
N/A

**Comment by seekin4u** [comment]
Поправь размету, шкрябник, чуть слезла.

**Comment by SpaiR** [comment]
#2688
