### ISSUE TITLE
Plastic flaps можно ударить грабом

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#2556]
Взять кого нибудь в граб и нажать на фрапсы.
``The Airtight plastic flaps has been hit by ... with the grab``

**Comment by RichardJones1** [comment]
Да, граб так работает, ему надо как то отпилить атаклог, но не знаю как... Разве что в самом коде атак лога??

**Comment by LudwigVonChesterfield** [comment]
I ded

Грабу можно поставить NOBLUDGEON если проблема в логе.
