### ISSUE TITLE
Две коробки

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2560]
#### Подробное описание проблемы
Хуманам выдаются две коробки, одна пустая, другая с баллоном

#### Что должно было произойти
Должна выдаваться одна коробка с баллоном

#### Что произошло на самом деле
Выдало две коробки, одна пустая, другая с баллоном

#### Как повторить
Я зашёл за бармена и увидел у себя две коробки

#### Дополнительная информация:
#2524

**Comment by LudwigVonChesterfield** [comment]
Вообще, если за бармена, это фича. У бармена должна быть коробка с патронами, и коробка с набором для выживания. Раньше патроны просто клались в коробку с набором.
