### ISSUE TITLE
Худы у боргов

### ISSUE THREAD

**Issue by FatFatFatFat** [TauCetiStation/TauCetiClassic#2564]
#### Подробное описание проблемы
Когда тело бывшего нюкера боргонизируют, его худ (Буква S) остается.Вроде как это работает и с бывшими тенелингами (у боргов будет доступ в хайвчат)
#### Что должно было произойти
У Борга не должно быть худов и доступ в хайвчат.
#### Что произошло на самом деле
У Борга худ нюкра и доступ в хайвчат.
#### Как повторить
Боргонизировать нюцкера
#### Дополнительная информация:
Вот этот скрин мне дал как раз такой борг.Сам он бывший нюцкер, а возле меня у руны тоже стоит бывший нюцкер.
![unknown](https://user-images.githubusercontent.com/36511952/41981010-2073df62-7a52-11e8-8a85-369a0f00c226.png)

**Comment by Skippeer12** [comment]
Все антагонисты привязываются на мозг игрока, по этому это так и работает. Не думаю что это баг или фича, просто так это работает.

**Comment by RichardJones1** [comment]
Желательно это пофиксить в коде худов

**Comment by KuzyXD** [comment]
Худ стоит починить для трейторов. Теннелинги по лору, если им киборготизацию сделают, то остаются треллами-теннелингами.
