### ISSUE TITLE
[Proposal] RP-Gang wars

### ISSUE THREAD

**Issue by torn223** [TauCetiStation/TauCetiClassic#2566]
Охуительная идея и предложение.

РП-Генг - режим,где главам банд нужно будет убеждать и брататься с другими маргинальными членами экипажа чтобы они вступили в их банды (как в революции). Это может быть мафия главы-бармена или серая волна главы-подопытного. Покупка генговых вещей вроде оружия,инструментов для режима и прочих аксессуарах будет производится - внимание - внутриигровыми кредитами. У Главы будет изначально своеобразный аплинк,через который он должен будет покупать предметы для своей банды на кредиты. Кредиты можно достать двумя способами: Скинуться в общак из своих сбережений,или же ограбить мимокрокодила,заблудившего в практически непосещаемый отсек. Для второго случая Глава может купить своеобразный сканер,который автоматически снимет с счета ИД-карты жертвы все кредиты и переведет их на счет общака. Контроль территории будет производится не с помощью специальных накоденных спреев,а силами самих членов банд и РП процессом,но контроль территории будет не победным условием. Победное условие: Если глава вашей банды не был арестован и/или убит,а главы других банд были арестованы/убиты,то вашей банде засчитывается победа. Если же хотя бы две главы банд живы и не под стражей,то засчитывается ничья. Если все главы банд мертвы или под стражей,то победа засчитывается экипажу. Получение удовольствия от этого режима игры будет зависить целиком от антагонистов. Банда гопарей-сероволновых,которые держат в страхе целую часть станции,быкуют на тех кто их не уважает и старается не ввязываться в открытые сражения между Службой Безопасности - неплохо. Группа террористов-робустеров,которые накупили пистолетов-пулеметов и пошли спидранить раунд,раша мостик с  бригом и убивая всех по пути - хуйня,а ее членам нужно выдать баны.

Что вы думаете по этому поводу? Какие будут недостатки у этого режима? Будут ли игроки отыгрывать свои роли,или же этот режим станет ревой 2.0? Можно ли его внедрять на сервер? Заставить ли меня кодить и спрайтить это все?

**Comment by WallShrabnic** [comment]
https://youtu.be/SeDVNgsYy0k

http://tauceti.ru/forums/index.php?topic=1574.1740

**Comment by WallShrabnic** [comment]
А теперь серьёзно, разберём по частям тобою написанное)))

>Охуительная идея и предложение.

Этим идеям место на форуме

>РП-Генг - режим,где главам банд нужно будет убеждать и брататься с другими маргинальными членами экипажа чтобы они вступили в их банды (как в революции)

Уже минус, текущая реализация РП-ревы просто ужасна сама по себе, а ты предлагаешь сделать ещё один унылый режим, боже, не надо

> Покупка генговых вещей вроде оружия,инструментов для режима и прочих аксессуарах будет производится - внимание - внутриигровыми кредитами

Текущая реализация системы денег элементарно не позволит этого сделать, это раз, вяжущие и бросающие генгеров в карцер по первому обвинению, это два

> Контроль территории будет производится не с помощью специальных накоденных спреев,а силами самих членов банд и РП процессом,но контроль территории будет не победным условием.

Давай, расскажи мне про этот РП процесс, и как его можно реализовать МЕХАНОМ. Игроки не будут просто так РПшить ради РП

> Получение удовольствия от этого режима игры будет зависить целиком от антагонистов

Как и все другие режимы, и зачем это тут нужно, непонятно

> Банда гопарей-сероволновых,которые держат в страхе целую часть станции,быкуют на тех кто их не уважает и старается не ввязываться в открытые сражения между Службой Безопасности - неплохо. Группа террористов-робустеров,которые накупили пистолетов-пулеметов и пошли спидранить раунд,раша мостик с бригом и убивая всех по пути - хуйня,а ее членам нужно выдать баны.

Палю фичу, в первом варианте на банду набегут СБ и результат см. выше. А второй будет происходит каждый второй раз, когда режим будет выпадать в ротацию

> Что вы думаете по этому поводу? Какие будут недостатки у этого режима? Будут ли игроки отыгрывать свои роли,или же этот режим станет ревой 2.0? Можно ли его внедрять на сервер? Заставить ли меня кодить и спрайтить это все?

Вот ответы в порядке появления вопросов.

Идея отвратительна. См. Выше. Нет, не будут. Нет, очевидно. Можешь закодить хоть говно, это уже лично твоё  дело

**Comment by torn223** [comment]
Спасибо за авторитетное мнение,послушаем других людей.
