### ISSUE TITLE
Полкана и Рекса сломали.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#2568]
#### Подробное описание проблемы
Пёсики стали слепоглухонемыми инвалидами.
#### Что должно было произойти
Они должны жрать тех, кто на них лезет.
#### Что произошло на самом деле
Полкана полчаса избивают станбатоном и стреляют в Рекса из пистолета, а им плевать.
#### Как повторить
Избить бедную скотинку.
#### Дополнительная информация:
![](https://i.gyazo.com/794e25c75ac34e05821ff7d3e9a8c712.png)
Не обращайте внимания на гибсы.

**Comment by Skippeer12** [comment]
Они уже старенькие, не кричи на них.

**Comment by RichardJones1** [comment]
Невоспроизводимо на локалке, но пока не закрываю.

**Comment by RichardJones1** [comment]
Попробовали короче, всё работает. Закрываю.
