### ISSUE TITLE
[Proposal] Ништяки для генетики

### ISSUE THREAD

**Issue by maxyo** [TauCetiStation/TauCetiClassic#2572]
Предлагаю сделать ништячки для генетики, чтобы добавить немного реализма и оживить разработочку генетики в целом:
1. Повысить процентный шанс проявления суперсилы до 100% или хотя бы до ~70%
2. Сделать так, чтобы силы и отрицательные эффекты могли выпасть на один блок. Так же сделать шанс выпадения болезни на супер силу 100%.  За все нужно платить. Это как раз уравновесит 1 пункт.
3. Добавить новых суперсил (можно и болезней, если предложат что-то годное):
- Устойчивость к низкому/высокому давлению. Чтобы в купе с другими силами можно было спокойно гулять по космосу.
- Список будет дополнятся

4. Гном и халк НЕ могут быть активны одновременно.

5. Дать гному возможность лазить в вентиляции с наушником.

6. https://github.com/TauCetiStation/TauCetiClassic/issues/2562

Вотъ, хочется список ништяков расширить, поэтому жду ваших предложений. Если тот, кто отвечает за введение фич одобрит, закодирую сам.

**Comment by WallShrabnic** [comment]
#кодить_будешь_ты

**Comment by Sakuya-Izayoi** [comment]
баланс...
