### ISSUE TITLE
[Proposal] Аварийный набор

### ISSUE THREAD

**Issue by Sombra912** [TauCetiStation/TauCetiClassic#2573]
Почему-бы не изменить содержимое коробки в рюкзаке? Можно ведь одолжить идею у Оникса, и сделать такой-же аварийный набор, а не просто баллон с маской.

https://ibb.co/f3Zvuy

**Comment by Sakuya-Izayoi** [comment]
а не многовато ли? ладно ещё автоиньектор, но вот жрачка и бинты это уже слишком.

**Comment by Sombra912** [comment]
На то набор и  "Аварийный"

**Comment by LudwigVonChesterfield** [comment]
Потому-что крупной корпорации, сокращающей деньги на скафандрах, и урезающей зарплаты будет в каеф выдавать полноценный набор с лек-вами, едой, так ещё и баллон-маской, да?

**Comment by TEXH4Pb** [comment]
Можно в лодаут добавить полноценный аварийный набор за дохуя очков.

**Comment by FelixRuin** [comment]
![image](https://user-images.githubusercontent.com/31424899/52522756-92251400-2c9a-11e9-8a96-335b3d0f381f.png)
хоть и аварийным набором и не назвать, в понимании оникса, но тоже можно считать

**Comment by RichardJones1** [comment]
Я считаю, что лишний хлам по типу еды или ножика в такой коробке не нужен
