### ISSUE TITLE
ГУИ фермобота

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2574]
#### Подробное описание проблемы
На классике не работает гуи фермобота.

#### Что должно было произойти
Должно работать гуи фермобота на классике.

#### Что произошло на самом деле
Гуи фермобота не работает на классике

#### Как повторить
Скрафтить фермобота на классике, анлокнуть его айди картой и кликнуть по нему.

#### Дополнительная информация:
На локалке заспаунил фермобота через команду спауна и он работал замечательно. На сервере Тау Кети классик мне робота собирали роботехи и ГУИ фермобота у меня не открывался.

**Comment by WallShrabnic** [comment]
Сначала поищите дубликаты, https://github.com/TauCetiStation/TauCetiClassic/issues/1641
