### ISSUE TITLE
Если занята профа, то роль багнется, при возвращении в лобби

### ISSUE THREAD

**Issue by Gittanley** [TauCetiStation/TauCetiClassic#2577]
#### Подробное описание проблемы
Если установлено в префиренсах "Return to lobby if preference unavailable", и занята профа, и должна была выпасть роль, то роль багается, при реве ты главрев, но в IC нету рев конверта
#### Что должно было произойти
При заходе за другую профу не выдавать роль/выдавать нормально
#### Что произошло на самом деле
Выдает криво
#### Как повторить
Поставить "Return to lobby if preference unavailable", поймать случай когда будет заполнена выбранная профа, и когда выпадает роль, и зайти за другую профу.

**Comment by RichardJones1** [comment]
Да.

**Comment by volas** [comment]
дубликат #1187
