### ISSUE TITLE
Нет симуляции атмоса на ЦК

### ISSUE THREAD

**Issue by Gittanley** [TauCetiStation/TauCetiClassic#2579]
#### Подробное описание проблемы
Инженер раскрутил окно на ЦК, и никого не убило
#### Что должно было произойти
Убить всех разгермой
#### Что произошло на самом деле
Произошла условная линия где можно ходить туда-сюда, возвращаясь из вакуума и обратно в атмосферу ЦК
#### Как повторить
Разобрать окно
#### Дополнительная информация:
![tau ceti station 2018-07-02 205030](https://user-images.githubusercontent.com/33177544/42179065-52208b22-7e3b-11e8-8f4f-1912ac61b772.png)

**Comment by Skippeer12** [comment]
Нет. Просто нет.

**Comment by WallShrabnic** [comment]
Не баг, а фича
