### ISSUE TITLE
Зоны и АПЦ.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#258]
#### Подробное описание проблемы
Созданые зоны для АПЦ чертежами СЕ работают не правильно.
Работает только свет, жизне обеспечение и консоли/вендоматы/машинерия не работают.
#### Что должно было произойти
В зонах созданых игроками должны работать все вещи.
#### Что произошло на самом деле
Работает только свет.
#### Как повторить
Построить комнату и использовать чертежи, поставить АПЦ.
#### Дополнительная информация:

![](http://i.imgur.com/7KfskBJ.png)

**Comment by Nok1a** [comment]
Сегодня тоже заметил. Причём когда используешь чертёж в недостроенной комнате, то размечается всё вместе с космосом, так же как и в законченной ( со стенами и т.д).
