### ISSUE TITLE
Аккаунты департаментов могут выигрывать в лотерею

### ISSUE THREAD

**Issue by Lexakr** [TauCetiStation/TauCetiClassic#2583]
#### Подробное описание проблемы
`-TC Daily wishes to congratulate Civilian Account for recieving the Tau Ceti Stellar Slam Lottery, and receiving the out of this world sum of 10000 credits! 
[Story by NanoTrasen Editor]
`
#### Что должно было произойти
В лотерее должны участвовать только живые существа

**Comment by RichardJones1** [comment]
Скорее пропозал, но оставлю. Довольно легко исправить
