### ISSUE TITLE
Проблема при деклере за учёного

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2586]
#### Подробное описание проблемы
При деклере за учёного учитываются два слота из трёх. Всегда спавнится при начале раунда всего двое, один слот остаётся незанятым после начала раунда и за него можно гарантированно зайти
#### Что должно было произойти
Три слота вучёных
#### Что произошло на самом деле
Слотов при старте два
#### Как повторить
Задеклерится в час пик и помолится шиве на удачу
#### Дополнительная информация:
N/A

**Comment by RichardJones1** [comment]
Всё еще актуально.
