### ISSUE TITLE
[Proposal] Сделать звуки открытия\закрытия шлюзов тише

### ISSUE THREAD

**Issue by ThePunisher95** [TauCetiStation/TauCetiClassic#2589]
Собственно звуки закрытия\открытия шлюзов слишком громкие на фоне остальных звуков. Плюс это очень раздражающий и резкий звук. Вот мне иногда хочется подрубить звук в ССке погромче, но не могу, ибо тогда колонки (и мои уши) разрывает звук шлюзов. А ведь это самый частый звук в ССке.

**Comment by RichardJones1** [comment]
Согласен, даже попытаюсь что-то сделать...

**Comment by RichardJones1** [comment]
#2883
 Done : )
