### ISSUE TITLE
Anomaly power utilizer

### ISSUE THREAD

**Issue by sovok4** [TauCetiStation/TauCetiClassic#259]
#### Подробное описание проблемы
У ксеноархеолога не работает Anomaly power utilizer. Не используется в руке. После вставки баратеи в него - не используется вообще никак. Его даже не разобрать обратно.
#### Что должно было произойти
Вставляешь в него батарейку, заряженную энергией артефакта, используешь в руке, открывается окно, где можно включить сам прибор.
#### Что произошло на самом деле
А ничего, как будто камень в руку взял.
#### Как повторить
Зарядить батарейку энергией включенного артефакта - > Вставить батарейку в Anomaly power utilizer

**Comment by Raschert0** [comment]
А у меня он даже батарейку не заряжает
