### ISSUE TITLE
Сломанные спрееры (обсуждение)

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2591]
#### Подробное описание проблемы
Вещества из спрееров не попадают в кровь при попадании на самого моба
#### Что должно было произойти
Вещества попадают в кровь если на жертве нет защиты
#### Что произошло на самом деле
Ничего
#### Как повторить
Попрыскать на людей из спрееров
#### Дополнительная информация:
https://github.com/TauCetiStation/TauCetiClassic/pull/2479

Не уверен, что это прямо так необходимо, но если отбалансить, то может оказаться довольно забавной мелкофичей

**Comment by LudwigVonChesterfield** [comment]
Небольшое расследование уточнило причину возникновения бага.

<code>	if(self.holder) //for catching rare runtimes
		if(!istype(self.holder.my_atom, /obj/effect/effect/smoke/chem))
			// If the chemicals are in a smoke cloud, do not try to let the chemicals "penetrate" into the mob's system (balance station 13) -- Doohl
			if(method == TOUCH)
				var/chance = 1
				var/block  = FALSE

				world.log << "This is geting weeeeeird"

				for(var/obj/item/clothing/C in M.get_equipped_items())
					if(C.permeability_coefficient < chance)
						chance = C.permeability_coefficient
					if(istype(C, /obj/item/clothing/suit/bio_suit))
						// bio suits are just about completely fool-proof - Doohl
						// kind of a hacky way of making bio suits more resistant to chemicals but w/e
						if(prob(75))
							block = TRUE

					if(istype(C, /obj/item/clothing/head/bio_hood))
						if(prob(75))
							block = TRUE

					chance = chance * 100

					world.log << "[chance]"

					if(prob(chance) && !block)

						world.log << "HEEEY WE ARE REACTING"

						if(M.reagents)
							M.reagents.add_reagent(self.id,self.volume/2)</code>

Как видим, вся процедура передачи реагента выполняется лишь в случае, когда на кукле которой мы передаём реагенты есть хоть какая-то одежда.

<s>А ещё эт показывает мою непричастность к случаю</s>
