### ISSUE TITLE
Сломанные взрывы лампочек

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2593]
#### Подробное описание проблемы
Взрывы лампочек не соответствуют  затраченным усилиям и ресурсам. Более того, всегда вводится в лампочку весь имеющийся форон в шприце
#### Что должно было произойти
Взрыв зависит от количества форона, которое мы ввели. В лампочку вводится весь имеющийся форон в шприце
#### Что произошло на самом деле
Взрыв лампочек не зависит от количества влитого в них форона, и всегда равен двум
#### Как повторить
Вводим шприцом форон в лампочку, вкручиваем, получаем взрыв размером 2
#### Дополнительная информация:
N/A

**Comment by RichardJones1** [comment]
Нужен тестовый фидбек

**Comment by volas** [comment]
может быть довольно грифонистой штукой

**Comment by KuzyXD** [comment]
Предлагаю сделать зависимость от количества форона, но с небольшим увеличением параметра взрыва.
