### ISSUE TITLE
[Proposal]На сервере дебилы на форуме

### ISSUE THREAD

**Issue by Kurshan** [TauCetiStation/TauCetiClassic#2594]
#### Подробное описание проблемы
НА сервере педалят говноеды
#### Что должно было произойти
На сервере не должны педалить говноеды
#### Что произошло на самом деле
В администрации одни говноеды
#### Как повторить
Поставить на трон трупократию
#### Дополнительная информация:
Мне похуй, я полковник
https://pastebin.com/fqkgx3mG

https://i.imgur.com/CKH6SEn.png

**Comment by AgRevol** [comment]
Не баг а фича

**Comment by ThePunisher95** [comment]
А все потому что понабирали всяких непонятных и мутных личностей и потом ещё непонятно зачем защищают их.

**Comment by Lancer411** [comment]
Зато по шаблону.

**Comment by Olt1771** [comment]
ПРИОРИТИ КРИТИКАЛ БЫСТРО

**Comment by Leshiy-ART** [comment]
Обана, круашанчик продолжает падать. Когда будет уже дно, а?

**Comment by wadangel** [comment]
Я не понимаю ваших проблем, честно. Замёржили https://github.com/TauCetiStation/TauCetiClassic/pull/1367 и всё.

**Comment by AgRevol** [comment]
Нам нужен герой который закодит это

**Comment by seekin4u** [comment]
да рассосется все само, че вы

**Comment by WallShrabnic** [comment]
(На самом деле опять нихуя не будет)

**Comment by SpaiR** [comment]
Геополитические войны в другой песочнице, в этой воюют с гитом и мержконфликтами.
