### ISSUE TITLE
[Proposal]Прячущиеся под резиной лицехваты

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2595]
#### Подробное описание проблемы
Лицеёбы могут прятаться под травой алиумов, нанося криты и бросая людей в глубокий сон
#### Что должно было произойти
Лицеёбы сосут при попытке толпой стелсозарашить экипаж
#### Что произошло на самом деле
См. выше
#### Как повторить
Поиграть в инфестейшн
#### Дополнительная информация:
N/A

**Comment by AgRevol** [comment]
Ну серьезно. Вот это - таки фича.

**Comment by WallShrabnic** [comment]
Это нихуя не фича, особенно когда ты зачищаешь грёбанное гнездо и тебя из стелса валят куча этих пидоров

**Comment by AgRevol** [comment]
Именно по-этому траву нужно выжигать.

**Comment by LudwigVonChesterfield** [comment]
Слой у травы выше чем у хаггеров наверное.

**Comment by WallShrabnic** [comment]
Выжигаешь такой траву, горелкой, получаешь фейсхаггера. Выжигаешь огнемётом - бан за массовое убийство из-за разгермы

**Comment by WallShrabnic** [comment]
Если кто-то захочет всерьёз этим заняться, то вот линк на работу Расчера https://github.com/TauCetiStation/TauCetiClassic/pull/1797
