### ISSUE TITLE
Магическая медицина ИСХОДА

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#2596]
#### Подробное описание проблемы
Реанимировали тело человека, после того как из него вырвалась лярва
#### Что должно было произойти
Человека нельзя реанимировать
#### Что произошло на самом деле
Реанимировали, получился кататоник
#### Как повторить
Провести необходимые процедуры с телом из которого вырвалась лярва

**Comment by wadangel** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/1669

**Comment by RichardJones1** [comment]
Алиенобаг который было бы хорошо пофиксить

**Comment by FelixRuin** [comment]
как написано выше, такой ишус уже есть

**Comment by KuzyXD** [comment]
Duplicate of #1669
