### ISSUE TITLE
У ИИ спал туман войны на на космосе и большей части карты Live!

### ISSUE THREAD

**Issue by Kernstall** [TauCetiStation/TauCetiClassic#2599]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/16035287/42531077-b38a802e-848b-11e8-9b7a-bedac966f259.png)
![image](https://user-images.githubusercontent.com/16035287/42531157-e552346c-848b-11e8-88d8-7c817c3fd56e.png)
![image](https://user-images.githubusercontent.com/16035287/42531169-f1dc6edc-848b-11e8-9185-256528d7bdbc.png)
Сервер-гамма, чат скрыл, но ишью написал, потому что могу что-то потестить еще и собрать инфу о баге
На первом пике ученого видно и по нему можно кликать, но джамп на него не происходит, потому что он "вне камер"

#### Что должно было произойти
Этого не должно быть

#### Как повторить
Без понятия, задавайте вопросы, пока я могу что-то потестить. Возможно здесь замешан телесаенс и джамп на ученого

**Comment by Kernstall** [comment]
Перепутал гит, отмена тревоги

**Comment by volas** [comment]
@Kernstall скажи версию бьенда, потом обнови если еще не обновил

**Comment by Kernstall** [comment]
Версия свежая, только качал. 512.1434

**Comment by volas** [comment]
Актуальная бета сейчас 512.1435, попробуй её

**Comment by Kernstall** [comment]
![image](https://user-images.githubusercontent.com/16035287/42534360-3933f72e-8495-11e8-8098-51b514633271.png)
Обновил, не пофиксило

**Comment by volas** [comment]
в билде есть блеклист версий, не переживай ;)

**Comment by RichardJones1** [comment]
Закрыть мб это? @volas

**Comment by volas** [comment]
рано, подождем еще пару месяцев и зафорсим стабильную версию бьенда как реквайред

**Comment by volas** [comment]
#3188
