### ISSUE TITLE
Ядовитый синаптизин

### ISSUE THREAD

**Issue by Valtar74** [TauCetiStation/TauCetiClassic#2606]
#### Подробное описание проблемы
Синаптизин даёт токсичный урон до границы передозировки.
#### Что должно было произойти
Синаптизин не должен давать токсинный урон пока доза не превысила предел передозировки 
#### Что произошло на самом деле
Одна единица синаптизина даёт урон в размере 44 единиц токсичного урона.
#### Как повторить
Вести синаптизин в размере 1 единицы
#### Дополнительная информация:
Общался по этому вопросу с администрацией на гамме и мне сказали что всё нормально он и должен быть токсичным. Вот только в вики у него есть граница передозировки и текущая работа синаптизина мне всё равно кажется неправильной .

**Comment by AgRevol** [comment]
Не баг а фича. А ещё ты вроде говоришь о гамме а это гитхаб классики, но это такое

**Comment by Lancer411** [comment]
Просто после передозировки все становится намного хуже.

**Comment by Valtar74** [comment]
Если всё нормально то нужно внести правки в вики. Сейчас врачи колят синаптизин в размере 5 единиц и отправляют человека гулять. А через минут пять его уже привозят обратно с токсинами под 100. И до большинства докторов не доходит в чём проблема. Таким больным даже диализ не делают потому что передоза нет. Данная проблема на обоих серверах как на гамме так и на классике. Просто на гамме колуны или мимы пихают синаптизин в клинеры и идут всех опрыскивать. 

И пять единиц а это одна иньекция которая даёт 220 токсичного урона. Вколол и человек гарантированно труп. Даже передоз не нужен.

**Comment by Valtar74** [comment]
Когда на станции у экипажа случаются галлюцинации синаптизин и назначают.
Да нужно достаточно много времени что бы почувствовать эффект. Но это не отменяет того факта что одна единица наносит урон в размере 44 единиц токсинов. И врачи очень часто травят им людей. Так что нужна правка на вики что бы доктора не убивали им людей. Или исправить сам синаптизин.

Насчёт клинеров не проверял это только догадка.

**Comment by Valtar74** [comment]
Так это ошибка вики или баг синаптизина который работает не так как написано на вики? Просто для меня первично вики и там написан несколько иной принцип действия в результате чего напрашивается вывод что синаптизин забагован. Поэтому я сюда и написал. Но за совет спасибо.

**Comment by LudwigVonChesterfield** [comment]
На вики не написано, к примеру, что от алкоголя пьянеют. Так это что, баг алкоголя? На вики ведь не написано.

**Comment by Valtar74** [comment]
Если бы на вики написали что от алкоголя пьянеют только при больших дозах а на деле достаточно всего 1 единицы что перестать нормально ходить и говорить. То да это явный баг. Ну или вместо его исправления бага нужно просто написать в вики что алкоголь приводит к опьянению при любых дозах.

**Comment by LudwigVonChesterfield** [comment]
<code>Ну или вместо его исправления бага нужно просто написать в вики</code>

Что ты собственно мог и сделать.
