### ISSUE TITLE
юниверсал пейнтер может красить без картриджа

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2618]
#### Подробное описание проблемы
Если достать картридж из пейинтера он продолжит красить. Судя по всему он вообще тонер из картриджа не юзает

#### Что должно было произойти
Пейнтер должен юзать краску и требовать её наличия

#### Что произошло на самом деле
Он рисует просто так

#### Как повторить
Кликнуть пустым пейнтером на трубу

**Comment by LudwigVonChesterfield** [comment]
Эта проблема не стара, и связана с тем что он эту краску не тратит.

**Comment by KIBORG04** [comment]
пофикшено???

**Comment by Venngedi** [comment]
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/0b035416-d4a3-4299-8c7a-5fa0895d1c67)

> пофикшено???

Да
