### ISSUE TITLE
При выстреле из тесла пушки нет спрайта молнии.

### ISSUE THREAD

**Issue by Zap-zapper** [TauCetiStation/TauCetiClassic#262]

**Comment by ZVee** [comment]
Был проведен локальный тест и на живом сервере. В обоих случаях молнии были.
Предположу что просто бъенд разово баганул, причем скорее всего со стороны клиента - не успел загрузить вовремя спрайт из ресурсов и отобразить клиенту.
С такими вещами желательно делать вывод после многократного подтверждения т.к меня терзают смутные сомнения, что выстрел произведен был единожды после чего был сделан вывод что молний совсем нет.
