### ISSUE TITLE
Тесла пушка.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#264]
#### Подробное описание проблемы
Тесла пушка, которая изучается в РнД не дает продвижения науке.
#### Что должно было произойти
Она должна давать продвижения по различным наукам, например энергии и материалов.
#### Что произошло на самом деле

![](https://i.imgur.com/aAPV61t.png)

#### Как повторить
Кинуть Тесла пушку в деконстрактор.
#### Дополнительная информация:
Вроде как оно прописано там, но его просто нет.

![](https://i.imgur.com/SU3axxw.png)

**Comment by Lancer411** [comment]
https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/projectiles/guns/energy/special.dm#L232
Думаю проблема в этой строке. Конкретно - в лишних пробелах между уровнями и названиями технологий.

**Comment by ZVee** [comment]
fixed in #321
