### ISSUE TITLE
ФИТЧА ИЗ КАРГО! HOT CARGO BOYZZZ

### ISSUE THREAD

**Issue by PrimeTed** [TauCetiStation/TauCetiClassic#267]
#### Подробное описание проблемы
ФИТЧИРУЕМ КАРГО!!!
#### Что должно было произойти
ПРОФИТНЫЕ ИЗИ ОЧКИ В КАРГО!!!
#### Что произошло на самом деле
ПРОФИТНЫЕ ИЗИ ОЧКИ В КАРГО!!!
#### Как повторить
Легко и просто! Заказываем 50 единиц пластика! И строим 5 ящиков! Отправляем ящики и... ПОЛУЧАЕМ ИЗИ ПОИНТЫ! Заказываем еще ящиков пластика, делаем ЕЩЕ БОЛЬШЕ ЯЩИКОВ, получаем ЕЩЕ БОЛЬШЕ ПОИНТОВ! А на полученные поинты заказываем ништяки для СТАНЦИИ.
#### Дополнительная информация: Так же можно делать и с КАНИСТРАМИ ДЛЯ ГАЗА! Заказываем ЖЕЛЕЗО и делаем КАНИСТРЫ. Да это же вполне ЛОГИЧНО. Нам шлют ресурсы, а мы делаем НИШТЯКИ! И нам платят за наш ТРУД! Это вполне ЛОГИЧНО и ПРАВИЛЬНО. Поэтому это скорее ФИТЧА.

**Comment by Lancer411** [comment]
Можно отпилить награды за ящики.
Оставить только за манифесты с печатями и за ценные материалы в ящиках: плазму, вторсырье из мусора, платину.

**Comment by PrimeTed** [comment]
Ахахах! Так вполне можно накрафтить ломов? ИЛИ КАНИСТРЫ!

**Comment by Lancer411** [comment]
Можно, только за них очков не дадут.

**Comment by PrimeTed** [comment]
Ты про канистры газовые уверен?

**Comment by Lancer411** [comment]
https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/controllers/subsystem/shuttles_bay.dm
Вот тут код наград за доставку материалов на ЦК.
Награды выдаются за:
Ящики - 5 очков.
Манифесты из ящиков, с поставленной печатью - 2 очка.
Платина - 10 очков за 1 единицу.
Форон - 3 очка за 1 единицу. (только в твердом виде)
Вторсырье - 3 очка за 1 единицу.

**Comment by PrimeTed** [comment]
Отбой, у вас на таукитах нельзя пластик заказывать.
