### ISSUE TITLE
Новый парк не имеет вентов/скрабберов

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#2673]
Сабж

**Comment by Lexakr** [comment]
Там стоят продублированные венты чуть выше, чтоб не портить "атмосферность" самого парка 
![image](https://user-images.githubusercontent.com/29842063/44013122-da07bcea-9eed-11e8-8215-7aeabb68ca07.png)

**Comment by volas** [comment]
В разгерму парк закрывается и атмосфернику не очень потом удобно его чинить. И просто если давление упадёт без разгермы - не вернётся, пока кто-то не откроет аварийные шлюзы.  
Как вариант, если не хочется располагать на траве - перенести лестницу правее, и поставить венты между шлюзами и лестницей.  
Хотя я не вижу ничего плохого и в вентах на траве.
