### ISSUE TITLE
Кто-то опять сломал механ еды, ожирения и прочего

### ISSUE THREAD

**Issue by EdlerN** [TauCetiStation/TauCetiClassic#2697]
#### Подробное описание проблемы
Чьи-то кривые руки превратили данный аспект игры в какой-то ебучий атракцион.
#### Что должно было произойти
Кукла должна время от времени голодать, время от времени кушать и толстеть если сожрала весь холодильник повара
#### Что произошло на самом деле
Тарелки супа хватает чтобы сделать вас жирдяем на всю жизнь. Но это еще не все. Теперь у нас есть прекрасная возможность набрать вес при нормальных нутриментах. Надо всего-лишь выиграть в лотерею. Чем-то еще объяснить прок ожирения при нутришене 420 на кукле я объяснить не могу. Надеюсь вы в это время не выполняете работы в открытом космосе?
#### Как повторить
Поиграть?
#### Дополнительная информация:
Приведите этот ебаный стыд уже в нормальный вид, кто нибудь.

**Comment by RichardJones1** [comment]
Плюсую, толстел несколько раз с одной банки колы. Надо это дело фиксить, и конкретно.

**Comment by LudwigVonChesterfield** [comment]
#2656

**Comment by volas** [comment]
Это ишью по тестовому PR-у, который с тех пор обновлялся и был смержин, и стоило бы закрыть.

Но эти партизаны всё еще испытывают какие-то проблемы и упорно об этом не сообщают. В общем, ап за ленивых превозмогающих партизанов, чтоб их всех...

**Comment by volas** [comment]
Они так и не дошли. Создавайте новое ишью, кого это волнует.
