### ISSUE TITLE
Событие grid_check работает некорректно.

### ISSUE THREAD

**Issue by skvazarb** [TauCetiStation/TauCetiClassic#270]
#### Подробное описание проблемы
Событие отключает энергию, но энергия не включается обратно после анонса о завершении.
#### Что должно было произойти
Отключение и включение энергии.
#### Что произошло на самом деле
Только отключение энергии.
#### Как повторить
Включить событие.
#### Дополнительная информация:
Не знаю есть ли оно в Secrets, но если Toggle a "lights out" event - это оно, то через панель оно не включается, при нажатии ничего не происходит.

**Comment by Skippeer12** [comment]
Там есть кнопка повер ап, и анповер. А ещё там есть кнопка повер ап алл СЕМЕС.

**Comment by Dennok** [comment]
Наверное поздно но "lights out" event ломает лампы. и все.
