### ISSUE TITLE
Абилка "липа" у воксов закрывает иконку крафта.

### ISSUE THREAD

**Issue by RichardJones1** [TauCetiStation/TauCetiClassic#2700]
#### Подробное описание проблемы
Иконка абилки "липа" у воксов закрывает собой иконку крафта.
#### Что должно было произойти
Иконка крафта должна была бы находиться на экране.
#### Что произошло на самом деле
Иконка абилки "липа" у воксов закрыла собой иконку крафта.
#### Как повторить
Зайти за вокса.

**Comment by BesumniiChebureck** [comment]
Актуально
