### ISSUE TITLE
Сломанная слепота у простых (simple) мобов

### ISSUE THREAD

**Issue by FelixRuin** [TauCetiStation/TauCetiClassic#2701]
#### Подробное описание проблемы
У мобов (simple_animal ?) отсутствует эффект слепоты
#### Что должно было произойти
Мышь в трубе видит только около себя
#### Что произошло на самом деле
Мышь видит всё идеально 
#### Как повторить
Залезть в вентиляцию за мышь
#### Дополнительная информация:
![screenshot_1](https://user-images.githubusercontent.com/31424899/44660861-9d98c180-aa11-11e8-9eae-361e18c85cc8.png)

**Comment by LudwigVonChesterfield** [comment]
Насколько ты уверен что это баг, и то, что люди должны играть за этих существ?

**Comment by FelixRuin** [comment]
мне казалось у всех игроков (не считая некоторых) есть возможность поиграть за мышь? ну и как и в добавок... это странно и неудобно?

**Comment by Kernstall** [comment]
Наоборот ведь удобно

**Comment by KIBORG04** [comment]
Слепота у мышей есть, да и у прочих симплов
