### ISSUE TITLE
[Proposal] Добавить Унатхам кнопку "Threat", которую они обязаны будут использовать для угрозы противнику перед атакой.

### ISSUE THREAD

**Issue by RichardJones1** [TauCetiStation/TauCetiClassic#2708]
#### Подробное описание проблемы
Многие считают, что благодаря бэку у ящеров есть оправдание чрезмерному насилию. Есть реальные примеры когда унатхи ломали череп за косой взгляд или неосторожное слово. Я сталкивался с этим, и я уверен, что вы тоже.
Конечно же, многие игроки предупреждают противника с помощью эмоутов "злобным хисс" или "угрожающе постукивая хвостом по полу", что сейчас унатх будет скратчить. Но мне кажется, и я вижу, что этого недостаточно. Многие игроки-хуманы-другие расы не понимают, что эти жесты являются сигналом "притихни и извинись, или получишь в ебло".
Я не пытаюсь оправдать гриф на ящерах, я хочу **внести ясности в спорные ситуации драк с участием унатхов и дать второй стороне конфликта ясно понять, что если он не прекратить вести себя вызывающе, то сейчас ему будет плохо, либо вызвать СБ.**
**Это не относится к самообороне/ЧП, относится лишь к обычным конфликтам, грубо говоря, это эмоция угрозы.**
#### Решение(?) проблемы
Сегодня беседовали об этом и у меня появилась идея.
На уровне кода сделать ящерам кнопку в интерфейсе, нажимая на которую они будут производить какой то звук/жест(Мое предложение - Низкий "Хисс" и удлинение когтей, но вы, думаю, предложите альтернативу. "@user@ hisses very low, his/her claws extend") , который мы примем за угрозу от ящера кому то физическим наказанием. Еще к этому можно прикодить звук характерный.
На уровне Вики мы пропишем, когда и как это нужно использовать, а в начальном гайде/каком то другом пропишем, что если ящер издает такой звук/жест нужно его успокоить/воздержаться от контакта с ним/позвать СБ. Можно прописать на уровне бэка.
Также можно добавить это в правила, дабы игроки на Унатхах всегда использовали данную кнопку-интент, прежде чем вредить кому-либо.
Алгоритм:
Происходит драка/убийство
Смотрим по логам где ящер совершал тот самый сигнал
Смотрим необходим ли он был
Смотрим как ответила другая сторона, попыталась ли сбавить обороны после сигнала, позвать СБ.
И уже после этого решаем, нужен ли был скрэтч со стороны унатха
Если же ящер, к примеру, не использовал кнопку угрозы, в данной ситуации  он будет учитываться как хуман. Но, повторюсь, **это не относится к самообороне/ЧП, относится лишь к обычным конфликтам, грубо говоря, это эмоция угрозы.**
Помнится, мне кто-то говорил, что закрепить в механе - самый верный метод.
Вот мой концепт иконки:
![anger2](https://user-images.githubusercontent.com/39438947/44994787-f552a200-afa8-11e8-9f47-0918213700e5.png)
**Основа иконки взята с статьи про Унатхов на вики, там много артов авторства либо Smalltasty, либо WalterJe. Спасибо вам за хорошие работы!**
#### Дополнительная информация:
**Играл на Унатхе своем всего лишь 10к, поэтому прошу более опытных игроков помочь/раскритиковать. Высказывайте то, что думаете.**

**Comment by AgRevol** [comment]
Проблем это не решит но только добавит новых. Дискасс

**Comment by volas** [comment]
Мне идея нравится. Если ящеры категорически против нерфов бэка/каких-то правил, то могла бы помочь такая условность. Ящерам разрешается быть грозными и скретчить за оскорбления и косой взгляд, но при этом они обязаны соблюдать ритуал.

Бонусом можно было бы даже докинуть баффы ящеру на время, но там нужно еще на баланс/кулдауны/возможности абуза смотреть.

**Comment by RichardJones1** [comment]
Если говорить о бонусах, не хотелось бы, чтобы это были бонусы к атаке. Фича подрузамевается, как шанс другой стороне конфликта остановить спор/позвать СБ/еще что то предпринять, дабы дело не дошло до драки. Можно дать бонусный резист к урону.

"Проблем это не решит но только добавит новых. Дискасс" - Подробнее, какие проблемы это может добавить?
По поводу "не решит" - го обсудим. В личке ты писал "По моему опыту игры за ящура - всем плевать на угрозы". Но ведь если после данного "специального" эмоута ящера хуман продолжит наезжать, то неправ будет он. Конечно, бывают исключения, может ящер сделал дикое говно... Но ведь в таких случаях надо звать СБ.
А с этим "специальным" эмоутом будет ясно, где переломный момент, и где самое время сказать: "Так, сэр, успокойтесь. Нам не нужна драка."

Еще предложение - при нажатии на кнопку дать на пару-тройку секунд сильное замедление унатху, чтобы у противника точно был шанс изменить ситуацию, а не получить когтями в лицо мнгновенно. Оправдать это можно бэком, например, Унатхи встают в специальную позу угрозы, издавая низкий гортанный звук и выставляя когти напоказ.

**Comment by Kernstall** [comment]
Внезапно, в сске людей не останавливает даже удары ломиком по голове 8 раз, пора бы снять розовые очки. Ты пишешь, что не хочешь, чтобы это был лицензия на гриф для ящеров но это так и будет. Быдло-Васяны, которые делают хисс за "мудак в свою сторону", потом убивают (Не, ну а схуяли, если я должен буду каждый раз отступить от ящера после того, как он нажмет кнопочку хисс, то я лучше выпилю ящеров), а после этого предъявляют, мол УМЕНЯБЫЛАПРИЧИНАЕГОВЫПИЛИТЬЯДЕЛАЛЪХИССЪХИССЪ. Это будущее, которое будет ждать тебя, велком
