### ISSUE TITLE
Ножницы не работают с подарочной бумагой.

### ISSUE THREAD

**Issue by RichardJones1** [TauCetiStation/TauCetiClassic#2714]
#### Подробное описание проблемы
Когда используешь подарочную упаковочную бумагу, во второй(неактивной) руке нужно держать кусачки, а в первой(активной) руке предмет для обвёртывания, и нажать им на бумагу, лежащую на столе. Если же вы не держите кусачек во второй руке в чат вам напишет "You need scissors!". 
Суть проблемы - Если держать во второй руке вместо кусачек Ножницы (Scissors) из барбершопа, то вам будет писать "You need scissors!", и работать бумага не будет, что нелогично.
#### Что должно было произойти
С помощью ножниц и подарочной бумаги я завернул уточку и подарил другу.
#### Что произошло на самом деле
"You need scissors!"
#### Как повторить
С помощью ножниц и подарочной бумаги попытаться завернуть в нее что-то
#### Дополнительная информация:
Я смогу закодить и сам, но могу забыть, а во вторых уже себе составил список дел, не знаю, получится ли... (А еще я косячу с гитом часто)

**Comment by EdlerN** [comment]
Написал бы лучше конкретнее, что дескать ножницы из барбершопа. А то НУТАКОЕ. Просто когда на станции не было этих ножниц - сообщение вполне очевидно намекало на кусачки. А теперь у нас ВНЕЗАПНО появились ножницы. Да.
