### ISSUE TITLE
[Proposal] Починить механ Пии.

### ISSUE THREAD

**Issue by RichardJones1** [TauCetiStation/TauCetiClassic#2722]
Необходимо убрать у Пии возможность быть тритором.
Необходимо починить у Пии доступные модули , такие как: Рация, Записи сб(нельзя ставить аресты).
Необходимо дать возможность Пии использовать эмоуты и examine на окружающем мире.
Возможно стоит добавить новые модули для Пии, дабы разнообразить геймплей.

**Comment by fanxelt** [comment]
Мне нравится, давно пора обратить внимание на вымирающий пИИ который дожен быть ПИЗЖЕ во всём чем стандартный ИИ, а капитанский пИИ должен ещё и двери для капитана открывать и стелить ковровую дорожку. Красную.

**Comment by RichardJones1** [comment]
Эх, нашелся бы герой-кодер...

**Comment by Belfogor** [comment]
не смей! ПИИ тритор это классика!
