### ISSUE TITLE
Подсветка камер ИИ

### ISSUE THREAD

**Issue by DeLaFlash** [TauCetiStation/TauCetiClassic#273]
#### Подробное описание проблемы
При активном переключении подсветки камер ИИ иногда экран становится полностью черным, для исправления приходится применять следование камерой на кого-то.
#### Что должно было произойти
Включение/выключение подсветки
#### Что произошло на самом деле
Черный экран
#### Как повторить
Несколько раз включить/выключить подсветку
#### Дополнительная информация:
Похоже, что возникает при частом использовании кнопки.

**Comment by kopoba** [comment]
[https://bitbucket.org/taucetistation/tauceti/issues/177/---------------------------](url)
