### ISSUE TITLE
Хуманы слышат хайвманд

### ISSUE THREAD

**Issue by CryptoKisik** [TauCetiStation/TauCetiClassic#2738]
#### Подробное описание проблемы
Живые человеки слышат хайвманд аналиенов. 
#### Что должно было произойти
Человеки не должны его слышать. По крайне мере живые.
#### Что произошло на самом деле
Живые человеки прослушивают хайманд.
#### Как повторить
Быть человеком во время аналиенов.
#### Дополнительная информация:
Аналиенов заспавнили, а не форсили. Может тут какая-то загадка.

**Comment by RichardJones1** [comment]
У меня такого бага не было... Можно подробнее, что за обстоятельства?

**Comment by CryptoKisik** [comment]
Да вроде ничего особенного. По крайне мере со стороны хуманов не было сделано. Был режим секрет. В нем трейторы. Туда же заспавнены алиены. Через N время люди начали слышать хайвманд. Сначала немного. Потом и вовсе весь.

**Comment by Ahion** [comment]
Не актуально, Старый иссуй
