### ISSUE TITLE
Сломанная еда и блевотина.

### ISSUE THREAD

**Issue by CryptoKisik** [TauCetiStation/TauCetiClassic#2739]
#### Подробное описание проблемы
Если блевануть или просто проголодаться, то можно жрать очень долго и не наедаться.
#### Что должно было произойти
Проголодался -> съел бутер -> наелся на N время.
#### Что произошло на самом деле
Блеванул/проголодался. Решил поесть. Сожрал 10 беляшей, две пиццы, 10 штук сырого мяса, еще пиццу, вафельки. И все равно хочешь.
#### Как повторить
Быть хуманом и проголодаться. Или же блевануть. Допустим после воронки в телесаенсе.
#### Дополнительная информация:
Ну.. В общем-то что-то сломалось. Иногда проголодаешься. Сожрешь огромный бутер. Дальше персонаж жрать не хочет. Но ты все равно люто голоден и еле ползаешь.

**Comment by RichardJones1** [comment]
+, тоже было

**Comment by RichardJones1** [comment]
Недавно людук пытался пофиксить это
#2838
Поэтому нужен фидбек, осталась ли проблема.
