### ISSUE TITLE
Робот-уборщик заедает у мостика

### ISSUE THREAD

**Issue by RichardJones1** [TauCetiStation/TauCetiClassic#2742]
#### Подробное описание проблемы
Робот уборщик в режиме патруля выключается всегда на одном и том же месте
![123123123](https://user-images.githubusercontent.com/39438947/45921028-f5620580-beb5-11e8-8723-dc32355d85f8.png)

#### Что должно было произойти
Робот должен был патрулировать дальше
#### Что произошло на самом деле
Он выключился
#### Как повторить
Сделать робота уборщика и включить у него режим патруля у медбея

**Comment by Belfogor** [comment]
#1381

**Comment by RichardJones1** [comment]
Тут стоит позвать Лекса, может его рук дело
@Lexakr
