### ISSUE TITLE
АПЦ который невозможно сломать и починить. 

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#275]
#### Подробное описание проблемы

Синии АПЦ и обычные не возможно сломать ни балоном ни чем другим.

![](http://i.imgur.com/a2YhuAk.png)

![](http://i.imgur.com/ZgobO2F.png)
#### Что должно было произойти

Они должны ломатся.
#### Что произошло на самом деле

Ломается только взорваный АПЦ у которого крышка сьехала на бок.

![](http://i.imgur.com/8t00aaw.png)
#### Как повторить

Попробовать сломать АПЦ. Всех типов.

**Comment by Lancer411** [comment]
Рабочие АПЦ нужно разбирать.

**Comment by Dennok** [comment]
Малфонутый апц не разобрать. Так как заблокированный не разблокировать.

**Comment by Skippeer12** [comment]
Я про то, что АПЦ нужно сделать ломающимся, как камеры есвордом.
Ну не прям срезать, а чу-чуть крышку срезал и зона уже без энернии.

**Comment by Dennok** [comment]
отвертка, кусачки и зона без света, дело 2-3х кликов. (ожоги в довесок, но это так)

**Comment by Dennok** [comment]
еще 1 иссуе и ктото починит єтот баг

**Comment by RichardJones1** [comment]
Да, и мираклер на гамме делал багфикс
