### ISSUE TITLE
Wipe Core

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#276]
**Подробное описание проблемы**
Не работает кнопка Wipe Core у ИИ

**Что должно было произойти**
ИИ должен был покинуть игру. 

**Что произошло на самом деле**
Пришло оповещение в общий чат о том что ИИ был помещен в хранилище, но ИИ остался в игре.

**Как повторить**
Нажмите кнопку Wipe Core

Дополнительная информация:

**Comment by WallShrabnic** [comment]
Таким образом можно абузить ИИ - тритора
