### ISSUE TITLE
Контроль атмосферы за ИИ на "Стрельбище"

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#278]
#### Подробное описание проблемы
ИИ не способен контролировать атмосферу отсека "Стрельбища" в бриге.
#### Что должно было произойти
ИИ должен нормально манипулировать атмосферной панелью на стрельбище.
#### Что произошло на самом деле
Вентили не слушались ИИ, экстренная откачка, перекрытие вентилей и прочее не работало. В результате, было выбито окно и постоянно закачивался отсек и воздух уходил в космос.
#### Как повторить
Зайти ИИ, поклацать панель контроля воздуха на стрельбище.
#### Дополнительная информация:
Уже не помню когда было, забыл написать. Забыл проверить работает ли с помощью компа в атмосферке. На следующем раунде попросил через ЛООК другого ИИ проверить будет ли работать. У него тоже ничего не вышло.

**Comment by Raschert0** [comment]
На стрелтбище (и в оружейке) у аир алярма стоит частота, отличная от дефолтной. Не знаю зачем это сделано. На стрельбище это скорее всего баг, а вот в арсенале могло быть так и задумано.
