### ISSUE TITLE
Бесполезные провода у дронов.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#2780]
#### Подробное описание проблемы
Дроны не умеют подбирать провода, а тридцатки им мало. Это BUG, а не ПРОПОЛЗАЛ, потому что.
#### Что должно было произойти
Они должны уметь подбирать провода. Ну или сделать им единиц 60, а то даже соляры в один заход не настроить нормально.
#### Что произошло на самом деле
Они не умеют.
#### Как повторить
Попробовать подобрать провода дроном.
#### Дополнительная информация:
Если бы у них повысили вместимость клинера и дали бы голопроектор табличек - это было бы идеально.

**Comment by Valtar74** [comment]
Поиграл сегодня за дрона, провода подбираются но не все и лимит у них 50. Вроде там провод должен быть белым и ещё некое условие. Провода в ассистентской я нормально подобрал а вот точно такой же белый в техах взять не смог.
