### ISSUE TITLE
Худ не переключается

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#2793]
#### Подробное описание проблемы
На F12 худ не переключается и итемы из слотов исчезают

#### Что должно было произойти
Худ должен переключаться

#### Что произошло на самом деле
После первого нажатия клавиши худ нельзя вернуть на экран. После перезахода итемы из слотов пропадают.

#### Как повторить
Нажать F12 несколько раз

#### Дополнительная информация:
пофиксите плиз

**Comment by Kortez90** [comment]
После релога вещи не пропадают, они не отображаются в худе, но они существуют. Проблема все еще актуальна на классике.
