### ISSUE TITLE
Нет регенерации урона при кровоточении у дион

### ISSUE THREAD

**Issue by FelixRuin** [TauCetiStation/TauCetiClassic#2799]
#### Подробное описание проблемы
Получив порез диона кровоточит (эффекта нет, но в описании есть) и получив брут или бёрн урон диона не регенерирует его вовсе, полностью завися от бинтов и мази из аптечки
#### Что должно было произойти
Диона получив порез и брут и/или бёрн постепенно регенирует урон
#### Что произошло на самом деле
Диона не регенерирует вообще после пореза
#### Как повторить
За диону получить брёт или бёрн урон после пореза

**Comment by RichardJones1** [comment]
Я так понимаю , человека не устраивает скорость регенерации Дион?

**Comment by RichardJones1** [comment]
Ещё информация - похоже, отсутствие регенерации было связано с новым светом, который мы тестили около месяца назад. Я напишу это в ПР со светом, а данное ишью закрою.
