### ISSUE TITLE
Где взрывы?

### ISSUE THREAD

**Issue by StrikS** [TauCetiStation/TauCetiClassic#280]
#### Подробное описание проблемы

Отсутствуют взрывы при использовании химических реагентов
#### Что должно было произойти

Закачиваем в сигарету шприцом форон получаем взрыв.
Кидаем гранату с калием и водой получаем взрыв.
#### Что произошло на самом деле

Закачиваем в сигарету шприцом форон получаем исчезновение сигареты и урон как с кулака в лицо
Кидаем гранату с калием и водой не получаем ни царапины.
#### Дополнительная информация:

Тоже самое если залить в мензурку калия, а потом долить воды.
Вчера сам пытался бахнуть гранату и был расстроен, как сказал Шкип это кодеры поломали взрывы, но я удивлен что баг-репорта до сих пор не было, хотя взрывы важно и весело. =)

**Comment by Dennok** [comment]
> Кидаем гранату с калием и водой не получаем ни царапины.
Это намеренный нерф.

> Закачиваем в сигарету шприцом форон получаем исчезновение сигареты и урон как с кулака в лицо
Вот это уж не знаю.

**Comment by StrikS** [comment]
Давайте тогда еще сингу сделаем безобидной, теслу и будем пить чай.

**Comment by StrikS** [comment]
Нельзя нерфить взрывы, это часть механа. Это как сухой закон, нужно не взрывчатку запрещать, а учить людей думать перед тем как бахать.

**Comment by Zap-zapper** [comment]
Я позавчера кидал в нюкеров водокалиевую гранату - по 100 каждого. До дырки в полу пробило.

**Comment by StrikS** [comment]
В гранату по 30 каждого, не царапины в полу. Заливал в пробирку 50 калия и доливал 50 воды. Даже не поцарапало.

**Comment by TermService** [comment]
Вчера вколол себе калий, затем воду(калия 15, воды - 5), я загорелся и норм побило так-то
