### ISSUE TITLE
Халк в одежде

### ISSUE THREAD

**Issue by ProrochPro** [TauCetiStation/TauCetiClassic#281]
#### Подробное описание проблемы

Был халком и после того как я уговорил РД меня не убивать, он освободил меня. Я хотел одеться но не мог взять в руки. Только когда мне кто-то протягивая что либо.
#### Что должно было произойти

Ну не знаю мб это фича, но наверное я не мог бы взять в руки что либо. Тем более одеть ещё.
#### Что произошло на самом деле

Я напялил на себя одежду и Всё. 
#### Как повторить

Протяните Халку коробку спичек и он её возьмёт не смотря на размер.
#### Дополнительная информация:

(

**Comment by Dennok** [comment]
Фича.
Халк не может в одежду.

**Comment by Kurshan** [comment]
Тащемта, фича, халки не могут брать итемы, если у них маленький w_class.

**Comment by Dennok** [comment]
И вообще , халки же это симпл мобы теперь., вроде.

**Comment by Kurshan** [comment]
Тут речь про хуманов с геном халка.

**Comment by ZVee** [comment]
Заберу на себя, возможно что-то пересмотрю на текущую реализацию (но все это не раньше (вообще все что заасигнил на себя недавно), чем отвалится фриз и будет мерж хотя бы контроллеров думаю).
