### ISSUE TITLE
Стул теряет цвет при бакле

### ISSUE THREAD

**Issue by hitsedesen** [TauCetiStation/TauCetiClassic#2817]
#### Подробное описание проблемы
При бакле на стул с синей седушкой и спинкой они меняют цвет на серый.
#### Что должно было произойти
Стул должен был остаться синим
#### Что произошло на самом деле
Стул поменял цвет
#### Как повторить
Забаклиться на стул
#### Дополнительная информация:
![](https://i.imgur.com/B1z85ro.png) ![](https://i.imgur.com/iOuRBzZ.png)

**Comment by FelixRuin** [comment]
так вроде со всеми стульями? нет? да и эта вещь... очень спорно на тему того что это баг или фича, так-как не влияет на что-либо и имеет свою пользу?

**Comment by hitsedesen** [comment]
И в чём же здесь "фича"?

**Comment by FelixRuin** [comment]
например в том что даже не смотря экземайном можно сказать сидит ли что-либо на чём-либо?

**Comment by RichardJones1** [comment]
У меня там как раз висит ПР с изменениями в этих файлах. Пофикшу, спасибо!
