### ISSUE TITLE
Сушение рук на расстоянии

### ISSUE THREAD

**Issue by hitsedesen** [TauCetiStation/TauCetiClassic#2819]
#### Подробное описание проблемы
Если начать сушку рук, затем отойти от аппарата и в последний момент к нему подойти - отобразится сообщение о том, что руки высушены.
#### Что должно было произойти
Процесс сушки рук должен был прерваться
#### Что произошло на самом деле
Руки высушены, хотя космонавт во время сушки гулял в нескольких тайлах от сушилки
#### Как повторить
Активировать сушилку, отойти на время звука сушки, как только звук сушки прекратится - сразу подойти на соседний к сушилке тайл.

**Comment by RichardJones1** [comment]
Надо в прок сушки добавить ду_афтер, как в проке разварки стены вилдинг тулом

**Comment by hitsedesen** [comment]
С раковиной, кстати, баг аналогичный
