### ISSUE TITLE
С макаки исчезает одежда, когда берёшь её на руки 

### ISSUE THREAD

**Issue by hitsedesen** [TauCetiStation/TauCetiClassic#2820]
#### Подробное описание проблемы
Если взять макаку, которая в баре, на руки, а потом дропнуть на пол, она будет без одежды, пока не сдвинется.
#### Что должно было произойти
Макака должна появится на полу в одежде.
#### Что произошло на самом деле
Макака без одежды, пока не сдвинется.
#### Как повторить
Взять макаку в руки, Drop на пол
#### Дополнительная информация:
![](https://i.imgur.com/lHJInsF.png)

**Comment by RichardJones1** [comment]
Ору, вот это баг)))) Да ты прямо машина для поиска багов
По поводу решения - подозреваю, что нужно добавить макаке update_icon куда то
