### ISSUE TITLE
Лицехват не закрывает обзор, когда находится на голове 

### ISSUE THREAD

**Issue by ghost** [TauCetiStation/TauCetiClassic#2826]
#### Подробное описание проблемы
Лицехват не закрывает обзор, когда находится на голове
#### Что должно было произойти
Ничего не видно, ведь на голове лицехват
#### Что произошло на самом деле
Всё видно будто его и нет
#### Как повторить
Нацепить лицехвата на голову
#### Дополнительная информация:
![](https://i.imgur.com/Nkq0Kya.png)

**Comment by RichardJones1** [comment]
У нас есть повязка на глаза, она слепоту не вызывает? Это, конечно, скорее пропозал, но было бы логично на самом деле.

**Comment by Motzord** [comment]
игрушечный лицехват не закрывает, ксенолицехват закрывает. Баг или фича?
