### ISSUE TITLE
Борги могут пристёгиваться к стульям

### ISSUE THREAD

**Issue by hitsedesen** [TauCetiStation/TauCetiClassic#2827]
#### Подробное описание проблемы
Боргом можно забаклиться на стул, после этого отбаклиться невозможно
#### Что должно было произойти
Борг не сел на стул
#### Что произошло на самом деле
Борг сел на стул и решил не вставать
#### Как повторить
Взять борга, встать на тайл со стулом, перетащить свою иконку на иконку стула
#### Дополнительная информация:
![](https://i.imgur.com/4VpmuUj.png)

**Comment by Belfogor** [comment]
Малогей detected

**Comment by RichardJones1** [comment]
Одна из многих проблем, являющихся следствием отсутствия у боргов человеческого механа рук. Я короче гляну, как решили эту проблему ребята с запала, и тогда посмотрим.
