### ISSUE TITLE
С сандалей не исчезает оверлей крови при мытье в раковине

### ISSUE THREAD

**Issue by hitsedesen** [TauCetiStation/TauCetiClassic#2831]
#### Подробное описание проблемы
С сандалей не смывается кровь, а точнее не исчезает оверлей крови
#### Что должно было произойти
Кровь должна смыться
#### Что произошло на самом деле
Оверлей крови остался
#### Как повторить
Запачкать сандали в крови, потом помыть

**Comment by StrikS** [comment]
А что, смывается?

**Comment by Motzord** [comment]
Не смывается, все еще актуально,  поднимаю так сказать
