### ISSUE TITLE
Одновременное использование раковины и сушилки для рук

### ISSUE THREAD

**Issue by hitsedesen** [TauCetiStation/TauCetiClassic#2833]
#### Подробное описание проблемы
Когда раковина и сушилка для рук распологаются рядом, можно нажать на раковину а потом на сушилку для рук, будут одновременно мыться и сушиться руки.
#### Что должно было произойти
Прекратиться мытьё рук или не начаться сушка.
#### Что произошло на самом деле
Одновременное мытьё и сушка рук
#### Как повторить
Кликнут на раковину, затем на сушилку, распологающиеся рядом.

**Comment by RichardJones1** [comment]
Это фича: одну руку можешь, а другую сушишь)))
