### ISSUE TITLE
Заикание у больных и бедных.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#2839]
#### Подробное описание проблемы

Куклы не заикаются, не расстягивают слова. Проблема в проках stutter(), slur(). Я точно не знаю, но Волас уведомлён, и вроде даже знает как это починить. Иссуй пишу для отчётности, и чтобы глаза мазолило.

#### Что должно было произойти

Обратное от описанного в пункте выше.

#### Что произошло на самом деле

Обратное от описанного в пункте выше.

#### Как повторить

Хорошенько получить в табло или сундук, увидеть в чатике "Your name stutters, "blah blah blah"", понять что ты ни капли не stutters.

#### Дополнительная информация:

Я даже не виноват. Feels good man.

**Comment by RichardJones1** [comment]
Новая проблема - теперь заикаются растягивая каждую букву на 4, это ужасно

**Comment by LudwigVonChesterfield** [comment]
Но ведь то что ты описал и есть задуманным механом, насколько помню Волас это уже починил, так что можно закрывать.

**Comment by LudwigVonChesterfield** [comment]
#2879
