### ISSUE TITLE
СПУ, СПУ и еще раз СПУ.

### ISSUE THREAD

**Issue by shadence** [TauCetiStation/TauCetiClassic#285]
#### Подробное описание проблемы

Проблема первая: Отрывает ладони ДАЖЕ  в изолированных перчатках при ударе током, например, при работе с проводами. Нужно бы защиту также, как и от сварки или флешек.
Проблема вторая: Портабл сьют кулеры не работают вообще. Космос остается не для СПУ. Перегрев и плавка всего, что можно.
Проблема три: OH&S. Этим все сказано. Кто придумал ограничения на самопочинку? Это же говно. Казните его.
Проблема четыре: OH SHIT IPC HAS BLOOD. СПУ-культи рисуют кровью, повреждая себя. Хеллоу OH&S при починке. Уберите им культей или просто дайте масляные руны.
Проблема пять: Особенные СПУ, что с начала раунда, не оперируются. У того СПУ брейндамаг и порваны легкие! HIRURG STABS IPC WITH THE SCALPEL
Проблема шесть: Брейндамаг ладно, повреждена позитронка и тд, и тп. Но порванные легкие?..
Проблема семь: Если не отменять OH&S, то разрешите хотя бы юзать нанопасту, что не работает на СПУ вообще. There's nothing to fix!
#### Что должно было произойти

1 - провод отрезаться, ладони остаться на месте.
2 - охлаждение системы, хождение по космосу или вакуумной среде
3 - починка и уменьшение урона, что на конечности
4 - масляные руны, либо отсутствие СПУ-культи.
5 - хирург(робототехник) оперирует СПУ. Robototehnik starts to cut IPC's left arm(например)!
6 - ничего не должно произойти. Внутренности остаться в порядке, которых нет.
7 - IPC applies the nanopaste to it's left arm(например)!
#### Что произошло на самом деле

1 - отлетели ладони. Перчатки остались
2 - перегрев и крит.
3 - повреждения остались
4 - рисуем блюспейс кровью, которой нет
5 - хирург забивает СПУ скальпелем
6 - порваны легкие
7 - Nothing to fix! Нанопаста не видит повреждения.
#### Как повторить

1 - попробовать поработать с электричеством, кусачками порезать провода.
2 - надеть сьют кулер, скафандр. Выйти в космос или куда-нибудь еще. Перегреться.
3 - попробовать починить себя горелкой или проводами. Умереть от того, что вовремя рука не починена.
4 - дать культиста СПУ. Наблюдать, как СПУ самоубивается без регенерации, рисуя тем, что отсутствует.
5 - нажать деклер, появиться за СПУ. Попросить себя пооперировать. 
6 - получить порванные легкие, выйдя в вакуум. Еще можно надеть баллон с маской, чтобы эффект проявился быстрее.
7 - попробовать юзнуть нанопасту на СПУ.
#### Дополнительная информация:

СПУ нужны. #ПочинитеСПУ #СделайтеСПУИграбельными

**Comment by ZVee** [comment]
1 - перчатки защищают полностью, ничего никуда не отлетало.
2 - охлаждает, другое дело что я обнаружил баг с самим охладителем - даже если заряд весь израсходуется, он все равно продолжает охлаждать исправно.

**Comment by LudwigVonChesterfield** [comment]
Абсолютно все проблемы описанные здесь или больше не актуальны, или явно являются фичами - OH&S

1 - ладошек нет
2 - кулер фиксили
3 - самопочинка - таки фича
4 - вынесу в отдельный ишуй, туда же припишу дион
5 - у СПУ уже свои операции
6 - у СПУ свои органы
7 - OH&S - явно фича
