### ISSUE TITLE
Достаём предметы из ёмкостей которые лежат в сумках.

### ISSUE THREAD

**Issue by Zandwitch23** [TauCetiStation/TauCetiClassic#2861]
#### Подробное описание проблемы
 Проблема в том что можно достать предмет, который лежит в коробочке, которая в свою очередь лежит в сумке, кликнув на фон предмета.
#### Что должно было произойти
 Ничего, как и когда жмёшь на иконку предмета.
#### Что произошло на самом деле
 Предмет оказался в руке.
#### Как повторить
 Берем в руку любую ёмкость с содержимым, которая влезет в рюкзак, например коробку с donk-pockets. Открываем её и убираем в сумку, при этом содержимое коробки остаётся на экране. Кликаем по фону, на котором изображена булочка.
#### Дополнительная информация:
 Возможно стоит рассмотреть вариант чтобы оставить эту возможность и соответственно починить наоборот саму иконку. Ирл такое представить можно. Тем более раз уж мы можем открыть саму коробочку не доставая из рюкзака перетягиванием на куклу.

**Comment by RichardJones1** [comment]
Да, знаю такой трабл, раньше дупал, что это фича...
Если говорить о сумках в целом, помню у Юлианза была совсем радикальная система, которую он взял и Ириса - рюкзаки нельзя открывать, если они на спине, а не в руке. Возможно, стоит подумать над этим вариантом, но... Мне кажется, это ненужное усложнение.

По идее можно убрать возможность таким образом открывать контейнеры, которые лежат у вас в рюкзаке.

**Comment by Zandwitch23** [comment]
Зато как удобно маску с баллоном при внезапных разгермах доставать. А ещё помните про инвалидов. Кстати залезть в рюкзак на спине одной рукой не так сложно, ну и там внутрь чего то зелезть тоже. Правда можно руку поранить о молнию.

**Comment by RichardJones1** [comment]
Хмммм, а ведь ты прав. Так в чем тогда баг?

**Comment by StrikS** [comment]
Это баг, и его надо фиксить.
Юлианза вариант лично мне не особо нравится. Усложнение ради усложнения. Рюкзаки станут юзлес. 
Есть вариант урезать по слотам сумку, но дать возможность вытаскивать вещи из коробок. Тогда и волки сыты и овцы целы. Но это сами смотрите, просто пришла идея такая.

**Comment by Belfogor** [comment]
На самом деле логично, чтобы вещи из рюкзака нельзя было достать, если не снял этот самый рюкзак со спины. Рюкзаки станут не анюзлес, просто теперь придется вещи первостепенной важности выкладывать в слоты, к которым можно получить доступ максимально быстро.

**Comment by RichardJones1** [comment]
>Ну на Фон иконки нажимаешь и берется предмет, а не на саму иконку.
Пофиксили, закрываю.
#2865
