### ISSUE TITLE
Склянка в модификаторе ДНК

### ISSUE THREAD

**Issue by Urantij** [TauCetiStation/TauCetiClassic#287]
#### Подробное описание проблемы
Если положить склянку с чем-либо в модификатор ДНК, а затем открыть/закрыть его, то склянка окажется снаружи. Её можно будет взять, переместить. Но в интерфейсе будет показано, что склянка всё ещё внутри модификатора. Если попытаться извлечь её, то она телепортируется к модификатору, словно была извлечена нормально.

#### Что должно было произойти
При открывании/закрывании модификатора ДНК склянка не должна выпадать.

#### Что произошло на самом деле
Склянка выпала.

#### Как повторить
Положить склянку в модификатор ДНК, затем открыть или закрыть его.

#### Дополнительная информация:
Не знаю, бесполезный баг, но раздражает.

**Comment by pblp** [comment]
Такой херни много. Слиперы, баг с крио и грабом, криокамеры в дормах.
