### ISSUE TITLE
Пиратисы и их волосы(особенно с ксеносами)

### ISSUE THREAD

**Issue by shadence** [TauCetiStation/TauCetiClassic#290]
#### Подробное описание проблемы

Когда человек или ксенос появляется за пирата, то у него нет волос/щупалец/другого
#### Что должно было произойти

Должны появиться с волосами/щупальцами/другим
#### Что произошло на самом деле

Лысые пираты, скреллы без щупалец
#### Как повторить

Зайти за перата
#### Дополнительная информация:
# ПофикситеКулингСистемыЗаСПУПиратаНереальноИгратьИЗаНюкераТоже

**Comment by ZVee** [comment]
Вообще, пираты задумывались только людьми, а в будущем случайная раса, которая будет одинакова для всех ее членов. Так что появление за ксеноса скорее баг, а не отсутствие "мохнатости".

**Comment by Skippeer12** [comment]
Вообще лучше оставить всё как есть, это же пейраты, пусть бегают лысыми.

**Comment by ZVee** [comment]
@Skippeer12 Не знаю, мне кажется что набегание 6-ю котами, унатхами, скреллами (в обход ВЛ конечно же) и т.д. выгляделоб забавнее, чем микс из разных рас.

**Comment by WallShrabnic** [comment]
Халявный вайт, не жирно ли?

**Comment by ZVee** [comment]
@WallShrabnic халявный вайт для конкретного режима который будет тебе форсить расу на ту, что решит рандом, даже если у тебя стоит другая и ты ненавидишь ту, за которую тебя забросило? Это тоже что и генетика с ее пересадкой мозгов, ксенобиология с ее големами, абдуторы с их режимом, в конце концов генокрады.

**Comment by dearprincesscelestia** [comment]
Поддерживаю пиратесов с разными вкусами. Котонабеги будут замечательны.

**Comment by Skippeer12** [comment]
Ну тогда для СПУ нужно делать холодильники, потому что все соснут ещё на шаттле.
