### ISSUE TITLE
Дионы не могут регенерировать после перелома

### ISSUE THREAD

**Issue by Chupakabrius** [TauCetiStation/TauCetiClassic#2900]
#### Подробное описание проблемы
После получения некоторого урона что ломает кости, регенерация прекращается (именно костей. Окси урон застывает). Остальная регенерация идёт нормально, но через определённый промежуток времени начинается голод.

**Comment by LudwigVonChesterfield** [comment]
Это фича. Дионы регенерируют сначала внутренние органы, потом переломы, а потом только простой дамга.

**Comment by RichardJones1** [comment]
Закрываю?

**Comment by Chupakabrius** [comment]
Это фича... превосходно. Значит я регенерировал внутренние органы два часа живя на удобрениях?

**Comment by LudwigVonChesterfield** [comment]
учитывая один из внутренних органов отвечает за способность к регенерации - вполне вероятно что да.

**Comment by Chupakabrius** [comment]
Но урон был нанесён только голове

**Comment by RichardJones1** [comment]
Значит, пока оставляю. Если честно, не особо понимаю код Дион... А ведь там уже скопилось багов
