### ISSUE TITLE
[Proposal] Взаимодействие с останками.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#2902]
Было бы круто если бы с ними можно было бы взаимодействовать чуть больше чем никак, как минимум:
1) возможность их сломать
2) возможность их взять в граб и бросить(?)

Как максимум:
1) возможность разбить их на косточки, а те подрубить и получить кальций, или ещё какую ересь.

**Comment by RichardJones1** [comment]
Actually a very good idea! Займусь

**Comment by LudwigVonChesterfield** [comment]
А ещё накрутите взаимодействия с паранормальщиной! Ну или я накручу... Подсвечники там из черепов... Черепа в принципе. И чтобы у людей которых сжигало оставались одни только косточки! охохохох

**Comment by Chupakabrius** [comment]
Тогда было бы превосходно разделывать трупы и получать кости. Разделал человека, у тебя есть скелет, добавил прутиков и вот тебе анатомический скелет у СМО(мясо в генетику, а медбею декорации под хелуин)... или у повара выставка костей зверюшек.
Светильника, кресла, стулья, столы, пол, двери... эх... романтика.
