### ISSUE TITLE
Лента позволяет проходить сквозь препятствия

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2919]
#### Подробное описание проблемы
Если поставить ленту а потом построить на ней объект, можно проходить сквозь этот объект
#### Что должно было произойти
Человек не должен проходить сквозь шлюз на котором стоит лента
#### Что произошло на самом деле
Он проходит
#### Как повторить
Поставить ленту, поставить НА ленте аирлок/стол, пройти сквозь объект

**Comment by Lizurt** [comment]
Также хочу добавить, что помимо объектов, можно вставать в тайл с другим человеком без проблем, если перемещаться по ленточке.

**Comment by Alexofp** [comment]
Исправлено в #3572
