### ISSUE TITLE
Отсутствие значка профессии ксеноархеолога в худе СБ

### ISSUE THREAD

**Issue by Lizurt** [TauCetiStation/TauCetiClassic#2927]
#### Подробное описание проблемы
Значок в худе СБ у ксеноархеолога не отображается. Знака вопроса даже нет, ничего нет.
#### Что должно было произойти
Значок на подобии какой нибудь кирки в фиолетовом окне должен был появиться
#### Что произошло на самом деле
Его нет
#### Как повторить
/
#### Дополнительная информация:
Также, возможно, этот баг остался и у парикмахера, но за него так редко заходят люди, что я даже не знаю, пофиксили ли его.

**Comment by RichardJones1** [comment]
Ок, спасибо, гляну сегодня, что там.
