### ISSUE TITLE
Сломанный резист

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#2932]
#### Подробное описание проблемы
При дизарме (а может и при остальных случаях где хуман лежит на полу) его невозможно грабать из за того что он мгновенно резистается пока находится в стане.
#### Что должно было произойти
Человек не должен суметь резистаться пока стан не прошел.
#### Что произошло на самом деле
Он резистается и захваты стали невозможными.
#### Как повторить
Попросить задизармить себя и прижать к полу а самому жать резист,

**Comment by AgRevol** [comment]
Чё пацаны возвращаем бои где дизарм страшнее есворда, а весь робаст сводится к тому кто первый грабнет врага?
