### ISSUE TITLE
Проблемы с питательностью еды

### ISSUE THREAD

**Issue by Lizurt** [TauCetiStation/TauCetiClassic#2933]
#### Подробное описание проблемы
Некоторая часть еды имеет крайне низкую питательность. Кукла съест много еды, но не насытится и захочет есть через 5 минут. Конкретный пример: пончики. Съев 6 пончиков вы, конечно, немного утолите голод , но только на минут 7. Потом вы снова будете хотеть есть. Эта проблема также, скорее всего, есть и у другой еды. 
#### Что должно было произойти
Еда должна обладать нормальной питательностью и утолять голод исправно
#### Что произошло на самом деле
Еда почти на насытила вас! Вы снова хотите есть, хотя съели кучу пончиков
#### Как повторить
Дождаться голода, съесть какую нибудь пищу
#### Дополнительная информация:
Пожалуйста ПОФИКСИТЕ ЭТО НАКОНЕЦ. Это проблема существует уже долго(несколько месяцев) и она очень раздражает.
Рамен с водой имеет нормальную питательность, можете отталкиваться от него. Стаканчик дошика не позволяет голоду вас потревожить вас хотя бы на 40 минут(20 для скреллов)

**Comment by LudwigVonChesterfield** [comment]
Насчёт пончиков имеет смысл.

От части проблема в том, что теперь разные реагенты насыщают не одновременно, а все вместе превращаются в единую массу которая дольше усваивается и меньше подкармливает. Поэтому тот же пончик в котором раньше было 3 уникальных реагента по 3 единицы объема  которые давали по 1 единице пищи за тик насыщал на 3, и умирал за 3 тика, теперь насыщает на 1 за тик ы течении 9 тиков, поэтому создаётся впечатление того что не насыщает

**Comment by LudwigVonChesterfield** [comment]
А ещё пока фиксил то как закодили питательность некоторой еды, невольно занерфил некоторые показатели. К примеру дошик в полтора разв менее питательнее, ведь так сильно насыщал исключительно из-за бага.

**Comment by KuzyXD** [comment]
А ведь уже оно на Тест мердже.
fixed #3730
