### ISSUE TITLE
Emoji in IE8

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#2941]
https://github.com/TauCetiStation/TauCetiClassic/blob/4c7f11d213f835ecbaed4103d74e5d237d1b0102/code/modules/goonchat/browserassets/js/browserOutput.js#L979

При просмотре логов заметил, что возможно у кого-то не работает эмоджипикер (не определенная функция)

**Comment by KiPakr** [comment]
У меня стоял IE8 и все эмоджи были пустыми квадратами. Но не только в сс-ке, так же в Яндекс Алисе. Так..если интересно.

**Comment by SpaiR** [comment]
ie8 в 2019

![image](https://user-images.githubusercontent.com/12721311/50605469-682a4600-0ed3-11e9-826f-db613d91ef3e.png)
