### ISSUE TITLE
[Proposal] Заставить куклы дышать

### ISSUE THREAD

**Issue by Garrysman232** [TauCetiStation/TauCetiClassic#2946]
Было бы неплохо приблизить потребность в воздухе у кукол ближе к реальности, ибо после отключения атмоса и т.д станция вполне неплохо функционирует на протяжении слишком долгого времени, например человек за минуту вдыхает 7 литров воздуха, в кубометре их 1000, нижняя граница содержания кислорода в воздухе, при котором человек может дышать - 17%, по Российским стандартам человеку необходим один кубометр воздуха в час, привязываем все это к внутриигровому времени и вуа-ля 

В чем смысл моего предложения? 

Сделать атмос чуть более нужным станции чем есть сейчас, сейчас можно спокойно вырезать атмос и станция будет работать(Ну разгермы не считаем), причем работать довольно долго, если прибавить потребность в кислороде у кукол то все станет гораздо лучше, а чтобы применить мое предложение не надо даже карту переделывать, все есть, просто надо чутка прибавить либо частоту использования кислорода, либо его объем, я конечно и сам закодил бы, но ваш мунспикный DM я не понимаю, так что вот

**Comment by RichardJones1** [comment]
имхо, тут и так у нас слишком не-казуально всё. ты видел как с этим на тг? куклы спокойно ходят в космосе. мне кажется, что усложнять больше существующего не нужно, у нас не ХардРП сервак для ценителей хардкора

**Comment by Garrysman232** [comment]
Я не предлагаю прям люто все сложно сделать, но атмос и атмосферные техники честно говоря совсем не нужны до первой разгермы

**Comment by RichardJones1** [comment]
А как же настройка атмоса? А пожары? А аномалии, разрушающие кучу труб и создающие дикие разгермы по пол станции?

**Comment by Garrysman232** [comment]
Зачастую настройка атмоса занимает не больше 6 кликов(лол даже если выкручивать до 15 мегапаскалей давления то трубы все равно не взорвутся), пожары, аномалии это всё всякого типо ЧС, и в основном сводится до разгерм,  при этом всем для устранения ЧС связанную с атмосферой хватает одного инженера который залатает дырку и включит отсос воздуха, с чем может справиться и ИИ

**Comment by RichardJones1** [comment]
Ах если бы так было всегда... Но господи, чаще всего это занимает у состава инженерного отдела по пол часа

**Comment by volas** [comment]
Это да, над диверсией атмоса, вроде как жизненно важного отсека, можно только посмеяться - в помещениях достаточно воздуха для довольно долгих раундов.
Но станция тут просто близка к реализму.
Другим вариантом может быть абсурдное увеличение объёма лёгких (буквально пара строк изменений), и урезание запасов в атмосферном.
Либо придумать еще какую-то систему, которая бы перерабатывала кислород на станции.

**Comment by Leshiy-ART** [comment]
Я наверное все таки за то что бы увеличить объем легких, хотя бы для теста. Да, абсурдно, но у нас все размеры в игре относительны, в том числе и объем газа на тайлах станции. Однако это, возможно, приведет к другим проблемам, например баллона кислорода будет хватать всего на пару минут.

**Comment by Garrysman232** [comment]
Чета в некроишью пишу, только заметил, ну так то баллон кислорода что в сумке у персонажа, это экстренный баллон, а вот полностью заполненного большого баллона хватает чуть ли не на всю смену, не говоря уже о мехе

**Comment by RigoSex** [comment]
Про хавку надо отдельную тему, а вот про дыхание:
Я вижу в этом большую роль в плане _ощущения космоса_
Ты полюбишь свои 4 тайла когда запрешься от ксеноморфов или какой ещё ебаки за то, что продышишь целых n-минут и у тебя будет время найти ещё кислорода
Ощущение изоляции
Но нужно знать меру, а то будет как с едой
