### ISSUE TITLE
Емаг и СПУ/Робоконечности

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#295]
#### Подробное описание проблемы

При Емаге конечности/СПУ и его конечностей высвечивается что: вы успешно скрыто Емагнули конечность
#### Что должно было произойти

Появится бафф/дебафф на конечность
#### Что произошло на самом деле

Потратился Емаг ничего не произошло
#### Как повторить

Провести по роботизированной конечности Емагом/части тела СПУ

**Comment by LudwigVonChesterfield** [comment]
У емагнутых робоконечностей стоит explosion(-1, -1, 2, 3)

Это пережиток старой системы взрывов где были разные радиусы, теперь же у нас суммируется по форме 2 * dev_radius + medium_radius + light_radius. В итоге у нас выходит радиус взрыва -1, собственно и не взрывается.
