### ISSUE TITLE
[Proposal] На счёт леса.

### ISSUE THREAD

**Issue by Kyler2262** [TauCetiStation/TauCetiClassic#2950]
**_Многим зашла тема с лесом за окном станции, поэтому предлагаю:_**

_1. Добавить воутмап
2. Сделать рандомный выбор карты (Какие-то раунды с лесом за окном, другие с космосом)_

**Comment by RichardJones1** [comment]
Скорее всего это дело продлится ещё не долго. Мне тоже зашло, но игра у нас всё таки про **космическую** станцию. Надеюсь, это дело простоит ещё долго.
Так или иначе, постараемся поскорее обсудить, сколько ещё простоит данная карта.

**Comment by RichardJones1** [comment]
Новый год прошёл... Надеемся, что в следующем году мы повторим этот шедевр.
