### ISSUE TITLE
Неудобный выбор вещей в инвентаре [Proposal]

### ISSUE THREAD

**Issue by brenoritvrezorkre** [TauCetiStation/TauCetiClassic#2951]
#### Подробное описание проблемы

Неудобный выбор вещей в инвентаре. Выбор вещи должен произойти по клику на слот или на вещь, а не только по клику на вещь. Если выбор только по клику на вещь, а вещь узкая как изображение, то это создаёт проблемы. 

#### Что должно было произойти

Кликаешь на сам слот - берёшь предмет в руки, действуешь с ним или подобное.

#### Что произошло на самом деле

Кликаешь на сам слот - ничего не происходит.

#### Как повторить

Кликните на слот в инвентаре.

#### Дополнительная информация:

Можете попробовать кликнуть на слот.

**Comment by RichardJones1** [comment]
Ты про рюкзаки или пояса?

**Comment by brenoritvrezorkre** [comment]
Пояса точно, про рюкзаки нужно вспоминать. Также про два слота справа от рук.

**Comment by RichardJones1** [comment]
А, ну... Да, в новой системе инвентаря Алексофп, человек, который кодил её, сделал то, что ты предлагаешь. Вот только в слотах карманов и поясов осталась старая система инвентаря, в которой кликать на слоты было нельзя.
Ну, хорошее предложение, на самом деле, не вижу минусов.
