### ISSUE TITLE
У детектива нету доступа в тюрьму с одного входа, но есть с другого.

### ISSUE THREAD

**Issue by KiPakr** [TauCetiStation/TauCetiClassic#2952]
#### Подробное описание проблемы
Детектив не имеет доступа в тюрьму если пытаться пройти через шлюзы около приемной СБ, но есть если проходить через шлюзы которые ведут к СМЕСу СБ.
#### Что должно было произойти
У детектива либо не должно быть доступа вообще либо должен быть доступ везде.
#### Что произошло на самом деле
В один и тот же отсек через один проход доступ есть, через другой - нет.
#### Как повторить
ЗАйти за детектива и проверить.
#### Дополнительная информация:
[https://prnt.sc/m332z1](url) - доступа нет
[https://prnt.sc/m33331](url) - доступ есть

**Comment by RichardJones1** [comment]
@Lexakr пофиксишь после того как нгшную карту уберем?

**Comment by RichardJones1** [comment]
Пофишкшено

**Comment by StrikS** [comment]
Нормальную фичу убили. Сколько ей уже?
