### ISSUE TITLE
Не отрубается Лайн Комбайнинг

### ISSUE THREAD

**Issue by forbidden-knowledge** [TauCetiStation/TauCetiClassic#2956]
#### Подробное описание проблемы
Когда я отрубаю Line Combining и перезахожу он снова включается

#### Что должно было произойти
Line Combining должен выключаться навсегда

#### Что произошло на самом деле
Line Combining включается после перезахода

#### Как повторить
Выключить Line Combining и релогнуться

#### Дополнительная информация:
Речь идёт об объединении повторяющихся строк в чате если что.

**Comment by RichardJones1** [comment]
@volas Проверишь потом?

**Comment by Motzord** [comment]
Не воспроизводится
