### ISSUE TITLE
Сломаны очки.

### ISSUE THREAD

**Issue by Kyler2262** [TauCetiStation/TauCetiClassic#2960]
#### Подробное описание проблемы
Сломаны термалки, мезонки, зрение генок (Augmented eyesight)
#### Что должно было произойти
Через термалки и зрение генок игрок должен увидеть людей. Через мезонки - структуру станции/астероида.
#### Что произошло на самом деле
Термалки и мезонные очки не работают как надо.
#### Как повторить
Надеть очки. Увидеть херовое функционирование очков.

**Comment by EdlerN** [comment]
Резонный вопрос - а вы пробовали менять версию бйонда? Потому что не так давно возникали проблемы которые решались именно этим.

**Comment by Kyler2262** [comment]
> Резонный вопрос - а вы пробовали менять версию бйонда? 
![image](https://user-images.githubusercontent.com/43703136/50828548-bff10300-1352-11e9-8d3e-def475d0f16e.png)

**Comment by RichardJones1** [comment]
Выяснилось, что Зве недавно пилил фикс торчащим спрайтам и задел это.
Сейчас обсудим проблему и решим что и как.

**Comment by ZVee** [comment]
Неактуально более, проблема росла из #2935 .
