### ISSUE TITLE
borg drill digspeed

### ISSUE THREAD

**Issue by EdlerN** [TauCetiStation/TauCetiClassic#2965]
#### Подробное описание проблемы
При выборе шахтерского модуля выдается дрель с digspeed = 60
#### Что должно было произойти
Должна выдаваться дрель с digspeed = 20
#### Как повторить
Заспавнить борга, взять шахтерский модуль, проверить вв дрели
#### Дополнительная информация:
Digspeed это то что отвечает за время на операцию. Чем больше тем дольше копаешь. Как-то странно что дрель борга копает в два раза медленнее обычной.

**Comment by Kyler2262** [comment]
Пусть ещо мезоночки пофиксят.

**Comment by ZVee** [comment]
Неактуально более, проблема росла из #2935 .
