### ISSUE TITLE
Пропадающий шлюз

### ISSUE THREAD

**Issue by RichardJones1** [TauCetiStation/TauCetiClassic#2967]
#### Подробное описание проблемы
У шлюза в робототехнике, того, на котором есть шаттерс и который ниже mech-bay'я пропадает спрайт, если его открывать.
видимо она в открытом виде на слой ниже шаттерзов.

#### Что должно было произойти
Спрайт двери должен был быть над шаттерсами

#### Что произошло на самом деле
Спрайт двери исчезает в закрытом состоянии

#### Как повторить
открыть шлюз

#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/39438947/50987297-54f22880-151a-11e9-8539-c48767bb0e24.png)
этот шлюз

**Comment by Lexakr** [comment]
Разве там не остается спрайт двери по ПКМу? Если остается то проблема явно не в спрайте, а в слоях. И это тогда не только в этом месте

**Comment by LudwigVonChesterfield** [comment]
#4536
