### ISSUE TITLE
Вокса не получается клонировать.

### ISSUE THREAD

**Issue by RichardJones1** [TauCetiStation/TauCetiClassic#2968]
#### Подробное описание проблемы
Попытался клонировать мёртвого вокса, нажал Scan - выдало  Subject already in database. Но в View Records пусто.

#### Что должно было произойти
Вокс должен был попасть в базу данных.

#### Что произошло на самом деле
нажал Scan - выдало  Subject already in database. Но в View Records пусто.

#### Как повторить
Клонировать мертвого вокса.

#### Дополнительная информация:
Был замечен только ОДИН случай, нужны тесты.

**Comment by LudwigVonChesterfield** [comment]
![image](https://user-images.githubusercontent.com/17705613/50994862-0e0a3000-1526-11e9-980f-1a16d3aef12b.png)

По-моему этим всё сказано.

**Comment by RichardJones1** [comment]
> ![image](https://user-images.githubusercontent.com/17705613/50994862-0e0a3000-1526-11e9-980f-1a16d3aef12b.png)
> 
> По-моему этим всё сказано.

Ох, печально...

**Comment by RichardJones1** [comment]
Странно, а почему?

**Comment by RichardJones1** [comment]
Ладно. Это ксеносы, закрываю.
