### ISSUE TITLE
Телепортация через всю карту. Или как сбежать от антага

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#297]
#### Подробное описание проблемы
С помощью криоподов можно телепортироваться от куда угодно к ним

#### Что должно было произойти
Ничего

#### Что произошло на самом деле
Телепортируюсь с любого слоя обратно к криоподу

#### Как повторить
Начать с помощью граба ложить персонажа, как только началось выполнение действия, перестать ложить, криопод закроется, отвести персонажа куда нибудь(которого мы ложили). Открыть.
ПРОФИТ! Он телепортировался на криопод

**Comment by WallShrabnic** [comment]
Это же фича, ты чё?)
