### ISSUE TITLE
Телепортация в мехе или РИПЛИ ака Фазон

### ISSUE THREAD

**Issue by NeoMind228** [TauCetiStation/TauCetiClassic#298]
#### Подробное описание проблемы
Телепортация сквозь стены при помощи РИПЛИ входа в трубы "delivery chute" и одной трубы
#### Что должно было произойти
РИПЛИ не должен влезать в трубы
#### Что произошло на самом деле
Вас телепортирует на один тайл вперёд и вы проходите сквозь стену
#### Как повторить
Подробная инструкция: ставим трубу под стену(необязательно) ставим вход в систему труб вплотную к стене направленный в ту сторону где за стеной можно выйти залазим в рипли входим вас телепортирует на тайл вперёд двигаетесь в сторону ОТ стены вуаля

**Comment by Dennok** [comment]
мм.... ващет не обязателен риппли.

**Comment by Dennok** [comment]
> ставим вход в систему труб вплотную к стене направленный в ту сторону где за стеной можно выйти

вот и выходит что все что по трубе идет вылазит на следующем тайле, и без разници там стена или спэйс

**Comment by Dennok** [comment]
хотя надо попроверять однако
