### ISSUE TITLE
На стрельбище в бриге(Fire range) отсутствует панель управления мишенью

### ISSUE THREAD

**Issue by RigoSex** [TauCetiStation/TauCetiClassic#2983]
_Подробное описание проблемы:_
Нет панели управления мишенью на стрельбище

#### Что должно было произойти
Должна быть панель управления мишенью
Это указано в бумаге в этом отсеке и раньше она была
#### Что произошло на самом деле
Её нет, мишень стоит, бумага издеватся над реальным положением вещей
#### Как повторить
Зайти на стрельбище

**Comment by volas** [comment]
@Lexakr глянешь тоже?

**Comment by RichardJones1** [comment]
@Lexakr

**Comment by Motzord** [comment]
Бумажку убрали
fixed #3265
