### ISSUE TITLE
У персонажей-женщин полученных в генетике растут усы.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#2984]
Как повторить:

Вырастить из куклы-мартышки куклу-человека женского пола, наслаждаться бородой.

**Comment by Garrysman232** [comment]
Вполне себе нормальный генетический дефект, на евреек посмотреть если то у многих усы растут

**Comment by Sakuya-Izayoi** [comment]
Not a bug

**Comment by KuzyXD** [comment]
Не баг уж точно.
