### ISSUE TITLE
[Proposal] Добавить атмосам выход в космос

### ISSUE THREAD

**Issue by Garrysman232** [TauCetiStation/TauCetiClassic#2985]
Так как у атмосы обделены доступом к комнате с двигателем, у них нет никакого выхода к космосу, и им приходится искать его, доступа к солярам у них нет, так что у них остается только 3-4(!) выхода в космос, и это на всю станцию

Предлагаю добавить выход в космос прямо в атмосферном отсеке или рядом

1. Нужно подвинуть все резервуары чуть вверх, либо удлинить атмос по высоте 

2. Аналогично первому

3. Все равно будет доставлять атмосам неудобство, да и расположение спорное, опять же придется все двигать

4. Не очень удобное место для атмосов, особенно учитывая что там втайлах 30 шлюз есть, но хотя бы что-то ближе 
![Здесь была картинка](https://i.imgur.com/5ztsBIH.png)

**Comment by Lexakr** [comment]
Давно нужно, конечно. Посмотрим, может получится удлинить немного атмосферку и запихать шлюз

**Comment by StrikS** [comment]
А может просто выдать доступ, а не мучать карту а? Не трож атмосию(
