### ISSUE TITLE
Краш клиента при входе в оружейную

### ISSUE THREAD

**Issue by Lizurt** [TauCetiStation/TauCetiClassic#2987]
#### Подробное описание проблемы
Когда входишь в оружейную с некоторым шансом крашится игра, приходится перезаходить
#### Что должно было произойти
Ничего
#### Что произошло на самом деле
Краш
#### Как повторить
Заходить в оружейную время от времени и с некоторым шансом ты неожиданно упадешь в апатию на минуту
#### Дополнительная информация:
Играл в раунд где кеп, 2 офицера и ГП зашли за оружием и все заснули. Иногда же ничего не происходит.
https://forum.taucetistation.org/t/oshibka-v-severnoj-chasti-briga/9771

**Comment by Lizurt** [comment]
Я конечно не разбираюсь в коде и вообще не уверен насчет того что щас напишу. Но попробуйте проверить эмбиент который включается при входе в оружейную. Когда я туда заходил замечал, что включается эмбиент в виде постоянного низкочастотного гула. Врят ли это вам поможет, но надеюсь все окажется так просто как я описал, ведь я тоже не знаю что вызывает этот краш и не замечал никаких закономерностей. Когда хочет - вылетает у всех в некоторое время. Чаще конечно же ничего не происходит, но краш происходит в самые важные моменты.

**Comment by Lizurt** [comment]
Снова произошел краш, но на этот раз когда я пролетал глазом ИИ мимо оружейной. Может быть, это было просто совпадение, но, все же, напишу это здесь

**Comment by volas** [comment]
Верхняя или нижняя часть? Всегда воспроизводится?

Скорее бьендобаг, и у меня пока нет идей, с чем это может быть связанно. Можно было бы с дампом ядра/крешлогом обратиться на форум бьенда, но для человека со стороны это будет наверно сложно собрать.

**Comment by Lizurt** [comment]
Когда был за ИИ - западная или юго-западная сторона. За хумана непосредственно в оружейной, на ее выходе.
Краш происходит не всегда(если я правильно понял "Всегда воспроизводится?"), примерно каждый 4 вход в оружейную или реже

**Comment by UDaV73rus** [comment]
Словил при выходе из оружейной через бластдуры, вспомнил что и раньше такое случалось раза три

**Comment by UDaV73rus** [comment]
При выходе из стрельбища на краю обзора заметил что спрайт держателя мешеней сменился и игра вылетела. Вдруг это сюда относится

**Comment by ext9z3** [comment]
https://i.imgur.com/jardcoq.png

**Comment by ext9z3** [comment]
![dwm_2019-09-11_02-21-36](https://user-images.githubusercontent.com/17950717/64655574-596a3a80-d435-11e9-831c-f1950c13541c.png)
Ап темы

**Comment by volas** [comment]
^на скрине выше "подробности" ошибки возможно могли бы помочь, что бы хоть что-то можно было бы отправить разработчикам бьенда.

В дискорде я еще писал про дампы и упоминался ``trace.bat``

Сейчас не с чем работать, и у меня не получилось воспроизвести проблему. 
Если у вас постоянно происходят там краши - можете мне написать.

**Comment by Lizurt** [comment]
Не самая полезная информация, но хоть что то.
АндроБетель и еще пять игроков зашли в оружейную, все разом, дружненько крашнулись, в одно и то же время. Так что похоже это происходит в определенные промежутки времени. Также хочу отметить, что все пятеро находились непосредственно в оружейной. Бетель думает что это из за света в оружейной.

Может убрать временно красный свет из оружейной и посмотреть не пропадут ли краши? Не думаю, что будут какие то еще подробности об этой проблеме, но надо попробовать что то с ней сделать.

**Comment by volas** [comment]
Это не решение проблемы

**Comment by igigin** [comment]
Ещё интересно было бы узнать происходит такое только на первом сервере или на двух/трёх, а может и локалке тоже.

**Comment by SomeUselessGuy** [comment]
Крашало на локалке, но там было запущено очень много всякого хлама. Могло сломаться из-за этого.

**Comment by SpaiR** [comment]
Учитывая тот факт, что у бьенда несварения от большого количества объектов в одном тайле (был игровой прецедент с, кажется, шкафчиком травы, который крашил всех кто его видел), тут скорее всего похожая ситуация. Потенциальный фикс: вместо вешалок расставить шкафчики. Потеряется визуальное восприятие контента оружейки, но к расположение предметов можно быстро привыкнуть. В крайнем случае можно сделать особые, например, полупрозрачные шкафчики, которые при экзамайне выведут в чат то что внутри них.

**Comment by volas** [comment]
Я тоже предполагал что связанно с множественными объектами на экране, но тесты не подтвердили. + у нас мусорщики есть, там мусора на экране больше.

Я думаю, так гадать можно долго, но будь хотя-бы один краш лог от кого нибудь - можно было бы передать Люммоксу и возможно достигнуть какого нибудь прогресса.

**Comment by cool20141** [comment]
Если будет полезно:
https://forum.taucetistation.org/t/oshibka-v-severnoj-chasti-briga/9771/17

**Comment by Motzord** [comment]
fixed #5041

(На самом деле это костыль)
