### ISSUE TITLE
[Proposal] Снятие взведённого c4

### ISSUE THREAD

**Issue by FelixRuin** [TauCetiStation/TauCetiClassic#2994]
#### Подробное описание проблемы
После установки с4 на стену/хумана/т.д его нельзя снять никаким адекватным образом, превращая его взрыв в неминуемый процесс
#### Что должно было произойти
Спокойно открепляешь с себя с4 взведённый на 999 секунд
#### Что произошло на самом деле
Взрываешься через 999 секунд, так как нет способа снять с4 или предотвратить взрыв
#### Как повторить
Нацепить с4 и попытаться его снять
#### Дополнительная информация:
Выход с надеванием одежды с большой защитой от взрывов после того как нацепили с4 звучит ещё тупее чем подумать

**Comment by LudwigVonChesterfield** [comment]
реквестирую слот под с4 на кукле

**Comment by Pivo24** [comment]
Снимать операцией включающей в себя отвёрточку :+1:

**Comment by RigoSex** [comment]
Я считаю нужен механ обезвреживания С4, к примеру: в виде перерезания одного из четырех проводов. Два из них взрывают, один отключает бомбу и её можно снять рукой, последний добавляет таймеру еще 30-60 секунд. И триторам хорошо, да бомбсуит в кой то веки будет полезным.
