### ISSUE TITLE
Исчезновение ведра.

### ISSUE THREAD

**Issue by dimelion** [TauCetiStation/TauCetiClassic#2997]
#### Подробное описание проблемы
Ведро исчезает, если вылить из него жидкость (испробовано на воде или аммиаке) в каталку уборщика. (Вероятнее всего, подобное происходит, если сперва ведро надеть на голову, а потом использовать по назначению)
#### Что должно было произойти
Ведро выливает жидкость в каталку уборщика.
#### Что произошло на самом деле
Ведро вылило жидкость в каталку уборщика и исчезло.
#### Как повторить
Надеть ведро на голову > Снять с головы > Налить в ведро воды > Перелить в каталку уборщика.
#### Дополнительная информация:
Не проверял все остальные возможности. Например: перелить жидкости из ведра в другие емкости.

**Comment by dimelion** [comment]
Все, разобрался, ведро каким-то чудом попадали в мусорный пакет, который был в каталке.

**Comment by RichardJones1** [comment]
Вскоре я сделаю так, чтобы ведро не удетало в мусорку, прикреплённую к каталке. Тоже бесит)))
А ишью закрою

**Comment by volas** [comment]
@RichardJones1 ишью не стоит закрывать предварительно, лучше как раз только ПРом
