### ISSUE TITLE
Прослушывание дион стетоскопом говорит о "здоровом пульсе".

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#3007]
У дион нет пульса.

**Comment by T6751** [comment]
@LudwigVonChesterfield у дион нет пульса при прослушивании стетоскопом. дело закрыто. 
![image](https://user-images.githubusercontent.com/66636084/84139125-fa833180-aa57-11ea-9d6e-c33c9b1fcbf8.png)
