### ISSUE TITLE
Остаются следы крови в воздухе на месте отрубленных конечностей

### ISSUE THREAD

**Issue by SkLepP** [TauCetiStation/TauCetiClassic#3012]
#### Подробное описание проблемы
Следы крови на конечностях остаются на том же месте при отрубании конечности
#### Что должно было произойти
Следы крови должны исчезнуть вместе с оторванной конечностью
#### Что произошло на самом деле
Следы не исчезли и остались в воздухе на месте отрезанной конечности
#### Как повторить
испачкать руки кровью и отрубить руку
#### Дополнительная информация:

**Comment by RichardJones1** [comment]
#2198

**Comment by KuzyXD** [comment]
Duplicate of #2198
