### ISSUE TITLE
Fluff labcoat исчезание спрайта

### ISSUE THREAD

**Issue by UDaV73rus** [TauCetiStation/TauCetiClassic#3060]
#### Подробное описание проблемы
Халаты флафа можно расстегнуть, а если застегнуть - пропадает спрайт и как итем, и на мобе.
#### Как повторить
Расстегнуть, застегнуть свой флаф лабкоат

**Comment by LudwigVonChesterfield** [comment]
наверное потому-что при застёгивании лабкоат берёт initial() значение переменной, а у флафф вещей оно - нулл

**Comment by Alexofp** [comment]
да, придется маленький костыль вставить
