### ISSUE TITLE
Если засунуть в "разрушающий анализатор" ученых гаечный ключ, то он сломается (анализатор)

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#3064]
#### Подробное описание проблемы
Если сунуть гаечный ключ в деструктивный  анализатор, то с ним становится невозможно взаимодействовать. 
Ключ нельзя было не вынуть, ни разрушить. А переменная busy навечно переключилась на 1. 

#### Что должно было произойти
Ключ нельзя засунуть. Потому что это технология, которая не подлежит изучению

#### Как повторить
Суньте ключ куда не надо.

**Comment by RichardJones1** [comment]
Странно, я всегда изучал гаечный в деструктивном

**Comment by Alexofp** [comment]
Не получается повторить, у меня ключ разрушается и всё хорошо
