### ISSUE TITLE
Арбалеты и последствия от них. неизлечимый урон и невынимаемые болты

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#3065]
#### Подробное описание проблемы
Арбалеты в том числе и те которые как пушка у воксов, часто забивают болты, которые невозможно вытащить. Наносят урон, который невозможно вылечить. 

#### Что должно было произойти
Болты должны выниматься. Урон должен лечиться 

#### Что произошло на самом деле
Хуйня 

#### Как повторить
Срабатывает не с первого раза. Раз через раз, но все же достаточно частенько происходит то что происходит.

**Comment by wadangel** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/1652 - это старый репорт
https://github.com/TauCetiStation/TauCetiClassic/pull/1943 - это старый сломавшийся фикс ращера
