### ISSUE TITLE
Research Division Air Alarm при открытии за ИИ начинает багаться

### ISSUE THREAD

**Issue by RAZUMNO** [TauCetiStation/TauCetiClassic#3070]
#### Подробное описание проблемы
Research Division Air Alarm при открытии за ИИ с изменённым состоянием атмосферы начинает багаться и переоткрываться постоянно. 
#### Что должно было произойти
Открыться окно и не закрываться
#### Что произошло на самом деле
Открылось окно и начало переоткрываться постоянно как только появлялось из-за чего оно ушло за экран.
#### Как повторить
Скорее всего нужно изменить состояние атмосферы в том отсеке
#### Дополнительная информация:
Была высокая температура и играл за ИИ

**Comment by Sakuya-Izayoi** [comment]
Я думаю когда создаёшь подобного рода баг репорты стоит прикреплять скриншот и вообще попытаться повторить баг на локалке.

**Comment by RichardJones1** [comment]
Очень странно. Всё должно быть в порядке. Нужен тестинг.
![image](https://user-images.githubusercontent.com/39438947/52359605-ad521280-2a53-11e9-99b2-50cf23dc7d6c.png)

**Comment by Lizurt** [comment]
Джонс, если что, здесь то же самое, что и с АРС. https://github.com/TauCetiStation/TauCetiClassic/issues/3071
Коротко - не баг, а фича. Чтобы ее вызвать нужно отключить камеру в отсеке с датчиком и попытаться кликнуть на настенный атмосферный датчик.

**Comment by RichardJones1** [comment]
Хмм... Ну да, чёт не вижу способа пофиксить это

**Comment by AndroBetel** [comment]
переставить в другое место от границ камер АПЦ и датчики чтобы ИИшки не позаривались на них и не зависали.
