### ISSUE TITLE
Science Maintenance APC при открытии за ИИ начинает багаться

### ISSUE THREAD

**Issue by RAZUMNO** [TauCetiStation/TauCetiClassic#3071]
#### Подробное описание проблемы
Подробное описание проблемы
Science Maintenance APC при открытии за ИИ с изменённым состоянием электроэнергии начинает багаться и переоткрываться постоянно.
#### Что должно было произойти
Открыться окно и не закрываться
#### Что произошло на самом деле
Открылось окно и начало переоткрываться постоянно как только появлялось из-за чего оно ушло за экран.
#### Как повторить
Скорее всего нужно изменить состояние электроэнергии в том отсеке
#### Дополнительная информация:
Была низкая электроэнергия и играл за ИИ

**Comment by Lizurt** [comment]
Знакомая проблема, но ее причина, скорее всего, не в изменении энергии. Возможно эта проблема связана с тем что АРС не находится в зоне видимости камер слежения ИИ. Его спрайт смещен на стену, которую ты, возможно, видишь, но сам он находится на полу перед стеной. Нажимая по нему ты пытаешься открыть то чего не можешь, чего тебе игра, конечно, не позволяет сделать. То же самое с пожарными и атмосферными тревогами.
