### ISSUE TITLE
Фиксите свет пожалуйста! :(

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#3081]
#### Подробное описание проблемы
Свет не работает! Уже который раунд фонарики не светят в темноте, а при блекаутах лампочки загораются, но не освещают!
#### Что должно было произойти
Адекватное освещение!
#### Что произошло на самом деле
Ничего не произошло, верните свет!!!1
#### Как повторить
Играть, просто играть! Оно само время от времени появляется!
#### Дополнительная информация:
Особенно круто играть шахтёрам!

**Comment by RichardJones1** [comment]
Уже в течении по крайней мере 4х дней не встречался

**Comment by Sakuya-Izayoi** [comment]
Can't reproduce

**Comment by RichardJones1** [comment]
С прошлого раза баг снова не появлялся, и слава богу
