### ISSUE TITLE
9mm Pistol Recoil

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#3091]
#### Подробное описание проблемы
Пистолет охранки калибра 9х19 имеет отдачу как у автомата Калашников без приклада.
#### Что должно было произойти
Ну не бывает так ебна. Скатайте в тир, постреляйте с макарыча или там CZ75, поймете о чем я.
#### Что произошло на самом деле
Бей - тупое гавно, те кто это закодили будут гореть в аду.
#### Как повторить
Играть за охранку и не дай б-г воспользоваться этим чудом.
#### Дополнительная информация:
![fail3](https://user-images.githubusercontent.com/19796920/52335863-80323f80-2a14-11e9-9430-880dcea32a5b.png)

**Comment by RigoSex** [comment]
Конкретно здесь стоит сделать тряску экрана в джва раза реже, чем ныне. Совсем отдачу убирать - ну это непорядок.

**Comment by Motzord** [comment]
В связи со системой скиллов не актуально
