### ISSUE TITLE
Электрошок на расстоянии

### ISSUE THREAD

**Issue by NeoMind228** [TauCetiStation/TauCetiClassic#310]
#### Подробное описание проблемы

Получить шок от дверей можно телепатически
#### Что должно было произойти

Дверь открывается без проишествий с помощью телекинеза
#### Что произошло на самом деле

Перс получает удар током
#### Как повторить

Получить телекинез ткнуть на дверь

**Comment by Dennok** [comment]
а еще можно гибнуть себя телкпатически потрогав сингу

**Comment by MorCrate** [comment]
Не баг, а фича! ... Ну, с сингулярностью точно!

**Comment by Gyaviste** [comment]
Вроде уже не работает

**Comment by NeoMind228** [comment]
Gyaviste Ну нихуя ты некрофил

**Comment by Gyaviste** [comment]
Ну ишьюс открыт и висит

**Comment by NeoMind228** [comment]
>Ло приорити 
>Нахуй никому не нужно

**Comment by Gyaviste** [comment]
Лоу приорити значит другое

**Comment by NeoMind228** [comment]
Именно то что баг абсолютно не критичен и никто не полезет его исправлять это и значит

**Comment by Gyaviste** [comment]
Нахуй никому не нужно и не критичен разные вещи

**Comment by NeoMind228** [comment]
Ты забываешь что находишься на тау ките и тут действует особая магия под названием "Всем насрать на то что не мешает устраивать анал карнавал"

**Comment by Gyaviste** [comment]
Мне не насрать, я решил посмотреть что есть за баги а этот не работает.

**Comment by NeoMind228** [comment]
Он не работал наверное джва месяца спустя после ишы

**Comment by Gyaviste** [comment]
Ленивые мэйнтенеры не закрывают, надо пинать их

**Comment by SpaiR** [comment]
@NeoMind228 Полегче, здесь таки не форум и определение "некрофил" неуместно. То что был лоу приорити - не значит что никто ничего не будет делать. Это именно определение приоритета для тех, кто разбирает ишьюсы. И кодеры на добровольной основе работают, поэтому не нужно выдвигать претензий в духе "ты забываешь где находишься". Кроме того, мог бы и сам закрыть, если знал что ишью неактуален.

**Comment by NeoMind228** [comment]
Я блджад не появляюсь на тау уже год я уже забыл про эту ишу и ко мне ещё претензии пишутся з.б.с.
