### ISSUE TITLE
Парамедики не могут открыть медицинский шкаф

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#3103]
#### Подробное описание проблемы
Парамедики не могут взять снаряжение из медицинского шкафчика.
#### Что должно было произойти
Парамедик должен был открыть шкаф своим доступом.
#### Что произошло на самом деле
Доктор, откройте шкаф!
#### Как повторить
Устроиться на работу парамедиком и попытаться взять  униформу.
#### Дополнительная информация:
https://imgur.com/LnSFOrg

**Comment by Lexakr** [comment]
А должен ли иметь?

**Comment by ViDLiathan** [comment]
Скриншот для кого?

**Comment by Lexakr** [comment]
Я знаю, что там жилет, но он выдаётся на старте и его можно перенести на раки

**Comment by ViDLiathan** [comment]
Нечего захламлять раки шмотьем. И парамедики назначенные от хопа не могут взять наушник и форму. У химиков и генетиков свои шкафчики есть.

**Comment by Lexakr** [comment]
Тогда я вижу здесь два варианта, учитывая что те же риги на складе мне не очень сейчас нравятся.

Первый - поменять доступ на шкафах, но тогда к ним будут иметь доступ и химики, и генетики, и вообще весь мед персонал

Второй - делать отдельную комнату - склад для парамедиков в медбеея где будут отдельно 2 шкафа с оборудованием парамеда, 2 полки и возможно какой-нибудь мех речаржер

**Comment by KuzyXD** [comment]
Тут, да, либо маппинг, либо доступ. Простая вещь.
