### ISSUE TITLE
[Proposal] Добавить кусачки в медбей и бриг

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#3104]
#### Подробное описание проблемы
Ксеносам, работающим в медблоке и бриге, приходится тратить время на поиск кусачек для башмаков и перчаток
#### Что должно было произойти
Коты и крокодилы берут кусачки со склада медблока/раздевалки брига и делают свои дела
#### Что произошло на самом деле
Ксеносы страдают и шарятся по ящикам в ЕВА.
#### Как повторить
Попасть в вайт
#### Дополнительная информация:
Ксеносы должны страдать, но не так.

**Comment by Lexakr** [comment]
Нет, кченосы должны страдать. Итак уже в каждом отделе почти фулл наборы инструментов

**Comment by wadangel** [comment]
Тебе в начале смены сложно пройтись по техам или потратить минуту на то, чтобы дойти до ЕВА? Так-то по-хорошему в ЕВА/ассистентскую приходится в любом случае бежать, потому что запасной комплект инструментов может пригодится всегда хотя бы для починки протезов, не говоря уж про то, что неплохо бы и красный ящик с глоустиками/рациями принес. Плюс батареи запасные для дефибрилляторов.

**Comment by Lexakr** [comment]
Наверное, не актуально?

**Comment by ViDLiathan** [comment]
Проблема то еще осталась

**Comment by ViDLiathan** [comment]
Опять таки, спасибо
