### ISSUE TITLE
Двойной хвост у ящеров, при вкалывании экстракта зеленого слизня.

### ISSUE THREAD

**Issue by Daviii22** [TauCetiStation/TauCetiClassic#3105]
#### Подробное описание проблемы
При вкалывании токсина зеленого слайма ящеру у него остается старый хвост и появляется новый.

#### Что должно было произойти
Хвост должен окраситься в голубой, как и все тело.
 
#### Что произошло на самом деле
Хвост остается прежнего цвета и появляется еще один.

#### Как повторить
Вколоть ящеру экстракт зеленого слайма.

#### Дополнительная информация:
http://prntscr.com/mht3x0

**Comment by Wozzy09** [comment]
не баг, а фича

**Comment by LudwigVonChesterfield** [comment]
Где-то был ПР на слизнелюдей который это фиксил...
