### ISSUE TITLE
Киборг хирург не может лечить и проводить операции.

### ISSUE THREAD

**Issue by NerdyPvP** [TauCetiStation/TauCetiClassic#3106]
#### Подробное описание проблемы
Борг хирург не может проводить операции, т.к всегда имеет 100% шанс на провал, и из-за этого оперируемый получает дамаг.
Так-же неудачно и использование бинтов, т.к при попытке кого-либо перевязать выводит сообщение о том что нужно стоять на месте и по этому использование прерывается.

#### Что должно было произойти
Нормальное лечение и проведение операций.

#### Что произошло на самом деле
Несколько трупов

#### Как повторить
Приковать пациента к каталке и начать проводить операцию системой управления надрезами(борговским скальпелем).

#### Дополнительная информация:

**Comment by wadangel** [comment]
![default](https://user-images.githubusercontent.com/29904082/52466385-31f77a80-2b93-11e9-8693-d526b06e3e45.png)
![default](https://user-images.githubusercontent.com/29904082/52466459-5eab9200-2b93-11e9-87dc-e0abb1b52da0.png)

Почему-то всё выходит. Не всегда, конечно, но ведь у обычной каталки не 100% шанс успеха, про это даже на вики написано.

> Также можно провести операцию на каталке, которая имеет всего лишь 1/4 шанса навредить пациенту. Будь осторожен! 

С наложением бинтов вообще никаких проблем нет.

> при попытке кого-либо перевязать выводит сообщение о том что нужно стоять на месте

Так на месте и нужно стоять как бы.

**Comment by NerdyPvP** [comment]
Интересно, я просто так двух человек подряд убил ._. выходит я просто неудачник, а про бинты, я стоял на месте и мне всё равно выводило это сообщение.
