### ISSUE TITLE
Гиперцин и дионы

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#312]
#### Подробное описание проблемы
На дион действует гиперцин
#### Что должно было произойти
Гиперцин не должен действовать на дион
#### Что произошло на самом деле
Ускорение, побочки от гиперцина
#### Как повторить
Сварить и принять гиперцин за диону
#### Дополнительная информация:
У дион нет крови, эффекты лекарств не должны проявляться, раз. На многие лекарства есть проверка, а на гиперцин нет, два

**Comment by StrikS** [comment]
Это фича, когда мой напарник-химик Void тормозит, я ему вкалываю гиперцин... =)

**Comment by WallShrabnic** [comment]
Это не фича, это не доработка. На большинство других лекарств есть проверка, а на эту нет

**Comment by StrikS** [comment]
Не занудствуй, я шучу.
