### ISSUE TITLE
Велосипедный тренажер и штанга

### ISSUE THREAD

**Issue by Ziliv** [TauCetiStation/TauCetiClassic#3133]
#### Подробное описание проблемы
Если сесть за велосипедный тренажер, а потом нажать на штангу, то ты сядешь за неё, но останешься сидеть на велосипеде. Этот баг не позволяет слезть с велосипиденого тренажера без педальной магии
#### Что должно было произойти
Ничего не должно было произойти.
#### Что произошло на самом деле
Я сел за штангу не слезая с велосипедного тренажера и застрял
#### Как повторить
1. Сесть за велосипедный тренажер.
2. Нажать левой кнопкой мыши по штанге
#### Дополнительная информация:
![screenshot_1](https://user-images.githubusercontent.com/47479810/52522762-4a9a8a00-2c92-11e9-9ad7-23a73bcfd3ab.png)

**Comment by RichardJones1** [comment]
Да, пофиксить бы этот баг. Займусь

**Comment by Pivo24** [comment]
Я уже ранее сообщал об этом баге, помню. Его видимо так и не пофиксили.
