### ISSUE TITLE
Сломанная хирургическая операция на черепе

### ISSUE THREAD

**Issue by Lizurt** [TauCetiStation/TauCetiClassic#3136]
#### Подробное описание проблемы
Хирургия сломана. Я попытался провести операцию по ремонту черепа хумана, но вместо этого я будто оперировал СПУ или борга. 
Вместо хирургического разреза я открыл какую то панель на затылке! // You have unscrewed Zagyg the Gray's screen with the scalpel. //
Ого. Дальше лучше. Я прокликал несколько инструментов. Скальпелем же мне удалось открыть какую то панель в этой панели: // You have unscrewed Zagyg the Gray's head's maintenance hatch with the scalpel. //
Дальше я не стал продолжать и попросил педалей вылечить хумана кнопками. Подозреваю, что сломана не только голова, но я это не проверял
#### Что должно было произойти
Нормальная операция
#### Что произошло на самом деле
Вскрыл потайную электрическую панель на затылке человека
#### Как повторить
Попробовать провести операцию на черепе
#### Дополнительная информация:
Да, это точно человек: This is Zagyg the Gray, a Human!

**Comment by LudwigVonChesterfield** [comment]
уже закрыто #3134
