### ISSUE TITLE
Если во время залезания в мусорку её уничтожить можно оказаться в нуллспейсе.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#3145]
#### Как повторить
взрыв, удар джаггернаута, прочие способы залезть в мусорку
#### Дополнительная информация:

- [ ]

**Comment by volas** [comment]
это касается если не всех, то большинства вещей, куда можно залезть

**Comment by RichardJones1** [comment]
А нельзя ли всунуть в qdel проверку на хуманов в contents и выпихивать оных?

**Comment by LudwigVonChesterfield** [comment]
нет, нельзя

**Comment by volas** [comment]
в дестрой только если

**Comment by Belfogor** [comment]
Так помещая любой объект во внутрь чего-то, он оказывается в нулл спейсе.

**Comment by LudwigVonChesterfield** [comment]
(нет), он оказывается внутри того во что ты поместил(что вполне логично)

нулл спейсом называю ситуации а которых loc предмета = null.

тобишь предмет фактически вне нашего игрового мира, и если ничего на него ссылаться не будет будет удалён сборщиком мусора
