### ISSUE TITLE
Пожарная тревога около сингулярности

### ISSUE THREAD

**Issue by Lizurt** [TauCetiStation/TauCetiClassic#3147]
#### Подробное описание проблемы
В инженерном отсеке при запуске двигателя сингулярности часто в раунде срабатывает пожарная тревога, примерно раз в 7-10 минут. Думаю вот такое близкое расположение к синге во время ЭМИ вызывает активацию пожарной тревоги http://prntscr.com/mjmhh7
#### Что должно было произойти
Ничего
#### Что произошло на самом деле
От ЭМИ вклчючилась пожарная тревога
#### Как повторить
Запустить сингу и ждать ЭМИ
#### Дополнительная информация:
Иногда за ИИ замечал, что инженеры ставят эту пожарную тревогу в другое место, отдаленное, что может являться подтверждением моего предположения. Сам я за ней не следил, но это очевидно.

**Comment by FelixRuin** [comment]
пятый пошёл, Лексакр, работат уже наконец

**Comment by Lexakr** [comment]
Хорошо, конечно, что багрепорты по карте отправляешь в ишьюсе, но вряд ли это нужно, когда ПР в тестмерже, лучше написать прямо там https://github.com/TauCetiStation/TauCetiClassic/pull/3128 . Про этот фаер алярм не нужно, он пофикшен. Ну а ишью закрой/те
