### ISSUE TITLE
Гейтвей при взломе Нюкеров, не возвращает обратно на базу.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#3150]
#### Подробное описание проблемы
Гейтвей при взломе Нюкеров, не возвращает обратно на базу.
#### Что должно было произойти
Нюкеры могут зайти в гейтвей на станцию, но обратно не могут.
#### Что произошло на самом деле
Они должны уметь проходить и на станцию и на базу.

**Comment by Sakuya-Izayoi** [comment]
fixed?

**Comment by volas** [comment]
da, #3157
