### ISSUE TITLE
Флэш кнокает

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#3152]
#### Подробное описание проблемы
Флэш кнокает слепых. Кнокает людей с кверком Blind, кнокает людей с дамагом на глазах больше 30, кнокает людей вообще без глаз.

#### Что должно было произойти
Не должен флэш кнокать если глаза нерабочие.

#### Что произошло на самом деле
Флэш кнокает слепых игроков.

#### Как повторить
Лишить куклу зрения и юзнуть на ней флэш.

#### Дополнительная информация:
Кверки :angry:

**Comment by ZVee** [comment]
Квирки тут не причем, так всегда было скорее всего. Разница только в том, что потерять зрение было сложнее, чем просто взять квирк.
