### ISSUE TITLE
Не все теха открываются при экстренном доступе

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#3159]
#### Подробное описание проблемы
При эвакуации не все двери в теха получили общий доступ
#### Что должно было произойти
Желтые лампочки должны гореть на всех дверях в техтоннели
#### Что произошло на самом деле
Двери в библиотеке, китайском ресторанчике не загорелись и не открывались, некоторые теха научного.
#### Как повторить
Объявить свободный доступ к техтоннелям через кейкод или эвакуацию

**Comment by Lexakr** [comment]
@ViDLiathan какие именно двери в техах рнд не становятся доступными?
