### ISSUE TITLE
не логируется резист, при захвате хлыстом генокрада

### ISSUE THREAD

**Issue by blind0** [TauCetiStation/TauCetiClassic#3164]
#### Подробное описание проблемы
я схватил человека хлыстом генокрада и взял в агрессивную хватку, после некоторого времени он просто выбирается из неё, хотя отсутствовали  какие-либо логи сопротивления
#### Что должно было произойти
при нажатии кнопки resist захваченным игроком, должны были остаться логи
#### Что произошло на самом деле
логи не остались, человек освободился и убил меня.
#### Как повторить
взять генокрада, схватить человека хлыстом и взять агрессивную хватку, после чего за захваченного человека жать кнопку resist
#### Дополнительная информация:
[видео, повтора бага](https://ttm.sh/IZ.mp4)

**Comment by LudwigVonChesterfield** [comment]
не должны, там шанс на отображение.
