### ISSUE TITLE
Проблемы жирных или дело о пропавшем риге

### ISSUE THREAD

**Issue by Thirteenalex** [TauCetiStation/TauCetiClassic#3166]
#### Подробное описание проблемы
Если разжиреть в мехе и быть при этом в риге, он пропадает
#### Что должно было произойти
Он не должен пропасть
#### Что произошло на самом деле
Он исечез равно как и балоны с воздухом
#### Как повторить
Разжиреть в риге сидя при этом в мехе

**Comment by Belfogor** [comment]
Требуется уточнение. Пропадает риг, или все же спрайт рига.
