### ISSUE TITLE
Нужен спрайт блуспейс кристаллу

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#3173]
#### Подробное описание проблемы
![radshot](https://user-images.githubusercontent.com/42682553/52863974-3818c880-314a-11e9-92cf-5bbee6ec6ed5.png)
Это блуспейс кристалл. Он бьёт током.
#### Что должно было произойти
Должен произойти спрайт.
#### Что произошло на самом деле
Произошла красная надпись No Sprite
#### Как повторить
Умереть от молний от No Sprite

**Comment by RichardJones1** [comment]
Фикс ещё вчера залил на гитхаб, дело за воласом. Но спасибо, что оформил ишью

**Comment by RichardJones1** [comment]
Пофикшено
