### ISSUE TITLE
Проблемы с анимациями

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#3176]
#### Подробное описание проблемы
При тыке на мертвое тело проигрывается анимация.
#### Что должно было произойти
Не проигрывать.
#### Что произошло на самом деле
Проигрывать
#### Как повторить
Да.

**Comment by RichardJones1** [comment]
Какой был интент? Какая конкретно анимация?

**Comment by AndroBetel** [comment]
ну как при хаге, но без каких-либо логов.

**Comment by RichardJones1** [comment]
Починил это в ПР-е про анимации
