### ISSUE TITLE
В личное дело игрока вносятся ризоны банов не со всех панелей. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#3189]
#### Подробное описание проблемы
В личное дело игрока, попадают только ризоны банов выданные через PP - Jobban 
![image](https://user-images.githubusercontent.com/12851693/52904787-6e814100-3239-11e9-9f16-0ed01e2f91f0.png)

При выдачи банов через всю туже PP - ban или через анбан панель 
![image](https://user-images.githubusercontent.com/12851693/52904790-83f66b00-3239-11e9-9e41-1a43179a7b3f.png)
они остаются только лишь в БД. 

#### Что должно было произойти
Все ризоны банов/замечания/джоббаны и прочее должны адекватно отображаться в нотисах. 

#### Что произошло на самом деле
Как всегда

#### Как повторить
Забаньте кого-нибудь.

**Comment by TechCatOther** [comment]
Было бы отлично добавить примеры, какими должны быть записи и какие данные нужны из базы в них
