### ISSUE TITLE
РИГи теперь не надеваются

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#3194]
#### Подробное описание проблемы
РИГ никак не надеть теперь, good job
#### Что должно было произойти
Любой РИГ спокойно одевается на тело.
#### Что произошло на самом деле
РИГ не надевается вовсе, сними ты хоть любой элемент одежды.
#### Как повторить
Играть за шахтёра, или за инженера, или за медика, или за СБ, например.

**Comment by ZVee** [comment]
В репорте нехватает очень важной информации - надеть нельзя было используя хоткий или кнопку быстрого надевания, т.к тыкая напрямую в слот, все прекрасно работает.
