### ISSUE TITLE
VV у кандидатов

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#3196]
У кандидатов очень ограниченный ВВ, а конкретно -- ВВ через ПП и некоторые места в чате не открываются, нельзя открывать ВВ через ссылку на атом из окна ВВ другого атома.

**Comment by RichardJones1** [comment]
>нельзя открывать ВВ через ссылку на атом из окна ВВ другого атома.

Вот да, почему так нельзя? Мне бы очень пригодилось, я тут дебажу археологию по вызову на сервер...

**Comment by Belfogor** [comment]
#3165

**Comment by Sakuya-Izayoi** [comment]
я админ кандидат и у меня не работает вв по ссылкам

**Comment by KuzyXD** [comment]
#3761 Я пофиксил, закройте.
