### ISSUE TITLE
Сломалась крутая картинки у camera obscura

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#3198]
![image](https://user-images.githubusercontent.com/17705613/52913993-f2840900-32cb-11e9-89c3-2d50318a2c12.png)

Раньше у этой камеры были триповые тёмные цветные изображения, а теперь какое-то вялое ничего(.

Подозреваю что связано с ПР-ом который выпиливал из префов Бленды.

**Comment by ZVee** [comment]
Связанно с изменениями плейнов. На фотке это оверлеи теней света (которые не обрабатываются корректно при создании фотки) и на деле они не должны попадать вообще на фотку. Но этого не происходит т.к в коде флетайкона не хватает игнорирования на оверлеи теней.
