### ISSUE TITLE
Проблемы со статус дисплеями

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#32]
Originally reported by: **Anonymous**

---

Некорректное отображение кириллицы на статус дисплеях (где кастомные соощения можно выводить из 2-х строк). Раньше всё работало нормально. В каком-то из последних обновлений сломалось.

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/32

**Comment by SpaiR** [comment]
бьёндопроблема с маптекстами и кириллицой
