### ISSUE TITLE
Cтан-талисманы культа [Proposal]

### ISSUE THREAD

**Issue by ArtBsd1** [TauCetiStation/TauCetiClassic#3213]
Стан-талисман у культа(бумажка, которая парализует) имбовая и всего стоит две руны. 
Я не знаю что тут ещё написать, да я бомбанул и прибежал суда, потому что уже не первый раз бомбит от этой бумажки. 
Пофиксите стан-талисманы культа.

**Comment by EdlerN** [comment]
Талисман требует изучения всех рун и подготовки. Талисманы одноразовые и их ограниченное количество. Талисман действует только в ближнем бою и только на одну цель. Но, да, на мимокрокодилов которые патрулируют теха они неплохо работают.

**Comment by WallShrabnic** [comment]
Я больше скажу, священник может эффективно контрить культ
