### ISSUE TITLE
Алиумы и sharp objectы

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#3219]
#### Подробное описание проблемы
Арбалетные болты намертво прибивают алиенов к полу, после вытаскивания болта алиен всё ещё не может вырваться, более того, формально, болт остаётся "в теле" алиена и его можно попытаться вытащить с нулевым результатом (точнее, результат есть, но только при первом вытаскивании). ПРи проверке аналогичная проблема со всеми застревающими предметами
#### Что должно было произойти
Спокойно вытащить болт/застрявшую стекляшку и пойти жрать хуманов дальше
#### Что произошло на самом деле
См. Выше
#### Как повторить
Попасть под раздачу от арбалета или броска
#### Дополнительная информация:
В таком состоянии алиен может крутиться и совершать прыжки

**Comment by RichardJones1** [comment]
Кажется что-то примерно такое было с болтами воксов... Да?

**Comment by Belfogor** [comment]
> Кажется что-то примерно такое было с болтами воксов... Да?

Болты воксов ничем не отличаются от классического арбалета. . У них просто спрайт арбалета другой.

**Comment by Kortez90** [comment]
Закрыто в связи с устаревшим issue.
