### ISSUE TITLE
Сейф капитана видно в коридоре!

### ISSUE THREAD

**Issue by drnordman** [TauCetiStation/TauCetiClassic#322]
#### Подробное описание проблемы
В коридоре, возле каюты капитана, сквозь стену видно сейф и стол. Взаимодействовать с ними нельзя, однако экзамайнуть можно.
#### Что должно было произойти
Стол и сейф не должны быть видны сквозь стену.
#### Что произошло на самом деле
Стол и сейф видно сквозь стену.
#### Как повторить
Пройти мимо каюты в центральном коридоре.
#### Дополнительная информация:
Снимок: http://i.imgur.com/ZyVAXRP.png
Вот что говорит Леший по поводу проблемы: Game Admin PM from-Leshiy: Если спрайт смещен больше  чем на 32 пикселя, то он будет виден с той стороны куда его сместили. Например сейф капитана смещен на 40 пикселей в право, вот его и стало видно в коридоре

**Comment by volas** [comment]
Какая версия бьенда? И если не последняя, попробуй обновить.

**Comment by Dennok** [comment]
кстати, заметил такойже прикол с кнопкой, хотя она сдвинута на юг я ее с востока заметил(с теха под отсеком форонщиков)
