### ISSUE TITLE
Проблемы нового инвентаря

### ISSUE THREAD

**Issue by TEXH4Pb** [TauCetiStation/TauCetiClassic#3225]
#### Подробное описание проблемы
С введением ограничения на взаимодействие с предметами, закрытыми другой экипировкой, остался один недочёт: предметы нельзя снять, если они закрыты чем-то, но зато спокойно можно надеть. Поэтому, ковыряясь инструментами в космосе, можно нечаянно запихнуть себе отвёртку за ухо, нажав 'E', и потом не иметь возможности её снять обратно из-за шлема.
#### Что должно было произойти
При попытке надеть предмет в недоступный слот, должно выводиться предупреждение, что этого сделать нельзя (как при попытке снять).
#### Что произошло на самом деле
Предмет наделся в недоступный слот.
#### Как повторить
Надеть риг, запихнуть себе за ухо отвёртку и попытаться её снять.
#### Дополнительная информация:
С кликом по слоту не проверял, есть вероятность что вообще будет работать только через 'E'.

**Comment by seekin4u** [comment]
это так, через буковку Е предмет сразу телепортируется на доступный слот, минуя механ проверки доступности слота
