### ISSUE TITLE
Ремап техтоннелей РнД и солнечная панель

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#3232]
#### Подробное описание проблемы
Произошло вот это: 
![wut](https://user-images.githubusercontent.com/42682553/53285183-cdc9de80-376e-11e9-98ed-ef667daf2031.png)

#### Что должно было произойти
Прохождение внутрь рубки управления солнечной панели
#### Что произошло на самом деле
Произошёл троллинг

**Comment by akr-nstu** [comment]
Произошел маппинг
