### ISSUE TITLE
Призраков можно положить в трей морга

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#3233]
#### Подробное описание проблемы
Призраков можно поместить в трей морга

#### Что должно было произойти
Призраки не должны помещаться в трей морга

#### Что произошло на самом деле
Их можно туда засунуть, тогда гост не сможет двигать камерой и ослепнет навсегда. Cancel Camera View не исправляет слепоту.

#### Как повторить
Встать на тайл перед морг треем, попросить своего друга его открыть-закрыть

**Comment by volas** [comment]
![default](https://user-images.githubusercontent.com/4064061/53294910-ff8b8580-3800-11e9-8dc6-51321d72d963.png)
реквестирую новую табличку в морг

**Comment by Lizurt** [comment]
К слову похожим образом работает глаз ИИ. Его можно положить в ящик и перемещать. К счастью, оттуда можно выбраться. Насчет ячеек морга не проверял. Не думаю что насчет такого нужно будет писать отдельный багрепорт, просто осведомил.

**Comment by LudwigVonChesterfield** [comment]
Мне что-то подсказывает что там цикл по всем предметам на тайле, а надо исключать ABSTRACT и /mob/dead

**Comment by Ahion** [comment]
Как не пытался, на локалке повторить не смог. Может уже не актуально?

**Comment by pss88** [comment]
#7041
