### ISSUE TITLE
[Proposal] Из меха невозможно вынуть пилота, не разрушив при этом самого меха

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#3236]
#### Подробное описание проблемы
Пилота можно вынуть, только уничтожив сам мех

#### Что должно было произойти
Нужен какой-нибудь механ вынимания

**Comment by RigoSex** [comment]
Как насчет консоли РД и ручного способа с откручиванием и разблокировкой, как при обслуживании?
Осталось придумать как их аккуратно обездвиживать...

**Comment by DarkLevelSS13** [comment]
Был вроде видел один из методов, я его находил где-то в одном руководстве с методом по вытягиванию мозга из борга.
Метод по вытягиванию мозга из борга рабочий а вот на счет меха не проверял.

**Comment by DarkLevelSS13** [comment]
Да, только на других серверах такая возможность есть.
