### ISSUE TITLE
пневмотруба-ловушка

### ISSUE THREAD

**Issue by blind0** [TauCetiStation/TauCetiClassic#3243]
#### Подробное описание проблемы
пневмотруба на аванпосте, в одном месте под неё можно залезть, но нельзя вылезти
#### Что должно было произойти
я должен был залезть под неё и должен был вылезти
#### Что произошло на самом деле
я застрял
#### Как повторить
залезть и попытаться вылезти
#### Дополнительная информация:
[видос, это место находится под аванпостом.](https://ttm.sh/Tw.mp4)

**Comment by RichardJones1** [comment]
Принял, будет пофикшено
