### ISSUE TITLE
Некорректное отображение спрайтов выключенных mesonic surveyors 

### ISSUE THREAD

**Issue by Albert033** [TauCetiStation/TauCetiClassic#3262]
#### Подробное описание проблемы: 

При выключении (деактивации)   mesonic surveyors пропадает их спрайт, хотя видно что кукла держит очки
#### Что должно было произойти: 

Должен был появится спрайт выключенных   mesonic surveyors

#### Что произошло на самом дел: 

Спрайт исчез

#### Как повторить: 

Просто выключить их как обычные мезонки

**Comment by RichardJones1** [comment]
Держит, тоесть в руке, так понимаю?

**Comment by Albert033** [comment]
Да, на самом спрайте куклы видны очки, и сам обджект никуда не пропал, просто нет спрайта, я все еще могу активировать их обратно через хоткей и они вернутся в норму
