### ISSUE TITLE
Бипски аррестовывает одноруких.

### ISSUE THREAD

**Issue by BiQndy** [TauCetiStation/TauCetiClassic#3269]
#### Подробное описание проблемы
Если Бипски заагрился на однорукого, то он него закует в наурчи.
#### Что должно было произойти
Бипски не должен ковать одноруких.
#### Что произошло на самом деле
Заковал однорукого.
#### Как повторить
Попробовать ударить Бипски, будучи одноруким.
#### Дополнительная информация:
-

**Comment by RigoSex** [comment]
`if(SECBOT_ARREST)		// arresting
			if(!target || !iscarbon(target))
				forgetCurrentTarget()
			else
				var/mob/living/carbon/C = target
				if(C.handcuffed)
					forgetCurrentTarget()`
Я попробую сделать проверку на однорукого бандита. Бип.
