### ISSUE TITLE
Проблемы мага

### ISSUE THREAD

**Issue by RichardJones1** [TauCetiStation/TauCetiClassic#3283]
#### Подробное описание проблемы
Когда маг превращает человека в животное с помощью одного из его волшебных посохов, есть шанс, что этот человек станет зомби

#### Что должно было произойти
Человек не должен был стать зомби и погрузить станцию в хаос

#### Что произошло на самом деле
Человек стал зомби, и начался пиздец

#### Как повторить
Зайти за мага и попробовать много раз превращать людей в животных

**Comment by De-dawa-2** [comment]
Так это же feachure

**Comment by RichardJones1** [comment]
> Так это же feachure

Нет, это появилось с введением зомби, я первый стал жертвой этого бага еще давно

**Comment by WallShrabnic** [comment]
> Так это же feachure

Не фича, а баг, посох не превращает хуманов в алиенов. Вообще, оттуда было бы неплохо заодно убрать слизней

**Comment by Belfogor** [comment]
>посох не превращает хуманов в алиенов

Превращает же.

**Comment by AndroBetel** [comment]
нет, не превращает, это закоменченно

**Comment by Leshiy-ART** [comment]
И заодно добавить в список прочую simple живность.

**Comment by LudwigVonChesterfield** [comment]
посох выпилили
