### ISSUE TITLE
Сломанные дабл клики

### ISSUE THREAD

**Issue by Lexakr** [TauCetiStation/TauCetiClassic#3286]
#### Подробное описание проблемы
За госта невозможно дабл кликом телепортироваться/фолловить 
#### Дополнительная информация:
Сломалось вроде бы недавно

**Comment by seekin4u** [comment]
Это какой-то прекол сложный, вчера даблкликал гостом и все прекрасно фолловилось и телепортировалось.

**Comment by ArtBsd1** [comment]
Тоже хотел написать про этот баг

**Comment by RichardJones1** [comment]
Пофикшено
