### ISSUE TITLE
СПУ может завербовать тенелинг (BUG)

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#3292]
#### Подробное описание проблемы
Тенелинг имеет возможность завербовать СПУ (произошло сразу с несколькими в раунде), еще есть информация о том что сам СПУ может быть тенелингом (не проверено)
#### Что должно было произойти
Тенелинг не должен быть тенелингом и иметь возможность быть завербованным
#### Что произошло на самом деле
Возвышенный тенелинг завербовал СПУ и он стал треллом
#### Как повторить
Стать возвышенным и завербовать толпу с СПУ
#### Дополнительная информация:
Желательно это исправить (напоминает генокрадов СПУ)

**Comment by Klpghf** [comment]
Сделать так, чтобы Enthrall и его аналог у возвышенного не работали на СПУ можно небольшим изменением двух строчек кода. А вот сделать так, чтобы при начале игры игрок с СПУ не мог быть выбран шадоулингом лично я не смогу - не осилю без посторонней помощи или долгого и мучительного ковыряния кода.

Также такие изменения явно сильно поменяют баланс игры. Но если нужно - могу сделать такой PR.
