### ISSUE TITLE
Не получается отозвать шаттл на последней минуте.

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#3295]
#### Подробное описание проблемы
Если ИИ вызывает шаттл, то его нельзя отозвать с консоли мостика.
#### Что должно было произойти
Он как бы должен отозваться.
#### Что произошло на самом деле
На таймере оставалась еще минута до прибытия шаттла, но даже с таким запасом времени кнопка отзыва не прожималась.
#### Как повторить
Как-нибудь.
#### Дополнительная информация:
Возможно это не баг, а фича. Красного когда не было, режим: Триторы.

**Comment by Belfogor** [comment]
Любой вызванный шаттл нельзя отозвать, после какого-то рубежа. Кажется три минуты, но это не точно.

**Comment by RichardJones1** [comment]
Любой вызванный шаттл нельзя отозвать зв пять минут до прилета, это не баг. Если хочешь предложить изменить это - напиши прямо сюда, я составлю пропазал за тебя даже, если захочешь.

**Comment by volas** [comment]
Если там нет фидбека для игрока при отзыве (сообщение, что и почему), я бы открыл.

**Comment by RichardJones1** [comment]
хоть это и не баг, ты прав
надо добавить какой то to_chat, что шаттл уже сликшом близко
