### ISSUE TITLE
Сломались спрайты формы СС, полученной через хамелеон кит (BUG)

### ISSUE THREAD

**Issue by Anntoni122** [TauCetiStation/TauCetiClassic#3305]
#### Подробное описание проблемы
Мы берем, допустим, хамелеонский головной убор, через Change Hat выбираем Waffen SS Hemlet или Waffen SS Cap или Nazi Officer Cap и спрайты не отображаются. Тоже самое связано с формой Waffen SS Form (еще также сломаны жакеты M35Filde).
#### Что должно было произойти
Спрайты должны отображается
#### Что произошло на самом деле
Спрайтов нет
#### Как повторить
Взять хамелеон кит и самому попробовать сделать тоже самое
#### Дополнительная информация:
Желательно это исправить, ибо иногда с помощью РнД устраиваются национал-социалистические бунты.

**Comment by RichardJones1** [comment]
Надеюсь это никогда не пофиксят 💯

**Comment by Fourest** [comment]
У меня всё работает

**Comment by Alexofp** [comment]
Не получается повторить, спрайты формы сс видно
