### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ArtBsd1** [TauCetiStation/TauCetiClassic#3310]
Бипский не производит арест, если у него отключено автопатруль. Он только сообщает и преследует.

**Comment by ArtBsd1** [comment]
Не арестовывает*

**Comment by SpaiR** [comment]
Данный ишью нужно перефоромить согласно темплейту (та часть, которую ты полностью удалил, в которой написано, что её удалять не надо). И прежде чем это делать рекомендую его прочесть (обратить внимание на часть с заголовком).
