### ISSUE TITLE
Отсутствие дефолтных спрайтов для некоторого медстафа

### ISSUE THREAD

**Issue by SpaiR** [TauCetiStation/TauCetiClassic#3313]
#### Подробное описание проблемы
Некоторый медстаф не имеет дефолтных спрайтов.

#### Что должно было произойти
Должны быть.

#### Что произошло на самом деле
Нету.

#### Как повторить
Открыть, например, z1.dmm в редакторе и найти стафф со скриншота.

#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/12721311/54590782-e8c00380-4a39-11e9-8a27-2283f9d11402.png)

**Comment by RichardJones1** [comment]
@AndroBetel
