### ISSUE TITLE
[Proposal] Сделать хоткей на OOC-чат

### ISSUE THREAD

**Issue by RichardJones1** [TauCetiStation/TauCetiClassic#3330]
В режиме хоткеев существует кнопка, отвечающая за say - "T". Но очень полезна была бы такая же для OOC-чата. Сделайте, пж, а то я не разбираюсь в той части кода...

**Comment by UDaV73rus** [comment]
F2 хватает вполне

**Comment by KuzyXD** [comment]
@RichardJones1 	а разве F2 недостаточно?
