### ISSUE TITLE
Выпилить клонирование

### ISSUE THREAD

**Issue by Fourest** [TauCetiStation/TauCetiClassic#3343]
#### Подробное описание проблемы: 
Клонирование очень часто вредит игре, она делает жизнь менее ценной, ломается с некоторыми ролями и так далее, а отыгрышем психологической травмы от клонирования мало кто занимается

**Comment by Lizurt** [comment]
Выпилить клонирование, имхо - слишком резкий поворот событий. Но частично я с тобой согласен. Думаю лучшим решением здесь будет убрать или занерфить клонирование хуманов, не прошедших заранее сканирование, поэтому их нельзя будет клонировать... А еще добавить квирк за два очка, который будет автоматически при твоем спавне добавлять тебя в базу данных. Люди будут больше бояться смерти, генетика станет более полезней, чем поиск генов халка или телекинеза, а дорожащие респавном люди все еще будут иметь возможность клонироваться без сканирования.

**Comment by WatlerJe** [comment]
Бояться смерти в игре, где через 30 мин-1 час начнется игровой новый раунд. Вы свою шизофрению на других не ретранслируйте.

**Comment by RichardJones1** [comment]
Если ты предлагаешь ремувнуть такую важную вещь, как клонирование (возвращает игроков в гейм), придется приводить намного более веские аргументы в пользу выпила. На ТГ, помнится, ПР по удалению автоклонирования(!!!) получил более сорока тамздаунов.
