### ISSUE TITLE
Резина убивает

### ISSUE THREAD

**Issue by Nyker228** [TauCetiStation/TauCetiClassic#3345]

**Comment by WallShrabnic** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/906

Похоже на дупликат

**Comment by WallShrabnic** [comment]
Для попадания в голокрит без химии нужно умудрится словить тушкой три прямых попадания. Для того, чтобы получить длительный weaken нужно почти весь магазин истратить. Это я не учёл комбат инжектор, и ещё кучу других условностей. Резина в данный момент не имба

Ну и да, ишью написан на волне проигрыша нюка (раунд недавно закончился)

**Comment by EdlerN** [comment]
Нюкеры рашат в соло и сосут от резины. Впрочем ничего нового. Там еще станлучи говорят накидывают викен если под ними стоять и принимать их лицом...

**Comment by Belfogor** [comment]
Броня вообще уменьшает входящий голо урон от резины?

**Comment by EdlerN** [comment]
Да, при том солидно

**Comment by Nyker228** [comment]
Две-три пули и нюкер в фул экпиве лежит на полу и ничего не может сделать. Найс уменьшает.

**Comment by WallShrabnic** [comment]
Не лежит, а находится в голокрите. В это время он вполне может отойти в безопасное место и спокойно переждать. Ну и как сказали выше, вы ходите по одиночке, умираете, а потом пишете ишьюсы. Найс логика

**Comment by Motzord** [comment]
Закрывайте

**Comment by LudwigVonChesterfield** [comment]
> Резина пробивает риг нюки, броню нюки и кнокает.

Если это хочется сделать ишуем, то это совсем другая проблема. А не "Резина убивает"
