### ISSUE TITLE
У голокарпов отвалился спрайт и они полностью невидимы. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#3347]
#### Подробное описание проблем
Голокарпы из инвиза пережрали людей. Игроки во всем обвинили клятих педалей.

**Comment by RichardJones1** [comment]
У меня сейчас на локалке всё работает...

**Comment by StrikS** [comment]
Вчера или позавчера повторилось. Консоль голодека была взломана. Невидимые голокарпы кушали людей, было забавно наблюдать, но багом это, к сожалению, не перестает быть.
