### ISSUE TITLE
Стеклянные окна с затемнением в хирургии при открутке не становятся обычными

### ISSUE THREAD

**Issue by Thirteenalex** [TauCetiStation/TauCetiClassic#3348]
#### Подробное описание проблемы
Стекла в хирургии если их открутить должны становится обычными
#### Что должно было произойти
Они должны перестать быть затемненными
#### Что произошло на самом деле
Они все ещё затемненые и за них можно прятатся
#### Как повторить
Открутить затемненное стекло
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/35332279/55294729-42e3a000-540e-11e9-8c55-45146c3e1db5.png)

**Comment by RichardJones1** [comment]
@Lexakr

**Comment by Lexakr** [comment]
Что? Это же проблема автора данных стекол. Могу убрать вообще с карты только

**Comment by RichardJones1** [comment]
а, я почему то подумал, что ты их делал, сорян
