### ISSUE TITLE
Невозможно поставить решётку.

### ISSUE THREAD

**Issue by DroneFlex** [TauCetiStation/TauCetiClassic#3355]
>  Подробное описание проблемы

Судя по всему, кусок "инженерной" части игры был сломан. Стало невозможно поставить решётку (grille). 

> Что должно было произойти
Собственно, произойти должна была решётка (grille)

> Что произошло на самом деле
При попытке поставить решётку выходит сообщение, что решётка ставится (Assembling grille...), но далее ничего не происходит, загрузка того, что делается какое-то действие, также не появляется.

>  Как повторить
Взять в руки прутья (metal rods) как минимум - 2 штуки, нажать на прутья в руке.

> Дополнительная
 информация: Вряд ли требуется

**Comment by FelixRuin** [comment]
Это из-за юз Тула тык

**Comment by volas** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/3276

**Comment by SpaceBimbo** [comment]
Нельзя так же консоли завершить. Консоль ставиться> плата > отвертка > Провода. На проводах затык. Звук есть, сообщение не выводится. Дальше нет возможности продолжить

**Comment by FelixRuin** [comment]
Благодарю за баг репорт
баг исправлен
я глупый

**Comment by DroneFlex** [comment]
Спасибо.
