### ISSUE TITLE
Консоли не собираются.

### ISSUE THREAD

**Issue by DroneFlex** [TauCetiStation/TauCetiClassic#3356]
#### Подробное описание проблемы
Стало невозможно собрать консоли. Собственно, всё хорошо до того момента, когда приходится вставлять в них провода. После этого - провода не ставятся и сборка консоли до конца становится невозможной.

#### Что должно было произойти
В сборку консоли должны были добавится провода, что сделало бы её дальнейшую сборку (добавку стекла) возможной.

#### Что произошло на самом деле
Произошёл звук того, что провода вставились, однако их количество в руке не изменилось, и непосредственно в консоли они отсутствуют. Их изъятиe из консоли путём кусачек также ни к чему не приводит (ну ещё бы, их же в ней нет).

#### Как повторить
1)Взять в руку металл, нажать на него, поставить computer frame, прикрутить его к полу ключом, вставить любую консольную плату, я использовал плату консоли мехбея (Mech Bay Power Control Console), но то же самое происходит с любой другой консольной платой платой; прикрутить плату отвёрткой, попытаться вставить провода. 
2)На готовой консоли: Открутить стекло отвёрткой, вытащить стекло ломом, срезать провода кусачками, попробовать вернуть их на место.

#### Дополнительная информация:
Всё описано выше.

**Comment by volas** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/3276

**Comment by FelixRuin** [comment]
Благодарю за баг репорт
баг исправлен
я глупый

**Comment by DroneFlex** [comment]
Спасибо.
