### ISSUE TITLE
Перезаход на сервер за строителя культа 

### ISSUE THREAD

**Issue by Reaperamk** [TauCetiStation/TauCetiClassic#3361]
1.Подробное описание проблемы

#### Что должно было произойти
При перезаходе на сервер строитель культа должен слышать речь персонажей рядом, как обычный персонаж.
#### Что произошло на самом деле
При перезаходе на сервер строитель культа не может слышать персонажей, так как считается, что он находится в сне. Ходить и строить он может, но речь воспринимается им как будто он спит.
#### Как повторить
Играя за строителя культа перезайти на сервер.
#### Дополнительная информация:
Баг повторяется в 4 случаях из 4.

**Comment by Belfogor** [comment]
Такая же проблема со всеми остальными конструктами и позитронным мозгом. Баг очень некисло портит жизнь
