### ISSUE TITLE
[Proposal] Нерф бладбоила и талисмана.

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#3372]
Бладбоил есть ОП ибо - Способен гибать сквозь стены, игнорирует любую броню, херачит сплешем и с одного удара.

У талисмана слишком долгий стан (секунд 40) с мутом, а так же для его крафта требуется лишь листок бумаги коих на станции очень много. 

Тащемта с этим надо что-то делать.

**Comment by WallShrabnic** [comment]
У талисмана 15 секунд стана. Бладбоил требует трёх человек, но вот сквозь стены... И да, всё это контрится одним священником, но давайте ещё сильнее баффнем охрану, чтобы роли сразу спавнились в бриге

**Comment by FatFatFat1** [comment]
гиб сквозь стены ,еще и на огромном радиусе ,это капец

**Comment by ramiro181** [comment]
Что касается бладбойла - руной в душевой общака гибнуло космонавтика аж в спортзале. Жирно как-то.
[https://imgur.com/RdfYhHU](url)
По прочему - я лично щитаю что:
а) Надо нерфить талисман - либо убирать молчанку, либо срезать длительность. За 15 секунд не то что голову отрежут - пол поменяют.
б) Руна призыва кукол из гостов - имбалансная хуита. Неоднократно видел как культ призывал нарсю почти без конвертов, запираясь где-нибудь в жопе техов и натаскав необходимых 9 человек из обсервов и соснувших.
в) Стенки - не сбиваются ничем кроме священника и швабры, работают бесконечно. Жирновато.
г) _Полная_ защита от тазера на робах. Оно действительно необходимо?

**Comment by EdlerN** [comment]
Я бы сказал вот что. Бладбойлу надо убрать урон сквозь стены, ибо это хуйня на постном масле выходит которую только мехами уничтожать. Стены - забивают лимит рун (который существует) потому бог с ними. Талисманы надо неким непрямым методом понерфить. Может сделать что они жрут кровь юзера при том немало так. А от тазера там не полная. По крайней мере насколько я припоминаю

**Comment by AndroBetel** [comment]
таки полная.

**Comment by WallShrabnic** [comment]
Я уже расписал, проблема в отсутствии/игнорировании священника на которого и талисманы не действуют, и руны он скрытые видит и бладбоил не работает. Возможно стоит сделать аналог святого щита, чтобы защита накидывалась на соседних с ним юнитов, чтобы наконец люди шли не боясь получить листочком в бочину. Или в правилах наконец написать, что о культе знают, ей богу больше нервных клеток сэкономите

Да и считать, что СБ обязана справляться с любыми антагами как минимум глупо, у нас игра про взаимодействие или что? Вообще, в это плане надо расширять правила, типа когда нет связенника офицеры могут попросить инженеров взломать автоматы со святой водой и нулл родами и пойти воевать самим, или если случилась вирусная тревога обычные врачи в отсутствии СМО и вирусолога могут пойти получив доступ в вирусологию и сделать лекарство, от этого никому хуже не станет

**Comment by WallShrabnic** [comment]
Охуенной дорогой идёте, ребята, вместо того, чтобы перепиливать роль (как ещё Куршан завещал) вы обмазываетесь нёрфами, доводя роль до неиграбельного состояния. Может уже просто выпилите все режимы и оставите только эксту?

**Comment by WatlerJe** [comment]
Любые изменения ролей, нерфы или бафы уже являются этими самыми перепилами.
Заветам Куршана? Кстати где он? Обзывание нерфами, доведение до неиграбельного состояния, эксту оставим, возбудимся, че ты несешь вообще?

**Comment by RichardJones1** [comment]
Это же шрубник, why are u surprised?

**Comment by rarytech** [comment]
Но у культа, кроме вышеперечисленных способностей нет эффективных инструментов, чтобы бороться с СБ.
Интересно, наскучит ли охранничкам когда-нибудь игра, в которой никто из антагонистов не сможет им сопротивляться?

**Comment by ViDLiathan** [comment]
Ой, а в революции вообще никаких рун нет, а их еще и тиранить и репрессировать разрешено.
Кульиисты, как правило, та же революция, но у ролек больше развязаны руки, а у охраны и глав наоборот почему то. 
Хотя, казалось бы, одни требуют своих законных прав и самостоятельно принимают решение на участии. Как правило, решивших занять нейтралитет не убивают. Роли не теряют человечности и не пполучают особых преимуществ.
А вот вторых принимают в ряды принудительно. Промывают мозги, отказавшихся лишают жизни и делают конструктов. Поклоняющиеся темному богу могут спокойно резать людей, они же фанатики.
Получают неприметное оружие в виде листочков, могут сразу призвать броню.
Да или даже просто разгуливать в ней - нельзя их ловить, пока не доказано, что они убивают кого то.

**Comment by Chip11-n** [comment]
У культа есть масса недостатков, как по мне он в некоторых отношениях слаб. Например: швабра которую можно напечатать в РнД и дать всем СБ = культ погиб. К тому же, бладбоил долго чертить в условиях сражения, да и собрать 3-х людей непростая задача. 
Да, и у культа ограничение на руны, и не выйдет очень продуманной западни без бладбоила. 
Тут такая ситуация: либо культ чертит бладбоил и живёт ещё минут 15, либо СБ вырезает культ. 
Моё предложение: занёрфить бладбоил, но убрать ограничения на руны, тем самым подталкивая людей на создания сложных и продуманных ловушек на людей.
