### ISSUE TITLE
Автотритор выпадает имплантированным майндшилдом

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#3378]
#### Подробное описание проблемы
Человек с майндшилдом получил триторку
#### Что должно было произойти
Майншилд должен препятствовать выпадению триторки
#### Что произошло на самом деле
Офицер-предатель
#### Как повторить
Имплантироваться майншилдом и получить автотритора

**Comment by RichardJones1** [comment]
Он вроде кадетом был, нет?

**Comment by Kernstall** [comment]
>Майншилд должен препятствовать выпадению триторки
Нет не должен

**Comment by WallShrabnic** [comment]
Должен. Офицеры триторы не нужны

**Comment by Kernstall** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/2109
Всем наплевать на твое мнение как что-то должно труъ работать, особенно в контексте репорта _бага_. Майндшилд предназначался как затычка на культревугэнг и это не баг. Попробуй сделать так, как это заведено: темка на воруме, вылить кучу текста ни о чем, сделать пропозал по крайней мере, а не багрепорт.
От себя добавлю, что при автотриторе цель вспоминает, что она агент синдиката(лул). Промывкой мозгов не особо пахнет.
Что действительно можно считать багом так это выпадение автотритора всяким пии, бомжам(?) и проч.

**Comment by megaomega005** [comment]
Не согласен
Маиндщилд- костыльная затычка, лайтовая версия лоялити имланта
Нужна для создания БоУлАнСа между рольками и СБ, путем затыкания им возможности стать любой ролью

**Comment by Kernstall** [comment]
Ну а в чем тогда эта затычка будет лайтовей обычного импланта лояльности, м? В том, что куклы с золотым иплантиком должны играть в полную преданность нт, а синим имплантиком могут позволить себе сказать "бля" в рацию. Я так вижу, что любители фаллософствовать на тему рп давно уже придумывают свои вселенные и требуют чего-то от офицеров из-за наличия у них майндшилда.

**Comment by EdlerN** [comment]
Банальная логика. Щит должен мешать смене роли в раунде. Т.е. он не снимает триторку, но должен мешать получению автотритора и подобного дерьма. Потому что это изменение роли в раунде.

**Comment by Kernstall** [comment]
Должен потому что ... "костыльная затычка"?
Объяснение такой вещи как майндшилд - защита от промывки мозгов. Не очень вяжется с автотритором, которому никто эти самые мозги не промывает. Автотритор изначально был агентом, только он вдруг это "вспоминает" - ну допустим специально амнезия была вызвана.
>он не снимает триторку

А ты уверен в этом? Насколько помню он по коду тот же самый имплант лояльности считай

>Потому что это изменение роли в раунде.

Только что придумал такое правило?

**Comment by FelixRuin** [comment]
Ненене, имплант лояльности снимает, майнд шилд не снимает

**Comment by Kernstall** [comment]
>Ненене, имплант лояльности снимает, майнд шилд не снимает

Нуокей, очередной аргумент почему он не должен и автотриторку предотвращать

**Comment by megaomega005** [comment]
Просто маинщилд был украден с другого билда, без обьяснений его механа и того, как он работает ИС
По сути ООС затычка, но в отличии лоялити не ограничивает эРПэ отыгрвшь офицериков

**Comment by volas** [comment]
Как выше заметили, майншилд защищает именно от промывки мозгов, и автотрейтор тут не при делах.

Если и обсуждать, то вне контекста имплантов, просто вопрос "хотим ли мы офицеров-триторов", а дальше это как угодно можно реализовать.
