### ISSUE TITLE
Если отрубить голову, то время респавна стремится к нулю

### ISSUE THREAD

**Issue by Miracler112** [TauCetiStation/TauCetiClassic#3381]
#### Подробное описание проблемы
Если отрубить голову, то для респавна не нужно ждать 30 минут

#### Что должно было произойти
Гост должен выжидать свои законные 30 минут
#### Что произошло на самом деле
Можно заспавнится сразу

#### Как повторить
Отрубить себе или другу голову

#### Дополнительная информация:
Злостный обход задержки

**Comment by RichardJones1** [comment]
Слушай, у меня на локалке всё нормально работает... Ты мб не деадминулся тогда?

**Comment by Miracler112** [comment]
Да нет, там паренек написал об этом в АХ, другие госты тоже заметили этот баг. Может там в том раунде что слетело, но если оно не повторяется, то думаю можно закрыть
