### ISSUE TITLE
Меме и капельница.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#339]
#### Подробное описание проблемы
При выборе режима подключения капельницы,появляется окошко с выбором персонажа к которому подключить ее. Среди прочего отображаются и мемки,если они присутствуют в оных.

#### Что должно было произойти
Мемку не должно быть видно таким образом,это весьма странно.

#### Что произошло на самом деле
Предоставляю скриншот.
http://prntscr.com/bqf7jv
#### Как повторить
Нужен один человек,меме, и капельница. В меню взаимодействия с капельницеq, при выборе режима, отображается возможность подключения ее к меме.

**Comment by MorCrate** [comment]
Таким образом палились даже обсерверы.
