### ISSUE TITLE
universal painter не работает

### ISSUE THREAD

**Issue by Zandwitch23** [TauCetiStation/TauCetiClassic#3411]
#### Подробное описание проблемы
При попытке покрасить окна пэйнтером, после выбора цвета пишет "not enough ink!"
#### Что должно было произойти
Должно работать.
#### Что произошло на самом деле
Не сработало.
#### Как повторить
Покрасить окно universal painter-ом.
#### Дополнительная информация:
Новые картриджи с чернилами не спасают.

**Comment by FelixRuin** [comment]
упс
сейчас починим
