### ISSUE TITLE
Гост-камера (камера обскура) "засвечивает" фотки

### ISSUE THREAD

**Issue by JinxMono** [TauCetiStation/TauCetiClassic#3415]
#### Подробное описание проблемы
При использовании гост-камеры сфотографированные тайлы отображаются некорректно или не отображаются совсем. На месте фотографии видны чисто белые тайлы с небольшими включениями нормально снятых тайлов.Также, в чате при осмотре фотографии пишутся все те, кто на фото есть, но кого засветило. Замечу, что с простым фотоаппаратом такого замечено не было. 
#### Что должно было произойти
Отобразиться фотография 3 на 3 тайла с эффектом камеры обскуры и может быть увидеть госта и всех кто вообще есть там.
#### Что произошло на самом деле
Пример: http://prntscr.com/nenytv
#### Как повторить
Взять гост-камеру и попробовать по фотографировать где угодно.
#### Дополнительная информация:
-- Administrator private message --

Admin PM from-Jacob Taken: Вообще этот баг уже пару лет, его даже на Бее вроде так и не исправили толком. Можешь даже не писать на Гитхаб, об этом баге знают почти все, но там нужен полный реворк фотоаппарата

Нажмите на имя администратора для ответа.

PM to-Admins: Может быть, но раньше он не "засвечивал" мне каждый первый снимок, такое было раз в... Редко короче. А тут тупо один за одним и это удача если ничего не засветится вообще. Значит что-то недавно было сделано что оно сломалось.

**Comment by RichardJones1** [comment]
Да, это из-за плейнов сломали когда делали АО, я думаю
