### ISSUE TITLE
Test subject при заходе после начала раунда появляется без одежды и карты.

### ISSUE THREAD

**Issue by mrtuskee** [TauCetiStation/TauCetiClassic#3428]
#### Подробное описание проблемы
При заходе за Test Subjecta через join появился без комбинезона, обуви, ПДА и карты (но с наушником и рюкзаком с вещами из loadout)
#### Что должно было произойти
Должен был появиться с комбинезоном, обувью, ПДА и картой.
#### Что произошло на самом деле
При заходе за Test Subjecta через join появился без комбинезона, обуви, ПДА и карты.
#### Как повторить
Зайти через join за Test Subject

**Comment by Belfogor** [comment]
Зашел через джоин. Все работает 
![image](https://user-images.githubusercontent.com/12851693/56750994-a652ba80-678d-11e9-880f-5907cd88b415.png)

**Comment by volas** [comment]
Это не могла быть задержка с прогрузкой спрайтов? Как правило через некоторое время после захода всё отрисовывается.

Если можешь, скинь скрин сетап чарактера.

**Comment by mrtuskee** [comment]
Не похоже на задержку с прогрузкой, (сначала тоже так подумал - несколько минут подождал, перезашел - не решило). Сетап прикреплю, но внешность/ имя уже были перерандомлены. Раса была та же - человек, никаких механических конечностей не было.  В лоадауте pAI, Zippo, Aviator  transparent glasses.
![Безымянныйsc](https://user-images.githubusercontent.com/49985899/56752458-7ec21900-67b2-11e9-80e3-908dd4dbc551.png)

**Comment by volas** [comment]
Извиняюсь, был не точен, нужна вкладка Occupation

**Comment by mrtuskee** [comment]
![Безымянныйsco](https://user-images.githubusercontent.com/49985899/56753099-065c5780-67b4-11e9-892e-1d0b67a0b242.png)

**Comment by volas** [comment]
@mrtuskee в твоём случае можно переключить под тест сабджект сабпрофу - нажми на "Medical Intert"

**Comment by mrtuskee** [comment]
Принял, спасибо.

**Comment by volas** [comment]
Это индивидуальное решение, баг пока открыт.

Файл настроек игроков должен был обновляться с последним обновлением, но я похоже что-то не доглядел, или возможно из-за тестмержа у нас уже некоторые версии сейвфайлов в прошлом перевалили за 21

https://github.com/TauCetiStation/TauCetiClassic/pull/3297/files#diff-c4ab94c0724cfa15100ac5bc51d48442R85

**Comment by ViDLiathan** [comment]
Проверьте толстых, наверняка у униформы спрайта нет

**Comment by ViDLiathan** [comment]
Проверьте толстых, наверняка у униформы спрайта нет на некоторыхпрофах

**Comment by ViDLiathan** [comment]
#1149
