### ISSUE TITLE
[Proposal] Добавьте simple-mob'ов на слои космоса.

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#3430]
Учёные с телесалом без страха лезут на дереликты, диджейские станции, заброшенные шаттлы в поисках бесплатного лута. Наличие космо-русских, космо-пиратов, агентов Синдиката, разного зверья и так далее как бы намекнёт учёным, что теленаука - опасное дело, без труда не выловишь рыбку из пруда и... Вы поняли.

Как бонус: Теперь космированные заживо люди в РИГах встретят больше опасностей на своём пути и будут вынуждены бороться за жизнь на разбитых дереликтах, кусках астероидов и так далее. Что думаете?

**Comment by De-dawa-2** [comment]
но ведь все это сольется в походы есбе на косморусских из телесала.....

**Comment by Pivo24** [comment]
СБшники полезут на косморусских - СБшники проиграют ролям на станции. А в экстендед их ограничивают только сами учёные, которые, к слову, печатают на протолате оружие посерьёзнее.

**Comment by RichardJones1** [comment]
В одном из первых своих раундов я за ассистента летал по космосу, и... Это было толи тут, толи на Парадайзах. Я встретил шаттл синдиката, и до сих пор не могу понять, были ли это НИПы, или реальный шаттл, но было ОЧЕНЬ прикольно, всмысле, угроза далёкого космоса реально ощущалась, и манила исследовать его дальше.

**Comment by Lizurt** [comment]
Если этим и будут заниматься, то, пожалуйста, не обходитесь обычным спавном космокарпов... Новые мобы, хоть даже схожие по опасности и механике с космокарпами будут весьма кстати. 
А так я полностью "за" в этой идее. И в первую очередь это не для нерфа ученых-телесайленсистов, а как раз таки для того, чтобы за них было интереснее играть

**Comment by RichardJones1** [comment]
Если говорить в целом о интересностях вне станции - на Гунах существует "Derbis Field", или что-то такое - просто слой, заваленный интересными постройками. А вот на Бэе система посложнее, там случайная генерация таких межзвёздных локаций, очень интересная.
Одну проблему вижу - чем интереснее космос, тем больше будет у игроков соблазн покинуть станцию, что тоже не айс...

**Comment by Belfogor** [comment]
Случайная генерация карты, пусть даже хотя бы отдельных слоев, задумка суперская ... но .. кто же это реализует?

**Comment by megaomega005** [comment]
Бэй12 уже реализовал,проверяй

**Comment by RichardJones1** [comment]
У нас кодбаза сильно отличается, портировать будет далеко не просто

**Comment by megaomega005** [comment]
С этим почти справилась половина кодера а.к.а филат

**Comment by KatoMarika** [comment]
А они не будут улетать со слоя и прилетать к станции?

**Comment by Lizurt** [comment]
> А они не будут улетать со слоя и прилетать к станции?

Чтобы они переместились на другой слой им надо за кем то идти. Может они и и будут редко двигаться в разные стороны сами, но пока с помощью такого рандома они дойдут до станции, пройдет куча времени. Да и если это случится, будет нормально. Раз недалеко от станции есть мобы, почему они не могут быть около станции? Защитных орудий у станции нет, так что все верно.
А так по быстрому двигаться не за кем. Если игрок специально будет пытаться их на другой слой сманить, то ничего не выйдет. Он покинет слой первым, карп потеряет его из виду и перестанет двигаться так быстро. Дальше в деле уже описанный мной рандом.

**Comment by FelixRuin** [comment]
в некотором роде сейчас этот пропозал мощно считать выполненным, ибо появились структуры с мобьём
