### ISSUE TITLE
Доступ у АВД

### ISSUE THREAD

**Issue by RichardJones1** [TauCetiStation/TauCetiClassic#3434]
#### Подробное описание проблемы
У АВД был базовый доступ в инженерку. Теперь его нет.

#### Дополнительная информация:

@Belfogor , скорее всего ты что-то наделал в https://github.com/TauCetiStation/TauCetiClassic/pull/3424

**Comment by ViDLiathan** [comment]
Инженерный доступ теперь не открывает двери с главного входа. Но все еще можно зайти со стороны техов.

**Comment by LudwigVonChesterfield** [comment]
#3424

**Comment by Belfogor** [comment]
#3462 Закрывайте
