### ISSUE TITLE
Телепорт тел без головы телепортатором тел

### ISSUE THREAD

**Issue by piterskiy2** [TauCetiStation/TauCetiClassic#3443]
#### Подробное описание проблемы
При попытке телепортировать труп без головы телепортатором тел, в чате вылезает ошибка, что Unknown is in a good state

#### Что должно было произойти
Труп должен был телепортироваться

#### Что произошло на самом деле
Труп не телепортировался и вылезла ошибка, что человек в норме

#### Как повторить
Попытаться телепортировать труп без головы телепортатором тел

**Comment by ViDLiathan** [comment]
Вроде бы высосаные генкой так же
