### ISSUE TITLE
Баг, не позволяющий пользоваться камерами видеонаблюдения

### ISSUE THREAD

**Issue by igor132** [TauCetiStation/TauCetiClassic#3447]
#### Подробное описание проблемы
При попытке открыть консоль просмотра камер появляется само окошко с фоном(как и должно быть), но списка камер нет и поверх окошка появляется ошибка (скрин ниже). 
При нажатии на ОК ошибка выскакивает снова. Продолжается это до тех пор пока не поставишь галочку и после этого не нажмёшь ОК. После избавления от ошибки список камер не появляется, как и прочих кнопок, позволяющих открывать камеры через карту.

Так же отмечу, что проверял я только консоли СБ (которые со всем списком), но не трогал ту, что в комнате допроса, а так же прочие. Проблема возникает только с этими консолями (медики просили меня включять датчики т.е. у них всё работает. Так же база данных СБ спокойно открывается), но у всех игроков

#### Что должно было произойти
Открыться список всех камер станции, после чего можно было выбрать нужную и начать просмотр
#### Что произошло на самом деле
Появляется пустое окно с ошибкой
#### Как повторить
Открыть консоль просмотра камер

#### Дополнительная информация:
обещянный скрин
![сс13_баг](https://user-images.githubusercontent.com/50137934/56955589-84b95080-6b4a-11e9-8b93-7e41204906a9.PNG)

**Comment by piterskiy2** [comment]
Такая же ошибка на любой консоли просмотра камер. Пример монитор камер в инженерке

**Comment by SpaiR** [comment]
@volas

**Comment by volas** [comment]
Мне кажется это не я, но проверяю

**Comment by igor132** [comment]
если вы про чувачка с боку что это я

**Comment by volas** [comment]
нет, мы про "кто виноват" :)

**Comment by igor132** [comment]
ты во всём виноват

**Comment by igor132** [comment]
я следить не могу за человеками

**Comment by igor132** [comment]
:)

**Comment by igor132** [comment]
я пошутил - не обижайся
