### ISSUE TITLE
У тех. ассистентов отвалился доступ

### ISSUE THREAD

**Issue by TEXH4Pb** [TauCetiStation/TauCetiClassic#3449]
#### Подробное описание проблемы
После #3297 у тех. ассистентов пропал доступ в тех. тоннели и хранилище инструментов  [пикрил](https://map.taucetistation.org/tiles/d24640f54/tiles/5/13/9?v=1.4.1-build:1552268560302)
#### Что должно было произойти
Тех. ассистенты должны иметь перечисленные доступы.
#### Что произошло на самом деле
Они их не имеют.
#### Как повторить
Зайти за тех. ассистента, упереться головой в шлюз тех. тоннеля.
#### Дополнительная информация:
@Belfogor

**Comment by rarytech** [comment]
Эй, это всё ещё актуально

**Comment by Belfogor** [comment]
Он у них не отваливался, поскольку и не должен был быть

**Comment by RichardJones1** [comment]
Тогда почини доступ у АВД)))

**Comment by rarytech** [comment]
круто, не понять этот полет мысли, который привел к тому, что  _техническому_ ассистенту не нужен доступ в _технические_ тоннели. И видимо не только мне, потому что кто-то вообще посчитал это багом

**Comment by megaomega005** [comment]
Очевидно, человек пытается заставить игроков занимать "нормальные" профессии, а не заниматься непотребствами на ассистухах
Пытается, к слову, уже долгое время и разными способами, в роде всаживания всем гиб-имплантов, привязки ассистентов к отделами и т.п.

**Comment by Belfogor** [comment]
#3467

**Comment by KatoMarika** [comment]
Перепроверено на всякий случай, можно закрывать.

**Comment by Alexofp** [comment]
Исправлено в #3467
