### ISSUE TITLE
Интерфейс наушника не открывается после ЭМИ

### ISSUE THREAD

**Issue by skvazarb** [TauCetiStation/TauCetiClassic#345]
#### Что должно было произойти
Интерфейс должен открываться
#### Что произошло на самом деле
Интерфейс не открывается
#### Как повторить
Любой наушник и ЭМИ

**Comment by StrikS** [comment]
Вчера кстати это заметил. Пришлось снимать с трупа рабочий.

**Comment by MorCrate** [comment]
Фича же.
Он через некоторое время разрешает.

**Comment by StrikS** [comment]
Через полчаса?

**Comment by MorCrate** [comment]
У меня через несколько минут позволило открывать.

**Comment by skvazarb** [comment]
Жду больше 15 минут, интерфейс всё еще не открывается.

**Comment by Raschert0** [comment]
А это всё фиксеры, которые "пофиксили" эми и глушилку абдукторов простым вырубанием наушника КЕМ

**Comment by MorCrate** [comment]
Код Моггилаза - пускай он и фиксит это.

**Comment by volas** [comment]
Не стоит так, дружелюбней нужно быть. И добро пожаловать в опен соурс.

**Comment by MorCrate** [comment]
Может чуточку недружелюбно выразился, я имел ввиду, что я не читал его коммиты и пока не охотно берусь брать это, так как вдруг это забагует ещё в большую степень.
