### ISSUE TITLE
Издевательство над инвалидами путем разбирания коляски одним кликом ключа

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#3463]
#### Подробное описание проблемы
Человек может подбежать и ключом разобрать коляску инвалиду на кусок металла

#### Что должно было произойти
Он не должен издеваться на весь раунд над инвалидами одним кликом

#### Что произошло на самом деле
Инвалид валялся на земле рядом с куском металла

#### Как повторить
Подбежать к инвалиду и тыкнуть ключом по коляске

#### Дополнительная информация:
Это просто издевательство над инвалидами

**Comment by Garrysman232** [comment]
даешь не разборные коляски, и апгрейженные коляски в рнд

**Comment by LudwigVonChesterfield** [comment]
>Стоит еще добавить и задержку на отстегивание

Целую мини-игру где инвалид будет на скорость жать резист сопротивляясь вытягиванию его из коляски.
