### ISSUE TITLE
Не обновляется панель проводов шлюза

### ISSUE THREAD

**Issue by rarytech** [TauCetiStation/TauCetiClassic#3472]
#### Подробное описание проблемы
При пульсе или обрезании провода, панель взлома не обновляется.
#### Что должно было произойти
При пульсе или обрезании провода в нижней части панели должны меняться on/оff и другие результаты.

#### Что произошло на самом деле
При пульсе или обрезании провода ничего на панели не меняется. Увидеть результат взлома можно только закрыв панель и открыв её заново
#### Как повторить
Попробовать взломать шлюз
#### Дополнительная информация:
гитхаб дает ссылку на похожее https://github.com/TauCetiStation/TauCetiClassic/issues/857

**Comment by Naryvan** [comment]
Судя по всему, сломал я. Сейчас посмотрю.
