### ISSUE TITLE
У культей есть имба, бумажки имба, бладбоил тоже[Proposal]

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#3478]
#### Подробное описание проблемы
У культа есть имба в виде бумажек и бладбоила

#### Что должно было произойти
Нужен баланс

#### Что произошло на самом деле
Пыщ бумажкой, ты труп.
Пыщь бладбоилом, еще трупы

#### Как повторить
Поиграй за культю

#### Дополнительная информация:
"Пыщ, паш, И ТОЛЬКО ПИСЮНЫ ПО СТЕНКАМ!"
"Пыщ, ух, я пожалуй с твоим телом чай попью, и даже глаза не закатывай, я могу тебя вечно в стане держать...ах время выходит ПЫЩ ПАШ, отрезали голову"

**Comment by volas** [comment]
дубликат #3372
