### ISSUE TITLE
[Proposal] Нерф Бладбоила и талисмана.

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#3479]
Дубль 2, прошел почти месяц с первого обращения, но всем похуй - все знают, типичная Тау Кеки и тому подобное.

Бладбоил есть ОП ибо - Способен гибать сквозь стены, игнорирует любую броню, херачит сплешем и с одного удара. Тут еще оказалось, что оно обладает высоким радиусом поражения.

У талисмана слишком долгий стан с мутом, а так же для его крафта требуется лишь листок бумаги коих на станции очень много. Подкалиберная бумажка способная пробить абсолютно любую защиту крафтится с помощью обыкновенной бумажки блять! ЛИСТА ОБЫКНОВЕННОЙ БУМАГИ!
Тащемта с этим надо что-то делать ибо своим РП довели до того, что им можно и в робах ходить по станции ибо "екипаж не знает об существовании культа", так они и обладают самым сильным оружием в игре для создания которого требуется либо бумага либо пол.

Либо снимайте волшебное незнание об культе, либо нерфите это гавно.

**Comment by volas** [comment]
дубликат #3372
