### ISSUE TITLE
[Proposal]  Нёрфите кровавого бога во имя бога баланса 

### ISSUE THREAD

**Issue by iVIKOTi** [TauCetiStation/TauCetiClassic#3480]
#### Подробное описание проблемы
Небалансные способности у культистов
#### Что должно было произойти
Завезите нёрф молоты
#### Что произошло на самом деле
Мои кишки размазались по стенам техов, от одного каста бладбойла, который был за километр от меня. До этого меня на МИНУТУ застанили ошеломлением
#### Как повторить
Рисуешь руну и обмазываешься кровью 
#### Дополнительная информация:
Типичная первая минута раунда культа, четыре недоумевающих офицера станятся ошеломлением с последующим отрубанием голов

**Comment by volas** [comment]
дубликат #3372
