### ISSUE TITLE
Ядерная бомба не обезвреживается

### ISSUE THREAD

**Issue by De-dawa-2** [TauCetiStation/TauCetiClassic#3483]
#### Подробное описание проблемы
Ядерная бомба не обезвреживается 

#### Что должно было произойти
После тыка сваркой на работающую бомбу должен был запуститься процесс распилки обшивки бомбы

#### Что произошло на самом деле
Ничего не произошло, пришлось выкидывать бомбу в космос

#### Как повторить
Поиграть за офицера сб или члена обр во время нюки, дожить до плента бомбы и попытаться обезвредить ее

#### Дополнительная информация:
#3276

**Comment by FelixRuin** [comment]
я уже ныл что я не в силах пофиксить это, так что да, я умываю руки, в душе не представляю как это сделал

**Comment by De-dawa-2** [comment]
тогда ревертай свой реворк инструментов, до него все работало!!!

**Comment by FelixRuin** [comment]
это не реворкать надо, а багфиксить, хз как, но у меня лапки

**Comment by EdlerN** [comment]
Ну значит смотри. Не починишь через недлю - уже будет лапка.

**Comment by FelixRuin** [comment]
я пожалуюсь в суд по правам лапок!!! я говорил что я это сломал случайно, всем было пофиг

**Comment by EdlerN** [comment]
Ты успей только пока лапки есть... Ну а если серьезно - иди давай, сам сломал, сам и чини. Или мне еще в логах твои обосрамсы поискать, чтобы тебе мотивации добавить? А то мне недавно рассказывали про один очень забавный случай который может стать очень печальным....

**Comment by RichardJones1** [comment]
Ну тогда надо понять в чем трабл и пофиксить, либо делать реверт... Какой функционал тот ПР вообще добавил?

**Comment by RichardJones1** [comment]
>Ты успей только пока лапки есть... Ну а если серьезно - иди давай, сам сломал, сам и чини. Или мне еще в логах твои обосрамсы поискать, чтобы тебе мотивации добавить? А то мне недавно рассказывали про один очень забавный случай который может стать очень печальным....



Дядя ЭдлерН, ну зачем вы так с винтером(((( Ему только меньше захочется пилить что-то. Он наверняка не знал про сломанную нюку, когда ПР апрували-мёржили...

**Comment by dred1792** [comment]
Тот ПР был сделан по моей просьбе для более простой реализации моей задумки, касательно которой я тебе говорил и спрайты просил мне нарисовать.

**Comment by SpaiR** [comment]
Оформи ишью как надо (без переходов на личности, пожалуйста). А именно изменить заголовок и конкретизировать суть проблемы (не разваривается нюка, так?).

**Comment by De-dawa-2** [comment]
хорошо все вот сделало
