### ISSUE TITLE
Отсутствие массы у газов

### ISSUE THREAD

**Issue by 1Samen** [TauCetiStation/TauCetiClassic#3485]
#### Подробное описание проблемы
Нету массы газов на сканере ,а еще масса газа не изменяется при охлаждении.

#### Что должно было произойти
При охлаждении o2 я должен был дышать при менее 16 kPa и давление в баллон бы снизилось.
#### Что произошло на самом деле
Давление в баллоне снизилось ,но при менее 16 kPa задыхался .
#### Как повторить
Просто охладить o2 в баллоне .
#### Дополнительная информация:
Куда делось давление если масса газа не изменилась ? Или я чего-то не понимаю ?

**Comment by EdlerN** [comment]
Могу лишь посоветовать учить физику. Что еще. А в механике скорее всего прописано не колличество газа а давление кислорода на турфе, Ну или откуда там персонаж дышит.

**Comment by 1Samen** [comment]
Блин заметил что допустил такую тупую ошибку. Надо было написать куда делось давление и масса газов ,а не то что масса газов не изменилась .
