### ISSUE TITLE
Баг с текстурами после нового раунда

### ISSUE THREAD

**Issue by Sombra912** [TauCetiStation/TauCetiClassic#3488]
#### После каждого раунда происходит вот такая вот вещь (скрин)

https://ibb.co/BZf4VTk

Приходится переустанавливать Ббьёнд, т.к. чистка кэша в документах не помогает. Очистка IE также не помогает

**Comment by ZVee** [comment]
Это выглядит как переход от хардварного рендеринга к софтварному. В преференсах самого бъенда в 4-й вкладке "games", есть настройка "use graphical ..."

![hwb](https://user-images.githubusercontent.com/8426718/57780270-94cb5580-7730-11e9-925f-d7ef2ff75ca8.png)

Вот ее стоит проверить когда такое происходит. Если галочка стоит, а на экране то что со скрина - стоит отключить и включить снова. Т.е сама настройка должна быть включена, т.к это поведение когда она наоборот выключена. А если она выключена, то и так понятно в чем дело.

**Comment by Sombra912** [comment]
Каждый раз выключать и включать?

**Comment by ZVee** [comment]
Если помогает, то да. За решение кода я не могу ничего говорить, и тем более обещать - тут уж если кто-то таки возьмется пробовать внедрять форс этого режима клиентам.

**Comment by KIBORG04** [comment]
Думаю не актуально
