### ISSUE TITLE
[Proposal] Роли и работа 

### ISSUE THREAD

**Issue by KatoMarika** [TauCetiStation/TauCetiClassic#3490]
#### Подробное описание проблемы
При режимах, в которых станция нуждается в защите вечно нет охранного состава, ибо они сидят в ролях за бортом.
#### Что должно было произойти
На станции должны быть силы, которые хоть как-то смогут ответить на агрессию. 
#### Что произошло на самом деле
Алгоритм выбора ролей вечно вытягивает людей из СБ.
#### Как повторить
Форсить нюку или воксов. Ну или пиратов, если их не сломали там совсем. 
#### Дополнительная информация:
Проблема уже обсуждается давно. но кажется пора уже что-то с ней делать.

**Comment by RichardJones1** [comment]
Да, старая проблема. Эт даже и не пропозал, а баг. Просто с нашими алгоритмами выбора роли закодить это будет очень тяжело.
