### ISSUE TITLE
С новой системой инвентаря нельзя снять аксессуары с униформы

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#3493]
#### Подробное описание проблемы
После пээра с новым инвентарем вместо красивого "HoS McLaw срывает значок с груди Shitsec McDebil!" при попытке снять аксессуар через меню раздевания происходит ничего.
#### Что должно было произойти
Аксессуар должен был оказаться на полу или в руках.
#### Что произошло на самом деле
Ничего

**Comment by RigoSex** [comment]
Подтверждаю баг, приходилось раздевать людей чтобы отобрать кобуру.
