### ISSUE TITLE
Очень маленькое поварское окно для еды [Proposal]

### ISSUE THREAD

**Issue by HaosHay** [TauCetiStation/TauCetiClassic#3508]
#### Подробное описание проблемы
Окно для выдачи еды у поварский слишком маленький, он постоянно очень сильно не эстетично, неудобно - забит едою.

#### Что должно было произойти
Еда раскладывается просторна на двух-трёх столах, экипаж спокойно может взять эту еду.

#### Что произошло на самом деле
Вся еда забита на одном столе в один тайл, где приходится правой кнопкой мыши кликать, что бы разобрать - что там вообще в меню валяется во всей этой куче.

#### Как повторить
Будьте активным поваром без бармена, забивайте еду в столик один тайтл, откуда экипаж будет брать ваши кулинарные шедевры.

#### Дополнительная информация
Реально неудобно, а учитывая что повысили голод - в нужде поваре ещё больше повысилось, а ему такие неудобства с кормлением экипажа. Даже в баре толком эту еду не раскидать. А ведь исправляется простыми изменениями в карте маппером.

![image](https://user-images.githubusercontent.com/50915887/58178197-2c93eb00-7cbf-11e9-9ca0-5476bd4ea3e0.png)

**Comment by RichardJones1** [comment]
Каждый раз когда я за повара прошу инженеров разобрать эти стёкла, поставив просто три створки. Удобно и практично.

**Comment by ViDLiathan** [comment]
Просто сделайте повару автомат-раздатчик еды. Как у ботаника или химика

**Comment by HaosHay** [comment]
> Просто сделайте повару автомат-раздатчик еды. Как у ботаника или химика

Это надо уже кодить. Это менее просто, чем, имхо, просто сделать окошки открывающие

**Comment by Belfogor** [comment]
Можешь перемапить. Я даже помогу разобраться как что и к чему. Дело там трех кликов. Потому что ждать пока кто-нибудь за это возьмется - гиблое дело.

**Comment by HaosHay** [comment]
> Можешь перемапить. Я даже помогу разобраться как что и к чему. Дело там трех кликов. Потому что ждать пока кто-нибудь за это возьмется - гиблое дело.

*пошёл писать в личку*
