### ISSUE TITLE
Бесконечная водка 

### ISSUE THREAD

**Issue by ArtBsd1** [TauCetiStation/TauCetiClassic#3510]
#### Подробное описание проблемы
Если открыть ватертанк в космосе, то емкость ватертанка бесконечна. В данном случае это 930 units of Vodka. Возможно, он и на станции не кончается.
#### Что должно было произойти
Содержимое ватертанка должно кончится 
#### Что произошло на самом деле
Не кончилось
#### Как повторить
открыть ватертанк

**Comment by KuzyXD** [comment]
Только что проверил это. Ватертанк в космосе разливает воду как по полу и кончается.
