### ISSUE TITLE
Шаттл не гибает людей

### ISSUE THREAD

**Issue by ArtBsd1** [TauCetiStation/TauCetiClassic#3515]
#### Подробное описание проблемы
Конец смены, ассистенты ждут шаттл. Когда звук о прибытии шаттла начал(Дакин зе...), ассистенты, которые ждали около шлюзов. Шлюзы открылись неожиданно, когда шаттл ещё не прибыл. Они   `переступили жёлтую линию и`  улетели в космос. По идее, их должно было раздавить, но их тела перенеслись к стенкам шаттла.
#### Что должно было произойти
Тела должны были эпично разорваться на куски 
#### Что произошло на самом деле
Их перенесли! 
#### Как повторить
Вызвать шаттл и броситься под него
#### Дополнительная информация:
![Снимок24](https://user-images.githubusercontent.com/44677341/58344626-ab2f8a80-7e6f-11e9-99c8-12362bf039e6.PNG)

**Comment by Lizurt** [comment]
И не должно по идее. Чтобы их разорвало на куски надо чтобы они были между чем то и чем то. Шаттл есть, но вдавливать мобов ему некуда - там вакуум. Стыковка должна по логике проходить на небольшой скорости, так что от скорости шаттла их тоже не гибнет.
В итоге получается, что их может лишь сильно оттолкнуть, но никак не гибнуть. Можно наверно только в качестве твика добавлять им урон помимо отталкивания. Было бы неплохо. Но это уже пропосал скорее всего а не баг

**Comment by ZVee** [comment]
А как же гибающий саплай? Просто на самом деле проблема копипасты, и до этого шаттла гиб не дошел, и не удивительно, учитывая что у нас каждая консоль управления шаттла, это копипаста на копипасте.
