### ISSUE TITLE
Кнопки-хоткеи ломают экран и имеют смещенное описание

### ISSUE THREAD

**Issue by Lizurt** [TauCetiStation/TauCetiClassic#3517]
#### Подробное описание проблемы
Кнопки-хоткеи, находящиеся слева вверху теперь сломаны. Их описание смещено непонятно куда вниз, а если их подвигать - вообще получается какая то непонятная хрень - экран уменьшается в зависимости от того, куда же этот хоткей сдвинуть. 

#### Что должно было произойти
Значки не должны ломать экран его уменьшением, а описание должно быть рядом со значком.

#### Что произошло на самом деле
Описание кнопок смещено, а их перемещение ломает экран.

#### Как повторить
Навести курсор на любой значок чтобы посмотреть описание, переместить значок ЛКМ по экрану чтобы сломать его

#### Дополнительная информация:
<details><summary>СКРИНШОТЫ-ПРИМЕРЫ ПРОБЛЕМ С ХОТКЕЯМИ-КНОПКАМИ:</summary>

![image](https://user-images.githubusercontent.com/42589308/58353280-c5209b80-7e76-11e9-9a62-8604c4259371.png)

![image](https://user-images.githubusercontent.com/42589308/58585879-78680680-8262-11e9-964a-dd9797e977fa.png)</details>

**Comment by Lizurt** [comment]
Чем больше я играю тем хуже баги с этими значками нахожу. Если этот баг не вызван недавним моим обновлением бьенда до последней версии - его стоит пофикисть побыстрее. В последний раз тейсти трогала эти значки. Я конечно не обвиняю ее, но мало ли, может она знает с чем это может быть связано @Smalltasty

**Comment by LudwigVonChesterfield** [comment]
Ну а я бы наверное открыл обратно чтобы все желающие ознакомиться с причиной подобного могли мгновеннием ока увидеть что ето Бьёнд всех сломал.
