### ISSUE TITLE
[Proposal] На весь медбей не хватает поясов и Худов

### ISSUE THREAD

**Issue by Mazzik12** [TauCetiStation/TauCetiClassic#3525]
#### Подробное описание проблемы
Из-за введения интернов и использования другими "Медиками"(Химик, генетик ,психолог, вирусолог) мед.поясов, на всех не хватает(даже если учитывать пояса в шкафах). Приходится либо носить все в сумке, либо пытаться отобрать у товарищей пояса.
#### Что должно было произойти
Весь медбей снабжен мед.поясами и ХУДами
#### Что произошло на самом деле
Медбей не экипирован до конца. Не хватает простейших поясов и Худов. ЦК не заботиться о продуктивности сотрудников?
#### Как повторить
Загрузить карту NSS Исход. Проверить колличество поясов и сравнить с максимально возможным колличеством всех работников мед.бея.

**Comment by AndroBetel** [comment]
/пропозел/: отбирать у генетиков и иже с ними пояса, им они все равно не нужны.

**Comment by 8161912** [comment]
Худы можно запросить в РнД, а поясам нужно добавить крафт в том же РнД.

**Comment by StrikS** [comment]
Пояса больше для карго характерны, там, например,  можно разгрузки заказать. А РНД всё же не швеи

**Comment by OfficerSoftheart** [comment]
Пояса - добавить крафт в ботанике
Худы - уже есть в РнД. 
Психотерапевту/генетику/вирусологу/химику не нужны как худы, так и пояса. Это уже РП ситуация, если хотят - пусть идут в РнД и просят, или берут в меде, но тогда врачам надо будет идти искать пояса и худы. Только вот профам выше данное нафиг не нужно, если есть врачи, там достаточно рюкзака для таскания пары банок с химикатами. На крайняк при развитом РнД можно взять трэшбэг оф холдинг с худами. Ну вообщем из пропозала, только добавить крафт разных поясов в ботанике.

**Comment by Belfogor** [comment]
решение все ваших без заключается в добавление нескольких поясов на карту. Это дело пяти минут.

**Comment by LudwigVonChesterfield** [comment]
Альтернативное решение: убрать оставшиеся пояса с карты, чтобы всем было хорошо и равно.

**Comment by Lexakr** [comment]
Не думаю, что стоит добавлять пояса и ХУДы на карту, их достаточно, все остальное можно и заказать

**Comment by Sakuya-Izayoi** [comment]
это баланс
