### ISSUE TITLE
Прозрачные и пропадающие шлюзы.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#3526]
#### Подробное описание проблемы
Если открыть шлюз в офис старшего инженера, то спрайт двери станет прозрачным. Если его закрыть и открыть, то он станет нормальным. То ли это через раз так выходит, то ли ещё как - я не знаю. Кажется, https://github.com/TauCetiStation/TauCetiClassic/issues/2967 - это что-то похожее.
#### Что должно было произойти
Он не должен быть таким.
#### Что произошло на самом деле
Он такой.
#### Как повторить
Открыть шлюз.
#### Дополнительная информация:
![изображение](https://user-images.githubusercontent.com/29904082/58469845-0780fb80-8149-11e9-8dd3-32277dd1b1e6.png)
![изображение](https://user-images.githubusercontent.com/29904082/58469891-28495100-8149-11e9-8fcb-0b1f0f66c659.png)

UPD: 
Шлюз в робототехнику становится невидимым после открытия.
![изображение](https://user-images.githubusercontent.com/29904082/58469995-6e061980-8149-11e9-94f6-51c1e1c03be5.png)

**Comment by T6751** [comment]
@LudwigVonChesterfield Сейчас уже и текстурки другие, ууф, ностальгия... прозрачных и пропадающих шлюзов не заметил в текущем билде. эти два дела можно закрыть?
![20200609 145644](https://user-images.githubusercontent.com/66636084/84144981-c9a7fa00-aa61-11ea-81dd-1f37821d08db.png)
![20200609 145653](https://user-images.githubusercontent.com/66636084/84144985-cb71bd80-aa61-11ea-903a-a1f9c49c1948.png)
![20200609 145758](https://user-images.githubusercontent.com/66636084/84144990-cdd41780-aa61-11ea-8e22-5177fa1754bf.png)

**Comment by LudwigVonChesterfield** [comment]
![image](https://user-images.githubusercontent.com/17705613/84147677-7be1c080-aa66-11ea-81de-26316b09b3bf.png)

Есть чувство что у вот этой штуки layer должен быть ниже чем у шлюза. Но в целом да, можно закрыть.

**Comment by LudwigVonChesterfield** [comment]
#4536
