### ISSUE TITLE
[Proposal] Повысить время для нюки

### ISSUE THREAD

**Issue by Artik12344** [TauCetiStation/TauCetiClassic#3527]
#### Подробное описание проблемы
Новички которые играют только третий день ставят галку на нюку
#### Что должно было произойти
Они не должны туда попадать
#### Что произошло на самом деле
Они попадают в нюку
#### Как повторить
Долго следить за игроками которые попадают в нюку и чекать время их игры 
#### Дополнительная информация:
Повысить до 40к минут отыгрыша как на Гамме

**Comment by EdlerN** [comment]
Автор обладает надёжными данными с сервера и ни разу не горит от того что в очередной раз пососал, при этом, пытаясь переложить вину на подбор команды.

**Comment by Artik12344** [comment]
Но это ведь реально проблема. Человек не понимает где он, что делать, кто он ибо просто не набрался опыта и вставил галку на антагов

**Comment by EdlerN** [comment]
Ты удивишься, но средний ингейм на нюкерах как есть - в районе 20к. Ровно как и средний ингейм по серверу. Этот параметр мало на что влияет. Ты к примеру до сих пор так и не научился играть...

**Comment by Lizurt** [comment]
40к конечно многовато будет, но повысить я тоже думаю стоит. Сейчас время на нюке [установлено на 480 минут](http://prntscr.com/nuh9qx). Это крайне мало для игры на такой непростой, командной и робастозависимой рольке. Средние значения конечно хорошо, но на этой рольке могли играть как и 100к+ деды, так и игроки у которых только что набралась первая тысяча. 
Когда выпадала нюка, я нередко замечал, что в команде бывают неопытные игроки, которые не знают что делать на той рольке, которая им выпала. Обычно когда начинается штурм они даже забывают переключить баллон в шлюзе или попросту улетают в дипспейс, не совладав с джетпаком. 
В моей недавней нюке так и произошло - несмотря на мой капс два раза о том, что надо включить баллон перед походом в шлюз - все равно один ничего не сделал и погиб. Если они даже не знают как переключать интернал, то как им воевать? Хорошо, конечно, что они набираются опыта при таких ошибках и вряд ли их совершат в дальнейшем, но этот легко отданный в начале игры слот нюкера мог занять более опытный игрок. Научиться базовому робасту и действиям в вакууме можно и без метода проб и ошибок - просто поиграть на менее важных рольках(тот же тритор ) или вообще на обычных профессиях.

Так что я тоже предлагаю поднять порог времени для нюкера, но не до 40к, а хотя бы в районе 10к-20к

**Comment by EdlerN** [comment]
И все забывают что на станции с офицериками абсолютно такая же история... давайте и там время поднимем... а еще врачам чтобы лечили и не вырезали случайно мозги... а еще инженерам чтобы не выпускали сингу... ну и главам примерно 100к поставить планку....

**Comment by volas** [comment]
* Можно переверстать табличку с "да/нет" антагами, добавить комментарии, явно указать ожидания от проф и примерную сложность
  * После чего можно даже сбросить текущие настройки игроков в этой вкладке
* Добавить им подсказку при старте. Как у воксов есть например. Только тут желательно бы в целом отрефакторить подобные подсказки в лицо игроку, и вынести их в отдельные конфиги (можно по аналогии с вики-книгами)...
* Можно перемапить базу, переписать старт, спавнить нюкеров хоть сразу со скафандром и включенными баллонами.

Проблема в том, что режим не частый, игрокам нет возможности равномерно обучаться аналогично как со станционными профами. И накрутка времени тут не поможет. Если только не делать из этого почти вайтлист, как на гамме. 
Если у человека не было возможности поиграть за эту профу - он точно так же будет теряться и волноваться в первый раз, даже если имеет уже десятки тысяч наигранных минут.
Так что половина сливающихся нюкеров, мне кажется, вполне нормально. Игроки учатся, в следующий раз будет лучше. Можно только всячески помогать, объяснять. 
И для победы нюки всё равно достаточно единственного человека. А если в раунде всё совсем плохо с балансом, может админ подсобить.

**Comment by Belfogor** [comment]
Проблема не в частоте режима. А в том что участвуют в этом карнавале игроки, которые толком не освоились в механе. Нюкеры не умеющие в баллоны и цепляющие ранцы на скафанд уже давно стали мейнстримом.

Сам режим имеет общие механики с режимом предателя. Игрок сыгравший хотя бы тройку раз трейтором, и в достаточно мере изучивший механ взаимодействия со всякими ништяками для выхода в открытый в космос, в целом должен суметь справиться с игрой в нюкера

**Comment by KatoMarika** [comment]
Если будете повышать время, то вайт на глав верните, для баланса закручивания гаек. 

То что команды нюкеров\воксов\пиратов да и в целом все остальные антаги сливаются - нормально, роли не обязательно должны выигрывать, так же как и экипаж не должен иметь 100% выживаемость.
