### ISSUE TITLE
мусорный конвейер в карго убивает.

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#3532]
#### Подробное описание проблемы
Куклы застревают прямо в disposal outlet и их там очень сильно убивает давлением по какой-то причине.
#### Что должно было произойти
Кукла свободно несется к мусорщикам.
#### Что произошло на самом деле
Кукла застревает и получает жестким повышенным давлением по голове.
#### Как повторить
Прыгнуть в мусорку и надеяться на повторение бага.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/44546836/58578769-36cf5f80-8252-11e9-95b2-1ffbc0c6109e.png)

**Comment by DarkLevelSS13** [comment]
Если человека закинули в стоячем положении в мусорку, и в то время как улетает по трубам он не лег, он не сможет пройди сквозь эти решетки. Вот что мне удалось выяснить.
