### ISSUE TITLE
Зависает игра через 2 минуты после входа на сервер.

### ISSUE THREAD

**Issue by Remigan** [TauCetiStation/TauCetiClassic#3541]
#### Подробное описание проблемы
Примерно через 2 минуты после захода на сервер игра зависает, и выходит красная полоска с надписью: "You are either AFK, experiencing lag or the connection has closed." Так происходит каждый раз. На других серверах такой проблемы нет.

**Comment by volas** [comment]
Пинг до этого момента нормальный? Попробуй обновить byond до последней версии.

**Comment by Belfogor** [comment]
Если с соединением проблемы, то вероятно нужно отследить что там с трафиком и не теряются ли там где-то пакеты на пути от клиента к серверу и обратно.

**Comment by KIBORG04** [comment]
Думаю не актуально
