### ISSUE TITLE
Инструменты и некоторые анонсы звучат как дерьмо и загружаемые в саунд амбиенты от админов тоже

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#3545]
#### Подробное описание проблемы
Пианино, гитара и остальные инструменты сломались, и воспроизводят звуки неправильно, из за чего получается какафония. Баба оповещающая о прилете шаттла тоже изменяет свой голос, то на очень низкий, то на очень высокий. Тоже самое с амбиентами у админов которые они загружают
#### Что должно было произойти
Нормальное воспроизведение звуков
#### Что произошло на самом деле
Изменение тональности
#### Как повторить
сыграть на пианино, дождаться шаттла, загрузить музло за админа

**Comment by SpaiR** [comment]
#3505

**Comment by Dominig12** [comment]
Вот дополнил дополнительными тестами

**Comment by ZVee** [comment]
>загрузить музло за админа

У них две кнопки, для локальных звуков - что симулирует обыденное поведение звука, для всяких там эффектов игровых, и глобальное - для музыки в которой никаких эффектов лишних быть не должно.

Собственно если музыку загружали в локальные, то не удивительно что все было плохо, там и звук будут слышать только кто рядом (причем с учетом дистанции от "госта" админа), и вариативность.

**Comment by Dominig12** [comment]
Да, это был локальной саунд

**Comment by SpaiR** [comment]
Не актуально.
