### ISSUE TITLE
Ядерный диск.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#355]
#### Подробное описание проблемы
Возможность телепортироватся с диском на слое стацнии.
#### Что должно было произойти
В портал нельзя зайди с диском
#### Что произошло на самом деле
Спокойно заходишь в портал и телепортируешься по станции
#### Как повторить
Берете диск и телепортер, можно ручной или стационарный, настраиваете его на маячек в атмосферке либо прибытии и прыгаете.

**Comment by Lancer411** [comment]
Так и задумано. Запрет на перенос диска на другой Z уровень это игровая условность. В пределах одного Z уровня диск можно перемещать без проблем любым образом.

**Comment by Dennok** [comment]
оууу... пипец.... теперь нюка будет вообще ппц быстрой.
тп в телепортную, марш до диска, марш обратно, тп на полигон и все.
 ппцц

**Comment by MorCrate** [comment]
Так она всегда такая была, нет?

**Comment by Uvash** [comment]
Может переделать спавн диска? Например спавн у старшего главы или варденна. Либо же старший глава должен оберегать диск, поисковик и золотую ИД карту.

**Comment by Skippeer12** [comment]
Если не баг, значит парень получил пермаджобку зря, ехххх
