### ISSUE TITLE
[proposal] [balance] Куклы слишком легко загрузить в крио

### ISSUE THREAD

**Issue by Zmey25** [TauCetiStation/TauCetiClassic#3553]
#### Подробное описание проблемы
Персонажа легко загрузить в криокапсулу (<1секунда), а вылезти из крио сложно(30секунд), в итоге это легкий способ вывести персонажа из игры, накинув ему в кровь химикатов.

#### Что должно было произойти
Персонажа в крио нужно заталкивать какое-то время, чтобы была возможность сбежать.

#### Что произошло на самом деле
Затолкали пока писал в чат

#### Как повторить
Перетянуть тушку на открытое крио

**Comment by ViDLiathan** [comment]
Если и вводить, то только если кукла стоит.
А то в последних нерфах слишком много действий с задержкой

**Comment by DarkLevelSS13** [comment]
Ого, еще одна причина усложнить работу для медиков, которые даже крио не могут настраивать...
Я буду вспоминать те веселые времена, когда в меде могли тебя спокойно вылечить, не держа тебя там 30 минут.

**Comment by Zmey25** [comment]
Окей, тогда давай сделаем возможность вылезать из крио сразу же, без задержки. Твои неумелые медики не пострадают.

**Comment by DarkLevelSS13** [comment]
Тогда кукла у которой топографический кретинизм (или как то про другому называлось геное заболевание, которое заставляло куклу произвольно ходить в стороны) у неё будет  сразу прерываться крио, ибо даже шаг в сторону, запускает процедуру изьятия куклы из крио.
