### ISSUE TITLE
Пулл тела на кушетке дамажит его

### ISSUE THREAD

**Issue by CoffeeMolka** [TauCetiStation/TauCetiClassic#3555]
#### Подробное описание проблемы
Если положить раненное тело на кушетку, закрепить и повезти пуллом, то тело оставляет за собой кровавый след, а так же получает дамаг.
#### Дополнительная информация:

**Comment by Dominig12** [comment]
Скорее всего вы пулили именно за тела, а не за каталку

**Comment by Pivo24** [comment]
Никак не научитесь ctrl-кликать по самой каталке а не по пациенту на ней.
