### ISSUE TITLE
Не работает ПКМ на тайлы

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#3558]
#### Подробное описание проблемы
При попытке посмотреть, взаимодействовать с предметами в тайле через ПКМ (пкм чтобы посмотретьс писок всех предметов в тайле, с последуйщим взаимодействием), не происходит ничего, будто ты играешь за ИИ
#### Что должно было произойти
Открыться список предметов в тайле
#### Что произошло на самом деле
Ощущаешь себя ИИ без пкма
#### Как повторить
Не уверен что это у всех, но сказали люди жалуются, и у меня тоже самое
#### Дополнительная информация:
Это у хуманов, у призраков все нормально
Возможно связано с версией бийонда

**Comment by Belfogor** [comment]
Не уверен на все сто, но проблема дает о себе знать после подгрузки свалки. По крайней мере жалобы на пропажу ПКМа поступали сразу же после этого.

**Comment by DarkLevelSS13** [comment]
Эта херня привязана к кукле, это я точно могу сказать (У самого такая ситуация была).

**Comment by KIBORG04** [comment]
Думаю не актуально
