### ISSUE TITLE
Ползунки звука не работают

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#3560]
#### Подробное описание проблемы
Ползунки звука не работают когда на них нажимаешь.
#### Что должно было произойти
Должен выскакивать ползунок на котором можно регулировать громкость.
#### Что произошло на самом деле
Его не возникает.
#### Как повторить
Нажать на иконку динамика над игровым чатом

**Comment by SpaiR** [comment]
Сейчас в тестмерже находится ПР с новым подходом регулировки звука #3505 А кнопка звука в окне чата в скором времени удалится.
