### ISSUE TITLE
[Proposal] Противогазы СБ или хаулеры для ОБР

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#3564]
Людям не хватает хаулеров на ОБР. Это может быть либо противогаз СБ (на замену тем противогазам что находятся у канистры с воздухом на базе ОБР), либо хаулер, цепляющийся на ухо и кричащий "Halt! Security!". Шатаут вот этому человеку за идею на форуме - https://forum.taucetistation.org/u/admiral/summary

**Comment by Yaroslavppv** [comment]
Вроде как добавили уже #3886
