### ISSUE TITLE
Бинты не снимаются

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#3574]
#### Подробное описание проблемы
Нажимаю Remove Bandages - но ничего не происходит, даже в логах. Даже если пациента полностью раздеть.
#### Что должно было произойти
Бинты по хорошему должны сниматься.
#### Что произошло на самом деле
Ничего не произошло, даже в чате никакой реакции.
#### Как повторить
Надеть бинты на куклу и попытаться снять их с куклы.
#### Дополнительная информация:
@ZVee

**Comment by StrikS** [comment]
Нужны подробности такого случая ибо снимались и не раз. советую попробовать прерывать наложение бинтов, может это сыграло свою роль

**Comment by Lizurt** [comment]
Не удалось повтортиь баг.
![e7389631b46f3c99e3f3373bcca2e338](https://user-images.githubusercontent.com/42589308/59845113-39126e80-9365-11e9-8ca8-9088927ef4c1.gif)
(лог о том что я снимаю бинт тоже появляется)

**Comment by ViDLiathan** [comment]
Не знаю причин срабатывания, но это иногда случаетя.
Может дело в какой-то операции, дефибриляции или крио.

**Comment by Yaroslavppv** [comment]
Тоже на днях не мог снять, вроде после пересадки головы, но это не точно

**Comment by Motzord** [comment]
Добавьте возможность самому снимать бинты, например с рук или ног, иначе нереалистично
