### ISSUE TITLE
У бинтов потерялись спрайты.

### ISSUE THREAD

**Issue by JesusForRent** [TauCetiStation/TauCetiClassic#3580]
#### Подробное описание проблемы
У бинтов (Как улучшенных, так и обычных), заспавнившихся в аптечках, отсутствуют спрайты.

#### Что должно было произойти
У них должны были быть спрайты

#### Что произошло на самом деле
Спрайтов нет

#### Как повторить
Зайти на сервер и открыть аптечку

**Comment by Lafrien** [comment]
Не только у бинтов, а так же у мембран.
![Tau Ceti Station 2019-06-23 104424](https://user-images.githubusercontent.com/52122969/59973160-07d3b180-95a4-11e9-8103-5c1ffdc92719.png)
