### ISSUE TITLE
Настройки звука не работают

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#3582]
#### Подробное описание проблемы
Не работают и не сохраняются настройки звука (изменение громкость не влияет на звучание)

#### Что должно было произойти
Громкость звука должна меняться.

#### Что произошло на самом деле
Настройки звука не сохраняются, громкость звука не изменяется

#### Как повторить
Открыть настройки звука изменить значения, сохранить изменения.

#### Дополнительная информация:
Играю под вайном

**Comment by volas** [comment]
в чате сообщение есть какое-нибудь после нажатия save?

**Comment by Motzord** [comment]
> в чате сообщение есть какое-нибудь после нажатия save?

Есть,  что-то типо настройки сохранены.

На деле допустим настроить джукбокс на приемлемую для ушек громкость действительно невозможно

**Comment by Sakuya-Izayoi** [comment]
> в чате сообщение есть какое-нибудь после нажатия save?

Preferences saved, но последее время пишет только после кликов десяти. И настройки не меняются.
