### ISSUE TITLE
Нельзя прятаться под резиной чужих.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#3583]
#### Подробное описание проблемы
Дроны и фейсхаггеры (про лярв не знаю) не могут прятаться под резиной, даже если у них прожат Hide.
#### Что должно было произойти
Они должны.
#### Что произошло на самом деле
Они не.
#### Как повторить
Попробовать спрятаться.

**Comment by Lizurt** [comment]
Почему должны? Резина полностью покрывает турф, на котором находится, она сплошная. Если за ней кто то мог бы прятаться, это была бы имба. Раньше фейсхагеры могли прятаться под резиной. Это оказалось плохой фичей и ее выпилили.
У охотника есть часть этой фичи. Переключаясь на режим "Ходьба"(stalk), он может стать полупрозрачным. На фоне резинового пола его очень сложно заметить.

**Comment by Belfogor** [comment]
Не должны. Это был недочет, который был зафикшен.

**Comment by SpaiR** [comment]
Не баг
