### ISSUE TITLE
Эмоуты у алиенов при смерти.

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#3584]
#### Подробное описание проблемы
Когда алиен при смерти то он делает *gasp, однако такого эмоута нет и там пишется долгая штука про то что такого эмоута нет и посмотрите в *help

**Comment by Lizurt** [comment]
Спасибо за багрепорт, исправлю, ПР все еще в тестмерже. Хорошо что не оказалось такого бага который бы испортил весь ивент и крашнул сервер :pepe:
