### ISSUE TITLE
В логах дублируется OOC/LOOC 

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#3585]
#### Подробное описание проблемы
При просмотре логов замечаешь, что OOC/LOOC дублирует написанное игроками.
#### Что должно было произойти
Они не должны дублироваться.
#### Что произошло на самом деле
Дублируются, хотя относительно недавно всё было цело, а сейчас сломалей.
#### Как повторить
Откройте логи сервера и обратите внимание на OOC/LOOC
#### Дополнительная информация:
<img>https://prnt.sc/o5ugf4</img>

**Comment by SpaiR** [comment]
@Udokun LOOC точно дублируется?, На скрине вижу только OOC.
