### ISSUE TITLE
Добавить мусорным кучам возможность вонять и выпускать токсины в воздух вокруг себя [Proposal]

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#3586]
#### Подробное описание проблемы
Мусорщики очень любят герметизировать свою мусорку
#### Что должно было произойти
При герметизации и вдыхании этого мусора им должно стать хотя бы херово и пойти токсины
#### Что произошло на самом деле
копаем мусор без масок будто все в порядке

**Comment by Lizurt** [comment]
Лучше уж сделать невозможность сброса мусора при наличии хоть какого то давления

**Comment by Dominig12** [comment]
нет, лучше сделать невыносимую вонь и токсины, это даст стимул убирать мусор из техов

**Comment by FelixRuin** [comment]
угу
мусор
в космосе
после появления давления начал вонять
мне вот кажется что это не так должно работать
от чего токсины? от кучек прутьев?
вонь от чего? от закрытых пачек ролтона?
это что, будем ломать полностью свалочку? чтоб при заходе ты сразу начинал умирать? да?

**Comment by Dominig12** [comment]
ну, ты просто предстваь, на свалочке появится необходимость, внимание, таскать газовую маску с кислородом

**Comment by FelixRuin** [comment]
я про свалку которая на другом z уровне
и там найти маску не так просто
и смысл? просто чтоб сделать гадость?

**Comment by Dominig12** [comment]
а на свалке разве не суть в том, чтобы выжить? Маску довольно легко найти

**Comment by De-dawa-2** [comment]
оки доки попробуй найти на свалке одновременно маску и болон, притом они находятся в разных кучах а ищо тебе попутно надо найти перчатки (скрафтить)ботинки и одновременно с этим успеть не умереть от постоянно капающих токсинов, которые заставляют тебя делать throw up. удачи!!!!!

**Comment by Dominig12** [comment]
изначально спавн с балоном и маской!

**Comment by LudwigVonChesterfield** [comment]
Токсины в воздух - это про форон? Звучит смешно.

**Comment by Dominig12** [comment]
нет нет, именно токсины, (новый газ чтоли добавить)

**Comment by FelixRuin** [comment]
ой, конечно, конечно, давайте добавим новый газ, угу, А ПОТОМ ЧТОБ НА ВСЮ СТАНЦИЮ АГА, И ЧТОБ ТЕХА ТОЖЕ БЫЛИ В ЭТОМ УГУ УГУ

**Comment by LudwigVonChesterfield** [comment]
Работа атмостехам, уборщику, переработчикам.

**Comment by Leshiy-ART** [comment]
1) Почему это в ишью а не темой на форуме?
2) Изначальная идея создания проблем гермитизации мусорки на деле создаст гораздо больше проблем в техах станции и на свалке.
Нужно описать подробнее, что ты понимаешь под "вонью" в ССке и как избежать проблем для других мест.
