### ISSUE TITLE
[Proposal] Удолить отзывание шаттла при реве.

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#3589]
#### Подробное описание проблемы
Шатол отзывается вечно и если один из главрев ушел покушать и сидит в шкафу то раунд не закончится никогда. Если же главрева умер - то ролька передается другому реверу! И так до бесконечности, пока педаль не сжалится и не вызовет шатол, перед этим вырубив фейк-риколл (что к тому же не всегда может быть)

**Comment by Skippeer12** [comment]
Мне просто интересно для чего администрация присутствует на сервере, если она не следит за ситуацией и не решает проблемы?
А вообще там при педальном вызове шаттла там идет запрос о том нужно ли отключать фейк-реколл.

**Comment by OfficerSoftheart** [comment]
@Skippeer12 Педали банально не умеют в кнопки. Недавно лично наблюдал ситуацию как они пытались крутить время, вызывать шаттл снова, а я тридцать три раза писал порядок действий  в кнопках, чтобы нормально вызвать шаттл. В итоге не смогли, пришлось звать педалей других.

Теперь эти педали пишут топ пропозалы 😄

**Comment by ViDLiathan** [comment]
Для меня до сих пор остаётся загадкой, почему эта фича вообще была введена.
Реверам ведь даже наоборот ввгодно, чтоб все лоялисты свалили со станции.
