### ISSUE TITLE
Анробастные инженерные борги в космосе

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#3590]
#### Подробное описание проблемы
Инженерного борга невозможно заробастить выключенной дубинкой СБ

#### Что должно было произойти
При попытке избить борга выключенной дубинкой, борг должен получать урон и в конце концов помереть
#### Что произошло на самом деле
При попытке избить борга выключенным станбатаном ничего не происходит, в логах не выводится скрипты атаки/избиения, борг не получает урон и может безнаказанно тебя убить
#### Как повторить
Берем инженерного борга, риг СБ, щит и выключенную дубинку. Пытаемся избить дубинкой в космосе. Умираем от безысходности

#### Дополнительная информация:
Удалось ударить только один раз после 100500 кликов
![image](https://user-images.githubusercontent.com/45365635/60353330-1a961e00-99ca-11e9-89ca-7147f69c3672.png)

**Comment by Zmey25** [comment]
Топ багрепорты, не могу ежа жопой напугать, помогите
