### ISSUE TITLE
Зомби клав можно положить на операционный стол

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#3591]
#### Подробное описание проблемы
Зомби клав можно положить на операционный стол
#### Что должно было произойти
Нельзя.
#### Что произошло на самом деле
Можно
#### Как повторить
Зомби клав положить на операционный стол

**Comment by Lizurt** [comment]
К слову, их также можно бросать и тем самым в космосе можно передвигаться, бросая собственные руки :ok_hand:
