### ISSUE TITLE
Небольшое изменение худа

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#3597]
#### Подробное описание проблемы
Иконка СЕ почти неотличима с иконкой инженера на секхуде
#### Что должно было произойти
СЕ и обычный инженер должны отличаться по иконке без дополнительных раздумий
#### Что произошло на самом деле
>Несколько секунд вглядываешься в иконку, разглядываешь одежду, применяешь экзамайн, чтобы понять СЕ вскрывает дверь, потому что так надо или инженер охуел и творит беззаконие
#### Как повторить
Поиграйте за сбшника
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/45365635/60760180-67649f00-a031-11e9-8257-43ca5eec11d1.png)

**Comment by Garrysman232** [comment]
Чем СЕ взламывающий дверь отличается от обычного инженера? Кого можно побить батоном и огрести люлей от ХоСа, а кого нет? И тот и другой подчиняется законам и не имеет неприкосновенности.

**Comment by AndroBetel** [comment]
у се есть неприкосновенность так-то.

**Comment by Garrysman232** [comment]
> у се есть неприкосновенность так-то.
Все равно, если чето делает СЕ значит так надо, а если обычный инженер то он тритор, и сразу нужно его стукать как то неправильно, инженер как бы обслуживает станцию и по факту он делает как надо, подробности можно в любом случае узнать как от СЕ, так и у инженера, ведь это не какой то ассистент который ломает дверь и творит беззаконие
