### ISSUE TITLE
Синдиборга видно в списке мессенжеров ПДА.

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#3598]
#### Подробное описание проблемы
Синдиборга видно в списке контактов ПДА и ему можно (наверное) написать СМСку.
#### Что должно было произойти
Его там нет.
#### Что произошло на самом деле
Он там есть и там пишется что он синдикейт-робот
#### Как повторить
Купить синдиборга и посмотреть в список контактов ПДА.

**Comment by KuzyXD** [comment]
На локалочке купил за трейтора синдикиборга и засунул в него мой "игрок"-клиент. Его не видно в ПДА, его сообщения в message monitor-е пишутся как Unspecified. Разве что от киборга нельзя получить по ПДА сообщение, а он умеет писать.
