### ISSUE TITLE
[Proposal] Удалить из наушников общий канал радио

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#3623]
Предлагаю удалить дефолтный канал из наушников. Дело в том, что наличие наушника с общим каналом в который можно говорить в любой точке карты даже с завязанными руками очень сильно усложняет жизнь ролям, к тому же общий канал есть в интеркомах, которые есть в каждом в отделе, а для кооперации между отделами есть КПК и консоли запросов.

**Comment by igigin** [comment]
https://forum.taucetistation.org/t/topic/6808
Вот тут та же суть, но аргументы лучше.
