### ISSUE TITLE
Сломанная консоль R&D

### ISSUE THREAD

**Issue by Ambassadoing** [TauCetiStation/TauCetiClassic#3625]
#### Подробное описание проблемы
Сломалась консоль R&D
#### Что должно было произойти
Она должна была работать
#### Что произошло на самом деле
Она не работает
#### Как повторить
Потыкайтесь в неё, пока не сломается
#### Дополнительная информация:
![Сломалася консоль](https://user-images.githubusercontent.com/48314394/61280901-5ea66280-a7c1-11e9-800c-7c1f3c5bbcf4.png)

**Comment by Alexofp** [comment]
Шаги повторения желательно всё же подробнее писать, я потыкал всё работает. Сломалась консоль скорее всего когда протолат разобрали пока его меню открыто было, вроде починил
