### ISSUE TITLE
Science Goggles

### ISSUE THREAD

**Issue by KatoMarika** [TauCetiStation/TauCetiClassic#363]
#### Подробное описание проблемы
Не работает фильтр научных очков(Science Goggles)
#### Что должно было произойти
У НАС БЫЛО ДВА ВЕДРА ФИОЛЕТОВОЙ КРАСКИ НА ЭКРАН
#### Что произошло на самом деле
НЕ ФИОЛЕТОВО
#### Как повторить
Надеть очки

**Comment by Dennok** [comment]
Странно, вроде было фиолетово. При ивонте надевал.
