### ISSUE TITLE
Маги не могут в пушки

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#3633]
#### Подробное описание проблемы

Когда маг пытается стрелять из лазеров он не может.

#### Что должно было произойти

Маг, пусть и с недовольством, но должен был выстрелить.

#### Что произошло на самом деле

Ружье висит, а не стреляет.

#### Как повторить

Попробовать выстрелить за мага.

#### Дополнительная информация:

https://forum.taucetistation.org/t/zhaloba-vikineavtoritet/10576/3

**Comment by volas** [comment]
Не баг, а фича. И ты сам прекрасно знаешь.
