### ISSUE TITLE
[Proposal] (Мольба) Добавить игрокам краткое разъяснение о разнице между АХ и менторхелпом. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#3637]
#### Подробное описание проблемы
Игроки не понимают разницы между менторхелпом и АХ. Они часто путаются и пишут вопросы о механе педалям, а вопросы по части каких-то игровых моментов менторам. Нужно куда-нибудь БОЛЬШИМИ БУКВАМИ добавить разъяснение о принципиальной разнице между этими двумя чатами. ШПАСИТЕ

**Comment by FelixRuin** [comment]
А в какой момент это писать?

**Comment by Belfogor** [comment]
На каком-то из серверов, я видел подобное разъяснение по нажатию ф1. Там выводилось дополнительное диалоговое окно, где пояснялось нахуя и зачем пишут в ф1, и после тонны разъяснений игроку давалось окошко для своих каракуль. Но куда бы и кто решил бы не сунуть (если решит) то лучше куда-нибудь на видное место. Вот чтобы прямо каждый напоминало при нажатие ф1 или ф9 куда они пишут, и что туда писать совсем не надо.

**Comment by LudwigVonChesterfield** [comment]
Этот сервер - английские колониал марины(Как минимум там точно так), если кому нужно посмотреть.
