### ISSUE TITLE
Харвестеры культа считаются в статистике за экипаж

### ISSUE THREAD

**Issue by KuzyXD-zz** [TauCetiStation/TauCetiClassic#3641]
#### Подробное описание проблемы
Вызов Нар-Си, он конвертит всех тушек в харвестеров, которые после считаются за "выживший персонал".
#### Что должно было произойти
Харвестеры — не выжившие, а монстры.
#### Что произошло на самом деле
Харвестеров посчитало как за экипаж (?) и посчитало в статистике.
#### Как повторить
Культ
Харвестеры
Закончить раунд и проверить статистику

**Comment by KIBORG04** [comment]
У меня в культе харвестеры учитываются в статистике и я это называю ФИЧЕЙ. Все, да, не баг а фича, решено
