### ISSUE TITLE
Стал Гостом после нажатия на Ready

### ISSUE THREAD

**Issue by OneForm1488** [TauCetiStation/TauCetiClassic#3644]
#### Подробное описание проблемы
Начался новый раунд,после чего нажал кнопку Ready и появился в виде Госта.

#### Что должно было произойти
Респавн с профессией.

#### Что произошло на самом деле
Респавн за Госта.

#### Как повторить
Понятия не имею.

**Comment by TEXH4Pb** [comment]
Не "понятия не имею", а выбрать "Be assistant if preference unavailable" и не попасть на выбранную профу. Товарищ @Belfogor , вы опять всё сломали. Предполагаю, что дело в #3297.

**Comment by Belfogor** [comment]
Это отношение к моему Пру имеет столько же, сколько этот комментарий к проблеме. Серьезно, такая проблема существует давно. Игра иногда очень странно распределяет роли.
