### ISSUE TITLE
Построенные в ходе игры шлюзы не работают

### ISSUE THREAD

**Issue by Ambassadoing** [TauCetiStation/TauCetiClassic#3649]
#### Подробное описание проблемы
Не работают построенные в ходе раунда игроком шлюзы
#### Что должно было произойти
Они должны открываться.
#### Что произошло на самом деле
Они не открываются даже если игрок не настроил в плате уровень доступа.
#### Как повторить
Построить шлюз, настроить/не настроить плату шлюза, попробовать открыть.

**Comment by LudwigVonChesterfield** [comment]
По-дефолту в них стоит доступ "access_engine", если это баг - сейчас примусь фиксить.

**Comment by Belfogor** [comment]
Проверил, у меня тоже не получилось выставить доступ шлюзу.
