### ISSUE TITLE
Обход бана на обсервера за ИИ

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#366]
#### Подробное описание проблемы
При игре за ИИ можно ЛЕГКО обойти бан на госта/обсервера
#### Что должно было произойти
При активации действия "Wipe Core" игрока с баном на обсервера НЕ кидает в госты
#### Что произошло на самом деле
При активации действия "Wipe Core" игрока с баном на обсервера КИДАЕТ в госты
#### Как повторить
Нажать на "Wipe Core"
#### Дополнительная информация:
Спасибо Куршану за бан на обсервера! Без него мы бы не смогли обнаружить этот баг.

**Comment by igigin** [comment]
Специально убирал проверку бана с вайпкора, когда пилил их. Не помню зачем. Верну пожалуй.
