### ISSUE TITLE
Частный сыщик не имеет доступ к компьютеру в частном офисе.

### ISSUE THREAD

**Issue by Kyler2262** [TauCetiStation/TauCetiClassic#3676]
#### Подробное описание проблемы
Доступ к компьютеру в частном офисе имеет только детектив или криминалист.
#### Что должно было произойти
Частный детектив должен залогиниться в компе.
#### Что произошло на самом деле
Частный детектив не может залогиниться.
#### Как повторить
Подойти к компуктеру, нажать {Log In}, написать ишью.

**Comment by Motzord** [comment]
Пофикшено, щас туда имеет доступ любой

**Comment by KIBORG04** [comment]
О, это я фиксил когда начинал свой путь
