### ISSUE TITLE
Кравл позволяет уворачиваться от пуль. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#3682]
#### Подробное описание проблемы
Кравл  повзволяет как НЕО, только его обленившееся версия, лежа на жопе уворачиваться от пуль. Абузиться просто ужас. 

#### Что должно было произойти
Пуля должна была настигнуть моба. 

#### Что произошло на самом деле
Он ото всех увернулся. 

#### Как повторить
Нажмите кравл.

**Comment by Ambassadoing** [comment]
Не понял. То есть лежит кукла, в неё стреляют, а пули по ней не попадают? Так? Или же сначала стрельнули в куклу, а пока пуля летит - она упала?

**Comment by Belfogor** [comment]
Пуля просто пролетает над куклой и летит дальше.

**Comment by Ambassadoing** [comment]
А клик идёт ПРЯМО по кукле, так? Ну тогда чё, пришла эра ползучих Нео.

**Comment by SomeUselessGuy** [comment]
Если клик прямо по кукле - пуля попадет. Вообще - оружие нельзя держать, если лечь на пол, где тут абуз я не понимаю.
(О парамедиках и гражданских подумайте хоть)

**Comment by LudwigVonChesterfield** [comment]
Не зря вроде бы кричат "Ложись" когда стреляют, дядя Бельфогор...

**Comment by Motzord** [comment]
Фича, можно закрыть
