### ISSUE TITLE
Анализатор киборгов считает СПУ органиками

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#3683]
#### Подробное описание проблемы
ПРи попытке проанализировать СПУ с помощью анализатора киборгов он выдает сообщение о том, что целью является органик
#### Что должно было произойти
Должны были выдаться данные о повреждениях компонентов и температуре
#### Что произошло на самом деле
СПУ оказывается органик
#### Как повторить
Просканируйте умирающего от перегрева и повреждений СПУ
#### Дополнительная информация:
Раньше все было нормально
![image](https://user-images.githubusercontent.com/24685276/61987608-babe8180-b020-11e9-8046-220ebb5fcee1.png)

**Comment by Zmey25** [comment]
Новый ишью: игроки считают спу играбельными

**Comment by LudwigVonChesterfield** [comment]
А в каком месте это скажет?

**Comment by Dominig12** [comment]
> Новый ишью: игроки считают спу играбельными

![image](https://user-images.githubusercontent.com/24685276/61987580-8945b600-b020-11e9-9eed-2e33bc755ec9.png)
При нажатии анализатором на СПУ выводится это сообщение

**Comment by LudwigVonChesterfield** [comment]
Проблема из-за #3659, и там она уже пофикшена. Если пустят в мёрж, или обновят тест мёрж - можно закрывать.
