### ISSUE TITLE
ИИ слышит звуки щелчков клавиш

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#3684]
#### Подробное описание проблемы

ИИ который взаимодействует с консолью слышит щелчки клавиатурой.

#### Что должно было произойти

ИИ не должен.

#### Что произошло на самом деле

ИИ да.

#### Как повторить

быть ИИ
а
взаимодействовать с клавиатурой

#### Дополнительная информация:

Хакермен

**Comment by Lizurt** [comment]
Именно с консолью? Если с КПК, то это дубликат https://github.com/TauCetiStation/TauCetiClassic/issues/3516

**Comment by LudwigVonChesterfield** [comment]
Консолью, любой из.
