### ISSUE TITLE
[Proposal] Рандомизировать наследствие слизней

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#3693]
Предлагаю каждый раунд рандомизировать возможное потомство слизней (с некоторыми ограничениями офк чтобы нельзя было случанйо всех убить и не получить больше). Так будет намного сложнее получить имбовые экстракты (адамантиевый) и будет смысл проводить какие-то исследования, делать записи, отчёты и прочее.

**Comment by KuzyXD** [comment]
Если рандомизировать, то как ты представляешь эти записи и исследования?
