### ISSUE TITLE
Automated Grid Check не возвращает энергию в апц

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#370]
По завершению и паписанию сообщения Power Systems Nominal

Power has been restored to NSS Exodus. We apologize for the inconvenience.

Должны были все апц стать заряженными, но это не произошло.

**Comment by ZVee** [comment]
Тут скорее сообщение стоит поправить, а восстановление заряда понерфили давно, только педально если прожмут.
