### ISSUE TITLE
случайные структуры могут заспавниться очень близко друг к другу.

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#3705]
#### Подробное описание проблемы
Случайные космические структуры могут заспавниться на расстоянии экрана или двух целыми кластерами по три штуки.
#### Что должно было произойти
Мертвые корабли в разных концах вселенной.
#### Что произошло на самом деле
Мертвые корабли на расстоянии вытянутой руки друг от друга.
#### Как повторить
Посмотреть на структуры.
#### Дополнительная информация:
Случай, который я видел - телепорт, планетарий и второй Ghost Ship заспавнились в экране-двух друг от друга.

**Comment by LudwigVonChesterfield** [comment]
"случайные текстуры" на "случайные структуры" поменяй пожалуйста

**Comment by AndroBetel** [comment]
упс
