### ISSUE TITLE
Ошибка загрузки PDA 

### ISSUE THREAD

**Issue by T9IHT9IKJI9JI** [TauCetiStation/TauCetiClassic#3709]
![f9c57a61d4a73536bafe04451fb151b7](https://user-images.githubusercontent.com/33500393/62013469-b36fb300-b19b-11e9-9a29-df94eb1dd5eb.png)
 Подробное описание проблемы: Зашел в раунд за уборщика, сначала попытался открыть сканер загрязнений через PDA, но выскочило окно с ошибкой. Скрин прикрепил.

Как повторить: Понятия не имею

Дополнительная информация: Следующей попыткой было просто открыть ПДА, но он также начал выдавать эту ошибку. Возможно из-за того, что формально открылся сканер, но т.к. его вкладка выдавала эту ошибку, то и ПДА остался на этой вкладке, но выйти в предыдущее меню не получается.

**Comment by volas** [comment]
#3669
