### ISSUE TITLE
Госты

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#371]
#### Подробное описание проблемы
Госты могут привязывать хуманов к кроватям/каталкам/стульям
#### Что должно было произойти
Они не должны их привязывать
#### Что произошло на самом деле
Они могут
#### Как повторить
Взять госта и перетащать спрайт хумана на кровать/каталку/стуло

**Comment by Dennok** [comment]
И отвязывать тоже могут.

**Comment by dearprincesscelestia** [comment]
Они еще и крутить стулья могут.

**Comment by MorCrate** [comment]
> Они ещё и крутить стулья могут.

Это фича же. Очень старая.

**Comment by Dennok** [comment]
>Они еще и крутить стулья могут.
Это великая фича

**Comment by dearprincesscelestia** [comment]
Фашисты!
