### ISSUE TITLE
Офицеры-вардены 

### ISSUE THREAD

**Issue by Thirteenalex** [TauCetiStation/TauCetiClassic#3715]
#### Подробное описание проблемы
У офицеров при стандартном доступе есть возможность зайти в армори к леталу
#### Что должно было произойти
Их не должно пустить
#### Что произошло на самом деле
Их пускает
#### Как повторить
Зайти офицером в летальную оружейку со стороны обычной
#### Дополнительная информация:
Возможно надо провести проверку остальных доступов

**Comment by GreyGunner** [comment]
Проверка показала, что на шлюзе вообще доступ для всех
