### ISSUE TITLE
Свет в глаза лишает зрения

### ISSUE THREAD

**Issue by KuzyXD-zz** [TauCetiStation/TauCetiClassic#3721]
#### Подробное описание проблемы
Если много раз лампой тыкать в глаза игроку, то в итоге будет чисто белый экран.
#### Что должно было произойти
Должно было откатиться и вернуть зрение.
#### Что произошло на самом деле
Зрение пропало совершенно, белая пелена. Перезаход лечит.
#### Как повторить
Взять лампу и посветить на хелпе в глаза игроку несколько раз подряд.

**Comment by OfficerSoftheart** [comment]
Старый баг, рабочий, казалось уже было ишшью. Ну и да, еще можно схожим образом рандомно, получить иммунитет к ослеплению.

**Comment by Zmey25** [comment]
Фича
