### ISSUE TITLE
[Proposal] Вывести переписку ПДА на бумаге

### ISSUE THREAD

**Issue by KuzyXD-zz** [TauCetiStation/TauCetiClassic#3723]
Создать кнопку "Распечатать", чтобы можно было к делу прикреплять.

**Comment by OfficerSoftheart** [comment]
@KuzyXD если и делать, то добавить отдельным картриджем данное. Вставляешь картридж, бумагу, и печатаешь из КПК.

**Comment by ext9z3** [comment]
Клёвая идея, я вообще за расширение функционала ПДА.
Пусть кодеры вообще форум таусети, как встроенную функцию, приплетут.
