### ISSUE TITLE
[proposal] поднять время для ролей

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#3729]
#### Подробное описание проблемы
куча новичков которые не умеют менять руки выставляют себе префы и не умеют менять руки уже на блобе/генке/триторе/нюке
#### Что должно было произойти
крутые роли экшен крутой ролевой отыгрыш хорошие ощущения от игры.
#### Что произошло на самом деле
блоб умер на десятой минуте раунда.

**Comment by Pivo24** [comment]
По другому новички за роль играть не научатся. Кнопок не пощупают, в ролеплей не попробуют.

**Comment by ext9z3** [comment]
> 
> 
> По другому новички за роль играть не научатся. Кнопок не пощупают, в ролеплей не попробуют.

Пусть хотя-бы базовому механу научатся, а потом уже пусть пробуют что хотят

**Comment by Zmey25** [comment]
Так они и не хотят учиться. Всякие малфы, которые "ололо гайд на читал и вообще за ии первый раз зашёл". Абдукторы, которые "ниче не понятно, лол, херня какая-то".(привет мистер_хелпер). При этом страдают коллеги по роли. 

Можно для отдельных ролей, вроде триторов оставить маленькое время, где роль вроде есть, а вроде и нет. И не страшно, если человек не читая гайд полезет на роль.
