### ISSUE TITLE
[Proposal] Держим оружие в двух руках

### ISSUE THREAD

**Issue by Artik12344** [TauCetiStation/TauCetiClassic#3736]
#### Подробное описание проблемы
Куколки держат тяжёлое оружие по типу Лазерных винтовок в одной руке
#### Что должно было произойти
Они должны держать такое оружие в двух руках
#### Что произошло на самом деле
Куколки держат тяжёлое оружие по типу Лазерных винтовок в одной руке
#### Как повторить
Взять тяжёлое оружие по типу Лазерной винтовки в руки

**Comment by FelixRuin** [comment]
Принято, займусь, ну лучше чиркани ещё что надо именно чтоб было двуручным онли

**Comment by megaomega005** [comment]
звоните срайтерам нужны срайты

**Comment by FelixRuin** [comment]
а хотя знаете, ну его эти ваши двуручники

**Comment by Artik12344** [comment]
Ты че... Ленивец мля

**Comment by WatlerJe** [comment]
Эта фича нужна больше для огнестрельного оружия, чем для лазерного.
Корпус лазерного оружия выполняется преимущественно из алюминия и пластика. Учитывая то, что там нету подвижных частей, то соответственно нету отдачи как у огнестрельного оружия. Массивными элементами являются ствол и съемный/несъемный аккумулятор, но и они не достаточно тяжелые чтобы заставлять стрелка носить оружие в двух руках.

**Comment by Motzord** [comment]
> Принято, займусь, ну лучше чиркани ещё что надо именно чтоб было двуручным онли

Дробовики (все вариации)
Автоматы/калаши нюки (туда же базуку, а то одной рукой стреляем, второй заряжаем)
Laser cannon (Усиленная большая версия винтовки, по любому будет значительно тяжелее и массивнее)
Tesla Gun
Температурная пушка (Не уверен надо ли...)

**Comment by Motzord** [comment]
А, еще револьвер. (Он руки/ноги отрывает, отдача должна быть внушительной)

**Comment by Artik12344** [comment]
Вообще то это предложение только по спрайту, а не по принципу двойного энерго-меча...

**Comment by Motzord** [comment]
Если заспрайтить две руки на одной пушке, то что будет, когда кукла возьмет по винтовке в каждую руку?

**Comment by Artik12344** [comment]
Как на инфинити - по оружию в каждой руке
