### ISSUE TITLE
Варден, Я руки не чувствую! Или как вытаскивать магазины будучи инвалидом

### ISSUE THREAD

**Issue by ghost** [TauCetiStation/TauCetiClassic#374]
#### Подробное описание проблемы

Если у хумана осталась одна рука, это не помешает ему вытащить рукой, которой нет, магазин из винтовки/пистолета/etc.
#### Что должно было произойти

Магазин из винтовки должен упасть на пол/ Остаться в оружии.
#### Что произошло на самом деле

Магазин из винтовки появился в руке, которой нет на самом деле.
#### Как повторить

Отрубить кукле руку, взять автоматическое оружие, вытащить магазин из него.
#### Дополнительная информация:

![image](https://cloud.githubusercontent.com/assets/20542000/17147889/8b0e5ff4-5386-11e6-8f1b-5241a57cb9ce.png)

**Comment by MorCrate** [comment]
Чисто технически это возможно же. ОЧЕНЬ неудобно, но возможно.

**Comment by Dennok** [comment]
Не так уж и очень. Я видел видео где чел зажимал оружие меж ног и перезаряжал его 1й рукой.

**Comment by Skyrull** [comment]
но магазин остается в отрубленной руке

**Comment by Dennok** [comment]
>но магазин остается в отрубленной руке
Но это да, бага

**Comment by TheBlackTree** [comment]
Вытащить магазин без руки - можно. Но взять магазин в отсутствующую кисть - нет.

**Comment by KuzyXD** [comment]
Нет.
