### ISSUE TITLE
[proposal] Добавить логирование пуллу. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#3742]
#### Подробное описание проблемы
Пулл объектов не оставляет никаких следов. 

#### Что должно было произойти
Должно было хотя бы оставить какую-нибудь пометку у пуллящегося объекта, и у моба пуллящего объект

#### Что произошло на самом деле
Нихуя. Вещи двигаются без какого либо следа

#### Дополнительная информация:
Это бы сильно облегчило жизнь администраторам

**Comment by Garrysman232** [comment]
Миллион лет этим пользуются чтобы не оставлять следов для педалей, и только сейчас кто-то решил что стоит внести

Прогресс

**Comment by Belfogor** [comment]
Не актуально в связи с появлением реплеев.
