### ISSUE TITLE
Старнности с выбором персонажа и его спавном.

### ISSUE THREAD

**Issue by OfGreyBugWaifu** [TauCetiStation/TauCetiClassic#375]
#### Подробное описание проблемы
Проблема странная и объясню пошагово.
1. Я захожу в сетапчеректер и выбираю персонажа из своих слотов (7 слотов, например). Я просто кликаю на персонажа в списке и закрываю окно.
2. Я деклерюсь и жду начала раунда.
3. Меня спавнит, но другим персонажем из моего списка. 
Например, когда я задеклерен Анной Бродвин (из списка), меня спавнит Форсеном Снюсом (тоже из моего списка персонажей).
#### Что должно было произойти
Меня должно было заспавнить выбранным персонажем.
#### Что произошло на самом деле
Меня спавнит случайным персонажем из моего списка персонажей.
#### Как повторить
Не имею понятия.

**Comment by ZVee** [comment]
Думаю что ты просто включил опцию "заход случайным персонажем из моих сохраненных". Где эта кнопка - я не помню, может сам найдешь, может подскажет кто.

**Comment by Dennok** [comment]
Я думаю он не сохранил выбор, так как то просто загружает пресет но не сохраняет его как текущий.
