### ISSUE TITLE
[proposal] Как насчёт сделать возможным вытаскивать карточку из ПДА на Alt ?

### ISSUE THREAD

**Issue by firstghost** [TauCetiStation/TauCetiClassic#3750]
#### Подробное описание проблемы
На других билдах, насколько я знаю, если карточка лежит в ПДА и по этому самому ПДА кликнуть с Alt-ом, то карточка даётся тебе в руки. Это бывает очень удобно, так как в некоторых случаях для авторизации требуется "провести картой".

#### Что должно было произойти
Карточка в руках, при нажатии на ПДА с клавишей "Alt".
#### Что произошло на самом деле
Ничего, а жаль

**Comment by FelixRuin** [comment]
да куда вы всё время торопитесь
через вкладку
через правую кнопку
теперь ещё через альт хотите

**Comment by UDaV73rus** [comment]
На стрелочках не ходят, руки на End не меняют. Торопятся куда-то
