### ISSUE TITLE
Отсутствие иконки речи

### ISSUE THREAD

**Issue by abnormalsoundofficial** [TauCetiStation/TauCetiClassic#3753]
#### Подробное описание проблемы
Во время нажатия F3 (или T по хоткеям), когда игрок пишет текст - отсутствует анимированная иконка слева сверху над персонажем, обозначающая то, что данный персонаж "говорит". Когда игрок отправляет сообщение - неанимированная иконка появляется, но только после отправки текста сообщения команды "say" через F3
#### Что должно было произойти
Игрок нажимает F3 -> пишет сообщение -> **пока игрок пишет сообщение - в левом верхнем углу на тайле персонажа появляется анимированное прямоугольное "облако речи" (анимацией является последовательное появление троеточия, от одной точки до трёх, дальше по циклу), обозначающее то, что ПЕРСОНАЖ ГОВОРИТ (игрок пишет текст)** -> игрок отправляет сообщение -> в левом верхнем углу на тайле персонажа появляется неанимированное прямоугольное "облако речи", обозначающее то, что персонаж "сказал".
#### Что произошло на самом деле
Игрок нажимает F3 -> пишет сообщение -> **никакого "облака речи" нет** -> игрок отправляет сообщение -> в левом верхнем углу на тайле персонажа появляется неанимированное прямоугольное "облако речи", обозначающее то, что персонаж "сказал".
#### Как повторить
Нажимаем F3 - пишем сообщение, но не отправляем. На персонаже наблюдаем отсутствие анимированного облачка.
#### Дополнительная информация:
05.08.19 всё было в порядке. Скорее всего баг появился при обновлении от того-же 05.08.19, потому что 06.08.19 проблема и появилась.

**Comment by LudwigVonChesterfield** [comment]
#3752
