### ISSUE TITLE
Нет спрайта у cyborg suit

### ISSUE THREAD

**Issue by Ydaater** [TauCetiStation/TauCetiClassic#3756]
#### Подробное описание проблемы
Нету спрайта у костюма cyborg suit
#### Что должно было произойти
При одевании костюма, я должен был его видеть на себе.
#### Что произошло на самом деле
Я одел костюм, а вместо него появилась плашка над головой

#### Как повторить
Надеть cyborg suit
#### Дополнительная информация:
![изображение](https://user-images.githubusercontent.com/21292885/62537386-f6472000-b858-11e9-8ee3-b26a1c708558.png)
![изображение](https://user-images.githubusercontent.com/21292885/62537419-052dd280-b859-11e9-9b18-771fed895c1a.png)
![изображение](https://user-images.githubusercontent.com/21292885/62537426-08c15980-b859-11e9-9485-27023f843c82.png)

**Comment by 4310V343k** [comment]
А можно лейбл Sprite Needs? Не нашёл нужного спрайта в билде

**Comment by Deahaka** [comment]
Это кстати можно уже закрыть.

**Comment by KIBORG04** [comment]
Пруф?

**Comment by Deahaka** [comment]
А, ой, это какой-то другой киборг сюит наверное. Который из картона имеет спрайт и после надевания шлема тоже
