### ISSUE TITLE
Броня детсада становится тёплой в открытом космосе

### ISSUE THREAD

**Issue by Snailcat** [TauCetiStation/TauCetiClassic#3757]
#### Подробное описание проблемы
Броня детсада не держит космическую радиацию.
#### Что должно было произойти
Броня детсада, как и броня Капитана. Должна держать космическую радиацию.
#### Что произошло на самом деле
При выходе детсадовца в открытый космос. Он начинает получать радиэшн демедж.
#### Как повторить
Выйти в открытый космос в риге детсада.

**Comment by WallShrabnic** [comment]
Она и не должна держать радиацию, как её не должна держать броня капитана
