### ISSUE TITLE
[Proposal] Почему из слипера одиссея нельзя выйти?!

### ISSUE THREAD

**Issue by Kyler2262** [TauCetiStation/TauCetiClassic#3762]
#### Подробное описание проблемы
 Из слипера Одиссея нельзя вылезти. Одиссей пиздит грифонир и выводит кого-либо из раунда.
#### Что должно было произойти
Из слипера можно выйти и избежать грифона.
#### Что произошло на самом деле
Нас засовывают в одиссей и мы не можем съебироваца.
#### Как повторить
Найти грифонира, дать слипер.

**Comment by Artik12344** [comment]
Автор точно-точно не горит от того что в только что прошедшем раунде его убили слипером и не решил сделать это предложение просто чтобы насолить людям которые хотят убивать слипером

**Comment by Kyler2262** [comment]
Ты прав, я горю. И в будущем кто-то ещё будет гореть из-за этой херни. И поэтому я просто предлагаю хоть как-нибудь нёрфануть это. 

Кстати, почему тогда обычный слипер в медбее не кидает в слип?

**Comment by Artik12344** [comment]
А разве в обычном слиппере человек становится бессмертным? А разве в слиппере Одиссея есть возможность вкалывать людям вещества?

**Comment by Ambassadoing** [comment]
>А разве в слиппере Одиссея есть возможность вкалывать людям вещества?
ЧСХ если у Одиссея также имеется шприцемёт с настроенным производством реагентов, то они вкалываются кукле в слипере.
Алсо против грифонящих клоунов имеется блокирование по ДНК или уровню доступа. Не заблокировали? Пеняйте на себя.

**Comment by ViDLiathan** [comment]
Те, кто блокирует гражданские мехи по ДНК попадают в особое место в аду.

Ну а мехам давно нужно возможность нормальной удаленной блокировки добавить и извлечения пилота и пассажиров без уничтожения.
