### ISSUE TITLE
[Proposal] Добавить возможности установки чипа лояльности в СЕТАП ХАРАКТЕРЕ

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#3763]
#### Подробное описание проблемы
Добавить галочку Cheap of Loyality Yes/No, где NO будет по дефолту.

**Comment by Artik12344** [comment]
А на первое апреля yes нельзя будет поменять на no

**Comment by LudwigVonChesterfield** [comment]
Я думал нельзя имплантировать всех направо и налево во время ревы потому-что это дорогое устройство и или потому-что он иногда сжигает мозги но ладно похоже при том при всём каждый первый может его получить...

**Comment by Miracler112** [comment]
Но ведь есть такая фича, как лояльность без чипа лояльности.. В настройках персонажа её можно будет поставить себе и тебя в реву никаким боком нельзя будет пригласить, ведь ты полностью лоялен НТ, естественно это нужно будет отыгрывать и самому, ибо это никак не покажет на худах
