### ISSUE TITLE
[Proposal] Добавление внутриигровой отсечки обхода джоббана путём назначения через главу персонала

### ISSUE THREAD

**Issue by LtSaavik** [TauCetiStation/TauCetiClassic#3778]
#### Подробное описание проблемы
В данный момент - и я сталкивался с этим в игре - игроки, имеющие джоббан на некоторую должность могут зайти в игру на другой (чаще всего - ассистентом из этого же департамента), и потом подойти к главе персонала с просьбой оформить их на забаненную должность.
В каких-то случаях возникали проблемы - когда ты точно знаешь, что у человека джоббан, но не можешь это обосновать IC. В других же - ты просто не знаешь и игрок получает то, что получать не должен.

Предложение такое: сделать видимым для Главы Персонала то, что у игрока джоббан.
Вариантов как это сделать лично у меня несколько:

**1. "Ролеплейный".**
Информация о проступке записывается в "Employement Notes" всех персонажей игрока без возможности редактирования, перед "ручными" записями...
    а) В виде просто запрета на работу:
> It is forbidden to hold positions [...] in the [...] department by Nanotrasen HR.
   
 б) В виде переноса комментария администратора, выдавшего джоббан (минус: не всегда вписывается в IC, плюс: возможность более корректного отказа с объяснением причин).

Для просмотра данных записей главе персонала надо будет открывать консоль Employment Records (справа от Identification Computer в кабинете ГП). 

_Плюсы_: 
- Используется неиспользуемый практически ныне функционал "трудовых записей".

_Минусы_: 
- Увеличит время выдачи должности желающим смены оной. 
- Не все ГП пользуются данной консолью (решается обязанностью, прописанной на вики). 
- Не понятно сразу, можно ли и нельзя ли выдавать должность, без отвлечения на Employment Records.

**2. "Механный".**
В  Identification Computer при вставлении карты персонажа игрока с джоббаном затеняются заджоббаненные должности без возможности их выбора (аналогично тому, как это выполнено в меню "Occupation"/"Join game" стартовой формы.

_Плюсы_: 
- Наглядность и быстрота. Вердикт выносится сразу при работе с картой.

_Минусы_:
- Отсутствие мотивации отказа.

_Нейтральное_ (имеет как положительную сторону отыгрыша коррумпированности, так и отрицательную сторону обхода фактического наказания за нарушения правил сервера):
- Возможен обход данной проблемы путём подкупа Главы Персонала с выдачей либо карты-дубликата, либо "кастомной" должности с требуемыми доступами.

**3. Смешанный.**
Одновременное сочетание двух вышеописанных способов - и добавление в Employment Records персонажа игрока записи о запрете на должность от лица NT HR любым из способов, и затенение в Identification Computer запрещённых должностей.

_Плюсы_:
- Наглядность и быстрота. Сразу после использования карты игрока видно, что есть проблемы и следует обратиться к трудовым записям - не заметить будет невозможно.
- Наличие мотивированного отказа с отсылкой к высшему руководству.
Не будет отказов по причине "потому что ээээ мээээ".
Открываются возможности как для отправления жалобы через АВД/ГП посредством факса, так и к коррупции описанным выше способом.
- Использование практически неиспользуемых ныне трудовых записей войдёт в привычку Глав Персонала, что, возможно, подстегнёт и игроков заполнять "Employement Notes" своих персонажей, потому что чаще всего сейчас их просто не читают - а зачем заполнять то, что никто никогда не прочтёт?

_Минусы_:
- Увеличение времени обработки заявки на смену должности. 
Но не такое большое, как в случае первого варианта, где требуется проверять каждую запись - тут будет проверка только в случае наличия фактического запрета в  Identification Computer, т.е., индивидуальная работа.

#### Что должно было произойти
Глава персонала не может назначить должность игроку с джоббаном на неё.
#### Что произошло на самом деле
Игроки обходят джоббан путём назначения у главы персонала, пользуясь отсутствием у него информации об этом.
#### Как повторить
Получить джоббан и сменить должность на забаненную у ГП.
#### Дополнительная информация:
Очень неплохой, как по мне, "пинок" в сторону отыгрыша и возможность превентивной отсечки обхода джоббанов.

**Comment by Artik12344** [comment]
1. Заплатить ХоПу чтобы он не смотря на запрет выдал должность
2. Заплатить ХоПу который возьмёт ничейную карту(у него там целая коробка) и сделает её под твоё имя и новую должность на которую выдали джоббан

**Comment by LtSaavik** [comment]
> 1. Заплатить ХоПу чтобы он не смотря на запрет выдал должность
> 2. Заплатить ХоПу который возьмёт ничейную карту(у него там целая коробка) и сделает её под твоё имя и новую должность на которую выдали джоббан

Я вроде это даже и написал в самом ишью? ;)
Вот только ГП должен будет крепко задуматься перед тем, как это делать - ведь это будет нарушение правил сервера, что неплохо так имитирует ответственность перед вышестоящим начальством. 
Ну а сама коррупция при актуальном игровом отсутствии понимания ценности денег будет очень неплохим подспорьем к увеличению этого понимания.

**Comment by Motzord** [comment]
Считаю отличной идеей, так как
а) Ролеплейно и идет хоть какое-то взаимодействие с прошедшими и настоящими раундами
б) Педально, ибо теперь админы могут не беспокоится за обход джобки через хопа
в) Справедливо.
