### ISSUE TITLE
Отсутствие дронов в unban panel

### ISSUE THREAD

**Issue by ghost** [TauCetiStation/TauCetiClassic#3781]
#### Подробное описание проблемы

В Unban panel отсутствует должность Maintenance drone из за чего невозможно заджобанить эту роль ливнувшему из раунда игроку.

#### Что должно было произойти
В unban panel должна присутствовать должность Maintenance drone

#### Что произошло на самом деле

Ее там нет

#### Как повторить

Попробовать забанить должность Maintenance drone через Unban panel

**Comment by Momsek** [comment]
Не баг. Дрон привязан к ИИ и боргу. Забанишь одно - другое тоже.

**Comment by Dwagdore** [comment]
#9882 Закрывайте ишшуй

**Comment by TEXH4Pb** [comment]
@KIBORG04 это можно закрывать
