### ISSUE TITLE
Сломанный клинер.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#3784]
#### Подробное описание проблемы
Клинером невозможно пшикать на стоящих людей - струя уходит в сторону.
Клинер через раз чистит руки от крови, хоть они в перчатках, хоть нет. Может повезти и ладошки будут чистые, может не повезти - они будут грязные.
#### Что должно было произойти
Струя должна идти на человека.
Ладошки должны быть чистые.
#### Что произошло на самом деле
Смотреть выше.
#### Как повторить
Попрыскать на стоячего.
Попрыскать на кровавые руки.
#### Дополнительная информация:
Скрины потерялись :(
(слапы так же работают?)
@LudwigVonChesterfield

**Comment by LudwigVonChesterfield** [comment]
#3708

**Comment by LudwigVonChesterfield** [comment]
Эта проблема была исключительно из-за ПР-а про огнетушитель.
