### ISSUE TITLE
форонщик, как отдельная профа [Proposal]

### ISSUE THREAD

**Issue by Wozzy09** [TauCetiStation/TauCetiClassic#3785]
#### Подробное описание проблемы
профа форонщика занимает слоты ученых
#### Что должно было произойти
форонщик НЕ занимает слоты ученых
#### Что произошло на самом деле
АААА. форонщик занимает слоты ученых
#### Как повторить
-_-
#### Дополнительная информация:
не очень классно, когда хочется поиграть ученым, но местные слоты уже заняты из которых два  форонщика и одним ученым. Необходмо запилить ее(профу форонщиков) как отдельную профу.

**Comment by WallShrabnic** [comment]
Профу фооонщика уже давно пора выпилить. Бесполезнее профессии на станции найти сложнт

**Comment by megaomega005** [comment]
Шрубник считает что они полностью юзлессные, несмотря на добавленный им механ с получением очков за радиус взрыва лимитки от АлексаФП 
Шрубник сказал- вы выпилили
За работу
