### ISSUE TITLE
броня игнорирует телескопик на хелпе

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#3796]
#### Подробное описание проблемы
если на человеке есть любой костюм - то телескоп на хелпе его не пробьет
#### Что должно было произойти
хоть что-то
#### Что произошло на самом деле
ничего

**Comment by Miracler112** [comment]
Я проверял не один раз и не один костюм, всё ведь проходило нормально и так, как должно. С каким конкретно костюмами там проблемы были?

**Comment by AndroBetel** [comment]
только что проверил на халате, хазард-весте и тех унатховских обносках. нет, пробивает.
