### ISSUE TITLE
Генерация структур друг в друге

### ISSUE THREAD

**Issue by Miracler112** [TauCetiStation/TauCetiClassic#3803]
#### Подробное описание проблемы

Случайные структуры сгенерировались друг в друге

#### Что должно было произойти

Они не должны быть друг в друге

#### Что произошло на самом деле

Они друг в друге

#### Как повторить

Помолится рандому

#### Дополнительная информация:
![Oh my](https://user-images.githubusercontent.com/21056879/62975677-984fa500-be23-11e9-9eb2-c151ca7959ed.jpg)

**Comment by Alexofp** [comment]
ужас я же чинил...

**Comment by Miracler112** [comment]
Ну вот оно как-то всё равно вылезло

**Comment by Dominig12** [comment]
еще вот пример
![scrnshot1](https://user-images.githubusercontent.com/24685276/63205322-710b0900-c0ab-11e9-8a6f-061c78d62483.png)
