### ISSUE TITLE
Красный код=полный доступ офицерам и главам [Proposal]

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#3805]
Собственно поиграв за глав и СБ достаточное количество времени, я уперся в одну неприятную нехватку, а именно — полный доступ в красный код.
Рассмотрим со стороны СБ:
Ожидание:
Красный код — СБ имеет право вламываться в отсеки и арестовывать всех, кого посчитает нужным.
Реальность:
Красный код — СБ не может вламываться в отсеки и лишь злобно пиликать шлюзами или выбивать стекла.

Рассмотрим со стороны глав:
ГП: 
Занят раздачей полных доступов офицерам, а позже и их отбиранием
ГСБ: Не может вломится в нужный отсек, если ГП не поднимет доступ
СМО: Не может сбежать куда-либо, спрятаться в капитанской.
РД, СЕ — аналогично.

Плюсы: Главы при красном коде смогут сбежать в относительно безопасное место (Мостик не самое безопасное место)
СБ сможет вламываться в отсеки и задерживать антагов.

Минусы: Если в красный код кто-то украдет у офицера карточку (aka снимет с трупа) то он получит полный доступ пока код не понизят.

Аргументы за:
Со стороны СБ:
Удобнее воевать с нюкой, ревой и прочим.
Если оружейку не открыли, отроют сами
[Пишите дальше сами]

Аргументы против.

СБ-татор, главы-таторы могут поднять код и залутать все что только им нужно (или еще хуже — спровоцировать поднятие кода)

Залутав карточку СБ в красный код можно получить полный доступ.

Дискасс, ребятки

**Comment by Ambassadoing** [comment]
Идея херь, у щитсеков и так много поблажек в красный код, так ты им ещё и фулаксесс дать хочешь.

**Comment by LtSaavik** [comment]
> ты им ещё и фулаксесс дать хочешь.

Причём, который они и так ингейм спокойно могут получить от ГП/капитана. Уж при красном-то коде точно.

**Comment by Motzord** [comment]
> > ты им ещё и фулаксесс дать хочешь.
> 
> Причём, который они и так ингейм спокойно могут получить от ГП/капитана. Уж при красном-то коде точно.
ГП и прочие главы вместо выдавания красного кода предпочитают сдохнуть в главном коридоре от нюки/ревы/разгермы, тем самым СБ вынуждено плакать и молится, чтобы ИИ открыл оружейку, если ИИ вообще есть.

СБ на станции создано именно для подавления всех саботирующих работу, а  красный код это боевое положение, позволяющее восстановить порядок на станции применением грубой силы.

Так пусть красный код будет действительно красным и пусть СБ будет фашиствовать во имя нанотрейзен, СОПа и произвола глав.

**Comment by rarytech** [comment]
Кажется, если главы предпочитают сдохнуть в разгерме, то это безответственность либо невезение игроков на главах и, как следствие, их персонажей, а не недостаток игровой механики.

**Comment by EdlerN** [comment]
Я уже молчу про то что лутаная карта офицера становится фулакусом.

**Comment by Motzord** [comment]
Я уже говорил об этом в описании.
Однако фулакус позволяет офицерам в красный код нормально фашиствовать, как и надо. Вламываться в отсеки, ловить магов в капитанской, избивать реверов из каргостана дубинками.

(Статистика британских ученых доказывает, что большинство битв за каргонию проигрывается офицерами по причине нехватки доступа. Также обращаю внимание, что пока офицеры бегают к ГП за  доступом, карго основательно баррикадируется и заказывает пушечки)

**Comment by Motzord** [comment]
В принципе есть два (три) варианта.
1) При повышение красного кода, фулакус автоматически выдается офицерам и главам.
При снижении, код также пропадает
2) при повышении до красного кода, двое глав тыкают в KAD кнопочки ответственные за фуллацесс. 
При понижении главы опять же тыкают в KAD и обрубают всем фуллацесс.
3) Никто ничего не делает, кодить никто не будет

**Comment by Motzord** [comment]
> Я уже молчу про то что лутаная карта офицера становится фулакусом.

Лутанная карта капитана/Яна/хопа тоже становится фулакусом, так что может у них тоже отберем?

**Comment by AndroBetel** [comment]
капитана и хопа два человека на станции и они не должны идти воевать.

**Comment by Motzord** [comment]
> капитана и хопа два человека на станции и они не должны идти воевать.

Во время нюки капитан и хоп либо ссыкливо нычутся на мостике, и никаких доступов от них не жди, либо самозабвенно погибают в борьбе с захватчиками. Тоже самое при реве. (И прожать кнопку у себя в кабинете намного проще чем раздавать и без того занятым войной офицерам, немного глупо.

На станции захватчики
@ 
Вместо того, чтобы воевать, создаем очередь в хопской и просим полный доступ
@ 
ГП и капитан уехали на астероид, воюйте без доступа.

**Comment by LtSaavik** [comment]
> На станции захватчики
> @
> Вместо того, чтобы воевать, создаем очередь в хопской и просим полный доступ
> @
> ГП и капитан уехали на астероид, воюйте без доступа.

Если офитсерам нужен фулахух для захватчиков - значит, они (захватчики) где-то в жопе станции и время на выдачу есть.
Если же надо воевать здесь и сейчас - то для главного коридора и ЕВЫ полный доступ не нужен.

> Во время нюки капитан и хоп либо ссыкливо нычутся на мостике, и никаких доступов от них не жди, либо самозабвенно погибают в борьбе с захватчиками. Тоже самое при реве.

Значит, надо таким главам (воюющим) джобку на глав. С невоюющими сложнее (не вижу причин главе персонала НЕ забиться на мостике от страха) - но до них офицеры уже добраться-достучаться могут.

**Comment by Motzord** [comment]
А может чтобы ГП опять же не сидел и не щелкал в критической ситуации по кнопочкам, формируя очередь из офицеров добавить в консольку кнопку Full acess officer security?

Ничего сложного, зато любой глава забившийся на мостике, может сделать в критической ситуации из остатков СБ вундервафлю с фуллацесом

**Comment by Ambassadoing** [comment]
Такая кнопочка уже есть, называется должность CAPTAIN. Правда если критическая ситуация разрешается, то таких капитанов остаётся человек шесть-семь и дай бог хотя бы кто-то из них сам, без лишних пендалей, пойдёт и сдаст доступ.

**Comment by Motzord** [comment]
> Такая кнопочка уже есть, называется должность CAPTAIN. Правда если критическая ситуация разрешается, то таких капитанов остаётся человек шесть-семь и дай бог хотя бы кто-то из них сам, без лишних пендалей, пойдёт и сдаст доступ.

Но благодаря моему предложению офицерский фуллацус также легко снимается как и добавляется? Нужны офицеры с полным доступом? Тыкнул на консоль. Не нужны офицеры с полным доступом? Снова тыкнул на консоль.

**Comment by Motzord** [comment]
Офицеры и их взаимодействие с кодом выглядит вообще забавно.
Зеленый код — полномочий как у охранников из пятерочки
Синий — более менее нормальные полицаи
Красный — фашисты, военная полиция и комнатные рембо.

Так почему бы в красный код и не дать им фашиствовать? Неужели НТ настолько пофиг на Исход, что у них не предусмотрена резервная кнопка "Выпускай щиткурионов"? (ОБР не всегда щитспавнят, что с точки зрения баланса очень даже хорошо, а с точки зрения ЦК очень глупо.)

**Comment by Pivo24** [comment]
В любой непонятной ситуации главы будут абузить КК чтобы СБшники:
А) Сдохли и даровали ролям фулл аксесс
Б) Ебали ролей без полного доступа.

Погони? Побег от СБ? Редкод - и уже через мгновение ты лежишь гниёшь в карцере. Или на полу, мёртвый. Может во время КК давать на офицерские карты доступ в арсенал (логично) и неполный доступ в остальные отсеки, как это сделано у глав или парамедиков (удобно).

**Comment by Garrysman232** [comment]
ОБР это не дезсквод, это отряд для регуляции положения на станции, в случае если экипаж не справляется, и в составе обр, о боже мой, есть не только вояки, но и инженеры с врачами

Так же при выпущенной сингулярности глупо не вызывать ОБР, при вирусе на станции глупо не вызывать ОБР, и еще туча причин при которой ОБР должно вызываться, но не вызывается

**Comment by Garrysman232** [comment]
И да, почему бы сразу не дать инженерам фулл аксесс? В любой отдел они и так пройдут потратив на открытие двери на секунду-две больше. А вот при случае пиздеца в каком то отделе, быстро сами смогут прибежать залатать дыру и починить что надо

Предлагаю фулл доступ инженерам, он им нужнее чем СБ даже
