### ISSUE TITLE
Сигналеры в бомбах не работают

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#3806]
#### Подробное описание проблемы
При создании бомбы у форонщика, сигналеры не работают.
#### Что должно было произойти
при подаче нужного сигнала должно было бахнуть
#### Что произошло на самом деле
Произошло Н И Ч Е Г О
#### Как повторить
сделать бомбу с активатором сигналером
#### Дополнительная информация:
с таймером и другими сенсорами работает

**Comment by Motzord** [comment]
Все работает, лично за форонщика проверял.
(А ты сигналер прикрутил обратно?)

**Comment by Dominig12** [comment]
там просто ебанутая задержка, отбой
