### ISSUE TITLE
Random shuttle call by nuke ops at ai satellite

### ISSUE THREAD

**Issue by Morair** [TauCetiStation/TauCetiClassic#3809]
#### Подробное описание проблемы
Иногда вызывается предложение вызвать шаттл нюкеру который выключает ии с помощью емп гранат, именно после взрыва емп гранаты.
![image](https://user-images.githubusercontent.com/37118270/63064012-a92e1280-bf18-11e9-8ea4-80e0cf5b8b11.png)

#### Что должно было произойти
Ничего

#### Что произошло на самом деле
Нюкер вызывает шаттл.

#### Как повторить
Кидать в активный ии емп и надеяться что вылезет табличка вызова шаттла, вызвать его.

#### Дополнительная информация:
За последний месяц вызвал так 2 раза, может кто из админов подтвердит.

**Comment by Sakuya-Izayoi** [comment]
Мне удалось добиться появления этого окошка, но при нажатии на Yes шаттл не вызвался.

**Comment by Morair** [comment]
Возможно у тебя не было активного ии чтоб баг сработал.
