### ISSUE TITLE
Не работающая способность: Не дышать

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#382]
#### Подробное описание проблемы

Не работает способность из генетики: Не дышать
#### Что должно было произойти

Не должны задыхаться\рваться лёгкие в безвоздушном пространстве
#### Что произошло на самом деле

Задохнулся\порвались лёгкие
#### Как повторить

Получить способность Не Дышать

**Comment by WallShrabnic** [comment]
Не знаю, как у тебя, но у меня работало

**Comment by Gyaviste** [comment]
Эта способность даёт тебе не дышать. С чего она должна ещё и от давления защищать?
