### ISSUE TITLE
Отвалившиеся детали в протолате

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#3825]
#### Подробное описание проблемы
В новой системе РнД отвалились манипуляторы и сенсоры
#### Что должно было произойти
Улучшенные версии манипуляторов и сенсоров должны быть доступны
#### Что произошло на самом деле
Их нет
#### Как повторить
Поиграть в новую систему исследований

**Comment by Ambassadoing** [comment]
Они есть, в ветке биотехнологий поищи. Я сам не сразу понял, где они.

**Comment by Motzord** [comment]
Не закрыто
