### ISSUE TITLE
Капитанский лазер=винтовка

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#3826]
#### Подробное описание проблемы
При извлечении капитанского лазера из кобуры, в логах отображается, что достали винтовку
#### Что должно было произойти
В логах должно писаться, что извлекли антикварный лазер
#### Что произошло на самом деле
Capitan name достал laser riffle и указал на землю
#### Как повторить
ЗАпихнуть капитанский лазер в кобуру и вытащить из нее

**Comment by AndroBetel** [comment]
капитанский лазер называется "laser rifle" если что

**Comment by Motzord** [comment]
> капитанский лазер называется "laser rifle" если что

Так задумано чи шо?
