### ISSUE TITLE
Баг ИИ и Воксы

### ISSUE THREAD

**Issue by TheReaperOfSouls** [TauCetiStation/TauCetiClassic#3828]
#### Подробное описание проблемы
Если вокс в невидимости засветится на камере с датчиком слежения, то ИИ сможет его фолловить вечность
#### Что должно было произойти
ИИ увидел бы оповещение об датчике слежения, но не смог бы следить за воксом в невидимости
#### Что произошло на самом деле
ИИ следил за воксов в стелсе и его нагнули офицеры.
#### Как повторить
Взять вокса, стелс броню, пройти рядом с камерой где есть датчик движения.
Попросить ИИ быть багоюзером.

**Comment by Belfogor** [comment]
@Lizurt Можешь глянешь, если уж занялся ребалансом воксов.
