### ISSUE TITLE
Не работающая способность: Телепатия

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#383]
#### Подробное описание проблемы

Не работает генетическая способность телепатия
#### Что должно было произойти

Возможность писать в мысли людям
#### Что произошло на самом деле

Нет возможности прожать кнопку Project Mind
#### Как повторить

Получить способность Телепатии

**Comment by WallShrabnic** [comment]
Опять же, у меня работало раньше. Как сейчас - ХЗ

**Comment by Gyaviste** [comment]
Ну так у прожект майнда отдельный ген
