### ISSUE TITLE
Ошибка описания в коде

### ISSUE THREAD

**Issue by dred1792** [TauCetiStation/TauCetiClassic#3835]
[Тут](https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/research/research.dm#L1497) написано "Basic Hardsuit Modules", в то время как  должно быть написано "Advanced Hardsuit Modules".

**Comment by Alexofp** [comment]
Это поле нигде не используется из-за моей лени прописывать каждой технологии описание но спасибо
