### ISSUE TITLE
Меме не получает улучшенное сзрение таяран

### ISSUE THREAD

**Issue by ZMikkie** [TauCetiStation/TauCetiClassic#384]
#### Подробное описание проблемы

Меме в таяре, таяра бегает по техам со своим врожденным улучшенным зрением в темноте. Меме ничего не видит и вообще в непонятках.
#### Что должно было произойти

Меме воспринимает мир через органы чувств хоста - меме должен видеть в темноте как таяра.
#### Что произошло на самом деле

Меме темно.
#### Как повторить

Вселиться в таяру за меме.

**Comment by Motzord** [comment]
Меме выпилили на корню
