### ISSUE TITLE
У менторов снова есть чатик

### ISSUE THREAD

**Issue by aIweiss** [TauCetiStation/TauCetiClassic#3841]
#### Подробное описание проблемы
У менторов есть чатик в виде возможности написать в менторхелп.
#### Что должно было произойти
У менторов есть возможность только отвечать страждущим.
#### Что произошло на самом деле
Тотальная деградация.
#### Как повторить
Получить флажок, позволяющий видеть менторхелп, и умирать от увиденного.
#### Дополнительная информация:
Уже же фиксили, кто сломал?

**Comment by Pivo24** [comment]
Оставь чатик!

**Comment by igigin** [comment]
Надо просто дементор принудительно в игре и, пока ментор дементор, чтобы мог вопросы задавать.

**Comment by ext9z3** [comment]
Менторы сами у друг друга механ уточняют для ответа на вопросы игроков, чтобы по 5 менторов сразу не ебалось в ПМку одному человеку, с каждым новым уточнением

**Comment by WallShrabnic** [comment]
У дцп опять обострение

**Comment by KuzyXD** [comment]
Я как и администратор пишу в мхелп, другие менторы пишут туда, чтобы ответ узнать. Ничего тут проблемного не вижу. Работает, как и должно.

**Comment by igigin** [comment]
> Работает, как и должно.

Привет, я автор этой хуйни и нет, так не должно. Но вы и в руле 0 проблем не видите.

**Comment by aIweiss** [comment]
а он просто автор чатика менторов, чатик работает так, как и должно))0)

**Comment by KuzyXD** [comment]
Все же это не проблема. Потому закрываю.
