### ISSUE TITLE
Баг с ручным телепортером

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#385]
#### Подробное описание проблемы

Баг с ручным телепортером
#### Что должно было произойти

Должен был телепортироваться вместе с ручным телепортером 
#### Что произошло на самом деле

При телепортации с ручным телепортером он якобы остался в рюкзаке но его нет http://prntscr.com/c0rh3m
#### Как повторить

С некоторым шансом при телепортации с ручным телепортером он пропадает

**Comment by WallShrabnic** [comment]
Подозреваю, что это не баг а фича, чтобы всякие Ольты гибались в космосе
