### ISSUE TITLE
Floral somatoray не работает.

### ISSUE THREAD

**Issue by Schutszaffel** [TauCetiStation/TauCetiClassic#3853]
#### Подробное описание проблемы
При использовании floral somatoray ничего не происходит.
#### Что должно было произойти
Растения должны мутировать/менять свои характеристики в зависимости от режима стрельбы.
#### Что произошло на самом деле
Сообщении о выстреле и никакого эффекта.
#### Как повторить
Выстрелить из floral somatoray в растение.

**Comment by Morair** [comment]
Все работает 
![image](https://user-images.githubusercontent.com/37118270/63429888-bbd2ab00-c434-11e9-93ae-c8abd2e2b852.png)

**Comment by Schutszaffel** [comment]
А что по мутациям?
