### ISSUE TITLE
Сломанный пёс.

### ISSUE THREAD

**Issue by Zandwitch23** [TauCetiStation/TauCetiClassic#3855]
#### Подробное описание проблемы
Ян ломается после перезахода на сервер или даже после 10-15 секундного лага.
#### Что должно было произойти
Всё должно оставаться как и было.
#### Что произошло на самом деле
Пропадает hud, соответственно "нюх-нюх" и лизание тут же исчезает, лечь и сесть можно только через инфо панель через crawl и rest. Речь окружающих становится не понятной. Надетые вещи по прежнему отображаются. В рюкзак можно заглянуть через иконку слева вверху, но вещи из него достать нельзя. 
#### Как повторить
Играя за Яна перезайти на сервер.
#### Дополнительная информация:
Кажется он спит на ходу.

**Comment by Zandwitch23** [comment]
Раньше это не так сильно доставляло, но с открытием дополнительных серверов лаги участились, а это оч западло после 10 минут с начала раунда. При чём губительный лаг был на Таукети2, а на сайте высвечивается еррора напротив Таукети1 и три :/

**Comment by KIBORG04** [comment]
Тильда у меня не удалось воспроизвести этот баг, я перезаходил и худ оставался на месте, поэтому хз про актуальность

**Comment by T6751** [comment]
Проблема с Яном после перезахода была ещё летом. Думаю это всё ещё может быть актуальным.
https://github.com/TauCetiStation/TauCetiClassic/issues/5844

**Comment by T6751** [comment]
Вероятно действительно неактуально

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/f-a-q-tehnicheskie-problemy-i-sposoby-resheniya/7864/84
