### ISSUE TITLE
Джампсуиты не чистятся после чистки клинером

### ISSUE THREAD

**Issue by ext9z3** [TauCetiStation/TauCetiClassic#3859]
#### Подробное описание проблемы
Если кликнуть по персонажу с грязной одеждой клинером, то костюм фактически очистится, но спрайт не заменится на чистый, пока одежду не переоденут
#### Что должно было произойти
Спрайт поменяться сразу
#### Что произошло на самом деле
Спрайт меняется только после переодевания
#### Как повторить
Брызнуть клинером на грязную одежду

**Comment by LudwigVonChesterfield** [comment]
#5278 

Там более общее.
