### ISSUE TITLE
Малф

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#386]
#### Подробное описание проблемы
Счётчик Малфа работает очень быстро, прям совсем.
#### Что должно было произойти
Счётчик должен тикать как у ядерной бомбы.
#### Что произошло на самом деле
Счётчик тикает слишком быстро и нельзя ничего сделать.
#### Как повторить
Взять малфа и врубить оверайд.
#### Дополнительная информация:
После подебы взрывается только спутник ИИ. Сделайте центр взрыва в центре станции.

**Comment by MorCrate** [comment]
Про взрыв - фича.

**Comment by Skippeer12** [comment]
Верните графон!
