### ISSUE TITLE
Невозможно отказать от предложения стать позитронкой на раунд

### ISSUE THREAD

**Issue by SomeUselessGuy** [TauCetiStation/TauCetiClassic#3869]
#### Подробное описание проблемы
Когда глупые людишки запускают позитронку, гостам выходит предложение стать позитронкой. Если нажать "Never for this round" - эффекта не будет.
#### Что должно было произойти
Мне не должно было спамить окном становления позитронкой
#### Что произошло на самом деле
Оно спамит
#### Как повторить
Сделать позитронку, выйти в госта, запустить позитронку, отказаться, запустить позитронку еще раз.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/40398890/63600198-8963b200-c5dc-11e9-8571-2e1d066de561.png)

**Comment by KIBORG04** [comment]
Работяги, актуальный ишуй?
