### ISSUE TITLE
Шэдоуллинг

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#387]
#### Подробное описание проблемы

Способность Veil не работает на мониторы.
#### Что должно было произойти

Мониторы должны выключится.
#### Что произошло на самом деле

Они не выключаются.
#### Как повторить

Взять шэдоуллинга и использовать Veil вблизи мониторов.

**Comment by WallShrabnic** [comment]
НЕ должны же вроде вообще выключаться

**Comment by ZVee** [comment]
Тут просто недопонимание абилки Veil на шедоулинге, монитор - он не лампа, но излучает свет, да. А абилка работает только исключительно на осветительные приборы. Посему, не могу считать багом.

**Comment by dearprincesscelestia** [comment]
А почему для шадовлинга это не лампа, если это очень много маленьких ламп?

**Comment by ZVee** [comment]
А почему ЭМИ не гасит лампы?

**Comment by dearprincesscelestia** [comment]
Шок сенсация, в есеске мониторы на цветных флюорисцентных грибах.

**Comment by ZVee** [comment]
Только вот светогрибы абилка тушит. Но при этом вендоматы, настенную технику и прочее - нет. Может догадаешься таки почему?

**Comment by dearprincesscelestia** [comment]
ИГРОВОЙ БАЛАНС

**Comment by ZVee** [comment]
И как же невозможность потушить компьютеры/вендоматы отражается на баланс? Ведь их свет недостаточен чтобы начать наносить урон, разве что если их понаставить в одном месте, да и то, там максимум тайл который в упор находится к ним будет сильным - что никак не спасет.

Вообще, подсказка в описании абилки, сделать чтобы тушилось все - гораздо проще, чем избирательно собирать в список определенные предметы что собственно и сделано в умении.

**Comment by dearprincesscelestia** [comment]
Но я не знаю описания умения! Меня просто смущает фраза "монитор - он не лампа".

**Comment by Skippeer12** [comment]
Ну тогда надо занерфить сфечение мониторов, потому как свет нет, а тебя дамажит.
