### ISSUE TITLE
Камеры с одинаковыми именами на NSS Exodus

### ISSUE THREAD

**Issue by SH42913** [TauCetiStation/TauCetiClassic#3870]
#### Подробное описание проблемы
На мостике имеются две разных камеры с одним именем _Bridge West_, из-за чего интерфейс выделяет их как одну и не дает между ними переключаться без переключения на третью камеру
![K5lcc9679d](https://user-images.githubusercontent.com/17111024/63601641-46570e00-c5df-11e9-999f-322686760fd2.png)
![mFM87bq9SY](https://user-images.githubusercontent.com/17111024/63601643-46570e00-c5df-11e9-955e-a008f6e6fd0c.png)

#### Что должно было произойти
Камеры _Bridge West_ и _Bridge East_

#### Что произошло на самом деле
Две камеры _Bridge West_

#### Как повторить
Открыть любую консоль охранных камер

**Comment by FelixRuin** [comment]
Bridge East это которая справа должна быть?

**Comment by SH42913** [comment]
Вроде, да.
West - запад(слева), East - восток(справа).
