### ISSUE TITLE
ИИшка с каких-то пор получил возможность тречить то, что не должен.

### ISSUE THREAD

**Issue by EdlerN** [TauCetiStation/TauCetiClassic#3874]
## Подробное описание проблемы
Я сильно сомневаюсь что ИИ должен быть в состоянии отслеживать невидимых существ
#### Что должно было произойти
Бай дезайн трек и прыжки работают только на мобов с нормальной картой
#### Что произошло на самом деле
ИИ в состоянии отслеживать любого моба не защищенного синди-картой (хоть это не сломали) не взирая на то, обнаружим ли он или нет.
#### Как повторить
Спавним ИИ, спавним пару камер, спавним моба выкручиваем ему альфу в 0. Спавним вокса в стелссьюте - включаем маскировку, можем отслеживать обоих
#### Дополнительная информация:
Ранее не было возможно отслеживать мобов без карты, но кто-то решил это поменять. Неплохо бы если бы этот кто-то решил и всплывшие от этого проблемы.

**Comment by LudwigVonChesterfield** [comment]
#3718
