### ISSUE TITLE
Кик игрока приводит к его "перме"

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#3875]
#### Подробное описание проблемы
При попытке кикнуть игрока, он не видит причину кика. Но не это главное. Главное то - что у жертвы появляются какие-то проблемы с клиентом и он не может потом зайти. Вроде как лечилось повторным киком, но возможно это просто временно не давало зайти на сервер.
#### Что должно было произойти
Кикнутый игрок должен иметь возможность сразу же зайти на сервер обратно.
#### Что произошло на самом деле
Еду руинит конекшн при попытке зайти.
#### Как повторить
Кикнуть Директора и смотреть как тебя пермят.
#### Дополнительная информация:
Тестировалось на подопытном 666 Олдеме.

**Comment by Motzord** [comment]
Можно закрывать, при кике игрока с песочницы никто не пермится
