### ISSUE TITLE
Исправление столов

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#3877]
#### Подробное описание проблемы
Некоторые столы, при попытке положить на него предмет "кладут" предмет на пол, вероятно это из-за того, что один спрайт накрывает другой
#### Что должно было произойти
Предмет должен лежать на краю стола
#### Что произошло на самом деле
Предмет "кладется" на тайл пола
#### Как повторить
Попытаться положить какой либо предмет на край стола и обнаружить его на полу 
#### Дополнительная информация:
Обычно замечаю этот баг, если на том же столе стоит компухтер, факс, держатель бумаг и прочее

**Comment by GreyGunner** [comment]
Виноваты не столы, а оборудование, которое стоит на этих столах. Проблема в том, что спрайт оборудования не передает его громоздкости, вложенной механом. Ряд машинерии вызывает следующие заблуждения:
- Люди думают, что рядом с ней можно что-то положить
- Люди думают, что ее можно перетаскивать
- Люди думают, что на стол с ней можно залезть или проползти под столом с ней

**Comment by volas** [comment]
возможно тогда флаги оборудования посмотреть

**Comment by GreyGunner** [comment]
Пропишу Density=0 у подобных агрегатов

**Comment by GreyGunner** [comment]
anchored=0 тоже поставлю

**Comment by GreyGunner** [comment]
По хорошему надо прикрутить механ, чтобы можно было гаечным ключем перетаскивать еще... займусь как-нибудь этим ишью в общем, в течении месяцев эдак 3-х

**Comment by Motzord** [comment]
Все еще актуально

**Comment by LudwigVonChesterfield** [comment]
Можно попробовать сделать чтобы предметы проходили через не занимающий весь тайл компьютер.

**Comment by LudwigVonChesterfield** [comment]
Кстати говоря, уже по сути исправлено в #5242

Правда вероятно можно ждать новых багов вида "я могу положить гребаную кувалду на один стол с огромнейшей микроволновкой", но такова цена неожиданных фиксов...
