### ISSUE TITLE
Из обсерва сразу в блоба

### ISSUE THREAD

**Issue by Morair** [TauCetiStation/TauCetiClassic#3879]
#### Подробное описание проблемы

Прожимаешь кнопку обсерв и становишься блобом а не гостом, другой человек сказал что его съел линг и после этого он стал блобом сразу.
Round id: #27460

#### Что должно было произойти

Становишься призраком и обсервишь раунд.

#### Что произошло на самом деле

Стал блобом

#### Как повторить

Зайти в госты, или подождать пока тебя скушает генокрад.

#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/37118270/63644145-80b5cd80-c6fb-11e9-87d0-aa3a630def4f.png)

**Comment by Sakuya-Izayoi** [comment]
возможно какая-то педаль игралась с кнопочками
