### ISSUE TITLE
[Proposal]Требуется создание временного мута помимо пермамута и раундового мута

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#3898]
#### Подробное описание проблемы
Чтобы выдать мут на определенное время нужно дать пермамут и написать нотес когда снять
#### Что должно было произойти
Написал время мута как с банами
#### Что произошло на самом деле
Дрочишь нотесы
#### Как повторить
Попробуй замутить протекающего рецидивиста

**Comment by volas** [comment]
Если человек регулярно нарушает правила общения, то это повод для бана. В этом плане у нас даже пермамуты лишние.

**Comment by Dominig12** [comment]
Но иногда есть сильное желание выдать мут на недельку
