### ISSUE TITLE
Доступ в медбей

### ISSUE THREAD

**Issue by Yaroslavppv** [TauCetiStation/TauCetiClassic#3900]
#### Подробное описание проблемы
Потерялся врачебный доступ у новых стеклянных дверей на левом входе в медбей. После вот этого #3839 
#### Что должно было произойти
Доступ только у врачей.
#### Что произошло на самом деле
Клоуны спокойно бегают по меду.
#### Как повторить
Зайти в раунд.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/30586104/63833400-68a8ad00-c98c-11e9-9db9-00b8f85b2f21.png)

**Comment by FelixRuin** [comment]
мне особо доставляет сводка из мап эдитора, это какой-то новый уровень ишусов, когда пишущий сделает ещё 2 шага и решит сам проблему
