### ISSUE TITLE
Огнетушители не убивают слаймов и вообще сломаны. Верните как было.

### ISSUE THREAD

**Issue by Ydaater** [TauCetiStation/TauCetiClassic#3914]
#### Подробное описание проблемы
Огнетушители не могут ничего против слизи. В коридоре заливаешь маленького слизня, ему все равно. А все из-за новой махиники, где можно стрелять огнетушителем на много тайтлов вперед (это пожарный кран или огнетушитель?) 
#### Что должно было произойти
Слизень должен был умереть после пары точных пшыков как было раньше.
#### Что произошло на самом деле
Слизень не умер после того как я распылил на него 800 воды и 1000 пены. 
#### Как повторить
Найти в коридоре слизня, судорожно его поливать огнетушителем, можно зарядить огнетушитель водой или пеной.
#### Дополнительная информация:
https://youtu.be/JcEoBgxZhS8

**Comment by LudwigVonChesterfield** [comment]
Вода и из спреев не убивает. Как и раньше убивает не вода, а волшебная жидкость в огнетушителе. Которая раньше была типо водой, а теперь типо пена.
