### ISSUE TITLE
Вставленные в РИГ магбутсы не защищают от притягивания сингулярностью

### ISSUE THREAD

**Issue by Loratron** [TauCetiStation/TauCetiClassic#3924]
#### Подробное описание проблемы
Магбутсы, вставленные в любой РИГ, при активации должны защищать не только от резкой смены давления, но и от притягивания сингой
#### Что должно было произойти
Магбутсы включены и кукла спокойно может ходить рядом с сингулярностью
#### Что произошло на самом деле
Магбутсы включены и кукла засосана в сингулярность
#### Как повторить
Вставить в любой РИГ магбутсы, надеть его, включить магбутсы и попытаться пройтись рядом с сингой

**Comment by WallShrabnic** [comment]
Они вообще не работают как нормальные магбутсы
