### ISSUE TITLE
[Proposal] запретить гостам воутать шаттл.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#3927]
#### Что мы имеем сейчас:
Скучающие госты, слившиеяся по какой-то причине и вызывающие шаттл по КД, как только смогут
#### Что мы хотим видеть
Живое голосование от живых игроков, которые решат когда будет конец смены без помощи призраков.
#### Почему мы хотим это видеть:
Крю трансферный мир побеждает слишком часто, лишая ранудов продолжительности, интересных ситуаций и прочего, по причине. "Воут черех 10 минут не буду ничего делать" 
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/45365635/64063177-174d2780-cbf1-11e9-86e0-485700889126.png)

@KuzyXD

**Comment by FelixRuin** [comment]
Нюкеры всех убили и стали пить чаи, на 30 минут от первого фрага никто не сможет проголосовать за конец раунда

**Comment by Motzord** [comment]
> Нюкеры всех убили и стали пить чаи, на 30 минут от первого фрага никто не сможет проголосовать за конец раунда

Если нюкеры всех убили — значит поставили бомбу.
Если поставили бомбу — значит в=потерпи еще 7 минуток.

Если нюкеры не поставили бомбу — прибежит педалька
Если прибежит педалька — нюкеры поставят бомбу

**Comment by FelixRuin** [comment]
Короче давайте чтоб ещё и шатлл тогда вызывался только педально, примерно это так как-то звучит, о, о, или ещё такое, всех убило сингой/радиацией/разгермой, осталось пару человек, которые шатлл вызывать не хотят, или вообще никого, тогда что? Педально шатлл вызывать грешно без факса, только воут стартовать. 
Серьёзно, все примеры почему это плохо включают то, что для работы такой системы нужен админ

**Comment by KuzyXD** [comment]
@FelixRuin прав насчет необходимости админа на каждый раунд. Надо придумать то, как будет работать воут, если живых на борту Исходуса < N-числа.

**Comment by Kyler2262** [comment]
А может просто продлить раунды на 3 часа?

**Comment by WallShrabnic** [comment]
Ишью - дубликат https://github.com/TauCetiStation/TauCetiClassic/issues/865
