### ISSUE TITLE
Откидывание мутантов.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#3931]
#### Подробное описание проблемы
При выстреле со скрафченого арбалета, его снаряды откидывают все живое и даже Зиллу, Халка и ему подобных
#### Что должно было произойти
Зилла должна была выдерживать какой-то там раскаленный прутик
#### Что произошло на самом деле
Зилла отлетает за экран
#### Как повторить
Стрельнуть по зилле с арбалета
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/45365635/64068181-a3cd0980-cc34-11e9-8f0d-ff3399d3f25c.png)

**Comment by Motzord** [comment]
![image](https://user-images.githubusercontent.com/45365635/64068190-c52df580-cc34-11e9-8075-2db3933b8d1a.png)
А это еще смешнее

**Comment by FridrihRichter** [comment]
Просто арматура из адомантия попалась.

**Comment by Motzord** [comment]
Арбалет вроде понерфили можно закрывать
