### ISSUE TITLE
Шрапнель на самом деле стекло

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#3937]
#### Подробное описание проблемы
При наступании на куски пуль, логируется наступание на стекло
#### Что должно было произойти
Должно логироваться наступание на шрапнель, звона стекла быть не должно
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/45365635/64127690-0e0bb880-cdb3-11e9-8924-10a4b3a5d8ae.png)
![image](https://user-images.githubusercontent.com/45365635/64127704-1bc13e00-cdb3-11e9-88a1-b2d5e074c132.png)

#### Как повторить
1.Набираем осколочки пуль
2 наступаем на них без ботинок.
3 ???
4. PROFIT

**Comment by Motzord** [comment]
#3937

**Comment by volas** [comment]
Не нужно самому ишью закрывать, как ПР будет смержен - это произойдет автоматически
