### ISSUE TITLE
 [Proposal]Баффнуть стечкин с глушителем.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#3938]
#### Подробное описание проблемы
Стечкин с глушителем слишком слабый для убивания кукол.
#### Что должно было произойти
Стечкин+глушитель = оружие для бесшумных УБИЙСТВ.
#### Что произошло на самом деле
6+ пулек в голову с расстояние в 1 тайл от цели. СМО относительно жив и даже не в крите.
#### Как повторить
Попробуйте кого нибудь убить заглушенным стечкиным.
#### Дополнительная информация:
В данный момент стечкин с глушителем совершенно себя не оправдывает из-за слишком сильного нерфа урона. Хотя любой пистолет с глушителем сделан для убийств (Причем калечит при выстреле в голову, мягко говоря не очень, хотя 3+ хэдшота должны убивать гарантированно), а на деле он лишь калечит и выполняет скорее запугивающую функцию, что совершенно не хорошо, для стелсотритора.

**Comment by Ambassadoing** [comment]
А урон вообще режется глушителем? Я что-то в коде не найду.

**Comment by AndroBetel** [comment]
не режется.

у стечкина дамаг - 25 брута. у куклы 200 (150 если считать падение в крит смертью) делим 200 (150) на 25 и получаем 8 (6) выстрелов, чтобы убить голожопого. слишком много, да? 

однако секрет фирмы - комбинировать предметы из аплинка. человек успел позвать на помощь, пока ты вытаскивал пистолет из сумки и целился ему в глаз? в следующий раз помажь его эми-фонариком. жертва просто слишком прыткая? выстрели ему в ногу из енерги-арбалета и пристрели беззащитного ублюдка. столько возможностей - но тупое закликивание эл кэ эмом всегда легче, но не всегда эффективнее.

**Comment by Ambassadoing** [comment]
Да можно хоть ту же болу самодельную кинуть и жертве уже будет почти нереально свалить

**Comment by Pivo24** [comment]
Как тебе объяснить-то, раз ты в дискорде не увидел.
У каждой куклы есть лимит в 70 брут урона на определённую часть тела. 70 брут урона на голове, на груди, на гроине, руках-ногах.

Если часть тела достигает или вскоре достигнет лимита в 70 брут урона, _ВЕСЬ УРОН, КОТОРЫЙ ПРИХОДИТСЯ НА ЭТУ ЧАСТЬ ТЕЛА, УРЕЗАЕТСЯ В ДВА РАЗА._
Нет, если выстрелишь тремя 9мм пулями (25 урона каждая) в голову, нанесётся не 75 брут урона (25 + 25 + 25), а 62,5 (25 + 25 + 12,5), чтобы лимит мог превыситься только при получении порезанного урона.

Поэтому я не зря писал, что нужно знать, как стрелять.

Сравни, шесть выстрелов в голову, с обрезанием урона, и шесть выстрелов по разным частям тела, чтобы лимит на них не превышал 70 единиц:

(25 + 25 + _12,5 + 12,5 + 12,5 + 12,5_) - 75 брут урона за 6 выстрелов. Этого мало, чтобы убить.
(25 в голову + 25 в голову + 25 в грудь + 25 в грудь + 25 в гроин + 25 в гроин) - 150 брут урона, крит, ещё и мозг повреждён, и органы.

И ведь ещё дополнительные застрявшие пули осложнят выживаемость даже самому закалённому СМО.

И ты пишешь что стечкин подвергся слишком сильному нерфу урона?

**Comment by UDaV73rus** [comment]
Револьвер отрывает голову за два(если не повезет - три) выстрела. Не дает дефибнуть и можно забрать голову. Жертва не успевает даже пискнуть. Стан с первого выстрела. Застревает шрапнель. Стоит на один ТК меньше стечкина с глушителем.
НУ А ЧО

**Comment by EdlerN** [comment]
Револьвер шумный. При том - очень шумный. Но для своей стоимости настолько эффективен что берется нюкопсами время от времени. Ибо имеет давным давно занерфленый у других пушек стан по неприкрытым участкам тела. Возмооожно стоит слегка поднять его стоимость.
