### ISSUE TITLE
Атмосферный риг не защищает от неблагоприятной атмосферы 

### ISSUE THREAD

**Issue by FridrihRichter** [TauCetiStation/TauCetiClassic#3940]
#### Подробное описание проблемы
Атмосферный РИГ не защищает людей от загрязнения фороном одежды под ригом. 
#### Что должно было произойти
Полностью герметичный атмосферный риг, приспособленный для устранения различных ЧП, связанных с атмосферой, не должен пропускать никакие ядовитые газы
#### Что произошло на самом деле
Полностью герметичный атмосферный риг, приспособленный для устранения различных ЧП, связанных с атмосферой, пропускает ядовитые газы под свою поверхность, в связи с чем одежда загрязняется и начинает отравлять носителя, который не может спокойно отправиться в медбей, потому что он блин ликвидирует утечку форона.
#### Как повторить
Одеть атмосферный риг и зайти в помещение с опасной концентрацией форона (1-2% уже достаточно)
#### Дополнительная информация:
Иногда РИГ все-таки защищает одежду от форона, но во время возгорания газа, одежда загрязняется всегда.

**Comment by 1Samen** [comment]
А у тебя был шлем интегрирован в риг ?

**Comment by Deahaka** [comment]
Не баг а фича

**Comment by simb11** [comment]
не фича а баг
