### ISSUE TITLE
[Proposal] Нерф АК и Булбича, запилите уже холд двумя руками.

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#3947]
#### Подробное описание проблемы
Автомат Капашников и бульдог есть ОП ибо с них можно прицельно стрелять с одной руки.
#### Что должно было произойти
Валыны такого сорта если имеют такой урон, то должны держаться двумя руками для прицельной стрельбы.
#### Что произошло на самом деле
Все это оружие было добавлено еще до превращение кукол в пакетики кетчупа хаянз.
#### Как повторить
Можем повторить.
#### Дополнительная информация:
Давно пора завести нормальную систему как на маринадах. Огнестрел в билде ТК открывает внутряки, а это уже смерть. Тут либо нерфать потери крови при артериальном, либо огнестрелу прописывать холд в двух руках для прицельной стрельбы.

**Comment by EdlerN** [comment]
Если мне не изменяет память - урон от калаша - 35 брута с пульки. Урон от лазура - 40 берна. Если нерфить то все вместе наверное уж.

**Comment by Motzord** [comment]
> Если мне не изменяет память - урон от калаша - 35 брута с пульки. Урон от лазура - 40 берна. Если нерфить то все вместе наверное уж.

Но лазер особого веса не имеет, как и отдачи (наверное, не с пульсача же стреляем)

А калаш это огнестрел и стрелять с одной руки точно в голову минимум странно

**Comment by EdlerN** [comment]
Я тебе про баланс, ты мне про реализм. К тому же, я не скажу что стрелять с ак одиночными с одной руки по цели в 8 метрах так уж сложно.

**Comment by GreyGunner** [comment]
@Motzord  https://youtu.be/2ye3p1LidAA?t=155

**Comment by WatlerJe** [comment]
Лазор не может вызвать артериалку и он не ломает кости.

**Comment by GreyGunner** [comment]
Зато может сквозь окна и решетки стрелять...

**Comment by EdlerN** [comment]
Лазер выбивает сердце/лёгкие

**Comment by ViDLiathan** [comment]
Гематома в мозгу, которая химией не лечится.
