### ISSUE TITLE
[Proposal] Больше ксено-вещей в лоадаут

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#3950]
#### Подробное описание проблемы
Малое количество ксено-вещей в лоадауте, хотя их больше в самой игре

#### Что должно было произойти
Несколько больше ксено-вещей в лоадауте

#### Что произошло на самом деле
Есть только украшение на щупальца для скрелов и шарф для таяран

#### Как повторить
Зайти в лоадаут и поискать ксено-вещи

#### Дополнительная информация:
Уже есть вещи которые можно найти в игре, но они встречаются крайне редко и их нет в лоадауте (например лизарбутсы).
Если будут добавляться новые вещи то могу заняться их спрайтингом.

**Comment by ViDLiathan** [comment]
Лизардбутсы не для ящеров ботиночки, а из ящеров

**Comment by Akellazp** [comment]
> Лизардбутсы не для ящеров ботиночки, а из ящеров

У них написано, что это специальные ботинки Унатхов

**Comment by Garrysman232** [comment]
> Лизардбутсы не для ящеров ботиночки, а из ящеров

Для ящеров ~~из~~ от ящеров
