### ISSUE TITLE
Немного о багах скелетов которые я нашел

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#3952]
#### Подробное описание проблемы
1)Скелет может стать жирным, хорошо видно в одежде 
![image](https://user-images.githubusercontent.com/24685276/64435331-fbeb8c00-d0ca-11e9-9698-a522ec95ae18.png)
![image](https://user-images.githubusercontent.com/24685276/64435361-07d74e00-d0cb-11e9-8b16-cda8fc7dd6ef.png)
2)Скелет вообще хочет есть, и он насыщается едой обычной
3) один раз произошел баг при котором сломалась система оповещения о заходящих айпи, фактически система считала что Я играю с айпи другого игрока, этот человек со мной тестил скелетов. Перед этим нас обоих выкинуло из игры при попытке реджува
4) Пару раз ломался реджув, и при попытке удалить голову на земле, удалялось все тело, даже с головой
5)Скелет может застрелиться выстрелом в рот..с любой пушки, даже лазерной.

#### Дополнительная информация:
Теперь то, что хотелось бы видеть у скелета
1) Возможность ходить когда слетела голова.
2) Возможность отсоединять себе конечности.

**Comment by WallShrabnic** [comment]
В следующий раз пожалуйста разделяй один ишью с кучей разныхх проблем на несколько более мелких по одному на баг

**Comment by Akellazp** [comment]
+у них есть проблемы с лечением органов (глаза, млзг и т.д.); и на космос они странно реагируют

**Comment by Motzord** [comment]
Скелеты реворкнуты, приколы с хождением без башки впилены, ишью можно прикрыть
