### ISSUE TITLE
Добавить СМО доступ парамедика [Proposal]

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#3953]
С одной стороны СМО глава и не должен бегать по вызовам, но с другой стороны СМО глава и должен обладать всеми доступами своих сотрудников в отделе. 
Бывают случаи, когда парамедики не могут отправиться на вызов, а их начальнику приходится брать их доступ, чтоб добраться до пациента.

**Comment by Sakuya-Izayoi** [comment]
мне кажется всё балансно на данный момент

**Comment by SpaiR** [comment]
Тезис про "каждый занимается своей работой" вполне логичен. Повышенный доступ излишен.
