### ISSUE TITLE
Броня воксов сильно поломана

### ISSUE THREAD

**Issue by Morair** [TauCetiStation/TauCetiClassic#3958]
#### Подробное описание проблемы
Вокс в боевом риге (/clothing/suit/space/vox/carapace) не получает урона в тело от лазеров, 
 летал пуль с пистолета, станбатонов(возможно больше, и не только этот риг), урон нормально идет только в голову.

#### Что должно было произойти
Вокс получает урон.
#### Что произошло на самом деле
Вокс как ходячий танк получает 0 урона в тело
#### Как повторить
Побить вокса.
#### Дополнительная информация:
https://github.com/TauCetiStation/TauCetiClassic/pull/3738

**Comment by maxyo** [comment]
Возможно дело в шлеме, он защищает не только голову, но и ноги, руки и туловище, и даже гроин:
https://github.com/TauCetiStation/TauCetiClassic/blob/184e29dc028f5c60bb547bd74f415c2e32b76774/code/modules/clothing/spacesuits/alien.dm#L147

Хотя возможно это фича.

**Comment by maxyo** [comment]
И что-то мне подсказывает что в космос можно выходить в одном этом шлеме
