### ISSUE TITLE
[Proposal]Сделать новый текст в репортах ЦК во время ревы

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#3970]
#### Подробное описание проблемы
Каждый раунд "рп"-ревы начинается одинаково(понижение ЗП, закрытие офисов). Может лучше придумать новых заданий и отправлять рандомное из них?
#### Что должно было произойти
Разнообразие заданий для глав и новые причины для бунда.
#### Что произошло на самом деле
Все одинаково, подход к проблеме почти никогда не меняется.
#### Дополнительная информация:
Если будут идеи для репортов в комментах тут, то могу накодить и я. 
(если не ошибаюсь, то все что нужно в файле rp_revolution.dm)

**Comment by Ambassadoing** [comment]
Тогда это уже будет мутини на минималках, а не рева

**Comment by KIBORG04** [comment]
> 
> 
> Тогда это уже будет мутини на минималках, а не рева

Что-нибудь балансное, а не "УБИТЬ ВСЕХ ВСЕНОСОВ"

**Comment by Ambassadoing** [comment]
Так в мутини их вроде как и не убивать надо, а поувольнять и деньги отобрать.

**Comment by KIBORG04** [comment]
А почему мутинити убрали?

**Comment by Zmey25** [comment]
Задание: Накопать побольше ресурсов и главам нужно отправлять всех на шахты. Аля северная корея в космосе или we need more minerals. 

зы. Добавить заданий триторам, а то скучно трусы воровать.

**Comment by KIBORG04** [comment]
> 
> 
> Задание: Накопать побольше ресурсов и главам нужно отправлять всех на шахты. Аля северная корея в космосе или we require more minerals.
> 
> зы. Добавить заданий триторам, а то скучно трусы воровать.

У триторов и так много заданий.
