### ISSUE TITLE
Старые риги. Верните. 

### ISSUE THREAD

**Issue by Ydaater** [TauCetiStation/TauCetiClassic#3973]
#### Подробное описание проблемы.
Одного дня тестмерджа хватило, комьюнити разделилось на две части, те кому лишь-бы рисуночки и риги не нужны даешь скафандры, и олдфаги фапающие на спрайты 2004 года + конструктивные критики. 

Верните как было.

#### Что должно было произойти
Нормальные старые риги должны были лежать там где должны. 
#### Что произошло на самом деле
На их месте лежат ужасные толстые скафандры.
#### Как повторить
Зайти на первый сервер.
#### Дополнительная информация:
Просто нет. Хватит. Не надо. Прекратите. Мы не хотим.

**Comment by Ydaater** [comment]
![изображение](https://user-images.githubusercontent.com/21292885/64651997-7568de80-d42b-11e9-974a-5fa7893788fd.png)

**Comment by ViDLiathan** [comment]
Сказали же, будет в течении недели, потом будет официальное голосование и обсуждение на форуме. Всем, кому настолько не нравятся новые риги, вежливо предложили пойти на второй сервер.

**Comment by Ydaater** [comment]
Лучше риги на второй сервере переместите. На первом они не нужны.

**Comment by Ambassadoing** [comment]
Не нравится - чапай на второй сервер.

**Comment by Motzord** [comment]
Игроки уже высказались отрицательно во всех голосовалках в которых можно, почему они должны ждать неделю?
