### ISSUE TITLE
[proposal] Мед. Хайлер парамедикам!

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#3984]
Когда парамедик бежит к пациенту, пытается протиснуться через толпу, несет пациента в мед чаще всего некоторые недогоняющие личности случайно или намеренно создают помеху его движению, в итоге либо парамедик замедляется толкая незадачливого зеваку, либо проходит "сквозь" него и теряет драгоценный секунды на подбор каталки с пациентом.

Я считаю медхайлер с звуком сирены может помочь решить эту проблему и добавит антуражу парамедикам, как скорой неотложной помощи. 

В чем суть?
>Нажимаем на хайлер
>секунд 10-15 звучит какой нибудь звук оповещающий о бегущимся парамедике, которому надо освободить блин дорогу, расступится.

(неплохо бы и одиссею прифигачить, ибо встать перед одиссеем чтобы он тебя толкал через весь коридор — отдельная веселуха)

**Comment by Valtar74** [comment]
Боюсь это будет мало полезная штука. Все нормальные игроки и так отходят в сторону а вот не нормальные ещё и любят открыть шкафчик или мешок с телом. Странно но люди находят это очевидно забавным.  Но это возможно будет полезно для особо глупых офицеров СБ. А то там есть некоторые личности у которые любят стрелять с тазера по убегающим от них парамедикам в техах. А так будет видно что человек не просто гуляет по тоннелям а идёт на вызов.

**Comment by maxyo** [comment]
Может просто шапку с мигалками?

**Comment by CeUvi** [comment]
Надо шапочку с мигалками и мигалки на риг, как у эСБэ.
