### ISSUE TITLE
[Proposal] Имплант лояльности Синдикату

### ISSUE THREAD

**Issue by maxyo** [TauCetiStation/TauCetiClassic#3987]
Добавление в аплинк импланта лояльности к Синдикату стоимостью 13 очков. Чип будет представлять собой обычный имплант, при вкалывании жертве, выдающий ей трейторку.
<details>
  <summary>Подробнее</summary>

**Цели трейтора-жертвы:**
1. Защитить _Имя купившего имплант_
2. Исполнять указы _Имя купившего имплант_

**Если уже есть чип лояльности?**
- Имплант НТ заменяется имплантом Синдиката.

**Вид в HUD'ах:**
- Будет представлять собой имплант лояльности НТ, с очень редким мерцанием в красный цвет.

**Воздействие на жертву:**
- По аналогии с имплантом НТ выдает брейндамаг при вкалывании.
- С интервалами отправляет сообщение имплантированному о любви к Синдикату.

**В случае извлечения импланта:**
- Человек теряет трейторку, и забывает все с момента вкалывания импланта до момента его удаления.

**Отображение в advanced medscanner:**
- Undefined implant

**Выдается ли аплинк имплантированному?**
- Нет

**Реакция на ЕМП**
- Теряется трэйторка, начинаются галлюцинации и сообщения о том, что ты хочешь убить человека, который вколол тебе имплант. И это продолжается до тех пор, пока имплант не вытащат.
</details>

**Информация под спойлером может обновиться.**

**Comment by KIBORG04** [comment]
Может просто будет вера в синдикат, а не трейторка?

**Comment by maxyo** [comment]
> Может просто будет вера в синдикат, а не трейторка?

Реализация трейторкой проще.

**Comment by Motzord** [comment]
>Имплант НТ заменяется имплантом синдиката.

Лично я против, ведь тогда все массово будут ловить капитанов и всаживать им триторимплант.


Б

**Comment by maxyo** [comment]
>А что будет если человек потеряет имплант? С него снимется триторка?
Предлагаю при потере импланта: "You have been brainwashed!"

Тогда это оставляет вколовшего имплант безнаказанным.

**Comment by Motzord** [comment]
> > Предлагаю при потере импланта: "You have been brainwashed!"
> 
> Тогда это оставляет вколовшего имплант безнаказанным.

Что в принципе логично, и справедливо, иначе будет лютый ролькохант

**Comment by KIBORG04** [comment]
Мне идея понравилась. Мб попробую сделать, но я говно-кодер. Может через пару недель и напишу.
Я тоже против о замене НТ-импланта на синдикатовский

**Comment by ZVee** [comment]
Учитывая что триторы добавляются автоматически и с учетом разных условий во все режимы, возможно это не очень хорошая идея, т.к предположим в игре уже 4, каждый из них купит хотя бы по одному импланту и это уже в два раза больше триторов минуя какие-нибудь проблемы вида что возможно в раунде уже и так много ролей.
А второе - ловля капитанов это не страшно, страшнее это имплант по дружбе.

**Comment by KIBORG04** [comment]
> 
> 
> Учитывая что триторы добавляются автоматически и с учетом разных условий во все режимы, возможно это не очень хорошая идея, т.к предположим в игре уже 4, каждый из них купит хотя бы по одному импланту и это уже в два раза больше триторов минуя какие-нибудь проблемы вида что возможно в раунде уже и так много ролей.
> А второе - ловля капитанов это не страшно, страшнее это имплант по дружбе.

Так если имплант работает так же как и емагнутый борг, то и правила сервера будут идти не на имплантированного, а на дающего приказ. И сделать цену на имплант 20 кристалов

**Comment by ZVee** [comment]
Боргов ограниченное кол.во (да их можно скрафтить, но придется и игрока найти, помимо крафта и ресурсов на самого борга) и некоторые трудности к достижению результата.

**Comment by KIBORG04** [comment]
А имплант будет как замена всех предметов, если будет стоить 20. Да и человек будет слабее обычного емагнутого борга

**Comment by ZVee** [comment]
Насчет слабее или сильнее это все сложно и в скилл игрока уходит, но борга могут попросту вырубить через консоль, забить эми, задизориентить флешкой, критануть модуль с егана важный, на худой конец обрезать провода контроля на дверях там.
На хуманов уже свои приколы, но хуман все же имеет больше свободы.
Но речь не про кто сильнее или слабее, а то что давать контроль к выдаче роли обычным игрокам возможно не самая лучшая идея, т.к в раунде может быть попросту не до нового хаоса (администраторам тоже больше возни).

**Comment by maxyo** [comment]
> Что в принципе логично, и справедливо, иначе будет лютый ролькохант

Немного подумав, поменял свое мнение. Стоит стирать память после удаления импланта.

**Comment by Motzord** [comment]
сама идея забавна, но тритору дается 20-28 тк, что при умелом использовании может обратить всю станцию в таторов. по схеме:
а) Вербуем кого угодно
б) Заставляем его купить синди-имплант
в)вербуем еще одного
г) повторяем до бесконечности

**Comment by maxyo** [comment]
> Но речь не про кто сильнее или слабее, а то что давать контроль к выдаче роли обычным игрокам возможно не самая лучшая идея, т.к в раунде может быть попросту не до нового хаоса (администраторам тоже больше возни).

Звучит разумно, но на практике - уже есть режимы вроде культа и ревы, в которых только другие игроки и решают дать роль или нет. И в среднем режимы протекают без лютого треша.

К тому же по сравнению с тем же культом, в котором человек получает томик с рунами, имплант имеет больше минусов чем плюсов. Я думаю что стоит сделать следующую реакцию на ЕМП импульс: теряется трэйторка, начинаются галлюцинации и сообщения о том, что ты хочешь убить человека, который вколол тебе имплант. И это продолжается до тех пор, пока имплант не вытащат. Это первый минус, так же думаю стоит сделать 100% шанс на значительный брейндамаг при вкалывании. Это затруднит имплантирование капитанов и хосов, потому что резко отупевшая глава будет привлекать много внимания. Следующий минус это высокая цена, 13 очков. Это даст возможность купить имплант лишь один раз, потратив больше половины очков. И еще очень большой минус, если имплантируют хоса или кэпа, это то, что имплант будет моргать красным при просмотре через худ.

Исходя из вышесказанного, я думаю что удачное имплантирование без быстрого раскрытия, получится только в достаточно редких случаях.

**Comment by SomeUselessGuy** [comment]
Давать аплинк за имплант? .-.

**Comment by ZVee** [comment]
>Звучит разумно, но на практике - уже есть режимы вроде культа и ревы, в которых только другие игроки и решают дать роль или нет. И в среднем эти режимы протекают без лютого треша.

Есть еще один момент касательно баланса кол.ва одинаковых по смыслу фич, сколько уже ролей которые могут давать другим роли?
Не стоит пытаться одни и теже идеи внедрять в каждый режим. Триторы например и так имеют отдельный режим, а еще и сами по себе спавнятся в каждом другом режиме, плюс могут емагать боргов. К тому же агентами не становятся вот так по щелчку чудо-импланта как это здесь обыгрывается, тогда как со стороны емагнутого борга тут даже и не придраться будет.

А так сама идея неплоха, но проблема копипасты идеи, и того же нюанса что выходит агентов просто штампуют в миг импалнтом, фиксят мозг в случае проблем и все, как-то слишком просто?

>И еще очень большой минус, если имплантируют хоса или кэпа,

Это не просто минус, а вывод довольно важной профессии из игры (хотя каких-нибудь плохих хосов с капитанами сгонять наверно прикольно).

Да и в целом, как бы там с этими нюансами этот имплант просто не превратился бы в средство грифа для тех или иных игроков, ну т.е такого левого капитана там можно взять и загрифонить например хосу который заметит что у капитана имплант какой-то левый и наверно это самозванец который очень хорошо продумал нюансы регистрации и т.д. Или по приколу под эми подставить такого если просечь что у него имплант, в общем можно и подстав напридумать. Но ладно, это все теории.

**Comment by maxyo** [comment]
>Есть еще один момент касательно баланса кол.ва одинаковых по смыслу фич, сколько уже ролей которые могут давать другим роли?

Каждая роль, имеющая возможность выдать роль делает это по-своему, уникально. За счет этого все способы добавления роли не сливаются в одну единую закопипащенную фичу. В случае импланта уникальность будет так же соблюдена.

> К тому же агентами не становятся вот так по щелчку чудо-импланта как это здесь обыгрывается, тогда как со стороны емагнутого борга тут даже и не придраться будет.

Думаю в данном случае жертву импланта не совсем верно будет называть агентом, он скорее расходный материал или заложник. И, вероятно, стоит сделать уточнение, либо при имплантировании, либо в статье к трейтору, о том, что, ставший тритором с помощью импланта человек, не получает знания, которые имеет нормальный трейтор.

>Это не просто минус, а вывод довольно важной профессии из игры (хотя каких-нибудь плохих хосов с капитанами сгонять наверно прикольно).

И все же убить проще чем нормально имплантировать. К тому же имплант достаточно просто удаляется и глава снова в строю.

Насчет грифа:
Мне кажется то что ты перечислил можно применить (почти) к любой роли. Это уже не во власти разработчика, и даже не во власти админа. Если игрок захочет загриферить кого-то, он это сделает. Имплант даст новые возможности для грифа, но, думаю, что это станет лишь одним из вариантов грифа, для того кто уже начал гриферить. К тому же ЕМП импульс не так-то просто устроить.

**Comment by aIweiss** [comment]
можно сделать как на гунах mindslave - ограниченными по времени. 

на тех, у кого стоит лоялти, лучше эффект не распространять (но можно сделать так, что синди-имплантированному плевать на лоялти, пока не кончится действие синди-импланта)

**Comment by KIBORG04** [comment]
@maxyo 
Прочтешь свою почту или сюда скопировать?
