### ISSUE TITLE
Забор крови из вены протеза

### ISSUE THREAD

**Issue by Maggot4th** [TauCetiStation/TauCetiClassic#3991]
#### Подробное описание проблемы
При использовании IV drip в режиме забор с пустым пакеты крови на нем происходит забор крови из тела
#### Что должно было произойти
В чате высветилось сообщение: "You trying to inject someones prothetic limb!"
#### Что произошло на самом деле
Пакет с кровью начал наполняться
#### Как повторить
В IV drip вставить пустой пакет с кровью
Перевести IV drip в режим Draw
Выбрать на кукле протезированную конечность 
Перетащить IV drip на спрайт персонажа

**Comment by AndroBetel** [comment]
оно, если я не ошибаюсь, не зависит от прицеливания на кукле, так что вполне возможно что ты кровь берешь из сосудов в шее, например.
