### ISSUE TITLE
Кифоторин не метаболизирует.

### ISSUE THREAD

**Issue by Stixonya** [TauCetiStation/TauCetiClassic#4003]
#### Подробное описание проблемы
После создания и использования кифоторина на раненом ОСБ, слипер отображал что Кифоторин не исчезает из крови в течение 8 минут реального времени.
#### Что должно было произойти
Кифоторин должен был уменьшаться с тиком на 0,07 единиц. (Информация взята с wiki https://wiki.taucetistation.org/Guide_to_Chemistry )
#### Что произошло на самом деле
Он не метаболизировал.
#### Как повторить
Использовать кифоторин.
#### Дополнительная информация:
Прилагаются скриншоты с интервалом в несколько секунд. (Больше сделать не получилось, так как ОСБ сбежал из слипера).
![Kyf](https://user-images.githubusercontent.com/55360868/64926075-d0228180-d801-11e9-8c6f-ed40024e40e6.jpg)
![kyf2](https://user-images.githubusercontent.com/55360868/64926084-e7616f00-d801-11e9-9c60-b863e647c0fd.jpg)

**Comment by FelixRuin** [comment]
голодный значит

**Comment by ZVee** [comment]
>голодный значит был ОСБ

>слипер отображал что Кифоторин не исчезает из крови в течение 8 минут реального времени

То что он не растворялся все равно выглядит некорректным. Так что видимо искали один баг, а нашли совсем другой.

**Comment by FelixRuin** [comment]
предположу что это сделано с целью защиты от выдачи химии в молоко, да и что сказать, наноботы, они могут втеории

**Comment by ZVee** [comment]
Там просто в комменте ошибка, типа должны перестать работать но продолжать расходоваться, а код указывает обратное. Возможно кстати в идеале надо не вообще тормозить трату, а понижать сильно, т.к при желании это можно и под контроль игроком использовать.

**Comment by Motzord** [comment]
Не баг, а механ кифоторина, он не будет метаболизироваться, пока в кукле нет нужного количества нутриентов-крови
