### ISSUE TITLE
[Proposal] Воксы случайно стреляют в союзников сразу после начале раунда

### ISSUE THREAD

**Issue by FridrihRichter** [TauCetiStation/TauCetiClassic#4011]
Во время спавнов у воксов-солдат в активной руке сразу появляется винтовка, стреляющая болтами. Воксы солдаты случайно стреляют в своих союзников, ломая им кости или делая летальные артериальные кровотечения. Обычно это происходит, когда человек пытается закрыть окно с заданиями или просто переключиться на окно сосаки. Пожалуйста, заберите у них эти винтовки и положите болтометы на склад с остальным снаряжением.

**Comment by Lizurt** [comment]
В основном согласен, но я бы просто с начала раунда экипировал их вещмешками и туда бы клал оружие. Все равно вещмешков хватит на всех воксов, новички их не берут. А так решиться 2 проблемы

**Comment by Akellazp** [comment]
Можно просто переложить им пушки в другую руку
