### ISSUE TITLE
[Proposal] Воксы голодают на своем корабле

### ISSUE THREAD

**Issue by FridrihRichter** [TauCetiStation/TauCetiClassic#4013]
Зачастую, воксам приходится выполнять свою миссию больше получаса, из-за чего они начинают голодать. 
У меня встал вопрос, почему на корабле воксов нет совсем никакой еды?
Пожалуйста, дайте воксам хотя бы пару коробочек с донк покетами, ведь они могут питаться только на своем корабле ( в азотной атмосфере). А если им придется воровать со станции лишние торговые автоматы или еду из столовой - это приведет еще к большим жертвам и конфликтам.

**Comment by GreyGunner** [comment]
А я ведь предлагал сделать голод более опциональным... Чтобы за смену в среднем достаточно было поесть всего один раз....

Я не шарю что жрут воксы, заказывай - добавлю. Одну коробку донк покетсов и все?

**Comment by FridrihRichter** [comment]
Они вроде как той же едой, что и экипаж питаются. Я  пончиками наедался в тюремном блоке и ловил отравление от кислорода. По идее воксам нужна сытная еда, которую не нужно разогревать в микроволновки, как те же донк покеты. Ведь у них нет микроволновки.
