### ISSUE TITLE
[Proposal] Предысторию обжективам!

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4022]
#### Подробное описание проблемы
Чаще всего, триторам дают задание украсть какой-либо предмет или убить/покалечить кого либо, но никому не понятно зачем ему кого-то калечить и для чего. Посему я предлагаю добавить процедурно генерируемую историю тритору и жертве, что даст возможность отыгрыша. Приведу аргументы.
а) Жертва совершенно не знает чем она провинилась перед синдикатом, что не очень интересно.
б) Тритор совершенно не знает, почему ему надо искалечить/убить жертву.

в) Тритор может иметь цель "украсть трусы [главанейм], но синдикат почему-то не объяснил ему, что это опозорит НТ/ пригодится в дальнейшем.

Я считаю что небольшая предыстория тритора по типу
 "Клоун когда-то обрызгал с водяного пистолета вашего начальника и поэтому вы должны переломать ему руки" 
А жертве "Когда-то вы обрызгали с водяного пистолета какого-то важного парня с дипломатом и он поклялся вам отомстить"

Решит проблему и добавит ролеплейности. (И капельку ролькохантинга)

**Comment by EdlerN** [comment]
Есть такая штука как "открытая предыстория". То что этого не прописано означает лишь то, что игроки в состоянии сами додумать, что и как произошло. Почему их кукла нужна синдикату, почему синдикат нанял именно их и всякое такое.

Это не решение проблемы. И ты убиваешь этим ту самую ролеплейность в пользу аркадности. И цирка какого-то.

**Comment by Motzord** [comment]
> Есть такая штука как "открытая предыстория". То что этого не прописано означает лишь то, что игроки в состоянии сами додумать, что и как произошло. Почему их кукла нужна синдикату, почему синдикат нанял именно их и всякое такое.
> 
> Это не решение проблемы. И ты убиваешь этим ту самую ролеплейность в пользу аркадности. И цирка какого-то.

Но чаще всего триторы убивают свою жертву молча, жертва даже не догадывается что она цель. (Да и с открытой предысторией, скорее всего две версии будут отличаться друг от друга)

**Comment by EdlerN** [comment]
Им все так же будет наплевать.

С открытой предысторией одна сторона может подыграть другой, если что. И это работает. Ну, если у людей в голове больше одной извилины

**Comment by Motzord** [comment]
Ладно, понял, закрываю
