### ISSUE TITLE
Однабаллоная бомба работает некорректно.

### ISSUE THREAD

**Issue by da-kiselev** [TauCetiStation/TauCetiClassic#4025]
#### Подробное описание проблемы 
Решил затестить однобаллонку, собирал как по инструкции, прикручивал к баку игнитер с сигналлером, а после использовал сварку. Пробовал разные рецепты, закачивал в него:
1. Форон с кислородом.
2. Горячий форон с кислородом.
3. Просто горячий форон.
Как итог, при подачи сигнала, вылетала искра и бак пропадал, без следа, даже в логах ничего нету.
#### Что должно было произойти
Однобаллонка должна была взорваться или не исчезать.
#### Что произошло на самом деле
Однобаллонка исчезает без следа, в логах не видно.
#### Как повторить
Собрать однобаллонку по инструкции: сигналлер прикручиваешь к игнитеру, все это к баку с фороном, в котором уже есть газ, использовать сварку и подать сигнал.
#### Дополнительная информация:
Ради интереса полазил в коде бомбы, я, в силу своих плохих навыков в программировании мало что понял, но: чётко написано, что при взрыве должен выдаваться лог админам; температура взрыва от 400 градусов, у меня была 5к; никаким образом бесследно исчезать она не должна, либо взрыв, либо в чат: «beep beep».

**Comment by Motzord** [comment]
Тестил однобаллонки, все работает, там не только проверяется температура но и высчитывается по непонятным взятым с потолка формулам количество "топлива"

Собственно тебе нужно не только горячий форон но и достаточное количество форона/кислорода чтобы был бубух, а чем горячее газ тем меньше молей поместится в баллоне.

Можно закрывать
