### ISSUE TITLE
Кукла перемещается на стол без перетаскивания спрайта.

### ISSUE THREAD

**Issue by Virusolog410** [TauCetiStation/TauCetiClassic#4026]
#### Подробное описание проблемы
Кукла должна перемещаться на стол с помощью перетаскивания спрайта. Однако в данный момент она перебегает с пола на стол как мышь или дрон.
#### Что должно было произойти
Кукла должна переместится на стол перетаскиванием спрайта.
#### Что произошло на самом деле
Она бегает с пола на стол без перетаскивания
#### Как повторить
Зайти за хумана, упереться в стол и побежать(в направлении стола). Вероятно, хуман пробежит через стол, будто его там нету.
#### Дополнительная информация:
Если усадить хумана на стул, то теперь на стол не получится забежать как мышь/дрон. Надо будет перетаскивать спрайт как раньше. Однако, если сесть на стул ещё раз, то проблема вернется. И так можно повторять n раз.
UPD. Такая же ситуация и со стеклянными столами, которые не ломаются, если на них забежать.

**Comment by Sakuya-Izayoi** [comment]
не актуально
