### ISSUE TITLE
[proposal] Добавить антагам возможность получения информации о жертве

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4032]
Ввести антагам, к примеру триторам предмет, который дает возможность получить папку с личным делом жертвы куда будут входить 
* Медзаписи
* Записи Службы безопасности
* Записи из отдела кадров.

Стоимость данной фичи небольшая 1-2 ТК.

В чем преимущество: 
1. **Татор получает красивую возможность** шантажировать или ударить по слабой точке жертвы. (Ну скажем, у капитана механическое сердце и эми граната подходит как нельзя кстати)
2. **Добавит логичности**: Неужели синдикек посылает суперподготовленого агента, убить хуйзнает кого, дав ему только имя, фамилию и профессию жертвы.
3. Добавит все таки оригинальности убийствам, и тому же самому "ролеплею" (если конечно жертва и татор не играют в победку)
4. Метод "узнать о своей жертве" будет использоваться чаще, ведь раньше, чтобы собрать полную информацию о цели, как в "суперкрутых шпионских фильмах", приходилось вломится минимум в три отсека повышенной важности, что сложнее чем просто встретить жертву в коридоре и закликать револьвером.

**Comment by ViDLiathan** [comment]
Во-первых, никто не заполняет настолько подробно, а во-вторых, должно быть бесплатно.

**Comment by Motzord** [comment]
> Во-первых, никто не заполняет настолько подробно, а во-вторых, должно быть бесплатно.
> 
> А еще такую инфомацию могут выдавать нюкерам, которые купят звонок другу-тритору.

Ну подробно не подробно, а если не ошибаюсь в стандартных медзаписях уже указаны роботизированные/поломанные органы конечности, даже без заполнений.

И как раз таки данная фича либо даст еще один аргумент для заполнения записей и проработки персонажа, либо посыл победкоигрокам быстро чистить свои записи, а то вычислят и убют блин

**Comment by ZVee** [comment]
Так уже есть такая возможность - консоли на станции (да, можно спалиться пока пытаешься в них залезть, но в этом и суть - что инфа не валяется на тарелке). А с воплощением этой идеи - они попросту не нужны будут, т.к всегда удобнее купить (а если еще и бесплатно...) готовую и стелсовую по факту инфу.

**Comment by Motzord** [comment]
> Так уже есть такая возможность - консоли на станции (да, можно спалиться пока пытаешься в них залезть, но в этом и суть - что инфа не валяется на тарелке). А с воплощением этой идеи - они попросту не нужны будут, т.к всегда удобнее купить (а если еще и бесплатно...) готовую и стелсовую по факту инфу.

Так поэтому таторы никогда и не желают получать инфу о жертве, ведь это надо много куда ломится, много каких консолей емагать, что обойдется в копеечку. Проще тогда закликать арбалетом, чем думать, механизированные ли у него конечности, любит ли жертва бухать и прочее.

Покупка инфы за 1-2ТК даст возможность татору хоть что-то узнать и возможно как-то разнообразить геймплей

**Comment by Ambassadoing** [comment]
Не позволит, у 95% игроков личные записи чисты, как совесть новорождённого. Чтобы эта фича имела смысл, надо либо как-то заставлять ВСЕХ заполнять личные записи хотя бы худо-бедно, либо одно из двух. А так - ерунда.

**Comment by Motzord** [comment]
> Не позволит, у 95% игроков личные записи чисты, как совесть новорождённого. Чтобы эта фича имела смысл, надо либо как-то заставлять ВСЕХ заполнять личные записи хотя бы худо-бедно, либо одно из двух. А так - ерунда.

сейчас как раз записи заполнять немного бесмысленно, а так у народа появится возможность заполнить записи хотя бы для того, чтобы татор не закликал пистолетом, а че-нибудь интересное сделал

**Comment by Ambassadoing** [comment]
> чтобы татор не закликал пистолетом, а че-нибудь интересное сделал

...И татор всё равно закликает пистолетом, а в записи заглянуть даже не подумает. Ты вообще представление имеешь о среднестатистическом таторе?

**Comment by Motzord** [comment]
> > чтобы татор не закликал пистолетом, а че-нибудь интересное сделал
> 
> ...И татор всё равно закликает пистолетом, а в записи заглянуть даже не подумает. Ты вообще представление имеешь о среднестатистическом таторе?

Среднестатистический татор и не купит информацию, если собрался закликивать револьвером. А татор здорового человека обязательно воспользуется данной фичей.

**Comment by Ambassadoing** [comment]
Это не так работает, Мотцорд. НИКТО по-волшебству не кинется заполнять свои записи и никто из триторов не станет что-то там *придумывать*. Если фичу добавят, то будет примерно так:
* Один-два человека (В ЛУЧШЕМ СЛУЧАЕ) удосужатся заполнить свои записи и с горечью обнаружат, что их записи всё равно никто не читает и их как закликивали молча с пистолета, так и закликивают.
* Один-два (опять же, в лучшем случае) тритора чисто из любопытства купят личное дело своей жертвы (или личные дела всего экипажа, хрен знает) и обнаружат там одно из двух: ничего или абсолютно бесполезные мусорные сведения, что равноценно "ничего". После пойдут всё также закликивать жертву пистолетом.

**Comment by ZVee** [comment]
>Чтобы эта фича имела смысл, надо либо как-то заставлять ВСЕХ заполнять личные записи хотя бы худо-бедно, либо одно из двух.

Можно пойти на очень безумный шаг - запретить вход если не заполнены эти записи. Конечно покажется что это занудно, особенно для тех у кого много персонажей, но с другой стороны это также даст пищу для размышлений владельцам своих персонажей и толчком к тому, чтобы придумать какой никакой бек своего персонажа (на мой взгляд это все же больше хорошо, чем плохо). Однако игрокам придется все же как-то следовать тому, что они опишут (но это уже на совесть можно оставить).
Сам переход можно сделать плавный - дать скажем 2-3 реальных месяца игрокам на решение этого вопроса и после уже включить запрет.

**Comment by Motzord** [comment]
> > Чтобы эта фича имела смысл, надо либо как-то заставлять ВСЕХ заполнять личные записи хотя бы худо-бедно, либо одно из двух.
> 
> Можно пойти на очень безумный шаг - запретить вход если не заполнены эти записи. Конечно покажется что это занудно, особенно для тех у кого много персонажей, но с другой стороны это также даст пищу для размышлений владельцам своих персонажей и толчком к тому, чтобы придумать какой никакой бек своего персонажа (на мой взгляд это все же больше хорошо, чем плохо). Однако игрокам придется все же как-то следовать тому, что они опишут (но это уже на совесть можно оставить).
> Сам переход можно сделать плавный - дать скажем 2-3 реальных месяца игрокам на решение этого вопроса и после уже включить запрет.

Согласен, тем более я заметил за последнюю неделю, количество "чайных" раундов возрастает. Неужели держим курс на РП?

**Comment by GreyGunner** [comment]
Помня, как я начинал... Я бы предложил, чтобы обязательность заполнения была начиная, скажем, с 6000 минут игры на сервере. Новичкам и без того тяжко... А тут они подумают ещё, что им надо пересчитать весь-весь бэк, чтобы попробовать поиграть лысиком умерев от непонятно чего

**Comment by SomeUselessGuy** [comment]
> Кроме того, у него может быть указано шахтер (вроде логично указать в трудовой подобное) а рандом забросить его на учёного

В таком случае надо делать что-то на уровне [job] и [head], для указания работы и, собсна, главы его отдела
