### ISSUE TITLE
На старте сервера инициализируются тысячи мусорных объектов

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#4043]
``\obj\`` с ``name="obj"`` и в нулевых координатах, стактрейсы показали на

https://github.com/TauCetiStation/TauCetiClassic/blob/64c3898eb1cd42aac36312e8fad3a55b2818a0b6/code/game/objects/items/weapons/storage/storage.dm#L27

https://github.com/TauCetiStation/TauCetiClassic/blob/4a4f2fd5e164e1d31bf81b594c16f8b7d4747ad4/code/game/objects/items/weapons/storage/storage_ui/default.dm#L46
(^ и там еще много таких холдеров)

возможно где-то еще есть виновные, но пока их за стораджами не видно...

**Comment by volas** [comment]
> А почему это вдруг на себя внимание взяло?

На тестовом прогоне шляпы из 1к вещей десятая часть были эти объекты, это было возмутительно

**Comment by ZVee** [comment]
Какой кошмар, это надо срочно прекратить!

---

А вообще, там таких улучшений по всему коду можно сделать, однако не везде возможно это правильно или хорошо. Со сторажами сделать это в принципе нормально - потому что создание не шибко дорогое, чтобы инитить его всем сторажам при поднятии сервера.

Еще я думал о том, чтобы эти объекты удалялись когда их не используют, но если говорить в ключе простой реализации типа - юзер прекратил смотреть в сумку и мы сразу удалили ГУЙ - то наверно это не очень хороший вариант в ситуации если скажем каждые 15 секунд будет кто-то заглядывать и мы будем все время переделывать постоянно объекты. Но с другой стороны - сумки которые возможно никто уже не откроет и их объекты ГУЯ висящие до смерти самой сумки или следующего раунда тоже как-то может ненормально. Но думаю пофиг, и сойдет просто создание по требованию.
Однако так или иначе в середине раунда описанная тобой проблема когда пользователи по на открывали сумки все равно в той или иной степени может существовать.

**Comment by volas** [comment]
Я думаю, неправильно просто использовать голый ``/obj/``, можно было бы создать какой-нибудь свой плейсхолдер тип или взять ``/obj/screen`` или хотя-бы ``/obj/effect``

**Comment by ZVee** [comment]
>неправильно просто использовать голый /obj/

`/obj/screen`, `/obj/effect`- а это кстати докину в сторажи, подумаю только какой лучше. Пока к screen больше склоняюсь.

**Comment by ZVee** [comment]
Посмотрел на `/obj/effect`, там сидит обновление чанков камеранета. Конечно для сторажей это не будет работать, т.к они не на турфе, но для меня это выглядит как класс для другой цели. Однако я бы перенес возможно именно на эффекты, но там остальные куски сидят под `screen` и в целом наверно это более корректный класс все же, т.к для худа предназначение.
