### ISSUE TITLE
[Proposal] Новые способы суицида.

### ISSUE THREAD

**Issue by da-kiselev** [TauCetiStation/TauCetiClassic#4045]
Приветствую, предлагаю ввести новые способы суицида, кроме как пулю в рот, (прошу заметить, именно в рот, хотя правильнее всего в висок, ибо в рот есть шанс выжить неплохой), и механ клик по кукле.

### Примеры:
1. Добавить возможность сделать из кабелей петлю, чтобы можно было повеситься, имеется низкий шанс того, что голова при удушье оторвётся, в истории бывали случаи, когда такое случалось. Согласитесь, открывается новая возможность для трейтора, как не делать пиу-пиу, а действовать скрытно.
2. Перерезание вен чем-то острым, но не через механ заклик, а как с выстрелом в рот, проходит некоторое время и вены перерезаются, имеется низкий шанс того, что перережешь сухожилия и нельзя будет двигать рукой, а предметы выпадают.
3. Пронзить себя чем-то острым, нож в сердце или выпускание кишок из брюха, первое довольно часто происходит. Высокий шанс того, что при попытке пронзить себе сердце, просто напросто промахиваешься и в тебе остаётся нож.

### Плюсы:
1. Можно будет  «красиво» уйти из жизни.
2. Больше не будет нелепых суицидов, когда человек забивает себя до смерти коробкой.

### Минусы:
Резкий и временный скачок суицида на станции.

**Comment by ZVee** [comment]
Есть нюанс который возможно не знаешь (либо не обозначил его в описании), суицид работает только для ролей, и это одна из причин, почему я в принципе не одобряю в целом эту систему и считаю что ее лучше просто выпилить.
Вторая проблема - это очень много мелкой работы для такой фичи, ведь по хорошему, к каждому объекту нужен индивидуальный подход, а потом пользователи еще и должны знать с чем работает а с чем нет и иметь собственно этот предмет.
По сути выходит фича которая иногда может по блистать красивым IC текстом. Конечно можно это все сделать довольно круто и корректно с визуальной точки зрения добавив еще и возможно элементов анимирование. Но в итоге это все еще потом и мейнтейнить со временем и дописывать новые с вводом новых предметов.

Единственное, можно просто сделать генерик типы, без индивидуальности к каждому предмету.
Вида - тупыми предметами одно, острыми другое, стрелковами третье и в таком духе, т.е прям глобальные методы которые просто читают некоторые переменные.

Но да, еще остается нюанс все еще, то что эта фича исключительно для антагов, и не дают ее всем по понятным причинам.

**Comment by aIweiss** [comment]
мне кажется, предложивший говорил не о суициде через /suicide

**Comment by ZVee** [comment]
С этим еще сложнее тогда, можно просто подтолкнуть людей к не очевидному - пытался починить себе проводами протез, а вместо этого повесился, потому что совпали условия. Плюс трудности в донесении до игроков всю эту информацию вида - что и с каким предметом должно быть включено на кукле (и еще не конфликтнуть там с каким-нибудь другим действием которое уже есть). Команда в этом плане намного облегчает всю эту суть.

Но нюанс все еще остается в том, что как правило нет повода к этим действиям и все еще остается проблема мейнтейнинга, причем через клики еще более муторного скорее всего.

Однако я не говорю что это плохо, просто слишком много возни может возникнуть и решений к тому, как это все сделать корректно с доносом до игроков и учетом уже существующих взаимодействий.

**Comment by da-kiselev** [comment]
Команда suicide бред полный, какой-то механ, поэтому я и предложил другие способы суицида, а не: «Вася Пупкин забил себя ящиком для инструментов насмерть», или: «Антаг Антагович перестал дышать без причины», это кстати в реальности не провернуть, сработает защитный механизм.

**Comment by ZVee** [comment]
>а не: «Вася Пупкин забил себя ящиком для инструментов насмерть»,

Это все равно запрещено как правило, ну не найдешь адекватной причины в большей части раундов почему вдруг можно. Но как я уже говорил, все равно в итоге в тех сторону врезаемся.

>или: «Антаг Антагович перестал дышать без причины»

У антагов не не без причины, а представь что какой-нибудь нано-имплант, но в целом зависит от предмета, а то что можно сделать и без - ну это второй вопрос.


А команда бред для тебя, потому что тебе все равно с точки зрения кода и проблем с которыми кодерам потом иметь, а еще момент в том, что потом сам же как игрок будешь не знать как выполнить то или другое с таким-то предметом, и в итоге и будет все равно тоже самое забивание себя ящиком. Плюс с командой не надо заморачиваться над условиями при которых это все должно проходить с каждым предметом вида - выбери на кукле рот, возьми такой-то предмет. Потому что для каждого под копирку это условие не выйдет использовать, а значит надо индивидуально подходить и я уже расписал что за проблемы с этим.

**Comment by aIweiss** [comment]
палю фичу: на станции можно приготовить снотворное и яд в химии, собрать усыпляющую смесь в атмосферке/токсинах, как относительно безболезненные способы суицида. относительно - потому что в реальности надо расчитывать серьезно и с врачами, но в игре сработает.

**Comment by Akellazp** [comment]
> «Антаг Антагович перестал дышать без причины»
Не без причины, а от откусывания себе языка и захлебывания кровью
