### ISSUE TITLE
Невозможно надеть предмет на куклу

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4047]
#### Подробное описание проблемы
Кодеры что-то там накодили мержеры чет там смержили и произошло чудо, на куклу больше нельзя надевать предметы, зато снимать можно
#### Что должно было произойти
Предметы должны надеваться и сниматься
#### Что произошло на самом деле
Хирурги негодуют, баллон и маску на пациента не напялить, воришки негодуют, карту/пда после "одалживания" нельзя вернуть
#### Как повторить
Попролбуйте что-нибудь надеть на куклу

**Comment by volas** [comment]
Только на первом сервере?

**Comment by Motzord** [comment]
> Только на первом сервере?

судя по всему да. Ишью выше тоже происходило со мной на первом

**Comment by LudwigVonChesterfield** [comment]
#4040 

100% уверен в этом. Там рантайм если натягивать шмотки на кого-то.
