### ISSUE TITLE
Легкие перестали рваться

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4048]
#### Подробное описание проблемы
Кодеры чет там закодили, мержеры чет там смержили легкие игнорируют вакуум и не рвуться
#### Что должно было произойти
Они должны были порваться
#### Что произошло на самом деле
Дважды случайно вышел в открытый космос без скафандра, доковылял до коридора и к моему удивлению легкие не порвались и в принципе я не помер
#### Как повторить
Зайдите в разгурму без скафндра и проверьте порванность легких

**Comment by Lizurt** [comment]
Легкие, если не ошибаюсь, рвутся не сразу. Каждый вдох имеет 5% шанса, что легкие порвутся, если воздуха недостаточно.

Как долго ты ходил по вакууму?

**Comment by Motzord** [comment]
> Легкие, если не ошибаюсь, рвутся не сразу. Каждый вдох имеет 5% шанса, что легкие порвутся, если воздуха недостаточно.
> 
> Как долго ты ходил по вакууму?

Первый раз пробежался/проползался/провалялся в полностью разгермленых техах церкви примрено с полторы минуты

Второй раз — 10 секунд в открытом шпессе

**Comment by Lizurt** [comment]
Ну вот, примерный шанс не порвать легкие за 90 секунд нахождения в вакууме - 10%.
Примерный шанс порвать не порвать легкие за 10 секунд нахождения в вакууме - 77%

**Comment by SpaiR** [comment]
У всего есть свой шанс
