### ISSUE TITLE
Искейп поды ломают гринтекст

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4053]
#### Подробное описание проблемы
При эвакуации на подах в церкви, гринтекст не засчитывается, считается что тритор не покинул станцию
#### Что должно было произойти
Traitor has succes
#### Что произошло на самом деле
Traitor has succes
#### Как повторить
Эвакуируйтесь за тритора через поды
#### Дополнительная информация:
В заданиях написано выбраться шатлом или подами

**Comment by LudwigVonChesterfield** [comment]
![image](https://user-images.githubusercontent.com/17705613/65710450-bbfd4080-e09b-11e9-8790-2858b410f975.png)

1) success, а ещё лучше "Traitor is successful"
2) у тебя очепятка

**Comment by ZVee** [comment]
Поды и не должны считать задания, они для эвакуации и просто отстреливаются на безопасное расстояние с последующим смыслом что возможно подберут спасатели - это если описывать с точки зрения происходящего (если я конечно не упустил чего, и там не сделали механику новую - чего конечно делать не стоит/не надо).

>В заданиях написано выбраться шатлом или подами

Тут надо текст подправить в заданиях.

**Comment by FelixRuin** [comment]
подом шанс что ты прилетишь, не надо тут... и такое чувство чем больше народу, тем выше шанс (или это работает как вера орков)

**Comment by ZVee** [comment]
Это мы оставляли эти 5% шанса и меняли все это когда-то.

**Comment by Motzord** [comment]
Меняйте шанс или задание татора. В принципе искей под должен работать, агента заберет какой-нибудь синдикат красава на синдикат космомаршрутке

**Comment by SpaiR** [comment]
Не баг, так задумано. Что надо править - текст задания, но "искейп поды" тут не при делах.
