### ISSUE TITLE
[Proposal]Сделать макс использования мылу

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4056]
#### Подробное описание проблемы
Мыло вечное, мыло вечно чистит, вечно роняет, вечно крутое
#### Что должно было произойти
Мыло грязнеет, становится меньше, теряет свою охеренность
#### Что произошло на самом деле
Мыло вечно чистое, хотя побывало в во всех задницах

**Comment by FelixRuin** [comment]
Собственно суть мыла в том что оно всегда чистое и всегда чистит пока не используется окончательно
а чтоб использовать мыло надо неплохо так постараться, этож чёрт подери космо мыло из жира ассистентов, оно должно быть долговечным
