### ISSUE TITLE
Перк стронг майнд не работает

### ISSUE THREAD

**Issue by FatFatFat1** [TauCetiStation/TauCetiClassic#4059]
#### Подробное описание проблемы
Перк не работает
#### Что должно было произойти
Галюны не бьют если у меня стронгмайнд
#### Что произошло на самом деле
Бьют
#### Как повторить
Взять стронгмайнд и выпить варлока и ждать галюны

**Comment by FelixRuin** [comment]
...
какого именно рода галюны? цветной экран? или появляющиеся мобы, оружие, дыры в полу?

**Comment by FatFatFat1** [comment]
мобы
