### ISSUE TITLE
[Proposal]  UPD 2.0 Интегрированный шлем в РИГ и интегрированный баллон, также добавить полоску ХП на РИГ’и

### ISSUE THREAD

**Issue by da-kiselev** [TauCetiStation/TauCetiClassic#4062]
Приветствую, предлагаю интегрировать шлемы РИГ’ов в костюм, хотя бы в инженерный, согласитесь, гораздо удобнее по нажатию одной кнопки выдвинуть шлем как в Dead Space, чем таскать его с собой или все время носить на голове.

UPD: Пришла идея о том, чтобы добавить встроенный баллон воздуха, который можно менять, а то как-то нелепо носить на поясе баллон, не РИГ уже. Костюм будет автоматически предупреждать, сколько кислорода осталась в костюме, при критически низком давлении, будет «кричать» и пиликать пользователю о том, что пора возвращаться. Будет возможность повесить внешний источник кислорода, который будет пополнять внутренний баллон при открытии клапана.

UPD 2.0: В холодном и недружелюбном космосе может случиться всякое, к примеру,  у твоего друга инженера появилась производственная травма во время работы в космосе или съел чего не того, в следствии чего он упал или встал на месте как каменная статуя и не может проронить ни слова. Тут нам и поможет шкала жизни на спине твоего товарища, которая снизошла прямо из игры Dead Space.

### Плюсы:
1. Не нужно больше носить с собой шлем, который только занимает драгоценное место в рюкзаках инженеров/СБ, а если все время носить его на голове, то выглядит как-то странно.

UPD: Не нужно будет носить с собой баллон воздуха, ведь по логике он должен быть встроен в РИГ.

UPD 2.0: Всегда можно будет узнать, перепил ли твой товарищ или ему нужно навести врача.

2. Выглядит элегантно, высосало в космос и вы упали? Не нужно больше в суматохе доставать шлем, можно нажать одну кнопку и шлем с характерным звуком выдвинется из вашего костюма. На вас напал ассистент, клоун или ещё какая внеземная тварь с огнетушителем? Просто наденьте шлем через кнопку, попутно отбиваясь от врага, а не в спешке пытаясь достать шлем из рюкзака, пока вас пару раз огрели по голове. 

UPD: Тоже выглядит довольно элегантно, не нужно будет занимать слот.

UPD 2.0: Заполняет пустое пространство на спине, выглядит привлекательно.

### Минусы:
Работа кодеру.

**Comment by volas** [comment]
Сделали, проверяй

**Comment by da-kiselev** [comment]
> Сделали, проверяй

Оперативненько, когда успели?

**Comment by igigin** [comment]
Лет пять назад.

**Comment by da-kiselev** [comment]
> Лет пять назад.

Хз, сколько новые риги не одевал, всегда нужно шлем сверху, сегодня к примеру одевал РИГ СБ, раньше была такая фича, ща не видел

**Comment by ZVee** [comment]
Это ТГ система, у них объект шлема абстрактный и не существует вне костюмов. Правда бывало что эти шлема мапперы маппили, игроки находили, а потом такой шлем нельзя было снять с моба без гиба (т.е нужно чтобы шлемы никак не попадали в игровую зону, мусорщики там, и т.д).

Но если это вообще распространять на все, мне кажется лучше оставить такую фичу для специализированных и технологичных решений. Т.к носить с собой постоянно это и так не правильно, даже если профа вроде обязывает (ну а вдруг вот-вот сейчас да разгерметизирует отсек - слишком параноидально, слишком мета).

**Comment by da-kiselev** [comment]
> Это ТГ система, у них объект шлема абстрактный и не существует вне костюмов. Правда бывало что эти шлема мапперы маппили, игроки находили, а потом такой шлем нельзя было снять с моба без гиба (т.е нужно чтобы шлемы никак не попадали в игровую зону, мусорщики там, и т.д).
> 
> Но если это вообще распространять на все, мне кажется лучше оставить такую фичу для специализированных и технологичных решений. Т.к носить с собой постоянно это и так не правильно, даже если профа вроде обязывает (ну а вдруг вот-вот сейчас да разгерметизирует отсек - слишком параноидально, слишком мета).

Ну, от части согласен, но инженерам или атмостехникам довольно удобно в них работать, они часто с ним не расстаются, поэтому прошу добавить хотяб инженерам такое, как максимум, то добавить ригам СБ. А параноидальное ношение вещей «первой» необходимости мета, наказывать надо.

**Comment by Loratron** [comment]
А теперь заходишь на локалку/сервер, берёшь абсолютно любой РИГ и шлем от него, клацаешь шлемом по РИГу (когда он в руках или на полу) и радуешься жизнью, после чего закрываешь ишью - этой фиче уже так много лет, что она появилась ещё до того как я на ТК начал играть

**Comment by Motzord** [comment]
Вот интегрированный баллон уже разумнее. На инфините видел это и данная плюшка очень радовала

**Comment by da-kiselev** [comment]
Требую Вики по ригам, а то какие-то “новомодные“ фичи, я изменил немного тему, предлагаю теперь ещё ввести встроенный баллон.

**Comment by Motzord** [comment]
> Требую Вики по ригам, а то какие-то “новомодные“ фичи, я изменил немного тему, предлагаю теперь ещё ввести встроенный баллон.

Фича реально старая, она была еще до того как я вкатился, ибо помню меня за нюкера учили магбутсы в риг пихать

**Comment by da-kiselev** [comment]
> > Требую Вики по ригам, а то какие-то “новомодные“ фичи, я изменил немного тему, предлагаю теперь ещё ввести встроенный баллон.
> 
> Фича реально старая, она была еще до того как я вкатился, ибо помню меня за нюкера учили магбутсы в риг пихать

Лол, а так можно? Не знал.

**Comment by Akellazp** [comment]
Как по мне полоска хп это уже слишком

**Comment by Motzord** [comment]
Еще полоску ХП на конечности и шанс попаданий по ним, а еще статус бар над пушками чтобы смотреть сколько у тебя выстрелов еще осталось, и обязательный худ при нюке/триторов у СБ, где у них в уголке выводится сколько они уже таторов наловили/убили

**Comment by da-kiselev** [comment]
> Еще полоску ХП на конечности и шанс попаданий по ним, а еще статус бар над пушками чтобы смотреть сколько у тебя выстрелов еще осталось, и обязательный худ при нюке/триторов у СБ, где у них в уголке выводится сколько они уже таторов наловили/убили

Не, в маразма то не надо скатываться, для инженеров довольно удобно, мало ли их какая аномалия гибнет.
