### ISSUE TITLE
Игрушки фейсхагеров имеют в себе механизмы с баками кислоты

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4074]
#### Подробное описание проблемы
Игрушки фейсхагеров прыгают на лица людей паралельно снимая/растворяя шлемы и маски
#### Что должно было произойти
Ну мааксимум игрушка может напрыгнуть, но не растворять шлемы/маски
#### Что произошло на самом деле
Игрушка фейсхагера убивает людей в космосе если напрыгивает на лицо, игрушка фейсхагера отправляет наличие шлемов ригов на станции в красную книгу
#### Как повторить
Наденьте риг, маску, шлем и положите рядом игрушку хагера
#### Дополнительная информация:
Этот баг появился скорее всего после ПРа с интеллектом фейсхагеров

**Comment by Zmey25** [comment]
Фича

**Comment by Lizurt** [comment]
Спасибо за репорт о баге. Если бы змей не написал "фича", я бы и не заметил этот ишью. Постараюсь исправить, так как мои изменения в игре добавили этот баг, причем весьма противный.
