### ISSUE TITLE
[Proposal] Половые вариации кусков тел

### ISSUE THREAD

**Issue by aIweiss** [TauCetiStation/TauCetiClassic#4075]
#### Подробное описание проблемы
Хотелось бы возможность установить в настройках ксенотелерасов более тонкую настройку половых вариаций, а не так, что отличается только лицо и пузо. Возможность сделать разные ноги, руки, хвосты, вот это вот все.

Понятное дело, что куклы все еще ограничены спрайтами, но так будет все равно проще.

**Comment by Motzord** [comment]
Наконец-то закодят размер гроина и груди...

**Comment by ArtBsd1** [comment]
Наконец - то будем мериться пиписьками
