### ISSUE TITLE
[Proposal] Добавьте возможность поджечь спички об подошву обуви.

### ISSUE THREAD

**Issue by da-kiselev** [TauCetiStation/TauCetiClassic#4081]
Предлагаю добавить возможность поджигать спички об подошву обуви, да, в далеком будущем спички скорее всего не делают из белого фосфора, но это не отменяет того, что это довольно эффектно.

### Плюсы:
Это модно, это стильно, это веет вестерном.

### Минусы:
Работа кодеру.

**Comment by Motzord** [comment]
Добавь, разрешаю.

Воевали против "мультяшных" ригов, предлагаем мультяшные фичи.


А закодьте тогда еще, чтобы можно было гибнуться падающей наковальней, и пинг к гравитации прикрутите, чтобы сначала бежал, потом видел дыру в шпесс, размышлял и только потом падал...

**Comment by da-kiselev** [comment]
> Добавь, разрешаю.
> 
> Воевали против "мультяшных" ригов, предлагаем мультяшные фичи.
> 
> А закодьте тогда еще, чтобы можно было гибнуться падающей наковальней, и пинг к гравитации прикрутите, чтобы сначала бежал, потом видел дыру в шпесс, размышлял и только потом падал...

Не мультяшная, а реальная, раньше спички делали из Бологое фосфора, они от любого чиха загорались
