### ISSUE TITLE
Дробовиком со станслагами можно застрелится

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4086]
#### Подробное описание проблемы
Дробовик со станпатронами позволяет сыграть в курткобейна
#### Что должно было произойти
Падаешь в крит и корчишься от боли
#### Что произошло на самом деле
Скосплеил солиста Нирваны
#### Как повторить
Засуньте дробовик со станпатронами в рот и дерните курок
#### Дополнительная информация:
Соль при стрельбе в рот также позволяет играть в суицидника, тестил на дробовике бармена

**Comment by FelixRuin** [comment]
кто мог подумать что вещь которая наносит урон при стрельбе себе в рот выносит мозг напрочь?
не является багов, да, это вроде как предсказуемое и понятное поведение соли в нёб

**Comment by Motzord** [comment]
> кто мог подумать что вещь которая наносит урон при стрельбе себе в рот выносит мозг напрочь?
> не является багом, да, это вроде как предсказуемое и понятное поведение соли в нёб

А насчет станслага, который aka тазер стреляет в рот шариком электричества?

Если он тоже выжигает мозги придется прикручивать суицид тазерам/станревольверам

**Comment by FelixRuin** [comment]
всё что не наносит урон или наносит гало урон основным, то он не убивает

**Comment by Motzord** [comment]
> всё что не наносит урон или наносит гало урон основным, то он не убивает

Проверь прямо сейчас на локалочке. Выстрели станслагом и солью в рот. Оба этих патрона наносят голоурон

**Comment by FelixRuin** [comment]
...
станслаг наносит урон (5, но однако)
