### ISSUE TITLE
[Proposal]Добавить СПУ возможность реанимации с помощью рестарт модуля (как у боргов)

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4097]
#### Подробное описание проблемы
СПУ невозможно реанимировать без педальной помощи
#### Что должно было произойти
Долгая починка всего тела от последствий перегрева и других повреждений и вставка модуля для рестарта систем должна принести плоды в виде реанимации СПУ
#### Что произошло на самом деле
Долгая починка всего тела от последствий перегрева и других повреждений не приводит ни к чему без педальной помощи
#### Как повторить
Найдите у некомпетентного роботехника на операционном столе мертвого СПУ и будучи компетентным роботехником попытайтесь его починить
#### Дополнительная информация:
СПУ должны бояться за свою тушку, но проблема в том, что иногда смерть наступает не по их воле (например бой вообще где то за стеной и он начинается с ЭМИ который достает до тебя)

**Comment by maxyo** [comment]
1. Достань процессор из ПК.
2. Урони его напол.
3. Попробуй починить его.
4. ???
5. Копи на новый.
