### ISSUE TITLE
Огнестрельное оружие в руках клоуна взрывается также, как и лазерное

### ISSUE THREAD

**Issue by da-kiselev** [TauCetiStation/TauCetiClassic#4103]
### Подробное описание проблемы
Приветствую, огнестрельное оружие взрывается в руках клоуна также, как и лазерное, хотя должно бахать с большим количеством шрапнели, либо мощнее. 
#### Что должно было произойти
Взрыв должен был быть сильнее, либо разлет шрапнели.

#### Что произошло на самом деле
Бахает также, как и тазер.

#### Как повторить
Взять любой огнестрел, тот же резиновый травмат. 

#### Дополнительная информация:
Клоун не может в нормальное оглушение других эти взрывом.

**Comment by FelixRuin** [comment]
это наказание для клоуна
а не тактический манёвр для оглушения взрывами

**Comment by SpaiR** [comment]
> должно бахать с большим количеством шрапнели

Никакой градации мощности взрыва кодом заложено не было, так что это скорее домысел. Ну и делать из этого, как верно замечено, тактический маневр - странно.
