### ISSUE TITLE
Проблема с поворотами на месте

### ISSUE THREAD

**Issue by GreyGunner** [TauCetiStation/TauCetiClassic#4109]
#### Подробное описание проблемы
Периодически пропадает возможность сменить направление взгляда (кнтрл+стрелочки или ЛКМ вдаль) 
#### Что должно было произойти
Персонаж при нажатии соответствующих кнопок должен повернуться в соответствующую сторону
#### Что произошло на самом деле
Персонаж не всегда поворачивается
#### Как повторить
Зайти на сервер, вращаться туда-сюда и в течении минут 5, скорее всего, на какое-то время повернуться не получится, а потом опять получится. 
#### Дополнительная информация:
Скорее всего блокировка возможности повернуться происходит у всех разом, т.к. не раз замечал, что как только эта возможность блокировалась у меня, так кто-то в ЛООС или ООС пишет о том, что эта возможность заблокировалась и у него

**Comment by FatFatFat1** [comment]
Не хочу писать ишью,тут скорее недоработка чем баг ,но напишу тут.
Когда фиксируешь направление и начинаешь кравлить,то фиксация не сбрасывается.Когда встаешь начинаешь бегать как без фиксации,но когда нажимаешь на кнопку еще раз,пишет что фиксация снята

**Comment by RichardJones1** [comment]
Баг был создан этим #3988 ПР-ом, сейчас ПР благополучно ревёртнут. Пока закрываю.
