### ISSUE TITLE
Баг с оружейной еще жив

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4113]
#### Подробное описание проблемы
Иногда случается непонятный аномальный баг в оружейной когда экран игры зависает
#### Что должно было произойти
Ничего не должно зависать в оружейной
#### Что произошло на самом деле
Завис между входом в тактическую и боевую оружейку, не мог посмотреть расстрел нюкеров за госта, читал игру по логам
#### Как повторить
Баг произошел при умирании в данном аномальном месте 
![image](https://user-images.githubusercontent.com/45365635/66499246-beaa5d80-eabf-11e9-9e61-b4bb6d595761.png)

#### Дополнительная информация:
Когда-то уже создавалось несколько подобных ишью, и вот баг снова здесь

**Comment by Lizurt** [comment]
Ишью является дубликатом: https://github.com/TauCetiStation/TauCetiClassic/issues/2987
Тема на форуме: https://forum.taucetistation.org/t/oshibka-v-severnoj-chasti-briga/9771

**Comment by volas** [comment]
Мы не можем воспроизвести, и без логов от игроков это не решить. И да, дубликат.
