### ISSUE TITLE
[Proposal] Добавьте бочки для алкоголя или упростите его изготовление.

### ISSUE THREAD

**Issue by 1Samen** [TauCetiStation/TauCetiClassic#4125]
#### Подробное описание проблемы 
За ботаника неудобно гнать водку ,другой алкоголь , и почему-то для этого надо просить у повара универсального эмнезия ,а так же надо запоминать все крафты.

#### Что должно было произойти 
Водка должна была бы ферментироватся из бочки (которой нет) ,а не эмнезия.
#### Что произошло на самом деле 
Магическим образам из эмнезия и картохи получил водку.

#### Как повторить 
Делать водку или другой алкоголь за ботаника.

#### Дополнительная информация:
Добавив бочку как на тг это упростит крафт алкоголя , и её будут все использовать. Потому что не надо мучать повара и учить крафты . Хотелось бы чтобы хотябы упростили изготовление алкоголя

**Comment by da-kiselev** [comment]
> #### Подробное описание проблемы
> За ботаника неудобно гнать водку ,другой алкоголь , и почему-то для этого надо просить у повара универсального эмнезия ,а так же надо запоминать все крафты.
> 
> #### Что должно было произойти
> Водка должна была бы ферментироватся из бочки (которой нет) ,а не эмнезия.
> 
> #### Что произошло на самом деле
> Магическим образам из эмнезия и картохи получил водку.
> 
> #### Как повторить
> Делать водку или другой алкоголь за ботаника.
> 
> #### Дополнительная информация:
> Добавив бочку как на тг это упростит крафт алкоголя , и её будут все использовать. Потому что не надо мучать повара и учить крафты . Хотелось бы чтобы хотябы упростили изготовление алкоголя

За ботаника можно гнать алкоголь? Где можно посмотреть гайд/рецепты?

**Comment by aIweiss** [comment]
эмнезия это когда зэбэваешь все, а энзим это ферменты, и для того, чтобы гнать алкоголь, они нужны
