### ISSUE TITLE
Недостающее свойство у платы.

### ISSUE THREAD

**Issue by seekin4u** [TauCetiStation/TauCetiClassic#4127]
#### Подробное описание проблемы
Машинерия "миксер красок" для барберской собирается не из машинного корпуса а из компьютера.

#### Что должно было произойти
Механизм должен собираться из машинного корпуса

#### Что произошло на самом деле
Пришлось наугад ставить компьютерный корпус и собирать его как компьютер, что бы получить /obj/machinery/, что противоречит логике.

#### Как повторить
Найти плату ```/obj/item/weapon/circuitboard/color_mixer``` и собрать из неё механизм через компьютерный корпус.

#### Дополнительная информация:
описания двух плат, отличие в наличии поля board_type = "machine" что, вероятно, и есть то условие от которого зависит выбор корпуса

```
/obj/item/weapon/circuitboard/space_heater
	build_path = /obj/machinery/space_heater
	board_type = "machine"
	origin_tech = "123"


/obj/item/weapon/circuitboard/color_mixer
	build_path = /obj/machinery/color_mixer
	origin_tech = "123"
```

**Comment by RichardJones1** [comment]
@LudwigVonChesterfield , разве правда не так задумывалось?

**Comment by LudwigVonChesterfield** [comment]
Миксер красок действительно скорее просто машинерия, чем компьютер/консоль.

Нет, так не задумывалось.
