### ISSUE TITLE
Древнейший баг, который почему-то не пофиксили.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4135]
#### Подробное описание проблемы
Если открыть ивентарь сумки ботаника, и не закрывая его кликнуть сумкой по миксеру блэндеру, а затим собственно "переработать" растения, то оверлей растений остается на экране до перезахода, игнорируя систему инвентаря.
#### Что должно было произойти
>Кликнул сумкой по блендеру/биогенератору.
>Сумка обновилась и убрала лишние предметы
#### Что произошло на самом деле
>Кликнул сумкой по блендеру/биогенератору
>Оверлей содержимого сумки не обновляется, пока не откроешь снова
>Забыл переоткрыть сумку
>Перемолол растения
>Наслаждаешься полосочкой амброзии вместо пола
#### Как повторить
Описано выше, догадаться можно
#### Дополнительная информация:
Баг присутствует и на финиках

**Comment by Motzord** [comment]
Вроде бы пофикшено

**Comment by T6751** [comment]
нет не пофикшено, 
![image](https://user-images.githubusercontent.com/66636084/84326301-47b0f180-ab85-11ea-9ba1-04237ca3e4c1.png)

**Comment by T6751** [comment]
@LudwigVonChesterfield @Motzord переоткройте иссуй
