### ISSUE TITLE
Добавить квиркам ограничение по профессиям

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4145]
#### Подробное описание проблемы
Люди с некоторыми болезнями, могут работать там, куда по-сути их нельзя допускать
#### Что должно было произойти
Инвалиды не работают в сб. (Если только инвалидность не на голову...)
#### Что произошло на самом деле
Слепые, безрукие хирурги. СБ с эпилепсией, Форонщики с кашлем, инженеры с механоглазами/сердцем, глухие вардены и капитан с синдромом Туррета
#### Как повторить
Выставьте все отрицательные квирки оторвите персонажу ноги и руки и зайдите за капитана

**Comment by Ambassadoing** [comment]
Ну так-то капитан не обязан быть самым прытким и самым боевым, он руководить должен. Так что подслеповатый капитан-инвалид преклонного возраста ещё куда ни шёл.

**Comment by Morair** [comment]
Давайте их еще в пул антагов не добавлять, а то кто наймет безрукого синдикатовца. Должно быть [Proposal] .

**Comment by Motzord** [comment]
> Давайте их еще в пул антагов не добавлять, а то кто наймет безрукого синдикатовца. Должно быть [Proposal] .

Ну кто-то же нанял в Горлексы инвалида-колясочника...
