### ISSUE TITLE
Не отображается рюкзак Phoron Researcher'а

### ISSUE THREAD

**Issue by Stixonya** [TauCetiStation/TauCetiClassic#4148]
#### Подробное описание проблемы
Не отображается рюкзак Phoron Researcher'а в интерфейсе инвентаря, с ним можно взаимодействовать только через меню в верхнем левом углу.
#### Что должно было произойти
Отображение рюкзака в интерфейсе, возможность взаимодействовать с ним (надевать/снимать/открывать).
#### Что произошло на самом деле
Рюкзак не отображается, функции не работают.
#### Как повторить
Зайти за phoron researcher.

#### Дополнительная информация:
![science backpack](https://user-images.githubusercontent.com/55360868/67393425-01cdfb80-f5ab-11e9-95af-139281ed9cfd.JPG)

**Comment by Motzord** [comment]
Не актуально
