### ISSUE TITLE
Фармбот для ботаники, пластиковые лапсы в Карго, новая шахтерка.

### ISSUE THREAD

**Issue by CryptoKisik** [TauCetiStation/TauCetiClassic#415]
#### Подробное описание проблемы:

~~1. У шахтеров нет доступа к вкладке "setting" в консоли рнд на шахтерке;~~
~~2. У пластиковых лапсов, которые отделяю шахтерку и КаргоБэй - 0 давления на тайле;~~
3. Фармбот для ботаники невероятно тупой (старая проблема).
#### Что должно было произойти

~~1.  При клике на вкладку "setting" в консоли рнд, должны открыться настройки консоли;~~
~~2. Если стать на тайл, то давление должно быть в норме;~~
3. Фармбот должен поливать, чистить от сорняков и прочее.
#### Что произошло на самом деле

~~1. При попытки открыть настройки, пишет, что нет доступа. У ученых тоже нет доступа;~~
~~2. На тайле нулевое давление;~~
3. Фармбот тупит и стоит на месте. Изредка решается поработать. Чертовы синтеты. 
#### Как повторить

~~1-2. Зайти за шахтера и проверить;~~
3. Собрать фармбота и отправить в ботанику.

**Comment by ZVee** [comment]
Раздельно пожалуйста создавать репорты, редко когда фиксят целиком.

**Comment by volas** [comment]
Можешь этот отредактировать и создать еще 2

**Comment by Uvash** [comment]
Доступ шахтёрам скоро починят.

**Comment by Raschert0** [comment]
@CryptoKisik 
Собственно говоря, флапсы тоже скоро починят, так что первые два пункта можешь убрать

**Comment by Uvash** [comment]
По поводу фарм бота. Можешь объяснить, что с ним не так. По коду у него задержка 10 секунд стоит, если не находит цель в зоне видимости. + Задержка для анимации и после анимации секун 5. Плюс он должен видеть несчастные ванны, иначе он игнорит их.
