### ISSUE TITLE
[Proposal] ОБР в титры!

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4156]
Я тут подумал, ОБР является тоже специальной ролью, и когда на станции уже полно говна, хочется знать <spoiler>**_Кто сделал рауд еще более хуевым_**</spoiler>, кто спас станцию от неминуемой угрозы!

а) Игроки будут меньше творить говно, зная, что твой ник посмотрят в конце раунда и будут считать тебя мудаком, ибо пришел на ОБР грифонить
б) Игроки будут знать кто их спасал из обр или кто мудачил, что повысит правильность банхаммеров
в) ОБР разве не заслужили титры?

**Comment by AndroBetel** [comment]
> а) Игроки будут меньше творить говно, зная, что твой ник посмотрят в конце раунда и будут считать тебя мудаком, ибо пришел на ОБР грифонить

![image](https://user-images.githubusercontent.com/44546836/67421573-71f37600-f5d9-11e9-8353-cfba26f70b2b.png)

**Comment by Ambassadoing** [comment]
>а) Игроки будут меньше творить говно, зная, что твой ник посмотрят в конце раунда и будут считать тебя мудаком, ибо пришел на ОБР грифонить
б) Игроки будут знать кто их спасал из обр или кто мудачил, что повысит правильность банхаммеров
в) ОБР разве не заслужили титры?


![emote](https://user-images.githubusercontent.com/48314394/67421667-aa934f80-f5d9-11e9-8245-a3203f0bdf6b.png)

**Comment by Motzord** [comment]
> > а) Игроки будут меньше творить говно, зная, что твой ник посмотрят в конце раунда и будут считать тебя мудаком, ибо пришел на ОБР грифонить
> > б) Игроки будут знать кто их спасал из обр или кто мудачил, что повысит правильность банхаммеров
> 
> ![image](https://user-images.githubusercontent.com/44546836/67421573-71f37600-f5d9-11e9-8353-cfba26f70b2b.png)

![image](https://user-images.githubusercontent.com/45365635/67422129-24273f80-f5d2-11e9-9f2a-cf495da8b84e.png)
