### ISSUE TITLE
Ремонт механического сердца отверткой невозможен.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#4169]
#### Подробное описание проблемы
Починить механическое сердце отверткой нельзя из-за того, что у отвертки несколько способов применения, из-за чего вместо ремонта сердца она используется как ретрактор и закрывает грудную клетку.
#### Что должно было произойти
Отвертка должна была починить сердце.
#### Что произошло на самом деле
Она закрыла грудную клетку.
#### Как повторить
Проводим операцию по лечению внутренних органов. Вскрываем грудную клетку. Так как нанопасты иногда нет, приходилось использовать отвертку или биогель. Тыкаем отверткой в открытую грудную клетку.

**Comment by AirBlack** [comment]
`/datum/surgery_step/ribcage/fix_chest_internal_robot //For artificial organs
	allowed_tools = list(
	/obj/item/stack/nanopaste = 100,
	/obj/item/weapon/bonegel = 30,
	/obj/item/weapon/wrench = 70
	)
	allowed_species = null

	min_duration = 70
	max_duration = 90`

Починка ключом производится, а не отверткой. Мне кажется, скорее ошибка вики.

**Comment by skvazarb** [comment]
>Мне кажется, скорее ошибка вики.
Устаревшие данные. ну да, можно считать ошибкой.

Гетто аналоги переделывали здесь https://github.com/TauCetiStation/TauCetiClassic/pull/706 и, откровенно говоря, некоторые замены выглядят абсолютно безумными. Особенно замена циркулярки на ломик(!!!), что позволяет вскрыть череп или даже ампутировать ломом конечность. Не могу представить себе такое даже на максимальных игровых условностях. К таким же странным идеям относится ремонт биомеханического органа с помощью гаечного ключа.
