### ISSUE TITLE
сломанный фотоальбом

### ISSUE THREAD

**Issue by Wozzy09** [TauCetiStation/TauCetiClassic#4178]
#### Подробное описание проблемы
фотоальбом не принимает фотографии

#### Что должно было произойти
фотография помещается в фотоальбом

#### Что произошло на самом деле

![image](https://user-images.githubusercontent.com/32817214/67719041-16165c00-f9e2-11e9-837a-8ae3e80375fd.png)

#### Как повторить
попытаться засунуть фотографию в альбом???

#### Дополнительная информация:
короче сам посмотрел
за***** кто-то поставил кавычки не в то место, чтоб этих *******
![image](https://user-images.githubusercontent.com/32817214/67722339-f1be7d80-f9e9-11e9-8785-0b243053c560.png)

**Comment by Wozzy09** [comment]
а еще он почему-то отображается как чемодан...
![image](https://user-images.githubusercontent.com/32817214/67719191-6988aa00-f9e2-11e9-9536-0b426a5b4cb7.png)

**Comment by Kortez90** [comment]
> 
> 
> а еще он почему-то отображается как чемодан...
Потому что это чемодан с респрайтом.
