### ISSUE TITLE
Что-то из тестмержа ломает обзерв

### ISSUE THREAD

**Issue by EdlerN** [TauCetiStation/TauCetiClassic#4187]
#### Подробное описание проблемы
Читай название
#### Что должно было произойти
Зашел на первый сервер нажал обзерв, пошел поглядеть что да как на станции
#### Что произошло на самом деле
Нау телепортинг
#### Как повторить
Зайти на первый сервер и нажать кнопку обзерв
#### Дополнительная информация:
Возможно админопроблемы. К тому же на втором сервере всё нормально.

**Comment by Dominig12** [comment]
зве в РНД сказал что то на стороне хоста надо перезагрузить, потому что не могут обнаружить лендмарку (а она есть)

**Comment by volas** [comment]
Если лендмарк есть, то это определенно проблема локейт()-а. В прошлом уже вроде бы сталкивались с такими аномалиями, не помню как решали (возможно само починилось).
Перекомпилил сервер, после рестарта если проблема не исчезнет - возможно будет смысл заменить локейт на что-то другое

**Comment by Dominig12** [comment]
> ```
> Runtime in new_player.dm,132: Cannot read null.loc
> ```
> 
> Если лендмарк есть, то это определенно проблема локейт()-а. В прошлом уже вроде бы сталкивались с такими аномалиями, не помню как решали (возможно само починилось).
> Перекомпилил сервер, после рестарта если проблема не исчезнет - возможно будет смысл заменить локейт на что-то другое

проблема исчезла

**Comment by Motzord** [comment]
Не воспроизводится, видимо само пофиксилось
