### ISSUE TITLE
Шахтерский борг не имеет возможности подбирать блюспейс кристаллы.

### ISSUE THREAD

**Issue by ZMikkie** [TauCetiStation/TauCetiClassic#419]
#### Подробное описание проблемы
Если борг сумеет разбить большой блюспейс кристалл, ему придется таскать куски по-одному пуллом. Он не может собрать куски (блюспейс кристаллы) в мешок для руд.
#### Что должно было произойти
Борг должен уметь собирать кристаллы мешком для руд.
#### Что произошло на самом деле
Борг страдал.
#### Как повторить
Разбить блюспейс кристалл, попытаться собрать мелкие кристаллы мешком.

**Comment by Raschert0** [comment]
Закрывайте

**Comment by volas** [comment]
#653
