### ISSUE TITLE
[Proposal] Убрать плазменный дробовик

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#4196]
#### Подробное описание проблемы
Плазменный дробовик нереально имбовый
#### Что должно было произойти
У людей, которые противостоят человеку с плазменным дробовиком должны быть шансы на выживание
#### Что произошло на самом деле
Шансов на выживание нет. Он с двух-трех выстрелов убьет любое существо (будь то халк, тенелинг и тд)
#### Как повторить
Попробовать победить человека с плазменным дробовиком

**Comment by Kortez90** [comment]
Я недавно побеждал хоса с плазменным дробовиком. Лазерный щит и стандартный ПП нюки.

**Comment by ArtBsd1** [comment]
Ксеноморфа с первого выстрела убивает

**Comment by Motzord** [comment]
А стреляли впритык или с одного конца коридора до мостика?

Если впритык, то ничего не имею против

**Comment by Kortez90** [comment]
> 
> 
> А стреляли впритык или с одного конца коридора до мостика?
> 
> Если впритык, то ничего не имею против

Если ты про мой бой с хосом, то расстояние было от 1 до 2-3 тайлов. Плазма отскакивала от щита, пару залпов в грудь пропустил.

**Comment by Dominig12** [comment]
Я против этого пропозла, заносите новый.
Дробовик это опасное оружие на средней дистанции, тоже самое касается и огнестрельного дробовика
Для использования дробовика нужно 2 руки
Пули этого дробовика отлетают от абелятивки

**Comment by ArtBsd1** [comment]
Ещё нужно сделать его более тяжелым. 
(Выше писал, что нужно уменьшить урон.)
