### ISSUE TITLE
Баг с зимней курткой и отображение одежды.

### ISSUE THREAD

**Issue by lvovauto** [TauCetiStation/TauCetiClassic#4197]
#### Подробное описание проблемы
Проблема связана с зимней курткой , надеть капюшон нельзя если у вас одет головной убор , но если снять головной убор , потом надеть капюшон зимней куртки и уже поверх него  головной убор одевается и остается на голове навсегда даже если вы его потом снимите , так же если вы снимите куртку не сняв капюшон , пропадут все ваши волосы и борода.

#### Что должно было произойти
Не должно быть возможности одевать головной убор когда на вас одет капюшон , если снять куртку не снимая капюшон волосы не должны исчезать

#### Что произошло на самом деле
Можно одеть головной убор по верх капюшона тем самым вызвав баг ,  и после снятие куртки с не снятым капюшоном волосы исчезают

#### Как повторить 
Одеть зимнюю куртку , одеть на ней капюшон , потом поверх одеть головной убор,убрать капюшон и снять куртку (теперь даже сняв головной убор с головы он все равно будет на персонаже ), снять куртку не снимая капюшон  (исчезновение волос)

**Comment by Ayuska** [comment]
А это актуально, кстати.

**Comment by Chip11-n** [comment]
#6607
