### ISSUE TITLE
Предложение по переработке системы переломов/повреждений конечностей [Proposal]

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4217]
Ладно, не буду томить, что мы имеем сейчас.

У костей есть значение при которых их вправить невозможно и они продолжат ломаться, но это все дело запросто сбивается бикардином или снятием/наматыванием бинтиков на поврежденную руку, до приемлемой величины.

(Брут урон кстати считается по всему телу, мол сломали руку, отбили гроин, а руку вправить низя, гроин покоцан сильно)

А хорошо ли это?

Предлагаю дать костям что-то вроде собственного порога прочности, который будет считаться на переломах. Так если кость вывихнули/сломали, то ее будет довольно таки просто вправить, но если нехороший человек планомерно закликивал конечность балоном, уже несколько минут, то руку вправить невозможно, потому что кость превратилась буквально в кашу. (Наконец-то у хирургов будет повод для справедливых ампутаций)

Такой же порог урона я предлагаю ввести и в случае с берном (Который будет считывать именно урон на конечности а не на всем теле)

Ожог четвертой степени конечно хорошо, но ампутации и замена на протез/культяпку лучше.

(Некроз и сепсис для нашего сервера редок, потому что кое-кто выпилил ПР людука)

Итак, что мы имеем:
>Сломали руку, до чуть ли не гиба, сбил урон чем угодно, кость внезапно, вправляется.
Или
>Сломали руку, на которой скажем 20 брута, накликали кукле по голове и рука внезапно не вправляется.

Что предлагаю я.
>Несильно сломали руку, в кости трещина, вправляется без проблем
>Руку закликивали балоном, кость переломана в открытый, вправить можно, но аккуратно
>Кто-то методично превращал вашу руку в отбивную и довел ее до порога урона? Помянем, вам на ампутацию.

Берн.
>Обжег ручку, несильно, помазал мазью — норм
>Сжег ручку об лазер — больно, помазал мазью, обкололся дермалином, сжег
>Решил постоять в фороновом пожаре/капитан методично отстреливал тебе руку лазером — на ампутацию

#Кодить_буду_не_я

**Comment by LudwigVonChesterfield** [comment]
Сломали руку, до чуть ли не гиба, сбил урон чем угодно, кость внезапно, вправляется.
Или

Что. Она не вправляется если залечить урон - и перелом остаётся пока его не починят. Ты точно сам знаешь о том как оно работает... ?

**Comment by Motzord** [comment]
> Сломали руку, до чуть ли не гиба, сбил урон чем угодно, кость внезапно, вправляется.
> Или
> 
> Что. Она не вправляется если залечить урон - и перелом остаётся пока его не починят. Ты точно сам знаешь о том как оно работает... ?

Я о том, что пока ты не собьешь урон, тряпками ли, бикардином ли, кость вправить хирург не может.

Но если ты 15 раз намотаешь снимешь бинтики или вколешь бикардин, даже открытый перелом впринципе неплохо вправляется, что забавно. Даже конечность превратившаяся в мясное месиво после того как намоталась на бур, в принципе вправляется нормально
