### ISSUE TITLE
Режим "Революция" не имеет конца.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#4225]
#### Подробное описание проблемы
Игра отклоняет любые шаттлы кроме педальных пока живы глав ревы, даже шаттл воута. Однако когда умирают глав ревы, новый глав рева выбирается рандомом из обычных реверов (и вроде как даже не уведомляет игрока об этом).
#### Что должно было произойти
При смерти глав рев или их заключении в бриге, шаттл не должен отзываться. Или же, если все главы мертвы (или законверчены в реву) то шаттл тоже не должен отзываться. Ну или придумайте сами.
#### Что произошло на самом деле
Что бы завершить раунд без педалей, нужно убить весь сервер.
#### Как повторить
Посмотреть педально один из раундов реверов.

**Comment by Leshiy-ART** [comment]
А еще есть вариант где глав можно сослать со станции. Не уверен работает ли это с астероидом, но с отправкой их на эвакуационном шаттле - точно работает.

**Comment by Avatar4** [comment]
Но прикол в том, что для этого надо прислать шаттл что бы их сослать
