### ISSUE TITLE
Появление в лобби борга

### ISSUE THREAD

**Issue by ArtBsd1** [TauCetiStation/TauCetiClassic#4226]
#### Подробное описание проблемы
Зашел за сервер, нажал Join to Game. Увидел "профессию" борга. Захотелось посмотреть как он заспавнится на станции. Нажал. 
![image](https://user-images.githubusercontent.com/44677341/68481510-369fab00-0259-11ea-86e0-418ba8fbe445.png)

#### Что должно было произойти
Я должен был появится не в лобби
#### Как повторить
Зайти за профессию борга.

**Comment by Leshiy-ART** [comment]
Обычно такая профессия не доступна. Возможно кто-то из администрации подкрутил счетчик свободных слотов во время раунда.

**Comment by ZVee** [comment]
У нас нет лейтджойна для боргов вообще (технически), так что это неудивительно в принципе. Поэтому и за баг считать сложно, т.к этой позиции и не должно быть в списках при штатной работе.

**Comment by ArtBsd1** [comment]
> #### Подробное описание проблемы
> Зашел за сервер, нажал Join to Game. Увидел "профессию" борга. Захотелось посмотреть как он заспавнится на станции. Нажал.
> ![image](https://user-images.githubusercontent.com/44677341/68481510-369fab00-0259-11ea-86e0-418ba8fbe445.png)
> 
> #### Что должно было произойти
> Я должен был появится не в лобби
> 
> #### Что произошло на самом деле
> #### Как повторить
> Зайти за профессию борга.
> 
> #### Дополнительная информация:

**Comment by TechCatOther** [comment]
А какая причина ограничения на подключение за борга через лобби с свободный позитронный мозг?

**Comment by TechCatOther** [comment]
Дубль #3595
