### ISSUE TITLE
Стандартный набор грифера

### ISSUE THREAD

**Issue by ArtBsd1** [TauCetiStation/TauCetiClassic#4227]
#### Подробное описание проблемы
Зашёл за профессию борга, случайно нажал на стандартный модуль борга. 
![image](https://user-images.githubusercontent.com/44677341/68484929-1d4e2d00-0260-11ea-8810-94153b5e0b64.png)
Там увидел стандартный набор трейтор - ассистента.
#### Что должно было произойти
В инвентаре стандратного модуля должны быть всякое вспомогательное оборудование(ломик, анализатор, раздатчик стаканов, ведерко(коров доить), гаечный ключ, музыкальный инструмент, ракушка, диктофон ну и флешку. 
#### Что произошло на самом деле
Набор трейтор ассистента в инвентаре стандартного борга
#### Как повторить
Зайти за стандартный модуль
#### Дополнительная информация:
Я пробовал сменить модуль, но всё равно выдавался этот набор. Закона нулевого нет, по логам никто не взламывал, но лазерный меч появился посередине смены, а всё остальное уже было. 
Лазерный меч настоящий. 
The camera has been sliced apart by TR-3043 with the energy sword!

**Comment by ArtBsd1** [comment]
Так, поправочка. 
Лазерный меч дался из-за нулевого закона, который почему-то у меня не было видно.  Все остальные предметы так и остались(Станбатон, флешка, баллон, лом, гаечный ключ, анализатор).

**Comment by aIweiss** [comment]
все остальные предметы - и есть норма для стандартного модуля

**Comment by Zmey25** [comment]
Стандартный модуль на то и стандартный, когда ты не знаешь какой хочешь модуль - игра тоже не знает и накидывает тебе кучу мусора. Выбирай сервисный модуль под свои нужды, но там раздатчик стаканов поломали.

**Comment by Momsek** [comment]
Не баг а твоя слепота. Все так и должно быть.

**Comment by Motzord** [comment]
Не баг.
