### ISSUE TITLE
Кристаллы с шахтерского астероида.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#423]
#### Подробное описание проблемы
Некоторые ядра кристаллов сломаны и не дают науку.
#### Что должно было произойти
Они должны давать технологии.
#### Что произошло на самом деле
Они не дают.
#### Как повторить
Достать один из ядер кристалла на шахтерском астероиде.
#### Дополнительная информация:

![](http://i.imgur.com/ZXIAjlt.png)

**Comment by sir-duck** [comment]
Не умею работать с гитом, тк что
/code/modules/research/xenoarchaeology/artifact/artifact_bluespace_crystal.dm
в 40 строке нужно поправить plasmatech на phorontech ?
