### ISSUE TITLE
Агентская карта палится на секхудах

### ISSUE THREAD

**Issue by Zmey25** [TauCetiStation/TauCetiClassic#4233]
#### Подробное описание проблемы
Карта агента не распознается на секхудах и пишет знак вопроса
#### Что должно было произойти
Должна менять худ в зависимости от прописанной профы, если такая есть
#### Что произошло на самом деле
Метагеймеры ходят за тобой молча (а всякие лоттеры просто расстреливают на месте)
#### Как повторить
Взять любую карту агента и секхуды
#### Дополнительная информация:
Как вариант, во время переименования можно сделать выбор из уже имеющихся проф или кастомной. В первом случае приписывать карте нужный худ

**Comment by Motzord** [comment]
> #### Подробное описание проблемы
> Карта агента не распознается на секхудах и пишет знак вопроса
> 
> #### Что должно было произойти
> Должна менять худ в зависимости от прописанной профы, если такая есть
> 
> #### Что произошло на самом деле
> Метагеймеры ходят за тобой молча
> 
> #### Как повторить
> Взять любую карту агента и секхуды
> 
> #### Дополнительная информация:
> Как вариант, во время переименования можно сделать выбор из уже имеющихся проф или кастомной. В первом случае приписывать карте нужный худ

Но ведь Change look...

**Comment by Zmey25** [comment]
Не-а, чейнж лук не влияет на худ.

**Comment by Momsek** [comment]
Так и должно быть. Как говорил ещё мой батя в 90-тых "Не баг а фича". Уж извиняйте, абсолютной имбы не существует.

**Comment by Zmey25** [comment]
Такой себе аргумент. Если имба заключается в получении доступа сканированием - то с тем же шансом можно просто украсть карту. Если в смене профессии - то есть крю манифест, тебя спалят. Если в паре с войс чейнджом - то палишься маской. Если рассматривать каждый из приведенных аргументов, то поймешь, что на станции всё, почти всегда, сводится ко вторым вариантам.
