### ISSUE TITLE
В MouseDrop_T лишние проверки на "доступность" (расстояние)

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#4235]
~~Нужно проверить все моусдропы, что бы присутствовали Adjacent проверки.
Где-то отсутствует, где-то проверяется через ``get_dist()`` но это некорректно.~~

UPD: Да, я не проснулся, всё действительно есть выше по потоку. Нужно просто убрать лишнее.

**Comment by LudwigVonChesterfield** [comment]
Скорее нужно убрать оттуда где они есть, сам прок MouseDrop_T не нативный, и вызываться не в близости не будет

```
/atom/MouseDrop(atom/over)
    if(!usr || !over)
        return
    if(!Adjacent(usr) || !over.Adjacent(usr))
        return // should stop you from dragging through windows

    INVOKE_ASYNC(over, /atom.proc/MouseDrop_T, src, usr)
```
