### ISSUE TITLE
[Task] В травис-тестах не проверяются в компиляции подключаемые/подгружаемые карты

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#4237]
Стоит наверно создать тревису отдельную задачу с инклудом и компиляцией всех дереликт-карт, гейтвеев и прочих подгружаемых шаблонов.

Сейчас их поддержка будет затруднительна, если кто-то изменит (удалит, сменит путь) предмет, присутствующий на этих картах, мы узнаем об ошибках на них не сразу, возможно когда-нибудь совершенно случайно.

**Comment by T6751** [comment]
Resolved by #3818
