### ISSUE TITLE
Бесконечная плитка за борга

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#4248]
#### Подробное описание проблемы
За инженерного борга можно иметь бесконечную плитку для пола
#### Что должно было произойти
При достижении количества плитки равному 0, должно выводиться соответствующее сообщение и ничего не должно происходить.
#### Что произошло на самом деле
Если при 0 плиток нажать на тайл пола без плитки, то ее можно будет снять ломом и использовать как реальную, и так до бесконечности.
#### Как повторить
Тыкнуть за инженерного борга на тайл пола нулем плиток и потом тыкнуть по тому же тайлу ломом.
#### Дополнительная информация:
Снимите варн за дюп плиток(

**Comment by Kortez90** [comment]
Не факт, что это проблема боргов. После взрывов иногда плитка "исчезает" и ее можно выдернуть невидимую ломом.

**Comment by Momsek** [comment]
Вообще, если не ошибаюсь, в таком случае оно автоматом конвертирует метал в плитку... Ну или я дебил и путаю билды(дебил то точно, а вто путаю ли билды...)

**Comment by AirBlack** [comment]
Не конвертирует. Когда становится 0 плиток у человека, то объект плиток пропадает. У боргов же не пропадает, а проверки на кол-во нет походу.
