### ISSUE TITLE
Стандартные химдиспенсеры не разбираются и следовательно не прокачиваются в РНД

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4254]
#### Подробное описание проблемы
Химдиспенсеры в химии (и старой химии тоже) по непонятным причинам не разбираются
#### Что должно было произойти
Они должны разбираться как вся адекватная машинерия
#### Что произошло на самом деле
Закликивание всеми инструментами и скармливание химии богу сингулярности
#### Как повторить
Попытайтесь улучшить химдиспенсеры в химии или слегка переставить их
#### Дополнительная информация:
Скорее всего у нас в коде есть два типа химдиспенсоров. Правильные и прибитые к полу. Fix it.

**Comment by hitsedesen** [comment]
Два типа диспенсеров - обычные и переносные. Там вроде и не предполагается чтобы обычные разбирались, вроде и не баг.

**Comment by Motzord** [comment]
> Два типа диспенсеров - обычные и переносные. Там вроде и не предполагается чтобы обычные разбирались, вроде и не баг.

Однако из-за этого диспенсеры становится и невозможно улучшить, ведь они не разбираются.

Блюспейс RPID тоже отказывается работать

**Comment by hitsedesen** [comment]
#3748

**Comment by Zmey25** [comment]
А зачем их улучшать? Они по дефолту улучшенные.
