### ISSUE TITLE
[Proposal] Лог против русской рулетке

### ISSUE THREAD

**Issue by ArtBsd1** [TauCetiStation/TauCetiClassic#4259]
#### Подробное описание проблемы
Для наших любимых админов. 
При суициде(ствол в рот) в логах VV не отмечается этот лог, было бы полезно сделать этот лог. 
#### Что должно было произойти
Админ должен был найти этот лог и забанить мудаков.
#### Что произошло на самом деле
В VV он не оказался, хотя считается лог аттак.
#### Для чего?
Для мудаков, которые любят застреливаться без особых причин или играя в русскую рулетку, убивая в ней себя 5-10 раз.

**Comment by Motzord** [comment]
Умные и прошаренные пацанчики ващета стреляются резиной и берут с собой ассистуху с дефибами, чтобы продолжать играть...
