### ISSUE TITLE
Невидимый персонаж в сетапе

### ISSUE THREAD

**Issue by ArtBsd1** [TauCetiStation/TauCetiClassic#4268]
#### Подробное описание проблемы
Кукла в сетапе не отображается, создание трапов приостановлено. 
![image](https://user-images.githubusercontent.com/44677341/69491953-f75e9480-0ebd-11ea-8ac6-dd6f5e41f878.png)

#### Что должно было произойти
Должен быть перс 
#### Что произошло на самом деле
Его нет
#### Как повторить
Зайти в сетап

**Comment by hitsedesen** [comment]
Не воспроизводится 
![image](https://user-images.githubusercontent.com/5979121/69492007-70f68280-0ebe-11ea-9e6c-ea7485424c24.png)

**Comment by Alexofp** [comment]
Кукла не отображается пока не будет инициализирована подсистема атомов. На винде на стандартой карте это примерно секунд 40 от запуска сервера, надо подождать. Если и через минуту ничего нет то тогда правда где-то проблема

**Comment by Kortez90** [comment]
Это не проблема. Без выбранной профессии персонаж не отображается.

**Comment by Belfogor** [comment]
@hitsedesen @Kortez90 
Точно такая же проблема. И не только у меня. Мне уже жалобы три поступало на то что невозможно настроить персонажа из лобби. 
![image](https://user-images.githubusercontent.com/12851693/69493115-7dc1a900-0eb3-11ea-9e05-0c58fd6e7c0d.png)
![image](https://user-images.githubusercontent.com/12851693/69493120-8b772e80-0eb3-11ea-8bc0-634e4e8d8074.png)

**Comment by Alexofp** [comment]
Понял в чём проблема, когда тест мержи обновят исправится

**Comment by Kortez90** [comment]
@Belfogor Low там мало. Нужен High.
