### ISSUE TITLE
IPC перегревается внутри меха в космосе.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#4272]
#### Подробное описание проблемы
СПУ перегревается внутри меха с использованием внутреннего бака, но только если находится на клетке космоса или решетке. На обычных тайлах в вакууме такого не происходит.
#### Что должно было произойти
Он не должен был перегреваться. 
#### Что произошло на самом деле
Неожиданный поворот. Он перегревается.
#### Как повторить

- Сесть в любого меха.
- Включить внутренний бак с кислородом меха.
- Зайти на клетку космоса

**Comment by Dominig12** [comment]
так СПУ не используют воздух, они используют охладители, вот если бы в мехе можно было включить кондиционер, то тогда даа

**Comment by Kortez90** [comment]
Во-первых, он там есть.
Во-вторых, он работает.
В-третьих, в кабине есть даже свой "атмос", но на самом деле нет.
В-пятых, #1488.

**Comment by LudwigVonChesterfield** [comment]
#1488

Осознанный дубликат?
