### ISSUE TITLE
Внешний конвейер не работает.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#4278]
#### Подробное описание проблемы
Конвейер вне аванпоста шахтеров не двигается.
#### Что должно было произойти
Вы не поверите, но он должен был двигаться.
#### Что произошло на самом деле
Неожиданный поворот - он этого не делает. (Такое ощущение, что позанимался сексом с бревном.)
#### Как повторить
- Выложить на выключенный конвейер руду из коробки.
- Включить конвейер.
#### Дополнительная информация:
![SS13-3](https://user-images.githubusercontent.com/36198983/69512433-0e03fa80-0f55-11ea-9651-c56eb5b5006b.gif)
Возможно из-за #4269.

**Comment by SpaiR** [comment]
Вероятность что это из-за #4269 - мала. Тут скорее проблемы например во время инициализации карты, то есть что-то специфическое. А лично у меня повторить баг не получилось, что с ПРом, что без.

**Comment by BiQndy** [comment]
Скорее всего, не работает из-за отсутствия света, видите, даже лампы не горят

**Comment by Kortez90** [comment]
> не работает из-за отсутствия света

Тогда почему работает шлюз и конвейер внутри?

**Comment by BiQndy** [comment]
Потому что это находится в другой зоне, зоне самой базы

**Comment by Kortez90** [comment]
У шахты есть свой апц снаружи?
