### ISSUE TITLE
Сделать ИИ возможность зарабатывать научные очки [Proposal]

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4279]
#### Подробное описание проблемы
Интересно будет обыграть вычисление ИИ для получения новых исследований
#### Что должно было произойти
Можно сделать повышение исследований с помощью вычислений разных примеров и чем сложнее пример, тем больше будет даваться очков

**Comment by Kortez90** [comment]
Консоль для буста РНД, где нужно решать тригонометрические функции.

**Comment by Dominig12** [comment]
ну а что, ИИ же не настолько дебил, вот и будет что то вроде крипты

**Comment by Zmey25** [comment]
Наконец-то Пената Пената будет полезной, примеры будет решать.

**Comment by Kortez90** [comment]
![ss13-1](https://user-images.githubusercontent.com/36198983/69597207-37388f80-1016-11ea-8003-346f3f8bebe5.png)

Пока зачаток. За каждый решенный пример рнд начисляется от 5 до 10 очков.
Потом сделаю уравнения и разные задачи с разными наградами. Стаки примеров, решение на скорость и так далее.

**Comment by Kortez90** [comment]
![ss13-1](https://user-images.githubusercontent.com/36198983/69700768-5873ab80-10fc-11ea-9105-8a519fe7b691.png)
Еще чуть-чуть апдейтов.
Перевел на `popup`, добавил кое-какой мусор, обновления окна. Интерфейс переделаю и возникли проблемы с добавлением в консоль в рнд очков.
