### ISSUE TITLE
Нужно больше фич для ИИ (личная кукла ИИ по типу СПУ только нет) [Proposal]

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4287]
#### Подробное описание проблемы
В случае когда требуется прямое вмешательство в физическом плане, а боргов нет, ИИ остается только страдать.
#### Что должно было произойти
У ИИ есть своя личная кукла (например СПУ) и только одна, он может взять контроль над этой куклой и делать что ему нужно (имея свои законы, а так же тот же доступ к электронике), если кукла сдохла, то ИИ будет страдать без куклы. Так же сам ИИ остается в ядре, он как бы по вай фаю подключается к кукле, ок да

**Comment by Motzord** [comment]
малф-ИИ лично крадет капитанскую карту, Нюку, диск ядерной аутентификации и йобу

ИИ лично воюет с нюкой...

**Comment by Pivo24** [comment]
Звучит интересно, посмотрел бы на малфа-робустера с арбалетом против инженеров со сварочками и офицеров с лазурами.

**Comment by Zmey25** [comment]
Помните дети, были времена, когда сска была про взаимодействие людей, когда она была ролевой игрой, когда ученые просили кислоту у химиков.. 

В этом суть иишки, тебе в начале прям пишут, что у тебя есть много плюсов, но твой единственный минус - отсутствие возможности физически передвигаться. Управляй боргами.

**Comment by skvazarb** [comment]
Миллениалы изобрели боргов. У ИИ есть доступ к камерам боргов и они выполняют его приказы. Чем предложенная кукла отличается от боргов с ролевой точкой зрения? Ничем.
