### ISSUE TITLE
Нюкерский Щит

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#429]
#### Подробное описание проблемы
Щит нюкеров не работает должным образом когда смотришь в сторону стреляющего
#### Что должно было произойти
Должны были отражаться выстрелы и не пропускать лазеры.
#### Что произошло на самом деле
Соснул от лвапы с второго выстрела
#### Как повторить
Начать стрелять в человека с энерго-щитом стоящим лицом к вам

**Comment by ZVee** [comment]
Не воспроизвести, все работает как надо. И прямо и по диагоналям.

**Comment by Olt1771** [comment]
Сейчас стоя в карго, с 3 выстрела или с 2 меня кнокнуло через щит, первые два оно не отразило, а просто поглотило, сейчас тестить буду у себя

**Comment by Olt1771** [comment]
You fire the laser rifle!
Willy Jackson is hit by the laser in the right leg!
Willy Jackson fires the sniper rifle!
You fire the laser rifle!
Willy Jackson is hit by the laser in the head!
Rosa Catleay  [Medical] (Intercepted) says, "Глава персонала их получил."
*click*
Willy Jackson fires the sniper rifle!
John Doe is hit by the sniper beam in the chest!
Your armor softens the blow!
A melted patch marks the surface of the blood-red hardsuit!
You are not holding anything to equip.
Your chest hurts badly.
Willy Jackson fires the sniper rifle!
John Doe is hit by the sniper beam in the chest!
Your armor softens the blow!
The melted patch on the blood-red hardsuit widens!
A small burn marks the surface of the blood-red hardsuit!
Willy Jackson fires the sniper rifle!
John Doe is hit by the sniper beam in the chest!
Your armor softens the blow!
The small burn on the scorched blood-red hardsuit widens!
Willy Jackson fires the sniper rifle!
John Doe is hit by the sniper beam in the chest!
Your armor softens the blow!
The small burn on the scorched blood-red hardsuit widens!
A small burn marks the surface of the scorched blood-red hardsuit!
Lucius Bile  [145.9] (Intercepted) says, "Пальба в карго"
Willy Jackson fires the energy gun!
John Doe is hit by the laser in the chest!
Your armor softens the blow!
The small burn on the scorched blood-red hardsuit widens!
Willy Jackson fires the energy gun!
John Doe is hit by the laser in the right arm!
Your armor softens the blow!
The small burn on the scorched blood-red hardsuit widens!
Willy Jackson fires the energy gun!
John Doe is hit by the laser in the chest!
Your armor softens the blow!
The small burn on the scorched blood-red hardsuit widens!
A small burn marks the surface of the scorched blood-red hardsuit!
Willy Jackson fires the energy gun!
John Doe is hit by the laser in the left arm!
Your armor softens the blow!
The small burn on the scorched blood-red hardsuit widens!
... You can almost hear someone talking ...
Your armor softens the blow!

Вот лог, в меня стреляли но в логе даже не отображалось что щит поглотил первые 2 выстрела

**Comment by ZVee** [comment]
Да логи постить смысла нет.

**Comment by Olt1771** [comment]
Просто это весьма странно, сам сейчас тестил, всё в норме. Играл на сервере, получил от лвапы, хотя стоял и смотрел в сторону стреляющего

**Comment by ZVee** [comment]
На сервере все что угодно бывает происходит, то что нельзя никак воспроизвести или получить локально и такие баги как правило невозможно и пофиксить соответственно, если конечно вдруг не будет возможности повторять. Возможно была какая-то особенность.

**Comment by Rarf247** [comment]
Потестил у себя на локалке. Скрины скидывать сюда наверное не буду.
Итоги:
Цель без брони и со щитом: в 5-и тестах из 5-и выстрел был полностью отражён щитом.
Цель в риге и со щитом в 5-и тестах из 6-и выстрел прошёл щит и был частично поглощен броней рига. В 1-м тесте из 6-и выстрел был полностью блокирован щитом, но не отражён.

**Comment by Olt1771** [comment]
Суть в риге, я об этом не подумал. Благодарю что обнаружил
