### ISSUE TITLE
Невозможность выбрать РД за СПУ.

### ISSUE THREAD

**Issue by Konradiuss** [TauCetiStation/TauCetiClassic#4292]
#### Подробное описание проблемы
Вот те доступные роли которые должны быть у СПУ:
https://wiki.taucetistation.org/Xeno_roles_restrictions
Проблема в том что они немного не соответствуют этой табличке. Нельзя выбрать РД.
![Screenshot_2](https://user-images.githubusercontent.com/56347411/69846824-f2af2d00-127d-11ea-9308-2f602a3c2d85.png)

#### Что должно было произойти
Должна быть возможность брать РД за СПУ.
#### Что произошло на самом деле
Брать РД за СПУ нельзя ограничение ксено-расы.
#### Как повторить
Попробовать просто выбрать РД в начале раунда или Join Game'ом.
#### Дополнительная информация:
Играю на первом сервере, после того как все почему-то перебежали на второй. Люблю меньше онлайна. Пишу потому-что эта проблема может не распространятся на оба сервера.

**Comment by FelixRuin** [comment]
Эта проблема уже решается

**Comment by Konradiuss** [comment]
Если что, то этот баг все еще существует.

**Comment by Konradiuss** [comment]
Uh... Up?

**Comment by FelixRuin** [comment]
Пр всё ещё в процессе доделывания
Серьёзно, он будет сделан, надеюсь на себя

**Comment by Konradiuss** [comment]
Я тоже правда надеюсь на тебя, хочу отыграть СПУ РД.
