### ISSUE TITLE
Не работают речевые особенности ксеносов

### ISSUE THREAD

**Issue by vitalezzz98** [TauCetiStation/TauCetiClassic#4297]
#### Подробное описание проблемы
После недавней обновы на первом сервере перестали работать всякие удвоения и утроения некоторых букв у таяр и ящеров
#### Что должно было произойти
Giant Cat says, "Эй, Еррржан, вставай!"
Giant Lizard says, "Эй, Ержан, вссставай!"
#### Что произошло на самом деле
Giant Cat says, "Эй, Ержан, вставай!"
Giant Lizard says, "Эй, Ержан, вставай!"
#### Как повторить
Попробовать набрать фразы, содержащие буквы "р" или "с"
#### Дополнительная информация:
На втором сервере всё это работает.
Нигде не нашел упоминание этой проблемы, поэтому не знаю решается она или нет.

**Comment by SpaiR** [comment]
Бага была связана с одним из ПРов в тест мерже. Обновил, так что должно пофиксится.
