### ISSUE TITLE
[Proposal] Добавить в банризон номер сервера и id раунда

### ISSUE THREAD

**Issue by aIweiss** [TauCetiStation/TauCetiClassic#4298]
#### Подробное описание проблемы
Забаненные не помнят, на каком сервере и в каком раунде произошел баннинг
#### Что должно было произойти
Они могут это посмотреть в любой момент
#### Что произошло на самом деле
Если ты не помнишь, то узнать нереально
#### Как повторить
Получить жбан.
#### Дополнительная информация:
Ишшуе-пропозал создан по мотивам смешнявки на форуме и в центрокомме

**Comment by Sakuya-Izayoi** [comment]
Вопрос к мейнтейнерам... Нам для этого надо завести ещё пару полей в базе данных или просто дописывать эти данные в банризон?

**Comment by volas** [comment]
В базе поля уже есть,
https://github.com/TauCetiStation/TauCetiClassic/blob/8ff8309d57357385832401933df7e308eff9b42e/SQL/ss13_feed.sql#L26-L30
