### ISSUE TITLE
[Proposal] Вернуть Ганг в ротацию

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4303]
#### Подробное описание проблемы
Ганг хороший и интересный режим, стоящий примерно на уровне с ревой, которого нет в ротации
#### Что должно было произойти
Он есть в ротации и все как всегда всем не нравится
#### Что произошло на самом деле
Его нет в ротации.
#### Как повторить
Не знаю

**Comment by Morair** [comment]
Его и нет потому что он ~~говно~~ плохой режим.
Рева 2.0, где ты взрываешь станцию и можешь купить себе оружие.
Also: https://github.com/TauCetiStation/TauCetiClassic/issues/4304 - Эй хочешь вступить в мой gang просто потому что да и взорвать станцию? - Да (а где мотивация ( у вас же рп сервер, да? )). Или как с текущим культом будет, рассказываешь про культ кулстори 5 минут каждому встречному, а тебе говорят - нет, о боже кровь...только не это... И так до конца раунда ( если тебя не кинут к психологу ) законвертив всего ~~своих метадрузей~~ 3 человек.

**Comment by Motzord** [comment]
> Его и нет потому что он ~говно~ плохой режим.
> Рева 2.0, где ты взрываешь станцию и можешь купить себе оружие.
> Also: #4304 - Эй хочешь вступить в мой gang просто потому что да и взорвать станцию? - Да (а где мотивация ( у вас же рп сервер, да? )). Или как с текущим культом будет, рассказываешь про культ кулстори 5 минут каждому встречному, а тебе говорят - нет, о боже кровь...только не это... И так до конца раунда ( если тебя не кинут к психологу ) законвертив всего ~своих метадрузей~ 3 человек.

Очень хороший аргумент, но культ почему-то вызывает нарси, рева выносит глав и  почему-то раунд не скатывается в эксту

**Comment by skvazarb** [comment]
1) Его никогда не было в секрете
2) Он отключен в конфиге, пропозал к билду не имеет отношения, автору нужно на форум

**Comment by cool20141** [comment]
Добавьте, пж

**Comment by cool20141** [comment]
Ну так что, ммм?

**Comment by cool20141** [comment]
Ну так когда, ммм?

**Comment by cool20141** [comment]
Ну че там с гэнгом

**Comment by T6751** [comment]
>     Его никогда не было в секрете
>     Он отключен в конфиге, пропозал к билду не имеет отношения, автору нужно на форум

А на форуме обсуждалось? К тому же ручка ещё не пофикшена #4304

**Comment by cool20141** [comment]
Ручку фиксить не надо, на форуме людей спрашивать–тем более. Нужно постфактум получать отзывы от игроков, я считаю, чтобы сложилось впечатление(И на форуме РО у меня)

**Comment by EdlerN** [comment]
> Ручку фиксить не надо, на форуме людей спрашивать–тем более. Нужно постфактум получать отзывы от игроков, я считаю, чтобы сложилось впечатление(И на форуме РО у меня)

![tenor](https://user-images.githubusercontent.com/26942612/89032795-157a6f80-d33e-11ea-80a1-fc5892d4fbf8.gif)

**Comment by cool20141** [comment]
![image](https://user-images.githubusercontent.com/53309265/89033277-1c55b200-d33f-11ea-879d-43bdaec9a9f1.png)
С таким человеком беседу вести не хочется :nauseated_face:

**Comment by Ambassadoing** [comment]
> Ручку фиксить не надо, на форуме людей спрашивать–тем более. Нужно постфактум получать отзывы от игроков, я считаю, чтобы сложилось впечатление(И на форуме РО у меня)

![15586214036122](https://user-images.githubusercontent.com/48314394/89034465-ad2d8d00-d341-11ea-99e0-c01de2e484ac.png)

**Comment by cool20141** [comment]
Ну что там по гангу, гэнгу

**Comment by Ambassadoing** [comment]
Кодь, фикси баги, возвращай.

**Comment by cool20141** [comment]
Код есть, багов нет, возвращать не хотят

**Comment by cool20141** [comment]
Верните ганг, добавьте ганг, сделайте ганг :crying_cat_face:

**Comment by KIBORG04** [comment]
Я сделал для них худы, остальное за вами

**Comment by cool20141** [comment]
Ну что там с гэнгом

**Comment by WallShrabnic** [comment]
Прикрывайте, код генга удалён

**Comment by T6751** [comment]
Режим был удалён в #6909. В связи с этим, если нужно возвращение ганга, то требуется сначала продумать идею и затем уже реализовать её без проблем старого режима.
