### ISSUE TITLE
Понерфить ручку бандитов в режиме ганг.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4304]
#### Подробное описание проблемы
Ручка ганга является альтернативу лолфлеш ревы, хорошо это или плохо решать вам
#### Что должно было произойти
Как и для вступление в культ/реву высвечивается окошко позволяющее добровольно выбирать
#### Что произошло на самом деле
Кольнули
Уснул
Недоволен
#### Как повторить
...

**Comment by T6751** [comment]
Режим был удалён в #6909. В связи с этим больше не актуально
