### ISSUE TITLE
Пофиксить худ ганга

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4305]
#### Подробное описание проблемы
Худ бандитов барахлит, лейтенант может не видеть члена банды и посчитать его шпионом
#### Что должно было произойти
Клоун — наш бандит, в нашей куртке, крутой чувак.
#### Что произошло на самом деле
"Мистер клоун? Рой Волкер передает вам привет"
#### Как повторить
Поиграйте в ганг, станьте лейтенантом, найдите персонажа в форме вашей банды, тыкните по нему ручкой и осознайте, что он в другой банде.

**Comment by T6751** [comment]
Режим был удалён в #6909. В связи с этим проблема больше не актуальна
