### ISSUE TITLE
[proposal] Красное освещение при дельте.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4306]
#### Подробное описание проблемы
Дельта является стадией когда станции приходит неминуемый п@здец, и очень огорчает, что это выглядит не так эпично
#### Что должно было произойти
>Анонсировали дельту, сирена страшно пиликает, везде аварийный красный свет, страшно блин
#### Что произошло на самом деле
>Дельта код. >Чет пиликает. >Пиздец вроде не так сильно ощущается
#### Как повторить
Включите дельту. Расстройтесь

**Comment by atik1n** [comment]
Реквестирую поменять звук сирены дельты на тот, что играет в анонсе

**Comment by ViDLiathan** [comment]
https://www.youtube.com/watch?v=kndNnPDfqW8
