### ISSUE TITLE
Бафнуть Walk и добавить стамину на Run [Proposal]

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4307]
#### Подробное описание проблемы
Люди постоянно бегают и горят от того что подскальзываются на воде
#### Что должно было произойти
Люди ходят шагом и не подскалльзываются на ровном месте, а так же не бегают по станции перманентно
#### Что произошло на самом деле
все бегают
#### Дополнительная информация:
Добавить стамину на бег и повысить скорость ходьбы

**Comment by AndroBetel** [comment]
нет

**Comment by Dominig12** [comment]
> нет

почему

**Comment by aIweiss** [comment]
1) переименовать волк в сталк

теперь люди медленно не ходят, а (кродуться), чтобы не поскользнуться

2) переименовать ран в волк

теперь люди ходят по станции

3, опционально) добавить ран со стаминой, и чтобы на нем при бампе во что-нибудь роняло и станило, а если упасть, то наносило брут на голову

теперь люди умеют беготь

**Comment by Motzord** [comment]
1. Спиздить систему с фиников
2. ???
3. Никто не будет кодить
4. ???
5. /thread

**Comment by Kortez90** [comment]
>Никто не будет кодить
Я бы занялся, если бы торчал на двух серверах сразу, но это не так.

**Comment by Motzord** [comment]
Уже был ПР со стаминой, всем не понравилось, закрываем

**Comment by LudwigVonChesterfield** [comment]
Тот ПР не делал то, что предложено в ишуе.

Тот ПР незначительно баффал Walk, и значительно нёрфил возможность бегать как сейчас

Что привело к общему замедлению темпа игры, что естественно мало кому могло понравиться.
