### ISSUE TITLE
[Proposal] Добавить NanoMed по всей станции.

### ISSUE THREAD

**Issue by Lafrien** [TauCetiStation/TauCetiClassic#4317]
#### Подробное описание проблемы
Добавить медицинские раздатчики NanoMed с бинтами и мазями по разным местам в коридорах станции для возможности забинтовать и обработать кровотечения пока ожидаешь Парамедика.
#### Что должно было произойти
Забинтовать себя и ожидать парамедика или врача, если они есть и путь от него к тебе не требует открывания аварийных створок с разгерметизацией или пожаром, или же продолжать свои дела.
#### Что произошло на самом деле
Кровотечение продолжает идти пока не придёт парамедик или врач. В шкафах только Дексалин и Инапровалин с анализатором, а отделы, в которых есть аптечки первой помощи требуют доступ, которого у тебя нету.
#### Как повторить
Порезать коленку или локоть в отбытии.
#### Дополнительная информация:
Огромное количество кислородных аптечек и отсутствие каких-либо простых аптечек первой помощи.

**Comment by Dominig12** [comment]
лучше уж не нано мед, а аптечки первой помощи в стенах как на шаттле

**Comment by Lafrien** [comment]
> лучше уж не нано мед, а аптечки первой помощи в стенах как на шаттле
Так тоже можно кстати. Или хотя бы просто аптечки первой помощи раскидать по станции.

**Comment by Motzord** [comment]
Проблема в том, что у немедиков нет доступа к наномеду. Можете добавлять, ничего не изменится

**Comment by FelixRuin** [comment]
доступ то убрать можно

**Comment by Kortez90** [comment]
Нет смысла. Кровотечение можно зажать рукой и ждать медиков. Бинты есть в свободном доступе почти во всей станции. Содержимое синих шкафов не предназначено для лечения порезов. Единственное, что стоило бы добавить - настенный шкафчик с бинтами и мазью в прибытии.

**Comment by BiQndy** [comment]
Добавить наномед по станции = убить профессию медиков, как по мне

**Comment by Kortez90** [comment]
> 
> 
> Добавить наномед по станции = убить профессию медиков, как по мне

Когда вокруг почти все метагеи и боевые - это особо ничего не изменит.

**Comment by Lafrien** [comment]
> Бинты есть в свободном доступе почти во всей станции.

В том то и проблема, что не во всей станции. Всего есть по одной аптечке в каждом отделе, куда требуется доступ соответствующего отдела.


> Добавить наномед по станции = убить профессию медиков, как по мне

Добавление бинтов для того, что бы не орать на всю станцию, что ты порезался убъёт всю профу медиков? Я не говорю добавить красные аптечки с мембранами по всей станции или добавлении возможности вправлять свои кости, а просто бинты и мази из аптечек первой помощи.

**Comment by Zmey25** [comment]
Станция про взаимодействие людей. В этом смысл игры, просить, чтобы тебя подлечили.
