### ISSUE TITLE
Хуманы не могут дышать воздухом в баллонах

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4321]
#### Подробное описание проблемы
Хуманы принимают из баллонов лишь чистый кислород, если заправить баллон из белой канистры с воздухом, они скорее всего начнут гаспать
#### Что должно было произойти
Дышишь.
#### Что произошло на самом деле
Не дышишь.
#### Как повторить
Подышать воздухом из баллона

**Comment by EdlerN** [comment]
Люди дышат воздухом из баллона. Проблема в том что тебе не важно сколько ты вдыхаешь газа. Тебе важно сколько ты вдыхаешь кислорода. А в смеси кислорода меньше чем если баллон заправлен чистым. Потому, выходное давление нужно ставить выше. 

А еще ментором зовётся, ей богу

**Comment by Motzord** [comment]
> Люди дышат воздухом из баллона. Проблема в том что тебе не важно сколько ты вдыхаешь газа. Тебе важно сколько ты вдыхаешь кислорода. А в смеси кислорода меньше чем если баллон заправлен чистым. Потому, выходное давление нужно ставить выше.
> 
> А еще ментором зовётся, ей богу

Блин действительно, я же забыл, что человеки то дышут воздухом нормально минимум при 60кпа. А в баллоне было дефолтные 17. Все, закрываю ишью

И это ментор...
