### ISSUE TITLE
Баг с граффити

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4323]
#### Подробное описание проблемы
Граффити, надписи и все оверлеи мелка и баллончика почему-то рисуются под стеной, а не на стене
#### Что должно было произойти
Спокойно изрисовал стены
#### Что произошло на самом деле
Теоретические гэнги по стелсу захватывают все отсеки.
#### Как повторить
Попробуйте нарисовать что-нибудь на стене

**Comment by Kortez90** [comment]
А также не смывается кровь и нет печати на бумаге от ЦК. Это дело рук одного рефактора под номером #4260.

**Comment by Motzord** [comment]
> А также не смывается кровь и нет печати на бумаге от ЦК. Это дело рук одного рефактора под номером #4260.

Только хотел писать ишью о несмываемой крови на иконке ботиночек. Оформлять или не стоит?

**Comment by Kortez90** [comment]
Почему бы и нет? Кровь не отмывается не только с ботинок, но и с инструментов и так далее.

**Comment by Motzord** [comment]
> Почему бы и нет? Кровь не отмывается не только с ботинок, но и с инструментов и так далее.

как оказалось это древнейшая проблема и вряд ли тот рефакторинг повлиял на это. (Но и не решил ее, что обидно)

**Comment by Kortez90** [comment]
Проблема появилась после него.

**Comment by Dominig12** [comment]
Насчет крови старая проблема, насчет граффити на стенах старая проблема, это не от рефрактора

**Comment by Motzord** [comment]
Проблема сейчас с кровью возникла как раз новая. Раньше такая херня была, лишь если мыть ботиночки в раковине, сейчас не помогает ни мыло ни клинер.
