### ISSUE TITLE
Тенелинги умирают при перерождении.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#4326]
#### Подробное описание проблемы
Сразу после перерождения тенелинг погибает.
#### Что должно было произойти
Это быть не должно. Неожиданно, да?
#### Что произошло на самом деле
А вот еще один невероятный поворот. Они умирают.
#### Как повторить
- Стать тенелингом.
- Переродиться.

**Comment by Kortez90** [comment]
И поставьте плашку "срочно". Целый режим сломался.

**Comment by skvazarb** [comment]
Это мой ПР из тестмерджа сломал, нехорошо получилось, что у нас есть спишесы, которые могут без мозгов жить. Добавил фикс.
