### ISSUE TITLE
Чрезмерно завышенная скорость конвейеров [Proposal]

### ISSUE THREAD

**Issue by Permyack** [TauCetiStation/TauCetiClassic#4331]
#### Подробное описание проблемы
Конвейерная лента слишком быстрая. За конвейером невозможно следить, конвейер невозможно контролировать.
#### Что должно было произойти
Приемлемая старая скорость конвейера. Удобно следить, легче контролировать.
#### Что произошло на самом деле
Конвейерная лента слишком быстро работает. Персонаж не в состоянии её перегнать, игрок не в состоянии проследить за ней и среагировать в нужный момент, когда это необходимо.
#### Как повторить
Включить конвейер и испытать его скорость.
#### Дополнительная информация:
Раньше конвейерная лента имела нормальную неторопливую скорость. Персонаж - человек вполне мог пробежать по прямой конвейерной ленте из пункта А в пункт Б без особых осложнений.
Сейчас персонаж будет зажат в пункте А без шанса сдвинуться дальше. Даже быстрые персонажи вряд-ли смогут справиться с этой задачей.
Игроку очень сложно следить за тем, что попадает на сам конвейер. Если в Карго включен конвейер и в Карго полетело чье-то тело или ценный предмет, то можете считать, что это тело или предмет уже у Мусорщиков.
Данное изменение может быть удобным лишь для шахтеров. Для иных игроков оно выглядит определенно излишним.
Я уверен, что можно было бы сделать систему переплавки руды более компактной, нежели ломать конвейер чрезмерно завышенной скоростью с которой вы сами не смогли бы совладать работая конкретно с самим конвейером.
Например: Можно было бы разгружать ящик с рудой напрямую в печь и из печи сразу (или почти сразу. Всё-же нужен промежуток глядя на который ты смог-бы понять, что всё настроил правильно. Кстати сейчас это тоже сложнее т.к. весь шлак начал бы гораздо быстрее лететь перед глазами) в упаковщик (не знаю как верно назвать штуку, которая создает стаки из листов). Схема "Ящик-Печь-Упаковщик" с минимальным использованием конвейерных лент выглядит гораздо лучше, чем увеличение скорости самого конвейера.

**Comment by BiQndy** [comment]
Да действительно это не удобно, приходится садиться в Рипли, что бы безопасно мусор скинуть на ленту.

**Comment by Kortez90** [comment]
#4269.
Конвейеры - опасная штука. Шахтер и мусорщик - опасная профессия. Если вы не можете следовать технике безопасности и не можете не лезть на ленту - это ваша проблема. У карго есть рычаги для ленты. В том же месте есть стульчик для оператора, который должен этим заниматься и сортировать то, что летит в мусор.

**Comment by Permyack** [comment]
> 
> 
> #4269.
> Конвейеры - опасная штука. Шахтер и мусорщик - опасная профессия. Если вы не можете следовать технике безопасности и не можете не лезть на ленту - это ваша проблема. У карго есть рычаги для ленты. В том же месте есть стульчик для оператора, который должен этим заниматься и сортировать то, что летит в мусор.

Рычаг далеко, ты в Скафандре. Тебе нужно обогнуть весь конвейер.
Раньше я без проблем вставал на ленту и выгружал мешок. Единственной проблемой была труба. Сейчас ты встаешь со стороны трубы и выходишь уже у измельчителя, который УЖЕ на тебя среагировал и отрубился (если повезет...а может их и вовсе обезопасили. Точно не знаю).
Если говорить про Карго, то похоже действительно стоит начинать устраивать драки по этому поводу. Хотя вряд-ли это сработает.

**Comment by Kortez90** [comment]
> 
> 
> > Конвейеры - опасная штука. Шахтер и мусорщик - опасная профессия. Если вы не можете следовать технике безопасности и не можете не лезть на ленту - это ваша проблема.


> 
> Рычаг далеко, ты в Скафандре. Тебе нужно обогнуть весь конвейер.
> Раньше я без проблем вставал на ленту и выгружал мешок. Единственной проблемой была труба.

**Comment by Permyack** [comment]
> 
> 
> > > Конвейеры - опасная штука. Шахтер и мусорщик - опасная профессия. **Если вы не можете следовать технике безопасности и не можете не лезть на ленту - это ваша проблема**.
> 
> > Раньше я без проблем вставал на ленту и выгружал мешок. Единственной проблемой была труба.
> 
> > Рычаг далеко, ты в Скафандре. Тебе нужно обогнуть весь конвейер.
> 
> 9 клеток.
> ![ss13-1](https://user-images.githubusercontent.com/36198983/70354691-568ab480-1881-11ea-Я

**Comment by Permyack** [comment]
> 
> 
> > > Конвейеры - опасная штука. Шахтер и мусорщик - опасная профессия. **Если вы не можете следовать технике безопасности и не можете не лезть на ленту - это ваша проблема**.
> 
> > Раньше я без проблем вставал на ленту и выгружал мешок. Единственной проблемой была труба.
> 
> > Рычаг далеко, ты в Скафандре. Тебе нужно обогнуть весь конвейер.
> 
> 9 клеток.
> ![ss13-1](https://user-images.githubusercontent.com/36198983/70354691-568ab480-1881-11ea-8937-e264a6ef6ff8.png)

Ты так путь пометить пытался или что? Напрямую явно не выйдет из-за скорости конвейера и трубы (стационарная пушка с шрапнелью...). То есть приходится обходить всё. Это не удобно.
Бонусом конечно можно сказать, что скорость не выглядит правдоподобной. ИРЛ человек должен следить за конвейером и знать, что всё хорошо. Здесь ты не успеваешь следить за ним...

**Comment by Kortez90** [comment]
Нет. Это кровь людей, не соблюдающих ТБ и лезущих на конвейер. То есть, таких как ты.
Неудобно? Долго? Лень? Что ж... Давайте тогда уберем монстров в астероиде. Ведь это неудобно. Давайте уберем доступ дверей, ведь так неудобно красть капитанскую карточку. Давайте уберем необходимость строить реактор, ведь это так неудобно. Давайте уберем батарейки, ведь это так неудобно. Давайте уберем ресурсы и исследования, ведь это так неудобно. Давайте уберем скафандры, ведь это так неудобно. Давайте уберем невозможность ходить голым в космосе, ведь это так неудобно.

**Comment by Permyack** [comment]
> 
> 
> Нет. Это кровь людей, не соблюдающих ТБ и лезущих на конвейер. То есть, таких как ты.
> Неудобно? Долго? Лень? Что ж... Давайте тогда уберем монстров в астероиде. Ведь это неудобно. Давайте уберем доступ дверей, ведь так неудобно красть капитанскую карточку. Давайте уберем необходимость строить реактор, ведь это так неудобно. Давайте уберем батарейки, ведь это так неудобно. Давайте уберем ресурсы и исследования, ведь это так неудобно. Давайте уберем скафандры, ведь это так неудобно. Давайте уберем невозможность ходить голым в космосе, ведь это так неудобно.

Глупая позиция на мой взгляд. Очень глупая. Нет смысла проводить подобные аналогии в данном случае. Это выглядит глупо. Я так-же могу заявить следующее: "Тебе неудобно ждать пока вся руда дойдет до печи, переплавится, дойдет от печи до Упаковщика, соберется в стаки и выйдет к тебе в ящик?" "Давай подкрутим скорость конвейерам, чтобы шахтеры не страдали". И именно это и произошло. Именно так это и выглядит. Двойные стандарты? Да, пожалуй.
Если уж говорить опять о Т.Б. ,то никаких проблем раньше не было. Спокойно встал на конвейер, разгрузил мешок, спокойно ушел. Ты не тратил время на обход конвейера и трубы, ты не останавливал весь процесс. Всё шло своим чередом. Единственной проблемой здесь могли бы стать какие-нибудь фризы или "ой, мне нужно срочно отойти". Вот это могло стать проблемой для игрока. В остальном всё было гладко.
Это конечно без учета Трубы и отдела.
А если уж говорить о трубе, тему с которой ты уже видел и зачем-то решил прикрепить ссылку на эту тему, то там остановка конвейера тебе не поможет. Карго всё-равно будет тебя игнорировать, как и многие. Ты всё-равно будешь находиться в опасности будучи даже на остановленном конвейере. В крайнем случае будет поврежден твой мех. И раз уж ты заговорил  о Т.Б. , то это наглядный пример нарушения Т.Б. Вряд-ли в мех вообще должно что-то прилетать.
Думаю в реальности люди бы продумали о том, чтобы такое вообще не происходило.

**Comment by Kortez90** [comment]
Что ж... Давай я тебе третий или уже четвертый раз скажу. Несоблюдение техники безопасности (не вставать на конвейер) ведет к трагическим последствиям. Если ты не можешь соблюдать банальные правила и не можешь нажать F3 и попросить карго не швыряться в тебя мусором, то это не проблема конвейеров и не проблема кода. Это твоя проблема, которую ты не хочешь решать внутри игры, потому что играешь в механ. Ученым неудобно прыгать в воронку с GPS, чтобы достать координаты и провести калибровку. Шахтерам неудобно копать, попутно сражаясь с монстрами. Врачам неудобно проводить операции множеством инструментов. Это часть геймплея, которую ты не хочешь соблюдать и весь твой пропозал состоит в том, что тебя угнетают конвейеры и ты хочешь работать по старым чертежам. Что уж там говорить, если тебе лень пройти каких-то девять клеток до рычага?

**Comment by Permyack** [comment]
> 
> 
> Что ж... Давай я тебе третий или уже четвертый раз скажу. Несоблюдение техники безопасности (не вставать на конвейер) ведет к трагическим последствиям. Если ты не можешь соблюдать банальные правила и не можешь нажать F3 и попросить карго не швыряться в тебя мусором, то это не проблема конвейеров и не проблема кода. Это твоя проблема, которую ты не хочешь решать внутри игры, потому что играешь в механ. Ученым неудобно прыгать в воронку с GPS, чтобы достать координаты и провести калибровку. Шахтерам неудобно копать, попутно сражаясь с монстрами. Врачам неудобно проводить операции множеством инструментов. Это часть геймплея, которую ты не хочешь соблюдать и весь твой пропозал состоит в том, что тебя угнетают конвейеры и ты хочешь работать по старым чертежам. Что уж там говорить, если тебе лень пройти каких-то девять клеток до рычага?

Что ж...Давай я тебе третий или уже четвертый раз скажу. Ни к каким последствиям при нормальном раскладе это не вело. Вообще. Я в состоянии нажать F3  и попросить карго не швыряться в меня мусором, но это не срабатывает.
И опять ты начинаешь писать не по теме. Не вижу дальнейшего смысла продолжать этот глупый спор с тобой, ты всё-равно не желаешь ничего понимать и не желаешь ничего видеть. Ты видимо даже не имеешь представления о текущей ситуации и пишешь лишь бы что-то написать.
Мне не сложно обойти конвейер, остановить весь процесс, сделать свои дела на конвейере прежде в 100 раз предупредив Карго о том, чтобы они ничего там у себя не сделали, включить конвейер и вернуться на исходную позицию. Но это долго и невыгодно.
Почему ты придираешься ко мне, к моим "нарушениям Т.Б.", которые в целом могут быть весьма преувеличены т.к. при старой скорости проблем с конкретно скоростью (а мы говорим сейчас именно про неё, а не про что-либо еще) не было, но при этом ни слова не говоришь о шахтерах на которых данное изменение и было нацелено? Всё те-же двойные стандарты.

Почему шахтеры не могли подождать пока руда не переплавится?  Это их проблема, а не проблема скорости конвейера, плавильни и упаковщика. Но почему-то для шахтеров (А для чего еще это делать? Карго в принципе пофиг на то, как быстро через них пролетит мусор и как быстро по конвейеру уйдет почта, которой они занимаются не так и часто. 

Мусорщикам, как я и писал, это попросту ни к чему. Они второе звено, невольно отвечающее за всё то, что попало в мусоропровод. Лишь они могут поймать кого-либо или что-либо, если Карго пропустило всё через себя. Мусорщикам нет реального профита от чрезмерно быстрой ленты. Они просто могут скидывать кубы мусора в упор к измельчителю и не напрягаться лишний раз.
Еще конвейеры есть у ученых, но там они не выглядят особо востребованными. Вряд-ли ученые провозят по ним что-то в большом количестве. Для кого-же их тогда так ускоряли? Думаю ответ очевиден, только для шахтеров, которые не могли подождать...

**Comment by Ambassadoing** [comment]
>мусорщикам профита от быстрых конвейеров нет, значит и шахтёрам тоже профита быть не должно, вертайте обратно, ряяя!!111!!!

Вот такая вот у тебя позиция сейчас.

Закройте уже этот бредовый ишью, пожалуйста.

**Comment by Permyack** [comment]
> 
> 
> > мусорщикам профита от быстрых конвейеров нет, значит и шахтёрам тоже профита быть не должно, вертайте обратно, ряяя!!111!!!
> 
> Вот такая вот у тебя позиция сейчас.
> 
> Закройте уже этот бредовый ишью, пожалуйста.

Я не припомню, чтобы ты выкладывал своё конструктивное и адекватное мнение по поводу данной темы "За" или "Против" отката данного изменения. Да и альтернатив ты не предлагал.
Фича полезна лишь шахтерам - это факт. Всё.

Цитирую твоё-же сообщение с форума: "Скорость увеличили, дабы шахтёры не ждали минут по пять-десять , пока их добыча перерабатывается."
Теперь я попробую ответить тебе в твоём-же (ну или почти в твоём) стиле: Скорость нужно откатить к старой, дабы мусорщики не тратили время на обход конвейера и не останавливали весь процесс ради того, чтобы закинуть скрап.
Я ничего не имею против самих шахтеров и вполне понимаю, что им не хочется ждать переплавки. Но почему решение проблемы для одной стороны, создает проблемы для другой стороны? Я уже предлагал более трудоемкий (возможно) вариант с ремапом шахты, нацеленный на создание более компактной "плавильни" (подразумеваю всю систему целиком). Печь и Упаковщик можно разместить ближе друг к другу оставив некое пространство для наблюдения (не все могут настроить Плавильню правильно и им лучше увидеть шлак своевременно, чем осознать всё, когда будет слишком поздно). С технической стороны схема не может быть не рабочей. Можно ускорить саму переплавку руды, но это рисковано т.к. при ошибке можно наделать больше шлака. Шахтеры сэкономят время на конвейере и им не придется долго ждать. Остальные же не будут мучаться с столь завышенными скоростями.
Неужели кто-то серьезно считает эту скорость адекватной для всех случаев? Кажется вы просто не учитываете мнение другой стороны, как факт.
И да, про всеобщие страдания это был сарказм. Неужели ты это не понял?

**Comment by Ambassadoing** [comment]
>Но почему решение проблемы для одной стороны, создает проблемы для другой стороны?

Все """проблемы""", которые ты, Пермяк, тут перечислял - это проблемы не скорости конвейера, а твоего *нежелания* сходить лишние девять клеток, чтобы ***ОТКЛЮЧИТЬ ЭТУ ЧЁРТОВУ ЛЕНТУ***. То, что ТЫ не хочешь лишний раз оторваться от аутирования в разгребание мусорных куч, чтобы обеспечить СЕБЕ безопасность при сбросе накопанного ТОБОЮ ЖЕ хлама на ленту - это ТВОЯ проблема. Не скорости ленты проблема, а ТВОЯ.

**Comment by Permyack** [comment]
> 
> 
> > Но почему решение проблемы для одной стороны, создает проблемы для другой стороны?
> 
> Все """проблемы""", которые ты, Пермяк, тут перечислял - это проблемы не скорости конвейера, а твоего _нежелания_ сходить лишние девять клеток, чтобы _**ОТКЛЮЧИТЬ ЭТУ ЧЁРТОВУ ЛЕНТУ**_. То, что ТЫ не хочешь лишний раз оторваться от аутирования в разгребание мусорных куч, чтобы обеспечить СЕБЕ безопасность при сбросе накопанного ТОБОЮ ЖЕ хлама на ленту - это ТВОЯ проблема. Не скорости ленты проблема, а ТВОЯ.

Ты понимаешь, что каждый раз, когда ты задаешь этот вопрос, ты подталкиваешь меня на аналогичный вопрос - Шахтерам так сложно было подождать? Придумай уже что-то новенькое что-ли. Попробуй адекватно расписать то для чего это нужно и почему все остальные должны с этим мириться, когда им попросту не нужна эта скорость. Попробуй, тогда уже и поговорим.

**Comment by AndroBetel** [comment]
человека заставили пройти 9 блоков и он противоборствует уже второй день, more at 11

**Comment by Ambassadoing** [comment]
>Ты понимаешь, что каждый раз, когда ты задаешь этот вопрос.

Я не задавал вопросов. 

>Попробуй адекватно расписать то для чего это нужно и почему все остальные должны с этим мириться, когда им попросту не нужна эта скорость.

Укажи мне пальцем на этих всех, которых *угнетают* быстрые конвейеры. Я пока вижу только тебя одного.
