### ISSUE TITLE
В РНД возможен бесконечный фарм очков

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4335]
#### Подробное описание проблемы
Этот баг существует с самого появления этой системы исследований, его суть заключается в том, что люди дробят крутые платы, изучают ветки, обновляют базу, печатают те платы, ПОСЛЕ ЧЕГО ОБНУЛЯЮТ КОНСОЛЬ, снова дробят эти платы, обновляются с базой и изучают ветки еще дальше, и так по кругу, это бесконечный фарм очков
#### Что должно было произойти
РНД не должно фармить очки на однихи тех же платах, должно быть взаимодействие форонщиков, биологов, археологов
#### Что произошло на самом деле
Какой то самый умный ученый заабузил очки с помощью плат телепортера и гиротрона
#### Как повторить
Выше сообщено
#### Дополнительная информация:
Я не смог придумать адекватного способа фикса без костылей

**Comment by Kortez90** [comment]
Разве при обнулении базы очки не сбрасываются?

**Comment by Dominig12** [comment]
> Разве при обнулении базы очки не сбрасываются?
> Можно привязать обнуление базы через консоль к обнулению сервера в целом, тогда такого не будет.
> 
> Или можно отменить обнуление очков при обнулении базы.

при обнулении базы сбрасываются НО, ПЕРЕД ОБНУЛЕНИЕМ ДЕЛАЮТ КРУТЫЕ ПЛАТЫ ПРИМЕРНО НА 19к ОЧКОВ В СУММЕ, а потом обновляют базу и на эти очки исследуют дальше, потом снова печатают крутые платы, потом снова обнуляют потом снова получают 19к очков, снова обнволяют и так далее

**Comment by Dominig12** [comment]
> > Разве при обнулении базы очки не сбрасываются?
> > Можно привязать обнуление базы через консоль к обнулению сервера в целом, тогда такого не будет.
> > Или можно отменить обнуление очков при обнулении базы.
> 
> при обнулении базы сбрасываются НО, ПЕРЕД ОБНУЛЕНИЕМ ДЕЛАЮТ КРУТЫЕ ПЛАТЫ ПРИМЕРНО НА 19к ОЧКОВ В СУММЕ, а потом обновляют базу и на эти очки исследуют дальше, потом снова печатают крутые платы, потом снова обнуляют потом снова получают 19к очков, снова обнволяют и так далее

**Comment by Dominig12** [comment]
> Разве при обнулении базы очки не сбрасываются?
> Можно привязать обнуление базы через консоль к обнулению сервера в целом, тогда такого не будет.
> 
> Или можно отменить обнуление очков при обнулении базы.

привязка обнуления сервера в целом, это хуевая идея так как каждый грифер может прийти и обнулить сервер, так же не стоит забывать про абуз с двумя консолями, одна из которых будет хранить в себе исследования, а вторая будет использоваться для фарма очков

**Comment by Kortez90** [comment]
Так... Человек изучил и сделал платы на ~19k очков. Затем сбросил базу, разобрал платы и получил это число очков, после чего просто обновил и вернул уровни? Может ввести переменную повторного изучения независимо от базы?

Все же, план с обнулением базы на сервере лучше. В консоли есть блокировка, в рнд есть диски для сохранения уровней, но этим не пользуются.

**Comment by Dominig12** [comment]
> Так... Человек изучил и сделал платы на ~19k очков. Затем сбросил базу, разобрал платы и получил это число очков, после чего просто обновил и вернул уровни? Может ввести переменную повторного изучения независимо от базы?
> 
> Все же, план с обнулением базы на сервере лучше. В консоли есть блокировка, в рнд есть диски для сохранения уровней, но этим не пользуются.

но это не решает проблему абуза с двумя консолями

**Comment by Kortez90** [comment]
Не решает. И не решает такой же абуз с дисками.
Но в случае со второй консолью будет несколько больше проблем. Можно просто запретить пользоваться консолью, если та не привязана к серверу, как в случае с телепадом, например. А привязывать консоли может только человек с доступом РД и мультитулом. К тому же, можно перенести начисление очков из консоли в сервер. Или можно сделать более радикально и просто запретить привязывать две консоли одновременно к одному серверу.

**Comment by Dominig12** [comment]
> Не решает. И не решает такой же абуз с дисками.
> Но в случае со второй консолью будет несколько больше проблем. Можно просто запретить пользоваться консолью, если та не привязана к серверу, как в случае с телепадом, например. А привязывать консоли может только человек с доступом РД и мультитулом. К тому же, можно перенести начисление очков из консоли в сервер. Или можно сделать более радикально и просто запретить привязывать две консоли одновременно к одному серверу.

радикальный вариант такой себе, а начисление и проверку можно пихнуть на сам сервер, чтобы раздробленные предметы хранились на сервере

**Comment by Zmey25** [comment]
Если делать привязку очков к вещи, то можно будет грифонить рнд, изучая крутые вещи в подпольном рнд в техах и сбрасывать очки вникуда.

**Comment by Kortez90** [comment]
Нельзя, если реализовать привязку консоли к серверу.

**Comment by Kortez90** [comment]
Я тут прикинул... В целом, решение довольно простое. Переносим хранение очков на сервер рнд ото всюду. Ксенобиология, форон и так далее. И храним их там. Так что никакой сброс базы данных не страшен, а вайп уровней в самом сервере значения не имеет и отпадает необходимость осуществлять связь консоли с сервером. К тому же, это поможет в борьбе против всяких вась, которые решат вайпнуть базу через другую консоль или "слить очки в никуда". При вайпе БД через консоль очки не стираются и остаются в том кол-ве, в каком были на сервере. Также нужно добавить `var/list` для исследованных вещей и уже разобранные вещи добавлять туда. Если вещь в списке, то не давать за нее никаких очков.
Реализовать это довольно просто, но лично мне лень этим заниматься и нет никакого настроения работать с DM после танцев с худом и ошибками компиляции карты.

**Comment by Kortez90** [comment]
Почти вся проблема из-за кнопки `reset`, которая удаляет `datum/research` и создает заново. Может просто ее убрать? Какой смысл вообще ресетить БД? К тому же, это можно сделать через сервер.

**Comment by atik1n** [comment]
@Kortez90 у меня появилась идея еще веселее
Разбить `sync_tech` на две части. `download` и `upload`, а не делать и то и то сразу.
При аплоаде у нас все мерджится, а при даулоаде просто все перезаписывается. Или криво?

**Comment by Kortez90** [comment]
От ресета базы это не спасает и никак не решает проблему.
