### ISSUE TITLE
Неболтирующиеся шлюзы у доков шахтерского шаттла.

### ISSUE THREAD

**Issue by Permyack** [TauCetiStation/TauCetiClassic#4336]
#### Подробное описание проблемы
Шлюзовые двери в доке шахтерского шаттла не болтируются, когда шаттл отлетает.
#### Что должно было произойти
Шлюзовые двери должны были болтироваться на тот момент, когда шахтерского шаттла нет. Всё должно быть точно так-же, как с шаттлом в отбытии или с иными шаттлами.
#### Что произошло на самом деле
Шлюзовые двери не болтируются, когда шаттл отлетает. Их может случайно открыть любой игрок вызвав тем самым разгерметизацию и возможно иные проблемы, связанные с чьей-либо жизнью.
#### Как повторить
Взаимодействовать с любым из шлюзов в момент, когда шахтерский шаттл отсутствует.
#### Дополнительная информация:
Ранее уже фиксировалась подобная проблема с шаттлом в отбытии. Спустя время проблема была устранена. Может быть здесь несколько меньший масштаб проблемы, но проблема всё-равно существует.

**Comment by Permyack** [comment]
Похоже подобная проблема есть с шлюзами в Карго. Но здесь я не уверен, сам не проверял.
Некоторые пишут, что шлюзы в Карго не закрываются или не болтируются, когда шаттл отлетает.

**Comment by Zmey25** [comment]
Это хитрая система обучения персонала. Кто не смог понять, что такое дверь - больше не играет в раунде.

**Comment by Permyack** [comment]
> 
> 
> Это хитрая система обучения персонала. Кто не смог понять, что такое дверь - больше не играет в раунде.
> 
> Вообще, шлюзы не обязаны болтироватся. Общий шаттл эвакуации блокируется чтобы избежать множества трупов. Шаттл велосити - чтобы дети, которые только зашли в игру не умирали. С остальными взаимодействуют якобы адекватные люди, опытные, поэтому нет смысла туда болты ставить.

Будь серьезнее. На реальной станции подобные двери бы закрывались исключая возможность случайно уйти в космос. Да и шаттлы могли бы не отлетать, когда в шлюзе что-то есть.

**Comment by Zmey25** [comment]
Как хорошо, что мы не на реальной станции. В том случае, кстати, можно дать доступ к шлюзами только для ИИ. Ему виднее ведь, когда тебе можно покинуть станцию, а когда нет.

**Comment by Permyack** [comment]
> 
> 
> Как хорошо, что мы не на реальной станции. В том случае, кстати, можно дать доступ к шлюзами только для ИИ. Ему виднее ведь, когда тебе можно покинуть станцию, а когда нет.

Смешно-смешно (нет, не смешно).
Давай поразмыслим немного. Ты на космической станции в каком-то там вымышленном будущем. Даже сейчас люди пытаются подходить к вопросу безопасности наших космонавтиков.
Неужели в вымышленном будущем люди так существенно отупели, что совсем забыли о безопасности и о том, что можно было бы болтировать двери?

**Comment by Motzord** [comment]
ПР смержен, ишью не закрыто
