### ISSUE TITLE
Отдельный ползунок громкости для писка дельты.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#4339]
#### Подробное описание проблемы
Пииииип. Пииииип. Раздражает.
Нужна отдельная настройка громкости или верб для выключения этой пиликающей херни во время дельты.
#### Дополнительная информация:
#4181.
Должен был быть [Proposal].

**Comment by SpaiR** [comment]
Не нужно, в ПРе описано почему.
