### ISSUE TITLE
Нюка перехватывает частоту обр.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#4341]
#### Подробное описание проблемы
Перехват нюки цепляет частоту обр.
#### Что должно было произойти
Такого быть не должно.
#### Что произошло на самом деле
Но оно есть.
#### Как повторить
- Быть нюкером.
- Вызвать ЕРТ.
- Сказать что-то в канал ЕРТ.

**Comment by aIweiss** [comment]
> Такого быть не должно.

учитывая, что обратное не работает, возможно, так и задумывалось.

**Comment by Kortez90** [comment]
Учитывая, что частота ОБР на станции **не работает**, так точно быть не должно.
Особенно когда ОБР говорит в свой канал на ЦК, а на станции его слышат нюкеры. Но когда ОБР прилетает, говорить в этот канал они уже не могут, потому что он не работает.
