### ISSUE TITLE
Повязки принадлежности к другим отделам есть лишь у СБшников.

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#4342]
#### Подробное описание проблемы
Возьми повязку в лодауте. Выбери цвет cargo. Там пишет, Restricted - Security Officer и другие охранные профессии. Но цвет cargo!
#### Что должно было произойти
Грузчик с повязкой карго
#### Что произошло на самом деле
Грузчик без повязки своего любимого отдела
#### Как повторить
Взять в лодауте повязку, сменить её цвет (соотвественно должны были смениться и требования к профессии, но...)

**Comment by Ambassadoing** [comment]
Повязки предназначены для назначения офицеров по отделам. На /tg/, например, считай во всех отделах есть по охранному посту.

**Comment by Kortez90** [comment]
Но здесь не тг и кпп есть только в медицинском отсеке и прибытии.

**Comment by Zmey25** [comment]
Что не мешает офицерам тусить в назначенном отделе, например в карго с повязкой своего любимого отдела.

**Comment by TechCatOther** [comment]
Это скорее новая фича

**Comment by TungstenOctopus** [comment]
Идея и правда неплохая как отдельная фича: учитывая, что многие любят юзать кастомные одежки, повязка будет являться индикатором твоего отдела.
