### ISSUE TITLE
Два одинаковых персонажа ломают крю манифест

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4344]
#### Подробное описание проблемы
Если два персонажа с одинаковыми именами но на разных профах задеклерятся, то в крю манифесте отобразится только один из них
#### Что должно было произойти
Два имени на разных профах
#### Что произошло на самом деле
Одно имя на одной профе, а второй фантомный и его нет
#### Как повторить
На дух сикеях создать одинаковых персов и задеклерится

**Comment by FelixRuin** [comment]
ам... А ЗАЧЕМ ТАКОЕ ВООБЩЕ НАДО?!

**Comment by Dominig12** [comment]
> ам... А ЗАЧЕМ ТАКОЕ ВООБЩЕ НАДО?!

я бы не написал если бы такого не произошло
