### ISSUE TITLE
[proposal] Порт системы учета "веса" голосов голосующих за крю стансфер. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#4346]
#### Подробное описание проблемы
Пока эта идея не утонула в форумном нытье. Возможно, кто-нибудь из кодеров решиться портировать эту прогрессивную идею. Фишка заключается в том, что каждый из участников имеет свой "удельный вес" голоса. Где госты, и люди наигравшие небольшое количество времени в раунде имеют наименьшее влияние на итоги голосования, по сравнению с игроками прошедшие временной порог. А так же главами и антагонистами, которые имеют наивысший удельный вес в принимаемом голосование. 

Таким образом система позволяет людям принимающим активное участие в развитие событий в раунде, иметь преимущественный вес в голосование за продолжение или окончание раунда, не лишая при этом и всех остальных права принимать участие в голосование. 

https://github.com/discordia-space/CEV-Eris/pull/2799

**Comment by Kortez90** [comment]
> свой "удельный вес" голоса

Прощай, демократия и легитимность голосования.

Нужна хотя бы ссылка, откуда портировать. Но легче накидать с нуля и в целом, не очень проблематично. Хотя будут проблемы с релогерами, мультиакками... А потом еще приедет маленький вагончик багов. И конечно же, экста на 10 часов, потому что вася не выключал клиент и сидел всю ночь в шкафу.

**Comment by Belfogor** [comment]
@Kortez90 
![image](https://user-images.githubusercontent.com/12851693/70454148-9f757f80-1ab2-11ea-9595-7ad16d28be94.png)

**Comment by Kortez90** [comment]
При беглом осмотре принял ее за линк в дискорд-конференцию. D:

**Comment by Zmey25** [comment]
Добавить еще если персонаж мертв спустя менее 15 минут после старта раунда (аля крио без рольки) - 0.1 сила голоса.
