### ISSUE TITLE
Шапка Хоса осталась без защиты

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#4349]
#### Подробное описание проблемы
Шапка хоса у которой должна быть защита, почему то ее не имеет
#### Что должно было произойти
Она должна давать защиту от урона по голове как в дермал патче
#### Что произошло на самом деле
Ее нет
#### Как повторить
Пострелять в голову кукле с данной шляпой из лазера и других пушек
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/19417166/70472914-a911de00-1ad8-11ea-99e7-fd2ea54404ce.png)

**Comment by Kortez90** [comment]
Потому что есть две шляпы - коллекционная и обычная, с защитой.

**Comment by Deahaka** [comment]
Полагаю не баг

**Comment by Deahaka** [comment]
думаю это легаси, как кепка капитана, которая имеет 50 брони, но токо потому что она helmet.
