### ISSUE TITLE
[Proposal] Привязать клавишу к действию, закрывающему все окна в игре.

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#4350]
Окей, у некоторых людей (я например) возникает проблема с тем, что при открытии охранной консоли видеонаблюдения они ловят невероятные лаги и фризы игры из-за количества нажимаемых кнопок в окне (проверял на других консолях видеонаблюдения, с другими network'ами (проще говоря, с меньшим количеством нажимаемых КнОпОчЕк), лагов не было).
Описываю состояние фриза - тупо ни на что не нажать. Или нажать на тот же крестик спустя очень долгое время. Очень неприятно и, согласитесь, неудобно при игре за того же смотрителя или офицера СБ.
Что предлагаю - привязать к свободной клавише не просто прок Cancel Camera View, но прок, закрывающий все открытые окошки, в качестве "аварийного метода" борьбы с лагами.

Что это может улучшить - игрокам, у которых каким-то образом геймплей связан с кучей открытых окошек (например парамедикам, использующим монитор датчиков внутри Одиссея или ИИ, который хочет знать всё и сразу со всех консолей), значительно облегчит жизнь и ускорит игровой процесс кнопочка сброса всех окон, позволяющая сразу, без лишнего отвлечения на нажатие всех-всех крестиков, окунуться в игру и посмотреть как там поживает его кукла.

Как вам идея?
P.S.: Наверное это также и скрытый крик о помощи, так как процесс наблюдения именно через охранную консоль камер - та ещё боль.
P.S.S.: Если такая клавиша существует, пожалуйста напишите, чтобы я с позором прикрыл эту тему.

**Comment by Kortez90** [comment]
Называется `Fix NanoUi (Close All)`.
При использовании камер у меня тоже бывали лаги, но негативных эффектов не вызывали. Разве что пинг временами скакал, если часто и быстро прыгать по камерам.
На датчики внутри меха это не влияет, а ИИ не может использовать консоли, если те не в поле его зрения.
Еще один костыль не нужен.
И что такое "P.P.S"? ППС? Полицейская патрульная служба? Парадигма Петрова-Сахарова?

**Comment by Pivo24** [comment]
Пост социалистический строй.

Просто привязать Fix NanoUI (Close All) к клавише тогда. Когда я не могу закрыть окно с камерами, я не могу даже Say нажать, даже Cancel camera view иногда не выходит прожать. Настолько всё плохо.

**Comment by Sakuya-Izayoi** [comment]
Нажми таб, смени раскладку на английскую, напиши `Fix N`, нажми пробел и энтер. Вот и всё.
