### ISSUE TITLE
Несмываемая кровь

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4358]
#### Подробное описание проблемы
Оверлей крови не пропадает ни с одного предмета при попытке его смыть

 Итем Стейт предмета меняется корректно, иконка же остается пермаментно заляпанной в кровищи
#### Что должно было произойти
Все корректно смывается
#### Что произошло на самом деле
Все инструменты в меде по механу чистые а по спрайтам кровавые, Наслаждаешься кровавыми шмотками в инвентаре и вообще недоволен
#### Как повторить
Запачкайтесь кровь, попробуйте отмыть кровь
#### Дополнительная информация:
Это уже начинает реально бесить....

**Comment by Kortez90** [comment]
#4325.

**Comment by Soldart-Krit** [comment]
Такая же фигня. Уже на форум писал в обсуждениях.
