### ISSUE TITLE
[Proposal] Добавить возможность использовать скафандры без кислородных масок

### ISSUE THREAD

**Issue by Maggot4th** [TauCetiStation/TauCetiClassic#4362]
Зачем одевать под герметичный шлем скафандра кислородную маску, когда даже в современных скафандрах в этом нет необходимости. Предлагаю добавить подключение шлемов к баллонам, что бы не было необходимости одевать маску или противогаз под и так герметичный шлем скафандра или РИГа.

**Comment by Kortez90** [comment]
Тогда нужно вводить весь функционал костюмов и отрезать ригам и скафандрам слот рюкзака, потому что его будет занимать система ЖО и поддержания давления.

![images_skafandr 1](https://user-images.githubusercontent.com/36198983/70818509-f4800100-1de4-11ea-9443-853fa9724849.jpg)

**Comment by Maggot4th** [comment]
У ригов есть хранилище рига, в который обычно и влезает баллон с кислородом, плюс судя по иллюстрации можно сказать что базовая система терморегуляции встроена в сам риг. А связь осуществляется через наушник. Я думаю, что почти весь этот рюкзак уже встроен в качестве модулей рига в самом риге благодаря миниатюризации(все таки как никак будущее).

**Comment by Maggot4th** [comment]
А скафандрам да, можно слот рюкзака убрать.

**Comment by Kortez90** [comment]
> рюкзак уже встроен в качестве модулей рига в самом риге благодаря миниатюризации(все таки как никак будущее)

Если он встроен, то нужен отдельный рюкзак рига, а не любой другой, который можно взять в руки. Раньше были риги, которые надевались на спину в слот рюкзака и раскладывались на тело, голову, ноги и так далее.

**Comment by Bullethole** [comment]
Вы сейчас обсуждаете 2 разных вещи, РИГ, и скафандр, риг- это не скафандр, скорее экзоскелет напичканный модулями (встроенными и непосредственно добавленными) 
Риг сделан не из  ткани, а метала, почитайте вики по поводу Рига (или поиграйте в мертвый космос )

**Comment by Kortez90** [comment]
Это неважно, ведь сейчас все костюмы для космоса надеваются десять тысяч лет, словно персонаж лезет в него через верх целиком. Даже если это складной риг, который вообще должен на спине находиться и раскладываться. К тому же, они **магическим** образом создают внутри себя давление, подходящее для любой среды и поддерживают его бесконечно, даже без источника.

**Comment by aIweiss** [comment]
складных ригов на таукети нет. и они кстати надеваются не быстрее, если что. 

а так - это хороший ишшуе.
