### ISSUE TITLE
[Proposal] Увеличение скорости передвижения в режиме ходьбы

### ISSUE THREAD

**Issue by Loratron** [TauCetiStation/TauCetiClassic#4367]
На данный момент у ходьбы есть только одно (не считая заглушения шагов) предназначение - спокойное прохождение участков мокрого пола. В остальном ходьба НИГДЕ не применима в силу своего сильнейшего замедления куклы. Фактически, ради одного только механа разлитой воды, на интерфейс была добавлена отдельная кнопка.
Ходьба могла бы спокойно использоваться любителями чаёвничества ради спокойных прогулок к торговым автоматам на 5 тайлов правее них, но на деле даже это будет выглядеть крайне неловко и медлительно. 
К примеру, чтобы из ресепшена медбея попасть к окошку в РНД, хуману потребуется какие-то 5 секунд. В то же время, при ходьбе эта же прогулка в среднем займёт **абсурдные** 22 секунды.
Я очень сомневаюсь, что ускорение ходьбы полностью сломает баланс на станции, а играть в любом случае станет приятнее. К тому же, уменьшение разброса между скоростью бега и шага позволит не задумываться о том, почему весь экипаж бегает по станции как Усейн Болт 24/7, а при виде, о ужас, ***МОКРОГО ПОЛА*** резко решает сделать передышку в 10 секунд и пройтись лёгким прогулочным шагом.

**Comment by Kortez90** [comment]
#4307.
