### ISSUE TITLE
DNA у IPC в медицинских записях.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#4372]
#### Подробное описание проблемы
У IPC в медицинских записях, которых и быть-то не должно, есть DNA и тип крови.
#### Что должно было произойти
Их быть не должно, как и самих записей в принципе.
#### Что произошло на самом деле
Но они есть.
#### Как повторить
- Зайти СПУ.
- Открыть медицинские записи своего персонажа.

**Comment by LudwigVonChesterfield** [comment]
Насчёт крови - надо проверять species.flags[NO_BLOOD], а для ДНК - species.flags[IS_SYNTHETHIC]

(тем кто может за это возьмётся)
