### ISSUE TITLE
Farmbot-ы начинают убивать после 2-10 минут, после изготовления

### ISSUE THREAD

**Issue by MichaelMaxPower** [TauCetiStation/TauCetiClassic#4374]
#### Подробное описание проблемы
FarmBot-ы (в дальнейшем именуемые фармботами), при прошествии 2-10 минут они начинали убивать и всячески вредить тем кого увидят (кидают бутылки с удобрением, царапают граблями и т.д.).
#### Что должно было произойти
Фармбот не должен вести себя таким образом при отсутствии взлома.
#### Что произошло на самом деле
Фармботы продолжают восставать после 2-10 минут как их изготовили (проверено несколько раз).
#### Как повторить
Построить Фармбота и подождать 2-10 минут.
#### Дополнительная информация:

**Comment by TechCatOther** [comment]
Больше похоже не событие "Ионный шторм". Есть шанс, что сломает бота. 
Бота успешно построил и все с ним было хорошо на протяжении часа.

**Comment by TechCatOther** [comment]
Воспроизвести не удалось
