### ISSUE TITLE
Сломанный шлюз на заброшенной станции Дварфов на астероиде

### ISSUE THREAD

**Issue by MichaelMaxPower** [TauCetiStation/TauCetiClassic#4375]
#### Подробное описание проблемы
На астероиде есть помещение с название Dwarf Station, в котором шлюз не работает. Без вскрытия дверей/окон/стен зайти туда невозможно.
#### Что должно было произойти
Шлюз на входе должен был нормально открыться, внутренняя дверь должна называться и/или иметь значение Internal.
#### Что произошло на самом деле
Внутренняя дверь во шлюзе не открывается из-за того что значение внутренней двери External (в итоге 2 двери там с названием/значением External).
#### Как повторить
Найти на астероиде данную станцию, попробовать войти стандартным методом, которым входят во все шлюзы (через кнопку).

**Comment by Ambassadoing** [comment]
Это фича. А ты хотел, чтобы заброшенная станция была на 100% рабочей?
