### ISSUE TITLE
Бесконечная дельта

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4376]
#### Подробное описание проблемы
При смерти малфа дельта не отключается
#### Что должно было произойти
Security code has been elevated to RED
#### Что произошло на самом деле
Вечный дельтакод, вечная сирена
#### Как повторить
Дайте малфу врубить дельту, а потом загрифоньте его

**Comment by atik1n** [comment]
> Security code has been elevated to RED
Security code has been lowered to RED

**Comment by Kortez90** [comment]
А я предупреждал.

**Comment by Motzord** [comment]
Дельтапроблема больше не обнаруживается
