### ISSUE TITLE
Шахтерский конвейер нельзя улучшить

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4378]
#### Подробное описание проблемы
Собственно шахтерская плавильня по сути машинерия, вроде печи и сжимателя, собираемые как и вся нормальная машинерия из рамы, платы и деталек. Следовательно машинерию можно улучшать путем замены деталек, что указано на вики.
#### Что должно было произойти
Прокачал печку заменив лазеры на ультрананоблюспейс, получаешь тонны очков и доволен приобретением
#### Что произошло на самом деле
Блюспейс РПИД отказывается стрелять детальками по машинерии
#### Как повторить
Попробуйте улучшить шахтерскую печь как указано на вики

**Comment by Dominig12** [comment]
Шахтерская печь из той машинерии которую нельзя собрать/разобрать и она не имеет деталей, что ты собрался улучшать

**Comment by Permyack** [comment]
Шахтеры и так сейчас шикуют из-за чрезмерно ускоренных конвейеров. Ты предлагаешь им и машинерию улучшить.
Давай еще Кинераторы с других билдов скопируем, чтоб их модифицировать можно было и перезаряжались они сами по себе. Вариант с Лаваленда помнится был самым жестким в этом плане. Но там это несколько резонно из-за агрессивной фауны и всяких злых боссов.
Еще и резаку стрельбу добавить...Весело конечно, но будет слишком жирно.
Думаю с такой фичей шахтеры вообще могут начать с жиру беситься.
Если они не забьют на шахту после первой партии и РНД решится выдать им набор деталей для улучшения, то в последствии шахтеры вполне себе могут играть в расслабленном состоянии.
Если еще и требования к руде будут понижаться...
Если не ошибаюсь, то сейчас для любого материала нужно более 1 единицы сырья. Представим, что улучшения будут влиять и на это. Нашел всего 1 сырой алмаз - получил 1 нормальный алмаз или даже больше. Из 1 получить 2 или 3, или может даже 4, или уж совсем 10.
Довольно сильно, не так-ли? И всё это будет происходить еще быстрее и с большим количеством очков.
При таком раскладе для балансировки придется либо делать что-то с мобами, чтобы они представляли большую угрозу. М.б. просто больше их сделать. Либо делать ценную руду более редкой, чтобы шахтеры были вынуждены серьезно рисковать ради её добычи.
