### ISSUE TITLE
Невозможный абуз голдграба

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4380]
#### Подробное описание проблемы
Как мы знаем, голдграб кушоет руду и приумножает ее в два раза после смерти
#### Что должно было произойти
Держим червяка в третьем грабе, высыпаем руду на один турф и тащим его туда, голдграаб кушает, мы его лутаем и получаем еще больше руды
#### Что произошло на самом деле
Голдграб все сожрал и выдал лишь по 5 едениц всего
#### Как повторить
Попробуйте заабузить червяка

**Comment by EdlerN** [comment]
Он работает как и задумано. Только немного иначе, чем ты думаешь. Иди, изучай.
