### ISSUE TITLE
[Proposal] Чтобы госты видели прей.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#4381]
#### Подробное описание проблемы

Это не проблема. Но было бы круто если бы госты видели прей.

**Comment by FelixRuin** [comment]
можно, но зачем?

**Comment by Kortez90** [comment]
А смысл?

**Comment by Pivo24** [comment]
Я вижу смысл для ксенобиологов, робототехников-поклонников Омниссии и паранормалистов конечно же.

Неплохо.
