### ISSUE TITLE
[Proposal] Дать парамедикам доступ к аварийным створкам

### ISSUE THREAD

**Issue by Loratron** [TauCetiStation/TauCetiClassic#4385]
Сейчас открывать мигающие опущенные створки без монтировки могут (ВРОДЕ БЫ) только инженеры, хотя парамедикам доступ к ним нужен ни чуть не меньше.
По-моему, когда-то у парамедиков был доступ к створкам, но его порезали вместе с каким-то фиксом доступа к инженерке. 
Не думаю, что нужно особо разъяснять причины для возврата этого доступа обратно в лапки парамедиков

**Comment by seekin4u** [comment]
Мы имеем инженеров, которые обычно не оставляют за собой разгерм, которые идут за желтенькие мигающие створочки что бы починить что-то, и имеем парамедиков которые за желтые створочки идут обычно что бы кого-то спасти, но лично мне кажется что на парамедиках далеко не всегда играет ответственный человек, я думаю очень часто ему будет глубоко насрать на то что створочка мигает а в отсеке он может быть не один НО ТАМ ЖЫ КТОТА УМИРАЕТ...
Собственно вот - это причина по которой у парамедиков нет легального доступа к створочкам, ведь они мотивированы всегда тем что бы спасти того самого единственного бедненького ассистента за створками, и далеко не всегда озадачены тем что в створки потом сдувает еще три человека.

А если выбирать между невозможностью причинить вред трем человекам за спиной, но пожертвовать одним в разгерме, чем что бы все четыре оказались в разгерме - статистически логично, что доступ им не нужен.

Гав-гав-гав-гавно твоя идея короче, учитывая какие игроки играют и как они думают об окружении, это только приведет к участившимся смертям.

**Comment by Kortez90** [comment]
У парамедиков есть доступ к этим створкам, как и у почти любого члена экипажа. Что мешает тебе носить с собой лом?

**Comment by ViDLiathan** [comment]
Отсутствие доступа у парамедика я считаю багом.
И нужно быть совскм гав-гав-гав глупым, чтоб думать будто без доступа парамедикам будет работаться лучше.

Во-первых, идиотов инженеров без рига преспокойненько всасывает в разгермы.
Во-вторых, почти все парамедики что не падают в апатию после десяти минут тихого раунда и/или ходят на вызовы довольно ответственны.
Ну и в-третьих, с доступом или с ломом, парамед все равно должен войти внутрь.
Но вот открытая ломом створка не закрывается сама, что то я не припоминаю чтоб большинство космонавтов с ломиком закрывали бы за собой створки. А ведь в этом 95% причин разгерм или пожаров по всей станции.

Так что для упрощения работы инженерам и парамедмкам все таки нужен доступ к створкам.

**Comment by Loratron** [comment]
> У парамедиков есть доступ к этим створкам, как и у почти любого члена экипажа. 

Доступ к обычным створкам есть, а доступа к мигающим очень сильно не хватает.

> Что мешает тебе носить с собой лом?

Почему-то инженеры обходятся без лома (хотя он у них всегда есть с собой), не смотря на то, что их работа не требует такой быстроты реакции, как у парамедиков. Придти в РИГе к месту разгермы, вспомнить что у тебя нет ломика, побежать искать его по всей станции, придти снова к разгерме, пол часа вручную вскрывать каждый шлюз, а после его закрывать.

К вопросу об ещё большем распространении разгермы: по моим наблюдениям, парамедики ГОРАЗДО реже распространяют их, чем те же инженеры. Никакой даже чуточку нормальный парамедик не допустит нескольким людям пострадать от открытия створки, ведь ему придётся их же и спасать. К тому же, когда доступ к створкам у парамедиков всё же и был, на это вообще никто не жаловался

**Comment by Kortez90** [comment]
Так. Здравствуйте. В заголовке пропозала написано "Дать парамедикам доступ к аварийным створкам". Доступ и парамедиков уже есть, называется лом. То, что использовать его долго и неудобно - к пропозалу не относится.

**Comment by Loratron** [comment]
> Так. Здравствуйте. В заголовке пропозала написано "Дать парамедикам доступ к аварийным створкам". Доступ и парамедиков уже есть, называется лом. То, что использовать его долго и неудобно - к пропозалу не относится.

"Так. Здравствуйте. В заголовке пропозала написано "Дать инженерам полный доступ". Доступ у инженеров уже есть, называется инструменты. То, что использовать их долго и неудобно - к пропозалу не относится."

**Comment by TechCatOther** [comment]
Ни разу не видел, что бы при пожаре в РЛ медики бежали внутрь горящего здания не дождавшись самых пожарных/спасателей. 

Спасение жизни кого конечно хорошо, но появление форона перед лицом медика, открывшего створку - достойна фотографии.

**Comment by Loratron** [comment]
> Это потому что им лом нужен, а доступа у них нету.

Я говорю и про времена, когда у парамедиков доступ был
