### ISSUE TITLE
Сломанный гринтекст

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4390]
#### Подробное описание проблемы
Триторам и генкам не обязательно выполнять задание "Stay alive and until end" им всегда засчитывают это
#### Что должно было произойти
Тритор сдох, тритор хас файлед
#### Что произошло на самом деле
Тритор сдох, тритор хас суцефул
#### Как повторить
Сдохните за тритора и осознайте, что вам засчитало задание "выжить"

**Comment by Motzord** [comment]
![image](https://user-images.githubusercontent.com/45365635/71446923-75b68c80-2731-11ea-89da-28a20e459c61.png)
Не ну вот че это такое

**Comment by Konradiuss** [comment]
Душа человека живет всегда, аминь.

**Comment by TechCatOther** [comment]
Так же видел баг в одном из раундов о засчитанной цели о краже предмета без её фактического выполнения

**Comment by ViDLiathan** [comment]
Это все просто хитрый план Синдиката по выполнению годового плана на гринтексты.

**Comment by SpaiR** [comment]
Может быть связано с #4359 
@volas ?

**Comment by LudwigVonChesterfield** [comment]
#4398
