### ISSUE TITLE
Тритор может не получить ТК

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#4397]
#### Подробное описание проблемы
Мидраунд тритор может не получить ТК

#### Что должно было произойти
При получении триторки в аплинке должны появится ТК

#### Что произошло на самом деле
В аплинке ТК не появилось

#### Как повторить
Стать мидраунд тритором

#### Дополнительная информация:
аплинк в наушнике был, я был в шлеме

**Comment by Dominig12** [comment]
триторка выпашая постреди раунда не должна всегда давать аплинк или ТК, так что тут никакого бага нет, закрывай

**Comment by Ahion** [comment]
Как так не должна? Что за странная логика: в начале раунда дает, а в середине не дает?

**Comment by KIBORG04** [comment]
дает
