### ISSUE TITLE
При попытке съесть пустой рамен простит его открыть

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#4403]
#### Подробное описание проблемы
Когда Dosi Ramen и Dosi Ramen(Spicy) заканчивается, то при попытке опять его съесть(или же кликнуть в любое место) пишет You need to open Dosi Ramen!

#### Что должно было произойти
Сообщение, что рамен пустой
#### Что произошло на самом деле
Пишет, что нужно открыть рамен
#### Как повторить
Открыть рамен, съесть рамен, опять кликать пустым раменом на себя
#### Дополнительная информация:
Небольшой лог
 ```
You open the Dosi Ramen.
You can taste dry ramen coated with what might just be your tears.
You swallow a gulp of Dosi Ramen.
You swallow a gulp of Dosi Ramen.
You can taste dry ramen coated with what might just be your tears.
You swallow a gulp of Dosi Ramen.
You swallow a gulp of Dosi Ramen.
You can taste dry ramen coated with what might just be your tears.
You swallow a gulp of Dosi Ramen.
You swallow a gulp of Dosi Ramen.
You need to open Dosi Ramen!
None of Dosi Ramen left, oh no!
You need to open Dosi Ramen
```

**Comment by Kortez90** [comment]
Это не единственная проблема "открывания" лапши, бутылок, банок с газировкой. Механика бесполезная почти полностью. А бутылку можно вообще открывать почти бесконечно.
