### ISSUE TITLE
Взломаный апц(синий экран) нельзя разобрать.

### ISSUE THREAD

**Issue by DjunDjun** [TauCetiStation/TauCetiClassic#4404]
#### Подробное описание проблемы
Взломанный апц, который горит синим нельзя разобрать. На вики написано, что его можно разбить баллоном или чем-то тяжелым.
#### Что должно было произойти
Должна была сломаться крышка апц
#### Что произошло на самом деле
Произошло ничего. Апц не прокликивается
#### Как повторить
Синий взломаный апц попробовать сломать

**Comment by Kortez90** [comment]
На вики некоторые статьи очень сильно устарели.
Взломанные APC вскрываются. У **сломанных** APC можно снять крышку огнетушителем.

**Comment by DjunDjun** [comment]
> Взломанные APC вскрываются. У **сломанных** APC можно снять крышку огнетушителем.

Не работает это. Огнетушитель не работает так же. И топор, и баллон с воздухом и т.п

**Comment by Zmey25** [comment]
Синий апц просто разбирается как обычный, летом можно было разобрать, но это бессмысленно, так как синий апц ничем не отличается от обычного. Если только не малф.

**Comment by DjunDjun** [comment]
> Синий апц просто разбирается как обычный, летом можно было разобрать, но это бессмысленно, так как синий апц ничем не отличается от обычного. Если только не малф.

Его нельзя разобрать, если не разбить крышку. А крышку нельзя разбить так как она не прокликивается. Мы полотора часа сидели ночью. Человек 7 приходило пытаться разобрать его. В итоге сачелей его взорвали.

**Comment by Motzord** [comment]
Не воспроизводится, лично при мне СЕ при малфе спидранил и разбирал синие АПЦ
