### ISSUE TITLE
[Map Issue] Звоночек у повара

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#4405]
#### Подробное описание проблемы
В звоночек у повара нельзя позвонить потому что он находится за стеклом к которому ни у кого нет доступа кроме самого повара.

#### Дополнительная информация:
Уберите эти окна оттуда вообще. Они там не нужны.

**Comment by TechCatOther** [comment]
Кухня по умолчанию закрытая, если повар будет готов открыть ее он просто может кликнуть на створки и они открываются. Тогда звонок будет доступен для всех. Думаю лучше будет если сделать по умолчанию опущеные ставни на кухни во время старта раунда, при появлнии повара он их откроет.

**Comment by Motzord** [comment]
Не актуально

**Comment by Motzord** [comment]
Можно закрывать у повара есть звоночек
