### ISSUE TITLE
Удаление записей в копьютере сотрудника удаляет охранные

### ISSUE THREAD

**Issue by TechCatOther** [TauCetiStation/TauCetiClassic#4406]
#### Подробное описание проблемы
В компьютере Employment Records  есть режим обслуживания, доставшегося ему от копьютера базы охраны. Присутвует меню "Record Maintenance", где можно удалить все записи (Этим кто-то пользуется?). При удалении всех записей на самом деле происходит удаленией только записей охраны.

#### Что должно было произойти
Тут три варианта:
- Удаление записей о сотрудниках и сломанный манифест на станцци, включая манифест в главном меню.
- Сломаный манифест на станции, но в главном меню он в порядке
- Этого меню вообще не должно быть

#### Что произошло на самом деле
Удалились только записи охраны

#### Как повторить
Зайти за любого главу и нажать Delete All Records в Employment Records, проверить записи охраны
#### Дополнительная информация:
Сам PR уже готов, но мне бы хотелось получить фидбек от компьюните как это должно вообще работать. В текущий момент остановился на варианте вывода ошибки при попытке удаления записей, либо ломается манифест в главном меню.

**Comment by Kortez90** [comment]
У экипажа АТМ аж три страницы в деле - в службе безопасности, в медицинском отсеке и общая. Лаптопы у глав тоже разные и хос может удалить через свой лаптоп только определенные записи, как и смо.

**Comment by TechCatOther** [comment]
Сам компютер доступен любым главам
`req_one_access = list(access_heads)`
Есть особый доступ для смены профессии в базе, что на самом деле не влияет на смену отдела. Он доступен ИИ,Капитану и ХоПу.
```
if("rank")
	var/list/L = list( "Head of Personnel", "Captain", "AI" )
	//This was so silly before the change. Now it actually works without beating your head against the keyboard. /N
	if ((istype(active1, /datum/data/record) && L.Find(rank)))
```
Получает удалять все завиписи может любой из глав и это работает. Вопрос то в том, должны ли только записи охраны удалятся из компьютера сотрудников? Почему не медицинские или общие, а именно охраны удаляются. 
Как еще вариант можно персонализировать эти машины под того, у кого они стоят и сделать их только для одной профессии.

**Comment by Kortez90** [comment]
Если бы в них был смысл...
Сейчас это игрушка для РП и всяких фаш-капитанов и хопов, но даже они используют эту функцию исключительно для переименования своего звания. Личные дела экипажа нужно вообще в корне переделывать и лучше целиком. Сейчас это какая-то каша из шнурков.

**Comment by TechCatOther** [comment]
Я там уже все переписал, поэтому если есть идеи как это должно работать - сделаю в ближайшее время

**Comment by Kortez90** [comment]
Сначала выкати ПР.
