### ISSUE TITLE
[Proposal] Анонс прибытия от ИИ

### ISSUE THREAD

**Issue by TechCatOther** [TauCetiStation/TauCetiClassic#4407]
#### Подробное описание проблемы
При прибытии шатла с велосити и присутвии ИИ на станции вместо ИИ говорит компьютер. Атмосферней будет использование имя ИИ при анонсах прибытия.

#### Что должно было произойти
Анонс прибытия будет от имени активного ИИ
#### Что произошло на самом деле
Анонс прибития происходит от "Arrivals Alert System"
#### Как повторить
Отправить шатл с велосити

**Comment by aIweiss** [comment]
back to the future
