### ISSUE TITLE
Бесконечный спам ЕМП.

### ISSUE THREAD

**Issue by Prusski** [TauCetiStation/TauCetiClassic#4412]
#### Подробное описание проблемы
ЕМП имплант можно спамить бесконечно.
#### Что должно было произойти
ЕМП должен перестать быть работоспособным после нескольких использований
#### Что произошло на самом деле
https://www.youtube.com/watch?v=PyLDQnLCSSQ
#### Как повторить
https://www.youtube.com/watch?v=PyLDQnLCSSQ
#### Дополнительная информация:
Не баг, а фича

**Comment by AndroBetel** [comment]
>в него стреляют из огнестрела
>жмет емпеху

**Comment by Kortez90** [comment]
А лучше после одного.
