### ISSUE TITLE
Контрабандные постеры

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#4413]
#### Подробное описание проблемы
На станции в многих местах включая бар и частный офис нередко можно встретить контрабандные постеры разработанны корпорациями Синдиката для морального и интеллектуального разложения работников НаноТрейзен

#### Что должно было произойти
На станции везде (кроме тех мест где не должны) должны висеть патриотические постеры НаноТрейзен которые прививают работникам любовь к корпорации.

#### Что произошло на самом деле
На станции висят постеры про коноплю, ребелс юнайт и объявления о наборе в армию синдиката.

#### Как повторить
Гулять по станции и смотреть на стены.

#### Дополнительная информация:
Map Issue

**Comment by BesumniiChebureck** [comment]
Не актуально. Может быть контрабанд постеры давно поубирали и повесили нормальные. Единственные места где с начала смены висят нелегальные постеры, это только в старом баре и заброшенной столовой, всё. Просьба закрыть.

**Comment by UsadoSmokk** [comment]
Жаль конечно, что убрали постеры из техов и туалетов, эх.....
