### ISSUE TITLE
[Proposal] Аннулирование доступа при статусе *Arrest*.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#4415]
#### Подробное описание проблемы
Добавить статусу задержания аннулирование доступа к дверям.

**Comment by TechCatOther** [comment]
Требуется доступ глав или вардена для этого или любого из сб?

**Comment by FelixRuin** [comment]
ммм
челикам которые всем ставят аррест такое точно понравится
этож возможность безнаказанно всех запереть по отсекам

**Comment by Kortez90** [comment]
> 
> 
> Требуется доступ глав или вардена для этого или любого из сб? Нужно ввести возможность просмотреть логи действий через консоль? Есть ли ограничение для звания на станции, при котором выключается доступы? Нужно ли их восстанавливать при снятии ареста или потребуется снова поставить через ХоПа?

Немного не в ту сторону. Не у карты убирать доступ, а в дверях заблокировать человека, у которого висит арест. И это должно относиться ко всем.

**Comment by Kortez90** [comment]
> 
> 
> ммм
> челикам которые всем ставят аррест такое точно понравится
> этож возможность безнаказанно всех запереть по отсекам

Это наказывается внутри игры. Особенно стоит палку сунуть в одно место людям из рнд.

**Comment by TechCatOther** [comment]
Тут еще потребуется добавить ИД карты к базе охраны и базе сотрудников. Сейчас ID это просто плашка с именем каким-либо и доступами. Возможно нужен сервер для базы делать, что бы была возможность обойти это.

**Comment by Kortez90** [comment]
Зачем эта наркомания? Двери же проверяют доступ при битье о них головой. Вставь им проверку статуса.

**Comment by TechCatOther** [comment]
Ты имеешь в виду это?
`/obj/machinery/door/airlock/Bumped(atom/AM)`
Так там только брейнлосс для сотрудника, вот для боргов работает

**Comment by Kortez90** [comment]
Это была шутка.

**Comment by ViDLiathan** [comment]
У нас нет необходимости доступа к записям охраны, чтоб менять статус ареста. Так что эта штука слишком грифозная будет.

**Comment by Motzord** [comment]
>Ставим арест на глав через консоль
>Смеемся

**Comment by Kortez90** [comment]
> 
> 
> > Ставим арест на глав через консоль
> > Смеемся

А потом ты получаешь люлей от глав, так как у них есть пульт и смеешь ты уже в камере.

**Comment by TechCatOther** [comment]
Как я писал выше, я не смогу получить статус сотрудника имея всего то его ID. Если уж хочется вам такое захардодить потребуется добавлять в ID статус сотрудника. Это несколько противоречет все системе, либо статус сотрудника это не доступ. А карта ID отвечает за доступ с возможностью скопировать туда данные с базы сотрудников при записи.

Естейственно сейчас настоящих системах пропусков такая тема бы прошла, но там вообще по другому все работает.
 При прикладывание пропуска на пульт СБ отправляется запрос с номером двери  + номером карты. По базе смотитрится какая кто закреплен за ней. В некоторых системах еще проверяется может ли данная карта пройти через эту дверь, тоесть входила ли она в данный закрытый блок, что бы попасть к этой двери. Потом проверяется доступ свзяанного сотрудника и открывается или идет отказ в доступе.

И вот если проверять через базу данных - то возможно управлять через консоли глав или сб доступом динамически. 

По вопросу анулирование через статус ареста. Если у тебя если очки сб ты его можешь выставить и это нигде не отразится. Вот идет погоня и куча СБ ловит одного преступника в техах, если у него поулчилось достать очки с худом охраны - вся охрана лишается доступа к дверям. Дальше вопрос, кто может вернуть его? Если любой СБ, тогда сам преступник моментально вернет себе доступ и снова это будет игра в закликивание, кто быстрее. 

Ну и наконец анулирование доступа через пульт СБ лишит возможности многим отигравать не скрыто-роли. А сейчас игроки и так жалуются, что за всю смену ничего не замечают потому-что все антаги действуют скрытно и режим превращается в эксту. Введения возможности сб закрывать досутп быстро приведет к увеличению скрыто-ролей.

**Comment by ArtBsd1** [comment]
Прикольная задумка, но кто будет такое кодить?
Тогда надо чтобы только варден, хос, хоп, капитан, ИИ выставлял арест, либо будут ассистенты, укравшиеся карту сб, выставлять аресты.

**Comment by WallShrabnic** [comment]
> А потом ты получаешь люлей от глав, так как у них есть пульт и смеешься ты уже в камере.

Главы не носят обычно с собой пульт. Плюс можно подловить их в конференц-зале
