### ISSUE TITLE
[Proposal] Добавить описание к режимам в меню голосования

### ISSUE THREAD

**Issue by TechCatOther** [TauCetiStation/TauCetiClassic#4418]
#### Подробное описание проблемы
Нету описание у разных режимов при голосовании. Новичку точно не  понятна разница между bay12, tau ceti classic и secret.
#### Что должно было произойти
Игрок знает, что выбирает
#### Что произошло на самом деле
Голосуешь за секрет
#### Как повторить
Запустить голосование на режим игры и забыть, что стоит за названиям режимов

**Comment by Ahion** [comment]
Нужно, нужно. Я до сих пор не знаю что такое tau ceti.))

**Comment by Akellazp** [comment]
> Нужно, нужно. Я до сих пор не знаю что такое tau ceti.))

tau ceti это сервер, а tau clаssic это режим

**Comment by Zmey25** [comment]
Описание: сикрет не поломанный и единственный нормальный режим.

**Comment by TechCatOther** [comment]
Разве остальные режимы поломаны? Что мне следует добавить в описание к ним? Почему они включен, если не работают?
