### ISSUE TITLE
[Proposal] Ксеноархеолог не может открыть окошко в рнд

### ISSUE THREAD

**Issue by KiPakr** [TauCetiStation/TauCetiClassic#4421]
#### Подробное описание проблемы
Ксеноархеолог имеет доступ в отсек иследований, но не имеет доступ к стеклянной двери в "приемной" этого же отсека
#### Что должно было произойти
Должен иметь доступ к отсеку в полной мере
#### Что произошло на самом деле
Не имеет доступ к отсеку в полной мере
#### Как повторить
Попытаться открыть стеклянную дверь в приемной отсека исследований

**Comment by Dominig12** [comment]
Он и не должен иметь доступ к окну лаборатории

**Comment by KiPakr** [comment]
К самой лаборатории имеет доступ, а к окну нет. Да?

**Comment by Dominig12** [comment]
> К самой лаборатории имеет доступ, а к окну нет. Да?

Археолог не имеет доступа в лабораторию но в общем в РНД имеет, он может бегать по коридорам но не может зайти в отдел исследований и разработок где прототипы делают, точно так же как и в роботику и остальные отделы

**Comment by KiPakr** [comment]
Он имеет доступ. Зачем говоришь если не знаешь, а? Я бы не писал это если бы это было не так.

**Comment by Dominig12** [comment]
> Он имеет доступ. Зачем говоришь если не знаешь, а? Я бы не писал это если бы это было не так.

Скинь скриншот окна которое ты имеешь в виду и я постараюсь понять, а то я не помню чтобы археолога давали доступ в лабораторию. Я проверю код и покажу тебе

**Comment by RichardJones1** [comment]
Археолог не имеет доступа в отсек проведения исследований на станции. Если ты туда попал через шлюз - это либо недочет, либо шлюз просто пультом поставили на общий доступ.

Также не вижу смысла в пропозале, ведь выполнять работу ученых археолог не должен.
