### ISSUE TITLE
Почините вы уже отображение граффити на стенах

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#4423]
#### Подробное описание проблемы
Нет рисунков, отображающихся непосредственно на самих стенах, хотя в то же время мы спокойно можем на них рисовать мелком или баллончиком
#### Что должно было произойти
Нормальное граффити на стене = Нормальная игра в гэнг = Нормальный отыгрыш ревера, пишущего viva la revolution на стенке баллончиком краски
#### Что произошло на самом деле
Нормальное граффити ПОД стеной = Играйте в гэнг, рисуя только на полу = Все уже забыли какого это - рисовать на стенках
#### Как повторить
Мелок в руку. Клик мелком по стене. Любой рисунок на ваш вкус. Вуаля.

**Comment by TechCatOther** [comment]
Duplicate of #4323
