### ISSUE TITLE
Почините вы уже отображение могил

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#4424]
#### Подробное описание проблемы
Нет могил (и ям), которые мы роем кликом лопатой по железному песку.
#### Что должно было произойти
Действительно спрайт кучки земли или ямы.
#### Что произошло на самом деле
Я забыл уже как выглядит спрайт кучки земли или ямы.
#### Как повторить
Свалка (ну или на астероиде найти пару могил). Клик лопатой по Iron Sand. Разочароваться.
#### Дополнительная информация:
Если поверх ямы будет какой-нибудь, скажем, гроб, то спрайт каким-то образом оказывается поверх гроба. Кстати я такую тему раньше писал, поднимаю.

**Comment by Bullethole** [comment]
круто бы было самому делать ямы, в любом месте, и закапывать в гробах людей)00)

**Comment by TechCatOther** [comment]
Duplicate of #3925
