### ISSUE TITLE
Почините вы уже модуль дрели на шахтёрском риге

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#4425]
#### Подробное описание проблемы
Начали поступать жалобы о том, что не может включиться дрель на шахтёрском РИГе. При попытке копать ею им пишет "The sonic jackhammer is turned off!"
#### Что должно было произойти
Копание руды наплечной дрелью
#### Что произошло на самом деле
The sonic jackhammer is turned off!
#### Как повторить
Заказывайте себе шахтёрский РИГ.

**Comment by TechCatOther** [comment]
Это риг назвается "mining hardsuite"? 
Взял такой риг, включил дрель на нем и все работает. Пробывал разрядить его, результат ниже.
![изображение](https://user-images.githubusercontent.com/378937/71650567-d0e71100-2d27-11ea-8b24-97555508ef7c.png)
Потребуется более точно описать как воспроизвести, по сообщению выше я не нашел откуда это может быть.

**Comment by MichaelMaxPower** [comment]
У меня лично это произошло после замены батарейки рига, на super. Пошел бурить, получил такую же проблему.

**Comment by Motzord** [comment]
Никогда не баговало, все работало стабильно. (Возможно кто-то держал Джакхамер в руке и врубил наплечный бур, тогда ВПОЛНЕ вероятно, что сел не наплечный бур а именно отбойник)

**Comment by Motzord** [comment]
Беру слова назад, оно багует

**Comment by volas** [comment]
возможно #4417
