### ISSUE TITLE
Лицо видно через радио

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#4429]
#### Подробное описание проблемы
Человек со сломанным лицом говоря по радио будет звучать как Unknown (as Имя)

#### Что должно было произойти
James Morgan says, "Hello, world!"

#### Что произошло на самом деле
Unknown (as James Morgan) says, "Hello, world!"

#### Как повторить
Сломать лицо и говорить по радио

**Comment by TechCatOther** [comment]
В момент данного сообщения слышаший видел персонажа?

**Comment by Ahion** [comment]
Вроде так и должно быть. С обезображенным лицом или в маске ты человека не узнаешь - Unknown. А если он начнет говорить, то узнаешь по голосу - Unknown (as James Morgan)

**Comment by TechCatOther** [comment]
Если человека слышно по радио у него не будет приставки "as". Это только при визуальном наблюдении

**Comment by Motzord** [comment]
В операции по восстановлению ебасосины фигурирует восстановление голосовых связок. (Да и вряд ли человек с разбитым в кровь лицом, выбитыми зубами и переломанным носом будет говорить НОРМАЛЬНО в наушник)

И да голос в наушнике не меняется будь ты хоть серым человечком, а жаль
/thread

**Comment by Ahion** [comment]
> Если человека слышно по радио у него не будет приставки "as". Это только при визуальном наблюдении

Логично

**Comment by LudwigVonChesterfield** [comment]
> Simptom (Xenobiologist) [145.9] says, "Я слегка потерялся"

> Now tracking Bill Miller on camera.
> Target is not near any active cameras

забавно что камера прыгает не к тому кто якобы носил бы голос, а к тому кто действительно что-то сказал и таким образом палит людей которые носят на себе чужие карты.

**Comment by LudwigVonChesterfield** [comment]
ой, это не в эти ворота
