### ISSUE TITLE
Швабра и руны культистов

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#443]
#### Подробное описание проблемы

Швабра, намоченная водой, просто смывает руны культистов
#### Что должно было произойти

Руна культистов должна была остаться
#### Что произошло на самом деле

Руна исчезла
#### Как повторить

Взять швабру, намочить ее в воде, кликнуть по тайлу с руной

**Comment by Raschert0** [comment]
Емнип, это фича

**Comment by Skippeer12** [comment]
Ну ты конечно молодец, спалил фичу. Браво

**Comment by dearprincesscelestia** [comment]
Почему швабра не должна смывать рисунок кровью?

**Comment by WallShrabnic** [comment]
Почему и как швабра может смывать руну стены?
