### ISSUE TITLE
[Task/обсуждение] Рефакторинг гейммодов, антагонистов,  [$40]

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#4434]
Один из очень проблемных моментов в билде - часть кода, связанная с режимами, за которую со времен форка ни разу не брались.
С этим была уже проделана работа на Бэй, ТГ, ВГ (везде по своему), мне кажется у [ВГ](https://github.com/vgstation-coders/vgstation13/tree/Bleeding-Edge/code/datums/gamemode) получился наиболее интересный вариант. Соответствующие PR-ы можно найти у них в трекере по специальному тегу [Role Datums](https://github.com/vgstation-coders/vgstation13/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+label%3A%22Role+Datums%22+) (конкретно рефакторинги у них имеют еще [Role Datums] в тайтле).
Отчасти это порт-реквест, но у нас было много уникальных изменений, которые требуется сохранить, так что в любом случае работы много.

Требуется:
* Датумные антаги
* Фракционные датумы антагонистов
* Соответствующий рефакторинг режимов, унификация и упрощение
  * Среди прочего - почистить дублирующийся код относительно итогов раунда (бесконечные ``completion_text +=`` сквозь тучи проков)
  * Убрать неактуальные режимы, что-то мы даже сейчас не компилируем (антирева, обычная рева, где-то там еще пираты были)
* Переписать ``scorestats``/``scoreboard`` (они сами по себе плохи, но еще часть полей дублирует считаемую статистику с других мест)
* (опционально, достаточно будет просто не сломать) в ``drop_round_stats()`` заменить ``stats["completion_html"]`` на вложенные json-ы итогов режима (формат можно обсудить со мной)

**Comment by volas** [comment]
Обсуждение пока не сложилось, но если что - на задачу есть еще бюджет, возможно по желанию разделить на несколько частей.

**Comment by KIBORG04** [comment]
На ВГ структура получилась классной, типо это взаимоотношение game_mode -> faction(team) -> role(antagonist). Но вот с кодом там довольно странное дело, множество неиспользуемых проков и переменных, баги, странный нейминг местами, спагетти код какой-то. Кодер с ВГ будто бы заставляет хардкодить, чтобы всё нормально работало. 
Но, впринципе, это всё фиксится и исправляется, но я узнал про это слишком поздно, поэтому ВГ-структура будет, наверное, даже с их динамичным режимом игры (хотя все же лучше взять с тг их улучшенный порт, но тогда порт в порту и в итоге мешанина)
Eсли что, все вы найдете у меня в ветке `some_gamemode_update`, но я планирую сделать большее, чем обычный порт, хочу оказуалить(упростить) код и от первой итерации тикера, до последней.
