### ISSUE TITLE
[Task] Бан аноунсер на родственные сервера

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#4435]
Наши основные сервера используют общую базу данных, и соответственно делят баны. Но проблема в том, что "забанен ли игрок" проверяется только на момент подключения, если игрок в момент бана на одном сервере находится одновременно на другом - он может продолжать играть там.

Требуется написать аноунсер, который будет сообщать на другие сервера информацию о банах, и кикать игроков с этих серверов по случаю бана на первом.

* Настройка серверов в ``config/announcer/``, отдельный файл со списком родственных серверов в формате ``byond://game.taucetistation.org:2506`` (в будущем этот же конфиг можно будет использовать для умных редиректов, но это потом)
* Сервер, где игрок получает бан, должен отправить через [world.Export()](http://www.byond.com/docs/ref/info.html#/world/proc/Export) сообщение на другие сервера из конфига
  * Сообщение должно содержать ckey игрока, его ip и cid
  * Для избегания спама сообщение так же должно содержать пароль, который так же должен находится в ``config/announcer/``. На сервере пароль следует хранить в глобальной переменной.
* Принимающий сервер должен в [``world.Topic()``](https://github.com/TauCetiStation/TauCetiClassic/blob/6a78e6e3f1dbd0fc663c896a1aa454203dba9584/code/game/world.dm#L130) проверить сообщение, пароль, проверить есть ли на сервере игроки с соответствующими ckey/ip/cid, и если да - получить из базы сообщение бана, показать игроку и кикнуть с сервера.

**Comment by Kernstall** [comment]
А через триггер на базе можно послать сообщение на все коннекшны?

**Comment by volas** [comment]
Не уверен, и не думаю что стоит решать через базу.

**Comment by Sakuya-Izayoi** [comment]
где баунтисорс

**Comment by TechCatOther** [comment]
Что требуется делать, если в базе нету причины бана или бан не найден? По анонсу полученные значения совпадают с игроком на сервере.

**Comment by volas** [comment]
Ничего
