### ISSUE TITLE
Неправильный шашлык

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4436]
#### Подробное описание проблемы
Шашлык можно делать лишь из мяса хумана и мартышки
#### Что должно было произойти
Куриный шашлык, шашлык из собаки, неба аллаха
#### Что произошло на самом деле
Пустил курицу на мясо, сломал гриль
#### Как повторить
Сделайте шашлык из пущеной на мясо курицы
#### Дополнительная информация:
Это не круто

**Comment by Kortez90** [comment]
Спрайты привези.

**Comment by Motzord** [comment]
> Спрайты привези.

зачем? Пускай имеет спрайт обычного шашлыка, а не ломает нахрен грил и делает мусор
