### ISSUE TITLE
Банкоматы не работают в IE8

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#4441]
#### Подробное описание проблемы
Вход в аккаунт в банкомате не работает в IE8

#### Что должно было произойти
По нажатию на кнопку должен происходить вход в аккаунт в банкомат

#### Что произошло на самом деле
Ничего

#### Как повторить
Воспользоваться банкоматом имея версию эксплорера не более 8

#### Дополнительная информация:
Ну там же ничего сложного вроде нет.

**Comment by TechCatOther** [comment]
А какая точная версия использовалась?

**Comment by TechCatOther** [comment]
Я проверил на IE8+Win7 и IE9+Win7
IE8 не поддерживается сервером нормально. Лучше обновить хотябы до IE9

**Comment by Sakuya-Izayoi** [comment]
Обновить нельзя.

**Comment by volas** [comment]
человек с wine-проблемами, но объясняет это в последний момент

**Comment by TechCatOther** [comment]
IE 8 всеми признан как худущий браузер за всю историю. Там 25% всего работает не так как в стандартах. Половина функций js работает в 10! раз медленнее. Если мы официально откажемся от его поддержки смогу обновить jquery и решить лаги и баги в нано интерфейсе.

**Comment by Ahion** [comment]
> решить лаги и баги в нано интерфейсе.
То что нужно!

**Comment by TechCatOther** [comment]
IE8 не поддерживается на сервере
