### ISSUE TITLE
Абдукторы все еще сломаны

### ISSUE THREAD

**Issue by Ayuska** [TauCetiStation/TauCetiClassic#4447]
#### Подробное описание проблемы
Раунд за абдукторов, крадем всех и все что не прибито, решаю взять второй научной инструмент, чтобы проверить можно ли сразу пометить двух людей и вернуть их через телепорт, возвращаю одного человека, пытаюсь вернуть второго. Кнопка Retrieve Mark становится серой. При попытках пометить агента и вернуть все так же серая.
#### Что должно было произойти
Оба научных инструмента абдкуторов телепортируют домой не сбивая значения.
#### Что произошло на самом деле
Рестарт раунда из-за сломанного режима.
#### Как повторить
Взять абдуктора, купить научный инструмент, попытаться пометить 2 и более человек, нажать Retrieve mark

**Comment by Zmey25** [comment]
>Голосуют за сломанный режим
>Пишут ишью, что режим сломан

**Comment by TheReaperOfSouls** [comment]
> 
> 
> > Голосуют за сломанный режим
> > Пишут ишью, что режим сломан

Этот режим есть в общем доступе при выборе BS12. Либо его дофиксите, либо уберите.

**Comment by pss88** [comment]
> Кнопка Retrieve Mark становится серой. При попытках пометить агента и вернуть все так же серая.

Попытки пометить были обоими научными инструментами? Или только вторым?
Консоль "знает" только об одном инструменте за раз. Чтобы переключить на другой, нужно кликнуть инструментом по консоли.

**Comment by Deahaka** [comment]
Полагаю особенность механа
