### ISSUE TITLE
[Proposal] Хим мастер в техах

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#4451]
Хим мастер это очень сильная штука. Учитывая, что правило о профильных знаниях теперь не более чем рекомендация, каждый дебил с доступом в тех. тоннели может сварить себе термит и загрифонить любой отсек, наготовить себе лекарств для робаста и тому подобное. Как вариант предлагаю туда поместить батарейку похуже и плату переносного хим. раздатчика в котором недоступны все химикаты.

**Comment by FelixRuin** [comment]
я не знаток рнд конечно
но случаем переносной хим диспенсер это не хай тек?
да и батарейка вроде только в нём есть
если через вв не менять (если конечно там не хард код)
