### ISSUE TITLE
Барные стулья нельзя взять в руку и невозможно из-за этого ломать лица

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#446]
#### Подробное описание проблемы
Стулья в баре не берутся в руки

#### Что должно было произойти
Барные стулья должны были оказаться в руке как оружие

#### Что произошло на самом деле
Ничего, стул остался на месте

#### Как повторить
Перетянуть стул на себя

#### Дополнительная информация:
Раньше брались стулья и можно было драку устроить

**Comment by dearprincesscelestia** [comment]
А просто кликать на стулья пробовал?

**Comment by Raschert0** [comment]
И интент, если не ошибаюсь, должен быть граб или харм

**Comment by Damirrus1** [comment]
А ну наверное так

**Comment by dearprincesscelestia** [comment]
Наверное как? Ты попробуй, если они берутся кликом - значит, там стоит не тот стул, итем (тот самый, который уже взят в руку).

**Comment by Damirrus1** [comment]
Нет, не работает, не берутся любыми интентами.

**Comment by dearprincesscelestia** [comment]
Баг конфермед.

**Comment by Raschert0** [comment]
Там просто не те стулья
Те, которые можно брать, в асистентской

**Comment by dearprincesscelestia** [comment]
Все табуреты (stool) одинаковые, у них даже итем в руке одинаковый четырехногий. Барные стулья высокие на одной ножке тоже были беромые в руки, и так и должно быть же, для того и фича.

**Comment by Damirrus1** [comment]
Вот стулья в церкви нормально берутся.

**Comment by Raschert0** [comment]
Короче, смотрите, что я нашёл

```
/obj/structure/stool/MouseDrop(atom/over_object)
	if(ishuman(over_object) && type == /obj/structure/stool)
		var/mob/living/carbon/human/H = over_object
		if(H==usr && !H.restrained() && !H.stat && in_range(src, over_object))
			var/obj/item/weapon/stool/S = new/obj/item/weapon/stool()
			S.origin = src
			src.loc = S
			H.put_in_hands(S)
			H.visible_message("<span class='red'>[H] grabs [src] from the floor!</span>", "<span class='red'>You grab [src] from the floor!</span>")
			return
	return ..()
```

Как можно понять из кода выше, эта фича работает только с обычными стульями (не барными)

**Comment by SpaiR** [comment]
барные стулья как бы к полу прикручены
