### ISSUE TITLE
Runtime in fuel.dm,43

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#4469]
#### Подробное описание проблемы
Рантайм ошибка в топливе

#### Как повторить
Поджечь разлитое топливо, взорвать зажигательную гранату

#### Дополнительная информация:
https://cdn.discordapp.com/attachments/343089687902027777/664218774286762004/unknown.png

**Comment by LudwigVonChesterfield** [comment]
#5120
