### ISSUE TITLE
Ножницы парикмахера нельзя очистить от крови

### ISSUE THREAD

**Issue by LiJard** [TauCetiStation/TauCetiClassic#4473]
#### Подробное описание проблемы
Кровь на ножницах парикмахера нельзя смыть в раковине или очистить клинером
#### Что должно было произойти
Кровь на спрайте ножниц должна была исчезнуть
#### Что произошло на самом деле
Не исчезает 
#### Как повторить
Пырнуть кого-то в бок ножницами несколько раз и после этого попытаться их отмыть

**Comment by LudwigVonChesterfield** [comment]
#4358
