### ISSUE TITLE
Острые предметы отрубают голову при разрезании шеи.

### ISSUE THREAD

**Issue by PunishedHideo** [TauCetiStation/TauCetiClassic#4480]
#### Подробное описание проблемы
С помощью острых предметов(кусачки или нож, например) можно отрубить голову кукле, если несколько раз разрезать ей шею.

#### Что должно было произойти
Если мы режем шею маленьким предметом, мы никак не сможем впоследствии отрубить голову.

#### Что произошло на самом деле
Голова легко отрубается после двух-трёх разрезов горла.

#### Как повторить
Берите куклу в третий граб и режьте ей шею.

**Comment by Ambassadoing** [comment]
Это фича.

**Comment by PunishedHideo** [comment]
Энто баг.(если убрать его, то можно усложнить жизнь триторам)

**Comment by Ambassadoing** [comment]
Но это фича.

**Comment by TechCatOther** [comment]
Для этого потребуется ввести понятие маленький или не маленький и достаточный для отрубания головы для всех предметов

**Comment by RichardJones1** [comment]
> Для этого потребуется ввести понятие маленький или не маленький и достаточный для отрубания головы для всех предметов

Во первых, у нас уже есть что-то похожее - w_class. Во вторых, мне кажется, достаточно просто ввести ограничение по force предмета

**Comment by Sakuya-Izayoi** [comment]
by design

**Comment by Motzord** [comment]
Не баг а фича. Можно закрывать

**Comment by Motzord** [comment]
Больше нельзя рубить головы кусачками-стеклом, нужно закрыть
