### ISSUE TITLE
fishing

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#4486]
#### Подробное описание проблемы
Пойманные на рыбалочке карпики в основном не имеют спрайта

#### Что должно было произойти
У карпов должны быть спрайты

#### Что произошло на самом деле
Большинство карпов не имеют спрайта

#### Как повторить
Порыбачить

**Comment by da-kiselev** [comment]
Лол, а можно рыбачить? Как?

**Comment by LudwigVonChesterfield** [comment]
этот ишшуй касается реккурентного новогоднего ПР-а

https://github.com/TauCetiStation/TauCetiClassic/pull/4357
