### ISSUE TITLE
[Proposal] Добавить катушку Теслы на контур с эмиттерами

### ISSUE THREAD

**Issue by MichaelMaxPower** [TauCetiStation/TauCetiClassic#4488]
#### Подробное описание проблемы
Как и в случае с коллектором сингулярности на контур эмиттера (красный провод) добавить катушку Теслы (слева или справа или снизу от центра Теслы/Сингулярности), или хотя бы в хранилище у инженеров.

**Comment by Ambassadoing** [comment]
Зачем? Чтобы инженерам вообще не нужно было ничего делать, кроме как всё прикрутить и движок запустить?

**Comment by WallShrabnic** [comment]
Лол, подвести ток с внешних контуров на внутренние - дело пяти секунд

**Comment by TechCatOther** [comment]
Подвод тока таким образов будет разряжать тебе СМЕС, что питает внутренний контур.
