### ISSUE TITLE
Не у всех вендоматов видно панель с проводами

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#4496]
#### Подробное описание проблемы
Не на всех вендоматах рисуется мейнтенес панелька с проводами

#### Что должно было произойти
На вендоматах корректно должна рисоваться мейнтененс панель

#### Что произошло на самом деле
На некоторых торговых автоматах панель не рисуется

#### Как повторить
Кликнуть отвёрткой по вендомату

#### Дополнительная информация:
У меня не работало на синем вендомате с газировкой, насчёт остальных не знаю.

**Comment by TechCatOther** [comment]
![изображение](https://user-images.githubusercontent.com/378937/72677751-fc505680-3ab0-11ea-9f71-93ec7e80f6d8.png)
Вендоматы, где не работает
