### ISSUE TITLE
Борги не могут отвязывать от стульев и т.д.

### ISSUE THREAD

**Issue by Motykoo** [TauCetiStation/TauCetiClassic#4497]
#### Подробное описание проблемы
Все виды боргов не могут отвязывать кукл от стулов, каталок и прочих объектов такого типа. Это очень сильно портит игру за борга СБ, а за хирургического чуть ли не делает его зависимым от чужой помощи. Почему борг, который может проводить высокоточные операции, раздевать людей и делать прочие тонкие вещи, не может банально открепить куклу от стула?
#### Что должно было произойти
Успешно снятся кукла со стула или каталки.
#### Что произошло на самом деле
Кукла остаётся привязаной к предметам.
#### Как повторить
За борга посадить какую-либо куклу на стул и кликнуть по стулу, чтобы попытатся отвязать её.

**Comment by Zmey25** [comment]
Борг и должен быть зависим от людей, т.к. борг не полноценная замена персонала. Поэтому всегда относился к этому как к фиче. Ключом гаечным по стулу помогает.

**Comment by Motykoo** [comment]
М-м-м, эРПе

**Comment by Sakuya-Izayoi** [comment]
У роботов нет рук.

**Comment by Motykoo** [comment]
> У роботов нет рук.

У некоторых есть, что даже на спрайтах видно.
И это не исключает того факта что у них есть другие виды конечностей, которыми они таскают предметы, раздевают людей, снимают наручники и т.д., что им мешает отцепить человека?

**Comment by TechCatOther** [comment]
Полностью поддерживаю, что часть модулей требует это. Надо добавить такое как минимум кризисному модулю(не боевой), хирургу и возможно охранному. Остальным не требуется.
За модуля медика вообще ничего не можешь сделать. У тебя есть каталка, но если ты можешь куклу прикрепить к ней, то открепить уже нет. И даже в сканер,слипер,крио не положить. Из-за этого модуль почти полностью бесполезен и может разве что варить химию и доставлять в мед пациентов без помощи им.

**Comment by Zmey25** [comment]
Каталкой по каталке отцепляет человека от каталки, но это не точно

**Comment by Ambassadoing** [comment]
Точно. Нажатие вешалкой для каталки на каталку складывает её. Последующий клик помещает её на вешалку.

**Comment by Sakuya-Izayoi** [comment]
А смысл от людей если роботы будут отлично с их работой справляться?

**Comment by TechCatOther** [comment]
В данный момент борг для ученных полностью бесполезен.

**Comment by RAZUMNO** [comment]
Один фиг это как минимум не логично. Почему есть возможность привязать человека, но нет возможности отвязать? Действие само по себе точно такое же, только в обратном порядке воспроизводится.

**Comment by Motykoo** [comment]
UP UP! Пофиксите уже. Я просто хз как.
