### ISSUE TITLE
[Proposal] Поменять звуки телескопика при хэлпе

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#4510]
#### Подробное описание проблемы
Станя космонавтиков телескопиком хоса или капитана при хэлп интенте издаются звуки харматона.
#### Что должно было произойти
Легкий звук "Тюк!"
#### Что произошло на самом деле
Звук хармбатона
#### Как повторить
Раскрыть телескопик и попробовать кого то застанить

**Comment by Sakuya-Izayoi** [comment]
Мне просто интересно как лёгкий "тюк" может сделать человеку так больно, что он упадёт?

**Comment by ViDLiathan** [comment]
> Мне просто интересно как лёгкий "тюк" может сделать человеку так больно, что он упадёт?

Мне телескопик всегда представлялся тонкой но просной палочкой с маленьким электрошокером на конце. Что-то из того, чем коров погоняют.

**Comment by Motzord** [comment]
Телескопик это телескопик, тонкая металлическая прочная палочка с утяжилетем на конце способная уебать до перелома.

У нее нет шокеров, это не станбатон а палка для отхуяривания

**Comment by ViDLiathan** [comment]
> 
> 
> Телескопик это телескопик, тонкая металлическая прочная палочка с утяжилетем на конце способная уебать до перелома.
> 
> У нее нет шокеров, это не станбатон а палка для отхуяривания

Железные аргументы, приправленные матом. Тут не оспоришь.
А если серьезно, то у не летальных атак должен быть другой звук.
