### ISSUE TITLE
Закрыть воут за рестрат при наличии администратора

### ISSUE THREAD

**Issue by TechCatOther** [TauCetiStation/TauCetiClassic#4513]
#### Подробное описание проблемы
При наличии администраторов на сервере игроки могут запустить технический воут на перезапуск раунда. Блокирует возможность при его отмене запустить крю трансфер.
#### Что должно было произойти
Воут на рестарт должен быть недоступен при администраторе онлайн.
#### Что произошло на самом деле
Отменив воут за рестарт невозможно начать крю трансфер до истечения таймера.
Игроки не замечают, что это воут за рестрат и соглашаются на него. 
#### Как повторить
При администраторе онлайн запустить воут на рестрарт
#### Дополнительная информация:
https://forum.taucetistation.org/t/apellyacziya-just-empty-wallshrubnick/15373/5

**Comment by volas** [comment]
Воут за рестарт при живом администраторе не сработает, лишь покажет результаты на которые можно ориентироваться если что.
Проблема скорее в таймере на воут, который не стоит наверно обновлять при воуте на рестарт.
