### ISSUE TITLE
[Proposal] Сделать вортекс аномалию менее грифозной

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#4516]
Согласен, что космонавты должны страдать, но по большей части только от своей тупости.

Вортекс аномалия, в отличии от многих других действует сразу и, кажется, даже до анноунса. Даже если ученому в риге вдруг посчастливиться оказаться рядом, она уже успеет сломать пол и может порвать скафандр.
Спавнится в центральных и людных частях станции, такие как доки, зал совещания глав, химия, кабинет АВД и другие. 
Уничтожает стены, трубы и пожарные створки, моментально распространяя разгерму еще больше. С нашим атмосом слишком грифозно и чинить неисправности чуть ли не до конца раунда.

Хотелось чтоб ее убрали центральных мест куда-нибудь в теха станции, запретить ей ломать стены и пол или вообще выпилить.

**Comment by Dominig12** [comment]
а разве игра должна щадить игроков?
