### ISSUE TITLE
Плитка дронов заканчивается позже, чем может показаться при экзамине.

### ISSUE THREAD

**Issue by dearprincesscelestia** [TauCetiStation/TauCetiClassic#452]
#### Подробное описание проблемы

При использовании плитки на полу ее хватает на число тайлов, большее, чем указано при проверке. 

#### Что должно было произойти

Стопки деревянных плиток, при экзамине которой выводится "There are 5 wood floor tiles in the stack.", должно было хватить на пять тайлов пола.

Стопки металлических плиток, при экзамине которой выводится "There are 15 floor tiles in the stack.", должно было хватить на пятнадцать тайлов пола.

#### Что произошло на самом деле

- Деревянной плитки хватило на одиннадцать тайлов пола.
https://i.gyazo.com/508ac17440761f93d833af4a787b89ff.png
- После пятого тайла пола иконка плитки пропала из "руки" дрона, однако возможность класть плитки не пропала до двенадцатой попытки.

- Металлической плитки хватило на тридцать девять тайлов пола.
https://i.gyazo.com/ddb543126b3d930e31965e95cc3b64d2.png
- После пятнадцатого тайла пола иконка плитки пропала из "руки" дрона, однако возможность класть плитки не пропала до сороковой попытки.

#### Как повторить

1. Зайти за дрона.
2. Взять плитку.
3. Проложить.
4. Продолжать прокладывать после исчерпания запаса.

**Comment by Raschert0** [comment]
Это касается и кабелей (но там просто спрайт исчезает (или он просто не превращается в спрайт кусочка кабеля, не уверен))
