### ISSUE TITLE
Научный борг и его лом

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#453]
#### Подробное описание проблемы
Научный борг не может достать свой лом

#### Что должно было произойти
При нажатии на иконку лома в инвентаре борга, он должен попасть на панель быстрого доступа

#### Что произошло на самом деле
Лом не выбирается

#### Как повторить
Быть боргом с научным модулем

#### Дополнительная информация:
Научный борг использует красную модельку лома, когда у всех остальных стандартный серый.
Когда был старый текстовый интерфейс модулей, его можно было достать.

**Comment by dearprincesscelestia** [comment]
Отсылки к хафлафу убивают функционал.
