### ISSUE TITLE
[proposal] Добавить протезированным рукам больше урона

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4535]
#### Подробное описание проблемы
Металлические эпичные культяпки наносят столько же условных единиц пиздюлей(брута) сколько и мясные.
#### Что должно было произойти
Да это же пиздец как мощно бить в ебальник металлической конечностью, наверное травмы больнее и сильнее чем от куска мяса с костями
#### Что произошло на самом деле
Баффа нет.
#### Как повторить
Устройте эпичный махач полукиборга с лысым ассистухой

**Comment by rarytech** [comment]
человек с протезом это инвалид или киберсолдат

**Comment by Motzord** [comment]
> человек с протезом это инвалид или киберсолдат

Смотря с какой стороны смотреть. Да, возможности протеза ограничены, он ломается, его надо чинить, но он черт возьми металлический и ты фактически не чувствуешь урона по нему.

**Comment by rarytech** [comment]
а по месту соединения с телом

**Comment by Sakuya-Izayoi** [comment]
Поставил два протеза в сетапе @ уже панчишь сильнее любого игрока @ отхиливаешь руки сваркой и проводами прямо в бою

**Comment by TechCatOther** [comment]
Похоже на Кобру

**Comment by da-kiselev** [comment]
Поддерживаю, протезы ломаются в мгновенье ока, в обычной кулачной драке, а плюшек никаких нету, ну повысьте вы им слегка урон, чтоб я имел шанс сломать им череп быстрее, чем они меня запыряют розочкой, либо пока протез не взорвется, одно из двух. Пример из раунда, бился с парнем на арене, я - однорукий ассистент с протезом, мой оппонент - двурукий углерод, и как бы все нормально, изначально все равны, но ближе к концу драки, мой протез чуть ли не искрился, а оппонент тем временем и дальше шёл на меня, после ударов по лицу протезом!

**Comment by Motzord** [comment]
> Поддерживаю, протезы ломаются в мгновенье ока, в обычной кулачной драке, а плюшек никаких нету, ну повысьте вы им слегка урон, чтоб я имел шанс сломать им череп быстрее, чем они меня запыряют розочкой, либо пока протез не взорвется, одно из двух. Пример из раунда, бился с парнем на арене, я - однорукий ассистент с протезом, мой оппонент - двурукий углерод, и как бы все нормально, изначально все равны, но ближе к концу драки, мой протез чуть ли не искрился, а оппонент тем временем и дальше шёл на меня, после ударов по лицу протезом!

Этим оппонентом был я, гыгык

**Comment by da-kiselev** [comment]
> > Поддерживаю, протезы ломаются в мгновенье ока, в обычной кулачной драке, а плюшек никаких нету, ну повысьте вы им слегка урон, чтоб я имел шанс сломать им череп быстрее, чем они меня запыряют розочкой, либо пока протез не взорвется, одно из двух. Пример из раунда, бился с парнем на арене, я - однорукий ассистент с протезом, мой оппонент - двурукий углерод, и как бы все нормально, изначально все равны, но ближе к концу драки, мой протез чуть ли не искрился, а оппонент тем временем и дальше шёл на меня, после ударов по лицу протезом!
> 
> Этим оппонентом был я, гыгык

Хыхыхыхыхы, как тебе мой одноруки бандит?

**Comment by da-kiselev** [comment]
> > > Поддерживаю, протезы ломаются в мгновенье ока, в обычной кулачной драке, а плюшек никаких нету, ну повысьте вы им слегка урон, чтоб я имел шанс сломать им череп быстрее, чем они меня запыряют розочкой, либо пока протез не взорвется, одно из двух. Пример из раунда, бился с парнем на арене, я - однорукий ассистент с протезом, мой оппонент - двурукий углерод, и как бы все нормально, изначально все равны, но ближе к концу драки, мой протез чуть ли не искрился, а оппонент тем временем и дальше шёл на меня, после ударов по лицу протезом!
> > 
> > 
> > Этим оппонентом был я, гыгык
> 
> Хыхыхыхыхы, как тебе мой однорукий бандит?

**Comment by Pivo24** [comment]
Протез = Искорки от повреждения
Протез = Защита конечности от сепсиса
Протез = Включил электрификацию на шлюзе, починил ручку проводкой
Протез = Ронять оружие от сбоев при повреждении, что не даёт участвовать в схватке

Ты предлагаешь:

Протез = Искорки от повреждения
Протез = Защита конечности от сепсиса
Протез = Включил электрификацию на шлюзе, починил ручку проводкой
Протез = Оружие которое никогда не уронишь

Ты, извини, совсем того?

**Comment by da-kiselev** [comment]
> Протез = Искорки от повреждения
> Протез = Защита конечности от сепсиса
> Протез = Включил электрификацию на шлюзе, починил ручку проводкой
> Протез = Ронять оружие от сбоев при повреждении, что не даёт участвовать в схватке
> 
> Ты предлагаешь:
> 
> Протез = Искорки от повреждения
> Протез = Защита конечности от сепсиса
> Протез = Включил электрификацию на шлюзе, починил ручку проводкой
> Протез = Оружие которое никогда не уронишь
> 
> Ты, извини, совсем того?

Кхм, я предлагаю протез = чуть больше урона в кулачной драке, угуууууу, а остальное, что ты мне приписал, уже было
