### ISSUE TITLE
режим heist не работает

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#4537]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/44546836/72730594-ba074200-3ba2-11ea-8c31-da59822839e9.png)

#### Что должно было произойти
воксы
#### Что произошло на самом деле
воксов нет
#### Как повторить
выбрать секрет

**Comment by Lizurt** [comment]
![image](https://user-images.githubusercontent.com/42589308/72731255-6b5aa780-3ba4-11ea-9272-c37f02438aba.png)

У товарища опечаточка в https://github.com/TauCetiStation/TauCetiClassic/pull/4460

('/hiest/` вместо `/heist/`)

**Comment by TechCatOther** [comment]
Упс. Извиняйте
