### ISSUE TITLE
Пропала команда sleeping в VV

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#4540]
#### Подробное описание проблемы
Пропала команда sleeping в VV
#### Что должно было произойти
Она должна там быть что бы иметь возможность быстро усыплять грифозных игроков
#### Что произошло на самом деле
Ее там нет
#### Как повторить
Посмотреть в ВВ любой куклы

**Comment by Dominig12** [comment]
#4478

**Comment by Dominig12** [comment]
@LudwigVonChesterfield
