### ISSUE TITLE
Power-Fist игнорирует броню

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#4541]
#### Подробное описание проблемы
Power-Fist полностью игнорирует любую броню. С полным баллоном на втором уровне он с одного клика ломает кости хосу или дедскваду в броне.
#### Что должно было произойти
Павер перчатка должна учитывать броню на носящем
#### Что произошло на самом деле
Она имба

**Comment by Zmey25** [comment]
[голосом глэдос из первой части портала, русская озвучка]: Сейчас вы поняли как кинетическая энергия влияет на броню, а именно - никак.

**Comment by TechCatOther** [comment]
А еще не оставляет отпечатков и крови. Идеальное оружие.
