### ISSUE TITLE
[proposal] Изменить цвет дизармлогов в плеер фильтре

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4550]
#### Подробное описание проблемы
Новички и не очень умные люди при видя красного лога с именем его куклы обязательно думают, что его бьют, даже если написано слово disarm
#### Что должно было произойти
Новичок и не очень умный человек меньше паникуют от дизарм логов, потому что это не бьют, а ТОЛКАЮТ
#### Что произошло на самом деле
*дизармнул ассистуху*
а) ЭСБЭ МИНЯ УБИВАЕТ БРОКЕН БОТТЛ
б) *ассистуха достает баллон и начинает тебя им забивать с ризоном "ты первый бить начал"*
#### Как повторить
Проследите тенденцию новичков паниковать от дизармлогов

**Comment by Motzord** [comment]
Дебильное словосочетание "плеер фильтре", мне нужно было просто выделить, что речь идет о тех логах, которые видят игроки а не педали...

**Comment by TungstenOctopus** [comment]
С одной стороны это проблема да. Но решение странное. Начнем с того, что у нас почему-то ОБЕЗОРУЖИВАНИЕ валит человека с ног. Объясню - что такое обезоружить человека безоружного? Это как? Продолжим. Человек повалил другого, достал баллон и проломил череп. Казалось бы, он его не бил, а ОБЕЗОРУЖИВАЛ. Безобидно да? А в итоге пиздец.
Также здесь играет роль то, что люди банально не знают англицкого языка и для них все эти kicked punched pushed disarmed - сорта говна. 
На данный момент дизармы справедливо считаются нападением. Не думаю, что стоит это менять.

**Comment by Motzord** [comment]
> С одной стороны это проблема да. Но решение странное. Начнем с того, что у нас почему-то ОБЕЗОРУЖИВАНИЕ валит человека с ног. Объясню - что такое обезоружить человека безоружного? Это как? Продолжим. Человек повалил другого, достал баллон и проломил череп. Казалось бы, он его не бил, а ОБЕЗОРУЖИВАЛ. Безобидно да? А в итоге пиздец.
> Также здесь играет роль то, что люди банально не знают англицкого языка и для них все эти kicked punched pushed disarmed - сорта говна.
> На данный момент дизармы справедливо считаются нападением. Не думаю, что стоит это менять.

Мне не нравится сама рефлекторная реакция на красный цвет логов и новичков. 

Вот тебе небольшое лирическое отступление, из-за которого получилось очень смешно.

Тащу я на парамедике труп, по человечески, прибегает интерн начинает его пуллить, я интерна есесна дизармлю, пушто нельзя так трупы таскать, а интерн херачит в меня слиптоксин и вызывает СБ пушто "Парамедик напал пока я помогал пациенту"

История смешная а ситуация страшная, возможно, если бы цвет дизармлогов был како нибудь синий/голубой/не_красный, новички понимали бы, что дизарм не попытка отхерачить куклу, а лишь попытка повалить. `а потом отхерачить`

**Comment by Sakuya-Izayoi** [comment]
дизарм это толчок по идее или какое-то действие с руками оппонента которое обезоруживает его. так что пиздить в ответ за дизармы это вполне справедливо. меньше хернёй страдайте в раундах.

**Comment by TungstenOctopus** [comment]
> Тащу я на парамедике труп, по человечески, прибегает интерн начинает его пуллить, я интерна есесна дизармлю, пушто нельзя так трупы таскать, а интерн херачит в меня слиптоксин и вызывает СБ пушто "Парамедик напал пока я помогал пациенту"

Ну так мог бы еще и кулаками ему по ебалу дать и был бы прав, в твоей ситуации ты напал на него для того чтоб остановить его, так ведь? А если бы прокнул пуш, то ты бы все еще считал это просто дизармом? Опять же, надо учиться брать ответственность за свои действия и поступки, считаешь, что надо кого-то дизармить - прими как факт, что он скорее всего будет дизармить тебя в ответ. И ему плевать прав ты или нет, вдруг он считает что ты на него напал? Ты же и правда на него напал. По какой причине - другой вопрос. Так что ты неправильно воспринимаешь ситуацию.

**Comment by Motzord** [comment]
Просто сделайте дизармлог другого цвета и все будут менее агрессивно реагировать на дизарм, пушто буковки не красные, я вам вот говорю все так и будет, не бухтите...

**Comment by igigin** [comment]
Но ведь дизарм - один из самых опасных интентов в сске.

**Comment by TungstenOctopus** [comment]
> Просто сделайте дизармлог другого цвета и все будут менее агрессивно реагировать на дизарм, пушто буковки не красные, я вам вот говорю все так и будет, не бухтите...

Тебе говорят что это опасный интент и на него надо агрессивно реагировать, а ты в ответ, что просто сделайте.

**Comment by TechCatOther** [comment]
Можно переименовать дизарм в пуш, если руки цели пустые. Но все же это агрессивный контакт по отношению к цели и красный цвет здесь верный.

**Comment by LudwigVonChesterfield** [comment]
Дизарм теперь официально пуш. Но логи всё так же красные. Проблема ли это до сих пор?
