### ISSUE TITLE
В режиме гэнга невозможно вызвать доминатор

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#4552]
#### Подробное описание проблемы
В режиме гэнга невозможно вызвать доминатор
#### Что должно было произойти
Босс должен иметь возможность вызвать доминатор с помощью ганг тула.
#### Что произошло на самом деле
Его нет. Даже заспавнить нельзя
#### Дополнительная информация:
Важно: Я его запускал во время режима Воксов (которые не запавнились). Взял двух игроков и дал им боссов и экипировку. Возможно, если изначально поставить режим гэнга то он будет работать.
![image](https://user-images.githubusercontent.com/19417166/72924560-d39eba00-3d59-11ea-95c5-d6fd29fc5c4e.png)

**Comment by Sakuya-Izayoi** [comment]
https://github.com/TauCetiStation/TauCetiClassic/blob/6226b4fe9a2bc99e629e564608a80f35b12dc4e3/code/game/gamemodes/gang/recaller.dm#L140

баг? или хитрая задумка автора против шитспаунеров?

**Comment by TechCatOther** [comment]
Явно фича

**Comment by WallShrabnic** [comment]
Закрывайте, генг выпилен

**Comment by T6751** [comment]
Режим был удалён в #6909. В связи с этим проблема больше не актуальна
