### ISSUE TITLE
Дело о пропаже телекристалов, или как у синдиката закончились деньги

### ISSUE THREAD

**Issue by Thirteenalex** [TauCetiStation/TauCetiClassic#4557]
#### Подробное описание проблемы
У автотриторов не выдаются телекресталы
#### Что должно было произойти
Они должны выдаться
#### Что произошло на самом деле
Их нет
#### Как повторить
Получить автотриторку
#### Дополнительная информация:
Опционально, проверить реву, нюку

**Comment by Sakuya-Izayoi** [comment]
#4397

**Comment by KIBORG04** [comment]
дает
