### ISSUE TITLE
Емаг помимо взлома бьет цель

### ISSUE THREAD

**Issue by TungstenOctopus** [TauCetiStation/TauCetiClassic#4558]
#### Подробное описание проблемы

Емаг помимо своей основной функции - взлома - делает еще дефолтное взаимодействие с объектами. Двери - открывает (или вызывает deny анимацию), роботов - бьет (сам не проверял, @AndroBetel )

#### Что должно было произойти

Емаг взламывает цель (если может) и на этом взаимодействие заканчивается

#### Как повторить

Кликнуть емагом по емагабельному объекту

#### Дополнительная информация:

https://github.com/TauCetiStation/TauCetiClassic/pull/3612

**Comment by AndroBetel** [comment]
![image](https://user-images.githubusercontent.com/44546836/73003193-44a3a780-3e16-11ea-91e6-d28497636870.png)
