### ISSUE TITLE
Штамп ЦК у офицериков велосити

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4559]
#### Подробное описание проблемы
Вместо Апрувед штамп, у офицеров велосити штамп ЦК. И печать ЦК, требуется просить педаль заменить
#### Что должно было произойти
Апрувед и Денает. Слава Арстоцке
#### Что произошло на самом деле
Случайно лепишь ассистухе штамп цк
#### Как повторить
Поиграйте на офицере велосити

**Comment by atik1n** [comment]
Fixed
