### ISSUE TITLE
Недофикшенный кравл

### ISSUE THREAD

**Issue by KatoMarika** [TauCetiStation/TauCetiClassic#456]
#### Подробное описание проблемы
Кравл позволяет вставать на столе, вставать быстрее чем это требует прогрессбар. 
#### Что должно было произойти
Персонаж должен был перестать вставать\удариться об стол головой
#### Что произошло на самом деле
Персонаж встал на столе\персонаж встал быстрее
#### Как повторить
Сделать следующий порядок действий: лежа перед столом начать вставать и после этого передвинуться. Тоже самое с быстрым вставанием.

**Comment by Miracler112** [comment]
Это фича. Вот со столом беда

**Comment by Skippeer12** [comment]
Такую фичу занерфали, ну всё.
