### ISSUE TITLE
Доступа "Офицер Велосити" не существует ни для консоли id-карт ни для консоли выдачи пропусков

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4561]
#### Подробное описание проблемы
>Ассистуха, кадет, офицер, лично капитан волеизъявляет поработать на велосити, оформил бумажки отправил запрос на вечномолчаливый ЦК
>Ладно, главы разрешили ассистухе работать у тебя
>Хочешь поменять доступ на карте или выдать пропуск
>А нужной кнопки нету
#### Что должно было произойти
Нужная кнопка есть, допуск выдается
#### Что произошло на самом деле
Ничего не происходит, педаль не хочет щитспавнить
#### Как повторить
Попробуйте дать себе допуск офицера велосити через консоль

**Comment by LudwigVonChesterfield** [comment]
Потому-что и такой профессии как офицер велосити не существует. Велосити юзает ЦК доступы, и является плюс-минус оок зоной.

**Comment by Motzord** [comment]
> Потому-что и такой профессии как офицер велосити не существует. Велосити юзает ЦК доступы, и является плюс-минус оок зоной.

так кто-то же делал отдельные доступы офицерам велосити, не?

Пушто они раньше имели фулакус на станции из-за ЦК доступов

**Comment by LudwigVonChesterfield** [comment]
они не из-за этого имели полный доступ к станции.

**Comment by Motzord** [comment]
> они не из-за этого имели полный доступ к станции.

В любом случае неприятно

**Comment by Sakuya-Izayoi** [comment]
Не баг, а пропосрал. Ещё и не нужен.

**Comment by EdlerN** [comment]
А давайте еще разрешим станции офицеров цк назначать, а? Раз уж совсем в маразм уходить.
Велосити - это не игровая зона. И спавн офицеров сугубо административное решение. Так что и доступ этот в консолях не нужен.
