### ISSUE TITLE
[Proposal] Индикатор тревоги в ПДА

### ISSUE THREAD

**Issue by TechCatOther** [TauCetiStation/TauCetiClassic#4565]
#### Подробное описание проблемы
Нет интерфейса для определения уровня тревоги на станции для обычного экипажа. Красный и дельта код можно посмотреть через пожарную тревогу или через экраны на стене, если их не заменили другими сообщениями. Для остальных недоступно отображение.
#### Что должно было произойти
Посмотрел в ПДА и понял, что код синий или зеленый. 
#### Что произошло на самом деле
Спрашиваешь у всех какой уровень тревоги
#### Дополнительная информация:
Хорошие место рядом с часами в ПДА. Просто картинка с цветом тревоги на станции. Дельту предлагаю сделать черного цвета, остальные по названию зеленый, синий, красный.

**Comment by AndroBetel** [comment]
для остальных это для кого? пожарные тревоги есть В КАЖДОМ отсеке, да и выйти-посмотреть в коридор - не очень долгое дело.

**Comment by Loratron** [comment]
На кнопках активации пожарной тревоги можно посмотреть любой код - не обязательно даже подходить к ним, код показывается самим спрайтом кнопки

**Comment by TechCatOther** [comment]
Но ты не всегда на станции, за шахтера или археолога не просто понять текущий уровень тревоги.
