### ISSUE TITLE
В капитанской душевой нет слива

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#4566]
#### Подробное описание проблемы
В капитанской душевой нет слива для воды
#### Что должно было произойти
Чистота тела и духа
#### Что произошло на самом деле
Не очень смышленый капитан закончил работу в эту смену
https://imgur.com/a/jmHGT1Y
#### Как повторить
Пойти помыться в капитанскую душевую

**Comment by T6751** [comment]
Resolved by #6159
