### ISSUE TITLE
[Proposal] Ячейки в поясах и инвентарь в рюкзаках

### ISSUE THREAD

**Issue by RAZUMNO** [TauCetiStation/TauCetiClassic#4567]
Есть предложение как можно сделать более логично и удобно. Сейчас довольно неплохо сделан инвентарь в рюкзаках, коробках и т.д. То есть, есть общее кол-во заполняемого места, какая-нибудь таблетка заполняет этот инвентарь на очень маленькое кол-во. В то же время, в том же медицинском поясе есть всего 7 ячеек, которые заполняются полностью любым предметом, который в него (пояс) можно положить. Есть предложение разделить пояс не на 7 ячеек, а на 7 инвентарей. Отображаться будет ровно так же эти инвентари, как и сейчас ячейки. Но заполняться будут предметами исходя из того, на сколько они большие, как это сделано сейчас в рюкзаках, коробках и т.д. То есть в кармашек в медицинском поясе можно положить уже не 1 таблетку, а 3 или 4. И тогда с рюкзаками станет пологичнее, т.к. персонал на станции, всегда бегающий с рюкзаками, это очень не реалистично, а уж с полностью набитыми, всяким барахлом, рюкзаками ещё более не реалистично.

**Comment by Zmey25** [comment]
Ко второй части сообщения: Манча это чисто ролеплейная штука, меня на блеке, например, били по голове за полный инженерский Рюкзак, а вот у нас к этому не так строго относятся (см. Курс на рп)

**Comment by ViDLiathan** [comment]
Что значит "Полный инженерский рюкзак"? Если ты набиваешь фулл стаками металла и стекла, то правильно ругают. НАМ БЫ ТАК

**Comment by GermanSUS** [comment]
Медицинский пояс, не сумка кондуктора, и все что там лежит просто крепится к нему или лежит в равных по размеру сумочках. А если добавить фитчу рюгзака, то мы потеряем разницу между поясами, а если оставить в этом случае запрет на вещи, то зачем фитчу добавлять? Что бы носить больше таблеток и лекарств?

**Comment by RAZUMNO** [comment]
> Медицинский пояс, не сумка кондуктора, и все что там лежит просто крепится к нему или лежит в равных по размеру сумочках. А если добавить фитчу рюгзака, то мы потеряем разницу между поясами, а если оставить в этом случае запрет на вещи, то зачем фитчу добавлять? Что бы носить больше таблеток и лекарств?

Именно чтобы носить больше таблеток и лекарств. В конкретно медицинском поясе. В других поясах, свои вещи будут больше носить (или меньше). Иначе опять же, 7 таблеток, Карл. 7! Возьми в руку 7 таблеток и скажи, где ты на поясе найдёшь 7 кармашков под размер таблетки? В то время, когда ты в абсолютно такой же кармашек можешь положить анализатор здоровья, шприц, etc.

**Comment by DarthSidiousPalpatine** [comment]
почему бы не носить таблетки в банках для таблеток?
