### ISSUE TITLE
Удаленное управление дверьми синтетами через камеры наблюдения 

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#457]
#### Подробное описание проблемы
Борги с помощью камер охраны могут взаимодействовать с дверьми, которые они видят с выбранной камеры.

![screenshot_1](https://cloud.githubusercontent.com/assets/20542000/17726407/96b4793e-6474-11e6-9b8c-3483388d5990.png)
(Сам борг был на мостике и наблюдал за илитарной кафешкой через камеры)

#### Что должно было произойти
Синтет открывает консоль, выбирает камеру, пытается открыть/электризовать/болтировать шлюз и получает шиш.
#### Что произошло на самом деле
Синтет открывает консоль, выбирает камеру и успешно открывает/электризует/болтирует шлюз.

#### Как повторить
Стать боргом, найти консоль с камерами, зайти в нее,  клацнуть мышкой по двери.

**Comment by raduser** [comment]
Это не баг, это фича!

**Comment by Damirrus1** [comment]
Я бы не назвал это багом

**Comment by Lancer411** [comment]
Собственно, а баг ли это?

**Comment by dearprincesscelestia** [comment]
Каким местом это баг?

**Comment by Skyrull** [comment]
LADNO, ficha.

**Comment by Raschert0** [comment]
Но взаимодействие с кнопками через камеры нужно выпилить

**Comment by dearprincesscelestia** [comment]
И у ИИ тоже?

**Comment by Raschert0** [comment]
Только у боргов же. Иначе немного теряется смысл бластдура в ядре ИИ

**Comment by Skyrull** [comment]
Надо выпилить доступ к кнопке закрытия бластдуров на спутнике ИИ у боргов и все.

**Comment by ZVee** [comment]
Это баг же.

**Comment by Belfogor** [comment]
ЗВЕУБЕРИРУКИПРОЧЬ
