### ISSUE TITLE
Отсутствие логирования в VV при вводе реагентов в куклу

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#4577]
#### Подробное описание проблемы
При обкалывании из шприца любого реагента в куклу - оно не логирует что кукле были введены эти реагенты.
#### Что должно было произойти
В VV должно логироваться любое внедрение любых реагентов в куклу
#### Что произошло на самом деле
Оно не логируется
#### Как повторить
Обколоть куклу любым реагентом и посмотреть в VV. 
#### Дополнительная информация:
Обкалывал космо наркотиком, гиперцином и бикардином. Ничего не залогировалось. Гипоспрей СМО логировался

**Comment by TechCatOther** [comment]
Точно требуется любые реагенты? Нутрименты, алкоголь, все реакции, вода. Может требуется только часть? Например, при логировании нутриментов там будет лог просто заспамлен. Возможно требуется логирование только шприца и подобных добавить туда.
