### ISSUE TITLE
[proposal] Автоматичное включение паникбункера в ночное время суток. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#4580]
#### Подробное описание проблемы
Большая часть набегов происходит в ночное время суток, когда все здоровые и нормальные люди крепко спят и когда никого из администраторов нет в сети. 
#### Что произошло на самом деле
![f4dc4b689cd899915ce4cca6abd15da8cadd49f5_2_690x308](https://user-images.githubusercontent.com/12851693/73133022-bb65be00-402b-11ea-9a74-dab7675b0cf6.png)

**Comment by Belfogor** [comment]
@volas @SpaiR

**Comment by Sage4or** [comment]
Белфогор, прости за эту ситуацию, но ты сам развязал мне руки.....

**Comment by Tiarv** [comment]
Может быть, добавить возможность включать паникбункер через голосование?
