### ISSUE TITLE
С Велосити все еще можно сбежать на ЦК

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#4582]
#### Подробное описание проблемы
С помощью скафандра, гаечного ключа, горелки, двух металродов, двух плиток и раздатчика мусорных труб можно сбежать из ангара шаттла прибытия на Велосити и попасть прямо на ЦК (и обратно, увеличив количество металродов и плиток)
#### Что должно было произойти
Нельзя.
#### Что произошло на самом деле
Можно.
#### Как повторить
См. подробное описание
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/44546836/73137430-e4587400-4068-11ea-8ea7-1f7d32758370.png)

**Comment by FelixRuin** [comment]
Откуда ты достанешь два металрода, две плитки, скафандр и раздатчик мусорных труб на велосити?
А если это со станции, то мне кажется это точно нарушение правил

**Comment by Motzord** [comment]
> Откуда ты достанешь два металрода, две плитки, скафандр и раздатчик мусорных труб на велосити?
> А если это со станции, то мне кажется это точно нарушение правил

Смотри, шитспавнишься инженером и у тебя уже при спавне пояс с инструментами. Опа, две плитки и металрод в кармане. Далее ничего вообще не мешает слетать на станцию и залутать все остальное и тем же велосити шаттлом вернуться обратно

**Comment by TechCatOther** [comment]
Шатл не отлетит, если там остались мобы

**Comment by AndroBetel** [comment]
можно встать в шлюзе и шаттл улетит, а шлюз останется открытым.

**Comment by AndroBetel** [comment]
ну и да, на шаттле можно вернуться обратно, если его позовут с велосити...

**Comment by TechCatOther** [comment]
Спасибо за информацию. Вот это как раз эксплоит, что нужно закрыть.

**Comment by AndroBetel** [comment]
такой себе эксплоит - шлюз можно тупо взломать - открыть и заболтировать, это даже будет надежнее.

**Comment by SpaiR** [comment]
![image](https://user-images.githubusercontent.com/12721311/73138468-dd832e80-4073-11ea-969a-e7ebdbc1fbe3.png)
Есть отдельное правило для самых ушлых. Таких можно и нужно банить. Не вижу смысла учитывать 100500 способов заэксплоить игру, когда дело касается не игровой локации.

**Comment by volas** [comment]
была пара ПРов с обсуждениями, но до мержа не дошли.
Стоит запретить строительство на слое с трейтом цк, может еще что-то что я не помню.
