### ISSUE TITLE
Несоответствие халков

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#4589]
#### Подробное описание проблемы
При мутации в халка у унатха есть шанс стать чемпионом хонка, у клоуна- обычным халком (возможно мутация человека в годзиллу тоже не должна быть)
#### Что должно было произойти
Человек становится халком, унатх- зиллой, клоун- чемпионом хонка
#### Что произошло на самом деле
См. 1 пункт
#### Как повторить
Просто много пытаться получить ген халка

**Comment by FatFatFat1** [comment]
Так мб ты пока блоки шатал случайно активировал кламзи унатху?

**Comment by BiQndy** [comment]
Там с кламзи всегда делается большой Хонк

**Comment by FatFatFat1** [comment]
А когда ты клована шатал наоборот, случайно кламзи вырубил

**Comment by Motzord** [comment]
Не, у меня тоже был случай.

Мою куклу (онли хуман, ксеносы вбанены) шатали в генетике и сделали, внезапно зиллой

**Comment by AndroBetel** [comment]
intended, у ящеров если я не ошибаюсь просто выше шанс стать зиллой.

**Comment by BiQndy** [comment]
У человека шанс 19% стать зиллой и 81 халкой

**Comment by TechCatOther** [comment]
Это не баг, а фича. Любой живой моб с кламзи станет клованом-халком. Если это ящер то будет зилой только, если человек может быть зилой, может халком. Если требуется поменять фичу можно отписать тут.

**Comment by Akellazp** [comment]
> Это не баг, а фича. Любой живой моб с кламзи станет клованом-халком. Если это ящер то будет зилой только, если человек может быть зилой, может халком. Если требуется поменять фичу можно отписать тут.

Я ставал унатхом-чемпионом хонка, хотя такого не должно быть. Так же у клоуна должен быть 100% шанс стать чемпионом хонка, хотя

**Comment by Akellazp** [comment]
Случайно закрыл

**Comment by TechCatOther** [comment]
Тоесть хочешь поменять, что бы чемпионом хонка становились только люди-клоуны и больше никто?

**Comment by Akellazp** [comment]
> Тоесть хочешь поменять, что бы чемпионом хонка становились только люди-клоуны и больше никто? Назначеные ХоПом тоже?

По-моему эта фича с чемпионом хонка изначально была придумано специально для клоунов, но я вообще не об этом, а о том что чешуйчатый унатх вдруг смог стать кожаным хонкером

**Comment by TechCatOther** [comment]
Тут спрайт только для людей. Если бы были для остальных можно было бы поменять. Ну и в генах нету информации о профессии. Разве неуклюжий унтах не клоун?

**Comment by Akellazp** [comment]
> Тут спрайт только для людей. Если бы были для остальных можно было бы поменять. Ну и в генах нету информации о профессии. Разве неуклюжий унтах не клоун?

Так я небыл неуклюжим унатхом.

**Comment by TechCatOther** [comment]
Мутация была получена через инъекцию или в сканере?

**Comment by Akellazp** [comment]
Инъекцией
