### ISSUE TITLE
Унатх не может надеть Лизард бутсы

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#4590]
#### Подробное описание проблемы
Унатх не может обуть обувь, созданную специально для унатхов.
#### Что должно было произойти
Взял лизард бутсы, надел ризард бутсы
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/47355061/73257393-59908a00-41cc-11ea-93d2-4180bc646dc1.png)

#### Как повторить
Попробовать надеть лизард бутсы

**Comment by Sakuya-Izayoi** [comment]
Ксенорасы должны страдать
