### ISSUE TITLE
"Мирнороли" и негодование, которое часто вызывает данная аномалия [Proposal]

### ISSUE THREAD

**Issue by Sage4or** [TauCetiStation/TauCetiClassic#4592]
Бывает, что некоторые игроки решают играть по особенному, по мирному, помогая экипажу, решая его проблемы и так далее, тому подобное. Данные случаи вызывают негодования как у гостов, иногда даже у админов, так и у живых космонавтиков, которые находятся в раунде с таким недо-антагом.
![image](https://user-images.githubusercontent.com/59475362/73259765-87300000-41d9-11ea-9692-482e54f8620b.png)

У нас же, по сути, антагонист противостоит каждому члену экипажа, будь то тест сабжект, либо капитан, но "мирнороли" полностью безобразят саму суть антагониста, делая для людей, которые голосовали за ЛЮБОЙ режим, кроме эксты, как раз саму эту эксту, только с щитспавном в виде, например, мага с имбовой хиллкой, который отнимает работу у врачей, а все цели выполнил путем выпрашивания, либо же пока никто не видит 

Предлагаю: в правила антагонистов добавить пункт о запрете мирноролей.

**Comment by TechCatOther** [comment]
Я думаю это нужно сюда
https://github.com/TauCetiStation/Rules

**Comment by Sage4or** [comment]
> Я думаю это нужно сюда
> https://github.com/TauCetiStation/Rules

Предложил идею, не думаю, что с правилами и их изменениями через ПР должен заниматься игрок со стажем меньше полугода

**Comment by LudwigVonChesterfield** [comment]
Тебе сказали что это предложение не касается билда(механо-составляющей) игры, а касается правил сервера. И тебе вероятно стоит это предложение залить туда.

**Comment by TechCatOther** [comment]
Я имею в виду, что данный репозиторий предназначен для механа игры. Если хочется добавить идею по новым правилам можно это сделать через форум или в репозитории Rules так же через Issues.
