### ISSUE TITLE
[proposal] Добавить сообщение в игру при взаимодействии с ускорителем частиц.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#4598]
Увы, на реплее нет возможности видеть на какой стадии ускоритель частиц, поэтому приходится искать любителей выпускать сингу другими не самыми удобными методами. Сообщение о том что ускоритель включился и поднялся или опустился на уровень со стороны персонажа, облегчило бы поиск виновных.

**Comment by TechCatOther** [comment]
Ты имеешь в виду, что сообщение о изменении статуса было отправлено в чат пользователю дополнительно? Или что бы в логи писало о изменении статуса?

**Comment by Avatar4** [comment]
Одно из двух, не суть важно. Хотя первое предпочтительнее. Это поможет быстрее разбираться с помощью реплеев. Но тут уже проблема с синтетиками которые на расстоянии могут активировать.
