### ISSUE TITLE
В бан панели отсутствуют некоторые "профессии"

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#4599]
#### Подробное описание проблемы
В бан панели отсутствуют некоторые "профессии"
#### Что должно было произойти
Они должны там быть что бы можно было их забанить или разбанить игрокам не в сети
#### Что произошло на самом деле
Их там из за чего забанить могут только самые старшие админы.
#### Как повторить
Посмотреть на джобан панель отдельного игрока и просто на бан панель
#### Дополнительная информация:
В бан панели отсутствует: Дрон, обсерв, мышь, ксеноморф и диона. А еще антагХуд, но его все равно для игроков не включают, так что не нужен.

**Comment by Chip11-n** [comment]
Полагаю фикшено
