### ISSUE TITLE
Karton rapid fire

### ISSUE THREAD

**Issue by Prusski** [TauCetiStation/TauCetiClassic#4607]
#### Подробное описание проблемы
Картон можно бить без интервала между атаками.
#### Что должно было произойти
Ух, ударил картон, нужно секунду отдохнуть.
#### Что произошло на самом деле
https://www.youtube.com/watch?v=tqAiPk-VFAc&feature=youtu.be
#### Как повторить
https://www.youtube.com/watch?v=tqAiPk-VFAc&feature=youtu.be

**Comment by Tiarv** [comment]
Аналогично у зиппо, можно вайпать чат постоянно открывая и закрывая зажигалку без кд.

**Comment by LudwigVonChesterfield** [comment]
Не аналогично, это два совсем разных """бага""". У зажигалки нет КД на открывание-закрывание, тут нет КД на клик. Если считаешь что зажигалку надо починить - пж напиши ещё один багрепорт.

**Comment by LudwigVonChesterfield** [comment]
#2507

**Comment by LudwigVonChesterfield** [comment]
#2010
