### ISSUE TITLE
Блоб не может наносить урон халкам. Шахтёрский РИГ даёт практически неуязвимость к блобу.

### ISSUE THREAD

**Issue by Zap-zapper** [TauCetiStation/TauCetiClassic#4608]
-->

#### Подробное описание проблемы
Блоб не может наносить урон халкам и наносит мизерный урон тем кто надел шахтёрский риг. 
#### Что должно было произойти
Шахтёр не должен был в одиночку забить разросшегося блоба лопатой, когда он окружён им со всех тайлов. Халки должны были получить урон и умереть
#### Что произошло на самом деле
Шахтёр забил блоба лопатой будучи окружённым блобом толщиной в два тайла. Халки просто били блоба а тот им не мог нанести урон.
#### Как повторить
Попробовать атаковать блобом халка/зиллу.
#### Дополнительная информация:
У шахтёров на РИГе 90 мили защиты. Не знаю с какой целью это было сделано, но это позволяет блоба забить лопатой в одиночку, нося этот РИГ.

**Comment by FelixRuin** [comment]
90 мили защиты против враждебной фауны
и если я верню помню, то при помощи пластин голиафа можно вообще любому ригу прикрутить эту возможность

**Comment by Zap-zapper** [comment]
> 
> 
> 90 мили защиты против враждебной фауны
> и если я верню помню, то при помощи пластин голиафа можно вообще любому ригу прикрутить эту возможность

факт остаётся фактом, шахтёр несколько минут долбил лопатой блоба, причём будучи вглуби его. Он просто прорубался вглубь, в то время пока блоб атаковал его со всех сторон.

**Comment by TechCatOther** [comment]
Можно часть урона перенести с физического на другой тип. Это должно решить такую ситуацию

**Comment by Leshiy-ART** [comment]
Как вариант - удваивать урон если с целью соприкасается 3 тайла блоба, и утраивать если вокруг цели 4 тайла блоба.
Тогда проблема с шахтерским ригом думаю будет решена.

**Comment by FelixRuin** [comment]
шахтёрский риг с любой униформой у которой есть броня даёт 100 процентный резист к урону в ближнем бою
тут хоть в 1.000.000 урон будет, изменится ровным счётом ничего
