### ISSUE TITLE
[Proposal] Сделать некоторых таторов смертниками

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4610]
#### Подробное описание проблемы
У всех таторов для гринтекста нужно выполнить задание выжить (иногда даже на шатоле сбежать или вовсе угнать)
#### Что должно было произойти
Татор выполняет гринтекст жертвуя своей жизнью во славу синдиката, НТ несет убытки и татор как бы ВИН
#### Что произошло на самом деле
Татор проиграл, хоть и выпилил свои цели, переломал ебла всем главам и был убит ОБР
#### Дополнительная информация:
Задание с трусами капитана и прочих вещей которые нужно украсть можно не давать, последним пунктом в нотесах тогда будет не
n. Стейл аливе анд антил энд.
А
"Выполни задания любой ценой"

**Comment by TechCatOther** [comment]
А какие типы заданий разрешать с данным пунктом?

**Comment by Motzord** [comment]
> А какие типы заданий разрешать с данным пунктом?

Убить/искалечить/угнать шаттл

Больше на ум не приходит

**Comment by TechCatOther** [comment]
Это только приведет к тому, что такие триторы будут выводить другого игрока в начале смены и дальше устраивать ксочку на станции без заботы о самосохранении. Получится, что атнтаг сольется в течении первых 5-10 минут.

**Comment by Motzord** [comment]
> Это только приведет к тому, что такие триторы будут выводить другого игрока в начале смены и дальше устраивать ксочку на станции без заботы о самосохранении. Получится, что атнтаг сольется в течении первых 5-10 минут.

Это один из исходов. Возможно татор отыграет шахида или придумает более экзотичный способ ради выполнения цели, сейчас все таторы стелсово выполняют цели и прячутся по техам в КК с ризоном "А вдруг убьют/абыщут"
