### ISSUE TITLE
Рука-молот у генокрадов не ломает шкафчики

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4611]
#### Подробное описание проблемы
Рука молот не ломает шкафчики но ломает укрепленные стенки, шлюзы и вообще мощная штука.

Зато рука хлыст ломает
#### Что должно было произойти
Рука молот спокойно ломает шкафчики
#### Что произошло на самом деле
ЭЫЫЫ, Я ТОЛЬКО ЧТО ВЫБИЛ ШЛЮЗ , НО НИМОГУ СЛОМАТЬ ШКАФЧИК
#### Как повторить
Попробуйте при помощи руки молот надамажить шкаф

**Comment by Fluffy-510** [comment]
Больше не актуально
