### ISSUE TITLE
Муллиган не работает

### ISSUE THREAD

**Issue by Marselinel** [TauCetiStation/TauCetiClassic#4612]
#### Подробное описание проблемы
После покупки муллигана я вколола его себе. Но инъекция не повлияла ни на имя, ни на внешность.

#### Что должно было произойти
Внешность и имя персонажа должны были измениться.

#### Что произошло на самом деле
У персонажа не изменились внешность и имя.

#### Как повторить
Купить и вколоть себе муллиган.

#### Дополнительная информация

![IMG_20200131_163421_849](https://user-images.githubusercontent.com/51530205/73548687-e09e6600-4449-11ea-90c0-289d11b2d573.jpg)

**Comment by Dominig12** [comment]
Проверено, действительно не работает, и уже давно
