### ISSUE TITLE
Пинпоинтер не может обнаружить местоположение активного ИИ, пока он является ядром

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4613]
#### Подробное описание проблемы
ИИ будучи малфом может спрятаться в любой заднице за стенками, и быть неуязвимым, пинпоинтер должен решать эту проблему, но не решает
#### Что должно было произойти
Описано выше
#### Что произошло на самом деле
ИИ малф в 8 стенках далеко в космосе хехает насчет тупых людей
#### Как повторить
Малф режим, малф спрятался, берите пинпоинтер и разочаруйтесь
#### Дополнительная информация:
Это какая то херня

**Comment by GermanSUS** [comment]
Да, последний малф куда то убежал и мы его не могли найти, я думал он на астероиде, но там не было его, решил бежать в телесало на других слоях искать, увы не нашел ни там ни там, пинпоинтер не работал.

**Comment by Sakuya-Izayoi** [comment]
Пинпоинтер уже показывает на ИИ #6582
