### ISSUE TITLE
[Proposal] Простой бафф блоба.

### ISSUE THREAD

**Issue by Prusski** [TauCetiStation/TauCetiClassic#4618]
Я предлагаю два пукта, которые могут значительно облегчить жизнь блобу в условиях постоянной борьбы с экипажем.

**I.** БЛОБ не способен адекватно противостоять человеку в шахтерском риге, так как тот имеет ультимативный резист к урону, наносимому БЛОБом, что приводит к возможности шахтера спокойно пробиться в ядро и забить БЛОБа лопатой без каких-либо сложностей.

Я собственно предлагаю раздробить урон, наносимый самим БЛОБом из 100% физического на:
33% Ожоги
33% Токсичный
33% Физический.
1% Моральный

Да, возможно это уменьшит урон, наносимый синтетическим единицам, но у нас ведь едкая размножающаяся биологически активная субстанция, а не боксер, способный бить только апперкотом.

**II.** Каждое созданное мини-ядро БЛОБа будет увеличивать максимальный лимит энергии БЛОБа на 5 единиц. Это даст блобу возможность ставить больше полезных "модулей" за раз при достаточном размере.

Собственно чем больше будет организм - тем больше у него потенциала к росту, звучит вполне логично.

**Comment by LudwigVonChesterfield** [comment]
Что такое моральный урон?

**Comment by AndroBetel** [comment]
это когда тебе в чат большим красным текстом пишут "лалка, не умеешь играть, удаляй игру"

**Comment by LudwigVonChesterfield** [comment]
так это токсичный
