### ISSUE TITLE
Убивает давлением и начинаешь задыхаться если заползти под решетку между карго и шахтеров

### ISSUE THREAD

**Issue by Miracler112** [TauCetiStation/TauCetiClassic#462]
#### Подробное описание проблемы
В карго когда заползаешь кравлом под решетку, где офис шахтеров, начинает убивать низким давлением, а если встать, то начинаешь задыхаться
#### Что должно было произойти
Не должно убивать давлением и воздух в тайле должен быть
#### Что произошло на самом деле
Нету воздуха как и давления, начинаешь умирать. когда туда заползаешь
#### Как повторить
Заползти под решетку, которая ведет в офис шахтеров

**Comment by Damirrus1** [comment]
Правильно, нечего залезать под решеточку.

**Comment by dearprincesscelestia** [comment]
Не фиксить.

**Comment by ZVee** [comment]
Что, почему закрыл?
