### ISSUE TITLE
Сон после перезахода за позитронные мозги.

### ISSUE THREAD

**Issue by OfficerSoftheart** [TauCetiStation/TauCetiClassic#4620]
#### Подробное описание проблемы
Вы позитронный мозг. 
Перезаходите в раунд.
Вы ничего не слышите, себя тоже. 

#### Что должно было произойти
Вы должны были видеть чат, и видеть бинарный канал.

#### Что произошло на самом деле
Вы спите за позитронку.
#### Как повторить
Зайти за позитронный мозг, перезайти в раунд. Вы спите.
У меня такая проблема была, когда меня взорвали, перезашел в раунд, ничего не слышу за позитронку.
#### Дополнительная информация:
-

**Comment by Sage4or** [comment]
Такое же происходит и играя за симпл мобов, за всяких големов из культа там и тд

**Comment by LudwigVonChesterfield** [comment]
#615
