### ISSUE TITLE
Добавить инж боргу в инвентарь универсальный краситель и развертываемые барьеры [Proposal] 

### ISSUE THREAD

**Issue by Sage4or** [TauCetiStation/TauCetiClassic#4624]
Поможет боргу лучше чинить разгермы, перекрашивать полы

**Comment by Sakuya-Izayoi** [comment]
А кнопку которая все повреждения станции чинит ему не добавить?!

**Comment by Zmey25** [comment]
И выпилить профу инженеров.

**Comment by Sage4or** [comment]
Барьеры и красители лишь минорные изменения, которые игру более удобной для всех сделает, не только для боргов
