### ISSUE TITLE
Перекраска КПК в клоунский не делает его скользким

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#4630]
#### Подробное описание проблемы
Перекраска КПК в клоунский не делает его скользким

#### Что должно было произойти
Любой КПК покрашенный в клоунский должен быть скользким.

#### Что произошло на самом деле
КПК скользким не становится

#### Как повторить
Перекрасить КПК в That's PDA painter

#### Дополнительная информация:
До перехода на компоненты работало. Полагаю, проблема в том, что компонент накидывается только при атом_ините. Возможен ещё баг когда клоунский КПК остаётся скользким после перекраски.

**Comment by LudwigVonChesterfield** [comment]
Это правда, он остаётся.
