### ISSUE TITLE
Квирк Stress Eater убивает магов жиром

### ISSUE THREAD

**Issue by Grox103FM** [TauCetiStation/TauCetiClassic#4636]
#### Подробное описание проблемы
Решил использовать в одном из раундов оверхил от третьего лечения мага, имея при себе квирк Stress eater.

#### Что должно было произойти

Маг оверхильнулся и пошёл танковать своей подтянутой стройной фигурой

#### Что произошло на самом деле

Маг заплыл жиром в техах , после чего его повязали СБшники т.к. мантия с него от жира слетела.

#### Как повторить

Поставить кукле квирк stress eater и получить оверхил от заклинания мага

#### Дополнительная информация:

Баг, который руинит немало магов-механобобов.

**Comment by Belfogor** [comment]
Для кодеров, которые потом будут это читать. При наличие квирка Stress eater и использование хилки мага, нутриенты начинают капать каждый тик по единице.

**Comment by Dominig12** [comment]
Для кодеров х2. Предположительно отрицательный урон накидывает нутрименты точно так же, как просто урон их сбрасывает
