### ISSUE TITLE
Кража женского варианта формы главы

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#4640]
#### Подробное описание проблемы
Было задание на кражу формы капитана. В шкафчике была только женская ферсия (dressed uniform). Взял ее. В конце гринтекст не засчитался.
#### Что должно было произойти
Гринтекст
#### Что произошло на самом деле
Редтекст
#### Как повторить
Украсть dressed uniform вместо обычной формы

**Comment by Sakuya-Izayoi** [comment]
By design

**Comment by Venngedi** [comment]
#4640 Цель на форму главы удалена, так что ишшуй можно закрыть
