### ISSUE TITLE
Бенчы на маршрутке с велосити можно крутить

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#465]
#### Подробное описание проблемы
Бенчы с шаттла велосити можно крутить как стулья. 
#### Что должно было произойти
Бенчы нельзя крутить.
#### Что произошло на самом деле
Бенчы можно крутить.
#### Как повторить
Найти бенч, покрутить его.
#### Дополнительная информация:
![slomanybench](https://cloud.githubusercontent.com/assets/20542000/17768307/4224c0a4-6555-11e6-9ef2-17bea35dfd59.png)

Спрайтов направленных на запад и восток нет.

![bench2](https://cloud.githubusercontent.com/assets/20542000/17768395/9ca97560-6555-11e6-809a-0d0e45abcc20.png)

**Comment by Miracler112** [comment]
#466

**Comment by Skyrull** [comment]
Починено.
