### ISSUE TITLE
Дело о пропаже спрайтов автоиньекторов из Space First-Aid kit

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#4654]
#### Подробное описание проблемы
Спрайты автоиньекторов пропали по показаниям игрока на ксеноархеологе
#### Что должно было произойти
Спрайты
#### Что произошло на самом деле
Нет спрайтов
#### Как повторить
Открыть мини-аптечку для космоса и проверить не пропали ли спрайты

**Comment by Ahion** [comment]
Спасибо за issue, поправил.
