### ISSUE TITLE
Не исчезает Power Alarm в помещении слева от инженерки (Assembly Line)

### ISSUE THREAD

**Issue by kildjen** [TauCetiStation/TauCetiClassic#4655]
#### Подробное описание проблемы
В Assembly Line после установки АПЦ и подключении к общей энергосети появляется power alarm, который никак не убирается. Переустановка АПЦ, переустановка АПЦ в другом месте, переподключение проводки, перезапуск АПЦ не решают проблему. АПЦ заряжен на 100%, горит зелёным цветом, но тревога не убирается.
![image](https://user-images.githubusercontent.com/54710369/73933880-745eaf00-48ee-11ea-87a8-02a7a7615586.png)
![image](https://user-images.githubusercontent.com/54710369/73933901-7f194400-48ee-11ea-84ce-24d056d654b9.png)
![image](https://user-images.githubusercontent.com/54710369/73933858-67da5680-48ee-11ea-98cd-8e5f0c07063e.png)
![image](https://user-images.githubusercontent.com/54710369/73933955-98ba8b80-48ee-11ea-9fea-88b0753394af.png)
![image](https://user-images.githubusercontent.com/54710369/73933979-a3752080-48ee-11ea-900f-95fed3b865e4.png)

#### Что должно было произойти
АПЦ установлен, питание подведено, тревоги нет.
#### Что произошло на самом деле
Консоль сообщает о наличии Power Alarm.
#### Как повторить
Установить АПЦ в Assembly Line и подключить к питанию.

**Comment by volas** [comment]
Возможно фикшено в #4652
Там вообще никакие тревоги не сбрасывались. Но я только рантайм смотрел.

**Comment by kildjen** [comment]
К сожалению, все новые АПЦ всё ещё висят в алярмах и не хотят пропадать.

**Comment by pss88** [comment]
Причина та же, что и в #6026
