### ISSUE TITLE
А время не капает

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#4662]
#### Подробное описание проблемы
Your ingame age не капает, новички плакают
#### Что должно было произойти
Your ingame age капает, новички не плакают
#### Что произошло на самом деле
Your ingame age не капает, новички плакают
#### Как повторить
Status > Your ingame age > Поиграть минут 10 > Status > Your ingame age > Плакать (если ты новичок)
#### Дополнительная информация:
Не-новичкам можно не плакать

**Comment by SpaiR** [comment]
Сервер не рестартился, поэтому до не долетела обнова. Сейчас все норм.
