### ISSUE TITLE
[map] Очень тактическое расположение кабинета РД

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4669]
#### Подробное описание проблемы
Кабинет ГЛАВЫ ИССЛЕДОВАНИЙ распологается очень тактично. С правой стороны форонная, с юга склад канистр с плазмой. Даже не знаю, что может пойти не так.
#### Что должно было произойти
РД не переживает за свою жопу отделенную от смерти какой-то там стеной из пластали
#### Что произошло на самом деле
Что-то пошло не так
![image](https://user-images.githubusercontent.com/45365635/74059705-35fde880-49f1-11ea-9935-b86bf130d543.png)

#### Как повторить
Посмотреть на карту

**Comment by AndroBetel** [comment]
это система сдерживания лицехвата если что

**Comment by TechCatOther** [comment]
Станция по изучению форона. Глава исследований рядом с важнейшем отделом, все в порядке же.

**Comment by Loratron** [comment]
Кабинет ГСБ располагается вплотную к техам, через которые можно легко попасть внутрь любому ассистенту с минутой свободного времени и инструментами. Кабинет СМО развивает эту же идею и выходит на совершенно новый уровень - вплотную к нему находится старая химия, в которой можно сварить термит и тут же прожечь им стену, не отходя от кассы, как говорится. Про кабинет СЕ вообще молчу, находится напротив самого опасного места на  станции.

В общем, что бы решить все эти проблемы, предлагаю просто выпилить глав и их кабинеты с билда, всё равно это простые ассистенты с доступом на мостик.

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/novosti-mapredaktorov/33242/40
