### ISSUE TITLE
Консоли телекомов

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#468]
#### Подробное описание проблемы

Нет возможности открыть консоли на телекомах, не за персонажа не за борга и ИИ

#### Что должно было произойти

Смог открыть консоль и настроившись на волну прослушивать её(конечно же синдикота)

#### Что произошло на самом деле

Не открывается меню консоли

#### Как повторить

Зайти за борга, хумана, ИИ попробывать открыть консоли

**Comment by ZVee** [comment]
Они отключены из-за бага создающего массивный лаг, и не факт что будет исправление.

**Comment by Olt1771** [comment]
Эх, а раньше можно было прослушивать ролей, печально
