### ISSUE TITLE
Доступ парамедиков в карго

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#4680]
#### Подробное описание проблемы
Парамедики почему-то имеют доступ в карго.

#### Что должно было произойти
Парамедики как и все остальные нормальные люди не должны иметь доступа к чужим отсекам.

#### Что произошло на самом деле
Наглый кот забегает в карго игнорируя находящихся на станции грузчиков, печатает себе ништяки или даже взламывает автомат.

#### Как повторить
Зайти в раунд на первом сервере.

#### Дополнительная информация:
Как вариант можно было бы выпилить котов.

**Comment by WallShrabnic** [comment]
Учитывая что в мусорку регулярно кого-то пихают, вполне оправдано. Если жалоба на конкретного ксеноса - то пиши жалобу на форуме

**Comment by Sakuya-Izayoi** [comment]
> Учитывая что в мусорку регулярно кого-то пихают, вполне оправдано. Если жалоба на конкретного ксеноса - то пиши жалобу на форуме

Только доступ у парамедиков ограничивается не мусоркой.

**Comment by Tiarv** [comment]
> Только доступ у парамедиков ограничивается не мусоркой.
Как парамедику попасть в мусорку минуя комнату с автолатом? WAIT. OH SHI~

**Comment by Sage4or** [comment]
> > Учитывая что в мусорку регулярно кого-то пихают, вполне оправдано. Если жалоба на конкретного ксеноса - то пиши жалобу на форуме
> 
> Только доступ у парамедиков ограничивается не мусоркой.

а у них еще даже и в бриг доступ есть! представь себе, могут взломать камеру своего кооп дружка и вытащить его на свободу!

**Comment by Akellazp** [comment]
У них доступ в карго и вообще базовый доступ во все отсеки потому что они....
...парамедики и им нужен доступ в каждый отсек чтобы не стоять по пол часа и кричать "ИИ АТКРОЙ ЧИЛАВИК УМИРАЕТ!!!"?

**Comment by Venngedi** [comment]
#11567 Закройте.
