### ISSUE TITLE
Мьют менторхелпа отнимает ахелп

### ISSUE THREAD

**Issue by Nettledash** [TauCetiStation/TauCetiClassic#4685]
#### Подробное описание проблемы
Мьют менторхелпа отключает возможность отвечать в ПМки админхелпа
#### Что должно было произойти
Мьют должен быть только на менторхелп
#### Что произошло на самом деле
Мьют распространяется и на админхелп
#### Как повторить
Замьютить менторхелп, попробовать воспользоваться ахелпом/ответить на ПМку
#### Дополнительная информация:
Это все

**Comment by Sakuya-Izayoi** [comment]
Не получайте муты. :confused:

**Comment by T6751** [comment]
Resolved by https://github.com/TauCetiStation/TauCetiClassic/pull/7319
