### ISSUE TITLE
[Proposal] Оксид форона

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#4688]
Предлагаю добавить такой газ как диоксид форона ака PhO2. Собственно, единственное его назначение это быть продуктом сгорания форона, потому что на данный момент при сгорании форона образовывается CO2, что никакого смысла не несёт. Можно придумать ему смешные фичи вроде токслосса или галюнов, подобные предложения пишите здесь, в ишью.

**Comment by LudwigVonChesterfield** [comment]
форон вроде бы сам органический, а не отдельный элемент

**Comment by LudwigVonChesterfield** [comment]
#1286

**Comment by rarytech** [comment]
после сгорания форона в округе обычно уже нет выживших, чтобы оценить смешные фичи

**Comment by Motzord** [comment]
Тогда уж рандомизировать оксид форона, чтобы форонщику было чем заняться.
>сжечь, охладить, накачать в баллон и посмотреть на тестовике че он делает. Возможно чет смешное и полезное
