### ISSUE TITLE
Оповещение от ЦК о трейторах

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#469]
#### Подробное описание проблемы
Приходит оповещение о трейторах, и пишется там
Someone Chief Medical Officer
СМО один на станции, он не получает дополнительные телекристаллы
#### Что должно было произойти
СМО должен получить дополнительные телекристаллы
И должно вместо Someone быть имя СМО
#### Что произошло на самом деле
Someone Chief Medical Officer
#### Как повторить
Стать трейтором главой, получить оповещение

**Comment by dearprincesscelestia** [comment]
Про отсутствие имени менять не надо, это же "КОЕ-КТО, КАКОЙ-ТО СМО, МЫ НЕ ЗНАЕМ  КАКОЙ ИМЕННО, НО КАКОЙ-ТО ИЗ ВАШИХ, УЖ ПРОСТИТЕ, РАБОТАЕТ НА СИНДИКОТОВ".

**Comment by Olt1771** [comment]
Это может быть с любой одиночной профой, ВОТ!
