### ISSUE TITLE
Глобальный рефакторинг

### ISSUE THREAD

**Issue by TechCatOther** [TauCetiStation/TauCetiClassic#4690]
### Описание
Общая заметка для глобальных измениний в коде, затрагивающие множество файлов. 

Предлагаю мейнтейнерам здесь добавить информацию о том, что потребуется изменить и может вызывать множественные конфликты при мерже с другими ПР. Затем после переваливания замен, например, за 10 одним ПР провести замену. Это решит вопрос с постоянными решениями конфликтов в ПРах при постепенных внедрениях.

---------------------------
### Готовые к замене
- [ ] istype(src, ...)
- [x] stat || paralysis || stunned || weakened || restrained
- [ ] zone_sel.selecting
- [x] << browse(

####  istype(src, ...)
Полиморфизм
#### stat || paralysis || stunned || weakened || restrained
Перевести в incapacitated(), исключая оптимизацию кода
#### zone_sel.selecting
Перевести на get_targetzone из #4134 
```
/mob/living/get_targetzone()
	if(zone_sel)
		return zone_sel.selecting
	return pick(TARGET_ZONE_ALL)
```
#### << browse(
Заменить вызовы `<< browse()`, если не используется nano на датум /datum/browser

**Comment by FelixRuin** [comment]
а может лучше просто поставить теги для такой хурмы и не придумывать колесо опять? Ишус то может уползти, а по тегу будет удобно посмотреть сколько и чего

**Comment by TechCatOther** [comment]
С тегом рефактор можно сказать нету других issue. Не совсем понятно куда эти теги потом закреплять, либо на каждый вариант делать свою issue.  Сделано одним issue из расчета на то, что одним ПР будет закрыт.

Как альтернатива можно использовать milestone для такого.

**Comment by TechCatOther** [comment]
Заменен майлстуном https://github.com/TauCetiStation/TauCetiClassic/milestone/5
