### ISSUE TITLE
Дропподы ЕРТ не стартуют. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#4693]
#### Подробное описание проблемы
Все работает до тех пор, пока не нажимаешь кнопкку старт. Дроппод намертво не желает лететь дальше. 

Проблема только лишь с теми дропподами, которые находятся в ангаре ЕРТ. Не работают только они, если этот же подкласс дроппода заспавнит он полетит. 

#### Дополнительная информация:
Какая-та магия

**Comment by Motzord** [comment]
Не воспроизводится. Дропподы ЕРТ успешно стартуют

**Comment by Motzord** [comment]
Все стартует, закройте уже это ишью
