### ISSUE TITLE
[Proposal]Киборг не может разобрать консоль Identification Computer.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#4698]
#### Подробное описание проблемы
Киборг не может разобрать консоль Identification Computer.
#### Что должно было произойти
Он должен быть способен ее разобрать.
#### Что произошло на самом деле
Инженерному киборгу пишет "It's too complicated for you."
#### Дополнительная информация:
Режим был малф

**Comment by TechCatOther** [comment]
Это фича для всех компьютеров
```
	if(!ishuman(user))
		to_chat(user, "<span class='warning'>It's too complicated for you.</span>")
		return
```

**Comment by Zmey25** [comment]
Где баг?

**Comment by Sakuya-Izayoi** [comment]
Бага нет. Нечего консоли разбирать.

**Comment by Avatar4** [comment]
> Это фича для всех компьютеров. Можно добавить исключение для боргов. Панель их управления тоже разбираемую делать?
> 
> ```
> 	if(!ishuman(user))
> 		to_chat(user, "<span class='warning'>It's too complicated for you.</span>")
> 		return
> ```

В смысле фича? как тогда их разбирать инженерам и прочим?

**Comment by TechCatOther** [comment]
Инженеры смогу разобрать, но борги-инженеры нет.

**Comment by Avatar4** [comment]
Ну так-то, это сильно осложняет жизнь малфам или триторам ИИ. Лучше бы вернуть такую возможность.

**Comment by ViDLiathan** [comment]
С каких пор борги не могут разбирать консоли? Где-то было обсуждение? Что я пропустил?
И почему они вообще не должны мочь разбирать консоли?

**Comment by TechCatOther** [comment]
Начиная отсюда https://github.com/TauCetiStation/TauCetiClassic/commit/533a691b7c1af099a3535253930f0c09491fc2f2

**Comment by Sage4or** [comment]
> С каких пор борги не могут разбирать консоли? Где-то было обсуждение? Что я пропустил?
> И почему они вообще не должны мочь разбирать консоли?

Мне кажется, ради реализма, не думаю, что сомнительно поворотливая машина сможет собрать пекарню тебе

**Comment by ViDLiathan** [comment]
> 
> Мне кажется, ради реализма, не думаю, что сомнительно поворотливая машина сможет собрать пекарню тебе

У специализированных боргов есть манипуляторы для работы с платами и мелкими деталями. Инженерный, научный борги и дрон вполне себе могут собрать\разобрать подобную технику.

**Comment by Sage4or** [comment]
> > Мне кажется, ради реализма, не думаю, что сомнительно поворотливая машина сможет собрать пекарню тебе
> 
> У специализированных боргов есть манипуляторы для работы с платами и мелкими деталями. Инженерный, научный борги и дрон вполне себе могут собрать\разобрать подобную технику.

тогда почему они не способны отстегнуть человека от стула? :с
