### ISSUE TITLE
[Port request] Абуз телепортации в стену.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#4706]
#### Подробное описание проблемы
Маги и другие существа способны телепортироваться в стену и подобные участки. В результате чего, грязно абузят данные возможности. Тоже самое можно делать с помощью предметов типа ручного телепортера.
#### Что должно было произойти
То ли на ТГ то ли в Бей есть возможность, которая не дает вытворять подобные манипуляции (скажите точно, кто там за них шарит). В идеале, хорошо бы что бы с таких мест выкидывало из стены, аварийных затворок и прочего. А если выкидывать некуда - то тоже какие-нибудь неприятные последствия (гиб?).
#### Что произошло на самом деле
Маги и подобные им существа абузят это с целью легкого уничтожения ИИ через стену. Выпил игроков посредством стана и расстрела пока в них никакие прожектайлы не могут попасть. Всякие умники изменяют законы ИИ через стену в аплоуде и прочее.
#### Как повторить
Телепортироваться в стену джаунтом или ручным телепортом.

**Comment by volas** [comment]
Можно гибать конечности, с каким-то шансом самого персонажа. Я не помню где это уже было, вероятно уже в любом другом билде.

**Comment by ViDLiathan** [comment]
В стену еще конструкты и шедоулинги могут телепортироваться

**Comment by Pivo24** [comment]
Выкидывание из стены/створки с последующим кноком и нанесением небольшого урона, как в случае с закрывающимися шлюзами.

И заодно получится фича, позволяющая малфу убивать экипаж створками.

**Comment by dred1792** [comment]
Ну, если я всё верно понял, то нужно тащить [это](https://github.com/Baystation12/Baystation12/blob/5d3c65942ccdfd9416c3be424f1b7bdaf6b9c418/code/modules/spells/targeted/ethereal_jaunt.dm#L104) и [этот вот](https://github.com/Baystation12/Baystation12/blob/dc3c68e489bef17a28652e0f210f9468a33ac547/code/game/turfs/turf.dm#L266) прок.

**Comment by 4310V343k** [comment]
Или переделать комнату с ядром?

**Comment by Grox103FM** [comment]
Лучше переделать комнату с ядром и аплоудом. В чём проблема передвинуть ии и консоль в простреливаемую зону? Да и к тому же, смену законов я понимаю, но убийство ИИ в тот же культ это норма. Как ещё бороться с этой ерундой которая качает воздух и болтирует двери? По поводу урона или гиба конечностей идея плохая,ведь те же тенелинги бегают с огромной скоростью по тесным техам. Промахиваются на тайл-лишаются ноги/оставляют кровь и их находят по пинпоинтеру. Такое себе. Просто урон тоже ужасно ведь тот же дух вечно носится в шифте и тоже случайно может вылететь в стенке со своим мизерным хп и получить урон который как правило лечить некому.

**Comment by Zmey25** [comment]
А в чем проблема следить куда ты приземляешься?

**Comment by Grox103FM** [comment]
В том что ты летишь на максимальные расстояния, а не за стену. Если бы ты двигался тайлов от силы на 10, но ты двигаешься на максимум тайлов и не всегда точно знаешь как долго ещё будешь шифтить.

**Comment by Zmey25** [comment]
Значит следи, как долго ты в шифте. Перелёт через стены (а за магуса ещё и с маленьким кд) это имба в наших реалиях, а ты ещё жалуешься, что тебя хотят заставить следить за своей куклой. Если ты хоть раз пытался словить таких персонажей, то должен понимать, что такое баланс.

**Comment by Grox103FM** [comment]
На случай шифтеров есть термалки, пинпоинтер и банальные вещи которые просто убивают, наподобие повреждения органов/малого нерегенерируемого хп голема/ваншота лингов. всё сбалансированно

**Comment by SpaiR** [comment]
#4732
