### ISSUE TITLE
Хамелион-Прожектор, будучи включенным,  исчезает при падении

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#471]
#### Подробное описание проблемы
Активировав Хамелеон-Прожектор, а потом нажав на кнопочку Crawl, маскировка спадает, а само устройство исчезает.
#### Что должно было произойти
Кукла падает, маскировка снимается, Хамелеон-Прожектор дропается.
#### Что произошло на самом деле
Кукла падает, маскировка снимается, Хамелеон-Прожектор пропадает без следа.
#### Как повторить
Взять Хамелеон-Прожектор, активировать его, упасть.

**Comment by Raschert0** [comment]
Я думаю, это фича

**Comment by dearprincesscelestia** [comment]
Потому что само обязательное выпускание предметов из рук при кравле - жуткая игровая условность.

По хорошему, ему бы "пропадать", но не совсем, а маскироваться под предмет, который выбран в маскировке. А человеку терять маскировку, да.
