### ISSUE TITLE
Киборг получает стан во время полётов на шаттле

### ISSUE THREAD

**Issue by PirogSema** [TauCetiStation/TauCetiClassic#4710]
#### Подробное описание проблемы
При полёте на шаттле на астероид борг отключается (не может двигаться и слышать) на несколько секунд, вероятно, из-за того, что не пристегнулся, что невозможно осуществить.
#### Что должно было произойти
Киборг не должен был отключиться.
#### Что произошло на самом деле
Борг отключился и не мог двигаться и слышать.
#### Как повторить
Зайти на шаттл на астероид и полететь куда-нибудь.
#### Дополнительная информация:
Нет

**Comment by TechCatOther** [comment]
Вроде правили же в #4392 
Возможно не помогло.

**Comment by PirogSema** [comment]
До сих пор есть эта проблема. Тот фикс помог только с тем, что борг теперь не влетает в стенку и не получает урон на шаттле, но стан всё ещё остался.
