### ISSUE TITLE
Кнопка массового усыпления есть, а массового пробуждения от нее нет

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4713]
#### Подробное описание проблемы
Есть кнопка массового усыпления, но нет кнопки массовго пробуждения. Масс модифай не работает
#### Что должно было произойти
Есть возможность усыпить и пробудить
#### Что произошло на самом деле
Такой возможности нет
#### Как повторить
Провести ивент где надо усыпить всю станцию, а потом вручную каждого пробуждать

**Comment by LudwigVonChesterfield** [comment]
Special Verbs --> Apply Mass Effect --> /datum/status_efffect/sleeping --> duration = 0

или надо быстрее?
