### ISSUE TITLE
Неккоректное отображение эффектов при вскрытии 

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4714]
#### Подробное описание проблемы
Заставил подышать куклу фороном при всрктии обнаружилось, что она внезапно попала в радиационный пояс
#### Что должно было произойти
Написано что кукла отравилась фороном
#### Что произошло на самом деле
Написано что кукла побывала в радицации
#### Как повторить
Поиграть с куклой ради отчетов о вскрытии
#### Дополнительная информация:
Возможно кукла прошла через радиационный пояс, потому что это была кукла из генетики и я не прав.

**Comment by KIBORG04** [comment]
Повторить не смог, кукла дышала всю жизнь фороном и в отчете написано тоже самое 
"Trace Chemicals: 
Toxin"
