### ISSUE TITLE
Фейсхагеры вполне себе хагают дион (и наверное телевизоров)

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4722]
#### Подробное описание проблемы
Фейсхагеры запросто заражают дион и энтов
#### Что должно было произойти
Нельзя
#### Что произошло на самом деле
Проломил грудак дионе
#### Как повторить
Заставьте бетеля провести ивонт

**Comment by UDaV73rus** [comment]
Был энтом, куча хаггеров пытались налипнуть, но не могли

**Comment by Motzord** [comment]
> Был энтом, куча хаггеров пытались налипнуть, но не могли

Налип на ту самую диону, которую ты потм держал в руках, вполне себе вылез лярвой
