### ISSUE TITLE
Не засчитывание украденных вещей

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#4730]
#### Подробное описание проблемы
Если ты по заданию украл предмет, но по завершению раунда он у тебя не в рюкзаке/кармане/одет на тебя, то задание на засчитывается
#### Что должно было произойти
Украл *вещьнейм*, положил в имплант/халат/разгрузку/в жёпу и задание засчитало
#### Что произошло на самом деле
Сделал все что описано выше, но задание не засчиталось
#### Как повторить
Сделать то, что написано выше

**Comment by TechCatOther** [comment]
Duplicate of #1249
