### ISSUE TITLE
Ломаем консоль управления счетами за ОБР

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#4737]
#### Подробное описание проблемы
Можно сломать и сделать неоткрываемой консоль управления счетами. 
#### Что должно было произойти
Этого быть не должно
#### Что произошло на самом деле
Можно сломать!
#### Как повторить
Заходим за ОБР, кабанчиком бежим к консоли управления деньгами, вводим достаточно большое число (точное не помню, но нескольких миллиардов/триллионов будет достаточно), консоль ломается и не открывается
#### Дополнительная информация:
Желательно решить эту проблему, поставив ограничение на консоль, а не просто вырезав доступ у ОБР

**Comment by DctrMM** [comment]
так там же барьеры вроде стоять должны не?

**Comment by WallShrabnic** [comment]
> так там же барьеры вроде стоять должны не?

Я про станционную
