### ISSUE TITLE
Полные шлема (РИГи, биохуды и др.) не мешают закрытию рта

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#474]
#### Подробное описание проблемы:
Куклы, которые носят шлема скафандров/РИГов, шапки костюмов рад/биозащиты не защищены от закрытия рта через агрессивный граб.
#### Что должно было произойти:
Космонавту, у которого на голове шлем от скафандра, нельзя закрыть рот.
#### Что произошло на самом деле:
Космонавту, у которого на голове шлем от скафандра, можно закрыть рот.
#### Как повторить:
Надеть на хумана закрытый шлем, взять его в двойной граб, выбрать на кукле интентов рот.
#### Дополнительная информация:
Реквестирую впил [етого](https://github.com/TauCetiStation/TauCetiClassic/issues/70)

**Comment by Uvash** [comment]
А ещё отрезанию головы через вскрытие горла

**Comment by Skyrull** [comment]
Да, вскрытие горла игнорит броню на голове (к шлемам это логично, а к скафандрам - не очень)
