### ISSUE TITLE
[proposal] Подпилить в Secret логирование огня

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4754]
#### Подробное описание проблемы
Видишь пожар в коридоре
@
Хошь посмотреть кто его устроил
@
Лог с fire_started где-то в ебенях и утерян
@ 
С лицом лягушки ищешь по отпечаткам/реплею
#### Что должно было произойти
Открыл секрет панель, нашел увидел  забанил
#### Что произошло на самом деле
Не нашел, не забанил, коридор сгорел
#### Как повторить
Попробуйте найти внезапный пожар и проебать нужный лог

**Comment by Sakuya-Izayoi** [comment]
use Ctrl+F
