### ISSUE TITLE
[proposal] Добавить в сплавы фороновое стекло

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4759]
#### Подробное описание проблемы
Фороновое стекло можно получить лишь при помощи криворуких археологов которые притащат осколки, или разобрать два окна на станции в форонной
#### Что должно было произойти
Шахтеры приносят фороновое стекло и все дружно строят суперматерию/укрепляют сжигатель.

(Да хотя бы пусть в карго заказывается стаком и в ящике)
#### Что произошло на самом деле
;Ало цк, мы стекло фороновое хотим
#### Как повторить
Попытайтесь найти фороновое стекло без археологов и вандализма

**Comment by Motzord** [comment]
А еще теленаука может помочь, однако...

**Comment by Sakuya-Izayoi** [comment]
balance...
