### ISSUE TITLE
Без доступа к аптечке в ксенобио

### ISSUE THREAD

**Issue by BiQndy** [TauCetiStation/TauCetiClassic#4760]
#### Подробное описание проблемы
При попытке взять лекарства или бинты в ксенобио на стене говорит ассетс динайд, хотя айди ксенобиолога на масте
#### Что должно было произойти
![dreamseeker_kxQuGLJopL](https://user-images.githubusercontent.com/43725089/75378922-9cd23b80-58e5-11ea-901a-7c71b6c57f06.png)

#### Что произошло на самом деле
![dreamseeker_UCimqLwKry](https://user-images.githubusercontent.com/43725089/75378949-a6f43a00-58e5-11ea-9780-1e2f69589779.png)

#### Как повторить
Быть ксенобиологом и заюзать настенную аптечку

**Comment by Akellazp** [comment]
Они так же не выдают ничего на шатле отбытия, возможно даже везде так
