### ISSUE TITLE
При открытии/закрытии шлюза спрайт не синхронизирован со звуком

### ISSUE THREAD

**Issue by Lizurt** [TauCetiStation/TauCetiClassic#4762]
#### Подробное описание проблемы

Спрайт шлюза открывается или закрывается слишком быстро, он опережает звук

#### Что должно было произойти

Звук и спрайт работают синхронно

#### Что произошло на самом деле

Спрайт опередил звук, либо звук опоздал за спрайтом

#### Как повторить

Откройте или закройте шлюз с новым спрайтом

#### Дополнительная информация:

**Comment by WatlerJe** [comment]
У новых аудио открывания и закрывания есть пустота в начале дорожки

![image](https://user-images.githubusercontent.com/19796920/75447889-43b4e700-597b-11ea-8d7e-d0e51f05c467.png)

Чего например нету у старого

![image](https://user-images.githubusercontent.com/19796920/75447930-57604d80-597b-11ea-846f-3511389429ae.png)

И да, я правда не понимаю как респрайт мог сместить точку старта у звукового файла. Количество анимаций осталось прежним, шесть, изменилась лишь частота смена кадров с 2х на 1. Как это может затормозить или оепередить время начала проигрывания звуковой дорожки я не знаю.
Заметил подобный _баг_ только ты, до этого никаких жалоб на асинхронное звучание не поступало, как до респрайта так и после.

**Comment by Lizurt** [comment]
Неужели?

![image](https://user-images.githubusercontent.com/42589308/75455911-ed4fa480-598a-11ea-9ef8-aa8aabaae7f7.png)

![image](https://user-images.githubusercontent.com/42589308/75456020-0e17fa00-598b-11ea-905b-a432a18d835f.png)

Ничего что ты задержку между кадрами уменьшил с 0,2 секунды до 0,1 секунды, а количество кадров не изменял? Очевидно, что теперь шлюз открывается за 0,6 секунд вместо 1,2. Звук не трогался, я об этом и не говорил, не знаю зачем ты пишешь вот это:

> И да, я правда не понимаю как респрайт мог сместить точку старта у звукового файла.

&

> 1. Как это может затормозить или опередить время начала проигрывания звуковой дорожки я не знаю.

Также странно говорить вот это:

> Заметил подобный баг только ты, до этого никаких жалоб на асинхронное звучание не поступало, как до респрайта так и после.

К чему это? Во первых заметил подобный баг не только я. Лично я видел как минимум одного игрока, написавшего в чатик про эту проблему. Во вторых, что с того даже если бы этот баг заметил один я? Или я просто задел твои спрайтерские чувства, написав про одну из проблем, которые принесли новые спрайты?

**Comment by TungstenOctopus** [comment]
Если у нас сократилось время анимации двери в два раза, что тогда звук должен оставаться, когда дверь уже открыта/закрыта. Думаю это можно решить найдя новые звуки или ускорив старые.

**Comment by Sage4or** [comment]
> Если у нас сократилось время анимации двери в два раза, что тогда звук должен оставаться, когда дверь уже открыта/закрыта. Думаю это можно решить найдя новые звуки или ускорив старые.

я конечно в этом не шарю, но, как мне кажется, можно еще замедлить двери

**Comment by TechCatOther** [comment]
Если и замедлять текущие двери, то только урепленные. Это создасть эффект их большого веса, и не скажется на скорости передвижений персонала по станции.

**Comment by Sage4or** [comment]
> Если и замедлять текущие двери, то только урепленные. Это создасть эффект их большого веса, и не скажется на скорости передвижений персонала по станции.

Блин, тогда ведь может оказаться так, что придется менять звук для стандартной двери, но он такой родной.....
