### ISSUE TITLE
Сломана "я" в предпросмотре(при экзамайне моба) флавора

### ISSUE THREAD

**Issue by Lizurt** [TauCetiStation/TauCetiClassic#4763]
#### Подробное описание проблемы

![image](https://user-images.githubusercontent.com/42589308/75380263-c42a0800-58e7-11ea-835f-007e7ee65eb0.png)

#### Что должно было произойти

![image](https://user-images.githubusercontent.com/42589308/75380060-701f2380-58e7-11ea-90e5-db111d5c47a0.png)

#### Что произошло на самом деле

![image](https://user-images.githubusercontent.com/42589308/75379997-5978cc80-58e7-11ea-8d11-0539e47d81b8.png)

#### Как повторить

Экзамайн по мобу с флавором, в наччале которого есть буквы "я"

#### Дополнительная информация:

**Comment by volas** [comment]
Возможно персонаж с легаси флавором, если так то достаточно переписать и сохранить еще раз.

**Comment by Lizurt** [comment]
Да, оказывается это так, он переписал флавор и все стало ок.

Если нужно, закройте ишью
