### ISSUE TITLE
Фармбот не заботится о грибах

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#4764]
#### Подробное описание проблемы
Фармбот заботится только о растениях, полностью игнорируя все виды грибов
#### Что должно было произойти
Фармбот заботится о всех растениях/грибах
#### Что произошло на самом деле
Фармбот не заботится о грибах
#### Дополнительная информация:
Незнаю, может конечно это не баг, а фича. Но реально неудобно

**Comment by BiQndy** [comment]
Грибы считаются как сорняки, поэтому ему пофиг на них

**Comment by Daoprotoss** [comment]
Я дурак, ему можно карточкой провести и выставить настройки
