### ISSUE TITLE
Отображение предметов

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#4769]
#### Подробное описание проблемы
Перестали отображаться многие предметы в руках, а также флафы не отображаются в руках и на персонажах
#### Что должно было произойти
Все работает стабильно как и раньше
#### Что произошло на самом деле
Все сломалось
#### Как повторить
Взять инструмент в руку/надеть флаф

**Comment by LudwigVonChesterfield** [comment]
#4718 f841609
