### ISSUE TITLE
Ящик ХоСа

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#477]
#### Подробное описание проблемы
Из-за новых сетов охраны из шкафчика ХоСа пропал Дермал Пач.
#### Что должно было произойти
Дермал Пач должен быть.
#### Что произошло на самом деле
Его нет.
#### Как повторить
Зайти за ХоСа.
#### Дополнительная информация:
#Дермал_Пач_живи.

**Comment by Moggilazz** [comment]
Алло, это не баг, его специально не положил

**Comment by WallShrabnic** [comment]
А зачем он?

**Comment by Lancer411** [comment]
Кто конкретно? Ящик ХоСа, ХоС или его дермал патч?

**Comment by Moggilazz** [comment]
Ну какбэ 2016, шапки без спрайтов не очень, если корректно выражаться (ГОВНО ЕБАННОЕ), пусть носят фуражку с такой же защитой, её что, зря рисовали?

**Comment by Lancer411** [comment]
Ну так это не шапка без спрайта, а своеобразный имплант бронированный, не?

**Comment by Moggilazz** [comment]
Это не совсем имплант, а хреновина с присоской, чтобы на лоб клеить
