### ISSUE TITLE
Иконки в автоматах работают только на первом сервере

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4773]
#### Подробное описание проблемы
В связи с недавним обновлением, иконки в автоматах работают только на первом сервере, вот скрин со второго
![image](https://user-images.githubusercontent.com/24685276/75628218-de196280-5be7-11ea-9821-851514fd23b0.png)

#### Что должно было произойти
Иконки должны быть везде
#### Что произошло на самом деле
Иконки только  на первом

**Comment by Ahion** [comment]
Действительно проблема есть и на третьем сервере тоже. Почему-то скрипт, который метадату вырезает, не работает на этих серверах.

**Comment by volas** [comment]
Скорее всего на время ТМ-а спрайтов я только на первом обновлял пакеты, потом забылось. Я посмотрю.

**Comment by Ahion** [comment]
Хорошо, спасибо volas

**Comment by Ahion** [comment]
@volas вроде исправил, можно закрывать.
