### ISSUE TITLE
Не совершившая разгерма

### ISSUE THREAD

**Issue by ArtBsd1** [TauCetiStation/TauCetiClassic#4777]
#### Подробное описание проблемы
Блоб сломал стенку в космос, должна была произойти разгерматизация, но этого не было. Я как герой ходил без скафандра, мои коллеги ходили только со скафандром
#### Что должно было произойти
Я должен был уже сдохнуть от разгермы, не дойдя до этого места. 
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/44677341/75695766-62ddac80-5ccc-11ea-92da-994b241bae56.png)
Я дошел, да
#### Как повторить
Не знаю, блобом сломать стенку? 
#### Дополнительная информация:
Возможно, из-за этого блоб и проиграл(нет)

**Comment by Grox103FM** [comment]
Атмос на тайлах блоба/на тайлах нв которых был блоб сломан намеренно чтобы... Там наверное много причин. Недопускание убийства блоба фороновым пожаром, устранение бесконечных разгерм от блоба и т.д.

**Comment by Akellazp** [comment]
> Недопускание убийства блоба фороновым пожаром
Блобу пофиг на форон

**Comment by Sakuya-Izayoi** [comment]
Всем известно, блоб атмос не обновляет.
