### ISSUE TITLE
Опечатка в pyrometer

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#4794]
#### Подробное описание проблемы
лишний символ градуса в выводе пирометра

#### Что должно было произойти
`Temperature: -1.23471e+07 K`

#### Что произошло на самом деле
![зображення](https://user-images.githubusercontent.com/30875884/76140631-4c857700-6065-11ea-8001-949842568dcb.png)

**Comment by Sage4or** [comment]
А если я опечатки тут не вижу и, как мне кажется, так и должно писаться?
Объясни свою позицию, пожалуйста, почему для тебя это считается опечаткой?
