### ISSUE TITLE
Разряженная лазерка борга.

### ISSUE THREAD

**Issue by CeUvi** [TauCetiStation/TauCetiClassic#4795]
#### Подробное описание проблемы
Когда сек-борг взломан у него появляется лазерка. Стрелять с неё можно даже когда она якобы разряжена.
#### Что должно было произойти
Спрайт должен быть либо отдельный, либо всегда заряженный.
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/56074620/76141134-8c069000-6072-11ea-878c-b8c014fbea01.png)
![image](https://user-images.githubusercontent.com/56074620/76141138-92950780-6072-11ea-9551-547898d333a5.png)
#### Как повторить
Побыть взломанным секурити-боргом и пострелять с лазерки.
#### Дополнительная информация:
почините боргов блин...

**Comment by Deahaka** [comment]
Когда переписали на самозаряжайку пофиксили
