### ISSUE TITLE
Прости багесто, мы всё проблема со свалкой.

### ISSUE THREAD

**Issue by DantezZz** [TauCetiStation/TauCetiClassic#4798]
#### Подробное описание проблемы
При активации маяк не притягивает к себе мусор.
#### Что должно было произойти
Должен был произойти мусор.
#### Что произошло на самом деле
Безработные мусорщики
#### Как повторить
Активировать маяк

**Comment by BiQndy** [comment]
Ты, случаем, не на текущем раунде на 2 серве пытался включить?

**Comment by DantezZz** [comment]
На первом. Мы ещё с вотером утром такую же штуку словили.

**Comment by FelixRuin** [comment]
Локализую проблему, не работает /obj/effect/falling_effect
даже у админов
да, нельзя на сервере раздавить роялем, а так хочется...
И дополнительно: Всё работает на локалке, это проблема на билде сервера (возможно тест мёржы или версия сервера)

**Comment by volas** [comment]
Это только на первом?

**Comment by FelixRuin** [comment]
Да

**Comment by volas** [comment]
Возможно что-то с удалением эффектов (где-то не чистится ссылка или что-то еще), вероятно общие корни с #4800. Может быть и с #4799

Сейчас разбираться не буду, пока просто откачу лишнее с первого сервера. Если проблема будет всё еще присутствовать - скажите. Днем нужно будет посмотреть ТМы.

**Comment by Ambassadoing** [comment]
На втором тоже не работает, держу в курсе.

**Comment by FelixRuin** [comment]
Как оно может не работать
если я заходил на второй и самолично на всяк случай проверил

**Comment by Ambassadoing** [comment]
Вчера вечером педалил на втором и мне в ахелп жаловались, мол, НЕ РАБОТАЕТ.

**Comment by BiQndy** [comment]
Так же проверил на локалке, всё работает, кажется всё-таки, ТМ какой то ломает

**Comment by Dominig12** [comment]
Чинит удаление и спавн маяка, так же хочу сообщить, что при проверке турфа, внутри него есть эффекты падающего объекта, это значит что маяк сам по себе работает, а эффекты работают плохо, стакаясь в турфе.
Как я и сказал, решает проблему, удаление и новый спавн маяка. 
@volas прочекай, может что из этого тебе поможет

**Comment by TechCatOther** [comment]
Исправлено https://github.com/TauCetiStation/TauCetiClassic/pull/4748/commits/385dc4e5115d90694a6446faceb8018f56ce6e76
