### ISSUE TITLE
Книга мага не имеет меню для выбора магии (test merge problem)

### ISSUE THREAD

**Issue by FelixRuin** [TauCetiStation/TauCetiClassic#4799]
#### Подробное описание проблемы
Книга мага, которая позволяет магу выбрать его магию, пуста, а если более конкретно, то там есть только надпись о том, сколько осталось очков, но при этом самой магии нету
#### Что должно было произойти
Маг может выбрать себе магию сам
#### Что произошло на самом деле
Маг в шоке, администрации работа
#### Как повторить
Попытаться открыть книгу мага за мага
#### Дополнительная информация:
всё работает на локалке, но при этом на первом сервере вообще вникакую не работает

**Comment by TechCatOther** [comment]
Исправлено https://github.com/TauCetiStation/TauCetiClassic/pull/4748/commits/385dc4e5115d90694a6446faceb8018f56ce6e76

**Comment by Motzord** [comment]
Fixed?
