### ISSUE TITLE
При использовании прицела на ЛВАПе пропадает интерфейс

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#480]
#### Подробное описание проблемы
Снайперская винтовка отключает интерфейс при зуме, но при выходе из зума интерфейс на место не возвращается.
#### Что должно было произойти
Зум выключается, интерфейс возвращается на место.
#### Что произошло на самом деле
Интерфейса нет.
#### Как повторить
Взять ЛВАПу, включить зум на ней.
#### Дополнительная информация:
Лечится F12 или перезаходом (в этом случае иконки вещей надетых на хумана исчезают, и появляются только если снять их)

![bag](https://cloud.githubusercontent.com/assets/20542000/17892038/f8894f0e-6960-11e6-95f8-764b63218ec5.png)

**Comment by KatoMarika** [comment]
Фича же

**Comment by Skippeer12** [comment]
^
