### ISSUE TITLE
Эффект кинетика не пропадает (test merge problem)

### ISSUE THREAD

**Issue by FelixRuin** [TauCetiStation/TauCetiClassic#4800]
#### Подробное описание проблемы
Эффект от кинетического акселератора (который у шахтёров и ксеноархеологов) остаточный эффект от выстрела не пропадает
#### Что должно было произойти
Выстрел -> Эффект места попадания -> Эффект исчезает
#### Что произошло на самом деле
Выстрел -> Эффект маста попадания -> Эффект остался на месте и не желает уходить
#### Как повторить
Выстрелить из кинетика
#### Дополнительная информация:
Всё работает на локалке, но при этом на первом сервере проблема

**Comment by Motzord** [comment]
Fixed?
