### ISSUE TITLE
Мышь превращается в обьект

### ISSUE THREAD

**Issue by BiQndy** [TauCetiStation/TauCetiClassic#4802]
#### Подробное описание проблемы
Мышь остаётся обьектом, а не мобом, если ту взять в руки а потом положить на пол.

#### Что должно было произойти
Мышь должна стать обратно мобом
#### Что произошло на самом деле
Мышь превратилась в обьект и ничего не может, потому что она предмет
#### Как повторить
Быть хуманом, взять в руки мышь, выложить её на пол, смотреть, как та превратилась в смешной немощный обьект

**Comment by DantezZz** [comment]
Эта проблема у всех мобов.

![Screenshot_233](https://user-images.githubusercontent.com/36475593/76161921-fd187700-6148-11ea-88d0-f1c878f1c698.png)

**Comment by Sakuya-Izayoi** [comment]
Это не проблема. Игра так устроена что нельзя держать в руках моба, поэтому когда ты по животному кликаешь создаётся объект-холдер в котором содержится этот моб. Когда ты объект дропаешь моб из него достаётся.

**Comment by BiQndy** [comment]
В любом случае, оно поломалось

**Comment by SpaiR** [comment]
> В любом случае, оно поломалось

Тебе говорят, что так оно работает. "Превращение" в объект - часть механики и определенная условность. Если ломается что-то еще, то конкретизируй. Если нет, то это не баг.

**Comment by BiQndy** [comment]
Сейчас если взять в руки мышь и потом её выложить, она остаётся обьектом и не может ни двигаться, ни говорить, вообще ничего не может, так же накладывается слепота. Раньше если тебя брали в руки и потом клали на пол - всё оставалось в норме и мог спокойно дальше играть.

**Comment by SpaiR** [comment]
С этого стоило начинать. Из твоего описания это было не понятно.

**Comment by Sakuya-Izayoi** [comment]
Я полагаю Test Feedback?

**Comment by Dominig12** [comment]
Проверено на первом, не подтвердилось, предположительно там где проверяли сломались контроллеры, я проведу проверку и там.
Проверено на втором, ничего не изменилось, все так же работает, проблемы нет
