### ISSUE TITLE
Мёртвые хагеры ведут себя как живые

### ISSUE THREAD

**Issue by EdlerN** [TauCetiStation/TauCetiClassic#4824]
#### Подробное описание проблемы
Трупики фейсхагеров прыгают на космонавтов и заражают их
#### Что должно было произойти
Трупы должны быть мёртвыми
#### Что произошло на самом деле
Ивенты уровня лолона каждый раунд.
#### Как повторить
Сходить на заброшенную шахтерку и походить рядом с трупами фейсхагеров
#### Дополнительная информация:
Кому-то надо сломать руки.

**Comment by ViDLiathan** [comment]
На астероиде на заброшенной базе трупы хаггеров, которые заражают космонавтиков полноценными лярвами

**Comment by Lizurt** [comment]
Походу я в глаза долблюсь, глупая ошибка

![image](https://user-images.githubusercontent.com/42589308/76466875-805ff400-63f9-11ea-8f43-24d53d304b19.png)

Не обратил внимания во время правок, что там 2 проверки на стат у разных мобов.
Думал "хмхмхмх а зачем нам проверка на то что моб сдох если выше проверяем он вообще в сознании или как"

В общем, помимо этого бага я сразу могу сказать начсет другого - теперь можно заражать мертвых людей мертвыми фейсхаггерами, т. к. по вышеописанным причинам поплыла и проверка `is_facehuggable()` у мобов

Пофикшу в ближайшее время
