### ISSUE TITLE
Кадеты-триторы

### ISSUE THREAD

**Issue by CeUvi** [TauCetiStation/TauCetiClassic#4827]
#### Подробное описание проблемы
Можно стать тритором за кадета.
#### Что должно было произойти
Ты не становишься тритором за кадета из-за импланта.
#### Что произошло на самом деле
Ты становишься тритором-кадетом.
#### Как повторить
Играешь за кадета и надеешься на выпадение рольки.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/56074620/76514250-affa1500-6468-11ea-9076-9b4f575133b5.png)

**Comment by Akellazp** [comment]
ne bag a feature

**Comment by TheReaperOfSouls** [comment]
Если я не ошибаюсь, по коду все должно работать, вероятно ошибка из-за того что ранее кадеты были ассистухами.

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/fludilka/3304/36781

**Comment by Venngedi** [comment]
#3466 Это можно закрыть.
