### ISSUE TITLE
Треклист Soviet Radio не проигрывает музыку

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#483]
#### Подробное описание проблемы
_Любая_ песня в треклисте советов не проигрывается.
#### Что должно было произойти
Музыкальное достояние комми слышно.
#### Что произошло на самом деле
Музыки нет.
#### Как повторить
Взять жукбокс, выбрать Soviet Radio.

**Comment by Lancer411** [comment]
Возможно пофиксил. Проверь в раунде.

**Comment by Skyrull** [comment]
Все еще не работает.

**Comment by Lancer411** [comment]
У меня работает. Проверь еще раз.

**Comment by KatoMarika** [comment]
А остальные у тебя работают?

**Comment by Lancer411** [comment]
У меня все работают. Куршан и Амбиент подтвердят.

**Comment by Kurshan** [comment]
Ну так во время раунда и починили.

**Comment by Lancer411** [comment]
Я закрываю значит.
