### ISSUE TITLE
говорящие абдукторы

### ISSUE THREAD

**Issue by Sage4or** [TauCetiStation/TauCetiClassic#4833]
#### Подробное описание проблемы
если вы выбрали персонажа с дополнительным языком, ну гаттер там или еще че, и вам выпадает роль абдуктора, то вы можете говорит на гаттере как обычный чел, не в хайв абдукторов
#### Что должно было произойти
доп языка нет, абдуктор плачет
#### Что произошло на самом деле
абдуктор может послать гсб на хуй на гаттере
#### Как повторить
выбрать секонд language в настройке персонажа и стать абдуктором

**Comment by FelixRuin** [comment]
да добейте этот режим уже наконец

**Comment by Sage4or** [comment]
убрать баг? неееееее
лучше добить режим, чтобы точно одни генокрады да триторы были

**Comment by Bullethole** [comment]
ты же в курсе да? что это специально.
вики читай

**Comment by Sage4or** [comment]
> ты же в курсе да? что это специально.
> вики читай

![image](https://user-images.githubusercontent.com/59475362/76626556-6681f680-654a-11ea-912a-01398e0aba41.png)
первый же абзац в вики абдукторов

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/8467
