### ISSUE TITLE
Вирус с гибинтош синдромом не гибает

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4837]
#### Подробное описание проблемы
Вирус гибинтош синдром делает минимальный взрывы станящие куклу, но не гибает
#### Что должно было произойти
гиб
#### Что произошло на самом деле
подопытный падает, плачет и просит чтобы это все закончилось
#### Как повторить
введите подопытному гибинтош синдром

**Comment by Pivo24** [comment]
Не баг, а фича. Все симптомы имеют свои стадии. Гибинтош в последней стадии - гибает.

**Comment by Akellazp** [comment]
Сначала станящие взрывы, потам гибы конечностей, потом полный гиб

**Comment by Motzord** [comment]
Вы правы я слишком рано создал ишью. Гиб был
