### ISSUE TITLE
[proposal] Малфоаннонс при любом взломанном АПЦ

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4839]
#### Подробное описание проблемы
Игроки увидев первый малфоаннонс тут же понимают что малф и начинают втихуя метагеить.
#### Что должно было произойти
Любой татор/нинжа/малф ломает апц и всем звучит первый малфоаннонс, что как бы путает игроков и не дает им сразу думать на малфа. (Вдруг таторы или нинжи)
#### Что произошло на самом деле
Синенькие АПЦ не только от малфа, их еще умеют ломать таторы с емагами и нинжа, но цк почему-то о подобном муве не уведомляет
#### Как повторить
Закодьте кто нибудь блин

**Comment by TechCatOther** [comment]
Вообще система с анонсами при малфе часто приводит к мета геймингу. Можно просто сделать их случайными с другим текстом и добавить в другие эвенты похожие.
