### ISSUE TITLE
[Proposal] Воксы и рост

### ISSUE THREAD

**Issue by Sage4or** [TauCetiStation/TauCetiClassic#4844]
По лору воксы, которых мы можем встретить на стейшене, маленькие, думаю, можно сделать, чтобы они выглядели на подобии людей под халфлингом из генетики, не добавляя плюсы этого самого халфлинга

**Comment by Sakuya-Izayoi** [comment]
а можно и добавляя
всё равно в маске не залезут в венты

**Comment by Avatar4** [comment]
В смысле, меньше чем люди? Если ты предлагаешь их ресайзом сделать меньше, то это отшакалит все спрайты которые недавно рисовали для воксоты. А переспрайтить все обилие одежды так тем-более не станут. Легче заменить лор

**Comment by Sage4or** [comment]
> В смысле, меньше чем люди? Если ты предлагаешь их ресайзом сделать меньше, то это отшакалит все спрайты которые недавно рисовали для воксоты. А переспрайтить все обилие одежды так тем-более не станут. Легче заменить лор

ну от обычных халфлингов ничего вроде не кошмарилось, мб я не замечал просто, да и тебе явно лучше знать

**Comment by UsadoSmokk** [comment]
> В смысле, меньше чем люди? Если ты предлагаешь их ресайзом сделать меньше, то это отшакалит все спрайты которые недавно рисовали для воксоты. А переспрайтить все обилие одежды так тем-более не станут. Легче заменить лор
если дать воксам халфингов, то все будет норм, единственное спрайты будут в ултра эйжди графикс, но это уже проблемы самих халфингов, но есть еще одна проблема, все начнуть ныть, мол ААААААААААААА ВОКСИ ИМБЯ НА СТОЛ ЛКЗТЬ МОГУТ, УУУУУУ, УДОЛИТЕ ЛИП, я уже и так натерпелся этих соплей, но я поговорю с балансерами и с совой, если дадут добро, то может быть и дам им эту мутацию

**Comment by Ambassadoing** [comment]
Не надо. Они не НАСТОЛЬКО маленькие.
