### ISSUE TITLE
NanoMed общака-Access denied.

### ISSUE THREAD

**Issue by Mintt69** [TauCetiStation/TauCetiClassic#4849]
#### Подробное описание проблемы
NanoMed недоступен ни зекам, ни СБ, Access denied.
#### Что должно было произойти
Доступ должен быть общий
#### Что произошло на самом деле
Access denied.
#### Как повторить
Попробовать открыть NanoMed  в общаке без доступа врача
#### Дополнительная информация:
https://i.gyazo.com/d2b5aa01a8acc4d87fea2eadc005b90b.png

**Comment by Enerty** [comment]
Ну если я правильно понимаю, как и что там у наномеда, то завтра или послезавтра починю
