### ISSUE TITLE
Кривой кабель и отсутствие камеры в туалете

### ISSUE THREAD

**Issue by 4310V343k** [TauCetiStation/TauCetiClassic#4856]
#### Подробное описание проблемы
После ПРа #4797 в туалете криво стоит кабель и нет камеры
#### Что должно было произойти
АПЦ должен заряжатся и ИИ должен все видеть
#### Что произошло на самом деле
АПЦ не заряжается и ИИ ничего не видит
#### Как повторить
Открыть и проверить в мап редакторе
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/56449763/76709152-6b42d800-670d-11ea-8782-f531adb55eaa.png)

**Comment by Enerty** [comment]
Сегодня исправлю

**Comment by Motzord** [comment]
Закрывайте
