### ISSUE TITLE
Шлем нюки включает лампочки на головах людей

### ISSUE THREAD

**Issue by Mintt69** [TauCetiStation/TauCetiClassic#4857]
#### Подробное описание проблемы
Можно зайти в меню своего шлема нюки и включить фантомные лампочки на головах людей вокруг
#### Что должно было произойти
Лампочки должны были включиться  только на носителе
#### Что произошло на самом деле
Даёт доступ к "фантомным" лампочкам и носитель может включить их кому угодно в пределах экрана
#### Как повторить
Надеть шлем нюки 
#### Дополнительная информация:
https://i.gyazo.com/9157d6c267ffd8f26f1ff4c7f0c8ecc1.png

**Comment by LudwigVonChesterfield** [comment]
https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/clothing/spacesuits/rig/rig.dm#L674

Вот тут, в аргументах вёрба мелькает "mob/user", а значит бьёнд позволяет передать в вербу любого моба на выбор.

Чтобы сделать хорошо - надо отдельный прок который собсна туглит свет(но именно прок), который принимает в качестве аргумента моба который тугглит свет, и отдельно верб который вызывал бы этот прок на юзера верба.

(Или может даже туглить свет самому костюму? Если так можно конечно же.)

**Comment by igigin** [comment]
Уже третий дубликат, если что.

**Comment by FelixRuin** [comment]
вертел, крутил, натягивал шлем, но так и кнопки этой не нашёл
да и вообще каких-либо странностей не нашёл, возможно этот пр всё починил https://github.com/TauCetiStation/TauCetiClassic/pull/4889
но в любом случае багов нету уже и можно закрывать, да? вроде да @LudwigVonChesterfield слыш, работать

**Comment by Sakuya-Izayoi** [comment]
не удалось потворить, возможно уже исправлено

**Comment by 4310V343k** [comment]
Пофикшено
https://github.com/TauCetiStation/TauCetiClassic/commit/488d49f66bca590dabe1eae8150b6056e159fe60#diff-e25793da14e983d32ffa0722472a29035afcb32afa0fbd2fefe6255f1d83e02bL674

**Comment by FelixRuin** [comment]
И всё ещё это нужно закрыть...
