### ISSUE TITLE
СПУ, не ремонтируются глаза(камеры)

### ISSUE THREAD

**Issue by Lexanx** [TauCetiStation/TauCetiClassic#4858]
#### Подробное описание проблемы
Если камеры СПУ повреждены, то при попытке их отремонтировать, нужно раскрутить панель на них отверткой, но сколько ты не пытайся её раскрутить, всегда будет сообщение что вы закручиваете панель.
#### Что должно было произойти
Открутить панель на камерах, и дальше уже лечить нанопастой/гаечным ключом
#### Что произошло на самом деле
Слепой СПУ без возможности открутить панели камер для ремонта глаз.
#### Как повторить
Попытаться открутить панели на камерах СПУ.

**Comment by FelixRuin** [comment]
в процессе фикса
