### ISSUE TITLE
СПУ нет способа вернуть отрубленный монитор (голову)

### ISSUE THREAD

**Issue by Lexanx** [TauCetiStation/TauCetiClassic#4859]
#### Подробное описание проблемы
В случае утери монитора СПУ, нет способа ремонта. И СПУ будет оставшуюся игру, ходить без головы, следственно без наушника и очков.
#### Что должно было произойти
Возможность возврата монитора на место
#### Что произошло на самом деле
Ни один из способов вики, не позволил вернуть монитор на место, итог, СПУ без головы
#### Как повторить
Отрубить СПУ голову, попытаться вернуть её на место

**Comment by LudwigVonChesterfield** [comment]
![image](https://user-images.githubusercontent.com/17705613/76748292-2eb1c380-6783-11ea-8357-46064ca8d8a0.png)

**Comment by LudwigVonChesterfield** [comment]
![image](https://user-images.githubusercontent.com/17705613/76748344-41c49380-6783-11ea-85a7-195a2ac76cca.png)

**Comment by LudwigVonChesterfield** [comment]
Использовать кстати можно как экран СПУ, так и роботическую голову из роботики.

**Comment by Lexanx** [comment]
Может быть я что то делаю не так, но у меня не выходит вернуть голову

**Comment by LudwigVonChesterfield** [comment]
Цель - голова.
Кусачки.
Ключ.
Монитор/Голова из роботики.

**Comment by Lexanx** [comment]
Я понял в чем проблема была, там был обрубок головы, который убирался только циркулярной пилой

**Comment by Lexanx** [comment]
По поводу головы из роботики, у меня её не получилось приделать. Сам процесс приделывания шел, и все. А старую на место вернул

**Comment by LudwigVonChesterfield** [comment]
Ты прав, я не прав. Обычная голова не работает.
