### ISSUE TITLE
Отсутствие ПКМ за ИИ сильно ломает игру для малфа

### ISSUE THREAD

**Issue by Poldan** [TauCetiStation/TauCetiClassic#486]
#### Подробное описание проблемы

ПКМ у ии вырезан. Из-за этого абилка machine overload не представляется используемой в принципе. 
#### Что должно было произойти

При ПКМЕ должна выползти менюха подрыва машины
#### Что произошло на самом деле

НИЧЕГО
#### Дополнительная информация:

Если крайне не хотите возвращать ии ПКМ - сделайте хоть хоткей на подрыв техники

**Comment by Kurshan** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/1965
