### ISSUE TITLE
[Proposal] Sleep для СПУ, как борьба с перегревом(уменьшение нагрева)

### ISSUE THREAD

**Issue by Lexanx** [TauCetiStation/TauCetiClassic#4868]
#### Подробное описание проблемы
При нажатии сна на СПУ, СПУ спит и видит сны

#### Что должно было произойти
Позволить СПУ во время сна, переставать греться, и сделать аналог ждущего режима/гибернации. (Будет очень полезно при поломках после ЭМИ)

#### Что произошло на самом деле
Во время сна СПУ так же тратит энергию, греется, и видит сны про пироги
#### Как повторить
Поспать

**Comment by GermanSUS** [comment]
Это можно будет заабузить, например в космосе. Тогда в тех условиях где нельзя охлаждаться, во время сна охлаждаться не будет, но и температура поднимается не будет
