### ISSUE TITLE
Вокс спавнится без маски при нюке.

### ISSUE THREAD

**Issue by JustEmpty** [TauCetiStation/TauCetiClassic#4873]
#### Подробное описание проблемы
При нюке воксы спавнятся без маски и баллона азота, на базе нет баллонов с азотом.
#### Что должно было произойти
Вокс заспавнился в маске и в сумке или кармане лежит баллон с азотом
#### Что произошло на самом деле
Вокс спавнится без маски и начинает потихоньку получать токсический урон
#### Как повторить
Зайти на воксе за нюку

**Comment by Sosicin** [comment]
Уже залил на гит фикс

**Comment by Sosicin** [comment]
При подобных багах прошу тоже незамедлительно говорить, буду фиксить
