### ISSUE TITLE
Не обновляется спрайт сумки после её мытья

### ISSUE THREAD

**Issue by Marselinel** [TauCetiStation/TauCetiClassic#4877]
#### Подробное описание проблемы
Если запачкать рюкзак кровью, а затем его помыть - спрайт рюкзака не обновится (рюкзак будет по-прежнему окровавленным), но при examine рюкзак будет чистым.
#### Что должно было произойти
Спрайт рюкзака должен обновиться и стать чистым.
#### Что произошло на самом деле
Спрайт рюкзака остался окровавленным после мытья.
#### Как повторить
Запачкать рюкзак и помыть его.
#### Дополнительная информация:
![IMG_20200317_123810_714](https://user-images.githubusercontent.com/51530205/76848899-1d34ee00-684d-11ea-98f7-6f328ac14d2e.jpg)

**Comment by Kyvikoi** [comment]
Ты очищал/-а в раковине или клинером?

**Comment by Marselinel** [comment]
> Ты очищал/-а в раковине или клинером?

И так, и так

**Comment by Motzord** [comment]
Неактуально
