### ISSUE TITLE
[Proposal]  Вернуть офицерский доступ в верхний арсенал

### ISSUE THREAD

**Issue by Mintt69** [TauCetiStation/TauCetiClassic#4878]
Предлагаю вернуть офицерский доступ в верхнюю оружейку, доступ на кнопку был оставлен и офицеры могут заходить туда без труда, но все окна закрыты и доступ к необходимой снаряге ограничен стёклами. 

Ниже приведу пару примеров и своих наблюдений.

 1) На практике: просто удалили эти вещи из пользования, Гсб/Варден никогда  не проявляют инициативу открыть эти створки и выдать броню по ситуации офицерам, все только об оружии вспоминают, потому что давно привыкли к такому раскладу- "что тебе нужно-то ты и берешь", офицеры не маленькие дети чтобы менять им подгузники, они должны решать сами чем и под какую ситуацию защищать себя.

Под те же створки попали флешбенги и доп. магазины на 9мм резину, у тех, кого еще остался доступ в эти створки, явно вызывает дискомфорт каждый раз бегать открывать то, что должно быть открыто всегда

Понятное дело офицер не будет брать РИОТ броню в начале раунда-просто потому что это НЕУДОБНО, так вот, мне, как игроку на офицере- НЕУДОБНО то, что в верхней оружейке стоит доступ, также вызывает дискомфорт тратить время каждый раз на ломание этих самых стекол или откручивание их сбоку, это настолько вошло в обыденность, что никто уже не видит то, какой дискомфорт и трата времени это вызывает. Сейчас объясню почему так...

 2) На практике: офицеру срочно понадобилось взять спец.средство из верхнего арсенала, появилась резкая необходимость, понятное дело  в обычное время ему незачем брать  данные вещи  без  "определенного случая", !ПОД КОТОРЫЙ! офицер сам решает, какую броню или средство ему взять, но они выходят закрытыми, открыть поблизости некому, в канал никто не отзывается, ты тратишь время и нервы на то, чтобы кликать по этой дверце батоном. Что очередной раз  приводит к тому, что доступ на верхнем арсенале не удобен и не нужен. 

Считаю добавление доступа на верхний арсенал !НЕНУЖНЫМ! и !НЕУДОБНЫМ!, я частый игрок на офицере и проблема  проверена исходом длительного времени.

**Comment by Motzord** [comment]
А я предлагаю другую альтернтиву. Добавить в кабинет вардена и хоса маленькую кнопочку для поднятия стекол в верхнем арсенале. 

(иначе офицерики смогут в начале раунда лутать любимый риот и мариновский шмот)

Тогда вардену или ГСБ надо лишь нажать на кнопочку чтобы все стекла поднялись и все были счастливы.

**Comment by AndroBetel** [comment]
раньше у стеклях у шкафов маринов был доступ вардена, а больше и нечего воровать из той оружейки, разве что для снежинковой красоты или 5 карманов на пулезащитной броне/станбатона запасного из риота

**Comment by TheReaperOfSouls** [comment]
Пояс маринов вмещает в два раза больше, так что лутать, найдется что
