### ISSUE TITLE
Ксеноархеология не приносит очков науки

### ISSUE THREAD

**Issue by Lexanx** [TauCetiStation/TauCetiClassic#4881]
#### Подробное описание проблемы
Ксеноархеология бесполезна для РнД.
Отчеты не дают очков, сканирования найденных артефактов, как через сайнс тул, так и на прямую, попытки запихнуть найденое в дестракт анализатор. Так же не дает очков.
Alien object has no research value
Strange statuette has no research value
и тд.

Поиграв несколько часов и решив просканировать все свои находки, очки исследования мне дал только кухонный нож и ( И инвентарь самого аванпоста, вроде горелки или станбатона)
Estimated research value of sharp cutting implement is 200

Так же Артефакты(И бумажка с их анализом) не приносят очков, ты просто находишь артефакт, понимаешь что он делает, и складываешь в шкаф. Потому что он опасный/бесполезный. Пользы от них так же нет.

Поиск окаменелостей, и после возрождения жизни, так же не приносит пользы. Если растение можно отдать ботанику. (Снова очков науки ты не получишь). То воссоздав существо, будь это Ксеноморф или улиткожаба, оно просто там будет. И единственное что ты сможешь сделать с ним, это РПшить. (Очков науки снова не получишь) 

#### Что должно было произойти
Ксеноархеология должна приносить очки науки за свои находки.

#### Что произошло на самом деле
Ксеноархеология не приносит РнД ничего.

#### Как повторить
Найти любой артефакт, попытаться извлечь из него научные очки.

**Comment by Zmey25** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/4188

Актуально
