### ISSUE TITLE
Ксеноархеология, комната изоляции 3. Сканируется укрепленное стекло вместо Артефакта

### ISSUE THREAD

**Issue by Lexanx** [TauCetiStation/TauCetiClassic#4883]
#### Подробное описание проблемы
Стекло находится в зоне сканирования сканера, и оно всегда будет сканироваться вместо артефакта
#### Что должно было произойти
Сканироваться артефакт.
#### Что произошло на самом деле
Просканировалось стекло
#### Как повторить
Воспользоваться сканером аномалий в комнате изоляции 3.
#### Дополнительная информация:
Так же хотелось бы там стекла попрочнее, как я понимаю, судя по системе зажигания, комната для нагрева температуры, и поджегов. Но стекла всегда ломаются при попытках нагреть зону внутри. (Ну или я криворукий такой ._.)

**Comment by Daoprotoss** [comment]
Я вроде когда гайд по археологии дописывал указал какую температуру надо ставить чтобы артефакт и активировался и сама комната не превращалась в местный филлиал ада

**Comment by Lexanx** [comment]
Да, нашел, на вики где указано. Значит я криворучка температурная. Но проблема со стеклом, всеравно остается

**Comment by TheReaperOfSouls** [comment]
Лечится мапингом, передвинуть стекло на другой тайл. Делать, пока что, буду не я

**Comment by Motzord** [comment]
> Лечится мапингом, передвинуть стекло на другой тайл. Делать, пока что, буду не я

если передвинуть стекло на другой тайл, герметичность нарушится  и будет не очень смешно, особенно когда артефакт активируется каким-нибудь фороном.
двигайте лучше сканер.
