### ISSUE TITLE
Упаковка свечек не влезает в библию

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#4895]
#### Подробное описание проблемы
В библию, в которую свободно помещается кадило, не помещается маленькая упаковка свечек ибо слишком большой объект
#### Что должно было произойти
Упаковка свечек помещается в библию
#### Что произошло на самом деле
Упаковка свечек слишком большая для библии
#### Как повторить
Попытаться засунуть упаковку со свечками в библию
#### Дополнительная информация:
-

**Comment by TheReaperOfSouls** [comment]
Это не совсем является багом.
Библия является контейнером, и упаковка свечек является контейнером.
Тут либо понижать размер свечей и коробки свечей, либо повышать размер у библии.

**Comment by Daoprotoss** [comment]
Ну тогда уж понижать размер свечей с коробкой. Библия  и так большая

**Comment by TheReaperOfSouls** [comment]
Попробую это сделать, надеюсь ничего не сломается 🤡

**Comment by Grox103FM** [comment]
Зачем помещать коробку свечей если можешь поместить свечи? Оба объекта нормального размера, а библия по вместимости как коробка
