### ISSUE TITLE
Люди без вайтлиста и минут могут зайти за нимфу

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#4898]
#### Подробное описание проблемы

шапка

#### Что должно было произойти

люди у которых не наиграно 40к минут и нет вайтлиста не должны мочь зайти за нимфу

#### Что произошло на самом деле

наоборот

#### Как повторить

иметь акк с меньше чем 40к минутами, умереть, дождаться промпта об игре за нимфу - зайти.

#### Дополнительная информация:
#4734

**Comment by volas** [comment]
честно говоря не очень понимаю, зачем нужно было вообще пытаться ограничивать фичу с нимфами вайтлистом

**Comment by LudwigVonChesterfield** [comment]
потому-что люди держат их к тем же стандартам что и дион
