### ISSUE TITLE
Термометр с прицелом.

### ISSUE THREAD

**Issue by ArtBsd1** [TauCetiStation/TauCetiClassic#4907]
#### Подробное описание проблемы
Зашел за СЕ, увидел впервые инфакрасный теормометр с прицелом. Подумал нафига? Нажал на него, камера улетела и вернулась в исходное положение, только без интерфейса. Долго искал как вернуть интерфейс, но нет, пришлось выходить(точнее админы кикнули).  Перезашел ии... Интерфейс появился, вроде бы всё круто, но ячейки ПДА, карты, пояса, портфеля и карманов стали пусты. Я перезаходил, но не помогало.
#### Что должно было произойти
Всё должно было закончится благоприятно. 
#### Что произошло на самом деле
Моя игра закончилась
#### Как повторить
Нажать на инфакрасный термометр с прицелом и перезайти.

**Comment by Sage4or** [comment]
есть такая кнопка, ф12, она тебе счастье сделает

**Comment by ArtBsd1** [comment]
> есть такая кнопка, ф12, она тебе счастье сделает
Стоит это где-то написать, если не написано. Вроде бы, даже админы не знали.

**Comment by 4310V343k** [comment]
Админы не знают, а рядовые игроки знают
Стоит задумать о их компетентности :/
