### ISSUE TITLE
Disposal unit между Моргом и Библиотекой отправляет весь мусор в Генетику

### ISSUE THREAD

**Issue by Tiarv** [TauCetiStation/TauCetiClassic#4909]
#### Подробное описание проблемы
Новый disposal unit в Starboard Primary Hallway между моргом и библиотекой подключен не к общей disposal network, а к локальной, соединяющей Генетику и Роботику. Поэтому любой мусор выброшенный в эту мусорку будет валиться в Генетику и Роботику (ну и дроны сильно удивляются).

#### Что должно было произойти
Прыгнув в мусорку между моргом и библиотекой с тегом "кухня" должен попасть на кухню.

#### Что произошло на самом деле
Прыгнув в мусорку между моргом и библиотекой с тегом "кухня" попадаешь в генетику.

#### Как повторить
Прыгнуть в мусорку в главном коридоре между моргом и библиотекой.

#### Дополнительная информация:
Box Station

**Comment by 4310V343k** [comment]
сделай скрин

**Comment by kildjen** [comment]
Это я значит так качественно намапил. Ща пофиксим.

**Comment by 4310V343k** [comment]
Нет, намапил ты нормально, там почему-то труба отправляет не в ту сторону

**Comment by kildjen** [comment]
Там не все так просто с трубами. Разбираюсь уже
