### ISSUE TITLE
В конце раунда не появляется таблица антагов в режиме автотритор.

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#491]
#### Подробное описание проблемы

Нет финального экрана при автотриторах

#### Что должно было произойти

ГРИНТЕКСТ

#### Что произошло на самом деле

ЕГО НЕТ

#### Как повторить

При автотриторах дождаться конца раунда

#### Дополнительная информация:

Возможно если автотритор один, там будет финальный экран

**Comment by ZVee** [comment]
Этот баг никто не может повторить пока, так что не ясно что или из-за чего.

**Comment by Raschert0** [comment]
А ещё этот ишью - повтор

**Comment by ZVee** [comment]
А еще на будущее - название ищю бы конкретнее, а то если не заходить, ничего не ясно.

**Comment by ZVee** [comment]
#249 - а еще, внезапно такой уже есть.
