### ISSUE TITLE
[Proposal] Добавить в функционал null road'а священника, возможность освобождать(читай убивать) големов

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#4912]
#### Подробное описание проблемы
Что во время культа или другого режима игры, големы это некая имба, которую фиг убьешь и которую легко наплодить. Я предлагаю добавить посоху священника функцию не только конвертить культистов, но и освобождать души от оков камня.
#### Что должно было произойти
Священник тыкает null road'ом и голем умирает. Это их понерфит и сделает священника чуть более полезным.
#### Что произошло на самом деле
Големы-культисты режут священника фарш
#### Как повторить
.
#### Дополнительная информация:
.

**Comment by Pivo24** [comment]
В принципе легко осуществить, достаточно поменять нуллроду урон с 15 до, скажем, 250. Нулл родом нельзя ударить кого-то другого, кроме големов культа, что и сделает нуллрод универсальным орудием против конструктов.

Но ради баланса стоит поставить проверку, чтобы атакующий был только священник. А то получатся ваншотящие конструктов офицеры.

**Comment by Daoprotoss** [comment]
Я вообще имел ввиду в общем големов гибать. Но пусть хотя бы культиских, уже радость будет

**Comment by KIBORG04** [comment]
Зачем делать из священника оружие уничтожения любых големов? Он и так может палить любых культистов и их руны в радиусе 6 от себя, а так же деконверт. К тому же, про силу нулрода станция не знает.
Если сделать гиб культистских мобов, то можно увидеть, как какой-то поп идет ломать неведомую дичь, которая убила 3 СБшников, своей палкой.

**Comment by Grox103FM** [comment]
Дисбаланс. Он и так по ним больше дамажит. Констрактам нелегко живётся, они люто урезанные, дисконект их убивает а тут ты ещё и ваншот хочешь их сделать? давай не надо. Ладно бы прогресс бар и переведение из культоголемов в свободных големов раз ты хочешь что-то сделать с ними, но никак не гиб.

**Comment by Daoprotoss** [comment]
А как будет работать механика свободных големов? Это еще более жопа, чем простой гиб.
