### ISSUE TITLE
Режим "Алиумы"

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#493]
Sentinel - Нейротоксин не работает.
Hunter - Можно прыгать в любом интенте.
Прыжок в интенте "help" дает возможность прыгать сквозь людей, не задевая их.
Можно прыгать с пуллом человека и всеми остальными прелестями, которы можно пуллить.
Задержка на прыжок после попадания по человеку слишком маленькая, секунды две-три.
Weeds - Растет только на один соседний таел.

![](http://i.imgur.com/sWdpasC.png)

Алиумы не умеют в укрепленые стены, ни квина, ни плевун, ни дрон.

**Comment by Skippeer12** [comment]
Забыл кое чего дописать..
В вентиляции они видят только таел где ползут и это жутко не удобно

**Comment by Moggilazz** [comment]
По заказу вождя ведутся опытно-конструкторские работы по этому поводу.

**Comment by ZVee** [comment]
>По заказу вождя ведутся опытно-конструкторские работы по этому поводу. 

А меня забыли оповестить, алиумов то я перепиливал когда-то.

**Comment by Moggilazz** [comment]
> А меня забыли оповестить, алиумов то я перепиливал когда-то.

Результат налицо
