### ISSUE TITLE
[Proposal] Добавить иконку предупреждающего сообщения для кнопки Restart

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#4930]
Сейчас, любой может прожать рестарт после полтора часа раунда если нет админов в раунде. Зачем и почему это можно использовать непонятно. Игрок может случайно прожать рестарт а не будет никого что бы это остановить (кроме игроков).

Нужно предупреждающее окно что бы люди знали когда можно делать рестарт а когда нет, дабы если они случайно и нажали, то рестарт не активировался сразу.

**Comment by TechCatOther** [comment]
Добавите тут текст для предупреждения?

**Comment by Avatar4** [comment]
> Добавите тут текст для предупреждения?

Я думал, в идеале сделать выскакивающее окно при нажатии на рестарт о том, когда его надо использовать. Это бы ограничило случайное нажатие и дало бы игрокам понять что просто так нажимать не стоит. Хотя, если будут админы, кнопка просто не прожмется. Так что точно не знаю
