### ISSUE TITLE
Сломаные проверки на расу

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#4935]
#### Подробное описание проблемы
Сломаны проверки на расу для многих предметов
#### Что должно было произойти
Спокойно надел на ксеноса ск-1, перчатки без пальцев и тд
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/47355061/77788514-1175d280-706a-11ea-9168-f6923f82b56c.png)
![image](https://user-images.githubusercontent.com/47355061/77788532-189ce080-706a-11ea-8a7d-5831c19f1992.png)
и тд
#### Как повторить
Зайти на ксеноса и попытаться надеть разные вещи

**Comment by Akellazp** [comment]
![image](https://user-images.githubusercontent.com/47355061/77790508-a5956900-706d-11ea-893e-4a3628e8334c.png)

**Comment by ViDLiathan** [comment]
А, уже было, окей
 #4936

**Comment by TechCatOther** [comment]
Возможно ПР #4918 исправит баг
