### ISSUE TITLE
Универсальный пирометр из РНД, не работает

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4938]
#### Подробное описание проблемы
После введения пирометров все развлекались ими как могли, стреляли друг в друга, вставляли друг в друга, много что делали, но никто не делал универсальный пирометр в РНД. Я был первый, в результате, при смене режима он не работает и CLICKает.
#### Что должно было произойти
Пирометр должен был уметь менять режим
#### Что произошло на самом деле
CLICK CLICK CLICK CLICK
#### Как повторить
Распечатать пирометр в РНД не прототип, а вполне хорошую МК модель, а так же, попробовать им воспользоваться
#### Дополнительная информация:
Пирометры бесполезны

**Comment by 4310V343k** [comment]
батарейку сувал в него?

**Comment by Dominig12** [comment]
> батарейку сувал в него?

В него можно запихнуть батарею?

**Comment by Dominig12** [comment]
Вставил батарейку, он продолжает кликакть, так же хочу сказать, что с остальными пирометрами все нормально

**Comment by 4310V343k** [comment]
У меня тоже кликает..

**Comment by LudwigVonChesterfield** [comment]
в пирометр который в РнД ещё надо компонент лазера всунуть.

**Comment by 4310V343k** [comment]
oof
