### ISSUE TITLE
Новый абуз РНД. Люди эволюционируют милорд.

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4939]
#### Подробное описание проблемы
Сама по себе проблема абузов РНД комплексная, и не решается парой патчей прошу сделайте РНД как в стелларисе). Ну да не о том. Ранее был абуз "Печатаем крутые платы, сбрасываем консоль, дробим платы, синхронизируемся, изучаем на очки", его прикрыли не позволив дробить прототипы. Но вместе с тем, ввезли новый абуз, с помощью отчетов. Этими отчетами могут быть "Археология, Вирусология, Отчеты о вскрытии", так же этим может быть "Ядра слаймов, Взрывы бомб". Происходит это по принципу "Изучаем отчеты, вносим в консоль, изучаем что нужно, обновляем базу, сбрасываем консоль, изучаем отчеты, синхронизируеся, используем очки" И так по кругу. 
#### Что должно было произойти
Ввели систему как в стелларисе, или же отключить кнопку ресета (но это обходится разбором сборкой консоли). Проблема комплексная и это надо решать
#### Что произошло на самом деле
Я будуччи ученым, на одном отчете о вскрытии за 10к очков, за 5 минут рекурсивной функции huyarimOchki(otchet);  имею максимальные изучения всех веток
#### Как повторить
"Изучаем отчеты, вносим в консоль, изучаем что нужно, обновляем базу, сбрасываем консоль, изучаем отчеты, синхронизируеся, используем очки" И так по кругу. 
#### Дополнительная информация:
Прокачка прототипов людука сбрасывается при сбрасывании консоли и обновлении. Проще говоря не сохраняется. Напишу отдельный ишью и про это

**Comment by Ahion** [comment]
> Ввели систему как в стелларисе

А как там в стелларисе? ))

**Comment by FelixRuin** [comment]
по времени
как я могу предположить

**Comment by Dominig12** [comment]
> по времени
> как я могу предположить

нет, там от очков вкладываемых в одну ветвь, а очки поступают из разных источников, в основном от исследователей, после изучения, система предлагает на выбор несколько исследований, и после выбора снова вкладываем в нее очки. В зависимости от того, какие исследования делали, будут падать технологии, например изучили что то редкое, например в археологии артефакт, может упасть редкая технологи я в ветках связанная с ней

**Comment by Ahion** [comment]
Не совсем понятно, но звучит интересно. Если напишешь на форуме по подробнее про то, как это может выглядеть в SS13, я с удовольствием почитаю. (только не в разделе дискуссий)

**Comment by ViDLiathan** [comment]
А вот на ТГ, если не ошибаюсь, помимо основного исследования пассивно падают очки. 
Может какое-то устройство, жрущее кучу энергии и дающее очки.

**Comment by LudwigVonChesterfield** [comment]
по поводу бага - должны сохранятся не только очки/технологии. но и способы которыми были получены очки. это даже в коде "реализовано", но похоже корректно не работает.

**Comment by Dominig12** [comment]
> по поводу бага - должны сохранятся не только очки/технологии. но и способы которыми были получены очки. это даже в коде "реализовано", но похоже корректно не работает.

там скорее фича в том, что очки которые уже были на сброшенной консоли, при обновлении остаются, в этом суть абуза

**Comment by Kortez90** [comment]
А я вас предупреждал. Лечить симптомы вместо лечения корня не стоит.
Проблема в самой системе очков, а если конкретнее, в системе их хранения и реализации. В целом, можно вообще весь фарм перекрыть, переписав систему начисления. Мне было лень ковыряться с доступом из определенных переменных в другие переменные, так что страдайте сами, продолжая клепать бесполезные заплатки.
Возвращаясь к теме, ATM одно существования начисления очков за ЭМИ уже фарм и выглядит смешно. При ресете консоль по-прежнему сбрасывает очки из даты, но также возвращает все уровни и **не сохраняет изученные прототипы**. Внесите постоянную переменную, которая не сбрасывается и сохраняет все схематики скрыто и проблема решена. И как я ранее предлагал - удалите уже кнопку ресета и все.
