### ISSUE TITLE
Мелок мима и клоуна сразу кончается, когда его пытаешься заюзать где-нибудь

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#494]
#### Подробное описание проблемы
Мелок мима сразу заканчивается, как пробуешь что-то написать.
#### Что должно было произойти
Мелок не должен был исчезнуть.
#### Что произошло на самом деле
Мелок исчез сразу при первом использовании.
#### Как повторить
Взять мелок мима и использовать на полу.

**Comment by Skippeer12** [comment]
Кастомные мелки клоуна и мима сломаны, так что лучше юзать обычные, которые можно заказать в карго.

**Comment by Damirrus1** [comment]
У мима мелок особенный, нуарный.

**Comment by Skyrull** [comment]
У клована тоже.

**Comment by volas** [comment]
#647
