### ISSUE TITLE
Изучение и улучшение прототипов сбрасывается при ресете и обновлении консоли

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#4940]
#### Подробное описание проблемы
Изучив все, а так же синхронизировав изучения с сервером, тебе по какой то причине срочно надо сбросить консоль (точно не абуз), а потом, обновив ее обратно, ты обнаруживаешь, что все прототипы, все достижения по прототипам сбросились, что неприятно, так как изучение прототипов, это много ресурсов, или очков
#### Что должно было произойти
При синхронизации, после ресете, после обновлении назад, прототипы должны сохраниться
#### Что произошло на самом деле
Все изучения прототипов сбросились
#### Как повторить
Синхронизировать с сервером, сбросить консоль, восстановить все назад с помощью сервера

**Comment by LudwigVonChesterfield** [comment]
при ресете - это абсолютно логично. сбрасываешь "знания" - забываешь как делать хорошие прототипы, насчёт "обновления", я гляну.

**Comment by LudwigVonChesterfield** [comment]
Перечитал, понял. Тут хочется чтобы синхронизировало качество прототипов на сервере. Я так это не задумывал, и хотел чтобы прототипы калибровались от машины.

Если есть желающий это сделать - пускай.
