### ISSUE TITLE
Дюп при помощи артефакта

### ISSUE THREAD

**Issue by Gort133** [TauCetiStation/TauCetiClassic#4943]
#### Подробное описание проблемы
Если использовать на ком либо граб,это займет ячейку твоей руки и это считается предметом.Суть бага: артефакт (alien machine) спокойно берет как предмет граб.

#### Что должно было произойти
при попытке затащить граб,в артефакт должен был залезть человек,которого ты грабнул или же сватил 
#### Что произошло на самом деле
артефакт забрал у меня из руки граб и из него можно было сделать предмет,а человек которого я грабнул остался так.
#### Как повторить
подойти к артефакту alien machine 
схатить куклу или игрока любой рассы(grab)
нажать на артефакт рукой занятой грабом
вуаля- артефакт взял граб как предмет , и может синтезировать из него предмет.

**Comment by 4310V343k** [comment]
убери1

**Comment by KIBORG04** [comment]
Бумага тоже бесконечная

**Comment by Dominig12** [comment]
> Бумага тоже бесконечная

не бесконечная, в paper bin ограниченное количество бумаги

**Comment by SomeUselessGuy** [comment]
Книги бесконечные...

**Comment by Gort133** [comment]
> Книги бесконечные...

сам факт того что из ничего можно делать что-то
