### ISSUE TITLE
Ян - Прилипание прицела на нём

### ISSUE THREAD

**Issue by Andreikepka** [TauCetiStation/TauCetiClassic#4952]
#### Подробное описание проблемы
После того, как кто-то возьмёт Яна в прицел, то на нём он останется. Не важно, если ты ушел далеко от того, кто взял тебя в прицел.

#### Что должно было произойти
Прицел должен уйти с Яна, как и со всех.

#### Что произошло на самом деле
Этот постоянный прицел на Яне видят все, тем самым вызывает конфуз у всех, и дискомфорт для игрока на Яне.

#### Как повторить
Просто прицелится в Яна с чего угодно: Пирометры или оружие

#### Дополнительная информация:
![Screenshot_1783](https://user-images.githubusercontent.com/62898551/78018087-efc06800-7355-11ea-9eb2-9a52a188e224.png)

**Comment by 4310V343k** [comment]
Весь раунд с прицелом бегал, а скрин не сделал

**Comment by Andreikepka** [comment]
Добавил скриншот
