### ISSUE TITLE
Толстая проблема

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#4953]
#### Подробное описание проблемы
Когда ты толстый и ты или другой человек использует не хелп интент, тебе пишется что ТЫ не можешь столкнуть ЕГО толстую задницу с пути
#### Что должно было произойти
Наоборот
#### Что произошло на самом деле
То что написано 2мя пунктами выше
#### Как повторить
Стать толстым и попытаться толкнуть когото

**Comment by LudwigVonChesterfield** [comment]
#4675
