### ISSUE TITLE
Водород не отображается в ящике с рудами

### ISSUE THREAD

**Issue by 4310V343k** [TauCetiStation/TauCetiClassic#4955]
#### Подробное описание проблемы
При загрузке водорода в ящик с рудами, он там не отображается
<details>
  <summary>Фотокарточки</summary>
  
  
![image](https://user-images.githubusercontent.com/56449763/78054703-219ff180-738b-11ea-9fed-dd99409ecd5d.png)
![image](https://user-images.githubusercontent.com/56449763/78054801-45fbce00-738b-11ea-9fb0-c26329b22725.png)

</details>

#### Что должно было произойти
Там есть количество водорода
#### Что произошло на самом деле
Там он даже не упоминается
#### Как повторить
Положить один raw hydrogen в ore box, profit
#### Дополнительная информация:
Как это еще никто не заметил? Видео не будет, так как я тупой

**Comment by Avatar4** [comment]
Но ведь Водорода в чистом виде в природе вообще не должно быть, или это игровая условность

**Comment by 4310V343k** [comment]
Очевидно, игровая условность
Это не отменяет факта того, что в ящике он не отображается
Кстати, вот это тоже неправильно отмечено
![image](https://user-images.githubusercontent.com/56449763/78228542-82d4db80-74d7-11ea-8e79-19b0cf6d4425.png)

**Comment by Ambassadoing** [comment]
Как это "не отображается"? Я вчера играл и у меня добытый водород замечательно отображался в ящике. 🤔
