### ISSUE TITLE
[Bug] Шахтерский модуль

### ISSUE THREAD

**Issue by MrFoxik** [TauCetiStation/TauCetiClassic#496]
#### Подробное описание проблемы
Борг с модулем шахтера, у него есть рюкзак который подбирает руду автоматически если по ней пройти.
Если на быстром слоте активировать совершенно другой или этот же предмет (рюкзак) и поднять руду.
Предмет сброситься и исчезнет в инвентарь.
Придется активировать все на быстрые слоты заново.
#### Что должно было произойти
Активированные предметы на быстром слоте не должны удаляться.
#### Что произошло на самом деле
Предмет убрался в инвентарь борга.
#### Как повторить
Активировать любой предмет на быстром слоте борга, иметь в ещё одном слоте тот самый рюкзак для подбора руды, с активированным предмет просто пройти по руде и подобрать её.
#### Дополнительная информация:

**Comment by Damirrus1** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/485
Не это?
