### ISSUE TITLE
"Steal a piece of corgi meat" bug

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#4960]
#### Подробное описание проблемы
Я гибнул Яна и взял его мяско с собой на шаттл, ибо роль. Словил редтекст, когда мясо лежало в рюкзаке.
#### Что должно было произойти
Гринтекст. Ян = корги
#### Что произошло на самом деле
Редтекст. Ян =/= корги
#### Как повторить
Убейте Яна и изнасилуйте его за трейтора-ГП и не парьтесь целый раунд по поводу необходимости искать мясо корги. Разочаруйтесь в конце раунда.
#### Дополнительная информация:
Яны должны страдать

**Comment by LudwigVonChesterfield** [comment]
Это с каких-то пор уже не актуально.
