### ISSUE TITLE
[Proposal] Разделение должностей Nurse и Medical Doctor

### ISSUE THREAD

**Issue by LtSaavik** [TauCetiStation/TauCetiClassic#4962]
#### Подробное описание проблемы
В данный момент имеется возможность выбора должности, занимаемой на слоте "Medical Doctor".
![image](https://user-images.githubusercontent.com/37975428/78216309-36cb6c00-74c2-11ea-9fc2-4ffd83ea91fa.png)
Очевидно, что разделение подразумевалось сугубо внутриигровое-ролеплейное, такое, как:
- **Доктор общей практики** [Medical Doctor] - _и швец, и жнец, и на дуде игрец_. Может всё. **_Высшее образование._**
- **Хирург [Surgeon]** - обитает в операционной. **_Высшее образование._**
- **Медсестра [Nurse]** - подай-принеси. **_Среднее профессиональное образование._**

И вот с медсестрой возникает проблема.
Слотов врачей на сервере - четыре. То есть, медсестра занимает именно слот лечащего врача. 
В то же время, по сугубо ролевым условностям, она (или "он", медбрат, но для простоты далее будет просто "медсестра") не имеет права практиковать лечение, кроме первой медицинской помощи и обработки ран, и, тем более, оперировать.
Но должна.
Ибо слот врача - занят, и люди просто не поймут, если медсестра будет становиться в позу и говорить "А я не умею". Доступ есть - иди оперируй, иначе нафиг со слота.

С игровой стороны вполне логично - ведь и четырёх врачей зачастую мало в напряжённых раундах (два по операционным, два на приёме), а тут ещё один будет отрываться на вот такую вот "позу". Но с ролевой точки зрения - полная фигня.
В итоге, становится непонятно, зачем вообще берёшь эту должность.

#### Что должно было произойти

**Предложение**. Вынести медсестру отдельной должностью (как детектива в СБ, например) с ёмкостью в два слота.
Тогда в медбее будет два человека на обслуживании - таком, как мытьё полов, отмывание инструментов от крови, пополнение медикаментов, настройка крио, переноска тел и т.п., то есть, всё то, что сейчас занимает докторов вместо лечения, плюс, не будет проблем с выполнением работ, не доступных по ролевой составляющей для данной должности.

#### Что произошло на самом деле
Занял слот медика - будь добр вкалывать, как полновесный врач, а не только прибирайся по медотсеку.
#### Как повторить
Зайти в игру, выбрав должность Nurse на сервере, где много людей, либо нет докторов.

**Comment by CeUvi** [comment]
Надо сделать медсестру подтипом интерна.

**Comment by LtSaavik** [comment]
> Надо сделать медсестру подтипом интерна.
Такое, на самом деле. Сам об этом думал, но в случае интерна это будет бесполезное чудо без доступов. 
То есть, надо прибраться в операционной? Зови дохтура.
Надо принести что-нибудь со склада? Зови дохтура.

И зачем оно такое надо? Ведь при таком раскладе доктору будет проще самому себе прибраться либо принести, а нурсик станет штукой даже бесполезнее, чем интерн. Интерн, он же, типа, будущий медик и может получить повышение в ходе обучения, а куда повысится медсестра? В доктора?

Вариант с отдельной медсестрой всё-таки оптимальнее.

**Comment by FelixRuin** [comment]
о
добрый ишус
пойду сделаю

**Comment by Kortez90** [comment]
> нурсик станет штукой даже бесполезнее, чем интерн

Они и на данный момент такие.

В этом нет смысла, учитывая мета-поведение вообще всех и "новые" правила. В медицинском отсеке **никто** не убирается. Наличие медсестры только займет место в и без того тесном отсеке. А вот то, что они занимают слоты врачей - не очень хорошо, но решаемо добавлением медсестер в ассистенты.

**Comment by GermanSUS** [comment]
Сам играю за медсестру. Да, в основном  я занимался мытьем полов клинером и перетаскиванием апатиков в палаты или же в крио. Так же рп составляющая в выдаче гематогенов людям после операции. 
Что могу сказать. Нужно и в правду вынести медсестру в отдельный слот, но доступ оставить тот же. 
Запретить метагейство на операции (если случаи не критичны) ну и все как бы. Мы же не хотим что бы милые медсестрички исчезли?

**Comment by ViDLiathan** [comment]
(И пустить в них ксеносов)

**Comment by Xianetta** [comment]
ужасная идея, текущая система намного лучше, она более универсальная и гибкая. а новая- это лишние ограничения (как в плане слотов так и ролеплейные) и потенциальные новые баны за ролеплей. более того, по такой логике нужно разделять вообще все профессии. например у нас есть роботист, который может быть специалистом по экзоскелетам или по киборгам. их тогда тоже нужно разделять. или инженеры- электрики и техники. и с учеными тоже самое. но пристали почему-то именно к медсестре. все эти подпрофессии- это просто незначительные ролеплей- элементы, которые ты можешь выборочно соблюдать или игнорировать. и вообще, не слишком ли много ограничительных обновлений, которые все портят? может вместо них добавите в игру что-то новое вместо того, чтобы портить старое?

**Comment by LudwigVonChesterfield** [comment]
уберите подпрофы и дайте возможность вызывать дроппод с нарядом медсестрички-хирурчика-прочего сброда

**Comment by AndroBetel** [comment]
лядук зашел на тг и увидел дропподы
