### ISSUE TITLE
[Proposal] Емаг маяка мусорщиков

### ISSUE THREAD

**Issue by TheLustOfBlood** [TauCetiStation/TauCetiClassic#4963]
Предложение добавить маяку мусорщиков эффект от емага. Например, при емаге маяка он будет становиться красным и будет повышен шанс на кучки синдиката, оружия, или же одежды, что немного облегчит жизнь мусорщика триторам, но будет полностью тратиться емаг, ещё есть вариант что при емаге маяка следующий запуск будет с гораздо большим шансом на ранее перечисленные кучи мусора, но это будет как бы один раз, чтобы снова запустить такой нужно будет снова емагнуть маяк. :bad:

**Comment by Sage4or** [comment]
Второй вариант определенно лучше

**Comment by GermanSUS** [comment]
Взломал маяк > выпала куча > откопал ещё емаг > повторить
Идея нравится, кодить её я конечно же не буду
