### ISSUE TITLE
Виноград не выжимается.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#4964]
#### Подробное описание проблемы
Виноград не выжимается в выжималке (All-In-One Grinder) в сок.
#### Что должно было произойти
Должен был произойти сок.
#### Что произошло на самом деле
Он не произошел.
#### Как повторить

- Взять несколько веточек винограда.
- Сунуть в выжималку.
- Сунуть банку в выжималку.
- Нажать "Juice".
- Получить ничего.

**Comment by Akellazp** [comment]
Пробуй гринд

**Comment by Kortez90** [comment]
> 
> 
> Пробуй гринд

Сахар и нутрименты.

**Comment by UsadoSmokk** [comment]
все понятно, похоже такой функции просто нет, могу попробовать решить
![image](https://user-images.githubusercontent.com/56721822/78386336-34226100-75ff-11ea-85f5-15cec0a31b52.png)
