### ISSUE TITLE
Неразрушаемые гирдеры

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#4967]
#### Подробное описание проблемы
Все что делитает стены, имеет шанс сорвать просто металл со стены и оставить неразрушаемый гирдер окторый можно только раскрутить.
От этого страдают халки, дедсад с пульсачами, конструкты культа и все что может ломать ручками стены, но каким-то волшебным образом не может сломать гирдер
#### Что должно было произойти
Гирдеры ломаются
#### Что произошло на самом деле
Закликиваешь гирдер а потом идешь закликивать другую стену в надежде что ее делитнет
#### Как повторить
Попытайтесь сломать гирдер за халка/конструкта/дедсадовца с пульсачом

**Comment by AndroBetel** [comment]
гирдеры ломаются но у них куча хп

**Comment by Sage4or** [comment]
жесть моцорд малогей.......

те же констракты культей могут моментально сломать гирдеры, а могут и полчаса стоять долбить, там вроде шанс какой то есть на моментальное уничтожение

**Comment by T6751** [comment]
халк: 1 удар
пульсач: 3 выстрела
артифайсер: 40 ударов

**Comment by T6751** [comment]
гирдеры разрушаются, иссуй можно закрывать
