### ISSUE TITLE
Люди могут носить НТ бричер

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#4968]
#### Подробное описание проблемы
Люди могут носить риг унатхов из евы (НТ бричер)
#### Что должно было произойти
Они не могут
#### Что произошло на самом деле
Они могут
#### Как повторить
Надеть бричер за человека
#### Дополнительная информация:
Возможно это сломал один из недавних пров

**Comment by Akellazp** [comment]
Проблема все еще актуальна

**Comment by Akellazp** [comment]
Все еще актуально

**Comment by Sakuya-Izayoi** [comment]
а что в нт бричере такого, что делает его непригодным для людей?

**Comment by cool20141** [comment]
Обычный рост унатхов ~2м, а так как могут быть и больше, то явно данный риг с запасом по размеру. Также если приглядеться, то можно увидеть, что там присутствует нехило так бронепластин, что явно его делает тяжеленным пиздец. И вот представь, Человек 1.70 ростом пытается надеть на себя эту громадину, а потом еще и умудряются как-то в ней перемещаться. Бред же

**Comment by Akellazp** [comment]
Все еще актуально
