### ISSUE TITLE
Если у тебя будет вещь в руках и Одиссей закинет тебя в слиппер, то вещь пропадает вникуда.

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#497]
#### Подробное описание проблемы

Если у тебя будет какая-нибудь вещь в руке и Одиссей (мех) закинет тебя в слиппер, то вещь пропадает и ее не вернуть.
#### Что должно было произойти

Вещь должна была выкинуться на пол.
#### Что произошло на самом деле

Вещь пропала.
#### Как повторить

Взять что-нибудь в руку и попросить меха засунуть тебя в слиппер.
#### Дополнительная информация:

Название СПЕШЛ фор ЗВе

**Comment by KatoMarika** [comment]
Подобное вроде еще случается с криосном, но лучше проверить.
