### ISSUE TITLE
[Proposal]Добавить систему страниц в статьи, как в комментариях.

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#4971]
#### Подробное описание проблемы
Может это и баг. 
У статей такая же проблема, какая была и с комментариями. Из-за большого количества сообщений с фотокарточками в одной статье, юзеры будут долго загружать страничку, может пару секунд. Проблема из-за большого количества итераций.
#### Что должно было произойти
Статья открывается быстро, но при этом появляется возможность листать страницы.
#### Что произошло на самом деле
Статьи открываются медленно.
#### Как повторить
Спамить большими соощениями с фотками.
#### Дополнительная информация:
Это можно пофиксить внедрением страниц, как это я сделал с комментариями.

**Comment by KIBORG04** [comment]
В добавление костыля, хотя как сделать с кэшированием я не знаю.

**Comment by KIBORG04** [comment]
Там ноноуи, в газете обычная хтмлка

**Comment by Kortez90** [comment]
Так замени все на nano. Интерфейсы мехов вообще на яве.

**Comment by KIBORG04** [comment]
Ага, это прийдется либо все писать заного, либо как-то интегрировать старый код
