### ISSUE TITLE
Фороновые двери создают непропорционально огромный ущерб

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#4972]
#### Подробное описание проблемы
С помощью форона можно сделать двери, которые в свою очередь если ударить активированой горелкой - грифонят всю станцию адским пламенем. Любимая вещь всяких набегаторов и прочих нелюдей. Урон от такого прикола слишком велик
#### Что должно было произойти
Ничего или намного меньший ущерб (небольшой взрыв что не продырявит плитку например)
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/19417166/78398371-a5601500-75fb-11ea-9ead-4b5e4fa17b2f.png)

#### Как повторить
Создать фороновые двери из форона, поджечь

**Comment by Sage4or** [comment]
не баг, а тупая фича

**Comment by Belfogor** [comment]
Пусть хоть фича, но ее нужно убрать.

**Comment by KIBORG04** [comment]
Либо ослабить

**Comment by Avatar4** [comment]
Здесь нет флага "Тупая фича"

**Comment by Avatar4** [comment]
Забавно однако, что я этот скрин взял из дискорда и не умирал как раз

**Comment by 4310V343k** [comment]
На этом скрине не одна дверь. Просто асиситуха расставил их по всех станции, по несколько штук, и все поджог

**Comment by totallynotdedawa2** [comment]
одна фороновая дверь подожженная в офисе карго, сжигает абсолютно весь отсек. надо немного понерфить ее
