### ISSUE TITLE
Ошибка компиляции taucetistation.dme

### ISSUE THREAD

**Issue by Fr4Ckt3r** [TauCetiStation/TauCetiClassic#4975]
#### Подробное описание проблемы
При запуске компиляции выводится множество ошибок (Код не трогал)
#### Что должно было произойти
Всё должно было скомпилироватся
#### Что произошло на самом деле
Появилось множество ошибок.
#### Как повторить
Запустить компиляцию на BYOND версии 513.1517
#### Дополнительная информация:
loading taucetistation.dme
loading interface\skin.dmf
code\__HELPERS\text.dm:322:warning: lentext: lentext is being phased out; replace with length
code\__HELPERS\text.dm:322:warning: lentext: lentext is being phased out; replace with length
code\__HELPERS\text.dm:324:warning: lentext: lentext is being phased out; replace with length
code\__HELPERS\text.dm:344:warning: lentext: lentext is being phased out; replace with length
code\modules\mob\mob_helpers.dm:188:warning: lentext: lentext is being phased out; replace with length
code\modules\mob\mob_helpers.dm:189:warning: lentext: lentext is being phased out; replace with length
code\modules\organs\blood.dm:420:warning: lentext: lentext is being phased out; replace with length
code\modules\organs\blood.dm:421:warning: lentext: lentext is being phased out; replace with length
code\modules\json\JSON Writer.dm:47:warning: lentext: lentext is being phased out; replace with length
code\datums\music_player.dm:249:warning: lentext: lentext is being phased out; replace with length
code\datums\music_player.dm:256:warning: lentext: lentext is being phased out; replace with length
code\datums\music_player.dm:307:warning: lentext: lentext is being phased out; replace with length
code\datums\music_player.dm:185:warning: lentext: lentext is being phased out; replace with length
code\datums\music_player.dm:201:warning: lentext: lentext is being phased out; replace with length
code\modules\research\xenoarchaeology\finds\finds_talkingitem.dm:86:warning: lentext: lentext is being phased out; replace with length
code\modules\research\xenoarchaeology\finds\finds_talkingitem.dm:91:warning: lentext: lentext is being phased out; replace with length
code\game\machinery\status_display.dm:128:warning: lentext: lentext is being phased out; replace with length
code\game\machinery\doors\brigdoors.dm:365:warning: lentext: lentext is being phased out; replace with length
code\modules\research\xenoarchaeology\artifact\artifact_replicator.dm:100:warning: lentext: lentext is being phased out; replace with length
code\modules\research\xenoarchaeology\artifact\artifact_replicator.dm:102:warning: lentext: lentext is being phased out; replace with length
code\modules\organs\organ_external.dm:473:error: clamp: invalid proc name: reserved word
code\modules\mob\hear_say.dm:236:warning: lentext: lentext is being phased out; replace with length
code\modules\mob\mob.dm:292:warning: lentext: lentext is being phased out; replace with length
code\modules\mob\living\silicon\robot\examine.dm:39:warning: lentext: lentext is being phased out; replace with length
code\modules\mob\living\silicon\robot\examine.dm:39:warning: lentext: lentext is being phased out; replace with length
code\modules\mob\living\silicon\robot\examine.dm:39:warning: lentext: lentext is being phased out; replace with length
code\modules\mob\living\carbon\human\examine.dm:515:warning: lentext: lentext is being phased out; replace with length
code\modules\mob\living\carbon\human\examine.dm:515:warning: lentext: lentext is being phased out; replace with length
code\modules\mob\living\carbon\human\examine.dm:515:warning: lentext: lentext is being phased out; replace with length
code\modules\json\JSON Writer.dm:19:warning: lentext: lentext is being phased out; replace with length
code\modules\admin\DB ban\functions.dm:416:warning: lentext: lentext is being phased out; replace with length
code\modules\admin\DB ban\functions.dm:418:warning: lentext: lentext is being phased out; replace with length
code\modules\admin\DB ban\functions.dm:420:warning: lentext: lentext is being phased out; replace with length
code\modules\admin\DB ban\functions.dm:422:warning: lentext: lentext is being phased out; replace with length
code\__HELPERS\text.dm:18:warning: lentext: lentext is being phased out; replace with length
code\game\objects\items\weapons\paint.dm:34:warning: lentext: lentext is being phased out; replace with length
taucetistation.dmb - 1 error, 35 warnings (4/4/20 11:45 pm)

**Comment by Fr4Ckt3r** [comment]
Лог брал из Dream Maker

**Comment by SpaiR** [comment]
Мы не делали переход на 513 бьенд, для работы с кодом нужно использовать 512 бьенд.
