### ISSUE TITLE
[Proposal] Failcheck для шлюзов в отбытии.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#4977]
#### Подробное описание проблемы
Дело копеечное.
Добавляем к автоматической блокировке дверей после отлета шаттла фейлчек поломок/отсутствия питания. Если у двери отрезан провод, снята панель или шлюз по каким-то другим причинам не может открыться, то создается автоматический анонс и таймер отлета продлевается на 5-10 минут, но только в случае, если шаттл не экстренный.

**Comment by Dominig12** [comment]
https://www.youtube.com/watch?v=QKfkMqqNwWg
