### ISSUE TITLE
Голодек: если закинуть баскетбольный мяч в упор в кольцо, то мяч пропадает

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#498]
#### Подробное описание проблемы
Взял мяч, подошел в упор к кольцу, кликнул по кольцу мячом, мяч исчез
#### Что должно было произойти
Мяч должен был появиться под кольцом
#### Что произошло на самом деле
Мяч исчез
#### Как повторить
Взять мяч, подойти к кольцу, кликнуть по кольцу

**Comment by ZVee** [comment]
Зачем репорты нефикшенные, на которые ПР висит даже, закрываем?
