### ISSUE TITLE
[Proposal] Добавить возможность возгорания от зажигалки

### ISSUE THREAD

**Issue by PunishedHideo** [TauCetiStation/TauCetiClassic#4981]
Если кукла покрыта чем то воспламеняемым(При examine видно "covered in something flammable"), то включённая зажигалка в её руке не поджигает её. Если добавить возможность возгорания через зажигалку, это принесёт немного реализма.

**Comment by LudwigVonChesterfield** [comment]
а это точно так работает? вот сейчас если кликнуть по кукле покрытой чем-то воспламеняемым то она загорится, а если не тыкнуть - не загорится. от того что я буду на дистанции протянутой руки зажигать вероятно я не загорюсь

**Comment by PunishedHideo** [comment]
Неправильно сформулировал, отредактировано.

**Comment by LudwigVonChesterfield** [comment]
my point still stands

**Comment by Sage4or** [comment]
Сколько раз не обливался бензином, пока заправлял зиппо, ни разу не загорался при поджоге зажигалки

Не думаю, что это добавит реализма, да и не нужно особо. Вон, если курить будешь в помещении с фороном - загоришься, мало этого?

**Comment by Motzord** [comment]
Не актуально, не нужно
