### ISSUE TITLE
Спрайты вскрытия спу

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#4983]
#### Подробное описание проблемы
При "вскрытии" спу во время "операций" видны органические внутренности человека
#### Что должно было произойти
Роботические внутренности
#### Что произошло на самом деле
Органические внутренности
#### Как повторить
"Вскрыть" спу

**Comment by UsadoSmokk** [comment]
а это баг?

**Comment by UsadoSmokk** [comment]
это просто недоработка, вроде у них нет своих оверлеев на операции

**Comment by Kortez90** [comment]
> 
> 
> это просто недоработка, вроде у них нет своих оверлеев на операции

Их нужно сделать.
