### ISSUE TITLE
Непропорциональный урон СПУ.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#4984]
#### Подробное описание проблемы
Если ты железный - бойся вставать под стульями. Потому что иначе тебя ждет кара в виде урона. Откуда он взялся, как мог стул проломить железный монитор - загадка.
Если ты железный - бойся падать в риге. Потому что иначе тебя ждет кара в виде урона. Откуда он взялся, как мог поток воздуха ударить спу о стену с такой силой, что у того пробилась грудная клетка - загадка.
У людей такие мини-раны заживают, а у СПУ - нет. Дисбаланс и бред в плане реалистичности, так как поломать железную гидравлику все же проблематичней, чем мясной мешок.
#### Что должно было произойти
СПУ не получают урона при ударе о стену в риге и при ударах головой о столы/стулья.
#### Что произошло на самом деле
СПУ получают. И это крайне странно.
#### Как повторить
- Стать СПУ.
- Удариться о стул, ползая под ним.

**Comment by Dominig12** [comment]
Ты забыл упомянуть про, если в вас кинули предмет, вы получите вмятину. Потому что корпус из аллюминия

**Comment by TungstenOctopus** [comment]
Имеет смысл, как решение, ввести новую механику сопротивления урону, но не ту, которая сейчас, процентовая, а в виде константы: грубо говоря, урон ниже порога в, скажем, 5 единиц не наносится, и, опционально, от каждого нанесения урона режется 5 единиц дамага. Я когда-то такое планировал для ящеров, и вообще ящитаю это необходимо.

**Comment by Kortez90** [comment]
> 
> 
> Имеет смысл, как решение, ввести новую механику сопротивления урону, но не ту, которая сейчас, процентовая, а в виде константы: грубо говоря, урон ниже порога в, скажем, 5 единиц не наносится, и, опционально, от каждого нанесения урона режется 5 единиц дамага. Я когда-то такое планировал для ящеров, и вообще ящитаю это необходимо.

Слишком много бесполезных страданий. Урон для спу при низком пороге, например урон от брошенной коробки или стула можно вообще отрезать, так как он не нужен и создан для человеков, которые этот урон регенерируют.

**Comment by TungstenOctopus** [comment]
Потому я и предлагаю решение: добавить отдельным раса типа СПУ порог, т.е. маленький дамаг не будет наносиься.

**Comment by FelixRuin** [comment]
молодцы
вы придумали то
что я совсем недавно сделал для спу
можете поправить примерно одну переменную с 1 до 4-5 и веселиться

**Comment by Kortez90** [comment]
> 
> 
> можете поправить примерно одну переменную с 1 до 4-5 и веселиться

Правь. Ты же делал.

А вообще, есть другое решение, более кардинальное. Уберем охис.

**Comment by FelixRuin** [comment]
я делал для коробок 
ибо так сказал ксеновизор по телевизорам
если хотите что-то править ещё
то ваше дело
ссылку на пр могу кинуть
думаю один иф вы даже через сайт изменить можете и сделать пр

**Comment by Kortez90** [comment]
> 
> 
> думаю один иф вы даже через сайт изменить можете и сделать пр

Тогда тем более, зайди и сделай.

**Comment by FelixRuin** [comment]
так вам это нужно
вы и сделайте
если руки хотяб есть

**Comment by Kortez90** [comment]
> 
> 
> так вам это нужно
> вы и сделайте
> если руки хотяб есть

А у тебя нет?
Чего ломаешься, если там один if поменять надо? Заодно и issue закроешь.
