### ISSUE TITLE
Ксеносы нюковцы не могут использовать риг

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5001]
#### Подробное описание проблемы
При попытке применить модкид ксеносов на риг нюки, риг исчезает оставляя ящера/таярру/скрелла  с голой жопой на шаттле
#### Что должно было произойти
Ксеносы либо получают свой риг, либо вообще не попадают в горлексы
#### Что произошло на самом деле
Ксеносы на нюке бесполезны
#### Как повторить
Зайти за ксеноса в нюку и попытаться надеть риг
#### Дополнительная информация:
Просто выпилите ксеносов из нюки

**Comment by AndroBetel** [comment]
а какой именно риг?

**Comment by Motzord** [comment]
> а какой именно риг?

вроде трабл с обоими ригами.

**Comment by AndroBetel** [comment]
мой прокол, зафиксю!

**Comment by Motzord** [comment]
> мой прокол, зафиксю!

просто выпили ксеносов из нюки

**Comment by AndroBetel** [comment]
не

**Comment by Akellazp** [comment]
прикол в том что риг не исчезает а становится невидимым
