### ISSUE TITLE
[Bug] Ксеносы и нюка.

### ISSUE THREAD

**Issue by TheLustOfBlood** [TauCetiStation/TauCetiClassic#5002]
#### Подробное описание проблемы
если вы нюкер ксенос и попробуете использовать на синдириг модкит, он просто исчезнет
#### Что должно было произойти
летишь играть в каэс на станцию
#### Что произошло на самом деле
сидишь на шаттле и кумаришь, педали не хотят давать скафандр
#### Как повторить
зайти за таяру/согхана/скрелла/или другую ксенорасу
#### Дополнительная информация:
я ебал так играть, извините за мат конечно, но пригорело у меня знатно, вижу уже не первый раз такое

**Comment by Akellazp** [comment]
прикол в том что риг не исчезает а становится невидимым
