### ISSUE TITLE
Раздача ролей происходит после раздачи професссий.

### ISSUE THREAD

**Issue by Marselinel** [TauCetiStation/TauCetiClassic#5005]
#### Подробное описание проблемы
В начале раунда с высшим приоритетом на ИИ я стал СМО, а ИИ не было среди игроков. Видимо, это случилось из-за того, что тот, кому повезло стать ИИ выпала роль вокса, а сам ИИ исчез.
Также я слышал от администратора, что таким образом можно спалить режим (когда профа не занята, а приоритет наивысший)
P.S.: я в этом не уверен.
#### Что должно было произойти
Сначала должны провериться рольки, а затем профы
#### Что произошло на самом деле
Проверка прошла с точностью до наоборот
#### Как повторить
Поставить высший приоритет на профу, не попасть на неё, увидеть, что эта профа незанята, наслаждаться магом/нинжей/воксами/нюкой.

**Comment by Kortez90** [comment]
Если бы поставил только ИИ, то кинуло бы туда.
И что мешает зайти после страта, не втыкаясь в деклер?

**Comment by Sage4or** [comment]
> И что мешает зайти после страта, не втыкаясь в деклер?

желание получить малфа\тритора..

**Comment by Lizurt** [comment]
Емнип главы имеют повышенный приоритет и если нет главы, а у тебя есть на неё даже не высший приоритет, то тебя все равно туда кинет.

Пару лет назад столкнулся с этим же, но за это время я и забыл от кого узнал эту инфу. Так что это тоже не точно, стоит проверить в коде

**Comment by Zmey25** [comment]
Я что-то тоже такое помню, хотя возможно я путаю с ревой, где на глав кидает чаще обычного.

**Comment by LudwigVonChesterfield** [comment]
У глав преф выше остальных.
