### ISSUE TITLE
[proposal] Добавить строку хаба с количеством активных педалей или индикатор no admins online

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5006]
#### Подробное описание проблемы
Заходишь на сервер попедалить
@
Там уже педалят 5 человек
#### Что должно было произойти
Видишь что педалят 5 человек
@
Идешь педалить на другой сервер

**Comment by volas** [comment]
не та репа, да и некуда, ~~страдай~~
