### ISSUE TITLE
Преф "Ghost Sight" не сохраняется

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#5007]
#### Подробное описание проблемы
Преф "Ghost Sight" не сохраняется, несмотря на нажатие "Save Slot". Причем подобное происходит после перезахода через обсерв.
#### Что должно было произойти
Бесполезная настройка должна была сохранить свое состояние.
#### Что произошло на самом деле
Бесполезная настройка не сохранила свое состояние и включилась обратно.
#### Как повторить
- Заходим в лобби.
- Заходим в перфы.
- Ставим "Only nearest creatures" в "Ghost Sight".
- Сохраняем слот.
- Заходим в раунд. Играем.
- Выходим.
- Заходим в следующий раунд обсервой.
- Наслаждаемся спамом в чат.

 "(F) Fredderik Poisoned snores.
(F) Billy Herrington snores.
(F) Elizabeth Jenner snores.
(F) Jack Gordon sleeps soundly."

**Comment by 4310V343k** [comment]
Ghost Sight вроде включает выключает отображение других призраков

**Comment by JustEmpty** [comment]
Я уже создал такую же тему, называется Emotes.

**Comment by Kortez90** [comment]
> 
> 
> Я уже создал такую же тему, называется Emotes.

Так сделай линк.

**Comment by volas** [comment]
@Lizurt можешь посмотреть?

**Comment by LudwigVonChesterfield** [comment]
#4831
