### ISSUE TITLE
Фултон не может отправлять запертые ящики

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#501]
#### Подробное описание проблемы
Засовываешь кучу предметов в ящик, закрываешь его, пытаешься отправить фултоном, ящик открывается, все содержимое вываливается, пустой ящик летит на корабль.
#### Что должно было произойти
Ящик должен был улететь вместе с содержимым.
#### Что произошло на самом деле
Ящик открылся и улетел на корабль.
#### Как повторить
Кликнуть фултоном по закрытому ящику
#### Дополнительная информация:
Отправлять ящики с предметами можно предварительно их заварив.

**Comment by Skippeer12** [comment]
Object->Toggle Open.
И вуаля! Ящик закрывается.

**Comment by Skyrull** [comment]
Не баг, а фича.
