### ISSUE TITLE
Нерабочие вирусы

### ISSUE THREAD

**Issue by achrom1c** [TauCetiStation/TauCetiClassic#5011]
#### Подробное описание проблемы
Создал вирус --> Взял шприц с чистой кровью --> Заразил эту ЧИСТУЮ кровь, что сделало ее ЗАРАЖЕННОЙ --> Вколол себе эту ЗАРАЖЕННУЮ кровь --> Не появилось надписей в чате, голод не стал восстанавливаться, иначе говоря, не произошло ничего --> Взял у себя кровь в пустой шприц -->  Проверил кровь в инкубаторе --> Как оказалось, в крови нету НИКАКИХ вирусов, она ЧИСТА как слеза младенца.

#### Что произошло на самом деле
Заражение вирусом,  и развитие симптомов как полезных, так и вредных 
#### Как повторить
Создать вирус и попробовать заразить себя, или кого-то еще
#### Дополнительная информация:
Возможно сейчас вирусология временно отключена, а я просто об этом не знаю? Тогда извиняюсь, зря быканул

**Comment by Motzord** [comment]
А вирус который ты вкалывал себе распространялся на людей? Возможно тебе прокнул рандом и ты внезапно сам по себе имел антитела к вирусу

**Comment by Motzord** [comment]
Я посмотрел VV того вируса и антител в твоих куклах.

Во первых вирус действовал на ящеров, а твоя кукла не ящер.

Во вторых да, антитела совпали (скорее исходя из первого)

**Comment by 4310V343k** [comment]
Это именно так и работает. Если ты не заразился, то ты либо имеешь антитела, либо ты не подходишь по расе к вирусу

**Comment by achrom1c** [comment]
Первоначально вирус был только для унатхов, однако потом я его irradiate много раз что бы он подходил к хуманам. Однако в принципе я вас понял, спасибо за помощь

**Comment by Motzord** [comment]
Ишью закрой
