### ISSUE TITLE
Доступ СМО

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5012]
#### Подробное описание проблемы
У СМО должены быть доступы как у всех его подчиненных (как у всех глав), но он не имеет доступа как у парамедиков (минимальный в каждый отсек)
#### Что должно было произойти
У СМО доступ как у всех его подчиненных
#### Что произошло на самом деле
У СМО нет минимального доступов в отсеки как у парамедиков
#### Как повторить
Зайти за СМО и попытаться пройти, например, в РнД

**Comment by Kortez90** [comment]
Дело в том, что вы уже настолько поехали на механе, что игнорируете тот факт, что это ролеплейная игра. СМО **не должен** бегать вместо своих подчиненных на вызовы. СМО **не должен** рвать жопу, накидывая на спину дефибриллятор, когда рядом стоит три хирурга и кот. СМО **не должен** нестись на всех парах в генетику, клонировать глав, когда там есть генетики. СМО не врач. СМО - офицер. (Нет, не тот, что бегает за рольками с хлоркой.)

**Comment by Akellazp** [comment]
> Дело в том, что вы уже настолько поехали на механе, что игнорируете тот факт, что это ролеплейная игра. СМО **не должен** бегать вместо своих подчиненных на вызовы. СМО **не должен** рвать жопу, накидывая на спину дефибриллятор, когда рядом стоит три хирурга и кот. СМО **не должен** нестись на всех парах в генетику, клонировать глав, когда там есть генетики. СМО не врач. СМО - офицер. (Нет, не тот, что бегает за рольками с хлоркой.)

Парамедики: *отстутствуют* или *идиоты*
Люди в крите в отсеке куда у СМО нет доступа: Ну да ну да пошли мы нахер

**Comment by AndroBetel** [comment]
ну пусть смо просит ии открыть или инженеров зовет, это в любом случае не его работа бегать за ранеными, когда можно за этим послать кого-то другого

**Comment by Akellazp** [comment]
> ну пусть смо просит ии открыть или инженеров зовет

Самое то когда нужно срочно спасти человека

**Comment by TechCatOther** [comment]
У СМО должен быть полный доступ по всем его отделам. Зачем ему ограничивать доступ в отсек, при этом оставляя его ответственным за его работу? Так даже все проверить невозможно.

**Comment by ViDLiathan** [comment]
Сейчас опять затиранят #4016

**Comment by AndroBetel** [comment]
у хоса есть имплант лояльности так што...

**Comment by Kortez90** [comment]
> ХОС у нас супер охранник

Некоторые хосы не просто супер-охранники, а еще медики, капитаны, инженеры, ученые и маги в одном лице. Они бегают по всем отсекам и лечат/чинят/изучают забив на то, что на них в этот момент смотрит через один тайл хирург/ученый/инженер. Это надо карать бананами, но сколько педалям не пиши - "Здесь нет нарушения. Он совсем не метагей, а просто в отсеке никого нет.".

**Comment by Kortez90** [comment]
> имплант лояльности

Имплант лояльности не база данных с навыками персонала станции. Это _условное_ ограничение для роли. То бишь, хос не может сказать "Ебал я в рот капитана, пойду стрелять в карпов, потому что он мне не нравится.". Больше ничего.

**Comment by AndroBetel** [comment]
окей buddy но к чему это ты про знания и навыки

**Comment by Kortez90** [comment]
> к чему это ты

К тому, что хос не должен бегать по отсекам без необходимости. А они это делают. Делают, потому что ищут роль.

**Comment by Zmey25** [comment]
10лет ии прекрасно справлялся с открытием дверей, как тут набежали желающие халявного доступа

**Comment by LudwigVonChesterfield** [comment]
#4016

![image](https://user-images.githubusercontent.com/17705613/83392234-713b8180-a3fd-11ea-906b-87078195d309.png)
