### ISSUE TITLE
[Task] Оптимизация производства големовых армий

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#5013]
#### Подробное описание проблемы
Простота производства големов, особенно при большом онлайне в гостах. В результате чего ксенобиолог может создать себе отряд големов.

Сами големы обладают иммунитетом к вакууму, артериальному кровотечению, элеткричеству, боли и т.п.
Обладают перманентной броней:
Шлем armor = list(melee = 77, bullet = 66, laser = 44, energy = 44, bomb = 80, bio = 100, rad = 80)
броня armor = list(melee = 77, bullet = 66, laser = 44, energy = 44, bomb = 80, bio = 100, rad = 80)
А так же имеют 300хп.

#### Предложения по решению
Убрать у адамантивого слайма возможность создавать потомство из себе подобных. Сократить количество выведения адамантивых слаймов из золотых с 2х до 1го. 
Запилить фичу с привязкой голема к руне - Душа голема находится в руне на которой он заспавнился и если стереть руну то голем умирает.

#### Дополнительная информация:
Возможно в будущем потребуются и другие меры по балансу.

UPD 11.04.20 Завести фиксы:
- Обрубить возможность голему вступить куда-либо (культ, трелл, рева и т.д.);
- Обрубить возможность голему призвать другого голема;
- Убрать возможность получать какие-либо гены и использовать их;

**Comment by Kortez90** [comment]
Достаточно просто ввести ограничения в виде усложнения создания или увеличения ресурсов при создании.

**Comment by Ambassadoing** [comment]
Надо не качественно ограничивать, а КОЛИЧЕСТВЕННО. Пусть будут сильные, крепкие, но малочисленные.

**Comment by Kortez90** [comment]
> малочисленные

Привязать их максимальное кол-во к кол-ву игроков на сервере?

**Comment by Ambassadoing** [comment]
> Привязать их максимальное кол-во к кол-ву игроков на сервере?

Можно. Можно просто фиксированное количество сделать, мол, не более двух-трёх големов ВООБЩЕ. И/Или ограничение на количество подчинённых големов у одного игрока - не более одного голема. И выпилить наконец-то возможность активации адамантиевых рун самими големами. Даже боргам нельзя клепать себе подобных, так почему големам можно?

**Comment by GermanSUS** [comment]
Тогда нужны такие баффы дебаффы:
1 голем на человека
Голем не может стрелять
Голем имеет броню против всего на 80 (Что бы танчить)
ИМ ОБРУБАЮТ ВСТУПЛЕНИЕ В КУЛЬТ!!!!!
Голем не может призывать голема

**Comment by Ambassadoing** [comment]
> Голем не может стрелять

Уже.

> ИМ ОБРУБАЮТ ВСТУПЛЕНИЕ В КУЛЬТ!!!!!

Согласен.



> 1 голем на человека

Тоже согласен.

> Голем имеет броню против всего на 80 (Что бы танчить)

Спорно, но тоже согласен. Пусть големы будут *реально решающими* в плане индивидуальной мощи.



> Голем не может призывать голема

Опять же, согласен.

**Comment by BiQndy** [comment]
По вашим планам выглядит так, шо условная каменюка сможет замудохать халка в соло

**Comment by Ambassadoing** [comment]
> По вашим планам выглядит так, шо условная каменюка сможет замудохать халка в соло

Как раз противовес этим зелёным голожопым любителям погрифонить.

**Comment by JustEmpty** [comment]
Снова нерфоцирк... Когда уже будут что-то строить а не разрушать...

**Comment by LudwigVonChesterfield** [comment]
Можно чтобы големы уменьшали количество макс. ХП создателя, тогда у него не будет такого большого рвения клепать много-много големов.

**Comment by Kortez90** [comment]
> уменьшали количество макс. ХП создателя

Тогда он будет завариваться в стены и сидеть в шкафу с консолью камер.

**Comment by LudwigVonChesterfield** [comment]
на что только готов игрок лишь бы не играть

**Comment by Kortez90** [comment]
Он как раз и играет. В механ.

**Comment by Akellazp** [comment]
просто сделать ограничение на 3 голема на 1 человека и не давать големам возможности активировать руны, и все будет прекрано
а так вы можете просто убить големов занерфив их до невозможности
големы всегда легко уничтожались убийством хозяина

**Comment by cool20141** [comment]
Смысл в этих нерфах, если они умирают, если убить их мастера, они сами ОЧЕНЬ медленные, так еще и не могут использовать огнестрел
Я считаю, что нужно:
1. Убрать големам регенерацию (Либо сильно ее уменьшить)
2. Убрать возможность использовать химикаты (Потому что так они даже ОБР могут нагнуть, если у них в рюкзаке шприцы со всякими триками и прочей фигней)

**Comment by LudwigVonChesterfield** [comment]
у големов нет регенерации... и возможно химикатов тоже

**Comment by cool20141** [comment]
Есть и то, и другое. В коде самом не копался, но если долго отдыхать с поврежденной частью, то она излечивается постепенно. Аналогично и с химией: если при каком-либо уроне вколоть соответствующий медикамент, то он будет работать. Проверял на локалке (Да и на сервере тоже, чего уж там), ставил себе около 50 берн/брут урона. За несколько секунд после инъекции бикаридина и келодерма все проходило

**Comment by Motzord** [comment]
Я боюсь говорить это на гитхаб, но...

На големов действую гены и вирусы.

Големохалки-телепаты с вирусом регенерации это не бред.

**Comment by Kortez90** [comment]
https://github.com/TauCetiStation/TauCetiClassic/blob/0331a8c929f79e36c2443eab27c6627204c75fd8/code/modules/mob/living/carbon/human/human.dm#L58-L59

Учитывая то, что големы это просто люди с респрайтом, то не удивительно.

**Comment by WatlerJe** [comment]
Обновил говермент ишью.

**Comment by Motzord** [comment]
> Обновил говермент ишью.

Забыл про вирусы

**Comment by Kortez90** [comment]
> 
> 
> Забыл про вирусы

Нет смысла перечислять все людское у големов. Им нужен отдельный класс, как у того же яна. А лучше сделать из них симплмобов.

**Comment by ViDLiathan** [comment]
Два голема на человека хороший вариант

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/predlozhenie-po-tau-v-czelom/18486/25
