### ISSUE TITLE
[Proposal] По нажатию Examine можно подглядывать в завернутые посылки

### ISSUE THREAD

**Issue by 4310V343k** [TauCetiStation/TauCetiClassic#5014]
#### Подробное описание проблемы
Можно будет проверять посылки на наличие проксимитиоднобалонок
#### Что должно было произойти
хос идет пиздить подрывников
#### Что произошло на самом деле
хос подрывается на can grenade
#### Дополнительная информация:
хотя так даже веселее

**Comment by TechCatOther** [comment]
Лучше тогда просто отдельный сканер ввести для такого. Что бы не прокликивать все через эксмайн, а пришлось идти за ним или искать его. Тогда больше шансов на срабатывания данных ловушек останется. Во вторых будет для трейторов еще один предмет, что полезно забрать.

**Comment by GermanSUS** [comment]
> Лучше тогда просто отдельный сканер ввести для такого. Что бы не прокликивать все через эксмайн, а пришлось идти за ним или искать его. Тогда больше шансов на срабатывания данных ловушек останется. Во вторых будет для трейторов еще один предмет, что полезно забрать.

У нас есть хороший детектор нелегала у велосити офицеров, заменить функционал из тыкнул>опа нелегал на тыкнул>подождал>опа нелегал

**Comment by Ambassadoing** [comment]
То есть хочешь убить всю суть неподписанных посылок? Окей. Идея плохая.
