### ISSUE TITLE
[Proposal] Черный список.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#5016]
#### Подробное описание проблемы
Нужен черный список для каждого игрока, состоящий из двух-трех слотов. В него можно внести других игроков и их сообщения из LOOC, OOC и дедчата не будут отображаться для того, кто внес другого игрока в этот список.

**Comment by LudwigVonChesterfield** [comment]
альтернативное решение: выпил ООК-а и ЛООК-а, все равно космонавтов только от игры отвлекают
