### ISSUE TITLE
Баг с манкинайзом

### ISSUE THREAD

**Issue by ForceKill** [TauCetiStation/TauCetiClassic#502]
#### Подробное описание проблемы

Если после превращения игрока в мартышку через панель ролек, случайно превратить его в инфекционную мартышку, то превратить в человека уже нельзя.
#### Что должно было произойти

Мартышка должна была превратиться в человека.
#### Что произошло на самом деле

Мартышка осталась мартышкой.
#### Как повторить

Быть администратором, превратить человека в мартышку, потом в больную мартышку, потом попробовать превратить в человека.
#### Дополнительная информация:

И так все подробности расписаны.

**Comment by Olt1771** [comment]
Так-же мартышки прокусывают армор и риги
НЁРФ ИТ
