### ISSUE TITLE
[Proposal] Добавить фунцию hide маленькому слизню

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#5021]
#### Подробное описание проблемы
Маленький комочек слизи не может прятаться от злых и коварных космонавтов с огнетушителями
#### Что должно было произойти
Маленький слизнюк имеет кнопку hide
#### Что произошло на самом деле
Мертвый слизнюк в вирусологии и ехидный вирусолог с огнетушителем
#### Как повторить
Попробуйте съесть обезьяну вирусолога
#### Дополнительная информация:
.

**Comment by Sakuya-Izayoi** [comment]
Он не такой и маленький, чтобы мог так прятаться.

**Comment by Kortez90** [comment]
Еще одна попытка легализации грифа слизнями.

**Comment by Daoprotoss** [comment]
> Он не такой и маленький, чтобы мог так прятаться.

Так он же желеобразный, спокойно себе вольется под столик.
