### ISSUE TITLE
Некорректно работает цель "покалечить"

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5022]
#### Подробное описание проблемы
Отыграл за татора многоходовочку, убил жертву и во время реанимации "случайно" поломал ей ребра, ну бывает так сказать, затем реанимировал и отпилил ноги.

#### Что должно было произойти
гринтекст
#### Что произошло на самом деле
Traitor has failed
#### Как повторить
Убейте жертву, покалечьте и реанимируйте. Или отпилите ей конечность операцией
#### Дополнительная информация:
Скорее всего баг произошел из-за того что цель умерла или обрубки считаются как нормальная конечность

**Comment by Sakuya-Izayoi** [comment]
Я думаю проблема в том что ты как раз таки отпилил конечность операцией. Потому что как раз таки это не считается.

**Comment by Ambassadoing** [comment]
Моцордва, а ты читал ФОРМУЛИРОВКУ задания? Покалечить, пока жертва ЖИВА. Да-да. И да, я думаю, что ампутация не засчитывается нарочно. *Слишком безболезненно* для жертвы.

**Comment by Akellazp** [comment]
у меня 2 или 3 раза не засчитывалось это задание когда я отпиливал ноги операцией

**Comment by Sakuya-Izayoi** [comment]
потому что там в коде чёрным по белому написано, что если конечность отпилена операцией, то не считается. потому что надо отпиливать не операцией.
