### ISSUE TITLE
NanoMed общака с неправильным доступом

### ISSUE THREAD

**Issue by Mintt69** [TauCetiStation/TauCetiClassic#5026]
#### Подробное описание проблемы
NanoMed на стене общака между 1-3 камерой все еще не имеет свободного доступа, отчего ни раненные зеки, ни СБ не может достать оттуда медикаменты 
#### Что должно было произойти
Доступ должен быть общий
#### Что произошло на самом деле
Доступ ограничен " Access denied"
#### Как повторить
Попробовать достать медикамент из NanoMed используя карту СБ или без
#### Дополнительная информация:

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/4849
было

**Comment by Mintt69** [comment]
> #4849
> было

ну так было но почему не пофиксили? уже много времени прошло

**Comment by KIBORG04** [comment]
Ну так там проблемы, ни я, ни второй челик не хотят юзать редактор карты. А писать повторное ишью не стоит, потому что их удалают
