### ISSUE TITLE
При копировании листочка с формой где присутствует тег подписи, он пропадает

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#5028]
#### Подробное описание проблемы
Если сделать форму например с Ордером на обыск а потом скопировать ее в копировальной машине, то тег Подписи пропадет.
#### Что должно было произойти
Он не должен пропадать
#### Что произошло на самом деле
Он пропал
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/19417166/79069854-28f3c300-7cda-11ea-8cce-4bfcf8098b24.png)

**Comment by T6751** [comment]
@LudwigVonChesterfield, закрой ещё этот иссуй
