### ISSUE TITLE
Пропадает текст на распечатанных копиях на принтере

### ISSUE THREAD

**Issue by SkLepP** [TauCetiStation/TauCetiClassic#503]
#### Подробное описание проблемы

После печати одного листа бумаги на принтере и складывания их в одну пачку, пропадает текст с копий
#### Что должно было произойти

Весь напечатанный текст должен оставаться на копиях
#### Что произошло на самом деле

Текст пропадает
#### Как повторить

Распечатать на принтере лист бумаги с текстом, копировать и сложить в одну пачку
#### Дополнительная информация:

...

**Comment by SpaiR** [comment]
@SkLepP ещё актуально? если да, уточни действия по повторению
