### ISSUE TITLE
[Proposal] Уменьшить кол-во слотов медиков.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#5030]
#### Подробное описание проблемы
Отсек маленький, а медиков прорва. Хирургов 3-4 штуки, операционных две. Работать негде, лечить негде. Людей в крите до пяти штук, которых негде хранить/лечить. Не развернуться. Ограничьте уже кол-во слотов хирургов до двух и запретите врачам заниматься их работой.

**Comment by UsadoSmokk** [comment]
хирург, это подвид врачей...… Этот фикс сделает только хуже, так как людей и так не хватает, а тут еще уменьшим....

**Comment by Kortez90** [comment]
В какую сторону тебе не хватает? Какой подвид врачей? Их делить надо и уже давно. Хирурги буквально дерутся за пациентов и комнаты.

**Comment by UsadoSmokk** [comment]
![image](https://user-images.githubusercontent.com/56721822/79074003-b3084f80-7d0b-11ea-8b1a-5254e18f6373.png)
потом, люди либо просто забивают на людей в меде, либо их просто не хватает, и чем плохо иметь больше двух серженов на станции? Один занят операцией, другой татар и все, помер какой-то Васян шахтер от легких гибнутых. А аргумент, мол, у нас всего две операционных, нифига не аргумент.

**Comment by Kortez90** [comment]
Ты не играл никогда в медицинском отсеке?
Две операционных и четыре хирурга с СМО. Что это значит? Это значит, что операционные кто-то со старта "захватывает" и начинает складывать там инструменты в рюкзаки, строить всякую хрень вроде шкафов со створками и даже диспенсеры. После чего в нее уже никто не пойдет работать, потому что либо занявший комнату хирург начнет кукарекать и рваться чинить вообще всех в своей операционной, либо это будет делать СМО. Что для остальных трех? Один из них займет операционную. Переделает. И уйдет в крио. Что делать двум другим? Сосать скальпели, потому что работать им не даст никто, ни в качестве врачей, ни в качестве хирургов.

**Comment by UsadoSmokk** [comment]
чего..... круто, наверное я такой везучий, раз меня даже в крио положить не могут и я даже не говорю про лечение органов. Двое сидят в меде, садят в крио и прочее говно и если хирурга мать позовет пожрать или еще что-то, то могут заменить в операционке.

**Comment by SvSvyat** [comment]
> Отсек маленький 
> Хирургов 3-4 штуки, операционных две. 
> Работать негде, лечить негде. 
> Людей .. негде хранить/лечить. 
И поэтому надо урезать слоты (ачотакова, всё равно клонируют, да?), а не ремапнуть, дав чуть больше места. Да-да.

**Comment by skvazarb** [comment]
Предложение очень сомнительное во всех смыслах. Запрет заниматься чужой работой в правилах де факто практически отсутствует, поэтому запрет для врачей в хирургию выглядит и нелогичным и просто не будет работать на практике.

А подсчитывать количество реально присутствующих людей по количеству слотов просто нельзя. Они в процессе раунда могут умереть, афкшнуть, могут оказаться дебилами. 4 слота это еще мало, всегда было 5, каждый из которых мог в хирургию, один слот уже отрезали когда бесполезных парамедиков добавляли.

**Comment by Motzord** [comment]
Немного не так звучит

>Добавить слот хирурга  в отдельную профу (2 шт)
>Урезать слот медиков на 2.

**Comment by Marselinel** [comment]
Урезать количество хирургов необходимо, так как бойня за операционные - это отвратительно, особенно, когда уже почти режешь пациента и приходит третий хирург и начинается: "А ЧТО С НИМ? А ДАВАЙ ПОЛЕЧУ", что отвлекает и раздражает.

Если хирурга позовёт мама кушать - доктор может заняться его обязанностями. Но пока хирурги на месте - соваться туда под страхом джобки не надо, будучи доктором.

Играя в медбее всё время я точно могу сказать, что разделение хирурга и доктора необходимо. 2 слота для хирурга, 3 - для доктора/медсестры.

**Comment by Kortez90** [comment]
> разделение хирурга и доктора необходимо

Ну хоть кто-то играл в медицинском отсеке.

**Comment by Kortez90** [comment]
>  а не ремапнуть

Уже ремапнули, смотри что получилось. Классно, да? А вон там есть чекпоинт охраны. Очень полезно! А вот внизу есть заброшенная гидропоника. Еще более полезно и места совсем не занимает!

**Comment by SvSvyat** [comment]
Ну всё, талоны на ремап кончились.
> А вон там есть чекпоинт охраны. Очень полезно!

Это проход в мед в условиях либо тотальной жопы, либо "да нам пихуй, что вы там на ресепшене трезвоните".  Ну, ещё это плюсик к ролевому ропе отыгрышу, и то, что медики его не юзают, выпрашивая у сб кого-нибудь на чекпоинт, это печально (заодно, глядишь, и медбей перестанет напоминать проходной двор). 

> А вот внизу есть заброшенная гидропоника. Еще более полезно

Там сосущие скальпели и дерущиеся хирурги со всякими там интернами выращивают травку. 
Редко? Психолог тоже редко отыгрывается, а кабинет-то стоит, место занимает.
В вирусологию ходят дай боже раз шесть за раунд, а она на самом видном месте. Комнаты со слиперами и крио это реально проходной двор до операционных. Кабинет психолога логичнее был бы около клонёрки. 
Но собирать фидбэк и работать над проблемами это слишком скучно, не-не. Слоты урезать веселее.

**Comment by Kortez90** [comment]
> медбей перестанет напоминать проходной двор

Не перестанет до тех пор, пока не начнут карать за нон-рп говно. А карать за нон-рп говно не начнут, потому что его легализовали.
 

> хирурги со всякими там интернами выращивают травку.

Там никто и никогда ничего не выращивает. Один я туда забегаю, чтобы сварить вина и продавать пациентам и то, крайне редко. Это место лута запачастей из треев, не более.


> В вирусологию ходят дай боже раз шесть за раунд

Вирусология дно и не нужна, потому что нет режимов, что ее используют. Есть **один** ивент, который происходит крайне редко и по большей части не делает ничего. Сопли, насморк. Вирусология - место старта трейтеров и показатель того, что происходит с отсеками, если некоторые режимы вырезают.



> Психолог тоже редко отыгрывается

А ты в курсе, почему? Потому что психологом почти никто играть не в состоянии. Как только они сталкиваются с реальностью, у них включается механоублюдок, который вызывает котов с хлоркой. Психолог - очередной ассистент, только вместо баллона у него шприц.

Пока до вас, хомяков, не дойдет что это **ролеплей**, этот детский садик будет вертеть на елде всех с потоком нескончаемого говна. Вот он, фидбэк. Работай над проблемой, раз кукарекаешь.

**Comment by SvSvyat** [comment]
> пока не начнут карать за нон-рп говно

Сотрудник СБ на чекпоинте - отличная мера пресечения говна. ИЦ-мера, что важно, не темка на форуме
> не дойдет что это ролеплей

Не туда воюешь.
Хотя, в принципе, уровень реальной вовлечённости понятен и без дальнейшего разбора.
> хомяков
>  детский садик будет вертеть на елде
> потоком нескончаемого говна
> кукарекаешь
> фидбэк

Если это образец **ролеплеера**, то я готова назваться анробастным каэсочником. За сим откланяюсь. Не нужен медбей - ок, ок.

**Comment by Kortez90** [comment]
> Сотрудник СБ на чекпоинте - отличная мера

Они же сами говно и творят. В том числе хосы, боевые хоп и так далее.



> решать проблемы ИЦ

Кто-то не играл даже главами. Ясненько.

**Comment by LtSaavik** [comment]
> В том числе хосы, боевые хопы и так далее.

У хесов и хепов есть доступ к створкам меда, им чекпойнт СБ не нужен.

> Они же сами говно и творят.

"Уыаааа, выдите усе из меда потому что потому!!!"
Как собешник, сидящий на этом самом чекпойнту (ну, сидевший, по крайней мере) - ты не прав.


> Не можешь аргументировать по сабжу - тебе здесь не место.
> Переводишь стрелки - тебе здесь не место.
> И так далее.

Пипец ты писос. На все доводы вот это писать - ну ты да, сразу видно, что аргументированную позицию имеешь.
