### ISSUE TITLE
[Proposal] Возможность пихнуть обратно в автомат.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#5034]
#### Подробное описание проблемы
По большей части это относится к пустым баночкам из-под а-т или инапровалина, что есть в автоматах и к химии, где эти банки создаются из ничего. В связи с этим их в медицинском отсеке тонны, а из-за лени людей дойти до мусорки и выкинуть пустую банку происходит мусорный трындец. Уборщика вообще кто-либо видел действительно работающим?

Решений это проблемы куча.
- Убираем бесплатное создание баночек и требуем вставлять в чеммастер **две** баночки, во вторую наливаем максимум 30u.
- Добавляем возможность пихать пустые баночки обратно в автомат с банками для переработки/растворения в пыль/добычи одного кредита за банку.

Можно также сделать с другими автоматами, если есть какая-то пустая тара.

**Comment by FelixRuin** [comment]
это я как понимаю у химиков там должен быть целый ещё один склад под банки?
ибо основной набор химии это уже 66 банок выходит

**Comment by Motzord** [comment]
> это я как понимаю у химиков там должен быть целый ещё один склад под банки?
> ибо основной набор химии это уже 66 банок выходит

дать возможность пихать в чеммастер лист стекла для создания баночек под лекарства

**Comment by Kortez90** [comment]
> пихать в чеммастер лист стекла

Тоже вариант.



>  набор химии это уже 66 банок

У химиков в шкафу (Который почти никто и никогда не открывает.) есть коробка с бутылками. У них коробки с бутылками где-то на столах был. Бутылки просто везде.

**Comment by Ambassadoing** [comment]
А в чём проблема-то? 95% банок люди спокойно утилизируют, остальные 5% не проблема поднять и выкинуть самому, если уж так не нравится видеть их валяющимися на полу.

**Comment by Kortez90** [comment]
> 95% банок люди спокойно утилизируют

В том и дело, что далеко не 95%, а я устал один хирургом убирать **весь** медицинский отсек и после двух минут за консолью убирать его снова.

**Comment by Pivo24** [comment]
Так ведь можно уже пихать товары обратно в автомат, клик отвёрткой по автомату, шлёп баночкой по открытой панели, клик отвёрткой, шлёп, утилизировал как батька.

Считай твой пропозал уже на половину выполнен с вталкиванием баночек в автоматы. Проблема в том, что вталкиваются только банки а-т и инопровала, а значит пустую баночку дексалина+ не скормишь НаноМеду, а значит пропозал выполнен на четверть даже.

По поводу баночек из химмастера - а из чего тогда делаются таблетки? Мне что туда грузить, чтобы получать оболочки для них? Не нада, нееет

**Comment by Kortez90** [comment]
> из чего тогда делаются таблетки?

Химикат. Дегидрированный, прессованный. Ресурс сам химикат. А вот стекло там из воздуха.

**Comment by FelixRuin** [comment]
а из чего будут таблетки из воды?

**Comment by Kortez90** [comment]
Очевидно, что таблетку воды создать нельзя, но можно. Условность.

**Comment by CeUvi** [comment]
> Условность

Банки тоже условность. Ты действительно хочешь, чтобы приходилось постоянно бегать к РнД за банками чтобы сварить пару лекарств?
