### ISSUE TITLE
[Proposal] Убрать разделение на хирургов и врачей.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#5039]
#### Подробное описание проблемы
![Безымянный](https://user-images.githubusercontent.com/36198983/79233780-f7adfb00-7e71-11ea-8b30-eaf418b2c948.png)

Зачем существует профессия хирургов, если на уровне правил в ней нет вообще никакого смысла?

**Comment by FelixRuin** [comment]
тогда и у всех забрать подпрофы
у химиков вот вообще это лишь меняет название

**Comment by ViDLiathan** [comment]
У химиков два слота и два рабочих места
