### ISSUE TITLE
емаг игнорирует расстояние до двери

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#5047]
#### Подробное описание проблемы
название
#### Что должно было произойти
дверь не должна взломаться от клика на неё с пяти турфов.
#### Что произошло на самом деле
дверь взломалась
#### Как повторить
нажать на дверь не вплотную когда у вас в руке емаг

**Comment by LudwigVonChesterfield** [comment]
а к другим объектам игнорирует?

**Comment by TungstenOctopus** [comment]
Не так давно был пулреквест, меняющий взаимодействие емага, от винтершока кажется, возможно связано

**Comment by AndroBetel** [comment]
да игнорирует и к другим объектам

**Comment by LudwigVonChesterfield** [comment]
вангую что emag_act вызывается из afterattack, а у последнего нет проверок на ренж, только булевый аргумент - который надо было бы отдельно принимать во внимание
^
на заметку любому фиксеру

**Comment by KIBORG04** [comment]
Как-то поздно это вскрылось

**Comment by Kortez90** [comment]
> emag_act вызывается из afterattack

https://github.com/TauCetiStation/TauCetiClassic/blob/4362fa206ca714580c4e7a709cc091eea0f86db7/code/game/objects/items/weapons/cards_ids.dm#L71-L75

А вот и виновник.
https://github.com/TauCetiStation/TauCetiClassic/commit/2ee38a0bd6789243bc353b123512be3c3228fe52#diff-f9a4ef4133d4cd61013225c878c1b298

**Comment by UsadoSmokk** [comment]
это разве не фича...….?

**Comment by Zmey25** [comment]
Не надейся
