### ISSUE TITLE
СПУ получают урон когда берут крапиву

### ISSUE THREAD

**Issue by GermanSUS** [TauCetiStation/TauCetiClassic#5049]
#### Подробное описание проблемы
Заголовок
#### Что должно было произойти
СПУ держит крапиву и вероятнее всего бьет ею людей
#### Что произошло на самом деле
Ай, я искрюсь и из рук все валится
#### Как повторить
Возьмите за СПу крапиву в руки
#### Дополнительная информация:
Урон от самой крапивы по СПУ нужно убрать, ЭТО ЖЕ РОБОТ!

**Comment by cool20141** [comment]
А на робота не должна действовать серная кислота?

**Comment by TungstenOctopus** [comment]
Думаю здесь проблема не в том, что крапива жалит СПУ, а в том, что крапива жалит серной кислотой

**Comment by GermanSUS** [comment]
> Думаю здесь проблема не в том, что крапива жалит СПУ, а в том, что крапива жалит серной кислотой

Тогда это многое объясняет.
