### ISSUE TITLE
Телесаенс.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#505]
#### Подробное описание проблемы
В консоле телесаенся нельзя сменить координаты.
#### Что должно было произойти
Должно быть "льзя".
#### Что произошло на самом деле
Когда ты вписываешь в ошоко координаты, он вроде как их запоминает, но не меняется в консоле.
#### Как повторить
Уметь в телесаенс.

**Comment by Dennok** [comment]
Координаты сменить нельзя. Ты наверное имел в виду параметры.
