### ISSUE TITLE
Немые не могут говорить на языке жестов

### ISSUE THREAD

**Issue by SomeUselessGuy** [TauCetiStation/TauCetiClassic#5053]
#### Подробное описание проблемы
Немые не могут говорить на языке жестов .-.
#### Что должно было произойти
Немой человек подходит к бармену и языком жестов рассказывает про килограммы печенек.

#### Что произошло на самом деле
U AR MUTED

#### Как повторить
Взять немую куклу, выучить язык жестов, потерпеть фиаско

#### Дополнительная информация:
Хелп

**Comment by Sakuya-Izayoi** [comment]
У меня персонаж немой и может говорить на языке жестов.

**Comment by Ambassadoing** [comment]
Сэйм щит, всё работает.

**Comment by SomeUselessGuy** [comment]
Зашел на таукеки, написал ":s Привет" (или чет такое, на счет :s не уверен)
![image](https://user-images.githubusercontent.com/40398890/79631217-0d246d00-8171-11ea-9576-35492e99111f.png)

**Comment by SomeUselessGuy** [comment]
Вот этот префикс взял из "Check known languages"

**Comment by SomeUselessGuy** [comment]
![image](https://user-images.githubusercontent.com/40398890/79636188-5aafd280-818f-11ea-9c69-b9ca3428cbf4.png)
![image](https://user-images.githubusercontent.com/40398890/79636194-61d6e080-818f-11ea-80a7-033926eeee32.png)
![image](https://user-images.githubusercontent.com/40398890/79636198-68fdee80-818f-11ea-9029-2cf9344f1487.png)
Вау, впервые за тысячу лет оно заработало
