### ISSUE TITLE
[Proposal] Убрать ЛООК и ООК.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5055]
#### Подробное описание проблемы

Космонавтов они отвлекают от игры, а некоторых вовсе вгоняют в депрессию #5016 

Предлагаю ЛООК вообще выпилить, а ООК оставить на "до начала раунда" и "после конца раунда".

**Comment by Sakuya-Izayoi** [comment]
Насчёт лоока согласен, а касательно ооц, его можно самостоятельно отключить чтобы не читать что за дичь там пишут. А так он иногда бывает полезен.

**Comment by Kortez90** [comment]
LOOC можно убрать вообще. За его использование и вмешивание в раунд гостов не банят, значит он будет удален.

**Comment by Zmey25** [comment]
Поддержу убрать лоок, его юзают в наглую паля оок инфу или ради угроз. Оок же лучше контролируется и отключить его можно в префах без проблем.

**Comment by UsadoSmokk** [comment]
> Поддержу убрать лоок, его юзают в наглую паля оок инфу или ради угроз. Оок же лучше контролируется и отключить его можно в префах без проблем.

как чувак с логами могу сказать одно, то и то контролируется хорошо(если вы не производите 10000 атаклогов в наносекунду)

**Comment by SvSvyat** [comment]
Gay Smallovich says, "((по нонрп, я новенький, как сесть на стул))"
Old Biggevich says, "Перетащи свою жопу на стул, прямо ПЕРЕТАЩИ на него, ЖОПУ на СТУЛ, ну же, ПЕ-РЕ-ТА-ЩИ."

Ну наконец-то в оок не будет всего этого нытья после равундов, и никакого обучения ассистух в лооке базовым вещам. Только ИК, только хардкор! Ну и дохлые менторы, конечно же. 
Полностью за, лучшее предложение за последнее время. 
_(нет.)_

**Comment by UsadoSmokk** [comment]
не понимаю, где кому насолил лоц, разве не круто сидеть в баре, пить чай и обсуждать фигню из ирл?

**Comment by LudwigVonChesterfield** [comment]
мне нравится как СвСвят говорит про какое-то "не будет после раундов" когда я отдельно сказал что после раундов оставить :joy:

**Comment by SvSvyat** [comment]
> когда я отдельно сказал что после раундов оставить 

Люди распаляются, распаляются в раунде! Без запала неинтересно в ооке сраться. 
Оно было преувеличением в порядке полурофла, но если это _действительно_ абсолютно серьёзно, то тем более нет. Основная суть проблемы там же и описана, кхе, могу повторить более _прямо_:
Все мимоассистухи, которые пытаются сесть на стул, встать со стула, случайно меняют интент и дизармят всех, пытаются взять колоду карт в руки или снять рюкзак для кпп, остаются фактически в соло. Спасибо, если они знаю про мхелп, вдвойне спасибо, если пишут туда. А если не знают, то ты им об этом даже сказать не сможешь. 
Нет. Ну, то есть, совсем нет.

**Comment by Tiarv** [comment]
Альтернативное предложение по поводу OOC: он сейчас по-умолчанию включен и желающие его могут себе лично выключить. А что если сделать его по-умолчанию отключенным, а желающие могли бы его себе включить? Либо запоминать настроечку для игрока, так чтобы после каждого рестарта не надо было его себе вырубать заново (но это, очевидно, сложнее).

**Comment by Ambassadoing** [comment]
Не трогайте LOOC и OOC. Что я отключать буду, когда космонавты срать начинают?
