### ISSUE TITLE
[Boxstation] В медбее отсутствуют карантийные створки.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5056]
#### Подробное описание проблемы
Почти во всех отделах за исключением карго и медбея в кабинетах глав имеется кнопка "Закрыть отдел кхуям, да так чтобы не открылся"
#### Что должно было произойти
СМО бежит в кабинет и тыкает кнопку во время нюки/эпидемии/другого надвигающегося пиздеца, медбей консервируется и медики пьют чай
#### Что произошло на самом деле
СМО бегает как угорелый и болтирует шлюзы, а каждый мимоассистент считает святым долгом взломать их и заодно полутать медсклад/трупы
#### Как повторить
Поищите кнопку для опускания створок.
#### Дополнительная информация:
Такие створки имеются в бриге и РнД.

**Comment by Kortez90** [comment]
Бриг и рнд - важные отсеки с пушками. Когда педальками лень работать, они мапят створки в таких отсеках, чтобы продолжать ничего не делать. Медицинский отсек - проходной двор, куда лезут все. Здоровые, больные - неважно. Важно залезть и лично вколоть себе а-т, трик и дексалин, залезть в сканер и орать "УМЕНЯЛЕГКИЕПОРВАЛО".

**Comment by Sakuya-Izayoi** [comment]
Медбей не должен закрываться в случае карантина и пить чай, он должен принимать больных и лечить их.

**Comment by Motzord** [comment]
> Медбей не должен закрываться в случае карантина и пить чай, он должен принимать больных и лечить их.

чаще всего карантин происходит из-за вирусолога, который сделал уберполезный вирус с адреналиновым скачком и пошел лапать медсестер.


Также створки были бы полезны в нюку, ибо большинство нюкеров свомим долгом считают устроить колумбайн в медбее. Вообще створки полезны на любые случае пиздеца, я для умного СМО не составит труда проконтролировать когда нажать на кнопку, чтобы впустить парамедика с ранеными
