### ISSUE TITLE
Косяки с ремапом.

### ISSUE THREAD

**Issue by KittyCat91** [TauCetiStation/TauCetiClassic#506]
#### Подробное описание проблемы
В западном коридоре между отделом логистики и складом инструментов нет датчиков атмосферы. Также датчиков лишены приемная отдела логистики и офис доставки отдела логистики где также отсутствуют и датчики пожара.
#### Что должно было произойти
Должны быть датчики атмосферы.
#### Что произошло на самом деле
Их нет.
#### Как повторить
Зайти в наблюдатели и пролететь над указанными отсеками.

**Comment by Skyrull** [comment]
Еще во многих шлюзах не стоят аварийные створки.
![e](https://cloud.githubusercontent.com/assets/20542000/18054677/9aeca5b0-6e26-11e6-92fb-71a527928c33.png)

**Comment by Skippeer12** [comment]
А в некоторых шлюзах нет кнопки.

![](http://i.imgur.com/vBzZqMa.png)

**Comment by ZVee** [comment]
>Зайти в наблюдатели и пролететь над указанными отсеками.

Хорошо бы скрины делать в таких репортах, а не только на словах описывать где нужно пролетать.

**Comment by Skippeer12** [comment]
Держите, тут всё что я нашел.
http://imgur.com/a/bSdrz?

**Comment by Raschert0** [comment]
https://dl.dropboxusercontent.com/u/73967379/ssmap/das3fsdfsd34.png

https://dl.dropboxusercontent.com/u/73967379/ssmap/das34fsdfds.png

https://dl.dropboxusercontent.com/u/73967379/ssmap/das43gfdfsdf.png

https://dl.dropboxusercontent.com/u/73967379/ssmap/das54hgfh3.png

https://dl.dropboxusercontent.com/u/73967379/ssmap/dsa4tgdfg65.png

https://dl.dropboxusercontent.com/u/73967379/ssmap/dsa43fdsfsd.png

https://dl.dropboxusercontent.com/u/73967379/ssmap/dsa43gfdgdf.png

**Comment by Raschert0** [comment]
![dsa54hgfghf54](https://cloud.githubusercontent.com/assets/11941910/18360939/ba7ddaa4-7608-11e6-940c-e1456a25e3d5.png)
![fdy45hfgsd](https://cloud.githubusercontent.com/assets/11941910/18360936/ba7938dc-7608-11e6-90e5-71255b1b4ee3.png)
![as56uhgfd](https://cloud.githubusercontent.com/assets/11941910/18360935/ba78406c-7608-11e6-9929-dc554aa2edd9.png)
![das43dsagdfgdf](https://cloud.githubusercontent.com/assets/11941910/18360937/ba7a4d12-7608-11e6-88d1-3db9fb4b0c16.png)
![das43vdsfds](https://cloud.githubusercontent.com/assets/11941910/18360938/ba7c7eca-7608-11e6-96de-b67512ecf464.png)
