### ISSUE TITLE
[Proposal] Многоразовый стазис мешок

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#5061]
Потому что от них и так идет генурон.
Потому что уже давно пора. 
Потому что моментально ломаются дурачками.
Потому что их дай бог используют раз в неделю.
Потому что есть хоть одна причина им быть такими, не считая того, что игроки должны страдать?

**Comment by Sakuya-Izayoi** [comment]
Это имба.

**Comment by Kortez90** [comment]
Их вообще можно вырезать.

**Comment by TungstenOctopus** [comment]
Редкое использование оправдано крутым баффом "не сдохнуть от кучи говна за секунду и дожить до медбея", ломание дурачками вполне фиксится приделыванием длительного открывания с прогрессбаром секунд на 10, последнее, кстати, нормальная идея

**Comment by Kortez90** [comment]
> Редкое использование оправдано крутым баффом

Что? По-твоему мешок не юзают из-за того, что он выполняет свои функции?

**Comment by TungstenOctopus** [comment]
> > Редкое использование оправдано крутым баффом
> 
> Что? По-твоему мешок не юзают из-за того, что он выполняет свои функции?

Его редко юзают, потому что он мало где лежит. А мало где лежит он потому, что он крутой, и в каждый отсек он совсем не нужен.

**Comment by Kortez90** [comment]
> Его редко юзают, потому что он мало где лежит.

Его редко юзают потому что во-первых, их всего 2-3 штуки на всю карту. А во-вторых, потому что это не нужно вовсе. Парамедики-коты носятся с каталками и обращаются с инструментами так, что инженеры и борги со втеком нервно потягивали капитанскую сигару за консолью камер. К тому же, они таскают с собой инапровалин с бинтами, а этого достаточно, чтобы урон не капал. И еще сверху, они носят с собой келодерм, бикаридин и кучу другого говна, которые могут еще живого человека дотянуть до ~90% хп. Возникает вопрос, зачем тебе мешок, если есть коты-механоебы, играющие в механ?
