### ISSUE TITLE
У гостов ограничивается обзор, если они орбитят труп в трее морга.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#5063]
#### Подробное описание проблемы
У госта ограничивается обзор, словно самого госта сунули в трей.
#### Что должно было произойти
Такого быть не должно.
#### Что произошло на самом деле
Но оно есть.
#### Как повторить
- Орбитнуть труп.
- Пихнуть труп в трей морга.
#### Дополнительная информация:
![Безымянный](https://user-images.githubusercontent.com/36198983/79639189-d65f4e80-8192-11ea-9d0d-c397a8ede14a.png)

**Comment by Sakuya-Izayoi** [comment]
это касается не только орбита, а вообще любого способа перемещения госта в морг. да, всё ещё можно закрыть госта в морге

**Comment by Ahion** [comment]
Как не пытался, на локалке повторить не смог. Может уже не актуально?

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/8337
