### ISSUE TITLE
Столы, опять, опять.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#507]
#### Подробное описание проблемы
Спрайты столов пропали.
#### Что должно было произойти
Спрайты столов должны быть.
#### Что произошло на самом деле
Их нет.
#### Как повторить
Залететь к абдукторам на шаттл.

**Comment by Raschert0** [comment]
Эй! Но ведь ты уже делал этот ишью! 
https://github.com/TauCetiStation/TauCetiClassic/issues/431

**Comment by Skippeer12** [comment]
Мне показалось что их зафиксили...
