### ISSUE TITLE
[Proposal] Мелкофичи воксам.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5072]
Я предлагаю такие фичи:
- [ ] Герметичность кожи. Если вокс не ранен - он спокойно себя чувствует при низких давлениях(в космосе).
- [ ] "Встроенный кортикальный ИИ" - Вокс может по нажатию на кнопочку предложить госту быть ко-пилотом, который сможет говорить(от лица вокса), а если "хост" пожелает - то и вовсе брать контроль над телом.
- [ ] Смена пилота вокса при реанимации(выбор из гостов). Придумать любой неортодоксальный способ реанимации.
- [ ] Встроенный в тело пИИ.
- [ ] Возможность какой-то ценой меняться сознаниями с синтетами.

**Comment by Kortez90** [comment]
Тоже бред. Причем антилорный.

**Comment by LudwigVonChesterfield** [comment]
Лор не живёт в мире идей, и может прогнуться под классный механ.

**Comment by UsadoSmokk** [comment]
> Тоже бред. Причем антилорный.

Ксеновизоры сами решат, что лорно, а что нет. Человек высказал свою позицию и все.

**Comment by Akellazp** [comment]
>Герметичность кожи. Если вокс не ранен - он спокойно себя чувствует при низких давлениях(в космосе).

уже есть

**Comment by LudwigVonChesterfield** [comment]
Нет, нету. Я её предлагал сделать, но не сделал.

**Comment by Akellazp** [comment]
Так они уже во всю лазят по космосу

**Comment by UsadoSmokk** [comment]
> Так они уже во всю лазят по космосу

Это что-то вроде баланса, как я понял

**Comment by 4310V343k** [comment]
> > Герметичность кожи. Если вокс не ранен - он спокойно себя чувствует при низких давлениях(в космосе).
> 
> уже есть

По космосу они гуляют, да. 
Людук предлагает сделать так, что если у вокса есть раны, то он типо негерметичен и получает дамаг от давления. Дамаг зависит от количества ранок
