### ISSUE TITLE
[Proposal] Реворк Хадов, порт alternate_appearance с ТГ. [$40]

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5073]
#### Подробное описание проблемы

https://github.com/tgstation/tgstation/blob/master/code/game/alternate_appearance.dm

#### Конкретика:
- [ ] Реворк системы хадов, для этого фреймворка.
- [ ] Перевод ХадОчков всех видов на новую, портированную систему
- [ ] Перевод видения кровавых рун ИИ на эту систему.

#### Доп. возможные фичи:
- [ ] Выглядеть для ИИ как киборг(фича с ТГ https://github.com/tgstation/tgstation/commit/a3dd455a37ce46bb17960c991c1c4216892ee343#diff-3b4aa55c4430c16026daadd860a8c336)
- [ ] Прятаться в "куст", когда ты его берёшь в руку(фича с ТГ, там можно найти ПР-ы которые к ней относятся).

**Comment by GermanSUS** [comment]
Алилуя, можно прыгать в кусты и стелсить без хамелионок

**Comment by TheLustOfBlood** [comment]
Фича с кустом прикольная

**Comment by LudwigVonChesterfield** [comment]
https://www.bountysource.com/issues/91195682-proposal-alternate_appearance

**Comment by KIBORG04** [comment]
Я правильно понимаю, что с помощью этой хуйни можно подменивать спрайты?

А в чем смысл худов на этой системе?

**Comment by LudwigVonChesterfield** [comment]
Она не только позволяет подменивать спрайты, но и красиво управлять тем, кто какие спрайты видит.

Именно поэтому вещи, которые должны быть видны кому-то конкретно удобно основывать на этой системе.

**Comment by KIBORG04** [comment]
Блин, мне нравится этот фреймворк. Я его обязательно когда-нибудь портирую.....

**Comment by KIBORG04** [comment]
У меня дошли руки до этого всего. Пара вопросов.

>Реворк системы хадов, для этого фреймворка.

Тут вообще не `alternate_appearance`, сколько `/datum/atom_hud`. Ну то есть еще более глобальный рефактор?

>Перевод видения кровавых рун ИИ на эту систему.

Какой в этом смысл? Сделать культ полностью невидимым для силиконов

**Comment by LudwigVonChesterfield** [comment]
> Какой в этом смысл? Сделать культ полностью невидимым для силиконов

Если что это уже так и работает, ИИ вместо рун видит кровь, я лишь говорю что это надо рефакторнуть на новую систему

**Comment by KIBORG04** [comment]
Не против, если будет два ПРа? Ведь уже много изменений выходит, еще и без `alternate_apperance`
![image](https://user-images.githubusercontent.com/26389417/89714626-40ae3000-d9ca-11ea-8900-513fa5ace142.png)
