### ISSUE TITLE
Заброшенный корабль

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#508]
#### Подробное описание проблемы

На этом корабле нет лампочек. Но есть АПЦ и переключатель.
#### Что должно было произойти

 Лампы бы туда добавить, чтобы было канонично.
Ну и было бы идеально, если бы с полом/стенами можно было взаимодействовать разбирать/собирать.
#### Что произошло на самом деле

Кто-то забыл засунуть туда лампы после того как добавил графонестый свет.
#### Как повторить

Телепортироватся на заброшенный корабль.
#### Дополнительная информация:

![](http://i.imgur.com/ssjuopY.png)

**Comment by ZVee** [comment]
>Кто-то забыл засунуть туда лампы после того как добавил графонестый свет.

Это никак не зависит от типа света. Да и возможно там и раньше не было.
