### ISSUE TITLE
[Proposal] Поддержка двух маппингов хоткеев должна прекратится.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5080]
#### Подробное описание проблемы

Если всерьёз занятся удобством интерфейса этой игры, то стоило бы прекратить спектакль коим является два разных режима хоткеев. Каждое изменение вводящее новую клавишу будет попоболью для одного из видов игроков, в связи с тем что """дотянутся не могу""" или """неудобно жмякать""", и нам клавиш не хватит всех удовлетворять(особенно учитывая что в районе нумпада их не так много)

#### Предложение решения:
1) План минимум: Выпилить один из видов маппинга.
2) План максимум: Позволить ребиндить определённые хоткеи(Не прямо макросы разрешить, а именно назначение клавише изменить, см. tgstation)

**Comment by LudwigVonChesterfield** [comment]
я думаю для любителей писать и бегать можно было бы оставить ходьбу на стрелочках

**Comment by LudwigVonChesterfield** [comment]
теперь прекращаем поддерживать гамму поггерс

**Comment by KIBORG04** [comment]
Не, просто давайте добавим воут в начале/конце раунда и все
