### ISSUE TITLE
Белый пиксель на воксах

### ISSUE THREAD

**Issue by JustEmpty** [TauCetiStation/TauCetiClassic#5086]
#### Подробное описание проблемы
Пиксель белый.
![м ц4с](https://user-images.githubusercontent.com/61095037/79693170-cff3d400-8271-11ea-84f5-bd662c96d692.PNG)

#### Что должно было произойти
Белого пикселя нет
#### Что произошло на самом деле
Он есть
#### Как повторить
Зайти за вокса
#### Дополнительная информация:
Бесит

**Comment by LudwigVonChesterfield** [comment]
На тебе ещё куча одежды. Ты уверен что это именно из-за спрайта вокса?

**Comment by UsadoSmokk** [comment]
![image](https://user-images.githubusercontent.com/56721822/79693727-35ee5480-828e-11ea-8dd6-5a959a88669a.png)
вот он, негодник

**Comment by JustEmpty** [comment]
Во время налёта воксов у всех белый пиксель

**Comment by UsadoSmokk** [comment]
> Во время налёта воксов у всех белый пиксель

уже решили, можешь закрывать

**Comment by LudwigVonChesterfield** [comment]
@UsadoSmokk Это я прохлопал. Обычно в ПР-ы пишут "closes #*номер ишуя*", и тогда бот сам закрывает. Впредь будь осторожен.

**Comment by LudwigVonChesterfield** [comment]
#5087

**Comment by UsadoSmokk** [comment]
> @UsadoSmokk Это я прохлопал. Обычно в ПР-ы пишут "closes #номер ишуя", и тогда бот сам закрывает. Впредь будь осторожен.

прости, не знал, буду пользоваться

**Comment by LudwigVonChesterfield** [comment]
https://github.com/TauCetiStation/TauCetiClassic/wiki/Styling-of-Pull-Requests-for-Dummies

Рекомендую к прочтению.
