### ISSUE TITLE
[Proposal] Механосторона импланта лояльности

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5088]
#### Подробное описание проблемы

Дабы имплант лояльности в том числе имел смысл со стороны механа предлагаю сделать так, чтобы капитан и ГСБ могли какой-то фразой причинять боль людям с имплантом лояльности, а то и вовсе вводить их в крит. Что-то типо "%МИМОКРОКОДИЛ НЕЙМ%, будь добр" - бах мимокрокодил упал.

**Comment by Motzord** [comment]
https://youtu.be/cZSuBmROSL8

**Comment by DedYarick** [comment]
Это типо как в Portal 2? "Фраза которая может выключить любой ИИ", давайте тогда еще для ИИ такое сделаем, типо сказал в канал - ;ИИ, воет ли черная луна? и ИИ вырубается :D

**Comment by LudwigVonChesterfield** [comment]
На ИИ у меня другие идеи, возможно я их сейчас тоже запишу.

**Comment by Akellazp** [comment]
Так есть же хим импланты с разной начинкой
И вообще, не будет ли это работать против самих гсб и капитана (плюс еще авд)? У нас же только один тип импланта лояльности. 
Да и зачем причинять боль людям с имплантом лояльности, если они уже лояльны? Лучше уже ввести какой-нибудь электро-имплант с механом химического, но опять же, какой от этого смысл?

**Comment by LudwigVonChesterfield** [comment]
я не хочу чтобы """лояльность""" регулировалась исключительно педалями с помощью правил, потому-что они очевидно с этим не всегда справляются(да и попробуй управься с 70-ю игроками), и были средства механовлияния.

**Comment by LudwigVonChesterfield** [comment]
Можно импланту ввести "иерархию", типо звания, и те у кого звание выше - могут заставить чувствовать боль тех кто ниже:
ЕРТ -> Капитан/АВД -> ГСБ -> любые другие имплантированные люди

Плюс можно было бы зависимость от кода на станции приделать туда же, и т.д.
