### ISSUE TITLE
[Proposal] Нужны способы идентификации глухонемого персонала

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#5089]
На данный момент невозможно сразу понять имеет ли какой-либо человек такого рода инвалидности. На научном объекте вроде космической станции ИМХО подобные сотрудники раз и допускаются к работе, то должны снабжаться разного рода экипировкой которая позволит окрудающим определить их инвалидности.

Из идей пока что такие: бейджик на униформу, куртка или кепка с символикой и альтернативные варианты айди-карт.

Я примерно знаю как это реализовать, мне всего-лишь нужен спрайтер который нарисует эти предметы.

**Comment by Motzord** [comment]
![image](https://user-images.githubusercontent.com/45365635/79701218-7ef8d580-829b-11ea-99f1-94aab81df0df.png)

**Comment by Sage4or** [comment]
хахахаха смотрите как смешно пошутили про евреев в нацистких лагерях))))

нихуя не смешно, моцорд, ты кринж

**Comment by DedYarick** [comment]
Ну типо я могу заспрайтить :/

**Comment by LudwigVonChesterfield** [comment]
/obj/item/clothing/glasses/sunglasses/blindfold

**Comment by FelixRuin** [comment]
> /obj/item/clothing/glasses/sunglasses/blindfold

она выглядит некрасиво и глупо... только если троллить клоунов всяких

**Comment by atik1n** [comment]
Не нужны. И так по ним понятно при общении с ними

**Comment by LudwigVonChesterfield** [comment]
Играл за немого. Могу сказать что нет, людям непонятно.

**Comment by cool20141** [comment]
В me пишешь что-то типа "машет руками, показывает на рот"

**Comment by FelixRuin** [comment]
текстура есть, осталось придумать текст для аксесуара, который увидят только 2-3 человека, ибо это будет аксесуаром на одежду и будет видно только название
![image](https://user-images.githubusercontent.com/31424899/85112870-0375bf00-b21f-11ea-8d85-4ba8f8196e51.png)

**Comment by atik1n** [comment]
> Играл за немого. Могу сказать что нет, людям непонятно.

Я тоже. Обычно пишу в me "указывает на ухо и стучит по нему" как жест обозначающий глухоту и все понимают

**Comment by FelixRuin** [comment]
ишус можно закрывать, решён
