### ISSUE TITLE
Убрать флаф вещи вхардкоженные в билд.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5093]
#### Подробное описание проблемы

Большая часть вещей с /fluff/ в их типе - пережиток прошлого, когда флаф шмотки для людей впихивали прямо в код. С текущей системой флаффов - аморально устарело, и должно быть выпилено.

Не обязательно категорически выпиливать всё, в чём есть такой тип. Некоторые вещи, к примеру как - чайник можно корректно интегрировать в билд, вынести в нужный тип, и т.д.

**Comment by LudwigVonChesterfield** [comment]
(п.с.: убирать желательно со спрайтами)

**Comment by Sakuya-Izayoi** [comment]
униформа тест сабджектов это флаф предмет :smile:

**Comment by LudwigVonChesterfield** [comment]
Без проблемно можно интегрировать её в часть нашего билда, у неё теперь наш спрайт.

**Comment by KIBORG04** [comment]
У нас в билде есть механ, на кастомные вещи в для ИИшки. Нужно ли оно нам?
https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/mob/living/silicon/ai/ai.dm#L243

**Comment by LudwigVonChesterfield** [comment]
А что за кастомные вещи у ИИшки?

**Comment by KIBORG04** [comment]
Я же сделал строчку механа. Типо, если есть такой механ, значит где-то есть спрайты

**Comment by KatoMarika** [comment]
Вроде как избавились от подобного, наверное можно закрыть. Пинайте Симбаку если что. 
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/18484142/3427d9d4-5259-4c32-8eab-669fde9a6c1b)

**Comment by KIBORG04** [comment]
Полистал билд, похоже на то
