### ISSUE TITLE
Не переходит во вкладку floor при нажатии Alt+LMB.

### ISSUE THREAD

**Issue by Kandid-afk** [TauCetiStation/TauCetiClassic#5095]
Из-за новой боёвки поломалась вкладка floor. Раньше ты просто нажимал Alt+LMB на тайле и переходило на вкладку floor с отображение всего, что на этом тайле есть. 
Сейчас же вкладка появляется, но на неё не переходит автоматически.

**Comment by LudwigVonChesterfield** [comment]
Я так и задумывал, потому-что считал что это будет мешать боёвке. Если достаточно людей посчитают что нет, внезапно выскакивающия ебарыга справа не мешает(и не глючит) - я верну как было.

**Comment by LudwigVonChesterfield** [comment]
c464eb5
