### ISSUE TITLE
Ковер.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#510]
#### Подробное описание проблемы

Спрайты ковра сломались.
#### Что должно было произойти

Они должны быть в порядке.
#### Что произошло на самом деле

Они выглядят вот так...

![](http://i.imgur.com/ClfNABN.png)
#### Как повторить

Постелить ковер.
#### Дополнительная информация:

Добавьте ковер в карго, пожалуйста, пожалуйста.

**Comment by ZVee** [comment]
Описание репорта не менее важная деталь, чем описание самой проблемы внутри. Просьба отнестись к этому со всей серьезностью. С названия "ковер" вообще ничего не ясно. Что ковер? Отсутствует? Неправильно отображается? Работает как космос? Жрет ассистентов?..

**Comment by Raschert0** [comment]
Хм, по поводу ковра. Может уберём у него различия между дирам 1 и 2, а также 4 и 8? А то что-то мне подсказывает, что проблема именно в этом

**Comment by SpaiR** [comment]
@Skippeer12 стелил ковёр и так и этак, всё было ок. баг ещё актуален?

**Comment by Skippeer12** [comment]
@SpaiR 
![51](https://cloud.githubusercontent.com/assets/18488106/19746700/3f9c1db6-9be0-11e6-96a6-bc8fa61c2260.png)
Похоже на то.

**Comment by StrikS** [comment]
Есть немного...
![image](https://cloud.githubusercontent.com/assets/15943769/19749696/6adec400-9c04-11e6-944a-4b9125305450.png)
(16 октября)
