### ISSUE TITLE
[Proposal] Б-го-фичи.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5105]
#### Подробное описание проблемы

На данный момент у Б-га в палке капеллана литерали 0 возможностей взаимодействовать с миром кроме чатика, и это делает эту роль невероятно унылой.

Я считаю что в связи с тем что:
1) Эта роль зависит от присутствия другой роли - капеллана.
2) Эта роль одна на раунд.

Её можно пробаффать плюшками, и добавить интересных интересностей. Мои предложения:

- [x] Дать возможность "Б-гу" не просто сидеть в палке, а летать вокруг капеллана в пределах двух-трёх тайлов(и быть видимым только капеллану).
- [x] Дать возможность "Б-гу" взаимодействовать с миром хотя бы на уровне госта(Гостокубы, гостосвечи, и т.д.)
- [ ] Дать возможность "Б-гу" "нести" на себе какой-то предмет сакральной важности(библию, свечи, коробку, фляги)(или даже любой предмет). Как бы это работало: капеллан тыкает палкой по предмету, и теперь этот предмет "привязан" к Б-гу, и летает вместе с ним.
- [x] Сделать чтобы "Б-г" слышал молитвы.

Большие изменения, которые могут быть связаны с Б-гом:
- [x] Дать "Б-гу" какую-то абстрактную полоску "маны", от которой зависят его способности.
- [x] Дать капеллану алтарь для жертв Б-гу.
- [x] Жертвы Б-гу зависят от религии, если религия кастомная - Б-гу даётся выбрать какие жертвы он хочет.
- [ ] Какие-то мелкие способности Б-жку.

План-максимум, уход в сюр:
- [x] Дать возможность за ману кастовать заклинания мага.
- [ ] Заклинания которые может кастовать Божок определены типами жертв которые он принимает.

Идеи для способностей:
Некрономикон:
- [ ] "Surge of souls" - капеллан выбирает цель, и его Божок становится видимым, так же видимым становятся все госты которые крутились вокруг Божка - и они летят в цель, отпихивая её(или делая что-то в зависимости от интента).

**Comment by Sakuya-Izayoi** [comment]
Причёи тут Борис Гребенщиков?

**Comment by Bullethole** [comment]
Дать богу возможность тушить свет, нажимать кнопки, чуток взаимодействия,  слышать прей и  вселяться в людей на определённый срок, а так же, минимально лечить людей, но это по кнопке определённой

**Comment by Bullethole** [comment]
Можно бы было сделать фракцию, то есть бог мог вербовать бы людей, по определённой команде, как рева на минималках, это даст движ в отсеке церковь.
что бы бог имел власть над телами вербующих, и если это дальше вводить то можно сделать полноценный режим как  всеми известный  " дьявол" (привет ТГ) , но только немного другой

**Comment by KIBORG04** [comment]
Бога видит любой, кто взял палку. Всегда видно его облачко, когда говорит всем.

> Дать богу возможность тушить свет, нажимать кнопки, чуток взаимодействия, слышать прей и вселяться в людей на определённый срок, а так же, минимально лечить людей, но это по кнопке определённой

Я уже занимаюсь этим

**Comment by LudwigVonChesterfield** [comment]
@Bullethole Ты даже не читал основной пост, там про прей уже есть.

Кстати, тоже хочу добавить идею к разделе "Полный сюр":
- Капеллан который выбрал себе трость с Б-гом теряет возможность говорить на Галактик Коммоне, и может говорить только на языке своей религии.
- Люди у которых с капелланом одна вера получают язык его религии(либо читают библию)
- Атеисты не позволяют гостам вокруг них, а так же капеллану и его Б-жку делать какие-либо фокусы просто своим присутствием.

**Comment by Bullethole** [comment]
> @Bullethole Ты даже не читал основной пост, там про прей уже есть.
> 
> Кстати, тоже хочу добавить идею к разделе "Полный сюр":
> 
> * Капеллан который выбрал себе трость с Б-гом теряет возможность говорить на Галактик Коммоне, и может говорить только на языке своей религии.
> * Люди у которых с капелланом одна вера получают язык его религии(либо читают библию)
> * Атеисты не позволяют гостам вокруг них, а так же капеллану и его Б-жку делать какие-либо фокусы просто своим присутствием.
 
Можно бы было дать импульс, то есть полтергейст, что бы  ты был не просто идиотом с палкой, а значил что-то, и тебе бы обращались нормально, а не так что " ой да ты заебал это пИИ, за вызывающее поведение в дурку" 
Я читал основной пост, но поиграв два раунда с натосом  на роли бога, я понял что  прей он не видит от слова совсем, а все что он может, так это толкать того, кто держит палку, залезать в мусорку, крутить стулья  и выключать лампочки настольные, больше-ничего

**Comment by KIBORG04** [comment]
Ну так да, прей он не видит еще

**Comment by LudwigVonChesterfield** [comment]
> [Proposal]

Мне кажется ты не совсем понимаешь как работает гитхаб. Это мои предложения по тому что стоит добавить.

**Comment by Bullethole** [comment]
Ну, пока не хватает богу  возможностей, ломать лампы, это не просто пИИ на минималках а бог
( это можно сделать как акустический визг у шоуди но чуть послабее... 
Я бы вообще хотел взять эту фичу как у ТГ  у моба ревенант, сыпать солью на пол что бы бог не мог пройти через это, и еще кучу всего.
это мои идеи, но не предложения
Поглощать трупы, то есть со звуком культиста при использовании руны общения тело испарялось в кости, и это бы шло, как выше сказано на ману, с помощью которой бог может юзать абилки

**Comment by KIBORG04** [comment]
> Ну, пока не хватает богу возможностей, ломать лампы, это не просто пИИ на минималках а бог


Бог и так может проклятой свечкой это сделать с шансом 5%

**Comment by Bullethole** [comment]
> > Ну, пока не хватает богу возможностей, ломать лампы, это не просто пИИ на минималках а бог
> 
> Бог и так может проклятой свечкой это сделать с шансом 5%

Это сама свечка делает, а не бог, как я знаю

**Comment by KIBORG04** [comment]
> > > Ну, пока не хватает богу возможностей, ломать лампы, это не просто пИИ на минималках а бог
> > 
> > 
> > Бог и так может проклятой свечкой это сделать с шансом 5%
> 
> Это сама свечка делает, а не бог, как я знаю

Ну да. Щас бог мега-рп моб, который ниче не может.

**Comment by Bullethole** [comment]
> > > > Ну, пока не хватает богу возможностей, ломать лампы, это не просто пИИ на минималках а бог
> > > 
> > > 
> > > Бог и так может проклятой свечкой это сделать с шансом 5%
> > 
> > 
> > Это сама свечка делает, а не бог, как я знаю
> 
> Ну да. Щас бог мега-рп моб, который ниче не может.

Я верю, что ты реализуешь всё, я не тороплю, а просто даю свое мнение об игре

**Comment by FatFatFat1** [comment]
У нас есть спрайты призрака повернутых направо-налево ,почему бы Богу такое не дать?

**Comment by FatFatFat1** [comment]
Так-же Бог ,по какой-то причине умеет смывать себя в мусор и лопать пену

**Comment by SomeUselessGuy** [comment]
А можно сюда багрепорты кидать? ;D

**Comment by LudwigVonChesterfield** [comment]
лучше отдельно

**Comment by KIBORG04** [comment]
> А можно сюда багрепорты кидать? ;D

Лучше как ишью

**Comment by LudwigVonChesterfield** [comment]
Я полностью удовлетворен реализацией #5184
