### ISSUE TITLE
плазменный дробовик не стреляет после того, как батарейку сунули л10-с или зарядник.

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#5106]
#### Подробное описание проблемы
плазменный дробовик не может стрелять обоймами из под l10-c
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/44546836/79792797-318e6e00-8358-11ea-901a-337a419d776b.png)

**Comment by Motzord** [comment]
Я создавал блин уже три ишшуе на эту тему

**Comment by LudwigVonChesterfield** [comment]
#4574
