### ISSUE TITLE
Встроенный наушник ИИ ломается ЭМИ

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#512]
#### Подробное описание проблемы
Встроенный интерком, который позволяет ИИ говорить в каналы станции, ломается ЭМИ. Восстановить встроенный наушник нельзя (наверное можно его включить пересбором самого ядра, но я не проверял).
#### Что должно было произойти
ЭМИ задевает ИИ, наушник не ломается.
#### Что произошло на самом деле
ЭМИ задевает ИИ, наушник ломается.
#### Как повторить.
Быть ИИ, попасть под ЭМИ.

**Comment by MorCrate** [comment]
Уже обсуждали это, мнение сошлось на то, что это фича.

**Comment by ZVee** [comment]
Не знаю что вы там обсуждали - но возможности починки наушника в ИИ насколько я знаю не существует, к тому же если ИИ функционирует, значит и модули все должны функционировать при условии, что нет возможности их ремонтировать. Поэтому варианта тут два. Каких? Они в сообщении этом.
