### ISSUE TITLE
[Proposal] Сделать чтобы госты могли тыкать по предметам требующих гостов чтобы поменять свой преф.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5123]
#### Подробное описание проблемы

1. Сейчас если гост нажал "никогда в этом раунде" когда ему предложило стать позитронкой/нимфой/говорящей палкой, то он больше никак не сможет это поменять.
2. Если человек не выставил в префах "Be *нейм*", он не может это изменить в ходе раунда.

#### Что должно было произойти

Человек, без префа тыкающий по позитронке делает не *пилиньк*, а может выбрать хочет ли он быть позитрнокой.

#### Что произошло на самом деле

Такой фичи нет

**Comment by LudwigVonChesterfield** [comment]
Такую же фичу можно пришить гидропонически ванночкам, капсуле с сурвайвором, палке капеллана.

**Comment by KIBORG04** [comment]
Он может это изменить в ходе раунда. Во время игры тыкаешь Preference -> Toggle be Candidate Role

**Comment by KIBORG04** [comment]
Ну так это же осознанный выбор человека не участвовать в подобных событиях

**Comment by LudwigVonChesterfield** [comment]
... который он мог совершить случайно, или передумать. и понадобится осознанный выбор - кликнуть по предмету, чтобы его изменить
