### ISSUE TITLE
[Proposal] Небольшой реворк палки капеллана

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5125]
#### Подробное описание проблемы

Свечение вокруг нуллрода когда рядом госты, культи и т.д. is very annoying, я считаю что это можно было бы упразднить-заменить и т.д. .

Я предлагаю убрать свечение у нуллрода, и дать капеллану какой-нибудь "камень душ", капеллан сможет его юзать раз в 10 минут, и всем гостам(кроме тех которые до этого выбрали "капеллан не заёбывай меня" присылается  предложение выбрать одно из слов на выбор, допустим: "god", "cult", "blood", "wine". Капеллан по этим словам сможет оценить сколько гостов у него "в распоряжении"(если палка нужна была для этого). Этот же камешек мог бы светится в присутствии гостов и культей.

**Comment by KIBORG04** [comment]
Либо встроить в способки бога, когда я выложу фреймворк. 

Так же, я вообще не считаю это свечение ОП или раздражающим, но то, что оно работает и в нуллроде - нелогично

**Comment by LudwigVonChesterfield** [comment]
Я просто не хотел бы полностью привязывать капеллана к божку, и дать возможность игроку *знать*, сможет ли он играть "через гостов/божка" до того как он сделает палку и разочаруется в том что в неё не вселится никто.

Можно чтобы этот камень душ ещё собирал "желающих" гостов, и типо если гост подписался на камень душ - капеллан этот камень может вставить в палку/кубик/свечку/*вставь сюда предмет нейм*, и гост будет её воодушевлять.

Таким образом госты будут знать что капеллан хочет что-то делать с гостами, а капеллан будет знать сколько гостов готовы играться с ним.
