### ISSUE TITLE
С камерой obscura много что не так

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5129]
#### Подробное описание проблемы

![image](https://user-images.githubusercontent.com/17705613/80079437-f3ac6800-8558-11ea-8d48-cd26f3035be0.png)

**Comment by SomeUselessGuy** [comment]
Еще эктоплазма не спавнится

**Comment by Sakuya-Izayoi** [comment]
> Еще эктоплазма не спавнится при сжигании если на ней есть призраки

спавнится
