### ISSUE TITLE
Меметическая Аномалия может приковывать людей к стульям

### ISSUE THREAD

**Issue by ghost** [TauCetiStation/TauCetiClassic#513]
#### Подробное описание проблемы

Меме может садить людей на стулья.
#### Что должно было произойти

Мемас не может посадить человека на стул.
#### Что произошло на самом деле

Мемас может.
#### Как повторить

Взять человека, стать Меме, сесть в человека, посадить человека на стул.
#### Дополнительная информация:

![123](https://cloud.githubusercontent.com/assets/20542000/18133528/d0441f9e-6fbc-11e6-80d1-a9712e3a0c61.png)

**Comment by RichardJones1** [comment]
Судя по ПРу курша - пофикшено. К тому же меме уже не в ротации
