### ISSUE TITLE
Тыкая на облачко говора, и вообще на многие оверлеи мобов - можно попадать по самим мобам

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5134]
#### Дополнительная информация:

Можно им всем сделать mouse_opacity игнорящий клики, чтобы кликая по облачку ты не кликал по самой кукле.

**Comment by Sakuya-Izayoi** [comment]
это нормально

**Comment by LudwigVonChesterfield** [comment]
Это кстати в любом случае уже "закрыто".

**Comment by LudwigVonChesterfield** [comment]
#5137
