### ISSUE TITLE
Спавнится два соулстона, вместо одного

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#5136]
#### Подробное описание проблемы
Метод `/obj/effect/proc_holder/spell/aoe_turf/conjure/cast(list/targets)` работает не так как нужно.
Из-за такого цикла `for(var/i in 0 to summon_amt)` он делает одну операцию два раза, вместо одного
#### Что должно было произойти
Один соулстон
#### Что произошло на самом деле
Два соулстона
#### Как повторить
У констрактора культиста прожать способность.
#### Дополнительная информация:
Поменять цикл на другой
Либо, сделать `var/summon_amt = 1` равную 0

**Comment by Sakuya-Izayoi** [comment]
1 to summon_amt
