### ISSUE TITLE
У божка-из-палки есть взаимодействия смертных

### ISSUE THREAD

**Issue by SomeUselessGuy** [TauCetiStation/TauCetiClassic#5138]
#### Подробное описание проблемы
У божка-из-палки есть возможность перевернуть стол, преить (самому себе, судя по всему), делать Point To (и он будет виден абсолютно всем), поворачивать стулья и стекла, залезть в морг/сжигатель и остаться там пока священник не вытащит, рестить (через IC меню, еще из-за этого невозможно встать пока священник не оттащит) и получить МНОГО урона (каким-то образом, лол).

#### Что должно было произойти
Ничего из вышеперечисленного.

#### Что произошло на самом деле
Все из вышеперечисленного.

#### Как повторить
Стать божком-из-палки и перевернуть стеклянный стол, преить, указывать на что-то, вертеть стулья, попросить священника открыть морг, рестить, встать у синги.

#### Дополнительная информация:
Хелп

**Comment by LudwigVonChesterfield** [comment]
#5121

Это уже пофикшено, но видимо ещё не залили на сервер.

**Comment by SomeUselessGuy** [comment]
Еще он залезать на столы может

**Comment by SomeUselessGuy** [comment]
> #5121
> 
> Это уже пофикшено, но видимо ещё не залили на сервер.

Прошло три раунда, ничего не пофикшено (вроде как)

**Comment by LudwigVonChesterfield** [comment]
со след раунда отпишешься пожалуйста.

**Comment by cool20141** [comment]
Бог, в твоем понимании–обычная душа, никто, лошок какой-то? Да и стоит учитывать, что это не обычный призрак, а целая роль. Даже у пИИ есть способности взламывать двери, например, почему бог не должен ничего уметь? Это глупо, я считаю. Надо напротив, дать богу как можно больше сил и взаимодействий

**Comment by LudwigVonChesterfield** [comment]
Смотри в другой ишуй где описан план на Бога.

**Comment by SomeUselessGuy** [comment]
> Бог, в твоем понимании–обычная душа, никто, лошок какой-то? Да и стоит учитывать, что это не обычный призрак, а целая роль. Даже у пИИ есть способности взламывать двери, например, почему бог не должен ничего уметь? Это глупо, я считаю. Надо напротив, дать богу как можно больше сил и взаимодействий

То, что я написал в этом ишью - **исключительно** баги (на мой взгляд) на данный момент. 
Божок-из-палки, как бесплотная сущность, не может теребить стулья, столы (разбивая их таким образом), преить (т.к. видит это только он (или сойдет для призыва гостов, okay)). Три последних пункта - _точно_ баги - меня расплющило мусором от маяка мусорщика

**Comment by SomeUselessGuy** [comment]
Еще что-то... ![image](https://user-images.githubusercontent.com/40398890/80190428-b9f96100-862d-11ea-9ec8-5be132902dd1.png)
@LudwigVonChesterfield 
Столы все еще опрокидываются, стулья теребить нельзя, рестить все еще можно, тоже самое с моргом

**Comment by LudwigVonChesterfield** [comment]
#4236 #5167
