### ISSUE TITLE
Медицинский кризисный борг. Не поднять каталку и колбу.

### ISSUE THREAD

**Issue by kopoba** [TauCetiStation/TauCetiClassic#514]
#### Подробное описание проблемы
1. Медицинский кризисный борг не может свернуть, поднять сверную каталку.
2. Если поместить колбу в раздатчик а затем вынуть взять ее не получиться. Получиться только закрыть крышку. 
   Если поместить колбу в машину делающую таблетки затем не вынимая убрать активный модуль колбы в хранилище. Колбу нелья будет не только закрыть но даже включить как модуль будет нельзя. 
#### Что должно было произойти
1. Ранее при перетаскивании каталки на себя каталка сворачивалась после сворачивания и клике по ней помещалась в борга.
2.  Ранее колбу можно было поднять в модули после извлечения из диспенсеров.
#### Что произошло на самом деле
1. Каталка не сворачивается и не поднимается.
2. Колба закрывается крышкой при попытке ее взять. Модуль колбы становиться неюзабельным.
#### Как повторить

Взять борга взять медицинский кризисный модуль.
Попробовать использовать каталку или колбу.
#### Дополнительная информация:

PS. Реквестую нормальные адвансед бинты и мази. Нынешние кончаются на половине пациента приходиться бросать пациента и бежать заряжаться.

**Comment by Raschert0** [comment]
Могу сказать по поводу колбы:
1. Достаёшь колбу из машины
2. Убираешь модуль колбы в инвентарь
3. Достаёшь модуль колбы из инвентаря
4. Колба переместилась тебе в руку

**Comment by RichardJones1** [comment]
Да, боргоишью никогда не кончатся

**Comment by Motzord** [comment]
Я возможно не прав, но на подходе (если еще не вмержили) объединение кризис борга с медборгом и в принципе можно будет закрыть

**Comment by Zickusable** [comment]
Еще колбу можно дистанционно  убирать в инвентарь
вставлять в химмастер при том, что колба остается лежать на химдиспенсере, например
может быть даже доставать из него химикаты дистанционно?

**Comment by kiVts** [comment]
Этого борга даже нет уже
закройте пж а то стыдно

**Comment by kopoba** [comment]
Жаль что борга уже нет
