### ISSUE TITLE
[Proposal] Прекратить поддержку Гаммы, как карты.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5144]
#### Подробное описание проблемы

У нас нет никакой системы голосовача за карту игроками, а значит:
- 1. они не видят программный продукт на который надо затрачивать время.
- 2. они не имеют ни малейшего понятия что делать на этой карте, когда таки на неё попадают.
- 3. из-за второго пункта "нормальное" тестирование и отлажка практически невозможны, люди саму карту не знают, не то что её недостатки и достоинства.

**Comment by Akellazp** [comment]
Так может лучше сделать систему голосования?

**Comment by LudwigVonChesterfield** [comment]
Сделай.

**Comment by WatlerJe** [comment]
Если найдутся те кто будут поддерживать карту Гаммы, то передадим им, это же касается воута на нее. На данный момент мы не можем поддерживать ротацию карт ввиду отсутствия заинтересованных в этом кадров.

**Comment by Sakuya-Izayoi** [comment]
а чо, гаммасеки отказались от своего дитятки?

**Comment by Lexakr** [comment]
Отказ от поддержки подразумевает выпиливание файла с картой из билда? Если да, то я скорее против

**Comment by LudwigVonChesterfield** [comment]
Я думал скорее накидывание "FEATURE FREEZE" на любые ПР-ы по Гамме. На случай если кто-то вдруг захочет поддерживать карту - чтобы он знал что нужно-можно доделать.

**Comment by volas** [comment]
Воут не впиливался как-раз из-за того, что не было карт, только бокс-стейшен и впиленная по остаточному принципу для примера гамма. 
Если сейчас у гаммы есть поддержка, и она играбельна без проблем и вопросов со стороны администрации - можно было бы сделать уже общий воут.
