### ISSUE TITLE
[Proposal] Сломанные ЕФТПОСы

### ISSUE THREAD

**Issue by cool20141** [TauCetiStation/TauCetiClassic#5147]
#### Подробное описание проблемы
ЕФТПОС не проверяет пин-код на правильность. Можно у кого-нибудь украсть карточку, провести по ЕФТПОСу, написать любой пинкод (Хоть 228, хоть 1–какой хочешь). Перевод осуществится
#### Что должно было произойти
Неверный пин-код не подходит
#### Что произошло на самом деле
Подходит
#### Как повторить
Взять ЕФТПОС, настроить его, взять карточку, провести оплату, ввести неверный пин-код
#### Дополнительная информация:
Учитывая, что некоторые хотят поварам и барменам з/п убрать, стоит сканеры пофиксить, чтоб эти самые повара и бармены не обкрадывали честный экипаж

**Comment by totallynotdedawa2** [comment]
никто не ставит счёт на 1/2 уровни безопасности поэтому и без пин кода все работает

**Comment by cool20141** [comment]
Я пропосал хотел сделать

**Comment by cool20141** [comment]
Короче, типа сделать по дефолту 1 уровень картам. Или даже второй

**Comment by Ahion** [comment]
Я делал ПР с оплатой через ПДА. Сканером пользоваться не обязательно.

**Comment by cool20141** [comment]
Да, хорошую вещь ты сделал, не спорю, но это не отменяет того, что сейчас бармен может просто грабить всех подряд без проблем, потому что половина не знает, как поставить 1/2 уровень безопасности на карту, а другая половина просто не ставит. Если бы по дефолту стоял 1, например, то бармен бы пососал

**Comment by Ahion** [comment]
Да, проблемой безопасности я тоже обеспокоен. Если по умолчанию сделать всем пароль, то при оплате в вендоматах он тоже будет требоваться. Я думаю это не очень удобно. Нужен баланс между безопасностью и удобством.

**Comment by Sakuya-Izayoi** [comment]
Это не проблема. Всё работает как нужно. Никто никого не грабит потому что деньги нафиг никому не сдались. А если есть карта то можно ограбить и без ефтпоса просто сунув её в банкомат.

**Comment by cool20141** [comment]
> Это не проблема. Всё работает как нужно. Никто никого не грабит потому что деньги нафиг никому не сдались. А если есть карта то можно ограбить и без ефтпоса просто сунув её в банкомат.

Почитай, пожалуйста, темку полностью. Я предлагаю по дефолту поставить 1 уровень, чтоб бедные ассистухи не бегали голожопыми и без еды после похождений бармена или повара с ЕФТПОСом (Ну или других членов экипажа, у которых он есть)

**Comment by LudwigVonChesterfield** [comment]
#1634

Я думаю что в обоих случаях, это явно не баг. Если кто-то захочет заняться - может.

**Comment by Venngedi** [comment]
#10884 Старый ЕФТПОС удалён. Пропосал можно закрыть.
