### ISSUE TITLE
Спрайт магазина с патронами повышенной мощности

### ISSUE THREAD

**Issue by JustEmpty** [TauCetiStation/TauCetiClassic#5150]
#### Подробное описание проблемы
![цму34п](https://user-images.githubusercontent.com/61095037/80216458-bde5ad00-8646-11ea-8a69-3c71f8b02357.PNG)
![уи к45](https://user-images.githubusercontent.com/61095037/80216480-ca6a0580-8646-11ea-861b-59e5e6316ebd.PNG)

#### Что должно было произойти
Нормальный спрайт магазина с патронами .45 повышенной мощности
#### Что произошло на самом деле
Вот эта вот ракета произошла
#### Как повторить
Купить магазин 
#### Дополнительная информация:
Спасибо, поржали всей нюкой. 
Не знаю актуально ли ещё, спрайтов не было замечено 23.04.2020

**Comment by AndroBetel** [comment]
должно быть пофикшено за сегодня...

**Comment by LudwigVonChesterfield** [comment]
#4027
