### ISSUE TITLE
Симплмобы не могут молиться

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5163]
#### Подробное описание проблемы
При игре за симпл моба ты не можешь молиться
#### Что должно было произойти
Помолился- получил (не получил) то что хотел (просто печеньку)
#### Что произошло на самом деле
Все симпл мобы радикальные атеисты
#### Как повторить
Стать симпл мобом (например халк) и попытаться в pray

**Comment by LudwigVonChesterfield** [comment]
Этот баг мог быть вызван рантаймом, который фиксился в #5106
