### ISSUE TITLE
Где очки в карго?!

### ISSUE THREAD

**Issue by ArtBsd1** [TauCetiStation/TauCetiClassic#5178]
#### Подробное описание проблемы
Новая обстановка отличная, но не для карго. Вся работа мусорщиков она не доходит до карго. 
![image](https://user-images.githubusercontent.com/44677341/80382348-9fd4b280-88bb-11ea-8168-2066d7f25fb9.png)

#### Что должно было произойти
Мусор должен был оказаться в карго
#### Что произошло на самом деле
Застряло в стенке
#### Как повторить
Выкинуть мусор 
#### Дополнительная информация:
Может быть это уже замечено.

**Comment by Lexakr** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/5176
