### ISSUE TITLE
Если заменить батарейку в костюме ниндзи, то spiderOS сменит имя носителя

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#518]
#### Подробное описание проблемы

Берешь батарейку, кликаешь ею по костюму ниндзи, улучшаешь батарею, заходишь в spiderOS, а там вместо вашего имени: welcome high-capacity power cell
#### Что должно было произойти

Имя носителя должно было остаться
#### Что произошло на самом деле

Имя носителя сменилось на название батарейки
#### Как повторить

Ткнуть батарейкой по костюму
#### Дополнительная информация:

<img src="http://linkme.ufanet.ru/images/1161293d1dec74fb1dc814c4f86f6b77.png" width="495" height="18" alt="Безымянный.png" title="Безымянный.png"/>
<img src="http://linkme.ufanet.ru/images/5ab00604783f554a9104da5dfe18feaf.png" width="281" height="71" alt="Безымянный.png" title="Безымянный.png"/>

**Comment by igigin** [comment]
Не смог воспроизвести, зато когда апгрейдишь, super-capacity становится сломанной high-capacity, hyper становится сломанной super, а дальше не проверял.

**Comment by Damirrus1** [comment]
Блюспейс вроде тоже в обычную превращается
