### ISSUE TITLE
Сломанные титры после #5146

### ISSUE THREAD

**Issue by 4310V343k** [TauCetiStation/TauCetiClassic#5195]
#### Подробное описание проблемы
#5146 
![image](https://user-images.githubusercontent.com/56449763/80593868-9a49aa80-8a2a-11ea-94fb-3ef47f5da248.png)
#### Что должно было произойти
+-0
#### Что произошло на самом деле
-67500
#### Как повторить
~

**Comment by Ahion** [comment]
А не все ли равно на рейтинг станции?))

**Comment by cool20141** [comment]
Просто выглядит так, будто каждый раунд не чистый на руку ГП подворовывает
