### ISSUE TITLE
[Proposal] Loading hints

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#5199]
А что если взять эту ссылку:
https://wiki.taucetistation.org/%D0%9F%D0%BE%D0%BB%D0%B5%D0%B7%D0%BD%D1%8B%D0%B5_%D1%81%D0%BE%D0%B2%D0%B5%D1%82%D1%8B#.D0.98.D0.BD.D1.82.D0.B5.D1.80.D1.84.D0.B5.D0.B9.D1.81

И сделать из советов в ней подсказки загрузочного экрана, появляющиеся каждый раз при входе в лобби?
Пример:
:nukeops: Остерегайтесь горящих трупов, если прикоснутся к ним и вовремя не потушить себя, то Вы можете умереть за считанные секунды. Жалкая смерть для оперативника. :nukeops:

**Comment by volas** [comment]
тут проблема не в том, что бы сделать, а что бы набрать достаточное количество подсказок и соответствующе оформить.
