### ISSUE TITLE
Телепорт абдукторов.

### ISSUE THREAD

**Issue by SkLepP** [TauCetiStation/TauCetiClassic#520]
#### Подробное описание проблемы
Если нажать на кнопку Retrieve Mark и при этом стоять на телепорте, то тебя меняет местами с маркированным персонажем.
#### Что должно было произойти
Маркированный персонаж должен вернуться на корабль, а ты должен остаться на месте.
#### Что произошло на самом деле
Маркированный персонаж попадает на корабль, а тебя телепортирует на место маркированного персонажа.
#### Как повторить
Играя ученым пометить агента, телепортировать его на станцию, после чего встать на телепорт и нажать Retrive Mark.

**Comment by dearprincesscelestia** [comment]
Несмотря на то, что это баг- это выглядело бы клево в качестве фичи. Отдельно прописанной.
1. Помечаешь кого-то.
2. Даешь ему убежать.
3. Ждешь, когда он будет с кем-нибудь наедине.
4. Меняешь его на агента.

Хотя может быть слишком сложно для игроков.

**Comment by SkLepP** [comment]
Да, и в то время, когда ты поменял его на агента, он дизармит жопой ученого, цепляет к столу и прощайте господа абдукторы.05.09.2016, 15:27, "dearprincesscelestia" <notifications@github.com>:Несмотря на то, что это баг- это выглядело бы клево в качестве фичи. Отдельно прописанной.
1. Помечаешь кого-то.
2. Даешь ему убежать.
3. Ждешь, когда он будет с кем-нибудь наедине.
4. Меняешь его на агента.

Хотя может быть слишком сложно для игроков.

**Comment by SkLepP** [comment]
Да, а потом тот, кого ты поменял с агентом дизармит жопой ученого на корабле, цепляет к столу и прощайте господа абдукторы.

**Comment by dearprincesscelestia** [comment]
Отлично же.
