### ISSUE TITLE
Неправильно отображение показа бумажки и выдача костюма капсулой

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5204]
#### Подробное описание проблемы
Когда кто-то кому-то показывает бумажку, то в чат выводится сообщение что это ты показываешь человеку бумагу, а не тот, кто действительно это делает. Также когда ктото пытается активировать капсулу на станции, то она "обращается" не к нему, а ко всем вокруг, но через "you"
![image](https://user-images.githubusercontent.com/47355061/80719007-8a51c980-8b03-11ea-8a36-26190780fc4f.png)

#### Что должно было произойти
Корректное отображение кто кому показывает бумажку, капсула "обращается" к активировавшему человеку
#### Что произошло на самом деле
То что описано выше
#### Как повторить
Все описано выше

**Comment by muWander** [comment]
С книгой то же самое

**Comment by LudwigVonChesterfield** [comment]
#4683 #4675 

это как-то интересно что такие схожие проблемы...

**Comment by LudwigVonChesterfield** [comment]
#6266
