### ISSUE TITLE
[Task] Рефакторинг ивентера [$15]

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#5210]
### Подробное описание проблемы
У каждого билда ССки есть Ивентер. Он запускает различные ивенты в зависимости от веса подсчитанных проф, времени со старта раунда и прочего. Нужен он для того, чтобы создавать на станции рандомные события в зависимости от числа играющих. Иными словами - чтобы не было скучно.

Ивентер ТК устарел и требует перепила под современные запросы игры, подробно об нашем ивентере можно прочитать здесь:
https://docs.google.com/document/d/1HdQbrWU78egBZXWXKYoGoO2ozAPhy-eoG1EFH2QTDlI/edit?usp=sharing

### Что нужно сделать

* Портировать и адаптировать c Paradise контроллер ивентов и педальный интерфейс к нему:
  * <https://github.com/ParadiseSS13/Paradise/blob/master/code/controllers/subsystem/events.dm>
  * <https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/events/event_container.dm>
  * <https://github.com/ParadiseSS13/Paradise/tree/master/code/modules/events>
* Провести ревизию всех текущих наших рандом ивентов, починить что сломалось, переписать в соответствии новому контроллеру ивентов
* Убрать ивенты из админской панели Secrets в пользу нового интерфейса
* (опционально) Портировать новые ивенты. Даже если будет что-то спорное - можно оставить за педальными кнопками. Ну и, не обязательно только с парадайзов, контроллер и датумы везде одинаковые.

Почему за пример взят Парадайз - ивент контроллеры везде одинаковые, как на TG. Но оригинальный TG не учитывает весы ролей, а на Парадайзах проделали уже некоторою работу и адаптировали идеи Бэя по учету весов ролей, и разделили ивенты на потоки незначительных/значительных/мажорных (пда-спам не будет соревноваться с метеоритами за шанс). Так что за пример для рефакторинга он более всех подходит. И система обособленна, так что для простоты можно портировать.

## Detailed description of the problem

Every Space Station 13 build has an "eventer" system. It manages different events, in regard to weight of jobs in round, time from round's start, etc. "Eventer" is required to create different random occurences depending on how many players are playing. In other words - make it so rounds are not bland, and boring.

Tau Ceti's Eventer is morally and technically outdated, it requires a major rework to fit modern state of the game. Here it would be possible to read in great detail about the current eventer, albeit in russian: https://docs.google.com/document/d/1HdQbrWU78egBZXWXKYoGoO2ozAPhy-eoG1EFH2QTDlI/edit?usp=sharing

## What should be done

- Port and adapt Paradise's event controller, and make an admin interface to it:
- https://github.com/ParadiseSS13/Paradise/blob/master/code/controllers/subsystem/events.dm
- https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/events/event_container.dm
- https://github.com/ParadiseSS13/Paradise/tree/master/code/modules/events

- Make a revision of all current random events in codebase, fix whatever's broken, rework up to date to the new version of the "eventer".
- Remove events from Secrets admin panel, in favour of the new interface.
- (optionally) Port new events. Even if something is contentious - it could be hidden behind admin shitspawn priveleges. Also, the ported events shouldn't be specifically from paradise, just whatever place that uses the same controller.

Why Paradise? Event Controllers are the same everywhere, but TG's dynamic event doesn't tally up the weight of different roles, while Paradise already made work in the regard, to adapt to Bay's sub-jobs. They also split the events into minor/major/important (so PDA-spam won't be contesting with meteors for a chance of occuring). As such, it's a better example for a rework.

**Comment by Ahion** [comment]
@WatlerJe откуда такой документ по ивентеру? Довольно разжевано написано.

**Comment by WatlerJe** [comment]
Сам написал, лел.

**Comment by Zmey25** [comment]
Нужно инфу на вику скинуть, если никто не возмется переписывать

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/predlozhenie-po-tau-v-czelom/18486/25
