### ISSUE TITLE
[Proposal] Полное абстрагирование "наблюдателей" из раундов.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5220]
#### Подробное описание проблемы

На данный момент "госты" очень часто по тем или иным причинам проникают в раунд - в роли ЕРТ-шников, нимф, големов, и т.д. . И почти всегда вместе с этим так или иначе притаскивают свои знания, полученные не легетимным путём. Я предлагаю это прикрыть механом.

#### Задание

1. Люди, решившие "наблюдать" за раундом, и желающие получать полную инфу по раунду - не должны мочь вернуться в этот раунд.
2. Люди, которых так или иначе вывели из игры должны мочь вернуться в игру дабы не слишком скучать.

#### Предложение

Всех гостанувшихся, и обзерверов изначально пихать в некую локацию, допустим "Рай", из которой они могут возвращаться в раунд(так как не имеют информации о нём) посредством вызовов ЕРТ, нимф, големов, пИИ, позитронок, а так же "микроивентов"(Капсула с выжившим на дереликте, и ивентов которые нужно было бы добавить(см. ниже)).

Когда в "Раю", игрок может прожать кнопку аки "Наблюдать за раундом", что сделает его привычным нам гостом - который летает, читает, и смотрит. Но уже никак не может вернуться в игру абсолютно - ни респавнов, ни микроивентов.

#### Задания

- [ ] Локация на слое ЦК(вероятно) - "Рай"(или какой-нибудь Бар), в которую попадают гостнувшиеся игроки.
- [ ] Опция "наблюдать за раундом" для гостнувшихся игроков. Наблюдающие игроки не могут вернуться в игру.
- [ ] Перепиливание всех поисков "гостов", на поиск людей в "Раю"(пИИ, нимфа, голем, позитронка).

#### Саб-задания

Дабы сделать это изменение качественно, вероятно стоило бы завезти некоторый контент, который не позволил бы сидящим в раю слишком скучать:

- [ ] Ивент "Шаттл торговцев". Рандомная структура в космосе - "Шаттл торговцев" имеет N подов для гостов, любой из тех кто в "Раю" может заспавниться в этом поде, если они все не заняты.
- [ ] Ивент "Шаттл Синдиката". Рандомная структура в космосе - "Шаттл синдиката" имеет N триторов со своим личным(статическим, допустим он без топлива) шаттлом, любой из тех кто в "Раю" может заспавниться на этом шаттле.
- [ ] Ивент "Цивилизация". Структура на астероиде, в которой иногда появляются поды для желающих "повыживать".
- [ ] Возможность вселяться во всякую животинку по типу карпов, голиафов, и василисков для любителей ультрахардкора.

#### Дополнительная интеграция

С такой системой можно было бы дать чуть больше механа существующим на станции профам(в основном связанным с "загробной жизнью", и "исследованиями")

- [ ] Надобность капеллану "отпевать трупы" - чтобы игрок не мог попасть в рай пока это не произойдёт, и вместо этого был бы гостом который может отлететь допустим на три тайла от трупа.
- [ ] Ритуалы капеллана которые могут отправить человека в Рай на какое-то время(все равно люди в раю имеют очень мало инфы по раунду)
- [ ] Переделать телесаенс под "исследовательский корпус" со своим дедикейтед охранником или двумя.

**Comment by cool20141** [comment]
А как они станут големами/нимфами, если для этого нужно находиться на локации, где делаются эти големы/нимфы.
А так идея очень классная. На ТГ или где-то еще для гостов была такая приколюха, что они могли заспавниться на заброшенной станции и чинить ее (Мб как-то иначе, не помню). Чем-то напоминает свалку, которую, увы, админы включают раз в 100 лет

**Comment by Sakuya-Izayoi** [comment]
сделать большой сад с музыкой, вином и девушками и чтобы там всем было хорошо чтобы никто не захотел возвращаться в раунд

**Comment by cool20141** [comment]
> сделать большой сад с музыкой, вином и девушками и чтобы там всем было хорошо чтобы никто не захотел возвращаться в раунд

И если у него в религии Islam, то спавнить 72 гурии и разрешать ЕРП

**Comment by LudwigVonChesterfield** [comment]
> А как они станут големами/нимфами, если для этого нужно находиться на локации, где делаются эти големы/нимфы.

... нимфам не нужно "тыкать" чтобы стать нимфой. големов можно переместить на механ нимфы

**Comment by cool20141** [comment]
> > А как они станут големами/нимфами, если для этого нужно находиться на локации, где делаются эти големы/нимфы.
> 
> ... нимфам не нужно "тыкать" чтобы стать нимфой. големов можно переместить на механ нимфы

Бля, я не про тыкать, а про то, что типа на какой-то локации они определенной находятся (Выращиваются). Например, если человек видит, что где-то в глубине техов выращивают плод с нимфой, то он может не захочет там рождаться. А если големам сделать механ нимф, то не очень круто будет, потому что будет происходить то же самое. Если сделать что-то вроде отметки на карте, где конкретно появляться будет, то круто будет (Хотя уже мертвым любая возможность вернуться в игру будет в радость)

**Comment by skvazarb** [comment]
Сама концепция запрещать входить в раунд из-за нажатия одной кнопки слишком жестокая. У нас обычный раунд даже в прайм тайм может идти 1.5-2 часа, в другое время счет может идти на часы. При этом мы хотим видеть как можно больше игроков в игре, а не в обсерве. Потому что у нас тут все-таки игра, а в обсерве в нее не играешь. Способов нелегально спалить режим, антагонистов и прочее и в самой игре достаточно и кооперы всякие есть. Поэтому такие случаи все равно приходится контролировать, тут расчет в любом случае на порядочность игроков и контроль со стороны администрации. Возможность зайти через 30 минут в игру особой погоды тут не делает, таймер вполне выступает достаточным ограничением, чтобы это как-то сильно абузить. Если игрок увидит, что на станции энергии нет, людей лечить некому или что-то еще и использует эту информация для выбора слота, то это даже и хорошо.  За долгое время существования этой системы, конечно, были единичные проблемы, но они не когда становились массовыми и не были серьезной проблемой.

Улучшение времяпровождения после смерти, наверное, выглядит хорошо, но беспокоят возможные недостатки. Если получится сделать его хорошо, то это может подорвать ценность жизни персонажа для игроков. Если после смерти они получат не менее скучный геймплей, а может и лучше (лол). А если получится плохо, то получится, что мы у игроков отбираем возможность хотя бы посмотреть за раундом под угрозой запретить в него возвращаться.

**Comment by da-kiselev** [comment]
Всеми руками за, но только вместо «рая», нужно сделай свой уютненький бар, наподобие того, что находится в шляпе. И концепция бара всем ясна и понятна, и набухаться можно, романтика. Ну и идея с тем, чтоб стряхнуть пыль с гробов хорошая. Только вместе с этим предлагаю добавить выбор персонажу, в его настройках, можно ли его будет клонировать или нет. Это как бумажка с разбором на органы, но тут будет механом определяться, можно ли клонировать человека или нет.

**Comment by Motzord** [comment]
Вместо рая нужен пляж...

**Comment by LudwigVonChesterfield** [comment]
я рад что каждый из вас предложил своё видение "рая", но это предложение не об этом

**Comment by skvazarb** [comment]
Отдельно осуждаю эту презумпцию виновности гостов. На личном опыте могу сказать, я очень часто заходил в раунд из гостов. Разумеется, плевать я хотел на всех этих ролей и знания о раунде, кому они вообще нужны. И таких игроков намного больше, в десятки раз больше чем вот этих довольно мифических абузеров. Особенно часто заходил за дрона, когда там какую-нибудь очередную бомбу в главном коридоре взорвут. Часто даже в довольно оживленное время некому заняться разгермой посреди станции или обрывом кабеля. Много раз видел как единственное разбитое окно или повреждение буквально метра кабеля приводили к вызову шаттла.

**Comment by LudwigVonChesterfield** [comment]
Совсем забыл это написать, но дописал

> Наблюдающие игроки не могут вернуться в игру, но могут вернуться в "Рай".

**Comment by Pivo24** [comment]
Будут ли госты возвращаться в Рай и брехать всем остальным чего им ждать за ЕРТ... :thinking:

**Comment by LudwigVonChesterfield** [comment]
Хм, это действительно плохое предложение. Разве-что их делать немыми :joypain:

**Comment by DedYarick** [comment]
Если "Рай", будет нормально реализован, обоими руками "За", если нужны будут спрайты, буду рад помочь :)

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/fludilka-dlya-obsuzhdeniya-imbalansnyh-mehanik-i-ih-fiksa/18343/44

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/fludilka-dlya-obsuzhdeniya-imbalansnyh-mehanik-i-ih-fiksa/18343/53

**Comment by FelixRuin** [comment]
если хоть кто-то решит делать это, то вот вам концепт "рая" 
![image](https://user-images.githubusercontent.com/31424899/85097764-2db88400-b201-11ea-8dde-731d921c2fe7.png)

**Comment by LudwigVonChesterfield** [comment]
кринж какой-то просто выпилите обзерв и гост кнопки
