### ISSUE TITLE
[Реворк капеллана] Проблема с мультитаском.

### ISSUE THREAD

**Issue by JustEmpty** [TauCetiStation/TauCetiClassic#5228]
#### Подробное описание проблемы
Мультитаск позволяет проводить один и тот же ритуал огромное количество раз без затрат благосклонности.
#### Что должно было произойти
Один ритуал в один момент времени
#### Что произошло на самом деле
![ци43п](https://user-images.githubusercontent.com/61095037/80922519-5f2adc80-8d86-11ea-94fc-48253afcf5c1.PNG)

#### Как повторить
Начать делать ритуал много раз.
#### Дополнительная информация:
В этой куче еды нашёл даже 500 кредитов

**Comment by LudwigVonChesterfield** [comment]
мультитаск был ошибкой

(там отсутствовала проверка is_busy, которая критическая для корректной работы мультитаска)

**Comment by KIBORG04** [comment]
> В этой куче еды нашёл даже 500 кредитов

Шоколадных

**Comment by JustEmpty** [comment]
> Шоколадных

Так-то настоящих)
