### ISSUE TITLE
[Proposal] Доп. интеграция менторов.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5250]
1. Кнопка "Ping Mentorhelp", игрок увидев малогея может за него заполнить вопрос в менторхелп, и ментор увидит этот вопрос и свяжется с малогеем. Что-то по типу:
Gay AI Ааа как делать чтобы слышали борги
Вася Пупкин жмякает ПКМ по Gay AI -> "Ping Mentorhelp"
Вася Пупкин пишет "Научите пожалуйста борга писать в бинарку"
Менторы отвечают.

2. Менторам позволить писать ПМ-ки самому игроку, когда дело касается механа.

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/mozhet-vypilit-vne-igrovye-chaty-iz-igry-looc-ooc/17862/57

**Comment by LudwigVonChesterfield** [comment]
1. Грубо говоря сейчас можно воспроизвести если спамить в прей просьбами о менторе-госте...
(Если бы 2 было реализовано)

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/mozhet-vypilit-vne-igrovye-chaty-iz-igry-looc-ooc/17862/79

**Comment by Snailcat** [comment]
Эта функция будет пользоваться спросом только у менторов не в раунде. Так как отвлекаться от игры и проводить полный курс "смены рук" - менторы в раунде будут только если им нечем в нём заняться.

**Comment by LudwigVonChesterfield** [comment]
Ничего не мешает сделать чтобы эта фича работала толкьо если ментор гост.

**Comment by Snailcat** [comment]
Идея Воласа мне также очень нравится.
> менторам нужна просто возможность писать игрокам с <N минут, я думал сделать но посмотрел на менторчат и передумал.
>
Сделать чтобы игроки могли менторы могли ПМить игрокам c <N минуток, и то что ты предложил - чтобы игроки могли ПМить менторам от лица других игроков с <N минуток.

**Comment by LudwigVonChesterfield** [comment]
Это ровно точно то, что я предложил только с "< N минуток"(И то в первом предложении я это kinda imply...)
