### ISSUE TITLE
Иногда не работает комбо

### ISSUE THREAD

**Issue by cool20141** [TauCetiStation/TauCetiClassic#5255]
#### Подробное описание проблемы
Комбоочки набраны, но альт-клик не работает
#### Что должно было произойти
Комбо должно работать
#### Что произошло на самом деле
Комбо не работает
#### Как повторить
Не знаю, просто много и часто сражаться, возможно баг произойдет
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/53309265/81207423-31d46d80-8fd6-11ea-82e2-20b5dce4f970.png)

**Comment by Motzord** [comment]
Комбочка может не работать если ты ее набил и только потом прицелился куда тебе надо. Для этого надо внезапно, побегать или подождать. 

Считаю это не багом а фичей, которая немного наказывает механоабузеров

**Comment by LudwigVonChesterfield** [comment]
Это связано с тем что в логике смены прицеливания куклы нет "обновления" комбы, она обновляется грубо говоря в Life() который вызывается раз в две секунды. Это можно пофиксить.

**Comment by TungstenOctopus** [comment]
Действительно, появление комбо часто опаздывает и из-за подобной задержки исход боя сильно меняется. Это обязательно нужно фиксить, если это возможно.

**Comment by LudwigVonChesterfield** [comment]
f73aa59
