### ISSUE TITLE
В Waste Disposal есть air alarm, но нет вентиляции

### ISSUE THREAD

**Issue by Tiarv** [TauCetiStation/TauCetiClassic#5261]
#### Подробное описание проблемы
В помещении Waste Disposal (под погрузочным залом Карго) есть Air Alarm но отсутствуют Air Vent'ы. А еще там есть disposal inlet/outlet'ы без airtight flaps и конвейер. Таким образом мы имеем помещение, в котором неминуемо сработает тревога при его корректном использовании (и будет откачан атмос) и невозможно ее корректное и/или удаленное (с поста атмостеха) устранение - только с ручным блокированием дверей и распахиванием створок фомкой.

#### Что должно было произойти
После срабатывания тревоги на место приходит инженер и врубает накачку воздуха с пульта, воздух накачивается.

#### Что произошло на самом деле
После срабатывания тревоги на место приходит инженер, врубает накачку воздуха с пульта... но в помещении нет вентиляции, поэтому воздух не накачивается.

#### Как повторить
Приходим в Waste Disposal, нажимаем кнопочку Disposal Vent Control на стене, поворачиваем рычаг disposal conveyor. Получаем атмосферную тревогу.

#### Дополнительная информация:
Box Station

**Comment by Tiarv** [comment]
На самом деле беда не велика, потому что раунды в которых этим помещением вообще кто-нибудь воспользуется хоть раз - довольно редки.

**Comment by Lexakr** [comment]
Наверное, 2 варианта:

1. Заменить флапсы на шахтерские
2. Удалить аир алярму

**Comment by Tiarv** [comment]
Можно еще вент и скраббер поставить, наверное.
