### ISSUE TITLE
Спавн запрещённой(?) еды на алтаре священника

### ISSUE THREAD

**Issue by 4310V343k** [TauCetiStation/TauCetiClassic#5268]
#### Подробное описание проблемы
Если на алтаре заспавнить еду, может появиться еда, которую нельзя создать в билде. К примеру, Roburger, который при съедении превращает человека в борга
#### Как повторить
Рандом

**Comment by KIBORG04** [comment]
Странно, что вы это говорите именно об алтаре, когда та же проблема и у экстракта слизня, где спавнится даже "еда"(это даже не еда, а абстрактная вещь, которую в игре никто не должен видеть), которая не имеет спрайта.. А робо-бургер создать можно было всегда, на вики про него написано.

**Comment by Motzord** [comment]
Друг, есть два вида робергера. Педальный со 100 грифозными боргонанитами гарантированно и игровой где их количество рандомно и шанс 1/4 что будет робургер с 5 единицами.

**Comment by KIBORG04** [comment]
> Друг, есть два вида робургера. Педальный со 100 грифозными боргонанитами гарантированно и игровой где их количество рандомно и шанс 1/4 что будет робургер с 5 единицами.

Откуда ты берешь инфу, если не из кода? Потому что у обычного робобургера шанс на 2 юнита нанитов 5%. 
И я не вижу ничего ужасного и плохого в грифозной еде, ведь те же ксенобиологи ее намного проще и в больших количествах получают.

**Comment by Motzord** [comment]
> > Друг, есть два вида робургера. Педальный со 100 грифозными боргонанитами гарантированно и игровой где их количество рандомно и шанс 1/4 что будет робургер с 5 единицами.
> 
> Откуда ты берешь инфу, если не из кода? Потому что у обычного робобургера шанс на 2 юнита нанитов 5%.
> И я не вижу ничего ужасного и плохого в грифозной еде, ведь те же ксенобиологи ее намного проще и в больших количествах получают.

я код не смотрел, помню просто робургеры на локалочке тестил, так что ты скорее всего прав
