### ISSUE TITLE
Поломанный weapon disarm

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5270]
#### Подробное описание проблемы
#4134

Weapon Disarm работает тогда и только тогда, когда в комбо есть 3 дизарма, если дизармнуть четвертый раз, то более у тебя не выйдет провести weapon disarm, пока комбо не сбросится полностью
#### Что должно было произойти
weapon disarm должен работать  и при четырех дизармах
#### Что произошло на самом деле
Пушнул четвертый раз и пососал.

**Comment by Motzord** [comment]
@LudwigVonChesterfield

**Comment by LudwigVonChesterfield** [comment]
Нажми Q
