### ISSUE TITLE
Атака емкости при набирании жидкости

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5272]
#### Подробное описание проблемы
Когда ты набераешь жидкость из емкости куда-либо то ты акатуешь емкость (бьешь ведром ватертанк, горелкой фуелтанк и тд)
#### Что должно было произойти
Спокойно набираешь жидкость/восполняешь топливо
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/47355061/81479291-00a0ab00-922b-11ea-9ed6-f58f5fc71bf6.png)
![image](https://user-images.githubusercontent.com/47355061/81479302-0b5b4000-922b-11ea-8084-1b4a37c1cd23.png)

#### Как повторить
Написано выше

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/5271
