### ISSUE TITLE
Не идет обновление спрайта в виде предмета.

### ISSUE THREAD

**Issue by Andreikepka** [TauCetiStation/TauCetiClassic#5278]
#### Подробное описание проблемы
Я измазал кровью ботинки, и пошел их мыть. Мою мою и его спрайт в виде предмета не был обновлен, он всё так-же остался в крови. На персонаже они стали чистыми, в виде предмета нет.
#### Что должно было произойти
Ботинки в виде предмета тоже должны стать чистыми.
#### Что произошло на самом деле
Ботинки в виде предмета всё ещё в крови, на персонаже чистые.
#### Как повторить
Просто утопить в крови-смазке вещи.
#### Дополнительная информация:
Старый баг когда-то уже был и его исправили. И он вернулся.
Предметы в UI:
![Screenshot_1841](https://user-images.githubusercontent.com/62898551/81512381-ddf4bc00-9328-11ea-89d5-39013da117ba.png)
Описание предметов через просмотр:
![Screenshot_1842](https://user-images.githubusercontent.com/62898551/81512403-02509880-9329-11ea-9ab9-79391b494a75.png)
Предметы на персонаже.
![Screenshot_1840](https://user-images.githubusercontent.com/62898551/81512409-16949580-9329-11ea-8d73-5327181ea882.png)
![Screenshot_1843](https://user-images.githubusercontent.com/62898551/81512414-1bf1e000-9329-11ea-87a4-45aa3b05a003.png)
P.S На другие предметы так-же идёт

**Comment by Sakuya-Izayoi** [comment]
Возможные дубликаты:
#3859
#1551

(на самом деле их больше)
