### ISSUE TITLE
Сломались преференсы.

### ISSUE THREAD

**Issue by GoodGrief1488** [TauCetiStation/TauCetiClassic#5284]
#### Подробное описание проблемы
При старте раунда игрокам не выдаются профессии, которые должны выдаться при их преференсах. Например, у меня стоял высокий преференс на детектива и низкий на кадета. Детектива нет, а я кадет. 
![image](https://user-images.githubusercontent.com/55449535/81829812-fab90b80-9543-11ea-8e35-ce001b3f968f.png)

#### Что должно было произойти
Игрокам даются профы на которые они ставят высокий преференс.
#### Что произошло на самом деле
Профы остались пустыми.
#### Как повторить
задеклариться при старте раунда.

**Comment by LudwigVonChesterfield** [comment]
В связи с ПР-ом #5274 у всех сброшен в префах хай преф, в ченжлоге это есть.

**Comment by GoodGrief1488** [comment]
Преференс был установлен обратно, но всё-равно происходит это.
