### ISSUE TITLE
СМЕСы на спутнике разряжаются за полчаса

### ISSUE THREAD

**Issue by Raschert0** [TauCetiStation/TauCetiClassic#529]
#### Подробное описание проблемы
СМЕСы на спутнике ИИ и в серверной разряжаются за полчаса
#### Что должно было произойти
До ПРа Денноковских изменений их хватало на несколько часов
#### Что произошло на самом деле
СМЕСы разрядились за полчаса с начала смены
#### Как повторить
Запустить раунд и подождать
#### Дополнительная информация:
@Dennok

**Comment by WallShrabnic** [comment]
Просто в СМЕСАх (Всех, почти) с самого начала нет энергии

**Comment by Raschert0** [comment]
DA LADNA? REALLY?

**Comment by Dennok** [comment]
там 1% энергии
столько сколько в 5 h батареях

**Comment by Uvash** [comment]
Есть же волшебный смес или же блюспейс маяк. На крайний случай, можно соляры прилепить или от станции питание сделать.

**Comment by Poldan** [comment]
Волшебный смес не нужен, ибо читерство.
Лучше поставьте ему туда полноценный пак солнечных батарей.

**Comment by Dennok** [comment]
Таки тоже так щитаю. ато умельци(в частности я) Будут запитывать станцию от магик смеса.
А соляры это хорошая идея
