### ISSUE TITLE
Берет с кривым спрайтом.

### ISSUE THREAD

**Issue by HistoriaDouble** [TauCetiStation/TauCetiClassic#5291]
#### Подробное описание проблемы
Берет без текстуры, нашел в куче мусора. На персонаже никак не отображается. Вместо спрайта бело-фиолетовые квадраты.
#### Дополнительная информация:
Прикреплю скриншот.
![Screenshot_5](https://user-images.githubusercontent.com/53089550/81965016-8015ec00-9628-11ea-9bfb-0e8703d07cd3.png)

**Comment by LudwigVonChesterfield** [comment]
в кучах мусора вообще много багованных предметов найти можно
