### ISSUE TITLE
Сброс нулевого закона в процессе смены

### ISSUE THREAD

**Issue by Lusius13** [TauCetiStation/TauCetiClassic#5299]
#### Подробное описание проблемы
В начале раунда за борга был активен нулевой закон. После, ближе к концу раунда, нулевой закон был сброшен.
#### Что должно было произойти
Нулевой закон должен был остаться.
#### Что произошло на самом деле
Закон сбросили.
#### Как повторить
А вот не знаю.
#### Дополнительная информация:
Начало раунда
![Screenshot_1](https://user-images.githubusercontent.com/65448765/82118723-cfbbfb00-9781-11ea-8220-19bf09401e1a.png)
Конец раунда
![Screenshot_2](https://user-images.githubusercontent.com/65448765/82118729-d5194580-9781-11ea-9462-122150f990e6.png)

**Comment by Lusius13** [comment]
Как вариант, сброс был вызван перелётом на шатле ученых, ибо там у боргов происходит отключение при старте/прилете.

**Comment by 4310V343k** [comment]
#5644
