### ISSUE TITLE
При нарезании некоторых продуктов стало спаунится на один кусок меньше

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#5303]
#### Подробное описание проблемы
После какого-то ПРа при нарезании продуктов (например, теста) спаунится на один кусок меньше, чем было.

#### Что должно было произойти
Как указано в slices_num у теста при разрезании должно спауниться три кусочка теста, так и было всегда.

#### Что произошло на самом деле
Спаунится два кусочка теста.

#### Как повторить
Взять плоское тесто, разрезать.

**Comment by BiQndy** [comment]
А что закрыл то? Я уже полез смотреть в чём дело

**Comment by BiQndy** [comment]
Заметил, что у "неаккуратных" ножей типа есворда кол.во кусков в норме и соответствует коду, в отличие от обычного ножа. Если кто сможет понять в чём дело, то будет хорошо, а то я не догоняю.
