### ISSUE TITLE
[Proposal] Обязать ИИ соблюдать стандартные процедуры

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#5310]
На данный момент ИИ глубоко насрать на SOP, он просто должен выполнять приказы ограничиваясь лишь своими законами. Тем не менее среди некоторых игроков на ИИ сложилось мнение что ИИ не всё равно на процедуры и он их должен придерживаться всегда.

В качестве эксперимента предлагаю добавить закон который обязует ИИ соблюдать процедуры.

**Comment by Akellazp** [comment]
ии не нужен соп. у него законы

**Comment by da-kiselev** [comment]
Мэх, не думаю, что ИИ нужен какой-то там СОП, придуманный для %вставить_раса_нейм%, умные инженеры компании НТ явно со всей ответственностью подходили к написанию законов. Да и, у ИИ всегда будут в приоритете законы, а не чтиво для быдло

**Comment by Shudyn** [comment]
Скажи ИИшке за главу/ассистуху исполнять СОП, и он будет его исполнять за счет закона СЛУЖИТЬ.
И никакой ПР не нужен.
