### ISSUE TITLE
[map issue] Добавление нормальных консолей камер на станцию

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5324]
#### Подробное описание проблемы
Есть два типа секьюрити консолей, обычная, заставляющая космонавтиков перезаходить, и адвансед, имеющая механ глаза ИИ, Я считаю, что стоит поставить именно адвансед консоли, а стандартные выпилить из-за их бесполезности и краша клиента при попытке использовать
#### Что должно было произойти
![image](https://user-images.githubusercontent.com/45365635/82318738-a3e28480-99d0-11ea-8b78-72f182e01c79.png)
![image](https://user-images.githubusercontent.com/45365635/82318848-d3918c80-99d0-11ea-9148-1e070d6c9ce4.png)

#### Что произошло на самом деле
"Дримсикер не отвечает"

![image](https://user-images.githubusercontent.com/45365635/82318893-e73cf300-99d0-11ea-809b-ebd3954fffc5.png)

![image](https://user-images.githubusercontent.com/45365635/82318911-f15ef180-99d0-11ea-8b26-013735b2a280.png)

#### Дополнительная информация

![image](https://user-images.githubusercontent.com/45365635/82319109-4e5aa780-99d1-11ea-926e-78d26b474780.png)

**Comment by cool20141** [comment]
Блин, так сам замени, не ленись

**Comment by KIBORG04** [comment]
Это не так просто. Там механ кривой и поломаный, видно какие-то вещи сквозь помехи, можно увидеть спутник ИИ

**Comment by TheLustOfBlood** [comment]
Будет лучше чем вылеты.
