### ISSUE TITLE
[Proposal] Изменить цели на побег триторов при определенных режимах

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5325]
Сейчас у триторов может быть 3 цели на "побег": остаться в живых, побег на шатле/капсуле, угон шатла. Но в таких режимах как блоб, воксы, нюка, малф раунд часто заканчивается до прилета шаттла, то есть все триторы, у которых цель не "выжить", автоматически проигрывают. Можно сделать так, чтобы в режимах, при которых раунд может закончится раньше прилета шатла, всегда была цель "выжить", а не "сбежать" или "угнать шатл".

**Comment by KIBORG04** [comment]
Зачем? Откуда там главные синдикаты знали, что их агент не сможет улететь?

**Comment by Sakuya-Izayoi** [comment]
убейте блоба, воксов, нюку или малфа если вам дорог ваш гринтекст

**Comment by PirogSema** [comment]
> 
> 
> убейте блоба

Но если его убить, то раунд закончится, а сбежать во время блоба не дадут
