### ISSUE TITLE
В интерфейсе борга не отображается вид намерения.

### ISSUE THREAD

**Issue by Drakon341** [TauCetiStation/TauCetiClassic#5329]
#### Подробное описание проблемы
В интерфейсе киборга неккоректно отображается вид намерения{хелп или харм}

#### Что должно было произойти
В интерфейсе киборга должен отображатся вид намерения.

#### Что произошло на самом деле
В интерфейсе киборга на месте вида намерения отображается микросхема.
#### Дополнительная информация:
![Безымянный](https://user-images.githubusercontent.com/64197080/82374235-6f4de780-9a27-11ea-8b39-af9e39a3a94d.png)

**Comment by LudwigVonChesterfield** [comment]
#5316

**Comment by LudwigVonChesterfield** [comment]
f07eb1f
