### ISSUE TITLE
Дефибрилятор врет.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5334]
#### Подробное описание проблемы
Если куклу стукнуть дефибом не делая CRP и не вводя сердце в фибриляцию, дефиб весело задорно скажет что  все норм, дефибрилейшн суцефул
#### Что должно было произойти
Defibrilation useless: heart status: stopped
#### Что произошло на самом деле
Дефибрейшн суцефул

Тело не реанимируется
#### Как повторить
Найдите труп и начните его реанимировать дефибами по старинке, удивитесь, почему дефибр говорит что все норм, но тело не воскрешается.

**Comment by Sakuya-Izayoi** [comment]
Откуда вообще дефибриллятору знать что там с пациентом, его задача током ударить и всё.
