### ISSUE TITLE
Халки-слабаки

### ISSUE THREAD

**Issue by cool20141** [TauCetiStation/TauCetiClassic#5336]
#### Подробное описание проблемы
Обычно халки не получают урона даже от всяких гаечных ключей (5 брута). Порог, после которого оружие им наносит урон – 10, но от ударов хумана, которые явно 10 урона не наносят, они урон получают 
#### Что должно было произойти
Урон от кулака не наносит урон халку
#### Что произошло на самом деле
Халк помер, когда его забил ассистуха голыми руками
#### Как повторить
Бить голыми руками халка

**Comment by LudwigVonChesterfield** [comment]
#5316

Вероятно тут потерялся механ порога урона от ударов по халку.
