### ISSUE TITLE
Баг даблесворда.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5341]
#### Подробное описание проблемы
#4458

Если крутануть даблесворд стоя у шлюза, то начнется процесс разваривания двери. В этот момент можно невозбранно и без КД крутится аки ураган.
#### Что должно было произойти
Нельзя, да и шлюз наверное развариваться не должон
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/45365635/82496949-cae2a880-9aed-11ea-9523-e3ba160519b9.png)
Один оверлей меча даже догоняет другой оверлей меча и бьет его

![image](https://user-images.githubusercontent.com/45365635/82496987-dc2bb500-9aed-11ea-845c-ba9d91e3d99c.png)

Дюп спина (четыре верчения одновременно вроде)

Это еще без мультитаскинга, боюсь представить что будет если с мультитаском разваривать оба шлюза одновременно...
#### Как повторить
Встаньте с даблесвордом возле шлюза. Крутанитесь. 
#### Дополнительная информация:
Еще тот самый оверлей есворда в шлюзе является незавершенной анимацией, поэтому как только кукла отойдет, верчение продолжится как бы "высвобождая" анимацию из шлюза

**Comment by LudwigVonChesterfield** [comment]
#4458 84bb2c0
