### ISSUE TITLE
Перемещение мобов через створки из-за комбухи

### ISSUE THREAD

**Issue by cool20141** [TauCetiStation/TauCetiClassic#5342]
#### Подробное описание проблемы
Перемещение мобов через створки.
#### Что должно было произойти
Моб врезается в створку
#### Что произошло на самом деле
Моб телепортируется сквозь створку, попадая в отдел
#### Как повторить
Если сделать тут комбуху
![image](https://user-images.githubusercontent.com/53309265/82554840-56504e00-9b6f-11ea-98cf-a3fa8956f2df.png)
То моб залетит сюда
![image](https://user-images.githubusercontent.com/53309265/82554861-60724c80-9b6f-11ea-8670-3ef8c6c49feb.png)
Может и в других местах так можно со створками–не проверял

**Comment by totallynotdedawa2** [comment]
все логично, потолка не существует и человека перебрасывает комбухой через створку
