### ISSUE TITLE
Сердце остановлено, но пульс есть

### ISSUE THREAD

**Issue by cool20141** [TauCetiStation/TauCetiClassic#5346]
#### Подробное описание проблемы
Если у куклы остановилось сердце, то пульс все равно почему-то будет
#### Что должно было произойти
Сердце остановилось=>пульс 0
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/53309265/82588820-f627cf00-9ba3-11ea-8b98-009587087573.png)
#### Как повторить
Остановить сердце
#### Дополнительная информация:
Я не доктор, но вроде так не должно быть

**Comment by T6751** [comment]
@LudwigVonChesterfield, пожалуй этот иссуй тоже нужно закрыть
