### ISSUE TITLE
Интелкарта и самовайпающийся ИИ

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#535]
#### Подробное описание проблемы

ИИ может вайпнуться с Интелкарты
#### Что должно было произойти

ИИ не может вайпнуться с Интел карты
#### Что произошло на самом деле

ИИ вайпнулся
#### Как повторить

Будучи на интелкарте ИИ нажать wipe core

**Comment by Dennok** [comment]
Ну. это как самоубийство/выход гостом для обычного чела. Думаю оно должно быть но если оно конешно ничего не ломает.

**Comment by Damirrus1** [comment]
Не баг, закрывай.

**Comment by Olt1771** [comment]
Аллоу, в Ядре он якобы отгружается в хранилище, а с интел карты куда? По вайфаю?

**Comment by dearprincesscelestia** [comment]
Возможно, баг-дисбаланс. Тритор скачивает ИИ на карту, ИИ вайпается, тритор плачет.
