### ISSUE TITLE
Швабра не моет

### ISSUE THREAD

**Issue by AirBlack** [TauCetiStation/TauCetiClassic#5350]
#### Подробное описание проблемы
Когда моешь шваброй через использовать или альт клик, вода появляется только на последнем турфе, на котором была швабра.
#### Что должно было произойти
Моется везде, где пройдет швабра
#### Что произошло на самом деле
Моется только последний турф, на котором была швабра
#### Как повторить
Попытаться помыть шваброй через альт клик или использовать швабру для helicopter move.
#### Дополнительная информация:
Профессия уборщика теперь неиграбельна. Вероятно что-то в этом ПРе #4458 .

**Comment by LudwigVonChesterfield** [comment]
Как же раньше без этой фичи то играли...
