### ISSUE TITLE
Поломанные комбухи за полуслайма

### ISSUE THREAD

**Issue by cool20141** [TauCetiStation/TauCetiClassic#5353]
#### Подробное описание проблемы
Суплекс за полуслайма наносит не brute урон, а clone урон, хотя, казалось бы, кидают человека об пол. Вроде чардж тоже clone наносит, а не brute, хотя тоже по логике должен явно не clone урон наноситься
#### Что должно было произойти
Вместо brute урона наносится clone урон
#### Что произошло на самом деле
Не тот тип урона
#### Как повторить
За расу полуслайма провести комбухи на человеке
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/53309265/82696905-ad8a1780-9c70-11ea-88a1-eb51af4731ec.png)
![image](https://user-images.githubusercontent.com/53309265/82696970-c8f52280-9c70-11ea-9b95-0d1a82428ecd.png)

**Comment by LudwigVonChesterfield** [comment]
Но ведь вы хотели чтобы перчатки волшебным образом наносили болевой урон комбухами. Почему перчатки должны наносить болевой, а слизни брут?

**Comment by cool20141** [comment]
Потому что вот такая вот несправедливость
Клон урон итак дикий, а тут еще допом наносится от комбух

**Comment by LudwigVonChesterfield** [comment]
Проблема в количестве урона, или его типе?

**Comment by cool20141** [comment]
Ну, лично я считаю, что в типе, потому что клон урон же сам по себе не проходит, потому битва с полусмаймом может означать смерть (Хотя они итак дофига урона наносят)

**Comment by LudwigVonChesterfield** [comment]
Но обычные слаймы тоже наносят клоун урон. Почему большие не должны? Жалоба на слаймов в целом?...

**Comment by cool20141** [comment]
Жалоба на то, что всякие суплексы/чарджи наносят клон урон
Обычные слаймы, насколько я знаю, такие приемы выполнять не могут

**Comment by LudwigVonChesterfield** [comment]
(чардж вроде могут)

**Comment by cool20141** [comment]
Он вроде не активируется. Комбуха типа появляется (Значок), но дальше ничего

**Comment by Sakuya-Izayoi** [comment]
так в этих же приёмах урон от ударов об окружение. и клон урон это вообще потому что слайм присасывается, а не бьёт

**Comment by cool20141** [comment]
Если clone урон от прикосновения, то почему он не наносится при help интенте?

**Comment by Sakuya-Izayoi** [comment]
а от чего по твоему клон урон?

**Comment by LudwigVonChesterfield** [comment]
@Sakuya-Izayoi если урон от ударов об окружение, то почему перчатки не должны наносить урон?

**Comment by Sakuya-Izayoi** [comment]
про перчатки я ничего не говорил

**Comment by LudwigVonChesterfield** [comment]
Это я у тебя спрашиваю. Если я сделаю чтобы у слизней урон от комб отличался от урона тычков, то почему перчатки должны отличаться?

**Comment by LudwigVonChesterfield** [comment]
Хотя в принципе комбам типа спин энд троу, чарж возможно имеет смысл поставить форсед Брут урон.

Но к примеру суплекс - даёт контакт с мобом, апперкот - даёт, не знаю стоит ли им менять.

**Comment by cool20141** [comment]
А чардж? Он же типа стукает лбом об предмет

**Comment by Sakuya-Izayoi** [comment]
везде где комбо предполагает урон от окружения должен наносится брут урон. можно разделить кое-где урон в комбах на урон от удара другого игрока и на урон от окружения (кстати мне интересно а комбы как-то логгируются во вскрытии)
