### ISSUE TITLE
Проблемы на корабле пиратов.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#537]
#### Подробное описание проблемы

Хабар пиратов на корабле пиратов перекрывает подоход к консоли корабля.
#### Что должно было произойти

Должен быть свободный подход к консоли.
#### Что произошло на самом деле

Телепортирующийся хабар завалил консоль
#### Как повторить

Использовать фултон.
#### Дополнительная информация:

![scrnshot1](https://cloud.githubusercontent.com/assets/7734424/18251587/8874b000-7392-11e6-92e9-097c08fad5a4.png)

**Comment by Damirrus1** [comment]
Пуллить мы не умеем(((

**Comment by Dennok** [comment]
Там слишком много вещей. Ты тупо не сможеш все упуллить если около консоли например весь склад инженерки, а машины нам не разобрать.
