### ISSUE TITLE
Битье груши отображается в админ логах

### ISSUE THREAD

**Issue by Enerty** [TauCetiStation/TauCetiClassic#5372]
#### Подробное описание проблемы
В админ логах видно избиение груши
#### Что должно было произойти
Избиение груши не должно появляться в админ логах
#### Что произошло на самом деле
В админ логах видно избиение груши
#### Как повторить
Запедалиться
#### Дополнительная информация:
Ничего более

**Comment by 4310V343k** [comment]
Грушу можно использовать что бы сбивать ей с ног, в таком случае не будет видно кто э
то сделал, без реплея

**Comment by LudwigVonChesterfield** [comment]
@4310V343k Это логгируется педалям, если ты про это.
