### ISSUE TITLE
ИИ не может открывать стеклянные двери

### ISSUE THREAD

**Issue by KrisPrs** [TauCetiStation/TauCetiClassic#5387]
#### Подробное описание проблемы
ИИша не может открывать стеклянные дверки
#### Что должно было произойти
Дверки должны открываться по клику
#### Что произошло на самом деле
Красная моргающая лампочка, показывающая отказ доступа
#### Как повторить
Кликнуть, будучи ИИшей, на стеклянную дверь

**Comment by LudwigVonChesterfield** [comment]
#5380

**Comment by Motykoo** [comment]
Когда это уже пофиксят... бесит
