### ISSUE TITLE
Сбои в законах боргомалфов при взломе

### ISSUE THREAD

**Issue by KrisPrs** [TauCetiStation/TauCetiClassic#5388]
#### Подробное описание проблемы
При взломе боргов через консоль РД малфом их законы сбрасываются к базовым НТ
#### Что должно было произойти
Законы не должны были измениться, а спецоборудование должно выдаться
#### Что произошло на самом деле
Законы сбросились, оборудование выдалось
#### Как повторить
Взять малфа, борга, взломать последнего через консоль

**Comment by 4310V343k** [comment]
#5644
