### ISSUE TITLE
Защитные створки РНД имеют общий доступ

### ISSUE THREAD

**Issue by GermanSUS** [TauCetiStation/TauCetiClassic#5389]
#### Подробное описание проблемы
Почему то, если тыкнуть на защитные створки в РНД (Та что на полигоне или при нажатии кнопки в комнате РД) они сработают! Можно их спокойно открывать закрывать, с энергией, хотя единственными способами их открытия должны быть нажатие кнопки РД или сифор.
#### Что должно было произойти
Створки не открываются/закрываются при нажатии на них
#### Что произошло на самом деле
Створки открываются/закрываются если нажать на них
#### Как повторить
Нажать на защитную створку в РНД, возможно где то еще, например бриг и инженерка, но я не уверен
#### Дополнительная информация:
У одного чела случился знатный бугурт от этого, но ишью он не написал, пришлось работать самому.

**Comment by SvSvyat** [comment]
Касается, кажется, любых створок. Можно открыть ту же оружейку лапками без всяких там кнопок и доступов, получается.

**Comment by GermanSUS** [comment]
Да, в бриге такая же проблема, получается створки сломаны везде

**Comment by LudwigVonChesterfield** [comment]
#5380
