### ISSUE TITLE
ИИ и его Вайп кор после смерти

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#540]
#### Подробное описание проблемы

ИИ может вайпнуться будучи мёртвым
#### Что должно было произойти

ИИ не должен смочь вайпнуться
#### Что произошло на самом деле

Он смог вайпнуться
#### Как повторить

Зайти за ИИ умереть, нажать Wipe Core
#### Дополнительная информация:

Было бы неплохо ИИ сделать не моментальную отгрузку вообще, ибо когда его штурмуют он просто вайпается и через 30 минут опять заходит и продолжает мстить ролькам. В последний раз когда я штурмовал ИИ в соло. Я начал в него стрелять, он нажав кнопку прямо пред мною просто вайпнулся, что ни есть хорошо. Далее он просто перезашёл в раунд через 30 минут

**Comment by Raschert0** [comment]
Всё же стоит это ещё раз проверить, но, по-моему, не фиксилось никем.
