### ISSUE TITLE
Невозможность разблокировки и взлома борга емагом

### ISSUE THREAD

**Issue by M4lkuth** [TauCetiStation/TauCetiClassic#5420]
#### Подробное описание проблемы
Пытаясь взломать борга по схеме секвенсер>лом>секвенсер, затея оказывается мертвой ещё в зародыше ибо:
1) Секвенсер не разблокировает борга на первом шаге
2) Секвенсер не взламывает борга, даже если открыть крышку нужной айди
#### Что должно было произойти
ударил борга секвенсером 
@ 
разблокировал панель
@
ломом открыл борга, и ударил секвенсером второй раз
@
борг в моей пати. Ура!
#### Что произошло на самом деле
ударил борга секвенсером
@
панель не разблокировалась
@
Попытки открыть панель борга ломом тщетны
@
даже разблокировав панель с помощью айди роботеха и открыв ее, борг все равно не взламывается, сколько бы раз не бил емагом
@
борг флешит тебя, сообщает о попытке взлома и ты отправляешься в бриг. Game Over.
#### Как повторить
Попытайтесь взломать борга секвенсером без и с айди капитана/робототехника/рд
#### Дополнительная информация:
фейлота...

**Comment by Andreikepka** [comment]
Для начала: Шанс взлома не 100%
Если ты об этом не знал

**Comment by M4lkuth** [comment]
Я про первый шаг, перед открытием ломом

**Comment by Andreikepka** [comment]
Так в оба стороны идёт. Что просто открыть борга - То его и взлом уже после открытия

**Comment by Andreikepka** [comment]
Поэтому если-ты не роботех(Ну или у кого есть доступ к боргам). То шансы взлома борга очень малые.

**Comment by M4lkuth** [comment]
Я на локалке избил борга секвенсером и так не смог открыть панель борга

**Comment by Andreikepka** [comment]
Кхм прям совсем не смог? Сколько раз пытался

**Comment by M4lkuth** [comment]
Несколько раз. Несколько боргов. Могу сейчас ещё раз проверить. Панель так и выдает: The cover is locked and cannot be opened

**Comment by Andreikepka** [comment]
Просто возможно, тебе тупо не везло совсем в локалке.

**Comment by M4lkuth** [comment]
5 раз иболее бью емагом борга, 5 раз он искрится, но панель не разблокировается. Может если ударить пять раз емагом, то борг взломается? для взлома обязательно же открывать панель? Может я чего-то не знаю?

**Comment by Andreikepka** [comment]
Взлом панели - Лом - Уже по открытому боргу. Всё так

**Comment by M4lkuth** [comment]
Тогда всё верно. Емаг не взламывает панель. Из-за чего ломом нельзя открыть и соответственно взломать борга

**Comment by Andreikepka** [comment]
Ну тут уже тогда ждать кодеров. Чтоб посмотрели что не так.

**Comment by 4310V343k** [comment]
Если кому-то будет так удобнее искать проблему:
![1](https://user-images.githubusercontent.com/56449763/83703977-96a4d700-a619-11ea-95d9-5f658a972bba.gif)

**Comment by M4lkuth** [comment]
выяснилось, что борга нельзя взломать даже, открыв крышку, дополнил описание
