### ISSUE TITLE
Роботы не могут нажимать кнопки в экзосьют фабрикаторе

### ISSUE THREAD

**Issue by Raschert0** [TauCetiStation/TauCetiClassic#543]
#### Подробное описание проблемы

Роботы не могут нажимать кнопки в экзосьют фабрикаторе
#### Что должно было произойти

Кнопки в экзосьют фабрикаторе должны нажиматься, если юзер - робот.
#### Что произошло на самом деле

Кнопки не нажимались
#### Как повторить

Стать роботом. Попытаться взаимодействовать с меню экзосьют фабрикатора.

**Comment by RichardJones1** [comment]
Я не уверен, что это необходимо роботу, ведь он, по сути, лишь помощник. Но знаю, что баг ещё есть, поэтому оставлю. Боргопроблемы.

**Comment by KuzyXD** [comment]
По прежнему не работает.
