### ISSUE TITLE
Комбы работают на коровке

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#5430]
#### Подробное описание проблемы
У коровы Бетси определено особое поведение для дизарма, но на ней можно применять комбы.

#### Что должно было произойти
Корову можно было бы толкать без набора комбоочков

#### Что произошло на самом деле
Коровка толкается и набираются комбо-очки

#### Как повторить
Нажать пуш на коровку

#### Дополнительная информация:
Как вариант можно выпилить это особое поведение.

**Comment by LudwigVonChesterfield** [comment]
А в чем баг? У неё это поведение было всегда, и точно так же оверрайдило дефолтное...
