### ISSUE TITLE
Перестали работать Lazarus Injector

### ISSUE THREAD

**Issue by BakerMontague** [TauCetiStation/TauCetiClassic#5444]
#### Подробное описание проблемы
С обновлением живности шахт на мобах(Голиаф, хайвлорд и т.д.) перестали работать Lazarus Injector'ы.
#### Что должно было произойти
При использовании на Мобе он должен был воскреснуть.
#### Что произошло на самом деле
Лишь удары Lazarus Injector'ом по телу моба. Он не восстает. 
#### Как повторить
Создать Lazarus Injector любого качества на фабрикаторе шахтеров и тыкнуть им по трупу моба.
#### Дополнительная информация:

**Comment by KIBORG04** [comment]
Вроде, схоже с емагиванием боргов. Мб, аттакбай/аттак где-то кривой
