### ISSUE TITLE
Баг со стазисом генокрадов

### ISSUE THREAD

**Issue by AAAAAAAASH** [TauCetiStation/TauCetiClassic#5453]
#### Подробное описание проблемы
У генокрадов сломался стазис
#### Что должно было произойти
Полное излечение
#### Что произошло на самом деле
Генка умирает за 10 секунд
#### Как повторить
Отрегенится за генку

**Comment by cool20141** [comment]
Наверное, опять проблемы с остановкой сердца

**Comment by Drakon341** [comment]
Да,помню за генку коснулся шлюза под высоким напряжением,сразу в крит и сдох.Причём с концами,стазис не работал,даже не появилась кнопка Regenarate.

**Comment by cool20141** [comment]
Это отдельный баг уже
