### ISSUE TITLE
При использовании даблесворда, он не только закрывается, но пытается провести spin атаку

### ISSUE THREAD

**Issue by cool20141** [TauCetiStation/TauCetiClassic#5455]
#### Подробное описание проблемы
При попытке закрыть даблесворд, начинается спин атака, но прерывается закрытием. И это не очень удобно, потому что хочешь закрыть–бьешь людей. Такой проблемы с одноручным мечом, кстати, нет–он спокойно закрывается
#### Что должно было произойти
Меч закрылся и никто не пострадал
#### Что произошло на самом деле
Началась круговая атака, по кому-то попало, но атака не продолжилась–меч закрылся
#### Как повторить
Деактивировать двуручный лазерный меч
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/53309265/83846881-f97a9900-a713-11ea-82db-43d6809733d6.png)

**Comment by cool20141** [comment]
Это, кстати, наносит урон закрытого меча, хоть по анимации он открыт

**Comment by Motykoo** [comment]
Можно легко своих же тимейтов при нюке порезать.

**Comment by LudwigVonChesterfield** [comment]
@cool20141 Это происходит при любой попытке "схлопнуть" меч, или только если на мидл-клик мышкой?

**Comment by cool20141** [comment]
Нет, на мидл-клик как раз все работает так, как и было задумано–меч крутится. А это срабатывает при попытке активировать меч (На Z или при нажатии на его иконку в руках)

**Comment by cool20141** [comment]
> Можно легко своих же тимейтов при нюке порезать.
Можно, только там 3 брута всего наносит таким способом

**Comment by cool20141** [comment]
> Можно легко своих же тимейтов при нюке порезать.

Можно, но там 3 брута наносится всего
