### ISSUE TITLE
Каталки разбираются на металл, вместо того, чтобы складываться

### ISSUE THREAD

**Issue by M4lkuth** [TauCetiStation/TauCetiClassic#5457]
#### Подробное описание проблемы
Любой ассистент может взять гаечный ключ и разобрать все каталки на металл, из-за чего в медбее не останется каталок. Крафт новых каталок невозможен, либо я чего-то не знаю. У каталок есть состояние "свернутый". Именно в это состояние должны переходить каталки, а не разбираться на металл.
![20200605 184536](https://user-images.githubusercontent.com/47116700/83896828-6d8d5f00-a75d-11ea-8256-2c44d77788c3.png)
#### Что должно было произойти
![20200605 184636](https://user-images.githubusercontent.com/47116700/83896842-71b97c80-a75d-11ea-8b14-ce7efd1c1d7c.png)
#### Что произошло на самом деле
![20200605 184540](https://user-images.githubusercontent.com/47116700/83896850-74b46d00-a75d-11ea-91cd-30a19e7df67e.png)
#### Как повторить
Использовать на каталке гаечный ключ
#### Дополнительная информация:
ууф

**Comment by LudwigVonChesterfield** [comment]
Каталки складываются если их перетащить на себя, это не баг.

**Comment by M4lkuth** [comment]
тогда как скрафтить каталку? если все они будут разобраны?

**Comment by LudwigVonChesterfield** [comment]
Это отдельное предложение - если хочешь, оставь его. Но "каталки разбираются на металл" - это не баг.

**Comment by M4lkuth** [comment]
Может запретить разбор каталок гаечным ключом? их же нельзя потом собрать или заказать в карго

**Comment by LudwigVonChesterfield** [comment]
Может дать возможность их собрать или заказать в карго? Я же сказал, это отдельный ишуй.

**Comment by M4lkuth** [comment]
хорошо, напишу предложение
