### ISSUE TITLE
[Proposal] Добавить возможность заказа каталок в карго

### ISSUE THREAD

**Issue by M4lkuth** [TauCetiStation/TauCetiClassic#5458]
#### Подробное описание проблемы
Каталки можно разбирать на металл, но нельзя собирать или заказывать новые.
#### Что должно было произойти
Если какой-нибудь ассистент разберет все каталки на металл, медбей может заказать новые в Карго
#### Что произошло на самом деле
Если какой-нибудь ассистент разберет все каталки на металл, медбей не сможет заказать/собрать новые и медбей будет без каталок совсем
#### Что это улучшит:
Позволит избежать ситуаций, когда кто-то разберет все каталки и медбею придется доставлять пациентов без каталок.

**Comment by 4310V343k** [comment]
Используй мешки для трупов 👍

**Comment by StrikS** [comment]
Нералиплейна таскать живых в мешках для трупов. Но адекватную альтернативу никто так и не придумал. 
Разве что сделать, чтобы каталки в рюкзак чтоб помещались обычный. Звучит как апгрейд в рнд или тупо автолате. Делать абсолютно все такие жаба душит. Абуз: разложил каталку, поменялся местами, положил на каталку, оружие выпало - слишком затратный, проще мылом.
И не забывать пиздить парамедиков, которые их будут печатать в карго.
