### ISSUE TITLE
Блюспейс хранилище повара

### ISSUE THREAD

**Issue by M4lkuth** [TauCetiStation/TauCetiClassic#5461]
#### Подробное описание проблемы
Хлеб может хранить в себе НЕОГРАНИЧЕННОЕ количество мелких предметов. В него можно сложить ВСЕ вещи со станции по типу инструментов из тулбоксов, плат из аплоада и хранилища плат и тд. В связке с имплантом сжатия получается идеальный тайник... Кроме того хлеб можно вкладывать в хлеб!
![20200605 214706](https://user-images.githubusercontent.com/47116700/83913249-e8fc0a00-a777-11ea-99db-5572970e99b0.png)
#### Что должно было произойти
@ 
кладу несколько предметов разного размера в хлеб и место заканчивается
#### Что произошло на самом деле
@ 
кладу все инструменты из ассистентской в хлеб
@
кладу все платы, что могу найти со станции
@
кладу все, что может влезть в хлеб и выкидываю в космос... Идельный гриф?
#### Как повторить
Сделайте хлеб за повара или закажите хлеб у него и начинайте складывать все вещи, которые могут в него влезть, что попадутся на глаза
#### Дополнительная информация:
(Проверял на локалке)
Взгляните на это и скажите, что вы видите? Просто хлеб? Не думаю...

**Comment by M4lkuth** [comment]
хлеб можно вкладывать в хлеб, обновил описание

**Comment by Shudyn** [comment]
Тебя в подворотне побьют фичеабузеры. Удаляй пока не поздно.

**Comment by M4lkuth** [comment]
То есть ты просто добавляешь молоко, яйцо, муку и получаешь свое домашнее блюспейс хранилище, которое можно вложить в другой хлеб, создавая матрешку. Блюспейс технология у повара на кухне, а ученые и не подозревают, ууф

**Comment by M4lkuth** [comment]
И ето не фича, ето баг, иначе бы людук закрыл иссуй, ууф
