### ISSUE TITLE
[Proposal] Как же хочется tgui

### ISSUE THREAD

**Issue by cool20141** [TauCetiStation/TauCetiClassic#5485]
Хочется красивый интерфейс. Сейчас же у нас местами довольно красивый интерфейс на первый взгляд, но на второй он кажется ужасным, и просто ужасный. На ТГ решили избавиться от этих пережитков прошлого и перешли на красивейший tgui (Скрин ниже)
![image](https://user-images.githubusercontent.com/53309265/83969536-3f348e80-a8d9-11ea-9012-2acf25a633da.png)
Хочется и нам такой. Можете посмотреть больше примеров этого tgui на билде тг.
Вот, например, днк консоль:
![image](https://user-images.githubusercontent.com/53309265/83969738-45773a80-a8da-11ea-9444-a77879f819c6.png)

**Comment by KIBORG04** [comment]
А у нас такого нет что ли? Тут лежат некоторые примеры его использования. Там используется в по большей части обычный хтмл и ксс, но еще и есть всякие простые штуки для динамического управления всем этим хтмлом. 
https://github.com/TauCetiStation/TauCetiClassic/tree/master/nano/templates

**Comment by cool20141** [comment]
Ну, это почти наноуи, как я понимаю, но намного более красивый

**Comment by KIBORG04** [comment]
Это тот же самый наноуи, все зависит от ксса и навыка дизейнерства

**Comment by cool20141** [comment]
Ну я хз, в этом не разбираюсь. Если такое можно сделать и с наноуи, то хорошо. Претензия больше в том, что у нас некрасивый интерфейс

**Comment by Sakuya-Izayoi** [comment]
Я так понял он хочет гуи на реакте

**Comment by KIBORG04** [comment]
> Я так понял он хочет гуи на реакте

А, я был не прав, тгуи намного мощней наноуи

**Comment by KIBORG04** [comment]
Тгуификация давно начата
