### ISSUE TITLE
СПУ перегреваются в мехе на тайле космоса.

### ISSUE THREAD

**Issue by Shudyn** [TauCetiStation/TauCetiClassic#5487]
#### Подробное описание проблемы
 СПУ перегреваются внутри меха с подачей атмосферы из меха. При этом не просто так, а только на тайлах космоса. На станции все работает как надо.

#### Что должно было произойти
 СПУ не перегреваются от внутренней атмосферы в мехе в космосе.
#### Что произошло на самом деле
СПУ перегреваются от внутренней атмосферы в мехе в космосе.
#### Как повторить
Залезть в мех, включить подачу атмосферы из внутренних балонов меха, зайти на тайл космоса, перегреться.

**Comment by LudwigVonChesterfield** [comment]
#1488
