### ISSUE TITLE
syringe attackby

### ISSUE THREAD

**Issue by 4310V343k** [TauCetiStation/TauCetiClassic#5492]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/56449763/83976440-897e3580-a902-11ea-86d9-d1b9f3d0949e.png)
![image](https://user-images.githubusercontent.com/56449763/83976537-2b9e1d80-a903-11ea-97ca-b8869250ec80.png)

**Comment by LudwigVonChesterfield** [comment]
#5486
