### ISSUE TITLE
Под куклой появляется анимация разливание воды

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#5493]
#### Подробное описание проблемы
После того как используешь Water flower, через какие-то промежутки времени происходит анимация, будто под куклой разливается вода.
#### Что должно было произойти
Ничего
#### Что произошло на самом деле
Иногда под куклой появляется анимация разливания воды
#### Как повторить
1. Взять в руки Water flower
2. Брызнуть на себя.
3. Ждать
#### Дополнительная информация:
-

**Comment by LudwigVonChesterfield** [comment]
Это называется промокшие вещи.
