### ISSUE TITLE
Шприцы бьют ёмкости

### ISSUE THREAD

**Issue by PirogSema** [TauCetiStation/TauCetiClassic#5495]
#### Подробное описание проблемы
Шприцы и тому подобные (имплантер) бьют то, куда вводят, но, к счастью, вводу вещества это не мешает. Также из-за этого ввод вещества происходит медленнее чем возможно было. То же самое происходит если запихнуть что-то в халат/жилет через тык на сам жилет/халат
#### Что должно было произойти
Ввёл вещество в банку, без каких-либо красных надписей
#### Что произошло на самом деле
![изображение](https://user-images.githubusercontent.com/22032604/83982978-6cae2600-a933-11ea-881f-179bf7d6f23b.png)

![изображение](https://user-images.githubusercontent.com/22032604/83983013-a2eba580-a933-11ea-9858-6fa4e54b9444.png)
#### Как повторить
Ввести что-то в пробирку, положить что-то в халат.
#### Дополнительная информация:

**Comment by Sakuya-Izayoi** [comment]
Последнее время все действия связанные с кликами теперь почему-то бьют предметы. Возможно последствия неудачного рефакторинга который мало того что не протестили локально, так ещё и пустили в билд без тестмержа.

По теме — таблетки бьют банки если пытаться их в них положить.

**Comment by PirogSema** [comment]
Эта странность всё ещё имеет место быть. Оно замедляет скорость ввода и вывода вещества. Если проводить действия на руках (вводить в бикер шприцом вещество, имея оба предмета в руках), то это тоже будет происходить.

**Comment by cool20141** [comment]
> @Sakuya-Izayoi нет. это по задумке так, ПР - #5462. Я считаю что наличие хоть какого-то фидбека о действии лучше чем ничего. Особенно учитывая то как часто у нас "действия" все равно выглядят как ничего.
> 
> Насчёт ишуя - #5486

Не этого ПРа, а #5441
