### ISSUE TITLE
[Proposal] вернуть выпиленную воут-систему

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#5500]
Раньше у нас была (афаик выпилена потому что сломана) система опросов с помощью которой администрация могла опрашивать игроков сервера по различным вопросам.

Я предлагаю вернуть данную систему для проведения голосований, статистических опросов и референдумов прямо на сервере. Эта система будет иметь преимущество над форумом так как не все игроки нашего сервера им пользуются или вообще знают о нём. Ведь если не учитывать мнение этих игроков полученые результаты будут подвержены довольно серьёзной и значительной погрешности.

**Comment by Ambassadoing** [comment]
>Эта система будет иметь преимущество над форумом так как не все игроки нашего сервера им пользуются
Если игрока нет на форуме, то я крайне сомневаюсь, что его в принципе интересуют дела сообщества.
