### ISSUE TITLE
Minor bug

### ISSUE THREAD

**Issue by Kyvikoi** [TauCetiStation/TauCetiClassic#5507]
#### Подробное описание проблемы
Ударив насосом по насосу, один пропадет.
#### Что должно было произойти
Один не должен был уничтожиться.
#### Что произошло на самом деле
Тот насос, который был в руке, пропал.
#### Как повторить
Взять в руку high power pump и ударить по такому же.

**Comment by KIBORG04** [comment]
Любой трубы по любой трубе, так как все они одного класса `/obj/item/pipe`

**Comment by T6751** [comment]
я вам больше скажу, они пропадают если ударить ими обо что-угодно. #5196

**Comment by KIBORG04** [comment]
Я еще больше скажу, они не удаляются, а дропаются в `contents` предмета.
Полагаю, проблема тут https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/game/machinery/pipe/construction.dm#L295
