### ISSUE TITLE
[sfield] сломался

### ISSUE THREAD

**Issue by atik1n** [TauCetiStation/TauCetiClassic#5509]
#### Подробное описание проблемы
[sfield] перестал работать как филд и на него нельзя кликнуть
#### Что должно было произойти
Появилось поле [sign] для подписи
#### Что произошло на самом деле
Не появилось
#### Как повторить
Написать на бумаге [sfield]

**Comment by T6751** [comment]
Точно сломался? вроде бы всё работает

**Comment by atik1n** [comment]
На первом просто нет кнопки [sign], что странно

**Comment by atik1n** [comment]
Новая информация. Они ломаются от принтера

**Comment by Sakuya-Izayoi** [comment]
Так это ты его вводил же
