### ISSUE TITLE
[Proposal] Ремап окон

### ISSUE THREAD

**Issue by atik1n** [TauCetiStation/TauCetiClassic#5514]
#### Подробное описание проблемы
У нас в баре, да и не только окна сделаны из четырех кусочков, в то же время на мостике и не только есть четырехсторонные окна. Может заменить?
![image](https://user-images.githubusercontent.com/14612180/84176827-ad6c8300-aa8a-11ea-907e-5f898d9f8c36.png)

**Comment by Akellazp** [comment]
Эти стекла можно сломать, поэтому на мостике и других защищенным местах полные укреп стекла, которые мало что может сломать. 
Замена не нужна

**Comment by Motzord** [comment]
Так и надо, закрывайте
