### ISSUE TITLE
Defibrillation successful при неудачной (труп остался трупом) реанимации.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#5517]
#### Подробное описание проблемы
Defibrillation successful есть, оживления нет. CPR - дефибы - Defibrillation successful - результата нет и оживления нет и эффекта шока нет.
#### Что должно было произойти
Либо надпись о неудаче при таком же результате, либо наоборот?
#### Что произошло на самом деле
см. выше
#### Как повторить
![image](https://user-images.githubusercontent.com/29904082/84188972-21b02200-aa9d-11ea-9dd2-24782b23062b.png)
![image](https://user-images.githubusercontent.com/29904082/84189594-29bc9180-aa9e-11ea-9781-44cfb80e2377.png)

#### Дополнительная информация:
https://github.com/TauCetiStation/TauCetiClassic/pull/5505
https://github.com/TauCetiStation/TauCetiClassic/pull/4672

> После таймера есть два варианта событий:
> 1.Ставят дефибриллятор и реанимируют челика
> 2.Каждые 1.2 секунды +-0.2 секунды кликают хелпом по груди и набирают 12 очков, после чего челик воскрешает. Есть 5% шанс сломать грудную клетку. Если довести очки до -2, сердце остановится и ему нанесется урон.

Не сработало ни то, ни то, ни вместе, ни отдельно. А ещё благодаря замечательным подлагиваниям и фризам сердца окошко в секунду кажется абсолютно ублюдочным и далеко не всегда возможным для отбивания ритма. Мне кажется, что если это дело и усложнять, то оно должно работать (хоть как-нибудь), а оно не работает.
Только вся соль в *проведённой* CPR. И это не один раз повторялось, а у двух трупов. Возможно, конечно, я что-то не так делаю...

**Comment by LudwigVonChesterfield** [comment]
Возможно билд не обновился к тому моменту когда ты играл.

**Comment by Motzord** [comment]
Как я помню ебать дефибами надо несколько раз ибо там шанс, а сама успешная дефибриляция сбрасывает таймер у трупа

**Comment by Motzord** [comment]
Это не баг а фича, ишью можно закрывать.

После фибриляции сердца надо бить дефибами несколько раз, и если сердце зафибрилированно, то удар дефибами будет успешен. Повторяй пока не реанимируется
