### ISSUE TITLE
Не все столбцы изменения ДНК генетики работают

### ISSUE THREAD

**Issue by cremp-bush** [TauCetiStation/TauCetiClassic#5520]
Решение:
В code\game\dna\dna_modifiler.dm
Поменять в строчке значение с 13 до 16 (16 - кол-во столбцов):
if ((select_block <= 13) && (select_block >= 1))

**Comment by cool20141** [comment]
А у них вообще есть функционал? Да и если ты знаешь как починить, то почему бы не починить, зачем писать ишью?

**Comment by Motzord** [comment]
Некоторый пустые столбцы видимо добавлены специально чтобы у генетиков была работка и мозгоебательство. Не уверен, что это баг, так и задумано

**Comment by cool20141** [comment]
Они не тыкаются вообще. Да и не влияют, видимо, ни на что. Их бы либо выпилить, либо к чему-то привязать

**Comment by cremp-bush** [comment]
Объясняю, в коде было прописано чтобы работали ТОЛЬКО 13 БЛОКОВ, несмотря на то, что их всего 16. Если поменять с в коде с 13 блоков на 16, то они ВСЕ будут работать. И, да, они РАБОЧИЕ.

**Comment by cool20141** [comment]
Ого, чел, если ты такой умный–закодь. А еще, если не затруднит, то скажи, за что отвечают данные блоки

**Comment by cool20141** [comment]
Хотя, вроде, они отвечают за че-то там с волосами

**Comment by cremp-bush** [comment]
Надо либо удалить блоки, либо пусть будут рабочими

**Comment by cool20141** [comment]
Ну так удали либо сделай (Лучше второе), ты же знаешь как

**Comment by cremp-bush** [comment]
Я пишу разработчикам, чтобы они в билде починили, а не только у меня починенное было

**Comment by cool20141** [comment]
Почини->сделай ПР->будет в билде
