### ISSUE TITLE
Щитом теперь нельзя отталкивать

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5540]
#### Подробное описание проблемы
Раньше можно было отталкивать людей щитом, но теперь можно им только бить
#### Что должно было произойти
Можно толкать людей щитом
#### Что произошло на самом деле
Нельзя толкать людей щитом
#### Как повторить
Попытаться толкнуть человека щитом

**Comment by LudwigVonChesterfield** [comment]
Ктрл-клик щитом
