### ISSUE TITLE
[Proposal] Система модульных модификаций специализации для СПУ

### ISSUE THREAD

**Issue by Shudyn** [TauCetiStation/TauCetiClassic#5549]
(Замаскированная система скиллов и знаний)
<details> 
  <summary>Примерный лор, кому интересно.</summary>
  Объединенными усилиями Позитронного Союза и сторонников либерализации синтетиков были достигнуты невероятные результаты - были разработаны чрезвычайно дешевые и простые для массового производства шасси для позитронных установок, снизив затраты на производство чуть ли не в 9 раз. Но ради получения широкой доступности выкупа и такого удешевления шасси, пришлось пожертвовать качеством деталей и материалов, что привело к падению производительности шасси и их функциональных особенностей. 
Разработанная позднее программа DEVKit позволила позитронкам модифицировать собственные корпуса с помощью приобретаемых ПО и наборов самомодификации. 

Удивительно, что после выкупа подавляющая часть позитронок производила такие модификации, чтобы достичь максимальной эффективности в тех областях, в которых они работали при "оковах", становясь непревзойденными мастерами своего дела, не желая изучать что-либо другое. 

Благодаря расширению канала "свободы", появилось невероятное количество наемных позитронных шасси, готовых заниматься своей специальностью дешевле и усерднее, чем специалисты-люди, но не требующих отпусков и большей части выходных, из-за чего корпорации, в том числе и Нанотразен, желающие как можно больше сэкономить на рабочей силе, стали приоритизировать СПУ в наеме на работу. 

Подобное решение не прошло без возмущений: некоторые люди остались без работы, или были вынуждены согласиться на меньшую зарплату, чтобы их не сократили в пользу не привередливых синтетиков.

</details>
Прочитайте до конца перед комментированием.

Для начала отвечу зачем оно вообще надо. Сейчас сэпуха, как и другие ксеносы, являются респрайтом хумана с мелкими изменениями. А так станет лорно и интересно, больше людей пойдут создавать себе телевизора, машины захватят станцию 😏 
Второй ответ: обкатка подобия системы скиллов в контролируемых условиях.

Что это значит: 
Базовая версия шасси телевизора обладает различными эффектами (в основном дебаффами), контролируемые профессией при заходе в игру и наличием модулей-органов для специальных умений.
1) Скорость бега 0.8 от стандартной
2) Скорость действий (с прогресс баром) 0.5-0.8 от стандартной (может быть, чтобы зависело от вида деятельности, но мне кажется это слишком трудоемко выйдет для внедрения). 
3) Дешевая охлаждающая система (какая сейчас). 
4) При стрельбе имеют шанс взорвать оружие в руках как клоун. 
5) Не имеют порога урона, то есть наносится любое количество. 
6) Порог урона, с которых начинают проявляться дефекты конечностей, ниже (я не в курсе какой сейчас у теликов и органиков). 
7) Не умеют пользоваться инструментами, кроме сварки и проводов для самопочинки - теперь все могут чиниться. 
8) Способность "Овердрайв", возвращающая все оригинальные (нынешние) возможности, убирающая дебаффы и запреты, но наносящая урон позитронке/быстро нагревающая корпус, то есть для случаев, когда это важно для выживания. (стандартный модуль "Overdrive")
9) Получают любой урон с множителем 1.
10) Кулаками наносят полтора брута.
11) Список может дополняться

Далее, в зависимости от выбранной профессии, производятся различные модификации от базовой модели, символизирующие глубокую специализацию (кстати убираются запреты на все профессии, кроме капитана)
Перечисляются только отличия от базовой версии шасси.

Все СПУ на гражданских профессиях:
1) Имеют порог урона в 1.
2) Имеют чуть лучшую охлаждающую систему (вместо 5 градусов в секунду нагревает только на 4).
3) Скорость бега - 0.9 от базы
4) Способность "Овердрайв" в два раза меньше урона наносит/меньше нагревает, (оптимизированный модуль "Overdrive").
        СПУ-ХОП и СПУ-КМ к вышесказанному имеют:
        1) Порог урона - 2.
        2) Скорость бега - базовая
        3) СПУ-ХОП умеет пользоваться оружием.

Все СПУ на научных профессиях:
1) Эффективнее тратят очки исследований (скажем, 0.8 от базовой стоимости исследования)
2) Деструктивный анализ дает в 1.2 раза больше очков от базовой стоимости.
^^(новый модуль - дополнительный процессорный юнит. Примерно представляю как можно добавить, например, через проверку того, кто исследует и наличие у него этого органа)
3) Множители получаемого урона - 1.2 или даже 1.5 (получают больше урона).
4) Кулаками наносят единичку брута, underwhelming.
5) Скорость бега - 1.
6) Способность "Deep Quantum Co-processor" - раз в 2 минуты в руке можно сгенерировать дискету на 2000 очков исследований. (модуль Deep Quantum Co-processor)
        СПУ-РД к вышесказанному имеет:
        1) Деструктивный анализ дает в 1.3 раза больше очков
        2) Исследования стоят 0.7 очков от базовой стоимости.
        ^^(новый орган - выделенный позитронный мини-процессор)
        3) Множители получаемого урона - 1.1 (или 1.3)
        3) Вместо способности "Deep Quantum Co-processor" - способность "Extradimensional 
            Calculations"-  раз в 2 минуты в руке можно сгенерировать дискету на 5000 очков 
            исследований (модуль Extradimensional Calculations)

Все СПУ на охранных профессиях:
1) Порог урона - 2.
2) Порог урона для начала дефектов конечностей - 13.
3) Скорость бега - 0.8 от базы  .
4) Множители урона: 0.8 (или 0.9) от базы. (ИМХО скорость важнее, чем врожденные резисты, поэтому это скорее нерф, чем бафф)
5) Умеют пользоваться оружием.
6) Способность "Enhanced Perception" -  при активации СПУ не может двигаться, но увеличивается радиус обзора (Модуль Enhanced Perception, дает зрение как от оружия с оптикой. Можно ли будет добавлять к этому еще и оптику от самой пушки - вопрос.)
        СПУ-ХОС к вышесказанному имеет:
        1) Вместо способности "Enhanced Perception" - Superior Perception. При активации СПУ не 
            может двигаться, но увеличивается радиус обзора и добавляется X-Ray зрение. Кулдаун 
            на повторное использование после деактивации - 10 секунд. (Рентген-зрение не имба, 
            так как очки-термалки уже есть) 

Все СПУ на инженерных профессиях:
1) Порог урона - 1.
2) Множители урона - 1.3 от брута, 1 от берна.
3) Скорость бега - 0.7 от базы.
4) Эффективная система охлаждения (могут гулять по космосу без скафандра сколько угодно)
5) ЭМ-экранирование - получают в 2 раза меньше урона от ЭМИ (в т.ч и внутренние органы). Модуль охлаждения не получает урона от ЭМИ (чтобы от ЭМП синги не отлетали насмерть). Все еще испытывают побочные эффекты вроде дизориентации и стана. (Модуль Экранирующая сетка)
6) Могут использовать инструменты.
7) Скорость действий - 1.1
8) Пассивная способность "Power Generator" - постепенно восполняет часть собственного запаса батареи за счет чего-нибудь (или просто так из света)
        СПУ-СЕ к вышесказанному имеет:
        1) К способности "Power Generator" - способность "Mounted RCD" - за счет 10%(15%) 
            от заряда своей батареи может воспользоваться встроенным РЦД.

Все СПУ на медицинских профессиях:
1) Скорость действий - 1.2.
2) Способность "Internal Chemical Storage" - работает как имплант-хранилище триторов, но может содержать только 6 колб на 30 единиц каждая.
3) Скорость бега - 1.
        СПУ-СМО к вышесказанному имеет:
        1) Порог урона - 1.
        2) Встроенный набор хирургических инструментов (как модули в риге)

Теперь, остановившись от чтения моих влажных deep dark fantasies, отмечу, чтобы вы не забывали про базовые дебаффы на скорость, на восприимчивость к урону, неумение пользоваться инструментами и оружием. Никакой СПУ, кроме инженерного, не сможет даже столик разобрать без овердрайва, который урон/тепло наносит. Без овердрайва не пострелять без шанса взорвать пушку в руке. Один ЭМИ все еще уничтожает охлаждающую систему, которая меньше чем за 20 секунд нагревает до максимума, и убивающая за ~3 минуты.
Отдохнули, продолжаем.

СПУ-таторы могут заказать за 10 ТК нелегальный набор модификаций, позволяющий за инъекцию нанитов убрать все дебаффы, как будто под вечным овердрайвом. 
 
СПУ-нюкеры изначально по статам равны (или в некоторых местах хуже) хуманов. За 30 ТК могут заказать "Hunter-killer kit", усиливающий собственную броню и дающий плазмаган, (может быть даже со сменой режимов карабин/дробовик!), работающий от внутренней батарейки СПУ. 

По идее из одного телевизора можно вырезать модуль-орган и вставлять другому, но не знаю, стоит ли добавлять возможность их производства в целях баланса. 

Выдвинул пропозал на обсуждение, пока пытаюсь научиться нормально пользоваться гитом в билде, где больше одного человека контрибьюторов. Большая часть фич - работа с имеющимися статами и их зависимость от профессии, что можно закостылить созданием субрас от СПУ с необходимыми эффектами. На четверть фич уже присмотрел код для копипаста. Остается посмотреть файлики, где это все есть и хорошо спланировать. А как семестр закрою, так и времени больше будет.
(скорее всего половина фич будет обрезана, остальная часть будет доделываться в качестве ДЛС в течение 5 лет peka)

**Comment by 4310V343k** [comment]
Если телевизоры придут и скажут, где баланс и лор, а где нет, могу попытаться помочь, мб
/shrug

**Comment by Shudyn** [comment]
> Если телевизоры придут и скажут, где баланс и лор, а где нет, могу попытаться помочь, мб
> /shrug

Я сам мейню телика, и я не прочь увидеть пару фишечек. Хотя бы одна ксенораса перестанет быть респрайтом хуманов.
