### ISSUE TITLE
Дыры в сыре/тортах.

### ISSUE THREAD

**Issue by DedYarick** [TauCetiStation/TauCetiClassic#5554]
#### Подробное описание проблемы
Сырное колесо и торты (это только те что я лично видел, возможно таких предметов больше) работают как хлеб, то есть в них можно положить что-либо, но в отличие от хлеба, достать нельзя. И так же из за этого теперь сырное колесо и торты нельзя порезать так как нож просто пропадает в них, достать его оттуда можно только сьев продукт.
#### Что должно было произойти
Сыр/торт порезан на кусочки.
#### Что произошло на самом деле
Нож исчезает в сыре/торте
#### Как повторить
Попытаться порезать сыр/торт.
#### Дополнительная информация:
![yssCyz0pbbU](https://user-images.githubusercontent.com/63983146/84512901-16016d00-ace2-11ea-8297-06c70d662b1f.jpg)

**Comment by cool20141** [comment]
Резать на харм, если в этом ты видишь баг. А чтоб что-то достать–перетащи сыр (И подобную еду) на себя, чтоб открыть инвентарь

**Comment by DedYarick** [comment]
Раньше можно было на любом интенте резать, я и подумал что баг.

**Comment by DedYarick** [comment]
> #### Подробное описание проблемы
> Сырное колесо и торты (это только те что я лично видел, возможно таких предметов больше) работают как хлеб, то есть в них можно положить что-либо, но в отличие от хлеба, достать нельзя. И так же из за этого теперь сырное колесо и торты нельзя порезать так как нож просто пропадает в них, достать его оттуда можно только сьев продукт.
> 
> #### Что должно было произойти
> Сыр/торт порезан на кусочки.
> 
> #### Что произошло на самом деле
> Нож исчезает в сыре/торте
> 
> #### Как повторить
> Попытаться порезать сыр/торт.
> 
> #### Дополнительная информация:
> ![yssCyz0pbbU](https://user-images.githubusercontent.com/63983146/84512901-16016d00-ace2-11ea-8297-06c70d662b1f.jpg)

**Comment by DedYarick** [comment]
Ошибка вышла, оказалось это не баг, а просто я не знал о механике.
