### ISSUE TITLE
[Bug] Поломка ружья бармена.

### ISSUE THREAD

**Issue by serejaroot** [TauCetiStation/TauCetiClassic#5558]
#### Подробное описание проблемы
Не заряжается ружье бармена горохом. (может и другими тоже)
#### Что должно было произойти
Зарядиться ружье
#### Что произошло на самом деле
Надпись You load shell into the double-barreled shotgun!x15, но горох в руке, а ружье пустое
#### Как повторить
Неизвестно. Сломалось после первых двух выстрелов.
#### Дополнительная информация:
У мотзорда тоже. И ружье, которое заспавнили тоже.

**Comment by LudwigVonChesterfield** [comment]
#5544
