### ISSUE TITLE
Хедс Оф Стафф находится на неположенной строчке в статистике ревы

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#557]
#### Подробное описание проблемы

Статистика в конце раунда с ревой отображается некорректно -  хедс оф стафф съехало.
#### Что должно было произойти

На отдельной строке.
#### Что произошло на самом деле

Съехало к хедам революции.
#### Как повторить

Закончить раунд с ревами, посмотреть статистику.
#### Дополнительная информация:

![default](https://cloud.githubusercontent.com/assets/20542000/23831758/a82996ec-0751-11e7-8b27-13f74f207188.png)

**Comment by DeadOberst** [comment]
Главы в итогах дублируются, если были убиты и клонированы.
