### ISSUE TITLE
Непонятный баг комбо-боевочки

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5570]
#### Подробное описание проблемы
Есть вероятность того, что кукла в ходе потасовки потеряет способность взаимодействия с чем либо из-за занятости рук.
#### Что должно было произойти
Такого быть не должно
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/45365635/84571632-c465ea80-ad94-11ea-9b83-ee1a5da90288.png)

С этого момента кукла не могла в комбо и в действия требующие прогрессбар, пофиксилось клонированием 
#### Как повторить
—\_('-')_/—

**Comment by Motzord** [comment]
UPD

![image](https://user-images.githubusercontent.com/45365635/84599351-a3bf9280-ae71-11ea-96d0-8820a21e99b3.png)

**Comment by Motykoo** [comment]
каждая боёвка заканчивается тем что ты Busy with something

**Comment by LudwigVonChesterfield** [comment]
Если это произойдёт в игре, пожалуйста слапните меня в дискорде - Dan#2265, чтобы я мог посмотреть.
