### ISSUE TITLE
Исчезающие сигналеры и таймеры,сенсоры и т.д при установке их на бомбу.

### ISSUE THREAD

**Issue by Drakon341** [TauCetiStation/TauCetiClassic#5572]
#### Подробное описание проблемы
При установке сигналера или любого детонатора на готовую бомбу,сингналер не отображается на ней.При этом на бомбу можно поставить бесконечное число сигналеров,при этом бомба спокойно работает.

#### Что должно было произойти
На бомбе должен отображаться установленный сигналер.
#### Что произошло на самом деле
Вид бомбы никак не изменился.

#### Как повторить
Поставьте сигналер или другой детонатор на бомбу.

**Comment by LudwigVonChesterfield** [comment]
#5544
