### ISSUE TITLE
Ритуалы превращения не дают пользы.

### ISSUE THREAD

**Issue by Noname995** [TauCetiStation/TauCetiClassic#5586]
#### Подробное описание проблемы
Ритуал клоунизации (возможно еще и превращение в борга) после прочтения пишет это
"Кукла" does not want to give themselves into this ritual!. Хотя сам человек нажал что согласен.
#### Что должно было произойти
Человек становится клоуном/боргом
#### Что произошло на самом деле
"Кукла" does not want to give themselves into this ritual!.
#### Как повторить
Провести ритуал с живым человеком.
#### Дополнительная информация:
zochem

**Comment by KIBORG04** [comment]
На радиальное меню не обращай внимания, я на этой ветке ничего там не менял.
![VlDe3RRdRY](https://user-images.githubusercontent.com/26389417/84642528-cf508480-af26-11ea-8ef1-c6d6f699bc2a.gif)

**Comment by Noname995** [comment]
> На радиальное меню не обращай внимания, я на этой ветке ничего там не менял. Если нужно, могу записать и весь экран.
> ![VlDe3RRdRY](https://user-images.githubusercontent.com/26389417/84642528-cf508480-af26-11ea-8ef1-c6d6f699bc2a.gif)

Как раз таки при окончании ритуала у священника вылезает что он не согласен, тех на ком испытывал говорили что принимали по нескольку раз, фавор тратится а ничего не происходит.

**Comment by KIBORG04** [comment]
Спасибо, что щас написал подробней. Скоро будет ПР
