### ISSUE TITLE
Камере в обесточенном помещении невозможно перерезать провода.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#559]
#### Подробное описание проблемы

Камере в обесточенном помещении невозможно перерезать провода.
#### Что должно было произойти

Когда кликаеш кусачками на провода в камере они должны перерезатся.
#### Что произошло на самом деле

Ничего.
#### Как повторить

Попробовать перерезать

**Comment by Olt1771** [comment]
И да, введите если обесточивалось помещение, то и камеры не работали бы

**Comment by Dennok** [comment]
угу

**Comment by Dennok** [comment]
возможно проблема тут https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/game/machinery/camera/wires.dm#L138

**Comment by Djekke** [comment]
Нашел где, но не представляю как исправить: [/code/game/machinery/camera/wires.dm#L136-L138](https://github.com/TauCetiStation/TauCetiClassic/blob/ea5121b94954b01cd2bb183f475dafd58a0102e6/code/game/machinery/camera/wires.dm#L136-L138) проверяет родительский прок, в котором в случае отключения энергии выдает `FALSE`: [/code/game/machinery/machinery.dm#L249-L257](https://github.com/TauCetiStation/TauCetiClassic/blob/ea5121b94954b01cd2bb183f475dafd58a0102e6/code/game/machinery/machinery.dm#L249-L257)
Вопрос в том как оно должно реагировать?
 - Позволять резать провода но не сигналить?
 - При разрезании провода, менять ли функционал?
 - Возможность восстанавливать провода? (Mend)

Так же при отключении энергии задет интерфейс проводов дверей (Но там он позволяет изменения, но не обновляет окно проводов)

**Comment by SpaiR** [comment]
Это все давно понятно. И я уже писал, что сделаю чуть позже для проводов отдельный датум и у них будет свой топик. Не нужно ничего трогать.

**Comment by Djekke** [comment]
Понял, #857 Тоже к этому относится
