### ISSUE TITLE
Мыши могут драг&дропом пихать в крио

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5591]
#### Подробное описание проблемы
Мышь через ктрлперетягивание может засунуть человека в крио
#### Что должно было произойти
Не должны мочь
#### Что произошло на самом деле
Могут

**Comment by cool20141** [comment]
И что мышам тогда делать, кроме как пихать людей в крио?

**Comment by LudwigVonChesterfield** [comment]
Ничего. Это умершие игроки. Их геймплей не должен быть весёлым (с текущей системой этого всего)

**Comment by cool20141** [comment]
Почему это им не должно быть весело? Они хоть и умерли, но они все же игроки

**Comment by LudwigVonChesterfield** [comment]
Если играть за мышей будет весело - то зачем играть в раунде, и не умирать?

**Comment by LudwigVonChesterfield** [comment]
И да, отстаивать баг на основах "скучного геймплея" - это верх.

Если хочешь чтобы у них был веселый геймплей - закодь им весёлый геймплей.
