### ISSUE TITLE
Синга и лазеры

### ISSUE THREAD

**Issue by atik1n** [TauCetiStation/TauCetiClassic#5592]
#### Подробное описание проблемы
![01mhIl2d8g](https://user-images.githubusercontent.com/14612180/84703950-b44f3600-af61-11ea-8efa-1dca6a3d1243.gif)

#### Что должно было произойти
Лазер не тянется к синге?

#### Что произошло на самом деле
Лазер тянется к синге

**Comment by cool20141** [comment]
Почему нет? Учитывая, что синга–это типа "черная дыра", то притягивание лазеров–нормальное явление

**Comment by T6751** [comment]
#2193
