### ISSUE TITLE
[Proposal] Убрать излишнюю трудность CPR.

### ISSUE THREAD

**Issue by wadangel** [TauCetiStation/TauCetiClassic#5593]
#### Подробное описание проблемы
Из-за излишней сложности механики она практически не используется (это субъективный взгляд из обсерва каждодневный) в гетто-условиях. 

Вчера были опыты на сервере при помощи удушения куклы (пробовали я, ещё один медик, унатх и ещё какие-то рандомы), выяснилось, что получилось это вообще только у меня ~~если я не ошибаюсь~~, да и то порядка пятидесяти кликов пришлось в сумме сделать, потому что в окошко ~1.2 секунды попасть очень трудно даже не столько из-за его узости, сколько из-за постоянных пролагов сервера. Сделать достаточное для оживления количество кликов без излишней возни не выходит, т.к. пара ошибок и фсо. 
Хотя фибрилляция работает нормально, да. С подключенным искусственным сердечком человека ещё реально поднять, а вот без - это совсем извращение для мазохистов, которое, ну, тупо не работает в условиях быстрого темпа игры и по этой причине лишено смысла.

*Analyzing Results for Unknown:
  Overall Status: dead
  Key: Suffocation/Toxin/Burns/Brute
  Damage Specifics: 182 - 0 - 0.5 - 0
Body Temperature: 6.50821°C (43.7148°F)
Time of Death: 13:11
Localized Damage, Brute/Burn:
  Chest: 0  - 0.5
Severe oxygen deprivation detected
Subject bloodstream toxin level minimal
Subject burn injury status O.K
Subject brute-force injury status O.K
Bone fractures detected. Advanced scanner required for location.
Blood Level Normal: 100% 560cl. Type: A+
Subject's Heart status: Attention! Subject's heart fibrillating.
Subject's pulse: 69 bpm.*

#### Дополнительная информация:
На мой взгляд, это можно пофиксить либо изменением непонятной системы "очков" на связку с  пульсом куклы, потому что выходит, что она при общем здоровье (нормальный пульс/нет урона) остаётся по статусу мертва и реанимации не происходит.

Получается, что медикам эта механика практически и не нужна (потому что дефибры), а остальной экипаж её из-за сложности и огромной необходимость во времени и концентрации внимания на rhytm-game не использует.

**Comment by LudwigVonChesterfield** [comment]
>  что она при общем здоровье (нормальный пульс/нет урона) остаётся по статусу мертва и реанимации не происходит.

Я бы поспорил что проблема в том что у куклы с поломанным сердцем нормальный пульс.

> Получается, что медикам эта механика практически и не нужна (потому что дефибры)

Медикам эта механика полностью не нужна.

**Comment by Motzord** [comment]
Все работает CRP это способ для поднимая космонавтов в гетто условиях, в медбее есть дефибы, но если их там не будет, у космонавтов есть трудоемкая альтернатива.

**Comment by LudwigVonChesterfield** [comment]
#5347
