### ISSUE TITLE
Отображение божка

### ISSUE THREAD

**Issue by Motykoo** [TauCetiStation/TauCetiClassic#5598]
#### Подробное описание проблемы
Гостота не видит бога, если у неё включен Toggle Darkness
#### Что должно было произойти
Темнота исчезнуть, бог остаться видимым
#### Что произошло на самом деле
Бог исчезает вместе с темнотой

**Comment by LudwigVonChesterfield** [comment]
Такие же баги бывают с отображением самих гостов. Некоторые госты видны когда тугл даркнесс включен, некоторые когда выключен.
