### ISSUE TITLE
[Proposal] Нерф спейс луба.

### ISSUE THREAD

**Issue by Shudyn** [TauCetiStation/TauCetiClassic#5606]
Понаблюдав из гостоты за очередным разносом половины команды нюкеров одним человеком со смазкой, я решил поставить этот вопрос на обсуждение.

На данный момент спейс луб является вторым компонентом победы над любым оппонентом после гиперцина, которые легко готовятся из общедоступных веществ в той же химии. Фактический станлок(размазывай индустриальным распылителем/спреем вокруг жертвы и та никуда не убежит, хотя времени стана достаточно, чтобы взять в третий граб) и разоружение из-за кнока не оставляет шансов на сопротивление против пользователя смазки. Его широкое использование ограничивается только изначальным количеством спреев на станции, но которого более чем достаточно для снабжения нескольких человек этим оружием.
Благо сейчас спейслубом нельзя отправить прямо в космос через шлюз, как раньше.

В связи с вышесказанным, предлагаю пути решений:
1) Убрать стан вообще, оставив функцию быстрого проскальзывания по смазанному полу (meh).
2) Усложнить формулу смазки, добавив туда форон и другие сложные вещества, уменьшив выход(лучше, но meh). 
3) Добавить мини-игру во время скольжения. Например, "ходьба" в любую сторону, кроме направления скольжения, приведет к падению и стану. Можно при проходе по тайлу со смазкой отправлять куклу в рандомную сторону (потеря баланса). Как по мне, не убьет смазку совсем, но при этом она перестанет быть оружием массового поражения и заставит быть более осторожным (лично мне этот вариант нравится хотя бы на бумаге).
4) Сделать резист от смазки для NOSLIP(meh).
5) Значительно уменьшить стан, так как он, фактически, гарантированный, до 0.5-1 секунды (тоже хорошо, но стоит отправлять содержимое рук вместе с владельцем, или просто не ронять его, но давать стан). 

Discuss.

(Нет, я не отлетел от смазки)

**Comment by LudwigVonChesterfield** [comment]
https://docs.google.com/spreadsheets/u/1/d/1-NEtDFMdtERvAX1vs_VYvh175L8M0E22-0EZlWIG15Q/edit#gid=0

**Comment by cool20141** [comment]
Просто добавить комбат бутсам защиту от смазки, а не нерфить ее полностью

**Comment by Akellazp** [comment]
Предлагаю уменьшить стан от смазки (реально очень долгий он сейчас), а ноуслипам либо уменьшить проскальзывание, либо убрать проскальзывание, оставив подскальзывание.
В рецепт смазки можно добавить форон, но как катализатор, не более

**Comment by 4310V343k** [comment]
А давайте не нерф, а баланс. Что бы смазка не подскальзывала, а проскальзывала на всю длину разлитой смазки и ещё пары тайлов

**Comment by simb11** [comment]
Закройте это, пожалуйста.
