### ISSUE TITLE
Невозможно демонтажировать окно в листы.

### ISSUE THREAD

**Issue by Bill-Luxe** [TauCetiStation/TauCetiClassic#561]
#### Подробное описание проблемы
Если создать "тонкое" окно и открутить с пола/решётки а потом использовать гаечный ключ - персонаж просто бьёт по стеклу.

#### Что должно было произойти
В открученном состоянии: Начать демонтаж окна в листы стекла (обычное в обычные листы, укреплённое в укреплённые листы)

#### Что произошло на самом деле
Бью гаечным ключом по окну, в итоге ломаю само окно.

#### Как повторить
Продолжать тыкать по развинченному с пола окну гаечным ключом.

#### Дополнительная информация:
Вообще, это единственный способ одновременно убрать окно и добыть с него лут, но ведь это выглядит немного по дурному, не так ли? Разве инженеры/дроны настолько некомпетентны чтобы демонтировать их в листы?

**Comment by ZVee** [comment]
Возвращать назад потраченные ресурсы, тем более полностью - точно будет неправильным. Да и осколки которые получаются после грубого демонтажа (т.е разбития стекла), можно обработать горелкой и получить обычное стекло.

**Comment by Dennok** [comment]
Темнеменее это ущербно, а также куб стекла хрен снесеш.

**Comment by Damirrus1** [comment]
Сними сейчас окно у себя дома и ударь его гаечным ключом, получилось?

**Comment by ZVee** [comment]
>а также куб стекла хрен снесеш.

Топором.

**Comment by Raschert0** [comment]
@Damirrus1 возьми кусок стекла и сделай из него окно. Получилось? (хотя разбор окна ключом всё равно не нужен)

**Comment by Bill-Luxe** [comment]
Ладно уж, я вижу что тут ничего более не поделаешь, теперь я хотя бы знаю что это не баг.
Спасибо за ответ.
