### ISSUE TITLE
Аттакбай по модулям рига

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5615]
#### Подробное описание проблемы
Хочу пихнуть металл в модуль самопочинки
#### Что должно было произойти
Металл пихается
#### Что произошло на самом деле
Я бью металлом модуль самопочинки
#### Как повторить
Попробуйте его заправить

**Comment by LudwigVonChesterfield** [comment]
Это случается только если модуль уже полностью заправлен.

**Comment by LudwigVonChesterfield** [comment]
Прошелся по коду.

Модули ригов не принимают напрямую какие-либо предметы, только когда эти модули уже внутри какого-то рига.
