### ISSUE TITLE
Перестал работать ускоритель роста волос

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5616]
#### Подробное описание проблемы
Сожрал/пшикнул/вколол Hair Grown Axelerator — 
#### Что должно было произойти
выросли волосы далась рандомная прическа
#### Что произошло на самом деле
Ничего

**Comment by T6751** [comment]
> Сожрал/пшикнул/вколол 

Ускоритель работает всеми способами. Вероятно проблема больше не актуальна
