### ISSUE TITLE
Всё еще пропадают сигналлеры и тд

### ISSUE THREAD

**Issue by atik1n** [TauCetiStation/TauCetiClassic#5617]
#### Подробное описание проблемы
#5572

**Comment by LudwigVonChesterfield** [comment]
Пожалуйста напишите названия предметов которыми вы тыкаете по предметам, указание на ПР лично мне не помогает понять что не так.

**Comment by Drakon341** [comment]
Сигналеры,таймеры,сенсор.

**Comment by atik1n** [comment]
> Пожалуйста напишите названия предметов которыми вы тыкаете по предметам, указание на ПР лично мне не помогает понять что не так.

По словам человека из раунда исчезают при присоединении к крану для лимитки

**Comment by LudwigVonChesterfield** [comment]
Названия которые используются в игре пожалуйста, чтобы я мог очень быстро их найти.

**Comment by Motzord** [comment]
gas(?) transfer valve. remote signalling divece, timer, proximity sensor (и все что можно вообще приебашить к игнитеру, то можно и к transfer valve

Вроде это все добро лежит в obj/item/device
