### ISSUE TITLE
Самоотозвался шаттл по голосованию

### ISSUE THREAD

**Issue by atik1n** [TauCetiStation/TauCetiClassic#5618]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/14612180/84963430-0d5dcc00-b112-11ea-8a67-43df9851b7a9.png)
Больше я видеть не могу, да и в логах ничего странного нет. Он просто отозвался. Причем в тихую. Причина неизвестна.
#### Что должно было произойти
Шаттл прилетел.
#### Что произошло на самом деле
Шаттл не прилетел.
#### Дополнительная информация:
Раунд \#34350

**Comment by Motzord** [comment]
Я ни на что не намекаю, но наверное раунд был ревой

**Comment by atik1n** [comment]
> Я ни на что не намекаю, но наверное раунд был ревой

Умник, тут даже видно, что нинжа
Да и даже в реву он со звуком это делает
