### ISSUE TITLE
[Proposal] Удаление кошачьих ушей из автомата клоуна.

### ISSUE THREAD

**Issue by MoodyBlues1606** [TauCetiStation/TauCetiClassic#5619]
Давайте будем честны, насколько часто вы видите клоуна/мима в кошачьих ушах? В большинстве случаев данный аксессуар оказывается у трапов, и это факт. Настолько едкое сочетание вызывает брейнротовые ситуации аля командный состав кошкодевочек, или единичные случаи неко-трапов (а порой и не только трапов). Удаление ушей пусть и не сильно, но порой заметно уменьшит кринжовость внешнего вида особо чутких модников среди экипажа.

**Comment by DedYarick** [comment]
Тебе бы голосование на форуме сделать, а потом уже ПР выкатывать.

**Comment by KIBORG04** [comment]
Где ты тут видишь ПР? Я не думаю, что этот человек вообще умеет делать ПРы.
Но голосование стоит сделать, мб кто-то нормальный их и удалит.

**Comment by FelixRuin** [comment]
да, в автомате клоуна кошачьим ушам не место, это уж точно
