### ISSUE TITLE
Проблема с подпрофой учёных

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#562]
#### Подробное описание проблемы

Ксеноархеолог является под профой учёного и если взять ксеноархеологов не будет учёных
#### Что должно было произойти

Должно было зайти N-oe кол-во учёных и археологов
#### Что произошло на самом деле

Зашло трое ксеноархеологов и ноль учёных
#### Как повторить

Зайти на профу ксеноархеолога 3-мя людьми
#### Дополнительная информация:

Сделайте как и раньше доступ учёным на астеройд (ибо в 1-2 раундах из 10 пристутствуют шахтёры)
И если кто то будет лутать риги "на всякий случай" бить за это по рукам

Так же, появилась новая проблема, если есть два ксеноархеолога, даже если ещё 2 свободных слота учёных, то выпадает рандомная профа

**Comment by Kurshan** [comment]
Таких как ты и придётся пинать.

**Comment by Olt1771** [comment]
Я б в телесале лутал каждый раунд и на всякий бы не снимал, да
