### ISSUE TITLE
Отрубание камеры энергомечем не удаляет ее из списка камер.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#563]
#### Подробное описание проблемы

Отрубание камеры энергомечем не удаляет ее из списка камер.
#### Что должно было произойти

Камера должна пропасть из списка камер.
#### Что произошло на самом деле

Осталось одно название в консоли камер.
#### Как повторить

Отрубить камеру энергомечем

**Comment by Belfogor** [comment]
А почему камера должна быть удалена из списка? В списках она числится как "неисправна"

**Comment by ZVee** [comment]
Потому что камера перестает существовать, с чего ей быть в списках?

**Comment by Belfogor** [comment]
Она остается в списках, но неактивна. В чем проблема? Так через эти списки можно отслеживать выключенные камеры. может быть и баг, но чертовски полезный.

**Comment by ZVee** [comment]
Тем что это референс на камеру которую готовится забрать мусорщик и которому мешают это сделать.

**Comment by SpaiR** [comment]
Собственно, после нескольких проверок более чётко определил суть проблемы. Из списка камер камера удаляется, с этим всё окей. Корень бага заключается в этих строчках. 
https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/game/machinery/computer/camera.dm#L42-L64
Каждая консоль при формировании ui создаёт кэш с json, в котором находятся все камеры на момент создания ui. Кэш у каждой консоли свой и он нигде не обновляется. Соответственно, если бы кэш обновлялся после изменения списка камер, то и проблем бы никаких не было.
Решением, скорее всего, могут послужить изменения из данного ПРа: https://github.com/Baystation12/Baystation12/pull/12074
, но не факт, нужно чекать.

**Comment by RichardJones1** [comment]
Нужен тестовый фидбек, а я же предлагаю такое решение - прикрутить кнопке Refresh в консоль камер механ обновления списка
