### ISSUE TITLE
Без ног и стекло!

### ISSUE THREAD

**Issue by Elfarino** [TauCetiStation/TauCetiClassic#564]
Когда едешь на коляске без ног, падаешь на стекле.

**Comment by FelixRuin** [comment]
было пофикшено в https://github.com/TauCetiStation/TauCetiClassic/pull/3368, не знал что можно просто написать вместо фикса - fix и будет лучше в теории, если там автоматически, а если нет, то закройте, да

**Comment by FelixRuin** [comment]
@TauCetiStation/collaborators
