### ISSUE TITLE
[Proposal] Добавить шлему абдукторов защиту от флешек и флешбенгов

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5640]
#### Подробное описание проблемы
У шлема абдукторов нет защиты от флешек
#### Что должно было произойти
Сhad абдуктор ворует асистентов налево и направо с помощью своего мощного батона
#### Что произошло на самом деле
Сосет от одного асистента с флешкой

**Comment by Motykoo** [comment]
Сверхразвитая раса использующая людей для развлечения и экспериментов, владеющая крутым оружием, возможностью мгновенной телепортации сосет от флешки.

**Comment by Shudyn** [comment]
Хороший ученый всегда за агентом смотрит и телепортирует обратно, если не получилось сделать нормально.
Продвинутые кондукторы тырят затемненные очки из стрельбища или снимают с глав.
