### ISSUE TITLE
Кастомный бутерброд не тратится при соединении его с другим бутербродом

### ISSUE THREAD

**Issue by GermanSUS** [TauCetiStation/TauCetiClassic#5642]
#### Подробное описание проблемы
Я играл за повара и решил сделать башню-сэндвич, все шло хорошо пока я не соединил маленький сэндвич и большой.
#### Что должно было произойти
Маленький пропадает а большой увеличивается на столько же, сколько кусочков было и в маленьком.
#### Что произошло на самом деле
Сэндвич увеличился на один кусочек, но маленький выпал на стол и так можно было продолжить делать.
#### Как повторить
Сделать два кастомных бутера и кликать одним на другой.
#### Дополнительная информация:
Можно и наоборот, на один кусочек сложить большой и к маленькому кусочку добавится 1 кусочек а большой бутер не потратится.

**Comment by LudwigVonChesterfield** [comment]
Напиши названия предметов пожалуйста.

**Comment by GermanSUS** [comment]
![image](https://user-images.githubusercontent.com/59874480/85152806-1c519500-b25e-11ea-9938-33a9a6a5dc12.png)
Вот я повторил эксперимент

**Comment by GermanSUS** [comment]
А вот последствие этого бага
![image](https://user-images.githubusercontent.com/59874480/85155126-0c878000-b261-11ea-96c6-fbf14c297dc0.png)
