### ISSUE TITLE
Отправка ПДА сообщения без связи

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#5657]
#### Подробное описание проблемы

Используя фичу передачи денег с ПДА на ПДА и оставив комментарий можно общаться за деньги между собой, даже когда сервера ПДА упали.

#### Что должно было произойти

Деньги не должны были передаваться когда связи нет

#### Что произошло на самом деле

Они передаются

#### Как повторить

Уложить сервера ПДА, взять два ПДА, с одного на другой перевести копейку с комментарием "ляяя ряяя"

#### Дополнительная информация:
@Ahion

**Comment by Ahion** [comment]
Да, сервер я не учел. Постараюсь исправить в ближайшее время.

**Comment by Shudyn** [comment]
Хорошая же фича. Только комиссию настроить, чтобы не абузили, и минимальный перевод в 50 кредитов. Мол, через банковские сервера идут сообщения, а не станционные.
