### ISSUE TITLE
риот щитом больше нельзя отталкивать без урона

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#5667]
#### Подробное описание проблемы
тайтл
#### Что должно было произойти
можно оттолкнуть без урона
#### Что произошло на самом деле
наносится урон (и вроде бы не отталкивается)
#### Как повторить
ударить человека щитом на дизарме

**Comment by LudwigVonChesterfield** [comment]
Ctrl-Click/Ctrl-Shift-Click с хелпом.

**Comment by AndroBetel** [comment]
не интуитивно в отличие от интентов

**Comment by LudwigVonChesterfield** [comment]
у нас пихание-притягивание-кручение уже на отдельной системе и имеется и на других предметах.

если перенесёшь чтобы все предметы на дизарм пихали если могут - будет "интуитивно".

то что ты описал - не баг, и описано в #4458

![image](https://user-images.githubusercontent.com/17705613/85407403-d7827280-b56b-11ea-8d05-31012e5f95de.png)
