### ISSUE TITLE
Долгое переливание в ёмкость

### ISSUE THREAD

**Issue by PirogSema** [TauCetiStation/TauCetiClassic#5673]
#### Подробное описание проблемы
При переливании вещества в ёмкость происходит атака и небольшая, но неприятная задержка из-за которой долго переливать вещество (рамен во флягу, криосмесь в бикер). Плюс показывается в чате сообщение о том что такой-то атаковал чем-то что-то.
#### Что должно было произойти
Быстрое переливание из одной ёмкости в другую
#### Что произошло на самом деле
Переливание с задержками между каждым актом переливания вещества в другую ёмкость
#### Как повторить
Взять ёмкость или шприц и попробовать быстро перелить вещество оттуда в другую ёмекость (бикер, фляга)

**Comment by TheLustOfBlood** [comment]
Действительно неприятной баг
