### ISSUE TITLE
[BUG] Борги отдают модули.

### ISSUE THREAD

**Issue by Grox103FM** [TauCetiStation/TauCetiClassic#5674]
#### Подробное описание проблемы
Борг через give может передавать модули.

#### Что должно было произойти
У борга нет кнопки give, и тем более она не работает

#### Что произошло на самом деле
Борг имеет эту кнопку и спокойно отдаёт свои модули.

#### Как повторить
Подойти к человеку, ткнуть по нему ПКМ и нажать на give, держа в "руке" модуль. Человек должен принять его

#### Дополнительная информация:
Нет

**Comment by 4310V343k** [comment]
Более того, борг может использовать вещь, лежащую в руке хумана, прямо из рук хумана, даже с другого конца станции, а если спрятать модуль, то человек сможет использовать модуль прямо из хранилище борга, при том он будет использоваться от лица борга, а иконка модуля в руках хумана пропадёт
