### ISSUE TITLE
Телекомм технику невозможно разобрать.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#569]
#### Подробное описание проблемы

Телекомм технику невозможно разобрать.
#### Что должно было произойти

Должно было разобратся на детальки и раму.
#### Что произошло на самом деле

Ничего.
#### Как повторить

Попробовать разобрать телекомм техику.
#### Дополнительная информация:

На стадии использования лома выдает сообщение о разборе но ничего не происходит.

**Comment by RichardJones1** [comment]
Да,есть, пытался как то пофиксить, почти получилость, но забил. Но баг есть
