### ISSUE TITLE
Немного о стамине в третьем грабе.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5690]
#### Подробное описание проблемы
Недавно вмержили ПР с системой стамины в третьем грабе (или не вмержили?)

Есть два проблемы которые нужно пофиксить чтобы система была полезна, а именно

1. Стан после захвата в третий граб больше, чем время за которое третий граб переходит в удушение
2. Пуш(дизарм) ломает третий граб одним кликом.
#### Что должно было произойти
1. У куклы должна быть возможность сопротивляться в третьем грабе, а не стоять болванчиком когда пройдет стан, а затем спокойно задушиться, так как удушение станит по КД без возможности резиста

2. Пуш не должен ломать третий граб
#### Что произошло на самом деле
1. Ого, я в третьем грабе, надо резистаться! Блин, я в стане и пока он пройдет меня удушат, а я никак не могу на это среагировать

2. Ого, я в третьем грабе, не буду резистать, просто кликну пуш и надаю по щщам.

**Comment by cool20141** [comment]
Еще ничего не вмержили https://github.com/TauCetiStation/TauCetiClassic/pull/5575
1. Стан я вырезал так-то, а для перехода в удушении нужно набить 0 и меньше стамины захваченному
2. Эту проблему тоже, можно сказать, почти решил
