### ISSUE TITLE
Сканер аутопсии — уникален

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5695]
#### Подробное описание проблемы
Сканер аутопсии имеется в количестве 2 штук и больше нигде не достается
#### Что должно было произойти
Печатается/заказывается
#### Что произошло на самом деле
Ученые подрались с медиками за сканер в морге в итоге избили криминалиста и отобрали у него
#### Как повторить
Попробуйте родить себе еще один сканер аутопсии

**Comment by LudwigVonChesterfield** [comment]
добавьте его или в протолат или в автолат. возможно ещё набор для аутопсии(лол) в карго

**Comment by LudwigVonChesterfield** [comment]
ещё было бы прикольно если бы был makeshift autopsy scanner который бы делался из анализатора здоровья, сканнера реагентов, палки, скальпеля, и проводов

и чтобы он иногда барахлил как-нибудь смешно

**Comment by KIBORG04** [comment]
Их же два

**Comment by Motzord** [comment]
> Их же два

Да, но он нужен ученым, криминалисту, медику и к примеру любому доктору менгеле самоучке. Особенно он нужен ученым для очков, и внезапно ближайшее место где его можно скомуниздить — медбей.

В итоге врачи хуесосят ученых, ученые хуесосят врачей

**Comment by Dushess0** [comment]
![image](https://user-images.githubusercontent.com/44201461/91864572-a19af200-ec70-11ea-929b-11a175fbe676.png)
Сделал вот такой ящик в карго за 2000. Что думаете?

**Comment by Loratron** [comment]
> вот такой ящик в карго за 2000.

А не слишком дорого? Столько же стоит ящик с 4 генераторами щита, а 2 набора брони и то на 500 меньше стоят

**Comment by Dushess0** [comment]
1500 нормально будет?

**Comment by KIBORG04** [comment]
Положи ещё для приличия ящик перчаток, масок и халат, стеоильность же все таки нужна

**Comment by Dushess0** [comment]
> Положи ещё для приличия ящик перчаток, масок и халат, стеоильность же все таки нужна

![image](https://user-images.githubusercontent.com/44201461/91873564-736de000-ec79-11ea-8b21-4a67c2372e17.png)

**Comment by Motzord** [comment]
Тогда уж запихни еще фотоаппарат и пленку

**Comment by Loratron** [comment]
> Тогда уж запихни еще фотоаппарат и пленку

Можно ещё и стол операционный, вскрывать-то не на чем
