### ISSUE TITLE
Поломка crew transfer vote

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5709]
#### Подробное описание проблемы
Воут может произвольно ломаться и не вызываться, или вызываться но таймер не будет тикать
#### Что должно было произойти
Воут корректно вызывается
#### Что произошло на самом деле
F1 

Педали суки, воут почините
#### Как повторить
Поиграйте на сервере, заметьте что воут сломан
#### Дополнительная информация:
Основная поломка воута — зависание воута режима после раундстарта, изза чего невозможно без педального вмешательства новый воут

**Comment by cool20141** [comment]
А с каких пор такое стало встречаться, кстати? Довольно давно уже вроде

**Comment by T6751** [comment]
Всё ли ещё актуально?

**Comment by T6751** [comment]
Похоже, что не актуально
