### ISSUE TITLE
Быстрое снятие скафандра/РИГа

### ISSUE THREAD

**Issue by Nocotov77** [TauCetiStation/TauCetiClassic#5722]
#### Что должно было произойти
Должен был запустится таймер на снятие скафандра/РИГа

#### Что произошло на самом деле
Скафандр снялся мгновенно

#### Как повторить
Достаточно перетащить скафандр со слота "Exosuit" на руку

**Comment by AndroBetel** [comment]
вижу и будет пофикшено

**Comment by TheLustOfBlood** [comment]
![88d440es-1920](https://user-images.githubusercontent.com/62372418/86035028-d1a5f900-ba65-11ea-992d-d7d98bfd04ff.jpg)

**Comment by 4310V343k** [comment]
удоли

**Comment by Tolerantboy** [comment]
Слыш, удоли

**Comment by cool20141** [comment]
Снимают риг обычно в мирной обстановке, так на кой черт делать дополнительную задержку, если от нее, по сути, ничего не решается, а только игрокам придется в очередной раз ждать

**Comment by LudwigVonChesterfield** [comment]
@AndroBetel когда пофиксишь, не забудь скопипастить в фикс во все места где ты это копипастил пж... авось у нас ещё какие-то вещи не должны мгновенно сниматься...

**Comment by AndroBetel** [comment]
мейнтейнер злодей я пытаюсь нормально сделать а не копипастить везде
