### ISSUE TITLE
ЭМИ импланты лежат в оружейке.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5727]
#### Подробное описание проблемы
Видимо кодер хотел завезти эми снаряды для гранатомета M79 но напихал туда эми имплантов

Это вальтерже со своим ребалансом виноват
#### Что должно было произойти
В оружейке не лежат импланты синдиката
#### Что произошло на самом деле
Они лежат там. Нахуя и зачем?
#### Как повторить
Зайти в оружейку и покопаться в снарядах для гранатомета

**Comment by Ayuska** [comment]
Это актуально:?

**Comment by 4310V343k** [comment]
Не актуально
