### ISSUE TITLE
Старт игры без рольки и... без вас

### ISSUE THREAD

**Issue by ArtBsd1** [TauCetiStation/TauCetiClassic#5737]
#### Подробное описание проблемы
При не выбранной профессии и при нажатии "READY", то смена стартует без вас. Остается только "READY"
#### Что должно было произойти
Я должен был стартовать за игрой
#### Что произошло на самом деле
Я в лобби без рольки, прошу компенсировать морально мне на карту.
#### Как повторить
Убрать профу и нажать Реди 
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/44677341/86265596-67b05f80-bbdd-11ea-8480-85c05a9d8dde.png)

**Comment by cool20141** [comment]
Ну так если у тебя стоит return to lobby, то тебя вернет в лобби, а что ты хотел?

**Comment by ArtBsd1** [comment]
> Ну так если у тебя стоит return to lobby, то тебя вернет в лобби, а что ты хотел?

А да, наверное. Тогда можно закрывать тему

**Comment by LudwigVonChesterfield** [comment]
![image](https://user-images.githubusercontent.com/17705613/86266376-ccfc5480-bbcd-11ea-8e2b-a758230e461b.png)
