### ISSUE TITLE
Цены в Price Tool-е пиратов

### ISSUE THREAD

**Issue by CeUvi** [TauCetiStation/TauCetiClassic#5739]
#### Подробное описание проблемы
У нас были снижены цены, деньги на счетах космонавтиков, но цены в прайс туле остались прежними
#### Что должно было произойти
Цены ниже
#### Что произошло на самом деле
Скафандр из голубого шкафа стоит 27к и так далее
#### Как повторить
Ткнуть прайс тулом куда-либо
#### Дополнительная информация:
верните пиратов

**Comment by Motzord** [comment]
пиратов выпилили на корню, да киборг?

**Comment by KIBORG04** [comment]
Не на корню, фултоны оставил
