### ISSUE TITLE
Термостат аираларма нельзя выставить на 0 градусов цельсия.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#574]
#### Подробное описание проблемы
Термостат аираларма нельзя выставить на 0 градусов цельсия.
#### Что должно было произойти
Должно было выставитса 0.
#### Что произошло на самом деле
Сказало что температура должна быть между 0 и 40.
#### Как повторить
попробовать поставить 0.
#### Дополнительная информация:
поставить 40 градусов можна, и поставить 0.00001 тоже можноа вот 0 нельзя.

**Comment by Raschert0** [comment]
Кхм, @Dennok а что непонятного в слове "между"? Она же значит, что число больше нижней границы и меньше верхней

**Comment by Dennok** [comment]
Всетаки обычно граници тоже входят но...
