### ISSUE TITLE
Невозможно отключить паник сифон кнопкой в настройке скрабера.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#575]
#### Подробное описание проблемы
Невозможно отключить паник сифон кнопкой в настройке скрабера.
#### Что должно было произойти
Должно быть можно отключить паник сифон кнопкой в настройке скрабера.
#### Что произошло на самом деле
Ничего.
#### Как повторить
Попробовать включить паник сифон скрабера а потом попробовать отключить паник сифон кнопкой в настройке скрабера.

**Comment by dearprincesscelestia** [comment]
Вернули баг? Молодцы, можно заходить за котмосферника и ругать НЕ ТРОГАЙ КНОПКУ ПАНИК, а потом вспоминать, что говоришь с людьми, и, плача, забиваться под стол.

**Comment by Dennok** [comment]
К счастью кнопочка в основном меню на отключение работает. А также режим общий если сменить то отключает.
