### ISSUE TITLE
[Proposal] Ограничение механом мозга разных рас

### ISSUE THREAD

**Issue by atik1n** [TauCetiStation/TauCetiClassic#5750]
![image](https://user-images.githubusercontent.com/14612180/86457555-86713c00-bd2c-11ea-9b02-1fdb95a6fe42.png)
Б**о**льшая часть ГМов проголосовала против возможности пересаживать мозг, поэтому будет логичнее именно ограничить это механом.

Возможный вариант:
При пересадки мозга от хумана, например, таяре мозг просто отмирает в состояние Brain dead. Всё, finita la comedia.

**Comment by Sakuya-Izayoi** [comment]
Ну это ГМы, а где голоса твоих так любимых игроков?

Что, зассал мнению игроков довериться?

**Comment by atik1n** [comment]
> Что, зассал мнению игроков довериться?

Это было голосование именно по правилам и стоит ли такое наказывать.
Выбор пал в сторону "да, стоит". А тогда еще лучшим решением будет именно ограничить механом.

**Comment by volas** [comment]
Аргументы к подобному решению есть?

Про педальный воут тоже не вполне ясно, зачем на него ссылаться - у нас подобное публично на форуме обсуждается.

**Comment by atik1n** [comment]
> Аргументы к подобному решению есть?

Единственный мой аргумент - банить за то, что даёт механ не очень то и правильно
Ограничивать бюрократией, как предложили в \#staffroom тоже странно, ибо бюрократия опциональна
Делать процедуры в СПД/процедурах НТ тоже не подойдет по тем же причинам, ибо в основном им у нас подчиняются СБ и Главы, иначе баны налево и направо пойдут
Либо просто оставить как есть, но и не банить вовсе за установку на поток пересадки мозгов хуманов в котов ради скорости

**Comment by volas** [comment]
Давай продолжим "почему". А почему вам понадобилось банить за это?

**Comment by atik1n** [comment]
Появились случаи, когда один администратор наказывает, а другой нет
![image](https://user-images.githubusercontent.com/14612180/86469071-5d0edb00-bd41-11ea-8045-2b2ebb8ceaa3.png)
![image](https://user-images.githubusercontent.com/14612180/86469099-6ac46080-bd41-11ea-87a4-f8ed7b5fdb36.png)

Именно после этого тикета я слапнул всех кого надо и не надо с вопросом "а как вы на это смотрите", ибо это не нормально.
Я понимаю, что у нас даже написано, что за трактовку правил ответственен администратор в раунде, но всё же не должно быть такого, что часть лояльна, а часть банит

\+ есть прецедент в виде [моего бана GermanRUS](https://forum.taucetistation.org/t/apellyacziya-germanrus-nebolshoe-nedorazumenie/19092/25) и [нового банхаммера](https://forum.taucetistation.org/t/banhammer-birk-bishop-kris-praison-allen-bennett-grifing-bagoyuz/19561/2)

**Comment by volas** [comment]
Ты не ответил. Почему эта часть механа вдруг стала наказываться? У нас есть правила, а если админы выдумывают свои - есть хедмин на них.

**Comment by atik1n** [comment]
> Почему эта часть механа вдруг стала наказываться?

Она граничит с ксеноограничениями. Это можно воспринимать как:
- обход ксенобанов (как в случае с Германом)
- получение преимущества от ксенорасы

Ну и так можно сделать кэпа-таяру, а вроде бы получение профессии через ГП у нас наказывается

**Comment by volas** [comment]
И ты рассуждаешь о ксеноограничениях, но сам же говоришь что ксеновизоры сразу решили что это не про них.
Значит, и проблемы нету? За исключением той, что кто-то опять начал по своим хотелкам банить и вводить остальных в заблуждение, игроков и педалей.

**Comment by atik1n** [comment]
> И ты рассуждаешь о ксеноограничениях, но сам же говоришь что ксеновизоры сразу решили что это не про них

Тут просто классическая картина. Админы в сторону ксеновизоров, ксеновизоры в сторону админов.

<hr>
![image](https://user-images.githubusercontent.com/14612180/86470225-a95b1a80-bd43-11ea-8341-18da3f49bc8e.png)
Про `есть хедмин на них`, он вроде тоже против такого

Я просто не знаю, что делать с этим всем и создал пропозал как площадку. Как вариант я мог создать тему в [комнате совещаний](https://forum.taucetistation.org/c/komnata-soveshhanij), но пусть огласка будет так

**Comment by Sakuya-Izayoi** [comment]
создай

**Comment by volas** [comment]
Можете снарядить того кто банил продвигать тему на форуме.

**Comment by atik1n** [comment]
> У нас есть правила, а если админы выдумывают свои

Кстати. Это может спокойно попасть под багоюз или абуз, что у нас наказывается. Ну и обход бана тоже.
Баны часто ловят именно батл-таяры и батл-жабы и тд. Собственно почему эта ситуация и спорная.

**Comment by LudwigVonChesterfield** [comment]
мозг пересадить можно? можно

багоюз или абуз заключается в чем? ты даже это не как "Баг" зарепортил, а как пропозал, а теперь вертишься-выдумываешь

**Comment by FelixRuin** [comment]
🤔 может просто сделать это по системе конечностей? что мозг может не прижиться в новом теле и давай обратно пересаживай в родное тело

**Comment by Motzord** [comment]
Имхо, это абуз ибо пересадка головы - клонирование, а пересадка мозга из гниющего трупа это реанимация. Странно и не круто, ок?

**Comment by LudwigVonChesterfield** [comment]
Если сделать чтобы смерть мозга была по времени такой же как смерть моба, то и реанимация не будет получаться. Это совсем другой баг, и не связан с тем что предлагается тут.

**Comment by cool20141** [comment]
> мозг пересадить можно? можно
> 
> (что характерно у нас это даже описывалось как способ реанимации человека которому отрезали голову и у тебя нет тела)
> (кроме конечно пересадки самой головы)
> 
> багоюз или абуз заключается в чем? ты даже это не как "Баг" зарепортил, а как пропозал, а теперь вертишься-выдумываешь

Это позволяет обходить вайтлисты на ксеносов. И если все смогут так делать, то к чему вообще будут отдельные ксеносы за время и квенты? А, да, подобная проблема была с боргами, типа бан на синтетов, но ничто не мешало вставить в борга после раундстарта мозг забаненного. Решилось все просто запретом на такое механом. Может и тут так: запрещать людям без ВЛ влезать в ксенотела?

**Comment by wadangel** [comment]
У меня упорно создаётся ощущение, что когда-то всем было прекрасно известно, что это баг и что за его абуз будут пинать и вообще про изнасилование пересадки мозгов с реанимацией даже ольт писал на форуме в своей темке, а потом это пофиксили. Но где-то с год или чуть меньше того назад всё сломалось, наверное, нужно было ишью ещё тогда написать. В любом случае, довольно забавно, что вместо наказывания откровенного механоёбства и правилопохуизма какие-то воуты, мнения игроков или ещё что. Я понимаю, что у нас свободный и уже давно даже ни капли не ролевой сервер, но это уже совсем край. 

![image](https://user-images.githubusercontent.com/29904082/86513695-ee9b4d00-be14-11ea-86fc-fcdacb9589a1.png)

Сомнительный пруф (и очень старый, конечно):
![image](https://user-images.githubusercontent.com/29904082/86513974-1390bf80-be17-11ea-8cd8-b9a526c2393a.png)


Бонус: смешная цитата из глубины веков!
![image](https://user-images.githubusercontent.com/29904082/86513774-99137000-be15-11ea-8ea9-c15751b47283.png)


А если серьёзно, то я не понимаю, как это можно разрешать и как тем более это можно разрешать с оглядкой на то, что ксеновизоры решили сиё злодейство не регулировать. Факт необходимости каких-то знаний лорабэека для ~~ахахах отыгрыша уровня пересаживающего по приколу мозги СПУ~~ игры на ксеносах, факт того что это (вроде бы) не просто респрайты хумана, сам лор и бэк, правила отыгрыша ксеносов, правила сервера, логика и здравый смысл - всё это идёт нахуй. Очень и очень грустно. Зато запермленцы спокойно баны обходят и даже на форум жалобы катают, что никого не волнует.

~~То, что одна педаль банит за что-то, а другая не банит, должно регулироваться нормальным кодексом административным и регуляцией выше стоящей администрацией, её обучением и контролем, а не, прости г-ди, демагогией и голосованиями в дискорде.~~

**Comment by GermanSUS** [comment]
Да почему опять я то блять
