### ISSUE TITLE
Бесполезные блюспейс помидоры

### ISSUE THREAD

**Issue by FBitSafe** [TauCetiStation/TauCetiClassic#5751]

**Comment by KIBORG04** [comment]
Криво оформил.

Что бы помидоры работали, им нужна очень высокая потенция

**Comment by FBitSafe** [comment]
на сколько большая?

**Comment by KIBORG04** [comment]
Больше или равно 15

**Comment by FBitSafe** [comment]
чем её повышать?

**Comment by LudwigVonChesterfield** [comment]
Возможно стоит сделать чтобы если недостаточная потенция у фрукта до какого-либо эффекта то чтобы это как-то явно показывалось игроку

или чтобы если недостаточно потенции то рос не мутант-вариант(блюспейс помидор) а обычный (помидор)

**Comment by KIBORG04** [comment]
> Возможно стоит сделать чтобы если недостаточная потенция у фрукта до какого-либо эффекта то чтобы это как-то явно показывалось игроку
> 
> или чтобы если недостаточно потенции то рос не мутант-вариант(блюспейс помидор) а обычный (помидор)

Эффект не совсем очевидный, но он есть
`visible_message("<span class='notice'>The [name] has been squashed.</span>","<span class='moderate'>You hear a smack.</span>")`

**Comment by Sakuya-Izayoi** [comment]
Ох уж эти игроки, все им постоянно что-то должны. Уже до помидоров добрались.

**Comment by FBitSafe** [comment]
афтар дебил, не знает как работают помидоры

**Comment by KIBORG04** [comment]
Мы знаем
