### ISSUE TITLE
OOC не выключается в начале раунда, если...

### ISSUE THREAD

**Issue by Rahmanio** [TauCetiStation/TauCetiClassic#5758]
#### Подробное описание проблемы
![Screenshot_15](https://user-images.githubusercontent.com/67812445/86503117-51b0c380-bdc4-11ea-9880-472bea23e3cc.png)
Не в первый раз замечаю это, даже постоянно в ночные раунды. OOC не выключается, если написать что-то после надписи OOC has been globally disabled.
#### Что должно было произойти
OOC is disabled
#### Что произошло на самом деле
OOC работает, хотя была надпись, что его нет.
#### Как повторить
![Screenshot_16](https://user-images.githubusercontent.com/67812445/86503122-5ffedf80-bdc4-11ea-8e8b-d5503f4255bf.png)

**Comment by volas** [comment]
OOC не выключается для людей в лобби

**Comment by LudwigVonChesterfield** [comment]
А ведь если бы у нас была отдельная пометка для ООК в лобби, то такого конфуза не было бы, правда Волас?

**Comment by Zmey25** [comment]
А вот если бы у нас не выключался оок, то такого конфуза не было, да Лудук?

**Comment by Rahmanio** [comment]
Так там написано глобали мутед, просто нужно изменить надпись на более подходящую. Или так ...globaly muted...(not in lobby). Бывает же такое

**Comment by Rahmanio** [comment]
Змей правильно заметил, я давно не заходил на тау, а раньше был OOC включён всегда. Вижу написано глобали мутед, 3 месяца играл и вообще не думал об этом. 
Вот вам, так скажем, отзыв от обычного игрока.
