### ISSUE TITLE
MMI и Позитронка в Экзоскелете, нет интерфейса

### ISSUE THREAD

**Issue by Lexanx** [TauCetiStation/TauCetiClassic#5763]
#### Подробное описание проблемы
После смерти, если вытащить позитронку СПУ, и поместить её в МЕХ, тот же риппли.  У тебя не будет интерфейса.
#### Что должно было произойти
Быть интерфейс
#### Что произошло на самом деле
Нет интерфейса
#### Как повторить
Взять друга на СПУ, вытащить его позитронку, и поместить в Риппли
#### Дополнительная информация:
При попытке F12
Inventory hiding is currently only supported for human mobs, sorry.

**Comment by Lexanx** [comment]
![image](https://user-images.githubusercontent.com/61974560/86527192-3cf82c80-bea5-11ea-974a-895db905712f.png)
Help me

**Comment by Ambassadoing** [comment]
А его и не будет, держу в курсе. Что ты мозг обычный в MMI запихнёшь, что обычную позитронку, что диону в MMI - не будет интерфейса. Это более обширная проблема.

**Comment by Lexanx** [comment]
Тогда сменю заголовок

**Comment by Sakuya-Izayoi** [comment]
А какой интерфейс ожидается? (приложите скрин пожалуйста)

**Comment by Lexanx** [comment]
Думаю что любой, какой нибудь. Подойдет даже обычный. Главное что бы была возможность выбирать места на кукле. И выбор. Хелр/Харм и тд. ( такой же когда просто залез в экзоскелет)

**Comment by Lexanx** [comment]
Ахх, стандартное без куклы. Но вот оно.
![image](https://user-images.githubusercontent.com/61974560/86728887-87a8ae80-c035-11ea-96e5-0cd13ddf9757.png)
