### ISSUE TITLE
[Proposal] Выбор причесок

### ISSUE THREAD

**Issue by neonbible** [TauCetiStation/TauCetiClassic#5764]
Суть такова:

Крайне неудобно что после просмотра прически и если она тебе не подошла, то список скипает в самое начало и снова приходится искать то что тебе подходит

Предложение:

Сделать так что бы список как минимум не скипало, а запоминался последний выбор, в идеале добавить стрелочки вперед и назад в выборе прически

**Comment by LudwigVonChesterfield** [comment]
Смешно было бы сделать радиальное меню для выбора причесок, и запоминать страницу на которой был игрок

**Comment by LudwigVonChesterfield** [comment]
(Или как у барбера)

**Comment by neonbible** [comment]
> (Или как у барбера)

Да, и как в автоматах можно было посмотреть прическу, ну это в идеале конечно...

**Comment by Sakuya-Izayoi** [comment]
Временное решение: можешь нажимать на клавиатуре первую буковку из названия прически, выделение будет проходиться по всем названиям которые начинаются с этой буквы.

**Comment by LudwigVonChesterfield** [comment]
У названий часто совпадают первые буквы.
