### ISSUE TITLE
Бесконечно живые мозги и абуз их пересадки

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5765]
#### Подробное описание проблемы
После пересадки мозга можно реанимировать куклу, что абузно на уровне манкитерапии.
#### Что должно было произойти
После пересадки мозга (как и головы) куклу можно только отнести в генетику и клонировать
#### Что произошло на самом деле
Хирург при помощи манкикубов, риеталина и инструментов реанимирует гибнутых нюкеров 5 генок в стазисе, жертву конокрада кого угодно, рядом бегает генетик, тихо всхлипывая, в клонировальне повесилась мышь.
#### Как повторить
Берете пострадавшую мертвую куклу А.
Вырезаете у нее мозг
Берете куклу из мартышки Б
Вырезаете у нее мозг и отдаете повару
Пересаживаете мозги А в Б.
Ебашите дефибом.

ВЫ СОБРАЛИ ФРАНКЕНШТЕЙНА.

(А если ты вообще крутой, то копируешь гены куклы А и инжектором колишь кукле Б)
#### Дополнительная информация:
Это абуз.

**Comment by Akellazp** [comment]
Feature

**Comment by LudwigVonChesterfield** [comment]
Думаю стоит сделать следующие вещи:
- Таймер смерти у мозга вместе с куклой(или чуть-чуть позже, чтобы было небольшое окно для такого фокуса, но не вечное)
- Неприживаемость мозга, как и у других конечностей

(можно было бы сделать чтобы если у человека нет вайтлиста неприживаемость 100%)

Дополнительно прикольно было бы сделать:
- Способы показать что тот кто в теле - не таяра в теле таяры, а человек в теле таяры - чтобы у него какие-то дефекты речи были узнаваемые к примеру
- Куча смешных эффектов которые показывали бы что мозгу в теле другой расы не место - инверс контрола, клик неправильной рукой, и т.д.

**Comment by Sakuya-Izayoi** [comment]
Я пытался сделать такой таймер, но из-за обилия говнокода я столкнулся с одной проблемой: мозг-орган и мозг-итем это две разные вещи. Также мозг всунутый в разные предметы не сохраняется, а создаётся заново.

Для начала нужно сделать чтобы все органы были итемами со спрайтами и в результате хирургических операций они не просто делитались, а выкладывались в лок холдера. 

Далее нужно сделать чтобы этот мозг-итем не делитался при всовывании в предмет с перемещением мозга-моба, а постоянно в нём находился. Ну и в отрубленной голове этот мозг должен постоянно находиться.

Ну и потом в этот мозг-итем нужно навесить таймер или ещё что.

Это так, напоминалка для меня, до тех времён, когда я займусь этим. Если желаете сделать что либо из вышеперечисленного, то я буду рад.
