### ISSUE TITLE
При помощи апперкота можно ходить сквозь стены

### ISSUE THREAD

**Issue by FatFatFat1** [TauCetiStation/TauCetiClassic#5767]
#### Подробное описание проблемы
При помощи апперкота я ходил сквозь стены
#### Что должно было произойти
Я не должен ходить сквозь стены
#### Что произошло на самом деле
Я ходил сквозь стены
#### Как повторить
Без понятия
#### Дополнительная информация:
Я незнаю что произошло , в один момент я совершал апперкот ,но вместо того что отлететь ,моя жертва "встала" на месте и чуть чуть сьехала (Изначально жертва лежала), затем я смог войти и выйти из стены рядом,при этом я не мог войти в пустой тайл рядом(как-будто стена и пол поменялись местами). Это было в раунде #34731 ,в самом конце , в капитанской рубке шаттла , персонажем Rick-ом Shorts-ом.

**Comment by Akellazp** [comment]
Скорее всего было как со мной, тоесть съезжает твой спрайт, но колизия (если ее так можно назвать) остается там где ей положено

**Comment by Motzord** [comment]
Уже нельзя, пофикшено
