### ISSUE TITLE
Черно-белый фильтр и госты

### ISSUE THREAD

**Issue by CeUvi** [TauCetiStation/TauCetiClassic#5768]
#### Подробное описание проблемы
Если гостануться во время того, как на тебя наложен черно-белый фильтр, он останется до самого рестарта.
#### Что должно было произойти
Нормальное зрение
#### Что произошло на самом деле
А где цвета
#### Как повторить
Гостануться из тела когда кукла спит, или валяется в крите.

**Comment by Sakuya-Izayoi** [comment]
Так со всеми фильтрами
