### ISSUE TITLE
Постоянные кражи титров

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5782]
#### Подробное описание проблемы
В последнее время в конце раундов стали пропадать титры
#### Что должно было произойти
Есть титры
#### Что произошло на самом деле
Нет титров
#### Как повторить
Сыграть несколько раундов
#### Дополнительная информация:
Воксы суки верните титры

**Comment by T6751** [comment]
это началось сегодня?

**Comment by Akellazp** [comment]
Несколько дней уже, если не больше. Пропадают часто, но не каждый раунд

**Comment by volas** [comment]
нужен айди раунда

**Comment by Akellazp** [comment]
34809

**Comment by Akellazp** [comment]
34859

**Comment by Akellazp** [comment]
34864

**Comment by Motzord** [comment]
34864

**Comment by Akellazp** [comment]
34867

**Comment by Akellazp** [comment]
34887

**Comment by Akellazp** [comment]
34889

**Comment by volas** [comment]
``null.key in ticker.dm:488`` https://github.com/TauCetiStation/TauCetiClassic/commit/d8029d336acf525d8f1c0bf2d5c6418d1e05edec

@T6751 посмотришь? (вообще может следовало бы ``key_name()`` использовать в таких местах)
