### ISSUE TITLE
При насильном надеании шапки на другую куклу, ты бьешь ее в ебало

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5783]
#### Подробное описание проблемы
При насильном надевани шлема на голову космонавтика (клик шапкой целясь в голову) после прогрессбара твоя кукла бьет другой кукле в табло
#### Что должно было произойти
Надел шапку, все довольны
#### Что произошло на самом деле
Линн Янг вместе с модной шапкой растамана получила в ебучку
#### Как повторить
Попытайтесь вежливо надеть на кого то шапку используя клик на голову пациента

**Comment by Akellazp** [comment]
> вежливо надеть

по-моему ты что-то перепутал

**Comment by Motzord** [comment]
> > вежливо надеть
> 
> по-моему ты что-то перепутал

 все равно удар в ебучку я считаю лишним

**Comment by LudwigVonChesterfield** [comment]
@Sakuya-Izayoi 

Всё работает как задумано?

**Comment by Sakuya-Izayoi** [comment]
Да. Я специально оставил нанесение урона. Это интент харм.
