### ISSUE TITLE
[Proposal] Выпилить колокол у священика.

### ISSUE THREAD

**Issue by Drakon341** [TauCetiStation/TauCetiClassic#5784]
У нас есть колокол,зачем он? Священник просто спамит им,и делает всякие анонсы.А станция трясётся так что как-будто взорвётся. 
Предложение:
Вырезать к чертям этот колокол.

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/kolokol-u-svyashhenika/19697/6
