### ISSUE TITLE
Держа на мушке нельзя стрелять в цель

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5790]
#### Подробное описание проблемы
Раньше можно было повесить мушку  любую куклу, кликнть по кукле и произести выстрел
#### Что должно было произойти
Повесил мушку, стрельнул
#### Что произошло на самом деле
Повесил мушку, хочешь стрельнуть — снимаешь мушку или недовольно урчишь и ждешь пока цель делает какое-нибудь действие
#### Как повторить
Попытайтесь повесить на куклу мушку и выстрелть в нее

**Comment by T6751** [comment]
Не могу воспроизвести. Вероятно проблема больше неактуальна

**Comment by KIBORG04** [comment]
Я вроде пофиксил, да
