### ISSUE TITLE
Брейндамаг на СПУ не чинится. Операции по ремонту внутренних органов не помогают

### ISSUE THREAD

**Issue by Lexanx** [TauCetiStation/TauCetiClassic#5795]
#### Подробное описание проблемы
Брейндамаг на СПУ не лечится
#### Что должно было произойти
Вылечится брейндамаг на СПУ
#### Что произошло на самом деле
Брейндамаг не вылечился
#### Как повторить
Имплантировать СПУ лояльностью в монитор, и попытаться исцелить полученный урон по мозгу
#### Дополнительная информация:
Операции по починке внутренних органов не помогают

**Comment by Shudyn** [comment]
У них позитронка в теле, а не в голове.

**Comment by Lexanx** [comment]
В том и дело, мне доводилось получить лояльность в монитор. И потом только с помощью админ магии смог починить брейндамаг. Операции не помогали
