### ISSUE TITLE
Лярва не эволюционирует в теле заражённого

### ISSUE THREAD

**Issue by PirogSema** [TauCetiStation/TauCetiClassic#5799]
#### Подробное описание проблемы
Когда прогресс достигает 200/200 лярва не вылезает из заражённого.
#### Что должно было произойти
Лярва вышла на свет, убив заражённого.
#### Что произошло на самом деле
Лярва продолжает сидеть.
#### Как повторить
Заразить кого-нибудь за фейсхаггера, возможно, сделав что-то, что вызовет этот баг.
#### Дополнительная информация:
Я не понимаю из-за чего конкретно это происходит, если вы что-то знаете или у вас есть догадки, мысли — сообщайте, потому что у других, возможно, всё хорошо.

**Comment by T6751** [comment]
Лярва продолжала спать же, когда прогресс достиг  200/200? через некоторое время должна была проснуться и появиться действие вылезти

**Comment by 4310V343k** [comment]
Всё в порядке. Надо ждать 300 тиков, что примерно 10 минут реального времени

**Comment by PirogSema** [comment]
> Лярва продолжала спать же, когда прогресс достиг 200/200? 

Да.

**Comment by T6751** [comment]
прогресс в статусе отображает взрослость **лярвы**, а не прогресс, когда будешь готов вылезти.
Внутри зараженного ты на самом деле **эмбрион** (не лярва) и ты проходишь свои пять этапов (stage) "роста", которые не отображаются в статусе и никак не зависят от этого прогресса в статусе. На 5-ом этапе появляется кнопка вылезти и ты выходишь лярвой взрослой на все 200, что означает готовность к эволюции. 

Думаю нужно будет добавить в status информацию об этапах эмбриона.

**Comment by 4310V343k** [comment]
> (и посмотреть, действительно ли так задумывалось, что параллельно идет рост лярвы и этапы эмбриона)

Нет, так определенно не задумывалось. Кстати, почему лярва из фейсхаггера, посаженного алиеном, бёрстается быстрее лярвы из феймсхаггера, подконтрольного игроком.
Звучит, как плохой баланс
