### ISSUE TITLE
Слишком мощный термит.

### ISSUE THREAD

**Issue by Shudyn** [TauCetiStation/TauCetiClassic#5809]
Оставлю ишуй, чтобы не забыть.

#### Подробное описание проблемы
Укрепленная стена, которая не разрушается от горящего форона с температурой 10000К
@ 
5 миллилитров горящего термита 2500К достаточно, чтобы срезать укрепку за 10 секунд.

Термит - ноубрейн быстрая разборка укрепок с простым рецептом у химиков.

#### Что должно было произойти
Термит укрепку либо дольше жжет (секунд хотя бы 30, или даже 60),
либо требовать литры термита, либо все сразу. 

#### Что произошло на самом деле
Термит сжигает укрепку за 10 секунд, требуя >= 5 миллилитров (с дроппера) термита.

#### Как повторить
Налить в бикер 5 единиц термита, вылить на укрепку и поджечь. Через 10 секунд образовывается проход в любую хай секурити зону.

#### Дополнительная информация:
Прекратим раш малфа за 60 секунд с термитом и метал фоумом.

**Comment by Motzord** [comment]
Термит занерфили в говно, закрывайте

**Comment by KIBORG04** [comment]
а щас как?

**Comment by Motzord** [comment]
> а щас как?

а щас укрепстена при 30 термита жарится две минуты, чтобы жарило быстрее надо больше термита
