### ISSUE TITLE
Борг не может открыть канистру

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#581]
#### Подробное описание проблемы

Борг не может открыть или закрыть канистру, стоя вплотную к ней
#### Что должно было произойти

Клапан должен был открыться или закрыться
#### Что произошло на самом деле

Ничего
#### Как повторить

Быть боргом и найти канистру
#### Дополнительная информация:

Нерфоцирк перешел все границы.

**Comment by ZVee** [comment]
Так и задумано.

**Comment by DeadOberst** [comment]
Злодей, это же нужная фича.
Как тритору дрону выпустить плазму?
Как боргу заполнить воздухом отсек при поврежденной вентиляции?
У синтетов же должны быть хоть какие то элементарные манипуляторы для работы со стандартизированными канистрами, как и раньше.

**Comment by ZVee** [comment]
Дроны не могут таскать/пулить такие объекты, а выпустить так, чтоб не получить бан - у нас мало кто может.
Трубы провести могут.
Чем меньше заменяют людей - тем лучше, и "За" там не только с моей стороны было, но не помню уже конкретно.

**Comment by Raschert0** [comment]
Зве, так о больших дронах а не о мейнтенанс.

**Comment by kopoba** [comment]
Возможность открывания канистр синтетами явно нужна.

**Comment by Skippeer12** [comment]
Б-Баланс
