### ISSUE TITLE
Зависание воутов

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5811]
#### Подробное описание проблемы
Воут может зависнуть и бесконечно продолжаться с таймером в 120 секундах
#### Что должно было произойти
Отчет до конца воута пошел
#### Что произошло на самом деле
Отчет до конца воута не пошел

**Comment by 4310V343k** [comment]
Почему-то я уверен, что это дубликат ишуй

**Comment by T6751** [comment]
#5709

**Comment by T6751** [comment]
Является ли всё ещё актуальным?
