### ISSUE TITLE
Борги не могут пользоваться фабрикаторами роботехов.

### ISSUE THREAD

**Issue by Shudyn** [TauCetiStation/TauCetiClassic#5815]
#### Подробное описание проблемы
При попытке боргом взаимодействовать с фабрикатором, открывается только менюшка фабрикатора: клики на кнопки внутри ничего не меняют.

#### Что должно было произойти
Борг может пользоваться фабрикатором.

#### Что произошло на самом деле
Борг может только смотреть, как пользуются фабрикатором.

#### Как повторить
Попытаться попользоваться фабрикатором.

#### Дополнительная информация:
Не знаю, если так и задизайнено, но хотя бы надо говорить боргу, что он не может взаимодействовать с фабрикатором по причине *чего-нибудь*.

**Comment by T6751** [comment]
#543
