### ISSUE TITLE
Не меняются значения датчика атмосферной тревоги

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#583]
#### Подробное описание проблемы
Невозможно менять значения газов и давления, при которых срабатывает тревога

#### Что должно было произойти
Значения должны были поменяться

#### Что произошло на самом деле
Значение осталось прежним

#### Как повторить
Разблокировать панель воздушной тревоги и попробовать поменять значения

#### Дополнительная информация:
Не пора ли перейти на такой же интерфейс как у АПЦ и химдиспенсера?
А то окошко постоянно скачет.
http://i.imgur.com/nD26HOJ.png

**Comment by igigin** [comment]
Дубляж вот этого #573.
