### ISSUE TITLE
Градиент воксов

### ISSUE THREAD

**Issue by 4310V343k** [TauCetiStation/TauCetiClassic#5831]
#### Подробное описание проблемы
Если у хумана, попавшего на вокса, был градиент, то и у вокса появится градиент
#### Что должно было произойти
Нормальная расцветка
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/56449763/87579598-d6fa7900-c6de-11ea-9e6e-be7e7031a355.png)

#### Как повторить
Смотри выше
#### Дополнительная информация:
Раунд№34971

**Comment by T6751** [comment]
> Если у хумана, попавшего на вокса,

поподробнее

**Comment by 4310V343k** [comment]
Режим воксов
