### ISSUE TITLE
Посадка на свой стул грабом.

### ISSUE THREAD

**Issue by Ydaater** [TauCetiStation/TauCetiClassic#584]
#### Подробное описание проблемы

Когда ты сидишь на стуле, можно посадить на свой стул другого человека, взяв его в grab. После этого ты не можешь встать со стула, ты прикован к нему. 

#### Что должно было произойти
Ты не должен был посадить на свой стул другого человека. Ты должен иметь возможность встать со стула.

#### Что произошло на самом деле

Человек, которого я посадил на стул спокойно на него сел, а потом встал и ушел, а я нет. 

#### Как повторить

Сесть на стул, использовать grab на человеке рядом, нажать на стул на котором сидишь, посадить человека, истерить на тему что больше не можешь ходить.

#### Дополнительная информация:

Не проверено, может ли тебе помочь встать другой человек

**Comment by DeadOberst** [comment]
Я как то застревал так, когда садился на стул, держа Яна.
Другой человек отлепить может, но там тоже что то с кравлом, грабом, столом и гаечным ключем, в общем все сложно.

**Comment by Dennok** [comment]
> гаечным ключем
Удаяя предмет к кторому привязывали/садили ты автоматом отвязываешся.
