### ISSUE TITLE
Превращение Яна в обычного корги

### ISSUE THREAD

**Issue by Rahmanio** [TauCetiStation/TauCetiClassic#5844]
#### Подробное описание проблемы
Играю на Яне, картинка зависла, перезахожу, превращаюсь в обычного корги, который не понимает людей. Вообще ничего не умеет.
#### Что должно было произойти
Ничего.
#### Что произошло на самом деле
Превращение в моба, священник может такого же заспавнить.
#### Как повторить
Перезайти в игру, играя за Яна.
#### Дополнительная информация:
Так как у меня способность стояла нюх, то я не мог ничего делать, только нюхать, снизу панелей не было.
Спас меня администратор FrankWilson, он сказал госнуться, потом он меня защитспавнил в Яна. Но на этом проблема была не решена, я не мог встать, был будто в отключке, благо другие игроки меня пообнимали, проблема решилась.

**Comment by T6751** [comment]
#3855

**Comment by cool20141** [comment]
Кста, у меня тоже иногда картинка зависает, какого хуя, кто эту хуйню сделал? Раньше такого не было(Если переключить на Text в Icons, а потом назад, то можно заметить, что персонаж-то двигается). Не писал отдельный ишью, потому что не ебу, как воспроизвести, да и мб это вообще с моей стороны проблемсы, но короче проблема есть

**Comment by Rahmanio** [comment]
> #3855

Очень интересно, за год так и не пофиксили(((

**Comment by Rahmanio** [comment]
#3855 закрыли, там проблема почти такая же, как и у меня, но на Яне я давно не играл. Стоит закрыть ишью, уже неактуально.
