### ISSUE TITLE
(СПУ Болеют новыми вирусами с ивентов)

### ISSUE THREAD

**Issue by Lexanx** [TauCetiStation/TauCetiClassic#5846]
#### Подробное описание проблемы
Снова СПУ, и снова проблемы с болезнями. Удалось заразится простудой, и без админмагии, не вылечится от неё.
#### Что должно было произойти
СПУ не болеют
#### Что произошло на самом деле
На меня накашлял тестовик, я начал шмыгать (Кулерами видимо)
#### Как повторить
Наверное это вирус от ивента.

#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/61974560/87855578-fcc39000-c921-11ea-9f97-741c38d6615b.png)
![image](https://user-images.githubusercontent.com/61974560/87855586-0baa4280-c922-11ea-8dbb-86137be5c480.png)
____________
Еще так же писал в марте про вирус мага. (Магитис кажется) От него так же нет лечения

**Comment by GermanSUS** [comment]
А может он кулерами шмыгает?

**Comment by Lexanx** [comment]
Вообщем снова, СПУ и Вирусы. Довелось мне опять заразиться и
![image](https://user-images.githubusercontent.com/61974560/87912243-b2ebbe80-ca75-11ea-9d22-667d7a302c09.png)

**Comment by Lexanx** [comment]
Но я не знаю, админмагия это была, или я нашел баги которые лечат другие баги. Но я нашел единственный способ пить за СПУ.
А это кола из автоматов, и залил туда 20 унций железа, и выпил.
![image](https://user-images.githubusercontent.com/61974560/87912426-09f19380-ca76-11ea-9e0f-7504be6e02dd.png)

памагити, я респрайт хумана

**Comment by 4310V343k** [comment]
нет. хуман это респрайт спу

**Comment by T6751** [comment]
>  (СПУ Болеют новыми вирусами с ивентов) 

А не с ивентов они болеть не могут уже значит?

**Comment by T6751** [comment]
#4808

**Comment by Lexanx** [comment]
> А не с ивентов они болеть не могут уже значит? да?

Да, с тех что делает вирусолог. СПУ не болеет.

**Comment by T6751** [comment]
(если что, есть еще вирусы в бутылках, которые тебя могут заразить, не только вирусолог)

**Comment by Lexanx** [comment]
> (если что, есть еще вирусы в бутылках, не только вирусолог. и вот они тоже могут заразить спу как-то)
> 
> ```dm
> /obj/item/weapon/reagent_containers/glass/bottle/wizarditis/atom_init()
> 	. = ..()
> 	var/datum/disease/F = new /datum/disease/wizarditis(0)
> 	var/list/data = list("viruses"= list(F))
> 	reagents.add_reagent("blood", 20, data)
> ```
Это вроде и есть магитис, о котором я говорил

**Comment by LudwigVonChesterfield** [comment]
@Lexanx отдельным багом напиши как залил в СПУ жидкость

**Comment by Lexanx** [comment]
@LudwigVonChesterfield готово
