### ISSUE TITLE
null в законах у ПИИ

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#5848]
#### Подробное описание проблемы
У ПИИ есть директива "служи своему хозяину", однако при прожатии педальной кнопки "показать законы синтетов выводится null
#### Что должно было произойти
Законы ПИИ не выводятся по нажатию педальной кнопки или выводятся директивы
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/45365635/87885483-b2700b00-ca16-11ea-815c-b7da59992a22.png)

#### Как повторить
Потыкайте Show AI Laws при активном ПИИ

**Comment by 4310V343k** [comment]
As intended
