### ISSUE TITLE
Rainbow cap не имеет скина.

### ISSUE THREAD

**Issue by Ydaater** [TauCetiStation/TauCetiClassic#585]
#### Подробное описание проблемы
rainbow cap не отображается на голове персонажа. 
#### Что должно было произойти
При одевании rainbow cap на голове должна была отобразиться кепка.
#### Что произошло на самом деле
На голове не появилось головного убора.
#### Как повторить
Найти rainbow cap в техах, одеть, удивляться пустой макушке. 
#### Дополнительная информация:
Кепка есть в инвентаре, её видно при examine, но её не видно на голове.

**Comment by Skippeer12** [comment]
Если флипнуть её, то спрайт появляется нормально.
