### ISSUE TITLE
[Proposal] Возможность положить мышь в мешок для мусора

### ISSUE THREAD

**Issue by Rahmanio** [TauCetiStation/TauCetiClassic#5851]
#### Подробное описание проблемы
На сервере нельзя убирать МЁРТВЫХ мышей в мешок для мусора, хоть это очень логичное действие, вместо того, чтобы перетаскивать по одной мыши до мусорки
#### Что должно было произойти
Хотел положить - вышло
#### Что произошло на самом деле
Хотел положить - не вышло
#### Как повторить
Никак(
#### Дополнительная информация:
Ваш уборщик Smitt Rahmanov, который заходит за уборщика раз в месяц.

**Comment by cool20141** [comment]
И как за мышек теперь грифонить, оставляя кучу трупов, заставляя хоть кого-то на станции работать, убирая их трупики?

**Comment by Tiarv** [comment]
Но можно брать в руки, сажать на голову и в сумку.

**Comment by cool20141** [comment]
Это живых

**Comment by Rahmanio** [comment]
> И как за мышек теперь грифонить, оставляя кучу трупов, заставляя хоть кого-то на станции работать, убирая их трупики?

Грифа не будет, я всё вижу. Ограничиваем грифонеров механом! Делаем игру за уборщика проще и интереснее! Слава Тау Китти.

**Comment by Rahmanio** [comment]
> Ок, ограничивай

Пока что не знаю, как, вот если бы мне кто помог разобраться. Я до сих пор не сделал репозиторий или как там его.

**Comment by cool20141** [comment]
https://wiki.taucetistation.org/Git

**Comment by cool20141** [comment]
В лс дискорда

**Comment by Rahmanio** [comment]
Фичу добавили
