### ISSUE TITLE
Prescription sunglasses

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#586]
#### Подробное описание проблемы
Черные очки с коррекцией зрения не имеют уникального названия.
#### Что должно было произойти
Очки должны называться prescription sunglasses.
#### Что произошло на самом деле
Называются просто sunglasses, как и обычные черные.
#### Как повторить
Установить в настройках персонажа необходимость в ношении очков и зайти за капитана или квартермейстера.
#### Дополнительная информация:
Обычные черные очки не корректируют зрение.

**Comment by Skippeer12** [comment]
Они и не должны. Хотя можно такие впилить в РнД.
Хочешь себе дебафы - страдай.

**Comment by Damirrus1** [comment]
У этого еще есть, агента АВД)))
