### ISSUE TITLE
[Proposal] [Map] Cargo Bay request console недоступен грузчикам

### ISSUE THREAD

**Issue by Tiarv** [TauCetiStation/TauCetiClassic#5866]
#### Подробное описание проблемы
Cargo Bay request console находится в кабинете КМа и недоступна грузчикам в его отсутствие. Для сравнения можно посмотреть на Бриг - там есть отдельная личная Request console в кабинете HoS и общая Security request console  в комнате совещаний. Возможно, в Карго следует сделать так же?

#### Что должно было произойти
Консоль должна находиться в Cargo Office.

#### Что произошло на самом деле
Консоль находится в кабинете Quartermaster.

#### Как повторить
Зайти в игру за карготеха или КМа

#### Дополнительная информация:
Box Station

**Comment by LudwigVonChesterfield** [comment]
у каждого главы так-то отдельно своя консоль вроде есть, и отдельная на отдел

**Comment by Tiarv** [comment]
Вот только консоль отдела в карго находится в кабинете КМа. А у КМа своей консоли нет.

**Comment by waryfost** [comment]
Почему предложение всё ещё открыто? Проблемы вроде нет более.

**Comment by KIBORG04** [comment]
А разве она когда-то была?

**Comment by Tiarv** [comment]
Хорошо закрыли, а консоль-то где? А консоль все еще в кабинете у КМа.

**Comment by Tiarv** [comment]
![image](https://user-images.githubusercontent.com/41039312/117280513-583c1b80-ae6b-11eb-9bbe-57bc206fe24b.png)

**Comment by Tiarv** [comment]
Кто-то набивает KPI по закрытию ишуй, видимо.

**Comment by KIBORG04** [comment]
Бля, ЭТА консоль, тогда открываю. Тип, этой же хренью все равно никто не пользуется

**Comment by CeUvi** [comment]
а зачем вообще нужна эта консоль

**Comment by Tiarv** [comment]
Заказы удаленно оформлть

**Comment by Sakuya-Izayoi** [comment]
> Заказы удаленно оформлть

не то чтобы у нас есть КПК и радио...

**Comment by Tiarv** [comment]
КПК не позволяет послать сообщение в отдел, только одному конкретному человеку.
Ни КПК, ни радио не являются официальным каналом связи по которому заказываются вещи в карго. А эта консоль является.
