### ISSUE TITLE
Сонливые фамилиары Священика.

### ISSUE THREAD

**Issue by Fugazz** [TauCetiStation/TauCetiClassic#5874]
#### Подробное описание проблемы
Иногда случается так, что призванный священником фамилиар не может двигаться. Как я понял, происходит это после того, как игрок за фамилиара перезаходит в игру. Возможно, не только по этой причине, это неизвестно, ведь такие случаи были и ранее. Через фамилиар становиться возможным проходить, не двигая его. Грабать и пуллить его все ещё возможно.
#### Что должно было произойти
Контроль над мобом без дебафов
#### Что произошло на самом деле
Эфект Слепоты,глухоты,и Сна в общем.
#### Как повторить
Перезайти в бион и на Сервер.
#### Дополнительная информация:
Мобом был Попугай.

**Comment by T6751** [comment]
Кажется, всё это связано:
#615
#3361
#3855

**Comment by Fugazz** [comment]
Видимо это проблема ВСЕХ Симпл мобов..

**Comment by KIBORG04** [comment]
Я когда делал божка встретил эту проблему при перезаходе. Я, вроде как, в `/Login() ` это фиксил. Но это довольно костыльно.
