### ISSUE TITLE
Маска воксов не фильтрует

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5876]
#### Подробное описание проблемы
Когда вокс находится внутри чего-либо (шкаф/мех/слипер/сканер и тд) то маска отказывается фильтровать воздух и ты дышишь кислородом, получая токсины
#### Что должно было произойти
Маска продолжает фильтровать
#### Что произошло на самом деле
Маска отказывается фильтровать
#### Как повторить
Залезть за вокса в шкаф, мех и тд

**Comment by Akellazp** [comment]
@Coiscin

**Comment by GermanSUS** [comment]
Я писал ему по этому поводу. Он ответил что так работает механ и  с этим ничего не поделать.

Так же воксы задыхаются от использования хамелеон прожектора.

**Comment by Akellazp** [comment]
Это баг а не механ

**Comment by CeUvi** [comment]
> Это баг а не механ

механ удаляет вещи когда ты заходишь в шкаф/слипер/мех/ещё куда-нибудь

**Comment by GermanSUS** [comment]
#5939 Наверняка решил эту проблему

**Comment by LudwigVonChesterfield** [comment]
@CeUvi пожалуйста не говори если не знаешь

В human/Life хендлится вдох в handle_breath, там вероятно две проверки
Первая проверяет на то находишься ли ты внутри чего-то
Вторая на то есть ли на тебе маска

Видимо логика этих проверок некорректная, из-за чего когда ты находишься внутри чего-то маска не проверяется
