### ISSUE TITLE
Беды вокса-священника

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5878]
#### Подробное описание проблемы
Вокс-священник спавнится без одежды изза специей рестрикта и без пда с картой(изза отстутствия одежды)
#### Что должно было произойти
Заспавнился, все вещи на месте
#### Что произошло на самом деле
Спавнишься голый, без карты и пда
#### Как повторить
Зайти за вокса-священника

**Comment by Akellazp** [comment]
@Coiscin

**Comment by Sosicin** [comment]
спасибо спрайтерам, которые не доделывают свои пр и в итоге случается это...…..

**Comment by T6751** [comment]
Такая же проблема у воксов-ботаников и воксов-барменов. Возможно и еще какие-то профы
Кажется, воксам униформу нужно добавлять сюда:
icons/mob/species/vox/uniform.dmi
