### ISSUE TITLE
Баг отображения крайней трубы под полом при скинаровании сканером.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#589]
#### Подробное описание проблемы

Края трубы не видно при сканировании сканером.
#### Что должно было произойти

Должен быть виен ее "призрак".
#### Что произошло на самом деле

Ничего.
#### Как повторить

Просканировать крайнюю трубу.
#### Дополнительная информация:

![tau ceti station 2016-09-15 145322](https://cloud.githubusercontent.com/assets/7734424/18596916/30dd0408-7c54-11e6-8002-a7eeb77fa370.png)
![tau ceti station 2016-09-15 145310](https://cloud.githubusercontent.com/assets/7734424/18596923/3b3a2e76-7c54-11e6-802e-d6170176739d.png)

**Comment by Skippeer12** [comment]
![image](https://user-images.githubusercontent.com/18488106/35793428-3d413418-0a5a-11e8-9122-a1703892ce79.png)

Новый атмос всё починил.
