### ISSUE TITLE
The station wasn't evacuated or no one escaped!

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5890]
#### Подробное описание проблемы
При прибытии шатла на цк в титрах отображается что никто не покинул станцию
#### Что должно было произойти
Показывается сколько человек улетело
#### Что произошло на самом деле
The station wasn't evacuated or no one escaped!
#### Как повторить
Улететь на шатле конца смены на цк и посмотреть титры
#### Дополнительная информация:
Раунд 35263

**Comment by Tiarv** [comment]
Консистентно не воспроизводится, но в последнее время нестыковки в титрах появляются чаще чем обычно. Некоторые раунды считаются, на первый взгляд, корректно, а в некоторых - вплоть до "no one escaped" при относительно заполненном шаттле. Я помню раунд в котором я в титрах был помечен как выполненная тритором цель на убийство, хотя я в течении раунда не умирал и улетел на шаттле (номера не будет).

**Comment by volas** [comment]
```
[11:30:59] TM: 5575 5726 5793 5847
...
[13:30:22] Cannot read null.stat in wizard.dm:215 :
proc name: declare completion (/datum/game_mode/wizard/declare_completion)
  source file: wizard.dm,215
  usr: null
  src: wizard (/datum/game_mode/wizard)
  call stack:
wizard (/datum/game_mode/wizard): declare completion()
Ticker (/datum/subsystem/ticker): declare completion()
Ticker (/datum/subsystem/ticker): fire(0)
Ticker (/datum/subsystem/ticker): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```
Где-то ссылка на визарда в list/wizards не почистилась
https://github.com/TauCetiStation/TauCetiClassic/blob/33ce1e3e49e2ed65d150c7a91c183f9b03ba852f/code/game/gamemodes/wizard/wizard.dm#L215
