### ISSUE TITLE
Зарплата АВД в реву

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5899]
#### Подробное описание проблемы
Во время ревы зарплата авд тоже снижается 
#### Что должно было произойти
Авд остается при своих деньгах
#### Что произошло на самом деле
Авд как лох с пониженной зарплатой
#### Как повторить
Быть авд в реву
#### Дополнительная информация:
Нужно вынести авд куда-то отдельно, ведь он не обычный персонал, но и не глава

**Comment by 4310V343k** [comment]
Напомню что рева это провокацие со стороны синдикека

**Comment by Akellazp** [comment]
> Напомню что рева это провокацие со стороны синдикека

Рева это не провокация со стороны синдиката, просто агенты начинают свою активность в удобно подвернувшийся случай со снижением зарплат

**Comment by Ahion** [comment]
Странно что она снижается, я добавлял АВД в исключение. Я посмотрю
