### ISSUE TITLE
Аспект Mortem не позволяет делать кровь из воды

### ISSUE THREAD

**Issue by BiQndy** [TauCetiStation/TauCetiClassic#5901]
#### Подробное описание проблемы
При тыкании по вотертанку библией с аспектом Mortem должна была появиться возможность превратить воду в кровь, как гласит вики
![opera_9c8t3y88Fe](https://user-images.githubusercontent.com/43725089/89095432-9edd8080-d3d6-11ea-920a-f26f58e5dfac.png)

#### Что должно было произойти
Превращение воды в кровь
#### Что произошло на самом деле
Ничего
#### Как повторить
Зайти за священника, выбрать Mortem, не смочь делать кровь для "Святых земель"

**Comment by Ro2tCrab** [comment]
**Проверил на втором сервере*

_Что должно было произойти_

**Comment by KIBORG04** [comment]
В коде все норм. Мб, ты тыкал, но не имел маны?

**Comment by BiQndy** [comment]
Я без маны тыкал, да, но святую воду мог делать без маны

**Comment by KIBORG04** [comment]
Щас вики обновлю и напишу, что в таких реакциях нужна мана. Иначе ниче не увидишь

**Comment by BiQndy** [comment]
Ну в таком случае вопрос решён.

**Comment by KIBORG04** [comment]
Если не сложно, можешь проверить на локалке, работает ли кровь? Я только к вечеру смогу проверить.

**Comment by KIBORG04** [comment]
А, ок

**Comment by BiQndy** [comment]
да, проверю
