### ISSUE TITLE
EngiBorg не может настроить доступ для платы шлюза

### ISSUE THREAD

**Issue by Ro2tCrab** [TauCetiStation/TauCetiClassic#5903]
#### Подробное описание проблемы
Инженерный борг не способен настроить доступ у платы шлюза своей роборукой, но самый обычный дрон способен!
#### Что должно было произойти
Борг должен был способен открыть меню настройки платы и менять доступ
#### Что произошло на самом деле
Использование платы в роборуке не даёт доступа к меню платы
#### Как повторить
Взять плату шлюза в роборуку борга и попытаться открыть меню платы
#### Дополнительная информация:
Инженерный дрон способен настроить плату :|

**Comment by AirBlack** [comment]
я думал это by design, чтобы емагнутые/батюшкины борги не арбузили доступы
