### ISSUE TITLE
Прокрутка чата колёсиком мышки не работает

### ISSUE THREAD

**Issue by NeOchenLord** [TauCetiStation/TauCetiClassic#5913]
#### Подробное описание проблемы
Не работает прокрутка чата колёсиком мышки

#### Что должно было произойти
При прокрутке колёсика мышки чат двигается вверх и вниз

#### Что произошло на самом деле
Ничего

#### Как повторить
Зайти на сервер и попробовать прокрутить чат колёсиком мыши

#### Дополнительная информация:
Временно (на 10-15 секунд) исправляется, если открыть и покрутить меню смайликов. Ломается, если нажать или выделить чат

**Comment by CeUvi** [comment]
Ломается когда нажимаешь или выделяешь что-то в чате.

**Comment by Fugazz** [comment]
Когда нажимаешь на Сообщение,и крутишь роликом мыши,Сообщение начинает двигатьСя на 1 пикСель вверх и вниз.
