### ISSUE TITLE
Сломанные УИ

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5914]
#### Подробное описание проблемы
Сломанные уи
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/47355061/89127050-359f5f80-d4f3-11ea-9c0f-f6b0f03227b9.png)
![image](https://user-images.githubusercontent.com/47355061/89127056-464fd580-d4f3-11ea-9262-8bc708979002.png)
![image](https://user-images.githubusercontent.com/47355061/89127060-4e0f7a00-d4f3-11ea-9334-e74984d0a4da.png)
![image](https://user-images.githubusercontent.com/47355061/89127248-c75b9c80-d4f4-11ea-8948-cf8c584ce20a.png)

**Comment by T6751** [comment]
А что в них сломано?

**Comment by cool20141** [comment]
Белая темка мб, глаза убивает

**Comment by T6751** [comment]
А разве до этого не была белая тема?

**Comment by cool20141** [comment]
Не, там красивая нт-тема была

**Comment by T6751** [comment]
Это, как я понимаю, после перехода на использование datum/browser вместо <<
Не уверен о какой красивой нт теме идет речь

**Comment by Akellazp** [comment]
Раньше они все выглядели по-другому

**Comment by T6751** [comment]
Они теперь выглядят по-другому, потому что теперь используют browser датум, вместо прямого вывода html
Новый стиль, благодаря датуму. (Это не баг)
И если кнопки работают, то заголовок "Сломанные УИ" я считаю некорректным. 
Если смущает новый стиль, то есть, то что теперь у окон есть заголовок, другой шрифт и у кнопок стиль, то так и написали бы сразу. Но это не баг. Это browser датум

|Было|Стало|
|-|-|
|![20200802 213146](https://user-images.githubusercontent.com/66636084/89129649-9b95e200-d507-11ea-8133-701cafc43dd1.png)| ![oof](https://user-images.githubusercontent.com/47355061/89127056-464fd580-d4f3-11ea-9262-8bc708979002.png) |

**Comment by T6751** [comment]
#2966 
Прямой вывод html заменили на browser датум, а люди думают, что УИ сломался, ууф

**Comment by cool20141** [comment]
Ок, мы поняли, для этого хватило бы и 1 коммента, а не 3х

**Comment by cool20141** [comment]
И да, два раза выводить "Noticeboard"–вот сломанное(А раз перешли на браузер, то сделайте темную темку пж, чтоб все смотрелось в едином формате)

**Comment by volas** [comment]
Лучше проблемы с переходом на датум отдельными ишью.
