### ISSUE TITLE
Сломался текст в книжечках, русский видимо

### ISSUE THREAD

**Issue by neonbible** [TauCetiStation/TauCetiClassic#5915]
#### Подробное описание проблемы
Иероглифы вместо букв
#### Что должно было произойти
Русский или около того текст
#### Что произошло на самом деле
Иероглифы
#### Как повторить
Почитать книги

**Comment by cool20141** [comment]
![image](https://user-images.githubusercontent.com/53309265/89128261-3937e400-d4fd-11ea-8243-e20716d18c86.png)
Это фича

**Comment by volas** [comment]
Вчера поправили, в целом нужно доделать #2966
