### ISSUE TITLE
Плохие буквы в крю манифесте (513 бьонд)

### ISSUE THREAD

**Issue by Shudyn** [TauCetiStation/TauCetiClassic#5919]
#### Подробное описание проблемы
Юникод в крю манифесте, видимо, не работает. 

#### Что должно было произойти
![image](https://user-images.githubusercontent.com/24765850/89156901-375d3780-d574-11ea-8c47-4fe0599722ce.png)
#### Что произошло на самом деле

![image](https://user-images.githubusercontent.com/24765850/89156915-3d531880-d574-11ea-9536-479a6a3ae618.png)

#### Как повторить
Воспользоваться юникод символами.

#### Дополнительная информация:
pepe

**Comment by volas** [comment]
Это который крю манифест? Скорее всего там charset не стоит и ие неправильно парсит кодировку. 

Связанно так же с #2966

**Comment by Motzord** [comment]
Хорошие там буквы, можно закрыть
