### ISSUE TITLE
Нельзя стакать rags-ы

### ISSUE THREAD

**Issue by Artik12344** [TauCetiStation/TauCetiClassic#5927]
#### Подробное описание проблемы
Если попробовать стакнуть rags, то выйдет сообщение 
![image](https://user-images.githubusercontent.com/48361107/89184664-d0567780-d5a1-11ea-86e2-d6dfaae5da3e.png)

#### Что должно было произойти
rags должен был стакнуться 
#### Что произошло на самом деле
rags не смог стакнуться
#### Как повторить
попробовать стакнуть rags
#### Дополнительная информация:
???

**Comment by LudwigVonChesterfield** [comment]
У рагов указано что стакаются по одному, вероятно это чтобы нельзя было таскать с собой кучу тряпок(почему-то).

Это не баг.
