### ISSUE TITLE
[Proposal] Шахтерский риг + топор в одиночку выпиливает блоба

### ISSUE THREAD

**Issue by Leshiy-ART** [TauCetiStation/TauCetiClassic#5929]
#### Подробное описание проблемы

Человек в mining hardsuit топором и парочкой suit patcher может в одиночку разбить блоба с тысячами накопленных опинтов.

![Tau Ceti Station 2020-08-03 204729](https://user-images.githubusercontent.com/4739426/89211761-ec224380-d5ca-11ea-9bdb-c60949f1d843.png)
(шахтер прошел блоба от конца мостика у ЕВА до места на скриншоте, ядро было в туалете дорм.)

#### Что должно было произойти

Шахтеру в риге блоб должен был хотя бы что-нибудь сломать, но весь урон нивелируется.

#### Что произошло на самом деле

Шахтер преодолел коридоры покрытые укрепленным блобом, разбил все ходячие споры, дошел до ядра и в одиночку сломал его топором.

#### Как повторить

Заспавнить блоба, взять хардсьют шахтера и завалить блоба не получая урона.

#### Дополнительная информация:

Не думаю что так должно быть, что бы в одиночку с одним лишь топором разбить жирного блоба.
Раунд #35359. Первый сервер.

**Comment by T6751** [comment]
#4608

**Comment by Leshiy-ART** [comment]
> #4608

О, спасибо.
