### ISSUE TITLE
Книги на языке стола зачарованний.

### ISSUE THREAD

**Issue by DedYarick** [TauCetiStation/TauCetiClassic#5931]
#### Подробное описание проблемы
Все книги которые выдает PC библиотекаря (а может и вообще ВСЕ книги, я не проверял) теперь на языке стола зачарований. 
#### Что должно было произойти
Нормальные букавы 
![image](https://user-images.githubusercontent.com/63983146/89216774-75923f80-d5e4-11ea-90c3-8ae1cc673e0d.png)

#### Что произошло на самом деле
Язык стола зачарований 
![image](https://user-images.githubusercontent.com/63983146/89217061-fbae8600-d5e4-11ea-9b09-05d8f91588c3.png)

#### Как повторить
Распечатать книгу и открыть.

**Comment by Tolerantboy** [comment]
Вообще все. Если сунуть бумажку в букбиндер, он выплюнет книгу с таким же сломанным текстом

**Comment by T6751** [comment]
Не актуально. Видимо после https://github.com/TauCetiStation/TauCetiClassic/pull/5966
![20200903 235927](https://user-images.githubusercontent.com/66636084/92173047-95678e00-ee44-11ea-839c-0861845bdfa8.png)
