### ISSUE TITLE
Люди в шкафах не слышат друг друга и людей вокруг.

### ISSUE THREAD

**Issue by CeUvi** [TauCetiStation/TauCetiClassic#5934]
#### Подробное описание проблемы
Люди в шкафах не слышат других людей в шкафах и людей вне шкафов. Вне-шкафные люди слышат людей из шкафа.
#### Что должно было произойти
Все всех слышат.
#### Что произошло на самом деле
Не слышат.
#### Как повторить
Поговорить находясь в шкафу.
#### Дополнительная информация:
то же самое происходить с дионами-нимфами в руках.

**Comment by Akellazp** [comment]
по-моему чтото подобное было когда я был в мехе

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/problemy-so-zvukom/20876/6
