### ISSUE TITLE
[proposal] емагнутый байкхорн делает бвоньк

### ISSUE THREAD

**Issue by Zmey25** [TauCetiStation/TauCetiClassic#5936]
#### Подробное описание пропошала
Байкхорн клоуна после емага должен менять звук на бвоньк

#### Почему это нужно
[Людям это нужно](https://forum.taucetistation.org/t/idei-dlya-donatov/20512)

#### Почему это не убьет атмосферу игры
Внутри игры просто поменяется звук, ничего сверхъестественного

#### Дополнительная информация:
Уменьшаем количество панических атак у игроков путем приучивания их к звукам природы

**Comment by Loratron** [comment]
А что в байкхорне емагать-то?...

**Comment by Zmey25** [comment]
Блюспейсный воздушный клапан. Эта технология запатентована планетой клоунов.

**Comment by cool20141** [comment]
10$ где?

**Comment by KIBORG04** [comment]
Людям это не нужно
