### ISSUE TITLE
СПУ и камень душ

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5937]
#### Подробное описание проблемы
Мертвого спу или спу в крите можно засунуть в камень душ
#### Что должно было произойти
Спу не засовывается в камень душ
#### Что произошло на самом деле
Получаем душу из спу
#### Как повторить
Кликнуть камнем душ по мертвому спу/спу в крите
#### Дополнительная информация:
Спу машины, у них нет души

**Comment by Tolerantboy** [comment]
Ghost in the Shell
