### ISSUE TITLE
Книги сломаны

### ISSUE THREAD

**Issue by Tolerantboy** [TauCetiStation/TauCetiClassic#5946]
#### Подробное описание проблемы
При открытии книг видишь гугли-вугли вместо текста
![РћСЂРґРµРЅ Р’РµР»РёРєРѕРіРѕ Р СѓРєРѕС‚РІРѕСЂРЅРѕРіРѕ Р’РѕР·РІС‹С€РµРЅРёСЏ](https://user-images.githubusercontent.com/20757723/89440765-d0e33f80-d754-11ea-9193-df18a0fb9feb.PNG)
#### Что должно было произойти
Книги можно читать
#### Что произошло на самом деле
Книги читать нельзя
#### Как повторить
Открыть книгу
#### Дополнительная информация:
Такая же проблема с оповещением, что тебе написал админ/ментор. Кроме текста сообщения самого, собственно админа/ментора, всё остальное написано сломанными символами типа РµР»РёРєРѕРіРѕ С‹С€РµРЅРёСЏ "Бла-бла-бла, тебе бан" РµР»РёРєРѕРіРѕ С‹С€РµРЅРёСЏ

**Comment by cool20141** [comment]
Уже было

**Comment by Tolerantboy** [comment]
> 
> 
> Уже было

Ну, я 2 страницы чекнул, а дальше ишьюи до обновы на которой они и сломались, и на них не нашел

**Comment by KIBORG04** [comment]
![image](https://user-images.githubusercontent.com/26389417/89451173-f9376200-d785-11ea-80b0-e8c9c65f0f41.png)

**Comment by LudwigVonChesterfield** [comment]
#5931
