### ISSUE TITLE
[Proposal] Задефайнить все значения переменной sensor_mode

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#5947]
#### Подробное описание проблемы
Значения сенсор_мода где-то цифрой, где-то дефайном

#### Что должно было произойти
`sensor_mode >= SUIT_SENSOR_BINARY`

#### Что произошло на самом деле
`sensor_mode >= 1`

#### Как повторить
Посмотреть в код

#### Дополнительная информация:
Ctrl + F `sensor_mode`
Можете добавить метку, что это Хороший Первый Ишуй

**Comment by 4310V343k** [comment]
А нужен ли дефайн? Мне кажется, вполне спокойно можно было бы обойтись и просто числовыми значениями

**Comment by KIBORG04** [comment]
По хорошему дефайны нужны любым цифрым, которые непонятно че делают, как в этом случае. И у нас уже дефайны придуманы, но не везде поставлены.
![image](https://user-images.githubusercontent.com/26389417/89446387-aa39fe80-d77e-11ea-9e64-0add6b8e21e4.png)
