### ISSUE TITLE
Имплант Лояльности не работает на антагов

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#595]
#### Подробное описание проблемы

Когда вкалываю имплант лояльности в культиста, он всё ещё является культистом
#### Что должно было произойти

Из него должен был выйти Дух поклонника Нар-СИ
#### Что произошло на самом деле

Он остался Культяпкой продолжая меня пытаться убить
#### Как повторить

Вколоть имплант лояльности в культиста
#### Дополнительная информация:

Возможно это работает со всеми масс антагами

**Comment by Flankir** [comment]
Это не баг. Имплант лояльности мешает обращению в культ но если имплантируемый уже в культе он не будет из него исключен.

**Comment by Damirrus1** [comment]
Кстати да, Нар-Си же бог какой-то там.

**Comment by WallShrabnic** [comment]
Культистов лечат святой водой

**Comment by Flankir** [comment]
Только ты ольт не должен об этом знать если ты не священник.

**Comment by WallShrabnic** [comment]
Имплант сжигает мозги, но не сжигает душу. Поэтому всякие ревы забывают своих соратников, а культ нельзя реконвертнуть

**Comment by Olt1771** [comment]
Раньше имплант выбивал из всех масс ролей(кроме шедоу, у нас деконверт увы отсутствует)

**Comment by Flankir** [comment]
Раньше было неправильно. И что?
