### ISSUE TITLE
Скролл чата на колесико мыши перестал работать

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#5955]
#### Подробное описание проблемы
Скролл чата на колесико мыши перестал работать когда нажимаешь мышкой по чату (джампнуть на лог за админа например на место взрыва)
#### Что должно было произойти
Он должен скролить всегда
#### Что произошло на самом деле
Он не скролит на колесико мыши
#### Как повторить
Поскролить колесиком мыши, нажать мышкой на чат, убедиться что не скролит
#### Дополнительная информация:
Чинится если открыть смайлики и закрыть

**Comment by T6751** [comment]
#5913
