### ISSUE TITLE
Блобозомби агрятся на боксерские груши

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5970]
#### Подробное описание проблемы
Блобозомби агрятся на боксерские груши
#### Что должно было произойти
Не агрятся
#### Что произошло на самом деле
Агрятся
#### Как повторить
Выпустить блобозомби на боксерскую грушу
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/47355061/89729152-9838b400-da3b-11ea-9894-479ad3be2eba.png)

**Comment by CeUvi** [comment]
Походу, вообще все симплмобы агрятся на груши (пауки как минимум)

**Comment by BiQndy** [comment]
Хм, можно грушой астероид танковать наверное тогда

**Comment by Tolerantboy** [comment]
> 
> 
> Хм, можно грушой астероид танковать наверное тогда

Бля, надо быстрее пойти абузить, пока не пофиксили

**Comment by LudwigVonChesterfield** [comment]
пора выпилить грушу

**Comment by Rahmanio** [comment]
> пора выпилить грушу

так мы же это исправили, что хостайл мобы не атакуют её, закрой пр вообще

**Comment by Rahmanio** [comment]
#7359 @LudwigVonChesterfield
