### ISSUE TITLE
Отвязка божка от посоха

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#5973]
#### Подробное описание проблемы
Если уничтожить посох, когда в нем есть божок, то божок останется, но при этом не будет привязан куда-либо и сможет свободно летать по всей станции, зачастую паля ролек и мешая им
#### Что должно было произойти
Уничтожили посох и божка вместе с ним
#### Что произошло на самом деле
Уничтожили посох, божок остался
#### Как повторить
Уничтожить посох, в котором уже есть божок (например в крематории)

**Comment by DedYarick** [comment]
Ето фича

**Comment by KIBORG04** [comment]
Тут нужен не баг, а пропозал) Это фича

**Comment by Tolerantboy** [comment]
Не баг, а фича и это не сарказм. Как я понял, божок теряет свои силы, но зато становится идеальным информатором. Хз как это балансить и надо ли, но это не баг.

**Comment by Loratron** [comment]
Если это фича, то почему божок появляется только после вселения в посох? Он только благодаря посоху и существует, баг это, а не фича

**Comment by KIBORG04** [comment]
Вы серьезно? Даже разраб фичи пишет, что это фича
![image](https://user-images.githubusercontent.com/26389417/89912577-61a99780-dbfb-11ea-8047-eae4fd28c352.png)

**Comment by Akellazp** [comment]
> Как я понял божок теряет силы

Нет не теряет. Если у него есть аспекты на разлитие смазки, то он становится призраком, способным уничтожить любого человека
