### ISSUE TITLE
Фикс зрения таяр не пофиксил зрение таяр.

### ISSUE THREAD

**Issue by CeUvi** [TauCetiStation/TauCetiClassic#5977]
#### Подробное описание проблемы
в шапке
#### Что должно было произойти
таяры видят в темноте.
#### Что произошло на самом деле
таяры не видят в темноте даже после фикса.
#### Как повторить
зайти в темноту за таяру.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/56074620/89856549-3ba3d900-dba2-11ea-8078-bda413d3d685.png)
![image](https://user-images.githubusercontent.com/56074620/89856565-45c5d780-dba2-11ea-9c7c-3e913111f56d.png)

**Comment by FelixRuin** [comment]
почему мне кажется, что билд просто не обновлися?
очки нацепи с фильтром, если ослепнешь полностью, то не обновлялся

**Comment by CeUvi** [comment]
билд обновился, закрываю
