### ISSUE TITLE
Как убрать командира ЕРТ из отряда

### ISSUE THREAD

**Issue by ghost** [TauCetiStation/TauCetiClassic#599]
#### Подробное описание проблемы

Лидера ЕРТ может и не быть, если...
#### Что должно было произойти

Место лидера ОБР не забивается после выхода.
#### Что произошло на самом деле

Место лидера ОБР забилось после выхода.
#### Как повторить

Быть в игре; 
Первым зайти за бойца ЕРТ; 
Нажать на кнопочку "OK" в первом пункте, где выбирается имя; 
Выйти из игры; 
Зайти в игру снова. После этих манипуляций роль командира не выдается никому.

**Comment by RichardJones1** [comment]
Нужно просто немного изменить алгоритм выдачи роли

**Comment by Motzord** [comment]
Скорее всего пофикшено пром с ghostly roles
