### ISSUE TITLE
Нельзя убрать терминал без его мастера.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#600]
#### Подробное описание проблемы
Нельзя убрать терминал без его мастера.
#### Что должно было произойти
При использовании кусачек на терминал без мастера он должен был демонтироватся.
#### Что произошло на самом деле
Ночего.

**Comment by Raschert0** [comment]
Ты о каких терминалах?

**Comment by Dennok** [comment]
под апц/смесами. Если разобрать СМЕС не сняв терминал то терминал уже не снять.
