### ISSUE TITLE
Баг с пИИ

### ISSUE THREAD

**Issue by AAAAAAAASH** [TauCetiStation/TauCetiClassic#6000]
#### Подробное описание проблемы
Не слышно речи за пИИ в непосредственной близости.
#### Что должно было произойти
пИИ общается без помощи радио локально
#### Что произошло на самом деле
пИИ слышит только радио
#### Как повторить
Зайти за пИИ
#### Дополнительная информация:
-

**Comment by BesumniiChebureck** [comment]
#5934
Этот баг скорее всего относится к этому ишуе, кстати появилось после 513

**Comment by KIBORG04** [comment]
И вот такой вот 6000ный ишуй? Дизлайк

**Comment by KIBORG04** [comment]
#6423
#6881
#6104
#6758
#6104

Найденные мной проблемные ишуи в добавок

**Comment by Permyack** [comment]
Раз уж мою тему решили закрыть.
Стоит добавить, что та-же проблема актуальна и для позитронки. М.б. ещё для мозга в ММИ и чего-то ещё с подобной механикой.
Раньше такого не было кажется и вот опять.

**Comment by KIBORG04** [comment]
Скоро год будет багу

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/blob/30414cf0a02d1032ff183ef07990c17a8a0656c5/code/modules/mob/living/say.dm#L145-L162

Вся суть бага в этом месте. Проблема в том, что алгоритм не может добавить моба пИИ внутри хумана. Там типо хуман(моб)->телефон с пИИ(обж)->сам пИИ(моб).
На тг это пофикшено с помощью одного рекурсивного алгоритма и я не очень знаю, почему бы просто его не спортировать. Воот, это все что я нарыл

**Comment by volas** [comment]
Глянул, потому что тут в дискорде опять вспоминали ~~и опять ничего не делали, даже не бампнули~~

Киборг выше прав, там свой код поиска слушателей нужно заменить на ``get_hearers_in_view`` и скопипастить обновление к этому проку с тг, расставить флаг ``HEAR_1`` к объектам которые имеют ``hear_talk``. Изи фикс.

**Comment by KIBORG04** [comment]
> Изи фикс.

**Comment by Akellazp** [comment]
когда уже пофиксят

**Comment by Permyack** [comment]
> когда уже пофиксят

Никогда. Очевидно же, что никто не заинтересован в том, чтобы сделать это.

**Comment by volas** [comment]
Если кому-то нужно - я могу расписать подробнее алгоритм действий, как это пофиксить. Стоит только дождаться мержа тгчата.

**Comment by KIBORG04** [comment]
Дождались

**Comment by volas** [comment]
Возвращаясь к проблеме. Вопрос с порта с тг уже сложнее, там случился https://github.com/tgstation/tgstation/pull/61422

Если не рефакторить, починить еще проще, но я не могу найти где и в какой момент это вообще сломали, и как это работало раньше. Самое близкое изменение, что я нашел, https://github.com/TauCetiStation/TauCetiClassic/pull/4040 - но вроде бы существенно ничего не меняли.

Не зная, как и когда это сломали, я не уверен, что пофикшу правильно.

**Comment by KIBORG04** [comment]
4040 вроде как и сломал

**Comment by volas** [comment]
Скорее всего с 513. Мы перешли на новую версию 2 августа 2020, и после этого начались репорты.

Возможно, связанно с https://www.byond.com/forum/post/2600534

Сейчас разбираться уже поздно, если бы сразу обратили внимание что это возможно из-за мажорной версии... моя теория - ``view()`` "по ошибке" возвращал внутренних мобов (спрятанных в чем-то, находящимся в пределах view), и Люммокс любезно нам это починил.
