### ISSUE TITLE
Админ мемо сломалось

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6006]
#### Подробное описание проблемы
В админ мемо написано чет умное и раньше при заходе это было читабельным.
#### Что должно было произойти
записи остались, все довольны
#### Что произошло на самом деле
там непонятные иероглифы вместо кирилицы
#### Как повторить
Быть педалью и почитать админ мемо

#### Дополнительная информация:
513

**Comment by cool20141** [comment]
А что было раньше, спали, пж

**Comment by OfficerSoftheart** [comment]
Все работает, не актуально. 
Пруф 
![image](https://user-images.githubusercontent.com/41524861/90627977-756d8300-e225-11ea-9fda-daf4da81f0d6.png)
