### ISSUE TITLE
Дрон не может построить шлюз или сложные устройства

### ISSUE THREAD

**Issue by Ro2tCrab** [TauCetiStation/TauCetiClassic#6013]
#### Подробное описание проблемы
Дрон потерял возможность менять уровень доступа на плате шлюза и устанавливать дотсуп
#### Что должно было произойти
 - Дрон берёт плату шлюза в руки и меняет доступ
 - Дрон способен собирать машины с лазерами, батарейками и прочими частями
#### Что произошло на самом деле
 -Дрон не может настроить уровень доступа на плате шлюза и установить его.
 -Дрон не может строить сложные машины
#### Как повторить
 - Попробовать построить шлюз с любым доступом
#### Дополнительная информация:
 Раньше дрон был способен провернуть подобное

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/6009

Шлюзы же фиксили

**Comment by Ro2tCrab** [comment]
Буквально 10-15 минут назад протестировал на сервере

**Comment by T6751** [comment]
В плане не может настроить плату? Плата "The airlock electronics" берется гриппером и кликом по грипперу открывается соответствующая панель
|![image](https://user-images.githubusercontent.com/66636084/90535485-9aa9b500-e183-11ea-86e4-368e051f7ca7.png)|![image](https://user-images.githubusercontent.com/66636084/90535416-89f93f00-e183-11ea-83b2-f4a1f01625d7.png)|

**Comment by Ro2tCrab** [comment]
Я пытался 3-4 раза провернуть подобное, но не смог. Я проверю ещё раз.

**Comment by T6751** [comment]
> Я пытался 3-4 раза провернуть подобное, но не смог. Я проверю ещё раз.

Если Панель открывается, то как понимаю, проблема в том, что не не получается кликнуть по кнопке.

**Comment by T6751** [comment]
На счет "сложных машин". Если это machine frame машины, то https://github.com/TauCetiStation/TauCetiClassic/issues/1542
