### ISSUE TITLE
Суицид nullrod'ом не работает

### ISSUE THREAD

**Issue by muWander** [TauCetiStation/TauCetiClassic#6014]
#### Подробное описание проблемы
Конфликт
#### Что должно было произойти
suicide
#### Что произошло на самом деле
The rod appears to do nothing.
#### Как повторить
Выбор рта на кукле, клик на себя с нуллродом в руке, suicide

**Comment by KIBORG04** [comment]
```
/obj/item/weapon/nullrod/attack(mob/living/M, mob/living/user)
	if (M.stat != DEAD)
                    ....
		else
			to_chat(user, "<span class='danger'>The rod appears to do nothing.</span>")
```
Это сообщение при атаке кого-то(в том числе и тебя) вызывается,
Хотя странно то, что эта возможность есть: `/obj/item/weapon/nullrod/suicide_act(mob/user)`

**Comment by Akellazp** [comment]
эм, это каким таким образом ты хочишь суициднуться нулродом?
