### ISSUE TITLE
WallHack

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6016]
#### Подробное описание проблемы
С помощью божка можно проходить сквозь стены.
Если он будет стоять в стене и ты проведешь по нему прием, то тебя закинет в стену и ты сможешь выйти с другой ее стороны.
#### Что должно было произойти
Эм... Хрен его знает вообще
#### Что произошло на самом деле
Вол Хак
#### Как повторить
Провести прием по божку в стене
#### Дополнительная информация:
Еще один повод удалить божка

**Comment by 4310V343k** [comment]
Баг не в том, что ты можешь улететь в стену, а в том, что ты можешь пиздить бога :pekasmart:
