### ISSUE TITLE
Пинпоинтер не показывает функционирующий ИИ

### ISSUE THREAD

**Issue by Mintt69** [TauCetiStation/TauCetiClassic#6022]
#### Подробное описание проблемы
Пинпоинтер не показывает функционирующий ИИ (Если быть точнее-малф)
#### Что должно было произойти
Пинпоинтер должен показывать стрелочку в местоположение ИИ
#### Что произошло на самом деле
Пинпоинтер показывает, что ИИ находится не на этом секторе космоса
#### Как повторить
Включить пинпоинтер, направив на функционирующий ИИ
#### Дополнительная информация:
Пинпоинтер начинает показывать стрелочку по прилету на ЦК, возможно указывает на тот ИИ, что там и находится, в таком случае пинпоинтер изначально настроен на функционирующий ЦКшный ИИ..

**Comment by 4310V343k** [comment]
oof
