### ISSUE TITLE
Фантомные Power тревоги

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#6026]
#### Подробное описание проблемы
Стоит вам хотя бы чуть-чуть прикоснуться к АПЦ с целью его разборки, вы не избавитесь от тревоги, которую его отключение вызовет, если не перезапустите консоли.
#### Что должно было произойти
Разбор АПЦ, может, и вызовет тревогу, но его повторная постройка не должна её оставлять.
#### Что произошло на самом деле
Разбор АПЦ вызвал тревогу. АПЦ уже вернули в нормальное состояние, даже стоит на том же месте, весь новенький, рабочий. Но тревога настойчиво мигает на консолях и указывает что там проблемы с током.
#### Как повторить
Разберите АПЦ, затем соберите его вновь в той же зоне. Всё внимание на консоль тревог.
#### Дополнительная информация:
а

**Comment by pss88** [comment]
Причина:
После разборки APC его объект удаляется. А бывшая ссылка на него остается в `sources` в `alarms` в `station_alert` консоли. Что-то вроде: `1 = null`.

Т.е. нужно в какой-то момент (например, при каждом `ui_interact`) перепроверять все списки `alarms`. И удалять оттуда null-ы и тревоги целиком, если они только из null-ов и состоят.
