### ISSUE TITLE
Глухой PAI

### ISSUE THREAD

**Issue by Ro2tCrab** [TauCetiStation/TauCetiClassic#6035]
#### Подробное описание проблемы
PAI может слышать каналы департаментов, но не может услышать /say или /me
#### Что должно было произойти
PAI должен быть способен слышать 
#### Что произошло на самом деле
PAI не слышит голоса окружающих 
#### Как повторить
Поиграть за PAI

**Comment by KIBORG04** [comment]
[Duplicate](https://github.com/TauCetiStation/TauCetiClassic/issues?q=is%3Aopen+label%3ADuplicate+sort%3Aupdated-desc)
