### ISSUE TITLE
Слепые мемесы

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#604]
#### Подробное описание проблемы

Мемес стартует с ограниченной зоной видимости. То бишь в одни тайл только под собой. От черного экрана можно избавиться, но только после того как мемес возьмет под прямой контроль игрока. 
#### Что должно было произойти

Мемес должен был любоваться окружающей обстановкой.
#### Что произошло на самом деле

Мемес слеп как мой дед.
#### Как повторить

Зайдите в раунд мемесом
#### Дополнительная информация:

Мемесы самый отстойный режим.

**Comment by Damirrus1** [comment]
Я обычно перезахожу, это как временное решение проблемы.

**Comment by Motzord** [comment]
Меме выпилен, я не уверен нужен ли этот ишью
