### ISSUE TITLE
Выпадание двух блобов одному игроку.

### ISSUE THREAD

**Issue by ramiro181** [TauCetiStation/TauCetiClassic#6040]
#### Подробное описание проблемы
При большом онлайне вместо одного блоба дается два, но даются они одному и тому же человеку, что по факту дает нам один блоб вместо двух.

#### Что должно было произойти

Два разных блоба на двух раных игроках.
#### Что произошло на самом деле

Два блоба на одном игроке.
#### Как повторить

Получить двух блобов при большом онлайне.
#### Дополнительная информация:

![44](https://user-images.githubusercontent.com/4301437/91212096-710b0380-e718-11ea-9552-21208d1a3c4a.jpg)

**Comment by T6751** [comment]
Во время раунда было два блоба? На обоих блобах был один игрок?

**Comment by T6751** [comment]
> При большом онлайне вместо одного блоба дается два, но даются они одному и тому же человеку, что по факту дает нам один блоб вместо двух.

Если я правильно понял, то, пусть на них и был один и тот же игрок, По факту мы имеем двух разных антагонистов (блобов), появившихся в разное время и погибших в разное время. Разве нет?

**Comment by cool20141** [comment]
Было такое дело как-то, у чела было одновременно два блоба, в титрах два раза написало его имя

**Comment by Akellazp** [comment]
да это постоянно происходит
