### ISSUE TITLE
Нельзя говорить когда находишься в шкафу

### ISSUE THREAD

**Issue by PirogSema** [TauCetiStation/TauCetiClassic#6041]
#### Подробное описание проблемы
Когда ты находишься в шкафу и говоришь что-то (не проверял радиоканалы), то сообщение не появляется.
#### Что должно было произойти
Ты написал что-то — другие увидели.
#### Что произошло на самом деле
Ничего.
#### Как повторить
Залезть в шкаф и сказать что-то.

**Comment by GermanSUS** [comment]
Такая же проблема когда ты в слипере, боди сканере, мехе.

**Comment by 4310V343k** [comment]
Нужен реворк сейкода

**Comment by BesumniiChebureck** [comment]
#5934 Такая же проблема с пИИ, позитронкой, ММИ, с людьми в слиперах, шкафах, дионой на плечах и всё появилось после 513
