### ISSUE TITLE
ИИ и его ремонт

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#605]
#### Подробное описание проблемы

ИИ невозможно починить если он трагически погиб
#### Что должно было произойти

Можно было восстановить ИИ с помощью интел карты через АИ игнатери рестор компьютер
#### Что произошло на самом деле

Ничего
#### Как повторить

Вставить мёртвого ИИ на интел карте в компьютер и попробовать восстановить

**Comment by Dennok** [comment]
Возможно если ИИ гостнулся то нельзя его починить.

**Comment by Belfogor** [comment]
ИИ вообще не чинится. Ни полностью убитый, ни частично поврежденный. А на возможность его починки не никак не влияет его наличие в "теле". Проверено
