### ISSUE TITLE
Беды NT Бричера

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6056]
#### Подробное описание проблемы
НТ бричер, который для унатхов, могут носить люди, воксы, и, возможно, вообще все (но последнее это не точно)
#### Что должно было произойти
НТ бричер могут носить только унатхи
#### Что произошло на самом деле
Да кто угодно может носить специальный скафандр унатхов
#### Как повторить
Надеть на себя бричер не будучи унатхом
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/47355061/92003474-be572880-ed49-11ea-9789-e744c4a202c2.png)

**Comment by cool20141** [comment]
Если что, унатхи–огромные ебалаи, для которых должен быть и риг соответствующий, а не такой, что его могут мелкие пиздюки aka воксы носить без проблем

**Comment by T6751** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/4968

**Comment by cool20141** [comment]
>closed
