### ISSUE TITLE
Пережатые вики-книги. 

### ISSUE THREAD

**Issue by DedYarick** [TauCetiStation/TauCetiClassic#6057]
#### Подробное описание проблемы
Книги с вики информацией имеют до невозможности сжатый "экранчик", из за чего их чтение - боль. 
#### Что должно было произойти
Нормально открытые книги.

#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/63983146/92139635-71e31a00-ee29-11ea-9be9-e8a4662cc7a9.png)

#### Как повторить
Открыть любую вики-книгу.

**Comment by 4310V343k** [comment]
Не пробовал растянуть окно книги?

**Comment by cool20141** [comment]
Так оно растянуто у него, он же скрин кинул. Почему-то остается куча незанятого пространства

**Comment by DedYarick** [comment]
Не растягивается, пробовал.
