### ISSUE TITLE
Портативная охлаждайка спу не работает в кармане

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6059]
#### Подробное описание проблемы
Портативное охлаждение спу, которое находится у них в коробке при спавне не работает по какой-то причине когда находится в кармане
#### Что должно было произойти
Включил, положил в карман, надел шлем, счастив
#### Что произошло на самом деле
Включил, положил в карман, надел шлем, умер
#### Как повторить
Все описано выше

**Comment by atik1n** [comment]
Она и не должна работать из кармана. Не баг
