### ISSUE TITLE
"Баги карты."

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#606]
#### Подробное описание проблемы
На кухне у повара расположены два устройства All-In-One Grinder. Которые не предназначены для создания сока.

#### Что должно было произойти
Вместо двух одинаковых устройств,должна присутствовать и соковыжималка и гриндер.

#### Что произошло на самом деле
Гриндеры перерабатывают фрукты на производные - сахар и питательные вещества.

#### Как повторить
Попробовать выжать сок в гриндере из любого фрукта который содержит в себе сок.

#### Дополнительная информация:
Соковыжималка предназначена для производства сока,который она и производит.
![image](https://cloud.githubusercontent.com/assets/20359322/18781177/64d67318-8189-11e6-828f-7440fb8ee7e1.png) 
![image](https://cloud.githubusercontent.com/assets/20359322/18781198/765a89da-8189-11e6-9e83-31f3ab5482df.png)
![image](https://cloud.githubusercontent.com/assets/20359322/18781351/00515682-818a-11e6-9f94-a3a55082021f.png)
![image](https://cloud.githubusercontent.com/assets/20359322/18781432/5aaa0dc2-818a-11e6-8f8c-d4136279bc1a.png)

**Comment by Raschert0** [comment]
В дополнение к багам
http://prntscr.com/cld2qt

**Comment by Dennok** [comment]
>Которые не предназначены для создания сока.<
В гриндере есть два режима, как выжимание так и измельчение. и повору они нужны.

**Comment by P-20** [comment]
Dennok, если бы читал внимательней то понял бы что гриндер не может делать сок.  И он не предназначен для этого. Для сока есть соковыжималка. Я лишь прошу заменить один из гриндеров на соковыжималку,что указано выше.  (и то что ты сказал что гриндер нужен повару это ничем, Все и так знают что гриндер нужен, но не два(и специально для тебя - лишь по названию прибора видно что он не предназначен для сока) )

**Comment by Dennok** [comment]
Алл ин он имеет два режива, один для выживания сока, другой для измельчения. Выже хотите отобрать у повара возможность дробить.
Ну а то что их да это да. проблема.

**Comment by P-20** [comment]
> Алл ин он имеет два режива, один для выживания сока, другой для измельчения. Выже хотите отобрать у повара возможность дробить.
Ну а то что их да это да. проблема.
Специально для тебя повторюсь. У повара будет и гриндер и выжималка(Там сейчас два устройства-гриндера)( Тебе может нарисовать ? Чтобы было видно что с одной стороны кухни гриндер,с другой стоит гриндер, и один из них пометить крестиком и сверху надрисовать соковыжималку, может так дойдет лучше?). Сообщением выше это сказано, и я не пойму, либо ты читаешь где-то между текстом,либо не понимаешь сути того.
И разъясню о режимах. Да. В гриндере два режима. Но он измельчитель. И Деннок,там нет режима для выжимания сока. Один режим для измельчения всякой мелочи,другой для измельчения фруктов.

**Comment by Dennok** [comment]
![image](https://cloud.githubusercontent.com/assets/7734424/19020192/34cfb47c-88aa-11e6-99ac-deafc23ec240.png)
Как мы видим тут есть кнопка гринд и джуис.

**Comment by Dennok** [comment]
Другое дело. что режим соковыжимания в алл ин он гриндере не работает.

**Comment by P-20** [comment]
> Другое дело. что режим соковыжимания в алл ин он гриндере не работает.
>
То что ты называешь режимом соковыжималки,немного другое,не то о чем ты думаешь, этот режим для фруктов и овощей,и из них получаются составные, из моркови имидозалин,из яблок нутрименты и прочее.

**Comment by Dennok** [comment]
>из них получаются составные, из моркови имидозалин,из яблок нутрименты и т.д.

Это режим измельчения.
Режим соковыживания тоже есть но там не для всего. И он работает. я проверил на томате и получил томатный сок.

**Comment by P-20** [comment]
Таки да, но все равно гриндер весьма странно работает.

**Comment by Dennok** [comment]
В каком смысле? Я конечно замечал что иногда он не дает сока. Но это было давно. и возможно зависит от плодов.

**Comment by P-20** [comment]
Он сейчас тоже не дает сока,со многих фруктов. Повара жалуются.

**Comment by Raschert0** [comment]
Вот ещё один баг (под дверьми, которые на входе в дормы), зона не общего помещения дорм, а комнаты с кроватью
![screenshot_2](https://cloud.githubusercontent.com/assets/11941910/19039919/814556aa-898a-11e6-929f-cd62bfafd4fc.png)

**Comment by Raschert0** [comment]
А вот ещё (часть техов в прибытии не имеет АПЦ, но свет есть!)
![screenshot_3](https://cloud.githubusercontent.com/assets/11941910/19040031/fdb0e4fc-898a-11e6-9a7c-e688d7a0ae3d.png)
