### ISSUE TITLE
Шлюзы доков ЦК

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6060]
#### Подробное описание проблемы
При стыковке шатла с цк, шлюзы цк остаются заболтированными
#### Что должно было произойти
Болты поднимаются
#### Что произошло на самом деле
Шлюзы заболтированны, на цк не попасть (если нет пульта дверей)
#### Как повторить
Прилететь на шатле отбытия на цк

**Comment by 4310V343k** [comment]
В своем пре я шаттл эвакуации вообще не трогал
Вроде

**Comment by T6751** [comment]
> В своем пре я шаттл эвакуации вообще не трогал

Можешь всё-таки посмотреть, пожалуйста? (Потому что, если откатить тот пр, то эти шлюзы не будут заболтированы)
