### ISSUE TITLE
[Proposal] Сделать, чтобы противогазы не убирали волосы

### ISSUE THREAD

**Issue by CeUvi** [TauCetiStation/TauCetiClassic#6070]
#### Подробное описание проблемы
При одевании противогаза у персонажа пропадают волосы. Почему так - непонятно.
#### Что должно было произойти
Волосы остались на месте.
#### Что произошло на самом деле
Волос нет.
#### Как повторить
Одеть противогаз.
#### Дополнительная информация:
Почему.

**Comment by cool20141** [comment]
![image](https://user-images.githubusercontent.com/53309265/92330943-80287480-f07b-11ea-834a-14f0dc3ed0c7.png)

**Comment by CeUvi** [comment]
У нас не такие противогазы.

**Comment by cool20141** [comment]
Скинь, я не помню, какие

**Comment by CeUvi** [comment]
У нас они закрывают только лицо.

**Comment by Loratron** [comment]
Отображение волос специально убирали, потому что они сквозь противогаз часто торчали. Тут приходится один из двух стульев выбирать

**Comment by CeUvi** [comment]
второй

**Comment by AirBlack** [comment]
![image](https://user-images.githubusercontent.com/5171605/92419379-0aadc880-f18f-11ea-8186-7c834ca22ecf.png)

**Comment by Ayuska** [comment]
Какие именно маски требуют торчащих волос твоих? Gas mask с визором, как в ящиках пожарных, или типичный, как кинули выше, противогаз?

**Comment by LudwigVonChesterfield** [comment]
сделайте возможность убирать-доставать волосы чтобы были довольны все, а не вот это вот...

просто чтобы некоторые маски блокировали перманентно и не позволяли так
