### ISSUE TITLE
[Proposal] Убрать абуз руны призраков у культа

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#6073]
#### Подробное описание проблемы
Культы могут призывать призраков для активации рун или призыва Нар-Си
#### Что должно было произойти
Культ призывает призраков исключительно для помощи себе
#### Что произошло на самом деле
Культ может зарашить Нар-си в четыре рыла за тридцать минут
#### Как повторить
Использовать руну призыва призраков
#### Дополнительная информация:
Возможно, стоит изменить механ работы руны

**Comment by ramiro181** [comment]
Вкину свои пять копеек.
1. Культисты призывают нарсю через гостов-обсервов сразу после открытия нужных слов. Ноль конвертов, нарси на 15 минуте раунда.
2. Культота устраивает каэску, мясо, кровь, кишки. Сосет у кекепажа. Полтора выживших культиста из ставят руну, спавнят кучу призраков и призывает Нарсю. Культ вин, хотя они соснули в (почти)полном составе.
3. Культисты убегают в жопу мира (вайтшип, дварф, западная шахтерка). Ставится руна, госты, Нарси, культ вин.

Такая работы руны провоцирует либо на спидран/стелсран (ноль участия кекепажа в режиме), либо на массовую каэску.

**Comment by KIBORG04** [comment]
Вообще считаю, что нужно полностью режим реворкать

**Comment by KIBORG04** [comment]
> Вообще считаю, что нужно полностью режим реворкать

Мало-мальская основа для реворка уже есть, кстати

**Comment by AirBlack** [comment]
Можно куклам не давать ролю культяпки, и абузов в десять раз меньше и срю манифест чистеньким будет. Абуз высасывания крови можно прикрыть блоком на тип mob/living/carbon/human/dummy, как сделано в соул стоне, обусловив это какой-нибудь жизненной энергией. Ну или за место куклы спавнить подобие божка.
