### ISSUE TITLE
Неправильно отображается руда и её количество, содержащаяся в ящике для руды.

### ISSUE THREAD

**Issue by Ambassadoing** [TauCetiStation/TauCetiClassic#6077]
Issue reported from  Round ID: 35974 (Tau Ceti Classic II (RU))

Reporting client version: 513.1528

#### Подробное описание проблемы
Если набрать в ящик руды, опустошить, положить что-то ещё и проверить содержимое через shift+click, то в ящике будет отображена руда так, как будто из ящика ничего не выгружали.
#### Что должно было произойти
Должно отображаться фактическое содержимое
#### Что произошло на самом деле
Отображается уже выгруженное
#### Как повторить
Попробуйте выгрузить из бура или из мешочка что-то в ящик, опустошить, а потом выгрузить что-то из бура или мешочка опять, осмотрите.
#### Дополнительная информация:
Случается через раз. Может где-то не обновляется отображение содержимого?

**Comment by AirBlack** [comment]
Если из бура выгрузить что-то в ящик, то тот в экзамайне не покажет, что он из бура вытащил,

**Comment by AirBlack** [comment]
При выгрузке из бура в stored_ore у ore_box не вписываются изменения, фикс в одну строку

**Comment by AirBlack** [comment]
Еще нашел баг, при использовании Empty ore box через верб, а не через кнопку в интурфейсе, stored_ore не сбрасывается из-за чего стакаются показатели руды, руда в экзамайне дюпается но на деле нет, не порядок

**Comment by 4310V343k** [comment]
Сейчас доделаю алгебру и сделаю корявый фикс, ломающий всё что угодно, но не чинящий полностью ящики. Жди

**Comment by AirBlack** [comment]
@4310V343k я первый
