### ISSUE TITLE
Сидя на стуле, нельзя перелистывать камеры и вообще пользоваться ими

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#608]
#### Подробное описание проблемы

Если сесть на кресло, то через терминал нельзя листать камеры.
#### Что должно было произойти

Сидя на кресле можно было бы листать камеры и смотреть в терминал
#### Что произошло на самом деле

Невозможность помониторить камеры
#### Как повторить

Сесть на стул, кликнуть по терминалу с камерами

**Comment by Dennok** [comment]
Вроде даже раньше ПДА нельзя было юзать.

**Comment by Raschert0** [comment]
Кхм, не получилось повторить
@Damirrus1 можешь указать какие именно консоли вызывают проблему?

**Comment by Damirrus1** [comment]
![image](https://cloud.githubusercontent.com/assets/21046015/20523773/868fb7b6-b0d8-11e6-8eaa-97515e99ae21.png)
Вот эта не работает, если на стульчике сидеть
