### ISSUE TITLE
Бухломат в шахтерской капсуле требует доступ

### ISSUE THREAD

**Issue by AirBlack** [TauCetiStation/TauCetiClassic#6084]
#### Подробное описание проблемы
Бухломат в капсуле за 12 кусков очков требует доступ бармена
#### Что должно было произойти
С шахтерами попили покушали гитару послушали
#### Что произошло на самом деле
Ассес дениед
#### Как повторить
Попытаться воспользоваться бухломатом из капсулы

**Comment by KIBORG04** [comment]
@BiQndy давай за работу

**Comment by BiQndy** [comment]
![мм](https://user-images.githubusercontent.com/43725089/92635706-f1b42d00-f2de-11ea-862f-0995921ac369.jpg)
