### ISSUE TITLE
Сохранение лора и спеллов божества после возвращения призрака в тело.

### ISSUE THREAD

**Issue by AnimalRidens** [TauCetiStation/TauCetiClassic#6086]
#### Подробное описание проблемы
После смерти космонавты становятся призраками, которые с определенной долей везения могут стать божеством. (То есть быть призванными священником.) В случае, если тело, в котором некогда обитал превратившийся в божество дух, кто-то решит реанимировать, дух вновь вернется в свою оболочку, сохранив при этом все свои божественные знания и способности.
А если детальнее:
После того, как куклу, гост-владелец которой уже стал божеством, реанимируют, призрак без какого-либо запроса возвращается обратно в куклу, сохраняя при этом лор божества в Notes и его спеллы (доступные, насколько я могу судить, через хоткеи в левом верхнем углу экрана).
#### Что должно было произойти
После реанимации куклы гост, ставший божеством, не возвращается в прежнее тело/возвращается с сохранением прежних нотесов и без божественных спеллов.
#### Что произошло на самом деле
После реанимации куклы гост, ставший божеством, вернулся в куклу, сохранив при этом нотесы божества (детальное описание собственного лора, заменяющее информацию о номере и пароле банковской карты) и, предположительно, все его спеллы.
#### Как повторить
1) Умереть. (Конкретно в моем случае произошел гиб.)
2) Принять предложение стать божеством.
3) Дождаться реанимации тела и проверить Notes и хоткеи.
#### Дополнительная информация:
Ситуация произошла в раунде, поэтому я, естественно, не стал проверять, работают ли в данной ситуации способности божества на самом деле - однако факт наличия их иконок, замены нотесов и пр. так или иначе имеет место быть.
На скриншоте ниже - то, как выглядят упомянутые мной иконки спеллов для куклы в отключке. При попытке прожать выдавало "Недоступно в бессознательном состоянии". После того, как кукла пришла в себя, иконки с поблекших сменились на яркие ("активные"), однако прожимать я уже не стал из-за боязни натворить дерьмо.
![Снимок экрана (6)](https://user-images.githubusercontent.com/29713931/92655558-503ad480-f2fa-11ea-836a-68d7aa8759db.png)

**Comment by KIBORG04** [comment]
Какой же убогий код клонирования, я чё-то посмотрел его, потестил и не понял, почему и как оно работает.

Типо, смотря на код, видно, что ему похуй в ком игрок сидит, но почему-то где-то в другом месте, хрен поймёшь где, он как-то детектид, что игрок не может вернуться в тело. Но проблема даже не в этом, а в том, что там какой-то тупой рантайм, который не должен быть, ибо это не логично, и не даёт думать.

Крч, сложно, фикс будет не супер быстрый

**Comment by KIBORG04** [comment]
Ёк макарек, этот код клонинга.. сука.. этот абуз работает не токо на божке

**Comment by KIBORG04** [comment]
Вот тварь на кодере была в 11 году

**Comment by KIBORG04** [comment]
Знаете, как этот баг исправили на других билдах? Они полностью выпилили клонинг машинку
