### ISSUE TITLE
Фотографии нельзя сжигать

### ISSUE THREAD

**Issue by IrLiZi** [TauCetiStation/TauCetiClassic#609]
#### Подробное описание проблемы
Вполне логично, что фотографию можно сжечь, как и бумагу. 
#### Что должно было произойти
Фотография должна сгореть, мать вашу!
#### Что произошло на самом деле
Она не сгорела и вообще ничего не произошло при клике zippo lighter'ом на фотографию.
#### Как повторить
Попытаться поджечь фотографию?
#### Дополнительная информация:
Э-э...немного реализма?

**Comment by dearprincesscelestia** [comment]
Ну, да, это логично. Но проблема в том, что сжигать листочек - это 
`/obj/item/weapon/paper/proc/burnpaper(obj/item/weapon/lighter/P, mob/user)`
А фотоаппарат делает это
`var/obj/item/weapon/photo/Photo = new/obj/item/weapon/photo()`
И хоть в коде бумаги есть заготовка под фотографии, которая должна наследовать в том числе и сжигание, фотоаппарат это не использует.
