### ISSUE TITLE
пИИ всё еще ничего не слышит и не может говорить когда находится в чем-то

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6104]
#### Подробное описание проблемы
пИИ всё еще ничего не слышит и не может говорить когда находится в чем-то
#### Что должно было произойти
Всё не сломано
#### Что произошло на самом деле
Всё сломано
#### Как повторить
Быть пИИ у кого-то в инвентаре

**Comment by Akellazp** [comment]
ап
баг серьезный, и затрагивает не только пии но и позитронки и ии на интелкарте

**Comment by Akellazp** [comment]
Когда фикс?

**Comment by KIBORG04** [comment]
Дубликат #6000
