### ISSUE TITLE
Улетающие платформы

### ISSUE THREAD

**Issue by FBitSafe** [TauCetiStation/TauCetiClassic#6116]
#### Подробное описание проблемы
При отключении гравитации, платформа у хранилища трупов улетает в дальние края

#### Что должно было произойти
Платформа должна стоять смирно

#### Что произошло на самом деле
Платформа летит

#### Как повторить
Отключить гравитацию и ЛКМ-ом тыкнуть по хранилищу

**Comment by Tiarv** [comment]
Какая платформа? У какого хранилища?

**Comment by FBitSafe** [comment]
> Какая платформа? У какого хранилища?

Платформа у хранилища с трупом, случайно не написал

**Comment by 4310V343k** [comment]
Скрин..

**Comment by Tiarv** [comment]
С каким трупом?

**Comment by AndroBetel** [comment]
в морге ёпту

**Comment by BesumniiChebureck** [comment]
Это есть платформа?
![image](https://user-images.githubusercontent.com/67091522/93322511-0ed78700-f81c-11ea-9b15-9c2f63fd946c.png)

**Comment by FBitSafe** [comment]
> Это есть платформа?
> ![image](https://user-images.githubusercontent.com/67091522/93322511-0ed78700-f81c-11ea-9b15-9c2f63fd946c.png)

да, платформа этой штуковины

**Comment by 4310V343k** [comment]
![dem_5f65daa6f3653](https://user-images.githubusercontent.com/56449763/93664831-725ef000-fa7a-11ea-966d-ec63fe34c6b8.png)
