### ISSUE TITLE
Полные ore box, хотя они пустые

### ISSUE THREAD

**Issue by Lusius13** [TauCetiStation/TauCetiClassic#6120]
Issue reported from  Round ID: 36155 (Tau Ceti Classic II (RU))

Reporting client version: 513.1527

#### Подробное описание проблемы
при взаимодействии с пустым ore box, пишет, что в нём есть содержимое.

#### Что должно было произойти
содержимого не должно быть, ибо он пуст

#### Что произошло на самом деле
он полон

#### Как повторить
кликнуть по пустому ore box, перед этим опустошив его

#### Дополнительная информация:
![Screenshot_3](https://user-images.githubusercontent.com/65448765/93585799-01eb9c80-f9b0-11ea-904c-616ae61246bd.png)
![Screenshot_4](https://user-images.githubusercontent.com/65448765/93585807-057f2380-f9b0-11ea-868a-646aeaadbf49.png)

**Comment by Tiarv** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/6077
