### ISSUE TITLE
Госты могут вносить изменения в статусы персонажей включая худы (Toggle HUDs)

### ISSUE THREAD

**Issue by notanennx** [TauCetiStation/TauCetiClassic#6136]
Issue reported from  Round ID: 36201 (Tau Ceti Classic II (RU))

Reporting client version: 513.1528

#### Подробное описание проблемы
Госты могут включить худ через Toggle HUDs и у них появляется возможность изменять статусы, будто на них одеты медхуды или секхуды. Изменения успешно вносятся и видны другими игроками.
![Bug](http://puu.sh/GuHeb/49489e9bb5.png)

#### Что должно было произойти
У гостов не должна иметься возможность изменять или видеть статусы.

#### Что произошло на самом деле
Госты успешно вносят изменения в статусы.

#### Как повторить
Станьте гостом, включите худ через Toggle HUDs, Examine по персонажу, далее вносим изменения.

#### Дополнительная информация:
Скорее всего причина в этом #5971

**Comment by KIBORG04** [comment]
Пофикшено, закрывай

**Comment by KIBORG04** [comment]
Пофикшено, но еще не обновлено в билде
