### ISSUE TITLE
Тенелинг в одежде не может положить карту в ID слот

### ISSUE THREAD

**Issue by Prusski** [TauCetiStation/TauCetiClassic#6140]
#### Подробное описание проблемы
Даже при всей надетой униформе, тенелинг без хитина не может поместить ID карту в слот для ID карты
#### Что должно было произойти
Я одел униформу с закрывающим лицо костюмом. Я напялил на себя свою ID карту. Я притворяюсь членом экипажа
#### Что произошло на самом деле
Я пытаюсь положить карту в ID Слот, а мне говорит: "Your species can not wear clothing of this type."
#### Как повторить
Попытаться поместить ID карту в слот ID карты с надетой на тебя униформой.
#### Дополнительная информация:
-

**Comment by Prusski** [comment]
А почему это так задумано?
Я думал, что ID Карта крепится на одежду, а не на конкретный биологический вид.

**Comment by LudwigVonChesterfield** [comment]
#1401
