### ISSUE TITLE
[Proposal] Люди с ИКСРЕЙем видят всех голыми 

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#6143]
#### Подробное описание проблемы
Иксрей видит сквозь стены, почему бы не видеть сквозь одежду? 

На самом деле, я это пишу себе, чтобы не потерять. После или во время порта альтернейт_апперанса закодю.

**Comment by LudwigVonChesterfield** [comment]
а почему если он видит сквозь стены, и через одежду - он не видит через кожу, мышцы, вплоть до костей?

вроде именно так икс рей и используют

**Comment by KIBORG04** [comment]
Он, поидее, даже сквозь кости должен. Типо, как он определяет через что видеть?

Ну у меня вообще два стула, либо видеть голых, либо видеть скелеты

**Comment by kalazus** [comment]
Как по мне, лучше оставить. Если он не может настраивать силу, то получается совсем странно: если видит сквозь железные стены, то почему он вообще должен видеть людей (кости ещё можно, но дион к примеру нет) и предметы (слишком маленькие, так что через них тоже должен видеть)? Либо добавить настройку в суперсилах, в которой настраивается насколько сильно вникать во внутренний мир человек.

**Comment by KIBORG04** [comment]
Блин, проблем оказалось больше, ладно
