### ISSUE TITLE
[Proposal] Порт мафии с ТГ

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#6151]
#### Подробное описание проблемы
После мержа TGUI 4.1 #6110 очень хочеца мафию портировать с тг, я могу попробовать это сделать. 
Но не просто портировать, но и **перевести на русский**, чтобы нашему коммунити было легче именно играть, а не сидеть в _нейм_переводчике.

Насчет русского языка можете тут отписать или в дисе, ибо тема спорная, как и сама локализация.

Тут есть есть ПРы и фиксы и тд.. Вообще я разберусь откуда портировать.
https://github.com/tgstation/tgstation/pulls?q=Mafia

Кто не знает, на тг госты могут сыграть в мафию, дада, ту самую настолку, в которую когда-то играли ваши деды. Суть в том, что есть триторы и мирные, а также всякие генокрады и тд.

UPD: Ссылка на вики мафии - https://tgstation13.org/wiki/Mafia

![89099502-98361580-d3a4-11ea-94d1-cd6cc3067899](https://user-images.githubusercontent.com/26389417/94071771-22c35000-fdfd-11ea-95f1-b83b8da61f3c.png)

**Comment by volas** [comment]
если в гостоте будет слишком много пряников, может получиться так, что люди будут специально сливаться, или как минимум не бояться этого

**Comment by KIBORG04** [comment]
> если в гостоте будет слишком много пряников, может получиться так, что люди будут специально сливаться, или как минимум не бояться этого

Для этого же и придуманы правила? 

Но да, интересный вопрос, будут ли люди в какую-то нюку скорее идти сливаться, чем воевать.

Но думаю, фича будет актуальна примерно пару недель или меньше, интерес к ней угаснет и все станет, как и всегда

**Comment by OfficerSoftheart** [comment]
> > если в гостоте будет слишком много пряников, может получиться так, что люди будут специально сливаться, или как минимум не бояться этого
> 
> Для этого же и придуманы правила?
> 
> Но да, интересный вопрос, будут ли люди в какую-то нюку скорее идти сливаться, чем воевать.
> 
> Но думаю, фича будет актуальна примерно пару недель или меньше, интерес к ней угаснет и все станет, как и всегда

Лучше добавить это в ИЦ, у нас есть как асистент для игр, как к КПК, или полноценный девайс  чтобы можно было играть в раунде по сетке с асистентами каждый смотрит  в свой мониторчик и мафиозят

**Comment by cool20141** [comment]
В IC никто играть не будет, а призракам, чтоб занять как-то 30 минут до респавна пойдет

**Comment by OfficerSoftheart** [comment]
> В IC никто играть не будет, а призракам, чтоб занять как-то 30 минут до респавна пойдет
Ага. Тест в VR показал что играют все. Мафия не так плоха.

**Comment by cool20141** [comment]
Че за вр

**Comment by cool20141** [comment]
Пож запили эпикмафия.ком полностью в сску!!!

**Comment by KIBORG04** [comment]
Там много ооц и мета фигни, все должны работать (странно, что у нас вообще нет игр для пда), есть контроль над игрой админам, пусть космонавты в игре играют в настольную мафию из ирл

**Comment by KIBORG04** [comment]
Какой тест в VR?

**Comment by KIBORG04** [comment]
Про локализацию лучше отпишите

**Comment by Zmey25** [comment]
- Заменить оок и мета инфу на безвредные аналоги аля стриптизерша, шпион-переодевака и пр.
- Впилить игру в пда
- Сделать задержку на действия побольше, чтоб на неё отвлекались только иногда, а не сидели в пда.
- Слышать как в баре ассистуха кричит "Меня опять убили, что за фигня!"

**Comment by volas** [comment]
давать играть в игре - еще хуже, у нас уже были капитаны которые позабыв про всё на свете сидели играли днд в библиотеке

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/mozhet-bolshe-rolej-dlya-gostov/21932/20
