### ISSUE TITLE
Неверное описание пруда между ботаникой и кухней

### ISSUE THREAD

**Issue by Morgarim** [TauCetiStation/TauCetiClassic#6154]
Issue reported from  Round ID: 36265 (Tau Ceti Classic II (RU))

Reporting client version: 513.1528

#### Подробное описание проблемы
Неверно описание пруда между ботаникой и кухней. Описание копирует описание раковины. 

#### Что должно было произойти
That's a puddle.
An endless puddle at the space station?

#### Что произошло на самом деле
That's a puddle.
A sink used for washing one's hands and face.

#### Как повторить
Осмотрите лужу между ботанической и кухней.

**Comment by KIBORG04** [comment]
Лол, какой сверхразум придумал сделать из раковины пруд? Это действительно гениально

**Comment by Morgarim** [comment]
Исправлено, описание просто убрали. Всем спасибо.

**Comment by KIBORG04** [comment]
> Исправлено, описание просто убрали. Всем спасибо.

Никто ничего не изменял, не одного ПРа на эту тему,
