### ISSUE TITLE
У капитана нет доступа к зарплатам

### ISSUE THREAD

**Issue by Morgarim** [TauCetiStation/TauCetiClassic#6165]
Issue reported from  Round ID: 36313 (Tau Ceti Classic II (RU))

Reporting client version: 513.1528

#### Подробное описание проблемы
При попытке взаимодействовать с зарплатами экипажа через ПДА капитана - не отображается список персонала

#### Что должно было произойти
Список персонала должен отображаться, что бы с ним можно было провзаимодействовать. 

#### Что произошло на самом деле
Список экипажа не отображается, будто бы у капитана нет подчинённых. Соответственно, влиять на зарплаты нет возможности. 

#### Как повторить
ПДА капитана > Кнопка финансов > Staff Salary

**Comment by Morgarim** [comment]
Проблема была только в одном раунде. Сегодня всё отображается корректно.

**Comment by LudwigVonChesterfield** [comment]
Был ли этот раунд ревой?
