### ISSUE TITLE
Кухонный нож добавляется в пиццу, вместо того, что бы разрезать её 

### ISSUE THREAD

**Issue by Morgarim** [TauCetiStation/TauCetiClassic#6166]
Issue reported from  Round ID: 36313 (Tau Ceti Classic II (RU))

Reporting client version: 513.1528

#### Подробное описание проблемы
При взаимодействии кухонного нож с пиццей (любой из карго) вместо того, что бы её разрезать, нож добавляется как ингредиент пиццы. 

#### Что должно было произойти
Нож должен разрезать пиццу на несколько частей. 
#### Что произошло на самом деле
Нож кладётся внутрь пиццы.
#### Как повторить
Закажите пиццу из карго, возьмите кухонный нож из автомата повара. Нажмите на пиццу. 
#### Дополнительная информация:
Проверял только с ножами.

**Comment by LudwigVonChesterfield** [comment]
Кликай хармом.
