### ISSUE TITLE
Не совсем правильно работает шахтёрский интерфейс

### ISSUE THREAD

**Issue by Ambassadoing** [TauCetiStation/TauCetiClassic#6173]
Issue reported from  Round ID: 36356 (Tau Ceti Classic II (RU))

Reporting client version: 513.1528

#### Подробное описание проблемы
Шахтёрский интерфейс (HUD) показывает не все клетки с рудой, которые должен показывать (то есть всё, кроме платины)
#### Что должно было произойти
Должен показывать все
#### Что произошло на самом деле
Часть клеток с рудой не показывается (не с платиной).
#### Как повторить
Зайдите за шахтёра и погуляйте по астероиду, потыкайтесь сканером по клеткам. Заметьте, что часть клеток с углём/железом/что-там-у-вас-ещё, которые должны без проблем отображаться, не отмечаются пиктограммой
#### Дополнительная информация:
???

**Comment by KIBORG04** [comment]
Я выпустил примерно 4 фикса на шахту, вероятно, какой-то ещё не не сервере
