### ISSUE TITLE
[Proposal] Изменение платных душевых. 

### ISSUE THREAD

**Issue by Morgarim** [TauCetiStation/TauCetiClassic#6177]
Issue reported from  Round ID: 36374 (Tau Ceti Classic II (RU))

Reporting client version: 513.1528

#### Подробное описание проблемы
За все душевые на станции нужно платить, даже за те, которые находятся в тюрьме и в капитанской. Непонятно чем это обусловлено, с учётом, что вся остальная вода на станции - бесплатная. 

#### Что должно было произойти
Часть душевых нужно сделать платной, а часть бесплатной.

#### Что произошло на самом деле
Зеки не могут помыться, так как у них изымают карточки. Капитан должен платить за душ в собственной каюте. 

#### Как повторить
Подойти в любую душевую кабину - кликнуть на душ.

**Comment by LudwigVonChesterfield** [comment]
> Непонятно чем это обусловлено

капитализмом

> вся остальная вода на станции - бесплатная.

А вода в душе - нет, вот и смирись с этим.
(возможно из-за того что там есть регулировка температуры, и с нужной сноровкой можно вместо крио использовать душевую)

> Зеки не могут помыться, так как у них изымают карточки

а согласно законам не должны, можешь с этим повоевать

**Comment by Morgarim** [comment]
> а согласно законам не должны, можешь с этим повоевать
Зачем им тогда душевые в бриге? 

Я не совсем понимаю, зачем вводить такой костыль, когда можно ограничить регулировку температуры до того уровня, что бы это не работало как крио\работало гораздо слабее.

**Comment by Venngedi** [comment]
Закрывайте. В генетике и в тюрьме душ включается бесплатно.

**Comment by KatoMarika** [comment]
Просили закрыть еще в 2023, все еще требуется закрыть.

**Comment by Chip11-n** [comment]
Исторический момент! Четырёхлетний ишуй объявляется закрытым! Ура товарищи! Мы сделали еще один маленький шажок в продвижении нашего социалистического строя!

**Comment by Morgarim** [comment]
Какой сейчас год? Тау Кита ещё жива?
