### ISSUE TITLE
Капитан не должен тонуть в душевой

### ISSUE THREAD

**Issue by Morgarim** [TauCetiStation/TauCetiClassic#6178]
Issue reported from  Round ID: 36374 (Tau Ceti Classic II (RU))

Reporting client version: 513.1528

#### Подробное описание проблемы
Если капитан решит помыться у себя в душевой - он утонет, так как в душевой нет слива, а один тайтл наполняется крайне быстро.
#### Что должно было произойти
На тайтле под душем, в ванной капитана, должен быть слив. 

#### Что произошло на самом деле
Слива нет, его так же нет в ванной в целом. И даже если капитан не захлебнётся, то зальёт всю свою каюту водой.
#### Как повторить
Помойтесь в капитанской душевой.
#### Дополнительная информация:
Кажется до меня никто не мылся за капитана в душевой, раз проблема существует с момента установки карты.

**Comment by T6751** [comment]
Забавно, #4566 всё ещё актуален
