### ISSUE TITLE
[Proposal] Порт полной разрушимости с ТГ

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#6184]
Многие могут заметить отсутствие возможности сломать абсолютно всё на Тау Ките.
Эту "проблему" уже давно решили на ТГ, обобщив проки ломания вещей(take_damage, bullet_act, внедрение в attackby, и так дальше), позволив ломать всё что можно с крутыми спец. эффектами - машинерия разлетается на её компоненты, стены рушатся в гирдеры, и так далее.

Предлагаю портировать и адаптировать это на Тау Киту.

**План минимум:**
- Портирование https://github.com/tgstation/tgstation/pull/20793, и всех его зависимостей.
- Адаптация под реалии Тау Киты(использование всех тех проков, которые у нас есть, и которые могут наносить вред).
- Проконсультироваться о вопросах баланса возможности сломать всё всем.

**План максимум:**
- Интеграция "уникальных" фич Тау Киты - комбобоевки, свипов/свайпов(Свипы могли бы навешивать дополнительные флаги атаки.)
- Датумизация атак для удобства использования(Создать датум-контейнер для всех параметров атаки - тип урона, сила атаки, флаги атаки(острый, режущий), "ключевые слова"(типо там IS_MAGICAL, IS_HOLY))

**Comment by SpaiR** [comment]
Перед указанным ПРом стоит рассмотреть следующие два:
https://github.com/tgstation/tgstation/pull/20714
https://github.com/tgstation/tgstation/pull/20726

В совокупности они все об одном.

**Comment by Ayuska** [comment]
Если Людук что-то не делает сам, становится страшно.

**Comment by kiVts** [comment]
Это просто невозможно - подумайте размеры работы тут придется (как и всем) вместе работать всем

**Comment by SpaiR** [comment]
> Это просто невозможно 

Литерали три ПРа у каждого из которых вменяемый дифф. Так что не придумывай.

**Comment by Shootnik01** [comment]
Дедчат?

**Comment by KIBORG04** [comment]
А мы разве не сделали её? Почему ишуй открыт? Бабки выплатили?

**Comment by kalazus** [comment]
Я её сделал без кислоты и возможно чего-то ещё. Ну и баунти не особо интересует.

**Comment by LudwigVonChesterfield** [comment]
почему никто не взял деньги

**Comment by maleyvich** [comment]
> почему никто не взял деньги

наверное никто не может

**Comment by volas** [comment]
подарили деньги баунтисоурсу, эх
