### ISSUE TITLE
Проблема с акциями на бирже

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#620]
#### Подробное описание проблемы

Внезапно (за 5 секунд), цена акции одной компании (Амброзия Софтвэйр) взлетела до небес, а после так же стремительно упала:

![scr1](https://cloud.githubusercontent.com/assets/20542000/18847387/e30e144c-844b-11e6-9999-2ff6d2079c43.png)
#### Что должно было произойти

Такого быть не должно.
#### Что произошло на самом деле

Такое случилось.
#### Как повторить

Сесть за биржекомп, подождать (?).
#### Дополнительная информация:

Профит, полученный в ходе торгов:
http://prntscr.com/cmno2x

**Comment by Skyrull** [comment]
Еще встретились одинаковые названия:

![scr2](https://cloud.githubusercontent.com/assets/20542000/18847754/339b6f08-844d-11e6-8771-b85a7cc0da3d.png)

**Comment by Damirrus1** [comment]
Ну ты чо, мы же разбогатели, а ты спалил.

**Comment by Dennok** [comment]
Ну... В этоиже вся соль.
Рандом на рандоме.

**Comment by WallShrabnic** [comment]
Нужно поставить ограничение в цене 1 ед. Акций

**Comment by Raschert0** [comment]
Нет, не нужно

**Comment by Raschert0** [comment]
Да, кстати, пики всё ещё наблюдаются? Я вроде попытался пофиксить это

**Comment by Skyrull** [comment]
Скачков не видел, как и экспорт сканеров в заказах.

**Comment by Raschert0** [comment]
Когда смотрел?

**Comment by Skyrull** [comment]
Сегодня.

**Comment by Skyrull** [comment]
Нет, скачки все же остались:
http://prntscr.com/co89ih

И к тому же снова поломались кнопки "Remove" и "Clear List" в консоли карго.

**Comment by Raschert0** [comment]
Похоже, у нас билдопроблемы, так как на локалке всё нормально

**Comment by Raschert0** [comment]
@Skyrull, есть ещё баг?

**Comment by SpaiR** [comment]
@Skyrull актуально?

**Comment by Skyrull** [comment]
Если только это: http://prntscr.com/d2g7vc

В остальном, скачков замечено больше не было.

**Comment by Skyrull** [comment]
![scr1](https://cloud.githubusercontent.com/assets/20542000/20000722/2656a776-a2a3-11e6-9e70-9df215985ade.png)
