### ISSUE TITLE
Беды с ХУДами.

### ISSUE THREAD

**Issue by CeUvi** [TauCetiStation/TauCetiClassic#6210]
#### Подробное описание проблемы
 - При вырезании майндшилд имлпанта (возможно и других) имплант не пропадает с худа. (секурити худ)
 - Иногда люди просто не показывается на худах. (мед худ, один раз я смог починить это переключением датчиков у чела, раунд #36511)
- За госта в конце раунда иногда не появляется антаг-худ.
#### Что должно было произойти
все должно быть хорошо.
#### Что произошло на самом деле
некие проблемы.
#### Как повторить
поиграть с худами, я думаю.

**Comment by Pimap3** [comment]
Также если шедоулинг затреллит кого-то с майндщилдом или лояльностью, то с худов опять же, лояльность не пропадает

**Comment by kalazus** [comment]
Мед худы никак не отображаются если у человека не установлены датчики (вроде нужен уровень 2+)

**Comment by KIBORG04** [comment]
> Также если шедоулинг затреллит кого-то с майндщилдом или лояльностью, то с худов опять же, лояльность не пропадает

Фэйк. Все работает. Лояльность и не должна пропадать
![image](https://user-images.githubusercontent.com/26389417/95653191-7d4bf400-0aff-11eb-9e2d-73c6b3f12b22.png)

**Comment by GermanSUS** [comment]
Шахтерский худ тоже сломан.
Значек артефакт не пропадает после выкапывания артефакта

**Comment by KIBORG04** [comment]
> Шахтерский худ тоже сломан.
> Значек артефакт не пропадает после выкапывания артефакта

Скорее всего это уже пофикшено. Либо ты пишешь нормально в чем проблема и как её повторить
