### ISSUE TITLE
Почему-то ломается интерфейс

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6237]
#### Подробное описание проблемы
В рандомные моменты времени, окна перестают появляться, кнопки не работают и выделяются жирным, приходится перезаходить
#### Что должно было произойти
Ничего
#### Что произошло на самом деле
Вот это
#### Как повторить
Не знаю.

**Comment by 4310V343k** [comment]
Ну хотя-бы скрин блин

**Comment by LudwigVonChesterfield** [comment]
#6235  ?

**Comment by T6751** [comment]
Вероятно вызвано тестмержем #6235
