### ISSUE TITLE
Консоль вызова шаттла не имеет кнопки вызова шаттла

### ISSUE THREAD

**Issue by d8texe** [TauCetiStation/TauCetiClassic#6241]
![изображение](https://user-images.githubusercontent.com/25967085/96351514-d9e57b00-10cc-11eb-9ffb-a922b7c1fc02.png)

**Comment by LudwigVonChesterfield** [comment]
пожалуйста в следующий раз хотя бы пытайся назвать ишуй как-либо относящеся к проблему

**Comment by d8texe** [comment]
ладно, извиняюсь

**Comment by T6751** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/5990

**Comment by T6751** [comment]
Исправлено
