### ISSUE TITLE
Ддосы через PDA

### ISSUE THREAD

**Issue by d8texe** [TauCetiStation/TauCetiClassic#6245]
Жду фиксов

Так же, через это я мог крашить клиенты.
![гы](https://user-images.githubusercontent.com/25967085/96362691-1d2d0180-1140-11eb-8226-b50d7b1d776d.gif)

**Comment by Ayuska** [comment]
Это красиво.

**Comment by d8texe** [comment]
> 
> 
> Это красиво.

Я старался 
![5791db7e03bbf15611c1643f](https://user-images.githubusercontent.com/25967085/96404362-cc72e280-11eb-11eb-8d3b-4bd60a22e6af.png)
