### ISSUE TITLE
Окно тревог ИИ.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6250]
#### Подробное описание проблемы
Два в одном.
Окно тревог ИИ не открывается при тревогах, если его до этого его не открывали через кнопку худа.
Окно тревог ИИ открывается постоянно, если было открыто через худ и сработала хотя бы одна тревога.
#### Что должно было произойти
Окно открывается и закрывается по клику игрока.
#### Что произошло на самом деле
Окно открывается и закрывается само по себе.
#### Как повторить

- Быть ИИ.
- Открыть окно тревог и закрыть.
- Наслаждаться спамом ассистентов пожарной тревогой.

**Comment by Zmey25** [comment]
Очень мешает. Либо приходится прятать это окно и больше его не использовать
