### ISSUE TITLE
Образцы вирусов ломаются от всего.

### ISSUE THREAD

**Issue by Prusski** [TauCetiStation/TauCetiClassic#6252]
#### Подробное описание проблемы
При нажатии по образцу вируса любым предметом с любым интентом он ломается, что делает игру за вирусолога невероятно стрессовой, потому что из-за пролага или простой невнимательности ты можешь кликнуть по образцу ручкой или бумажкой и он сломается в щи.
#### Что должно было произойти
Ой, я забыл выбросить отчет о вирусе и попытался взять образец. Ну ничего, сейчас положу бумажку на стол и продолжу работать.
#### Что произошло на самом деле
**### С̷̨̗̅̉̈̆У̶̲̌̔̿̿̐̾̈́̕К̸̢͚̻̯͇̭͖̉̇̒͌̍̇̽̀̌͒͜͝А̷̨̧̨̙̞͉̞͕̳̬̪̎̀̎̐̆ ̶̨̧̣̥̳̭͙͕̪̜͈̎͊͂̀̔̈́̀͐  М̵̧̢̣͎̺̟͈̼͋̍͌̀͠ͅͅЕ̴͖̘̰̟̙̏̆̍̿̚͠Н̶̙̹̱̱̂̈̏̀̈̂͂̀͗͐̓̊̉Я̷͉̖̪̜͉͂̌̾   ̶͇̥̟̒͆Э̴̢̥̱̩̙̺͇̯͕͍̦̼̽͗̍͑̍̃̾͌̿̂͗̏̂Т̵̛̱̼̰͆̈́͛́͋̑͐̚͠͝О̵̭̬͎̲̖͇̭̩͉̳̤̭̲̐̈́́̎́̈́̎̕͘ ̴̯͚̤̒̿͋̌̏̄̐̀̍̾͝͠  З̸̪̹̠͖̦̝͝Ӑ̵̪̪̭͓̻͍̀͆Е̸̞̅̇̽͗͊̚Б̸̧̗̦̰͐͂͌̾̇́̚А̵͓͊̀̓̒͘͘Л̶̢̛̈́̾͒̈͋͐̏̈́̎̚͝͝О̴̡̮̞̦̙̦̩͛!̶̥̗̋̇̇̀̀̓͂̈́̐̕͠ ̵̧͇̼̯͉̞͔͋̊̾̊̓͋̈́̓͛͌͛͜  Э̵̝̓̀͐̄͠Т̷̡̩̦̻̥́̎͐̽̐̊̿͘͠А̷͍͓͛ ̵̧̎̄̋̐̃͌͠  Х̸̫̗̼͕͈̹͚̣̥̄̏͒̿̓̀̈́͋̈͊Ӳ̷̣͌͐͌̂́̀̐̊̕͘͝͝Й̷̣͕̽̽̑͗́͝Н̶̧̰͍̯͙͇̗͚̜͖̗̬̑̌̐̓͐̂̈́̕͜Я̵͚̺̝̉̑̈́̃͝ ̷̨̢͕̬̖̠̰̲̬̽͂͛̿ͅО̴̨̛͎͉̩̜̺̌̽̚П̵̛͓͔̫̺͔̪̝̘̦̈̇̌̿̈́̍̋͂̓̚͜͜͜͝Я̴͈̬̹̰͕̗̞̟̱̯̣̠́͋͑͋́̊͗Т̷͇̹͍̖̩͙͒͊̐́̆̓͋́̏̑Ь̵̣̩̘̰̹̉͆̾̈ ̸̛̛̬̽̏̾̓̿͛̕̕͝͠С̶̨̭̼̬͖͕̹͇̹̩̼̱̳͊̍̈́̄͊͐̍Л̶̯̲̱͊̍̒͒̊̚̚͝О̶̨͙̺̦̫͓̥̹͔͎̄ͅМ̷̞͎̼̪͕̝̗̆̍́̆̐͜А̵̧̖̯̬͎̹̭̙̫̯̃̀͑̄̈́̇̋͋̒͒͐͘͜Л̸̨̨̢̛̤̟̥̟͉̘̹́̀̐̈́̚͝А̵̤̃̓́̉̒̍С̴̝̾̾̑́̓̈͆̇̈̍̈́̕Ь̴̗͔̖̗̙̔̔̈́̆͆͑̚  ,̴̧̛͖͎̩̦̗̖͍͓̣͐̀̏͗͐̈́͠ ̷̪̱̠͕̹͂̈́̆͂̕͘̕Ё̶̛̰̙͍̻̦͙͕̮̈̊͒̒̈̍̅̂̆͠Б̸͈͔̺̣̣͕͓̟̥̭͆͒̿̇̄̕̚͝ͅ   ̷̛͚̙̻͙̬͂̈́͐̈́͗̂̕͝͝Т̸̭̥͔͍̤̺̲̳͕̓͑̈͐̾̈́͗̓̅͘͝ͅВ̶̥͙̜̠̮͕̱̮́̏̅̀̏̓̇͑О̷̧̯̅͑̑̌͑͌͂͐̒͐̕͘͘Ю̴͕̩̱͙̣̱͎̃͌͂̃͂̈́͑̚͜ ̴̳̩͚̲̜̰͕͇̺̉̎̓̀͘  М̴̡̫̝̘͚̬̗̄̎̀̀̾͗̔̈́̈͒͘А̷͍̺̄͂̎̈́̎̀̈̚Т̶̢̣̰̱̟͚̩̹̭͎͂͒̈́͗̓́̽̈́̒̿͜ͅЬ̵̨̺͉̠̬̤̽͗͊̅̅͋̈́̕͝͝͝,̴̧̼̪̣͖̫̙͚̫͍̒̊͐ͅ**
#### Как повторить
Поработать вирусологом.
#### Дополнительная информация:
Ну пусть они ломаются хотя бы на харме, пожалуйста.

**Comment by Kortez90** [comment]
Так и есть, но у них шанс сломаться 50%.

**Comment by Tolerantboy** [comment]
Я так тыкал специально ручкой, думал, что так подписать склянку можно будет, а та сломалась. Хорошо, что вирус в той склянке был херовский и его симптомы так ни у кого и не проявились

**Comment by Kortez90** [comment]
> подписать склянку можно будет

Подписать можно, но только лейблером.
