### ISSUE TITLE
ИИ потерял возможность открывать/закрывать аварийные створки

### ISSUE THREAD

**Issue by Prusski** [TauCetiStation/TauCetiClassic#6253]
#### Подробное описание проблемы
Вчера при игре за ИИ я обнаружил, что не могу взаимодействовать с аварийными створками, что очень сильно ограничило мой функционал.
#### Что должно было произойти
Нажал на створку. Подтвердил действие. Закрыл/Открыл.
#### Что произошло на самом деле
Нажал на створку. Подтвердил действие. Тебе пишет, что тебе нужно находиться рядом с ней для взаимодействия.
#### Как повторить
Попытаться открыть створку.

**Comment by Kortez90** [comment]
Не встречал такого. Нужны более подробные данные о методе и условиях повторения.

**Comment by Prusski** [comment]
Вспомнил, что до этого на спутник забежал нинжа и пукнул своим ЭМИ импульсом, после чего снова убежал. Может быть это как-то связано.

**Comment by Tiarv** [comment]
Проверил на текущем билде. ИИ имеет возможность манипулировать аварийными створками.

**Comment by 4310V343k** [comment]
Не актуально
