### ISSUE TITLE
Неисчезающий значок аномальности 

### ISSUE THREAD

**Issue by DedYarick** [TauCetiStation/TauCetiClassic#6257]
#### Подробное описание проблемы
Если выкопать из аномальной породы все ископаемые (с учетом того что в ней нет артефактов) значок "аномальности" не пропадает и продолжает мозолить глаза. 
#### Что должно было произойти
Выкопал все что можно было - значок изчез.
#### Что произошло на самом деле
Выкопал все что можно было - значок остался. 
#### Как повторить
Выкопать из аномальной породы все ископаемые (с учетом того что в ней нет артефактов). 
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/63983146/96589439-3e3b5100-12fe-11eb-9610-9a38d0fc435b.png)
![image](https://user-images.githubusercontent.com/63983146/96589950-dd604880-12fe-11eb-9c3c-134e6ab3179e.png)
![image](https://user-images.githubusercontent.com/63983146/96589978-e5b88380-12fe-11eb-9991-a812651201be.png)

**Comment by KIBORG04** [comment]
> Поиграть за ксеноархеолога

Да, давай каждый кодер будет играть в игру по 3 часа в день и до всего сам додумываться. Сложно написать полную цепочку действий, чтобы прям пронумеровано было?

**Comment by DedYarick** [comment]
> > Поиграть за ксеноархеолога
> 
> Да, давай каждый кодер будет играть в игру по 3 часа в день и до всего сам додумываться. Сложно написать полную цепочку действий, чтобы прям пронумеровано было?

Да тут вроде... В подробном описании проблемы все написано.

**Comment by KIBORG04** [comment]
Ниче непонятно. Я не имею большого опыта игры на ксеноархеологе, а что знал уже забыл. Я незнаю, что такое у тебя на самом последнем скриншоте. Я незнаю чем ты сканируешь, я незнаю что ты выкапываешь. Какие-то зацепки, которые позволят мне понять каким образом ты выкопал, чем выкопал, что написалось после выкопки и тд..

**Comment by DedYarick** [comment]
> Ниче непонятно. Я не имею большого опыта игры на ксеноархеологе, а что знал уже забыл. Я незнаю, что такое у тебя на самом последнем скриншоте. Я незнаю чем ты сканируешь, я незнаю что ты выкапываешь. Какие-то зацепки, которые позволят мне понять каким образом ты выкопал, чем выкопал, что написалось после выкопки и тд..

Все делаю по вики, вскапываю Excavation Pick Set и Hand Pickaxe если оно того требует, сканирую Depth Analysis Scanner, периодически для проверки использую Measuring Tape.
