### ISSUE TITLE
Робопаук сломан

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6258]
#### Подробное описание проблемы
Когда ты робопаук, ты не можешь двигаться и говорить
#### Что должно было произойти
Ты можешь двигаться и говорить
#### Что произошло на самом деле
Ты не можешь двигаться и говорить
#### Как повторить
Стать робопауком
#### Дополнительная информация:
Я был боргом, меня сломали, полетал некоторое время гостом, потом вижу что мой мозг засунули в робо паука, возвращаюсь в тело, а сделать ничего не могу

**Comment by Akellazp** [comment]
Кажется робопаук вообще находится без сознания всё время

**Comment by Kortez90** [comment]
Починился?

**Comment by Akellazp** [comment]
Нет. Похоже проблема не в самих робопауках, а конкретно в моей ситуации что-то сломалось

**Comment by 4310V343k** [comment]
> Нет. Похоже проблема не в самих робопауках, а конкретно в моей ситуации что-то сломалось

Но ведь сломалось

**Comment by LudwigVonChesterfield** [comment]
Это может быть связано с тем что симплмобы когда ты выходишь из раунда засыпают навсегда?
