### ISSUE TITLE
Кляп не работает на мага

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#626]
#### Подробное описание проблемы

Кляп не препятствует использованию спелов мага.
#### Что должно было произойти

Он  не должен иметь возможности их использовать.
#### Что произошло на самом деле

Ему пофиг на кляп.
#### Как повторить

Нацепить на мага кляп из мед.блока
#### Дополнительная информация:

Судя по механу, маг сначала произносит ключевые слова, а зачем происходит то или иное действие. А кляп не дает возможности произносить слова.

**Comment by Raschert0** [comment]
Не смог повторить. Кляп отлично помогает от мага. Вы точно кляп надевали а не повязку на глаза?

**Comment by SpaiR** [comment]
@Skippeer12 Так баг есть или нет?
