### ISSUE TITLE
Пуш все еще ломает грабы

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6262]
#### Подробное описание проблемы
Кукла в третьем грабе (Естественно после того как пройдет очень долгий стан) может одним пушем избавится от захвата, что сводит на нет удержание заложников.
#### Что должно было произойти
Кукла не может просто так пушнуть из третьего захвата
#### Что произошло на самом деле
Может.
#### Как повторить
попадитесь в третий граб, надейтесь что ваш оппонент слоупок, когда сойдет стан толкните его.

**Comment by LudwigVonChesterfield** [comment]
Ещё можно: поднимать вещи, стрелять вещами, бить вещами, хармить...

Это точно не проблема того, что стан от третьего граба почему-то временный?

**Comment by T6751** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/5601
