### ISSUE TITLE
Убрать кнопку Ghost для игроков

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6281]
#### Подробное описание проблемы
игроки любят гостаться когда в их игре и маняролеплее что то идет не так как хотелось бы. Арестовали шиткурити а ты роль? Гостаемся и ноем в дедчат какие все плохие. Режим малф? Гостаемся прям сразу, даже не идем в крио. Короче надо выпилить кнопку, чтобы игроки не могли гостаться, а могли лишь играть, или не играть. (Если ты умер, то гостаться можо, ок?)
#### Что должно было произойти
Игроки учатся доигрывать ситуацию до конца, ведь на горящей жопе гостануться и сидеть в дедчатике не выйдет. (можно будет только ливнуть и перезайти через некоторое время)
#### Что произошло на самом деле
дурачки в знак протеста против чего нибудь гостаются а потом пишут в дедчат что морган жеймс или чисто теоретический Карл Кузнецов шитсек и фашист
#### Как повторить
Арестуйте не очень робастную роль. 
Потащите на допрос
Z-z-z...

**Comment by Zmey25** [comment]
Такие предложения через форум

**Comment by Kortez90** [comment]
К тому же, механом резать вещи, которые решаются через молоток(банхаммер) не круто. Если за тебя все будет делать механ, зачем тогда ты нужен?

**Comment by Ahion** [comment]
Такие проблемы должны решаться диалогом администрации с игроком, а возможность уйти в госты должна остаться.

**Comment by LudwigVonChesterfield** [comment]
@Kortez90 он уже не педаль, и он не нужен.

@Motzord то что человек не сможет гостануться когда его арестовали по его мнению ни за что не значит что он будет отыгрывать ситуацию до конца. В крайнем случае он просто отойдет от компьютера пить чай, вместо того что ему не нравится. Или просто игру закроет. Что, запретишь ему и окна закрывать?

**Comment by LudwigVonChesterfield** [comment]
Но да, предложение на 10 строк вместо ПР-а реализовывать ишуем на гитхабе пепега

**Comment by BesumniiChebureck** [comment]
А  почему это баг, а не пропорсал....

**Comment by Chip11-n** [comment]
Вроде как решили на форуме, что нам такое не нужно. Можно закрывать?

**Comment by Venngedi** [comment]
![image](https://github.com/user-attachments/assets/db30d473-797d-44ae-8a68-1139d80e8c62)
