### ISSUE TITLE
Баг с позитронкой

### ISSUE THREAD

**Issue by SashkaMalinka** [TauCetiStation/TauCetiClassic#6290]
### Подробное описание проблемы
При перезаходе на сервер будучи позитронкой в мехе проподает чат и управление

#### Что произошло на самом деле
Пропало управление и чат стал ...You almost hear someone talking...  и ... You can almost hear something ...

#### Как повторить
Стать позитронкой, загрузится в мех, перезайти на серве

#### Дополнительная информация:
Issue reported from  Round ID: 36824 (Tau Ceti Classic II (RU))
Testmerges: ```#6189 #6207 ```
Reporting client version: 513.1536

**Comment by KIBORG04** [comment]
Почему вообще всем мобам не добавить насильное просыпание в `login()`, как у божка?

**Comment by SashkaMalinka** [comment]
Скрин от захода и чуть дальше 
![image](https://user-images.githubusercontent.com/63392331/97231247-460e6000-17ec-11eb-92d3-2d02bcc6531c.png)

**Comment by Kortez90** [comment]
Такая же фигня с борерами в трубе.

**Comment by SashkaMalinka** [comment]
Открылась новая информация что если просто перезайти за позитронку то будет тоже самое

**Comment by T6751** [comment]
#615
