### ISSUE TITLE
tgui-like интерфейс криминалиста

### ISSUE THREAD

**Issue by atik1n** [TauCetiStation/TauCetiClassic#6292]
#### Подробное описание проблемы
В части мест интерфейса пробиваются остатки прежней роскоши, а именно `<a` и так далее по списку
#### Что должно было произойти
Всё красиво
#### Что произошло на самом деле
Код разметки вылезает в интерфейс
#### Как повторить
Посмотреть консольку криминалиста

**Comment by KIBORG04** [comment]
Я не нашел ни одного сломанного тега, разве что были в кнопках непонятные скобочки `{Text}`, но, мб, так и было задумано.
Мы ведь про один и тот же интерфейс? 
![image](https://user-images.githubusercontent.com/26389417/97341865-a35eeb80-1896-11eb-9cbf-60310377d708.png)

**Comment by atik1n** [comment]
У меня как раз у этих кнопок и ломалось /shrug

**Comment by KIBORG04** [comment]
А, ятестил на не той ветке
