### ISSUE TITLE
"Toggle mode" не обновляет спрайт капельницы.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6297]
#### Подробное описание проблемы
У капельницы при нажатии на "Toggle mode" спрайт не меняется.
#### Что должно было произойти
Спрайт меняется.
#### Что произошло на самом деле
Спрайт меняется только после того, как туда вставили контейнер.
#### Как повторить
Попробовать переключить режим капельницы без контейнера.
#### Дополнительная информация:
![GIF 28 10 2020 0-24-51](https://user-images.githubusercontent.com/36198983/97363735-11fe7200-18b4-11eb-8e9f-2ac2a7be5b30.gif)

**Comment by TungstenOctopus** [comment]
Кстати, если там действительно "Toggle mod", то по идее должен быть "Toggle mode"
