### ISSUE TITLE
Дюп синди-боргов

### ISSUE THREAD

**Issue by NeOchenLord** [TauCetiStation/TauCetiClassic#6298]
#### Подробное описание проблемы
Есть возможность дюпать боргов нюки

#### Что должно было произойти
Один спавнер берёт одного госта и делает одного борга

#### Что произошло на самом деле
Один спавнер берёт несколько гостов и делает несколько боргов

#### Как повторить
До окончания времени ожидания гостов несколько раз активировать спавнер в руке.

**Comment by KIBORG04** [comment]
Полагаю, это из-за введенного тильдой pollGhostCandidate или подобного

**Comment by T6751** [comment]
>Полагаю, это из-за введенного тильдой pollGhostCandidate или подобного

А до этого нельзя было так сделать, хмм?

**Comment by KIBORG04** [comment]
> А до этого нельзя было так сделать значит, хмм?

Вроде, не было ишью о бесконечных синди боргах, значит нельзя было.

**Comment by EdlerN** [comment]
> А до этого нельзя было так сделать значит, хмм?

Раньше спавнило только одного всегда. Вероятно там была какая-то заглушка. А с изменением метода - заглушка перестала работать.

**Comment by KIBORG04** [comment]
Когда я рефакторил старый код призывания на новый, то я не трогал синдиборгов, ибо тогда ктрл + ф их не нашел, либо они уже были изменены.
