### ISSUE TITLE
Режим соковыжимания в All-In-One Grinder не работает.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#630]
#### Подробное описание проблемы
Режим соковыжимания в All-In-One Grinder не работает.
#### Что должно было произойти
Должен был вижатса сок.
#### Что произошло на самом деле
Ничего.
#### Как повторить
Попрорбовать вижать сок.
#### Дополнительная информация:
Я попытался выжать сок из яблок и ничего не вышло.

**Comment by Damirrus1** [comment]
Работает, но криво. Из ягодок получается, но если еще попробовать то не пополнится.

**Comment by Dennok** [comment]
Хм. Из томата вышло.

**Comment by SpaiR** [comment]
https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/game/machinery/kitchen/juicer.dm#L14
Список всех возможных соков. Яблочный сок и так далее - нужно добавлять.

**Comment by Dennok** [comment]
Да, действительно. Можно написать что не для всего есть сок, но врятли кто то это будет пилить.
