### ISSUE TITLE
Ультимейт факап на хеллоуин: Дело о пропавших спрайтах костюмов

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#6308]
#### Подробное описание проблемы
Одёжа в спукомате не имеет спрайтов. Купленная одёжа - тоже без спрайтов.
#### Что должно было произойти
![image](https://user-images.githubusercontent.com/42682553/97748494-9a705300-1afe-11eb-8065-df477f440197.png)

#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/42682553/97748717-f509af00-1afe-11eb-89e8-6e36222b64d6.png)

#### Как повторить
Просто глянуть в костюмы.
#### Дополнительная информация:
Issue reported from  Round ID: 36903 (Tau Ceti Classic II (RU))
Testmerges: ```#6207 #6214 #6280 #6302 #6306 ```
Reporting client version: 513.1536

P.S.: МУАХАХАХА ЩА КАК ЗААБУЗЮ /me достаёт свой хамелеон-проектор

**Comment by T6751** [comment]
Должно быть уже исправлено. Просто обновить нужно сервера
