### ISSUE TITLE
[Proposal] Верните красный, красивый шлем пожарного

### ISSUE THREAD

**Issue by cool20141** [TauCetiStation/TauCetiClassic#6314]
#### Подробное описание проблемы
Теперь вместо красного шлема пожарного вот такой
![image](https://user-images.githubusercontent.com/53309265/97807554-95341500-1c72-11eb-92a4-46fad88916ba.png)
Красный надо
Этот не надо

**Comment by 4310V343k** [comment]
👀

**Comment by cool20141** [comment]
:wink:
