### ISSUE TITLE
Научный борг не способен найти артефакты без HUD'ов.

### ISSUE THREAD

**Issue by Ro2tCrab** [TauCetiStation/TauCetiClassic#6317]
#### Подробное описание проблемы
Научный борг обделён шахтёрским HUD'ом, который ему нужен для работы.
#### Что должно было произойти
-
#### Что произошло на самом деле
Научный борг не может найти артефакты и добыть их.
#### Как повторить
Попытайтесь найти артефакт с помощью научного киборга.

**Comment by Kortez90** [comment]
В графе "Что должно произойти" указана пустота.
Борг без худа нашел пустоту.
Проблема решена. Зачем issue?

**Comment by KIBORG04** [comment]
Был ли он вообще? Научный борг - не шахтер, чтобы на астеройде тусоваться и искать артефакты.

**Comment by KIBORG04** [comment]
Вообщем-то да. Этих худов и раньше не было, а значит я ничего не ломал

**Comment by Ro2tCrab** [comment]
При чём же тут шахтёр? Мы говорим о ксеноархеологии.
 Борг способен полноценно заниматся ксеноархеологией, но без HUD'ов он потерял возможность самостоятельно находить артефакты.

**Comment by KIBORG04** [comment]
Способен заниматься и только способен. Но насколько позволяют мои навыки сыщика, майнерских худов у саентс борга примерно никогда не было, а значит, это на грани бага и пропосала
