### ISSUE TITLE
Мезонки опять параша

### ISSUE THREAD

**Issue by 4310V343k** [TauCetiStation/TauCetiClassic#6322]
#### Подробное описание проблемы
тайтл
#### Что должно было произойти
Мезонки такие же красивые, как после фикса ВинтерШока
#### Что произошло на самом деле
Что-то опять сделало их вырвиглазными
#### Как повторить
Одеть мезонки

**Comment by Kortez90** [comment]
И что с ними не так? Нужен скрин.

**Comment by 4310V343k** [comment]
Берегите глаза (мезонки нужны для просмотра турфов за стенами, но даже с этим они не справляются(см. теха))
![image](https://user-images.githubusercontent.com/56449763/97953399-67a1b580-1db1-11eb-8f00-46e344dbe6e3.png)
Вот как "отображаются" руды у майнборга
![image](https://user-images.githubusercontent.com/56449763/97953422-8142fd00-1db1-11eb-9523-cfdbda401ed6.png)![image](https://user-images.githubusercontent.com/56449763/97953430-83a55700-1db1-11eb-835f-64bb29d2f755.png)|
![image](https://user-images.githubusercontent.com/56449763/97953433-856f1a80-1db1-11eb-8d56-13bef7d9d5a5.png)![image](https://user-images.githubusercontent.com/56449763/97953435-86a04780-1db1-11eb-9038-6130ca10ed92.png)

**Comment by Sakuya-Izayoi** [comment]
Пофикшено #6572
