### ISSUE TITLE
Самооткрывающееся окно.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6323]
#### Подробное описание проблемы
![GIF 03 11 2020 8-09-40](https://user-images.githubusercontent.com/36198983/97954002-4cd04080-1db3-11eb-89cc-5a4c973b21d6.gif)
#### Что должно было произойти
Нажал на крестик - закрылось.
#### Что произошло на самом деле
Нажал на крестик - закрылось, после чего открылось снова.
#### Как повторить
Потыкать в консоль топливных инъекторов, когда те активны.

**Comment by 4310V343k** [comment]
Красивая гифка, мне нравится

**Comment by Akellazp** [comment]
такая же вигня с тревогами за ии

**Comment by Tiarv** [comment]
Для мусорки чинили тут 
https://github.com/TauCetiStation/TauCetiClassic/pull/6190

**Comment by 4310V343k** [comment]
> Для мусорки чинили тут
> #6190

Как это относится к этому иссую?

**Comment by Kortez90** [comment]
> 
> 
> Для мусорки чинили тут
> #6190

https://github.com/TauCetiStation/TauCetiClassic/blob/436076abe50f7e569b9595c48d29c9448cc9edcb/code/modules/power/fusion/fuel_assembly/fuel_control.dm#L61-L64

**Comment by 4310V343k** [comment]
> > Для мусорки чинили тут
> > #6190
> 
> https://github.com/TauCetiStation/TauCetiClassic/blob/436076abe50f7e569b9595c48d29c9448cc9edcb/code/modules/power/fusion/fuel_assembly/fuel_control.dm#L81
> 
> > Как это относится к этому иссую?
> 
> Напрямую.

Мусорка. К ПРу про фуел инжектор
