### ISSUE TITLE
Ccылки сломались

### ISSUE THREAD

**Issue by cool20141** [TauCetiStation/TauCetiClassic#6327]
#### Подробное описание проблемы
В игре есть ссылки, например, на пры в тм, при нажатии на них я перехожу не на github.com, а на %22https//github.com" (Ну что-то такое)
#### Что должно было произойти
Должен был перейти на нужную ссылку
#### Что произошло на самом деле
Перешел на какую-то странную, пришлось ручками чинить
#### Как повторить
Нажать на ссылку
#### Дополнительная информация:
Работает также с ссылками, оставленными игроками(например, на ютуб-видео какое-нибудь)

**Comment by Kortez90** [comment]
![GIF 04 11 2020 10-51-45](https://user-images.githubusercontent.com/36198983/98083797-ec610200-1e8b-11eb-941f-3c47b8a7539e.gif)

**Comment by 4310V343k** [comment]
Хоть где-то нормально описали в чем проблема, спасибо папаша

**Comment by 4310V343k** [comment]
![IMG_20201104_110612.jpg](https://user-images.githubusercontent.com/56449763/98085025-cb011580-1e8d-11eb-8c73-f8b5475bccfc.jpg)

**Comment by T6751** [comment]
Да, нужно просто обновить бьенд у себя

http://www.byond.com/docs/notes/513.html
