### ISSUE TITLE
Госты не могут писать в ООК даже после конца раунда

### ISSUE THREAD

**Issue by 4310V343k** [TauCetiStation/TauCetiClassic#6328]
#### Подробное описание проблемы
Госты не могут писать в ООК/ЛООК
#### Что должно было произойти
OOC: Remindme: моцорд фейлота
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/56449763/98121247-1b916680-1ec0-11eb-948d-0c7a0c365c8a.png)
#### Как повторить
Нажать Observe в лобби, дождаться конца раунда, попытаться что-либо сказать в оок

**Comment by CeUvi** [comment]
Это педаль выключила.

**Comment by 4310V343k** [comment]
Значит пошёл писать анпедал 😡

**Comment by BesumniiChebureck** [comment]
Так ты ишуе то закрой...
