### ISSUE TITLE
У ИИ и компьютера тревог разные данные.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6342]
#### Подробное описание проблемы
![GIF 09 11 2020 16-00-28](https://user-images.githubusercontent.com/36198983/98544335-e6f92280-22a4-11eb-8d68-b2ddc95a39a5.gif)

#### Что должно было произойти
Данные одинаковы.
#### Что произошло на самом деле
Данные разные.
#### Как повторить

- Зайти ИИ.
- Ткнуть в компьютер станции.
- Ткнуть на кнопку тревог в худе при тревогах.

**Comment by 4310V343k** [comment]
Вроде дубликат
