### ISSUE TITLE
Бесконечная занятость куклы

### ISSUE THREAD

**Issue by Pimap3** [TauCetiStation/TauCetiClassic#6346]
#### Подробное описание проблемы
После нажатия бумажкой на хелпе по глазам другой куклы, мой персонаж забагался и не мог делать многие действия, например положить на кровать клоуна
#### Что должно было произойти
You buckled Joker to the roller bed
#### Что произошло на самом деле
You are busy. Please close or cancel your action
#### Как повторить
тыкнуть бумажкой по глазам на хелпе другой кукле
#### Дополнительная информация:
Round ID#37096

**Comment by Kortez90** [comment]
> тыкнуть бумажкой по глазам на хелпе другой кукле

![GIF 10 11 2020 20-03-09](https://user-images.githubusercontent.com/36198983/98706447-e8534980-238f-11eb-9e36-264559861270.gif)

Need more data.

**Comment by Akellazp** [comment]
Это связано с боевкой а не тыканьем бумажкой
