### ISSUE TITLE
IPC не может бегать, после того как его полностью отремонтировали.

### ISSUE THREAD

**Issue by Lexanx** [TauCetiStation/TauCetiClassic#6352]
#### Подробное описание проблемы
Если СПУ настрелять в грудь с летала, огнестрела. А потом вытащить шрапнельку, полностью отремонтировать, включая внутренние органы. То способность бегать не вернется. Он будет ходить как будто еще ранен
#### Что должно было произойти
Если полностью отремонтировать СПУ, он должен бегать, а не ходить
#### Что произошло на самом деле
https://i.gyazo.com/8b55e640f605fc19c91a043bc66f2c59.mp4 - Настрелянный, и отремонтированный полностью СПУ, передвигается медленно.
https://i.gyazo.com/865ec6a127464e28e22c5b09af2d99c3.mp4 - Не тронутый, СПУ
#### Как повторить
Выстрелить в СПУ с летала, почти целую обойму. После чего полностью отремонтировать. 
#### Дополнительная информация:
Я не смог понять, что не так с ним. Но исправляется только через rejuvinate.
То есть где-то, что то не обновляется/сбрасывается. После полного ремонта.
Буду рад даже любом подсказкам как починить это.

**Comment by Kortez90** [comment]
Только что проверил. Расстрелял из глока магазин боевых пуль, вытащил шрапнель, починил спу. Бегает, как и должен.

**Comment by Lexanx** [comment]
> Только что проверил. Расстрелял из глока магазин боевых пуль, вытащил шрапнель, починил спу. Бегает, как и должен.

Это не всегда бывает. У меня в игре несколько раз случалось. (Вчера тоже было)
И вот на локалке смог тот же результат воспроизвести. Почему так, не знаю

**Comment by Kortez90** [comment]
Проблема правда есть, только она глубже.
После смерти и восстановлении спу через извлечение позитронки одна спу не слышала, а другая долго бегала. Возможно проблема в уроне позитронки, который не лечится.

**Comment by Kortez90** [comment]
@Lexanx 
Попробуй такой порядок действий.

- Заспавнить спу.
- Одеть спу.
- Избить спу в голову армблейдом генокрада, но не отрывать ее.
- Избить спу в грудь армблейдом генокрада до смерти.
- Выйти из тела спу.
- Зайти обратно.
- Починить весь наружный урон.
- Починить органы. (Спорное действие.)
- Извлечь позитронку.
- Засунуть обратно.
- Починить органы.

Если это вызовет похожие баги, вроде невозможности бегать, то дело в уроне по позитронке и это можно исправить костылем в одну строчку, убирая урон по позитронке, во время ее установки в спу.

**Comment by Kortez90** [comment]
Все. Нашел тот гадкий прок, который не давал бегать после ремонта и не сбрасывался после операции - `shock_stage`. Чини.
