### ISSUE TITLE
Предметы кражи в импланте сжатия не засчитываются в гринтексте

### ISSUE THREAD

**Issue by ChewedGum** [TauCetiStation/TauCetiClassic#6356]
#### Подробное описание проблемы
Если трейтор будет держать вещи которые должен украсть внутри импланта сжатия в момент окончания раунда, то задачу на их кражу не засчитает в гринтексте.
#### Что должно было произойти
Допустим, цель на трусы капитана. Прячем их в имплант, садимся на шатл отбытия, прилетаем на ЦК и в гринтексте указывается что успешно выкрали их.
#### Что произошло на самом деле
Задачку не засчитало за выполненную.
#### Как повторить
Получить триторку, украсть предмет-цель, спрятать в имплант и вывезти со смены.

**Comment by Kortez90** [comment]
Duplicate of #1249.
