### ISSUE TITLE
Новый Say на TGUI

### ISSUE THREAD

**Issue by TheLustOfBlood** [TauCetiStation/TauCetiClassic#6359]
#### Подробное описание проблемы

Во-первых, теперь окно иц чата открывается с некой задержкой, сами буквы проявляются также с задержкой, что весьма неприятно. 
(не исключаю что проблема в сырости мерджа, в моём железе или пинге, но раньше чат работал нормально) 
Во-вторых, если быстро сказать что-то два раза то может произойти такой казус, при подтверждении второго предложения выйдут совершенно другие слова. 

#### Что должно было произойти

Solar Deneck asks, "Его разорвало?" 

Кукланейм says, "Похоже" 

Solar Deneck says, "Понял" 

#### Что произошло на самом деле

Solar Deneck asks, "Его разорвало?" 

Кукланейм says, "Похоже" 

Solar Deneck asks, "Его разорвало?"

#### Как повторить

Быстро сказать две фразы. 
Печатать в новом Say-окне

**Comment by Kortez90** [comment]
#6341.

**Comment by KIBORG04** [comment]
#6341
