### ISSUE TITLE
Шкаф можно спрятать за слипером

### ISSUE THREAD

**Issue by atik1n** [TauCetiStation/TauCetiClassic#6373]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/14612180/99197293-b0d70980-27a2-11eb-8e43-cd5340e50639.png)
#### Что должно было произойти
Шкаф нельзя спрятать за слипер
#### Что произошло на самом деле
Шкаф запрятался
#### Как повторить
Пихнуть шкаф в слипер на шаттле

**Comment by 4310V343k** [comment]
Почему нельзя

**Comment by Kortez90** [comment]
Потому что это машинерия, через которую нельзя ходить вообще. Даже людям. Залезать внутрь - можно. Ходить сквозь - нет.
