### ISSUE TITLE
Орбит трупов в морге ломает камеру госта.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6375]
#### Подробное описание проблемы
Если орбитить труп, который пихнули в морг, то происходит это.
![GIF 16 11 2020 13-40-55](https://user-images.githubusercontent.com/36198983/99243328-96884480-2811-11eb-8ac6-4a8c1a60a18f.gif)

#### Что должно было произойти
На госта не накладывается обзор в одну клетку.
#### Что произошло на самом деле
Ю-ху, дырка.
#### Как повторить

- Орбитнуть труп.
- Сунуть труп в ячейку морга.

#### Дополнительная информация:
#5063
#3233

**Comment by 4310V343k** [comment]
Уже второй дубликат, ты это знаешь, НО ЗАНОВО СОЗДАЕШЬ ИШУИ

**Comment by Kortez90** [comment]
Да я только вспомнил, что они вообще были. Их надо освежить.
