### ISSUE TITLE
Не выдаются кодовые слова

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6379]
#### Подробное описание проблемы
При выпадении тритора могут не выдаться кодовые слова
#### Что должно было произойти
Есть кодовые слова
#### Что произошло на самом деле
Нет кодовых слов
#### Как повторить
Стать тритором
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/47355061/99411622-7da88d80-28fc-11eb-8820-a6a1a1417ee8.png)
#37207

**Comment by KIBORG04** [comment]
Это не баг
```
if(prob(80))
	var/code_phrase = "<b>Code Phrase</b>: [codewords2string(global.syndicate_code_phrase)]"

if(prob(80))
	var/code_response = "<b>Code Response</b>: [codewords2string(global.syndicate_code_response)]"
```
