### ISSUE TITLE
Broken Mine-Science Shuttle Console

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#638]
#### Подробное описание проблемы

Если повредить стекло на терминале управления шаттлом, его уже не починить - с ним все еще можно взаимодействовать, даже с отверткой в активной руке. Тем не менее, шаттл не отправляется.
#### Что должно было произойти

Терминал не должен работать. При помощи отвертки должно сниматься стекло.
#### Что произошло на самом деле

Сломанный терминал можно использовать. С отверткой тоже открывается окно терминала.
#### Как повторить

Выстрелить с лазера в терминал. Ну или сломать его как-нибудь еще.

**Comment by Damirrus1** [comment]
Только что проверил - все нормально работает.
<img src="http://linkme.ufanet.ru/images/d58bc16f91768c5b44f36817fea43b9e.png" width="152" height="140" alt="1.png" title="1.png"/>

**Comment by Raschert0** [comment]
А, я ж её фиксил, но почему-то забыл закрыть ишью

**Comment by igigin** [comment]
Ещё бы рефенс на то где ты это фиксил.

**Comment by Raschert0** [comment]
#653

**Comment by Raschert0** [comment]
Ай, не то #638

**Comment by Raschert0** [comment]
#655 потом с десктопа почищу
