### ISSUE TITLE
Баг соединения Тобразной трубы.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#639]
#### Подробное описание проблемы

При подсоединении к Тобразной трубе труб с запада и потом юга вписывает южную трубу в две переменные, когда должно записывать только в одну.
#### Как повторить

прикрутить трубы как показано на скрине
#### Дополнительная информация:

![2016-10-03_12-56-32](https://cloud.githubusercontent.com/assets/7734424/19033861/48488f5a-8969-11e6-9d2e-c5cab52ffea4.png)

**Comment by ZVee** [comment]
>Какие таги?

Под переменной tag.

**Comment by Skippeer12** [comment]
Вот это наверное тоже закрывай, Игигил.
