### ISSUE TITLE
Mind_transfer мага работает с IPC.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6395]
#### Подробное описание проблемы
Похоже, маг может прыгнуть с помощью спелла в спу и стать техно-магом. Сомневаюсь, что это хорошо.
В проверка у спелла, в списке разрешенных существ, числились классы `human` и `monkey`. А IPC спавнятся на старте с классом `/mob/living/carbon/human`. В других местах этот список, вроде бы, не дополнялся.
#### Что должно было произойти
Маг не может прыгнуть в спу.
#### Что произошло на самом деле
![tehnomagiya 1](https://user-images.githubusercontent.com/36198983/99878689-44cc2980-2c18-11eb-9d6c-e0acab9bb659.jpg)
#### Как повторить
Попытаться прыгнуть с помощью спелла в спу с игроком внутри.

**Comment by Akellazp** [comment]
Ну это же МаГиЯ

**Comment by Kortez90** [comment]
Ты хочешь, чтобы за тобой бегал почти неубиваемый маг? Хочешь?

**Comment by KIBORG04** [comment]
Который умирает от ионки

**Comment by atik1n** [comment]
У нас есть СПУ маги. Не вижу проблемы.

**Comment by Kortez90** [comment]
Тогда нужно разрешить СПУ играть магами на уровне режима.

**Comment by atik1n** [comment]
А они уже играют, у них никто не отбирал возможности

**Comment by Kortez90** [comment]
Ну тогда ладно.

**Comment by UsadoSmokk** [comment]
> А они уже играют, у них никто не отбирал возможности

верни возможность играть за хопа....
