### ISSUE TITLE
Пересбор консоли роботики

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6397]
#### Подробное описание проблемы
Если пересобрать консоль роботики, используя ту же плату, то вместо консоли роботики появится консоль исследований которая стоит в лаборатории
#### Что должно было произойти
Консоль осталась сама собой
#### Что произошло на самом деле
Консоль стала консолью исследований
#### Как повторить
Пересобрать консоль в роботике
#### Дополнительная информация:
Issue reported from  Round ID: 37283 (Tau Ceti Classic II (RU))
Testmerges: ```No test merges```
Reporting client version: 513.1536

**Comment by Kortez90** [comment]
Какую конкретно консоль?

**Comment by 4310V343k** [comment]
> Какую конкретно консоль?
> Хотя это не особо важно. Компьютер в робототехнике - муляж, грубо говоря. Экземпляр консоли исследований, который не имеет платы для строительства и существует в единственном экземпляре.

Потыкав на плату консоли ты переключаешь её между РНД/Роботикой/Шахтёркой
Доброе утро

**Comment by Kortez90** [comment]
Так плата едина. Тут нет бага.

**Comment by Kortez90** [comment]
Провел несколько тестов и проблемы не выявил. При раскручивании консоли в робототехнике появляется плата с нужным путем.

**Comment by LudwigVonChesterfield** [comment]
Не восспроизводится.
