### ISSUE TITLE
Куча повторяющихся рантаймов при взрыве меха.

### ISSUE THREAD

**Issue by BiQndy** [TauCetiStation/TauCetiClassic#6401]
#### Подробное описание проблемы
При взрыве Абсолютно любого меха, хоть Одиссея или Гигакса, выскакивает фигова туча рантаймов
![dreamseeker_ZHr50XrMcN](https://user-images.githubusercontent.com/43725089/99904517-5545d800-2cdc-11eb-9156-c81eab8cab98.png)

#### Что должно было произойти
Мех спокойно взорвался
#### Что произошло на самом деле
Мех взорвался и вызывает много рантаймов, вызывая лагги
#### Как повторить
Взять абсолютно любой мех и уничтожить его
#### Дополнительная информация:
Рантаймы, скорее всего, связаны с тем, что при взрыве появляется новый обьект - останки меха, но по прежнему продолжается вызов функций, которые берут Аиртанк у меха, которого, по сути, уже нет.
Фото рантаймов для быстрого нахождения:
![dreamseeker_BbgmLaOjuM](https://user-images.githubusercontent.com/43725089/99904526-6393f400-2cdc-11eb-9e92-cf5d7fc2cb5e.png)

![hkbaTITTAs](https://user-images.githubusercontent.com/43725089/99904531-68f13e80-2cdc-11eb-8e86-ae0fafb1248e.png)

**Comment by Kortez90** [comment]
У баков меха отдельный датум процессинга, который нигде не останавливается.
