### ISSUE TITLE
Не работает визуализация Электрификации двери у ИИ. (Нет значка молнии на двери)

### ISSUE THREAD

**Issue by Starcoding** [TauCetiStation/TauCetiClassic#6405]
#### Подробное описание проблемы
При электрификации дверей, (ALT+Click, либо через настройки двери - Просто клик по двери) не показывает значок молнии.
#### Что должно было произойти
На двери появляется спрайт молнии.
#### Что произошло на самом деле
Не появился спрайт.
#### Как повторить
Зайти за ИИ и попробовать электрифицировать дверь.

**Comment by 4310V343k** [comment]
Сенсоры включены были?

**Comment by Starcoding** [comment]
Нет, не были. Думаю можно закрывать тикет.
