### ISSUE TITLE
Конструкты удаляют ящики.

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#6408]
## Подробное описание проблемы
Конструкты культа ломают ящики вместе со всем содержимым.
#### Что должно было произойти
Ящик сломался, содержимое выпало.
#### Что произошло на самом деле
Всё содержимое ящика удалилось вместе с вещами и людьми внутри.
#### Как повторить
Запертый или заваренный ящик ударить конструктом культа.
#### Дополнительная информация:
Если сломать не запертый ящик - содержимое сохраняется.

**Comment by Kortez90** [comment]
Любые симпл мобы с юзером внутри, которые бьют ящики - удаляют их. Правда, перед удалением они открываются и вещи удаляться не должны.
