### ISSUE TITLE
Предмет без текстурке в вендомате клоуна

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6414]
#### Подробное описание проблемы
У клоуна в вендомате есть предмет без тектурки (кажется он остался после хеллоуина)
![image](https://user-images.githubusercontent.com/47355061/100124189-020e8980-2e84-11eb-8753-259b71417204.png)

#### Что должно было произойти
Его нет/есть текстурка
#### Что произошло на самом деле
Он есть/текстурки нет
#### Как повторить
Посмотреть в вендомат клоуна
#### Дополнительная информация:
Issue reported from  Round ID: 37336 (Tau Ceti Classic (RU))
Testmerges: ```No test merges```
Reporting client version: 513.1536

**Comment by Kortez90** [comment]
Спрайт отвалился также и у самого предмета.
