### ISSUE TITLE
Проверка на расу работает неправильно

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6417]
#### Подробное описание проблемы
Проверки на расу у скафандров воксов и нт бричера работают неправильно, позволяя людям их носить
#### Что должно было произойти
Люди не могут носить скафандры воксов и нт бричер
#### Что произошло на самом деле
Люди могут это сделать
#### Как повторить
За человека надеть скаф воксов/бричер

**Comment by Kortez90** [comment]
Только бричер? Какой конкретно скафандр воксов?

**Comment by Akellazp** [comment]
как минимум стелс скафандр

**Comment by Kortez90** [comment]
Забавно, но у всех ригов `species_restricted = null`.

**Comment by LudwigVonChesterfield** [comment]
Если вчитаться в проверки можно обнаружить что они делают

"если список пустой, или если список содержит один элемент и этот элемент - "исключить всех"(что очевидно означает что просто нет особенной расы для этого рига" - убери ограничения. это не могло быть решением проблемы, потому-что не могло проблему вызывать.
