### ISSUE TITLE
Слипер Одиссея усыпляет СПУ так, что он уже не может проснуться

### ISSUE THREAD

**Issue by Balphagore** [TauCetiStation/TauCetiClassic#6419]
#### Подробное описание проблемы
Слипер Одиссея усыпляет СПУ, по всей видимости, навсегда. После извлечения из слипера разбудить СПУ так и не удалось. Даже администраторам.

#### Что должно было произойти
СПУ вообще не должен засыпать в слипере, так как медикаменты не должны на него влиять. Ну или хотя бы моментально просыпаться после извлечения.

#### Что произошло на самом деле
СПУ при попадании в слипер заснул так же как обычный органик, но проснуться уже не смог. Администраторы в раунде пытались как-то исправить ситуацию, но ничего не помогло.

#### Как повторить
Загрузить СПУ в слипер Одиссея. Выгрузить его. Возможно такая же проблема с обычным слипером.

#### Дополнительная информация:
Issue reported from  Round ID: 37351 (Tau Ceti Classic (RU))
Testmerges: ```No test merges```
Reporting client version: 513.1536

**Comment by Kortez90** [comment]
А вытаскивать позитронку пробовали?

**Comment by Balphagore** [comment]
Нет, позитронку не пробовали. Это был уже конец раунда.

**Comment by ViDLiathan** [comment]
Так там проблема была в том, что телепортировали спу из меха, но Одиссей всё равно считал, что он внутри.

**Comment by ViDLiathan** [comment]
Давно пора перебалансить слиппер и сделать возможность резизтаться

**Comment by Balphagore** [comment]
> Так там проблема была в том, что телепортировали спу из меха, но Одиссей всё равно считал, что он внутри.

Телепортировали? Я думал просто извлекли. Прямо перед тем как я оттуда выпал туда залез кто-то из врачей.
