### ISSUE TITLE
Немые пИИ

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#6423]
#### Подробное описание проблемы
пИИ, когда того держат в руках/кармане/сумке, не имеет возможности говорить.
#### Что должно было произойти
пИИ говорят, пока их держат.
#### Что произошло на самом деле
Молчание.
#### Как повторить
Страдать за пИИ
#### Дополнительная информация:
Issue reported from  Round ID: 37367 (Tau Ceti Classic II (RU))
Testmerges: ```No test merges```
Reporting client version: 513.1536

**Comment by KIBORG04** [comment]
Дубликат:
https://github.com/TauCetiStation/TauCetiClassic/issues/6104
https://github.com/TauCetiStation/TauCetiClassic/issues/6000

**Comment by SomeUselessGuy** [comment]
why
