### ISSUE TITLE
Поджигание игнитером не логируется

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#6426]
#### Подробное описание проблемы
Активация игнитера в руках, создает искры, искры поджигают топливо, это не логируется
#### Что должно было произойти
Логирование поджигание от искр при активации игнитера
#### Что произошло на самом деле
Логирования нет
#### Как повторить
Разлить топливо, взять игнитер, подойти к топливу, использовать игнитер, поджечь тем самым топливо, не увидеть лога

**Comment by Kortez90** [comment]
У обоих игнайтеров есть лог, но у ручного только при сборке. Сомневаюсь, что обобщать лог в игнайтере для активации вообще стоит, иначе в логи, какой-нибудь любитель тыкать на игнайтер, сможет спамить.

**Comment by Dominig12** [comment]
> У обоих игнайтеров есть лог, но у ручного только при сборке. Сомневаюсь, что обобщать лог в игнайтере для активации вообще стоит, иначе в логи, какой-нибудь любитель тыкать на игнайтер, сможет спамить.

тогда может сделать лог поджигания от искры? Потому что он не срабатывает

**Comment by Kortez90** [comment]
```
for(var/obj/effect/decal/cleanable/liquid_fuel/fuel in location.contents)
				message_admins("[key_name_admin(usr)] ignites \the [location] \the [src]. [ADMIN_JMP(usr)]")
```
Вот костыльный вариант. Логи поджигания, вроде бы, есть при дебаге.

**Comment by Dominig12** [comment]
> > тогда может сделать лог поджигания от искры?
> 
> Эти?
> https://github.com/TauCetiStation/TauCetiClassic/blob/e8f0ece9c23257a91c74efb199f8befa227e7e92/code/modules/atmospheric/ZAS/Fire.dm#L38-L44

ага, но я вижу уже пулл готов, прости что так поздно
