### ISSUE TITLE
[Proposal] Выпилить малфа

### ISSUE THREAD

**Issue by cool20141** [TauCetiStation/TauCetiClassic#6429]
Хуйня режим, вот только что в раунде ИИ обосрался и жестко спалился, но никто и не подумал его ебнуть, потому что анальные рп ограничения, почему-то все еще существующие для этого режима
По-сути, здесь фан получает только ИИ и его борги, может быть еще чуть-чуть(нет) сб, а остальной экипаж, задыхаясь от форона(или сгорая в нем) или усыпляющего газа вынужден за этим "весельем" наблюдать извне

Выпилите уже этот режим ИЛИ отмените рп-ограничения, как для нюки, потому что этот цирк с "ой, какой-то хакер на станции, будем его искать" уже порядком поднадоел

**Comment by KIBORG04** [comment]
> отмените рп-ограничения, как для нюки, потому что этот цирк с "ой, какой-то хакер на станции, будем его искать" уже порядком поднадоел

М, прям вижу как те же 99% станции начинают получать удоволствие от режима

**Comment by cool20141** [comment]
Да, я бы за кого угодно с радостью побежал со сваркой и термитом наперевес(ой, еще и его "пофиксили") ебать этого негодяя, а ии придумает что-то поинтереснее зафоронивания, потому что хоть какая-то часть, без последствий со стороны админов, будет одевать на себя маски, риги, костюмы и все такое, а не просто "застроил спутник, включил форон, лопнул лампочку–готово"

**Comment by kiVts** [comment]
Потому-что вы такие механоебы только и хотите поскорее идти на штурм спутника с ионками и термитом на спутник через ту самую стенку, а пока малф еще не показался будем аутировать, гы весело же. не умеете чаи пить а скорее бы уебать всех в мясо для вас есть крио. У малфа же поскорее сжечь все зажево ведь люди такие уебки что только и пинают его палкой ведь не дай бог ИИ пойдет по рп вместо того чтобы дать фороном подышать и скажет вам пезда то  на спутнике уже будут всякие рои волкеры ионкой обстреливать. 
Вы ожидаете от игры что она будет делать весело вам все время, что механ никогда не наскучит, а что наскучило "Выпилим!" у нас и так режимы вымирают, куда дальше то?

**Comment by cool20141** [comment]
Чел, теперь закончи хотя бы полтора класса начальной школы, проставь запятые и исправь ошибки в своем бессвязном тексте, вот тогда можно будет что-то уже понять из него

**Comment by kiVts** [comment]
Страдай.

**Comment by cool20141** [comment]
Нет, все намного проще: просто не буду читать твою писанину

**Comment by atik1n** [comment]
Выпиливать - самый худший выбор из всех.
Не лучше ли изменить?

**Comment by cool20141** [comment]
Почитай все предложение, дорогой его решительная многопочтимость, о хэд всея тау киты

**Comment by atik1n** [comment]
> Почитай все предложение, дорогой его решительная многопочтимость, о хэд всея тау киты

Прочитал. Пункт "отмените рп-ограничения, как для нюки, потому что этот цирк с "ой, какой-то хакер на станции, будем его искать" уже порядком поднадоел" всё также подпадает под "а го выпилим малфа". Тут и не пахнет конструктивным предложением по изменению.

**Comment by cool20141** [comment]
Не знаю, зачем тебе все нюхать и каким горьким опытом ты научен, но если тебя не устраивает мое предложение–можешь сам предложить альтернативу. Малф, который ололо-форонит станцию, и экипаж, который должен отыгрывать лоботомированных деградантов–ситуация не самая лучшая. Наоборот, естественно, ничем не лучше. Собственно, в самом предложении я и написал, что хоть как малф будет палиться, но реакции от игроков, по мнению админов, никакой быть не должно до дельта-кода. Вот конкретно в ситуации, из-за которой я и написал этот пропосал, ИИ просто в общий радиоканал сказал, мол, рубите свет, режьте провода в бриге. Что-то сделали? Нет, потому что админы пиздюлей дадут, ибо "ниршна". В общем, режим сам по себе мог бы быть интересным, если бы не такая безнаказанность малфа из-за того, что люди вынуждены рпшить

**Comment by Dwagdore** [comment]
Закрывайте пропосал. Малф выведен из ротации
![image](https://user-images.githubusercontent.com/111453473/186088198-6c3f9153-c1bc-4feb-9134-d64528c9f0d5.png)

**Comment by Chip11-n** [comment]
Малфа выпилили
