### ISSUE TITLE
Шахтёрские мобы лечатся бинтом

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6436]
#### Подробное описание проблемы
По сути данный баг убивает лазарус инжектор. При применении бинта на труп моба ему накидывается чуть-чуть хп и он оживает. Потом его можно убить с одной тычки и получить от него все преимущества.

#### Что должно было произойти
Бинт не должен ревайвать мобов

#### Что произошло на самом деле
Мобы ревайваются от бинта

#### Как повторить
Кликнуть бинтом по мёртвому мобу

**Comment by Kortez90** [comment]
Оживлять кого-то, кроме лорда нет смысла, а у лорда больше не спавнится труп. #6422

**Comment by Sakuya-Izayoi** [comment]
> Оживлять кого-то, кроме лорда нет смысла, а у лорда больше не спавнится труп. #6422

У василиска дропаются алмазы, например. А голдграб может создавать руду, которую он поедает.

**Comment by LudwigVonChesterfield** [comment]
Думаю баг заключается исключительно в том что симпл анималы оживают когда ХП восстанавливается, залечивание ран бинтиками звучит адекватно

**Comment by Kortez90** [comment]
Странно то, что он их вообще лечит. У бинта есть проверки `is_human()` в `can_heal()` и `heal()`. Даже если учесть потенциальный обход их обеих и переход сразу к родительскому `try_heal()`, то мы попадаем в еще одну проверку `is_human()`, а следом и в еще один `can_heal()`.
На практике же, при использовании бинта на трупе моба мы сразу же попадаем в родительский `heal()`. Возможно дело в `returrn ..()`.
