### ISSUE TITLE
Это не я оно само или ты можешь стать тритором вне зависимости от своих желаний

### ISSUE THREAD

**Issue by Thirteenalex** [TauCetiStation/TauCetiClassic#6448]
#### Подробное описание проблемы
Ты можешь стать раундстартом тритором даже если у тебя вырублены префы
#### Что должно было произойти
Тебе не должно выдать триторку
#### Что произошло на самом деле
Тебе выдает триторку как будто ты включил префернсы
#### Как повторить
Выключить преференс на триторов и играть с самого начала раунда
#### Дополнительная информация:
Issue reported from  Round ID: 37445 (Tau Ceti Classic II (RU))
Testmerges: ```No test merges```
Reporting client version: 513.1536

**Comment by Kortez90** [comment]
Делал это на протяжении нескольких лет и ни разу такого не происходило. Может дело, все же, не в коде?

**Comment by PirogSema** [comment]
У меня такое случалось. Были такие вот преференсы: 
![изображение](https://user-images.githubusercontent.com/22032604/100624507-99685680-3334-11eb-8084-0ee9fc2c92a8.png)

**Comment by Rolt146** [comment]
И у меня подобное случалось. Все роли кроме гены были отключены. В начале раунда стал геной, а потом еще и трейтором

**Comment by Zmey25** [comment]
Случалось данным давно один раз. Думал, что я случайно их включил, хотя обычно они выключены. Возможно педальное вмешательство, потому что случай одноразовый

**Comment by Tiarv** [comment]
Какой был режим?

**Comment by Sakuya-Izayoi** [comment]
чуваки, это педали вам выдали ролку
