### ISSUE TITLE
[Proposal] Лазерный дробовик.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6449]
#### Подробное описание проблемы
Этой игре не хватает лазерного дробовика в арсенале станции и спрайта для него.
#### Дополнительная информация:

![GIF 30 11 2020 15-40-00](https://user-images.githubusercontent.com/36198983/100611639-b136df00-3322-11eb-8c8c-0efa6c1980f2.gif)

**Comment by totallynotdedawa2** [comment]
скаттер лазган

спрайт сам рисуй

**Comment by AndroBetel** [comment]
скаттер лазган не работает как скаттер там просто много лучей в одно место бьют

**Comment by UsadoSmokk** [comment]
Но у нас есть плазма, которая схожа с лазерным дробовиком (можно заряжать и наносит берн дамаг). Хм. Так-то оно прикольно, много оружия лишним не бывает, однако мы получим условно тоже самое, ну может чутка слабее.

**Comment by Kortez90** [comment]
Плазма имеет собственный магазин, который надо заряжать батарейками и имеет зависимость от них. У лазерного дробовика такого быть не должно и питаться он должен либо от батарейки, либо как все остальные лазерные стволы.
