### ISSUE TITLE
ЭМИ-гранатамет

### ISSUE THREAD

**Issue by GoodGrief1488** [TauCetiStation/TauCetiClassic#6451]
#### Подробное описание проблемы
Эми для м79 не работают.
#### Что должно было произойти
Борг выходит из строя от трех гранат.
#### Что произошло на самом деле
Борг отстреливается
#### Как повторить
Атаковать борга ЭМИ м 79

**Comment by skorpion-beta** [comment]
Ты уверен что от трех?

**Comment by Motzord** [comment]
Так закодено, не баг а механ. (выстрелы ионки мощнее эми гранаток)
