### ISSUE TITLE
Найден секрет бага комбо. You are busy.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6456]
#### Подробное описание проблемы
Кукла во время исполнения комбо может сломаться и не мочь во взаимодействие
#### Что должно было произойти
Должна уметь даже при неудачно сложившихся обстоятельствах
#### Что произошло на самом деле
У куклы не получилось комбо. Кукла инавлид
#### Как повторить
Начните делать комбо на подопытном клоне из генетики, например чарж
Когда комбо будет готово прожмите альтклик
Кто-то третий, или же вы сами должны прервать анимацию комбо любым способом, например
Подскользнуть исполнителя комбо на чем-либо
Прописать ему комбо первее, прежде чем завершится анимация
Оттолкнуть "жертву" чем либо, например щитом или отпулить ее.

В итоге комбо как бы находится в суперпозиции оно по коду "выполнено" но не завершено как полагается.

Лудук приди, лудук приди, лудук приди.
#### Дополнительная информация:
Issue reported from  Round ID: 37470 (Tau Ceti Classic II (RU))
Testmerges: ```No test merges```
Reporting client version: 513.1536

**Comment by 4310V343k** [comment]
Ураураура

**Comment by Akellazp** [comment]
я багался и без посторонней помощи

**Comment by Motzord** [comment]
> я багался и без посторонней помощи

Возможно ты каким то образом после альтклика передвинул жертву на тайл куда нибудь прервав анимацию комбо.

**Comment by Akellazp** [comment]
я это вообще с грушей делал
