### ISSUE TITLE
борера не видно через медхуды

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6461]
#### Подробное описание проблемы
Раньше (до апдейта худов) люди зараженные борером имели крутой значок 
![image](https://user-images.githubusercontent.com/45365635/100780481-701df800-3412-11eb-81e6-b5bb9a7e4fb4.png)

#### Что должно было произойти
Я бегаю в медхудах, вижу зараженных и реагирую
#### Что произошло на самом деле
Худы не показывают зараженных
#### Как повторить
Посмотрите на куклу с борером через медхуд

**Comment by KIBORG04** [comment]
Я, вроде, это выпилил, потому что оно не юзалось

**Comment by Motzord** [comment]
> Я, вроде, это выпилил, потому что оно не юзалось

И что же впилилось другое чтобы юзалось?

**Comment by KIBORG04** [comment]
ничо

**Comment by Motzord** [comment]
> ничо

вот иди и впиливай обратно. Оно юзается.

**Comment by KIBORG04** [comment]
И это ты мне пишешь через 3 месяца после мержа

**Comment by Motzord** [comment]
> И это ты мне пишешь через 3 месяца после мержа

я только сейчас просто полноценно насладился таким режимом как бореры
