### ISSUE TITLE
Блоб не может ломать консоли

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6467]
#### Подробное описание проблемы
Блоб не может ломать консоли
#### Что должно было произойти
Блоб может ломать консоли
#### Что произошло на самом деле
Блоб не может ломать консоли
#### Как повторить
Не сломать консоль за блоба

**Comment by Kortez90** [comment]
Какую конкретно консоль?

**Comment by Akellazp** [comment]
Любую консоль

**Comment by Kortez90** [comment]
Не верю.

https://github.com/TauCetiStation/TauCetiClassic/blob/37380c082eaba30cfcd7a5ca39bad268b33bc5b5/code/game/machinery/computer/computer.dm#L80-L84

**Comment by Akellazp** [comment]
стекло консоли ломается и всё, самой консоли поиг абсолютно

**Comment by Kortez90** [comment]
Верно. У них меняется `stat` на `BROKEN`. Что еще нужно? Почему они должны удаляться?

**Comment by Akellazp** [comment]
потому что блоб разрушает абсолютно всё?

**Comment by Akellazp** [comment]
и это можно просто использовать как абуз, застраивая всё консолями от блоба
