### ISSUE TITLE
[Proposal] Мешок амбу.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6482]
#### Подробное описание проблемы
![1c5fadbd9e54e854e80da373f08482ae 1](https://user-images.githubusercontent.com/36198983/101262914-f60fab00-3752-11eb-9d00-293e2e8d0900.jpg)

Не помешала бы такая вещь, как дыхательный мешок. Порой нужно дунуть в рот, а легких нет.
Нужен также спрайт и механика.
Спавнить можно либо у медиков в личной коробке, либо в шкафу в единичном экземпляре.

**Comment by Sakuya-Izayoi** [comment]
Что это? Очередной способ спасения космонавтикой? Он нам точно нужен?

**Comment by Kortez90** [comment]
Нет. Это средство, с помощью которого спу может подышать в рот трупу, чтобы сбросить урон.

**Comment by LudwigVonChesterfield** [comment]
А нужна ли СПУ возможность подышать в рот трупу, чтобы сбросить урон, когда из невозможность делать это позиционировалась как значущее отличие респрайта?

**Comment by Kortez90** [comment]
Нужна и этот баланс учтен единичным экземпляром. Бывали ситуации, когда дыхнуть в рот просто некому и остается только клонирование через генетику, которая закрыта.

**Comment by LudwigVonChesterfield** [comment]
Значит открываешь генетику, вау...

Почему у всех всегда все раунды должны быть типичными, одинаковыми, и по ГОСТ-у, разве это не круто когда приходится нестандартно мыслить на ходу?

А оксиурон кстати сбрасывается не только дыханием рот-в-рот...

**Comment by Kortez90** [comment]
Избивать дефибриллятором долго. Однажды я просто не успел сбросить достаточно урона и труп протух. ИВЛ не снимает урон. Дексалина плюс почти не производят и времени для этого нет.

**Comment by Sakuya-Izayoi** [comment]
Ну умер космонавтик и умер. Всё равно через полчаса зайдёт, не заскучает. Всё-таки, иногда надо проигрывать.
