### ISSUE TITLE
Загадка Z-уровня цк.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6492]
#### Подробное описание проблемы
![GIF 08 12 2020 1-08-22](https://user-images.githubusercontent.com/36198983/101411434-06aa5780-38f2-11eb-8425-0f4d05d65652.gif)

Летал по слою цк возле базы нюки, пролетел южнее, наткнулся на велосити, вроде и предположительно конвейер, который отправил призрака в полет.

А дело, похоже, в этом месте. Оно запускает еще и призраков в полет, который можно сбросить переходом на другой слой.
![Безымянный](https://user-images.githubusercontent.com/36198983/101411786-9b14ba00-38f2-11eb-8647-7adc019973ad.png)

#### Как повторить
- Пролететь в указанном на скриншоте месте.

**Comment by LudwigVonChesterfield** [comment]
похожие симптомы когда слезаешь с шаттла летящего

**Comment by 4310V343k** [comment]
Есть волшебные толкатели, которые как и шкафы в морге не проверяют на гостов

**Comment by BesumniiChebureck** [comment]
Да-да-да. Это не совсем баг (конкретно у шаттлов), а так и задумано. Вот там находится "мусорка" велосити
![image](https://user-images.githubusercontent.com/67091522/101481090-ace37500-3965-11eb-91ca-7161a90f6016.png)
И там стоят спец. толкатели, которые кидают тебя вправо (сторона зависит от типа толкателя), и ты должен попасть в невидимую стеночку, по достижению которой ты попадешь на астероид (о них позже). Вот те толкатели на том месте:
![image](https://user-images.githubusercontent.com/67091522/101481336-0e0b4880-3966-11eb-857e-36de1a26dc98.png)
![image](https://user-images.githubusercontent.com/67091522/101481357-1c596480-3966-11eb-8978-80f6b4a69b9d.png)
![image](https://user-images.githubusercontent.com/67091522/101481366-211e1880-3966-11eb-9a36-9c0b2b518eba.png)
А вот теже толкатели у шаттлов:
![image](https://user-images.githubusercontent.com/67091522/101481421-35621580-3966-11eb-80f6-31f3a5ddffde.png)
Но у шаттлов есть особенность - они застроены теми самыми стеночками-телепортерами вокруг себя, которые телепортируют на астероид:
![image](https://user-images.githubusercontent.com/67091522/101481730-af929a00-3966-11eb-96de-d2015ab012a1.png)
Вот и суть "проблемы". У мусоросброса велосити данные штуки кидают тебя вправо, и в конце будут стоять телепорталки на астероид. Но госты за счет пролетания сквозь стены и своей быстроты, обычно пролетают мимо этой штуки, и их будет бесконечно вести вправо (пока они не нащупают телепорталку). 
![image](https://user-images.githubusercontent.com/67091522/101482097-3b0c2b00-3967-11eb-8844-50a362255683.png)
Красное - телепортеры, остальное - двигалки вправо. Решение проблемы достаточно простое - 
![image](https://user-images.githubusercontent.com/67091522/101482176-5b3bea00-3967-11eb-9084-eee5240b1166.png) На телепортере и кидалке поставить 0. Чтобы госты не попадали на эту штуку. Надеюсь объяснил понятно. Сегодня-завтра сделаю ПР на поправление этой штуки (и в описании ПР буду ссылать на этот комментарий).
