### ISSUE TITLE
[Proposal] Добавить какой-то режим с хакером

### ISSUE THREAD

**Issue by SomeUselessGuy** [TauCetiStation/TauCetiClassic#6496]
#### Что за режим?

Да самый обычный. Берем нескольких членов (или не членов, можно просто участников) экипажа, промываем им мозги (чтоб не сбежали) и даем рольку. Задача та же, что и у малфа - взломать какое-то количество АПЦ и взорвать станцию. Сбегать при этом всем необязательно :peka:
#### Зачем его нужно добавлять?

Появится еще один клон революции/гангов/тп
Рандомные токсики перестанут создавать свои ПРы (#6429)
При сообщениях о взломе челокеки могут гействительно найти взломщика
https://www.youtube.com/watch?v=6jSVEEqqbbY
#### Нужно ли оно на самом деле?

Нет
#### Как сделать?

Да хрен его знает
#### Дополнительная информация:

B3$||0/|Е3N0

**Comment by LudwigVonChesterfield** [comment]
> Зачем его нужно добавлять?
Появится еще один клон революции/гангов/тп

> Зачем?
Ну чтобы скопировать то что уже есть

> Рандомные токсики перестанут создавать свои ПРы (#6429)
Это не ПР, а предложение как и твое если что

> Нужно ли оно на самом деле?
Нет
Хорошо, спасибо.
