### ISSUE TITLE
На медхудах не видно зараженных

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6505]
#### Подробное описание проблемы
Если на станции есть, вирус и если он изучен, зараженные на худах все равно не отображаются крутым зеленым квадратиком
#### Что должно было произойти
Вирусолог изучает вирус, медики видят зараженных через худы в третьем режиме датчиков
#### Что произошло на самом деле
Медики бегают и сканируют всех подряд
#### Как повторить
1. берем куклу со свключенными датчиками
2. Заражаем вирусом
3. Изучаем вирус внося его в БД
4. Смотрим на куклу
5. Недовольно урча идем тыкать в нее сканером

**Comment by KIBORG04** [comment]
Ставлю пометку для себя(или кого-то) в будущем.
У нас есть в мобе аж три листа с вирусами. Как я понял, юзается именно virus2 для вирусов этого типа `/datum/disease2/disease`. В проке же обновления худов, ищется вирус в viruses для типа `/datum/disease`.
![image](https://user-images.githubusercontent.com/26389417/101999249-3390ad00-3cec-11eb-8ec4-a3c020c3de3d.png)

P.S: ето пиздец с этими вирусами, почему у нас вообще 2 фреймворка и аж 3 листа в хумане?
