### ISSUE TITLE
Суккумб не убивает СПУ

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6509]
#### Подробное описание проблемы
СПУ не умирает если он получил достаточное количество урона и прописал суккумб.

#### Что должно было произойти
СПУ должен умереть при суккумбе

#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/30875884/101821388-8faed200-3b30-11eb-83e1-be4071e494b1.png)

#### Как повторить
Получить дамаг и прописать суккумб.

**Comment by 4310V343k** [comment]
А как он должен умереть? Позитронку выплюнуть?

**Comment by Sakuya-Izayoi** [comment]
Выключиться и больше не включаться.
