### ISSUE TITLE
Термалы и человек в шкафу

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#651]
#### Подробное описание проблемы

Термалы не просвечивают шкафчики и не показывают, что там человек.
#### Что должно было произойти

Силуэт космонавтика должен просвечиваться через закрытый шкафчик.
#### Что произошло на самом деле

Криминальная пена успешно сныкалась от хоса в шкафчике
#### Как повторить

Надеть термалы и поискать кого-то в шкафу.

**Comment by Skippeer12** [comment]
Шкафы у нас усиленые, имеют защиту от радиации, давления, открытого космоса, лазеров, дробовиков, ветерка и так далее.

**Comment by Udokun** [comment]
Говорят в шкафу тебя даже админ не найдёт.
