### ISSUE TITLE
Бан культиста не дает зайти за обр

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#6512]
#### Подробное описание проблемы
Бан культиста не дает зайти за обр
#### Что должно было произойти
Доступ в обр должен быть
#### Что произошло на самом деле
Игра считает что он забанен
#### Как повторить
Забанить себе культистов и попытаться войти за ОБР
#### Дополнительная информация:
Issue reported from  Round ID: 37661 (Tau Ceti Classic II (RU))
Testmerges: ```#6400 ```
Reporting client version: 513.1536

**Comment by EdlerN** [comment]
Там у человека бан на СБ, который блокирует ОБР в том числе. Бан на культ к этому не имеет отношения.

**Comment by Avatar4** [comment]
Да, так что закрываю
