### ISSUE TITLE
Рядовые Генга не видят кто у них Лидер и лейтенант

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#6513]
#### Подробное описание проблемы
При режиме Генга, рядовые которых законвертили - должны видеть иконку своего лидера и лейтенанта (но не остальных рядовых). Лидер так же должен видеть всех кого он законвертил, даже рядовых.
#### Что должно было произойти
Лидер должен видеть роль всех своих подопечных, лейтентант тоже, рядовые должны видеть только лейтенанта и лидера (а остальных опознавать по форме)
#### Что произошло на самом деле
Никто не знает кто к какой банде принадлежит. Все опознают друг друга по форме
#### Как повторить
Запустить генг изначально перед началом раунда (это важно)
#### Дополнительная информация:
Возможно я не прав, но насколько помню - все должно было быть именно так. Что бы только лидер мог узнать предателя в своих рядах (если вражеский ганстер надел одежку их банды)

**Comment by Pivo24** [comment]
Так и должно было быть, поэтому всё хорошо...

**Comment by Avatar4** [comment]
Таки нет, лидера рядовые точно видели ранее

**Comment by Rolt146** [comment]
Я за рядового не видел что я сам нахожусь в банде. Если бы я отошел от компа, меня конвертнули и я вернулся бы обратно - то я бы ничего не заметил

**Comment by T6751** [comment]
Режим был удалён в #6909. В связи с этим проблема больше не актуальна
