### ISSUE TITLE
Деконверт роли намереньем уколоть майндшилдом 

### ISSUE THREAD

**Issue by Rolt146** [TauCetiStation/TauCetiClassic#6516]
#### Подробное описание проблемы
Режим ганста.
Лолконвертнули в банду, но видя что она такая себе, иду в бриг за имплантом защиты разума. Получаю имплантер, жмякаю на себя и... я деконверчен, однако имплант все еще был в имплантере
#### Что должно было произойти
Сначала в теле появляется имплант, следом деконверт
#### Что произошло на самом деле
Жму имплантером по себе, падаю в обморок деконверта, очухиваюсь цивилом, но имплант все остается в имплантере
#### Как повторить
Самому уколоться имплантером в ганста режим

**Comment by Akellazp** [comment]
ясно рольт нонрп идет себя деконвертить когда ему промыли мозги
я считаю это бан

**Comment by aIweiss** [comment]
майндшилдом

деконверт

это как лечить отрубленную ногу, прикрывая ее щитом

**Comment by KIBORG04** [comment]
Я удалил ганст
