### ISSUE TITLE
CR-20. Путь патрон не соответствует действительному калибру

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6518]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/45365635/101982067-2fc44280-3c7a-11eb-8a15-32dd33f7edf7.png)
![image](https://user-images.githubusercontent.com/45365635/101982078-44083f80-3c7a-11eb-9c0b-45ed63d23256.png)

#### Что должно было произойти
![image](https://user-images.githubusercontent.com/45365635/101982105-54b8b580-3c7a-11eb-8db3-c931e6ae389b.png)
Или же правильные православные .45 в пути к обоймам
#### Что произошло на самом деле
Скрины выше
#### Как повторить
Зашитспавните себе патроны 12мм. Удивитесь, что вместо них там .45

**Comment by Kortez90** [comment]
Ошибки в путях нет. Просто .45 зачем-то обозвали `m12mm`. Может, С-45 раньше использовала их?

**Comment by Motzord** [comment]
> Ошибки в путях нет. Просто .45 зачем-то обозвали `m12mm`. Может, С-45 раньше использовал их?
> Причем это относится только к магазинам. `a12mm` - уже не .45.

это неприятная опечатка, возможно cr-20 действительно раньше использовала их.

**Comment by Motzord** [comment]
Кортез пофиксил, я это помню
