### ISSUE TITLE
Нимфа на голове космонавтика слепа

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#652]
#### Подробное описание проблемы

Будучи на чьей то голове или на руках диона ничего не видит, как если бы сидела в шкафу.
#### Что должно было произойти

Обзор не должен был исчезать.
#### Что произошло на самом деле

Диона ослепла.
#### Как повторить

Быть нимфой и попроситься на ручки.

**Comment by Dennok** [comment]
Это касается всех мобов макак.

**Comment by DeadOberst** [comment]
#2403

**Comment by LudwigVonChesterfield** [comment]
грустно, но актуально
