### ISSUE TITLE
Консоль камер внезапно перестаёт работать (возможно вайнопроблемы)

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6520]
#### Подробное описание проблемы
![](https://i.imgur.com/nkzAAIz.png)
Если много кликать по камерам в консоли камер появляется вот такой прямоугольничек.

#### Что должно было произойти
Камеры должны работать нормально

#### Что произошло на самом деле
Иногда появляется вот такой прямоугольник.

#### Как повторить
Кликать по разным камерам в консоли камер

#### Дополнительная информация:
Wine 5.0.3, вайновский IE8. Всё остальное работает нормально. Другие консоли после поломки одной работают сравнительно нормально

**Comment by kiVts** [comment]
Ты хочешь сказать что ты на линуксе?
