### ISSUE TITLE
Поле сдерживания изолятора

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6530]
#### Подробное описание проблемы
Поле сдерживания изолятора работает даже когда апц выключен
#### Что должно было произойти
Выключаешь апц, поле спадает, твои друзья генки выбегают и вы вместе всех убиваете
#### Что произошло на самом деле
Выключаешь апц, а полю похер
#### Как повторить
Включить поле в изоляторе апц а потом выключить апц мультитулом по проводам
#### Дополнительная информация:
Issue reported from  Round ID: 37704 (Tau Ceti Classic II (RU))
Testmerges: ```#6313 #6362 #6400 ```
Reporting client version: 513.1537

**Comment by EdlerN** [comment]
А ничего что поле запитано от проводов под генераторами?
