### ISSUE TITLE
Баг you are busy всё еще есть

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6538]
#### Подробное описание проблемы
Баг с бесконечной занятостью всё еще есть и стал еще жестче
Теперь ты не можешь делать даже действия которые не требуют прогрес бара (сесть/встать со стула, уколоться автоинжектором)
#### Что должно было произойти
Бага нет
#### Что произошло на самом деле
Баг есть
#### Как повторить
Вроде это произошло когда я сделал апперкот ожившему через ритуал капеллана мечу из голодеке, изза которого он умер и исчез, так как он был не в голодеке
#### Дополнительная информация:
Issue reported from  Round ID: 37725 (Tau Ceti Classic II (RU))
Testmerges: ```#6313 #6362 #6400 ```
Reporting client version: 513.1537

**Comment by 4310V343k** [comment]
Ура, куделы не по таймингам. Разбираться я с этим не буду

**Comment by LudwigVonChesterfield** [comment]
@Akellazp если найдешь способ гарантированно воспроизвести баг, я возьмусь чинить.

**Comment by 4310V343k** [comment]
Убить апперкотом вещь, которая моментально после этого куделитнется. Как минимум
