### ISSUE TITLE
Возможность гибнуть госта

### ISSUE THREAD

**Issue by Raschert0** [TauCetiStation/TauCetiClassic#654]
#### Подробное описание проблемы
Через ВВ можно гибнуть госта с появлением на полу ошмётков.
#### Что должно было произойти
Гост не должен был гибаться
#### Что произошло на самом деле
Гост остался цел, но на турфе с этим гостом появились кровь-кишки
#### Как повторить
1. Получить ВВ
2. Найти госта
3. Гибнуть госта

**Comment by Tankred0** [comment]
Так это же не баг, это же фича.

**Comment by WallShrabnic** [comment]
Это фича же. Не каждый игрок имеет BB

**Comment by Dennok** [comment]
Думаю гост таки уничтожается, но так как гост это фундаментальный моб то клиенту без моба дают госта.
