### ISSUE TITLE
Рантаймы при нажатии на руну.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6547]
#### Подробное описание проблемы
Сообщения на 61-й и 65-й строчке рантаймят с `null` при многократных нажатиях на руну.
#### Что должно было произойти
Рантайма нет.
#### Что произошло на самом деле
А он есть.
#### Как повторить
Много раз и с большим кол-вом людей нажимать на руну.
#### Дополнительная информация:
https://github.com/TauCetiStation/TauCetiClassic/blob/778f83034e26a2bd4a1bd22c824357ae4184878f/code/game/gamemodes/cult/cult_datums.dm#L59-L66

**Comment by Sakuya-Izayoi** [comment]
@KIBORG04 это исправлено в новом культе?

**Comment by KIBORG04** [comment]
Скорее это просто неактуально, чем я чё-то фиксил
