### ISSUE TITLE
[Proposal] Рандомизация доков.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6549]
#### Подробное описание проблемы
Частенько игроки ждут прилета шаттла в том доке куда он должен прилететь и технически это мета.
Но что если рандомизировать при старте раунда доки и присылать шаттл с оперативниками/агентами ЦК в разные места?

**Comment by KIBORG04** [comment]
> технически это мета.

С чего тут быть мете? Типо, ты считаешь, что сотрудников не уведомляют откуда им улетать? Может тогда и расположение отсеков на станции является метой?

**Comment by Kortez90** [comment]
![Безымянный](https://user-images.githubusercontent.com/36198983/102382849-ed816500-3fdb-11eb-9603-936879188c24.png)

**Comment by KIBORG04** [comment]
Ты нигде не писал указал про какой конкретно шаттл ты пишешь

**Comment by Kortez90** [comment]
> присылать шаттл с оперативниками/агентами ЦК



> 
> 
> Ты нигде не писал указал про какой конкретно шаттл ты пишешь

**Comment by Sakuya-Izayoi** [comment]
может тогда обрам сделать возможность прилететь в какую-нибудь точку рядом со станцией как у шаттлов антагонистов?

**Comment by Kortez90** [comment]
Лучше заменить точки спавна шаттлов на динамические с возможностью выбора.
