### ISSUE TITLE
Пирометр из протолата не имеет заряда

### ISSUE THREAD

**Issue by Rolt146** [TauCetiStation/TauCetiClassic#6551]
#### Подробное описание проблемы
Если распечатать на протолате пирометр и попытаться им сделать пиу-пиу, мы услышим только звук осечки. Пирометр можно запихнуть в речарджер, но заряда мы от данного мува всеравно не получим. Были протестированы прототипы различных качеств - от моделей до мк2, результат одинаковый
#### Что должно было произойти
Пиу-пиу из пирометра
#### Что произошло на самом деле
*click*
#### Как повторить
Сделать пирометр на протолате

**Comment by Motzord** [comment]
Батарейку в пиометр пихать не пробовал?
/thread

**Comment by 4310V343k** [comment]
И батарейку, и микролазер надо пихать. Закрывайте
