### ISSUE TITLE
Автолат вместо пачки патронов к дробовику дает только одну гильзу

### ISSUE THREAD

**Issue by ChewedGum** [TauCetiStation/TauCetiClassic#6552]
#### Подробное описание проблемы
Автолат вместо пачки патронов к дробовику дает только одну гильзу.
#### Что должно было произойти
Тыкаем в интерфейсе автолата по кнопке распечатки слагов - вылезает пачка слагов.
По бакшотам - пачка бакшота.
И т.д.
#### Что произошло на самом деле
Вылезает всего одна гильза стоимостью 3,5 листов металла. 
#### Как повторить
Попробовать распечатать аммуницию к дробовику в автолате. 
#### Дополнительная информация:
Из-за этого дробовиками никто не ползуется в этом билде рофл лмао

**Comment by Akellazp** [comment]
дробовиками пользуются, и бага нет

**Comment by ChewedGum** [comment]
эх щяс бы у автолата постоять потыкать минут 5-10 чтобы себе коробку патронов наскрести мммм вот это я понимаю гей мплей

**Comment by Akellazp** [comment]
эх щас бы за три нажатия иметь запас патроном до конца следующей смены

**Comment by ChewedGum** [comment]
https://www.youtube.com/watch?v=ta41xU-tkFA

**Comment by Rolt146** [comment]
Кстати, считаю эту тему актуальной, ибо по патрону печатать это бред. Например в фаллаут билде сразу коробка с патронами печатается, и все довольны (хотя там конечно и расход патронов больше, но все-же). Так же никто не печатает стан патроны на дробовик, ибо дешевле распечатать револьвер на 20 пиу-пиу, чем одну гильзу ценой в револьвер для какого-то там бармена.

**Comment by Kortez90** [comment]
> считаю эту тему актуальной, ибо по патрону печатать это бред.

Интерфейс автолата вообще нужно переделывать и сделать очередь создаваемых предметов. Возможно когда-нибудь переведем интерфейсы на TGUI.

**Comment by Motzord** [comment]
Самый банальный способ пофиксить данную проблему это добавить в автолат коробку патронов но печататься она будет столько же сколько n-количество патронов в этой коробке (да 5-10 минут)

**Comment by ChewedGum** [comment]
Давайте тогда ещё сделаем чтобы пачка патронов для глока 5-10 минут печатались, хули мелочиться.

**Comment by ChewedGum** [comment]
И ведь пофиксили же.
