### ISSUE TITLE
Оверлей газа ниже всего

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6560]
#### Подробное описание проблемы
Оверлей (если его можно так назвать) газа (форон/азот) находится ниже чем всё остальное
![image](https://user-images.githubusercontent.com/47355061/102765767-bddcaf00-4385-11eb-93d3-496e38718164.png)
На скрине можно видеть как машинерий, консоли, вещи, стулья, столы, "живые" существа, даже трубы находятся поверх оверлея газа
#### Что должно было произойти
Оверлей газа выше всех объектов так как это газ
#### Что произошло на самом деле
Газ находится ниже всего
#### Как повторить
Пустить форон в комнату и посмотреть на вещи, которые будут над оверлеем форона
#### Дополнительная информация:
Issue reported from  Round ID: 37840 (Tau Ceti Classic II (RU))
Testmerges: ```#6313 #6362 #6400 ```
Reporting client version: 513.1539

**Comment by Tiarv** [comment]
А кликать по машинерии это мешать не будет?

**Comment by LudwigVonChesterfield** [comment]
Газ можно сделать не кликабельным
