### ISSUE TITLE
Турфы стен выглядят тёмными на мезонках

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6568]
#### Подробное описание проблемы
Турфы стен, включая и камни на астероиде выглядят абсолютно чёрными при включенных мезонках.

#### Что должно было произойти
Турфы должны быть хоть немного яркими, чтобы можно было их разглядеть

#### Что произошло на самом деле
Все турфы стен абсолютно чёрные

#### Как повторить
Надеть и включить мезонки. На шахте это особенно заметно.

**Comment by Rolt146** [comment]
Уже была подобная тема, но да, мезонки стали совершенно не юзабельными
