### ISSUE TITLE
[Proposal] Интеграция анестезии в операционный стол

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6577]
Идея заключается в том, чтобы сделать операционный стол атмос-девайсом, который по трубам подключается к канистре с N2O (а по желанию хирурга к чему-нибудь другому). У стола будет баундед маска, которую нельзя забрать дальше, чем на пару тайлов от стола, в идеале, чтобы нельзя было вынести за пределы операционной. Эта маска будет подключена к столу, и брать газ по трубам, подключенным к нему. 

Это избавит врачей от необходимости постоянно цеплять баллон на пациента, немного освобождает место в хирургии и выглядит довольно футуристично и круто.

**Comment by Kortez90** [comment]
В этом нет смысла, так как подразумевалось, что роли будут использовать анестезию при игре и специально, отчасти для этого, сделали дополнительные входы в операционные через тоннели. Делать из операционного стола стол абдукторов нет смысла.

**Comment by Sakuya-Izayoi** [comment]
И много раз ты видел чтобы кто-то использовал анестезию? Если кто-то захочет, он может себе сделать баллон с н2о в атмосе, а в атмосе это можно сделать даже без эмага! (эмаг нужен чтобы разблокировать шкафчик)

**Comment by Kortez90** [comment]
Это уже другая история.

**Comment by Venngedi** [comment]
#8073 Мучения хирургов закончились после мержа этого ПРа.

> подключается к канистре с N2O (а по желанию хирурга к чему-нибудь другому)

> брать газ по трубам, подключенным к нему

> избавит врачей от необходимости постоянно цеплять баллон на пациента, немного освобождает место в хирургии

Так как уже есть ИВЛ с баками, то делать хирургический стол с таким же функционалом вряд ли кто-то будет. Пропосал можно закрыть
