### ISSUE TITLE
Рыба пойманная в проруби не имеет спрайта

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6580]
#### Подробное описание проблемы
Рыба из проруби не имеет спрайта

#### Что должно было произойти
Рыба должна иметь спрайт

#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/30875884/103095863-c560ba00-460a-11eb-93c6-82ce6fa2d7e2.png)

#### Как повторить
Сделать прорубь и поймать в ней рыбу

**Comment by T6751** [comment]
#6499

**Comment by T6751** [comment]
В последней версии леса должно быть исправлено https://github.com/TauCetiStation/TauCetiClassic/pull/6499/commits/5688ee89112f6be84376dde874f92598c0abd1d3
