### ISSUE TITLE
Баг взрывов на зимней карте

### ISSUE THREAD

**Issue by Rolt146** [TauCetiStation/TauCetiClassic#6592]
#### Подробное описание проблемы
Взрывы перестали работать так, как должны. От взрыва только звук. Особенно больно ученым-форонщикам - на полигоне только 1 взрыв происходит, хоть самих бомг гораздо больше
#### Что должно было произойти
Бубухи работают как надо, полигон токсинов разбиты в хлам от лимитки, датчик фиксирует до 8 взрывов
#### Что произошло на самом деле
Полигон цел, все лимитки при активации на месте, зафиксирован лишь один взрыв. У самих лимиток после активации пропадает кислородный баллон
#### Как повторить
Поделать взрывы на зимней карте

**Comment by T6751** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/6499

**Comment by 4310V343k** [comment]
![image](https://user-images.githubusercontent.com/56449763/103141709-34bcd380-4709-11eb-99e8-7977493ad09a.png)
На локалке не воспроизводится

**Comment by Dominig12** [comment]
пока не найдут решение проблемы, етсь предложение взрывать в космосе, на астероиде даже, через ученых и теленауку

**Comment by 4310V343k** [comment]
> пока не найдут решение проблемы, етсь предложение взрывать в космосе, на астероиде даже, через ученых и теленауку

Почитай мой ответ на два этажа выше.

**Comment by Dominig12** [comment]
> > пока не найдут решение проблемы, етсь предложение взрывать в космосе, на астероиде даже, через ученых и теленауку
> 
> Почитай мой ответ на два этажа выше.

на сервере была туча рантаймов от каждого взрыва, там в РНД канал скидывали

**Comment by 4310V343k** [comment]
> > > пока не найдут решение проблемы, етсь предложение взрывать в космосе, на астероиде даже, через ученых и теленауку
> > 
> > 
> > Почитай мой ответ на два этажа выше.
> 
> на сервере была туча рантаймов от каждого взрыва, там в РНД канал скидывали

Рантаймы уже пофикшены

https://github.com/TauCetiStation/TauCetiClassic/pull/6499/commits/461a6009c46b502fdc91ba670615b8dea9c435be

**Comment by Dominig12** [comment]
> > > > пока не найдут решение проблемы, етсь предложение взрывать в космосе, на астероиде даже, через ученых и теленауку
> > > 
> > > 
> > > Почитай мой ответ на два этажа выше.
> > 
> > 
> > на сервере была туча рантаймов от каждого взрыва, там в РНД канал скидывали
> 
> Рантаймы уже пофикшены
> 8 часов назад
> [461a600](https://github.com/TauCetiStation/TauCetiClassic/commit/461a6009c46b502fdc91ba670615b8dea9c435be)

принято, тогда как проверю скину. Но я полагаю человек просто мог сделать бомбы неправильно или что то еще

**Comment by Dominig12** [comment]
действительно, взрыва не было, я проверил на первом сервере ингейм
балон был уничтожен, фороновый бак пуст, но самого взрыва не оказалось

**Comment by kalazus** [comment]
Вчера вечером пытались за големов взрывать(ся) на полигоне масляные экстракты, тоже 0 реакции. Полностью проходит часть кода с вызовом взрыва (там используется sleep вместо spawn, так что пишет о вливании только после взрыва), но он не происходит.
