### ISSUE TITLE
Баг с зимней курткой и головными уборами

### ISSUE THREAD

**Issue by NinjaPikachushka** [TauCetiStation/TauCetiClassic#6593]
#### Подробное описание проблемы
При особых манипуляциях с курткой и шляпой, которые описаны ниже, любая шляпа надетая игроком остается на нем, после того, как она была снята. Головной убор нельзя убрать, а также их можно комбинировать. Ничего кроме визуала оно не дает.
#### Что должно было произойти
Игрок снимает головной убор, шляпа пропадает.
#### Что произошло на самом деле.
На игроке остается миллиард всего.
![image](https://user-images.githubusercontent.com/76616162/103150981-b86ad480-478a-11eb-8934-9496e86e7603.png)

#### Как повторить
Надеваем нужную нам вещь на голову, берем и тыкаем  по куртке, которая в руках, чтобы активировался капюшон. Затем надеваем куртку уже с капюшоном и сразу же снимаем её. Вуаля, шляпу можно снимать, и она теперь навеки с нами. Можно повторять до бесконечности.

**Comment by Dominig12** [comment]
Подобный баг, но с волосами
Если надеть куртку и надеть капюшон, а потом не снимая капюшон снять куртку, останется лысый чел
Вернуть можно, если чел наденет куртку и снимет капюшон

**Comment by NinjaPikachushka** [comment]
Можно наоборот. С одетым капюшоном и волосами остаться. Картку с капюшоном надеть сразу.

**Comment by T6751** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/6499

**Comment by 4310V343k** [comment]
Как я это не заметил!?
