### ISSUE TITLE
[Proposal] Лечить мозг зомбям при конверте

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6598]
![image](https://user-images.githubusercontent.com/30875884/103171016-693ba700-4851-11eb-8512-d26b41635f7e.png)

Ещё там где-то был анонс, что за харм в голову зомби будут банить, но он у меня не сохранился.

Собственно, если бить в голову нельзя, то почему в игре это всё ещё можно? Причём за нарушение запрета на харм в голову страдает только сама жертва, а не тот зомби, который этот запрет нарушил. Предлагаю просто реджувать зомби мозг при конверте, а лучше сделать им какой-нибудь особый зомби-мозг, который нельзя продамажить.

**Comment by LudwigVonChesterfield** [comment]
зачем зомбям вообще внутренние органы, замените их на заглушки которые не имеют никакого функционала но чтобы на сканах показывало "ууу очень повреждено" и тогда смешно и весело и без проблем
