### ISSUE TITLE
Позитронка в мехе без экшон кнопок

### ISSUE THREAD

**Issue by Rolt146** [TauCetiStation/TauCetiClassic#6600]
#### Подробное описание проблемы
Если попасть в мех, будучи позитронкой, то никакого интерфейса и экшон кнопок теперь нету, даже банальной вкладки меха
#### Что должно было произойти
Позитронка пользуется интерфейсом меха как и раньше до обновления с мехами
#### Что произошло на самом деле
Позитронка в мехе может только передвигаться, но не пользоваться оборудованием
#### Как повторить
попасть в мех будучи позитронкой
#### Дополнительная информация:
Issue reported from  Round ID: 37980 (Tau Ceti Classic II (RU))
Testmerges: ```#6362 #6394 #6400 #6499 #6540 ```
Reporting client version: 513.1528
"

**Comment by Kortez90** [comment]
#6313.

**Comment by Sakuya-Izayoi** [comment]
я думаю это скорее свзано с тем, что у позитронок в мехе вообще ограниченный функционал.
т. е. до экшен кнопок позитронки не могли юзать оборудование типа пушек

**Comment by Rolt146** [comment]
> я думаю это скорее свзано с тем, что у позитронок в мехе вообще ограниченный функционал.
> т. е. до экшен кнопок позитронки не могли юзать оборудование типа пушек

Как раз таки все могли позитронки до обновы, ибо они могли через верб меха попасть в интерфейс меха и менять пушечки, менять имя меха, блокировать или разблокировать протоколы и собственно стрелять и пользоваться оборудованием.

**Comment by kalazus** [comment]
Не умею нормально в локалку, чтобы проверить, но в mech.dm > mmi_moved_inside нужно добавить GrantActions(brainmob)
