### ISSUE TITLE
Неправильное отображение цены в вендомате

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6602]
#### Подробное описание проблемы
У раскупленных предметов в вендомате неправильно отображается цена

#### Что должно было произойти
Везде должна быть цена в формате `%d cr.`

#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/30875884/103219708-264c0300-4927-11eb-8aa3-bcdcbc6d5ea0.png)

#### Как повторить
раскупить все предметы в вендомате

**Comment by 4310V343k** [comment]
Блин на вайне интерфейсы красивее смотрятся
