### ISSUE TITLE
Карпики не режутся ножом

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6604]
(тест фидбек)

#### Подробное описание проблемы
Карпики пойманные на рыбалке не режутся ножом, хотя должны

#### Что должно было произойти
Карпики должны резаться ножом

#### Что произошло на самом деле
Карпики не режутся ножом

#### Как повторить
поймать карпика и тыкать в него ножом

#### Дополнительная информация:
https://github.com/TauCetiStation/TauCetiClassic/pull/6499/files#diff-998bf4748e2aa4d93b9c959a6b473b6bce1a46cb9f6932fcc2eb252092639dfeR438-R455

**Comment by T6751** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/6499

**Comment by Sakuya-Izayoi** [comment]
Также было бы неплохо чтобы их можно было перемолоть на карпотоксин+протеин без разделки.

**Comment by 4310V343k** [comment]
Можно закрывать
https://github.com/TauCetiStation/TauCetiClassic/pull/6499/commits/e2cac1ff0c00922361f44595bf3fb618d055dd24
