### ISSUE TITLE
Неправильное отображение прогресса эмбриона алиена.

### ISSUE THREAD

**Issue by NinjaPikachushka** [TauCetiStation/TauCetiClassic#6609]
#### Подробное описание проблемы
Прогресс эмбриона алиена неправильно отображается.
#### Что должно было произойти
цифорки/300
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/76616162/103287941-cb80dd00-49f4-11eb-94b5-3df500aa60fe.png)
300/цифорки
#### Как повторить
Стать эмбрионом алиена.

**Comment by Kortez90** [comment]
#6453.

**Comment by Motzord** [comment]
Вмержить вмержили, а закрыть забыли
