### ISSUE TITLE
бумажные алиены

### ISSUE THREAD

**Issue by CeUvi** [TauCetiStation/TauCetiClassic#6610]
#### Подробное описание проблемы
Алиены всё ещё умирают с двух-трёх пуков лазерки
#### Что должно было произойти
Алиены живут долго и не сосут от одного человека с аеганом
#### Что произошло на самом деле
Сосание
#### Как повторить
Поиграть в алиенов
#### Дополнительная информация:
Issue reported from  Round ID: 38000 (Tau Ceti Classic II (RU))
Testmerges: ```#6400 #6453 #6499 #6540 ```
Reporting client version: 513.1532

**Comment by Lexanx** [comment]
80 урона с любого лазера. Это типо Алиены так огня бояться? В фильмах лазеров конечно не было. Поэтому хз насколько оно правильно.
Но чужие ваншотались с плазмы,(Чужой против Хищника) которая в игре почему то около 30 наносит им. Логичней было бы выдавать плазме больше урона, чем лазеру в таком случае. Но тут я думаю, баланс департамент нужен?

**Comment by Kortez90** [comment]
Fixed by #6704.
