### ISSUE TITLE
Установка постеров на стены.

### ISSUE THREAD

**Issue by OfGreyBugWaifu** [TauCetiStation/TauCetiClassic#662]
#### Подробное описание проблемы

При установке постеров, они зачастую будут клеиться не на ту стену, куда вы кликнули, а на стену (или даже пол или дверь) слева, справа, сверху или снизу.
#### Что должно было произойти

Постер должен был повеситься на стену, на которую я кликнул.
#### Что произошло на самом деле

Постер повесился на стену рядом с той, на которую я кликнул.
#### Как повторить

Срезать из прачечной\столовой постер\заказать из карго и кликнуть им на стену.
#### Дополнительная информация:

Функционально постер также вешается не туда, куда кликнул - его механо место тоже уезжает вместе с моделькой и срываешь\срезаешь его кликом по съехавшей текстуре.

**Comment by SpaiR** [comment]
@OfGreyBugWaifu баг ещё актуален? Если да, то напиши конкретную последовательность действий как его можно повторить, так как с этим возникают проблемы.

**Comment by Djekke** [comment]
Баг актуален, срезав кусачками постер он повесился на стену за стеной на которую клеил.

**Comment by Dennok** [comment]
По коду я вижу что постер крепит в турф, когда надо чтоб его делало как и апц, сдвигом на турф с спаном перед ним.

**Comment by Dennok** [comment]
вот тут https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/game/objects/effects/decals/contraband.dm#L235
