### ISSUE TITLE
Иксрей камеры не работают из консоли камер

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6630]
#### Подробное описание проблемы
Иксрей камеры которые делаются из анализатора работают у ИИ, но не работают из секьюрити консоли. Могу предположить что они не работают и из консоли ксенобиолога

#### Что должно было произойти
Иксрей камеры должны показывать тайлы скрытые стенами из секьюрити консоли

#### Что произошло на самом деле
Иксрей камеры не показывают тайлы за стенами из секьюрити консоли

#### Как повторить
Сделать иксрей камеру и посмотреть на неё из секьюрити консоли.

**Comment by BesumniiChebureck** [comment]
Скорее всего просто беды с переменной network() у этих камер.

**Comment by AirBlack** [comment]
Вообще неплохо было бы перенести камеры на тгуи или на че там на тг камеры, шобы сам вью не менялся и то что в камере отображалось бы в отдельном окне

**Comment by KIBORG04** [comment]
Вроде как, на тг все камеры, как у нас сейчас в ксенобиологии, то есть ты летаешь за глаз по станции

**Comment by AirBlack** [comment]
я видел где-то что камеры в отдельном окне были как уменьшенные вьюхи, так логичнее и было бы прикольно сделать, надо на тг зайти проверить

**Comment by AirBlack** [comment]
да, на тг так, как я и говорил, а именно вот так
![image](https://user-images.githubusercontent.com/5171605/103504913-fea6ee80-4e82-11eb-9c8e-acfc2dd924ff.png)

**Comment by AirBlack** [comment]
<details>
  <summary>здравствуйте</summary>
![image](https://user-images.githubusercontent.com/5171605/103560975-e2d33500-4ee2-11eb-9c9a-32c8f175dd90.png)
</details>

**Comment by Sakuya-Izayoi** [comment]
Очень круто! Вот если бы иишка мог себе ещё такое окошко открывать и в случае чего джампаться на камеры...

**Comment by AirBlack** [comment]
ИИшка и без этого может джампиться на камеры
