### ISSUE TITLE
[Proposal] При добавлении бана автоматически добавлять номер раунда.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6631]
#### Подробное описание проблемы
Нужно избавиться от дописывания номера раунда в нотесах вручную и автоматизировать процесс, как в случае с ником добавившего и датой.

**Comment by ViDLiathan** [comment]
Эта функция должна быть выключена по умолчанию. Или через диалоговое окно, в которое можно самому вписать айди, а по умолчанию там текущий раунд.
