### ISSUE TITLE
[Proposal] Добавить воуту restart описание

### ISSUE THREAD

**Issue by Tiarv** [TauCetiStation/TauCetiClassic#6632]
#### Подробное описание проблемы
Мимокрокодилы приходят и прожимаю рестарт когда им хочется. Мимокрокодилы не знают что прожимать рестарт просто так нельзя и узнать им об этом неоткуда, если специально не будут предварительно искать (а они не будут). Мимокрокодилы получают жбан, а потом бегут плакать. Поэтому было бы круто, если бы возле кнопочки воута на рестарт была бы маленькая красненькая надпись, которая бы гласила, например, следующее: "Only in case of emergency. Misuse will be punished with prejudice".

**Comment by Sakuya-Izayoi** [comment]
Надо не добавлять какое-то описание или ещё что-то, надо просто не позволять делать то, за что можно получить бан.

Для рестарта нужно 75% голосов. Если он прошел, значит игроки считают что он нужен.

Тут проблема не в том, что игрок рестартят раунд когда хотят, а в том, что администрация считает игроков слишком тупыми, чтобы принимать такие решения.

Вот если вы действительно так считаете проще забрать воут на рестарт вообще, тогда и банить никого не придётся, и игроки не будут плакаться из-за рестартов.

**Comment by Tiarv** [comment]
> Для рестарта нужно 75% голосов. Если он прошел, значит игроки считают что он нужен.

В текущей реализации кроме трешолда в 75% голосов там еще есть глобал кулдаун, поэтому если условный Вася гибнулся и прожал рестарт от обидки или малоумия, то когда рестарт будет нужен - за него нельзя будет проголосовать.

И, сейчас есть кнопка, за нажатие на которую пиздят ногами, при этом узнаешь о том что тебя за нее отпиздят ногами только после того как ты на нее нажмешь. Надо либо прекратить такую практику, либо написать что кнопка делает и в каких случаях ее нужно нажимать, в каких - не нужно, что будет если ты нажмешь ее не тогда, когда надо.

**Comment by T6751** [comment]
Описание к рестарт воуту добавлено в #7452
