### ISSUE TITLE
Открываются сразу два шлюза, хотя должен открыться один

### ISSUE THREAD

**Issue by Kleyrt** [TauCetiStation/TauCetiClassic#664]
#### Подробное описание проблемы

У ксенобиолога открываются оба шлюза
#### Что должно было произойти

Один шлюз закрывается, второй открывается
#### Что произошло на самом деле

Оба шлюза открылись
#### Как повторить

Нажимаем одну любую кнопку, отвечающую за шлюз, и быстро нажимаем вторую кнопку, отвечающую за другой шлюз

**Comment by Dennok** [comment]
Ващет это ты ее забагал. Если одна дверь заблокирована мобом она не закрадется, но при этом вторая откроется.

**Comment by Kleyrt** [comment]
Лол, нет. Я это делал один и в дверях никого не было. Могу в игре показать, если непонятно.

**Comment by Dennok** [comment]
Да. второй вариант кликнуть вторую кнопку пока 1я дверь еще не до конца открылась.

**Comment by Kleyrt** [comment]
Я этот способ и описал

**Comment by LudwigVonChesterfield** [comment]
#2605
