### ISSUE TITLE
СПУ могут быть культистами

### ISSUE THREAD

**Issue by ghost** [TauCetiStation/TauCetiClassic#6640]
#### Подробное описание проблемы
СПУ могут законвертить в культ. Для этого нужно согласие, но лучше это ограничить механом, ибо это в корне неверно
#### Что должно было произойти
СПУ не должен конвертиться в культ, так как у них нет души, а культ основан на крови и душах. Даже в предложении конверта спрашивают - готовы ли вы пожертвовать своей душой
#### Что произошло на самом деле
СПУ законвертился в культ
#### Как повторить
Поставить СПУ на руну конверта и законвертить. Если он согласится, то присоединится к культу.
#### Дополнительная информация:
Неплохо бы проверить так же, как работает конверт СПУ в треллы тенелингов. Там согласие не нужно, но суть примерно такая же. Раньше они конвертились и приходилось снимать трелла педально.

**Comment by Kortez90** [comment]
#5256.
