### ISSUE TITLE
Шлюзы иногда толкают в окна.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6649]
#### Подробное описание проблемы
Человек, попавший в закрывающийся шлюз может отправиться не на пустой тайл, а в тайл с окнами и гридом.

**Comment by Sakuya-Izayoi** [comment]
#6566 test feedback

**Comment by KIBORG04** [comment]
![image](https://user-images.githubusercontent.com/26389417/103883427-3e254300-50ee-11eb-9b99-4faa379f429c.png)

Видимо, пофикшено, если проблемы была с форсмувом
