### ISSUE TITLE
Ножики

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#665]
#### Подробное описание проблемы
Ножик пробил РИГ, застрял в теле и его нельзя вытащить
#### Что должно было произойти
Ножик можно вытащить
#### Что произошло на самом деле
You have nothing stuck in your body that is large enough to remove.
#### Как повторить
Кинуть ножиком в человека в РИГЕ

**Comment by StrikS** [comment]
Хехеех, клоун молодец. Хорошо метнул.

**Comment by YulianR** [comment]
Вообще странно, надо сделать чтоб только осколки и пули-шрапнели нельзя было вытащить руками. А то глупо получается, воткнул например вилку (NERFED) в человека, а вытащить не можешь почему-то

**Comment by Skippeer12** [comment]
> Вообще странно, надо сделать чтоб только осколки и пули-шрапнели нельзя было вытащить руками. А то глупо получается, воткнул например вилку (NERFED) в человека, а вытащить не можешь почему-то

Можно вытащить все, от осколка пули и до вилки. Но если ты будешь делать это руками, то ты скорее подохнишь от дамаги, которую сам себе и нанесешь либо упадешь в болевой крит и подохнишь от кровотечения.
