### ISSUE TITLE
[Proposal] Объединение двух мед-модулей киборгов в один.

### ISSUE THREAD

**Issue by Ro2tCrab** [TauCetiStation/TauCetiClassic#6657]
В нынешних реалиях на **Мед-Модулях** редко можно встретить киборга, ибо существует серьёзное ограничение того, что наш юнит способен сделать.
К примеру: Обычный медик носит в сумке от 6 типов лекарств в отдельных колбах, которые он может применить в зависимости от ситуации. Киборг же обладает ограниченным спектром лекарств в гипоспрее (В количестве 30 юнитов каждого, но этих лекарств недостаточно для эффективного лечения.) и колбой на 150 юнитов реагента. Киборг не способен провести реанимацию своими силами, ибо не способен взаимодействовать и лечить (В арсенале киборга есть только бинты и мазь) людей должным образом. В итоге мы получаем крайне медленного и не эффективного сотрудника мед-блока, которому просто нечего делать на станции.
Аналогичная участь может ждать и модуль хирурга, ибо со своими модулями он не способен сделать что-то вне хирургии, но в то же время хирург может уйти от пустого операционного стола и начать помогать лечить менее травмированных пациентов.
Что в итоге? Геймплей за **Мед-Бота** является крайне скучным из-за низкого показателя эффективности по сравнению с гуманоидами. Геймплей **хирурга**  является слишком узконаправленным и заставляет игрока сидеть на месте всю смену.

Я считаю необходимым объединение двух разных мед-модулей с добавлением  мембран для лечения конечностей и обновлением списка реагентов гипоспрея (Лекарств из обычного Sleeper'а будет достаточно). Да, это не решает проблему неспособности юнита реанимировать человека, но сделает работу киборга эффективней и разнообразней.

**Comment by Lafrien** [comment]
Я против данной просьбы. "Мед-Бот" на самом деле имеет более, чем достаточно средств для своего существования.
1. Имеет доступ в химию и возможность в неё-же. Сделать алкизин, сделать баночку и вколоть из баночки в пациента или запихнуть в холодильник - запросто.
2. Наш медбот не врач, а парамедик. Каталка, доступ к мгновенному вкалыванию гипоспреем через костюмы, "Чёрт, да он же в космос вышел за 6 действий со шлюзами со своим полным доступом и встроенным пультом управления и ведь не задыхается даже!". 
Одного этого пункта уже более, чем достаточно.
3. Может он и имеет гипоспрей с ограниченными лекарствами, но этого достаточно оттянуть время неминуемой смерти до прибытия в медбей.
4. Если вызов был не столь экстренный, то на месте можно остановить кровотечение бинтами и помазать мазью, дабы не ввести инфекцию. Для ускоренного выздоровления ввести трик.
Единственное, чего может и не хватает медботу, так это возможно планшет датчиков, хоть и так этот юнит уже многое может.

Давайте дальше к модулю хирурга.
Тут я может и соглашусь - по сравнению с прошлым модулем хирург просто шутка узкопрофильная и единственный бонус этого модуля состоит в том, что у тебя с начала раунда уже есть "Вскрыватель2000". Да, на этом все плюшки данного модуля заканчиваются и это обидно...

Модуль Врача не надо ни в какую сторону трогать, можно если только планшет выдать, если сильно хочется его бафнуть и дать ему прямой намёк, чем он должен заниматься на самом деле.
А вот с модулем Хирурга нужно-бы поработать, ведь и до того механ хирурга однообразен и долгок, при том, что на всю станцию от силы 3 стола, а врачей может быть до 4х, то хирург-боту иногда негде работать при полном наплыве трупов (если не считать каталки), а отличия от обычного хирурга не столь высокое, к сожалению.

**Comment by Sakuya-Izayoi** [comment]
> А вот с модулем Хирурга нужно-бы поработать, ведь и до того механ хирурга однообразен и долгок, при том, что на всю станцию от силы 3 стола, а врачей может быть до 4х, то хирург-боту иногда негде работать при полном наплыве трупов (если не считать каталки), а отличия от обычного хирурга не столь высокое, к сожалению.

Просто напомню, что модули у нас не навсегда и их можно сменить. Так что если на смену зашло много врачей, всегда можно сменить модуль на более полезный.

**Comment by Lafrien** [comment]
> Так что если на смену зашло много врачей, всегда можно сменить модуль
Если с начала раунда много врачей, то ты не возьмёшь модуль хирурга (об этом кстати позже), а если их стало много, то далеко не "всегда" можно сменить модуль. Требуется Робототехник/РД. А в процессе раунда их не только может и не быть, или быть занятыми другим делом, но и просто умереть.

Еще возвращаясь к тому, что модуль хирурга с самого начала раунда даже не хочется брать по той причине, что ты мог просто быть более полезным простым мешком плоти, чем чрезмерно узкопрофильный модуль. 
Фишка модуля парамедика в том, что он в космос без проблем может выйти да по отделам без проблем кататься, но модуль хирурга просто-напросто остаётся в одном отделе и не только не может использовать свои преимущества быть многогранным юнитом с полным доступом, но и не может дать квалифицированную мед-помощь - он не сможет вылечить твои повреждения мозга вызванные имплантом, не сможет вылечить ожоги, так как нету мази и не сможет вылечить кровотечение, поскольку мембран мало и они нужны для операций.
Хирург-бот - сомнительный выбор, как и некоторые другие модули.

**Comment by FBitSafe** [comment]
хмм, хирург-бота можно бафнуть полным отключением провала операции, чтоб он мог проводить их даже на каталке, а мембраны мог пополнять через вендомат с медикаментами.
