### ISSUE TITLE
В камерах инженерки на обычной карте нет нетворка Engineering

### ISSUE THREAD

**Issue by AirBlack** [TauCetiStation/TauCetiClassic#6667]
#### Подробное описание проблемы
На камерах инженерки нет нетворка Engineering. На зимней карте вроде есть по словам Кортеза.
#### Что должно было произойти
Камеры инженерки есть и видны на консоли инженерной
#### Что произошло на самом деле
Камер нет, в консоли видны только дроны, борги и тревоги
#### Как повторить
Посмотреть в консоль камер инжунерных
#### Дополнительная информация:
Возможно это as intended и в инженерной консоли добавлен нетворк Engineering только ради того чтобы следить за боргами и дронами да и мне так нравится, но вот кортез мне мозги выпотрошил насчет этого и обвинял что мой пр это сломал(это не так) и что там должны быть еще камеры всей инженерки.

**Comment by BesumniiChebureck** [comment]
На камерах у инжей нету нетворка Инженеринг ни с твоим ПРом, ни с Зимним Лесом, ни с обычной картой. А нетворк, изначально предназначался для того чтобы следить за дронами и инж. боргами, да.
![image](https://user-images.githubusercontent.com/67091522/103996760-5ad38080-51ab-11eb-9590-f99ff4a2f58e.png)
![image](https://user-images.githubusercontent.com/67091522/103996820-6de65080-51ab-11eb-95f4-3d58729aa0e3.png)
![image](https://user-images.githubusercontent.com/67091522/103996899-835b7a80-51ab-11eb-9e97-1ab1eb3c2939.png)

**Comment by Kortez90** [comment]
> На зимней карте вроде есть по словам Кортеза.

А вот это неправда.

**Comment by AirBlack** [comment]
> А вот это неправда.
то есть ты все-таки ругался на то что в консоли той инженерной нашей любимой сразу не появлялись камеры с мест где тревога? ты же так и говорил, что так и так в этой консоли должны быть все камеры инженерки и говорил что так было на зимней карте вроде.

**Comment by AirBlack** [comment]
не, ну если это as intended то можно закрывать спокойно, только пусть мне кто-нибудь из знающих билд скажет, что это as intended
