### ISSUE TITLE
Камера "Cargo Bay Entrance" не туда смотрит. 

### ISSUE THREAD

**Issue by DedYarick** [TauCetiStation/TauCetiClassic#6668]
#### Подробное описание проблемы
Не баг, скорее недоработка - Камера "Cargo Bay Entrance" (это если что внутренняя часть карго) показывает коридор между парихмахерской и офисом ГП 
![image](https://user-images.githubusercontent.com/63983146/104001306-80af5400-51b0-11eb-8102-1a566bda2857.png)

#### Что должно было произойти
Камера "Cargo Bay Entrance" показывает Cargo Bay Entrance
#### Что произошло на самом деле
Камера "Cargo Bay Entrance" показывает коридор между парихмахерской и офисом ГП 
#### Как повторить
Сидя за камерами посмотреть камеру "Cargo Bay Entrance"
![image](https://user-images.githubusercontent.com/63983146/104001739-2b277700-51b1-11eb-9a4d-038f1cf8c92c.png)

**Comment by AirBlack** [comment]
Проверил, проблема карты

<details>
<summary>пруф</summary>

![image](https://user-images.githubusercontent.com/5171605/104003362-8155e380-51cc-11eb-9564-7d52efc3764c.png)

</details>

я не умею и боюсь редачить карты так что нужен маппер, я конечно могу вручную изменить ситэг в дмм

**Comment by AirBlack** [comment]
сменил на Central Hallway South-West

**Comment by BesumniiChebureck** [comment]
Это не из-за ПРа с новыми камерами, с_тэг был указан не верно ещё до него.

**Comment by AirBlack** [comment]
я знаю, но кортез повешал ишью на меня и сказал делать, посмотри сколько на мой пр ишью повешали, я офегел

**Comment by DedYarick** [comment]
Ещё одна камера с неправильным названием. 

Камера "Security Maintance" смотрит в теха брига. 
![image](https://user-images.githubusercontent.com/63983146/104049770-8fb8f500-51f6-11eb-9104-becd7832f7af.png)

**Comment by Kortez90** [comment]
И куда она "должна" смотреть по-твоему?
С названием у нее порядок.

**Comment by DedYarick** [comment]
Точно, мой косяк. Неправильно название перевёл, простите.

**Comment by Sakuya-Izayoi** [comment]
> И куда она "должна" смотреть по-твоему?
> С названием у нее порядок.

Мне кажется это Dormitory Maintenance

**Comment by Lexanx** [comment]
Не знаю может так и было задумано.
Но в Бриге еще есть вот-с
![image](https://user-images.githubusercontent.com/61974560/104074222-98bebc00-5220-11eb-9197-1ce3d846569c.png)
North West

И 

![image](https://user-images.githubusercontent.com/61974560/104074247-a83e0500-5220-11eb-88ac-91fa993be791.png)


Понимаю что это камеры расположенные в 2 разных частях комнаты. Но видно на них одно и тоже с разницей в 1 клетку шириной. ( которая по большей части показывает стену и стекло)

Раньше с северной камеры можно было проглядывать улицу, и в ней был смысл. Теперь же не особенно

**Comment by AirBlack** [comment]
меня попросили убрать изменение си тэга из моего пра и в другом пре сменить, из своего пра я убрал но новый создавать не стал, простити, пусть маппер какой-нибудь все эти камеры поменяет

**Comment by AirBlack** [comment]
с верхней камеры улицу ну или космос видно прекрасно, у тебя так обрезалось из-за сработавших створок из-за которых перестало быть видно космис
<details>
<summary>пруф</summary>

![image](https://user-images.githubusercontent.com/5171605/104107759-249c1b00-52e9-11eb-9b50-e5cd5da92aff.png)

![image](https://user-images.githubusercontent.com/5171605/104107768-34b3fa80-52e9-11eb-85c2-33991efcac66.png)

</details>
