### ISSUE TITLE
Кусачки срезают наручники при попытке вскрыть шею

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6673]
#### Подробное описание проблемы
Если попробовать вскрыть шею человеку в кабельных наручниках кусачками, то они срежутся.

#### Что должно было произойти
Должна вскрываться шея/отрезаться голова, например, только при харм интенте. Наручники срезаться же при хелпе

#### Что произошло на самом деле
При любом интенте срезаются наручники.

#### Как повторить
Надеть cable restraints на человека, взять в киллграб, кликнуть кусачками по голове.

#### Дополнительная информация:
https://github.com/TauCetiStation/TauCetiClassic/blob/d9c2db2b0725c5345d7f36dc7cea91c9fce213f6/code/game/objects/items/weapons/tools.dm#L160

Тут ещё не очень хорошо удаляются наручники, как мне кажется.

**Comment by TheLone1y** [comment]
Фича
