### ISSUE TITLE
Камеры абдукторов сломаны.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6679]
#### Подробное описание проблемы
Консоль камер шлемов абдукторов показывает один статичный спрайт.
#### Как повторить
- Посмотреть через камеру абдукторов при наличии шлемов.

**Comment by 4310V343k** [comment]
Всегда работало, теперь нет
Ни скрина, ни объяснений
Шлем включили? Он привязан к консоли? Абдукторы раундстартовые?

**Comment by Kortez90** [comment]
Это из-за ТМ.
Да, включили, да привязан, да обычные.

**Comment by AirBlack** [comment]
камеры синдикеков так же не работают

**Comment by AirBlack** [comment]
пофиксил
