### ISSUE TITLE
Переселение души из живого персонажа при клонировании.

### ISSUE THREAD

**Issue by Parterson** [TauCetiStation/TauCetiClassic#668]
#### Подробное описание проблемы:

В начале раунда сканировался в генетике, персонаж погиб, я зашел за ЕРТ. Затем ИИ стал клонировать "старого" меня и моя душа переселилась в тело в клонподе.
#### Что должно было произойти:

Я должен был остаться в прежнем теле
#### Что произошло на самом деле:

Я переселился в тело в клонподе.
#### Как повторить:

Просканироваться, умереть, зайти за ЕРТ, начать процесс клонирования

**Comment by StrikS** [comment]
Займусь

**Comment by KuzyXD** [comment]
В итоге парень не занялся. Простое ишью же.
