### ISSUE TITLE
anchored иногда приравнивают к десятичной дроби

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#6685]
#### Подробное описание проблемы
anchored вроде как даже не подразумевалась как десятичная дробь

![image](https://user-images.githubusercontent.com/26389417/104136652-94bda600-53a8-11eb-8b77-9f1664204fb1.png)

#### Что должно было произойти
Нету точки

#### Что произошло на самом деле
Точки есть

#### Как повторить
Посмотреть в код

#### Дополнительная информация:
Контрл + ф `anchored = 1.0` => `anchored = TRUE`
Контрл + ф `anchored = 0.0` => `anchored = FALSE`

**Comment by KIBORG04** [comment]
похожая фигня и с денсити
![image](https://user-images.githubusercontent.com/26389417/104136829-ace1f500-53a9-11eb-8757-4138a90e30c0.png)

**Comment by KIBORG04** [comment]
>Контрл + ф anchored = 1.0 => anchored = TRUE
Контрл + ф anchored = 0.0 => anchored = FALSE

А еще лучше поменять на тру и фолс не только десятичные дроби, но и обычные цифры

**Comment by Sakuya-Izayoi** [comment]
а в дримчекере можно как-то сделать чтобы для этих переменных валидными значениями были только TRUE и FALSE?

**Comment by T6751** [comment]
В целом можно сказать, что это глобальная проблема, что у нас булевые переменные вместо TRUE FALSE используют 1 и 0.
На тг, например, эта проблемы была затронута в этом ПРе: https://github.com/tgstation/tgstation/pull/53221

В целом было бы хорошо пройтись по билду и заменить соответственно циферки на TRUE и FALSE. Хотя решать эту проблему постепенно тоже хорошо.
