### ISSUE TITLE
[Proposal] показывать задеклеренных чаров

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6687]
Порт реквест фичи с эриса, а именно, показывание в стат панельке перед раундстартом задеклеренных чаров и их high-преференс, чтобы видеть кто куда заходит и всё такое.

**Comment by AndroBetel** [comment]
у нас админам нельзя сикеи игроков и кукол показывать почему-то а ты такую штуку просишь

**Comment by SpaiR** [comment]
А потом заходишь в крюманифест и видишь, что 6 типов из задеклереных отсутствуют... Вариантов как это можно использовать для метагейминга слишком много. Да и в принципе, подобное уже было пару лет назад, но в виде задеклереных сикеев. И даже там это всплывало, потому что игроки запоминали кто на ком играет.

**Comment by FelixRuin** [comment]
но утверждать то, что они эвейдят цели на себя тоже можно
