### ISSUE TITLE
Рантайм таймера.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6688]
#### Подробное описание проблемы
```
Invalid timer: timer.timeToRun=8941.9||QDELETED(timer)=8943.1||world.time=8943.1||head_offset=8731.9||practical_offset=526||timer.spent=0 in timer.dm:82 :
proc name: fire (/datum/controller/subsystem/timer/fire)
  source file: timer.dm,82
  usr: null
  src: Timer (/datum/controller/subsystem/timer)
  call stack:
Timer (/datum/controller/subsystem/timer): fire(1)
Timer (/datum/controller/subsystem/timer): ignite(1)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```
#### Как повторить
Загадка.
#### Дополнительная информация:
По каким-то странным причинам периодически рантаймит таймер.

**Comment by KIBORG04** [comment]
Скорее всего из-за прока Trip у голиафоф.

Афк стоя на локалочке получил несколько рантаймов с таким описанием, предварительно модифицировав его для получения делегата каллбэка.
![image](https://user-images.githubusercontent.com/26389417/104165838-f878bb00-540a-11eb-8194-59d0d8645ad0.png)

**Comment by Kortez90** [comment]
Этот прок вызывался во время выпуска тентаклей голиафом. На что он мог реагировать в шахте вообще?

**Comment by LudwigVonChesterfield** [comment]
на шахтерских мобов с дружественным модификатором к примеру

**Comment by Kortez90** [comment]
Воспроизвести не вышло.

**Comment by KIBORG04** [comment]
> Воспроизвести не вышло.

Встань афк на локалочке на 10-110 минут. Воспроизводится во всех случаях из десети
