### ISSUE TITLE
Большие дионы и Plant Be Gone

### ISSUE THREAD

**Issue by Lexanx** [TauCetiStation/TauCetiClassic#6689]
#### Подробное описание проблемы
Дионы являются растениями, и логично предположить что plant be gone. Должен быть вреден для них, но как оказалось. Вреден он только маленьким дионам. Взрослые успешно необращают на него внимание.

#### Что должно было произойти
Plant be gone должен быть вреден для всех дион

#### Что произошло на самом деле
Маленькая Диона получает Токси урон, Хуман получает Токси Урон. А вот Большая диона, выше этих низменных проблем.

#### Как повторить
Опрыскать Взрослую Диону plant be gone.

**Comment by kalazus** [comment]
Перерыл кучу кода, оказывается что дионы неуязвимы к токсинам из-за флага отсутствия крови. Займусь возможно на выходных.
