### ISSUE TITLE
Трик перестал лечить берн урон.

### ISSUE THREAD

**Issue by CryptoKisik** [TauCetiStation/TauCetiClassic#669]
#### Подробное описание проблемы:
После недавнего обновления медицины обнаружилась проблема. Трикордразин (анти-токсин + инапровалин) перестал лечить берн урон.

#### Что должно было произойти:
Трик должен лечить берн урон.

#### Что произошло на самом деле:
Трик просто находится в организме. Берн урон не уменьшается.

#### Как повторить:
Получить ожоги любой тяжести и вколоть в себя трик.

**Comment by StrikS** [comment]
Проверил на локалке действительно берн не лечится. Со всеми остальными типами урона вроде все хорошо.
