### ISSUE TITLE
 Book Scanner пропал [Bug]

### ISSUE THREAD

**Issue by Worm-dodcom** [TauCetiStation/TauCetiClassic#6690]
#### Подробное описание проблемы
В библиотеке был Book Scanner позволяющий новые книги записывать в базу данных, но сейчас его почему то нет, значит новые книги в базу не добавить. 
#### Что должно было произойти
 Book Scanner есть в библиотеке.
#### Что произошло на самом деле
 Book Scanner-ра нет в библиотеке.
#### Как повторить
Зайти на один из серверов, пройти в библиотеку и не обнаружить  Book Scanner.

**Comment by 4310V343k** [comment]
Пришёл с другого билда и говорит что у нас неправильно
У библиотекаря в кармане спавнится портативный сканер, им и работай

**Comment by Worm-dodcom** [comment]
Ты про barcode scanner? Он же только добавляет книги в буфер, этот сканер не дает возможности добавить книгу в базу данных.

**Comment by 4310V343k** [comment]
Ты прав

**Comment by Worm-dodcom** [comment]
Так как тогда добавлять новые книги в базу данных?

**Comment by Kortez90** [comment]
![Безымянный](https://user-images.githubusercontent.com/36198983/104208603-bb7beb00-5441-11eb-8be1-ddc6b4d8b884.png)

**Comment by Worm-dodcom** [comment]
Да, все верно, но проблема же в том, что в библиотеке нет этого принтера, есть только два что печатают копии документов. Там где был этот принтер сейчас мусорка и растение в горшке.

**Comment by Kortez90** [comment]
![Безымянный](https://user-images.githubusercontent.com/36198983/104210534-0dbe0b80-5444-11eb-9e5e-9d088dd9dd32.png)

**Comment by 4310V343k** [comment]
Это копирка

**Comment by BesumniiChebureck** [comment]
Кортез эта штука на твоем последнем скрине просто делает копии бумаги и фото.

А нам надо это:
![image](https://user-images.githubusercontent.com/67091522/104211413-195e0200-5445-11eb-8c08-c497bfdb58be.png)
В библиотеке есть эта штука, просто у неё спрайт другой:
![image](https://user-images.githubusercontent.com/67091522/104211520-37c3fd80-5445-11eb-9d70-b403336e5bd3.png)

**Comment by 4310V343k** [comment]
![image](https://user-images.githubusercontent.com/56449763/104212409-419a3080-5446-11eb-9bc9-f90325d874b2.png)
Всё равно не то :)

**Comment by Kortez90** [comment]
Все верно. Один любитель переделывать трубы удалил сканер, решив что это третий копировальный аппарат. #6500.
![Безымянный](https://user-images.githubusercontent.com/36198983/104212602-760dec80-5446-11eb-88cc-d4e418f79aa2.png)

**Comment by BesumniiChebureck** [comment]
> Всё равно не то :)

Блин

> Все верно. Один любитель переделывать трубы удалил сканер, решив что это третий копировальный аппарат

Уже второе стелсо изменение этого ПРа.
