### ISSUE TITLE
Баг возможности вывалить вещи на пол перетаскиванием

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#6695]
#### Подробное описание проблемы
Если засунуть пробирки в защищенный виал бокс вирусолога и закрыть, то перетягиванием на пол колбы всеравно можно достать
#### Что должно было произойти
Колбы не вываливаются из закрытого виал бокса
#### Что произошло на самом деле
Вываливаются
#### Как повторить
Разблокировать secure vial storage box, засунуть пробирки, заблокировать, перетащить спрайт коробки на пол

**Comment by T6751** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/6394
