### ISSUE TITLE
Бесполезные инструменты для раскопок у научного борга

### ISSUE THREAD

**Issue by Kleyrt** [TauCetiStation/TauCetiClassic#671]
#### Подробное описание проблемы

У борга (научного) есть инструменты для ксеноархеологии, однако нет дрели или чего нибудь, чем можно копать (не считая кирку, которая копает на 30 см). Также, у борга нет набора кирок для раскопок (на 2, 4, 6 и т.д. см)
#### Что должно было произойти

Должны присутствовать все инструменты, иначе зачем боргу инструменты для ксеноархеологии (типо того, что ищет аномалии. Он есть у борга)?
#### Что произошло на самом деле

Инструментов нет.
#### Дополнительная информация:

Просто хотел позаниматься раскопками за борга, и обнаружил, что у него не всё есть для ксеноархеологии. Обидно. Хотя зачем боргу этим заниматься, если борги не могут поднимать предметы? И вообще, если посудить, то борг научный будет полезен только в ксенобиологии. А так - он как ассистент. Ассистент-инвалид.

**Comment by Damirrus1** [comment]
Борги и есть ассистенты-инвалиды, они помогают, а не заменяют.

**Comment by dearprincesscelestia** [comment]
Во-первых, 

> Борги и есть ассистенты-инвалиды, они помогают, а не заменяют.

Это. Предполагалось, что научборг должен уметь помогать любому из ученых (кроме торчащих в рнд аутистов; хотя и там можно пуллить склянки к химикам за кислотой и щелкать кнопки на анальном дестроере), не умея заменить никого.

Во-вторых, они пилились под старый механ, плюс с настраиваемой киркой. Я даже не помню, вышла ли у меня она. В любом случае, кирки надо будет делать заново.

И все же, во-первых, научборг не должен уметь полностью заменять ученого. Наверное. Хотя всегда можно украсть манипулятор у дрона и переписать так, чтобы можно было брать научный шитз.
