### ISSUE TITLE
Сломан интерфейс у консоли дронов.

### ISSUE THREAD

**Issue by BesumniiChebureck** [TauCetiStation/TauCetiClassic#6726]
#### Подробное описание проблемы
Название
#### Что должно было произойти
Нормальная консоль
#### Что произошло на самом деле
![улнекул](https://user-images.githubusercontent.com/67091522/104815551-45eb9280-5826-11eb-9f67-757b8e287796.PNG)

#### Как повторить
Нажать вот по этой консоли
![image](https://user-images.githubusercontent.com/67091522/104815564-5a2f8f80-5826-11eb-9055-01a6b2e535d7.png)

**Comment by Kortez90** [comment]
#6343.
