### ISSUE TITLE
На одиссее не работает стрейф

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6728]
#### Подробное описание проблемы
Если включить стрейф режим на одиссее, он будет поворачиваться

#### Что должно было произойти
В стрейф режиме одиссей не должен поворачиваться при движении

#### Что произошло на самом деле
Одиссей поворачивается в стрейф режиме

#### Как повторить
Включить стрейф режим на одиссее и походить в разные стороны

#### Дополнительная информация:
Апдейт: стрейф режим у одиссея делает так, что он ходит без поворота, ИМХО это должна быть отдельная кнопка, то есть должно быть две кнопки: стрейф режим и ходьба без поворота

**Comment by Kortez90** [comment]
#6313.
