### ISSUE TITLE
Ивент космопыли не работает

### ISSUE THREAD

**Issue by PirogSema** [TauCetiStation/TauCetiClassic#6738]
#### Подробное описание проблемы
Пояс космопыли сразу заканчивается после начала
#### Что должно было произойти
Пыль атакует станцию хотя бы 10 секунд
#### Что произошло на самом деле
Пыль сразу заканчивается как начинается, станция не получает почти никакого ущерба
#### Как повторить
Получить ивент space dust
#### Дополнительная информация:
![изображение](https://user-images.githubusercontent.com/22032604/105061943-1ee1ca80-5a8b-11eb-9f2d-d02d20cd08fc.png)

Issue reported from  Round ID: 38405 (Tau Ceti Classic II (RU))
Testmerges: ```#6394 #6557 #6660 #6675 #6686 ```
Reporting client version: 513.1528

**Comment by 4310V343k** [comment]
Luck

**Comment by Kortez90** [comment]
https://github.com/TauCetiStation/TauCetiClassic/blob/6bf22d247f6dc7b4f2f37cd9583c85f41c124cf5/code/modules/events/dust.dm#L5-L6

Неудивительно.
