### ISSUE TITLE
Пии еще не починили

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6758]
#### Подробное описание проблемы
Этому крутому багу из-за рефактора сейкода уже примерно полгода, но никто его еще не починил, а следовательно потерялась собственно играя возможность нормально функционировать за карманный компухтер, из-за чего пии можно выпиливать из-за мазохизма при попытках за него поиграть.
#### Что должно было произойти
Пии умеет говорить когда его держут в руках/штанах/пда/сумке/шкачиках/где угодно/etc
#### Что произошло на самом деле
Космонавтивки virgin кладут пии на тайл и разговаривают потому что нет иных возможностей.
#### Как повторить
Вкатитесь за пии, плачьте

**Comment by Kortez90** [comment]
#6423.
#6104.
#6000.
