### ISSUE TITLE
Пропавшие спрайты брюк и джинсов

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#676]
#### Подробное описание проблемы
Спрайты с разных брюк и джинсов в автомате в раздевалке пропали.
#### Что должно было произойти
У вещей должен был спрайт
#### Что произошло на самом деле
Спрайта нет. Ни вещи, ни на персонаже.
#### Как повторить
Воспользоваться автоматом с одеждой.
#### Дополнительная информация:
http://i.imgur.com/y58t9NS.png

**Comment by Kurshan** [comment]
Стоит составить целый список пропавших вещей.

**Comment by Damirrus1** [comment]
Это, да кстати, скрины можно вставлять CTRL+V

**Comment by Kurshan** [comment]
Проблема в пути \code\modules\clothing\under файлика pants.dm. @SpaiR
