### ISSUE TITLE
Укрепленный шлем Синдиката не имеет спрайта для воксовской модификации.

### ISSUE THREAD

**Issue by BesumniiChebureck** [TauCetiStation/TauCetiClassic#6764]
#### Подробное описание проблемы
У Укрепленного шлема Синдиката в модификации под воксов нету спрайта. Из-за чего он не видим и его не возможно снять/одеть (хотя одеть ещё можно попытаться). Спрайт на кукле есть если что.
#### Что должно было произойти
Всё нормально
#### Что произошло на самом деле
![ah](https://user-images.githubusercontent.com/67091522/105494157-70789800-5ccb-11eb-93b4-ce18aab503fa.png)

#### Как повторить
Модифицировать Хэви Синдикат шлем под воксов.
#### Дополнительная информация:
...

**Comment by Kortez90** [comment]
Спрайта объекта нет.
![Безымянный](https://user-images.githubusercontent.com/36198983/105495837-b6366000-5ccd-11eb-9385-5aaecb33a6fe.png)
