### ISSUE TITLE
Скелеты не могут управлять своим телом.

### ISSUE THREAD

**Issue by Kortez90** [TauCetiStation/TauCetiClassic#6770]
#### Подробное описание проблемы
После воскрешения камнем некромантии поврежденный труп, возможно с переломом ноги, стал скелетом, но не смог двигаться, встать или вообще как-либо взаимодействовать с окружающим миром, кроме чата.
#### Как повторить
Сделать скелета с помощью камня.

**Comment by KIBORG04** [comment]
Не смог повторить даже на сервере

**Comment by Kortez90** [comment]
Очень просто. Делаешь человека, убиваешь. Камнем некромантии возвращаешь. Клиент должен быть внутри.

**Comment by KIBORG04** [comment]
Я так и делал

**Comment by Kortez90** [comment]
У нас с даркватером вышло не один раз. И на сервере тоже.
