### ISSUE TITLE
Сломаные action buttons

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#6773]
#### Подробное описание проблемы
Было замечено пропадание Action Buttons вверху экрана
#### Что должно было произойти
Кнопки вверху экрана есть
#### Что произошло на самом деле
Их нет!
#### Как повторить
Рандом при надевании РИГа, а также меха, возможно сломаны ВООБЩЕ ВСЕ action кнопки
#### Дополнительная информация:
https://github.com/TauCetiStation/TauCetiClassic/issues/6763

**Comment by T6751** [comment]
Связано с измением прока удаления на qdel
https://github.com/T6751/TildaStation/blob/cb24a0743ea276e58abbfa28a39b021c073e41a5/code/_onclick/hud/action.dm#L49
