### ISSUE TITLE
Пропал спрайт у джетпака нюки

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#678]
![7a6e06d82a27103f945fffc107cb9bd6](https://cloud.githubusercontent.com/assets/4064061/19492794/41fe97ee-9589-11e6-9cec-8cd59f5521fc.png)
Обнаружил Вальтер.

**Comment by Skippeer12** [comment]
Ещё там же и целеуказателя нет, всё у той же нюки.
