### ISSUE TITLE
Кнопка выключения света не на своем месте [MAP]

### ISSUE THREAD

**Issue by Rolt146** [TauCetiStation/TauCetiClassic#6780]
#### Подробное описание проблемы
Кнопка выключения света находится посередине экрана и выключает свет не только в отбытии поста медблока, а во всем отбытии
![Скриншот 23-01-2021 201743](https://user-images.githubusercontent.com/62613651/105632667-6e4a4100-5e65-11eb-8849-92e3d0c69db9.jpg)

#### Что должно было произойти
Кнопка на стене, свет отключается лишь в самой комнате
#### Что произошло на самом деле
кнопка на экране, свет выбубает во всем отбытии

**Comment by BesumniiChebureck** [comment]
Исправлено. Можете закрывать.

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/shattloresprajt/21625/209
