### ISSUE TITLE
Эми аннигилировало пда вместе с картой

### ISSUE THREAD

**Issue by Rolt146** [TauCetiStation/TauCetiClassic#6781]
#### Подробное описание проблемы
Я во время ожидания шаттла пробегал мимо мостика и попал под воздействие эми излучения. И в этот момент пропала карта и пда безвозратно. На мне был скафандр, так что выкрасть пда никто не мог. Возможно это был и сигнал с таторского катриджа, но карта хотябы должна была остаться (она остается даже если потрогать суперматерию)
#### Что должно было произойти
Эми пукнула, индивидуальные вещи остались
#### Что произошло на самом деле
Эми пукнула, пда с картой пропало в небытие
#### Как повторить
Попасть под эми (скорее всего несколько раз)
#### Дополнительная информации
Был раунд #38491, первый сервер, в 10 минутку до прибытия шаттла

**Comment by Pivo24** [comment]
ЭМИ может быть следствием от хака ПДА с детоматикса, не думаю что всё плохо.

**Comment by T6751** [comment]
>  но карта хотябы должна была остаться

В 10% случаях при разрушении ПДА ничего не должен оставлять, так что данный случай вероятно и попал в эти 10 процентов
![image](https://user-images.githubusercontent.com/66636084/105758610-7d61e980-5f60-11eb-8113-c9f33b0ae509.png)
Если нужно, чтобы ПДА всегда оставлял айди, то это уже нужно оформить новый пропосал. Данная же вещь не баг, а работает как задумано
