### ISSUE TITLE
Попытка сделать шахтерский автомат с наградами создает null machine

### ISSUE THREAD

**Issue by Rolt146** [TauCetiStation/TauCetiClassic#6785]
#### Подробное описание проблемы
Если сделать автомат для конверта очков в награды, то мы получим null machine
#### Что должно было произойти
Получился автомат шахтеров для получения наград за очки
#### Что произошло на самом деле
После закручивания винтиков машинерия стала невидимой и неосязаемой
#### Как повторить
сделать кустарно автомат шахтеров
#### Дополнительная информация:

**Comment by Kortez90** [comment]
А как вы смогли его сделать, если у него даже платы нет?

**Comment by Rolt146** [comment]
> А как вы смогли его сделать, если у него даже платы нет?

![Скриншот 25-01-2021 192308](https://user-images.githubusercontent.com/62613651/105733637-d28f0280-5f42-11eb-8ee2-fa7964e5e6f2.jpg)

**Comment by Kortez90** [comment]
Это плата какого-то мистического `equipment_vendor`, которого не существует. Автомат у шахтеров - `equipment_locker`.
