### ISSUE TITLE
Синди борги не говорят на сикоде

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#6793]
#### Подробное описание проблемы
Синди-борги не говорят ни на си-коде, ни на тернарном языке.

#### Что должно было произойти
Синди борги должны общаться на си-коде как минимум, а в идеале помимо этого и на тернарном

#### Что произошло на самом деле
Синди борг не понимает ни си-кода, ни тернарного

#### Как повторить
Засуммонить нюкерского борга и приказать ему что-то на си-коде или тернарном.

**Comment by Kortez90** [comment]
#6734.
