### ISSUE TITLE
Научный борг не способен с нуля собрать киборга.

### ISSUE THREAD

**Issue by Ro2tCrab** [TauCetiStation/TauCetiClassic#6800]
#### Подробное описание проблемы
Научный борг способен взять позитронку, мозг, MMI, части киборга, провода и вспышку, но не может засунуть последнее в голову киборга.
#### Что должно было произойти
Вспышка устанавливается в голову киборга
#### Что произошло на самом деле
Игра выдаёт сообщение : How do you propose to do that?
#### Как повторить
Попробовать собрать рабочую голову киборга.
#### Дополнительная информация:
-

**Comment by Kortez90** [comment]
В чем баг и почему вдруг они должны это делать?

**Comment by Ro2tCrab** [comment]
Дата мёрджа ПРа : декабрь 2020
Если не ошибаюсь, то в последний раз эту часть кода (Я не разбираюсь в коде)
`/obj/item/robot_parts/head/attackby(obj/item/I, mob/user, params)
	if(istype(I, /obj/item/device/flash))
		if(istype(user, /mob/living/silicon/robot))
			to_chat(user, "<span class='warning'>How do you propose to do that?</span>")
			return
		else if(flash1 && flash2)`

**НЕ** редактировали с августа 2020
А этот ПР должен был дать нам возможность собрать киборга : https://github.com/TauCetiStation/TauCetiClassic/pull/6481
И я УВЕРЕН в этом, ибо в commits можно найти эту строчку.
 **> Киборг может строить других киборгов, мехов и брать манки кубы**

Это только мои догадки.

**Comment by Zmey25** [comment]
Парень дело говорит. Баг.
