### ISSUE TITLE
Не фоловится лоок

### ISSUE THREAD

**Issue by Thirteenalex** [TauCetiStation/TauCetiClassic#6835]
#### Подробное описание проблемы
Не работает кнопка фолова за лооком
#### Что должно было произойти
админский гост должен был закрепится за фоловом лоока
#### Что произошло на самом деле
Этого не случилось
#### Как повторить
Администрировать игру, ждать пока напишут в лоок
#### Дополнительная информация:
Issue reported from  Round ID: 38714 (Tau Ceti Classic II (RU))
Testmerges: ```No test merges```
Reporting client version: 513.1536

**Comment by KIBORG04** [comment]
Билд не обновлён был просто
