### ISSUE TITLE
Жёлтые линии в отбытии

### ISSUE THREAD

**Issue by NeOchenLord** [TauCetiStation/TauCetiClassic#6842]
#### Подробное описание проблемы
Тётенька из динамиков говорит не заходить за жёлтые линии, которых нет в "новом" отбытии

#### Что должно было произойти
Тётенька из динамиков не говорит про жёлтые линии ИЛИ жёлтые линии есть в отбытии

#### Что произошло на самом деле
Тётенька из динамиков говорит про жёлтые линии, которых нет

#### Как повторить
Дождаться пристыковки шаттла к станции

**Comment by kiVts** [comment]
Ебать 'Разрешите приебатся'

**Comment by BesumniiChebureck** [comment]
![image](https://user-images.githubusercontent.com/67091522/107205794-4c2cf300-6a0f-11eb-8302-11b22df60f51.png)

**Comment by muWander** [comment]
Типа "не заходите внутрь заболтированного шлюза"? Автор прав, взгляни на старое отбытие

**Comment by Kortez90** [comment]
Полоски есть? Есть.
Предупреждение о том, что за них не надо заходить до прилета шаттла есть? Есть.
В чем проблема?

**Comment by NeOchenLord** [comment]
Куда туда дальше заходить за жёлтые полоски-то?
