### ISSUE TITLE
Разгрузка + Шкаф = Не зафиксированные предметы кражи для тритора

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#6850]
#### Подробное описание проблемы
Полез в вентиляцию на шаттле значит с телепортером в разгрузке, радуюсь жизни... Получил редтекст из-за неукраденного телепортера... Теперь меня в школе все дразнят ;(
#### Что должно было произойти
Гринтекст
#### Что произошло на самом деле
Меня дразнят в школе
#### Как повторить
Быть мной ИЛИ спрятать в разгрузку важную вещь и залезть в шкафчик.
#### Дополнительная информация:
Issue reported from  Round ID: 38796 (Tau Ceti Classic II (RU))
Testmerges: ```#6660 #6746 #6776 #6782 #6810 ```
Reporting client version: 513.1539

**Comment by AndroBetel** [comment]
lox
