### ISSUE TITLE
Незарегистрированные предметы тритора - Часть 2: Мяско корги

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#6865]
#### Подробное описание проблемы
Нашёл странное сходство - <a href="https://github.com/TauCetiStation/TauCetiClassic/issues/6850">на этом ишью</a> и на вот этом свеженьком - в обеих в качестве незарегистрированого предмета для кражи фигурирует мясо корги. В первом случае я украл его, сложил в разгрузку и сел в шкафчик, из-за чего подумал что это проблемы тут. В этом случае я улетел на шаттле с мясом корги (Яна) в РУКАХ. Его не засчитало, и подозреваю дело именно в мясе.
#### Что должно было произойти
Гринтекст поскольку ты молодец и убил весь экипаж ради собачьего мяса (тру стори)
#### Что произошло на самом деле
Меня продолжают дразнить в школе и называть фейлотой, а мама уже хочет отказываться от меня :(
#### Как повторить
Сп*здить мясо Яна, попробовать его спрятать как в разгрузке, так и пронести в руке.
#### Дополнительная информация:
Мясо получено путём дробления Яна в емагнутом pile ripper'е.

**Comment by NinjaPikachushka** [comment]
А ведь он реально убил весь экипаж и всё сб ради одного мясо... Еще и получил редтекст...

**Comment by Tiarv** [comment]
Вроде старая история, нужно мясо корги из карго, а мясо Яна не подходит.
