### ISSUE TITLE
[Admin] Бан панель - дроны

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#6866]
#### Подробное описание проблемы
В бан панели нет дронов.
#### Что должно было произойти
В бан панели есть дроны чтобы тиранить.
#### Что произошло на самом деле
В бан панели нет дронов чтобы тиранить.
#### Как повторить
Зайти и затиранить себе дрона.

**Comment by UsadoSmokk** [comment]
При бане каких-то синто, банится и дроны

**Comment by Shudyn** [comment]
Может лучше сразу кнопки для целых отделов добавить?

**Comment by Pirsnya** [comment]
> При бане каких-то синто, банятся и дроны

Ты уверен? Потому что в бане через ПП есть отдельно майтенс дроны, а через панель только их нет.
