### ISSUE TITLE
Blob & crew transfer

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6868]
#### Подробное описание проблемы
У нас значит есть рандомный ивент с блобом и отдельный режим блоб, беды конкретно в несостыковке этих двух событий
#### Что должно было произойти
Если на станции блоб (не важно ивентовый или нет) шаттл невозможно вызвать по причине "BIOHAZARD/QUARANTINE/ETC"
#### Что произошло на самом деле
Режимный блоб заставляет воевать иначе смерть, ивентовый блоб не мешает вызову шаттла
#### Как повторить
Вызвать шатол пока на станции тусуется ивентовый блоб

**Comment by Pirsnya** [comment]
Во первых не баг во вторых не баг а фича
