### ISSUE TITLE
Вырвиглазные термалы убивают игроков

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6878]
#### Подробное описание проблемы
Цветофильтр термалов настолько отвратительный, что за 15 минут беганья в них у меня болит голова и глаза
#### Что должно было произойти
Игроки не слепнут из-за сомнительных механик и не проклинают того, кто этот цветофильтр прилумао
#### Что произошло на самом деле
Я пью цитрамон и пишу дебильный ишью в час ночи, потому что мне плохо
#### Как повторить
Побегайте в термалах.

**Comment by kalazus** [comment]
Это специально сделано чтобы гсб не бегал с термалками 24 на 7.

**Comment by Motzord** [comment]
> Это специально сделано чтобы гсб не бегал с термалками 24 на 7.

А давайте закодим механику, ломающую игрокам пальцы, чтобы они специально не делали "действие_нейм"?

**Comment by KIBORG04** [comment]
С этим посложнее, потому что монитор не может ломать пальцы

**Comment by Motzord** [comment]
> С этим посложнее, потому что монитор не может ломать пальцы

Ну тогда пускай вбрасывает на пк юзера трояны и порнобаннеры с фурри.

**Comment by Loratron** [comment]
> и порнобаннеры с фурри.

Так надо наоборот наказывать игроков за использование термалов, а не стимулировать к этому

**Comment by Zickusable** [comment]
Термалки не защищают от флеша и не дают худ, так зачем носить их на постоянке? Возможно и вовсе дать ГСБ миксхуды с переключением режима на термалки или все одновременно.

**Comment by FBitSafe** [comment]
Просто сделать как в Деус Сексе, чтобы термалы задвигались тебе в лицо.

**Comment by Haggerd** [comment]
> Просто сделать как в Деус Сексе, чтобы термалы задвигались тебе в лицо. А фильтр оставить.

Сделай, если просто

**Comment by Chip11-n** [comment]
Фильтры меняли
