### ISSUE TITLE
Пии глухой пока в руках у человека

### ISSUE THREAD

**Issue by Thirteenalex** [TauCetiStation/TauCetiClassic#6881]
#### Подробное описание проблемы
Зашел за пии человек взял в руки, перестал слышать людей
#### Что должно было произойти
Он должен слышать в руках у куклы
#### Что произошло на самом деле
Он оглох в руках у куклы
#### Как повторить
зайти за пии и попасть в руки куклы
#### Дополнительная информация:
Issue reported from  Round ID: 38997 (Tau Ceti Classic II (RU))
Testmerges: ```#6776 #6782 #6789 #6814 #6837 ```
Reporting client version: 513.1536

**Comment by Thirteenalex** [comment]
Так пии вообще ничего не слышит в руках у куклы

**Comment by KIBORG04** [comment]
Дубликат #6000
