### ISSUE TITLE
Беды с Remote View

### ISSUE THREAD

**Issue by NeOchenLord** [TauCetiStation/TauCetiClassic#6882]
#### Подробное описание проблемы
Мутация Remote View не работает

#### Что должно было произойти
Нажимая на кнопку во вкладке Superpowers, вылезает окно и далее ген работает

#### Что произошло на самом деле
Кнопка есть, но нажимая на неё ничего не происходит

#### Как повторить
Получить ген Remote View и попробовать его использовать

**Comment by KIBORG04** [comment]
Не работает из-за такого рантайма
![image](https://user-images.githubusercontent.com/26389417/108633699-9e95f700-7486-11eb-9fa3-9daa152378aa.png)
