### ISSUE TITLE
"Секретная" информация о Дельте доступна всем.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6883]
#### Подробное описание проблемы
В книжней полке в лобби брига лежит книга с СПД, в которой напрямую говорится о существовании коде дельта. Почитать об этом может любой клоун.
#### Что должно было произойти
Персонал не может игровыми путями кроме болтливых глав знать о процедуре самоуничтожения станции, порядке ее инициализации и порядке действий
#### Что произошло на самом деле
Vasya Pupkin says: [145.9] А ВЫ ЗНАЛИ ШО ЕСТЬ ТАКОЙ КОД ДЕЛЬТА?!??!
#### Как повторить
взять книжку СПД в лобби брига
#### Дополнительная информация:
Это ломает весь тру рп ролеплей RP экспириенс

**Comment by FelixRuin** [comment]
так... вопрос, а почему не должны знать? В плане для всех будет секретом, что есть процедура самоликвидации станции при ситуации - лучше так, чем никак?

**Comment by KIBORG04** [comment]
А еще каждый по камерам может ядерную бомбу найти

**Comment by Motzord** [comment]
> так... вопрос, а почему не должны знать? В плане для всех будет секретом, что есть процедура самоликвидации станции при ситуации - лучше так, чем распространить хтонический пиздец дальше

![image](https://user-images.githubusercontent.com/45365635/108637781-30106380-749d-11eb-909a-9cdd245777de.png)

**Comment by kiVts** [comment]
ПО секрету всему свету, потому что нанотрейзен. только так и не иначе!!!!!!

**Comment by Motzord** [comment]
Как я помню, книжку сопа выпилили из  книжной полочки брига.
