### ISSUE TITLE
[Proposal] Красивые баночки красивому Химику

### ISSUE THREAD

**Issue by notkripton** [TauCetiStation/TauCetiClassic#6885]
#### Подробное описание проблемы
-
#### Что должно было произойти
Мой неутолимый врачебный фетиш и голод по всякого рода фармацевтике просто не даёт мне покоя, и я думаю что я такой не один, но бы спросите почему? Так потому что таблетками никто не пользуется, нет, серьезно, когда в последний раз вы видели химика, который вместо склянок пихает в холодильник хорошо отсортированные разноцветные баночки с таблетками внутри которых пилюли с точной дозировкой лекарств. Причем таблетки намного круче обычного шприца и баночек вот почему:
1. В одну баночку может поместиться до десятка таблеток, каждая из которых почти как две жидких банки с лекарствами.
2. Таблетки намного быстрее скармливаются пациенту чем если вкалывать шприцом.
3. Точная дощировка
4. О боже эти прекрасные спрайты таблеток и баночек не дают мне покоя...
#### Что произошло на самом деле
-
#### Как повторить
Моих предложений 2, и звучат оно так: 
1. Почему бы не поменять кнопку multiple pills в хим сортировщике на кнопку, которая бы выдавала банку, в которой были бы таблетки с таблетками такой дозировки, которой указали до этого. Чисто как по мне намного приятнее будет не по 8 склянок с жидкостями перетаскиватьч а одну-две баночки с таблетками, которые так же бы легко делались. Да и если подумать, то пластиковая банка намного дешевле в стоимости производства, нежели стекло.
2. Убрать возможность класть стеклянные банки и пробирки в холодильник химика. Звучит как что-то тупое, но на самом деле нету в игре такого препарата, который бы нельзя было использовать никак, кроме как шприцом. Да и по сути сами склянки - для опытов и хим. реакций, а таблетки как раз для врачебного применения, к тому же надо отучивать людей от старой глупой привычки.
#### Дополнительная информация:
Нагрузки на врачей и интернов это не понесет, а даже наоборот, у химиков разнообразится геймплей, а в кодинге думаю вообще не возникнет проблем, все в плюсе!

**Comment by Motzord** [comment]
Ты че дурак?

**Comment by KIBORG04** [comment]
Неправильное оформление..

**Comment by notkripton** [comment]
Простите я дурак, думал откроется редактор xD
