### ISSUE TITLE
[Proposal] Таблеточная реформа для меда.

### ISSUE THREAD

**Issue by notkripton** [TauCetiStation/TauCetiClassic#6886]
#### Подробное описание проблемы
Мой неутолимый врачебный фетиш и голод по всякого рода фармацевтике просто не даёт мне покоя, и я думаю что я такой не один, но сейчас избавиться от этой жажды просто невозможно, и вы спросите почему? Так потому что таблетками никто не пользуется, нет, серьезно, когда в последний раз вы видели химика, который вместо склянок пихает в холодильник хорошо отсортированные разноцветные баночки с таблетками внутри которых пилюли с точной дозировкой лекарств. Причем таблетки намного круче обычного шприца и баночек с жидкими лекарствами вот почему:

1. В одну баночку может поместиться до десятка таблеток, каждая из которых почти как две жидких банки с лекарствами.
2. Таблетки намного быстрее скармливаются пациенту чем если вкалывать шприцом.
3. Точная дозировка.
4. О боже эти прекрасные спрайты таблеток и баночек не дают мне покоя...
#### Что должно было произойти
-
#### Что произошло на самом деле
-
#### Как повторить
Моих предложений 2, и звучат они так:

1. Почему бы не поменять кнопку multiple pills в хим сортировщике на кнопку, которая бы выдавала банку, в которой были бы таблетки с таблетками такой дозировки, которой указали до этого (т.е. эта кнопка бы не просто выдавала n таблеток по отдельности, а сразу бы давала их в банке, у которой было бы такое же название, как у самих таблеток). Чисто как по мне намного приятнее будет не по 8 склянок с жидкостями перетаскиватьч а одну-две баночки с таблетками, которые так же бы легко делались. Да и если подумать, то пластиковая банка намного дешевле в стоимости производства, нежели стекло.
2. Убрать возможность класть стеклянные банки и пробирки в холодильник химика. На самом деле нету в игре такого препарата, который бы нельзя было использовать никак, кроме как шприцом. Да и по сути сами склянки - для опытов и хим. реакций, а таблетки как раз для врачебного применения, к тому же надо отучивать людей от старой глупой привычки.
#### Дополнительная информация:
Нагрузки на врачей и интернов это не понесет, а даже наоборот, у химиков разнообразится геймплей, а в кодинге думаю вообще не возникнет проблем ===> ULTRA PROFIT.

**Comment by notkripton** [comment]
Также как вариант можно сделать так, чтобы при клике таблеткой по пробирке та превращалась обратно в жидкость, если вдруг нужна другая дозировка.

**Comment by 4310V343k** [comment]
> Убрать возможность класть стеклянные банки и пробирки в холодильник химика. 

:joypain:
Мы либо уравниваем значение таблеток и банок, либо приходим к той же проблеме, что и была ранее, но наоборот.

К тому же всё и сейчас нормально. 
Базовые лекарства которые нужны каждую минуту, вроде бика, дермы и дплюса хранятся в баночках на поясе, что бы можно было и тремя кликами ввести HESOYAM пациенту, и, при желании, ввести по отдельности, в разных комбинациях и разных дозировках
Не такие востребованные, вроде алкизина или имидазолина - вообще без разницы. И в том, и в другом случае они просто будут пылиться где-нибудь у крио
А редко используемые вроде УПАСИ БОЖЕ декстрометорфана и так находятся в таблетках по два юнита, для экономии

> Также как вариант можно сделать так, чтобы при клике таблеткой по пробирке та превращалась обратно в жидкость, если вдруг нужна другая дозировка.

Они уже

**Comment by Motzord** [comment]
>Также как вариант можно сделать так, чтобы при клике таблеткой по пробирке та превращалась обратно в жидкость, если вдруг нужна другая дозировка.

уже вкодено, в пробирке должна быть жидкость, чтобы ты растворил в ней пилюлю

> Почему бы не поменять кнопку multiple pills в хим сортировщике на кнопку, которая бы выдавала банку, в которой были бы таблетки с таблетками такой дозировки, которой указали до этого 

Просто скажи, что ты не знал, о фиче с фастсобиранием таблеток кликом банкой под пилюли по тайлу с ними

>Таблетки намного быстрее скармливаются пациенту чем если вкалывать шприцом.

А еще медленнее усваиваются, шприц же заставляет лекарства хилить космонавтика как только лекарства были введены

>На самом деле нету в игре такого препарата, который бы нельзя было использовать никак, кроме как шприцом.

Дексалин-гиперзин. Де юре можно конечно, де факто применяются они либо когда космонавтик в разгерме и глотать таблетки в скафандре неудобно, либо когда космонавтик хочет быстро бегать в риге

> Убрать возможность класть стеклянные банки и пробирки в холодильник химика.
Предлагаю убрать возможность писать дебильные пропосалы

> Убрать возможность класть стеклянные банки и пробирки в холодильник химика.
Почему ты не предложил замедлить скармливание таблеток/уменьшить кд на вкалывание, если тебе так приницпиальна эта фича?
