### ISSUE TITLE
Тазеры которые удалили, перерождаются в новом исекайном мире...

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#6890]
#### Подробное описание проблемы
При создании ЕД 209 используют тазеры РНД, при уничтожении ЕД 209 из них выпадают удаленные тазеры СБ
#### Что должно было произойти
Используем тазеры РНД, выпадают тазеры РНД
#### Что произошло на самом деле
Используем тазеры РНД, выпадают  удаленные тазеры СБ
#### Как повторить
Собрать ЕД 209 и уничтожить

**Comment by kiVts** [comment]
ННЕЕЕТТТ!!!!!
