### ISSUE TITLE
Гранаты вода-калий (и возможно лимитки) не бахают на тайле пола в космосе

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6892]
#### Подробное описание проблемы
Взрывы в космосе работают плохо, это мы знаем, но взрывы на тайле пола должны работать, следовательно, если я делаю тайл пола, и бахаю на нем гранату, взрыв должен быть нормальным и каким я ожидаю
#### Что должно было произойти
Поставил тайл пола, кинул гранату вода-калий 150/150 и доволен
#### Что произошло на самом деле
Поставил тайл пола, кинул гранату, обосрался
#### Как повторить
Поставьте тайл пола в космосе, взорвите на нем гранату

**Comment by volas** [comment]
От того, что ты поставишь плитку пола, кислород в космосе не появится.

**Comment by Motzord** [comment]
> От того, что ты поставишь плитку пола, кислород в космосе не появится.

Почему тогда лимитки спокойно бахают в вакууме?

**Comment by FelixRuin** [comment]
> > От того, что ты поставишь плитку пола, кислород в космосе не появится.
> 
> Почему тогда лимитки спокойно бахают в вакууме? (учоные же зашвыривают их на открытый в шпессе полигон)

ты... прикалываешься? Смесь форона с КИСЛОРОДОМ врядли нуждается в дополнительном КИСЛОРОДЕ

**Comment by Motzord** [comment]
> ты... прикалываешься? Смесь форона с КИСЛОРОДОМ врядли нуждается в дополнительном КИСЛОРОДЕ

Так в космосе взрыв плохо распространяется потому что там вакуум,а не потому что там нет кислорода, бака.
