### ISSUE TITLE
Синаптизин не спасает от стана станамулета

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6899]
#### Подробное описание проблемы
написано в шапке
#### Что должно было произойти
Кукла не падает, потому что под синаптизином
#### Что произошло на самом деле
Кукла падает, что портит возможность противодействовать закликиванию бумажками
#### Как повторить
Повоюйте с культом под синаптизином, лягте отдыхать из-за бамажки

**Comment by kalazus** [comment]
Синаптизин адреналин, а не наркотик защищающий от всех чувств. От него ты быстрее оклемаешся (вроде в 2 раза), а не будешь неуязвим к эффектам.

**Comment by KIBORG04** [comment]
Как сказал человек выше, синаптизин и не должен контрить станы ДО их наложения на куклу.

**Comment by kiVts** [comment]
Синаптизин адреналин? не смешите меня, ни в жизни адреналин не принесет токсины 
тут адреналин в игре это что-то между гипирцином и инаправалином
а синамптизин это наркотик - вернее блокер - который не дает чуствовать боль например он 'целится' в Ноцицептивные рецепторы - блокировать их - альтернативный способ полностью(нет) убирать боль

**Comment by Pivo24** [comment]
> Синаптизин адреналин? не смешите меня, ни в жизни адреналин не принесет токсины
> тут адреналин в игре это что-то между гипирцином и инаправалином
> а синамптизин это наркотик - вернее блокер - который не дает чуствовать боль например он 'целится' в Ноцицептивные рецепторы - блокировать их - альтернативный способ полностью(нет) убирать боль

why

**Comment by kiVts** [comment]
ДЕлать мне  просто нечего помогите
