### ISSUE TITLE
[Proposal] Задача триторам передать чемоданчик другому

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#6905]
#### Подробное описание проблемы
Почему бы не добавить еще одну задачу для трейторов?

Я придумал обжект, в котором тебе раундстартом даётся закрытый дипломат, с которым должен улететь другой определённый тритор. Смысл задачи в том, что тебе изначально даётся очень мало входных данных о определении нужного тритора, а этот татор даже и не знает об этом дипломате. 

Это, можно сказать, ещё одна мирная цель, при которой тебе придётся защищать коллегу

Могу и я когда-то потом закодить

> ты придумал чемоданчик, а тг реализовали документы
там оба тритора знают у кого какие документы, у одного синие, у другого красные
и рандомные задачи, например у одного может выпасть что он должен забрать оба документа

**Comment by notkripton** [comment]
Также как идея добавить в аплинк опцию (или предмет), которая/ый возвращал бы дипломат обратно. 
Примерно за 5-7 телекристалов.

**Comment by Pivo24** [comment]
Надо условный чемоданчик чем-то заменить наверное, а то представляю как инженеры раундстартом спавнятся и у одного из них чемоданчик - метагеи ~~и я в том числе~~ сразу смекнут что к чему и будет то что будет.

**Comment by raduser** [comment]
На тг есть подрежим двойные агенты, который в определенный момент, если память не изменяет, пришёл в своём развитии к тому, что каждому двойному агенту, помимо стандартных задач, надо было достать документы определённого цвета, которые были у одного из других двойных агентов.

**Comment by kiVts** [comment]
Предлагаю так - татор не знает кто дипломат, ему дается два кодовых слова - одно  которое нужно сказать и другое слово на ответ - дипломату(он тоже татор)  
Будет как то так
Татор говорит рамашка, димпломат слышит
И говорит какашка все молодец на тебе гринтекст и тд и тп

И наоборот если дипломат будет заниматся самодейтельностью

Моя идея что это совсем не обязательно вгонять этот ваш "Чемоданчик" в рамки раунда - они могут обменятся на марсе, могут на цк а в раунде происходит "Идентификация"

**Comment by Motzord** [comment]
Можно было бы сделать еще круче. Сами "документы" зашифрованы и у глав есть приколюха для дешифрации. Собственно если документы расшифрованы, то кекипаж молодец, синдикат сосет. Документы расшифровываются какое-то время 5-10 минут, и всем таторам в обжективы добавляется пункт "предотвратить дешифрацию"
