### ISSUE TITLE
В TGUI появляется карта.

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#6925]
#### Подробное описание проблемы
В некоторых машинах на Fancy TGUI (ПДА, атмосферные насосы, некоторые мониторы) появляется карта и сбитый интерфейс. Скрин ниже:
#### Что должно было произойти
Обычное меню
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/42682553/110251163-53a0d700-7f90-11eb-919a-ccecea4b6edc.png)

#### Как повторить
Хз?
#### Дополнительная информация:
Не знаю, не имею ни малейшего понятия что из моих системных или других приколов может на это влиять.

**Comment by volas** [comment]
Ты один с подобной проблемой? Попробуй почистить кэш бьенда и IE.

**Comment by Pivo24** [comment]
Попробую
