### ISSUE TITLE
Предмет, который засунули в еду, виден, если кликнуть по еде ПКМ

### ISSUE THREAD

**Issue by Tiarv** [TauCetiStation/TauCetiClassic#6938]
#### Подробное описание проблемы
Если засунуть предмет в хлеб, то он виден в контекстном меню, если кникнуть по еде ПКМ

#### Что должно было произойти
Предмет, который засунули в еду, не должен быть виден в контекстном меню по нажатию ПКМ на еде. Должна быть видна только еда.

#### Что произошло на самом деле
Предмет, который засунули в еду, не виден в контекстном меню по нажатию ПКМ на еде

#### Как повторить
Засунуть предмет в еду. Кликнуть по еде ПКМ.

#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/41039312/111060489-46af4680-84ae-11eb-912e-b30f5e62c50a.png)

**Comment by FBitSafe** [comment]
У меня иногда на ПКМ спрайты предметов путаются, у пшеницы спрайт ведра или у камня спрайт кирки

**Comment by Tiarv** [comment]
Видимо, это и правда просто текстурки, а не предмет внутри. Упс.
