### ISSUE TITLE
Божок из палки не может использовать Благославение на предметах.

### ISSUE THREAD

**Issue by Ro2tCrab** [TauCetiStation/TauCetiClassic#6941]
#### Подробное описание проблемы
При использовании заклинания звуки есть, но ничего сделать нельзя.
#### Что должно было произойти
+5 к урону оружия и утрата 300 маны.
#### Что произошло на самом деле
Ничего.
#### Как повторить
Получить аспекты для Благославения божка и использовать заклинание
#### Дополнительная информация:
Issue reported from  Round ID: 39485 (Tau Ceti Classic (RU))
Testmerges: ```#6843 #6923 ```
Reporting client version: 513.1542

**Comment by KIBORG04** [comment]
Пофиксил в одном из последних коммитов
