### ISSUE TITLE
Одиссею пофиг на культостены

### ISSUE THREAD

**Issue by Rolt146** [TauCetiStation/TauCetiClassic#6943]
#### Подробное описание проблемы
Будучи не культистом, можно открывать культодвери, будучи в мехе
#### Что должно было произойти
Культодвери не работают с теми, кто не культяпка
#### Что произошло на самом деле
Культодвери может открыть непосвященый в тайные знания, имеющий всего лишь мех
#### Как повторить
Залесть в мех, будучу не ролью. Открыть культодверь
#### Дополнительная информация:
Issue reported from  Round ID: 39500 (Tau Ceti Classic (RU))
Testmerges: ```#6843 #6923 ```
Reporting client version: 513.1528
"

**Comment by KIBORG04** [comment]
Пофиксил в одном из последних коммитов
