### ISSUE TITLE
Сервер можно уронить при помощи добровольца, трех тайлов пола и смазки

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#6948]
#### Подробное описание проблемы
Кукла разгоняется до около световой скорости, скользит без смазки на миллионы тыщ тайлов, проскальзывает сквозь стены и не желает останавливается, роняя сервер
#### Что должно было произойти
Такого быть не должно
#### Что произошло на самом деле
Я уронил сервер. Дважды
#### Как повторить
Подробнейшая инструкция в реплее раунда #39536

Повторный опыт в раунде #39537

**Comment by Motzord** [comment]
Кому интересно че там по дамагу:
![image](https://user-images.githubusercontent.com/45365635/111384556-b6921c80-86ba-11eb-9b28-d59f3ef81e7b.png)
Кукла без брони в полете 10 минут

**Comment by Motzord** [comment]
> а че по научным очкам

Тут же спросите вы, предвкушая дохуиллион очков и все исследования почти раундстартом
![image](https://user-images.githubusercontent.com/45365635/111385356-bba39b80-86bb-11eb-8c19-4d20c11a7d4d.png)


Почему-то пиздюли куклы от смазки, логироваться не захотели

**Comment by Motzord** [comment]
![image](https://user-images.githubusercontent.com/45365635/111385592-19d07e80-86bc-11eb-9391-33aa97c81d7c.png)

Вот здесь, примерно на 3:50 - 4:20 минуте раунда самая подробная инструкция, с веселыми багами в виде летающей каталки на смазке и прочими прелестями упавшего контроллера

**Comment by Motzord** [comment]
https://media.discordapp.net/attachments/443547609777569813/821505567012552714/12412.gif?width=681&height=468

Сам прикол

**Comment by Motzord** [comment]
![12412](https://user-images.githubusercontent.com/45365635/111386835-e1ca3b00-86bd-11eb-8e17-b786b7ca32c8.gif)
![2141](https://user-images.githubusercontent.com/45365635/111386849-e68eef00-86bd-11eb-808c-70c350cb3037.gif)

**Comment by FBitSafe** [comment]
Тело пролетает всю карту и даже другие слои?

**Comment by Motzord** [comment]
> Тело пролетает всю карту и даже другие слои?

Теоретически это можно устроить, если умудрится выпулить тело в космос. (По крайней мере на одном из тестов удалось заставлять ассистуху проскальзывать сквозь укрепки)
