### ISSUE TITLE
Талисманы ничего не делают!

### ISSUE THREAD

**Issue by Ro2tCrab** [TauCetiStation/TauCetiClassic#6955]
#### Подробное описание проблемы
Талисман успешно потратил ману на создание и поглощение силы ритуала, но попытки использовать его не увенчались успехом.
#### Что должно было произойти
Вжух! Магия!
#### Что произошло на самом деле
Ничего. Пустая трата маны.
#### Как повторить
-
#### Дополнительная информация:
Issue reported from  Round ID: 39607 (Tau Ceti Classic (RU))
Testmerges: ```#6843 #6915 #6949 ```
Reporting client version: 513.1542

**Comment by KIBORG04** [comment]
делают

Нужно больше информации

**Comment by Ro2tCrab** [comment]
Не делают! Я тыкал их на себя, в руке, нуллродом, книгой, на руну и на алтарь.

**Comment by Ro2tCrab** [comment]
> 
> 
> делают
> 
> Нужно больше информации
Какого рода информация тебе нужна?

**Comment by KIBORG04** [comment]
Ритуал и куда жал

**Comment by Ro2tCrab** [comment]
> 
> 
> Ритуал и куда жал

Что я делал.
1. Призвал талисман
1.1 Получил талисман. (Бумага с жёлтым символом)
2. Нажал бумагой на алтарь (Использованные ритуалы : Испуг, общение, призыв талисмана) 
2.1 Получил три разных талисмана.
3. Пытался использовать талисман.
3.1 Использовал в руке.
3.2 Бил им по людям
3.3 Тыкал им по руне
3.4 Тыкал на талисман книгой
3.5 Тыкал на талисман жезлом.
3.6 Попробовал 3.4 и 3.5 в обратном порядке.
3.7 Тыкал на алтарь (Ответ : Талисман уже зачарован)
3.8 Cжёг с помощью зажигалки.
