### ISSUE TITLE
Неправильные спрайты магазина 45 калибра. 

### ISSUE THREAD

**Issue by DedYarick** [TauCetiStation/TauCetiClassic#6961]
#### Подробное описание проблемы
В автолате вместо спрайтов магазина 45 калибра (и резины, и летала) спрайт гранаты гранатомёта, вне автолата спрайты правильные. 
![image](https://user-images.githubusercontent.com/63983146/111911332-f2e0c680-8a86-11eb-8b21-ab4f34f931e8.png)
![image](https://user-images.githubusercontent.com/63983146/111911337-fa07d480-8a86-11eb-9fd5-658f8ad8b5cc.png)

#### Что должно было произойти
Магазины 45 калибра имеют спрайты магазинов 45 калибра
#### Что произошло на самом деле
Магазины 45 калибра имеют спрайты гранаты гранатомёта. 
#### Как повторить
Посмотреть в автолат. 
#### Дополнительная информация
-

**Comment by KIBORG04** [comment]
Возможно, связано с https://github.com/TauCetiStation/TauCetiClassic/pull/6903

**Comment by Ahion** [comment]
Я недавно делал ПР по автолату, такого бага не было. Возможно были ПРэ, которые меняли спрайты в этом файле?
