### ISSUE TITLE
Невозможно выбраться из построенного цельного окна

### ISSUE THREAD

**Issue by Raschert0** [TauCetiStation/TauCetiClassic#697]
#### Подробное описание проблемы
Из полнотайлового окна после постройки нельзя выбраться
#### Что должно было произойти
Из него можно было бы выбраться
#### Что произошло на самом деле
Тот, кто создал окно, застрял в нём
#### Как повторить
1. Взять стекло
2. Построить полнотайловое окно
3. Ощущать безысходность

#### Дополнительная информация:
@SpaiR ставлю ничего, что это последствия твоего фикса #635

**Comment by SpaiR** [comment]
@Raschert0 Проиграл. Подобный нюанс был до этого. Выбраться можно. Начинаешь пулить окно и кликаешь на соседний тайл.

**Comment by Raschert0** [comment]
@SpaiR но если ты строишь окно в космос и под ним должна быть решётка, то я плохо представляю как это сделать (а в остальных случаях пулл, конечно, помогает)

**Comment by SpaiR** [comment]
В таком случае о чём баг?

**Comment by Raschert0** [comment]
Но я же говорю, окно в космос. Если нужно чтобы оно было на решётке, то ты его не построишь, так как на решётку запуллить окно нелзья. А, ну ещё у нас, емнип, дроны и борги не могут пуллить по клику мышки.

**Comment by SpaiR** [comment]
Тогда нужно менять механ, чтобы окно появлялось перед человеком, а не под ним.

**Comment by Raschert0** [comment]
Эй!
А что делать синтетам? Для них это как раз баг

**Comment by SpaiR** [comment]
Тоже самое, нужно чтобы окно спавнилось перед ними.
Недочёт механики != баг.

**Comment by igigin** [comment]
> А что делать синтетам?

Не строить цельные стекла, очевидно.
