### ISSUE TITLE
РИГ не мешает снятию/одеванию предметов.

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#70]
Originally reported by: **Anonymous**

---

Это относится и к раздевнию другим персонажем (карта, ПДА, тулбелт). Также можно снимать /одевать маску через шлем. На тестовом проблемы нет(беевский билд)

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/70

**Comment by Leshiy-ART** [comment]
Кажется этот ишь уже не актуален.
