### ISSUE TITLE
Лицехваты разбиваются об маски/шлема космонавтиков

### ISSUE THREAD

**Issue by ChewedGum** [TauCetiStation/TauCetiClassic#7007]
#### Подробное описание проблемы
Лицехват мгновенно умирает если прыгает на лицо космонавтика у которого экипирован какой-нибудь gas mask/шлем от ервоса.

#### Что должно было произойти
https://www.youtube.com/watch?v=Uf1NX7e8Gao

#### Что произошло на самом деле
https://www.youtube.com/watch?v=-ZGlaAxB7nI

#### Как повторить
1. Заспавнить куклу
2. Надеть на неё шлем/маску закрывающее лицо/голову.
3. Заспавнить лицехвата.
4. Вселиться в лицехвата.
5. Прыгнуть на лицо кукле созданной в шагах 1-2.

#### Дополнительная информация:
https://www.youtube.com/watch?v=KxZmiVUQksA

**Comment by kalazus** [comment]
Не баг, он плавит шлем/маску с, вроде, 50% шансом (т.е. в шлеме с маской 25% напрыгнуть). Если ахио не поломал эту механику...

**Comment by ChewedGum** [comment]
Ну и зачем? Какая вообще логика стоит за всем этим? В кино они шлем из, вероятно, укрепленного стекла плавили, тут они умирают от соприкосновения с дешевым пластиком. Для чего, в чем смысл? Фейсхаггерам и так жутко тяжело живется уже в середине раунда из-за гражданских палящих с летала с двух рук, а тут ещё и серьезный шанс мгновенной смерти при успешном прыжке (который тоже не так то просто выполнить) необоснованный вообще ничем.

**Comment by Ahion** [comment]
Как по твоему тогда, экипажу контрить лицехватов?

**Comment by ChewedGum** [comment]
Помимо того что любой ассистуха с ломом может забить лицехвата или отбежать от них на 2-3 (по ощущениям) тайла прервав возможность на прыжок? 
Никак. Ты кино вообще смотрел?

**Comment by Ahion** [comment]
Что ты в меня кином своим тыкаешь? У нас тут не кино, а онлайн игра в которую люди играют по ту и другую сторону. И у экипажа должна быть возможность предпринять какие-либо действия чтобы предотвратить или уменьшить шанс откинуться от лицехвата. Я уже молчу о том, что напрыгнуть на лицо за лицехвата проще простого, у него большая скорость и есть возможность заходить на тот же таил, на котором находится жертва и _"любой ассистуха с ломом"_ скорее разобьет череп себе и окружающим, чем попадет этим ломом по лицехвату.

Короче, с такими бредовыми предложениями надо на форум во флудилку. Иссуй можно закрывать.

**Comment by ChewedGum** [comment]
Ладно, хер с ним, допустим маски и дальше защищают с той вероятностью 25-50%. 
Вот только почему хаггер при этом мгновенно умирает? Было бы более разумно если он прыгал в сторону куклы на которую пытался залезть, (возможно) станился на секунду и в чат выдавало что-то вроде "неудачный прыжок, маска помешала зацепиться." 
Как оно есть сейчас это абсолютно бессмысленно и ничем не обусловлено.

**Comment by GermanSUS** [comment]
Тогда может сделать так что неудачный прыжек убивает лице хвата но дамажит шлем? Условно это заставит играть хайву ещё сообщней даже на уровне лмцехватов, один плавит шлем, другой заражает. Тим плей!

**Comment by Motzord** [comment]
не баг, а ишью не закрыли
