### ISSUE TITLE
Неправильный input в СМЕСах.

### ISSUE THREAD

**Issue by notkripton** [TauCetiStation/TauCetiClassic#7009]
#### Подробное описание проблемы
Инпут на СМЕСах нереалистичен и крайне неудобен, из-за него может теряться колоссальное кол-во вырабатываемой энергии.
#### Что должно было произойти
Если в СМЕСе стоит 70к энергии, то он должен принимать и 70к и больше.
#### Что произошло на самом деле
Инпут на СМЕСах работает как ограничитель в обе стороны. Тоесть если вы поставите в нем значение в 70000, а в сети будет 50000, то ничего поступать не будет. Но если в сети 90000, то принимать СМЕС будет только поставленные вами 70000, так что решить путем установки минимального значения на инпуте не получится. Как пример будут соляры, ведь значение энергии в них разное: ~3 минуты выработки 90к энергии и ~8 минут они вырабатывают значение от 20 до 60к энергии. Какой инпут ты бы не поставил около 50% энергии будет уходить впустую.
#### Как повторить
Запустить соляры, ставить разные значения в инпуте и смотреть в VV сколько смес получает энергии.
#### Дополнительная информация:
.

**Comment by TechCatOther** [comment]
Это всегда была фича для инженеров, что бы решить головоломку как подавать питание ранее

**Comment by notkripton** [comment]
> Это всегда была фича для инженеров, что бы решить головоломку как подавать питание верно

Причем здесь подача энергии если проблема в ее приеме. Я что-то пропустил или инженерам теперь настолько хватает энергии, что они ищут фичи куда бы ее девать?

**Comment by TechCatOther** [comment]
Вообще после запуска двигателя сейчас действительно очень высокая выработка. Причем настолько, что они поголовно идут пить чай. Тут никак, кроме как зависимость удара током от энергии в сети не сделана причины почему ты не можешь принимать 100500 тысяч по одному кабелю. 

Ну, если инженерам и правда мешает данная ситуация можно убрать ее. Только вот это ничего не принесет как мне кажется в геймплей, а наоборот уберет историю с настройкой смесов у солнечных панелей. Все просто будут ставить максимально и все.

**Comment by notkripton** [comment]
Так потому что смес такой урезанный соляры и запускают так редко. Везде и даже на вики люди кричат про 300к энергии от соляр, но в лучше случае они даже 120к не смогут вырабатывать, да и есть ещё периоды вращения когда они вообще не будут вырабатывать ничего, а все потому что на смесе нельзя, условно, нажать такую кнопку чтобы он принимал ЛЮБУЮ энергию, которая в него входит.

**Comment by notkripton** [comment]
>Все просто будут ставить максимально и все.

Они и сейчас просто ставят max в СМЕСах да уходят в крио.

**Comment by TechCatOther** [comment]
На моем опыте соляры дольше гораздо включать. Но это ладно, можно сделать как ты описываешь, тогда сразу на всех ставить максимум приема при создании. Учитывая как часто ставят соляры это на механику не повлияют.
Думаю как пропозал нужно ставить, либо точно не баг. Такое поведение ожидаемое. Это игра и тут другие правила.

> Они и сейчас просто ставят max в СМЕСах да уходят в крио.

А потом и на солярах не будет настройки.

**Comment by notkripton** [comment]
Энергии панелей не хватает чтобы в соло записать станцию. Двигатели вырабатывают больше чем станция требует, так что включать соляры вместе с двигателем бессмысленно. Замкнутый круг дисбаланса панелей.

**Comment by Tiarv** [comment]
Так подруби соляры мимо смеса, какие проблемы. А смес будет просто сглаживать пики, чтобы у тебя разом все лампочки не выбило по всей станции.

**Comment by notkripton** [comment]
> Так подруби соляры мимо смеса, какие проблемы. А смес будет просто сглаживать пики, чтобы у тебя разом все лампочки не выбило по всей станции.

Так ручки же жечь будет проводами, не?

**Comment by Tiarv** [comment]
Так я тебе не сингулярность предлагаю в общую сеть отдать, а соляры, один предустановленный сет которых на коробке дает всего лишь 90к, и то непостоянно. А единовременно солнышко греет не больше двух сетов, т.е. больше 180 там не будет никогда - если мы рассматриваем только соляры. Но если осторожничаешь - пики можешь съедать смесом, подключив его в сеть сбоку и выставив на нем инпут, скажем, 150к (или сколько ты там хочешь срезать).

**Comment by Akellazp** [comment]
Урон от тока всегда один и тот же вне зависимости от напряжения в сети

**Comment by notkripton** [comment]
> Так я тебе не сингулярность предлагаю в общую сеть отдать, а соляры, один предустановленный сет которых на коробке дает всего лишь 90к, и то непостоянно. А единовременно солнышко греет не больше двух сетов, т.е. больше 180 там не будет никогда - если мы рассматриваем только соляры. Но если осторожничаешь - пики можешь съедать смесом, подключив его в сеть сбоку и выставив на нем инпут, скажем, 150к (или сколько ты там хочешь срезать).

Это все же костыли, а хотелось бы по-человечески.

> Урон от тока всегда один и тот же вне зависимости от напряжения в сети

Если будет слишком большое руки в пепел сжигать будет от 1 касания.

**Comment by Zmey25** [comment]
Неопытного инженера сразу видно. Ты еще не прошел игру, раз не знаешь как решить эту головоломку.
