### ISSUE TITLE
[Config] Заканчивается раунд при смерти некоторых ролей

### ISSUE THREAD

**Issue by Pimap3** [TauCetiStation/TauCetiClassic#7017]
#### Подробное описание проблемы
При смерти или задержании главной роли, происходят титры. То-есть, повязали хед реверов и сразу же титры из-за чего раунд продолжаться не может
#### Что должно было произойти
Раунд не закончился, глав ревы повязаны и имеют шанс сбежать из брига и продолжить революцию. Или, маг убит, но раунд продолжается
#### Что произошло на самом деле
Титры...И бомбящий народ
#### Как повторить
Повязать в наручники хед. реверов, убить мага
#### Дополнительная информация:
-

**Comment by KIBORG04** [comment]
Это не баг. Просто конфиг немного изменили

**Comment by KIBORG04** [comment]
![image](https://user-images.githubusercontent.com/26389417/114184976-d6c99a00-994d-11eb-8e98-dacf2c130405.png)

Эти режимы подвержены этому конфигу

**Comment by KIBORG04** [comment]
Вроде починили

**Comment by KIBORG04** [comment]
Не починили

**Comment by KIBORG04** [comment]
Теперь точно починили
