### ISSUE TITLE
[Task] Добавить откат до Extended в бандлах, если дефолтные режимы не могут запуститься

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#7023]
![изображение](https://user-images.githubusercontent.com/4064061/114362335-e2040c00-9b7f-11eb-9e81-b9730633fdde.png)
(скрин из дискорда)

Это может быть еще со времен, когда эксту убрали из секретов. Сейчас на том же третьем новые игроки не могут знать о воуте и не могут запустить раунд.

Следует, если все can_start режимов провалились (мало игроков, нету игроков для ролей), форсить раунд в режиме эксты.

**Comment by volas** [comment]
@KIBORG04 возможно у тебя в #6985 это уже решается? Если нет, возможно добавить?

**Comment by KIBORG04** [comment]
Поидее, у меня это решается, если в бандле есть экста, если же её нет то и будет такая же ошибка.

**Comment by KIBORG04** [comment]
Я наверное такое могу сделать, но опять же мне немного сложно тестить запуски режимов с двух акков

**Comment by TechCatOther** [comment]
Да, только тут видимо нужно с отсутвием

**Comment by TechCatOther** [comment]
> 
> 
> Я наверное такое могу сделать, но опять же мне немного сложно тестить запуски режимов с двух акков

Могу после ревью проверить на локалке

**Comment by volas** [comment]
> Поидее, у меня это решается, если в бандле есть экста, если же её нет то и будет такая же ошибка.

В текущих бандлах её тоже нету. Может быть, добавить в бандлы с минимальным приоритетом, пусть и будет небольшой шанс что режим может выпасть в обычных обстоятельствах вместо каких-то антагонистов?

**Comment by KIBORG04** [comment]
> В текущих бандлах её тоже нету. Может быть, добавить в бандлы с минимальным приоритетом, пусть и будет небольшой шанс что режим может выпасть в обычных обстоятельствах вместо каких-то антагонистов?

Я конечно не эксперт в понимании древнего кода, но вроде как в бс12 как раз есть экста, ведь в тау классике эту эксту пропускают
![image](https://user-images.githubusercontent.com/26389417/114444974-29b68200-9bd8-11eb-89fb-527b25ca1385.png)


https://github.com/TauCetiStation/TauCetiClassic/blob/b69b08ce43b8e6ea52d9f4f356cc27a7042f7b22/code/controllers/configuration.dm#L805-L814

**Comment by KIBORG04** [comment]
Вообщем я сделал тут: [`2d9e96a` (#6985)](https://github.com/TauCetiStation/TauCetiClassic/pull/6985/commits/2d9e96a52efa6c0d8d5f017f5eadeab5392a3cfb)
