### ISSUE TITLE
Антагхуд чужих и борги.

### ISSUE THREAD

**Issue by kalazus** [TauCetiStation/TauCetiClassic#7028]
#### Подробное описание проблемы
Если бывший чужой станет боргом (после смерти ghost ролью в позитронку), у него в конце будут антаг худ чужих. Скорее всего худ остаётся при любых ghost ролях.
#### Что должно было произойти
Антаг худа нету.
#### Что произошло на самом деле
Антаг худ есть.
#### Как повторить
Умереть за аленя и зайти за борга.

**Comment by KIBORG04** [comment]
Проблема в том, что позитроннка и еще некоторые другие места, которые берут игроков из гостов, перемещают майнд госта в своего моба через transfer_to. А в этом проке и ролька переместится в борга, и худ.

А так же дубликат все такое багу миллион лет
