### ISSUE TITLE
Ловушка для гостов

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#7041]
#### Подробное описание проблемы
Я обсервил тело, его сунули в морг, после чего я не мог двигаться, использовать фоллоу, тп к мобу и локации
#### Что должно было произойти
Я не попал в ловушку
#### Что произошло на самом деле
Ловушкааааааааа
#### Как повторить
Обсервить труп, подождать пока его сунут в морг
#### Дополнительная информация:
Issue reported from  Round ID: 40453 (Tau Ceti Classic (RU))
Testmerges: ```No test merges```
Reporting client version: 513.1542

**Comment by pss88** [comment]
Who you gonna call?

**Comment by LoTaRk-FroG** [comment]
У меня было что-то подобное однажды, перезаход помог
