### ISSUE TITLE
Собираемый телепорт почему-то настраивается брутально силой кусачек 

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#7043]
https://github.com/TauCetiStation/TauCetiClassic/blob/15bcb4aba5fe7b7111196956b6c3580b33973f5c/code/game/machinery/teleporter.dm#L426-L428

возможно тут опечатка и должен быть мультитул, возможно не опечатка и нужно все равно добавить какой-то более логичный шаг

**Comment by AirBlack** [comment]
Ну видимо кусачки - какой-то магический инструмент, который, помимо обрезания проводов, может их паять. Как в аирлоках, в которых провода паяются кусачками.

**Comment by Mercurialaste** [comment]
Тк, буквально выше описано действие мультитула, как я понял, на примере мех зарядника, смысл в том, что вариант с кусачками привязывает к первому попавшемуся рядом. Или типа того, а мультитул позволяет, привязать хаб к любой консоли. Мб, в консоли не прописана привязка.
