### ISSUE TITLE
Шлемы для РИГов спадают с костюма

### ISSUE THREAD

**Issue by Pimap3** [TauCetiStation/TauCetiClassic#7047]
#### Подробное описание проблемы
При нажимание toggle helmet с шлемом на голове, шлем от РИГа отцепляется и падает на пол
#### Что должно было произойти
Шлем засунулся обратно в РИГ и ваша кукла осталась без него
#### Что произошло на самом деле
Шлем упал на пол и отцепился от РИГа
#### Как повторить
Прицепить шлем к РИГу. Надеть его. Попробовать снять шлем
#### Дополнительная информация:
-

**Comment by KIBORG04** [comment]
возможно из-за https://github.com/TauCetiStation/TauCetiClassic/pull/7012
