### ISSUE TITLE
Одежда атмостеха

### ISSUE THREAD

**Issue by Leshiy-ART** [TauCetiStation/TauCetiClassic#705]
ВЕРНИТЕ ОБРАТНО СПРАЙТЫ ФОРМЫ АТМОСТЕХА!
УБЕРИТЕ ЭТИ ГРЯЗНЫЕ ЛОХМОТЬЯ! 
КАСКУ ТОЖЕ НЕ ТРОГАТЬ! Что это вообще за каски шахтеров из 50-х?

А еще у нас асей отвалился, да.

**Comment by Leshiy-ART** [comment]
Иначе я буду вынужден писать костыли, что бы в настройках можно было выбирать спрайты формы.
Возможно эти спрайты и красивые, но не сюда. Слишком много градиентов, замылености и округлости.

**Comment by volas** [comment]
Фикс асея буквально только что замержили. А атмостехи... @WatlerJe говорил, что может еще будет менять.

**Comment by Leshiy-ART** [comment]
А можно пока что просто поменять обратно, а как Вальтер может быть еще что-то изменит - посмотрим? И сегодня все могут заливать все что душе угодно?

**Comment by sovok4** [comment]
Ещё в ПРе заметили, что тускло и мыльно, но нет, все равно смержили. Вы бы хоть голосование на форуме устраивали за смену стандартных спрайтов.

**Comment by WatlerJe** [comment]
Остальным нравится. Тащемта привыкните.

**Comment by StrikS** [comment]
Не нравятся остальным...
![image](https://cloud.githubusercontent.com/assets/15943769/19739984/62a26c0c-9bd6-11e6-9fe7-0ccfc607fd29.png)

**Comment by WatlerJe** [comment]
Вайн в ООС, это ваши аргументы?

**Comment by StrikS** [comment]
В оос это как раз потребители смотрят.

**Comment by WatlerJe** [comment]
У вас там пуканы по любому поводу пригорают, так что требую конструктивную критику. Что и как хотелось бы исправить. Если вы просто исходите на гавно с криками "Верните старое", то какой смысл мне всеэ то для вас же рисовать?

**Comment by StrikS** [comment]
Вот тебе конструктивная, ты промолчал. "Я очень рад, что у нас есть такой спрайтер как ты, WalterJe. Но, прошу, не превращай яркие, сочные, цвета инженеров в болотные цвета канализационной службы. Особенно это касается бело-желто-зеленого комбеза CE." 
![image](https://cloud.githubusercontent.com/assets/15943769/19740069/c61acaae-9bd6-11e6-949a-53793fe34bb1.png)

**Comment by WatlerJe** [comment]
Старые цвета кислотные, СЕ так вообще зеленый с желтым и серым. Если будет настроение и время то может переделаю. опять же я кроме потоков говна от тебя и тебе подобных не получаю, так что тут мотивация заведомо падает.

**Comment by Leshiy-ART** [comment]
>кроме потоков говна от тебя и тебе подобных не получаю
Спасибо, это все что я хотел узнать.

**Comment by WatlerJe** [comment]
Тебе-то какая разница? Ты вообще заходишь раз в месяц, брысь в могилу.

**Comment by StrikS** [comment]
Я по-моему мягко скзал, что мне не нравится и поблагодарил тебя за твой труд. 

> "Я очень рад, что у нас есть такой спрайтер как ты, WalterJe. Но, прошу, не превращай яркие, сочные, цвета инженеров в болотные цвета канализационной службы. Особенно это касается бело-желто-зеленого комбеза CE."

**Comment by volas** [comment]
>Ещё в ПРе заметили, что тускло и мыльно, но нет, все равно смержили. Вы бы хоть голосование на форуме устраивали за смену стандартных спрайтов.

Никто же не говорит, что это навсегда. Вальтер старается. Мне тоже не всё в новых спрайтах нравится, но сейчас это стоит воспринимать как эксперименты, и мне лично было бы интересно посмотреть, что в результате получится в финале.  
Критиковать каждый может, а могли бы спокойно обсуждать и искать варианты.

**Comment by WatlerJe** [comment]
Энивэй, тут конкретно Леший, конкретно просит вернуть старый спрайты, так как они привычнее, я не спорю. Но здесь у меня вот идея по их улучшению и внезапно это юзерам нравится, не всем конечно но есть те кому они действительно зашли, а есть те кому они не нравятся. Так что вы себя своим мировоззрением не ограничивайте, помимо вас еще существует пипл и у них тоже есть свое видение некоторых вопросов.
