### ISSUE TITLE
Борер не может покинуть носителя

### ISSUE THREAD

**Issue by muWander** [TauCetiStation/TauCetiClassic#7050]
#### Подробное описание проблемы
Борер не покидает носителя. 
#### Что должно было произойти
Должен покинуть завершив процесс Release host
#### Что произошло на самом деле
Сообщение о завершении появляется но носитель не покидается
#### Дополнительная информация:
Issue reported from  Round ID: 40491 (Tau Ceti Classic (RU))
Testmerges: ```No test merges```
Reporting client version: 513.1539
Носитель кстати был без игрока внутри (кататоник), ранее такая проблема была с мартышкой

**Comment by KIBORG04** [comment]
Бореры впринципе очень багованные и плохо закоденные
