### ISSUE TITLE
Интерфейс скафандра остается даже если его снять

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#7056]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/19796920/115990771-b9dbca80-a5cd-11eb-83e8-2e05af485e03.png)

#### Что должно было произойти
Этого быть не должно
#### Что произошло на самом деле
Скрин выше
#### Как повторить
Надеть и снять скафандр
#### Дополнительная информация:
Функционал кнопок сохраняется, в чат пишет что переключение работает

**Comment by Motzord** [comment]
Проблема обнаружилась после этого #7012

**Comment by Ahion** [comment]
Странно, посмотрю
