### ISSUE TITLE
Форон заражает вещи через риг и хазмат

### ISSUE THREAD

**Issue by ViDLiathan** [TauCetiStation/TauCetiClassic#7058]
#### Подробное описание проблемы
Одежда заражается, даже если на космонавтике полный комплект защитной одежды.
#### Что должно было произойти
Космонавтик должен спокойно гулять по фороновой инженерке в противогазе и в защитном костюме.
#### Что произошло на самом деле
Трусы под хазматом облучились и космонавтик отравился.
#### Как повторить
Надеть на себя риг или хазмат, взять противогаз и выпустить форон.

**Comment by AirBlack** [comment]
Причем сам риг не заражается. Встает вопрос, нафиг очистка вообще в контейнере для рига? По приколу?
Может сделать какую-нибудь спец машинерию для обезараживания одежды, а то обычная стирка обезараживает, как-то неправильно(или у меня шиза)

**Comment by ViDLiathan** [comment]
Проблема всё ещё актуальна.

**Comment by Deahaka** [comment]
С хазматом баг, с ригом фича

**Comment by simb11** [comment]
Не согласен с человеком выше
