### ISSUE TITLE
Рандомивент с культопорталом слишком сильный

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#7080]
#### Подробное описание проблемы
Рандомивент с порталом слишком грифозный и просто напросто уничтожает раунды, в которых и так происходит некоторый омск.

#### Что должно было произойти
Рандомивент с порталом не должен мешать играть.

#### Что произошло на самом деле
В раунде происходит некоторое говно, появляется портал, из него вылазят мистические твари, убивают и ломают всё подряд устраивая 100%-ную разгерметизацию и раунд заканчивается.

#### Как повторить
Играть на первом сервере.

#### Дополнительная информация:
#40698
https://image.prntscr.com/image/tBpsICUeSkG8FF7B14o78Q.png
Станция просто ОПУСТЕЛА потому что конструкты вырезали всё население.

**Comment by KIBORG04** [comment]
наныл

**Comment by muWander** [comment]
разве ивент не был изначально работал так, что конструкты не могли покидать зону в которой заспавнился портал?

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/7137/commits/c42d92f3e730d6cfa163c16cd97e7d28ca8cde45
