### ISSUE TITLE
[Task] Устройство для предотвращения телепортации в некоторые зоны

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#7083]
Следует добавить какое-то устройство помех для всех видов телепортации на станции. Пусть это будет какая-то плоская херня прокручивающаяся к полу и активируемая картой.
При телепортации куда-нибудь с телесаенсом или телепортом или магией нужно проверять наличие работающего устройства в радиусе n тайлов и если есть - выталкивать человека или портал куда-то в рандомную другую сторону.
Следует разместить это устройство в капитанской, в арсенале СБ, у ИИ.
Будет хорошо, если заранее предусмотреть методы обезвреживания устройства - емаг, может ЭМИ.

Связано #4732

**Comment by volas** [comment]
> в радиусе n тайлов

Тут нужно будет подобрать в зависимости от размеров отсеков, и что бы устройство в капитанской задевало общие коридоры. Можно сделать радиус меньше и просто больше размещать на отсек.
Альтернативный вариант был бы делать действующим на всю area, но тогда возможны абузы. Даже если космос добавить в исключения, есть техи и коридоры с большими area.

**Comment by Sakuya-Izayoi** [comment]
Хочу добавить, что на дропподы с камерабагом это тоже должно работать. У них уже сейчас есть механизм предотвращения телепорта в важные места, но он основан на хардкоде.

**Comment by WallShrabnic** [comment]
Зачем это, если у нас и так одни из самых слабых антагов среди всех билдов в принципе?
