### ISSUE TITLE
Позитронный мозг, ПИИ не могут общаться будучи в руках или в инвентаре игрока.

### ISSUE THREAD

**Issue by Permyack** [TauCetiStation/TauCetiClassic#7089]
#### Подробное описание проблемы
ПИИ, Позитронка не могут общаться будучи в руке или в инвентаре игрока
#### Что должно было произойти
ПИИ, Позитронка должны иметь таковую возможность. Довольно неудобно, когда ты слышишь определенные вещи, но не имеешь возможности ответить. Так-же кажется не слышно окружающих, может лишь сам радиоэфир. На этот счет я не уверен.
#### Что произошло на самом деле
Будучи ПИИ или позитронным мозгом я не имел возможности общаться с кем-либо, когда был в руках или в инвентаре персонажа
#### Как повторить
Возьмите роль ПИИ или позитронного мозга. Другой игрок должен взять вас в руки или поместить в инвентарь. Попробуйте пообщаться с ним.
#### Дополнительная информация:
Так-же возможно данная проблема актуальна и для мозгов, помещённых в ММИ. Это я не имел возможности проверить. Может есть ещё подобные роли у которых точно такая-же проблема.
Issue reported from  Round ID: 40759 (Tau Ceti Classic (RU))
Testmerges: ```#7035 #7037 #7051 ```
Reporting client version: 513.1542

**Comment by KIBORG04** [comment]
Дубликат #6000
