### ISSUE TITLE
Консоль атмостеха

### ISSUE THREAD

**Issue by Leshiy-ART** [TauCetiStation/TauCetiClassic#709]
Через консоль управления атмосферными датчиками нельзя теперь настроить сенсоры.
А так-же уже давно нельзя отключить удаленно тревогу/снять блокировку.

Консоль камер тревог (энергии/атмосферные) работают через раз, или того меньше.

**Comment by Skippeer12** [comment]
Через эту консоль можно управлять аир алярмами только когда есть аир алярм. В иных случаях нет.
Ну и блокировка уже давно убита. Да.

**Comment by Dennok** [comment]
Развечто ты настроиш в нужном тебе аираларме удаленный консроль на ON

**Comment by Leshiy-ART** [comment]
Вот только при аялрме у меня не вышло ничего нажать. На самом алярме удаленный контроль стоял на Авто.

**Comment by StrikS** [comment]
Нужно больше данных
