### ISSUE TITLE
Ошибка при открытии crew monitoring computer.

### ISSUE THREAD

**Issue by Invent0-r** [TauCetiStation/TauCetiClassic#7103]
#### Подробное описание проблемы
Вот такое чудо появляется иногда при открытии Монитора наблюдения. Раз в неделю стабильно. При закрытии появляется опять. Не то что бы не давало играть, но неприятно.

![image](https://user-images.githubusercontent.com/46276761/116891820-d87a3b00-ac37-11eb-856e-b3d06db6acbd.png)

#### Дополнительная информация:
Issue reported from  Round ID: 40810 (Tau Ceti Classic III (RU))
Testmerges: ```#7035 #7037 #7051 ```
Reporting client version: 513.1542

**Comment by Sakuya-Izayoi** [comment]
#3669 дубликат
