### ISSUE TITLE
Проблемы с ожирением

### ISSUE THREAD

**Issue by Zickusable** [TauCetiStation/TauCetiClassic#7112]
#### Подробное описание проблемы
Наевшись до синей полоски, ничего не происходит плохого, но стоит полоске перейти на предыдущую стадию (желтый), кукла внезапно полнеет, для СБ в юбке это плохо кончается(трусы слетают со всеми вещами). В последний раз юбка поменялась на обычные трусы СБ, но у всех она почему-то стала показываться серой(в слоте все еще красная)
#### Что должно было произойти
Ожирение при ПЕРЕедании(серая полоска)
Женская униформа не слетает
#### Что произошло на самом деле
Внезапно оказалась голой в толпе тестовиков
#### Как повторить
Покушать до фула. Не переесть!
Сжигать калории до предыдущей отметки сытости.
#### Дополнительная информация:

**Comment by WatlerJe** [comment]
Насколько я понимаю ожирение на ТК работает следующим образом: При достижении куклой N числа пищи и выше в организме, происходит активация отсчета через которое кукла должна потолстеть, то есть изменится спрайт, появляются дебафы/бафы и т.д. По сути происходит мутация.
В игре же счетчик игнорирует количество ед. пищи после начала отчета, и выдает ожирение через отведенное ему время.
Все свои заключения выше я сделал исходя из игрового опыта, к сожалению не нашел в коде как это работает.

Касательно одежды, здесь все просто. Для каждой униформы и сьюта должна иметься вариация спрайта для толстых которая активируется когда у куклы включается ожирение, механика есть, но нету спрайтов для всего этого. 
Ввиду отсутствия организации и требований, в билд за все эти годы завезли тонны флафовых шмоток, при этом никто не позаботился о том, чтобы у них была в наличии вариация для толстых. В результате не всю униформу можно носить с ожирением, сьюты так вообще нельзя. Такие дела.

**Comment by LudwigVonChesterfield** [comment]
![image](https://user-images.githubusercontent.com/17705613/159375596-ecabbf0a-43b0-4b28-90a7-2374789ff07f.png)

Юбка сломалась по причине нет спрайтов, так же ломается униформа если её приспустить (Roll Down Jumpsuit)

![image](https://user-images.githubusercontent.com/17705613/159375651-1cf4bba3-7c49-4a5b-b95e-82ecd3f60e03.png)

Здесь видно как выглядят спрайты приспущенной униформы, с ними всё работать будет

![image](https://user-images.githubusercontent.com/17705613/159375631-36d558f0-e410-4195-a442-ed22fe4c984a.png)

Почему серый комбинезон? Потому-что он сюда закинут как спрайт без имени. Если не получается из файлика достать спрайт - берётся спрайт без имени.
