### ISSUE TITLE
[Proposal] Добавить кнопку действий "resist" на игровой экран 

### ISSUE THREAD

**Issue by ChewedGum** [TauCetiStation/TauCetiClassic#7113]
#### Подробное описание проблемы
Лезть во вкладку ИЦ, искать кнопку резиста - неудобно и эстетически неприятно выглядит. Подобные геймплейные действия должны быть доступны на экране игры.  
#### Что должно было произойти
Кукла загорелась - игрок нажимает на кнопочку резиста на экране - кукла успешно себя тушит.
#### Что произошло на самом деле
Кукла загорелась - лысый ассистент орет ИЦ и в ООЦ матом будучи не в курсе как себя потушить - кукла сгорает насмерть, попутно устраивая цепной пожар поджигая всех остальных персонажей в радиусе 20 тайлов.
#### Как повторить
Как-нибудь.
#### Дополнительная информация:
На каком-то другом сервере видел такие кнопочки но их названия не помню.

**Comment by KIBORG04** [comment]
Я тебя, наверное, удивлю, но кнопка резиста на игровом экране еще c года так 2011
