### ISSUE TITLE
Взлом хрефа в слипере позволяет создавать любой реагент

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#7120]
#### Подробное описание проблемы
Взлом хрефа в слипере позволяет создавать любой реагент

#### Как повторить
никак.

![image](https://user-images.githubusercontent.com/30875884/117327847-b7198900-ae9b-11eb-9610-bb537d6d4806.png)
![image](https://user-images.githubusercontent.com/30875884/117327874-bd0f6a00-ae9b-11eb-9254-ab6053ad06bb.png)
![image](https://user-images.githubusercontent.com/30875884/117327943-ce587680-ae9b-11eb-854d-931b6d73d181.png)

**Comment by KIBORG04** [comment]
Пойду абузить

**Comment by Ro2tCrab** [comment]
Тоже самое..

**Comment by KIBORG04** [comment]
> Абузим? А за это можно словить бан?

За это нужно банить
