### ISSUE TITLE
Некорректная работа эведенс багов (evidence bag).

### ISSUE THREAD

**Issue by JustUser2211** [TauCetiStation/TauCetiClassic#7142]
#### Подробное описание проблемы
Мы получаем бесконечное количество плетей для всех желающих людей.
#### Что должно было произойти
Вот это.
![2021-05-10_16-01-31](https://user-images.githubusercontent.com/62606828/117663179-0a941b80-b1a9-11eb-9b3b-ea7c917d3fd3.png)
#### Что произошло на самом деле
![2021-05-10_15-52-54](https://user-images.githubusercontent.com/62606828/117663438-56df5b80-b1a9-11eb-984a-23dac0881132.png)
![2021-05-10_15-53-07](https://user-images.githubusercontent.com/62606828/117663467-5cd53c80-b1a9-11eb-8d1b-7d7533b9a146.png)
![2021-05-10_15-53-51](https://user-images.githubusercontent.com/62606828/117663478-5f379680-b1a9-11eb-8d31-e6f4e03be039.png)
Полностью рабочая плетка из пакета, даже если мы ее не покупали в абилках.
#### Как повторить
Щелкнуть эведенс багом по плетке, после - просто достать ее.
#### Дополнительная информация:
Данная плетка не будет работать у НЕ генокрадов. Плетку не видно в руках.

**Comment by volas** [comment]
есть ли в билде вообще еще более безобидные с виду но столь же проблемные фичи, как эти пакеты улик

**Comment by JustUser2211** [comment]
Я тут потестил, это еще работает с кувалдой и щитом, уф...
Щит даже для НЕ генок полноценно работает.

**Comment by Motzord** [comment]
![image](https://user-images.githubusercontent.com/45365635/117673003-0a008280-b1b3-11eb-923d-9f41e45e13f1.png)

**Comment by Motzord** [comment]
Представляю вашему вниманию тот самый легендарный пакет с пакетами
![image](https://user-images.githubusercontent.com/45365635/117675733-809e7f80-b1b5-11eb-88e7-10c7d020fcb1.png)

**Comment by Motzord** [comment]
![image](https://user-images.githubusercontent.com/45365635/117677759-6a91be80-b1b7-11eb-9c72-0876b0f9cd18.png)
Мартышка не может вылезти из волшебного пакета. Смешно

**Comment by Motzord** [comment]
Требую переименовать ишью для более корректного поиска в дальнейшем

**Comment by JustUser2211** [comment]
> ![image](https://user-images.githubusercontent.com/45365635/117677759-6a91be80-b1b7-11eb-9c72-0876b0f9cd18.png)
> Мартышка не может вылезти из волшебного пакета. Смешно

Это я обманул чутка, выйти из пакета все же можно.

**Comment by JustUser2211** [comment]
Одно из костыльных решений - сделать все абилки хьюдж айтемами, может кто сделает...

**Comment by KIBORG04** [comment]
Я не предполагаю, я пишу способ фикса

**Comment by LudwigVonChesterfield** [comment]
а ещё у нас есть canremove который используется у шлема рига который тоже возможно надо проверять но не совсем в этом случае.

вероятно требуется более комплексное решение чем искать все места в билде где возможно нужно проверить DROPDEL

(к примеру проки вида can_drop, can_take_off, и т.д.)
