### ISSUE TITLE
Беды комбо Disarm с клоунами.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#7145]
#### Подробное описание проблемы
Дядя людук закодил, что клоун при дизарме будет класть всякие предметы в руку оппоненту и это смешно, но он не учел пару вещей.
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/45365635/117679770-3d461000-b1b9-11eb-9806-5b8a3667a960.png)
![image](https://user-images.githubusercontent.com/45365635/117681725-0f61cb00-b1bb-11eb-8536-11563bd92469.png)

![image](https://user-images.githubusercontent.com/45365635/117682415-b0e91c80-b1bb-11eb-9638-ac970434e9d0.png)
Тут беда уже вне скоупа этого ишью, однако при клоунском слайд кике, ты стягиваешь не только униформу/трусы и прочие приколюхи, но даже неснимаемые вещь вроде големской кожи, хитина тенелингов. 
(То что снимается игнорируя риги и прочее, я думаю тоже проблема)
#### Как повторить
Клоун не может пихать приколы в руки всем подряд игнорируя проверки. Клоун не может сдирать трусы сквозь риги и сдирать неснимаемые вещи.
#### Дополнительная информация:
опять лудук во всем виноват

**Comment by Motzord** [comment]
@LudwigVonChesterfield

**Comment by KIBORG04** [comment]
Схожий баг с #7142, где не учтены флаги дропдел и абстракт.
