### ISSUE TITLE
Нюкеры/дедсад/вставьте_название_крутой_роли умирают от смазки

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#7158]
#### Подробное описание проблемы
Смазка до сих пор остается ультимативной не контрящайся вещью, к тому же отсутствует нормальный фидбек для игроков о том, что на полу налита чертова смазка, как это сделано например с топливом/водой. К тому же крутые ботиночки нюкеров/магбутсы/etc  не защищают от смазки, из-за чего крутые парни сосут от любого химика со стаканом смазки.
#### Что должно было произойти
Игрок видит что пол в смазке/есть способы не подскользнутся на смазке/etc
#### Что произошло на самом деле
Нюкеры всем дрим тимом пролетели на смазке в техах и упали Марку Лисенко под ноги, под мое хиханье. я настолько сильно засмеялся что прыснул чаем на монитор, а это плохо, не надо настолько смешно делать
#### Как повторить
разлейте смазку и пытайтесь со всей силы на ней не подскользнутся.

**Comment by LudwigVonChesterfield** [comment]
а с каких пор нет подсказок о том что подскальзывает пол

**Comment by Motzord** [comment]
> а с каких пор нет подсказок о том что подскальзывает пол

У водички есть волшебный оверлей на плиточках, указывающий что плитка мокрая и блестит. Экзамайнить в бою каждый турф чтобы узнать есть ли  на нем смазка — не круто.

**Comment by LudwigVonChesterfield** [comment]
я имею ввиду, подсказки нет
