### ISSUE TITLE
Большая задержка при использовании рации

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#7162]
#### Подробное описание проблемы
Если говорить в рацию через :r/:l при этом держа её в правой/левой руке, сообщения будут отправляться с несколькосекундной задержкой.

#### Что должно было произойти
Сообщения по рации должны отправляться мгновенно (как по любым другим радиодевайсам)

#### Что произошло на самом деле
Перед отправкой сообщения проходит несколько секунд.

#### Как повторить
1. Взять рацию в правую руку.
2. Включить динамик, но не включать микрофон.
3. Say ":r спасите грифонят
4. Увидеть что сообщение отправится спустя пару секунд.

**Comment by Tiarv** [comment]
Почему должны? Может это обычное радио, а не блушпейс.

**Comment by Invent0-r** [comment]
> Почему должны? Может это обычное радио, а не блушпейс.

Скорость радиоволны - все еще скорость света.
