### ISSUE TITLE
Роль блоба выпадает кому угодно

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#7176]
#### Подробное описание проблемы
Вардены/хосы/капитаны/офицеры получают роль блоба и раундстартом завладев пушечкой выпиливают своих прямых противников
#### Что должно было произойти
Варден не устраивает колумбайн брига раундстартом, чтобы на изи сделать гринтекст
#### Что произошло на самом деле
I'm dead
#### Как повторить
![image](https://user-images.githubusercontent.com/45365635/118380382-fce7f700-b5e9-11eb-859a-35c18dde5cd7.png)
Уже повторили

**Comment by Pimap3** [comment]
Не баг, а фича!

**Comment by Sakuya-Izayoi** [comment]
Во-первых не баг, во-вторых так можно. Да, это хуйня полнейшая. #7124
