### ISSUE TITLE
Проблема с кэшем.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#718]
#### Подробное описание проблемы

После удаления кэша, невозможно зайти на TK.
![image](http://image.prntscr.com/image/2bee8960a45b44c68be5b1f55cbf5e18.png)
Ничего не происходит.
#### Что должно было произойти

Должна была произойти загрузка ресурсов.
#### Что произошло на самом деле

Клиент завис.
#### Как повторить

Удалить папку с кэшем, и подключиться на сервер.
#### Дополнительная информация:

Предварительно рекомендуется сделать копию кэша.

**Comment by volas** [comment]
Антивирусы/фаерволы/виндоус дефендер? Скорее что-то ограничило права бьенда.
Можешь попробовать еще сам бьенд переставить.

Проблема точно не билда.

**Comment by P-20** [comment]
Все это опробовал, тестировал на других ПК, даже привлек ментора. У него та же проблема.

**Comment by P-20** [comment]
Проблема решена сносом системы, и установкой с нуля. Проблема была вызвана вероятно одним из последних обновлений для Win10.
