### ISSUE TITLE
Споры блоба бьют груши вместо экипажа

### ISSUE THREAD

**Issue by Zickusable** [TauCetiStation/TauCetiClassic#7189]
#### Подробное описание проблемы
Споры блоба бьют груши в свободное время или вместо избиения экипажа.
#### Что должно было произойти
Споры побеждают людей
#### Что произошло на самом деле
Споры тестируют комбухи на грушах
#### Как повторить
Заспавниться блобом в техах дорм и создавать споры

**Comment by Pimap3** [comment]
Все симплмобы почему-то атакуют груши. Думаю это фича

**Comment by KIBORG04** [comment]
Маловероятно, что фича. Мб, грушам стоит прописать стат на дед, тогда не будут трогать.

**Comment by LudwigVonChesterfield** [comment]
вернуть груши объекты все равно ими по назначению никто не пользуется

**Comment by Rahmanio** [comment]
> Маловероятно, что фича. Мб, грушам стоит прописать стат на дед, тогда не будут трогать.

Когда груши умирают, они падают на землю, так закодили.

**Comment by volas** [comment]
нужно скорее всего посмотреть в сторону мобских фракций, есть ``faction = "neutral"`` но кажется в хостайл мобах не учитывается. Добавить грушам и в ``/mob/living/simple_animal/hostile/CanAttack``

**Comment by LudwigVonChesterfield** [comment]
и тогда груши будут видны через стены термалками

или ещё какой-то дурацкий мем, типо того что они могут крутить стулья

или что их можно пристёгивать к креслам, и вешать в виселицу

или что их можно дробить у повара в дробилке

думаю делать мобом то что есть объектом в нашем билде на данный момент - было ошибкой.

**Comment by volas** [comment]
> или что их можно пристёгивать к креслам, и вешать в виселицу

это не только проблема груш, где-то у меня было... вот
![изображение](https://user-images.githubusercontent.com/4064061/120795711-7ff1d280-c542-11eb-9092-36b26c8291be.png)

И как и остальное. Запретить термалкам видеть определенных мобов может пригодится не только для груш, и так далее.

**Comment by KIBORG04** [comment]
> И как и остальное. Запретить термалкам видеть определенных мобов может пригодится не только для груш, и так далее

Это поидее невозможно. Термалки, мезонки повзоляют видеть сквозь других объекты благодаря бьондо флагу sight (вроде). А так как это бьондофлаг, то вообще непонятно как это изменить

**Comment by Sakuya-Izayoi** [comment]
> > И как и остальное. Запретить термалкам видеть определенных мобов может пригодится не только для груш, и так далее
> 
> Это поидее невозможно. Термалки, мезонки повзоляют видеть сквозь других объекты благодаря бьондо флагу sight (вроде). А так как это бьондофлаг, то вообще непонятно как это изменить

сделать чтобы был не флаг, а штука которая накидывает клиенту картинки-копии нужных мобов.

**Comment by KIBORG04** [comment]
Ты их все равно не увидишь, так как ТЕМНОТА создаваемая от density (типо моб не может увидеть сквозь стену) тоже является бьондоштукой, которую довольно сложно обойти. Насколько я помню, штуки в этой темноте даже не рендеряться. Но есть один способ, как получить рендер в этой темноте, но тогда можно будет абузить ПКМ клики в темноту.

**Comment by volas** [comment]
> Это поидее невозможно. Термалки, мезонки повзоляют видеть сквозь других объекты благодаря бьондо флагу sight (вроде). А так как это бьондофлаг, то вообще непонятно как это изменить

хм, да, но опять же не проблема только груш. Мимики и всё что угодно страдают тоже, и для них это даже более критично.
