### ISSUE TITLE
Тритор "умирает" после переноса разума

### ISSUE THREAD

**Issue by MrBite** [TauCetiStation/TauCetiClassic#7213]
#### Подробное описание проблемы
Если маг перенесётся в тело трейтора,а потом вернётся обратно,то в титрах показывает что трейтор мёртв,а цели на выживание/кражу провалены,даже если на самом деле они выполнены
#### Что должно было произойти
Трейтор возвращается в своё тело/выполняет задания в новом и получает свой гринтекст
#### Что произошло на самом деле
Гринтекста нет
#### Как повторить
Поменяться с магом телами и вернуться обратно,после чего выполнить цели и завершить раунд. Глянуть в титры
#### Дополнительная информация:
Раунд #41491,второй сервер

**Comment by KIBORG04** [comment]
скорее всего пофикшено
