### ISSUE TITLE
Борг шахтёр не может копать. Сломан бур.

### ISSUE THREAD

**Issue by BeebBeebBoob** [TauCetiStation/TauCetiClassic#7231]
#### Подробное описание проблемы
Игра уже шла примерно 40 минут. Я зашёл за приведение и вселился в позитронку. Потом борг и взял модуля шахтёра. Полетел на шахт. станцию добывать руду по умолчанию. Не помню в какой порядке брал модули но обычно я брал бур, мешок под руды и Meson Vision (очки). Пошёл с ящиком в шахту добывать и тут вылезает ошибка 
"You don't have the dexterity to do this!" красный жирным текстом. Потом пытался на другой режим. Пытался отверткой на бур. Пытался перекладывать из инвентаря обратно. Всё таже ошибка.
#### Что должно было произойти
Обычно работающий бур. Ну типо я должен был выкопать камень и всё.

#### Что произошло на самом деле
Как описал выше вылезла ошибка "You don't have the dexterity to do this!".

#### Как повторить
Первый раз ошибка вылезает играя за борга шахтёра. Ещё не повторял.

#### Дополнительная информация:
Нету.

**Comment by Phoenix4O4** [comment]
@KIBORG04 тут кажется ты в курсе что там. Или не?

**Comment by KIBORG04** [comment]
фикшено
