### ISSUE TITLE
Неприятное соотношение окошки PDA -> Crew Manifests. 

### ISSUE THREAD

**Issue by BeebBeebBoob** [TauCetiStation/TauCetiClassic#7233]
#### Подробное описание проблемы
Добавили в Crew Manifests DM что круто но из-за добавления каждый персонал занимает не одну строку а две. Можно исправить расширив окно но неприятно когда ты несколько раз открываешь и закрываешь ПДА ибо часто работашь с окошками.
#### Что должно было произойти
Приятное пропорция в Crew Manifests. 
![image](https://user-images.githubusercontent.com/32985153/120032312-ad022a80-c002-11eb-940f-0ea7a4931ca9.png)

#### Что произошло на самом деле
Каждый раз когда снова открываю окно вот что выходит. 
![image](https://user-images.githubusercontent.com/32985153/120032355-bd1a0a00-c002-11eb-9161-fce80f73e7d0.png)

#### Как повторить
Просто открыть ПДА и войти в Crew Manifests.

#### Дополнительная информация:
нету.

**Comment by logimy** [comment]
Беру в работу, сейчас поправлю
