### ISSUE TITLE
Всемогущий стол хирурга

### ISSUE THREAD

**Issue by Zickusable** [TauCetiStation/TauCetiClassic#7242]
#### Подробное описание проблемы
Чувак под анастезией или тупо лежа без ног может класть кого угодно на стол
#### Что должно было произойти
Сообщение лежачему коврику: "У тебя недостаточно ловкости для этого!"
#### Что произошло на самом деле
СБшник-нехорошийчеловек затролил СМО перекладкой его на стол, после чего справедливо остался в шкафчике без ног до конца смены
#### Как повторить
Лежа не операционном столе под анастезией (или без) перетащить мышкой врача на стол

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/6650
