### ISSUE TITLE
Мыши и команда me

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#7247]
#### Подробное описание проблемы
Когда мыши прожимают команду me, то сначала открывается стандартная менюшка me, а потом после ввода текста вместо отображение в чатике открывается вторая менюшка в которую уже надо вводить текст, ибо он покажет только текст из второй менюшки
#### Что должно было произойти
Мышь прожимает me и вводит текст, который появится в чате
#### Что произошло на самом деле
Мышь прожимает me вводит любую фигню и дальше уже вводит текст во второй менюшке
#### Как повторить
1. Выбрать мышь
2. IC > Me
3. Ввести любой текст
4. Убедиться что текст профакапился и открылась вторая менюшка
5. Ввести в менюшку любой текст и убедиться что текст появился в чате
#### Дополнительная информация
Мороженное с шоколадной крошкой очень вкусное. Всем советую

**Comment by Akellazp** [comment]
это вроде как проблема вообще всех симпл мобов
