### ISSUE TITLE
Окна на tgui не возможно сдвинуть/закрыть

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#7248]
Ту херню для выдачи пропусков
Осознайте что крестик окна для выдачи пропуска улетел за экран и ты не можешь по каким то волшебным причинам перетащить окно
С лицом жабки тыкай fixnanoui
#### Что должно было произойти
Я могу спокойно передвигать-растягивать-закрывать окна на tgui без отдельных кнопок и плясками с бубном
#### Что произошло на самом деле
Я не могу
#### Как повторить
написал выше

**Comment by KIBORG04** [comment]
Так проблема же типо с размером твоего моника, не?

**Comment by Motzord** [comment]
> Так проблема же типо с размером твоего моника, не?

Возможно, так оно и есть, сейчас проверил консоль камер, с окном больше таких траблов нет. Теперь посчет консоли выдачи пропусков:
![image](https://user-images.githubusercontent.com/45365635/120103468-60306800-c158-11eb-9ef5-daf2feb67323.png)

**Comment by Motzord** [comment]
Я тупо не могу прокликать верхнюю грань окна, как бы не старался, о крестике я вообще молчу.

**Comment by volas** [comment]
win+стрелочки могут помочь

**Comment by Motzord** [comment]
> win+стрелочки могут помочь

Не могут, win+стрелочки взаимодействует с окном игры, а не с окном консоли. (Тупо хардкодом блин нужно окно сместить чуть ниже и все)

**Comment by Phoenix4O4** [comment]
Попробую поправить сейчас.

**Comment by Phoenix4O4** [comment]
Исправил в другом ПРе, теперь при разрешении 800x600 открывается вот так 
![image](https://user-images.githubusercontent.com/41524861/120107103-59115600-c168-11eb-957a-68fb904abbda.png)
