### ISSUE TITLE
Ивентовый культопортал из-за сомнительной фичи грифонит станцию когда не надо

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#7258]
#### Подробное описание проблемы
Киборг запилил фичу с ивентовым культопорталом, с ограниченной зоной для конструктов, но проблема в том, что зона эта расширяется каждые сколько-то времени что ведет к загрифониванию станции гостотой джаст фор лулз
#### Что должно было произойти
Зона портала не расширяется, гостота страдает, космонавтики играют в тир и все веселятся
#### Что произошло на самом деле
Спавнятся джагернауты, отражают лазеры, впитывают пульки, воюют с СБ, культопортал расширяется, джага бежит делать разгерму, гроб-кладбище-пидор станция загрифонена в условную реву.
#### Как повторить
Дождитесь культопортала, идите воевать с конструктами, не успейте заспидранить и умрите от разгермы.
#### Дополнительная информация:
У анс в билде хватает грифонящих ивентов делающих разгермы вроде пыли, плесени, метеоров, ебучего копья и пирокластика. Культопортал как аномалию, очень проблематично обезвреживать ученым из-за защиты в виде гостоты, а офицеры не успевают перестреливать жирных конструктов (особенно джагернаутов, из-за щита+механа аблятивки+тонны ХП) в итоге любой режим с этим порталом, может превратится в "Гостота веселится и грифонит космонавтов"

**Comment by Sakuya-Izayoi** [comment]
Будто бы у экипажа нечем контрить разгерму.

Вообще, там три жалких конструкта спаунится, так что ничего страшного.

**Comment by Akellazp** [comment]
мотзорд проиграл и ноет
