### ISSUE TITLE
Проблемы с отображением законов у ИИ

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#7262]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/45365635/120243706-02437380-c271-11eb-9cb8-1e03b18892c8.png)

#### Что должно было произойти
У ИИ корректно отображаются законы
#### Что произошло на самом деле
https://forum.taucetistation.org/t/banhammer-maksimsiral-ii-selfantag/25789
![image](https://user-images.githubusercontent.com/45365635/120243742-14bdad00-c271-11eb-8ef6-49ad85065984.png)

#### Как повторить
Скорее всего связано с ПРом про командные рольки. (Наблюдалось только на первом сервере после тестмержа(

**Comment by KIBORG04** [comment]
Я фиксил, но билд забыл обновить

**Comment by 4310V343k** [comment]
актуально

**Comment by KIBORG04** [comment]
Там такой был угар вы бы видели. И там не то чтобы проблема была с их отображением, раундстартовому ИИ впринципе законы не выдавались
