### ISSUE TITLE
Беды с пИИ

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#7263]
#### Подробное описание проблемы
пИИ не слышат чат, только радио
#### Что должно было произойти
пИИ слышит то что он говорит, и то что говорят другие
#### Что произошло на самом деле
пИИ слышит только радио и не слышит обычную речь в том числе и свою
#### Как повторить
1. Стать пИИ
2. Что-то сказать в обычный say
#### Дополнительная информация:
Все еще считаю мороженное с шоколадной крошкой лучшим. А мята плохо растет...

**Comment by KIBORG04** [comment]
#6000

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/6000
