### ISSUE TITLE
Раунд не закончился при блобе

### ISSUE THREAD

**Issue by muWander** [TauCetiStation/TauCetiClassic#7272]
#### Подробное описание проблемы
Блоб вырос, анонс критической массы блоба спамился в чат каждый тик, но раунд не заканчивался до форсрестарта
#### Дополнительная информация:
Блобов было два, и этот (второй) вылупился позднее первого почему-то (педальная магия?)
Issue reported from  Round ID: 41692 (Tau Ceti Classic (RU))
Testmerges: ```#7093 #6985 ```
Reporting client version: 513.1542

**Comment by KIBORG04** [comment]
Фикшено короче
