### ISSUE TITLE
Оружие и кобура

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7276]
#### Подробное описание проблемы
если засунуть оружие в кобуру и очень быстро вытягивать(h) то оно пропадет
#### Что должно было произойти
Оружие осталось
#### Что произошло на самом деле
Оружие пропало
#### Как повторить
Положить оружие в наплечную кобуру(shoulder holster) и очень быстро нажимать h

**Comment by 4310V343k** [comment]
![](https://i.imgur.com/jBSUDrj.png)
Не воспроизводится

**Comment by AndroBetel** [comment]
у меня воспроизводилось с тазером, я еще быстро режимы менял

**Comment by KIBORG04** [comment]
Не нажимайте очень быстро h и бага не будет. Плюс, мб, новые хоткеи пофиксят это

**Comment by LudwigVonChesterfield** [comment]
#7093

**Comment by LudwigVonChesterfield** [comment]
f09de2c
