### ISSUE TITLE
Алиены не могут потушить себя

### ISSUE THREAD

**Issue by ChewedGum** [TauCetiStation/TauCetiClassic#7281]
#### Подробное описание проблемы
При возгорании, алиены могут попытаться "stop, drop and roll" через кнопоку "resist" чтобы потушиться (как любой гуманойд на этом билде), однако это не делает вообще ничего кроме того как станит их на несколько секунд. Подсказка справа наверху на худе говорит что пока лучше бы постоять на сорняках (weeds) и это каким-то образом поможет. На самом деле это вранье и тоже никак не помогает.
#### Что должно было произойти
Отчаянный инженер влетает в логово ксеноморфов, стреляет с огнемета пару раз. Загоревшиеся ксеноморфы тушатся за 10-20 секунд, нагоняют инженера и превращают его внутренности в наружности. 
#### Что произошло на самом деле
Подоженные ксеноморфы катаются по полу изо всех сил и продолжают гореть. 
#### Как повторить
Загореться за ксеноморфа, попробовать потушиться.

**Comment by JustUser2211** [comment]
![Алени](https://user-images.githubusercontent.com/62606828/120722891-489b0b80-c4d9-11eb-97f2-c2e524c1f63a.png)
В это время алени, которые нажали резист два раза.

**Comment by ChewedGum** [comment]
Т.е. дважды нужно кликнуть? Типа когда упал и лежа в стане нажимаешь "резист" опять?

**Comment by BeebBeebBoob** [comment]
Там даже в вики написано что нужно нажать резист чтоб потушить себя.

**Comment by ChewedGum** [comment]
Недавно проверил, оказывается действительно нужно прожать резист пока лежишь в стане чтобы потушиться.

**Comment by ChewedGum** [comment]
А почему закрыли то? Оно же с первого тыка в резист должно тушиться.

**Comment by KIBORG04** [comment]
Алиены не тушатся и алиены должны тушится с первого клика это разные проблемы

**Comment by ChewedGum** [comment]
Мог бы попросить сменить название темы.
