### ISSUE TITLE
Синий экран ТГУИ в орбит окошке

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#7288]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/30875884/120887687-fc48ec00-c5fc-11eb-88e9-4cf98dc7e0e9.png)

После рандомивента со спауном алиенов появилось вот такое.

#### Дополнительная информация:
Issue reported from  Round ID: 41799 (Tau Ceti Classic (RU))
Testmerges: ```#7287 #7259 #7093 ```
Reporting client version: 513.1542

**Comment by Phoenix4O4** [comment]
> #### Подробное описание проблемы
> ![image](https://user-images.githubusercontent.com/30875884/120887687-fc48ec00-c5fc-11eb-88e9-4cf98dc7e0e9.png)
> 
> После рандомивента со спауном алиенов появилось вот такое.
> 
> #### Что должно было произойти
> #### Что произошло на самом деле
> #### Как повторить
> #### Дополнительная информация:
> Issue reported from Round ID: 41799 (Tau Ceti Classic (RU))
> Testmerges: `#7287 #7259 #7093 `
> Reporting client version: 513.1542

Такое может быть, и да, вроде только где алиены есть. Насколько помню оно временно, поправлю вместе с антаг.орбитом
