### ISSUE TITLE
Сломанный тринарный

### ISSUE THREAD

**Issue by atik1n** [TauCetiStation/TauCetiClassic#7292]
#### Подробное описание проблемы
Тринарный не работает через :x

#### Что должно было произойти
||||| pings ...

#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/14612180/120897701-2ec00c80-c630-11eb-9c7f-9dbe138a9799.png)

**Comment by Akellazp** [comment]
фейспалм чел :ч

**Comment by atik1n** [comment]
> фейспалм чел :ч

Чел. И :x и :ч должны работать.

**Comment by 4310V343k** [comment]
![image](https://user-images.githubusercontent.com/56449763/120936164-1672ef00-c70f-11eb-8bb9-dddec3256c5c.png)
И не поспоришь ведь
