### ISSUE TITLE
Отсутствие логов разговоров при ношении ПИИ в кармане или в руках

### ISSUE THREAD

**Issue by MemorDeQbist** [TauCetiStation/TauCetiClassic#7293]
#### Подробное описание проблемы
ПИИ слышит живой разговор только, если лежит на карте. Стоит ему оказаться в руках или в кармане, как все звуки пропадают. Остаются лишь каналы. Чтобы напрямую общаться, приходится кидать ПИИ на пол. 
#### Что должно было произойти
ПИИ должен слышать, что говорит ему хозяин, будучи у него в руках или в карманах
#### Что произошло на самом деле
ПИИ не слышит никаких звуков, если находится в руках или в карманах куклы
#### Как повторить
Взять активного ПИИ в руку или засунуть в карман
#### Дополнительная информация:
Issue reported from  Round ID: 41810 (Tau Ceti Classic (RU))
Testmerges: ```#7287 #7259 #7093 ```
Reporting client version: 513.1542

**Comment by KIBORG04** [comment]
#6000 

Бля, не зря тот ишуй получил такой красивый номер
