### ISSUE TITLE
Ходьба по диагонали выкидывает из труб

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#7296]
#### Подробное описание проблемы
Если попробовать пойти по диагонали в трубе, тебя из нее выкинет

#### Что должно было произойти
В трубах нельзя ходить по диагонали

#### Что произошло на самом деле
В трубах можно ходить по диагонали

#### Как повторить
Пойти по диагонали в трубе

**Comment by LudwigVonChesterfield** [comment]
real smooth

**Comment by BeebBeebBoob** [comment]
Это можно даже назвать экслоитом если играешь за ксеносов. Заварили например вентиляции в комнате и заперлись и если находясь в трубе пойти по диагонали то ты "вылезаешь" из трубы как если из выхода вентиляции хотя это невозможно. Очень опасный эксплоит так сказать.
