### ISSUE TITLE
Мидраунд блоб не может захватить станцию.

### ISSUE THREAD

**Issue by kalazus** [TauCetiStation/TauCetiClassic#7301]
#### Подробное описание проблемы
Мидраунд блоб по достижении нужного кол-ва тайлов не выигрывает.

#### Что должно было произойти
Блоб захватил станцию.

#### Что произошло на самом деле
Blob Telepathy, Blob Overmind (19) says, "507/500

#### Как повторить
Мидраунд блобом захватить нужно кол-во тайлов.

#### Дополнительная информация:
Скорее всего связано с #6985

**Comment by KIBORG04** [comment]
Сервер какой пишите

**Comment by kalazus** [comment]
1

**Comment by kalazus** [comment]
> Сервер какой пишите
1

**Comment by KIBORG04** [comment]
фикс в [`e714526` (#6985)](https://github.com/TauCetiStation/TauCetiClassic/pull/6985/commits/e714526dd37078a5b6c9a3909c572f024395ceda)
