### ISSUE TITLE
Пропадает ID карта при попытке достать её из АТМ

### ISSUE THREAD

**Issue by BuldozerJarosti** [TauCetiStation/TauCetiClassic#7314]
#### Подробное описание проблемы
При попытке достать ID карточку из АТМ с купюрой(скорее всего с другими предметами тоже самое) в активной руке, она пропадает из игры, ни в руках, ни в слотах не персонаже, ни на тайле под ним, ни в самом АТМ её нет.
#### Что должно было произойти
Карточка остаётся в АТМ или же просто падает на пол.
#### Что произошло на самом деле
Карточка исчезла из игры.
#### Как повторить
Достать ID карту из АТМ с купюрой в активной руке(возможно работает и с другими предметами).

**Comment by Sakuya-Izayoi** [comment]
анимации людука 100%. с холстером точно так же
