### ISSUE TITLE
[Bug] Суперспособность обёрточной пленки

### ISSUE THREAD

**Issue by notkripton** [TauCetiStation/TauCetiClassic#7315]
#### Подробное описание проблемы
Если закрыть игрока в любом шкафчике и обмотать его пленкой для посылок из карго, то он никак собственноручно оттуда выбраться не сможет.
#### Что должно было произойти
При попытке выйти из шкафчика пленка рвется.
#### Что произошло на самом деле
Взрослый сотрудник нанотрахен не может осилить обёртку для посылок.
#### Как повторить
Закрыть ассистента в ящике и кликнуть по нему обёрточной пленкой, выкинуть в космос (опционально).

**Comment by Sakuya-Izayoi** [comment]
Резист пробовал?

**Comment by Pivo24** [comment]
Резист помогает как при заваренном шкафчике

Отклоняйте немедленно!!!!!!!!!!!!!!!!

**Comment by notkripton** [comment]
> Резист помогает как при заваренном шкафчике
> 
> Отклоняйте немедленно!!!!!!!!!!!!!!!!

Ты шо наипсал блин расшифруйте

**Comment by muWander** [comment]
Резист работает и вынимает, прогрессбара только не появляется емнип

**Comment by KIBORG04** [comment]
Ну раз можно выбраться значит не баг
