### ISSUE TITLE
Спам бумажек в камеры ИИ.

### ISSUE THREAD

**Issue by BeebBeebBoob** [TauCetiStation/TauCetiClassic#7329]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/32985153/121405582-e2ddd200-c965-11eb-991a-2aa069106b7b.png)

#### Что должно было произойти
Может ограничение 5 раз?
#### Что произошло на самом деле
Любой может спамить и не давать ИИ говорить либо что-то сделать с каким-либо оборудованием потому что бумага важнее всего! Человек может спамить сколько угодно и мешать ИИ.
#### Как повторить
Играть за ИИ. Другой берёт бумагу и спамит по камере.

**Comment by Sakuya-Izayoi** [comment]
by design
