### ISSUE TITLE
Сломана кнопка Create Antagonist в админ-панели

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#7332]
#### Подробное описание проблемы
См. название
#### Что должно было произойти
Рабочий спавн антагонистов
#### Что произошло на самом деле
Роли не спавнятся должным образом. Попытка заспавнить магуса ни к чему не привела. В хрефах, несмотря на то, что было указано трое попыталось заспавнить шестерых. С культом вообще произошёл мем. Вместо четырёх заспавнилось 42 (!!). Вроде как такое же было позже с генокрадами
#### Как повторить
Create Antagonist. К слову, спавнил лично я скрытно, могло тоже повлиять
#### Дополнительная информация:
N/A

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/6985/commits/cd3f540fbd9fd42ed0a1ff8055aa647de8989ed2
