### ISSUE TITLE
Неправильно количество команд абдукторов.

### ISSUE THREAD

**Issue by kalazus** [TauCetiStation/TauCetiClassic#7337]
#### Подробное описание проблемы
Режим абдукторов спавнит только 1 команду. 

#### Что должно было произойти
Режим абдукторов спавнит команды в зависимости от онлайна (вроде при полном вообще должно быть 3)

#### Что произошло на самом деле
Одна команда при почти полном онлайне. 

#### Дополнительная информация:
Возможно связано с #6985

**Comment by ssbugman** [comment]
А режим абдукторов работает вообще? Он в принципе ни разу не выпал за все время якобы присутствия в ротации.

**Comment by Sakuya-Izayoi** [comment]
> А режим абдукторов работает вообще? Он в вообще ни разу не выпал за все время якобы присутствия в ротации, то есть его ни разу не было уже за несколько месяцев.

Он в ротации вообще-то несколько больше, чем несколько месяцев и выпадают, ну, скажем, с достаточной частотой. (Если бы он не выпадал уже несколько месяцев человек бы не смог вообще догадаться об этой проблеме, так ведь?)

**Comment by ssbugman** [comment]
> Он в ротации вообще-то несколько больше, чем несколько месяцев и выпадает, ну, скажем, с достаточной частотой. (Если бы он не выпадал уже несколько месяцев человек бы не смог вообще догадаться об этой проблеме, так ведь?)

Не знаю как он это заметил но лично я не видел чтобы абдукторы выпадали ни разу, а вот унылая рева в тим бейсед падает с частотой в 50% от всех раундов в этом режиме и уже достала.

**Comment by T6751** [comment]
@kalazus можешь сказать айди раунда или примерное время?

**Comment by kalazus** [comment]
> @kalazus можешь сказать айди раунда или примерное время?

Написал где-то под 50 минуту на 1 сервере. Похоже что Round #41956.

**Comment by Rahmanio** [comment]
Подтверждаю, видел множество раундов с абдукторами, всегда 1 команда, по началу думал что это связано с онлайном, но сейчас подумав и увидев ишью считаю это баг.

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/6985/commits/25ceb22c462324bc3af175c9d4aff4d30d50fc69

Поидее фикс. Если не сработает то напишите
