### ISSUE TITLE
экшн кнопки у шедоулингов

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7338]
#### Подробное описание проблемы
Неправильные иконки у экшн кнопок шедоу
#### Что должно было произойти
Нормальные иконки
#### Что произошло на самом деле
Иконка свитка за место нормальной иконки
#### Как повторить
стать шедоулингом
#### Дополнительная информация:

**Comment by Sakuya-Izayoi** [comment]
а ты видел иконки эти?

**Comment by simb11** [comment]
Иконки должны хоть как то отличаться.Ну или их вообще не должно быть...

**Comment by KIBORG04** [comment]
Можно ли считать одинаковые иконки их отсутствием? Раз все иконки идентичны, не несут смысла, то это же равносильно отсутсвию картинки..

**Comment by simb11** [comment]
вуху пофикшено
