### ISSUE TITLE
Режим абдукторов фактически исключен из ротации

### ISSUE THREAD

**Issue by ssbugman** [TauCetiStation/TauCetiClassic#7339]
**Подробное описание проблемы**
Режим абдукторов формально присутствует в ротации но никогда не выпадает.

**Что должно было произойти**
Периодически режим абдукторов происходит наравне с прочими режимами.

**Что произошло на самом деле**
Абдукторов не было ни разу за все время после добавления новой голосовалки (в старой вариант включавший их никогда не выбирали, не факт что они работали и там), хотя они формально присутствуют и в секрете и в тим бейсед. Все прочие режимы падали достаточное число раз, абдукторов словно на самом деле нет.

**Как повторить**
Достаточное время вести статистику режимов.

**Comment by Sakuya-Izayoi** [comment]
Такое ощущение что ссбугимэн обладает лучшей статистикой по гейммодам чем мейнтейнеры

**Comment by ssbugman** [comment]
> Такое ощущение что ссбугимэн обладает лучшей статистикой по гейммодам чем мейнтейнеры

Я не знаю ведут ли мейнтейнеры вообще статистику и не считают ли они что какие то режимы должны быть гораздо чаще других.
Этот репорт ставит целью прояснить в том числе и их позицию, не выставили ли абдукторам осознанно вероятность 0 в конфиге оттого что кому-то не понравился этот режим, как например решением всего одного-двух человек вместо пиратов игрокам навязали никому не интересных воксов.
Сейчас причина непонятна, известно только что абдукторов реально нет.

**Comment by KIBORG04** [comment]
Советую тебе чаще играть в игру, чтобы видеть абдукторов. Инфа из конфигов секрета, поэтому могу сказать, что только у экста шанс на выпадение 0.
Кондукторы падают, даже в эксте. Да даже я их видел, хоть почти не захожу.
Бага нету, есть только проблема с одной командой у них.

**Comment by ssbugman** [comment]
А какой у них минимальный порог декларов может в его завышенности причина?
Я каждый день захожу и подряд несколько раундов смотрю. Даже если абдукторы в вообще бывают они случаются крайне редко по сравнению с другими режимами хотя частота должна быть равна по хорошему..
