### ISSUE TITLE
размер чата не сохраняется после рестарта

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7352]
#### Подробное описание проблемы
смотрите название
#### Что должно было произойти
раунд закончился и размер чата остался тем же
#### Что произошло на самом деле
раунд закончился и размер чата не остался тем же
#### Как повторить
зайти на сервер,нажать рестарт,посмотреть на чат

**Comment by KIBORG04** [comment]
в префах отключи настройку растягивания экрана, fit че-то там

@4310V343k

**Comment by simb11** [comment]
ок
