### ISSUE TITLE
Space carps trying to kill mice

### ISSUE THREAD

**Issue by Rahmanio** [TauCetiStation/TauCetiClassic#7356]
#### Подробное описание проблемы
Карпы атакуют мышей и устраивают разгерметизацию.
#### Что должно было произойти
Нет агрессии на мышей.
#### Что произошло на самом деле
Мыши грифонят.
#### Как повторить
Зайти за мышь и подождать карпов.
#### Дополнительная информация:
Я бы написал это ишью ещё полгода назад, если бы не пара админов.

**Comment by volas** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/7189#issuecomment-854564523

У карпов как раз есть проверка на фракцию, если я правильно помню, и нужно просто дописать мышам.

**Comment by Rahmanio** [comment]
> У карпов как раз есть проверка на фракцию, если я правильно помню, и нужно просто дописать мышам.
Дописал мышам фракцию, ничего не изменилось, посмотрел в файл карпов, проверки на фракцию нет. Решил пойти дальше, попытался добавить агрессивным мобам запрет на атаку нейтральных существ. Тоже ничего. Сделал карпов, пауков, споры блоба  нейтральными, всё работает, но опять проблема, human тоже состоят во фракции нейтральной. Дописал людям фракцию station, так как у всех рас изначально нет фракции.
