### ISSUE TITLE
Навод курсора на лежачих персонажей

### ISSUE THREAD

**Issue by metroshnik** [TauCetiStation/TauCetiClassic#7361]
#### Как повторить у некоторых - админов точно такое есть, просто поиграть.
![изображение_2021-06-13_202749](https://user-images.githubusercontent.com/85842692/121816710-d28b6700-cc85-11eb-84e7-593349a2265c.png)

#### Дополнительная информация:
Issue reported from  Round ID: 42034 (Tau Ceti Classic II (RU))
Testmerges: ```No test merges```
Reporting client version: 514.1555

**Comment by 4310V343k** [comment]
514 бьонд?

**Comment by Sakuya-Izayoi** [comment]
> 514 бьонд?

в теле ишуя написано что да

**Comment by 4310V343k** [comment]
> > 514 бьонд?
> 
> в теле ишуя написано что да

Это было предположение, что виноват именно он, а не вопрос какой бьонд он использует

**Comment by Akellazp** [comment]
виновата скорее всего именно 1555 версия

**Comment by 4310V343k** [comment]
> виновата скорее всего именно 1555 версия

Ты прав. В 514.1556 уже пофикшено

https://i.imgur.com/cxHZxTJ.gif

**Comment by metroshnik** [comment]
пофикшено, благодарю.
