### ISSUE TITLE
Персонаж меняется местами с шаттлом

### ISSUE THREAD

**Issue by Rahmanio** [TauCetiStation/TauCetiClassic#7365]
#### Подробное описание проблемы
Если стоять на тайле, куда должен прибыть шаттл, вас отправит на то место, где он был до этого.
#### Что должно было произойти
Откинуть персонажа от шаттла, накинув брут урон.
#### Как повторить
Встать на место шаттла, перед его прилётом.
#### Дополнительная информация:
Давно стоило написать это ишью.

**Comment by Sakuya-Izayoi** [comment]
я и близко не смотрел в код шаттлов, но я припоминаю что с телепортом абудкторов была проблема, когда он менял местами людей из-за прока Move, возможно здесь такая же проблема.

**Comment by KIBORG04** [comment]
> Что должно было произойти
Откинуть персонажа от шаттла, накинув брут урон.

Должен быть гиб. А вообще, это довольно важная задача, которая уже пофикшена на всяких тогэ

**Comment by Rahmanio** [comment]
> > Что должно было произойти
> > Откинуть персонажа от шаттла, накинув брут урон.
> 
> Должен быть гиб. А вообще, это довольно важная задача, которая уже пофикшена на всяких тогэ

Хай приорити, а про баг знают уже давно 0_o

**Comment by Rahmanio** [comment]
> Должен быть гиб. А вообще, это довольно важная задача, которая уже пофикшена на всяких тогэ

Я потестил, гибает, но люди говорят что не всегда

**Comment by Rahmanio** [comment]
Вот доп информация от человека, раунд #42046, в конце эвак шаттл кота выкинул на цк.
![unknown](https://user-images.githubusercontent.com/67812445/121966298-0befcf80-cd77-11eb-82ed-f6166536195c.png)
