### ISSUE TITLE
Лишний сегмент трубы/провода. (будет дополняться)

### ISSUE THREAD

**Issue by Leshiy-ART** [TauCetiStation/TauCetiClassic#739]
Баг на карте. Лишняя мусорная труба.
![image](https://cloud.githubusercontent.com/assets/4739426/19968722/d5e821a0-a1e6-11e6-9e4d-2757c9e0c276.png)

**Comment by Leshiy-ART** [comment]
Остатки проводов в окне атмосферки.
![image](https://cloud.githubusercontent.com/assets/4739426/19975456/1686e898-a1fd-11e6-9ad8-2c25846cee64.png)

**Comment by Leshiy-ART** [comment]
Кусок провода в окне кабинета мозгоправа.
![image](https://cloud.githubusercontent.com/assets/4739426/19975559/7bf7015e-a1fd-11e6-9063-8f641e161dd8.png)

**Comment by Leshiy-ART** [comment]
Лишний провод в атмосе.
![image](https://cloud.githubusercontent.com/assets/4739426/19975961/f0c832b8-a1fe-11e6-9ae7-6f9e9d1988f7.png)

**Comment by Leshiy-ART** [comment]
Кто будет вносить правки - закройте пожалуйста ставнями окна заброшенного отсека.
(кнопку можно бросить где-нибудь в отсеке)
Проход прорубить из техтоннелей, сделать в стене дырку от термита.
А то этот срач у мостика в центральном коридоре - вообще не дело.
![image](https://cloud.githubusercontent.com/assets/4739426/19979148/794c5208-a20a-11e6-80db-95ce6575a6da.png)

**Comment by Leshiy-ART** [comment]
И поставьте туда атмосферный датчик...

**Comment by Leshiy-ART** [comment]
Уберите элитность и дайте людям место для приема пищи.
Сами перенесли бар и сказали что тут будет столовая, и сами же закрыли доступ большей части персонала. Нормально чтоу!
![image](https://cloud.githubusercontent.com/assets/4739426/19979478/abefccf2-a20b-11e6-8c55-9dace0ed7769.png)

**Comment by Dennok** [comment]
Так єтож суть. Оно только для ГЛАВ

**Comment by Leshiy-ART** [comment]
Идите стройте в другом месте элитные места для глав. Дайте людям пожрать нормально!

**Comment by Leshiy-ART** [comment]
Поправьте кривую зону. Внешняя зона не должна заходить в комнату.
Как-то вообще странно вышло тут.
![image](https://cloud.githubusercontent.com/assets/4739426/19981135/b32f7660-a211-11e6-8fc0-b6828e781aa5.png)

**Comment by StrikS** [comment]
Нужно что-то новое придумывать на счет столовки, ибо она была создана, чтобы вызывать зависть персонала и все такое, но даже во время рев ей почти не пользуются, что уж говорить о других режимах. Сейчас участок от мостика до поворской можно залить бетоном и никто этого даже не заметит (главное коробку с донк покетами вынести)
