### ISSUE TITLE
Баг с исчезающими наручниками Абдуктора

### ISSUE THREAD

**Issue by Krampuzzz** [TauCetiStation/TauCetiClassic#7392]
Доброго времени суток!

Играя за Абдуктора, обнаружил следующий баг - если взять из коробки с наручниками один экземпляр, переложить его в карман, а потом попробовать взять в руку, он исчезнет.
Порядок действий:
1. Берете в свободную руку наручники из коробки
2. Перекладываете их в свободный карман
3. Обратно перекладываете в свободную руку
  3.1 Также если данными наручниками попытаться воспользоваться по назначению - они исчезают

**Comment by simb11** [comment]
Зачем им вообще наручники...

**Comment by notkripton** [comment]
Для ерп кншн
