### ISSUE TITLE
Исчезающая кукла Абдуктора-агента

### ISSUE THREAD

**Issue by Krampuzzz** [TauCetiStation/TauCetiClassic#7393]
Доброго времени суток!

Обнаружил так баг(возможно фичу). Что при определенных действиях, кукла абдуктора полностью исчезает, на нее нельзя навестись курсором(Проверять через ПКМ на том тайле, где кукла стоит - не пробовал).
Алгоритм действий:
1. Необходимо заполучить облик любой куклы
2. Взять в руки небольшой предмет, который можно будет поместить на пояс(Например пистолет абдуктора)
3. Применить маскировку, чтобы абдуктор изменил облик на члена экипажа
4. Перетащить предмет из руки на пояс
После этого моделька абдуктора полностью исчезает. На нее нельзя навестись курсором. Но при этом кукла может спокойно перемещаться. Выдает куклу только висящие на поясе предметы.

**Comment by KIBORG04** [comment]
1. Оформлено не по шаблону
2. А ведь кто-то реально думает что это не баг

**Comment by 4310V343k** [comment]
Не баг и дубликат...
