### ISSUE TITLE
2 королевы аленей

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#7397]
#### Подробное описание проблемы
В раунде #42127 было 2 королевы
#### Что должно было произойти
Может быть только 1 королева
#### Что произошло на самом деле
Было 2 королевы
#### Как повторить
Фиг его знает, скорей всего за трутней одновременно прожать эволюцию
#### Дополнительная информация:
Номер раунда #42127

**Comment by Phoenix4O4** [comment]
Аленей нет в билде. Проблема решена.

**Comment by KIBORG04** [comment]
думаю пофикшено
