### ISSUE TITLE
Из-за длинных имен скреллов и прочих нелюдей кнопка «DM» в крюманифесте все равно делает две строчки

### ISSUE THREAD

**Issue by logimy** [TauCetiStation/TauCetiClassic#7408]
#### Подробное описание проблемы
В заголовке ишью

#### Что должно было произойти
Я должен был это поправить еще в первом фиксе, но что-то забыл о ксеносах. Ряды персонала в кру манифесте в пда должны быть в одну строку

#### Что произошло на самом деле
О ксеносах забыли. Теперь своими именами они ломают удобство ПДА

#### Как повторить
Дождаться ксеноса и заглянуть в круманифест, или сделать себе натужно большой ступиднейм

#### Дополнительная информация:
Я исправлю завтра. Ишью чтоб не забыть

**Comment by Sakuya-Izayoi** [comment]
я думаю можно удалить ксеносов

**Comment by logimy** [comment]
> я думаю можно удалить ксеносов

СПУ Антон не оценил вашу шутку.

**Comment by BeebBeebBoob** [comment]
Скоро Скреллы придумают в три строчки XD.

**Comment by logimy** [comment]
> Скоро Скреллы придумают в три строчки XD.

Я сделаю так, чтоб кнопка ваще не создавала новую строку
