### ISSUE TITLE
Дабл есворд кнокает через броню

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7410]
#### Подробное описание проблемы
Десворд кнокает даже если вы носите броню хоса,риот
#### Что должно было произойти
Риот броня защищает от десворда
#### Что произошло на самом деле
Хос сосет от одного удара меча
#### Как повторить
Взять броню с высокой защитой от мили и ударить себя десвордом

**Comment by Sakuya-Izayoi** [comment]
Я не знаю точно но мне кажется есворды бьют энерджи а не мили (мили это про молотки, топоры и ножи, наверное)

**Comment by Gort133** [comment]
Не забывайте что у татора этот есворд забрать могут и кнокнуть уже его самого в броне татарской #все_равны

**Comment by Sakuya-Izayoi** [comment]
Я думаю проблема не в таторах, а в нюкерах, которые под адреналом нероняемые.

**Comment by Gort133** [comment]
Зимнонюкеры тоже страдают от флешбенг+кнок есвордом  тактики

**Comment by Pivo24** [comment]
> Зимнонюкеры тоже страдают от флешбенг+кнок есвордом тактики

Не страдают

Проверь нюкерский боевой комплект+ Адреналин, кинув под себя флешбенг, на песочнице

**Comment by ChewedGum** [comment]
Помню времена когда на триторе попытался навалять хосу, прокат на мыле и 15 ударов ему по башке, он даже не почуствовал... Дааа... Вот ведь здорово было, балансово главное.

**Comment by WallShrabnic** [comment]
Дубинка СБ кнокает сквозь броню за два удара и ещё накидывает тонну голодамага. 

Это какая-то форма шизофрении, да?
