### ISSUE TITLE
Ломается бинт чата "T" при начале новой смены и иногда в течении смены.

### ISSUE THREAD

**Issue by weedmoon42** [TauCetiStation/TauCetiClassic#7411]
#### Подробное описание проблемы
После начала новой смены стабильно перестает работать хоткей чата "t" и приходится перезаходить, иногда он ломается случайно во время смены.
#### Что должно было произойти
-
#### Что произошло на самом деле
-
#### Как повторить
-
#### Дополнительная информация:
Баг появился недели полторы-две назад после введения кастомных хоткеев.

**Comment by logimy** [comment]
Уже есть пр на фикс, один момент

**Comment by kalazus** [comment]
Мержить не будут (как минимум 1 мейнтейнер) из-за того что пинг будет влиять на появления окна ввода. Так что проблема остаётся актуальной.

**Comment by volas** [comment]
Закрою в пользу #7303
