### ISSUE TITLE
Нельзя менять руки (модули) у боргов при помощи хоткеев

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7415]
#### Подробное описание проблемы
Нельзя менять модули при помощи хоткеев(z или x,не помню точно)
#### Что должно было произойти
Можно
#### Что произошло на самом деле
Нельзя
#### Как повторить
Взять в слот рук 2-3 вещи и попытаться поменять руки через хоткеи
#### Дополнительная информация:
Хоткеи киборга наверное сломали

**Comment by Ro2tCrab** [comment]
Фиксится сбросом хоткеев.
