### ISSUE TITLE
Беды со стрэйфом у меха

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#7419]
#### Подробное описание проблемы
Когда мех смотрит вниз в режиме стрейфа и после этого стрейф отключается, то мех идет вниз, если зажать клавишу вверх
#### Что должно было произойти
Мех должен идти вверх 
#### Что произошло на самом деле
Мех идет вниз
#### Как повторить
1) Залезть в меха
2) Заставить его повернуться на юг
3) Включить стрейф
4) Немного пройтись вверх и отключить стрейв
5) Зажать клавишу вперед
6) ...
7) Profit! Он пошел вниз
#### Дополнительная информация:
Test merged PRs: #7346 #6985

**Comment by KIBORG04** [comment]
#7346
