### ISSUE TITLE
Банковский аккаунт персонажа создан до его рождения

### ISSUE THREAD

**Issue by MrBite** [TauCetiStation/TauCetiClassic#7426]
#### Подробное описание проблемы
Если создать СПУ и поставить ему небольшой возраст,а потом глянуть в IC->Notes,то мы обнаружим что наш банковский аккаунт был создан до нашего "рождения"
#### Что должно было произойти
Видим реалистичную дату
#### Что произошло на самом деле
Не видим реалистичную дату
#### Как повторить
Создать СПУ с небольшим возрастом,зайти в раунд и глянуть в IC->Notes
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/84805922/122779754-db4bf080-d2b6-11eb-8f40-18cf5fcc557e.png)
![image](https://user-images.githubusercontent.com/84805922/122779906-00d8fa00-d2b7-11eb-9f66-1653ae30b08d.png)
![image](https://user-images.githubusercontent.com/84805922/122779785-e3a42b80-d2b6-11eb-80a7-7145241ed94a.png)

**Comment by Zmey25** [comment]
Сборку спу начинают с создания банковского акка
