### ISSUE TITLE
"Setup Character" закрывает собой окно входа в игру

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#743]
#### Подробное описание проблемы
Керектер Сетап нельзя двигать и изменять в размерах. Это чревато блокированием как Сетапа, так и окошка входа в игру.
Т.е. мы одновременно нажимаем на Деплой Реди и Сетап Керектер. Сетап керектер нельзя закрыть из-за деплоя, а отмену деплоя закрывает окно настройки персонажа.
#### Что должно было произойти
Окно настройки персонажа не закрывает окно входа в игру / окно можно двигать, изменять в размерах / деплой рэди не блокирует окно настройки.
#### Что произошло на самом деле
Окно настройки персонажа заблокировалось, деплой снять нельзя, сетап закрыть нельзя.
#### Как повторить
Одновременно нажать нажать на "Setup Character" и "Deploy Ready".
#### Дополнительная информация:
Лечится перезаходом на сервер.

**Comment by WallShrabnic** [comment]
Это фича

**Comment by Skyrull** [comment]
Семерка

**Comment by Raschert0** [comment]
Кстати, двигать его можно, но из-за его высоты на некоторых экранах это сделать проблематично
