### ISSUE TITLE
ИИ не вайпается.

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#744]
#### Подробное описание проблемы
При попытке выйти за ИИ из раунда посредством "Wipe Core" во вкладке ООС, проходит сообщение но ничего не происходит.
#### Что должно было произойти
Игрок должен был выйти из ИИ тем самым что бы другой игрок мог занять его место при желании.
#### Что произошло на самом деле
Появляются только сообщения. Выйти из ИИ невозможно без гостанья.
#### Как повторить
За ИИ попробовать вайпнуться.
#### Дополнительная информация:
http://imgur.com/XTtJqRF

**Comment by WallShrabnic** [comment]
Это древний пофикшенный и затем сломанный баг автотритора
