### ISSUE TITLE
Не работает кнопка "Eject" в стак-машине ресурсов.

### ISSUE THREAD

**Issue by Kyler2262** [TauCetiStation/TauCetiClassic#7443]
#### Подробное описание проблемы
В стак-машине ресурсов не работает кнопка eject

#### Что должно было произойти
При нажатии на Eject можно забрать ресурсы

#### Что произошло на самом деле
РЕСУРСЫ ЗАСТРЯЯЯЛИИИ ААААААА

#### Как повторить
Добыть ресурсы, переплавить, и расстроиться. 

#### Дополнительная информация:
Issue reported from  Round ID: 42326 (Tau Ceti Classic (RU))
Testmerges: ```#7381 ```
Reporting client version: 513.1542

**Comment by KIBORG04** [comment]
#7381

**Comment by BeebBeebBoob** [comment]
Есть обход ставить самому во сколько должен быть стаки. Ну например 12 алмазов и 23 урана и 40 серебра. Сперва 40 печатаем -> Выдаёт только 40 серебра. потом 23 урана и т.д. Неприятный обход кнопки Eject.

**Comment by T6751** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/7381/commits/ae12703fb514d5f9d02a05af5f63d2f7face3aef
