### ISSUE TITLE
Не соответствие названия представителя фауны действительности.

### ISSUE THREAD

**Issue by Ruumyn** [TauCetiStation/TauCetiClassic#7450]
#### Подробное описание проблемы

Последнее время все чаще натыкаюсь на представителей фауны на астероиде, у которых в названии есть, например Angelic Friendly Goliaf, но при этом есть признаки другого трейта на нем, например вокруг него трясется земля, как будто он еще и Strong. В итоге ты игнорируешь моба, считая что он не враждебный, а он атакует тебя. И получается, что это Angelic Strong Goliaf. Пока что замечал ложное описание только про трейт Friendly, надеюсь это не специально внедренная механика.

#### Что должно было произойти

В Названии Моба, вместо Friendly, должен быть соответствующий трейт

#### Что произошло на самом деле

Моб скрывает свою истинную силу, под видом дружелюбия ( i am friendly).

#### Как повторить

Найти подобного моба на астероиде и навести курсор, затем проверить на дружелюбность.

**Comment by KIBORG04** [comment]
Походу недавний пр с изменением фракций все сломал. @Rahmanio ты вроде кодил, фиксь!!!!!!!!!!

**Comment by Sakuya-Izayoi** [comment]
в названии моба максимум два трейта показывается. если проэкзамайнить и навести мышкой на название, то видно все трейты

**Comment by Ruumyn** [comment]
Суть не в этом, а в том, что трейт friendly не работает

**Comment by kalazus** [comment]
Вроде Голиаф бьёт щупальцами даже если он дружелюбный, может про это баг?

**Comment by KIBORG04** [comment]
Возможно я зря человека слапнул

**Comment by Ruumyn** [comment]
Я голиафа только в пример привел, и нет, на меня нападал friendly голиаф и отгрызал мне голову, также нападал и Friendly Василиск

**Comment by BeebBeebBoob** [comment]
Либо ток friendly сломался. Либо ты его "разозлил"(что? сам того не знаю).

**Comment by 4310V343k** [comment]
![image](https://user-images.githubusercontent.com/56449763/123494564-f0af7a80-d628-11eb-9e6a-d2845d43c4f4.png)

**Comment by Rahmanio** [comment]
> Походу недавний пр с изменением фракций все сломал. @Rahmanio ты вроде кодил, фиксь!!!!!!!!!!

Извиняюсь за долгое отсутствие активности, гитхаб не дал уведомлений, никаких. Вроде всё зафиксил.
