### ISSUE TITLE
перевод анонсов некрасивый

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#7451]
![image](https://user-images.githubusercontent.com/44546836/123483493-758d9a80-d60f-11eb-92e7-77e89b376876.png)
>мыши размножается
>вычистите это, пока не начало влиять (???)

**Comment by AndroBetel** [comment]
![image](https://user-images.githubusercontent.com/44546836/123485324-8ee41600-d612-11eb-9586-ddc0c73a25bc.png)

**Comment by AndroBetel** [comment]
![image](https://user-images.githubusercontent.com/44546836/123485356-a0c5b900-d612-11eb-9070-29b07e718e03.png)
lllllllllllllllllet's get ready to RUMBLE!!!

**Comment by 4310V343k** [comment]
Вот именно про это я и говорил

**Comment by KIBORG04** [comment]
Да подпилить пару анноунсов и все будет нормально

**Comment by TechCatOther** [comment]
Всегда можете поправить их через ПР

**Comment by BeebBeebBoob** [comment]
может всё дело в шрифте? Довольно таки он старомодный.(про чёрную надпись)
