### ISSUE TITLE
Ошибка Dream Seeker при использовании Production Machine Console на Шахтёрской станции

### ISSUE THREAD

**Issue by PersyFOX** [TauCetiStation/TauCetiClassic#7453]
#### Подробное описание проблемы
При открытии Production Machine Console на Шахтёрской станции вылезает ошибка и вылетает вся игра
#### Что должно было произойти
Открыться консоль продукции
#### Что произошло на самом деле
Вылезает ошибка о прекращение работы Dream Seeker
#### Как повторить
-
#### Дополнительная информация:
![Баг 2](https://user-images.githubusercontent.com/86224151/123502503-9678de80-d655-11eb-96bb-d1cc2025ac6c.png)

**Comment by volas** [comment]
Какая версия byond-а используется?

**Comment by PersyFOX** [comment]
> Какая версия byond-а используется?

В свойствах написано - 5.0.514.1557 (5.0 Beta)

**Comment by volas** [comment]
Попробуй откатись до стабильной 513, если ты не играешь на других серверах где бы требовалась бета. Бета на то и бета, что с ней могут быть проблемы, и мы всё еще далеки от неё.

**Comment by PersyFOX** [comment]
> Попробуй откатись до стабильной 513, если ты не играешь на других серверах где бы требовалась бета. Бета на то и бета, что с ней могут быть проблемы, и мы всё еще далеки от неё.

Можно узнать как откатить? Может ссылка на версию?

**Comment by PersyFOX** [comment]
> Попробуй откатись до стабильной 513, если ты не играешь на других серверах где бы требовалась бета. Бета на то и бета, что с ней могут быть проблемы, и мы всё еще далеки от неё.

Хотя уже понял сам

**Comment by PersyFOX** [comment]
Спасибо, проблема решена

**Comment by PersyFOX** [comment]
Странно...ошибка снова...было же вс нормально в первые минуты игры после того как сошёл с Беты

**Comment by T6751** [comment]
Возможно это как-то связано с #7381, который сейчас в тестмерже

**Comment by T6751** [comment]
На всякий случай, можешь сказать айди раунда, когда такое произошло?

**Comment by PersyFOX** [comment]
> На всякий случай, можешь сказать айди раунда, когда такое произошло?

ID #42394 Ну это вообще на всех играх у меня. У меня частые проблемы с интерфейсами, не знаю в чём причина

**Comment by T6751** [comment]
` с интерфейсами`

Только с интерфейсами на тгуи (те, у которых глазик вверху слева)?

**Comment by PersyFOX** [comment]
> ` с интерфейсами`
> 
> Проблемы только с интерфейсами на тгуи (те, у которых глазик вверху слева)?

Ну вроде бы да. Но вот ещё одна моя проблема с интейрфейсом #7423

**Comment by volas** [comment]
Попробуй посмотреть по предложениям из F.A.Q. https://forum.taucetistation.org/t/f-a-q-tehnicheskie-problemy-i-sposoby-resheniya/7864

**Comment by T6751** [comment]
> Решил проблему сам обновлением Internet Explorer до 11 версии

Так понимаю, что эта проблема также решена обновлением IE

**Comment by PersyFOX** [comment]
> > Решил проблему сам обновлением Internet Explorer до 11 версии
> 
> Так понимаю, что эта проблема также решена обновлением IE

Да
