### ISSUE TITLE
ИИ не видит две двери на шахтерском аванпосту

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#7455]
#### Подробное описание проблемы
Ии не видит две двери
![image](https://user-images.githubusercontent.com/61596681/123510917-d6a48500-d686-11eb-9813-9e69bdf58b58.png)
#### Что должно было произойти
Он видит всю шахтерку
#### Что произошло на самом деле
Я не могу нормально украсть гитару у шахтерки, т.к. ИИ не может открыть две двери
#### Как повторить
1) Зайти за ИИ
2) Попробовать открыть две двери на картинке
#### Дополнительная информация:
 Ƹ̵̡Ӝ̵̨̄Ʒ

**Comment by Tiarv** [comment]
Они появляются на камере если сначала открыть дверь в медпункт. Может, считать, что фича?

**Comment by 4310V343k** [comment]
Дверь прозрачная...
