### ISSUE TITLE
Из смирительной рубашки нельзя выбраться

### ISSUE THREAD

**Issue by notkripton** [TauCetiStation/TauCetiClassic#7466]
#### Подробное описание проблемы
Из смирительной рубахи нельзя выбраться резистом
#### Что должно было произойти
Нажимаешь резист и происходит прогресс бар как с наручниками.
#### Что произошло на самом деле
При нажатии резиста ничего не происходит
#### Как повторить
Нацепить на себя рубаху и пожмякать резист

**Comment by Dominig12** [comment]
На то это и смирительная рубашка

**Comment by Gort133** [comment]
Не, ну если это будет прогресс бар на 30 минут... 
Может за 30 минут и можно...

**Comment by LudwigVonChesterfield** [comment]
если дать возможность выбираться из рубашки то большую часть ролек на которых надевали эти рубашки будут стрелять на месте

**Comment by notkripton** [comment]
> если дать возможность выбираться из рубашки то большую часть ролек на которых надевали эти рубашки будут стрелять на месте

Пхахыхха. Мне интересно как ты себе это представляешь. Мало того, что у врачей априори не должно быть пушек, так ведь из наручников тоже можно выбраться. Что-то не видел как офицеры убивали зеков под предлогом того, что из наручников можно выбраться.

> Не, ну если это будет прогресс бар на 30 минут...
> Может за 30 минут и можно...
> 
> Психбольного в твит. Требуется знаток

Из наручников ты в реале тоже не вылезешь за три минуты. Либо ломай палец, либо час пили об что-то острое.
