### ISSUE TITLE
Не всегда работает пулл

### ISSUE THREAD

**Issue by notkripton** [TauCetiStation/TauCetiClassic#7468]
**UPD: это уже починили поэтому ищуй закрывается.**

#### Подробное описание проблемы
Пишу ишуй за человека с форума (https://forum.taucetistation.org/t/perestal-rabotat-pul/26347). Сам сталкивался с такой проблемой, но уже со шкафчиком. Какой-то из пров походу что-то сломал.
#### Что должно было произойти
Пулл работает
#### Что произошло на самом деле
Пулл не работает
#### Как повторить
Хз, я закономерностей пока не видел, но бывает, что багается.

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/perestal-rabotat-pul/26347/10
