### ISSUE TITLE
Эвакуационный шаттл озверел и сбросил таймер до 1 часа

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#7480]
#### Подробное описание проблемы
Шаттл сбросил таймер до одного часа
#### Что должно было произойти
Должно пройти 3 минуты и он улетает
#### Что произошло на самом деле
Шаттл хотел сидеть на станции 1 час
#### Как повторить
Неизвестно, в доп. инфе прикреплен айди раунда
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/61596681/123884919-07214300-d955-11eb-99fc-81a80701d451.png)

**Comment by T6751** [comment]
Это произошло в 03:00 по серверному времени, да?
![image](https://user-images.githubusercontent.com/66636084/123886680-a6940500-d958-11eb-9ec0-56149d208cc8.png)

**Comment by Daoprotoss** [comment]
> Это произошло в 03:00 по серверному времени, да?
> ![image](https://user-images.githubusercontent.com/66636084/123886680-a6940500-d958-11eb-9ec0-56149d208cc8.png)

Честно не знаю
