### ISSUE TITLE
[Bug] Игрок может продолжать играть за рассы на которые имеет бан

### ISSUE THREAD

**Issue by Dushess0** [TauCetiStation/TauCetiClassic#7486]
#### Подробное описание проблемы
Можно играть за рассы на которые имеешь бан, если имеешь сохраненную куклу с этой рассой. 
#### Что должно было произойти
Я смог зайти в раунд за диону, хотя имею бан на них.
#### Что произошло на самом деле
Я не должен был зайти в раунд, должно было бы написать что у меня нету возможности играть за эту рассу.
#### Как повторить
До момента получения бана создать куклу с нужной рассой и сохранить ее. Получить бан. Не изменять/удалять куклу и просто зайти зайти в раунд как обычно.
#### Дополнительная информация:
Думаю что стоить добавить проверку в начале раунда, может ли игрок играть за эту рассу или в моменте получения бана удалять сохраненные куклы с данной рассой.
_P.S. Не баньте плиз за то что тестил это_

**Comment by Tolerantboy** [comment]
Мне кажется лучше не удалять, а просто запретить. А то вдруг у игрока там километры наратива в записях и флаворе, и всё это потрётся, жалко

**Comment by Dushess0** [comment]
Пофиксили

**Comment by Dushess0** [comment]
Пофиксили
