### ISSUE TITLE
Нельзя вставлять карты в ПДА

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7487]
#### Подробное описание проблемы
нельзя вставить айди карту в ПДА(ручку можно)
#### Что должно было произойти
Карта вставляется без проблем
#### Что произошло на самом деле
ничего
#### Как повторить
зайти на сервер,попытаться засунуть айди карту в пда
#### Дополнительная информация:
42554
тау сети 1

**Comment by KIBORG04** [comment]
Попробуй ещё раз, у тебя обязательно получится

**Comment by T6751** [comment]
#7406
