### ISSUE TITLE
Неправильное направление у окон шаттла отбытия

### ISSUE THREAD

**Issue by YulianR** [TauCetiStation/TauCetiClassic#751]
![dreamseeker_2016-11-05_14-26-15](https://cloud.githubusercontent.com/assets/6051766/20030001/83a49ab6-a364-11e6-9f4d-2294cdccd487.png)

**Comment by YulianR** [comment]
![dreamseeker_2016-11-10_20-28-05](https://cloud.githubusercontent.com/assets/6051766/20189079/4db29db2-a784-11e6-8adc-d7f6eaa9fedd.png)

**Comment by Skippeer12** [comment]
Там же ишьус есть про ковер!

**Comment by YulianR** [comment]
![dreamseeker_2016-11-10_20-28-05](https://cloud.githubusercontent.com/assets/6051766/20189233/f3a51bc8-a784-11e6-9bc9-170bd8d736a7.png)
