### ISSUE TITLE
[Proposal] Поменять местами медпункт и комнату детектива.

### ISSUE THREAD

**Issue by BeebBeebBoob** [TauCetiStation/TauCetiClassic#7516]
#### Подробное описание проблемы
Я считаю что медпункт который сбоку от кабинета АВД редко используется. Под редко имею в виду почти никогда.
Я думаю что это связано с тем что он не так близок к основному коридору и его мало кто либо знает. Будто это тех туннели которые закрыты для прохода. Если вот передвинуть ближе к бригу или поменять местами АВД кабинетом то может люди в том числе и медики будут сюда заходить место того чтобы пялить в мед отдел.

#### Дополнительная информация:
Нету?

**Comment by Motzord** [comment]
Он не используется потому что там мало медикаментов, уж проще будет перемотать и долечивать в меде, чем тащить в этот бесполезный сарай с двумя мембранками и пакетом

**Comment by Haggerd** [comment]
Просто он нужен в критических ситуациях, при отсутствии доступа к меду.

**Comment by Artik12344** [comment]
Если бы ещё доступ дали туда..
