### ISSUE TITLE
Баги аирлочных светяшек

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#752]
#### Подробное описание проблемы
Светяшки горят там, где гореть не должны.
#### Что должно было произойти
Лампочки горят там, где нужно.
#### Что произошло на самом деле
Лампочки горят не там, где нужно.
#### Как повторить
Найти шлюзы, поставить на них болты, смотреть.
#### Дополнительная информация:

![lampidermo](https://cloud.githubusercontent.com/assets/20542000/20030159/8295aea6-a389-11e6-9600-a60b8813c28d.png)
![scr2](https://cloud.githubusercontent.com/assets/20542000/20030161/859e3abe-a389-11e6-9fa4-148cab7b3fc6.png)
![scr3](https://cloud.githubusercontent.com/assets/20542000/20030163/87abf5b2-a389-11e6-985b-f04833c3366f.png)
![scr4](https://cloud.githubusercontent.com/assets/20542000/20030188/057e3b6c-a38a-11e6-8156-a070674770b6.png)

**Comment by Damirrus1** [comment]
oh niet, вот с ксенобиологией ето да

**Comment by Dennok** [comment]
Там не только у ксено а везде где шлюзы.
