### ISSUE TITLE
Сингулярити бастер ломается при броске

### ISSUE THREAD

**Issue by 4310V343k** [TauCetiStation/TauCetiClassic#7521]
#### Подробное описание проблемы
![](https://i.imgur.com/e2VbaUY.gif)
#### Что должно было произойти
Офф-хенд делитается, как и везде
#### Что произошло на самом деле
Офф-хенд остаётся в офф-хенде
#### Как повторить
Взять бастер в две руки, кинуть мейнхенд

**Comment by KIBORG04** [comment]
На тг есть компонента двуручности оружия. Ее портирование фиксит это баг, да и не только его
