### ISSUE TITLE
Рантайм на мафии

### ISSUE THREAD

**Issue by Artik12344** [TauCetiStation/TauCetiClassic#7522]
#### Подробное описание проблемы
Играли в мафию, и тут появилась дасти, которая заявила что произошла аномалия #138 
#### Что должно было произойти 
Наверно никаких рантаймов не должно было быть
#### Что произошло на самом деле
какие то рантаймы произошли
#### Как повторить
Неизвестно
#### Дополнительная информация:
произошло под конец раунда 42635

**Comment by 4310V343k** [comment]
Эх, вот бы узнать, что за аномалия там была...

**Comment by Artik12344** [comment]
13:03 раунд 42636, опять кот, только теперь ещё и вот это
![image](https://user-images.githubusercontent.com/48361107/124454949-b31dc080-dd91-11eb-8e8c-5ae34746a861.png)

**Comment by Artik12344** [comment]
раунд 42636 13:08 вновь кот в мафии

**Comment by Artik12344** [comment]
раунд 42636 13:21 кот в мафии ещё один
