### ISSUE TITLE
Обджектив на мафиозника

### ISSUE THREAD

**Issue by NeOchenLord** [TauCetiStation/TauCetiClassic#7529]
#### Подробное описание проблемы

Антагам стали выпадать задания на игроков в мафию, которую недавно так любезно портировал Киборг

#### Что должно было произойти

Антагам выпадают роли только на реальный экипаж

#### Что произошло на самом деле

Антагу выдало роль на игрока в мафию

#### Как повторить

Получить роль в середине раунда, как раз в тот момент когда в процессе сессия мафии

**Comment by 4310V343k** [comment]
:joypain:

**Comment by Haggerd** [comment]
Всё ок, это задача в гоустомире от самого Нар-Си
