### ISSUE TITLE
Дасти, аномалия #1515

### ISSUE THREAD

**Issue by Haggerd** [TauCetiStation/TauCetiClassic#7538]
#### Подробное описание проблемы
Дрон что-то делал с АПЦ, выскочил Дасти.
![Screenshot_2](https://user-images.githubusercontent.com/9301475/124627655-6a94fe80-de88-11eb-80b6-70b6c77764ac.png)
![Screenshot_4](https://user-images.githubusercontent.com/9301475/124627666-6b2d9500-de88-11eb-9986-3650781f464c.png)

#### Что должно было произойти
Дасти не должен выпрыгивать
#### Что произошло на самом деле
Дасти выпрыгнул
#### Как повторить
Пошаманить с АПЦ будучи дроном
#### Дополнительная информация:

```
[17:37:15] parent_preqdeleted overridden. Use override = TRUE to suppress this warning in unsorted.dm:1515 :
proc name: stack trace (/proc/stack_trace)
  source file: unsorted.dm,1515
```

**Comment by T6751** [comment]
> parent_preqdeleted overridden. Use override = TRUE to suppress this warning in unsorted.dm:1515 :
proc name: stack trace (/proc/stack_trace)
  source file: unsorted.dm,1515
  
Данный рантайм больше не актуален после #7530
