### ISSUE TITLE
Каргошаттл

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#754]
#696 
В общем, как писал Вальтер - и реализация не очень, и версия не та. Нужно либо допиливать, либо откатывать и допиливать (на сервере в данный момент откатил).
Рандомные скрины с обсуждения
https://i.gyazo.com/ca40043426c4de2bc7b7dfd661cf737c.png (кривые плитки)
https://i.gyazo.com/6f4ebe3e9f8debc9588135b4458eb57e.png (нужны всё же костыли в виде стен-объектов, или какой-то автоматизированный костыль, нужно глянуть Бэй/ТГ - у нас шаттлы давно отстали по реализации)
https://tauceti.slack.com/files/igigil/F2ZEEVBCP/pasted_image_at_2016_11_05_17_42.png

**Comment by Raschert0** [comment]
У ТГ с шатолами всё совсем иначе. Туда если и смотреть, то только с планами на полный перепил наших.

**Comment by volas** [comment]
На Бэй тоже сильно переделывали. Но вообще да, можно оставить на потом, пока пожить так.

**Comment by Kurshan** [comment]
Многотурфные передвигающиеся шаттлы плохая затея, прошлая реализация была получше. confirmed. @SpaiR

**Comment by SpaiR** [comment]
@Kurshan О том, что турфы не могут в нормальное перемещение шаттлосистемой я не знал. Когда я у тебя спросил почему стены не турфы, а объекты ты невнятно ответил, что типа поды такие, ну и как бы вот. Если бы мне сразу сказали, что, дескать, тут у нас говно нерабочее и только вот так вот и можно, я бы и слова больше на эту тему не сказал.
И прошлый вариант суть не реализация, а костыль, как не крути.

**Comment by volas** [comment]
Могли бы в рамках ПРа обсуждать, я бы сказал :confused:

**Comment by volas** [comment]
#786
