### ISSUE TITLE
[Proposal]убрать возможность строить шлюзы на спутнике

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7541]
#### Подробное описание проблемы
В данный момент тактика застройки спутника шлюзами - самая имбовая,через такую сеть дверей нужно идти к ядру минимум минут 5,из-за чего в 80% случаев экипаж проигрывает

**Comment by Zmey25** [comment]
А откуда статистика? Я вот уже много лет хочу статистику режимов, но не могу найти нигде.
А шлюзы можно ломать за 5 секунд. То, что экипаж оказался менее опытным, чем ИИ не означает, что нужно нерфить двери.

**Comment by BeebBeebBoob** [comment]
РЦД в помощь.
