### ISSUE TITLE
[Буг] Засчитались цельки, которые не должны были

### ISSUE THREAD

**Issue by notkripton** [TauCetiStation/TauCetiClassic#7551]
#### Подробное описание проблемы
Раунд #42694 
Играю себе на ГП, пиздохаю реверов, как вдруг в титрах написано, что цель на конверт/убийство меня сацессфул. К концу раунда я был жив и спокойно летел на шаттле, в реве не состоял (не было ни худа над головой, ни целек в нотесах). Стелсконверт исключен. А под конец я вообще кольнулся лояльностью во славу НТ, так что это вообще магия какая-то.
![Снимок экрана (194)](https://user-images.githubusercontent.com/75007994/124805373-152e1f80-df64-11eb-9152-2095ca91b5c4.png)

#### Что должно было произойти
Целька не засчиталась
#### Что произошло на самом деле
Целька засчиталась
#### Как повторить
Хз
#### Дополнительная информация:
Раунд веселый вышел, кстати.

**Comment by KIBORG04** [comment]
> exile from station.

> летел на шаттле
