### ISSUE TITLE
После становления треллом не пропадает имплант лояльности

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7555]
#### Подробное описание проблемы
Если законвертить человека с имплантом - имплант остаётся на своем месте
#### Что должно было произойти
Имплант пропал
#### Что произошло на самом деле
Имплант лояльности остался
#### Как повторить
Стать шедоу,попытаться затреллить человека с имплантом
#### Дополнительная информация:
мб и с защитой разума такое самое.
раунд 42712 тау сети 1

**Comment by ssbugman** [comment]
Майндшилд удаляется. А вот про имплант лояльности забыли.

**Comment by KIBORG04** [comment]
Да вроде должен исчезать

**Comment by KIBORG04** [comment]
Номер раунда оставьте
