### ISSUE TITLE
Можно смотреть Guard без +BAN

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#7556]
#### Подробное описание проблемы
В ВВ можно посмотреть отчет по гарду без +бана

#### Что должно было произойти
Нет доступа к отчету без +бана

#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/30875884/124927233-1401fe80-e007-11eb-9749-a8c7b2c89ca2.png)

#### Как повторить
Открыть в ВВ клиента, в нем найти гард.

**Comment by volas** [comment]
Он там скрыт за R_LOG, который у тебя есть как у ксеновизора

**Comment by Sakuya-Izayoi** [comment]
![image](https://user-images.githubusercontent.com/30875884/124928734-8cb58a80-e008-11eb-95ec-3365f2ca6fa0.png)

**Comment by volas** [comment]
У тебя и так эта информация будет с логов, потому что у тебя есть доступ. Но можешь предложить Снейлу оторвать у всех ксеновизоров этот флаг, я не буду против.
