### ISSUE TITLE
[Proposal] Спидран в стиле воксов.

### ISSUE THREAD

**Issue by BeebBeebBoob** [TauCetiStation/TauCetiClassic#7562]
#### Подробное описание проблемы
Думаю не впервые такое происходит когда режим воксов и воксы тупо начинают спидран. (Типо задания стырить кого-то или стырить что-то из инж отдела и проворачивают это как если их ждёт там еда и у них она остывают)
ПРЕДЛОЖЕНИЕ: Либо увеличить минимальное количество задании либо переделать режим например воксы должны стырить на какую-ту сумму из станции (Живой человек например стоит 1000 и надо своровать на минимум 5000 очков что-то в этом духе).

#### Дополнительная информация:
Раунд воксов примерно 5 минут проходит и потом титры кек

**Comment by 4310V343k** [comment]
Верните пиратов!1

**Comment by Pimap3** [comment]
А если воксов убивает СБ, то экста на полтора часа ;P

**Comment by Venngedi** [comment]
#9173
