### ISSUE TITLE
мафия и дионы которые не умирают.

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7563]
#### Подробное описание проблемы
в мафию могут зайти дионы,которые после своей смерти становятся нимфами.
#### Что должно было произойти
дионы умерли и ничего не могут сделать
#### Что произошло на самом деле
дионы становятся нимфами и всё также могут играть
#### Как повторить
зайти в мафию за диону

**Comment by KIBORG04** [comment]
Ты уверен, что это так? Я фиксил уже это и при смерти никто не должен заспауниьться

**Comment by simb11** [comment]
пару дней назад тестил,наверное и правда фиксанули.
