### ISSUE TITLE
нету панели мафии

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7564]
#### Подробное описание проблемы
нету панельки с голосованием,ролями и прочим в мафии.
#### Что должно было произойти
панель есть
#### Что произошло на самом деле
панели нету,даже екшн кнопки
#### Как повторить
зайти в мафию
#### Дополнительная информация:
раунд 42720

**Comment by KIBORG04** [comment]
Вроде пофиксил

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/7483/commits/3917e458c765d4a5e10bedb10827510fbd6a9156
