### ISSUE TITLE
Рева до сих пор не дает вызывать шатол

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#7567]
#### Подробное описание проблемы
Пока глава или главрева жил (или находится на слое станции), шатол не вызывается из-за чего главам/главревам приходится умирать/убегать на другой слой/роскомнадзорится/etc
#### Что должно было произойти
Крю трансфер вполне спокойно летит на станцию, у космонавтов не горит жопа и не появляется стремление выпилить глав, чтобы это все закончилось
#### Что произошло на самом деле
У меня появилось не только желание убить глав, но и удалить бйонд
#### Как повторить
Поиграйте в реву, с живучими главами и живучими главревами

**Comment by Sakuya-Izayoi** [comment]
Бэд ишью дескрипешен

**Comment by Motzord** [comment]
> Бэд ишью дескрипешен

что не так?

**Comment by volas** [comment]
Если шаттл с консоли - не баг, а пропозал. Если шаттл с воута - баг. Укажи конкретнее суть проблемы.

**Comment by volas** [comment]
Информации нет, закрываю.
