### ISSUE TITLE
Обновить бы карту на crew monitor со новым спутником

### ISSUE THREAD

**Issue by BeebBeebBoob** [TauCetiStation/TauCetiClassic#7582]
#### Подробное описание проблемы
эээээ

#### Что должно было произойти
Новая карта на crew monitor

#### Что произошло на самом деле
Старая карта

#### Как повторить
Использовать crew monitor

**Comment by KIBORG04** [comment]
Забыли. Запустите это на локалке и делайте ПР
![image](https://user-images.githubusercontent.com/26389417/125198918-95a69600-e26c-11eb-8376-00ca6df09173.png)

**Comment by BesumniiChebureck** [comment]
Блин ну че вы всегда сообщаете об этом после мержа
