### ISSUE TITLE
Фабрикаторы на шахтерке 

### ISSUE THREAD

**Issue by verbmaks** [TauCetiStation/TauCetiClassic#759]
#### Подробное описание проблемы
После сборки шахтерского дрона, фабрикатор не возвращается в меню, сохраняя статус сборки. Следовательно любое взаимодействие с ним становится невозможным.
#### Что должно было произойти
После сборки дрона фабрикатор должен был вернуться в меню сборки
#### Что произошло на самом деле
Фабрикатор сохранил статус "сборка дрона"
#### Как повторить
Собрать в фабрикаторе шахтерского дрона
#### Дополнительная информация:
На данный момент проблема лечится разборкой фабрикатора и обратной его сборкой

**Comment by Damirrus1** [comment]
Если что, это из-за того, что делается моб, а не объект.

**Comment by SpaiR** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/1283/commits/3e5a8ebfbe1de90489fb57292a2d957b7551dd2a
