### ISSUE TITLE
Skrellian hardsuit и NT breacher chassis могут носить люди

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7594]
#### Подробное описание проблемы
В ЕВА есть спец. риги для скреллов и унатхов,которые могут носить не только они,что странно
#### Что должно было произойти
скреллианские риги могут носить только скреллы,нт бричерс чазисы могут носить только унатхи
#### Что произошло на самом деле
Их могут носить хьюманы
#### Как повторить
Зайти на сервер за человека,зайти в ЕВА,надеть риг,посмотреть вики и зайти на статью про броню/хардсьюты:Композитный РИГ для ведения боевых действий. Носить его могут только Унатхи(описание нт бричера).Данный костюм имеет белую вариацию. Носить его могут только Скреллы(описание скрелльского хардсьюета).
#### Дополнительная информация:

**Comment by BeebBeebBoob** [comment]
![image](https://user-images.githubusercontent.com/32985153/125537261-4017170c-e79c-4a31-b618-70b6d849b227.png)
Подтверждаю из вики (https://wiki.taucetistation.org/Guide_to_Defense).
+
name = "skrellian hardsuit"
desc = "Seems like a wetsuit with reinforced plating seamlessly attached to it. Very chic."
Гугол = "Похоже на гидрокостюм с армированной обшивкой, легко прикрепленной к нему. Очень шикарно."
Гидрокостюм? Скреллам как раз но людям в таком было бы неприятно ходить.(наверное)
