### ISSUE TITLE
Шаттл конца смены отменяется во время ревы

### ISSUE THREAD

**Issue by splifin2** [TauCetiStation/TauCetiClassic#7596]
#### Подробное описание проблемы
Шаттл конца смены отменяется механом отмены шаттла во время ревы (пока главы/хеды ревы живы)
#### Что должно было произойти
Шаттл прилетает, главы улетают, рева ловит гринтекст.
#### Что произошло на самом деле
Шаттл не прилетает, рева устраивает вырезание глав, рева ловит ничью.
#### Как повторить
Устроить воут на конец смены во время ревы
#### Дополнительная информация:
ID раунда: 42841

**Comment by volas** [comment]
Раунд 42841 был экстой и шаттл в нем не отзывался. Если будет еще информация - слапните или откройте новый ишью
