### ISSUE TITLE
Акселераторы археологов

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#760]
#### Подробное описание проблемы:
Шахтёры воруют акселераторы с научки

#### Что должно было произойти:
Хотя бы ошибка допуска на аирлоке, как в техах

#### Что произошло на самом деле:
Свободно вошёл, забрал и ушёл. В результате сэкономил ресурсы/ваучер, что очень жирно

#### Как повторить:
Пойти за шахтёра на научку

#### Дополнительная информация:
Я вообще считаю, что акселератор археологам не нужен. Но вы, хотя бы, переместите его вглубь научки

**Comment by RigoSex** [comment]
@RichardJones1 как оно сейчас обстоит?

**Comment by RichardJones1** [comment]
Ах да. Спасибо, что напомнил, я заменил столы стойками за створками, к которым нужен доступ.
