### ISSUE TITLE
Мехи и молнии [Закрыто]

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#761]
#### Подробное описание проблемы
Мехи не реагируют на молнии. Будь это тесла или блюспейс кристалл. Можно, например, на РИПЛИ подойди вплотную и избить кристалл и получить халявное ядро аномалии
#### Что должно было произойти
Удар током по меха мб, ЭМИ
#### Что произошло на самом деле
Ничего
#### Как повторить
Выпустить теслу и сесть в мех, или на мехе подъехать к кристаллу
#### Дополнительная информация:
ЗАКРЫТО ПО ПРОСЬБЕ КИЛЬКИ

**Comment by SpaiR** [comment]
>ЗАКРЫТО ПО ПРОСЬБЕ КИЛЬКИ

В смысле? Нактуально или что?

**Comment by Skyrull** [comment]
@SpaiR http://tauceti.ru/forums/index.php?topic=5383.msg90428#msg90428

**Comment by SpaiR** [comment]
@Skyrull это конечно всё очень здоров, но что с ишью делать? @WallShrabnic ишью можно самому закрывать, кнопка снизу
