### ISSUE TITLE
Skrell digest не работает.

### ISSUE THREAD

**Issue by BeebBeebBoob** [TauCetiStation/TauCetiClassic#7614]
#### Подробное описание проблемы
```
on_skrell_digest(mob/living/M)
	..()
	return !flags[IS_ORGANIC]
```
Данный кусочек кода нигде не работает. Возможно связано с тем что либо не у всех проставлен флажочек IS_ORGANIC поэтому не проходит. Либо сама флажочек не работает. Либо что-то совсем другое( например что это отдельны digest )

#### Что должно было произойти
Многие реагенты работали как надо(алкоголю нет. Грибы все вкусные. Мясо только черть ест)

#### Что произошло на самом деле
Скрелл - рескин хумана.

#### Как повторить
пробовать за скрелла грибы, алкоголь и мясо.

**Comment by 4310V343k** [comment]
> Данный кусочек кода нигде не работает. Возможно связано с тем что либо не у всех проставлен флажочек IS_ORGANIC

Доброе утро, почитай что такое наследование в ООП

> алкоголю нет

Так и есть. Органический алкоголь(весь в билде, вроде) они усваивают.

> Мясо только черть ест

Мясо вызывает токсины.

> Грибы все вкусные

Единственная проблема. На вики сказано, что и органические наркотики хорошо усваиваются и плохо действуют, но в коде ничего про это нет.

**Comment by KIBORG04** [comment]
Да нет, работает
