### ISSUE TITLE
[Proposal]Реакцию на ЭМИ костюму ниндзи

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7615]
#### Подробное описание проблемы
Костюм ниндзи,который почти полностью состоит из всякой электроники,не восприимчив к ЭМИ.
#### Что должно было произойти
Нинжу бьёт током/костюм разряжается/etc
#### Что произошло на самом деле
Ничего

**Comment by 4310V343k** [comment]
Костюм садится, при чём довольно ощутимо. По крайней мере так было и ничего не должно было это сломать

**Comment by 4310V343k** [comment]
Беру свои слова обратно. ЭМИ реально ничего не делает

**Comment by EdlerN** [comment]
Нинжа это роль для унижения ролей. И его экипировка сделана таким образом именно для того чтобы он мог это успешно делать. В общем, идеи уровня охуительных.

**Comment by simb11** [comment]
А почему он тогда спавнится как рандом ивент а не только как щитспавн

**Comment by simb11** [comment]
фух слава богу нинжа снова является щитспавном для уничтожения ролей
