### ISSUE TITLE
Ошибка при осмотре лужи крови

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#762]
#### Подробное описание проблемы
Осмотр лужи крови дает "Это окровавленная кровь".
#### Что должно было произойти
Показывает "Это кровь".
#### Что произошло на самом деле
Показывает "Это окровавленная кровь".
#### Как повторить
Найти кровь, осмотреть ее.
#### Дополнительная информация:
http://prnt.sc/d3t3hp

**Comment by Skyrull** [comment]
Также относится и к следам из крови 
http://prntscr.com/d3tj6f

**Comment by jarezzz** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/1090
