### ISSUE TITLE
Ошибка при осмотре лужи масла

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#763]
#### Подробное описание проблемы
При осмотре лужи масла пишет "Это окровавленное масло".
#### Что должно было произойти
Пишет "Это масло".
#### Что произошло на самом деле
"Пишет "Это окровавленное масло".
#### Как повторить
Найти разлитое масло, осмотреть.
#### Дополнительная информация:
http://prntscr.com/d3tcd6

**Comment by Skyrull** [comment]
Также относится и к следам от масла: 
http://prntscr.com/d3tfxc

**Comment by jarezzz** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/1090
