### ISSUE TITLE
[Task] Нёрф гиперцина.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#7637]
На данный момент гиперцин не имеет никаких существенных недостатков которые нет способа контрить не переставая ширяться. Из-за чего гиперцином ширяется каждый кто может, постоянно.

Предлагаю добавить гиперцину показатель "привыкания". Со временем эта толерантность повышается, и ускорение от него с этим уменьшается. Когда гиперцина в крови нет - толерантность спадает.

Эдлерн рекомендует примерно такие цифры к этому:

> Что тоже не совсем хорошо. А что если сделать какой-нибудь статус эффект типа толерантности гиперцину и сделать так чтобы он набегал от 0 до 100 минут за 7-10. При этом за столько же времени сбегал обратно. И реальный эффект от гиперцина был не всегда максимальный, а помноженный на 1 - Процент привыкания.

( #7206 )

**Comment by LudwigVonChesterfield** [comment]
(Лично я предпочёл бы, чтобы гиперцин не работал/работал хуже когда кукла испытывает боль, тогда и "мирное" использование (шахтёры, ксеноархеологи) осталось легитимным, и уколы адреналинагиперцина бы остались полезными)

**Comment by 4310V343k** [comment]
Гиперцин и так не контрит замедление от боли

**Comment by LudwigVonChesterfield** [comment]
Гиперцин + риг + боль быстрее чем риг + боль

**Comment by 4310V343k** [comment]
А

**Comment by volas** [comment]
Не буду переписывать и это в целом по замедлениям, просто оставлю ссылку https://discord.com/channels/401030271417188353/401031448963973120/883408728521572442

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/voprosy-k-administraczii/5430/1131

**Comment by Rogostick** [comment]
Можно поднять шанс негативных эффектов до 20, и добавить более серьёзные эффекты с шансом в 5. Это заставит пользовать гипер реже и осторожнее.

**Comment by Rogostick** [comment]
Написал систему при которой после каждого использования у нас уменьшается эффективность гипера. Судя по тестам она даже работает.
Сверху делаем:
`var/hyp_eff = 1`
а это у гипера самого:
```
	if(prob(40))
		M.emote(pick("twitch","blink","shiver"))
		hyp_eff -= 0.1
	if(prob(5))
		M.adjustOxyLoss(5)
```
это у нас находиться в code/modules/reagents/reagent_types/Chemistry-Medicine.dm
Ещё для работы данной штуки нужно вот это:
`chem_nullify_debuff *= hyp_eff`
в code\modules\mob\living\carbon\human\human_movement.dm
P.S. на балансные циферки не претендую.

**Comment by LudwigVonChesterfield** [comment]
ну, заливай Pull Request. если нужна помощь - дёрни @Codehelp-slap в дискорде в #how-to-code
