### ISSUE TITLE
Кресло-каталка и одноногие

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#764]
#### Подробное описание проблемы
Одноногим при деклере не дают кресло-каталку
#### Что должно было произойти
Дать кресло-каталку
#### Что произошло на самом деле
Не дали кресло-каталку
#### Как повторить
В настройке персонажа сделать ампутированную ногу одну
#### Дополнительная информация:
Где моё кресло-каталку

**Comment by Damirrus1** [comment]
Зочем одноногим каталка?

**Comment by WallShrabnic** [comment]
Наверное, чтобы было удобно ходить?

**Comment by Dennok** [comment]
Есть костыль. Или палка, В меде пусть ее дают. А вообщето былобы неплохо портануть лоадаут(чтоб у нас все на креслах каталках ездили.)
