### ISSUE TITLE
У чужих не появляется игровой экран на старте раунда

### ISSUE THREAD

**Issue by Zmey25** [TauCetiStation/TauCetiClassic#7646]
#### Подробное описание проблемы
Начиная раунд за чужого при старте не появляется игровой экран, вместо этого ты продолжаешь видеть экран лобби
#### Что должно было произойти
Игровой экран - геймплей - веселье
#### Что произошло на самом деле
Экран лобби, выбор между реди, обсерв и т.д.
#### Как повторить
Стартануть за чужих в их режиме
#### Дополнительная информация:
Issue reported from  Round ID: 43073 (Tau Ceti Classic (RU))
Testmerges: ```#7372 #7499 #7607 #7642 ```
Reporting client version: 513.1532

**Comment by KIBORG04** [comment]
#7642

**Comment by KIBORG04** [comment]
Еще вроде текст при спавне не вовремя пишется
