### ISSUE TITLE
Автоматические турели не реагируют на возвышенного тенелинга

### ISSUE THREAD

**Issue by DeadOberst** [TauCetiStation/TauCetiClassic#765]
#### Подробное описание проблемы
Турели в ядре ИИ не стреляют по возвышенному шедоу.
#### Что должно было произойти
Турели должны были расстрелять проклятого интервента.
#### Что произошло на самом деле
Он разгуливал по ядру как у себя дома.
#### Как повторить
Быть тенелингом, насобирать аутят, возвыситься и наведаться в ядро или загрузочную.

**Comment by Raschert0** [comment]
Ну, я бы в его присутствии тоже прикинулся бы шлангом (а на самом деле весьма странно)

**Comment by WallShrabnic** [comment]
Ну я тащем та не мог покинуть тебя клыками. Чсх, я не могу уничтожить туннели, типа мы не трогаем тебя, ты не трогаеш нас

**Comment by Dennok** [comment]
Там прикол с телепортацией. При телепортации в зону телепортонувшегося почемуто не вводит в список целей. 100% было с педальным джамт ту турфом. Еще вроде если через телепорт было.

**Comment by Raschert0** [comment]
Нету зоновых турелей - нету проблемы
