### ISSUE TITLE
[Proposal] Содержимое листов в классе /obj/machinery/vending писал фашист

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#7650]
#### Подробное описание проблемы
Содержимое переменных `products` `contraband` `premium` `prices` у `/obj/machinery/vending` написано для роботов, которые могут даже такое прочитать.

Одним из самых очевидных примеров является автомат с одеждой. Тут просто куча всяхти типов и цифр. Ниче непонятно емае вообще.
https://github.com/TauCetiStation/TauCetiClassic/blob/9b280925439976bebd1f2e230fb7d9b094f0d578/code/game/machinery/vending.dm#L1157-L1178

Я предлагаю создать папку для вендоматов и каждый раскидать по отельным файлам. Это уже улучшит восприятие, но самое главное - это ставить после каждой запятой перенос строки, это увеличит понимание содержимого в количество_запятых раз. Работа не пыльная, но муторная

**Comment by notkripton** [comment]
А что конкретно тут непонятного?

**Comment by KIBORG04** [comment]
У меня в вскоде и на сайте оно не помещается все в один монитор 1920x1080.

Если ты каждый элемент расположишь в новой строке, намного все будет читаемее, вместительнее, понятнее, больше будет подвержено редактированию и добавлению новых элементов.

**Comment by KIBORG04** [comment]
https://github.com/tgstation/tgstation/blob/a11124e9cf3cb2e1c02d127adfcd52269275d6de/code/modules/vending/clothesmate.dm

**Comment by notkripton** [comment]
Ну значит я либо робот, либо фашист.... (все вместе)
