### ISSUE TITLE
[Proposal]Дротик пробивает любую броню

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7651]
#### Подробное описание проблемы
Дартсы для дробовика кнокают человека в любой броне,хоть обычный броник,хоть риг
#### Что должно было произойти
Броня защищает от дротиков
#### Что произошло на самом деле
Не защищает
#### Как повторить
Зарядить ружьё дротиками,стрельнуть в человека в броне,посмотреть на то,как он упадет.

**Comment by Motzord** [comment]
Not a bag.

**Comment by simb11** [comment]
Была убрана возможность получить дротики при помощи автолата,можно и закрыть.
