### ISSUE TITLE
Плазменные пушки не работают

### ISSUE THREAD

**Issue by ChewedGum** [TauCetiStation/TauCetiClassic#7661]
#### Подробное описание проблемы
Плазменные пушки не стреляют.

#### Что должно было произойти
Плазма вылетает из стрелялы и наносит урон тому в кого попадет.

#### Что произошло на самом деле
Появляется космический кiт и сообщает о какой-то ошибке. 

#### Как повторить
Взять плазменную шуту и попробовать выстрелить из неё.

#### Дополнительная информация:
(F) Runtime meows, "Зафиксирована аномалия #101. Пожалуйста, отойдите подальше."
Раунд 43131

**Comment by 4310V343k** [comment]
Сам ты псина

**Comment by ChewedGum** [comment]
нет ты

**Comment by KIBORG04** [comment]
я убрал это оскорбление
