### ISSUE TITLE
Необновляющийся при отпадании спрайт правой руки

### ISSUE THREAD

**Issue by YulianR** [TauCetiStation/TauCetiClassic#767]
#### Подробное описание проблемы
Когда отпадает правая рука (именно она) спрайт никак не хочет обновляться и показывается, что она еще есть
#### Что должно было произойти
То же, что при отрезании другой конечности - обновляется спрайт и рука уже не показывается
#### Что произошло на самом деле
То что я описал в первом пункте
#### Как повторить
Отрезать правую руку

**Comment by Dennok** [comment]
Там вроде проблема в спрайте а не в обновлении.
