### ISSUE TITLE
У ОБОПа нету иконок ХУДа и имплантов

### ISSUE THREAD

**Issue by ChewedGum** [TauCetiStation/TauCetiClassic#7676]
#### Подробное описание проблемы
Прилетает толпа бойзов с оружием на станцию у которых ни имплантов, ни каких-либо неоспоримых пруфов своей принадлежности к ЦК и НТ. По сути офицеры и главы могут тут же открывать огонь по ним едва завидев.
#### Что должно было произойти
Дать им импланты лояльности и доступ как у ОБРа.
#### Что произошло на самом деле
Прилетают непонятные типы во всеоружии которых СБ думает размазывать по полу или нет. 
#### Как повторить
Поиграть в новый гэнг.
#### Дополнительная информация:
Раунд 43212.

**Comment by KIBORG04** [comment]
добавлю имплант и хватит

**Comment by KIBORG04** [comment]
![image](https://user-images.githubusercontent.com/26389417/127035570-982c1e82-1614-422f-81f1-4d82de0f1004.png)

Скоро...

**Comment by Prusski** [comment]
Так ОБОП ведь не принадлежит НТ. Это неподкупная полиция сола, которая бьёт лицо всем, кто нарушит закон.
Зачем им N на худах?

**Comment by KIBORG04** [comment]
Если бы ты читал анонсы.. У нас лор не тгшный

**Comment by KIBORG04** [comment]
Вроде пофиксил
