### ISSUE TITLE
Выпилить РП [Proposal]

### ISSUE THREAD

**Issue by DarkSovet-bruh** [TauCetiStation/TauCetiClassic#7682]
#### Подробное описание проблемы
Бесполезное и раздражающее явление - РП. Оно у нас и так хуёво сделано, лучше уж выпилить, чтобы не было стыдно.

**Comment by KIBORG04** [comment]
класс

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/fludilka/3304/43196
