### ISSUE TITLE
[Proposal] Ломание шеи через граб. 

### ISSUE THREAD

**Issue by TheLustOfBlood** [TauCetiStation/TauCetiClassic#7686]
Странно что куклы не умеют ломать шеи, те же триторы, те же офицерики, хотя все знают об этом, и знают в теории как это делается. Можно было бы сделать чтобы третий граб + клик на харме по голове запускал процесс сворачивания шеи длинною в 5-10 секунд, но при этом у куклы была возможность сопротивляться этому путем напряжения мышц шеи, то бишь если прожимался резист то направленное на него действие отменялось.
Правда вот, какую-нибудь спящую|закритованную|захлоренную куклу это вряд ли спасёт. 
Как-то так, я не уверен насчёт баланса этой инстасмерти буквально от голых рук.

**Comment by 4310V343k** [comment]
Нахуя никто пользоваться не будет, ибо рядом лежит кусок стекла

**Comment by TheLustOfBlood** [comment]
> Нихуя никто пользоваться не будет, ибо рядом лежит кусок стекла

Так тут без крови, без звука, если не считать какой-нибудь хруст для приличности только. 
Просто схватил за бошку, сломал и побежал.

**Comment by KIBORG04** [comment]
когда уже сделаете, чтоб хедшот ваншотил

**Comment by AndroBetel** [comment]
лучше чтобы можно было поцелуем душить

**Comment by TheLustOfBlood** [comment]
Ладно, хрень напридумывал.
