### ISSUE TITLE
баг с отображением ресурсов в протолате

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7689]
#### Подробное описание проблемы
Неправильно отображаются ресурсы в протолате
#### Что должно было произойти
Всё нормально
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/84613249/127320074-decd4148-b202-49b4-91b6-c8146fb2da91.png)

#### Как повторить
Включить консоль рнд и посмотреть на цены в протолате и принтере для создания плат
#### Дополнительная информация:

**Comment by BlankCringe** [comment]
верни радужные бананы и имплантеры ирод!
