### ISSUE TITLE
Недостающая вентиляция в инженерном коридоре

### ISSUE THREAD

**Issue by StrikS** [TauCetiStation/TauCetiClassic#770]
#### Подробное описание проблемы
В нижней части инженерного коридора отсутствует вентиляция рядом с датчиком атмосферы.
Пожарные створки опущены разделяя коридор на две части. В верхей части вентиляция в нижний датчик.  Включаем подачу воздуха...
#### Что должно было произойти
Датчик регистрирует изменения атмосферы и поднимает пожарные створки при 90кпа и перестает накачивать при 101кпа
#### Что произошло на самом деле
Датчик не регистрирует изменения верхней части. Створки не поднимаются, давление в верхней части растет до бесконечности(4500) если не заметить. При открытии створки все вещи с силой швыряет в стену в том числе и космонавтика, если не врубил магбутсы.
#### Дополнительная информация:
Можно вентиляцию запихнуть под стол для эстетичности
![image](https://cloud.githubusercontent.com/assets/15943769/20090225/a119ddfe-a5ad-11e6-8735-71ab77369f59.png)

**Comment by Dennok** [comment]
Нельзя. Створки при опускании тогда ее блокируют.

**Comment by Dennok** [comment]
И как я тут вижу На южной стене коридора чтоли тоже аир алярм висит?

**Comment by StrikS** [comment]
![image](https://cloud.githubusercontent.com/assets/15943769/20168760/a2fdaa62-a745-11e6-8a54-cbef595dbf41.png)
Каким образом створки что-то блокируют ПАДЦТАЛОМ?
>И как я тут вижу На южной стене коридора чтоли тоже аир алярм висит?

Висит, можно один аир алярм который у южной стены в верхнюю часть коридора кинуть.

**Comment by Dennok** [comment]
Угу можно. А про стол я не про тот подумал.
