### ISSUE TITLE
Карта на пол ПДА,которую нельзя скрыть

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7706]
#### Подробное описание проблемы
Появляется очень неудобная карта,которая очееееень мешает работать с ПДА,а ну еще интерфейс меняется на старый
#### Что должно было произойти
всё ок,карты нету

#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/84613249/127731808-20d555b8-86b6-42f2-8216-5bdbdf6dd40c.png)

#### Как повторить
хз,захожу в пда и вижу карту
#### Дополнительная информация:
чинится при помощи фикса уи

**Comment by KIBORG04** [comment]
почисти кеш
