### ISSUE TITLE
Криво стоит консоль на велосити

### ISSUE THREAD

**Issue by StrikS** [TauCetiStation/TauCetiClassic#771]
#### Подробное описание проблемы
Консоль стоит криво
#### Что должно было произойти
Консоль должна стоять ровно
#### Что произошло на самом деле
Консоль стоит криво
#### Как повторить
Поставить консоль криво
#### Дополнительная информация:
![image](https://cloud.githubusercontent.com/assets/15943769/20095062/b55392ac-a5c5-11e6-964d-38da7cf9c0b1.png)

**Comment by Leshiy-ART** [comment]
Там вообще Велосити пора переделывать.

**Comment by Damirrus1** [comment]
Спрайта то нет :C

**Comment by Skippeer12** [comment]
Спрайтов не будет. А эти давно уже откатили.
