### ISSUE TITLE
Неправильные размеры у вещей

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7717]
#### Подробное описание проблемы
После обновления появилось два одинаковых размера,смалл и смалл,одно может положить в карман(гаечные ключи,сварки,провода и прочие),а другое нельзя(лазерные винтовки,еганы,листы металла и тд)
#### Что должно было произойти
Разные названия
#### Что произошло на самом деле
Что одно small,что другое small
#### Как повторить
посмотреть на размер,допустим лазерки и флешки.Понять что одно можно положить в карман,коробку,а другое нет

**Comment by volas** [comment]
Эх, не хотел перегружать описания предметов и мобов полной градацией размеров, потому что она не очень очевидна (кто больше - Large, Big или Massive?), и для некоторых категорий использовал общий флавор. 
Но для некоторых вещей индикация нужна, как тут, так что я вернул еще один отдельный флавор. Теперь градация для небольших вещей: minuscule (слот уха) -> tiny (карманы) -> small.

Что бы в игре это было понятнее, добавил еще тултип с точным размером.

#7462
