### ISSUE TITLE
Нету шкафа с глоками.

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7726]
#### Подробное описание проблемы
несмотря на то что в чейнджлоге написано про то что в оружейную добавлен шкаф с глоками,его там нету.
#### Что должно было произойти
![image](https://user-images.githubusercontent.com/84613249/128004322-4da724a6-71a4-4c01-a795-b6a0d4e12948.png)

#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/84613249/128004257-913070e8-991f-4eaf-9e0f-655b738a97fd.png)

#### Как повторить
посмотреть в чейнджлог и в оружейную.

**Comment by KIBORG04** [comment]
Билд старый
