### ISSUE TITLE
Отличия между худ иконкой се и инженера

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7730]
#### Подробное описание проблемы
Между иконками СЕ и инженера почти ноль разницы,из за чего их достаточно сложно отличить
#### Что должно было произойти
Разные иконки
#### Что произошло на самом деле
Почти одинаковые
#### Как повторить
Надеть худа и посмотреть на человека с картой се,а потом на человека с картой инженера
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/84613249/128172355-57326f70-3160-4d16-90b2-42eda6eff813.png)

**Comment by KIBORG04** [comment]
Ты ещё сравни маентеинс техника и рд

**Comment by Rahmanio** [comment]
Это конечно скорее пропосал, а не баг. В игре в принципе отличить можно, но я согласен, возможно стоит что-то с этим сделать.
