### ISSUE TITLE
[Proposal] сделать в флаффе-шляпе кнопку hide hair

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#7733]
хочется в флафф сделать тебе какой-нибудь шлем от скафандра или капюшон например, ты его делаешь, надеваешь, а сквозь него торчит твоя модная прическа. было бы неплохо сделать эту самую кнопку hide hair или костыльно отдельный тип флаффа с флагом HIDE_HAIR

**Comment by Venngedi** [comment]
#8120 Без лишних слов
