### ISSUE TITLE
Мешок мусорщика не может собрать мусор 

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#7739]
#### Подробное описание проблемы
Мешок мусорщика не может вместить себя мусор
#### Что должно было произойти
Я кликаю на мусор и он засовывается
#### Что произошло на самом деле
You fail to pick anything up with the industrial trash bag.
#### Как повторить
1) взять мешок мусорщика
2) попробовать засунуть туда мусор
#### Дополнительная информация:
Мяу

**Comment by Haggerd** [comment]
Что именно ты подразумеваешь под мусором? Unrefided scrap, который остаётся после раскопки мусорных куч? Или что-то другое?

**Comment by Daoprotoss** [comment]
> Что именно ты подразумеваешь под мусором? Unrefided scrap, который остаётся после раскопки мусорных куч? Или что-то другое?

Имеенно оно

**Comment by pss88** [comment]
А раньше Unrefined Scrap засовывался в этот мешок?

**Comment by LudwigVonChesterfield** [comment]
да, и должен засовываться так-то.

**Comment by Daoprotoss** [comment]
Баг починись пж, я за мусорщика нормально аутировать хочу

**Comment by KIBORG04** [comment]
Я начал расследование:
 1. На сервере действительно такой баг есть, в ТМах генг и размеры.
 2. На самой новой локалочке с генгом бага нету

Вывод: во всем виноват https://github.com/TauCetiStation/TauCetiClassic/pull/7462
