### ISSUE TITLE
[Proposal]Дробь для дробовика никому не нужна

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7745]
#### Подробное описание проблемы
В автолате и на базе обр лежат некие бакшоты для дробовика,но из за своих +-40 урона с 3-4 метров,отсутствия гиба конечностей и еще пары моментов не юзаются,поэтому всем плевать на дробь и все используют слаги,которые в несколько раз эффективнее.
Как идея,сделать дробь реально дробью,чтобы была возможность поразить сразу несколько целей,а не как сейчас,максимум 2.

**Comment by LudwigVonChesterfield** [comment]
ещё круто было бы сделать чтобы дробь попадала по всему телу, а не только куда целился

**Comment by Rahmanio** [comment]
> ещё круто было бы сделать чтобы дробь попадала по всему телу, а не только куда целился

Сделать рандомные шансы попадания в зависимости от того, куда ты целишься? целишься в голову, заденет туловище, гройн и руки, ноги скорее всего не затронет, маленький шанс. Но шансы ещё от дистанции должны зависеть, большая система как по мне.
