### ISSUE TITLE
шахтёрский фабрикатор делает майнинг риг уже с пластинами.

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7755]
#### Подробное описание проблемы
В риге,который создал фабрикатор уже есть пластины голиафа,из за чего он уже имеет 90% резиста к мили
#### Что должно было произойти
риг нужно самому улучшать
#### Что произошло на самом деле
уже сделан готовый,улучшенный риг
#### Как повторить
сделать шахтёрский риг в майнинг фабрикаторе и посмотреть статы

**Comment by kalazus** [comment]
Шахтёрский риг стандартом имеет 90% мили, а пластины Голиафа могут повысить защиту только до 80%. Плиты нужны только на шлем.

**Comment by simb11** [comment]
раньше можно было и на риг поставить....

**Comment by 4310V343k** [comment]
Нельзя было

**Comment by simb11** [comment]
ладно,тогда закрываю.
