### ISSUE TITLE
АПЦ который невозможно сломать и починить. (Попытка джва)

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#776]
#### Подробное описание проблемы
Есть АПЦ, который при взломе или поломке невозможно сломать чтобы починить его.
#### Что должно было произойти
У АПЦ должна сломатся крышка, чтобы её можно было снять и починить его.
#### Что произошло на самом деле
АПЦ просто мигает и его невозможно сломать ни балоном ни топором.
![421](https://cloud.githubusercontent.com/assets/18488106/20149891/de9fdbe2-a6bb-11e6-9175-016a97549263.png)
#### Как повторить
Найти вот такой вот АПЦ и попробовать сломать у него крышку.
![512](https://cloud.githubusercontent.com/assets/18488106/20149885/da842db0-a6bb-11e6-9f59-dba908884f65.png)

#### Дополнительная информация:
Такой АПЦ может починить только борг, сняв у него защиту, чтобы открыть ломом.
Ну или крайний метод, сделать взрыв возле него, тогда крышка сьедет и он будет сломан, тогда его и можно будет доломать и пересобрать.

**Comment by Dennok** [comment]
вообще по логике так должно быть можно сломать ЛЮБОй АПЦ.Но, к сожалению они неуязвимы (крое взрывов)

**Comment by Lancer411** [comment]
>к сожалению они неуязвимы (крое взрывов)

Или к счастью.

**Comment by Dennok** [comment]
Ну это да. Ато грекйтайды с балонамибы выносчсили всю станцию, Как щас на ТГ можно выносить балоном двери

**Comment by skvazarb** [comment]
>Ну это да. Ато грекйтайды с балонамибы выносчсили всю станцию, Как щас на ТГ можно выносить балоном двери

Как будто у них сейчас мало способов для вандализма. В текущем варианте это скорее мешает ремонту, чем помогает от грейтайдеров.

**Comment by Lancer411** [comment]
Ломать нужно только взорванные АПЦ. Обычные хакнутые АПЦ логично бы было открывать мультитулом.
Раньше эти АПЦ открывались обычной картой инженера и разбирались в штатном порядке. Как сейчас это работает, не имею представления.

**Comment by Skippeer12** [comment]
Примерно никак.
The interface is broken.

**Comment by SpaiR** [comment]
#275
