### ISSUE TITLE
Починка датумов анонсов и педальных клавиш

### ISSUE THREAD

**Issue by atik1n** [TauCetiStation/TauCetiClassic#7762]
#### Подробное описание проблемы
1) sanitize, а именно его использование в педальных кнопках, не только в message
https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/admin/secrets/secrets_menu/custom_announcement.dm

```
A.message = sanitize(input(ui.user, "Please enter anything you want. Anything. Serious.", "What?", A.message) as message, MAX_PAPER_MESSAGE_LEN, extra = TRUE)
```
Убрать санитайз тут и вынести его в файле
https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/datums/announcements.dm
В `.play()`

2) В самих анонсах, в этой папке:
https://github.com/TauCetiStation/TauCetiClassic/tree/master/code/datums/announcements

изменить рантаймовые мессаджи, как у блоба, из `.play()` на инициализацию, чтобы она работала в педальных кнопках
![image](https://user-images.githubusercontent.com/14612180/129082736-d2e44549-c53a-4195-9773-173f8daa0a4e.png)

**Comment by volas** [comment]
2 - нужно заменить /play у анонсов на /new

**Comment by atik1n** [comment]
> 2 - нужно заменить /play у анонсов на /new

`play()` вызывается в коде именно в момент воспроизведения, тут нужно быть осторожным
