### ISSUE TITLE
бесплатный респавн у боксерской груши

### ISSUE THREAD

**Issue by muWander** [TauCetiStation/TauCetiClassic#7778]
#### Подробное описание проблемы
если зайти за боксерскую грушу и нажать rest дадут респавн
#### Как повторить
будучи наблюдателем нажать на грушу и написать rest
#### Дополнительная информация:
в одном раунде когда проверял не дали респавн а сократили время до респавна на 5 минут, хз от чего зависит

**Comment by Haggerd** [comment]
Мне больше интересно, почему вообще обычные игроки могут вселиться в грушу...
