### ISSUE TITLE
[Proposal]Убрать кноки у мили оружия

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7780]
#### Подробное описание проблемы
У большинства мили оружия очень смешные кноки,доходит до того что можно одним ударом ломика положить офицера в риге сб,или двойной меч,у которого каждый второй удар - ввод в сон.Или хотя бы сделать так,чтобы броня ЗАЩИЩАЛА от кноков,сейчас даже в броне хоса/риотке можно умереть от ассистента с огнетушителем.

**Comment by notkripton** [comment]
Если ты про раунд, где ты улетел в кнок охотясь за ксенобиологом, то это ты сам себя дубинкой ударил, а не я тебя ломом.

**Comment by LudwigVonChesterfield** [comment]
броня и так защищает, но кноки завязаны на шансах

и до тех пор пока они завязаны на шансах, учитывая что человек крепче запоминает плохие моменты, а не хорошие - всем будет казаться что их сбивают с первого удара (иногда это даже правда)
