### ISSUE TITLE
Фракции и роли не удаляются при невозможности старта режима

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#7784]
#### Подробное описание проблемы
Это происходит, если режим ПОТЕНЦИАЛЬНО может запуститься, прошёл все проверки на реди и тд, но при заполнение фракций нехватило человек. В итоге режим не запускается, но выданные роли майнду госта остаются (вроде).

#### Что должно было произойти
Новый режим с одним типом роли

#### Что произошло на самом деле
Вокс во фракции балласов, хеитса, ментов
![image](https://user-images.githubusercontent.com/26389417/129607686-4e38fff0-54f4-4b5a-9395-2dabdb024e50.png)

#### Как повторить
Рандомно выпал генг два раза подрят. 1 игрок прошел в режим 2 раза и получил рольку. Но в итоге, чтобы заполнить лидеров 2й банды тупо нехватило

#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/26389417/129607428-39979eb0-c636-45cd-9e98-4e6a68a2b1f3.png)

Предложения пофиксить:
1. Если не запустилось, то дропаем удаляем все к чертям.
2. Недопустить возможность режиму выпасть, если у игроков недостаточно префов. Это отсекать как с малфом, что если нету работы ИИ - не быть режиму.

**Comment by 4310V343k** [comment]
агт
