### ISSUE TITLE
Неправильное отображение местоположения королевы

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7786]
#### Подробное описание проблемы
по неизвестным мне причинам,в менюшке алиенов написано что квина находится на центкоме
#### Что должно было произойти
всё ок,написано что королева на станции 
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/84613249/129731440-5e50562e-4379-4bb5-98ff-7f762e94769f.png)

#### Как повторить
не знаю.
#### Дополнительная информация:
мб это просто админы заспавнили еще одну квину на центкоме
рануд 43833

**Comment by KIBORG04** [comment]
Как всегда во всем виноваты админы

**Comment by atik1n** [comment]
Мне надо было остановить поток OOC в IC от нескольких особей и я выбрал сначала Antag-OOC, а потом ваш хайв чатик. Из-за этого поломалось. Прошу прощения.

**Comment by KIBORG04** [comment]
Тут скорее пропосал, о написание нескольких королев или еще чего

**Comment by LudwigVonChesterfield** [comment]
На Колониал маринах есть такая сущность как "Queen Mother / Space Empress", возможно стоит педалям дать кнопку анонса в хайв от лица этой сущности

**Comment by atik1n** [comment]
> На Колониал маринах есть такая сущность как "Queen Mother / Space Empress", возможно стоит педалям дать кнопку анонса в хайв от лица этой сущности

Я подумал, что возможно стоит сделать кнопку-хаб для всех антагов? Возможно, этим займёсь или распишу пропозал
