### ISSUE TITLE
активация зума снайперки крашит игру

### ISSUE THREAD

**Issue by PirogSema** [TauCetiStation/TauCetiClassic#7787]
#### Подробное описание проблемы
Активация зума снайперки крашит клиент
#### Что должно было произойти
Активировался зум
#### Что произошло на самом деле
Крашнулась игра
#### Как повторить
Активировать зум снайперки
#### Дополнительная информация:
Issue reported from  Round ID: 43833 (Tau Ceti Classic (RU))
Testmerges: ```#7708 #7768 #7591 ```
Reporting client version: 514.1557
буквально вчера такого не было, однако тогда каждый раз при использовании зума вызывался рантайм

**Comment by KIBORG04** [comment]
Возможно, из-за 514
