### ISSUE TITLE
[Proposal] Улучшение взаимодействия с ID картами.

### ISSUE THREAD

**Issue by Rahmanio** [TauCetiStation/TauCetiClassic#7791]
#### Подробное описание
В 23 веке ID карты это очень важная составляющая геймплея. Предлагаю сделать отдельную консоль, где будут отображены все ID карты и имена людей. Можно будет удобно аннулировать доступ любого члена персонала, в случае если он убегает от ареста. Данная консоль просто может отключить/включить любую ID карту. Консоль можно поставить на мостике(есть одно бесполезное место), каждый глава будет иметь доступ только к своему отделу, капитан же может отключить любую карту, также свою запасную карту, в случае пропажи. У нас 23 век, если какой-то маг крадёт ID карту капитана, он имеет полный доступ и его никак не убрать. 

Предполагаю, у ИИ и боргов доступа к этой консоли, не будет. В силу баланса, в каждом отделе, можно будет отключить по 2 карточки одновременно, а карточки глав и капитана(кроме запасной) нельзя будет отключить.

#### Что должно было произойти
*

#### Что произошло на самом деле
*

#### Как повторить

*
#### Дополнительная информация:
*

**Comment by AndroBetel** [comment]
мб капитану сразу дать кнопку, которая любого на станции гибнуть может? охрану заодно удалить можно, а то зачем ей стараться играть и ловить злодеев
