### ISSUE TITLE
Моментальный респавн или добавление минуток к таймеру респавна.

### ISSUE THREAD

**Issue by kalter228dead** [TauCetiStation/TauCetiClassic#7792]
#### Подробное описание проблемы
Если перейти в призраки, вселиться в грушу для битья и нажать кнопку rest можно моментально респавниться или к вашему таймеру добавится 5-10 минуток.
#### Что должно было произойти
Таймер никак не должен меняться.
#### Что произошло на самом деле
Моментальный респавн или добавление минуток(еще не до конца понял, как оно работает)
#### Как повторить
Гост-вселение в грушу-рест-респавн.

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/7778
