### ISSUE TITLE
[Proposal] Добавить коту-рантайму кнопку РЕПОРТ только для создателя кота и гостов 

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#7797]
#### Подробное описание проблемы
Мне нравится, что люди котов репортят, но они все еще делают это неправильно. Например, не пишут раунд, тестмержы, может еще что-то. Сейчас кот появляется только если существует usr. То есть, поидее, если usr вызывает рантайм, то он должен знать весь контекст бага. Наверное. 
Ну так мое предложение: коту в описание добавляется кнопка, которую видят только создатель рантайма и госты. Если на нёё нажать, то нажиматель получает печеньку и открываться гитхаб с заполненной формой. 
То есть, юзер одной кнопкой всё репортит, так еще и может что-то дописать.

Я могу это сделать, но тут придёт @volas и скажет: "мета удаляй", как в прошлый раз.

**Comment by Haggerd** [comment]
Лучше медальку давать...
За медальку не впадлу было бы
