### ISSUE TITLE
[Runtime] Халк VS шлюз

### ISSUE THREAD

**Issue by QWxiZX** [TauCetiStation/TauCetiClassic#7808]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/70110199/130325481-becdf6f7-3f40-4cf6-848b-0097ee0f9130.png)
![image](https://user-images.githubusercontent.com/70110199/130325482-a9c450f6-4a6e-4d88-aeb1-a156f04a32d8.png)
Халк липнулся - высрал кота.
#### Что должно было произойти
-
#### Что произошло на самом деле
-
#### Как повторить
-
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/70110199/130325496-316a4abd-df52-444b-ad82-e8f89b79dd13.png)

**Comment by KIBORG04** [comment]
Не по форме

**Comment by QWxiZX** [comment]
> Не по форме

Я не знаю, что конкретно вызвало, как это повторить и что произошло на самом деле.

**Comment by KIBORG04** [comment]
мы тоже

**Comment by QWxiZX** [comment]
> мы тоже

Поэтому, чтобы вы узнали, если вам захочется, у вас есть время и номер раунда.

**Comment by KIBORG04** [comment]
)

**Comment by QWxiZX** [comment]
> )

Я знаю, что вам не захочется, поэтому просто для приличия написала)

**Comment by KIBORG04** [comment]
вроде не сломано ниче
