### ISSUE TITLE
Несоответствие размеров предметов в кобуре для дубинки

### ISSUE THREAD

**Issue by Rahmanio** [TauCetiStation/TauCetiClassic#7823]
#### Подробное описание проблемы

https://user-images.githubusercontent.com/67812445/130403927-63163ef4-511b-41ce-a842-6bdf9d611aff.mp4

#### Что должно было произойти
Лазмеч, поверфист и меч культистов нельзя засунуть в кобуру.
#### Что произошло на самом деле
Вышеперечисленные предметы можно положить в кобуру, а лазмеч вообще достаётся без звуков.
#### Как повторить
Положить в кобуру лазерный меч и тд.
#### Дополнительная информация:
Благодаря данному событию можно по сути хранить предметы в кармане, а так же доставать их бесшумно.

**Comment by ChewedGum** [comment]
А ножи туда все равно не лезут, мда.

**Comment by Rahmanio** [comment]
> А ножи туда все равно не лезут, мда.

Они и не должны туда по форме подходить... Это не ножны, у вас детей всё плохо с представлением и воображением. Для ножей надо вводить специальные ножны. А, тогда ножны будет бесполезными, потому что ножик можно в ботинки засунуть. Думай головой прежде чем высирать что-то.
