### ISSUE TITLE
Новый TGui для ритуалов выдаёт ошибку при появлении нового капеллана.

### ISSUE THREAD

**Issue by Ro2tCrab** [TauCetiStation/TauCetiClassic#7830]
#### Подробное описание проблемы
Если до тебя был капеллан, то использование алтаря выдаст синий экран.
#### Что должно было произойти
Новый капеллан может выбрать аспекты и продожить игру.
#### Что произошло на самом деле
![hudproblem](https://user-images.githubusercontent.com/68421546/130530686-d742bf1d-13d5-47cc-bdc8-4d331f66311b.png)
#### Как повторить
Попросить первого капеллана войти в крио и зайти за нового.
#### Дополнительная информация:
Round ID : 44035

**Comment by LudwigVonChesterfield** [comment]
#7701

**Comment by KIBORG04** [comment]
Как не странно, повторить не удалось
