### ISSUE TITLE
Сломались термалы

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7832]
#### Подробное описание проблемы
недавно,после обновления освещения(или чего то там,не совсем понял чего именно),перестали нормально работать термалы,во время ходьбы человека его не видно сквозь стены
#### Что должно было произойти
людей в термальных визорах видно всегда
#### Что произошло на самом деле
во время того,как человек ходит его не видно в очках.
#### Как повторить
надеть термальные очки,посмотреть на то как люди бегают за стеной,в темноте и тд,понять что их нельзя увидеть. 
#### Дополнительная информация:
Test merged PRs: #7708 #7701 #7519 
2021,08.23/24
скорее всего связанно с #7802

**Comment by Morar1** [comment]
Не смог повторить только с #7802 на сервере.

**Comment by KIBORG04** [comment]
Я и на сендбоксе не смог повторить. Видел всегда чела в техах, в темноте, сквозь стены и тд

**Comment by KIBORG04** [comment]
https://user-images.githubusercontent.com/26389417/130615038-6855af1d-cf61-4ecb-8ab9-262cce6046d0.mp4


то что курицу не видно, когда она не за стеной, это впринципе нормально, ибо видеть сквозь стены позволяет механ бульонда, а темнона - механ тау кеки

**Comment by KIBORG04** [comment]
Даже на первом термалы работают, как надо
