### ISSUE TITLE
[Runtime] Рантайм пустого фреймворка настроений?

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#7834]
#### Подробное описание проблемы

```
[04:52:42] Cannot read 10.mood_multiplicative_actionspeed_modifier in mobs.dm:152 :
proc name: do after (/proc/do_after)
  source file: mobs.dm,152
```

**Comment by KIBORG04** [comment]
Наверное, в текущем виде хрен поймешь почему, поэтому наверное можно закрыть.

https://github.com/TauCetiStation/TauCetiClassic/blob/59f44b6e3d503bafd92f14a0d2bd68314a353696/code/__HELPERS/mobs.dm#L152

**Comment by KIBORG04** [comment]
Хотя..... Есть пара кандидатов


https://github.com/TauCetiStation/TauCetiClassic/blob/2ab51bc75c341682cacbf4a879e8fef3148a003e/code/game/mecha/combat/combat.dm#L87-L87

https://github.com/TauCetiStation/TauCetiClassic/blob/2ab51bc75c341682cacbf4a879e8fef3148a003e/code/game/mecha/combat/combat.dm#L105-L105

**Comment by LudwigVonChesterfield** [comment]
код мехов имеет такую же функцию, там что-то типо
```/obj/mech/proc/do_after()```

надо наверное в этих местах добавить `src.` для disambiguation

(удивительно что мехи у нас работают при том что они вызывают не то что должны)

ИЛИ упразднить вот эту фигню у мехов почему оно вообще так

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/8275/files
