### ISSUE TITLE
Проблема с отображением интерфейсов вне основного монитора

### ISSUE THREAD

**Issue by Phoenix4O4** [TauCetiStation/TauCetiClassic#7840]
#### Подробное описание проблемы
Не открываются бьендовские интерфейсы, после того как перенес программу на неосновной экран.
#### Что должно было произойти
Должен был открыться интерфейс на основном экране(ну или дополнительном)

#### Что произошло на самом деле
Открывается 1 интерфейс правильно на неосновном экране, и далее не может открыться ни один интерфейс кроме тгуи.

#### Как повторить
 Открываешь ССку. Все ок, интерфейсы открываются, ты доволен.
Перетаскиваешь ССку на любой другой экран - интерфейс в лучшем случае один раз откроется и все, больше при нажатии кнопок ничего не происходит, ни на одном экране интерфейсы не открываются, рантаймов нет.
#### Дополнительная информация:
 ТГуи интерфейсы открываются нормально.
интерфейсы которые browser.dm, например Активные Тикеты

После загрузки на основном экране. Интерфейсы не открывал.
![image](https://user-images.githubusercontent.com/41524861/130778786-75272dc8-2d42-413f-975b-65c3fc87c367.png)
После нескольких попыток открыть интерфейс.
![image](https://user-images.githubusercontent.com/41524861/130778835-5ad0707e-b292-4d49-aaa5-20045fa08b09.png)

**Comment by Phoenix4O4** [comment]
а) Дело не в бета-версии
б) @volas мб у тебя есть идеи в чем может быть дело?

**Comment by volas** [comment]
https://www.byond.com/forum/post/2401027

я бы предложил попробовать сделать экран с бьендом основным
