### ISSUE TITLE
Небольшие недочеты маппинга, которые бы хотелось пофиксить, но не критично.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#785]
Как уже ясно из названия, это не полноценный ишьюс, а скорее предложение.

Тут есть несколько кусков карты, которые хотелось бы пофикисить, но лень разбиратся в маппинге и программах. Так что просто оставлю это здесь.

1.Починить стену в инженерном отделе, сделать её укрепленной заместо обычной.
![4214](https://cloud.githubusercontent.com/assets/18488106/20234395/5fb77a64-a883-11e6-9008-abdc76328e8d.png)
2. Добавить во все четерех тайловые шлюзы по две вентеляции. А то это прям со всем не очень с одной стоять и ждать там по пол часа.
![1](https://cloud.githubusercontent.com/assets/18488106/20234400/765a3c2a-a883-11e6-8858-136867e358a1.png)
![2](https://cloud.githubusercontent.com/assets/18488106/20234402/7994239c-a883-11e6-9fe9-4b7e22bf9e8f.png)
![3](https://cloud.githubusercontent.com/assets/18488106/20234403/7d25e478-a883-11e6-80c3-d9b90da21d65.png)
3. Добавить ещё один шлюз, на место старого отбытия, где сейчас находятся спасательные поды.
![5](https://cloud.githubusercontent.com/assets/18488106/20234411/997fe920-a883-11e6-8ed8-432f8b623093.png)

4. Доступ, а вернее его отсутствие. Нужно добавить доступ к шлюзам докторам и офицерам. А то это уж прям не серьезно. Риги есть, а выйти через шлюз не могут.

**Comment by SpaiR** [comment]
#786
