### ISSUE TITLE
Рантайм апдета бьюти у зоны

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#7855]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/26389417/131030129-7f79dce0-9cc2-4d47-a63f-bfdf5abd223b.png)

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/7749

Для формальности отставлю

**Comment by LudwigVonChesterfield** [comment]
думаю что должно было быть пофикшено в https://github.com/TauCetiStation/TauCetiClassic/pull/7749/commits/c4cb28de163bab38ad162e7661f04384ddf1a7bb

и не могу восспроизвести, но ещё попробую выловить на живом сервере

**Comment by LudwigVonChesterfield** [comment]
пытался отловить, но не смог. отпишу сюда для будущих добрых саморитян

происходит (очевидно?) когда моб зашёл в зону, в которой и был, при этом не выйдя из неё (?)

смог гарантированно восспроизвести мехом заходящим из космоса в любую зону на станции. когда выходишь из зоны в космос - сигнал выхода не вызывался, и когда заходил обратно в зону - этот рантайм. дальше этого не выяснил

**Comment by KIBORG04** [comment]
Вроде +- пофикшено было когда-то удалением бьюти у айтеом.
