### ISSUE TITLE
Флаффы не считаются одеждой

### ISSUE THREAD

**Issue by NeOchenLord** [TauCetiStation/TauCetiClassic#7866]
#### Подробное описание проблемы

Система настроения Людука не считает флафф одеждой, из-за чего накидывается дебафф, будто я хожу голым.

#### Что должно было произойти

Моя флафф-униформа скрывает мое тело от чужих глаз

#### Что произошло на самом деле

Я грущу потому что якобы голый

#### Как повторить

Надеть флафф униформу

#### Дополнительная информация:

ПР Людука - https://github.com/TauCetiStation/TauCetiClassic/pull/7749

**Comment by LudwigVonChesterfield** [comment]
```
/obj/item/clothing/under/custom
	name = "Custom uniform"
	body_parts_covered = 0
```

у всей флафф одежды прописано что она ничего не прикрывает
