### ISSUE TITLE
Орбит у призраков после 514

### ISSUE THREAD

**Issue by UDaV73rus** [TauCetiStation/TauCetiClassic#7869]
#### Подробное описание проблемы
На первом орбите всё хорошо, но если второй раз на этот же объект орбитнуться, то анимация будет дергаться

#### Что произошло на самом деле
Анимация после каждого периода вращения дергается

#### Как повторить
Второй раз орбитнуть ту же вещь

#### Дополнительная информация:
Новый 514 бьенд сломал
Анимация сбрасывается, а таймер где-то нет

**Comment by volas** [comment]
Есть проблема в некоторых минорных версиях, скорее всего ты не на последней 514
