### ISSUE TITLE
Термалы не видят в темноте

### ISSUE THREAD

**Issue by Misakiwa** [TauCetiStation/TauCetiClassic#7879]
#### Подробное описание проблемы
Термалы не видят в темноте
#### Что должно было произойти
Термалы видят в темноте
#### Что произошло на самом деле
Термалы не видят в темноте
#### Как повторить
Надеть термалы

**Comment by KIBORG04** [comment]
и не должны

**Comment by Misakiwa** [comment]
Почему ТЕРМАЛЫ не должны видеть в темноте, когда они видят через стену, но если чел через стену в темноте уже не видят. 
Тут 0 логики и нерф бессмысленный.
(Хотя я и не против, все равно их почти только хос носит)

**Comment by EdlerN** [comment]
Я бы сказал тут хреновое описание проблемы. Термалы и не должны работать как ПНВ. С другой стороны, если с планами света сломалась возможность видеть людей в темноте - это уже совсем другая проблема.

**Comment by Misakiwa** [comment]
Еще термалы хоть и не видят в темноте, похоже видят глаза лингов, не уверен, что так и должно быть, уведомляю

**Comment by KIBORG04** [comment]
Зовем мираклера и говорим что он все сломал.
