### ISSUE TITLE
Не спавнятся разгрузки в шкафчиках брига.

### ISSUE THREAD

**Issue by ThePunisher95** [TauCetiStation/TauCetiClassic#788]
#### Подробное описание проблемы
У щитсечной снаряги есть три вида спрайтов, и так называемые разгрузки (webbing net) спавнятся в шкафчиках раздевалки только при стандартных текстурах.
#### Что должно было произойти
Все три вида текстур должны иметь спавн разгрузок.
#### Что произошло на самом деле
Разгрузки спавнятся только при стандартных текстурах.
#### Как повторить
Зайти в раунд за щитсека и молить рандом о пощаде.
#### Дополнительная информация:
Всё таки разгурзки очень нужная вещь для щитсека, ведь постоянно не хватает места в сумке, а тут такое вот западло.

**Comment by Skippeer12** [comment]
Не баг а фича!

**Comment by YulianR** [comment]
Спасибо мистер могилец

**Comment by Skyrull** [comment]
Суть в том, что каждый набор имеет свой плюс. В стандарте это разгрузка.

**Comment by Skippeer12** [comment]
Не пали фичи в ишусах! Ирод

**Comment by WallShrabnic** [comment]
Это фича, закрывай

**Comment by SpaiR** [comment]
не актуально, т.к. теперь появились слоты в стандартной броне
