### ISSUE TITLE
Беды с археологическими находками

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#7880]
#### Подробное описание проблемы
Согласно коду, находку можно выкопать без разрушения только с 10% шансом без генератора поля(Suspension Field Generator), но они копаются спокойно и без него. 
#### Что должно было произойти
Археологи ходят с генератором поля, дабы не просрать свои находки
#### Что произошло на самом деле
Никто с ним не ходит, ибо он и не нужен.
#### Как повторить
1) Попробовать покопать находки без генератора поля.
2) Убедиться, что только в редких случаях они рассыпаются.
#### Дополнительная информация:
̊͠O'- ײ-͆̓̓͡ o̊

**Comment by Zmey25** [comment]
Они все так же имеют какой-то шанс развалиться без поля

**Comment by Daoprotoss** [comment]
То ли я был крайне везучим, то ли сейчас больно невезучий, но теперь она почти всегда ломается без поля
