### ISSUE TITLE
Тритор ИИ без нулевого закона

### ISSUE THREAD

**Issue by FBitSafe** [TauCetiStation/TauCetiClassic#7893]
#### Подробное описание проблемы

Во время игры на ИИ мне выпала роль, после на станции появился Блоб, тем самым **заменив** нулевой закон на новый, после его смерти роль осталась, а закона не осталось

#### Что должно было произойти

два нулевых закона наверное

#### Что произошло на самом деле

После смерти блоба спец законов не осталось

#### Как повторить

Зайти за ИИ> выдать роль тритора> заспавнить блоба> убить блоба

**Comment by Motykoo** [comment]
Актуально

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/8278
