### ISSUE TITLE
Снайперская винтовка кнокает сквозь любую броню

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#7896]
#### Подробное описание проблемы
Броня вроде как должна защищать от кноков лазерной снайперки,но хоть в броню ерт стреляй,хоть в обычную,хоть в аблятивную - падение,разве что чуть меньше лежать.
#### Что должно было произойти
офицер в аблятивке получает заряд лазерки и 20 бёрна спокойно стоя на ногах
#### Что произошло на самом деле
офицер в аблятивке получает заряд лазерки,падает и умирает от трейтора с глоком
#### Как повторить
выстрелить в человека одетого в аблятивную броню/риг сб/etc снайперской винтовкой из карго.

**Comment by AndroBetel** [comment]
почему вообще луч лазера на жопу опрокидывает

**Comment by UDaV73rus** [comment]
Опрокидывает чтобы чувствовался импакт и мощь
Нужен микростан чтобы упал-встал. Можно было бы повесить и на многие дургие вещи
