### ISSUE TITLE
Баг с настроением(мокрая одежда)

### ISSUE THREAD

**Issue by Pimap3** [TauCetiStation/TauCetiClassic#7898]
#### Подробное описание проблемы
После того как помыл и посушил одежду(а также надел её). У персонажа появляется мудлет, что ему не нравится носить мокрую одежду, хотя она полностью сухая. Настроение конечно же падает
#### Что должно было произойти
Вы посушили и одели одежду, вам приятно
#### Что произошло на самом деле
Одежда мокрая.
#### Как повторить
Помыть в раковину одежду, а потом её посушить сушилкой для рук
#### Дополнительная информация:
Issue reported from  Round ID: 44306 (Tau Ceti Classic (RU))
Testmerges: ```#7860 #7749 #7701 #7519 ```
Reporting client version: 514.1566

**Comment by LudwigVonChesterfield** [comment]
![image](https://user-images.githubusercontent.com/17705613/131859254-f1ed0c43-ac2c-41ad-ad31-1ea70032db87.png)

Я надеюсь тут имеется ввиду что не пропал мудлет, а не именно что одежда осталась мокрой.

**Comment by Pimap3** [comment]
Надо было уточнить. Да мудлет не пропал, но одежда сухая
