### ISSUE TITLE
Мусорка в вирусологии не в том месте

### ISSUE THREAD

**Issue by YulianR** [TauCetiStation/TauCetiClassic#791]
#### Подробное описание проблемы
![dreamseeker_2016-11-13_18-54-37](https://cloud.githubusercontent.com/assets/6051766/20247360/d2fe79aa-a9d2-11e6-8232-1e8faaeaca28.png)
#### Что должно было произойти
Труп улетает дальше в спейс
#### Что произошло на самом деле

Мусор врезается в спутник

![dreamseeker_2016-11-13_18-54-37](https://cloud.githubusercontent.com/assets/6051766/20247360/d2fe79aa-a9d2-11e6-8232-1e8faaeaca28.png)
#### Как повторить
Выкинуть что-либо через мусорку

**Comment by StrikS** [comment]
Хехех, это фича. Мусорка справляется со своей задачей, а вот трупы уже бессознательных пациентов меда уже не покидаешь на другой слой. :D Хотя их и на этом едва найдут.

**Comment by igigin** [comment]
Нет, не фича. Просто тот кто переносил спутник совершенно не подумал про то, что он на пути следования всякого мусора в опенспесс.

**Comment by StrikS** [comment]
Куршана обидеть может каждый!
