### ISSUE TITLE
При экзамине контейнера с химикатами видно точное количество каждого химиката

### ISSUE THREAD

**Issue by Raschert0** [TauCetiStation/TauCetiClassic#793]
#### Подробное описание проблемы
В названии
#### Что должно было произойти
Должно было видно только общее количество химикатов без названий
#### Что произошло на самом деле
Видно было количество и названия
#### Как повторить
Налить что-нибудь в пробирку

**Comment by Skippeer12** [comment]
Хейтер, прекрати.
