### ISSUE TITLE
При экзамине огнетушителя, который лежит в рюкзаке, не выводит, сколько в нём осталось воды

### ISSUE THREAD

**Issue by Raschert0** [TauCetiStation/TauCetiClassic#794]
#### Подробное описание проблемы
В названии
#### Что должно было произойти
Должно было вывести количество воды
#### Что произошло на самом деле
Количество воды не было выведено
#### Как повторить
Положить огнетушитель в рюкзак и заэкзаминить его

**Comment by Skyrull** [comment]
Там вроде со всеми емкостями такое.

**Comment by Skippeer12** [comment]
Не баг, а фича.
Чтобы посмотреть сколько там чего, надо взять это что-то в руку. Пусть будет!

**Comment by Raschert0** [comment]
Не фича, а баг
