### ISSUE TITLE
Отсутствует кнопка в консоли восстановления флоры

### ISSUE THREAD

**Issue by KsarZ** [TauCetiStation/TauCetiClassic#7968]
#### Подробное описание проблемы: В консоли восстановления флоры (flora reconstitution console) на исследовательском аванпосте отсутствует кнопка
![image](https://user-images.githubusercontent.com/86472011/133073377-515e0610-4d1b-411c-9691-6e148142cf76.png)

**Comment by FBitSafe** [comment]
ты собрал все 5 генов?

**Comment by KsarZ** [comment]
> ты собрал все 5 генов?

ген был только один, но я всё же каким-то образом вызвал баг который позволил пихнуть один и тот же ген в несколько слотов, но это никак не помогло

**Comment by Daoprotoss** [comment]
А в чем собственно баг, кнопка появляется после сбора 5 правильно поставленных и подходящих генов, на картинке только один ген.

**Comment by KsarZ** [comment]
> А в чем собственно баг, кнопка появляется после сбора 5 правильно поставленных и подходящих генов, на картинке только один ген.

и где же ты прикажешь эти гены искать?

**Comment by Daoprotoss** [comment]
Ну... даже незнаю... попробуй на астеройде поискать камни с находкой имеющие тип материала "Trace Organic Cells"

**Comment by KsarZ** [comment]
> Ну... даже незнаю... попробуй на астеройде поискать камни с находкой имеющие тип материала "Trace Organic Cells"

так это такой камень собственно и был, только вот был там только один ген

**Comment by Daoprotoss** [comment]
Ну это не баг, далеко не факт, что за один камень ты сможешь собрать все гены для клонирования, чаще всего нужно 2-3 камня с окаменелостями чтобы собрать полноценную хероборину

**Comment by KsarZ** [comment]
> Ну это не баг, далеко не факт, что за один камень ты сможешь собрать все гены для клонирования, чаще всего нужно 2-3 камня с окаменелостями чтобы собрать полноценную хероборину

тогда пардон, я об этом не знал
