### ISSUE TITLE
[Proposal] Переместить консоль реконструкции фауны в ксеноархеологии

### ISSUE THREAD

**Issue by Daoprotoss** [TauCetiStation/TauCetiClassic#7971]
#### Подробное описание проблемы
Консоль реконструкции расположена крайне плохо, чтобы реконструировать какую-то животину археолог должен зайти в камеру изоляцию, нажать кнопку клонирования и потом резко начать бежать, ибо есть такой немаленький шанс того, что тебе попадется агрессивная зараза, которая вполне способна убить зазевавшегося ученого
#### Что должно было произойти
Консоль должна быть расположена за стеклом, в то время как капсула с животиной в камере изоляции(как в ксенобиологии)
#### Что произошло на самом деле
Консоль расположена в самой камере, нехилый шанс не успеть вовремя убежать от появившейся твари
#### Как повторить
1) Зайти в камеру изоляцию и нажать кнопку clone
2) Не успеть убежать от появившегося чужого и получить по лицу
#### Дополнительная информация:
̊͠o‘-ײ-͆̓̓͡o̊

**Comment by Rahmanio** [comment]
@Daoprotoss Переместить ту консоль некуда, надо будет увеличивать пространство. Займусь небольшим ремапом.

**Comment by Daoprotoss** [comment]
Как хочешь, главное, чтоб сама консолька была не в изоляторе

**Comment by Rahmanio** [comment]
> Как хочешь, главное, чтоб сама консолька была не в изоляторе

Трабл в том, что она работает только рядом с клонилкой, не знаю получится ли за пределы изолятора вынести и чтобы всё работало.

**Comment by Daoprotoss** [comment]
Ну чисто в теории, можно просто увеличить дальность работы изменив в 98 строчку эту единицу, это решит проблему и не заставит переделывать половину комнаты
https://github.com/TauCetiStation/TauCetiClassic/blob/65dd75742a6e792496eb595d7a93fcdc58b626d3/code/modules/research/xenoarchaeology/genetics/reconstitutor.dm#L97-L103

**Comment by Rahmanio** [comment]
> Ну чисто в теории, можно просто увеличить дальность работы изменив в 98 строчку эту единицу, это решит проблему и не заставит переделывать половину комнаты @Rahmanio
> https://github.com/TauCetiStation/TauCetiClassic/blob/65dd75742a6e792496eb595d7a93fcdc58b626d3/code/modules/research/xenoarchaeology/genetics/reconstitutor.dm#L97-L103

Можно будет попробовать посмотреть. Так ты наверное и сам можешь всё сделать или как?

**Comment by Daoprotoss** [comment]
Я верю в тебя Рахмано, вся надежда юных археологов спастись от неминуемой смерти от лап проклятых ксеносов лежит в твоих руках...
(Мне просто влом с гитхабом и мапой разбираться)

**Comment by Rahmanio** [comment]
> Я верю в тебя Рахмано, вся надежда юных археологов спастись от неминуемой смерти от лап проклятых ксеносов лежит в твоих руках...
> (Мне просто влом с гитхабом и мапой разбираться)

Проблему с дистанцией решил, но комнату переделывать надо, так как если просто воткнуть консоль куда попало, будет некрасиво.

**Comment by Daoprotoss** [comment]
Тут уже дело твое
