### ISSUE TITLE
Большинство фич Иана при игре за боррера внутри него ограничены

### ISSUE THREAD

**Issue by ChewedGum** [TauCetiStation/TauCetiClassic#7979]
#### Подробное описание проблемы
Если боррер залезает внутрь Иана то при захвате контроля большинство фич иана не работают. Нету ХУДа, инвентаря, нельзя переключать интент, брать вещи, открывать двери через клик (если таранить их то можно), открывать ящики и т.д.
#### Что должно было произойти
Можно.
#### Что произошло на самом деле
Нельзя.
#### Как повторить
Взять боррера, залезть в Иана, посмотреть на то что он может и не может, прослезиться.
#### Дополнительная информация:
Было испытано в раунде 44613, админ пытался помочь но не вышло.

**Comment by KIBORG04** [comment]
Донать

**Comment by ChewedGum** [comment]
Пофикси.
