### ISSUE TITLE
Цель "сбежать и остаться свободным" не засчитывается так, как нужно.

### ISSUE THREAD

**Issue by PirogSema** [TauCetiStation/TauCetiClassic#7988]
#### Подробное описание проблемы
Цель "Escape on the shuttle or an escape pod alive and free." засчитывается даже если цель была в бриге шаттла в наручниках.
#### Что должно было произойти
Цель не защиталась как выполненная.
#### Что произошло на самом деле
Задание выполнено.
#### Как повторить
Сесть с этой целью в бриг шаттла.
#### Дополнительная информация:
Issue reported from  Round ID: 44654 (Tau Ceti Classic (RU))
Testmerges: ```#7918 #7822 ```
Reporting client version: 514.1564
![изображение](https://user-images.githubusercontent.com/22032604/133601146-dead7556-a444-4b61-869c-da080d6a85c9.png)
![изображение](https://user-images.githubusercontent.com/22032604/133601167-8fcd53ba-5630-435b-a6ee-dfc35598d390.png)

**Comment by KIBORG04** [comment]
Так это админ, он себе подкрутил
