### ISSUE TITLE
Доступ у Advanced Scanner в криминалистской

### ISSUE THREAD

**Issue by StrikS** [TauCetiStation/TauCetiClassic#799]
#### Подробное описание проблемы
Детектив не может пользоваться продвинутым сканером в криминалистке, даже если ему открыли отсек. (Борг, ИИ, Хос) 
#### Что должно было произойти
Если детектив в попал в криминалистику отсек он может спокойно пользоваться оборудованием.
#### Дополнительная информация:
При клике по терминалу появляется окно со ссылкой "Log In", при нажатии ничего не происходит.
Возможно стоит снять любые доступы на эту консоль, чтобы желающие могли залогинится и стереть улики.

**Comment by Dennok** [comment]
снять любые доступы на эту консоль, чтобы желающие могли залогинится и стереть улики.
DA

**Comment by WallShrabnic** [comment]
Доступ получают через ХоПа или капитана, а не борга/ИИ/ХоСа

**Comment by dearprincesscelestia** [comment]
> снять любые доступы на эту консоль, чтобы желающие могли залогинится и стереть улики.
DA

Да. Так и надо.

**Comment by Dennok** [comment]
Зачем тогда там есть кнопочка лога? Может воообще все доступы выпилите?

**Comment by StrikS** [comment]
Не надо сгущать краски, тут доступ вполне может быть убран, это создаст дополнительные игровые возможности/ситуации.

**Comment by Dennok** [comment]
А если убрать все доступы это даст еще больше игровых ситуаций.

**Comment by SourcePony** [comment]
Давайте ка я продолжу товарища Стрикса, с которым абсолютли согласен.

**Подробное описание проблемы**

Детектив - самая бесполезная профессия на станции, даже бесполезнее какого-нибудь приватного очка или ассистента, если на станции нету криминалиста.
Для того чтобы расследовать что-то без криминалиста (что, конечно, можно сделать) приходится потратить очень много времени бегая от офиса приватных очек, которые иногда застраиваются там же и начинают лить говно в уши про то что у вас есть свое оборудование до всратого меда где вскрытие не всегда сделают, потому что откачивают бедных ассистентов, бесконечными толпами прущих с ожогами рук, или, боже, что еще хуже, с качалки. 
А вот за это время тебя бесконечно смогут задолбать те же СБшники, не нюхавшие работы детектива, очередной разлитой краской на полу в техах. 

**Что должно было произойти**

Детектив должен быть полностью автономной профессией, практически не зависящей от других и свободен в своих действиях, чтобы уделять больше времени расследованию и работе с свидетелями.

**Что произошло на самом деле**

Криминалист не зашел в катку/Отыгрывает пьяного ирландца

**Как повторить**

Зайти за детектива, когда в раунде отсутствует криминалист/За криминалистов заходят пофанится

**Comment by SourcePony** [comment]
Ах да, отдельное слово про ХоПа и Капитана. Если вы уж и говорите, что доступ получается через них, так заходите за них. Давно я вижу этих двоих в катках, легче ассистонта взять, да.

**Comment by WallShrabnic** [comment]
Никто не понимает сути (тм) детектива, заставляя его подрабатывать и криминалистом, da

**Comment by sovok4** [comment]
Посмотрите любой фильм, связанный с раскрытием преступлений, от сериалов про ментов до зарубежных кинолент. Детектив там занимается опросом свидетелей и подозреваемых, сбором улик и, иногда, участвует в задержании. Лабораторным анализом улик и вскрытиями всегда занимается криминалист.
А профессия бесполезная, потому что офицеры слишком много на себя берут, а за детектива по большей части играют какие-то клоуны, типа женщин с аниме-прической до пола.

**Comment by Belfogor** [comment]
В тех же фильмах криминалист всегда ЕСТЬ. В реалиях ССки, если кто-то из этой парочки не зашел в игру, второй автоматически становится бесполезным куском дерьма.

**Comment by WallShrabnic** [comment]
Криминалист в наших реалиях ещё и бесполезен, если знать пару фич

**Comment by sovok4** [comment]
Не зашел чемист или СМО - генетик клепает умственно отсталых клонов, а ботаник выращивает обычные овощи для повара, который тоже не зашел. Без саентиста роботех может собрать только убогого рипли, а без шахтера ни саентист, ни роботех не могут во что-то интересное.
Нехватка персонала - это нормально. Вот только для любимого собе исключений быть не должно: машина закона должна работать всегда, а её шестеренки должны быть универсальными и взаимозаменяющимися.

**Comment by StrikS** [comment]
Меня устраивает текущий мапинг и текущее положение вещей, мне не в лом бегать от офиса частного детектива до митбея. Но если криминалист отсутствует, а тебя запустили в его кабинет(например у тебя сидит в допросной подозреваемый, а до офиса ЧД бежать долго), то все оборудование должно исправно работать, а не ставить палки в колеса.

**Comment by SourcePony** [comment]
Хочу посмотреть любой фильм связанный с деятельностью детективов в 25-26 веке.

**Comment by WallShrabnic** [comment]
Детектив тоже, охранник с летальным дробовиком - наш ответ преступному скаму

**Comment by Balphagore** [comment]
Почему детектив нехрена не делает? Потому что болтовню берут на себя офицеры, так как отдавая преступника другому работнику, рискуешь все просрать. Сколько раз было так, что передаешь детективу взятого с поличным преступника, кратко обрисовываешь ситуацию и уходишь дальше воевать, а детектив его отпускает, потому что что-то упустил, не расслышал, недопонял, задержанный его обдурил или детектив просто тупой. И это - нефига не интересная ситуация, это тупость. Поэтому опытные офицеры, которые не хотят все просрать ведут преступника от задержания до камеры (а иногда надо еще и в камере за ним приглядывать, ибо он может позвать АВД или ХОСа, нассать им в уши и его отпустят) В итоге детектив просто нехрена не делает, а чаще всего путается под ногами даже без нормальной аммуниции или бухает в баре.

Так что триаду офицеры-детектив-криминалист, по моему, надо как-то менять. Отсылки к РНД и медбею тут некорректны. Без мехов станция проживет, за варку алкизина врачом ради возврата игрока в раунд, думаю, пинать никто не будет, и чаще всего так и происходит. А вот если охрана не может поймать тритора просто потому что никто не зашел за криминалиста, то это уже херово. Тритор, выполнив рольку, скорее всего, заляжет на дно (гринтекст же важнее) и раунд скатится в аутизм. И это потому что на терминале доступ только криминалиста и ХОСа через карту. Даже ИИ и борги не могут ничего поделать (в химию же надо только как-то зайти и придумать обоснование варке алкизина, а тут вообще практически нет альтернатив) 

То есть нормальное исследование улик на станции доступно только в присутствии криминалиста, или если этим озаботится ХОС, или если выдадут доступ капитан и ХОП. Но с главами у нас часто беда даже в раундах на 60+ рыл, все любят гонять за ассистентов. Да и даже если глав полный комплект - на них рассчитывать не стоит, у них свои проблемы, а иногда ХОП и капитан сами преступники. Но в раундах с генками/триторами исследование улик бывает критически важно. Да и в реве/культе частенько не помешает. Вскрытие продублировано, его можно провести и в медбее и в криминалистской и это хорошо. А вот с расследованиями совсем беда. Почти все функции детектива берут на себя офицеры, а функции криминалиста не продублированы вообще (кроме вскрытия).

А ведь охрана, это не аутичный РНД и не медбей, где можно немного использовать мету (Они не так сильно влияют на раунд в целом).  Охрана - первая (а иногда и последняя) линия обороны. Сколько раундов скатилось в говно из-за того, что некому было открыть оружейку? И это при том что открыть ее может Варден, ХОС, капитан, ХОП, ИИ, борги. А сколько раундов скатилось в говно, потому что роботисты не собрали Рипли шахтерам-аутистам? Охрана должна быть гибкой, мобильной и достаточно автономной, но фактически, без криминалиста она может только лупить клоуна станбатонами и гоняться за ассистентами, то есть ловить тех, кто попался с поличным. Никаких расследований. Поймать скрытного и умного предателя невозможно чисто физически, так как улики даже если есть, с ними ничего не сделаешь. Так что менять что-то надо. Отдельный офис для криминалиста и детектива - это круто, но это убило детектива, он теперь частный сыщик с пистолетом и доступом в бриг.

Я вижу несколько вариантов. 
Самый очевидный - дать возможность ИИ и борготе давать доступ к криминалистскому оборудованию. Это не потребует ни ремапов, ни изменений доступов, но в критический момент можно будет провести расследование даже силами офицеров (иногда такое необходимо, надо только обыграть это). Это не решит проблему полностью, но сильно упростит ее. Но я не знаю, так ли просто это реализовать. Фактически - это возможность за синтетиков логиниться в аппаратуру аналогично наличию карты. Может такое тупо невозможно накодить.

Более геморройный, но и более сбалансированный - ремап и дублирование доступа. Перенести оборудование в склад вещдоков и сделать туда дополнительную дверь в коридор, с доступом криминалисту. Сейчас, фактически, криминалист, изучающий улики - не может поместить их на хранение, а офицерам на улики обычно похрен, в итоге они чаще всего валяются в кабинете криминалиста, куда даже варден доступа не имеет (вроде), а склад вещдоков не используется вообще. Еще криминалисту надо вернуть фотоаппарат и диктофон (как же фотографирование трупов и записи собственных мыслей на диктофон? Это же классика) и ими можно забить место, которое занимала аппаратура. И продублировать доступ к аппаратуре для детектива. Тогда криминалист и детектив могут как и раньше аутировать каждый в свое, но в случае необходимости будут взаимозаменять друг друга. 

Ну и третий - самый прямолинейный и простой: дать детективу доступ криминалиста. Просто и без затей. Так было раньше и все было нормально. Люди играли и за детективов и за криминалистов и получались интересные расследования. Детектив был фактически старшим в группе. И все было зашибись. А сейчас почему-то все думают, что если дать детективу такой доступ, то криминалиста надо сразу удалять ибо он будет не нужен. Да зачем? Охрана либо аутирует в полном составе, либо так завалена работой, что дело найдется для всех.

**Comment by WallShrabnic** [comment]
Раньше за криминалиста заходило 2.5 аутиста, которые в принципе не могли жаловаться. Но проблема тут в том, что никто не понимает сути (тм) работы детектива

**Comment by RigoSex** [comment]
`Самый очевидный - дать возможность ИИ и борготе давать доступ к криминалистскому `
На текущий момент проблемы не существует, ИИ и боргота открывают эту консоль и логинятся без проблем. Да, дефективу все еще самый бесполезный во всем отделе, бесполезнее клована.
От скуки они лезут стреляться и первыми идут в ряды траллов и реверов.

**Comment by KuzyXD** [comment]
Директор и администраторы считают, что детектив не должен заниматься этим (но может). Его стезя в вынюхивании информации и допросах. @EdlerN @volas, что делать с этим ишшью?
