### ISSUE TITLE
[Proposal] Сделать лежачего клоуна скользким

### ISSUE THREAD

**Issue by Zickusable** [TauCetiStation/TauCetiClassic#7994]
#### Пропозал
Лежачий клоун будет скользким как банан. Даже после смерти клоун будет смишным. Он станет независимым от скользких предметов. Даже после смерти клоун будет смешным.
Бежим навстречу ГСБ, падаем в кравл перед ним, ХОНК, ждем своей реанимации.

**Comment by TEXH4Pb** [comment]
А как клоуна задерживать то тогда? При взятии лежачего человека в синий граб кукла автоматически заползает на жертву, разве нет?

**Comment by Zickusable** [comment]
В пропозале не написано про срок, там написано про реанимацию.
Если прям приспичит, можно и так раздеть, придерживая на полу дубинками.

**Comment by UDaV73rus** [comment]
Вот как работают суды при анкапе

**Comment by kiVts** [comment]
Сделать что пока на клоуне его пда на клофуне можно подскальзнутся, придется снимать пда
