### ISSUE TITLE
У хирургов нет доступа в хирургию

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#800]
#### Подробное описание проблемы
У хирурга нет доступа в хирургию и ее подсобку.
#### Что должно было произойти
Доступ есть.
#### Что произошло на самом деле
Доступа нет.
#### Как повторить
Стать хирургом, попытаться зайти в хирургию.
#### Дополнительная информация:
Возможно и у других подпроф тоже.

Проблема появилась после мержа [этого](https://github.com/TauCetiStation/TauCetiClassic/pull/748)

**Comment by StrikS** [comment]
Хирургия не нужна. Сейчас пофикшу.

**Comment by StrikS** [comment]
Еще раз все протестил, все работает как положено. Даже проверил то, что если пикаешь парамедика, то доступы у хирургов меняются на доступы парамедика, но это не так. Буду сейчас досконально тестить, там две строчки всего, странно что там есть место багу, да еще плавающему.
