### ISSUE TITLE
Borer's god mode

### ISSUE THREAD

**Issue by Rahmanio** [TauCetiStation/TauCetiClassic#8009]
#### Подробное описание проблемы
Борер даже после смерти может быть управляемым. На секунду вы оживёте и сможете двигаться / залезть в кого-то и тд, но нужно иметь очень быстрые руки.
#### Что должно было произойти
Борер после смерти не может быть управляемым.
#### Что произошло на самом деле
The borer is dead?(двигается)
#### Как повторить
Для этого необходимо нажать гост, а потом вернуться в тело.

**Comment by Rogostick** [comment]
Действительно рабочая схема- не порядок.
