### ISSUE TITLE
Съедается первая буква в чате эссенций

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#8024]
#### Подробное описание проблемы
Съедается первая буква в чате эссенций(:ф/:a)
#### Что должно было произойти
никаких проблем нет,все буквы не месте.
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/84613249/134348824-9189465e-b6da-43f4-93b2-f7cb20f2599e.png)

#### Как повторить
быть убитым генокрадом,написать что то в канал его жертв

**Comment by Rahmanio** [comment]
Я надеюсь это не пр Перверта сломал, потому что недавно всё было ок.
