### ISSUE TITLE
[Runtime] помыл туфли - призвал кота.

### ISSUE THREAD

**Issue by QWxiZX** [TauCetiStation/TauCetiClassic#8031]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/70110199/134787930-896ada1b-218d-4ef2-bc88-8ffc317692d0.png)
![image](https://user-images.githubusercontent.com/70110199/134787932-24e5ddbd-c842-41c0-aeb2-214c08e70aaf.png)
![image](https://user-images.githubusercontent.com/70110199/134787937-ab521a44-a180-4c8b-9d00-8d13b98efadb.png)

#### Что должно было произойти
![image](https://user-images.githubusercontent.com/70110199/134787940-1201b203-8101-4c52-987b-8d68b3d7acc2.png)

#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/70110199/134787941-76192191-c12c-41da-839f-d35e54ef1b30.png)

#### Как повторить
![image](https://user-images.githubusercontent.com/70110199/134787945-be758c1e-56af-4a51-99e9-f991f16d22f0.png)

#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/70110199/134787949-2f1039c6-b8d0-4d83-b591-dff9130732ec.png)

**Comment by KIBORG04** [comment]
походу че-то с настроениями

**Comment by Rogostick** [comment]
Интересно что при повторении рантайм не вызывается

**Comment by LudwigVonChesterfield** [comment]
В какой-то момент пофиксилось.
