### ISSUE TITLE
[Runtime] Рантайм

### ISSUE THREAD

**Issue by Rogostick** [TauCetiStation/TauCetiClassic#8036]
#### Подробное описание проблемы
Рантайм
#### Что должно было произойти
Ничего
#### Что произошло на самом деле
Рантайм "Зафиксирована аномалия #312"
#### Как повторить
Похоже добить мага в крите.
#### Дополнительная информация:
Issue reported from  Round ID: 44960 (Tau Ceti Classic (RU))
Testmerges: ```#7969 #7918 #7822 #7760 ```
Reporting client version: 514.1565

**Comment by 4310V343k** [comment]
Может хоть номер раунда?

**Comment by Rogostick** [comment]
> Может хоть номер раунда?
конечно можно
![Screenshot_13](https://user-images.githubusercontent.com/89801803/134820608-cfa2421b-ff41-46e6-bdc5-9e4a4b0452c6.png)

**Comment by KIBORG04** [comment]
![image](https://user-images.githubusercontent.com/26389417/134822543-a68da8ba-22e7-4684-8357-89f0f38b352f.png)

Ладно

**Comment by 4310V343k** [comment]
Я слепой, бывает
