### ISSUE TITLE
В шатоле прибытия нет монтирвки

### ISSUE THREAD

**Issue by raduser** [TauCetiStation/TauCetiClassic#804]
#### Подробное описание проблемы
Нет монтировки в шатоле прибытия
#### Что должно было произойти
Должна быть монтировка
#### Что произошло на самом деле
Её нет
#### Как повторить
Зайти в шатол и посмотреть
#### Дополнительная информация:
Очень нужна монтировка

**Comment by WallShrabnic** [comment]
Зачем?

**Comment by raduser** [comment]
Она там всегда была (точнее красный тулбокс), в связи с этим часто не выйти из шаттла.

**Comment by skvazarb** [comment]
Сейчас створки открываются без ломика и инженерного доступа, поэтому актуальность его нахождения там под вопросом.

**Comment by Flankir** [comment]
Если есть разница давлений створки открываются только ломом.

**Comment by igigin** [comment]
А если разница давлений не в пределе норм, то может и не стоит их открывать?

**Comment by Raschert0** [comment]
>А если разница давлений не в пределе норм, то может и не стоит их открывать?

Да не, бред какой-то

**Comment by Flankir** [comment]
Если я диона то почему бы мне их таки не открыть? Глядишь и скафандры принести или давление восстановить.

**Comment by igigin** [comment]
А, ну а шатол пускай летит назад без воздуха, ладно тогда.

**Comment by Flankir** [comment]
Там какбе шлюз и разгерма только за дверью ведущей на станцию из шлюза но блокируются обе створки.

**Comment by igigin** [comment]
>только за дверью ведущей на станцию

Такие то истории

**Comment by Flankir** [comment]
а ты типа не в курсе что разгерма в доках не означает разгерму внутри шлюза между дверями? Так зачем блокировтаь створку ведущю в шлюз из шаттла?

**Comment by Parterson** [comment]
А если света нет?
