### ISSUE TITLE
Немые смеются со звуком

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#8040]
#### Подробное описание проблемы
Если прописать *laugh за немого то можно услышать звук смеха
#### Что должно было произойти
laughs silently и без звуков
#### Что произошло на самом деле
laughs silently и со звуками
#### Как повторить
взять куклу с перком mute и прописать *laugh

**Comment by Akellazp** [comment]
Кто сказал что немые не могут производить звуки?

**Comment by simb11** [comment]
раз немые не могут кричать и стонать,то они и не должны смеяться со звуком.
