### ISSUE TITLE
Карта БЩ не воспринимается консолью медзаписей

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#8055]
#### Подробное описание проблемы
Если попытаться пихнуть карту БЩ в консоль медзаписей, то карта туда "пихнется" но никаких изменений в интерфейсе консоли не произойдет
#### Что должно было произойти
Консоль захавала мою карту, кнопочка [---------] поменялась на нейм карты, я ковыряюсь в консольке
#### Что произошло на самом деле
Ничего не произошло
#### Как повторить
Открыть медзаписи при помощи карты бщ

**Comment by KIBORG04** [comment]
Это кстати не проблема бш и вроде как пофикшено
