### ISSUE TITLE
Мехи не бьют в мили

### ISSUE THREAD

**Issue by Misakiwa** [TauCetiStation/TauCetiClassic#8076]
#### Подробное описание проблемы
Мехи не бьют в мили
#### Что должно было произойти
бьют
#### Что произошло на самом деле
нет
#### Как повторить
попробовать на харме ударить мехом в мили
#### Дополнительная информация:
проверял на дарк гигаксе

**Comment by KIBORG04** [comment]
не бьют вроде только комбаты

**Comment by Misakiwa** [comment]
> не бьют вроде только комбат мехи

А в чем смысл?
Это же очень сильный нерф, дефолтное оружие у того же дарк гигакса очень мало дамажит, приходилось всегда панчами добивать чтоб человек не встал и не задуэлил тебя ионкой, сейчас это очень слабый мех, медленный, умирающий за 4 болта ионки без мили панчей.
Раньше все панчи работали и было хорошо. 
?

**Comment by Misakiwa** [comment]
![image](https://user-images.githubusercontent.com/36154069/136237871-60f1df80-baf6-47d5-b45c-2718a90324a7.png)
Ударил 1 раз на обычном гигаксе, заспавнил рантайма, больше ударить не смог.

**Comment by Misakiwa** [comment]
Кароче протестил, любой боевой мех может ударить ровно 1 раз, фаерфайтер не может ударить вовсе, как и другие гражданские мехи, подозреваю.

Баг.

**Comment by Misakiwa** [comment]
Дрель, собственно, работает, но она не панчит, а *дриллит*
