### ISSUE TITLE
[Runtime] Рантайм

### ISSUE THREAD

**Issue by Rogostick** [TauCetiStation/TauCetiClassic#8079]
#### Подробное описание проблемы
Рантайм
#### Что должно было произойти
Ничего
#### Что произошло на самом деле
Рантайм
#### Как повторить
Без понятия. Играл на ИИ.
#### Дополнительная информация:
Issue reported from  Round ID: 45240 (Tau Ceti Classic (RU))
Testmerges: ```#8061 #8049 #8039 #7822 #7760 ```
Reporting client version: 514.1565

**Comment by KIBORG04** [comment]
![image](https://user-images.githubusercontent.com/26389417/136269026-9e1f6b5f-f833-476d-91c8-d2fc5188aaaa.png)
