### ISSUE TITLE
Детективам не выпадают роли

### ISSUE THREAD

**Issue by ChewedGum** [TauCetiStation/TauCetiClassic#8080]
#### Подробное описание проблемы
Заметил ещё когда новый генг ввели что на детективе нельзя вступить в банду, позже пробовал вступить в культ - без педальной магии ничего не получалось. Последний месяц что беру детектива роли не выпадают, префы стоят, джобок активных нету.
#### Что должно было произойти
Детективу выпадают роли/может получить их вступив в "какую-нибудь хуйню"(tm).
#### Что произошло на самом деле
Не выпадает/не вступить.

**Comment by KIBORG04** [comment]
Спроси у кодеров старобэя, или там у зве, я хз. Это было всегда

**Comment by ChewedGum** [comment]
Я понятия не имею что за старобэй, кто его кодил и как это вообще к теме относится.
Не логичнее было бы майндщилд выдавать детективу раундстартом в таком случае?
