### ISSUE TITLE
Смерть от удара током.

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#8085]
#### Подробное описание проблемы
Куколка может получить разряд током, словить фибриляцию сердца и не добежав до медотсека помереть, совершенно не поняв что случилось и не сумев себе помочь
#### Что должно было произойти
а) Куколка путем выведения лога в чатик уровня "You heart beating very speed and strong" "You heart hurts" "you feel your heartbeats go faster" понимает, что сердечку пизда, и предпринимает важные действия в виде вызова парамедика

б) Укол иноправолином выводит сердце из фибриляции и космонавт может контрить такие приколы от игры интуитивно понятным способом. 
#### Что произошло на самом деле
"АААА АДМИН МЕНЯ УДАРИЛО ТОКОМ И Я УМЕР ЧЕ ДЕЛАТЬ"
#### Как повторить
Зайдите на сендбокс классик и специально расстреливайте кукол с теслаганов, стучитесь об наэлектризованные двери и прочая.
#### Дополнительная информация:
Это так же скрытнобафф магусов с их электроколдунством, теслоганов и малф-ИИшек. Это должно контрится достаточно простым способом (настолько же простым, насколько наэлектризвоать дверь за ИИшку) поэтому добавление иноправолину функций выведения сердца из фибриляции я считаю крутой темой

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/vopros-otvet/13334/3401

**Comment by Motzord** [comment]
> Ну ты можешь лечь и тебе сделают фибрилляцию другие игроки. Но ок, могу сделать чтобы иноправолин позволял сердцу не остановиться при фибрилляции, но не выводил его в нормальное состояние. В нормальное состояние пусть выводит другой игрок, дефибриллятор или еще что.



Для выведение сердца в нормальное состояние, надеюсь достаточно кликнуть один раз хэлпом по груди космонавтику? (или тебе надо полностью проворачивать CPR и ломать космонавту ребра или держать возле себе парамедика с дефибами?)

**Comment by DarthSidiousPalpatine** [comment]
Вот я тоже об этом думал. Просто сделать чтобы инопровалин не позволял остановиться сердцу самому.

**Comment by Motzord** [comment]
> Вот я тоже об этом думал. Просто сделать чтобы инопровалин не позволял остановиться сердцу самому

>Или, еще круче, если сердце под фибриляцией, следующий удар током гарантированно починит сердце космонавта. Итого, если совместить с иноправолином, космонавту будет достаточно еще раз потрогать оголенные провода

**Comment by DarthSidiousPalpatine** [comment]
Ну вот сердце итак может запуститься из фибрилляции ИЛИ ДАЖЕ ОСТАНОВКИ, но с 5% шансом. Можно повысить шанс, хз

**Comment by KIBORG04** [comment]
логи нужны

**Comment by DarthSidiousPalpatine** [comment]
Всмысле инопровалин уже есть. Он уже не позволяет сердцу остановиться?
Просто в том смысле что если ты заметил что сердце биться перестаёт - колешь себе инапровалин из личной коробки и ковыляешь до меда

**Comment by KIBORG04** [comment]
> Всмысле инопровалин уже есть. Он уже не позволяет сердцу остановиться? Просто в том смысле что если ты заметил что сердце биться перестаёт - колешь себе инапровалин из личной коробки и ковыляешь до меда

я о том, что не нужно повышать шанс починки сердца от тока, так как уже ~~есть~~ ты решил добавить иноправолин
