### ISSUE TITLE
Скафандры исчезают после ожирения куклы

### ISSUE THREAD

**Issue by Kilkalestia** [TauCetiStation/TauCetiClassic#809]
#### Подробное описание проблемы
Человек в скафандре рекуклера ожирел, в следствии чего его риг просто исчез из игры.
#### Что должно было произойти
Риг должен был выпасть на пол
#### Что произошло на самом деле
Риг исчез
#### Как повторить
Получить ожирение в риге рекуклера
#### Дополнительная информация:

**Comment by skvazarb** [comment]
Не воспроизводится, или там были дополнительные факторы или юзер просто придумал.

**Comment by Dennok** [comment]
Вообще это СПАДАНИЕ скафандра при ожирении достало. Сделайте чтоб нельзя было его снять.
