### ISSUE TITLE
Отсутствует события входа в зону\выхода из зоны при нестандартных способах перемещения

### ISSUE THREAD

**Issue by skvazarb** [TauCetiStation/TauCetiClassic#810]
#### Подробное описание проблемы
Турели не выбирают цель, которая оказалась в зоне с помощью телепортации
#### Что должно было произойти
При телепортации должен учитываться вход в зону
#### Что произошло на самом деле
Телепортация не считается входом в зону
#### Как повторить
Оказаться в зоне включенных турелей с помощью любого способа телепортации.
#### Дополнительная информация:
Телесаенс, блинк, маяк, ручной телепорт, абдукторы, ниндзи и т.д.
Аналогичная проблема с мешками для тел, шкафами, мехами и т.д.

**Comment by dearprincesscelestia** [comment]
> Аналогичная проблема с мешками для тел, шкафами, мехами и т.д.

Класс. Забираешься в шкаф, и ползками-ползками подходишь к аплоаду и ставишь что хочешь.

**Comment by StrikS** [comment]
Можно не ползками.

**Comment by volas** [comment]
Ошибка чуть более общая. Касается всех возможных событий входа в зону. 
Именно area/Entered() не часто используется, но как минимум: туррели, эмбиенс, джубокс.
turf/Entered() возможно тоже стоит проверить. Там HasProximity и различные сенсоры, и прочие вещи.

Другое дело, что да, туррели по зоне не очень хорошо. Но это по крайней мере работает быстро.

**Comment by SpaiR** [comment]
`arom.loc = newloc` заменить на `atom.forceMove(newloc)` - fixed
