### ISSUE TITLE
Smartfridge с классом secure совсем не secure

### ISSUE THREAD

**Issue by Unchi-unchi-un-chi-chi** [TauCetiStation/TauCetiClassic#8108]
#### Подробное описание проблемы
В игре есть холодильники для разного всякого - smartfridge, и есть "защищённые" холодильники с классом secure, которые, по идее, не должны позволять брать что-либо из них без соответствующего доступа. Проблема в том, что они спокойно позволяют брать из себя что-либо даже без карточки, хоть в чат и выводится сообщение Access denied.

#### Что должно было произойти
Голожопый ассистент пробирается в вирусологию/ксенобиологию и пытается взять пробирку с опаснейшим вирусом/экстракт слайма из умного холодильника с классом secure, но у него ничего не выходит -- у него нет доступа, от чего умный холодильник ничего не выдаёт.

#### Что произошло на самом деле
Умный холодильник булькнул "Access denied" и всё равно выдал пробирку/экстракт ассистенту.

#### Как повторить
Подойти с любым доступом к умному холодильнику с классом secure и взять что-либо из него.

**Comment by FoLZer** [comment]
Тот кто закодил - молодец. Вызов венда идёт до проверки на "запертость", строка 369.
https://github.com/TauCetiStation/TauCetiClassic/blob/1633ab2a0a1eecccf1e31184b63031b8516e5d59/code/game/machinery/kitchen/smartfridge.dm
