### ISSUE TITLE
Кнопка перерождения Шедоулинга исчезает

### ISSUE THREAD

**Issue by Motykoo** [TauCetiStation/TauCetiClassic#8134]
#### Подробное описание проблемы
Когда шедоулинг нажимает на кнопку перерождения (Hatch), то у игрока выскакивает окно с вопросом уверен ли он в своем выборе. Если окно закрыть не выбрав утвердительного ответа, то кнопка исчезнет и игрок навсегда останется человеком, без возможности переродиться.
#### Что должно было произойти
Кнопка перерождения (Hatch) должна быть доступна до того момента, пока персонаж не начнет перерождение.
#### Что произошло на самом деле
Кнопка перерождения исчезла, не проверив начал ли персонаж перерождение.

**Comment by Motykoo** [comment]
> ![image](https://user-images.githubusercontent.com/26389417/139479276-bd119a03-8505-493b-96e0-28ec125eca11.png)
> 
> Оно не исчезает, а чтобы увидеть кнопку, нужно перезайти.

я перезаходил, когда обнаружил этот баг. Не помогло, только выдачи роли шедоулинга заново

**Comment by Motykoo** [comment]
Я за DM не шарю, но считается ли закрытие окна без выбора какого-либо ответа за "No"? Ибо я сделал именно так, просто закрыл окно через крестик.

**Comment by KIBORG04** [comment]
Может я тут с бульондом и поторопился, но подобную проблему я часто наблюдал на борерах, на каких-то других антагах, где помогал перезаход.
Здесь, походу, проблема в том, что при клике на крестик тгуи_алерт возвращает нулл
