### ISSUE TITLE
Буква Я сломана в некоторых случаях отображения в диалоговом окне СС

### ISSUE THREAD

**Issue by SourcePony** [TauCetiStation/TauCetiClassic#814]
#### Подробное описание проблемы

OOC: 1Online1: http://img0.joyreactor.cc/pics/post/Warhammer-40000-Wh-Песочница-фэндомы-ло&#255;листы-1678590.jpeg 

#### Что должно было произойти

OOC: 1Online1: http://img0.joyreactor.cc/pics/post/Warhammer-40000-Wh-Песочница-фэндомы-лоялисты-1678590.jpeg 

#### Что произошло на самом деле

OOC: 1Online1: http://img0.joyreactor.cc/pics/post/Warhammer-40000-Wh-Песочница-фэндомы-ло&#255;листы-1678590.jpeg 

#### Как повторить

Попробовать послать ссылку в ООЦ, написать букву "я" в флаворе, рекордсах или книгах (но про книги не точно)

**Comment by Damirrus1** [comment]
Это защита от ссылок, да.

**Comment by Kurshan** [comment]
Раз уж на то пошло, то и в ризонах банов тоже.

**Comment by Belfogor** [comment]
А так же во флаворах.  В личных медицинских и охранных заметках, по крайней мере через меню в лобби.

**Comment by volas** [comment]
>А так же во флаворах. В личных медицинских и охранных заметках, по крайней мере через меню в лобби.
Если про imput-окно, то так и должно быть. https://github.com/TauCetiStation/RuBaystation12/issues/3

**Comment by Skyrull** [comment]
![image](https://cloud.githubusercontent.com/assets/20542000/20710874/cb97edc2-b666-11e6-9542-0d787dd4fb59.png)

Должно быть "Кто не любит ящеров"

**Comment by SpaiR** [comment]
@SourcePony минус картинки

ps На imgur можно сохранять безлимитное количество картинок с неограниченным сроком хранения

**Comment by igigin** [comment]
>минус картинки

Но тут и не было картинок.

**Comment by SpaiR** [comment]
Слишком сложно.

**Comment by igigin** [comment]
Про ссылки уже не актуально:
![image](https://cloud.githubusercontent.com/assets/17473163/25545031/4c974422-2c87-11e7-9389-353b5ae2002d.png)

Воуты и ризоны банов, флаворы, рекордсы и книги тоже. Закрываю.
