### ISSUE TITLE
Противогаз сб прячет волосы

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#8141]
#### Подробное описание проблемы
В противогазе сб не видно волос
#### Что должно было произойти
видно
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/84613249/139577183-d451f938-0ff7-42e3-a606-1523ec7d7b33.png)
![image](https://user-images.githubusercontent.com/84613249/139577194-8c75e2e6-2d9b-4eaf-a843-6ebd43049a8c.png)

#### Как повторить
Надеть противогаз

**Comment by volas** [comment]
В #8120 я поправил проблему, что не все предметы проверяли флаг скрытия волос. Похоже противогаз имеет флаг и должен был и раньше скрывать волосы, просто это не работало.
Если поведение не нужно, надо BLOCKHEADHAIR убрать у предмета. И у возможных других предметов, где проблема могла всплыть.

**Comment by simb11** [comment]
Тоже самое и с кучей других масок.
