### ISSUE TITLE
Нет параллакса и космической пыли в космосе

### ISSUE THREAD

**Issue by StrikS** [TauCetiStation/TauCetiClassic#815]
#### Подробное описание проблемы
Не портирован параллакс, космос не космос!
#### Что должно было произойти
Вышел в космос и там параллакс...
https://dl.dropboxusercontent.com/u/33846352/parallax/dreamseeker%202016-05-17%2001-42-39-51.webm
#### Что произошло на самом деле
Вышел в космос, а он не красивый!
#### Как повторить
Ничего не кодить, надеть риг, выйти в космос.
#### Дополнительная информация:
https://github.com/d3athrow/vgstation13/pull/10085

**Comment by dearprincesscelestia** [comment]
Чет до звезд руками дотянуться можно.

**Comment by WallShrabnic** [comment]
...и способен дотянуться до звёзд, не считая, что это сон...

**Comment by SourcePony** [comment]
В космосе не должно быть параллакса, просто статичная картинка. Если хотите реалистичности, конечно. Положение звезд будет изменятся ну с очень большими дистанциями, а не пролетом пару метров на джете.

**Comment by Leshiy-ART** [comment]
Мы не стремимся к реализму.

**Comment by StrikS** [comment]
Красиво и чувствуется что станция, не прилеплена к космосу, а отдельно от него. Движения звезд можно корректировать в конфиге.

**Comment by dearprincesscelestia** [comment]
> В космосе не должно быть параллакса, просто статичная картинка. Если хотите реалистичности, конечно.

Это утверждение содержит противоречие. "Просто статичная картинка" - это и есть параллакс - в космических масштабах.  В данный момент у нас звезды нарисованы на полу, который безо всякого параллакса двигается относительно космонавтика с той же скоростью, что и, например, стенка.

**Comment by SourcePony** [comment]
> Это утверждение содержит противоречие. "Просто статичная картинка" - это и есть параллакс - в космических масштабах.

Ни в коем случае. Я имею ввиду, что параллакс здесь будет 0,0001 процентный, если не меньше.

**Comment by StrikS** [comment]
Подкрутим, а теперь портируй.

**Comment by Leshiy-ART** [comment]
Не забывайте что у нас в первую очередь это игра и главное что бы визуал был приятный.

**Comment by dearprincesscelestia** [comment]
> Ни в коем случае. Я имею ввиду, что параллакс здесь будет 0,0001 процентный, если не меньше.
Т.е космические масштабы и будут подразумевать, что для смещения звезды на 1 сантиметр нужно будет пролететь от одного края карты до другого.

Ну так как раз с этой штукой по ссылке на ПР так можно сделать. Хоть 0.0001, хоть 0.00000000000001.

**Comment by Udokun** [comment]
Как уже было сказано сверху, звёзды находятся достаточно далеко, чтобы так двигаться. К пыли претензий нет, только можно чуть уменьшить их количество, а то прям в мою комнату космонавт заходит.
