### ISSUE TITLE
Runtime убийца ИИ

### ISSUE THREAD

**Issue by Lexanx** [TauCetiStation/TauCetiClassic#8155]
#### Подробное описание проблемы
Когда происходит рантайм, тупые турели агрятся на кота и стреляют по нему, но т.к. все выстрелы проходят мимо наглого кота, ИИ получает порцию лазера по своей светящийся башке.
#### Что должно было произойти
На рантайма не должны агрится турели
#### Что произошло на самом деле
В одном из раундов я так умер, просто не понял что происходит, почему по мне турели мои стреляют.
В этом раунде турели были не в летале, и успел поделать скринов
#### Как повторить
Вызвать рантайм играя на ИИ
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/61974560/140240068-40031c37-13aa-47b0-b4bf-d2340b9883d4.png)
![image](https://user-images.githubusercontent.com/61974560/140240077-5fbd5a67-f8ec-4988-95d2-781c5f7fdd69.png)

**Comment by 4310V343k** [comment]
Дубликат?
