### ISSUE TITLE
Полицейские береты не защищают от флешбенгов

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#8171]
#### Подробное описание проблемы
Police beret инспекторов ОБОПа не защищают уши от флешбенгов
#### Что должно было произойти
Защищают
#### Что произошло на самом деле
Не
#### Как повторить
Надеть этот берет и кинуть флешку

**Comment by Akellazp** [comment]
они и не должны, это сраные береты

**Comment by DarthSidiousPalpatine** [comment]
А можно еще чтобы они Гроину броню давали?

**Comment by kalazus** [comment]
Вообще, это странно, что у ОБОПа есть куча флешбенгов, но защиты от них нету. Так что защита от них им точно нужна.

**Comment by DarthSidiousPalpatine** [comment]
Может, стоит им имплант какой сделать, или наушники.
