### ISSUE TITLE
Баг изложения ионного закона

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#8174]
#### Подробное описание проблемы
Символы номера ионного закона может зарандомить так, что игра подумает что я попытася произнести эмоут и не скажет закон
#### Что должно было произойти
Назвал закон
#### Что произошло на самом деле
Не назвал
#### Как повторить
Рандом изложение законов?
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/47355061/140646066-cd6c1e64-1f63-430d-9794-fb91fe70f6fa.png)

Issue reported from  Round ID: 46125 (Tau Ceti Classic (RU))
Testmerges: ```#8115 #8049 #8039 #7760 ```
Reporting client version: 514.1569

**Comment by FoLZer** [comment]
А может оставить как фичу? Типо из-за сбоя закон не смог произнестись. Только определять эмоут тогда надо будет
