### ISSUE TITLE
Шапки детектива не защищают

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#8182]
#### Подробное описание проблемы
Если смотреть по коду,то шапка детектива,кунгхедбанд и прочие дет_хеды должны защищать,но они этого не делают
#### Что должно было произойти
Защищают
#### Что произошло на самом деле
Не
#### Как повторить
Проверить урон с шапкой детектива на голове

**Comment by Sakuya-Izayoi** [comment]
https://github.com/TauCetiStation/TauCetiClassic/blob/6bc6d01eedfea144f010063d97fb4fcb9128eff8/code/modules/clothing/head/jobs.dm#L95
