### ISSUE TITLE
PAI не видит что говорит и что говорят другие

### ISSUE THREAD

**Issue by Motykoo** [TauCetiStation/TauCetiClassic#8192]
#### Подробное описание проблемы
ПИИ не видит разговоров, в том числе своих.
#### Что должно было произойти
ПИИ должен слышать что говорят люди вокруг него и что говорит сам.
#### Что произошло на самом деле
В чате не отображаются разговоры.
#### Дополнительная информация:
Testmerges: `#8039 #8049 #8092 #8164 #8183`

**Comment by Firein91** [comment]
#6035 #6000 #7263

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/6000
