### ISSUE TITLE
Сброс клавиатуры при наборе текста для ЦК

### ISSUE THREAD

**Issue by Rolt146** [TauCetiStation/TauCetiClassic#8195]
#### Подробное описание проблемы
При наборе текста на консоли для сообщения ЦК, активное окно набора текста сбрасывается раз в несколько секунд, что затрудняет набор текста. Особенно, когда ты явный антагонист на мостике
#### Что должно было произойти
Свободно пишешь полотно текста на ЦК
#### Что произошло на самом деле
Набираешь слово, набралось 3-4 буквы, и окошко набора текста стало не активно, нажатие клавиш игнорируется, пока мышкой не кликнешь по окошку набора текста. 
#### Как повторить
Напичатать текст на цк через консоль на мостике
#### Дополнительная информация:
Раунд нюки 10.11.2021 примерно 20:00-22:00

**Comment by Sakuya-Izayoi** [comment]
закрывай окно консоли коммуникации

**Comment by Firein91** [comment]
Это кстати, везде так с say тоже если какое-то окошко постояно обновляется, например со слиппером точно так было, 
скорее всего с крио камерой и датчиками и слиппером таже хрень

**Comment by Motykoo** [comment]
в добавок к этому - консоль атмосферника по управлению атмосферой на станции тоже по КД сбрасывается, найти нужную панель и исправить проблему (включить скраберы и т.д.) не реально.

**Comment by kiVts** [comment]
Даже с чертовским воут окошком так

**Comment by KIBORG04** [comment]
Там окошка каждую секунду пересоздается, чтобы корректное время было. Да. Это ужасно
