### ISSUE TITLE
Не засчитывает конверт глав

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#8198]
#### Подробное описание проблемы
При реве не засчитывает конверт глав
![image](https://user-images.githubusercontent.com/47355061/141461487-e79fc59e-bb7e-4391-a434-e3ea2938edc6.png)

#### Что должно было произойти
засчитало
#### Что произошло на самом деле
нет
#### Как повторить
конвертнуть главу в реву и дождаться титров
#### Дополнительная информация:
Issue reported from  Round ID: 46275 (Tau Ceti Classic (RU))
Testmerges: ```#8193 #8168 #8164 ```
Reporting client version: 514.1569

**Comment by Sakuya-Izayoi** [comment]
duplicate of #8160
