### ISSUE TITLE
Досье, детектив. Не синхронизируются отпечатки.

### ISSUE THREAD

**Issue by TauKitty** [TauCetiStation/TauCetiClassic#82]
Originally reported by: **Anonymous**

---

Недели полторы назад все работало. Когда готовы отпечатки на 80%, если вставить карту с отсканированными отпечатками в деле высвечивается что сходство найдено, хотя в досье теперь информация не обновляется, то есть остается 80%. Раньше Имя прописывалось прямо в досье, что при распечатке давало необходимые доказательства.

---
- Bitbucket: https://bitbucket.org/taucetistation/tauceti/issue/82

**Comment by RichardJones1** [comment]
Нужно тестирование

**Comment by RigoSex** [comment]
В следующий заход криминалистом наделаю скриншотов и потестирую.

**Comment by KuzyXD** [comment]
Сделал этот следующий заход. Компьютер выдает сообщение об "вставленных и соответствующих отпечатках", если у тебя их даже нет в руках. Все так же информация не обновляется.
