### ISSUE TITLE
ОБОП может не прийти

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#8209]
#### Подробное описание проблемы
В фэмилис в ОБОП могут не набраться люди и ОБОП не прилетит

#### Что должно было произойти
ОБОП должен набираться из гостов пока не наберется

#### Что произошло на самом деле
ОБОП не набрался один раз и больше не пробовать

#### Как повторить
В фэмилис дождаться тайминга прилета обопа и не набрать в него игроков.

**Comment by KIBORG04** [comment]
Скорее тут пропосал. В первую попытку либо набрался, либо нет. Все зависит от гостов. А тут ты говоришь, что должны быть несколько таких попыток.

**Comment by KIBORG04** [comment]
Надо с тг спортировать https://github.com/tgstation/tgstation/blob/b9d150b812011b9613534ff2c2301fc49b1af22d/code/datums/spawners_menu.dm
