### ISSUE TITLE
Транспортный челнок с "Велосити" не гибает мобов в зоне, куда он прибывает

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#821]
#### Подробное описание проблемы
Транспортный челнок, который курсирует между станцией и "Велосити", не гибает клиентов.

#### Что должно было произойти
Аутиста должно было гибнуть.

#### Что произошло на самом деле
Он получил несколько единиц брута и материализовался внутри шаттла.

#### Как повторить
Постарайтесь остановить челнок грудью. 

#### Дополнительная информация:
Возможно аналогичная проблема и с другими челноками. Грузовой челнок в карго гибает. ПРОВЕРЕНО

**Comment by Damirrus1** [comment]
![image](https://cloud.githubusercontent.com/assets/21046015/20642868/5bdd304a-b43c-11e6-9e4c-af09524a2820.png)

**Comment by Raschert0** [comment]
Ну, немного лучшее название

**Comment by Belfogor** [comment]
Возможно предложенный тобой вариант лучше.

**Comment by Damirrus1** [comment]
А вот это было обидно.

**Comment by Belfogor** [comment]
Ну ладно тебе. У меня в заднице фитиль загорелся. Хоть возгорание в боевом отделение случилось и не по твоей вине. Извиняй.
