### ISSUE TITLE
Инженерный РиГ не изолирует от электричества.

### ISSUE THREAD

**Issue by Konradiuss** [TauCetiStation/TauCetiClassic#8216]
#### Подробное описание проблемы
После надевания инженерного РиГа, или атмосферного, или РиГа старшего инженера, и попытке укладывать провода он не работает как должен, а именно тебя бьет электричеством и оставляет на РиГе маленькую пробоину.
Точно такой же эффект встречается при контакте с наэлектризованными шлюзами.
Как вывод, делаю, что где то слетела функция, или метод класса который отвечал за изоляцию РиГов инженеров, атмосферников, старшего инженера.
#### Что должно было произойти
При надевании инженерного РиГа, или РиГа старшего инженера не нося изоляционные перчатки, ты все еще должен иметь возможность безболезненно прикасаться к наэлектризованной технике и укладывать провода.
#### Что произошло на самом деле
При надевании инженерного Рига, или РиГа старшего инженера тебя бьет током при прикосновении к наэлектризованным приборам или при укладке проводов.
#### Как повторить
Надеть инженерный РиГ, или РиГ старшего инженера без надевания изолирующих перчаток. Попробовать прикоснуться к наэлектризованным приборам или начать укладывать провода под напряжением.
#### Дополнительная информация:
Если вы наденете изолирующие перчатки, а поверх инженерный РиГ, то всё будет хорошо.

**Comment by AndroBetel** [comment]
А ты это в каком конкретно риге проверял?

**Comment by Konradiuss** [comment]
> А ты это в каком конкретно риге проверял?

Как и писал. В обычном инженерном и РиГе старшего инженера.
Играю на втором сервере.
Даже обновил локалку для теста, на локалке тоже эти оба РиГа не защищали, хотя должны.

**Comment by simb11** [comment]
#11422
