### ISSUE TITLE
Множественные проблемы с модулями сервисного борга. 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#822]
#### Подробное описание проблемы
Вообще сам по себе этот модуль одна сплошная проблема. Не работает зажигалка. Она как модуль функционирует, но юнит не может ей воспользоваться. 

Так же у этого модуля имеется бутылочка с каким-то ЭНЗИМАМИ. Если ее поместить в какой-нибудь контейнер, то вынув бутылку из него, юнит уже не сможет ВООБЩЕ пользоваться бутылкой. Помимо всего прочего она еще и выпадает на поверхность, и хуманы могут ее абузить. 

Но ТОП трабл именно с ШЕЙКЕРОМ. Если смешать в нем какой-нибудь коктейль (предположительно. Лично я намешал антифриз) от будет БЕСКОНЕЧНО восполняться. То есть содержимое шейкера не слить и не вылить! 

#### Что должно было произойти
Все должно было работать

#### Что произошло на самом деле
Нихуя не работало. 

#### Как повторить
Пострадайте на сервисном борге

#### Дополнительная информация:
Fix it

**Comment by Snipered** [comment]
1) Борг просто не может её открывать/закрывать, а так она полностью работает(тестил на сигарах и бумаге).
2) Так со всеми "контейнерами" у боргов. Если целенаправленно попытаться сделать то, что ты не должен делать с этой бутылкой, то да, ты не сможешь пользоваться ей и всеми остальными контейнерами у боргов. Если я не ошибаюсь.
3) Очень скоро выкачу ПР с изменением этого шейкера на другую штуку, что и пофиксит этот баг.

3)

**Comment by RichardJones1** [comment]
Боргопроблемы
