### ISSUE TITLE
[Proposal] Кредиты менять на Каргопоинты

### ISSUE THREAD

**Issue by Lexanx** [TauCetiStation/TauCetiClassic#8230]
#### Подробное описание проблемы
Когда оцениваешь что то с помощью экспорт сканнера. Пишется цена в кредитах, которые ты получишь за этот товар при отправке его.
Отсюда следует что Кредиты = Каргопоинты.
Но почему то на прямую, кредиты никак нельзя обменять на каргопоинты, из за этого уменьшается смысл денег.
Да и давно стоит дать кредитам большую значимость в игре. Сейчас это бумажка которая никого не интересует, раз в мильён лет можно кого то подкупить. Но деньги серавно не потратить.
#### Что должно было произойти
Должно быть так, тебе глава выдал премию, ты обналичил в кредиты, и заказал в карго себе питцу на праздник.
#### Что произошло на самом деле
Ненужные в игре кредиты копятся только ради того, что у твоего персонажа условно после раунда есть жизнь.

**Comment by Tap0r** [comment]
> Должно быть так, тебе глава выдал премию, ты обналичил в кредиты, и заказал в карго себе питцу на праздник.

А сейчас так нельзя?

Мне кажется, что это будет просто абузиться при нюке и подобном, когда кэп или ГП будут просто скидывать всё, что есть, на счёт КМу.

**Comment by kalazus** [comment]
Вроде же был пр про это.

**Comment by Lexanx** [comment]
> кэп или ГП будут просто скидывать всё, что есть, на счёт КМу.

Ну, тогда что можно придумать с тем, куда экипажу тратить кредиты? 
Игрокам они не нужны потому что не видят игромеханической ценности в них. Я вот в раунде прошлом встретил ВОКСА, которому не надо были 6тысяч кредитов просто так.

**Comment by DarthSidiousPalpatine** [comment]
> > кэп или ГП будут просто скидывать всё, что есть, на счёт КМу.
> 
> Ну, тогда что можно придумать с тем, куда экипажу тратить кредиты? Игрокам они не нужны потому что не видят игромеханической ценности в них. Я вот в раунде прошлом встретил ВОКСА, которому не надо были 6тысяч кредитов просто так.

Уже придумано, но я не смог до ума довести - онлайн-магазин, покупаешь вещи за предметы, Они приходят в карго на том же шаттле в маленьких уже запакованных посылках с биркой отправителя и именем.

**Comment by Tap0r** [comment]
> > кэп или ГП будут просто скидывать всё, что есть, на счёт КМу.
> 
> Я вот в раунде прошлом встретил ВОКСА, которому не надо были 6тысяч кредитов просто так.

Ну так... Он же ВОКС, всё правильно. Их вики почитай, они ценности денег не понимают.

**Comment by Venngedi** [comment]
#9242 Закрывайте.
