### ISSUE TITLE
[proposal] Дать нюкерам наплечную кобуру

### ISSUE THREAD

**Issue by ChewedGum** [TauCetiStation/TauCetiClassic#8262]
#### Подробное описание проблемы
Есть бесполезная разгрузка, нету крутой кобуры.
#### Что должно было произойти
У нюкера кончились патроны в основном оружии, он на хоткей мгновенно выхватил вторичное.
#### Что произошло на самом деле
Не вытащил, пока открывал инвентарь и вспоминал где его стечкин/.357 его убили (this is so sad, can we hit 50 likes?)

**Comment by Sakuya-Izayoi** [comment]
у вас есть карманная кобура...

**Comment by ChewedGum** [comment]
Не работает на хоткей, даже если бы работала то занимала слоты в которые куда более важные вещи нужно ложить чтоб под рукой были.

**Comment by Stolaire** [comment]
Карманную кобуру, ровно как ножны для батона (чего?) нельзя повесить в слот брони и боевого рига. Но могу ошибаться

**Comment by simb11** [comment]
у них теперь есть кобура так что закройте пжлст

**Comment by simb11** [comment]
Пофикшено в #9215
