### ISSUE TITLE
Мерцание и исчезновение курсора

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#8269]
#### Подробное описание проблемы
Курсор периодически мерцает и исчезает в контекстны меню

#### Что должно было произойти
Курсор должен быть виден всегда

#### Что произошло на самом деле
Курсор исчезает в некоторых контекстных меню

#### Как повторить
Райткликнуть на любой тайл, поводить мышкой по контекстным меню.

**Comment by KIBORG04** [comment]
#8242 #8117; - ТМы первого

**Comment by KIBORG04** [comment]
Из-за 8117 проблема

**Comment by Sakuya-Izayoi** [comment]
и смещение курсора при драгндропе тоже из-за этого?

**Comment by KIBORG04** [comment]
Хз, но мигание и исчезновение именно с ранлевелсом
