### ISSUE TITLE
Непредсказуемое увеличение урона при добавлении в VV

### ISSUE THREAD

**Issue by skvazarb** [TauCetiStation/TauCetiClassic#828]
#### Подробное описание проблемы
При добавлении брут или берн урона мобу в VV фактическое значение отличается от указанного в большую сторону.
#### Что должно было произойти
Фактическое значение должно соответствовать введенному.
#### Что произошло на самом деле
Оно может значительно отличаться.
#### Как повторить
Добавить относительно большое количество брут/берн урона мобу через VV.

**Comment by Skippeer12** [comment]
Брут дамаг скачет из-за того что конечности отлетают при определенно высоком уроне, а так как прописаный урон распределяется по телу, то и конечности могут отлететь разные.

А вот с бёрном должно быть всё хорошо.

**Comment by skvazarb** [comment]
>Брут дамаг скачет из-за того что конечности отлетают при определенно высоком уроне, а так как прописаный урон распределяется по телу, то и конечности могут отлететь разные.

Там проблемы и без потери конечностей.

**Comment by Skippeer12** [comment]
>Там проблемы и без потери конечностей.

Ну так, брут ломает ещё кости, а они тоже вносят свой вклад в дамаг по телу/конечности.

**Comment by RichardJones1** [comment]
Нужен тестовый фидбек

**Comment by volas** [comment]
Шкиппер прав, там могут быть другие повреждения органа.
