### ISSUE TITLE
В карго шаттл без стен.

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#8281]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/44546836/143487152-01724368-1841-4036-a5e5-3ca9b49cc79d.png)
Улетел со стенами, прилетел без стен.
#### Дополнительная информация:
https://github.com/TauCetiStation/TauCetiClassic/pull/8252

**Comment by KIBORG04** [comment]
выглядит как фича
