### ISSUE TITLE
Откат спрайтов инженерного шмотья

### ISSUE THREAD

**Issue by sovok4** [TauCetiStation/TauCetiClassic#829]
#### Подробное описание проблемы
Спрайты инженерного шмотья мыльные и мрачные, кроме того эти курткоштаны отошли от термина jumpsuit. А джампсьют вот допустим: http://prntscr.com/dcpyvi
#### Что должно было произойти
Инженерное шмотье должно было быть ярким и незамыленным, сворачиваться вниз, как джампсьют и вообще быть похожим на него.
#### Что произошло на самом деле
Инженерное шмотье стало жертвой быдлографона
#### Как повторить
Смержить быдлографонистый ПР с курткоштанами, когда всех тошнит от одного его вида

**Comment by Damirrus1** [comment]
Не похоже на баг, если честн

**Comment by SpaiR** [comment]
Пропозалы никто делать не запрещает.

**Comment by StrikS** [comment]
Мне нравятся у инженеров из шмоток все более-менее, а вот насчет наборов СБ я уже пилю ПР, чтобы как поклонники Вальтера были довольны, так и те кому больше нравятся другие наборы.

**Comment by Skippeer12** [comment]
Куртейка инженеров не плохая, а вот Сешная форма, ну прям не очень

**Comment by Tankred0** [comment]
Форма СЕ похожа на костюмы современных мусорщиков так то...

**Comment by Kurshan** [comment]
Все привыкли, все сожрали, уже неактуально.
