### ISSUE TITLE
Бесконечный емаг у синдиборга

### ISSUE THREAD

**Issue by splifin2** [TauCetiStation/TauCetiClassic#8290]
#### Подробное описание проблемы
Если синдиборг потратил весь заряд емага, то емаг падает на пол, но синдиборг получает НЕВИДИМЫЙ емаг.
#### Что должно было произойти
Синдиборг тратит весь заряд емага и не может что-либо делать
#### Что произошло на самом деле
Синдиборг емагает двери невидимым емагом
#### Как повторить
Потратить весь заряд емага на синдиборге

**Comment by FoLZer** [comment]
Такая же проблема существует и с некоторыми предметами у мед борга, может ещё у кого. Займусь как только смогу.
