### ISSUE TITLE
Проблемы с чатом

### ISSUE THREAD

**Issue by skvazarb** [TauCetiStation/TauCetiClassic#830]
#### Подробное описание проблемы
Сообщения при брейндамаге выводятся как-то так 
>yells like an idiot, "ПїЅПїЅПїЅПїЅПїЅПїЅПїЅПїЅ!"
#### Что должно было произойти
Должны выводится нормально
#### Что произошло на самом деле
>yells like an idiot, "ПїЅПїЅПїЅПїЅПїЅПїЅПїЅПїЅ!"
#### Как повторить
Брейндамаг
#### Дополнительная информация:
Чтобы не плодить ишью, предлагаю о похожих проблемах писать в этом.

**Comment by WallShrabnic** [comment]
Не совсем понял суть проблемы, нужны примеры из раунда (lokalo4ki)

**Comment by skvazarb** [comment]
Пример из раунда есть же
>yells like an idiot, "ПїЅПїЅПїЅПїЅПїЅПїЅПїЅПїЅ!"

**Comment by volas** [comment]
Скорее всего кодировка в dm файле с фразами поехала.

Что-то аналогичное как тут с нинзей, https://github.com/TauCetiStation/TauCetiClassic/pull/724 (кстати, тоже не фикшенно)
