### ISSUE TITLE
Способ получения сравнительно большого количества очков в рнд.

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#8307]
#### Подробное описание проблемы
Удары одним и тем же предметом с разным именем распознаются сканером для вскрытия как удары разными предметами. Это приводит к тому, что научный инструмент считывает больше исследовательских очков с отчета о таком вскрытии.

#### Что должно было произойти
Удары одним и тем же предметом с разным именем должны учитываться как удары одним и тем же предметом.

#### Что произошло на самом деле
Удары одним и тем же предметом с разными именем учитываются как удары разными предметами.

#### Как повторить
1. Взять новый предмет в руку
2. Ударить им по кукле
3. Переименовать его хандлаблером
4. GOTO 2 пока можно переименовывать предмет
5. GOTO 1

**Comment by KIBORG04** [comment]
См. в метод `add_autopsy_data(`. Для него необходимо изменить аргумент для `used_weapon`, где передается название оружки, а не его `type`. Вроде не сложно, но нужно будет все равно шаманить.

**Comment by LudwigVonChesterfield** [comment]
передавать `type` возможно было бы глупым решением, потому-что удар включенным есвордом и выключенным - разные вещи

я бы брал какой-то хеш от атаки, типо там hash("тип: огонь, урон: 10") и на этом всё

**Comment by kalazus** [comment]
> передавать `type` возможно было бы глупым решением, потому-что удар включенным есвордом и выключенным - разные вещи
> 
> я бы брал какой-то хеш от атаки, типо там hash("тип: огонь, урон: 10, флаги: sharp") и на этом всё

Тогда совсем нельзя будет понять чем убили (для чего первоначально и создавалась аутопсия). Если, конечно, не сделать таблицу урона какую-нибудь, но тогда придётся и мета-вещи туда закинуть по типу убийство генки. Самое простое решение, брать везде init(name).

**Comment by LudwigVonChesterfield** [comment]
я говорю про получение очков а не аутопсию

**Comment by volas** [comment]
бамп. Игроки абузят, админы банят.

**Comment by TheLone1y** [comment]
У гады игроки, у гады админы...

**Comment by Deahaka** [comment]
> бамп. Игроки абузят, админы банят.

с подключением. Удалить абуз вместе с заработком очков кроме вайтлистовых источников урона: халк, космос, сжигание, генокрадское жало.
Кто сделает?

**Comment by KIBORG04** [comment]
Там сложнее, надо изменить способ сохранения оружия в логи ударов.

**Comment by Deahaka** [comment]
> Там сложнее, надо изменить способ сохранения оружия в логи ударов.

Я не вижу смысла давать очки за удары цветами, извини
