### ISSUE TITLE
LOOC открывается при нажатие на шифт альт и контрол

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#8319]
#### Подробное описание проблемы

https://user-images.githubusercontent.com/26389417/143926867-6bcdf5ec-6a49-4230-b3ba-d51bfd503532.mp4

https://github.com/TauCetiStation/TauCetiClassic/pull/8312

![image](https://user-images.githubusercontent.com/26389417/143927067-3da61afb-a5bc-4fa9-a625-19678e8b2458.png)

#### Что должно было произойти
Не откроется

#### Что произошло на самом деле
Открылся

#### Как повторить
Убрать все бинды с любого коммуникейт-бинда. Нажать на шифть/контрол/альт

**Comment by Sakuya-Izayoi** [comment]
У меня не открывается.

**Comment by Sakuya-Izayoi** [comment]
Точнее у меня такое было один раз на сендбоксе до этого ПРа. Я там че-то делал с хоткеями. Короче, странный баг.

**Comment by KIBORG04** [comment]
Убери все хоткеи из любых биндов коммуникации. Тогда появится.

**Comment by KIBORG04** [comment]
Проблема не конкретно лоока

**Comment by KIBORG04** [comment]
Походу там надо делать валидацию значения `key`, чтобы в макросы не попало `key = "None"`.
https://github.com/TauCetiStation/TauCetiClassic/blob/86c4053efabe67f28ee0a84dd3aff58f4fa539a9/code/modules/client/client%20procs.dm#L714-L736
