### ISSUE TITLE
Секундомер КД у спеллов не пропадает, если кд спелла 0

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#8324]
#### Описание

https://user-images.githubusercontent.com/26389417/144125904-77511d6a-dc97-4572-be0a-b12a4c6dfa93.mp4

Взять любой спелл с кд 0 секунд. Например, хаевминд лингов.

#### Что должно было произойти
Секундомер пропал

#### Что произошло на самом деле
Остался

#### Как повторить
Получить спелл
Активировать спелл

**Comment by Ahion** [comment]
Почему вообще эти спеллы используют кулдаун, если перезарядка у них 0 секунд
