### ISSUE TITLE
Пропадают иконки у спеллов

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#8325]
#### Подробное описание проблемы
Похоже, что стало появляться после мержа секундомера-КД для спеллов

#### Что должно было произойти
Иконка всегда в своем контейнере

#### Что произошло на самом деле
Пропадает, когда активируешь спелл (вроде)

#### Как повторить
нажать спелл. Пробовал с коммуникейтом культа

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/3197

**Comment by Ahion** [comment]
Что-то я не смог повторить баг на локалке, даже с коммуникейтом культа.

**Comment by KIBORG04** [comment]
Вроде пофикшено? Но больше не замечал
