### ISSUE TITLE
У гостов открываются вербы Drop Pod'а

### ISSUE THREAD

**Issue by Motykoo** [TauCetiStation/TauCetiClassic#8326]
#### Подробное описание проблемы
Когда гост стоит рядом с дроп подом, то появляется вкладка с его вербами
#### Что должно было произойти
У гостов не должны появляться вербы
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/59807075/144133407-67f3ea9b-ac69-4a97-9880-2afea8c59270.png)

**Comment by Sakuya-Izayoi** [comment]
Юзать он их может? Если нет, то это не баг и так устроены вербы.

**Comment by Motykoo** [comment]
> Юзать он их может? Если нет, то это не баг и так устроены вербы.

не может. Ну ок
