### ISSUE TITLE
У отрубленной головы есть только белый цвет волос. Другие цвета отсутствуют

### ISSUE THREAD

**Issue by Raschert0** [TauCetiStation/TauCetiClassic#833]
#### Подробное описание проблемы
См. название
#### Что должно было произойти
Должны были быть волосы тогго цвета, который был у игрока, которому отрубили голову
#### Что произошло на самом деле
См. название
#### Как повторить
Отрубить голову
#### Дополнительная информация:
Возможно, также у отрубленной головы и единственная на все случаи причёска, а не волосы, которые были у игрока

**Comment by Skippeer12** [comment]
Это норма, не трогай пожалуйста.

**Comment by dearprincesscelestia** [comment]
> Возможно, также у отрубленной головы и единственная на все случаи причёска, а не волосы, которые были у игрока

Насколько я помню, все же волосы, выбранные для куклы.
