### ISSUE TITLE
[Proposal] Финальная форма генокрада и ограничение на количество съеденых

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#8339]
Это касается отсутствия ограничения на количество жертв генокрада - на данный момент он может съесть всю станцию и не подавиться, и это сложно оценивать со стороны администрации и правил. Вроде как, и не по правилам выпиливать станцию, но в то же время у генокрада есть ic-цель на это - насыщение.

Предложение добавить ограничение на количество съеденных жертв генокрада, после достижения которого он заметно мутирует/теряет контроль над своими способностями, получая с этим ряд баффов и нерфов.

В финальной форме может быть добавлен ряд нерфов, например он не сможет больше питаться, будет гораздо медленнее. Как и баффов - более живучей.

Лимит где-то 5-6 человек, и на пути к нему после очередной съеденой жертвы писать игроку какое-то ic-редупреждение "вы можете потерять контроль" и тд тп. Возможно добавить промежуточную стадию перед финальной, где у него вырастает рука-меч без возможности трансформировать обратно или что-то такое.

Это спрайт с гунов (взять скорее всего против их лицензии, но я уверен что видел где-то что-то похожее в tg или bay билдах):
![изображение](https://user-images.githubusercontent.com/4064061/144520009-8ae1bcf5-ce74-427d-a592-4f1fb8e34678.png)

Более абстрактные и не приоритетные идеи (можно вернуться после осуществления необходимого минимума выше):
1. Финальную форму можно сделать целью охоты для других чейнжлингов. Типо поедание деликатеса. что может дать какие-то особые баффы. Со стороны игры это автоматически будет балансить разошедшихся антагонистов.
2. Можно оставить финальной форме возможность питаться и расти, вплоть до становления эпическим антагом конца на уровне нар-си.

---
*авторство идеи - весь педальсостав, я просто нашел время оформить в пропазал*

**Comment by volas** [comment]
И со стороны администрации в случае реализации больше не будет разночтений. Убиваешь для пропитания (пока можешь) - в рамках правил. В остальном можно будет [применять первое правило антагониста ](https://rules.taucetistation.org/#%D0%B0%D0%BD%D1%82%D0%B0%D0%B3%D0%BE%D0%BD%D0%B8%D1%81%D1%82%D1%8B).

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/fidbek-na-metu-na-genokradov/29993/1

**Comment by volas** [comment]
Для старта хардкод-ограничения на количество съеденных жертв без остальных изменений уже будет достаточно и зафиксирует решение проблемы.

**Comment by Sakuya-Izayoi** [comment]
> Для старта хардкод-ограничения на количество съеденных жертв без остальных изменений уже будет достаточно и зафиксирует решение проблемы.

Ограничение может быть константным или лучше менять его в зависимости от населения станции?

**Comment by volas** [comment]
На твоё усмотрение. Я думал о 5-6 держа в уме обычный раунд на первом, но действительно имеет смысл делать меньше для допустим ночных раундов или 3-го сервера.

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/diskashn-ogranicheniya-po-sozhrannym-u-genokrada/22947/162

**Comment by LoTaRk-FroG** [comment]
17 поинтов на генке? Это очень мало с учётом наших любимых игроков на СБ и полной меты на чейнжлингов. Может поднять хотя бы до 8-10 челиков?

**Comment by AndroBetel** [comment]
Ниче не мешает ручками убивать и не поглощать.

**Comment by volas** [comment]
> Ниче не мешает ручками убивать и не поглощать.

Я понимаю, что ты имел в виду "можно убивать не только поглощая", но другие могут не правильно воспринять как призыв к действию, потому оставлю комментарий - правила антагонистов никто не отменял.

> 17 поинтов на генке? Это очень мало с учётом наших любимых игроков на СБ и полной меты на чейнжлингов. Может поднять хотя бы до 8-10 челиков?

Если кап пойнтов проблема, то можно увеличить пойнты за человека. В соседнем PR-е #8338 Бетель еще нерфит цену на некоторые способности.

**Comment by LeBubble** [comment]
генокрад SSS Ранга: Сова

**Comment by volas** [comment]
> Можно оставить финальной форме возможность питаться и расти, вплоть до становления эпическим антагом конца на уровне нар-си.

Всё сделано кроме этого. Запишу некоторые мысли:
1. Развитие не обязательно делать поеданием геномов, можно по таймеру давать очки мутации
2. Если делать, это должен быть сложный путь, возможно с автоматическим вызовом ЕРТ для противостояния на каком-то этапе
3. Концепт медленной "башни" ок
4. Из абилок - было бы неплохо дать (пассивную?) возможность спавнить слабых мусорных мобов с майндом жертв в виде конечностей рук/голов/ног. Как абилка "дать конечности разум" можно было бы дать и обычному чеинджу, прям как на гунах.
5. Вообще всё развитие можно было бы построить на основе уже текущих абилок, видоизмененных и бафнутых. Может быть больше в сторону пассивных. Тот же щит например - появляется, выдерживает сколько-то урона, изчезает, возвращается по КД. Жала - автоматически жалит космонавтов через n тайлов рандомным жалом (толстоты, смены внешности и тд).
