### ISSUE TITLE
В автомате детектива сломались иконки шмоток

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#8350]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/24685276/144749882-51f18f4a-0abc-4885-9ae7-e5084d3f4bb3.png)
В автомате детектива сломались иконки

**Comment by KIBORG04** [comment]
Почисти кеш

**Comment by KIBORG04** [comment]
![image](https://user-images.githubusercontent.com/26389417/144750047-7a80927f-02b4-47d9-96f6-91ccd5bc1246.png)
