### ISSUE TITLE
[Proposal] Тестер генокрадов

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#8352]
Меня попросили расписать для обсуждения.

Экипажу требуется способ для однозначного определения генокрадов (почему - было на форуме и в дискорде, я не буду повторяться если не попросите), при этом этот способ должен быть не бесплатным - затратным по времени, по ресурсам.

<details>
<summary>Путь рассуждений, опционально для чтения</summary>
Вариант решения - добавление одноразовых тестов на станцию. Проблемой является "цена" этих тестов и "цена" их применения, что бы СБ не имело возможности протестировать весь экипаж сразу. Можно ограничить их изначальное количество, сделать их применение стоящим времени (взял кровь в тест - ему нужно 2-5 минут отработать перед проявлением результатов). 

Но экипажу желательно иметь способ восполнения количества тестов, и что бы опять же это не было дешево по ресурсам, потому моей главной идеей была сделать зависимость производства тестов от успехов экипажа в борьбе с генокрадами - от каких-то материалов, добытых с генокрадов. Пусть кровь, что бы ничего не изобретать (всё равно мы будем вносить в неё изменения для работы тестов). Но добавлять в РнД-шный принтер еще один тип материала только для производства теста странно, потому кровь будет требоваться самому уже распечатанному тесту для работы.

Мы тестируем кровь на принадлежность к генокраду и для этого нам нужна кровь генокрада, уже интересная зависимость. Пусть условием будет кровь другого генокрада, и для большего интереса кровь недавно живого генокрада.

И лоровставка - кровь разных генокрадов в особых условиях (воссоздаваемых тестером) имеет особую реакцию между собой. На что тест и реагирует.

Само производство тестера будет стоить каких-то редких ресурсов и определенного уровня технологий. Тест и позитивно сработавший тест должны бустить исследования.
</details>

### Концепт

Тест - объект, содержащий две камеры реагентов, одна бесконечно хранит эталонный образец, в другую наподобие как шприцем можно собрать кровь тестируемого. После запуска, через 2-5 минут, если и эталонный образец и тестируемый оказались от (разных) генокрадов - тест положительно пищит. Тест не годится после использования повторно, и кровь внутри сгорает/испаряется после использования и не доступна для извлечения.

У экипажа изначально несколько тестов, и для сложности саботажа раскинуты по разным отсекам:
~3 уже заряженных и готовых к использованию теста в бриге
~2 пустых в общем хранилище на черный день
~1 пустой в кабинете РД, как резерв и для ускорения исследований

Пустой тест перед использованием придется зарядить "эталонным" образцом. Для этого экипажу придется поймать хотя-бы одного достоверно известного генокрада, и пока он еще жив взять кровь шприцем и загрузить в первый отсек теста. Тест заряжен и готов к использованию, только (как выше в лороставке, тест фиксирует реакцию крови двух разных генокрадов) не будет реагировать на изначального генокрада. Уже заряженные тесты у СБ будут реагировать на всех генокрадов станции.

Кровь генокрада вне живого генокрада теряет свои особые свойства через N-цать минут и становится не пригодной для тестирования. Тест в "эталонной" камере сохраняет её в "активном" состоянии, пригодном для реакции, бесконечное время. Так экипаж не сможет запастись расходниками для тестов, пока сами тесты не готовы.

Производство пустого теста - нужно достигнуть какого-то определенного уровня науки в ветке биологии (какой именно - обсуждаемо), и распечатать на принтере при не самой дешевой стоимости ресурсов (что бы шахтерам требовалось работать и рнд не могло не поморщившись распечатать десяток тестов и тут же сразу заправить от подвернувшегося генокрада).

### Итого

Как концепт мне очень нравится как сложился этот вариант. Даёт равные возможности для экипажа и генокрадов, интересные механики для взаимодействий и возможности для про*баться.

Если у СБ есть живой генокрад в заключении, с которого они "заряжают" тесты - СБ в выигрыше, но генокрад становится им нужен живым со всеми сопутствующими рисками, да еще и может по хейвмайнду предупредить остальных, что у экипажа появились тесты, и у кого именно. Если СБ избавляется от генокрада - они остаются без возможности делать тесты дальше.

Генокрад даже может как-то добровольно сдать кровь для создания тестов, ради профита, что эти тесты потом не будут работать на самого генокрада.

Генокрады могут заранее саботировать все тесты на станции (я не против меты в этом плане, пусть даже целенаправленно целятся в упомянутые отсеки), но это сложно. Даже если смогли - РнД всё еще сможет добраться по дереву технологии да создать новые, но на это потребуется время, да еще и наличие живого генокрада для зарядки тестов. По итогу это будет просто выигранная генокрадами отсрочка. 

А если экипаж остался без готовых тестов, да еще не смог поймать достоверного генокрада для производства новых - сам виноват, а гены молодцы.

Сам тест можно заряжать кровью не только генокрадов - если есть два подозреваемых, то можно сыграть в рулетку. Он сработает, если оба генокрады. И после этого можно вычислить остальных. Но это всё время, и за это время генокрады вполне могут придумать какой-то план и выбраться.

И при зарядке сконструированного теста нужно еще быть уверенным, что в тестовый отсек ты вливаешь кровь именно генокрада. С генокрадами, если они не спалились, это может быть сложно. Может и так случиться, что РнД только что потратилось на кучу тестов, которые из-за чьей-то ошибки оказались бесполезным барахлом.

### Техническая часть

Сам по себе тестер сделать просто, но пока у меня довольно смутные представления насколько сложно будет прикрутить особый механ крови генокрадов.
Любой ``/datum/reagent`` и кровь в т.ч. имеют поле ``list/data`` для какого-то особого описания, так уже работают вирусы. Метку, что кровь принадлежит генокраду, можно будет хранить там же, вместе с уникальным айди генокрада для тестера и таймером жизни этой метки. Насколько сложно это добавить, и насколько сложно будет закодить таймер этой крови вне генокрада/тестера - я пока не уверен, нужно посмотреть и изучить дальше.

### Итого

Если мы введем прямые однозначные тесты, и еще починим косвенное [детектирование генокрадов через боди сканер и наличие протезов/искусственных органов](https://forum.taucetistation.org/t/fidbek-na-metu-na-genokradov/29993/82?u=volas), то я думаю можно будет еще больше бафнуть стелс абилки генокрадов. Что бы вычисление генокрадов по косвенным признакам и подозрениями, а не по прямым типо мутировавшей руке, играло больше роли.

**Comment by TEXH4Pb** [comment]
А как тебе такой вариант? Использовать в качестве эталонного образца не кровь любого генокрада, а какой-нибудь биоматериал, который остаётся в небольших количествах в жертвах генокрадов. Может быть даже сделать так, чтобы по этому материалу можно было найти только генокрада, который этот материал оставил. Таким образом генокрады сами себе будут регулировать темп игры: больше жертв- проще поиск. Если хорошо прятать жертв или вовсе их устранять, то и тесты будет делать сложнее.

**Comment by ssbugman** [comment]
Вот идея технаря толковая, так не получится слепо колоть тесты каждому кто попал в бриг.

**Comment by UDaV73rus** [comment]
Интересный концепт

Запосчу что писал в дискорде, эти варианты можно мешать и друг с другом и с тем что выше

1. После % смертей, на станцию прилетает ученый-ксенбиолог с охранником в биозащите и у них есть тесты
2. В доки по вызову, прилетает тест-капсула которая не как шаттл, а как объект в который суешь человека и она одноразово сканит и улетает.

Второй вариант нравится что его нельзя саботировать полностью, только отсрочить

**Comment by DantezZz** [comment]
Тесты, это конечно хорошо, но будут ли выдаваться QR-коды??
