### ISSUE TITLE
Не работают ксеноязыки в русской расскладке.

### ISSUE THREAD

**Issue by Tankred0** [TauCetiStation/TauCetiClassic#836]
#### Подробное описание проблемы
При использовании языка таяр: :о(:j) в сей, коты не говорят на своём языке. С использованием латинской :j все нормально.
#### Что должно было произойти
Кот должен говорить на своём языке после :о
%tajaranname% mrowls: Ухты я говорю как настоящий таяра
#### Что произошло на самом деле
%tajaranname% say: :о Ух, ты я не могу говорить как настоящий таяра
#### Как повторить
Зайти за кота и попробовать на русской раскладке сказать что то по таярски( :о)
#### Дополнительная информация:
Судя по всему не работают все ксеноязыки на русской раскладке.

**Comment by igigin** [comment]
Если верить гиту они никогда и не работали, поэтому отмечу как предложение.

**Comment by Nerevrin** [comment]
Никогда не работали. Но сделать-бы неплохо. Верно не только для таяр, но и для остальных ксеносов.
