### ISSUE TITLE
У алиенов не работает термал вижен и вместо него них ноер вижен

### ISSUE THREAD

**Issue by Misakiwa** [TauCetiStation/TauCetiClassic#8360]
#### Подробное описание проблемы
Не работает зрение хуманов через стены, вместо него них ноер вижен, который убирается после перезахода.
#### Что должно было произойти
Работать
#### Что произошло на самом деле
Не работает
#### Как повторить
Зайти за alien
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/36154069/145082162-e9861465-9886-42a1-ad6c-293de5423204.png)

**Comment by Sakuya-Izayoi** [comment]
#8274

**Comment by Misakiwa** [comment]
> #8274

Работало же после этого пра, это, по моему, только-только появилось.

Апдейт: это не только у квины, а у всех. А еще у них включен ноир вижен. 
Я уверен, что это пр с кнопками абилок для аленей.

**Comment by KIBORG04** [comment]
из-за него. А хули ноер_вижон я еще не разобрался
![image](https://user-images.githubusercontent.com/26389417/145085306-b1f78ba0-f466-45ff-8872-3d2873206402.png)
![image](https://user-images.githubusercontent.com/26389417/145085313-282f7e9a-5593-409c-a341-efb72e13567f.png)
