### ISSUE TITLE
[Proposal] Добавить First-Aid Kit и/или Nanomed на научный аванпост

### ISSUE THREAD

**Issue by hazehazehaze** [TauCetiStation/TauCetiClassic#8366]
#### Подробное описание проблемы
Очень часто на научном аванпосте есть необходимость зашить/остановить артериальное кровотечение, но там нет даже простого бинтика, хотя Nanomed с suture kit есть даже в ботанике.
#### Что должно было произойти
спасение жизни
#### Что произошло на самом деле
смерть

**Comment by Rahmanio** [comment]
skill issue
![Screenshot_527](https://user-images.githubusercontent.com/67812445/145481491-ff28922e-1b9c-4363-9521-278628a2986a.png)

**Comment by Rahmanio** [comment]
но я добавлю наномед на случай, если зашивалок не хватит трёх ксеноархеологов...
