### ISSUE TITLE
При рестарте борга видны призраки

### ISSUE THREAD

**Issue by DanKOisTaken** [TauCetiStation/TauCetiClassic#8367]
#### Подробное описание проблемы
Играл на борге. Меня уничтожили. После восстановления робототехником остался гост вижн.
#### Что должно было произойти
Я не вижу призраков
#### Что произошло на самом деле
Я вижу призраков
#### Как повторить
Сидеть на борге во время восстановления. Возможно ещё нужно пару раз войти/выйти в/из тела
#### Дополнительная информация:
Issue reported from  Round ID: 47043 (Tau Ceti Classic (RU))
Testmerges: ```#8293 #8303 #8334 #8338 #8333 ```
Reporting client version: 514.1571

**Comment by TEXH4Pb** [comment]
@KIBORG04 мне кажется, у этого бага могут ноги расти оттуда же, откуда и у моего с вентиляцией. У меня есть подозрения, что у мобов update_vision неправильно работает.

**Comment by KIBORG04** [comment]
На боргов тот баг вроде и не должен работать

**Comment by TEXH4Pb** [comment]
> На боргов тот баг вроде и не должен работать

Но у меня ведь подкласс боргов
