### ISSUE TITLE
[Proposal] Нужно поменять цвет окси урона у Crew Monitorng Computer

### ISSUE THREAD

**Issue by Misakiwa** [TauCetiStation/TauCetiClassic#8368]
Очень давно надо было поменять, ведь он просто не читабельный, пока его не выделишь, эм. . .
Например, на голубой.
![image](https://user-images.githubusercontent.com/36154069/145262847-67b24397-ed5b-479a-a679-9cf34de1201c.png)

**Comment by kiVts** [comment]
Просто менее кислотный синий, все время путаю с 8 или 9
