### ISSUE TITLE
Клонировали меня, а я маг. Нажимаю выход из тела (вещи на мне) пропадаю но идти не могу

### ISSUE THREAD

**Issue by Gelole** [TauCetiStation/TauCetiClassic#8374]
#### Дополнительная информация:
Issue reported from  Round ID: 47074 (Tau Ceti Classic II (RU))
Testmerges: ```#8340 #8338 #8334 #8333 #8303 #8293 ```
Reporting client version: 514.1569

**Comment by KIBORG04** [comment]
че
