### ISSUE TITLE
Кое-кто не переключил раскладку и заюзал русскую с, а не английскую

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#8378]
#### Подробное описание проблемы
https://github.com/TauCetiStation/TauCetiClassic/blob/675d78b9c480077cb7e8be71ff1156ca23bc0e0a/code/modules/mob/living/carbon/xenomorph/effects/aliens.dm#L537

#### Что должно было произойти
`c` а не `с`

#### Что произошло на самом деле
`c`
#### Как повторить
https://github.com/TauCetiStation/TauCetiClassic/blob/675d78b9c480077cb7e8be71ff1156ca23bc0e0a/code/modules/mob/living/carbon/xenomorph/effects/aliens.dm#L537
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/26389417/145605140-2f686835-a6d0-4aa9-b892-e13a80848b58.png)

**Comment by KIBORG04** [comment]
Я могу даже баунти выделить на решение данной задачи, вы только напишите, если кто-то решиться взяться за это.

**Comment by KIBORG04** [comment]
![image](https://user-images.githubusercontent.com/26389417/145607650-72399aa6-c8c7-4efe-a2ea-80f2172b82ff.png)

Я еще нашел.

**Comment by Ahion** [comment]
Ну жду баунти тогда
