### ISSUE TITLE
Не работает граб фишка "живой щит" 

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#838]
#### Подробное описание проблемы
Если воспользоваться другим космонавтиком как живым щитом, через тройной граб, то все пули все равно достанутся его захватчику. 

#### Что должно было произойти
Космонавтик, который был использован как щит, должен был сперва принять урон на себя

#### Что произошло на самом деле
Весь урон достался человеку, который же и использовал космонавтика как живой щит. 

#### Как повторить
Возьмите в тройной граб другую куклу и постарайтесь словить пару пуль/лазеров.

**Comment by SpaiR** [comment]
#489
