### ISSUE TITLE
[Proposal] [F] Для абдукторов

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#8380]
#### Подробное описание проблемы
Добавить чату абдукторов заветную кнопочку [F], оно же Follow
#### Что должно было произойти
Должна быть [F]
#### Что произошло на самом деле
Нужно рыться через панель чтобы найти того самого агента :(

#### Дополнительная информация:
Удобство и оперативность, ябзакодил, но я нуб простите пожалусто

**Comment by Venngedi** [comment]
Закрывайте. У абдукторов есть (F).
