### ISSUE TITLE
Полностью пропал гоствижен

### ISSUE THREAD

**Issue by Lexakr** [TauCetiStation/TauCetiClassic#8385]
#### Подробное описание проблемы
Полностью пропал гоствижен, включать/выключать не помогает, такая проблема у всех плееров. Видно только своего госта
#### Что должно было произойти
Видно гостов со включенным гоствиженом
#### Что произошло на самом деле
Гостов не видно
#### Как повторить
Зайти в обзерв на сервере

**Comment by KIBORG04** [comment]
Это че, опять мой сигхт рефактор все сломал?
