### ISSUE TITLE
 Перевод законов ии

### ISSUE THREAD

**Issue by Lianes1** [TauCetiStation/TauCetiClassic#8388]
#### Подробное описание проблемы
Некорректный перевод законов ии на вики из-за чего появляется не соответствие
#### Что должно было произойти
Все корректно переведено, либо изменен закон на английском языке
#### Что произошло на самом деле
Некорректный перевод
#### Как повторить
Открыть вики, зайти в игру за ии и сравнить законы.
#### Дополнительная информация:
Serve: Serve the crew of your assigned space station and Nanotrasen officials to the best of your abilities, with priority as according to their rank and role.
Служить: Прислуживай экипажу станции и представителям НТ, в меру своих способностей, в соответствии с их рангом и ролью.
Главное не соответствие происходит в моменте со словом "priority", в переводе оно просто упущено.
__Что это значит__
 Приведу следующий пример. Если следовать толкованию законов ии на английском языке, то это значит, что мы должны выполнять любой приказ от членов персонала, которые не нарушают другие законы ии, лишь с поправкой на их очередность выполнения. То есть если тестовик попросит открыть дверь в хопскую, ии не может отказать тестовику, если только хоп или любой другой глава не скажет ии не пускать внутрь тестовика.

С другой стороны, если толковать законы ии со стороны русского перевода, то получается, что ии начинает опираться на соп и прочие регулировки НТ, то есть, ИИ обязан выполнять все приказы, которые попадают в возможности определенной должности но не более, то есть ии не обязан исполнять просьбу тестовика об открытии двери в хопскую

**Comment by volas** [comment]
У нас где-то был вымученный ПР но кто-то похоже умер

**Comment by kiVts** [comment]
Да там тоже конченый перевод что муха повесилась

**Comment by kiVts** [comment]
Вообщем вот перевод serve для меня

Служи экипажу назначеной вам станции и другим официальным представителям НаноТрасен,  в меру ваших возможностей, с приоритетом и соответствием их Ранга и роли. 
Нет это не капипаста с транслятора


Проблема в том что, мы потеряли BEST of your abilities

**Comment by Fenriros** [comment]
Напиши в  ПР
