### ISSUE TITLE
Можно ставить турельки под шлюзы

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#8389]
#### Подробное описание проблемы
Можно ставить турели под шлюзы из за чего их невозможно уничтожить  
#### Что должно было произойти
нельзя ставить
#### Что произошло на самом деле
можно ставить
#### Как повторить
поставить турель под шлюз,закрыть шлюз

**Comment by Sakuya-Izayoi** [comment]
Duplicate of #8204 

Хватит плодить одинаковые ишью, это не способствует решению проблемы

**Comment by simb11** [comment]
ладно...
