### ISSUE TITLE
Худ здоровья отображается не правильно.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#839]
#### Подробное описание проблемы
Худ, который показывает здоровья куплы показывает его не правильно.
#### Что должно было произойти
Он должен работать корректно.
#### Что произошло на самом деле
Вот это.
![5215](https://cloud.githubusercontent.com/assets/18488106/20708872/ac783f04-b63a-11e6-8ad6-ab01ae410c49.png)

#### Как повторить
Получить урон.
#### Дополнительная информация:
Так же худ не показывает урон на кукле, когда он есть на кистях или пятках.

**Comment by SpaiR** [comment]
>Он должен работать корректно.

Я вижу по аналайзеру урон у головы. На кукле голова пожелтела. В чём проблема?

**Comment by Raschert0** [comment]
100% над куклой

**Comment by SpaiR** [comment]
Всё, понял. А то упоминалась кукла, вот я и подумал... Камень в огород  фразы:
>Худ, который показывает здоровья куклы

**Comment by Skippeer12** [comment]
Ну я пытался, не умею я в название, не бей сильно.

**Comment by Skippeer12** [comment]
![51251](https://cloud.githubusercontent.com/assets/18488106/20709517/a7e61746-b63e-11e6-8ef8-73e6bfd49b65.png)

**Comment by Skippeer12** [comment]
Проблема в том что я не доглядел что там в крови был инапровалин.
