### ISSUE TITLE
Трансит труба и ее хождение сквозь стены, разрыв реальности

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#8393]
#### Подробное описание проблемы
Если сбоку зайти в трансит трубу по диагонали то в трансит трубе появится персонаж но сам игрок (и персонаж) пройдет сквозь стену (визуальный дюп?)
#### Что должно было произойти
Игрок заходит в трансит трубу
#### Что произошло на самом деле
Игрок проходит сквозь стену и ?визуально? дюпается
#### Как повторить?
Самый легкий способ:
Метка - местонахождения персонажа
Стрелка - направление движения 
![image](https://user-images.githubusercontent.com/82588639/145701742-6aac3297-2c12-4b18-aa25-e17af74a0103.png)
Или
![image](https://user-images.githubusercontent.com/82588639/145701706-ffe7bac2-7b9b-46b4-88f8-9d2b6b36ce1e.png)
#### Дополнительная информация:
Приемник мусора имеет аналогичный баг
Думаю это случилось после добавления диагонального перемещения
Раунд 47150, 1 сервер, ТМ: #8383 #8333 #8293 #8280

**Comment by KIBORG04** [comment]
дупликате

**Comment by LoTaRk-FroG** [comment]
Киборг ты дурак, даты смотри :rastroen:
