### ISSUE TITLE
Рантайм криопода, вызванный ТМом дрона

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#8395]
#### Подробное описание проблемы
> 820 Runtime in cryopod.dm:211 : cannot read from list
   1033 Runtime in cryopod.dm:211 : cannot read from list

#### Что должно было произойти
нету

#### Что произошло на самом деле
есть

#### Как повторить
???

#### Дополнительная информация:
#8280

**Comment by TEXH4Pb** [comment]
Вроде пофиксил у себя в ветке, рантаймить не должно больше.
