### ISSUE TITLE
[Proposal] Дать синдиборгам систему выбора игроков как у pAI

### ISSUE THREAD

**Issue by DanKOisTaken** [TauCetiStation/TauCetiClassic#8397]
#### Подробное описание проблемы
К синдиборгам должны предъявлятся намного бОльшие требования, чем к обычным боргам. Сейчас за синдиборга может заходить любой игрок с префами на оперативника, что иногда приводит к ситуациям, когда за него садится игрок, даже не знающий что такое борги и как на них играть. Данная же система позволит отсеять часть людей, которые не понимают как играть.
#### Что должно было произойти
При призыве синдиборга оперативники могут выбрать понравившийся им вариант.
#### Что произошло на самом деле
За синдиборга заходит игрок с малым опытом на борге.
#### Как повторить
Зайти на 1 сервер в час пик -> активировать маяк -> дождаться появления -> приказать боргу поменять руки
#### Дополнительная информация:
Возможно вы спросите: "Как тогда люди будут учится на них играть?", а я отвечу: "Для этого есть обычные борги и дроны.".

**Comment by Sakuya-Izayoi** [comment]
это отличный способ для друзей постоянно выбирать друг друга и не давать рандомам поиграть на роли. когда ты полагаешься на другого игрока, будь-то синдиборг или какое-то обычное взаимодействие в раунде это всегда рандом и это нормально, с этим ничего не поделать.

**Comment by TEXH4Pb** [comment]
Согласен с аргументами выше. Предложеная механика напрямую нарушает правила игры о метагейме, так что введение её в игру абсурдно.

**Comment by DanKOisTaken** [comment]
Хммм, я правда не думал о таком раскладе. Тогда лучше оставить всё как есть, ибо может вызвать очень много бурлений.

**Comment by DarthSidiousPalpatine** [comment]
И, тогда, каждого главу открывать за минутки на определённых главах. Только как это ввести-то, лол. Все минутки сбрасывать теперь?
