### ISSUE TITLE
Проблема с отображением карты через Crew Monitoring Computer или планшетный аналог парамедиков

### ISSUE THREAD

**Issue by Follint** [TauCetiStation/TauCetiClassic#8406]
#### Подробное описание проблемы
Время от времени, по неизвестным причинам во время игры при попытке открыть окно этой консоли высвечивается ошибка, запечатленная на скрине. Если нажать OK, то она выскочит вновь, пока не будет отмечен бокс "не разрешать этой странице создавать новые сообщения". Причины не известны, перезаход иногда помогает, а иногда нет. Раунд, после которого пишу ишью - 47276. Примерно в 13:20-13:25 серверного времени эта проблема появилась, но в 13:37 уже снова пропала. Ни перезахода, ничего для решения проблемы предпринято не было. Ранее с этой проблемой уже сталкивался, иногда помогает перезаход, а иногда не помогает ровным счетом ничего. Если выскакивает эта ошибка - карта ломается и её нельзя смотреть
#### Что должно было произойти
Окно не должно появляться, карта должна быть всегда доступна.
#### Что произошло на самом деле
Окно появляется, карта становится недоступна
#### Как повторить
Понятия не имею. То происходит эта ошибка, то нет.
#### Дополнительная информация:
![problemos](https://user-images.githubusercontent.com/96236648/146357214-4e951add-9235-408c-a028-b3dc3e541c7f.jpg)

**Comment by kiVts** [comment]
Этому багу уже 2 года точно

**Comment by Sakuya-Izayoi** [comment]
Duplicate of #7377
