### ISSUE TITLE
Гунчат без гуниконок.

### ISSUE THREAD

**Issue by Leshiy-ART** [TauCetiStation/TauCetiClassic#841]
Иконки мне запилите :(
![image](https://cloud.githubusercontent.com/assets/4739426/20712096/c3d4d7de-b653-11e6-8fa8-c128c48cdf69.png)

**Comment by Raschert0** [comment]
Э... А чистка кеша не помогла?

**Comment by StrikS** [comment]
А у меня все есть

**Comment by Leshiy-ART** [comment]
Nope. Только что почистил - никаких изменений.

**Comment by SpaiR** [comment]
Какая у тебя система на компьютере стоит?

**Comment by Leshiy-ART** [comment]
![image](https://cloud.githubusercontent.com/assets/4739426/20712288/7b01b828-b654-11e6-8b21-56511a4af734.png)

**Comment by Leshiy-ART** [comment]
Ох, е. Подозреваю это из-за IE8

**Comment by SpaiR** [comment]
>Подозреваю это из-за IE8

Обновись, если появятся иконки - отпишись, закрой ишью.

**Comment by Leshiy-ART** [comment]
Да. Обновил - все заработало.
Пора вывешивать минимальные системные требования для ССочки.

**Comment by Raschert0** [comment]
Минимальные требования:
- Core i7
-   GTX 1080
-   SSD 300GB
