### ISSUE TITLE
Отстреленная голова слагом отправляет генокрада в нульспейс

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#8425]
#### Подробное описание проблемы
Раунд 47438. Лишение головы слагом из дробовика отправляет в нульспейс. Хедслаг спавнится живым прямо в нульспейсе, кроме гостаться ничем админ не поможет, так как "отображение гостов херовое" (с) Лижард
#### Что должно было произойти
Либо хедслаг вылазит из головы до смерти (в чём и суть абилки), либо не вылазит вообще и слаг в голову не прокает ласт резорт
#### Что произошло на самом деле
Лишение головы слагом отправляет червяка в нульспейс. 
Deahaka was Troy Orgail (survived as ) и иконка моего хедслага
Objective #4: Stay alive until the end. SUCCESS
#### Как повторить
Нажать ласт резорт перед смертью, а может не прошёл клик и это баг спавна червяка, я без понятия

**Comment by kalazus** [comment]
Весьма вероятно что описание неправильное. Отстрел головы работает как нужно, а вот гиб (слаги поинтбланк в тело), именно и создаёт хеадслага в нуллсепейсе.

**Comment by Deahaka** [comment]
> Весьма вероятно что описание неправильное. Отстрел головы работает как нужно, а вот гиб (слаги поинтбланк в тело), именно и создаёт хеадслага в нуллсепейсе.

Клауд (если я не ошибаюсь) умер через минуты две от отстрела головы, но спрайт его госта был именно мозг, хотя он сказал что пытался нажать ласт резорт. Почему у меня червяк в нульспейсе - загадка.

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/put-k-velikomu-uchimsya-chitat-zanovo/30645/1
