### ISSUE TITLE
Проблема с трансплантацией мозга

### ISSUE THREAD

**Issue by 05126619z** [TauCetiStation/TauCetiClassic#8429]
#### Подробное описание проблемы
После трансплантации мозга из ГП в куклу нельзя было дефибрилировать тело куклы с мозгом ГП, подозреваю, что из-за фикса пересадки бошки и мозгов вокса.
#### Что должно было произойти
После трансплантации, дефибриляция, и здоровый ГП
#### Что произошло на самом деле
После вставки мозга в куклу, дефибрилятор выдавал Operation Aborted
#### Как повторить
Пересадить мозг с любым игроком внутри

**Comment by KIBORG04** [comment]
И че тут не так?

**Comment by 05126619z** [comment]
Да то, что после пересадки мозга уже нельзя клонить после фикса

**Comment by KIBORG04** [comment]
Так и не должно
