### ISSUE TITLE
Говорящие абдукты, знающие сол и трейдбанд

### ISSUE THREAD

**Issue by flying-george** [TauCetiStation/TauCetiClassic#8430]
#### Подробное описание проблемы
Абдукты умеют говорить с персоналом, ртом
#### Что должно было произойти
Они должны молчать
#### Что произошло на самом деле
Говорят на соле и трейдбанде
#### Как повторить
Написать за абдукта :1 и :2 перед сообщением
#### Дополнительная информация:
Issue reported from  Round ID: 47505 (Tau Ceti Classic (RU))
Testmerges: ```#8402 #8359 #8333 #8316 #8280 #8179 ```
Reporting client version: 514.1568

**Comment by ssbugman** [comment]
Я думал это фича и для них это просто чужой язык.

**Comment by Deahaka** [comment]
Блин, почему я об этом узнал уже когда собираются фиксить? А такая надежда была, что стелсоабдукторы больше не будут говном ненужным...

**Comment by KIBORG04** [comment]
Это всю жизнь было фичей, но я код не смотрел, а значит не буду закрывать ишуй

**Comment by AndroBetel** [comment]
У воксоу все им известные языки вырезаются, а про абдукторов забыли. У них рта нет ваще...

**Comment by KIBORG04** [comment]
Это действительно похоже на баг.

**Comment by Sakuya-Izayoi** [comment]
Duplicate of #4833

**Comment by flying-george** [comment]
Педали сказали, что это баг, имхо они язык не признают. Но вообще согласен, что фича очень клевая
