### ISSUE TITLE
Ремап инженерки: Подача азота отличается от остальных подач из смесителей

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#8439]
#### Подробное описание проблемы
Всё в скринах:

Вот так выглядит типичный смеситель с вентилем на выходе, на примере О2,
![image](https://user-images.githubusercontent.com/42682553/147459397-cc200b6d-1cf2-4d4c-90be-f6d98fa63404.png)

А это азот, где вместо вентиля почему-то насос, который к тому же был сначала вырублен,
![image](https://user-images.githubusercontent.com/42682553/147459484-07a693ce-fa46-43b6-9afe-27057019b257.png)

Я бы и не заметил этого изменения, если бы не увидел 0 кПа в смесителе воздушной смеси - раньше был просто включенный вентиль, доставлявший азот из смесителя в миксер - и это потом объединялось в воздушке.

Почему он тут? Регуляцию давления азота можно провести и через консоль смесителя, зачем этот насос???
#### Что должно было произойти
Вентиль!
#### Что произошло на самом деле
Насос! Я думал что вентиль включенный, а там насос выключенный!
#### Как повторить
Быть атмостехом
#### Дополнительная информация:
Меня забуллил маппер

**Comment by Tap0r** [comment]
Это не моё :call_me_hand:
![tapor2](https://user-images.githubusercontent.com/88531962/147467593-5272242c-d5da-4199-aee3-5b9ad71dfdbc.png)

**Comment by Pivo24** [comment]
А как так я же единственный атмостех...

**Comment by kalazus** [comment]
Возможно это только на зимней карте.

**Comment by KIBORG04** [comment]
Опытным путём установлено, что добавляет этот насос https://github.com/TauCetiStation/TauCetiClassic/pull/8359

**Comment by KIBORG04** [comment]
Как-то пофиксилось
