### ISSUE TITLE
Прокладывание проводов убивает сердце

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#8440]
#### Подробное описание проблемы
При прокладке проводов сердце может случайно зафейлиться даже если провода не подключены к электросети.

#### Что должно было произойти
Прокладка проводов не подключенных к электросети не должна вырубать сердце.

#### Что произошло на самом деле
Прокладка проводов не подключенных к электросети вырубила сердце.

#### Как повторить
Минимальный сетап который нужен это моток проводов и достаточное количество турфов чтобы их класть. При прокладке с некоторым шансом сердце вырубится, что можно будет распознать по характерным сообщениям в чат.

#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/30875884/147508929-43c475f6-a266-447f-a519-b845f31ce805.png)

**Comment by KIBORG04** [comment]
Мне кажется, шанс на остановку сердца прокает слишком часто.

**Comment by ssbugman** [comment]
Мне кажется механ остановки сердца слишком глупый и риск остановки должен быть только при сильных ударах, например когда коллекторы напрямую воткнули.

**Comment by DarthSidiousPalpatine** [comment]
Он так и должен быть. Прокладывание проводов просто багнутое, судя по всему.

Не проблема сердца.

**Comment by DarthSidiousPalpatine** [comment]
Сердце отключается только от препаратов, что останавливают сердце и от сильного удара током. Причём с шансом.

Не проблема остановки сердца что провода без тока бьют током, видимо, каждый раз.

**Comment by KIBORG04** [comment]
Слишком часто прокает и не даёт кукле хоть как-то выжить. Дебильный механ, которые мешает игроку играть в игру и тупо убивает, даже без фидбека в чат

Я блин буквально умер, когда разбил лампочку.

**Comment by ssbugman** [comment]
> Сердце отключается только от препаратов, что останавливают сердце и от сильного удара током. Причём с шансом.
> 
> Не проблема остановки сердца что провода без тока бьют током, видимо, каждый раз.

Очевидно что проверка на силу вообще не происходит и даже при ударе нулевой силы шанс равен тому который будет при хватании провода прямо у коллектора.

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/8006/files#r775875360

Проблема тут и из-за этой строчки онли
