### ISSUE TITLE
[Proposal]Слишком имбовый пирометр СЕ

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#8443]
#### Подробное описание проблемы
Сейчас емагнутый пирометр се — самое сильное лазерное оружие которое только можно найти на станции,это потому что он наносит 45 урона,очень скоростельный,не снижает скорость передвижения,имеет почти бесконечный заряд батареи и зум,который не убирается даже при беге,что в итоге превращает пирометр в оружие массового уничтожения любых живых существ.Даже аблятив не особо спасает.
Вот несколько идей для нерфа пирометра:Сделать убирание зума как у снайперки.Увеличить потребление энергии до 2500е за выстрел.Уменьшить скорость стрельбы.

**Comment by Sakuya-Izayoi** [comment]
Можно поднять цену за выстрел только в эмаг режиме хотя бы до 1000, я думаю.

**Comment by Kurshan** [comment]
Забыл прилинковать, закрывайте https://github.com/TauCetiStation/TauCetiClassic/pull/8465
