### ISSUE TITLE
[Proposal] Нерф хедкрабов алиенов

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#8447]
#### Подробное описание проблемы
Кидание фейсхагера алиенами с каким-то (очень высоким) шансом прокает лип и стан оппоненту, адекватной защиты этому не найти никак.
Предлагаю убрать возможность хантерам и стражам брать в руки неигровых крабов, чтобы это не использовалось в нападении, а только как защита. Дронам и квине оставить, так как они реже ходят в бой, где используется этот метод ведения войны.

#### Дополнительная информация:
Стан от хедкраба длится не меньше 10 секунд, а это на уровне гранатомёта

**Comment by Pivo24** [comment]
Охотникам бы с квиной Regurgulate вернуть, честно, без этой кнопочки мне никак... Грустю

**Comment by Ahion** [comment]
Да, думаю это ограничение имеет смысл.

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-otkat-podnyatiya-fejshaggerov/31089/58
