### ISSUE TITLE
Можно строить столы и залазить на них в непроходимых турфах.

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#8453]
#### Подробное описание проблемы
Находясь в стене можно построить стол или стеллаж и потом с помощью драг н дропа залезть на этот стеллаж или стол.

#### Что должно было произойти
1. Столы и стеллажи нельзя ставить в стенах.
2. На столы и стеллажи нельзя залазить если они в стенах.

#### Что произошло на самом деле
1. Столы и стеллажи можно ставить в стенах.
2. На столы и стеллажи можно залазить если они в стенах.

#### Как повторить
Попасть на непроходимый тайл (например, стену) любым известным способом, построить там стол или стеллаж, выйти из этого тайла и попробовать залезть на стол.

**Comment by volas** [comment]
есть еще проблема с трубами, и что так можно выбраться за пределы станции на слое цк.

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/8456
