### ISSUE TITLE
Отсутствие эффекта "слепоты" в вентеляции.

### ISSUE THREAD

**Issue by Ahegaoorc** [TauCetiStation/TauCetiClassic#8454]
#### Подробное описание проблемы
После перезахода в игру, когда дрон находился в вентеляции, эффект "слепоты" пропал и стало видно всё помещение.
#### Что должно было произойти
Эффект "слепоты" должен был остаться
#### Что произошло на самом деле
Эффект "слепоты" пропал
#### Как повторить
Перезайти в игру находясь в вентеляции
#### Дополнительная информация:
![issue](https://user-images.githubusercontent.com/96296015/147883795-e051875f-6468-448d-aad8-a0b9a6ab572c.png)

**Comment by LoTaRk-FroG** [comment]
Дупликат #8450
