### ISSUE TITLE
Комнатка для убийства слаймов теперь бесполезна из-за зимней карты.

### ISSUE THREAD

**Issue by notkripton** [TauCetiStation/TauCetiClassic#8462]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/75007994/148104829-43c44b49-fd4d-4bae-991d-156689de38cc.png)
^
||
Из-за зимней карты вот эта комнатка ксенобиолога для убийства слаймов стала бесполезной, так как космоса за окном уже нету и слаймы умирать в ней не хотят.
Как возможное решение можно добавить слаймам урон от холода, ну или убрать на время зимы эту комнатку и оставить бедных биологов плакать.

**Comment by Pivo24** [comment]
Ты уверен что это "комнатка для убийства слаймов"?

:joy: 

Знаешь как убивали слаймов? Тянули их в предбанник, по одному, закрывали обязательно слайма в пространстве 2 на 1, и делали два клика огнетушителем по плитке пола под слаймом. Слайм умирал, следующий.

~~Ууууу тупые зумеры ууууууууууууу~~

**Comment by KIBORG04** [comment]
Ууууу тупые зумеры ууууууууууууу

**Comment by notkripton** [comment]
Та знаю я как их убивать, фашисты вы сраные :pekarage:
Комнатка обьективно (!) круче и это НЕ обсуждается!
А еще вики не аргумент иии
![image](https://user-images.githubusercontent.com/75007994/148127946-2c895584-04d1-4464-b3e5-507c7abc100b.png)

**Comment by Dushess0** [comment]
Просто заполни эту комнату пеной их огнетушителя и наслаждайся.

**Comment by Sakuya-Izayoi** [comment]
Это не баг и не пропосал, это просто нытье. Нойте на форуме.
