### ISSUE TITLE
[Proposal] Пирометр как оружие последнего шанса

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#8466]
#### Подробное описание проблемы
Пирометр СЕ в емагнутом состоянии позволяет воевать в одиночку против станции. Это очень помогает камбекать игру нюкерам и триторам, если тупо давят числом, и это хорошо. Но пирометр, работающий на батарейках, по факту бесконечный, что позволяет антагонисту выпиливать вообще всех вплоть до конца раунда, не оставляя шанса что-то предпринять обычным гражданям, которые и остались не убитыми. По-этому предлагаю сделать заряд пирометру на убийство 10 человек, то есть (200/45)*10+5 = 50 - константных выстрелов, которые не обновить, не сбросить и не улучшить никакими деталями и батарейками. Перегревается инструмент и не стреляет в летальном режиме.
#### Дополнительная информация:
200 это макс хп куклы, 45 это урон пирометра, 5 лишних выстрелов на промахи

**Comment by Kurshan** [comment]
Забыл прилинковать, закрывайте https://github.com/TauCetiStation/TauCetiClassic/pull/8465
