### ISSUE TITLE
[Proposal] Удаление платы СБ-модуля из кабинета РД

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#8475]
#### Подробное описание проблемы
9 из 10 СБ-боргов являются ролькохантящими-грифодебилами, которые берут ксеноса (нехумана) исключительно для преимущества в бою с антагом, при этом не регулируемы ни Космозаконом, ни СПД, ни даже своими законами, руководясь исключительно своими хотелками.
Пропосал именно на удаление только раундстартовых СБ-боргов, так как даже один такой может заруинить режим в начале смены.
#### Дополнительная информация:
Борги избивающие людей за слова "это генокрад"; арестовывающие без захвата, если ты в розыске и подскользнулся перед ним; хармдубинка, если отстегнулся от стула в допросной, будучи в наручниках; погоня по всей станции и вне её за флешер при пуле человека в наручниках - - - Не кайф.

**Comment by Tap0r** [comment]
- Борги избивающие людей за слова "это генокрад"

Ситуация максимально не ясна. Кто говорит? Почему говорит?

- арестовывающие без захвата, если ты в розыске

А че ему делать то. Давайте бипски блять вырежем, он людей в розыске арестовывает, совсем ахуел.

- хармдубинка, если отстегнулся от стула в допросной, будучи в наручниках.

Я на первом редко играю, может быть для вас там это обыденность, но мне кажется это утиные истории. Борг в допросной, что он там делает? Охраняет? Проводит допрос?

- погоня по всей станции и вне её за флешер при пуле человека в наручниках.

Не понял, борг пуллит, ты флэшишь? И какой реакции ты ждёшь в ответ на перегрузку сенсоров и попытку устроить побег?

Вывод: проиграл, пошёл на гит, удали не позорься 🪓🪓🪓

**Comment by Deahaka** [comment]
> Ситуация максимально не ясна. Кто говорит? Почему говорит?
> Я в техах увидел человека, пришёл СБ борг - я ему сказал что это генокрад - тот запиздил его почти сразу дубинкой и повёл в камеру брига
> А че ему делать то. Давайте бипски блять вырежем, он людей в розыске арестовывает, совсем ахуел.
> Бипски ломается тремя ударами, борг 1000-ю
> Я на первом редко играю, может быть для вас там это обыденность, но мне кажется это утиные истории. Борг в допросной, что он там делает? Охраняет? Проводит допрос?
> Это обыденность потому что на боргах сидят грифодебилы, о которых я и рассказываю, разве так и должно быть? Борг ничего не охраняет, просто стоит ролькохантит.
> Не понял, борг пуллит, ты флэшишь? И какой реакции ты ждёшь в ответ на перегрузку сенсоров и попытку устроить побег?
> Одно дело побег, но и то это не нарушение законов синтетов, а другое это флешер когда борг чем-то занят, без попытки дальше что-то делать. Он гнался за мной по движку минуты 3, а потом в космосе минут 10. Это норма?
