### ISSUE TITLE
[Proposal]Что-то сделать с синаптизином

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#8476]
#### Подробное описание проблемы
Синаптизин абсолютно бесполезен,его никто не просит(кроме вирусолога),его никто не использует по прямому назначению.В боевых автоиньекторах он только мешает своим токсичным уроном и замедлением от него же.Амброзия деус должна лечить,вроде как,но она наоборот убивает человека из-за урона от синаптизина.Сам по себе синаптизин полезен только снижением стана от СШ гранат,в других ситуациях он юзалесс
#### Что должно было произойти
Синаптизин хоть изредка используется как адреналин
#### Что произошло на самом деле
Синаптизин никто не использует потому что он приносит больше вреда,чем пользы
#### Как повторить
Попытаться использовать синаптизин 
#### Дополнительная информация:
Самое просто решение этой проблемы - удалить токсикдемедж при попадании в организм и усложнить рецепт/добавить туда какой-нибудь шахтёрский ресурс(уран, например).

**Comment by Rolt146** [comment]
Синаптезин это хороший яд. Человееу суперхуево от коктеля токсинов, но при этом состояние здоровья показывает как идеальное. Стелсотриторы его любят
