### ISSUE TITLE
Иноправолин не дает сердцу остановиться и это плохо для мертвых.

### ISSUE THREAD

**Issue by DespairSoul** [TauCetiStation/TauCetiClassic#8480]
#### Подробное описание проблемы
Перед смертью player/куклы в нем(-ей) был иноправолин. Пока он в теле (иноправолин), массаж сердца почему-то нельзя провести.
#### Что должно было произойти
Даже с иноправолином в крови перед смертью - можно сделать массаж сердца.
#### Что произошло на самом деле
Вселенная просто игнорирует попытки массажа сердца, пока иноправолин в теле.
#### Как повторить
Иноправолин в тело, тело умирает с иноправолином в крови, попытка реанимации.
#### Дополнительная информация:
Если выкачать иноправолин из трупа, то массаж сердца снова будет доступен. Если ввести иноправолин в уже мертвое тело, ошибка не случается.

**Comment by DespairSoul** [comment]
Еще вот, иноправолин не дает остановиться сердцу у трупа уже, вот оно как. Получается, есть шанс, что так и должно быть? Но думаю вряд ли у трупа бы билось сердце все равно, даже с иноправолином + он не усваивается.
![image](https://user-images.githubusercontent.com/62647323/148724376-b9de2b71-552c-4b54-8820-1545564bc4d6.png)

**Comment by kalazus** [comment]
По плану инапровалин должен держать сердце в фибрилляции. Т.е. начальный массаж сердца чтобы заставить его работать не нужен. А вот почему не работает обычный массаж сердца для окси урона не понимаю.
