### ISSUE TITLE
Скерллы не могут модифицировать скафандр СЕ под себя.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#849]
#### Подробное описание проблемы
После нерфов игигина, скреллы разучились модифицировать скафандры главы инженерного отдела.
#### Что должно было произойти
Они должны смочь модифицировать скафандр под себя.
#### Что произошло на самом деле
Они не могут.
#### Как повторить
Пойди поиграть скреллом СЕ.
#### Дополнительная информация:
#Коты_не_нужны#Ящеры_тоже
Так же не помешал бы спрайт, но их нет.

**Comment by igigin** [comment]
Спрайта нет - фикса нет. Со спрайтом фикса тоже не будет. Ксеносы-главы не нужны.

**Comment by Balphagore** [comment]
Но по правилам на вики скреллы могут быть СЕ, СМО и РД

**Comment by igigin** [comment]
Что вовсе не значит, что они нужны.

**Comment by Balphagore** [comment]
Это мемчики не нужны. А скрелл, даже если он кому-то не нужен, должен иметь возможность, будучи СЕ, нацепить свой скафандр. От этого может зависеть судьба станции.

**Comment by igigin** [comment]
Значит всего-то надо запретить жабам в СЕ. Задачу понял.

**Comment by Balphagore** [comment]
Если проще запретить жабам в СЕ, чем рисовать для них скаф, то почему бы и нет, я не ксенолюб. Просто все должно быть последовательно. Если жабы могут быть СЕ - нужен и риг, если нет... Хотя стоп... А почему собственно нет? А если ассистент-тритор-жаба сможет раздобыть на всей станции только риг СЕ, то и он должен иметь возможность его модифицировать. Это же может быть жизненно важно. Или ксеносы могут нацепить человеческий риг, а все эти модификации просто визуальные? (я вот честно не в курсе, как я сказал - не ксенолюб) Если отсутствие модификации не ограничивает возможность надеть его, то тогда вообще плевать.

**Comment by dearprincesscelestia** [comment]
> А если ассистент-тритор-жаба сможет раздобыть на всей станции только риг СЕ, то и он должен иметь возможность его модифицировать. 

А если клоун-тритор-жаба сможет раздобыть только тазер, то и он должен иметь возможность стрелять из него?

**Comment by igigin** [comment]
То что жабы могут в СЕ совершенно не значит, что под них делали этот риг. Как и то, что если кто-то что-то может украсть, не значит, что он может это использовать.

**Comment by Balphagore** [comment]
> А если клоун-тритор-жаба сможет раздобыть только тазер, то и он должен иметь возможность стрелять из него?

Так если клоун-тритор, то что мешает ему стрелять из тазера? Они вроде с наручниками не дружат, или им и оружие порезали?

> То что жабы могут в СЕ совершенно не значит, что под них делали этот риг. Как и то, что если кто-то что-то может украсть, не значит, что он может это использовать.

Если жабы официально могут быть СЕ, то риг должен быть рассчитан на модификацию под них. А вообще, физическая возможность модифицировать риг СЕ должна быть для любой расы. Умеют они это делать или нет - другой вопрос, но возможность нужна, от этого может зависеть судьба какого-нибудь раунда. Например абдукторы, сменили СЕ расу при помощи железы, он же не перестал от этого сразу быть СЕ. Или вы намекаете, что риг не поддается модификации в принципе из-за того, что он укреплен? Ну так с технической точки зрения он мало отличается от обычных, почему он не должен поддаваться модификации. 

В общем, мое мнение такое - все должно быть логично и последовательно. Если жаба может быть СЕ, то ее риг должен быть рассчитан и на нее. В идеале же, все риги должны быть рассчитаны на всех ксеносов, просто на всякий случай, даже на дион (как бы абсурдно это не казалось). Мы ведь тут код обсуждаем, а не личные предпочтения и ненависть к ксеносам. Но это в идеале, с чисто технической точки зрения. И это мое личное мнение.

**Comment by dearprincesscelestia** [comment]
> Так если клоун-тритор, то что мешает ему стрелять из тазера? Они вроде с наручниками не дружат, или им и оружие порезали?

А на тазеры кламси не распространяется? Тогда не тазер, а еган.

> В общем, мое мнение такое - все должно быть логично и последовательно. Если жаба может быть СЕ, то ее риг должен быть рассчитан и на нее. В идеале же, все риги должны быть рассчитаны на всех ксеносов, просто на всякий случай, даже на дион (как бы абсурдно это не казалось). Мы ведь тут код обсуждаем, а не личные предпочтения и ненависть к ксеносам. Но это в идеале, с чисто технической точки зрения. И это мое личное мнение.

Логично и последовательно как раз жабе-СЕ пойти в ЕВА и взять оттуда жабий риг, благо их там два, потому что логично и последовательно не пересобирать сложный скафандер под анатомию руками, рискуя сделать в нем дыры, а на заводе собрать подогнанный, нет?

**Comment by Moggilazz** [comment]
Эй, ксенофилы и поклонники Драгонира - спрайт скрелльского варианта скафа СЕ есть в природе, может и найдёте.

**Comment by StrikS** [comment]
Человек звучит гордо! Мы не будем подчиняться ксеносам - главам!

**Comment by igigin** [comment]
Я думал этот ишьюс уже закрыт давно.
