### ISSUE TITLE
С помощью нескольких консолей РнД можно получить бесконечное количество очков исследований при взрыве бомб/ЕМИ на полигоне.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#8499]
#### Подробное описание проблемы
Платы консолей РнД доступны на втором уровне инженерных исследований, который можно достичь запихнув в диконстрактор батарейку, после чего вы делаете несколько консолей и взрываете бомбы, очки со взрыва бомб будут доступны сразу на всех консолях которые вы собрали, путем не хитрых манипуляций с сихнонизацией, можно не только изучить всё но и поднять уровень технологий чтобы не делать прототипы.
#### Что должно было произойти
Очки со взрыва должны были попасть только на одну консоль
#### Что произошло на самом деле
Дупликация очков для изучения
#### Как повторить
1. Построить несколько консолей.
2. Взорвать бомбы на полигоне.

**Comment by TauKitty** [comment]
This issue has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/apellyacziya-skipper12-1darkwater1/31046/1

**Comment by Skippeer12** [comment]
Баг пофиксили, оригинальный ишью закрыли, дубликат не имеет смысла. #4351
