### ISSUE TITLE
Лежа можно качать бицуху

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#850]
#### Подробное описание проблемы
Crawl -> Клик по новой качалке -> Ты качаешься
#### Что должно было произойти
Crawl -> Клик по новой качалке -> You cannot do it
#### Что произошло на самом деле
![image](https://cloud.githubusercontent.com/assets/21046015/20850039/38b0d388-b8fb-11e6-9042-40a7039c2aaf.png)
#### Как повторить
Кравлом кликнуть по качалочке

**Comment by Raschert0** [comment]
Да, нужно сделать так, чтобы при попытке делать это из кравла на тебя падала штанга

**Comment by Skippeer12** [comment]
20 брута 40 окси.
Если никто не поможет поднять штангу, умрешь.

**Comment by WallShrabnic** [comment]
Жим лёжа жи
