### ISSUE TITLE
Неправильное описание у офицерских перчаток

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#8500]
#### Подробное описание проблемы
Неправильное описание у security gloves.
#### Что должно было произойти
Heavily padded heavy-duty black security gloves.
#### Что произошло на самом деле
Heavily padded heavy-duty red security gloves.
#### Как повторить
Осмотреть перчатки

**Comment by Rahmanio** [comment]
![Screenshot_797](https://user-images.githubusercontent.com/67812445/149675842-0e1a34a4-c1bb-4596-a1af-f819e0733daf.png)
Тот, кто это сделал в принципе и спрайт назвал секьюрити ред, который в отличии от старого спрайта не имеет красных оттенков.
![Screenshot_798](https://user-images.githubusercontent.com/67812445/149675861-98d26845-241c-4e85-a966-12157a9815fb.png)
