### ISSUE TITLE
Абдукторы могут говорить с экипажем через мегафое

### ISSUE THREAD

**Issue by Rolt146** [TauCetiStation/TauCetiClassic#8509]
#### Что должно было произойти
Ничего, немой абдуктор и глухой мегафое
#### Что произошло на самом деле
Capitan say: хаха, золотая карта моя
#### Как повторить
Быть кондуктором, взять в руки мегафон и заюзать его

**Comment by WallShrabnic** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/191

**Comment by muWander** [comment]
там вообще ни одна проверка не работает, немые например тоже могут говорить в микрофон
