### ISSUE TITLE
Борги могут стрелять себе в глотку

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#851]
#### Подробное описание проблемы
Силиконовые, имеющие в модулях оружие (охранный, охранный взломанный, синди), могут запихивать дуло своего же оружия в рот.
#### Что должно было произойти
Борги не могут застрелиться.
#### Что произошло на самом деле
Борги могут.
#### Как повторить
Стать охранным/боевым боргом, взять из модулей пушку, выбрать на кукле рот, стрелять.
#### Дополнительная информация:
Тазер:
![scr1](https://cloud.githubusercontent.com/assets/20542000/20861285/3873b546-b9b6-11e6-9ac0-802276b9fa85.png)

Энерго-арбалет синдиборга:
![scr2](https://cloud.githubusercontent.com/assets/20542000/20861286/4934e5c6-b9b6-11e6-95d8-49eb386adac1.png)

**Comment by StrikS** [comment]
Блин, вообще класс. :D

**Comment by Skippeer12** [comment]
Такую фичу спалил, как ты вообще живешь

**Comment by dearprincesscelestia** [comment]
Заменить рот на ПАУЕР СОККЕТ, и будет фича.
