### ISSUE TITLE
Упаковка удаляет флафф/предмет в сумке

### ISSUE THREAD

**Issue by NeOchenLord** [TauCetiStation/TauCetiClassic#8518]
#### Подробное описание проблемы
Я попытался упаковать свою шапку-флафф в почтовую бумагу, пока она лежала в сумке. Она исчезла.
Я не знаю что спровоцировало это, то ли флафф, то ли нахождение в сумке, то ли оба.

#### Что должно было произойти
В сумке маленькая коробочка с флаффом

#### Что произошло на самом деле
Флаффа нет :(

#### Как повторить
Флафф-шапку упаковать, пока она в сумке

#### Дополнительная информация:
Issue reported from  Round ID: 48238 (Tau Ceti Classic (RU))
Testmerges: ```#8356 #8359 #8404 #8445 ```
Reporting client version: 514.1571

**Comment by Sakuya-Izayoi** [comment]
А какое поведение наблюдается с другими предметами? Может упакованный итем на полу под ногами дропается?

**Comment by NeOchenLord** [comment]
Я дурак. Всё работает как надо, это я просто не увидел упаковку на полу 💯
