### ISSUE TITLE
[Proposal] Удар током через протез

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#8519]
#### Подробное описание проблемы
Было бы круто сделать шанс остановки сердца при ударе через протез меньше

**Comment by KIBORG04** [comment]
Так протезы металлические

**Comment by Deahaka** [comment]
Было бы круто и от мины убрать остановку сердца, но пока что гусев не взялся балансить

**Comment by Venngedi** [comment]
#9642
