### ISSUE TITLE
Вокс может стать ОБОПовцем

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#8520]
#### Подробное описание проблемы
Вокс может получить роль внедрённого агента ОБОП
#### Что должно было произойти
Вокс не может получить эту роль, так как на него не действует имплант и ЦК нормально проводит рассовую политику
#### Что произошло на самом деле
Вокс ОБОПовец
#### Как повторить
Взять расу вокса и получить раундстартовую роль
#### Дополнительная информация:
раунд с багом: 48243

**Comment by KIBORG04** [comment]
Не баг
![image](https://user-images.githubusercontent.com/26389417/150170799-fd3603e9-0bf7-42d3-adb7-5f64cd11b6bf.png)
![image](https://user-images.githubusercontent.com/26389417/150170836-b87a182c-6def-4be4-8bf1-70cd29b4df9c.png)
