### ISSUE TITLE
[Proposal]Выдать воксам,оперативникам синдиката и обр улучшения для худов

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#8524]
#### Подробное описание проблемы
Добавьте на базу синдиката,ОБРа и на скипджек воксов улучшения для худов.Сейчас улучшения никак нельзя получить кроме как создать в РнД,что для всяких воксов,нюкеров и ОБРовцев очень сложно провернуть.

**Comment by Sakuya-Izayoi** [comment]
Буквально оказуаливание.
