### ISSUE TITLE
Бореры поломались :(

### ISSUE THREAD

**Issue by Shootnik01** [TauCetiStation/TauCetiClassic#8526]
#### Подробное описание проблемы
При заходе за борера, в течении 10-20 секунд, игрока выкидывает из игры. При возвращении, он оказывается в меню респауна (если не успел найти хоста) и в человеке, но с повторным вылетом за те же пару десятков секунд

#### Что должно было произойти
Никаких вылетов и выходов в меню респауна
#### Что произошло на самом деле
Вылеты
#### Как повторить
Зайти за борера
#### Дополнительная информация:
Почините, а? Бореры - классный режим, грустно, что убрали из ротации, но хотя бы иногда (по воле ~~щитспавнеров~~ наших любимых педалек) поиграть хотелось бы

**Comment by KIBORG04** [comment]
Зашел. Не вылетело.

**Comment by Shootnik01** [comment]
![image](https://user-images.githubusercontent.com/75479005/150638615-e75122d1-48e6-4b85-acd2-f8dddf53aada.png)
