### ISSUE TITLE
После возвращения СПУ к жизни он становится живым, но как бы не живым.

### ISSUE THREAD

**Issue by DespairSoul** [TauCetiStation/TauCetiClassic#8542]
#### Подробное описание проблемы
СПУ откинулся, его восстановили и вставили позитронку обратно. Его температура осталась 250 градусов (появилась неуязвимость к огню и космосу), если упасть - больше не встать.
#### Что должно было произойти
СПУ стал обычным, а не какой-то медленно ходящей аномалией, которая если споткнется больше не встанет.
#### Что произошло на самом деле
СПУ стал медленной-дионой-аномалией, который устойчив к любым температурам, однако его ноги по сути не работают.
#### Как повторить
Возможно, т.к. не тестил - умереть и восстановиться обычным путем, через починку корпуса и вытаскивание-вталкивание позитронки обратно.

**Comment by DespairSoul** [comment]
Потестил, это происходит от смерти в космосе. Или температуры. Даже лазеры не убивают, дичь какая-то жесткая прям. Оно живое!
![image](https://user-images.githubusercontent.com/62647323/151267785-ed39650a-1a1a-4e35-83f9-14b8b85f3517.png)

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/spu-hotyat-nerfanut-v-govno-a-ya-ne-hochu/38469/48
