### ISSUE TITLE
Баг с ползунком в окне служителя культа

### ISSUE THREAD

**Issue by BakerMontague** [TauCetiStation/TauCetiClassic#8549]
#### Подробное описание проблемы

Космо-культисты теперь не могут скролить меню стола жертвоприношений. Ни колесиком, ни ползунком справа, да последнего даже и нет на месте. 
У святого отца так же дела сейчас плохи.

#### Что должно было произойти

Окно стола религий должно было пролистываться вниз при соответствующих действиях игрока.

#### Что произошло на самом деле

Ползунок пропал у всех. С ним и геймплей у большинства. Но таки придумалс выделятс текст и тянуть вниз, такой вот костыльс.

#### Как повторить

За культи пройти путь до стола Рая. Иль за свято отца. Открыть.

#### Дополнительная информация:

 Проблема замечена всеми служителями культа сразу, так что дело не в игроках и их PC. 
 Fix TGUI применяли, перезаход применяли.
 Скачал и тестировал на локалке билд вот с этим последним изменением: https://github.com/TauCetiStation/TauCetiClassic/commit/8d56015fd107089a0af58f72b837ab3dc41441fa
Там всё работало-да-крутилось без проблем.
 На всякое подозрение: Byond version 514.1578; Windows 10

**Comment by KIBORG04** [comment]
Лол что. Наверное, связано с #8343

**Comment by BakerMontague** [comment]
> Лол что. Наверное, связано с #8343

Доброго времени суток, Киборг! Тоже пришла мысль в сторону ТГ чата. 
Проблема выпалилась буквально в районе 5 часов назад по опросам ведущих сатанистов Тау Сети. Но это может быть не точно.
