### ISSUE TITLE
Меню camera_bug не обновляется самостоятельно в некоторых случаях

### ISSUE THREAD

**Issue by skvazarb** [TauCetiStation/TauCetiClassic#855]
#### Подробное описание проблемы
Если выбрать цель для отслеживания и нажать [cancel camera view], меню перестает обновляться самостоятельно при перемещении цели в другую зону.
#### Что должно было произойти
Меню должно обновляться самостоятельно при перемещении цели (наверное).
#### Что произошло на самом деле
Меню обновляется только принудительно.
#### Как повторить
1. Выбрать цель для отслеживания.
2. Нажать [cancel camera view]
3. Переместить цель в другую зону
#### Дополнительная информация:
Это скорее мелкое неудобство, но полагаю, такая работа не предполагалась.

**Comment by RichardJones1** [comment]
Предполагаю, что да
