### ISSUE TITLE
Вы зачем запретили столы на тайле с машинерией строить?!?!

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#8552]
#### Подробное описание проблемы
Микроволновка и её друзья запихиваются на стол когда ты стоишь на одном тайле с ними и ставишь стол под себя. Я СУПЕР СИЛЬНО подозреваю тот фикс возможности ставить стол в стене связанным с тем, что теперь низзя никак её засунуть, мы позвали весь инженерный консилиум и никто из инженеров не может поставить микроволновку на стол.
#### Что должно было произойти
То же как и раньше - ставишь микроволновку или иную машинерию на свой тайл, и строишь под собой стол - всё, эстетично красиво.
#### Что произошло на самом деле
Инженеры собрались всем отделом чтобы поставить микроволновку на стол в то время как станцию кушоют разгермы фороны и т.д.
#### Как повторить
Написано выше
#### Дополнительная информация:
Issue reported from  Round ID: 48517 (Tau Ceti Classic (RU))
Testmerges: ```#8511 #8404 #8359 #8343 ```
Reporting client version: 514.1565

**Comment by UDaV73rus** [comment]
Кажется про этот фикс говорили что убьет подобные моменты, но это никого не остановило

**Comment by KIBORG04** [comment]
Не фича, а баг. Багоюзерство плохо. Фикс вас спас от бана

**Comment by kalazus** [comment]
> Не фича, а баг. Багоюзерство плохо. Фикс вас спас от бана

Всегда считал что мапдеп нужно забанить, а теперь есть легитимная причина "багоюз"!

**Comment by AirBlack** [comment]
железные столы можно переворачивать на бок, туда ставить машинерию, потом поворачивать обратно. на стеклянный стол микроволновку никак не поставить к сожалению

**Comment by Mercurialaste** [comment]
Пофикшено, вроде.
