### ISSUE TITLE
Лазер сб борга не заряжается

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#8558]
#### Подробное описание проблемы
Лазер взломанного сб модулья борга не заряжается при нахождении в зарядке для боргов
#### Что должно было произойти
Встал в зарядку и зарядил лазер
#### Что произошло на самом деле
Встал в зарядку и не зарядил лазер
#### Как повторить
Встать в зарядку для боргов с разряженным лазером
#### Дополнительная информация:
Issue reported from  Round ID: 48602 (Tau Ceti Classic (RU))
Testmerges: ```#8540 #8404 #8359 #8343 ```
Reporting client version: 514.1569

**Comment by Rahmanio** [comment]
Так лазер же вроде стреляет до того, как у борга полностью кончится энергия или то что он стреляет пока есть энергия является багом?

**Comment by Mercurialaste** [comment]
Бага нету. Просто нету перезарядки есть зарядка на батареи = стреляй. Нету, умирай.

(Пишу повторно, как утверждение комментарию выше.)
