### ISSUE TITLE
Не-магусы могут телепортироваться с помощью свитка телепортации

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#860]
#### Подробное описание проблемы
Обычные члены экипажа (и не только), не обладающие магическими способностями могут использовать свиток телепортации мага.
#### Что должно было произойти
Они не могут использовать свиток.
#### Что произошло на самом деле
Они могут.
#### Как повторить
Взять свиток, заюзать его не будучи магусом.

**Comment by Skippeer12** [comment]
Не баг, а фича

**Comment by Belfogor** [comment]
Не баг же, а фича

**Comment by Damirrus1** [comment]
Это не баг, фича же.

**Comment by Skyrull** [comment]
Понял, не баг, а фича

**Comment by WallShrabnic** [comment]
Это не фича, а баг

**Comment by dearprincesscelestia** [comment]
Эта фича - баг, а не.

**Comment by WallShrabnic** [comment]
Обоснуйте, как человек, не зная для чего нужна эта бумажка, будет её использовать?

**Comment by Lancer411** [comment]
Ты прикасаешься к бумажке, магия которой создает в твоем сознании карту станции, выбор зон и понимание, что сейчас тебя телепортнет. После совершения выбора в своем сознании, космонавт непроизвольно произносит адрес отсека, чем завершает ритуал телепортации.

**Comment by Belfogor** [comment]
Впермите Шрабнику гит.

**Comment by Moggilazz** [comment]
Это бага нужна затем, чтобы можно было давать пинка под зад всем, кто без рольки её использует, не удоляйте плез, у нас план по банам не закрыт.
