### ISSUE TITLE
Люди с имплантами получают роли триторов, реверов, культистов.

### ISSUE THREAD

**Issue by Nerevrin** [TauCetiStation/TauCetiClassic#862]
#### Подробное описание проблемы
Люди с имплантами могут быть триторами, реверами, etc
#### Что должно было произойти
Агент\капитан\ХеС не должен становиться тритором, ревером, etc.
#### Что произошло на самом деле
Агент\капитан\ХеС получают роли триторов, реверов, etc
#### Как повторить
Дождаться прока роли на агенте\капитане\ХеСе

**Comment by Raschert0** [comment]
Ну, с триторкой ещё ладно. Не любая триторка направлена против НТ (хотя как посмотреть, да)

**Comment by Flankir** [comment]
Ну тематически они либо становятся триторами еще до имплантации, либо их импланты неисправны/взломаны/фальшивые.
Другое дело что у генки импланта вообще не должно быть (и это должно быть палевом на сканерах сб)

**Comment by WallShrabnic** [comment]
Не баг, а фича

**Comment by Nerevrin** [comment]
Кокая фича? Второй АВД глав-ревер за неделю.

**Comment by Skyrull** [comment]
![image](https://cloud.githubusercontent.com/assets/20542000/20978426/12d226ae-bcd3-11e6-84ce-e11b15c149bc.png)

**Comment by WallShrabnic** [comment]
Открою чекрет - конвертить людей с имплантом в культ вроде нельзя. В любом случае, там суть основана на ДУШЕ и КРОВИ и к физическому телу отношения не имеет. 
Триторка - перепрограммирвоание импланта, ЕМНИП. 
А ревер - это да

**Comment by Nerevrin** [comment]
Ревер - тоже тритор. Заебалей искать причины. Выпилите это к чертям и всё тут.

**Comment by WallShrabnic** [comment]
Реверы не триторы

**Comment by Nerevrin** [comment]
Ну и в чём смысл твоего коммента? Я про это и говорю вообще.

**Comment by Balphagore** [comment]
Если имплантировать обычного тритора, то ему механом промоет мозги как обычному реве? Или просто будет конфликт интересов триторки и импланта? А вообще смотрите - что мы имеем. Главревы не имплантируются в принципе. Механом выводится сообщение о неудаче и имплант не появляется в худе (не знаю, как с медицинской точки зрения, может он остается в теле, но просто не работает). Механом вырубается имплант, если носитель получает рольку от педали. На худах выглядит опять же как исчезновение импланта. Как-то раз ХОС имплантировал тритора-шахтера, который заказал пушечек, но еще ничего не успел сделать и тот отправился работать как ни в чем не бывало. И при этом никто не спорил и не возникал, так что, видимо, ситуация корректная и имплант убивает триторку с точки зрения РП (про механ я спросил в начале, я не знаю, как по нему, меня не имплантировали тритором)

Так что АВД-главрева - это стопроцентный баг. Главрев не может быть имплантирован по механу игры. Если имплант отображается на худе, значит он активировался и перебил реву. Скорее всего так же с триторами. Если тритор при имплантировании "брейнвошится" механом, как обычные ревы, то вообще без вариантов. Если нет, то по РП выпонять можно только роли, которые не наносят вред НТ. В любом случае, если имплант отображается на худе, то он работает и глушит все начинания против НТ, ибо при получении рольки уже во время раунда - имплант вырубается. Так что капитаны/ХОСы/АВД-триторы - это конфликт, на который все забивают, думая что раз я тритор, то имплант мне не помеха. Но если смотреть по механу, то очень даже помеха.

С культом и имплантом вообще непонятно и я не встречал четкой единой позиции. В культ нельзя конвертнуть только того, у кого джобка на культ, капитана и священника (причем настоящего, если он был священником изначально, ассистент, повышенный до священника, конвертится). Исходя из этого выходит, что имплант культу не помеха. АВД и ХОС спокойно конвертятся, а священник не конвертится и без импланта. Но, так как четкого правила по этому поводу нет, то на имплант все забивают, а ведь по механу он продолжает работать и выдает фразочки о том, какое НТ классное, во время того, как ты отпиливаешь голову капитану.

И еще мне не нравится ситуация с ХОПом. Так как он больше не является замом капитана и возглавляет только гражданский персонал, но при этом имеет почти полный доступ (полный если выставит его себе сам) и летальное оружие, и без импланта. То что ХОП-тритор, как и капитан-тритор не контрится - это уже мем нашего сервера и если капитан-тритор - это почти точно баг, то ХОП-тритор это просто парадокс. Его понизили, но оставили пушечки и возможность заиметь полный доступ, но не снабдили имплантом. Если его понизили до командования поварами, то почему он может выдать полный доступ и имеет летальное оружие без импланта? Надо забрать у него возможность выдавать доступ других глав и капитана и отобрать у него еган. Если же все нормально и фулаксес с леталом ему необходимы, то ему надо запихать в бошку имплант. Но это отдельный разговор, думаю стоит вынести его в отдельный запрос.

**Comment by Nerevrin** [comment]
Обычные триторы тоже сопротивляются импланту.

**Comment by Balphagore** [comment]
Это точно? Ибо в той ситуации с шахтером-тритором у него были пушки и незакрытый аплинк на КПК, так что он стопудово тритор. но имплантирование прошло нормально. Правда это было довольно давно... Если сейчас тритора тоже нельзя имплантировать, то вообще без вариантов, капитаны, ХОСы и АВД не должны быть триторами, это бред

**Comment by Nerevrin** [comment]
Только что имплантировал себя. Имплант на худе не появился.

**Comment by Balphagore** [comment]
У тритора? Ну тогда все четко - либо триторка, либо имплант. А главрев даже имплантировать не получается, механ выдает команду, что работник сопротивляется, или что-то такое.

**Comment by StrikS** [comment]
>Если сейчас тритора тоже нельзя имплантировать, то вообще без вариантов, капитаны, ХОСы и АВД не должны быть триторами, это бред

Триторы имплантируются спокойно, смотрите код. Не имплантируются главы революции!

Триторами могут быть все, это нормально, просто имплант взломан.

**Comment by Balphagore** [comment]
Если триторами могут быть все, то тогда надо делать что-то с их заданиями, ибо здание капитана украсть свои штаны и свой пинпойнтер - это бред. Фактически на станции становится на одного тритора меньше, экшена тоже меньше. Надо либо делать нормальные задания триторам-капитанам, либо выпилить у них возможность быть триторами, либо сделать вероятность этого такой астрономически маленькой, что это было бы реально редко, ибо даже на вики написано, что взлом импланта очень дорогая процедура и делается это очень редко (в статье про АВД). А еще на вики написано, что сложность рольки зависит от должности. Капитан и ХОП - очень простые для триторства должности, а значит им надо давать самые сложные задания. А какие самые сложные задания на станции кроме убийства кого-нибудь? Украсть вещи капитана/ХОПа. Это же гениально! Может в этом проблема? Выпилить у триторов-ХОПа и капитана задания на похищение чего-либо, пусть изворачиваются с убийствами. Тогда будет более или менее нормально. Стелсящие рольки - потеря для раунда, а когда тебе дают задание украсть свои же вещи или вещи к которым у тебя есть доступ, то потеря потерь.

**Comment by StrikS** [comment]
На, уже давно есть документ с новыми цепями в Рнд висит. Заполняй. Как более менее будет, то создавай ишью будем добавлять.

**Comment by WallShrabnic** [comment]
Меня как-то успешно имплантировали за тритора, я обратился в АХ и сказали, мол, отыгрывай потерю памяти
