### ISSUE TITLE
Баги с качалкой

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#8631]
#### Подробное описание проблемы
Можно спамить кликами по Weight Machine и ты будешь каждый раз снова качаться.

#### Что должно было произойти

https://user-images.githubusercontent.com/26389417/154629229-508657ef-f822-4913-846c-0cbd3e11329c.mp4

#### Что произошло на самом деле
видео выше не должно было произойти

#### Как повторить
Кликать по кач-машине много много раз

**Comment by DarthSidiousPalpatine** [comment]
Когда на первом появится качалка?

**Comment by KIBORG04** [comment]
Когда крит. баг пофиксишь.
