### ISSUE TITLE
Attach can't be detach

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#8640]
#### Подробное описание проблемы
Вещи по типу разгрузок, галстуков, медалей и прочих цеплялок на форму, теперь нельзя снять.
#### Что должно было произойти
Их можно было бы снять.
#### Что произошло на самом деле
Это нельзя сделать.
#### Как повторить
В игре.
#### Дополнительная информация:
Проблема в том, что игра даже не предлагает игроку выполнить это действие.

**Comment by Tap0r** [comment]
Альт кликом они теперь снимаются

**Comment by LudwigVonChesterfield** [comment]
#8582
