### ISSUE TITLE
Лепучая дефибы

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#8641]
#### Подробное описание проблемы
Надеть на спину дефибы можно, а вот снять нельзя.
#### Что должно было произойти
Их можно снять самостоятельно.
#### Что произошло на самом деле
Не дает снять, спамит таким сообщением 
![image](https://user-images.githubusercontent.com/19796920/154786955-3ec90ae4-e351-490c-beb3-c82cd760f44b.png)

#### Как повторить
В игре.
#### Дополнительная информация:
Bruh вообще билд поломали.

**Comment by LudwigVonChesterfield** [comment]
[d6d4473](https://github.com/TauCetiStation/TauCetiClassic/pull/8579/commits/d6d447393d72c0fe9c4c875cfbf14c048e4558f4)
