### ISSUE TITLE
Плавность и скорость кукол

### ISSUE THREAD

**Issue by Helg2** [TauCetiStation/TauCetiClassic#8648]
#### Подробное описание проблемы
Недавно была введена плавность анимации которая добавила плавные переходы и анимацию когда ты тащишь тяжёлые предметы. Так вот плавность полная фигня и так как анимация плавности занимает дофигища времени теперь все бегают как дионы, а ходят как черепахи. Я уже молчу о замедлении при голо-уроне и урона собственно на кукле. При попадании тазера ты становишься настолько медленным что попасть в тебя еще 20 раз не составляет проблемы даже самым упоротым. Про електроды у тазера видимо тоже все забыли. Пусть золото боргам и убрали в сейф но теперь борги с модулем ВТек будут бить нещадно. Если с таковой скоростью у врага есть лазерная винтовка то тебе неминуемо пиздец. Теперь чтобы не быть убитым под рукой нужно всегда хотя бы иметь бутылку и сварку а иначе тебя запинают этой же сваркой и ты не сможешь убежать.
#### Что должно было произойти
Анимация есть, скорость та же но красиво
#### Что произошло на самом деле
Анимация занимает дофига времени и скорости даже нету даже у таяр.
#### Как повторить
Походить
#### Дополнительная информация:
Issue reported from  Round ID: 49061 (Tau Ceti Classic II (RU))
Testmerges: ```#8601 #8404 #8359 #8555 ```
Reporting client version: 514.1578

**Comment by Shootnik01** [comment]
Это правда, кста

**Comment by KIBORG04** [comment]
пофикшено
