### ISSUE TITLE
Мертвые люди остаются сотрудниками космической станции после смерти.

### ISSUE THREAD

**Issue by SourcePony** [TauCetiStation/TauCetiClassic#865]
#### Подробное описание проблемы

Заходящие за обзерв (гостота) имеют право голосовать за инициацию вызова шатлла. 
Количество голосов за каждый пункт видно всем.

#### Что должно было произойти

Заходящие за обзерв (гостота) не имеют право голосовать за инициацию вызова шатлла. 
Количество голосов не должно быть видно никому до конца голосования (Демократия, говорите? Так проводите ЧЕСТНЫЕ выборы.)

#### Что произошло на самом деле

Заходящие за обзерв (гостота) имеют право голосовать за инициацию вызова шатлла. 
Количество голосов за каждый пункт видно всем.

#### Как повторить

Зайти за обзервера (госта), инициировать голосование за вызов шатола/дождаться пока этого сделает кто-то другой, проголосовать за один из пунктов.

#### Дополнительная информация:

Кнопка воута придумана для людей, которым скучно играть в раунде. Гостота должна страдать и не иметь прав, так как не является живыми существами, способными к эмоциям. Если людям плохенько сидеть в гостах - ждите респауна, заходите за пИИ/Боргов, не умирайте. 

Отображение голосов возбуждает в человеке стадный инстинкт и не дает ему думать своей черепной коробкой.

**Comment by igigin** [comment]
Каким образом это название должно быть связано с тем, что внутри? Зве бы такой ишью просто закрыл бы не спрашивая.

**Comment by YulianR** [comment]
То есть если три аутиста играют, а сорок человек не хотят заходить в десятичасовой раунд, они должны ждать пока аутисты наиграются? Блять вы вообще нормальные? Вам увеличили время до 2 часов, это блять на час больше, нет вам мало, нужно больше аутизма

**Comment by WallShrabnic** [comment]
^this 
Нюка будет молча выпиливать персонал и аутировать десять часов, da

**Comment by Raschert0** [comment]
Ну вообще, если включить запрет гостам голосовать (да, это настраивается на конфиги), то они смогут голосовать при количестве трупов большем, чем 50% от общего количества (персонала или игроков, не помню уже)

**Comment by Balphagore** [comment]
Таки давно прошу отрубить возможность гостам голосовать, даже как-то такое делали, но почему-то не прижилось. А вот невозможность увидеть количество голосов - это интересная идея, ибо народ реально у нас очень инертный и если он не определился, то голосует за тот вариант, который набрал больше голосов. А надо чтобы игрок голосовал исходя из своих предпочтений, а не стадного инстинкта. Идеальная система для меня - это голоса гостов идут за половину голоса живого человека (тогда большое количество трупов сможет переголосовать трех живых аутистов, но если раунд идет нормально, то соснувшие не смогут перезапустить раунд просто потому что их должно быть в два раза больше), голоса тех кто жив, но не проголосовал идут автоматом за продолжение раунда (ну бывает такое, что экшон такой, что пропускаешь голосование, госты то в экшоне не участвуют и всегда есть время голоснуть за конец раунда), голоса тех кто жив, но ливнул (не гостанулся) - идут автоматом за конец раунда и результаты голосования видны только по его завершении.

**Comment by StrikS** [comment]
Я согласен про то, что нужно выпилить возможность видеть результаты, до того как ты проголосовал. А лучше вообще показывать только только в конце . Чтобы не орали: "Еще голос за шатол!"

**Comment by WallShrabnic** [comment]
Вот только это приведёт к массовому наплытию на велосити лысых ассистентов, кторые зашли в раунд чтобы проголосовать

**Comment by Dennok** [comment]
>голоса тех кто жив, но ливнул (не гостанулся) - идут автоматом за конец раунда
Вот с этим не согласен, ту кто ливнули не должны учитываться в голосовании.
А так норм.

П.С. И сделай уже нормальное название под тему.
