### ISSUE TITLE
Хочеца мафию

### ISSUE THREAD

**Issue by Lianes1** [TauCetiStation/TauCetiClassic#8651]
#### Подробное описание проблемы
Мафия не работает.
#### Что должно было произойти
Мафия работает
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/86564420/154814484-f421dfac-4937-4513-b757-faa8366d9daa.png)

#### Как повторить
Зайти в госты и попробовать поиграть в мафию

**Comment by 05126619z** [comment]
Такое выскакивает не всегда
Я например ловлю такое с просмотром камер

**Comment by Lianes1** [comment]
всегда, пока я в гостах у меня эта штука
