### ISSUE TITLE
В армори нет охранных противогазов

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#866]
#### Подробное описание проблемы
http://prntscr.com/dgzi4y
В арсенале нет охранных противогазов.

#### Что должно было произойти
Противогазы должны лежать на стенде (может и нет).
#### Что произошло на самом деле
Их нет.
#### Как повторить
Зайти в первый отсек арсенала, с болью смотреть на пустую полку.

**Comment by WallShrabnic** [comment]
Ето всё Моггилаз со своими наборами испортил, делайте откат

**Comment by Moggilazz** [comment]
ОЙ

Чёртов гитхаб, как сюда влез, так тоже обсираться начал. Уже завёл Вольво.

**Comment by SpaiR** [comment]
#876
