### ISSUE TITLE
[Proposal] Перевести банды в рандомные ивенты

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#8667]
Банды очень скучны, как полноценный режим. Спавн конкурирующих бандитов среди экипажа в другом режиме, где есть нормальные антаги, привнесёт тот же игровой опыт и ролейплейную составляющую, при этом не создавая эксту для всех остальных.

**Comment by Bullethole** [comment]
Хуйню сморозил

**Comment by Deahaka** [comment]
Пусть будут банды. Надо только добавить больше нормальных
![0000000000000000000000000000000000](https://user-images.githubusercontent.com/96499407/216958448-2fb7e658-190d-4de3-aa3d-c09f84f4d496.png)
