### ISSUE TITLE
Отвалилась возможность выбора цвета и формы таблеток в ЧЕММАСТЕРЕ

### ISSUE THREAD

**Issue by Belfogor** [TauCetiStation/TauCetiClassic#868]
#### Подробное описание проблемы
В чеммастере больше нельзя выбирать цвет и форму таблеточек со спейсдрагом. Теперь предоставлен лишь рандомный вариант. 

#### Что произошло на самом деле
Таблетки стали леденцами. 

#### Как повторить
Пострадайте за ЧЕММАСТЕРОМ

#### Дополнительная информация:
Предлагаю выкрутить мастеру-ломастеру пальцы.  Готов предоставить инструменты по розничной цене.

**Comment by StrikS** [comment]
Самое забавное, что это уже не меньше полгода такая ситуация, так как я не знаю другого чеммастера, кроме как с рандомными таблетками.

**Comment by WallShrabnic** [comment]
Её и не было же вроде. А так - было .ы круто исправить

**Comment by Dennok** [comment]
Была.
