### ISSUE TITLE
После респавна особка остаётся та же

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#8680]
#### Подробное описание проблемы

взять особку
заспавниться
зареспавниться
а особка то та же

#### Что должно было произойти

возможность получить другую особку

#### Что произошло на самом деле

особка та же

**Comment by KIBORG04** [comment]
фича

**Comment by AndroBetel** [comment]
Не фича, вот бы поменять. =(

**Comment by LudwigVonChesterfield** [comment]
#8821
