### ISSUE TITLE
Языковые особки убирают немоту

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#8709]
#### Подробное описание проблемы
Взял немого персонажа, выпала особка на знание всех языков, в ходе раунда понял что немоты нет и немота есть одновременно. То есть, при попытке говорить на каком-либо языке выходит сообщение "U are mute." как и надо, а при попытке говорить на стандартном языке всё норм
![image](https://user-images.githubusercontent.com/82588639/155877044-e6085696-5004-4a72-9423-7b441beb0dde.png)

#### Что должно было произойти
Персонаж знает все языки, но все еще немой
#### Что произошло на самом деле
Персонаж знает все языки, не может на них говорить, но может говорить на стандартном
#### Как повторить
Получить особку на знание всех языков и зайти за немого
#### Дополнительная информация:
Мне кажется это из-за #8687

**Comment by LoTaRk-FroG** [comment]
закрываю в пользу #8710

**Comment by HeAPTEM** [comment]
у меня не было особки на языки
