### ISSUE TITLE
Глава персонала должен либо обзавестись имплантом, либо распрощаться с летальным оружием и полным доступом

### ISSUE THREAD

**Issue by Balphagore** [TauCetiStation/TauCetiClassic#871]
#### Подробное описание проблемы
Глава персонала теперь не является ВРИО капитана и командует исключительно гражданским персоналом, однако он имеет расширенный доступ и может повысить его до полного, а так же имеет летальное оружие и подключение к каналу охраны. Такой набор был необходим, когда он замещал капитана в его отсутствие и даже тогда, по логике, требовал наличие импланта. Сейчас же он имеет практически неограниченные возможности, оружие и может быть тритором (капитан-тритор, это баг). Это слишком большое преимущество для того, кто командует карго, поваром, барменом и клоуном. ХОС, в критической ситуации, становится по иерархии над ХОПом, но не получает полного доступа даже при наличии импланта лояльности. У ХОПа же практически полный доступ есть по умолчанию и никто не мешает ему получить его полностью и выдать кому попало, но он не имплантирован. Глав имеет право назначать только капитан, но ХОП, который на одной ступени с другими главами, а в критической ситуации ниже ХОСа, может выдать доступ любого другого главы.

Нынешний ХОП - это очень вожделенная профессия именно из-за такого набора преимуществ, что можно заметить по тому, что он единственный глава, который почти всегда есть на станции.  У него меньше обязанностей, чем у капитана, но почти неограниченные возможности. То, что "ХОП-тритор не контрится" - это уже мем нашего сервера. Капитан-тритор тоже, но в его случае - это баг. В случае с ХОПом же - это незавершенное понижение до обычного главы. Раньше он был заместителем капитана и народ считал его противовесом ему (не имплантированный гражданский заместитель, против имплантированного представителя ЦК), по этому о импланте особой речи не возникало. Теперь же он просто такой же глава как все, у которого забыли забрать вкусные плюшки.

#### Что должно было произойти

ХОП должен лишиться летального оружия, доступа к каналу охраны, возможности выдать доступ других глав и капитана, и открывать ящики с оружием из карго, либо получить имплант лояльности, с которым он больше не сможет быть тритором, когда соответствующий баг пофиксят (https://github.com/TauCetiStation/TauCetiClassic/issues/862) и лишится абсолютной свободы. Так же изъятие лишних плюшек ослабит очень сильного генокрада-ХОПа (наличие импланта, на самом деле, тоже должно, но генокрад с имплантом - это спорный вопрос)

#### Что произошло на самом деле

ХОП может творить на станции что хочет, выдавая любой доступ себе и кому попало, а если он тритор, то остановить его крайне проблематично даже ХОСу с армией офицеров. Более того, он имеет летальное оружие, возможность заказать и открыть летальное оружие в карго и прослушивает канал охраны без дополнительных средств, так что той крайне трудно скоординироваться против него.

#### Как повторить

Зайти за ХОПа и наслаждаться жизнью. Словить ХОПом тритора и наслаждаться беспомощностью охраны. Словить ХОПом генокрада и сожрать всю станцию (Хотя ХОПов-генокрадов я последнее время не видел, но в свое время им мог противодействовать только ИИ, если тот не додумался его перепрограммировать)

**Comment by Raschert0** [comment]
>Капитан-тритор это баг

Но никто это фиксить не будет (так как фича)

**Comment by Balphagore** [comment]
Тогда надо отбирать плюшки, ибо оооочень жирно для командования барменом и клоуном, а карго по большей части, командует КМ. Хотя иногда такой жирный тритор может устроить интересную ситуацию, но по большей части ХОПы триторы, пользуясь положением, выполняют рольку так скрытно, что это даже не интересно.

**Comment by StrikS** [comment]
>Раньше он был заместителем капитана и народ считал его противовесом ему (не имплантированный гражданский заместитель, против имплантированного представителя ЦК)

Врио - временно исполняющий обязанности. Хоп получал полную власть в ОТСУТСВИИ КЕПА.
Хоп уже потерял ВРИО. Сейчас у него есть фулаксесс и пушка, чтобы его защищать.
Глава персонала без возможности выдать доступ? Ты как это себе представляешь?

**Comment by Balphagore** [comment]
ХОП был противовесом капитану, потому что мог принимать серьезные решения, если капитан начинал чудить, сейчас, когда ХОП просто ХОП, ему не стоит принимать серьезные решения даже если капитан в край офигел. Он перестал быть противовесом. Беганье без импланта ХОПу прощали, потому что имплант притупляет критическое мышление и нужен был кто-то без импланта, на случай если у капитана что-то перемкнет и он не сможет нормально оценить ситуацию. Теперь ХОП командует барменами и клоунами и беганье без импланта с пушками и фулаксесом ему уже не простят.

 Пушка нужна, чтобы защищать не ХОПа, а его фулаксес. Если отобрать у него фулаксес, то и пушка будет не так нужна. 

Глава персонала теперь равен с остальными главами, а раньше он был даже в обычной ситуации выше их. Но если он равен другим главам, а глав может назначать только ЦК и капитан, то на кой ляд ему возможность выдавать доступ других глав и самого капитана? Пусть выдает доступ всех подчиненных, кроме самого главы, а глав уж назначает кто положено. 

И у меня не пригорело, претензии к нынешнему ХОПству я высказывал уже давно, просто сейчас, когда начали обсуждать триторов с имплантами эта тема у меня в голове оформилась окончательно. И вообще, пригореть от совершенно стелсового тритора, которому надо украсть свои же штаны - это надо постараться. Я давно не видел боевых-хопов триторов, но часто вижу боевых ХОПов, которые влезают в дела других отделов, хотя сейчас не имеют на это права, а имеют только возможность, которую с завидным постоянством абузят.

**Comment by StrikS** [comment]
Псс,  то что у него не будет доступа к комнатушкам глав,  не сильно повлияет на фулаксес. Пушка по прежнему будет нужна. А вот геморроя это прибавит.
Что касается пушки, раз ты не видишь триторов с пушками, то в чем проблема? Если хоп рембует это проблема отвгрыша, а не механа. 
Как я уже упоминал, это нормально, что территором может стать любой,  но если навесить ему имплант в раунде, то он станет лоялен.

**Comment by Balphagore** [comment]
Порезанный фулаксес будет вызывать гораздо меньше интереса, когда можно получить полноценный в каюте капитана. А если отобрать у ХОПа еще и возможность выставлять доступ вардена, то вообще станет не интересно. Фулаксес чаще всего нужен для доступа в одну из комнатушек глав, или ради летала. Если у ХОПа не будет ни доступа, ни летала, ни доступа к леталу (если отобрать еще и вардена) то он станет тем, кем он сейчас по факту должен быть. Бюрократом и главой гражданского персонала. И интерес к нему практически пропадет. Его будут брать, чтобы командовать и менять профессии и отправлять отчеты, а не чтобы бегать по станции аки бэтман с фулаксесом и еганом. Для этого есть охрана, и ХОП к ней больше вообще никак не относится, кроме плюшек, которые у него не забрали. Но тут возникает целая дилемма с варденом, его иногда таки надо назначить через ХОПа, хоть он и не глава. Но в критической ситуации он замещает ХОСа, а в критической ситуации ХОС становится главнее ХОПа. Получается, что варден в критической ситуации как минимум равен нынешнему ХОПу и неплохо бы его доступ тоже забрать, особенно если учесть, что с ним можно залезть в арсенал и пооткрывать ящики с оружием. 

Если триторами могут быть все, даже с имплантом (кроме ХОСа, насколько я знаю - он просто не может быть тритором), то тогда имплантирование ХОПа не поможет и надо отбирать лишнее. Сейчас ХОП - глава гражданского персонала и бюрократ и его возможности должны быть соответствующими, а они значительно выше, чем нужно и из-за этого ему нужна броня и оружие. Меня тут в первую очередь беспокоит сама концепция ХОПа, а то, что он может быть тритором с такими возможностями - это неприятное дополнение к ней.

**Comment by sovok4** [comment]
Отнимаем короче у хопа табельное, а АВД добавляем шкаф с двумя комбатшотганами и боеприпасами всех сортов и расцветок. Имплант есть, все требования выполнены.

**Comment by Balphagore** [comment]
ХОПу оружие нужно для защиты своего фулаксеса, а АВД - неуловимый Джо, нафига ему оружие? Факс защищать? Я думал, что триторка с имплантом при респауне - баг, а оказалось это фича, так что наличие импланта уже не особо важно, и ХОПа надо раскулачивать, а не имплантировать.

**Comment by WallShrabnic** [comment]
Тема уже поднималась на форуме, непонятно, зачем она тут нужна, если норот решил ничего не менять http://tauceti.ru/forums/index.php?topic=4629.0

**Comment by StrikS** [comment]
Оу , действительно, идем по второму кругу, а между тем уже все расписали на форуме.

**Comment by DeadOberst** [comment]
ХоП без импланта это из той же категории, что и клоун на научной станции.
Влепите хопу имлант и на станции не будет происходить столько интересных ситуаций в его взаимодейстии с охраной и хосом.
