### ISSUE TITLE
Депрессия от плохого муда и немота

### ISSUE THREAD

**Issue by Helg2** [TauCetiStation/TauCetiClassic#8716]
#### Подробное описание проблемы
Итак, относительно недавно была введена желтизна экрана при плохом настроении и если муд скатывался в пропасть то всё становилось монотонным. Но есть одна проблема ввиде Am I the loneliest being in the universe?... I need to be heard!, которая возникает когда долго  ни с кем не говоришь. Но эта проблема также есть у немых, мима и абдукторов

#### Что должно было произойти
У них по идее не должно быть ухудшения муда так как абдукторы общаются при помощи телепатии, мим молчит из-за обета молчания, а немые могли попросту свыкнуться с этим. И никакого жёлтого экрана
#### Что произошло на самом деле
Жёлтый экран присутсвует
#### Как повторить
Зайти за мима, немого или абдуктора и подождать
#### Дополнительная информация:
Issue reported from  Round ID: 49295 (Tau Ceti Classic II (RU))
Testmerges: ```#8674 #8614 #8605 #8571 ```
Reporting client version: 514.1578

**Comment by DarthSidiousPalpatine** [comment]
Утоли свои печали в алкоголе.

**Comment by LudwigVonChesterfield** [comment]
У немых есть общение руками, а абдукторов надо пофиксить, да. Про мима отвечать отказываюсь, грустный мим это смешно.
