### ISSUE TITLE
Решётка не делается

### ISSUE THREAD

**Issue by Helg2** [TauCetiStation/TauCetiClassic#8728]
#### Подробное описание проблемы
При попытке сделать решётку решётка телепортируется на другой слой вместо нужного тебе места.
#### Что должно было произойти
Решётка стоит, все довольны
#### Что произошло на самом деле
Решётка стоит на другом слое, прутиков нету
#### Как повторить
Попытаться сделать решётку
#### Дополнительная информация:
Issue reported from  Round ID: 49324 (Tau Ceti Classic (RU))
Testmerges: ```#8674 #8614 #8605 #8579 #8571 ```
Reporting client version: 514.1578

**Comment by LudwigVonChesterfield** [comment]
#1a24d68
