### ISSUE TITLE
Если класть в переполненный жилет/лабхалат/веббинг вещи, будет писать что нельзя прицепить аксессуар

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#8730]
#### Подробное описание проблемы

название

#### Что должно было произойти

никаких сообщений в чат

#### Что произошло на самом деле

You cannot attach more accessories of this type to the hazard vest.

#### Как повторить

набиваем халат вещами, пытаемся положить в него ещё что-то

**Comment by Deahaka** [comment]
Потому что аксессуары на вещах-контейнерах ложаться в ячейки

**Comment by LudwigVonChesterfield** [comment]
я бы наверное предложил сделать надевание как и снимание на альт-клик, тогда не было бы непоняток когда хочешь налепить аксессуар - а когда положить в карман
