### ISSUE TITLE
Решетка не собирается

### ISSUE THREAD

**Issue by NeOchenLord** [TauCetiStation/TauCetiClassic#8731]
#### Подробное описание проблемы
Grille не собирается

#### Что должно было произойти
Тыкаю по паре палок в руке, собирается решетка

#### Что произошло на самом деле
Палки тратятся, а самой решетки нет

#### Как повторить
Собрать решетку из палок

#### Дополнительная информация:
Issue reported from  Round ID: 49342 (Tau Ceti Classic (RU))
Testmerges: ```#8674 #8614 #8605 #8579 #8571 ```
Reporting client version: 514.1571

**Comment by LudwigVonChesterfield** [comment]
1a24d68
