### ISSUE TITLE
Аварийные створки слоем ниже, чем окна, решетки, двери и прочее

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#874]
#### Подробное описание проблемы
![image](https://cloud.githubusercontent.com/assets/20542000/21051029/72f49532-be48-11e6-9a8f-ac02dc4f423d.png)

Аварийные створки лежат под шлюзами, окнами и прочим.
#### Что должно было произойти
Они должны закрывать собой двери и окна.
#### Что произошло на самом деле
Створки лежат под шлюзами.
#### Как повторить
Активировать створку, посмотреть на нее.

**Comment by Balphagore** [comment]
Так наоборот же кодили, чтобы они были снизу, разве нет? Так лучше видно - где что повреждено. Когда все под створками, то надо подходить и через альт смотреть - где пробоина.

**Comment by SpaiR** [comment]
Так и задумано
