### ISSUE TITLE
[Proposal] Удаления малфа из основной ротации

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#8748]
_(И наконец, самое вкусное.)_

На данный момент малф и 2/3 борга, не могут достаточно развлечь игроков как режим, в большинстве скатываясь в +/- 30 -- 40 минут эксты и следующую за этим резню против 2/3 боргов и ИИ, резня все ещё может быть ранней или после небольшой подготовки не затягиваясь на выше упомянутое время. При этом, игроки обязаны или игнорировать отсутствие других антагов _(или его скудное количество.)_ и после первого же анонса, стараться делать вид, что они конечно не знаю что сейчас за режим и чего ожидать в ближайшие 5 минут. _(Как можно заметить, большинство игроков уже после первого анонса могут откровенно начать с пустого места вести очень активное наблюдение за юнитами или троллить ИИ на тему -  "ИИ, а ты же не плохой? Да?" или, так или иначе готовится к штурму спутника.)_  

Перевести малфа, хотя бы временно в разряд ивентов возможно решит эту проблему, так как:
Его не будут ожидать. _(В игре будут присутствовать другие антагонисты, способные разнообразить смену.)_
Частично, уйдет мета на малфа. _(Хотя за ней все ещё будет трудно следить.)_
Расширится возможный отыгрыш. _(Как пример, малф сможет кооперироваться с другими антагами для достижения своих или общих для них целей.)_

Думаю, в комментариях к этому предложению найдется достаточно мнений которые смогут дополнить его и поделится личным опытом - "Почему же малф так плох?".

**Comment by cnaper-dodo** [comment]
Вообще,СПУ и робототехи могут кооперироваться с малышом,для сохранения своей жопы.У робототехов есть мета на малфа,так что...да.

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/9102
