### ISSUE TITLE
Дробовики и револьверы не стреляют

### ISSUE THREAD

**Issue by AndroBetel** [TauCetiStation/TauCetiClassic#8752]
#### Подробное описание проблемы
Тайтл.
#### Что должно было произойти
Стреляют.
#### Что произошло на самом деле
Не стреляют
#### Как повторить
Пострелять из револьвера или дробовика, будет только *click*
#### Дополнительная информация:
Рантаймов нет, но полагаю, что это из-за ПРа на телепатию

**Comment by LudwigVonChesterfield** [comment]
80e429a
