### ISSUE TITLE
Материал строительства удаляется при попытке создания предмета

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#8764]
#### Подробное описание проблемы
Если использовать минимальное количество металла, необходимое для создания предмета, то металл исчезнет, а предмет не создастся.

По видимому, это затрагивает только те предметы, которые после создания появляются в руке/на полу, а не те, которые вызывают меню строительства, как с какой-нибудь консолью или каркасом машины. Металл, например, удалится при создании рамки АПЦ, если в руке ты держишь ровно 2 листа металла, но сама рамка АПЦ не появится. Или, держа 1 лист металла в руке, ты не получишь например 4 плитки для пола таким образом. Если останется "сдача" при трате материала - то всё работает нормально.

То же самое замечено и с прутьями при попытке создать решётку под собой.

За простыми и укреплёнными листами стекла такое не замечено.

За древесиной замечен похожий баг - сандалики не сделать например.

По пластику и остальным ресурсам не могу сказать, поскольку там строительство задействует уже менюшку.

#### Что должно было произойти
Всё хорошее
#### Что произошло на самом деле
Всё плохое
#### Как повторить
Строить, используя ровно столько, сколько надо для стройки
#### Дополнительная информация:
Round ID: #49412, 15:20

**Comment by kalazus** [comment]
Причина почти наверное #8579 , там сразу используется материал, пропадает в нуллспейсе и только после он пытается под собой (уже в нуллспейсе) поставить то что нужно построить.

**Comment by LudwigVonChesterfield** [comment]
[58d42a4](https://github.com/TauCetiStation/TauCetiClassic/pull/8579/commits/58d42a48e986097c1b390bfc0bac8e26457919fe)

**Comment by kalazus** [comment]
Открывай снова, таких мест не 1, минимум ещё прутики Селф аттак.

**Comment by LudwigVonChesterfield** [comment]
прутики тоже пофикшены, а любые другие места репортите пожалуйста с инструкцией к восспроизведению
