### ISSUE TITLE
Разгрузка удаляется при ЛКМ-клике ей по одёжке

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#8765]
#### Подробное описание проблемы
ЛКМ клик удаляет разгрузку!

В иной раз, конечно, ЛКМ клик вообще не позволяет нацепить оную. Вообще не гарантировано, что клик по брюху разгрузкой удалит её и второй раз, и третий, или откажет надевать её на себя. Втф.

#### Что должно было произойти
Или надевает разгрузку как обычно, или вообще не даёт надевать разгрузку. Разгрузка не должна исчезать из руки!
#### Что произошло на самом деле
Разгрузка исчезла из руки. По всей видимости баг воспроизводится рандомно, но в начале смены на раунде что я приложил - подробно видно, что она исчезла.
#### Как повторить
ЛКМ-клик по пузику разгрузкой. Не проверял галстуки и кобуры
#### Дополнительная информация:
Round ID #49412

**Comment by LudwigVonChesterfield** [comment]
тыкал brown webbing vest и никуда он не исчезал. это точно актуально?

**Comment by AndroBetel** [comment]
Быстрый эквип через кнопку Е заставляет аксессуары исчезать.

**Comment by Deahaka** [comment]
> Быстрый эквип через кнопку Е заставляет аксессуары исчезать.

А у меня всё работает... Только через Е и надеваю хольстер, на H всё достаётся как положено...

**Comment by Pivo24** [comment]
Вот так вот!!

**Comment by Deahaka** [comment]
Сейчас попробовал - действительно нельзя снять альткликом хольстер с одежды, но хоткей работает...

**Comment by NinjaPikachuska** [comment]
С кобурой вообще смешно. При нажатии E она прикрепляется к кукле. Тоесть, будучи без вещей вообще, можно достать оружие из кобуры, которую никак не снять.
