### ISSUE TITLE
Невозможно разобрать телекоммуникационное оборудование

### ISSUE THREAD

**Issue by skvazarb** [TauCetiStation/TauCetiClassic#877]
#### Подробное описание проблемы
На этапе извлечения компонентов и удаления машины ничего не происходит.
#### Что должно было произойти
Оборудование должно разбираться
#### Что произошло на самом деле
На этом этапе кроме сообщения ничего не происходит
https://github.com/TauCetiStation/TauCetiClassic/blob/0f6e6cadcac3ac36a19acb0a71c1cec076bc9efa/code/game/machinery/telecomms/machine_interactions.dm#L60
#### Как повторить
1. Заспавнить /obj/machinery/telecomms/*
2. Попытаться разобрать
#### Дополнительная информация:
С собранными в течение раунда проблем, но те, которые уже на мапе или заспавнены, разобрать невозможно.

**Comment by SpaiR** [comment]
#569
