### ISSUE TITLE
It's too complicated for you.

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#8777]
#### Подробное описание проблемы
Борги не могут разобрать или как либо взаимодействовать инструментами с консолью управления боргами. _(В том числе и взломанные.)_

#### Что должно было произойти
Борг разбирает консоль как обычную.

#### Что произошло на самом деле
It's too complicated for you.

#### Как повторить
Попытаться разобрать консоль за борга.

#### Дополнительная информация:
Стоящие рядом консоли _(Да и вообще любые другие.)_ борги разбирают спокойно, делать исключением именно эту консоль странно. _(Хотя бы для взломанных боргов. Если для боргов со стандартными законами можно ещё придумать оправдание в виде подпрограммы подчинения или типа того, то в ситуации с взломанными юнитами - это не рабоатет.)_

**Comment by Kurshan** [comment]
Ни разу не ищью. Всё так и задумано по очевидным причинам.

**Comment by Mercurialaste** [comment]
> Ни разу не ищью. Всё так и задумано по очевидным причинам.

Даже для взломанных боргов?
Что именно им мешает разобрать консоль кроме оного решения кодеров?

Что мешает поменять разбитый у консоли экран? _(Это взаимодействие тоже я напомню, решили выключить.)_

**Comment by KIBORG04** [comment]
Не баг а фича
