### ISSUE TITLE
Багнутый салат

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#878]
#### Подробное описание проблемы
Не рабочий рецепт салата: "Tossed Salad"

#### Что должно было произойти
Салат должен был приготовится в микроволновке
#### Что произошло на самом деле
Вышла кучка фигни
#### Как повторить
Всунуть 2 Cabbage, 1 Tomato, 1 Carrot, 1 Apple в микроволновку и убедиться что он не работает.
#### Дополнительная информация:
По моей просьбе, порылись в коде и рецепта салата не нашли, хотя он сам по себе остался. Так же, после обновления кухни другие рецепты стали сомнительны как минимум потому что мука стала порошком. К примеру рецепт "Monkey's Delight" уже сомнительно готовить как там нужна 1 Flour.

**Comment by Damirrus1** [comment]
Вопрос уже решается.

**Comment by dearprincesscelestia** [comment]
А жареных гвоздей не добавишь?

**Comment by Dennok** [comment]
А жаренные айрон родсы для кого?

**Comment by dearprincesscelestia** [comment]
О, точно, пойдут.
