### ISSUE TITLE
Решётка (Grille) больше не ставится

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#8782]
#### Подробное описание проблемы
Не ставится решётка больше, всё
#### Что должно было произойти
Решётка
#### Что произошло на самом деле
Ничего
#### Как повторить
Сделать решётку из прутьев металла
#### Дополнительная информация:
Round ID #49472, 2 сервер

**Comment by LudwigVonChesterfield** [comment]
e946562
