### ISSUE TITLE
[Proposal] Расширить список доступных фракций, религий, гражданств и родных систем в Редакторе персонажа

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#8783]
**Религии:**

Из вики священника:

* Аколизм (объединение всех земных религий);
* Космо-Христианство (религия ксенофобов) - можно заменить текущий Christian на это;
* Технологизм (религия про перерождение в машине);
* Орден Великой Леди (Order of Great Lady, вера в дракона Леди Эльзру);

**Фракции:**

* BioTech Solutions, первоначальные создатели Бипски, специализируются в создании киборгов и спонсируются НТ.
* Убрать Алеф (Aleph), указанную в лоре СПУ как террористическую группу Позитронного Союза.
* Добавить Ксион (Xion), корпорацию, впервые создавшую СПУ!
* Позитронный Союз, собсна.
* Скреллианская Империя.
* Таяранские кланы? Хадии, Кайтам и Назкиин, каждый в отдельности? Или не надо?

**Гражданства:**

* Бимна, или Тау Кита III, планета в системе с сильной экономикой;
* Лутиэн, или Тау Кита II, конкретно одна из многих колоний среди опасных джунглей планеты;
* Новый Гибсон, или Тау Кита IV, та самая раздираемая восстаниями планета;
* Рид, или Тау Кита V, планета с фермами и паранормальными слухами о бабайках;
* Венера, которую забыли указать вместе с Марсом;
* [Аргелиус](https://wiki.taucetistation.org/E_Eridani), планета с двумя колониями на далёкой звезде Эпсилона Эридана, находящаяся под защитой НТ и обучающая офицеров на службу в НТ взамен.

**Родные системы:**
* Переименовать Epsilon Ursae Majoris на Epsilon Eridani (тот самый Эпсилон Эридана);
* Убрать Nyx, наверное, ведь про него ничего не написано.

**Comment by LudwigVonChesterfield** [comment]
альтернатива: выпилить эти опции потому-что их и так никто никогда не видит :flushed:

**Comment by Pivo24** [comment]
Они в Employment Records'ах и в Security Records'ах на видном месте...

**Comment by LudwigVonChesterfield** [comment]
и шо ты с ними делаешь?

**Comment by Pivo24** [comment]
Читою

**Comment by Akellazp** [comment]
ого, беполезно! :+1:

**Comment by Pivo24** [comment]
Нет, полезно...

**Comment by DarthSidiousPalpatine** [comment]
Переведи Free Trade Union как Независимый Профсоюз и будет ок.
А то Независимый союз торговцев, млять.

**Comment by Dwagdore** [comment]
Замержили. Можно закрывать
