### ISSUE TITLE
Внезапная стена на одном тайле с окном.

### ISSUE THREAD

**Issue by Kilkalestia** [TauCetiStation/TauCetiClassic#879]
#### Подробное описание проблемы
На входе в отдел переработки справа в окне стоит лишняя стена
#### Что должно было произойти
Её там быть не должно
#### Что произошло на самом деле
Она там есть 
#### Как повторить
Нажать ПКМ по тайлу
#### Дополнительная информация:
![image](https://cloud.githubusercontent.com/assets/23171919/21082435/70d9323a-bfec-11e6-96fd-4d2669636c98.png)

**Comment by StrikS** [comment]
![image](https://files.slack.com/files-pri/T04PN2JUW-F3CKBK0G0/screenshot_1.png)
