### ISSUE TITLE
Мехи и консоль контроля

### ISSUE THREAD

**Issue by MrFoxik** [TauCetiStation/TauCetiClassic#881]
#### Подробное описание проблемы
Использование подачи ЕМП импульса по мехам с помощью консоли контроля оных не взрывает их, не наносит урон, ничего.
#### Что должно было произойти
Мех должен был получить урон/постепенно получать урон/взорваться
#### Что произошло на самом деле
Мех не получил урон или не взорвался
#### Как повторить
Нажать EMP impulse на консоли мехов в комнате РД.
#### Дополнительная информация:

**Comment by Skippeer12** [comment]
Он должен выжигать им батарейку до нуля и на этом всё.
Но так как никто не ставит маячки на боевых мехов это бесполезная функция работает только на Риппли и Одиссея.

**Comment by Dennok** [comment]
Добавилиб чтоли функцию извлечения космонавтика из меха туда чтоли. Ато чтоб достать чела из него надо уничтожать мех.
