### ISSUE TITLE
Особка "mutant" не работает, если зайти не раундстартом

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#8811]
#### Подробное описание проблемы
Особка "mutant" не работает, заходишь в раунд, а мутаций нет.
#### Что должно было произойти
Мутация есть.
#### Что произошло на самом деле
Её нету.
#### Как повторить
Получить особку "mutant" и зайти в раунд

**Comment by Zickusable** [comment]
И богатство тоже не выдается

**Comment by LoTaRk-FroG** [comment]
Так, 5 раз выпадала особка, из этих 5 только 1 раз выдало мутацию-болезнь. Может ли быть так, что блок не активируется?
