### ISSUE TITLE
Гост может сосать (заглатывать)

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#8831]
#### Подробное описание проблемы
Название чисто для привлечения внимания.
Гост может делать gulp down на стаканы и всем окружающим это будет высвечиваться в чат.
#### Что должно было произойти
Гост не может.
#### Что произошло на самом деле
Гост может.
#### Как повторить
Зайти за госта и сделать gulp down на любом стакане.

**Comment by DarthSidiousPalpatine** [comment]
Ааа. не фиксьте, я хочу это увидеть в раунде
