### ISSUE TITLE
Latejoin голем культа получает стандартное ограничение движения

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#8852]
#### Подробное описание проблемы
Ивент-аномалия-портал культа.
Если подождать пока зона движения големов расширится, а потом зайти за голема, то ограничение движения останется стандартным, не смотря на расширение. 
#### Что должно было произойти
Голем двигается в соответствии с зоной.
#### Что произошло на самом деле
Голем двигается в соответствии со стандартным значением зоны, при этом стандартная зона расширяется вместе с настоящей зоной.
#### Как повторить
Получить портал культа, подождать 5-10 минут, зайти за голема и ахуеть.

**Comment by KIBORG04** [comment]
у каждого челика свой радиус, а не общий
