### ISSUE TITLE
Борги не могут выбирать язык по умолчанию

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#8854]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/90282587/158705575-9ec96816-5ab3-4d23-931a-d59e8142a4cd.png)
Льзя... У боргов там нету кнопок.

#### Что должно было произойти
Борги булят мешки с мясом у по умолчанию говорят на тринарном. _(К примеру.)_
#### Что произошло на самом деле
Говорить на тринарном _(К примеру.)_ можно говорить только вводя префикс соответствующего языка. 
_(Может кстать, кто-нибудь сказать почему префикс тринарного был перенесен с :x :ч на :p :з?)_
#### Как повторить
Быть боргом.
#### Дополнительная информация:
–

**Comment by LudwigVonChesterfield** [comment]
[751c2f1](https://github.com/TauCetiStation/TauCetiClassic/pull/8810/commits/751c2f128f8b6f4a701f91143212cf198abc1a7c)
