### ISSUE TITLE
Слимы и баги\недоработки

### ISSUE THREAD

**Issue by OfGreyBugWaifu** [TauCetiStation/TauCetiClassic#886]
#### Подробное описание проблемы
Геймпей слимов узок и недоработан - но это не удивительно - они появляются в раунде редко и не очень его улучшают. Вне зависимости от этого я прошу немного любви и внимания нашим мутным друзьям. Например:
1) При смерти большой слим разделяется на маленьких - но не управляет ни одним из них - он просто гостается, совсем мгновенно.
2) Слим совсем не может есть нормальную еду - ни мясо, ни овощи, даже жидкости. Более того - они не могут есть большинство других мобов (коров и медведей).
3) Слим - игрок не страдает от температуры - только от воды из огнетушителя.
4) У слимов нет интента - каждый их клик - агрессия, хоть игроки - слимы должны быть разумны.
#### Что должно было произойти
1) При смерти игрок должен занимать место одного из двух легко убиваемых слимов.
2) Слим должен иметь возможность кушать обычную еду и напитки.
3) Слим или должен страдать от всей воды (лужи на полу) или от всей температуры (криоганы и т.п.)
4) Слимы должны иметь возможность хоть гладить или облизывать других игроков.
#### Что произошло на самом деле
Ничего из вышеперечисленного.
#### Как повторить
Зайти за ксенобилого и вколоть себе экстракт чёрного слима.

**Comment by OfGreyBugWaifu** [comment]
Было бы шикарно добавить слабостей к воде (урон при проходах по лужам, при попадании под душ, при разбрызгивании (спреер, мензурка)) и убрать космический дамаг - так слимов можно было бы давать нюцке или пейратам, или давать игрокам возможность немного выходить за рамки станции - ведь на слимов нет ригов и нет баллонов.

**Comment by Dennok** [comment]
Вроде слаймы мобы спокойно себя чувствуют в космосе.

**Comment by WallShrabnic** [comment]
Слаймы - люди быстро в космосе гибаются

**Comment by OfGreyBugWaifu** [comment]
Слимы мобы страдают либо от давления, либо от космоса самого - если посадить слимов-детишек в правый-нижний вольер и открыть створки, то они, через какое-то время, умрут.
