### ISSUE TITLE
Оверлей книги на трибуне поверх лица если трибуны смотрит на север

### ISSUE THREAD

**Issue by QWxiZX** [TauCetiStation/TauCetiClassic#8860]
#### Подробное описание проблемы

А ещё в нормальной кафедре стоячей спрайт ломается.
![image](https://user-images.githubusercontent.com/70110199/158877569-fc653dd8-7b3b-4763-a23f-b3644fe07a1f.png)
Если стоять на тайле с ней и Rotate через ПКМ. Книга идёт впереди лица.

#### Что должно было произойти

иначе

#### Что произошло на самом деле

вот так

**Comment by LudwigVonChesterfield** [comment]
это можно конечно пофиксить, но оно пофиксится само когда все dir = заменят на set_dir
