### ISSUE TITLE
Смещение pixel_x pixel_y при кликплейсе альткликом

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#8862]
#### Подробное описание проблемы

![image](https://user-images.githubusercontent.com/17705613/158886665-15c044fb-aa96-47a8-a9a9-d9f952e884d1.png)

Альт-кликом кликнул по ящику и положил шмотку.

#### Что должно было произойти

Она должна была быть где-то в пределах ящика.

#### Что произошло на самом деле

Она лежит физически в ящике, но смещена так что выглядит будто вне ящика.

#### Как повторить

Заложить ящик кучей всякого шмота.
Альт клик по ящику.
В окошке справа сверху положить вещь в ящик.

**Comment by Deahaka** [comment]
Было и с столами. Подходишь в столовую/окошко РнД с листом бумажки, альткликаешь на стол и эта бумажка уходит вправо, иногда вообще на соседнюю клетку или через две.

**Comment by kalazus** [comment]
Происходит из-за того что название предмета в статпанели считается частью спрайта, как чинить хз, учитывая что нормально вроде не получить высоту и ширину спрайта, который ещё строка.

**Comment by LudwigVonChesterfield** [comment]
ну как минимум надо min(смещение, 32), уже на половину беды меньше было бы

**Comment by kalazus** [comment]
Так спрайты могут быть и больше.

**Comment by LudwigVonChesterfield** [comment]
пока-что спрайты на что ложить можно только 32 на 32............ но ты конечно можешь таки поискать проки получать ширину высоту
