### ISSUE TITLE
Безногие, безрукие и другие могут быть антагами

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#8877]
#### Подробное описание проблемы
Жирные, слепые, безногие и прочие неспособные к боевым действиям люди могут становиться антагонистами. Ладно трейторами или генокрадами, там можно хоть как-то выкрутиться и по тихому выполнить цели, но инвалид может стать нюкером и даже магом.
#### Что должно было произойти
Все ОК
#### Что произошло на самом деле
Чёртов маг оказался слепоглухонемым жирдяем с турретом и заиканием.
#### Как повторить
Сделать персонажа с кучей отрицательных трейтов и поставить префы на антагов.

**Comment by KIBORG04** [comment]
Фича
