### ISSUE TITLE
Отвалился спрайт антикварного лазера в руках

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#888]
#### Подробное описание проблемы
При ношении антикварного лазера в руках спрайт отстутствует.
#### Что должно было произойти
Спрайт должен быть
#### Что произошло на самом деле
Спрайт украли
#### Как повторить
Достать антикварный лазер

**Comment by StrikS** [comment]
Фича! Стелс пушка!

**Comment by StrikS** [comment]
Я тут подумал... в общем это баг, все-таки...
