### ISSUE TITLE
[Bug] Сломанный атмос в генокрадо-раундах. 

### ISSUE THREAD

**Issue by Smalltasty** [TauCetiStation/TauCetiClassic#8890]
#### Подробное описание проблемы
В раунде с генокрадами ОЧЕНЬ часто багуется атмос. Проблемы могут быть самыми разными: 
* безумно высокая температура и, как следствие, высоченное давление. 
![изображение](https://user-images.githubusercontent.com/12589405/159131257-421ec95a-a68a-4979-90e6-394683551041.png)
* безумно низкая температура и, как следствие, отрицательное давление. 
![изображение](https://user-images.githubusercontent.com/12589405/159131287-f3427502-2fc1-4b75-a442-461c996c1390.png)
* А до каких значений может дойти температура и давление - вообще загадка. 
![изображение](https://user-images.githubusercontent.com/12589405/159131350-fa028d86-5f69-4cee-88ae-ad6ce68da92b.png)
Достоверно неизвестно место откуда именно это начинается. В частности раунд 49788 и 49786 были раундами с генокрадами и багнувшимся атмосом. 
Время бага на реплее 49788 - 27:07 (мощности ноута не хватает чтоб просмотреть каждого кто что-либо делал на сервере в то время).
#### Что должно было произойти
Атмос не должен багаться по желанию левой пятки. 
#### Что произошло на самом деле
Станция мертва из-за аномально высоких показаний взбесившегося атмоса. 
#### Как повторить
Зафорсить генок на сервере и посмотреть что будет происходить. 
#### Дополнительная информация:
Один и тот же рантайм был замечен в обоих раундах: 
49786: 
![изображение](https://user-images.githubusercontent.com/12589405/159131559-82cebc39-b7c1-4ec2-9f12-42f7b53fd94b.png)
![изображение](https://user-images.githubusercontent.com/12589405/159131545-e4288e81-5585-45d9-9970-5a2d1ee13f5a.png)
![изображение](https://user-images.githubusercontent.com/12589405/159131552-2c9e099e-2e59-488c-9afd-a406925ff31a.png)
49788: 
![изображение](https://user-images.githubusercontent.com/12589405/159131595-3729a93a-d871-4ed5-a772-e53cec1257c5.png)
![изображение](https://user-images.githubusercontent.com/12589405/159131603-3b377ab5-47e9-410a-ac92-f19e1a0163e4.png)
![изображение](https://user-images.githubusercontent.com/12589405/159131632-7ed8fa95-e332-4c42-948a-06b575654e2b.png)

Issue reported from  Round ID: 49788 (Tau Ceti Classic (RU))
Testmerges: ```#8579 #8779 #8868 ```
Reporting client version: 514.1582

**Comment by volas** [comment]
Тут у меня пельмен спрашивал, когда было первое появление, и я его случайно обманул. Ошибка
> illegal: pow() in xgm_gas_mixture.dm:195

встречается как минимум с 2020. И не только в генокрадах. И это может быть просто следствием других проблем, не всегда фатальных.

По раунду 49786, еще был проблемный рантайм в цепочке мастера (но мастер вроде не падал):
```
Cannot read null.lingchemdisplay in essences.dm:205 :
proc name: Life (/mob/living/parasite/essence/Life)
  source file: essences.dm,205
  usr: null
  src: Kenneth Harrow (/mob/living/parasite/essence)
  src.loc: the monkey (71) (/mob/living/carbon/monkey)
  call stack:
Kenneth Harrow (/mob/living/parasite/essence): Life(2)
Mobs (/datum/controller/subsystem/mobs): fire(0)
Mobs (/datum/controller/subsystem/mobs): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

**Comment by Smalltasty** [comment]
Конкретно сейчас атмосопроблемы только в генках встречаются. Был ещё один тип проблемы, когда атмос останавливает процессинг. Генка разбивал стекло в космос, но воздух не уходил, створки не опускались. Но это было давно. 
Конкретно эти два раунда в репорте я была в админах, сообщений о зависших контроллерах не видела в чате.
