### ISSUE TITLE
Зомби грустит

### ISSUE THREAD

**Issue by kalazus** [TauCetiStation/TauCetiClassic#8899]
#### Подробное описание проблемы
Зомби грустят как люди

#### Что должно было произойти
Зомби не нужно прибираться, чистить и сушить одежду, курить, говорить.

#### Что произошло на самом деле
Зомби грустят так как вокруг кровь и кишки

#### Как повторить
Поиграть за зомби

**Comment by DarthSidiousPalpatine** [comment]
Зомби грустят потому что им больно видеть белый свет
Им лучше в полной темноте
Они очень много-много лет
Мечтают только о еде.

**Comment by Bullethole** [comment]
еще если закуфать зомби и кинуть еще в шкаф, то он уже нихуя не сделает
