### ISSUE TITLE
Если перезайти в синдидрона пока он в трубах черный оверлей пропадает

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#8902]
#### Подробное описание проблемы

Если проделать шаги описаные в как повторить, дрон в трубах видит всё, вместо 3 на 3 тайлов

#### Как повторить

Купить дрона
Залезть в трубу
Выключить контроль
Включить контроль

**Comment by KIBORG04** [comment]
Дубликат вроде

**Comment by LoTaRk-FroG** [comment]
Дубликат дубликата.

**Comment by LudwigVonChesterfield** [comment]
#8450
