### ISSUE TITLE
Проблема с головными уборами у воксов

### ISSUE THREAD

**Issue by UsadoSmokk** [TauCetiStation/TauCetiClassic#8904]
#### Подробное описание проблемы
Воксы не могут надеть какси и ушанки(и кастомные шапки), не смотря на наличие в спрайтах воксов нужных иконок

#### Что должно было произойти
Если в файлах воксов есть иконка каски, вокс сможет надеть каску

#### Что произошло на самом деле
На голову вокса не лезет каска, ушанка и кастомные шапки

#### Как повторить
Попытаться надеть что-то из этого

#### Дополнительная информация:
Баг зависит от чего-то неясного, в одном раунде все может быть плохо, на следующий уже починиться.

**Comment by LudwigVonChesterfield** [comment]
Вероятно связано, а если и не связано то всё равно надо исправить, с тем, что:

https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/clothing/clothing.dm#L88

Хардкод айкон стейта

https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/mob/living/carbon/human/update_icons.dm#L140

Функция получающая настоящий айкон стейт.

Рекомендую добавить функцию get_standing_icon_state() которая будет использоваться в обоих местах, таким образом не будет существовать ситуаций, когда айкон стейт который используется для проверки ограничений отличается от айкон стейт оверлея на мобе.
