### ISSUE TITLE
Фиксили букву "Я" в резонах банов, но когда бан пишет в ноутсы "Я" всё еще сломана.

### ISSUE THREAD

**Issue by Tankred0** [TauCetiStation/TauCetiClassic#891]
#### Подробное описание проблемы
 В ноутсах у игроков сломана буква я при добавлении ноутса автоматически при бане.

####  Что должно было произойти
Будучи Ассистентом захватил власть и проявил чудеса отвратительного ролеплея за капитана(полное не умение в отчёт, командование, отыгрыш, etc.) Попытался перестрелять офицеров за то, что те отказались ему подчиняться

#### Что произошло на самом деле 
`Будучи Ассистентом захватил власть и про&#1103;вл&#1103;л чудеса отвратительного ролепле&#1103; за капитана(полное не умение в отчёт, командование, отыгрыш, etc.) Попыталс&#1103; перестрел&#1103;ть офицеров за то, что те отказались ему подчин&#1103;тьс&#1103`

####  Как повторить
Накинуть джоббан или просто бан где в ризоне будет буква Я

**Comment by Raschert0** [comment]
@volas последствия фикса

**Comment by Tankred0** [comment]
Поправил строчку что произошло: Гит исправлял часть текста и делал нормльную Я
