### ISSUE TITLE
Отсутствует возможность внутри раунда проверить нативный список экипажа

### ISSUE THREAD

**Issue by skvazarb** [TauCetiStation/TauCetiClassic#892]
#### Подробное описание проблемы
Если я ничего не упускаю, на данный момент внутри раунда нет никакого способа проверить список экипажа на начало раунда, а не актуальное состояние. В общем случае это не является критичной проблемой, но это представляет неразрешимую проблему для синтетиков в определении членов экипажа и их ранга. Таким образом, они не могут выполнять корпоративные законы должным образом.
Можно предложить, как минимум, несколько способов решения этой проблемы:
1. Добавить синтетам второй вариант крю манифеста, который не меняется в течение раунда.
2. Аналогичный вариант для Identification Computer.
3. Отдельное поле в Employment Records.
.

**Comment by dearprincesscelestia** [comment]
Можно контрпропозал?

Контрпропозал сложнее и с приглашением на дискуссию.

Убрать из крю манифеста автоматические добавления вовсе, и возложить их на хопа-шитсеков-ии-медеков через консоли рекордсов.

Правда, это как-то совсем вне моего текущего скилла (наверное), но я вброшу идею, вдруг решат, что правда надо.

**Comment by StrikS** [comment]
>Убрать из крю манифеста автоматические добавления вовсе, и возложить их на хопа-шитсеков-ии-медеков через консоли рекордсов.

Даааа, учитывая что никогда не заполняются дела почти

**Comment by Dennok** [comment]
И пусть мед анализаторы (ручные и худы) работают только если член экипажа есть в рекордсах, он в одежде с сенсором, и они активны хотяб в 1м режиме(а лучше во 2м).

**Comment by Flankir** [comment]
Ну худы логично, но при чем тут ручные то? Это сканер, ему не нужны сенсоры костюма.

**Comment by Dennok** [comment]
Можно будет добавить в РнД апгрейд для сканера чтоб без сенсоров работал.
И кинуть СМО адвансед с сканом всего что только можно.

**Comment by Flankir** [comment]
И главное, а с какой стати собственно синтеты должны иметь возможность без каких либо усилий вычислить самозванцев? Пускай потрудятся залезть в личное дело.

**Comment by skvazarb** [comment]
>Пускай потрудятся залезть в личное дело.

Какое личное дело? Все доступные игровые способы показывают только актуальное состояние списка экипажа, в этом и проблема.

**Comment by Dennok** [comment]
Консолька с личными делами у каждого главы отдела(а еще в ваулте ящичек с ними, но там всеодно нужна карта главы.), Консолька медзаписей в меде, секюрити рекордсы у секюрити.
ВОт это все может указать на то прилетел чел с велосити или просто мимокрокодил.

**Comment by skvazarb** [comment]
Может указать, а может не указать. В абсолютном большинстве случае как раз не может.

**Comment by Dennok** [comment]
поему не может?
Есть дело значит чела начальство прислало (или он молодец и сделал себе личные дела)
А нет дела - значит мимокрокодил.

**Comment by skvazarb** [comment]
Так дело то есть, но там у ассистента написано "Captain", потому что он только что себе доступ поставил в консольке.

**Comment by Dennok** [comment]
А вот это да, что в крю манифесте доступ идет от карты.

**Comment by Dennok** [comment]
И вообще, к чему ты клониш? Если асистент потставил себе доступ капитана то для синтетов он капитан.

**Comment by skvazarb** [comment]
С чего он для них капитан то? А если их два, оба капитаны?
Чтобы понять весь абсурд ситуации, легко привести пример. Ассистент проникает в капитанскую и ставит себе доступ капитана. А когда туда прибегает охрана чтобы его арестовать, их всех арестовывает щиткурити борг за нападение на законного капитана.

**Comment by Dennok** [comment]
Уот так уот. 
А как иначе?

**Comment by skvazarb** [comment]
Я написал как иначе в первом посте. Совершенно очевидно, что ранг экипажа для синтетов определяется на начало раунда, а не по доступу на карте в течение раунда.

**Comment by StrikS** [comment]
А почему бы синтетам не подчиняться капитану по крю? Это как во властелине колец "у тебя меч? Армия бессмертных повинуется!"

**Comment by skvazarb** [comment]
Я привел пример к чему это может приводить. Это создает огромную дыру в безопасности, которая никак необоснованна игровым балансом и полностью противоположна хоть каким-то намекам на реалистичность. Так как для боргов ранг экипажа является важнейшим критерием, а доступ на карте и, соответственно, текущее состояние крю манифеста - изменяются элементарным образом. При этом назначение глав в течение раунда вообще не предусмотрено.

**Comment by StrikS** [comment]
Да, борг пусть вяжет за нападение, фактически для машины они напали на члена экипажа ранга капитана. Еще один повод доказать, что борги не очередной респрайт.

**Comment by skvazarb** [comment]
Но зачем кому-то может понадобиться такая система? У боргов корпоративные законы, которые как раз предназначены для поддержания иерархии и защиты глав. Если игроку нужно получить контроль над боргами, для этого уже есть механизм изменения законов. Изменить себе доступ несравнимо проще и это делает изменение законов почти бесполезным. Это всё серьезно нарушает игровой баланс, когда синтетики должны считать относительно надежными.

**Comment by StrikS** [comment]
Мостик самая защищенная часть станции, тебя будут слушаться борги, если ты им прикажешь, да и то, если ты попросишь арестовать офицеров, на это нужны основания. А если щитсеки молча(как обычно) начнут стрелять, то пусть пиняют на себя. Если же ты, например, начнешь палить по щитсекам, то борг вправе тебя задержать. Законы по прежнему корпоративные, не синдикатовские. То что ты привел интересная игровая ситуация, а как она разрешится зависит от интеллекта "капитана".

**Comment by skvazarb** [comment]
Консоль и нужный доступ стоят не на мостике для начала.  Твоя логика в предыдущем сообщении потратилась чуть больше чем полностью. Если по твоей же очень странной логике, ассистент с доступом капитана становится для синтетов капитаном, то он в своей каюте отбивается от мятежников, которые на него напали, и имеет, с точки зрения синтетов, на это полное право, при этом надо помочь именно ему, а не офицерам-мятежникам. Последнее можно назвать как угодно, но точно не интересной игровой ситуацией.

**Comment by StrikS** [comment]
Нужный доступ можно получить либо обув хопа либо украв карту. И никак иначе

> Если по твоей же очень странной логике, ассистент с доступом капитана становится для синтетов капитаном, то он в своей каюте отбивается от мятежников, которые на него напали, и имеет, с точки зрения синтетов, на это полное право, при этом надо помочь именно ему, а не офицерам-мятежникам. Последнее можно назвать как угодно, но точно не интересной игровой ситуацией.

А по моему очень интересно. Хочешь использовать дедуктивный метод играй за людей. 

P.S. Или накодь логи изменения доступа в id компьютере. Чтобы все могли туда глядеть.
