### ISSUE TITLE
У абдукторов (и возможно всяких шедоулингов и прочих антагов) портится настроение

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#8938]
#### Подробное описание проблемы
Абдуторы получают дебаффы  к настроению, что вообще-то несвойственно высшей расе
#### Что должно было произойти
Кондуктор бесчеловечен и не должен бегать на кухню воровать жратву и курить
#### Что произошло на самом деле
Я проиграл потому что гонял с сигаретой
#### Как повторить
Поиграйте за кондуктора и словить депрессию

**Comment by DarthSidiousPalpatine** [comment]
наоборот прикольно что кондукторам надо воровать вещички экипажа

**Comment by KIBORG04** [comment]
Фича, либо сам фикси

**Comment by Venngedi** [comment]
#9236 Fixed.

**Comment by Deahaka** [comment]
> наоборот прикольно что кондукторам надо воровать вещички экипажа

Oh no, gysev's cringe
