### ISSUE TITLE
Обезьяна в вентиляции - причина поломки атмоса

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#8939]
#### Подробное описание проблемы
Недавно стал частить баг где воздух вдруг возрастает до СТРАШНЫХ значений, атмос ломается, а экипаж умирает. Замечали, что в генко-раунды такое часто.

Что ж, причина найдена, и найдена она была не в генко-раунд. Обезьяна, ползая по вентиляции, получает урон от высокого давления и температуры в трубах. Каким-то образом это высокое давление теперь окружает обезьянку не внутри самих труб, а над ними, то есть в коридорах.
#### Что должно было произойти
Обезьяна или получает урон, или не получает урон, но главное - без разгерм на всё живое с 111410591059109 кПа
#### Что произошло на самом деле
Да
#### Как повторить
Генетика - ген обезьяны - в вентиляцию и поползать
#### Дополнительная информация:
Issue reported from  Round ID: 49902 (Tau Ceti Classic II (RU))
Testmerges: ```#8868 #8779 #8579 ```
Reporting client version: 514.1582

**Comment by KIBORG04** [comment]
Насколько информация точка? Какой коммит это делает? Как?

**Comment by KIBORG04** [comment]
Рантайм логи этого раунда вообще не содержат какой-либо информации о поломке атмоса.

**Comment by Pivo24** [comment]
> 
Насколько информация точна? Какой коммит это делает? Как?

Мега точно прям сейчас проверяем на сэндбохе.

Не ебу какой.

Я описал как.

**Comment by Pivo24** [comment]
> Рантайм логи этого раунда вообще не содержат какой-либо информации о поломке атмоса.

Рантайм-котек и не спавнился в свою очередь, всё просто происходит вот так

**Comment by NinjaPikachuska** [comment]
Я просто залез в венту за макаку в капитанской, посидел там, и атмос вокруге сломался.

**Comment by NinjaPikachuska** [comment]
Залезаем.
![image](https://user-images.githubusercontent.com/89906909/159792926-06eb6c10-09f2-43cb-a797-d7c45cc8e5a8.png)
Сидим в трубе и смотрим, как лагает температура.
![image](https://user-images.githubusercontent.com/89906909/159792934-08de93f4-93b9-4fd7-9cd5-a903379b8c7d.png)
![image](https://user-images.githubusercontent.com/89906909/159792941-270a35da-636a-477e-b4ff-f07e1f8c68d8.png)
Слышим атмос тревоги, вылезаем и любуемся.
![image](https://user-images.githubusercontent.com/89906909/159793032-7e57ede0-aae3-419c-acee-73620ec9f017.png)
![image](https://user-images.githubusercontent.com/89906909/159793215-26f9de93-2d53-4154-a5ac-77d4aaab73c6.png)

**Comment by KIBORG04** [comment]
Видимо, ПР калазуса реально все сломал.

**Comment by kalazus** [comment]
Так баг был до меня... Вроде, но чекну сегодня.
