### ISSUE TITLE
Дреды до сих пор отсутствуют

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#8941]
#### Подробное описание проблемы
Сосискин твой хотфикс ничего не хотфикснул, Dreads и Long Dreads всё ещё пропали
#### Что должно было произойти
Дреды у ящеров отображаются
#### Что произошло на самом деле
Нет не отображаются, дреды украли вохи
#### Как повторить
Выбрать ящера в редакторе персонажей, и уже там поглядеть данные причесоны.

Можно зайти в игру и через парикмахера поглядеть - та же беда
#### Дополнительная информация:
https://github.com/TauCetiStation/TauCetiClassic/pull/8925

**Comment by KIBORG04** [comment]
Сервер не обновлен
