### ISSUE TITLE
Общегалактический вокс

### ISSUE THREAD

**Issue by Vysserath1** [TauCetiStation/TauCetiClassic#8950]
#### Подробное описание проблемы
Особки на изменения языка плохо работают с воксами. Самое что я заметил - особка на гласные Ё меняет Вокс-Пиджин на Общегалактический, на котором они говорить не могут изначально.
#### Что должно было произойти
У вокса все гласные заменены на Ё
#### Что произошло на самом деле
Вокс говорит не на Пиджине, а на Общем
#### Как повторить
Получить за вокса особку на гласные Ё 
#### Дополнительная информация:
Я в том раунде был нюкеров, может как-то повлияло, но врятли

**Comment by LudwigVonChesterfield** [comment]
он говорит на Шкандинавском а не общем вообще-то

**Comment by LudwigVonChesterfield** [comment]
(описание особки: "Ты знаешь только один язык и будешь говорить только на нём")

**Comment by Vysserath1** [comment]
У меня не было ни одной Ё
Вообще
Никаких дефектов
Чистый галактик

**Comment by Vysserath1** [comment]
Кстати. Украинский акцент также не работает. Спокойно говорю без дефектов
И фишки трейда не работают
Речь никак не меняется
