### ISSUE TITLE
Сломанная особка diggydiggyhole

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#8959]
#### Подробное описание проблемы
Чел становится карликом, но волосы остаются на месте взрослого человека.

ПРОПУЩЕН ВЫЗОВ regenerate_icons(). По крайней мере, вызов этой функции через ВВ помогло.

https://github.com/TauCetiStation/TauCetiClassic/blob/254c7de861f04497074f7e5fd01267904d40ff4d/code/datums/qualities/quirkieish.dm#L72-L88

#### Что должно было произойти
Волосы карлика

#### Что произошло на самом деле
Волосы летают

#### Как повторить
Выдать особку

**Comment by LudwigVonChesterfield** [comment]
#8851
