### ISSUE TITLE
Кэтволки на зимнем боксе невидимы и светятся синим

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#8960]
#### Подробное описание проблемы
Кэтволки почему-то синие 

![image](https://user-images.githubusercontent.com/26389417/160195702-9a71c2c1-77f4-4ea1-b45e-375c9b53b13b.png)

![image](https://user-images.githubusercontent.com/26389417/160195692-93b5a1c7-7e70-431d-a841-d9372d3bebd7.png)

#### Что должно было произойти
Их нету или они просто видимы. Не светятся синим.

#### Что произошло на самом деле
Снег. Синие.

#### Как повторить
Включить бокс стейшон (снови) и полетать гостом.

**Comment by kalazus** [comment]
Синие это нормально (т.к. у нас нет лёгкого статичного света), но почему пропали хз, скорее всего уровень изменился из-за того что заставили изменить тип, чинится изменение уровня.
