### ISSUE TITLE
Алтарь священника не меняет спрайт

### ISSUE THREAD

**Issue by MrFoxik** [TauCetiStation/TauCetiClassic#8965]
#### Подробное описание проблемы
Уже несколько месяцев никто не репортит, что алтарь священника не меняет свой спрайт после его выбора в книге.

#### Что должно было произойти
Алтарь священника должен был поменяться с дефолтного НТшного
#### Что произошло на самом деле
НИЧЕГО
#### Как повторить
Поменять спрайт через библию, и посмотреть на реакцию.

**Comment by KIBORG04** [comment]
> Уже несколько месяцев никто не репортит

(12 месяцев, если быть точным)
