### ISSUE TITLE
Генокрад кравл мусклез

### ISSUE THREAD

**Issue by UnRobust** [TauCetiStation/TauCetiClassic#8976]
#### Подробное описание проблемы
Генокрад прожимает  Strained Muscles, армблейд и кравл
Генокрад избивает людей армблейдом под спидами и по нему невозможно попасть.

#### Что должно было произойти
По генокраду возможно попасть
#### Что произошло на самом деле
Генокрад дрочит на гринтекст потомучто по нему невозможно попасть

#### Как повторить
Crawl, Strained Muscles, Armblade
#### Дополнительная информация:
Как то дизбалансно

**Comment by Deahaka** [comment]
Альтклик по полу и дубинку в руки, стрелять он лёжа точно не сможет. Xenomorph gaming...

**Comment by LudwigVonChesterfield** [comment]
@KIBORG04 это кажется skill issue?

**Comment by KIBORG04** [comment]
Скилл ишуй. А еще в кравле нельзя драться поидее

**Comment by KIBORG04** [comment]
А не, кажись можно в кравле драться за генку. Пипец. Но все равно данный баг не баг

https://forum.taucetistation.org/t/bh-epicheskij-gejmerskij-govnokrad/32671
