### ISSUE TITLE
Отсутствие отображения джампсьютов на воксов.

### ISSUE THREAD

**Issue by INwirstD** [TauCetiStation/TauCetiClassic#8978]
#### Подробное описание проблемы
Стандартные джампсьюты, всех цветов, при надевании на вокса не отображаются на модельке. (Судя по всему ещё некоторые, например, генетика тоже не отображался). Помимо этого всего, джампсьюты нельзя roll dawn-ить, даже те которые отображаются нормально. 
#### Что должно было произойти
Джампсьюты должны отображатся и roll dawn-ится
#### Что произошло на самом деле
Джампсьюты не отображаются и не roll dawn-ятся
#### Как повторить
Надеть джампсьют на вокса.
#### Дополнительная информация:
Issue reported from  Round ID: 50031 (Tau Ceti Classic (RU))
Testmerges: ```#8930 #8868 ```
Reporting client version: 514.1581

**Comment by WatlerJe** [comment]
Такое не только у воксов, но и у всех рас.
