### ISSUE TITLE
Vox CMO hardsuit modification

### ISSUE THREAD

**Issue by ZER0-In** [TauCetiStation/TauCetiClassic#8985]
#### Подробное описание проблемы
В автомате модификаторов ригов, модификатор рига СМО для воксов подписан как Unathi CMO hardsuit modification. Ошибка в названии. 
#### Что должно было произойти
Должно быть название Vox CMO hardsuit modification
#### Что произошло на самом деле
Unathi CMO hardsuit modification
#### Как повторить
Подойти к автомату модификаторов рига в EVA.

**Comment by LudwigVonChesterfield** [comment]
кто-нибудь пожалуйста сделайте чтобы модификаторы были не на расу + вид рига, а просто на расу. "Vox hardsuit modification", и работает на любой риг - делая из него Воксориг

**Comment by pro100kotah** [comment]
Лучше уж тогда всем ксеносам так сделать, чтобы проблем меньше было.

**Comment by simb11** [comment]
#10465
