### ISSUE TITLE
Broken Bluespace Shelters

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#8992]
#### Подробное описание проблемы
Не работают шелтеры шахтеров ни в космосе, ни на астероиде, считает что мы находимся на станции и выдает вместо шелтера набор из скафандра, баллона и аптечки.
The bluespace shelter capsule says, "You must use shelter at asteroid or in space! Grab this shit and shut up!"
#### Что должно было произойти
Должен был построиться шахтерский спасательный шелтер.
#### Что произошло на самом деле
"The bluespace shelter capsule says, "You must use shelter at asteroid or in space! Grab this shit and shut up!""
Выдали набор из скафа, баллона и аптечки.
#### Как повторить
Использовать любой шахтерский шелтер на астероиде.

**Comment by Tap0r** [comment]
Это третий сервак?

**Comment by Mercurialaste** [comment]
Насчет этого бага. Из того что было замечено мной, шелтер можно с некоторыми поправками открыть будучи на тайле космоса. Но как только ты пытаешься открыть его на астероиде, вместо этого падает костюм. 
_(И нет, камни астероида не мешают открытию шелтера, помешать могут только каких-либо строения, по типу стен или стекол.)_
