### ISSUE TITLE
Кепка теряет спрайт

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#8995]
#### Подробное описание проблемы
При нажатие Flip cap спрайт исчезает
![image](https://user-images.githubusercontent.com/26389417/160705171-ccabaa38-aa1c-4bcf-a645-0b25ae768444.png)

#### Что должно было произойти
Кепка флипнулась

#### Что произошло на самом деле
Кепка потеряла спрайт, в том числе и на голове

#### Как повторить
Взять кепку (тестил на /obj/item/clothing/head/soft). Пкм -> флип кеп

**Comment by Mercurialaste** [comment]
О... А если на неё использовать хамельёнку...
