### ISSUE TITLE
[Proposal] Уменьшить шанс выпадения хеиста

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#8997]
#### Подробное описание проблемы
Сейчас ситуация такова, то хеист падает чересчур часто. Один из самых наших худших режимов в данный момент выпадет намного чаще, чем ЧЕНДЖЛИНГИ!! Хотя че там, че там примерно одинаково надо людей.

![image](https://user-images.githubusercontent.com/26389417/160780024-a02bc7e9-26d1-4b6b-8e12-582906709f60.png)

Хеист даже в топе на втором сервере!
![image](https://user-images.githubusercontent.com/26389417/160780105-0b51f14c-af85-4032-8890-1752ce04fe27.png)

Пофакту, все что нужно сделать - изменить пробалити в коде.
https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/game/gamemodes/modes_declares/heist.dm

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/9010
