### ISSUE TITLE
Гост катается по конвейеру

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#9002]
#### Подробное описание проблемы
Гост катается по конвейеру хотя не должен.
#### Что должно было произойти
Гост стоит на месте.
#### Что произошло на самом деле
Гост едет.
#### Как повторить
Встать на активный конвейер за госта.

**Comment by Akellazp** [comment]
фича

**Comment by Fluffy-510** [comment]
Больше не актуально

https://github.com/TauCetiStation/TauCetiClassic/assets/109436132/a7a0330d-38b6-4832-ae6f-4e99afcf7f1c
