### ISSUE TITLE
Призраки не могут крутить стулья

### ISSUE THREAD

**Issue by MrFoxik** [TauCetiStation/TauCetiClassic#9006]
#### Подробное описание проблемы
Одним весенним днём я встал с кровати, и решил зайти на Тау Сети. Нарисовал гигантскую доску Уиджи, поставил стулья и понял что оказывается какой-то негодяй отключил кручение стульев. ЧТО?
#### Что должно было произойти
Стулья должны весело крутиться, обливаясь эктоплазмой.
#### Что произошло на самом деле
Стулья не только не крутятся, они ещё и эктоплазмой не обливаются.
#### Как повторить
НЕ КРУТИТЬ СТУЛ ЗА ПРИЗРАКА.
#### Дополнительная информация:
Верните кручение стульев.

**Comment by KIBORG04** [comment]
Не смешно
