### ISSUE TITLE
Эктоплазма из фотографий с призраками.

### ISSUE THREAD

**Issue by MrFoxik** [TauCetiStation/TauCetiClassic#9007]
#### Подробное описание проблемы
Либо сломано, либо шанс чрезвычайно мал, но выбить эктоплазму из сожженной фотографии с призраком практически (?) невозможно.
#### Что должно было произойти
При сожжении фото с призраком с каким-то более реальным шансом из него должна выпасть эктоплазма.
#### Что произошло на самом деле
Ничего.
#### Как повторить
Сфотографировать призраков, и потом сжечь все эти фото получив ничего.
#### Дополнительная информация:
Я не уверен конечно что оно сломано, но скорее всего оно сломано!

**Comment by KIBORG04** [comment]
Не пиши на гитхаб информацию, которую не знаешь
