### ISSUE TITLE
Сброс прогрессбара на борге

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#9015]
#### Подробное описание проблемы
Скажите пожалуйста это прекол или реальнасть.
Борг копает буром без прогрессбара, не тратит заряд и ещё подиагонали раскапывает по три тайла сразу.
#### Что должно было произойти
Всё по-старому
#### Что произошло на самом деле
![Баг 2](https://user-images.githubusercontent.com/96499407/161258547-d9781204-2183-4078-af2d-50b825fd107e.png)
17к очков 15-я минута.
#### Как повторить
Зайти за шахтоборга, заставить шахтёров-хуманов плакать

**Comment by LoTaRk-FroG** [comment]
Это типо бафф от макс скилла, как я понял.

**Comment by Mercurialaste** [comment]
> #### Подробное описание проблемы
> Скажите пожалуйста это прекол или реальнасть. Борг копает буром без прогрессбара, не тратит заряд и ещё подиагонали раскапывает по три тайла сразу.
> 
> #### Что должно было произойти
> Всё по-старому
> 
> #### Что произошло на самом деле
> ![Баг 2](https://user-images.githubusercontent.com/96499407/161258547-d9781204-2183-4078-af2d-50b825fd107e.png) 17к очков 15-я минута.
> 
> #### Как повторить
> Зайти за шахтоборга, заставить шахтёров-хуманов плакать
> 
> #### Дополнительная информация:

17 очков - не показатель, плохо стараешься.

**Comment by Deahaka** [comment]
Борг за 5-10 минут игры в шахту выкапывает 3 Дюранда и Гигакса, норм.

**Comment by Mercurialaste** [comment]
> Борг за 5-10 минут игры в шахту выкапывает 3 Дюранда и Гигакса, норм.

Было и до скилов. Никто особо не жаловался почему-то.
