### ISSUE TITLE
[Proposal] Добавить всем боргам флешеры

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#9017]
#### Подробное описание проблемы
Из-за отсутствия оружия самообороны борги юзают подручные дрели, бензопилы и яды, в случае если на них нападают. С флешером не будет "самообороны с вмятинами коленей в другую сторону обидчику". И вообще разве это должно быть не единственным оружием борга против членов экипажа?

**Comment by Zickusable** [comment]
#7435

**Comment by Deahaka** [comment]
А мог бы отдельным ПРом давно замержить, ну ничего
