### ISSUE TITLE
Спрайты маленького роста зашакалены.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#902]
#### Подробное описание проблемы
Спрайты маленького роста из генетики выглядят отвратительно на гуманоеде. 
#### Что должно было произойти
Верните старые спрайты
#### Что произошло на самом деле
Эти спрайти слишком шакалистые
#### Как повторить
Получить способность маленького роста
#### Дополнительная информация:
![default](https://cloud.githubusercontent.com/assets/18488106/21307696/5caae710-c5df-11e6-8c09-5f3b08212c86.png)

**Comment by sovok4** [comment]
Они же всегда были зашакалены.

**Comment by Skippeer12** [comment]
Не до такой степини же

**Comment by Leshiy-ART** [comment]
Там как бы деформация спрайта бъендом, и на сколько я знаю - это никак не пофиксить (других способов деформации нет)

**Comment by Dennok** [comment]
Егож вроде никто не трогал. А раньше двже этого не было.

**Comment by SpaiR** [comment]
Спрайт изменяется механом бьёнда, у нас тут доступа нету.
