### ISSUE TITLE
Воруем интеркомы.

### ISSUE THREAD

**Issue by NinjaPikachuska** [TauCetiStation/TauCetiClassic#9024]
#### Подробное описание проблемы
Интерком можно подвинуть, перетягивая его на какой-нибудь стол.
#### Что должно было произойти
Интерком не двигается.
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/89906909/161327924-61dd3c40-228c-4153-8c82-5ca8535fb2d3.png)
#### Как повторить
Перетянуть интерком на стол.
#### Дополнительная информация:
Смешной баг.

**Comment by LudwigVonChesterfield** [comment]
datum/component/clickplace проблема. видимо не проверяет на anchored

**Comment by DarkFurrSss** [comment]
Вспомнили спустя год
