### ISSUE TITLE
Список всех смешных багов 2022 года

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#9025]
#### Подробное описание проблемы
1. Человек с ПДА был всегда скользким, даже когда стоял. https://github.com/TauCetiStation/TauCetiClassic/pull/8581 https://github.com/TauCetiStation/TauCetiClassic/pull/8597
2. Шаттл на новый год улетал медленно по частям, тайл за тайлом. Ишуй или найду щас.
3. Зарплата каждые 30 секунд [`6a6d8b6` (#9266)](https://github.com/TauCetiStation/TauCetiClassic/pull/9266/commits/6a6d8b68e99f762ca0f79e060fa774f66ca37597)
4. Мартышки дышали в вентиляции и делали миллардное давление и температуру. Хз где ишуй или пр
5. https://github.com/TauCetiStation/TauCetiClassic/issues/10056

**Comment by AndroBetel** [comment]
при осмотре голого чела призраком ему дебафф к муду накладывался, смешно?

**Comment by KIBORG04** [comment]
м, ну как сказать.. Не совсем заметно.

**Comment by KIBORG04** [comment]
В 21, вроде, году госты могли вешать на всех арест

**Comment by DarthSidiousPalpatine** [comment]
Можно записать всю мою историю ПРа с сердечком в смешной баг?)

**Comment by KIBORG04** [comment]
Это не смешно

**Comment by LudwigVonChesterfield** [comment]
@Akellazp это же не в 2022-ом было

если говорить про смешные абузы, то комбухи позволяли выполняя апперкот и взяв мыш в карман - попасть в карман мобу

**Comment by simb11** [comment]
Инвалиды стрит рейсеры АКА #10056

**Comment by Deahaka** [comment]
Добавьте на первое апреля не забудьте https://github.com/TauCetiStation/TauCetiClassic/pull/10405

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/vspominaem-sobytiya-uhodyashhego-goda-i-vse-ostalnoe/37099/5

**Comment by KIBORG04** [comment]
2022 год кончился. Слишком мало багов.
