### ISSUE TITLE
На ящурах, таярах не отображается спрайт броника.

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#9030]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/19796920/161377060-022b093b-d54e-498d-8ff8-6fe1ffe02298.png)

#### Что должно было произойти
Должен быть спрайт на кукле, а его нету.

**Comment by LudwigVonChesterfield** [comment]
![image](https://user-images.githubusercontent.com/17705613/161382317-95e1e3c8-3704-4299-89c5-8b284d7e0576.png)

Слева те на ком отображается, справа те на ком нет.

**Comment by LudwigVonChesterfield** [comment]
на таярах, унатхах не отображается вообще ничего надетое в слот брони. ни броники, ни халаты.

**Comment by LudwigVonChesterfield** [comment]
У унатхов и Таяр почему-то свои спрайтщиты для костюмов, и в них у спрайтов не нужные названия.

**Comment by LudwigVonChesterfield** [comment]
#8916 сломал

раньше если для таяр/унатхов не находило спрайта в их спрайтщите - использовало дефолтный спрайт (как оказывается для большинства вещей так и делало)

после того ПР-а если раса объявила свой спрайтщит, нужно все спрайты в него закинуть, сейчас это не так.

тому кто захочет это решать, предстоит выбор. вернуть как было и дальше каждый раз когда кто-то надевает одежду проверять наличие икон_стейта в тысяче картинок

или перекинуть все хуманспрайты в спрайтщит таяр и унатхов

**Comment by WatlerJe** [comment]
Учитывая то, что действительно меняющийся спрайт под расу это скафандры, то можно вывести конкретно их в отдельную группу и ссылаться на эту группу когда персонаж ящур/кiт надевается конкретно скафандр (или любой другой похожий по принципу костюм), ну а остальным сьютам просто ссылаться на хуманские.

Но если создавать для Тояр и Унатхов свой suit.dmi который будет копией хуманского, то каждый раз когда надо будет добавить новый сьют, придется добавлять в каждый из этих файлов.
