### ISSUE TITLE
Если прибыть жирным все вещи на костюме пропадают вникуда

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#9035]
#### Подробное описание проблемы

вещи которые носятся на униформе (карта, пояс(ПДА), карманы) пропадают если пропала униформа при спавне если ты жирный

#### Что должно было произойти

вещи складываются в пакет/выдаётся альтернативная форма

#### Что произошло на самом деле

вещи пропали

#### Как повторить

1. выбрать Kung Jeans
2. выбрать квирк на Полноту
3. Зайти в игру
4. Убедиться что пропали: ПДА, карта, что-либо что спавнится в карманах (как наручники у СБ)

#### Дополнительная информация:

![image](https://user-images.githubusercontent.com/17705613/161384570-732cceb8-2ad3-4a99-9232-392c13bf9f57.png)

**Comment by AndroBetel** [comment]
у нас везде equip_to_slot_or_del, надо заменить на equip_to_slot_or_collect
