### ISSUE TITLE
Не раундстарт борги не обладают скилами

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#9036]
#### Подробное описание проблемы
Не раундстарт борги не обладают скилами и делают все также как и тестовики.
#### Что должно было произойти
Скилы есть
#### Что произошло на самом деле
Скилов нет
#### Как повторить
Зайти в борга через позитронку.

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/skilly-na-tau-opyat/31475/431
