### ISSUE TITLE
Skill issue у големов

### ISSUE THREAD

**Issue by DanKOisTaken** [TauCetiStation/TauCetiClassic#9042]
#### Подробное описание проблемы
При заходе за голема есть только нулевой melee скилл. 
#### Что должно было произойти
`Они не помнят о своих предыдущих жизнях, но имеют **огромные знания**.` - вырезка с вики.
#### Что произошло на самом деле
Големы хуже ассистух.
#### Как повторить
Зайти за голема

**Comment by LudwigVonChesterfield** [comment]
наконец-то нерф големов который мы все ждали

**Comment by LudwigVonChesterfield** [comment]
#8845
