### ISSUE TITLE
Кодовые фразы не подсвечиваются

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#9045]
#### Подробное описание проблемы
Кодовые фразы и ответы не подсвечиваются цветом в чате.
#### Что должно было произойти
Слова имеют собственный цвет
#### Что произошло на самом деле
Слова чёрные. Произошёл реверт? Я что-то проспал?!?
#### Как повторить
Попробовать это за трейтора на песочнице, а позднее и в игре
#### Дополнительная информация:
Issue reported from Tau Ceti Classic Sandbox
Testmerges: ```#8868 #8845 ```
Reporting client version: 514.1582

**Comment by LudwigVonChesterfield** [comment]
> Testmerges: #8868 #8845

> #8868
