### ISSUE TITLE
Skill issue у дронов всех типов.

### ISSUE THREAD

**Issue by Ro2tCrab** [TauCetiStation/TauCetiClassic#9058]
#### Подробное описание проблемы
Управляемый дрон синдиката и обычный дрон имеют проблемы со скилами.
#### Что должно было произойти
Проклятые роботы умеют всё делать.
#### Что произошло на самом деле
Машина созданная для ремонта/саботажа станции не может понять как использовать инструменты.
#### Как повторить
Очевидно.
#### Дополнительная информация:
-

**Comment by LudwigVonChesterfield** [comment]
#8845
