### ISSUE TITLE
Имбовая резина, или плиз нёрф ит

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#906]
#### Подробное описание проблемы
Резиновые пули (rubber) дико имбовы - вгоняют в голокрит с двух-трёх попаданий в РИГе. При этом не реагируют на щиты, что убивает всю контру
#### Что должно было произойти
Урон хотя бы уровня электродов. Возможность заблокировать выстрел щитом.
#### Что произошло на самом деле
Щиты не блокируют пули от слова совсем, РИГи и бронежилеты чуть чуть, но не существенно
#### Как повторить
Взять в арсенале для охранников нелетал и пойти выносить нюку
#### Дополнительная информация:
N/A

**Comment by Skippeer12** [comment]
Булетпруфы спасают от резины довольно таки хорошо. РИГи по меньше, но для нюки и пиратов это не проблема, у них есть боевые аптечки, а в них есть обезбаливающее.
Это скорее нерф в сторону нюко/пиратов. А нюко/пираты должны страдать и плакать, потому как заебали выносить оружейку и спавнится при одном офицере.
Потому как против персонала всё ещё работает тазер довольно таки хорошо.

**Comment by Belfogor** [comment]
Потестил в тепличных условиях. Стрелял по куклам в ригах ЕРТ из 9мм пистолета, соответственно резиновыми и боевыми. Чтобы свалить куклу стреляя боевыми понадобилось 12 попаданий, для резины же всего три. Проблема в том, что для резиновых пуль создали новый тип урона "agony", но никто не удосужился создать защиту от этого типа урона. Так что резиновой пули плевать во что вы одеты.

**Comment by Belfogor** [comment]
Я пристально изучил и код и понял, что нихуя не понял. Суть в том, что "agony" наносит совершенно любое оружие Н/Д. (батоны, резиновые пули, тайзеры), но почему-то лишь эффект от тайзера ослабевает в зависимости от брони. В любом случае это скорее баг ну или по крайней мере требует пересмотра.

**Comment by skvazarb** [comment]
Тазер ослабевает не от брони, а от специального коэффициента
https://github.com/TauCetiStation/TauCetiClassic/blob/0f6e6cadcac3ac36a19acb0a71c1cec076bc9efa/code/modules/mob/living/carbon/human/human_defense.dm#L35

**Comment by igigin** [comment]
Нерфить то это никто и не хочет. Это же баф хуманов, такие не нужны.

**Comment by WallShrabnic** [comment]
Закрывать?

**Comment by Kurshan** [comment]
Её неплохо так понерфили, так что пропозал даже успешен.

**Comment by WallShrabnic** [comment]
Ок 
https://youtu.be/qTa9Jn37hYM
