### ISSUE TITLE
Абуз особки "War Face"

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#9063]
#### Подробное описание проблемы
При помощи особки "War Face" игроки бесконечно спамят эмоут *scream
#### Что должно было произойти
Все существа мира не могут так долго орать.
#### Что произошло на самом деле
Они надрывают горло, нарушают атмосферу игры и взрывают барабанные перепонки нормальных игроков
#### Как повторить
Здесь описывать абуз я не буду, если нужны подробности - дискорд открыт
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/24526545/161801307-27c15e30-4639-4bac-99bb-ba193930cfde.png)

**Comment by GermanSUS** [comment]
Так и без особки можно орать

**Comment by KIBORG04** [comment]
Как

**Comment by GermanSUS** [comment]
Просто скрим прописываешь и много орёшь. А у Вар Фэйса особый крик штоли?
