### ISSUE TITLE
Абдукторы получают прическу и бороду из лоадаута

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#9068]
#### Что должно было произойти

хз лично мне нрав, но раньше так не было

#### Что произошло на самом деле

![Uploading image.png…]()

#### Как повторить

1. выбрать аниме волосы розовые
2. стать похитителем
3. угар

#### Дополнительная информация:
#8972 

можно пофиксить сбрасывая абдукам прическу, но я не стану.

**Comment by volas** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/9583
