### ISSUE TITLE
У офицеров нет доступ к шлюзам ведущим в космос.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#907]
#### Подробное описание проблемы
Офицеры опять без доступа в шлюзовую систему, чтобы выйти в космос и начать творить правосудие там. А ведь Куршан сказал что зафиксил это.
#### Что должно было произойти
Офицеры должны иметь доступ к шлюзам ведущим в космос.
#### Что произошло на самом деле
Access Denied
#### Как повторить
Попытатся нажать на кнопку чтобы запустить процедуру шлюзовой системы.
#### Дополнительная информация:
Шлюз который находится возле криминалиста работает не корректно. Внешняя дверь шлюза не имеет питания, из-за чего открывается только ломом, кто-то намудрил с зонами, опять.

**Comment by Balphagore** [comment]
По-моему, шлюз рядом с криминалистом - это фича для легкого доступа на станцию. Обесточенный, но в космос выходит провод под напряжением, а рядом всегда лежит ящик с инструментами, в котором есть лом. Излюбленное место захода нинж без взрывов, резгерм и траты энергии. А вот остальные шлюзы - это да. Офицеры щас могут выйти в космос только через тот же шлюз криминалиста, у всех остальных требуется карта инженера. Когда делали ремап брига - можно было нарисовать там шлюз для охраны, кстати

**Comment by Skippeer12** [comment]
Доступ к шлюзам у офицеров есть только в доках на этом простовый выход в космос заканчивается.

**Comment by Balphagore** [comment]
Доступ к шлюзам в доках есть даже у нюкеров, так как он там вообще отсутствует. Из шлюзов же, на которых доступ выставлен им доступен только шлюз криминалиста, так как он обесточен и в нем вообще нет системы откачки/закачки воздуха, по идее он просто не достроен, так как провод под напряжением через него выходит прямо в космос. Так что это, по-ходу фича, а вот на остальные шлюзы техтоннелей неплохо бы добавить доступ офицерам. А по хорошему еще и парамедику, раз ему дали доступ в техи. У шлюзов в техах обычно нет камер ИИ, так что парамедику надо либо переться от ЕВА в доки, а уже от них облетать всю станцию, либо тащить с собой борга.
