### ISSUE TITLE
Выпилить кнопку LEAP, заменив на бросок пустой рукой

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#9074]
#### Подробное описание проблемы

Возможно немного неинтуитивное взаимодействие, но:

- Кнопка броска есть даже когда рука пустая, значит должна что-то и в этом состоянии делать (имхо)
- Уберёт огромную кнопку закрывающую интерфейс крафта у Воксов.

**Comment by Deahaka** [comment]
Её же можно выключить в префах (f12) вроде

**Comment by GermanSUS** [comment]
Ща придёт акелла и скажет просто выпилить лип

**Comment by Mercurialaste** [comment]
Если кнопка броска включена, она разве не позволяет поймать летящий в тебя предмет?
 _(Где-то вроде это упоминалось, но не припомню чтобы доводилось подобное использовать.)_

**Comment by LudwigVonChesterfield** [comment]
сможешь проверять или вокс агрессивен бросив в него предмет. звучит как топ фича. ты бросил - если он "на готове" то схватит)

**Comment by 4310V343k** [comment]
https://www.youtube.com/watch?v=mmEEDa2tcdU

**Comment by Akellazp** [comment]
предлагаю просто выпилить воксов
а если вас такое решение не устраивает то выпиливаем лип
