### ISSUE TITLE
Слиппер выводит сообщение, когда в него пытаются положить прикованного пациента

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#908]
#### Подробное описание проблемы
Если тебя, будучи прикованного к чему-то, попытаются засунуть в слиппер, выйдет следующее сообщение:
![image](https://cloud.githubusercontent.com/assets/21046015/21356848/e6ac5c1c-c6f4-11e6-9c0f-0850b110ea20.png)
#### Что должно было произойти
Сообщение не должно было появиться.
#### Что произошло на самом деле
Сообщение появилось.
#### Как повторить
Быть доктором, закинуть пациента в слиппер, когда он прикован к чему-то.

**Comment by StrikS** [comment]
Приорити критикал!

**Comment by Dennok** [comment]
Лол былбы еслиб его таки туда всунули.
