### ISSUE TITLE
[Proposal] Объединить куклу боли и выбор конечности

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#9080]
#### Подробное описание проблемы

![image](https://user-images.githubusercontent.com/17705613/162176665-0e641cef-3b91-44e9-bc6f-795147618c32.png)

![image](https://user-images.githubusercontent.com/17705613/162176681-90fc4f91-5f9a-41ca-a9b7-e7e92c266b32.png)

Узнали? Согласны?

Предлагаю отображать боль на кукле выбора куда бить.

**Comment by Bullethole** [comment]
не узнали, не согласны, кринж

**Comment by Akellazp** [comment]
не узнали, не согласны

**Comment by Zickusable** [comment]
Красный селект будет искажать цвет степени повреждения куклы

**Comment by pss88** [comment]
Они разные по смыслу. Одна изображает тебя, другая твоего противника.

**Comment by LudwigVonChesterfield** [comment]
Ладно, это спорная выходит шизоидея. Новая шизоидея это сделать по слоту на каждую часть тела, и ПКМ по слоту выбирает его как цель ударов
