### ISSUE TITLE
Совместный перенос персонажей по леерам.

### ISSUE THREAD

**Issue by SourcePony** [TauCetiStation/TauCetiClassic#909]
#### Подробное описание проблемы

Запуленый персонаж не перенеся на другой леер вместе с тем, который его пулил.

#### Что должно было произойти

Персонажи должны были переместится на один леер.

#### Что произошло на самом деле

Персонажи оказались на разных леерах.

#### Как повторить

Запулить персонажа, долететь до точки телепортации вместе с ним.

#### Дополнительная информация:

Было обидно, что я помирал один, а не вместе с человеком, которого пулил.

**Comment by Skippeer12** [comment]
Рандомный рандом, который сделали ещё больше рандомным, чтобы нельзя было лутать дереликт в два рыла.
P.S. Юзайте ящики.
P.S.S. Не баг а фича.
