### ISSUE TITLE
Офицер бипски и возможно ЕD-209 работают не корректно.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#910]
#### Подробное описание проблемы
Офицер бипски патрулирует только часть от мостика к бригу. 
#### Что должно было произойти
Офицер бипски должен патрулировать всю станцию целиком (исключая тех.тоннели)
#### Что произошло на самом деле
Он этого не делает
#### Как повторить
Наблюдать за офицером бипски.
#### Дополнительная информация:
И он всегда спавнится один, раньше их было от двух до трех штук на станции.

**Comment by WallShrabnic** [comment]
Бипски вообще часто (был) сломан - не двигался а сидел около брига и при попытке направитьь на маршрут тут же его закачивал. Ну Бипски всегда был один жеж, это роботехники старались

**Comment by sir-duck** [comment]
ED-209 патрулирует нормально, или такая же трабла?

**Comment by ZVee** [comment]
Пинайте Куогото такого, кто маяки с карты посносил. Они такие маленькие, прозрачные и в стелсе!
![dasr32fdsdsf](https://cloud.githubusercontent.com/assets/8426718/21694600/bba280a4-d38e-11e6-8d0f-72deaa1e259f.png)

А если серьезно - поглядев только что, куда ездит бипски, в голову внезапно упала мысль про маяки, так что возможно дело как раз в карте.

**Comment by Skippeer12** [comment]
@Kurshan не грифонь! А лучше пофикси.

**Comment by Damirrus1** [comment]
![image](https://cloud.githubusercontent.com/assets/21046015/21872218/0d6563a8-d889-11e6-8bdf-57ed8f895b99.png)
До, впиред!
