### ISSUE TITLE
Если перевернуть покрашенною кепку, то она потеряет свой цвет.

### ISSUE THREAD

**Issue by RONSI7** [TauCetiStation/TauCetiClassic#9109]
#### Подробное описание проблемы
Покрашенные в стиральной машине кепки теряют свой цвет, если их перевернуть.
#### Что должно было произойти
Кепка переворачивается и остается зеленой/красной/оранжевой/дальше по списку.
#### Что произошло на самом деле
Кепка перевернулась и стала серой.
#### Как повторить
Взять покрашенною кепку в руки, нажать горячую клавишу действия.
#### Дополнительная информация:
Данный баг не наблюдается на оранжевых кепках из брига.

**Comment by LudwigVonChesterfield** [comment]
смахиваешь краску переворотом. 😂

**Comment by KIBORG04** [comment]
В карго кепки вообще по дефолту розово белый квадрат
