### ISSUE TITLE
Соломалось окошко known languages

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#911]
#### Подробное описание проблемы
Вместо букв для языков оно показывает Sol Common (:/list)
#### Что должно было произойти
Оно должно отображать буквы корректно.
#### Что произошло на самом деле
Кто-то его сломал (игигил же)
#### Как повторить
Зайти во вкладку IC-> Check Known Languages
#### Дополнительная информация:
![555](https://cloud.githubusercontent.com/assets/18488106/21368591/e0c396b4-c70b-11e6-8343-0fd732818eb0.png)

**Comment by igigin** [comment]
Eto tak, я сломал.
