### ISSUE TITLE
Cargo cap не имеет спрайта

### ISSUE THREAD

**Issue by RONSI7** [TauCetiStation/TauCetiClassic#9111]
#### Подробное описание проблемы
Сargo cap, что лежат в шкафчиках карго, для грузчиков, не имеют спрайта.
#### Что должно было произойти
Сargo cap, имеет спрайт кепки.
#### Что произошло на самом деле
Cargo cap не имеют спрайта.
#### Как повторить
Зайти на I-II сервер в карго, не обнаружить спрайта у cargo cap.

**Comment by KIBORG04** [comment]
Ето правда
