### ISSUE TITLE
[Proposal] Реагент "метатромбин" для остановки крови

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#9112]
#### Подробное описание проблемы

Реагент, широкодоступный, позволяющий временно остановить любую кровопотерю, скажем, кровь мгновенно сворачивается при контакте с большим количеством воздуха вне тела куклы, но без тромбоза.

Как только реагент выходит из тела - кровопотеря продолжается, то есть можно к примеру выжить с артериалкой, если постоянно колоть метатромбин.

https://github.com/TauCetiStation/TauCetiClassic/pull/3655
https://github.com/TauCetiStation/TauCetiClassic/pull/4073

Пожалуйста, учтите мои ошибки и сделайте как надо.

**Comment by Mercurialaste** [comment]
Раз он общедоступный, что на счет сделать его частью экстренной коробки? Которая идет раундстартом. Тоже автоинжектор на 5 или более унций.
