### ISSUE TITLE
Black hard-worn suit детектива неправильно отображается на кукле

### ISSUE THREAD

**Issue by Blamburg** [TauCetiStation/TauCetiClassic#9116]
#### Подробное описание проблемы
Black hard-worn suit детектива при надевании отображается как white hard-worn suit with brown pants. В руках нормально, на теле - другой костюм.
#### Что должно было произойти
Black hard worn suit выглядит как положено
#### Что произошло на самом деле
Black hard-worn suit выглядит как white hard-worn suit with brown pants
#### Как повторить
Надеть Black hard-worn suit из нуаромата детектива

**Comment by INwirstD** [comment]
Уже фикс есть - https://github.com/TauCetiStation/TauCetiClassic/pull/9108#issue-1199840521
