### ISSUE TITLE
Жир не должен убирать хардсьюиты

### ISSUE THREAD

**Issue by IlinMihail** [TauCetiStation/TauCetiClassic#9119]
#### Подробное описание проблемы
Жирок от переедания убирает любые экзосьюиты, включая скафандры. Приводит это к тому что можно сдохнуть в космосе от одного лишнего дошика, что довольно обидно и нереалистично.

#### Что должно было произойти
Жир не убирает хардсьюит.

#### Что произошло на самом деле
Жир убирает хардсьюит.

#### Как повторить
Сожрать пару дошиков.

**Comment by AndroBetel** [comment]
фича

**Comment by IlinMihail** [comment]
Жёсткая фича

**Comment by IlinMihail** [comment]
За какого нить нюкера сдохнуть в космосе если вколол себе слишком много нутримент инжекторов - такое себе

**Comment by WatlerJe** [comment]
Нужны спрайты жирных сьютов.

**Comment by Gort133** [comment]
Как член саббаланс депа заявляю что это фани и это фича

**Comment by IlinMihail** [comment]
Ну тогда закрываю
