### ISSUE TITLE
Артефакты которые убивают новоприбывших ксеноархеологов.

### ISSUE THREAD

**Issue by Skippeer12** [TauCetiStation/TauCetiClassic#912]
#### Подробное описание проблемы
Артефакты которые стоят с начала смены в изоляционных помещения могут убить или нанести значительный вред персоналу который прилетает на шаттле или подходит вблиз научного астероида. А единственая защита это противо аномальные костюмы, которые лежат прям перед входом в изоляционные блоки в которых находится тот артефакт-убийца.
#### Что должно было произойти
Ксеноархеологи должны получить комплект костюмов для защиты от излучений или даже собственный отсек на станции для переодеваний и приготовлений для исследования в научном комплексе на астероиде.
#### Что произошло на самом деле
![51](https://cloud.githubusercontent.com/assets/18488106/21371425/021e0e08-c71a-11e6-8826-b237ea02aa1c.png)
У ксеноархеологов нет защиты против излучений и телепортаций или ещё как дряни, которую излучают артефакты, чтобы получить эту защиту им либо нужно воровать у ученых костюм из лаборатории теленаук, либо страдать и плакать.
#### Как повторить
Зайти за профессию ксеноархеолога и пойти на астероид.

**Comment by Dennok** [comment]
99.9% не используют скафандры, но да, можно вообще былобы перемапить. и вынести переодевалку к выходу.

**Comment by Skippeer12** [comment]
Так проблема в том, что при прилете на аванпост, тебя с шаттла начинает шатать артифактом и ты уже ничего не можешь сделать.
Стот упомянуть, что есть разные типы артифактов и вот этому чловеку на скриншоте не повезло очень сильно.
Есть менее слабые артефакты, меняющие ДНК или дающее слип.
Но от всего этого есть одна защита и она находится перед комнатой с артефактами, до который ты скорее всего не доберешься, потому что тебя оприходует на шаттле.
![5556](https://cloud.githubusercontent.com/assets/18488106/21371851/468767ea-c71c-11e6-8ae1-125f2e0025fc.png)

**Comment by Zmey25** [comment]
Пользуются костюмами все, кто мозги имеет. Я вот только что не добежал до костюма, меняло днк и довело до госта примерно за минуту.

Можно просто сократить количество артефактов до одного. Их не сложно выкопать.

**Comment by sovok4** [comment]
Если бы шаттлы РнД и шахты снова были разделены, то намапить предбанник с этими костюмами было бы просто, а так я даже не знаю, куда это запихнуть.

**Comment by Skippeer12** [comment]
@sovok4 У меня есть идея и сейчас сделаю по быстрому, но маппить я это не буду

**Comment by Skippeer12** [comment]
Вообщем предложил такую вот концепцию.
![default](https://cloud.githubusercontent.com/assets/18488106/21429688/aaa70116-c868-11e6-9d56-a3120257301e.png)

Ну и это место надо было чем-то закрыть.
![default](https://cloud.githubusercontent.com/assets/18488106/21429703/b63b7688-c868-11e6-8902-954bd5976793.png)

Сказали что анарно и так далее и тому подобное. Так что наверное прийдется нерфить таки аномалии.

**Comment by Nerevrin** [comment]
Щитол будет сносить стену улетая же.

**Comment by Skippeer12** [comment]
С чего бы это же?

**Comment by Nerevrin** [comment]
Я не про механ же. Ты представлял, как он вылетать должен?

**Comment by Raschert0** [comment]
Не вижу ничего необычного. Шаттл отлетает в сторону (да, это космос и у шаттла есть маневровые двигатели)

**Comment by Dennok** [comment]
Если вы не знали, шаттлы вообще в верх /низ летают.

**Comment by Dennok** [comment]
Через потолок.
