### ISSUE TITLE
Шлемы ЕРТ красятся сами по себе

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#9121]
#### Подробное описание проблемы
Шлем ОБР у тех, кто вставлял в риг, потом снимал через ПКМ и одевал снова красился в жёлтый цвет
#### Что должно было произойти
Спрайт не меняется
#### Что произошло на самом деле
Красный шлем стал жёлтым
#### Как повторить
вставить шлем в риг и попытаться его снять/одеть

**Comment by LudwigVonChesterfield** [comment]
#9120
