### ISSUE TITLE
Выпилить пульс

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#9125]
#### Подробное описание проблемы

Его никто не юзает

про его фичи никто не знает

те что есть не глубокие

Юзать нет зачем, когда все в медбее находятся в двух шагах от слипера который выполняет работу "пульса" в тысячу раз лучше
при кустарном лечении пульс не даёт полезной информации

верб "Check Pulse" переделать на индикатор того что кукла умерла, и всё.

**Comment by kiVts** [comment]
Так уже же можно понять разве нет?

**Comment by LudwigVonChesterfield** [comment]
на пульсе как оказалось завязан смешной эффект сердцебиения что наверное довольно атмосферно короче пускай чинят баги пульса а сам пульс пускай пока остаётся
