### ISSUE TITLE
[Proposal] Выпилить возможность вставлять предметы в вендоматы

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#9139]
1. Абузы.
2. """По лору""": только авторизированные Карго Индастриз Рефиллмент Картрижды могут пополнять ассортимент, иначе всякие каргонцы же туда напихают бомб!

Предлагаю просто выпилить возможность вставлять вещи из ассортимента вендомата в вендомат.

**Comment by Bullethole** [comment]
давай сука, выпиливай всё что можно, ограничивай возможности станции и своди всё к еще более унылому и без того геймплею, ты ж кодер, закодь новую профу под шумок умений и пусть вставление катриджей в вендоматы будет зависить от навыка определенной роли
да и какой там абуз?

**Comment by AndroBetel** [comment]
>
![image](https://user-images.githubusercontent.com/44546836/163245498-aa7d36a3-2551-4259-ba7e-94bafed6862e.png)
