### ISSUE TITLE
Таяры могут носить магбутсы

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9145]
#### Подробное описание проблемы
Таяры могут носить магбутсы
#### Что должно было произойти
Не могут
#### Что произошло на самом деле
Могут
#### Как повторить
Надеть магбутсы будучи таяраном
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/84613249/163376722-af17d49a-d6bb-4b3c-abb5-f332bedb9e30.png)

**Comment by Bullethole** [comment]
любой хуман может надеть бутсы, нет ограничения по этой теме
Хуй знает как это работает но это работает

**Comment by WatlerJe** [comment]
Не баг, а фича.
