### ISSUE TITLE
Поменяйте книжный сканер на копировальную машинку в медбеевском ресепшене

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#9149]
#### Подробное описание проблемы
Книжный сканер для компутера библиотекаря
#### Что должно было произойти
Копировальная машинка вжух вжух 100 форм на рецепты
#### Что произошло на самом деле
Амогус
#### Как повторить
Сидеть в ресепшене и играть в бумажки
#### Дополнительная информация:
Issue reported from  Round ID: 50481 (Tau Ceti Classic II (RU))
Testmerges: ```#8868 #9132 #8911 #8980 #9106 #9122 ```
Reporting client version: 514.1582

**Comment by Gort133** [comment]
Нееет, випо, зачем??!??? Ааааааа
