### ISSUE TITLE
При использовании станбатона на харме сообщение об ударе троируется.

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#915]
#### Подробное описание проблемы
Сообщение об ударе хармбатоном троируется.
#### Что должно было произойти
Должно появиться только одно сообщение об ударе.
#### Что произошло на самом деле
Появилось три сообщения об ударе.
#### Как повторить
Взять станбатон, ударить им кого-то на харме.
#### Дополнительная информация:
![image](https://cloud.githubusercontent.com/assets/20542000/21399439/cb4a2332-c7d5-11e6-9d05-b49ea47fcb5d.png)

**Comment by Skippeer12** [comment]
Так это три разных сообщения о одном действии
:itsok:

**Comment by YulianR** [comment]
Последнее писаться не должно, ибо тут без разницы включен он или нет, ведь нанесен сильный удар на харме. Первые два тоже можно в один соединить

**Comment by igigin** [comment]
Первое - стандартное сообщение об ударе любым предметом любую цель,
Второе - сообщение именно о харм интенте,
Третье - станбатон отключен/разрядился.

Каждое сообщает о разном, но логи они засоряют только так, это да.

**Comment by Dennok** [comment]
Вроде было что удар по мишам был двойным, но это ктото фиксил.

**Comment by Skippeer12** [comment]
Не фиксил

**Comment by igigin** [comment]
#1385
