### ISSUE TITLE
Неправильное сообщение при отковыривании плиток

### ISSUE THREAD

**Issue by IlinMihail** [TauCetiStation/TauCetiClassic#9157]
#### Подробное описание проблемы
При отковыривании обычных плиток ломом вылазит сообщение о том что отковыряна свето-плитка

#### Что должно было произойти
Нормальное сообщение

#### Что произошло на самом деле
![unknown.png](https://user-images.githubusercontent.com/57045293/163631609-06baf6bf-f40a-4255-813b-76e3bff11fe8.png)

#### Как повторить
Отковырнуть плитку ломиком

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/9155
