### ISSUE TITLE
[Task] Контр-меры для форон флуда

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#9160]
Очередное обсуждение на форуме напомнило о проблеме.

Сейчас не хватает контр-мер для противостоянию заполнению станции фороном из атмоса. Будь то малф, или нюка. Особенно если в раунде нет атмосферников.

Возможное решение - добавить новый тип трубы, который бы улавливал количество определенных токсинов, и при достижении какого-то порогового значения орал бы об этом в общий канал. С возможностью отключения тревоги емагом.
По умолчанию можно разместить на месте выхода синей трубы из отсека атмосферки, только передвинуть под укрепленную стену рядом.

![Снимок экрана от 2022-04-16 11-52-39](https://user-images.githubusercontent.com/4064061/163668739-4f7bda98-096c-4444-924d-45e367b34f22.png)

Таким образом, если кто-то захочет утопить станцию в опасных газах - это будет уже не просто пойти и открутить нужный вентиль. Либо придется разбирать стену и как-то разбираться со спрятанной тревогой-предохранителем, больше рискуя обнаружением, либо у станции будет немного времени успеть среагировать на автоматическое сообщение-тревогу и приготовится.

Можно сделать еще крафт, или добавить в фабрикатор, тут на усмотрение кто это будет делать.

**Comment by Deahaka** [comment]
Можно даже не улавливать какой-то конкретный тип газа, а фиксировать превышение безопасного порога давления (вроде это 315КПа, но можно меньше). Как раз будет меньше смертей антагов в вентиляциях из-за гениев атмосферного отсека с выходным давлением 10 000 КПа на станцию.

**Comment by volas** [comment]
Не знаю, как сейчас, но раньше высокое давление было нормальной практикой, что бы оперативно устранять аварии и восстанавливать атмосферу в отсеках

**Comment by Deahaka** [comment]
Скорость закачки не от давления в трубе зависит. Что 10 000, что 300 одинаково восстанавливает атмосферу, просто "запас" на восстановление в 100 раз больше, если давление в трубе как при фороновом пожаре. Сейчас можно без последствий удалить канистру с готовым воздухом из атмосферки, поставив с миксера на выход сразу и ничего не поменяется. Даже быстрее будет работать.

**Comment by kiVts** [comment]
А случаем Алт Кликом по трубе ключем в стене кликнуть нельзя?

**Comment by Sakuya-Izayoi** [comment]
> А случаем Алт Кликом по трубе ключем в стене кликнуть нельзя?

net
