### ISSUE TITLE
[Proposal] Удаления Deahaka из основной ротации 

### ISSUE THREAD

**Issue by Zmey25** [TauCetiStation/TauCetiClassic#9166]
#### Подробное описание проблемы
Deahaka есть в игре
#### Что должно было произойти
Deahaka  не должно быть в игре
#### Что произошло на самом деле
он есть
#### Как повторить
зайти в игру и проверить наличие во вху
#### Дополнительная информация:
неумею кодить, но постараюсь захаркодить бан на этот сикей

**Comment by KIBORG04** [comment]
вам на форум

**Comment by Zmey25** [comment]
Уже делаю

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/golosovanie-vykidyvaem-malfunction-ai-iz-raundstart-rezhimov/33022/1

**Comment by volas** [comment]
все хардкод баны в `/world/IsBanned``

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/udalenie-simbaki-maksimalno-seryozno-pervyj-kommuniti-ban/38617/31
