### ISSUE TITLE
Локализация турфов недочет

### ISSUE THREAD

**Issue by LoTaRk-FroG** [TauCetiStation/TauCetiClassic#9168]
#### Подробное описание проблемы
При снятии плитки ломом пишется "Вы сняли светящийся пол монтировкой.", но на деле никакого светящегося пола нет.
#### Что должно было произойти
Ничего не пишется.
#### Что произошло на самом деле
Пишется сообщение от разбора светящейся плитки.
#### Как повторить
Разобрать плитку.

**Comment by LudwigVonChesterfield** [comment]
фиксили
