### ISSUE TITLE
Неправильный перевод разбора плитки

### ISSUE THREAD

**Issue by Dushess0** [TauCetiStation/TauCetiClassic#9171]
#### Подробное описание проблемы
При разборе плитки ломом пишет что разбираешь свето плитку
#### Что должно было произойти
Вы демонтировали плитку.
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/44201461/163691408-6868890b-decd-41d7-89d5-0ad433f34c39.png)
Вы демонтировали светящуюся плитку.
#### Как повторить
Разобрать ломом плитку на полу на шахтерской станции
#### Дополнительная информация:
Тестируйте свой перевод

**Comment by KIBORG04** [comment]
да пофикшено
