### ISSUE TITLE
СПУ и баганная шкала настроения

### ISSUE THREAD

**Issue by QWxiZX** [TauCetiStation/TauCetiClassic#9174]
#### Подробное описание проблемы
1. СПУ вообще имеют настроение.
2. Из этого следует, что СПУ получают удовлетворение от курения сигарет.
3. Также из первого пункта следует баг с тем, что после смены батареи СПУ становится черепахой из-за предельно низкого настроения, ведь всегда считает себя крайне толстым.
#### Что должно было произойти
У СПУ нет настроения.
#### Что произошло на самом деле
Можно абузить или страдать от этого.
Проходил всю смену в поднятом настроении из-за возможности бесконечно курить сигареты.
#### Как повторить
-
#### Дополнительная информация:
-

**Comment by LudwigVonChesterfield** [comment]
> Проходил всю смену в поднятом настроении из-за возможности бесконечно курить сигареты.

а курят сигареты чтобы круто выглядеть или чтобы дым по рту?

**Comment by QWxiZX** [comment]
> > Проходил всю смену в поднятом настроении из-за возможности бесконечно курить сигареты.
> 
> а курят сигареты чтобы круто выглядеть или чтобы дым по рту?

Дымоотвод. Видимо. выводит лишний горячий воздух и тем самым кулер охлаждает.
