### ISSUE TITLE
[Proposal] Демки Кнопка Выключить

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#9178]
#### Подробное описание проблемы

система демок (реплеев) нагружает как ещё один атмос, нужно иметь возможность админам её временно выключать в критические моменты.

предлагаю запилить кнопку "Toggle Demo Recording" которая бы отключала демку до рестарта/следующего нажатия

**Comment by volas** [comment]
С записью сообщения в демо, кто это сломал.

На ТГ есть целая панель с отключениями разных жрущих вещей, для помощи поиска источников лагов, можно её портировать и отключение демо сделать в её составе. Я не помню ПР, могу потом поискать.

**Comment by LudwigVonChesterfield** [comment]
к сожалению Волас успел сделать панель с ТГ до хитрого плана с отключением реплеев и не включением оных.
