### ISSUE TITLE
Разряжение из-за лаз-гана

### ISSUE THREAD

**Issue by Helg2** [TauCetiStation/TauCetiClassic#9185]
#### Подробное описание проблемы
При лаз-гане в активном слоте, на сб-борге батарея разряжается за считанные секунды
#### Что должно было произойти
Батарея не разряжается из-за факта существования лаз-пушки
#### Что произошло на самом деле
Батарея разрядилась из-за факта существования лаз-пушки
#### Как повторить
Попросить малфа взломать консоль РД и выбрать лаз-ган в активный слот
#### Дополнительная информация:
-

**Comment by Mercurialaste** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/8778

**Comment by Chip11-n** [comment]
#9812
