### ISSUE TITLE
[Proposal] Заменить рандомных мобов ксеноморфов

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#9186]
#### Подробное описание проблемы
Метовые ксеноморфы в виде раундстарт ивента нередко вызывают синий код и абсурдную с точки ООС панику. Однако IC появление ксеноморфов вполне может побудить глав/персонал так действовать. Практика что это "обычное явление" немного кринж, как и особка на С4.
Предлагаю заменить их на любое другое животное, например агрессивного козла/помидор-убийцу/кусачую собаку(последнее смешнее). Либо же поменять на похожих к чужим змей/пауков, а не взрослых особей.

**Comment by KIBORG04** [comment]
Если для вас это обычное явление, то закройте игру и не заходите как минимум год

**Comment by Deahaka** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/11112
