### ISSUE TITLE
[Proposal]Спидран диска за 4 минуты или слишком крутой гейтвей

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9192]
#### Подробное описание проблемы
Гейтвей при своей малой цене(15 телекамней) является слишком лёгким способом попасть на станцию, он кроме того что почти мгновенно и бесшумно закидывает на станцию, так ещё и спавнит в буквально 10 шагах от мостика, а с учётом того, что в списке экипажа не всегда есть нормальные главы, диск оказывается у нюкеров спустя минуту, после чего они почти всегда побеждают, потому что времени на дифьюз бомбы и просто войну с нюкерами не хватает.
сделайте чтобы был анонс сразу после взлома или перемапьте его в какую-нибудь даль, в РнД, например.

**Comment by KIBORG04** [comment]
Будто бы через шаттл нельзя было...

**Comment by simb11** [comment]
Ну так шаттл стоит в два раза больше и не телепортирует прямо к диску

**Comment by Sakuya-Izayoi** [comment]
> с учётом того, что в списке экипажа не всегда есть нормальные главы

skill issues

**Comment by Deahaka** [comment]
Смена страток с шаттла на гейт показывала, что переключение режимов, джетпаки и преодоление препятствий для нюки было практически подавляющей причиной сосания, и избавившись от них стабильно каждый нюкер теперь получает возможность поиграть в террориста. 
Предложил бы сбавить цену на дропподы, так как это посути тот же гейт, а стоит как 3 шаттла.
