### ISSUE TITLE
Некорректная работа кустарного арбалета

### ISSUE THREAD

**Issue by RONSI7** [TauCetiStation/TauCetiClassic#9193]
#### Подробное описание проблемы
Арбалет ручной сборки почти полностью сломан. Первое, если положить заряженный арбалет в рюкзак/за спину/на пояс/ и достать его, то снаряд вывалится на землю. Второе, тоже самое, если просто перекинуть его с одной руки в другую. Третье, если арбалет с батарейкой, то вывалиться не стержень, а шрапнель. Четвертое, у арбалета нет мили урона, СОВСЕМ, он словно сделан из плюши. Пятое, вставленный металлический стержень в арбалет превращается в почти точно такой же обьект, но гораздо больший в инвентаре и не стакающийся(снаряд). Шестое, стержень (снаряд) при выстреле с арбалета под батарейкой не меняет свой спрайт на раскаленный аналог.  
#### Что должно было произойти
Арбалет ручной сборки нормально функционирует. У него нет проблем в заряженном состоянии, у него есть мили урон, выпущенные снаряды не увеличиваться в объёме, стакаются; стержень (снаряд) меняет свой спрайт на раскаленный когда это нужно. 
#### Что произошло на самом деле
То что написано в первом пункте заявки.
#### Как повторить
Зайти на сервер, сделать арбалет, использовать арбалет.

**Comment by kalazus** [comment]
Первая половина не баги, а механика арбалета т.к. заряженный арбалет невозможно переносить нормально. С руками да, прокол, но такое не помню.

**Comment by RONSI7** [comment]
Я это осознавал, но все равно решил вписать на всякий случай. И понимаю почему было так сделано, если дать возможность носить в рюкзаке заряженный арбалет, то появляются простая схема для абьюза-сделать их побольше, все зарядить, а когда надо использовать разом.

Это крайне эффективно для убийства- убойная сила у арбалета большая, а когда у тебя их 2-3, то у жертвы нет шансов выжить, количество нивелирует скорость перезарядки и еще плюс ко всему скрытно, можно в паре метров стоять от цели, а она ничего не будет подозревать.

И я предлагаю вот что: вернуть возможность носить в инвентаре заряженный арбалет, но сделать его слишком большим для рюкзака. Это уберет возможность носить больше двух арбалетов и делать это незаметно(с арбалетом за спиной/на поясе особо не погуляешь не насторожив окружающих и не привлекая внимания офицеров.)

В итоге игроки получат возможность делать огнестрел по силе не уступающие револьверу, но с очень медленной перезарядкой и привлекающие к себе много внимания.

**Comment by Deahaka** [comment]
> И я предлагаю вот что: вернуть возможность носить в инвентаре заряженный арбалет, но сделать его слишком большим для рюкзака. Это уберет возможность носить больше двух арбалетов и делать это незаметно(с арбалетом за спиной/на поясе особо не погуляешь не насторожив окружающих и не привлекая внимания офицеров.)


У нас вроде нет спрайта арбалета на поясе, так что это будет как раз таки стелсовое оружие, как и пневмоган. Сейчас всё сбалансированно работает, но убойность как раз таки у арбалета крошечная, что приводит к низкой популярности по сравнению с бола+станпрод=противник лежит.

**Comment by RONSI7** [comment]
Спрайта действительно нет, но его можно обнаружить через examine. Как мне кажется, большинство прожимают кнопку осмотра, если другая кукла в поле их зрения дольше 10-15 секунд.
