### ISSUE TITLE
[Proposal] Заменить дебаф к скорости от настроения на дебаф к урону/шансу попадания

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#9195]
Одна из целей системы настроения сделать тяжелее грифонить набегаторам

скорость бега же вредит не только им, но и их целям

предлагаю заменить дебаф к скорости на дебаф к шансу попадания.

**Comment by kiVts** [comment]
на самом деле смешно что ты грустный и не можешь бить точно 🤡 О нет я растроен о нет я не могу бить

**Comment by volas** [comment]
У меня плохой привкус от идеи вносить больше рнг в боёвку игры. Я не против ближнего боя, это своя миниигра, но перестрелки всегда были зависимы от скилла самих игроков и мне не хочется это менять и как-либо идти с этого пути.
