### ISSUE TITLE
Открытие шлюза кноком ломает разгерму и та работает неправильно

### ISSUE THREAD

**Issue by Kilkalestia** [TauCetiStation/TauCetiClassic#921]
#### Подробное описание проблемы
Маг неудачно использовал кнок и открыл шлюз в космос, но ничего не произошло 
#### Что должно было произойти
Должна была появиться разгерметизация 
#### Что произошло на самом деле
Её не было
#### Как повторить
За мага открыть кноком шлюз в космос 
#### Дополнительная информация:
![default](https://cloud.githubusercontent.com/assets/23171919/21467692/1c33ad0c-ca08-11e6-90c0-aecce21df6c1.png)

**Comment by Dennok** [comment]
Дак этож МаГиЯ. Магические силы открывают аирлоки но не выпускают воздух.

**Comment by SpaiR** [comment]
>Открытие шлюза кноком ломает разгерму

Не в кноке дело и разгерма не ломается. Мага не засосало из-за двух шлюзов. Если бы их не было или был бы только один, то он бы очень оперативно полетел бы покорять просторы космоса.
