### ISSUE TITLE
Hack intercept не работает

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#9212]
#### Подробное описание проблемы
Модуль малфа Hack intercept не работает и все на этом.
#### Что должно было произойти
Все хорошее, нужно взломать 7 АПЦ.
#### Что произошло на самом деле
Все плохое, после 3 АПЦ срабатывает малфааннонс.
#### Как повторить
Взять модуль Hack intercept.
#### Дополнительная информация:
-

**Comment by LoTaRk-FroG** [comment]
#8506
