### ISSUE TITLE
Можно в кравле бить и делать комбо

### ISSUE THREAD

**Issue by KIBORG04** [TauCetiStation/TauCetiClassic#9214]
#### Подробное описание проблемы
Апперкот из положения лежа

#### Что должно было произойти
Нельзя

#### Что произошло на самом деле
Апперкот из положения лежа

#### Как повторить
Кравлить? Хз. Но в моей ситуации чел упал от урона и после падения продолжил драться.

**Comment by Deahaka** [comment]
![0 1 1 1](https://user-images.githubusercontent.com/96499407/165837236-468aacd9-ee0a-4f2f-96da-93a1dc1e0080.png)
учтено, хз?

**Comment by KIBORG04** [comment]
Почему можно сделать апперкот лежа все еще под вопросом, да и почему бить можно тоже вопрос. Ты вообще кинул код набивки очков

**Comment by Deahaka** [comment]
Ну я про комбо, то что в кравле можно бить не баг

**Comment by Bullethole** [comment]
да, я был рад что вернули робаст жопай

**Comment by LudwigVonChesterfield** [comment]
в кравле набить сложнее

**Comment by Deahaka** [comment]
Я видел вчера момент. Какой-то клоун(буквально) пытался заробастить ассистуху аперкотами из положения лёжа. Оба в крите и с переломами по итогу. Впринципе можно 0.25 модификатор на очки поставить, если не сильно хочется получать от лежачего ответку...

**Comment by KIBORG04** [comment]
я думаю, нужно и урон уменьшать, и возможность только в ноги бить

**Comment by Deahaka** [comment]
> я думаю, нужно и урон уменьшать, и возможность только в ноги бить

Мне для другой фичи надо, как заставить бить только в ноги? Или стрелять только в ноги?
