### ISSUE TITLE
Бутылка и дермалка.

### ISSUE THREAD

**Issue by NinjaPikachuska** [TauCetiStation/TauCetiClassic#9216]
#### Подробное описание проблемы
Бутылка при ударе в голову с дермалкой станит, хотя не должна.
#### Что должно было произойти
Дермалка, как шлем, должна спасти от удара бутылки.
#### Что произошло на самом деле
Дермалка не спасает.
#### Как повторить
Ударить бутылкой в дермалку.
#### Дополнительная информация:
Вся проблема скорее всего в этой проверке.
![image](https://user-images.githubusercontent.com/89906909/165921739-0e48f1b3-ce2c-4ca8-a3a8-c8e45fb2b940.png)

![image](https://user-images.githubusercontent.com/89906909/165921788-884039c7-f10d-4a06-a25c-b7831d61a089.png)

**Comment by simb11** [comment]
#9167
