### ISSUE TITLE
Баг с акциями

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#922]
#### Подробное описание проблемы

После покупки акций часть акции пропала

#### Что должно было произойти

Не должны были пропасть

#### Что произошло на самом деле

Часть акции пропала(как на данном скриншоте http://prntscr.com/dniqgj)

#### Как повторить

Купил акции сингуло и ровно половина пропала

**Comment by Raschert0** [comment]
Акции сильно подешевели и произошла деноминация. Количество акций
уполовинилось и цена половины твоих акций в этот момент вернулась тебе

**Comment by Olt1771** [comment]
Самое забавное что ни пени не вернулось

**Comment by Raschert0** [comment]
#1086
