### ISSUE TITLE
chem skill issue

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#9224]
#### Подробное описание проблемы
Персонажи, чей навык работы с хим оборудованием, позволяет работать с хим раздатчиком, в то же время, не позволяет им без задержки работать с хим мастером.
#### Что должно было произойти
Предполагаю, без задержки.
#### Что произошло на самом деле
Задержка.
#### Как повторить
Иметь возможность без задержки работать с хим раздатчиком.
#### Дополнительная информация:
-

**Comment by Mercurialaste** [comment]
@Dushess0

**Comment by Dushess0** [comment]
Сейчас у хим аппаратов такие требования к умениям
```
/obj/machinery/chem_dispenser
required_skills = list(/datum/skill/chemistry/trained)
```
```
/obj/machinery/chem_dispenser/constructable
required_skills = list(/datum/skill/chemistry/novice)
```
```
/obj/machinery/chem_master
required_skills = list(/datum/skill/chemistry/master)
```
```
/obj/machinery/chem_master/constructable
required_skills = list(/datum/skill/chemistry/trained)
```
```
/obj/machinery/chem_master/condimaster
required_skills = list(/datum/skill/chemistry/novice)
```
```
/obj/machinery/reagentgrinder
required_skills = list(/datum/skill/chemistry/novice)
```

**Comment by Dushess0** [comment]
Я подумаю над изменением, но я бы все же оставил хим мастеру самый последний уровень в химии

**Comment by Mercurialaste** [comment]
> Я подумаю над изменением, но я бы все же оставил хим мастеру самый последний уровень в химии

Твое право, бтв, задержка минимальная и абузится через башенку из прогрессбаров.
_(Минимальная она по крайней мере для тех, кто без задержки с хим автоматом взаимодействует.)_
