### ISSUE TITLE
Депрессивные серые человечки итс нот вери гуд

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#9228]
#### Подробное описание проблемы
У абдукторов включена система настроения, в середине раунда начинаются серьёзные проблемы с геймплеем.
#### Что должно было произойти
Серые человечки не должны подвергаться этой мучительной депрессии
#### Что произошло на самом деле
Скажите прощай своим глазам
![Screenshot_2](https://user-images.githubusercontent.com/24526545/166136697-8bf6e874-ff0f-4a4e-b21f-64b85e62fc57.jpg)
#### Как повторить
Поиграйте за абдукторов.
#### Дополнительная информация:
Issue reported from  Round ID: 50890 (Tau Ceti Classic (RU))
Testmerges: ```#9209 #9201 #9188 #9106 #9041 ```
Reporting client version: 514.1583

**Comment by LoTaRk-FroG** [comment]
Гайс ай хев э бэд нюв депрессивные серые человечки ис нот э баг.

**Comment by UDaV73rus** [comment]
у всех антагов выключено настроение, это баг

**Comment by Sakuya-Izayoi** [comment]
поеш

**Comment by KIBORG04** [comment]
Не у всех, только у ченджлингов

**Comment by Deahaka** [comment]
> Не у всех, только у ченджлингов

Разрешаешь убрать абдукторам и борерам?

**Comment by QWxiZX** [comment]
У СПУ тоже уберите пожажа

**Comment by KIBORG04** [comment]
у бореров и так нету

**Comment by Deahaka** [comment]
У меня шиза? Был же ишуй о муде борера

**Comment by LoTaRk-FroG** [comment]
У бореров есть муд когда они контролят мешок мяса.

**Comment by Venngedi** [comment]
#9236 Fixed.
