### ISSUE TITLE
Не работает механ взятия на прицел

### ISSUE THREAD

**Issue by YulianR** [TauCetiStation/TauCetiClassic#923]
#### Подробное описание проблемы

Когда берешь на прицел кого-либо, если он выполняет запрещенные действия - твой персонаж не стреляет

#### Что должно было произойти

Если взятый на мушку игрок двигается или делает что-либо еще, твой персонаж должен сам выстрелить по нему

#### Что произошло на самом деле

То что описано в первом пункте

#### Как повторить

Взять человека на прицел и чтоб он подвигался и все такое

#### Дополнительная информация:

Не работает уже так давно, что fix it pls

**Comment by StrikS** [comment]
Да, вчера брал на прицел парня, выстрела не было, абыдна.
