### ISSUE TITLE
Потеряны пути для толстых вариаций формы и не только.

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#9233]
#### Подробное описание проблемы
Охранная форма: Детектив, офицер, кадет и ХоС. Не работает спрайт для толстых. 
![image](https://user-images.githubusercontent.com/19796920/166226239-860175ee-5ed0-42d1-95ce-16dfb6a186af.png)

У медиков такая ситуация:
![image](https://user-images.githubusercontent.com/19796920/166226628-092870b7-9a1d-4aaa-a90e-0629e39b583d.png)
![image](https://user-images.githubusercontent.com/19796920/166226785-be25f8a7-8cc9-4a10-af47-3f6b4206b1e3.png)
![image](https://user-images.githubusercontent.com/19796920/166227793-caae39a1-5ebd-4f5e-bdc0-a17d272b2244.png)
![image](https://user-images.githubusercontent.com/19796920/166228238-53adc401-187a-4e38-8151-79aa8976094b.png)
(Красным обозначена форма которая не предназначена для толстых, у нее нету спрайта для них)

У худых медиков проблема в том, что потерялись пути, поэтому берет значение от родителя "code\modules\clothing\under\jobs\medsci.dm."

Форма генетика в рубашке, неправильно написан путь для толстых, должен быть "genetics_new."

С жирными происходит следующее:
Когда кукла худая, использует путь "icon = /icon (icons/mob/uniform.dmi). "icon_state = "secred"" (например форма офицера) после того как кукла потолстела она ищет  "Icon = /icon (icons/mob/uniform_fat.dmi). "Icon_state = "security"".

В общем проблемы с путями и именами, спрайты для всего этого есть. Такое к сожалению происходит с большим количеством формы на станции, то что перечислено выше только лишь часть.

**Comment by NinjaPikachuska** [comment]
У части форм не совпадает айтем и айкон стейт, типо такой:
![image](https://user-images.githubusercontent.com/89906909/166231318-7b956bc7-3984-4639-9125-7c20f6e191d6.png)
У части форм вообще нет айтем стейта, из-за чего он берется у родителя, как у форм медиков:
![image](https://user-images.githubusercontent.com/89906909/166231855-dd5d0a1c-393c-42e4-a7ec-2b93078d6f38.png)

**Comment by NinjaPikachuska** [comment]
По поводу формы генетика
![image](https://user-images.githubusercontent.com/89906909/166238226-6d18d24f-9aa5-41cb-afd5-c0c8ba529551.png)
Должен называться
![image](https://user-images.githubusercontent.com/89906909/166238274-e456e8ab-8d1b-4898-98d6-6f257a607ed3.png)
