### ISSUE TITLE
Невозможно достать что-то из тела. Скелеты парализованы

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#9235]
#### Подробное описание проблемы
Превращение мёртвой куклы в скелета, при определённых манипуляциях, парализует скелета навсегда, даже реджув не помогает. Наблюдается иконка Embedded object, которого нельзя вытащить. Камень некромантии и культ страдают.
#### Что должно было произойти
Нет никаких проблем у скелетов, всё можно вытащить и полечить.
#### Что произошло на самом деле
Слева на хумане тот же баг с невозможностью вытащить объект. Его даже на сканере не показывает. Просто стрельнули в ногу с глока или револьвера.
![0 0 0](https://user-images.githubusercontent.com/96499407/166304917-ada62f46-d3ea-44b2-bcb9-7a0ba75716df.png)
При этом сначала игра принимает лежачего скелета не кравлющим, "улаживая его", так что врядли тут изменение кравла виновато.
#### Как повторить
Настрелять в любую часть тела чем-то. Гарантированный эффект, если кукле отпилить все конечности, а после настрелять в торс бакшотами/слагами и скелетофицировать.
#### Дополнительная информация:
Может это конечно не связанные вещи, но я посмотрел код скелетов и не смог найти ничего, что могло бы сковывать скелета во время его создания. Может реворк гомункулов киборга что-то поменял? Баг был замечен ранее, но не могу сказать точно когда. Может Киборг найдёт раунд культа с моей куклой в предвестнике культа/скелете/гомункуле и будет больше информации

**Comment by Sakuya-Izayoi** [comment]
Я обнаружил что в таком случае у скелетов weakened постоянно устанавливается в 9. Если изменить через ВВ, то значение 9 снова вернется.

**Comment by KIBORG04** [comment]
Короче ржака. Веакен ставится на 10, ниже по коду он сбрасывается до 9. Всё происходит из-за большого голоурона. 
https://github.com/TauCetiStation/TauCetiClassic/blob/0a30ee15375d8c1952e05d564a68cc358a02b4ed/code/modules/mob/living/carbon/human/life.dm#L806-L813

Так как скетелы не чувствуют боли, то и голоурон у них не отнимается)
https://github.com/TauCetiStation/TauCetiClassic/blob/0a30ee15375d8c1952e05d564a68cc358a02b4ed/code/modules/mob/living/carbon/human/human_defense.dm#L9-L14

**Comment by Deahaka** [comment]
Пофикшено
