### ISSUE TITLE
ИПС страдают от депрессии

### ISSUE THREAD

**Issue by EnshizhArkoshfol** [TauCetiStation/TauCetiClassic#9237]
#### Подробное описание проблемы

ИПС как и жалкие органики испытывают эмоции обо всем на свете, чего быть не должно.

#### Что должно было произойти

ИПС должен иметь статичный муд

#### Что произошло на самом деле

Желтый экран и сильное замедление от депрессии по поводу лишнего веса появившегося после замены батареи

#### Как повторить

Потерять заряд ниже 50% / заменить батарею / %вставить действие режущее муд%

#### Дополнительная информация:

Странно что никто до этого не додумался, учитывая свежие ПРы для абдукторов и генокрадов.

**Comment by LudwigVonChesterfield** [comment]
больше не страдают
