### ISSUE TITLE
ED-209 не собирается с бронёй СБ.

### ISSUE THREAD

**Issue by dred1792** [TauCetiStation/TauCetiClassic#924]
#### Подробное описание проблемы

При сборке ED-209 броня СБ не цепляется на раму с ногами

#### Что должно было произойти

А должна!

#### Что произошло на самом деле

Не прицепилась

#### Как повторить

Следуя гайду на Вики

#### Дополнительная информация:

А вот если заспавнить старый жилет охраны, то всё цепляется.

Баг найден - Kaskardness.
Протестирован мной, при его помощи.

**Comment by sir-duck** [comment]
https://github.com/TauCetiStation/TauCetiClassic/blob/0f6e6cadcac3ac36a19acb0a71c1cec076bc9efa/code/game/objects/items/robot/robot_parts.dm#L127

Броньки сб там уже нет?

**Comment by dred1792** [comment]
Она и не там должна быть. Мне уже в принципе подсказали как всё исправить, как "clonning" закончится буду ПР пилить.

**Comment by volas** [comment]
@dred1792 Можно в ручную не закрывать, а просто в ПР-е написать "fixes #num". 
Закроется тогда автоматически, когда ПР будет смержен.
