### ISSUE TITLE
[Proposal] Вернуть возможность ловить вещи.

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#9256]
Вернуть возможность ловить вещи, которые кидают в тебя, когда ты держишь кнопку броска включенной. Зачем ее отключили вряд ли кто-то узнает.

**Comment by KIBORG04** [comment]
её никто не удалял

**Comment by pro100kotah** [comment]
Добавит кучу интеракций и допустим перекидывать друг другу оружие было бы прикольно. Допустим в режиме блоба ловить разряженное и кидать обратно в руки заряженное. Хотя люди просто, наверное, продолжат кидать на пол. Я говорю про моменты, когда в тебя кто-то кидается огнетушителями или плиткой пола, а ты берешь и ловишь их. 
Или добавить возможность ловить предметы с шансом, когда ты находишься в движении. Либо поймал, либо по тебе ударило:
![image](https://user-images.githubusercontent.com/57403011/167230813-b8e61835-f4ed-4386-97b6-9822d88d273b.png)

**Comment by KIBORG04** [comment]
Раньше можно было пули ловить

**Comment by RONSI7** [comment]
Вот вернуть такую возможность клоуну, с очень маленьким шансов. Он же актер каскадер - ловкость рук и никакой магии.
