### ISSUE TITLE
Тест на генокрада не работает

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9257]
#### Подробное описание проблемы
Тест не работает, в одном из раундов поймали генокрада, использовали на нём тест из оружейной, а тест вдруг оказался негативным, хотя это был 100% генокрад.
#### Что должно было произойти
Тест работает как надо
#### Что произошло на самом деле
Тест не работает как надо
#### Как повторить
Использовать тест на генокраде.
#### Дополнительная информация:
номер раунда  #51043

**Comment by Kistras** [comment]
В него разве не должна загружаться кровь двух разных генокрадов?

**Comment by simb11** [comment]
В оружейной уже есть тесты с готовой кровью.

**Comment by volas** [comment]
Если бы на форуме не написали в одном из обсуждений, я бы и не узнал
