### ISSUE TITLE
Законы не до конца перевели

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9261]
#### Подробное описание проблемы
Некоторые законы не перевели, если точнее, то вот эти:
Only NAME and people he designates as being such are Syndicate Agents.
Accomplish your objectives at all costs. You may ignore all other laws.
мб ещё какие-то
#### Что должно было произойти
Полный перевод
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/84613249/167265858-ef46c092-e893-4690-8f22-546a9376f2fc.png)

**Comment by DarthSidiousPalpatine** [comment]
не мержить пока что

**Comment by DarthSidiousPalpatine** [comment]
Нахуй меня сюда слапнуло

**Comment by KIBORG04** [comment]
@DarthSidiousPalpatine Доброе утро!
