### ISSUE TITLE
Великий и ужасный 659

### ISSUE THREAD

**Issue by D3kr0s** [TauCetiStation/TauCetiClassic#9264]
#### Подробное описание проблемы
Runtime meows, "Зафиксирована аномалия #659. Пожалуйста, отойдите подальше."
Появилось в тот момент, когда была попытка изучить последний фрагмент древа биологических исследований. Не клацалось и в итоге не получалось изучить, даже после переключений между другими фрагментами. В конечном итоге появился рантайм, а консоль перестала реагировать. То есть её интерфейс больше не открывался.
#### Что должно было произойти
Фрагмент должен был изучиться, а консоль работать дальше стабильно.
#### Что произошло на самом деле
Из-за бага рантайма 659 консоль перестала реагировать
#### Как повторить
В процессе изучений данный рантайм попадается не всегда, а лишь с некоторым шансом.
#### Дополнительная информация:
Issue reported from  Round ID: 51076 (Tau Ceti Classic II (RU))
Testmerges: ```#9242 #9209 #9201 #9188 #9106 ```
Reporting client version: 514.1583

**Comment by KIBORG04** [comment]
159 Runtime in rdconsole.dm:659 : Cannot read null.name
