### ISSUE TITLE
Нельзя сбивать людей во время высокоскоростной езды на стуле

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9270]
#### Подробное описание проблемы
Нельзя сбивать людей во время быстрой езды на стуле. Вроде как, раньше можно было, сейчас же нельзя
#### Что должно было произойти
Можно
#### Что произошло на самом деле
Нельзя
#### Как повторить
Сесть на стул, взять огнетушитель, найти человечка, попытаться сбить его.

**Comment by Pivo24** [comment]
Раньше нельзя было

Не баг, получается???

**Comment by KIBORG04** [comment]
тоже не помню, чтобы можно было. Обычно ты врезался и себе лицо ломал.
