### ISSUE TITLE
Описание кровавых рук остаётся, если руки помыть

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#9277]
#### Подробное описание проблемы
Мы можем отмыть кровавые перчатки и при Examine мы перестаём видеть красный текст, сигнализирующий о грязи на них

Но мы не можем отмыть руки. Вернее как, можем, спрайт крови с ладоней пропадёт, но красный текст He has a blood-stained hands! остаётся.

БОНУС: По-моему с голыми ногами та же история.

#### Что должно было произойти
Никаких сигналов о кровавых руках, когда ты эти руки помыл
#### Что произошло на самом деле
He has a blood-stained hands!/feet!
#### Как повторить
Убейте всю станцию без перчаток и помойте руки, побегайте по лужам крови босиком и помойте ноги
#### Дополнительная информация:
Issue reported from Tau Ceti Classic Sandbox
Testmerges: ```#9242 #9234 #9209 #9201 #9106 ```
Reporting client version: 514.1583

**Comment by Mercurialaste** [comment]
Эт вроде касается и некоторой одежды, которую нужно просто перенадеть, чтобы она отбагала. _(Перенадеть руки будет… Несколько сложнее.)_

**Comment by Fluffy-510** [comment]
Не актуально
![Снимок экрана (88)](https://github.com/TauCetiStation/TauCetiClassic/assets/109436132/3afba473-08ca-48fd-ae06-515cb95d9298)
(то же с душем)

**Comment by Venngedi** [comment]
#12119
