### ISSUE TITLE
Нет ветки вирусологии в РнД

### ISSUE THREAD

**Issue by BenDJaminUt** [TauCetiStation/TauCetiClassic#9287]
#### Подробное описание проблемы
Невозможно изучить вирусологию
#### Что должно было произойти
![image](https://user-images.githubusercontent.com/29231723/168417830-31f9b7a9-dc43-47ee-8455-f2b5a6d9e344.png)
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/29231723/168417807-078c4432-8419-4023-99e4-e6842be3a01c.png)
#### Как повторить
Захотеть построить вирусологию на Фалконе
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/29231723/168417970-7593e20a-d3eb-42b7-ac94-deae8133e8e2.png)

**Comment by Mercurialaste** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/9265/commits

Эт вроде багфикс такой, не? 

_(Оборудование вирусолога и так невозможно разобрать, ни разу не видел чтобы собирали.)_

**Comment by KIBORG04** [comment]
Фича
