### ISSUE TITLE
Воксы-налётчики умирают раундстартом

### ISSUE THREAD

**Issue by Vysserath1** [TauCetiStation/TauCetiClassic#9288]
#### Подробное описание проблемы
Игрок с куклой СПУ при спавне за налетчика воксов раундстартом мертв
#### Что должно было произойти
Живой вокс налетчик
#### Что произошло на самом деле
Мертвый вокс налетчик
#### Как повторить
Поставить своей кукле расу СПУ и попасть в тиму налетчиков
#### Дополнительная информация:
Я до этого не привязывал этот прикол к расе, пока QWxi не столкнулся с таким же говном. Чисто мое предположение, что это из-за того, что у СПУ нет пульса

**Comment by Akellazp** [comment]
**Что должно было произойти**

Мёртв не только тот у кого персонаж спу а все

**Comment by Vysserath1** [comment]
Я за СПУ заходил и умирал. Кьюви тоже СПУшка (скоро уже нет *плак*). Про другие случаи не знаю

**Comment by QWxiZX** [comment]
В чате был флуд с tiny prick.

**Comment by KIBORG04** [comment]
Инфаркт при игре на воксах

**Comment by KIBORG04** [comment]
После мержа https://github.com/TauCetiStation/TauCetiClassic/pull/9173 можно закрыть ишуй
