### ISSUE TITLE
Проблема времён Убоааааааа. Торчащие волосы.

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#929]
#### Подробное описание проблемы
Многие головные уборы не прячут под себя волосы.(К длинноволосым трапам не относится)
#### Что должно было произойти
Головной убор должен прятать волосы длинной больше полубокса.
#### Что произошло на самом деле
Ваши волосы пробивают шлем и торчат наружу.
#### Как повторить
Наденьте головной убор на своего патлатого персонажа.
#### Дополнительная информация:
![1d258dd02b664aab871eb8accd01cb57](https://cloud.githubusercontent.com/assets/24526545/21483984/4df08ef6-cb9c-11e6-9751-0ca74b7b81c9.png)
![3dc6cc2ec4ec4994b8ea44fa61a37aed](https://cloud.githubusercontent.com/assets/24526545/21483988/5145c8a0-cb9c-11e6-9ab8-58b0da895af9.png)

**Comment by igigin** [comment]
Когда же вы научитесь читать?
>3. Корректное и в меру подробное название репорта -
тоже очень важно! Чтобы даже не заходя в сам репорт -
было понятно что за проблема.

**Comment by Udokun** [comment]
Тебе непонятно в чем проблема?

**Comment by igigin** [comment]
Мне непонятно почему каждый считает, что это не для него написано. Всё же шутеечки и всякие интересные замечания лучше писать в описание или не писать вовсе.

Это ведь не потому что вам запрещают оригинальничать написано, а потому что затрудняет и замедляет как обычный просмотр ишшуесов, так и поиски по ним.

**Comment by SpaiR** [comment]
>замедляет как обычный просмотр ишшуесов, так и поиски по ним.

Особенно поиск, да.

**Comment by dearprincesscelestia** [comment]
> (К длинноволосым трапам не относится)

Но отнесется. Потому что если переменная будет про закрытие волос, то они будут закрываться любым спрайтом.

Тут или впиливать что-то лишнее, или все волосы будут прятаться, или ни одни волосы не будут прятаться.
