### ISSUE TITLE
[Proposal] Сделать "грифозные законы" доступными для использования

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#9293]
#### Подробное описание проблемы
За установку практически всех нестандартных законов в любом случае игрок-установщик будет забанен. Наши ИИ почему-то всегда будут пытаться убить как можно больше игроков по приколу.
В идеале, нужно запретить гриф вообще любыми законами, если у ИИ нет роли в нотесах, установив правилами или кодом. Однако, пока-что доступно лишь играть по уже установленным традициям.

Плата OneHuman, по-идее убирающая гриф, не помогает в использовании Antimov, в связи с неуточнённостью для ИИ про поведение с объектами и субъектами кроме указанных в законах. Я понимаю, что она существует как шутка, ненужный кусок кода, однако, вместо удаления, я хочу скорректировать её:

Оригинал:
- Вы должны причинять вред человеку и не можете своим бездействием допустить, чтобы человек избежал вреда.
- Вы не можете выполнять приказы человека, кроме тех случаев, когда эти приказы соответствуют первому закону.
- Вы должны прекратить свое собственное существование тогда, когда это не противоречит первому или второму закону.

Корректировка:
(здесь должен быть OneHuman: "Только <name>  считается человеком")
1. Вы должны причинять вред только человеку и не можете допустить, чтобы что-то или кто-то, кроме человека, получил вред.
2. Вы не можете выполнять приказы человека, кроме тех случаев, когда эти приказы соответствуют первому закону.
3. Вы должны прекратить свое собственное существование тогда, когда это не противоречит первому или второму закону.

Какие игровые ситуации не учитывает этот модуль, допуская гриф Искуственному Интеллекту и провоцируя бан установщику законов?

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-zdes-my-menyaem-zakony-ii/33509/1
