### ISSUE TITLE
В автолате вместо speed loaders на револьвер тр-7 патроны по одному

### ISSUE THREAD

**Issue by Misakiwa** [TauCetiStation/TauCetiClassic#9299]
#### Подробное описание проблемы
В автолате вместо speed loaders на револьвер тр-7 патроны по одному
#### Что должно было произойти
Должны быть speed loaders
#### Что произошло на самом деле
Вместо них патроны по одному
#### Как повторить
Взломать автолат
#### Дополнительная информация:
Очень смешно ниже выглядят .38

**Comment by simb11** [comment]
не баг а фича

**Comment by Misakiwa** [comment]
кринжича
