### ISSUE TITLE
Бипски патруль

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/TauCetiClassic#930]
#### Подробное описание проблемы
Стандартный бипски который появляется на станции порой отказывается переходить в патруль и стоит на месте.
#### Что должно было произойти
Бипски изначально должен патрулировать станцию. А если патруль вырублен, то при включении начать патрулировать.
#### Что произошло на самом деле
В некоторых раундах он просто отказывается патрулировать. Даже если включить патруль-мод он все равно его вырубит.
#### Как повторить
Тут сложно. Бывает он стоит а бывает нет. Возможно придется перезапускать серв.
#### Дополнительная информация:
![image](https://cloud.githubusercontent.com/assets/19417166/21484741/5b793a42-cba0-11e6-9472-c96bb4c095b1.png)

**Comment by SpaiR** [comment]
#910
