### ISSUE TITLE
Карго и проблема их очков

### ISSUE THREAD

**Issue by SheoLeo** [TauCetiStation/TauCetiClassic#9305]
#### Подробное описание проблемы
Каргопоинты больше не начисляются.
#### Что должно было произойти
Карго живет, а не выживает
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/86962735/169094772-e7d58388-20d7-4a74-a44b-79e47a1f190f.png)
![image](https://user-images.githubusercontent.com/86962735/169094797-9bc0ac74-7c71-43ef-ae10-826a18272c04.png)

#### Как повторить
Зайти за КМа, грузчика
#### Дополнительная информация:
Issue reported from  Round ID: 51337 (Tau Ceti Classic II (RU))
Testmerges: ```#9266 #9201 #9132 #9106 ```
Reporting client version: 514.1583

**Comment by KIBORG04** [comment]
Я лично хз о чем этот пропосал.
