### ISSUE TITLE
[Proposal] Бебраланс комбат-модуля боргов

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#9309]
**I. Знакомство.**
Комбат модуль очевидно не нужно спавнить в раунд примерно никогда, так как это имба.
У него в наличии: флешка, плазма-резак, лазерная винтовка, термалы, модуль щита, мобильный модуль и гаечный ключ.
Флешка, резак, геачный ключ и винтовка вполне адекватно смотрятся. Модуль щита, блокирующий 50% урона, если включён, тоже можно побороть антагонистам. Термалы очевидно можно убрать, однако самый звездец это мобильный модуль. Он ставит модификатор скорости в 0, что позволяет летать по станции быстрее гостов (!!!).
И всё это, кроме лазерки, не жрёт энергию вообще (!!!).

**II. Предложение.**
Что надо сделать: установить модификатор в мобилити моде на уровень скорости втек-модуля (переменные `move_speed` или `speed` на уровне около еденицы, не меньше). Добавить отнимание энергии у модулей. Убрать термалы.

**III. Для чего это нужно.**
Далее уже можно будет добавить в выбор админам при спавне ОБР следующее окошко (с проверкой на редкод обязательно, чтобы мотивировать плееров на станции кодировать активнее): "Хотите ли вы вызвать боевого дрона?" и собственно спавнер для него. Но конечно же сначала требуется выполнить задачи по фиксу этого бойца, а там уже я помогу, если будет всё не в одном ПРе.

**Comment by Mercurialaste** [comment]
Нужно как минимум починить лазерку, это я писал и сравнивал в --
https://github.com/TauCetiStation/TauCetiClassic/issues/8778

Насчет расхода энергии у модулей щита и скорости, модуль щита снимает энергию, когда впитывает урон и это хорошо заметно на бесконечной батарейке. _(Вроде когда тестил, это было единственное кроме ЭМИ, что могло её разрядить.)_

Насчет модуля мобильности, по сути, хотели сделать отсылку на дройдек из ЗВ, но чет переборщили, скорость у этого модуля по сути, должна быть больше чем у ВТЕК, но не такой бешенной. _(Если я ещё правильно помню, расход энергии высчитывается от скорости борга + активных модулей.)_

Термалы отдельный рофел, их хотят уже убрать у ГСБ, вот как раз у этого борга можно заменить их на ПНВ, хотя в большинстве случаев, как и синди модуль, боевой модуль будет использовать его крайне редко.

И момент насчет спавна, там нужно менять само условие, тк даже если crisis = 1, нужно чтобы код, был выше красного, а также, эта переменная дает возможность ВСЕМ боргам при смене модуля выбрать комбат, а не только одному. 

Вроде, все что помнил, написал, мб потом добавлю или поправлюсь.

**Comment by Deahaka** [comment]
Не видел проблем с лазеркой, пока она не в слоте. Всё заряжалось нормально. Расход энергии должен быть всегда при экипированном модуле, как у всех боргов, тут не понятно что даст твой вариант. Насчёт что хотели авторы — очевидно щитспавнить смешные штучки, скорее всего для себя или друзей, другого варианта у меня нет.
Вариант сделать вообще постоянный спавн борга при обр, но админ через панельку может разрешить кризис, что без редкода не даст выбрать комбат модуль просто.

**Comment by Mercurialaste** [comment]
> Не видел проблем с лазеркой, пока она не в слоте. Всё заряжалось нормально. Расход энергии должен быть всегда при экипированном модуле, как у всех боргов, тут не понятно что даст твой вариант. Насчёт что хотели авторы — очевидно щитспавнить смешные штучки, скорее всего для себя или друзей, другого варианта у меня нет. Вариант сделать вообще постоянный спавн борга при обр, но админ через панельку может разрешить кризис, что без редкода не даст выбрать комбат модуль просто.

У лазерки слишком большой расход и малый заряд, я вроде приводил пример с тем, что одна и та же БС батарея позволяет делать совсем разные вещи, на мехе и борге. Банально уменьшить расход до более приемлемого и норм.

*(Взломанный модуль комбат модуля к слову, работает по-старому.)*

И насчет того, "что хотели авторы", я вроде ставил вопрос того, что такой расход стоит специально, или там случайно нолик лишний дописали.

Есть кста, вариант вынести комбат модуль как синди модуль. Т.е. сделать его отдельным синтетиком. _(Синди модуль к слову, обаладает пластиной на 200 прочности, но у него все ещё 300 сумарного ХП, если я правильно помню. Было бы неплохо сделать комбат модулю такую же пластину, учитывая то, что скорее всего его максимум будт чинить сваркой. Да и то, маловероятно. А ну и поставить доступ к его панели - капитана и ОБР, чтобы всякие шутняры не могли его открыть/разобрать, также удалить его из консоли управления боргами РД, тк его могут подорвать ещё на подлете к станции.)_

**Comment by TryXAH** [comment]
Со скоростью, естественно, переборщили, однако ломать совсем мобильный модуль не стоит. Уровень втека это уже совсем дно, какая мобильность тут вообще. Заодно можно естественную скорость борга уменьшить, для боланса
А лазерка ебнутая вообще, за десять секунд в слоте способна разрядить борга полностью.

**Comment by Deahaka** [comment]
> Со скоростью, естественно, переборщили, однако ломать совсем мобильный модуль не стоит. Уровень втека это уже совсем дно, какая мобильность тут вообще. Заодно можно естественную скорость борга уменьшить, для боланса А лазерка ебнутая вообще, за десять секунд в слоте способна разрядить борга полностью.

Включается моментально и даёт скорость быстрее таяры = потенциал для абуза харрасмента, как собственно сейчас и есть с втеком. А втек на боевом модуле уже может быть имбой такой, чтобы летал как башенный. Часто такого происходит точно не будет.

**Comment by Deahaka** [comment]
> > Со скоростью, естественно, переборщили, однако ломать совсем мобильный модуль не стоит. Уровень втека это уже совсем дно, какая мобильность тут вообще. Заодно можно естественную скорость борга уменьшить, для боланса А лазерка ебнутая вообще, за десять секунд в слоте способна разрядить борга полностью.
> 
> Включается моментально и даёт скорость быстрее таяры = потенциал для абуза харрасмента, как собственно сейчас и есть с втеком. А втек на боевом модуле уже может быть имбой такой, чтобы летал как бэшенный. Часто такого происходит точно не будет.

**Comment by TryXAH** [comment]
В чем проблема летания по станции? Он боевой борг, может себе позволить в конце концов. Опять же, обр частенько сливают, так что минусов не вижу. 
Да и если убрать прибавку к скорости в мобильном модуле, то и ничего плохого не будет

**Comment by Mercurialaste** [comment]
> > > Со скоростью, естественно, переборщили, однако ломать совсем мобильный модуль не стоит. Уровень втека это уже совсем дно, какая мобильность тут вообще. Заодно можно естественную скорость борга уменьшить, для боланса А лазерка ебнутая вообще, за десять секунд в слоте способна разрядить борга полностью.
> > 
> > 
> > Включается моментально и даёт скорость быстрее таяры = потенциал для абуза харрасмента, как собственно сейчас и есть с втеком. А втек на боевом модуле уже может быть имбой такой, чтобы летал как бэшенный. Часто такого происходит точно не будет.

мб тогда просто убрать модуль мобильности? По своей сути, да, он позволяет чуть ли не убегать от пуль.
Как и упомянул выше, можно сделать комбат модуль отдельным синтетом как синди, а чтобы он не был совсем медленный, пихнуть ему ВТЕК, учитывая что он будет только с ОБР в большинстве своем. 
_(Без ВТЕК борг будет всегда плестись где-то позади людей, которые конечно не будут его ждать.)_

Также к слову, насчет щита, если поднять ему расход батареи и при активации, сделать ему замедление,  но добавить возможность активировать его, вместе с ещё одним модулем, можно дать боевому модулю если не мобильность, то танковость.
Разница в том, что из-за мобильности борг может спокойно уйти от взрыва ЭМИ гранаты или просто мансить от выстрела из ионки, щит же, по своей сути предполагает впитывание урона, а замедление подталкивать если не к тому, чтобы дать один раз ионкой, то хотя бы попытаться оглушить его флешером.

_(Хотя к слову, в коде апгрейдов я видел модуль устанавливающий защиту от флешеров для боргов, можно по приколу дать ему это улучшение, хотя честно, это улучшение также неплохо смотрелось бы и на синди модуле.)_

**Comment by Deahaka** [comment]
Я буду ждать пока кто-то начнёт и потом уже буду обсуждать что ещё можно, а что нельзя.

**Comment by Deahaka** [comment]
Впринципе уже норм
