### ISSUE TITLE
Не отображается чат.

### ISSUE THREAD

**Issue by 73sasha98** [TauCetiStation/TauCetiClassic#931]
#### Подробное описание проблемы
Нету чата,смотрите скрин.
#### Что должно было произойти
работающий чатик появиться.
#### Что произошло на самом деле
не появился.
#### Как повторить
запустить игру.
#### Дополнительная информация:
Не работает только на Тау Кити, на других все норм.
![default](https://cloud.githubusercontent.com/assets/24793079/21500432/d7f09b9c-cc4f-11e6-8eab-def84f92edda.JPG)

**Comment by Raschert0** [comment]
Обнови интернет эксплорер

**Comment by Dennok** [comment]
8го достаточно, хотя пишет что чтото пахать не будет.

**Comment by Dennok** [comment]
Highlighting is disabled. You are probably using Internet Explorer 8 and need to update.

**Comment by 73sasha98** [comment]
Все работает терь,спасибо.

**Comment by Dennok** [comment]
самое интересное это то что оригинальный гуночат все еще работал при старом ИЕ, но только автопродвижения при новых сообщениях не было.

**Comment by Raschert0** [comment]
Самое интересное, что со старым ИЕ не работает не только чат, но и наноУИ. Так что без обновления до, как минимум, 8-й версии никак

**Comment by Dennok** [comment]
Разве? Както не заметил, хотя не помню точно.

**Comment by Dennok** [comment]
Развечто висла консоль камер, но то изза кол-ва., и не проверял при 8й.
