### ISSUE TITLE
Получение очков карго сломалось

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9315]
#### Подробное описание проблемы
![c1](https://user-images.githubusercontent.com/84613249/169402621-24e8bf30-abc8-4f87-8e97-b4ab349fd55b.PNG)
![image](https://user-images.githubusercontent.com/84613249/169402572-44563706-b86b-4ff5-8b48-df2f84f5dc2f.png)
Отправили в карго целую кучу дорогой фигни, а денег за эту фигню не дали, хотя в логах можно заметить, что всё отправленное барахло прибыло на ЦК
#### Что должно было произойти
всё ок, деньги есть
#### Что произошло на самом деле
всё не ок, вещи отправили, а денег нет
#### Дополнительная информация:
возможно, проблема в зимней карте, хотя я очень сомневаюсь.

**Comment by KIBORG04** [comment]
Вроде именно что ТМ, так как до этого работало.
https://github.com/TauCetiStation/TauCetiClassic/pull/9266

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/13465
