### ISSUE TITLE
Метаболизм х100 или же новая система метаболизма.

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#9316]
#### Подробное описание проблемы
Нереально упоротый новый метаболизм, будто что-то сломалось. Возможно только у воксов:
Отравление воздухом за 10 секунд убивает, потому что накопленные токсины действуют нереально быстро. 5 юнитов антитоксина за 2 секунды лечат 60 токсин урона. 70 брут урона с головы лечатся за 3 секунды 15 юнитами бикардина. Голод наступает через минуту, после того как поел. Инфекции слишком быстро перетекают в некроз, уколотый спейсалин улетает прямо на глазах, как и остальное лекарство.
#### Что должно было произойти
Не должен был быть метаболизм х100
#### Что произошло на самом деле
По ощущениям метаболизм х100
#### Как повторить
Попробовать полечиться лекарствами за вокса или набрать токсинов в тело. Так как тестить остальные расы мне лень, скажу что такое работает только на воксе.

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/9266

**Comment by pro100kotah** [comment]
> #9266

Это вроде не то

**Comment by DarthSidiousPalpatine** [comment]
"Инфекции слишком быстро перетекают в некроз"
Странная строчка. А может лайфтик теперь тикает чаще обычного?

**Comment by simb11** [comment]
Проблема с нереально быстрым лечением замечена у всех рас, не только у воксов.

**Comment by KIBORG04** [comment]
Меня на воксе карпы когда загрызли, я так и не умер, даже вставал и смог бежать, правда очень не долго
