### ISSUE TITLE
У абдукторов волосы

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#9329]
#### Подробное описание проблемы
У абдукторов прически с персонажа в преференсах
#### Что должно было произойти
Абдукторы лысые
#### Что произошло на самом деле
У абдукторов волосы
#### Как повторить
Попасть за абдукторов имея прическу у персонажа за которого нажал реди
#### Дополнительная информация:
Issue reported from  Round ID: 51437 (Tau Ceti Classic (RU))
Testmerges: ```#9266 #9226 #9201 #9106 ```
Reporting client version: 514.1569

**Comment by Deahaka** [comment]
фича?

**Comment by Akellazp** [comment]
хуича

**Comment by volas** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/9583
