### ISSUE TITLE
Коробка гранат M79 на ЦК ничего не содержит

### ISSUE THREAD

**Issue by Riverz1** [TauCetiStation/TauCetiClassic#9338]
#### Подробное описание проблемы:
Коробка гранат для М79 не содержит в себе гранаты для М79

#### Что должно было произойти:
В коробке должны быть гранаты для М79

#### Что произошло на самом деле:
В коробке гранат для М79 должны были появиться гранаты

#### Как повторить:
Зайти за ОБР и посмотреть в коробку гранат для М79

**Comment by Riverz1** [comment]
Пофикшено

**Comment by KIBORG04** [comment]
Кем????

**Comment by Rahmanio** [comment]
ишью закрывается с пром, если его замержили, зря закрыл
