### ISSUE TITLE
[Proposal] Ослабление эффективности киборгов

### ISSUE THREAD

**Issue by Rahmanio** [TauCetiStation/TauCetiClassic#9341]
#### Подробное описание проблемы.
Киборги очень эффективные и ничего не отдают взамен своей эффективности.

#### Другая идея.
ПР #9312 не решает совершенно главную проблему киборгов, а именно эффективность их работы.

Предлагаю сделать боргам более жесткое потребление энергии, сейчас с обычной батарейкой борг может не заряжаться полчаса-час, а с батарейкой получше(её выдают раундстартом, если попросить) и вовсе весь раунд.

**Comment by TryXAH** [comment]
Потребление энергии действительно можно и повысить, а то около часа на простой батарейке кататься это не очень круто.
Имхо, боргов нужно двигать в сторону их дороговизны и малого количества. 
В плане, можно разделить протезы и части боргов, последним добавить стоимость за ресурсы с шахты. По желанию пихнуть еще изучение борготы в ветку исследований на место позитронки. Ну и раундстартом поставить один готовый корпус для позитронки.
Так же снизить им самостоятельности от роботехов. Платы там не на смену модуля, а по аналогии с сб, только ставится без выбора. И что-то в том же духе. 
Таким образом, сами борги начнут 4 закон исполнять более тщательнее, зная, что в случае и уничтожения новый корпус им напросто могут не сделать, и людишки начнут бережнее к ним относится, не взрывая по каждой ерунде. А еще триторы ии и малфы в таком случае гораздо плотнее бы пытались в кооперацию с робототехниками, без которых их железная армия просто бы загнулась.

**Comment by Mercurialaste** [comment]
Ну… Говорить что «ничего» они не отдают откровенно странно, но допустим.
 _(Хотя банальное отсутствие разводного ключа у мед борга уже является ограничением, которое тот никак не восполнит.)_

 Дюшесс им даже макс скилы убрал, чтобы людишки так не плакали, что они больше не нужны.

Увеличить потребление батареи можно и нужно, хотя как я и писал в рнд, тогда нужно или полностью перераспределять потребление энергии, или исходя из сравнений приходить к удобоваримым значениям. 
_(Думаю, ещё раз говорить что выстрел из пульсача у условного виндикатора, занимает всего 0.3 от батареи, не увеличивает энергопотребление при активном модуле и отнимает энергию только за ходьбу и использование снаряжения.)_

_(Ну и да, если сейчас тупо поднять энергопотребление киборга, ничего кроме разнесения чумы СБ борга добиться не получится.)_


На счет того, как будут относится к киборгам, честно, хз за мой опыт игры, тебя либо забивают на похуй и оставляют на месте где забили, либо подрывают, в случае сбойности. _(Конечно даже без попыток в ремонт.)_


Трухан, плоха воровать идеи, которые я тока сегодня ночью писал в рнд.)
И на счет этой самостоятельности, хотя бы немного её должно остаться, чтобы условный научный юнит мог частично заменить собой робототехника в сфере обслуживания юнитов и установки протезов. _(Лоу-поп или отсутствие робототехника/рд, науч борог обычно всегда есть хотя бы один, а вот робототехи без возможности пособирать мехов и поубивать антагов могут и в крио пойти, если им лень, вообще лечь у себя в морге.)_

**Comment by Rahmanio** [comment]
Короче мне не нравится пр #9312, я ещё бы понял сделали 75 хп броне боргов, но 25 это перебор. Короче чел плох

**Comment by Mercurialaste** [comment]
> Короче мне не нравится пр #9312, я ещё бы понял сделали 50-75 хп броне боргов, но 25 это перебор. Чел плох

Тк он энергозатратность и не трогал, только взаимодействие боргов с антагами и легкость убийства боргов для антагов.

**Comment by Rahmanio** [comment]
> > Короче мне не нравится пр #9312, я ещё бы понял сделали 50-75 хп броне боргов, но 25 это перебор. Чел плох
> 
> Тк он энергозатратность и не трогал, только взаимодействие боргов с антагами и легкость убийства боргов для антагов.

а я про то что это ослабление не то ослабление, которое нужно киборгам...

**Comment by Mercurialaste** [comment]
> > > Короче мне не нравится пр #9312, я ещё бы понял сделали 50-75 хп броне боргов, но 25 это перебор. Чел плох
> > 
> > 
> > Тк он энергозатратность и не трогал, только взаимодействие боргов с антагами и легкость убийства боргов для антагов.
> 
> а я про то что это ослабление не то ослабление, которое нужно киборгам...

Я понимаю про что ты, хз, понимают ли другие.
