### ISSUE TITLE
Кровь заражённая вирусом не передаёт вирус

### ISSUE THREAD

**Issue by xenkokcocs** [TauCetiStation/TauCetiClassic#9345]
#### Подробное описание проблемы
Пытался заразить обезьяну вирусом через кровь не вышло пробовал все варианты передачи вируса той же кровью не сработало так же не смог заразить своего персонажа, выработки анти-тел соответственно тоже с кровью не работают
#### Что должно было произойти
Обезьяна или я должны были заразиться 
#### Что произошло на самом деле
Не заразить обезьян вирусом и персонажа
#### Как повторить
зайдите за вирусолога попробуйте если нет защиты от дурака, то бись от меня то у вас тоже не получиться заразить обезьяну или себя. Так же антитела от существующего вируса через кровь не передаются.
#### Дополнительная информация:
Issue reported from  Round ID: 51502 (Tau Ceti Classic (RU))
Testmerges: ```#9266 #9226 #9201 #9106 ```
Reporting client version: 514.1569

**Comment by Mercurialaste** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/9321
https://github.com/TauCetiStation/TauCetiClassic/issues/9223
