### ISSUE TITLE
Добавить воут на смену карты, игрокам [Proposal]

### ISSUE THREAD

**Issue by Dominig12** [TauCetiStation/TauCetiClassic#9349]
#### Подробное описание проблемы
Сейчас, для смены карты необходим админ, так же ему необходимо сидеть до конца раунда или сразу же выставлять карту на стандартную чтобы потом к нему не было претензий

#### Что должно было произойти
Игроки при желании могут запустить воут на смену карты из списка разрешенных карт (без тестового полигона и тд)

#### Что произошло на самом деле
Админ создает воут самостоятельно, после чего либо ждет конца раунда, либо сразу после смены карты, выставляет карту стандартную и игроки не наигрались на прикольной карте

**Comment by Pirsnya** [comment]
Предлагаю сделать так, чтобы после выбора карты она менялась на дефолтную, то есть при окончании раунда на сноу следующий раунд будет спейс. А так же ограничение на фалкон ввести чтобы там не играло 70 человек, если она будет в ротации, естетвенно.

**Comment by Deahaka** [comment]
Я извиняюсь, а какие у нас карты есть живые, кроме бокса и фалькона, чтобы их ставить??

**Comment by Pirsnya** [comment]
> Я извиняюсь, а какие у нас карты есть живые, кроме бокса и фалькона, чтобы их ставить??

Бокс зимний\космос, фалькон, всё, обчёлся.

**Comment by volas** [comment]
А я хотел закрыть с ссылкой на https://github.com/TauCetiStation/TauCetiClassic/pull/9566 и начать комбо отсчет недель с закрытым топ-багам. А теперь это не баг, а ишью. Эхх.
