### ISSUE TITLE
Емагнутую стеклянную створку нельзя разобрать

### ISSUE THREAD

**Issue by Skyrull** [TauCetiStation/TauCetiClassic#936]
#### Подробное описание проблемы
Емагнутую стеклянную сторку нельзя разобрать или сломать.
#### Что должно было произойти
Створка ломается и разбирается.
#### Что произошло на самом деле
Створку нельзя разобрать или сломать.
#### Как повторить
Емагнуть стеклянную створку, попытаться демонтировать ее (открыть панель отверткой и вытащить плату ломом).

Речь идет про такие дверцы http://prntscr.com/dppnet

**Comment by Balphagore** [comment]
А ты точно правильно ее разбираешь? Она, вроде, должна быть открыта, чтобы вытащить плату. Хотя, если она даже не ломается, то скорее всего баг.

**Comment by Skyrull** [comment]
Да, пишет что нужно ее ОТКРЫТЬ, хотя она уже и так открыта.

**Comment by Dennok** [comment]
Все работает. Не знаю в чем ваша проблема.

**Comment by Dennok** [comment]
Хотя есть еще вариант что она была открыта когда ее емагали.
