### ISSUE TITLE
Неправильные цены и пропажа предметов из вендоров?

### ISSUE THREAD

**Issue by Dushess0** [TauCetiStation/TauCetiClassic#9360]
#### Подробное описание проблемы
В токсинной исчезло 3 вентиля для бомб и 5 сигналлеров. Сами вентили и сигналеры стоят по 1 кредиту. Так же пропала часть вещей в вендоре роботики. Так же цены на обычный рамен были 1 кредит.

На рамены как бы все равно, но убирать часть вентилей (что дают очки в рнд  и которые НЕЛЬЗЯ ЗАМЕНИТЬ ИХ ВСЕГО 8 НА СТАНЦИИ) и часть вещей и роботики это явное ухудшение качества жизни. 

Плюс это не логично: 
> делаешь исследования для НТ
> получаешь зарплату от НТ
> платишь часть зарплаты что бы купить вентили что нужны для исследований?
#### Что должно было произойти
Нормальные ценны и количество товаров. 
#### Как повторить
Зайти в раунд, посмотреть ассортимент вендоров
#### Дополнительная информация:

Test merged PRs: [#9266](https://github.com/TauCetiStation/TauCetiClassic/pull/9266) [#9226](https://github.com/TauCetiStation/TauCetiClassic/pull/9226) [#9201](https://github.com/TauCetiStation/TauCetiClassic/pull/9201) [#9106](https://github.com/TauCetiStation/TauCetiClassic/pull/9106)

**Comment by KIBORG04** [comment]
Фича
