### ISSUE TITLE
Тактическая перезарядка плохо работает 

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9383]
#### Подробное описание проблемы
Тактическая перезарядка работает не полностью, нельзя перезаряжать пистолет магазинами из рюкзака, разгрузки и прочих контейнеров
#### Что должно было произойти
Можно
#### Что произошло на самом деле
Нет
#### Как повторить
взять пистолет, магазин, положить магазин в рюкзак, попытаться ТАКТИЧЕСКИ перезарядиться.
#### Дополнительная информация:
#9201

**Comment by Dushess0** [comment]
Связано с телепатией то как она считает предметы что можно драг и дропнуть. Пофикшу как только разберусь что надо подкрутить
