### ISSUE TITLE
Скиллы Фалкона

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [TauCetiStation/TauCetiClassic#9389]
#### Подробное описание проблемы

карта маленькая, нужно чтобы скиллы у конкретных проф компенсировали маленький экипаж

**Comment by BenDJaminUt** [comment]
Да. Да. Да. Да.

**Comment by Tap0r** [comment]
Замержите скиллы уже и я это сделаю

**Comment by Dushess0** [comment]
> Замержите скиллы уже и я это сделаю

Done

**Comment by Tap0r** [comment]
найс, щас я убью всех :axe::axe::axe::axe::axe::axe::axe:

**Comment by Chip11-n** [comment]
В пользу #9417
