### ISSUE TITLE
Флакон из экстракта лазурного слайма не утраивает эффект, при использовании на других экстрактах

### ISSUE THREAD

**Issue by Slegarrr** [TauCetiStation/TauCetiClassic#9391]
#### Подробное описание проблемы
Флакон из экстракта лазурного слайма ничего не делает, при использовании на экстрактах
#### Что должно было произойти
Флакон из экстракта лазурного слайма , при использовании на экстрактах должен утраивать их эффективность
#### Что произошло на самом деле
Эффект от экстрактов обыкновенный, вместо усиленного
#### Как повторить
Зайти за ксенобиолога, вывести лазурных слизней, переработать их в экстракт и вколоть в него форон. Далее, выпавший из экстракта флакон, использовать на любом другом экстракте.

**Comment by Vysserath1** [comment]
Не баг. Протестил - все работает. Чел просто не знал, что надо форон 3 раза вводить в ядро которое улучшил.
