### ISSUE TITLE
Эмоуты Яна слетели.

### ISSUE THREAD

**Issue by Zandwitch23** [TauCetiStation/TauCetiClassic#9421]
#### Подробное описание проблемы
Играя за Яна при введении эмоутов по типу ```*tail, *drool, *whimper``` и т.д. (те что прописаны специально для пёселя) в чатике ничего не происходит.
#### Что должно было произойти
Должно произойти действие.
#### Что произошло на самом деле
Ничего не произошло.
#### Как повторить
Написать в чат эмоут.
#### Дополнительная информация:
Эмоуты хумана работают. Все проверить не удалось так как ```*help``` тоже не работает.

**Comment by KIBORG04** [comment]
Там удалены эмоуты без механа. Для получения списка эмоутов пиши *list. 

А ещё там классный эмоут *dance появился
