### ISSUE TITLE
Невозможно редактировать новые записи в  Employment Records за Ии и возможно за других синтетиков

### ISSUE THREAD

**Issue by SpaceBimbo** [TauCetiStation/TauCetiClassic#943]
#### Подробное описание проблемы
 Консоль перестает открываться после создания новой записи персонажа в Employment Records/Medical records/Security records
#### Что должно было произойти
После создания записи консоль открывается и позволяет заполнить дело до конца
#### Что произошло на самом деле
Консоль перестает реагировать на "клики" синтетиков и людей
#### Как повторить
Создать новую запись и попытаться открыть ее, консоль вылетает

**Comment by MorCrate** [comment]
Там на всех мобов, включая хуманов.

**Comment by SpaceBimbo** [comment]
Ну я жи написал в третьем пункте

**Comment by SourcePony** [comment]
Не ПОСЛЕ создания, а после захода в новую запись. Консоль к херам зависает. Итог: потерянная карта и невозможность регистрации нового члена экипажа. Приоритет: Самый высокий что у вас есть

**Comment by Dennok** [comment]
Незнаю что там у вас виснет. У меня новая запись тупо не открываетса, притом другие кнопки нашут.
И на крайняк можно отверткой раскрутить консоль чтоб получить обратно карту.
