### ISSUE TITLE
Генетика полностью сломалась (предположительно, из-за недавнего ПРа с активацией генов)

### ISSUE THREAD

**Issue by QWxiZX** [TauCetiStation/TauCetiClassic#9432]
#### Подробное описание проблемы
Как ни облучай куклу, ни дави мутагеном, и как её ни Pulse Radiation - никакие блоки не становятся 801 или 802, что сообщает о болезнях. Болезней больше нет (то есть, они есть, но никак не отображаются). Ничего не понятно. 

На самом деле болезни теперь просто выше 802 и так их можно вычислять - но так их не отделить от сил и всегда выходит 12 генов вместо 11 на листике болезней, потому что вскрывается что-то ещё. Неловко и неудобно.
#### Что должно было произойти
Всё нормально.
#### Что произошло на самом деле
Генетика сломалась и работать невозможно.
#### Как повторить
@Morar1 глянь, по-моему, твоя штука сломала.
#### Дополнительная информация:
Issue reported from  Round ID: 51885 (Tau Ceti Classic (RU))
Testmerges: ```#9394 #9291 #9226 #9106 #8955 ```
Reporting client version: 514.1583

**Comment by Morar1** [comment]
Ничего не сломано.

**Comment by QWxiZX** [comment]
> Ничего не сломано.

Ахахах. СКОЛЬКО БАГОВ!
Ещё пачка багов сегодня была интересная.
![image](https://user-images.githubusercontent.com/70110199/172577329-8cd67894-90a5-4d1a-b2a0-cc5826b0ac21.png)
![image](https://user-images.githubusercontent.com/70110199/172577341-75d6805a-fd9b-44c6-bf16-e405696d45ee.png)
Человек превращается в мартышку после Transfer'а того, что в мартышку его превращать не должно - И ПРИ ЭТОМ БЛОКИ В НИЗКИХ ПОКАЗАТЕЛЯХ ВСЕ ЕЩЁ ОСТАВЛЯЮТ ЕГО КАК МАРТЫШКУ.
Офицер ещё к тому же упал в вечный стан от галлюцинаций, имея чистые гены, спасла только манкизация. 
Какая-то хуйня, убирайте это, пожалуйста, вот вам раунд со всеми доказательствами.

Issue reported from  Round ID: 51891 (Tau Ceti Classic (RU))
Testmerges: ```#9394 #9291 #9226 #9106 #8955 ```
Reporting client version: 514.1583

**Comment by KIBORG04** [comment]
А что если так выглядит истинная генетика, а все до этого было багом?

**Comment by QWxiZX** [comment]
![image](https://user-images.githubusercontent.com/70110199/172580488-1b315da7-277f-4363-8c07-e3179a43758d.png)
Возможно, что это просто раунд баганный.

**Comment by KIBORG04** [comment]
Кажись раунд этот был сломан нахуй. Мне админы пишут об этом даже

**Comment by QWxiZX** [comment]
НОВОЕ ОТКРЫТИЕ.
ОКАЗЫВАЕТСЯ, ЧТО TRANSFER КАКИМ-ТО ОБРАЗОМ ПЕРЕДАЕТ ВСЕ ОТКРЫТЫЕ ГЕНЫ ИЛИ ЧТО-ТО ВРОДЕ ТОГО. 
Иного объяснения, почему после открытия чего-то эти гены как-то вставляются в уже записанный Transfer - непонятно.
В 83666 раунде вы можете видеть, как где-то в 14:50 кукла человека получила халка и свечение, хотя в этих генах, которые ему были Transfer, халка даже не было. Но он открылся 5 минут назад где-то.
Я все еще не совсем понимаю, что это за херня, но то же было со свечением недавно за минут 10 до этих событий, хотя свечения тоже в том наборе генов не было.

**Comment by kalazus** [comment]
Генетика давно сломана, и если мучить труп (а может и не только труп), то что-то происходит с записанными генами. Лучше хранить гены на внешних, или сразу применять. Это не связано с недавним пром.

**Comment by QWxiZX** [comment]
> Генетика давно сломана, и если мучить труп (а может и не только труп), то что-то происходит с записанными генами. Лучше хранить гены на внешних, или сразу применять. Это не связано с недавним пром.

гены, что были записаны и хранились в Transfer, всегда нормально передавались

**Comment by pro100kotah** [comment]
Подтверждаю, раньше transfer работал нормально и можно было спокойно без уколов людям давать все открытые полезные гены, скурпулезно записанные в буфер. Теперь же там что-то сломано.

**Comment by QWxiZX** [comment]
> Подтверждаю, раньше transfer работал нормально и можно было спокойно без уколов людям давать все открытые полезные гены, скурпулезно записанные в буфер. Теперь же там что-то сломано.

Так изменения же уже откатили, вроде?
Когда ты в последний раз проверял?

**Comment by volas** [comment]
Багрепорт был сделан по багнутому раунду (там что-то глобально полетело, может контроллер), и автора как понимаю где-то могло еще смутить кэширование.

Если будут проблемы - создайте новый ишью.
