### ISSUE TITLE
Помощь не работает

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9435]
#### Подробное описание проблемы
Помощь не работает, при попытке запросить помощь ничего не происходит. 
#### Что должно было произойти
Всё работает
#### Что произошло на самом деле
Нет
#### Как повторить
Попросить помощь...

**Comment by Misakiwa** [comment]
Кнопка сет скиллс ту максимум тоже не работает

**Comment by KIBORG04** [comment]
Виноват ТМ эмоутов или дюшес?

**Comment by Dushess0** [comment]
ТМ емоутов

**Comment by Dushess0** [comment]
локально билд проверял работает. Опять кодеры все сломали

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/8955/commits/450f7173fc44238adc903247e9411c0a34b18729
