### ISSUE TITLE
Баг с отоброжение внутреннего кровотечения при лечении бикаридином и крио.

### ISSUE THREAD

**Issue by Olt1771** [TauCetiStation/TauCetiClassic#944]
#### Подробное описание проблемы
Когда вылечиваешь бикаридином или крио внутреннее кровотечение то на сканере и в стационарном сканере отображается что оно всё ещё есть

#### Что должно было произойти

Должно было отобразиться что внутреннего кровотечения нет

#### Что произошло на самом деле

Оно якобы есть но его нет

#### Как повторить

Влить передоз бикаридином дождаться пока заживёт внутряк использовать любой из сканеров отображающий внутреннее

#### Дополнительная информация:

Именно из-за этого думали многие что бикаридин не лечит внутряк

**Comment by ZVee** [comment]
Крио - это в смысле при добавлении иной хим. смеси в крио? А "бикаридин" вроде как и не должен лечить внутреннее, а крио - если речь про обычную смесь - только хуже делать. 
Однако смущает во всей этой истории - "Оно якобы есть но его нет".

**Comment by skvazarb** [comment]
Бикардин успешно "лечит" повреждение внутреннего кровотечения всмысле уменьшения дамага самой раны
https://github.com/TauCetiStation/TauCetiClassic/blob/0f6e6cadcac3ac36a19acb0a71c1cec076bc9efa/code/modules/organs/organ_external.dm#L458
Но полностью оно не проходит. Возможно, потому что значение изменяется непосредственно, что довольно странно. Остается вопрос, является ли это предполагаемой работой или багом.
>Оно якобы есть но его нет

Если у человека в крови инапровалин или бикардин, то никаких эффектов для него быть и не должно.

**Comment by ZVee** [comment]
Ну вот исходя из комментов - бикаридин при овердозе должен лишь тормозить эффект. И по коду если пройтись по всей цепочки - нет намека на то, что химия удаляет интернал вовсе.

**Comment by Raschert0** [comment]
Химия не удаляет интернал, но вгоняет его в 0 и его должно удалить рано или поздно из списка повреждений

**Comment by skvazarb** [comment]
Как раз не вгоняет в 0. Полагаю, из-за этого
https://github.com/TauCetiStation/TauCetiClassic/blob/2c41eb155d7277fc310b80ff778addaeb7791d71/code/modules/organs/wound.dm#L321
На минимальной стадии 5 дамага.

**Comment by Olt1771** [comment]
bicaridine and inaprovaline stop internal wounds from growing bigger with time, and also stop bleeding / Internal wounds get worse over time. Low temperatures (cryo) stop them.
        if(W.internal && !W.can_autoheal() && owner.bodytemperature >= 170)

Моя код не хорошо понимать, но по идее сказано о полной остановке

**Comment by ZVee** [comment]
Переводится как - Такая-то химия предотвращает усугубление внутренних ран и кровотечение. Как правило - комментарии в коде должны содержать очень точную формулировку, иначе говоря - речь про обычное кровотечение и про внутренние раны по крайней мере то как вижу это я.
Тут надо задаться вопросом - внутренние раны и внутреннее кровотечение это одно и тоже или нет - и тогда будет ответ на все это.
Переменная "internal" тоже не говорит о том, что речь про внутреннее кровотечение, там написано о том, что она отвечает за то, что рану можно только хирургически убрать.

**Comment by skvazarb** [comment]
Не может пропасть полностью из-за этого
https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/organs/wound.dm#L322
Т.е., вероятнее всего, так и планировалось изначально. Может быть стоит изменить? Полное лечение бикардином выглядит интересной и достаточно сложной механикой.
Но в текущем варианте это не баг.

**Comment by ZVee** [comment]
Сложной - трудно назвать, передоз на деле легкая механика, а так - это вы сами решите уже в как вам угодно (в данный момент в моих комментариях не надо искать за или против). Я лишь озвучил свой взгляд на механ кода, который не факт что верен (т.к меня смущают слова internal wound и internal bleeding и из-за недостатка инфы - не могу понять - разное это или нет). В весь код меда я не лазал с головой, а по комментариям автор мог не все описать точно.

**Comment by skvazarb** [comment]
Лечится не только передозом, надо ждать 10 минут с момента появления, а потом еще дамаг уменьшать до нуля. В это время передоз токсинами дамажит. При этом в крио может и не получится хумана охладить до 170 из-за сопутствующих инфекций.

**Comment by Raschert0** [comment]
Да, кстати, если его охладить, то бикаридин перестанет лечить. Но и кровь перестанет идти совсем

**Comment by Olt1771** [comment]
По сути если человек поступает с внутряком он в крите\без конечностей. Обычно таких сразу клонируют, по этому было бы неплохо, эдак поддерживать жизнь с помощью химии, но сделать это чуточку сложнее

**Comment by StrikS** [comment]
Не вижу ничего плохого в том, чтобы бикардин при передозе в несколько минут убирал интернал. У бикардина хороший метаболизм, его потребуется много. Это будет затратной альтернативой на тот случай некому провести операцию.
