### ISSUE TITLE
Карта при вытаскивании из АТМ может удалиться

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9445]
#### Подробное описание проблемы
Если во время вытаскивания карты у игрока будут заняты обе руки, то карта удалится.
#### Что должно было произойти
карта оказалась на полу
#### Что произошло на самом деле
карта оказалась в неизвестности
#### Как повторить
Вставить карту в АТМ, взять две любые вещи в руки, попытаться вытащить карту из атмчика

**Comment by Deahaka** [comment]
Банкомат сожрал, как в жизни
