### ISSUE TITLE
"Клин" у плазма оружия.

### ISSUE THREAD

**Issue by pro100kotah** [TauCetiStation/TauCetiClassic#9466]
#### Подробное описание проблемы
У плазма оружия срабатывает клин, когда то стреляет либо ничем, но при этом выстрел есть, а проджектайла и урона нет. Либо вообще отказывается стрелять при полной обойме.
#### Что должно было произойти
Выстрел. Обычный, нормальный выстрел.
#### Что произошло на самом деле
"Клин", когда оружие просто отказывается стрелять и выдает щелчок, как при пустой обойме, но при этом обойма новая/заряженная. Либо просто стреляет ничем и тратит заряд обоймы.
#### Как повторить
Баг работает с plasma 104-sass и plasma 10-bc. Если пострелять из одного, потом снять обойму и ту воткнуть в другую.
#### Дополнительная информация:
При этом оружие будет стрелять, будет издавать звук, но снаряд в виде плазмы не будет вылетать из-за чего и не будет наноситься урон. Этот баг ломает саму пушку, (Винтовку или Дробовик, баг срабатывает и с тем, и с тем), даже если вставить абсолютно новую обойму или зарядить ее, то пушечка продолжит стрелять воздухом/будет давать пустой клик. Пустого клика я добился тем, что вынул батарею из обоймы и вставил обратно, а затем обойму пустил в оружие. После чего оружие доламывается в край и при стрельбе вызывает рантайм.
![image](https://user-images.githubusercontent.com/57403011/173364682-0508b96b-52df-4cc1-97c6-60c870802a79.png)
Дополнение: Поломанное оружие не фиксится пиханием в нее обоймы, заряженной блюспейс батарейкой. Оружие дает отстрелять красную плазму, но когда дело доходит до синей, снова "клинит".

**Comment by pro100kotah** [comment]
Говорили, что на гите иш уже есть, даже есть некий фикс от Мотзарда, но при этом баг все еще существует.

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/10867

**Comment by Chip11-n** [comment]
Сталкивался с таким же, ну хоть теперь буду знать из-за чего оно было

**Comment by pro100kotah** [comment]
Даже застрелиться нельзя...
![image](https://user-images.githubusercontent.com/57403011/173366885-1609c964-2780-4b5a-a439-725dcf58f080.png)

**Comment by Deahaka** [comment]
Что-то удаляет из ammo_type чамбера этот патрон, но непонятно что

**Comment by Motzord** [comment]
Баг до сих пор актуален и в каком-то ишьюсе я писал че за дела и как это можно пофиксить
