### ISSUE TITLE
Фантомная боль

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9470]
#### Подробное описание проблемы
Игрок может получить некую неосязаемую, невидимую боль, которая не отображается на иконке состояния персонажа(там где пульс типо), понять что она у вас есть можно по плохому настроению и замедлению.
#### Что должно было произойти
хз наверное эта боль должна отображаться на индикаторе здоровья или ещё где то
#### Что произошло на самом деле
непонятно что, персонаж неизвестно почему имеет плохой муд и бегает со скоростью улитки.
#### Как повторить
много путей получить такое состояние, самый лёгкий - ударить себя пару раз дубинкой.

**Comment by LudwigVonChesterfield** [comment]
ето вероятно shock_stage который ещё и не имеет ограничения сверху, и можно эту фантомную боль потом весь раунд ждать когда она опустится.
