### ISSUE TITLE
РЦД оказывается забагован, а мы и не знали.

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#9481]
#### Подробное описание проблемы
РЦД может строить стены под себя или других мобов, под другие объекты.
#### Что должно было произойти
Не строит стены.
#### Что произошло на самом деле
Строит стены.
#### Как повторить
Взять любой РЦД и в режиме постройки стен нажать им под себя/объект.
#### Дополнительная информация:
https://www.youtube.com/watch?v=b4UPB5qWy6Y&ab_channel=Mercurialaste
https://www.youtube.com/watch?v=YXtFnZX3Cpo&t=1s&ab_channel=Mercurialaste
https://www.youtube.com/watch?v=WULQAzvHW6c&ab_channel=Mercurialaste

**Comment by muWander** [comment]
а ещё рцд боргов может разобрать укрепленную стену

**Comment by Mercurialaste** [comment]
> а ещё рцд боргов может разобрать укрепленную стену

А ещё рцд меха может разобрать укреп стену.
_(Не говоря о возможности делать это на расстоянии.)_

Как и то что я описал, больше похоже на фичу, чем на баг, но без уточнения, баги это или фичи, ни одно из утверждений неверно.

**Comment by pro100kotah** [comment]
Баги и фича размытое понятие. У боргов нет альтернатив барьеров, поэтому только через РЦД можно заходить в зону с разгермой, не раскидывая ее по всей станции. А еще инженерный юнит не может укреп стены строить ибо гриппер не может брать пласталь. Либо поправьте эти приколы и добавьте нужные модули, либо оставляйте это как фичу.

**Comment by Mercurialaste** [comment]
> Баги и фича размытое понятие. У боргов нет альтернатив барьеров, поэтому только через РЦД можно заходить в зону с разгермой, не раскидывая ее по всей станции. А еще инженерный юнит не может укреп стены строить ибо гриппер не может брать пласталь. Либо поправьте эти приколы и добавьте нужные модули, либо оставляйте это как фичу.

Ну, по мне, то что рцд может строить под объекты и мобов - не баг. 
Но за это есть одобренный банхаммер, из чего следует, что о чудо, кто-то считает это багом.
