### ISSUE TITLE
Скелеты голодают и не могут насытиться 

### ISSUE THREAD

**Issue by Misakiwa** [TauCetiStation/TauCetiClassic#9487]
#### Подробное описание проблемы
Скелеты голодают, но поднять шкалу голода они не могут
#### Что должно было произойти
Не должно этого быть
#### Что произошло на самом деле
Оно есть
#### Как повторить
Поиграть
#### Дополнительная информация:
Issue reported from  Round ID: 52096 (Tau Ceti Classic (RU))
Testmerges: ```#9433 #9408 #9394 #9226 ```
Reporting client version: 514.1583

+ кринж мудлет улетает в 0

**Comment by Motykoo** [comment]
> ^ Фейк, скелеты голодают и не могут насытиться едой.
тебе видео записать как я ем за скелета и он насыщается?

**Comment by kalazus** [comment]
Иконка справа не соответствует действительности т.к. она показывает насыщенность вместе с не переваренными нутриентами. Проверил перепроверил на сэндбоксе и проблема есть.

**Comment by Motykoo** [comment]
да, заметил, nutrition иконке не соответствует
