### ISSUE TITLE
Пинпоинтер не видит цель на другом слое

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#9522]
#### Подробное описание проблемы
Поинтер не может запеленговать цель при условии, что искомая цель не находится на одинаковым с поинтером слое.
#### Что должно было произойти
Поинтер должен пеленговать цель на других слоях и продолжать их вести на разных слоях.
#### Что произошло на самом деле
1) Если цель была запеленгована на одном слое с поинтером то поинтер способен вести цель между слоями, главное не менять настройку;
2) Если цель не находится на одном слое с поинтером, то поинтер уходит в отказ: "Failed to locate the captain's antique laser gun!". При этом не ясно, находится ли цель на другом слое или же ее просто теперь не существует.
#### Как повторить
Ингейм.

**Comment by WallShrabnic** [comment]
С чего бы пинпоинтер должен был пеленговать цели на других слоях?

**Comment by Deahaka** [comment]
Пинпоинтер ищет любую цель на любом слое кроме ЦК

**Comment by simb11** [comment]
Инвентарь это, кстати, тоже отдельный слой, из-за чего поинтер может не найти вещь на человеке или в рюкзаке человека.
Почему он не должен искать вещи на других слоях? Почему тогда нюкерский поинтер пеленгует диск даже на первом слое? Или капитанский ищет человека или ИИ на другом слое?

**Comment by Deahaka** [comment]
Каким образом диск может покинуть з слой и слой нюки?

**Comment by simb11** [comment]
Я не совсем про это, поинтер нюкеров, при попытке включить его на 1 слое, показывает координаты диска на станционном, а не пишет "фейлед ту локейт чё то там"

**Comment by DctrMM** [comment]
> "Failed to locate the captain's antique laser gun!"

Я писал об этом год назад, пинпоинтер это крайне сломанная штука, кому интересно вот - https://github.com/TauCetiStation/TauCetiClassic/issues/7728
