### ISSUE TITLE
Весь чат В ТРУХУ.....

### ISSUE THREAD

**Issue by maleyvich** [TauCetiStation/TauCetiClassic#9525]
#### Что произошло на самом деле: 
![image](https://user-images.githubusercontent.com/104298869/174952452-317ef9c5-77c1-4e35-8bde-0594496c2076.png)

**Comment by Mercurialaste** [comment]
Сделали же возможность создавать отдельные чаты...
![image](https://user-images.githubusercontent.com/90282587/174953660-7dc5e8a9-7e12-428c-81a8-791280b8dda3.png)

**Comment by kalazus** [comment]
1) писать нужно с новой строки, а не продолжать шаблон.
2) в preferences есть куча кнопок, и одна из них отвечает за видимость эмоций за гостов. Будь мужиком и найди её сам.
3) в чате можно сделать отдельную вкладку для общения ooc/гостов.

**Comment by Akellazp** [comment]
почему я должен менять свои преференсы из-за того что кто-то сделал хуйню?
