### ISSUE TITLE
Бесконечный стан мыла и шкафа

### ISSUE THREAD

**Issue by ghost** [TauCetiStation/TauCetiClassic#9534]
#### Подробное описание проблемы
Если положить мыло в шкафчик и посадить туда человека, а потом открывать и закрывать шкаф, тогда он будет до бесконечности кататься на мыле и не выходить из стана
#### Что должно было произойти
Кукла после того как открылся шкаф не должна скользить на мыле
#### Что произошло на самом деле
Кукла скользит на мыле когда шкаф открывают и закрывают
#### Как повторить
Взять шкаф и положить туда мыло, затем положить туда куклу и открывать и закрывать

**Comment by BunkyFly** [comment]
Стан ту вин

**Comment by KIBORG04** [comment]
Ура!
