### ISSUE TITLE
Холостые выстрелы у А28.

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#954]
#### Подробное описание проблемы
Когда начинаешь стрелять из А28 не наносится урон по людям (в редкие случаи появляются логи попадания), также пули не разбивают стёкла.
#### Что должно было произойти
А28 должен нормально стрелять и наносить ущерб.
#### Что произошло на самом деле
Пуф-пуф.
#### Как повторить
Возьмите А28 и постреляйте во всё что можно.

**Comment by Damirrus1** [comment]
Все нормально. Люди кладутся от боли. Пушка уже перебафнутая. И боргов отключает, и кладет пацанов в риге.

**Comment by Udokun** [comment]
Нанёс 10 выстрелов апатику, ни один выстрел не попал в него, игнорирование пуль у объектов.

**Comment by Damirrus1** [comment]
Клацай по кукле, а не в пол.

**Comment by Tankred0** [comment]
Пиратская резина, хе

**Comment by Udokun** [comment]
По кукле и клацаю.

**Comment by Damirrus1** [comment]
Не знаю, ты криворукий или что, но все идеально. Даже вырубает людей в сон

**Comment by Udokun** [comment]
Только что были пираты, снова проверил, логи не появляются.

**Comment by Damirrus1** [comment]
Только что получал от пиратов по лицу с их оружия.

**Comment by Udokun** [comment]
У меня что, бан на логи и урон? Даже по лицу не могу им ударить.

**Comment by Lancer411** [comment]
@Udokun У пиратов автоматы заряжены резиной. Они только станят.

**Comment by Uvash** [comment]
Поправлю: специальной, бронебойно-электромагнитной резиной. Станят ассистентов, разбирают мехов/киборгов.
