### ISSUE TITLE
Дубликат одежды в портфеле раундстартом

### ISSUE THREAD

**Issue by BenDJaminUt** [TauCetiStation/TauCetiClassic#9543]
#### Подробное описание проблемы
Про появлении на велосити или где-нибудь ещё в портфеле спавнится та же одежда, что и на персонаже
#### Что должно было произойти
![image](https://user-images.githubusercontent.com/29231723/175980756-84ac1422-d706-46be-8bc5-7a94dd9f97a5.png)
#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/29231723/175980683-4bb6abdb-d4f8-4a54-8f12-e07183d27d38.png)

#### Как повторить
зайти в игру, лол
#### Дополнительная информация:
Issue reported from  Round ID: 52395 (Tau Ceti Classic III (RU))
Testmerges: ```#9226 #9394 #9408 #9433 ```
Reporting client version: 514.1583

**Comment by RichardJones1** [comment]
Пытаюсь воссоздать на локалке и не получается... Ну и когда тестил ПР тоже такой ошибки не получалось. Я явно что-то упускаю. @BenDJaminUt у твоего перса были какие то особенности? трейты или тд

**Comment by RichardJones1** [comment]
А в ишью человек описывает что у него именно дубликаты появились.

**Comment by BenDJaminUt** [comment]
Такое случается каждый раз, как я захожу в игре. Возможно это связанно с тем, что я играю за вокса.
Из лодаута у меня футболка и оранжевый джампсьют. Захожу за медбрата.
Интересно, что после этого бага у меня в портфеле начала спавниться ручка-фонарик, хотя раньше у меня её в наборе никогда не было.

**Comment by RichardJones1** [comment]
Хм, любопытно. Видимо, ботинки спавнятся тебе в инвентарь, потому что игра не может надеть их на тебя и выдает сандали. А фиолетовый джампсьют спавнится потому что на тебе уже есть одежда из лодаута и поэтому она на тебя не может надеться. Про ручку хз.
Короче, пойду фиксить...

**Comment by BenDJaminUt** [comment]
ну, раз пр фикса появился, убираю ишью. 

вы, ребята, молодцы, думаю сами почините как-нибудь дальше :)
