### ISSUE TITLE
[Proposal] Дать рефлектив блобу особенный спрайт

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9559]
#### Подробное описание проблемы
Дайте рефлектив блобу уникальный спрайт, сейчас он почти не отличается от других стенок блоба.
Сделайте его спрайт синим, или белым, или ещё каким, чтобы выделялся на фоне других стен..

**Comment by Vysserath1** [comment]
Давайте его подсвечивать сквозь стены и сообщение от ЦК чтоб приходило с точными координатами

**Comment by Mercurialaste** [comment]
> Давайте его подсвечивать сквозь стены и сообщение от ЦК чтоб приходило с точными координатами

Ебашить огнём БС артиллерии.
