### ISSUE TITLE
[Port Request] ИИ интеракции для админов

### ISSUE THREAD

**Issue by volas** [TauCetiStation/TauCetiClassic#957]
Сабж.
https://github.com/tgstation/tgstation/pull/13474
https://github.com/tgstation/tgstation/pull/13936

Барт предложил, создам ишью что бы не потерялось. Ну и вообще предлагаю подобные порт-реквесты делать для уже готовых на других билдах вещей.

**Comment by dred1792** [comment]
В общем, надо бы продублировать тут. Я этим уже занимаюсь, вот.

**Comment by igigin** [comment]
Чот я мисскликнул при заходе в пр.
