### ISSUE TITLE
Телекинез бесполезен

### ISSUE THREAD

**Issue by kalazus** [TauCetiStation/TauCetiClassic#9581]
#### Подробное описание проблемы
Тк жрёт слишком много нутриентов. Если правильно понял, на первом уровне за каждый тайл расстояния он жрёт 10 единиц голода (из 500 "нормальной" шкалы голода). Это жесть, учитвая что жрёт он даже если ты просто жмякнешь на рандомный тайл чтобы посмотреть в ту сторону.

#### Что должно было произойти
Из-за тк его пользователь вечно голодный, даже если не собирается пользоваться им. Пользовать ТК невозможно.

#### Что произошло на самом деле
Я ГОЛОДЕН!

#### Как повторить
Взять телекинез.

**Comment by Chip11-n** [comment]
Может вовсе убрать эту механику голодания из-за тк? Или я не знаю про жесточайшие его абузы? Типо, это же должна быть награда за работку, а не потеха

**Comment by IlinMihail** [comment]
тк и до этого не особо полезный был а с голодом и прочими изменениями он совсем никому не нужен

**Comment by Mercurialaste** [comment]
[Proposal]

**Comment by QWxiZX** [comment]
Сахар даже не помогает.
Причина - мелкие действия, которые жрут кучу нутриментов и которые ты при этом не хочешь совершать. Как, например, посмотреть кликом в другую сторону. Вот это всё не должно тратить совершенно, а всё остальное, что тратить должно, сократить бы хотя бы вдвое.
