### ISSUE TITLE
Нельзя вызвать два рука-меч генокрадов

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#959]
#### Подробное описание проблемы
Если попытаться вызвать еще одну руку-меч, сменив конечно же активную руку, то старая пропадет и новой не будет
#### Что должно было произойти
Две руки-меч
#### Что произошло на самом деле
Старая рука-меч убралась
#### Как повторить
Вызвать руку-меч, сменить активную руку, активировать еще одну руку-меч

**Comment by WallShrabnic** [comment]
Непонятно, зачем две руки-меча, когда бить можно только одним

**Comment by Lancer411** [comment]
Соединить их в дуалсорд.
