### ISSUE TITLE
Мылом нельзя чистить одежду

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9601]
#### Подробное описание проблемы
Мылом нельзя чистить одежду, вместо этого персонаж ест мыло.
#### Что должно было произойти
Спокойно чишчу одежду
#### Что произошло на самом деле
You unwillingly chew a bit of the soap.
#### Как повторить
держа мыло в руке выбрать любую конечность и нажать по себе

**Comment by AndroBetel** [comment]
у меня всё работает, мыло ты ешь только на харме
