### ISSUE TITLE
Баг с наушниками у АВД

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#9604]
#### Подробное описание проблемы\
Если вначале Раунда поставить себе в желаемых АВД, то при появление (хоть на Исходе, хоть на снежном, хоть на гамме) то он спавниться без наушника авд и в течение всего раунда в таких случаев АВД остаётся без канала глав и сб, это крайне важно для авд взаимодействия с отделами. В шкафчике авд даже нет двух запасных наушников.
Однако наушник есть у авд который летит с велосити. 100% 

#### Что должно было произойти
Спавн с наушником при выборе авд для начала в раунде. Также два запасных наушника( так как на станции могут быть два АВД)

#### Что произошло на самом деле
Спавнит без наушника, запасных в шкафу нет и невозможно достать после нигде на станции.

**Comment by AzzyDreemurr13** [comment]
Проблема не решена, ибо наушников в шкафу авд не появляются, хоть типо добавили, но на деле их нет

**Comment by kiVts** [comment]
Давайте еще добавим что если челу падает раундстарт ивент без наушника то игра  ГОВОРИТ об этом? (только кукле без наушника

**Comment by Deahaka** [comment]
> Проблема не решена, ибо наушников в шкафу авд не появляются, хоть типо добавили, но на деле их нет

Ахахах, так не замержили же))



> Давайте еще добавим что если челу падает раундстарт ивент без наушника то игра ГОВОРИТ об этом? (только кукле без наушника

А давайте удалим. А то слишком сложный и не дружелюбный раундстарт-ивент для игроков))
А если вдруг на меня нападут и я не смогу закричать в радио "ебучий тритор меня убивает"?
