### ISSUE TITLE
Баг в титрах. Нет аккаунтов борготы.

### ISSUE THREAD

**Issue by Leshiy-ART** [TauCetiStation/TauCetiClassic#961]
![image](https://cloud.githubusercontent.com/assets/4739426/21619626/91a0ca10-d201-11e6-89a4-ba32ae53ba20.png)

Собственно все в скриншоте. Не пишет наших героев. (раньше вроде работало, даже если гостанулся)

**Comment by sovok4** [comment]
Если игрок гостанулся из тела, то и не напишет.

**Comment by Damirrus1** [comment]
Ну в этом то и баг

**Comment by Leshiy-ART** [comment]
Вот при малфе, всех боргов перебили и естественно гостанулись. В общем да, всегда писало боргов, даже если они не роли.
И еще, звук двери всегда был таким громким? На фоне остальных звуков это ПШШШ прям в ухо орет...

**Comment by RichardJones1** [comment]
Необходимо проверить.

**Comment by LudwigVonChesterfield** [comment]
Это всё ещё актуально.
