### ISSUE TITLE
ВИРУСОЛОГИЯ - антитела невозможно извлечь 

### ISSUE THREAD

**Issue by azorko9695** [TauCetiStation/TauCetiClassic#9621]
#### Подробное описание проблемы
Уже выработанные в крови антитела невозможно извлечь на центрифуге, всплывает сообщение, будто кровь чистая (см. скриншот). 
#### Что должно было произойти
извлечение антител 
#### Что произошло на самом деле
игра думает что кровь без антител
#### Как повторить
выработать кукле антитела > суйнуть пробирку с антителам в центрифугу > увидеть что кровь без них и огорчиться
#### Дополнительная информация:
Issue reported from  Round ID: 52719 (Tau Ceti Classic (RU))
Testmerges: ```#9509 #9535 #9570 #9592 #9594 ```
Reporting client version: 514.1585

![ишуй](https://user-images.githubusercontent.com/45846852/178579331-d19c1cb1-8019-4126-bec7-69d65073d022.png)

**Comment by Deahaka** [comment]
Создание антител это баг, нужно искать правильный путь для лечения не через это...

**Comment by azorko9695** [comment]
> Создание антител это баг, нужно искать правильный путь для лечения не через это...

без рофлов щас остается только путь через молитвы священнику

**Comment by Deahaka** [comment]
> > Создание антител это баг, нужно искать правильный путь для лечения не через это...
> 
> без рофлов щас остается только путь через молитвы священнику

Ты думаешь ты шутишь, а у него есть возможность создавать вирусы и антитела к ним

**Comment by azorko9695** [comment]
> > > Создание антител это баг, нужно искать правильный путь для лечения не через это...
> > 
> > 
> > без рофлов щас остается только путь через молитвы священнику
> 
> Ты думаешь ты шутишь, а у него есть возможность создавать вирусы и антитела к ним

Уже предвкушаю, как к вирусологу обращаются по этому делу, а он отвечает, мол, "я ничего не могу, нам только всем остается обратиться к богу!

**Comment by azorko9695** [comment]
^^^ 
Так и появился лайфвеб, кста

**Comment by Motzord** [comment]
#9930
