### ISSUE TITLE
Нарезка еды сломана: Все столовые приборы нарезают "неаккуратно"

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#9651]
#### Подробное описание проблемы
Повара и едоки теряют 1 кусочек еды, даже если нарезают еду скальпелем, ножом и подобным. Из-за того, что нормальные ножи имеют свойства CUTTING и Sharp=1, код автоматически ставит им режим "неаккуратной" нарезки - хотя по задумке это должны делать кусачки, стёкла, мечи и прочее.
#### Что должно было произойти
3 кусочка теста вместо 2, при нарезке плоского теста. На 1 кусочек пиццы больше! Не знаю...
#### Что произошло на самом деле
В долгосрочной перспективе - не окупающие себя траты ресурсов на создание чего-то, что включает в рецепт кусочки теста.
#### Как повторить
Повар геймплей
#### Дополнительная информация:
Issue reported from Tau Ceti Classic Sandbox
Testmerges: ```#9509 #9592 #9622 ```
Reporting client version: 514.1583

**Comment by BiQndy** [comment]
чекнул код и хз, там стопудовая опечатка наверно или я не понимаю ход мыслей того, кто это недавно трогал
```
	var/inaccurate = 0
	if(W.get_quality(QUALITY_CUTTING) > 0 || W.sharp)
		inaccurate = 1
```
могу чисто условие заменить на if(!W.get_quality(QUALITY_CUTTING) && W.sharp) и должно быть норм
