### ISSUE TITLE
Аплоад не работает.

### ISSUE THREAD

**Issue by QWxiZX** [TauCetiStation/TauCetiClassic#9655]
#### Подробное описание проблемы
Аплоад ИИ отказывает в доступе Acces Denied старшему инженеру, научному руководителю и капитану.
#### Что должно было произойти
Не отказывает.
#### Что произошло на самом деле
Отказывает.
#### Как повторить
Повторить.

Добавьте алсо пожалуйста чтобы не надо было покупать емаг и hacked ai law и так взламывал.
#### Дополнительная информация:
Issue reported from  Round ID: 52831 (Tau Ceti Classic (RU))
Testmerges: ```#9509 #9592 #9622 ```
Reporting client version: 514.1583

**Comment by volas** [comment]
@AndroBetel

**Comment by volas** [comment]
#9676
