### ISSUE TITLE
Скрипка. Перемешанный порядок нот

### ISSUE THREAD

**Issue by Mandareen** [TauCetiStation/TauCetiClassic#9657]
#### Подробное описание проблемы
Скрипка, в отличии от других музыкальных инструментов, имеет неправильное звучание (неправильный порядок нот). Более низкое звучание начинается с A, а заканчивается высоким G (ABCDEFG - Ля Си До Ре Ми Фа Соль), а должно иметь иной порядок - CDEFGAB - До Ре Ми Фа Соль Ля Си. Проигрываемая нотами музыка имеет искаженное звучание (молчу про сам ужасный звук скрипки). Они не должны идти в алфавитном порядке.
#### Что должно было произойти
Порядок - До Ре Ми Фа Соль Ля Си - плюс уши
#### Что произошло на самом деле
Порядок - Ля Си До Ре Ми Фа Соль - минус уши
#### Как повторить
Сравнить скрипку с другими музыкальными инструментами методом прослушивания. К примеру, пианино имеет плавный подъем звука, а скрипка имеет подъем звука "лестницей"
BPM: 600
Cb1,Cn,C#,D#1,Dn,Db,E#1,En,Eb,F#1,Fn,Fb,G#1,Gn,Gb
A#1,An,Ab,B#1,Bn,Bb
Cb2,Cn,C#,D#2,Dn,Db,E#2,En,Eb,F#2,Fn,Fb,G#2,Gn,Gb
A#2,An,Ab,B#2,Bn,Bb
Cb3,Cn,C#,D#3,Dn,Db,E#3,En,Eb,F#3,Fn,Fb,G#3,Gn,Gb
A#3,An,Ab,B#3,Bn,Bb
Cb4,Cn,C#,D#4,Dn,Db,E#4,En,Eb,F#4,Fn,Fb,G#4,Gn,Gb
A#4,An,Ab,B#4,Bn,Bb
Cb5,Cn,C#,D#5,Dn,Db,E#5,En,Eb,F#5,Fn,Fb,G#5,Gn,Gb
A#5,An,Ab,B#5,Bn,Bb
Cb6,Cn,C#,D#6,Dn,Db,E#6,En,Eb,F#6,Fn,Fb,G#6,Gn,Gb
A#6,An,Ab,B#6,Bn,Bb
Cb7,Cn,C#,D#7,Dn,Db,E#7,En,Eb,F#7,Fn,Fb,G#7,Gn,Gb
A#7,An,Ab,Bn7,Bb
Cb8,Cn,C#,D#8,Dn,Db,E#8,En,Eb,F#8,Fn,Fb,G#8,Gn,Gb
A#8,An,Ab,B#8,Bn,Bb
Cb9,Cn,C#,D#9,Dn,Db,E#9,En,Eb,F#9,Fn,Fb,G#9,Gn,Gb
A#9,An,Ab,B#9,Bn,Bb
#### Дополнительная информация:
В sound/musical_instruments/violin всю эту тонну звуковых файлов необходимо переименовать

**Comment by KIBORG04** [comment]
Нихуя у нас есть скрипачи

**Comment by volas** [comment]
@Mandareen #9680 со следующего раунда будет на сервере, если будет возможность на днях - посмотри, пожалуйста, и скажи если там еще остались проблемы.

**Comment by Mandareen** [comment]
@volas хоть и поздно, но подтверждаю - все отлично работает
