### ISSUE TITLE
Пинпоинтер не работает

### ISSUE THREAD

**Issue by NinjaPikachuska** [TauCetiStation/TauCetiClassic#9658]
#### Подробное описание проблемы
Поинтер не ищет объекты, если их положить в любой контейнер, так как предмет обретает 0 слой и эта проверка просто не проходит.
![image](https://user-images.githubusercontent.com/89906909/179416176-d481341f-9ef3-4220-9743-5cf1f50202bb.png)

![image](https://user-images.githubusercontent.com/89906909/179414403-b0c828e9-44e7-4a08-9301-97f6c1e27fdd.png)

![image](https://user-images.githubusercontent.com/89906909/179414064-dad0533e-ded7-401f-8761-20cd55d216c5.png)

#### Что должно было произойти
Поинтер ищет вещь в сумке.
#### Что произошло на самом деле
Поинтер не может ничего найти.
#### Как повторить
Зайти на тау киту.
#### Дополнительная информация:
Может сделать, чтобы оно указывало на турф объекта через get_turf, а не на сам объект? 
И еще не понятно, зачем добавили ограничение на текущий слой. Проблема была в том, что искало РЦД на ЦК слою. Что мешает заменить проверку на is_centcom_level?

**Comment by volas** [comment]
@simb11 пытается пофиксить в #9620, с попеременным успехом
