### ISSUE TITLE
Последнее задание трейторов некорректно определяется

### ISSUE THREAD

**Issue by Damirrus1** [TauCetiStation/TauCetiClassic#967]
#### Подробное описание проблемы
Последнее задание трейторов должно определяться по редзоне шаттла (т.е. офицерский мини-отсек на шаттле), а не по наличию наручников
#### Что должно было произойти
Тритор должен был соснуть от того, что офицер был добрым и снял наручники, но оставил тритора сидеть в камере
#### Что произошло на самом деле
Тритор сидел под заключением без наручников, но получил гринтекст.
#### Как повторить
Натворить говно за трейтора, быть притащенным офицерами на шаттл в камеру, попросить снять наручники.

**Comment by ZVee** [comment]
А если тритор под видом офицера, которому пришлось по каким-то причинам встать на эти заветные клетки.. Выйдет что он зафэйлит свое задание находясь в этой комнате без наручников.

**Comment by Damirrus1** [comment]
Несколько раз подумает головой, да и не вся красная зона, а та, которая предназначена для зеков.

**Comment by ZVee** [comment]
Тоже самое можно и контр-аргументировать - охранник который освобождает потенциально-опасного преступника от оков, что может привести к ряду непредвиденных ситуаций - вероятно офицер-новичок, которых плохо учился. Никто в здравом уме не будет снимать наручники с заключенного при перевозке.

**Comment by Damirrus1** [comment]
Да.
