### ISSUE TITLE
[Proposal] Снаряжение абдукторов

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#9671]
#### Подробное описание проблемы:

Снаряжение абдукторов не подходит для любой попытки в _агрессивную_ игру, вместо салочек с СБ, «успеют ли они прибежать, перед тем как я украду».

Основными проблемами являются: 
1. Отсутствие защиты от флешек и защиты у шлема как таковой. _(Добавление защиты хотя бы в боевом режими было бы очень кстати.)_
2. Отсутствие защиты от ярких вспышек. _(Хотя вместо очков, можно также обойтись баффом шлема.)_
3. Отсутствие защиты от ударов током. _(Боевые перчатки в помощь.)_
4. Отсутствие защиты всего туловища у брони в боевом режиме.
5. Отсутствие каких либо медикаментов на случай потребности в лечении или боевых стимуляторов для ведения действий против СБ и вооруженного предметами самообороны/оружием экипажа. _(Гранатомёт делает бум по агенту, агента забирают, повторять пока не закончатся гранаты.)_
6. А также, карты спосоьной копировать доступы по типу карты агента синдиката. 
_(Ворующие карты абдукторы — не круто.)_

**Comment by Mercurialaste** [comment]
> Пусть спиздят снаряжение, подходящее для попытки в агрессивную игру.
> Могут найти перчатки, очки, любой шлем на станции - что угодно.
> Это ж ебанные космоцыгане.

Зачем пиздить то, что можно дать раундстартом исключив ситуации, по типу тех, когда раундстартом летят к ХоСу или Капитану за их шмотом?
Они как бы ученые, а не цигане.

**Comment by QWxiZX** [comment]
> Зачем пиздить то, что можно дать раундстартом исключив ситуации, по типу тех, когда раундстартом летят к ХоСу или Капитану за их шмотом?

зачем играть вообще
Выбираешь агрессивную игру (которую не поддерживает педальсостав, кстати) - иди и готовься. Если абдукторы смогут раундстартом с ноги шлюз выбивать без каких-либо предпосылок и резать СБ - это вот вообще не весело.

**Comment by Chip11-n** [comment]
Добавлено
