### ISSUE TITLE
Консоль загрузки законов не работает.

### ISSUE THREAD

**Issue by Kenshy4420** [TauCetiStation/TauCetiClassic#9675]
#### Подробное описание проблемы
Сменить законы посредством консоли из аплоуда невозможно.
#### Что должно было произойти
При взаимодействии с консолью, должен был всплыть меню выбора активного ИИ
#### Что произошло на самом деле
Access denied
#### Как повторить
Быть РД и выше, и попробовать сменить ИИ/Боргу законы.
#### Дополнительная информация:
Очередной ПР, который вмержили без теста.

**Comment by Mercurialaste** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/9655

_(В названии стандартного ишшуя не обязательно писать баг, по умолчанию, любой ишшуй — баг, только ишшуи с [Proposal] помечаются соответственно.)_

**Comment by Kenshy4420** [comment]
Сделано

**Comment by volas** [comment]
Закрываю в пользу #9655
