### ISSUE TITLE
Смешной баг ИИ.

### ISSUE THREAD

**Issue by NinjaPikachuska** [TauCetiStation/TauCetiClassic#9678]
#### Подробное описание проблемы
Итак, ставим камеру на открытый шкаф. Просим закрыть его. Глазик закрывается в шкафу, а после обретает коллизию. Через него нельзя пройти, через него не пролетают пули и лазеры. Вызывается эта проблема при любом forceMove глазика, хоть get mob через педальную панельку.
![image](https://user-images.githubusercontent.com/89906909/179632154-3f7b1c9a-cafb-4d73-878c-5226c2cf587e.png)
![image](https://user-images.githubusercontent.com/89906909/179632301-abbec985-0f7b-431a-8889-6a5bc1e3894e.png)

#### Что должно было произойти
У ИИ нету смешного бага.
#### Что произошло на самом деле
Он есть.
#### Как повторить
Описал выше.
#### Дополнительная информация:
Подобное поведение еще вызывает кабинка в морге.

**Comment by Deahaka** [comment]
Вот так ИИ должен защищать собой людишек. Жаль делать это везде не получится

**Comment by Mercurialaste** [comment]
Из того что я знаю, похожее будет если как-то криво голограмму вызвать. 

По карцней мере у меня происходили моменты, когда космонавтики ТОЛКАЛИ голограмму или невидимый глаз ИИ туда сюда, сами того не понимая.

**Comment by Mercurialaste** [comment]
> Такая же проблема и с камерами ксенобио.
> ![image](https://user-images.githubusercontent.com/89906909/180241032-d0262b7a-71ed-49bf-81f1-0efcb0df4824.png)

Попробуй ещё адвенсед камеру и камеру блоба

**Comment by TheLone1y** [comment]
Пинайте этот баг он деструктивен

**Comment by KIBORG04** [comment]
Лайкаем

**Comment by Motzord** [comment]
Лайкаем
