### ISSUE TITLE
У рефлект блоба нет спрайта

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9682]
#### Подробное описание проблемы
У рефлект блоба нет спрайта
#### Что должно было произойти
Спрайт есть
#### Что произошло на самом деле
Спрайта нет
#### Как повторить
Посмотрите на рефлект блоба в игре

**Comment by Udokun** [comment]
Проверено с @Rahmanio, спрайты появляются.

**Comment by Motzord** [comment]
Есть, закройте
