### ISSUE TITLE
У РД на Гамме нет платы сброса протоколов безопасности

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation/TauCetiClassic#9685]
#### Подробное описание проблемы
При игре на роботехнике на карте Гамма, нет платы сброса протоколов безопасности для юнитов и т.д. А без неё не видать юнита сб когда он нужен по запросу ИИ или Главы

#### Что должно было произойти
Плата на Гамме должна появлятся в кабинете РД как на Исходе.

#### Что произошло на самом деле
Платы нет на Гамме у РД. А на Исходе есть

#### Как повторить
-
#### Дополнительная информация:
-

**Comment by Deahaka** [comment]
Гамма - идеальная карта?

**Comment by Mercurialaste** [comment]
> Гамма - идеальная карта?

Нет, там есть другие режимы, кроме эксты.
