### ISSUE TITLE
[Proposal] Убираем абдукторов из основной ротации режимов. 

### ISSUE THREAD

**Issue by SweetMaurse** [TauCetiStation/TauCetiClassic#9711]
#### Подробное описание проблемы

Абдукторы сами по себе - стали (каким и были) унылым двести раз переваренным калом.

#### Что должно было произойти

Юхууу!!! Абдукторы это весело! 

#### Что произошло на самом деле

Фу.. Абдуууукторы.. Я в крио. 

#### Как повторить

Запустить раунд с абдукторами и грустить.. 

#### Дополнительная информация:
А если серьёзно. Как по мне стоит убрать абдукторов из основной ротации и добавить их как ебент по типу воксов. Это решит проблему с унылостью и позволит игрокам меньше по этому поводу стрессовать. ( мы же знаем наше комьюнити.)
Форумник с отвратительным голосованием: https://forum.taucetistation.org/t/golosovanie-a-davajte-udalim-abduktorov/34847

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/golosovanie-a-davajte-udalim-abduktorov/34847/8

**Comment by TheLone1y** [comment]
Спедалился.

**Comment by Venngedi** [comment]
#11483 Можно закрыть.
