### ISSUE TITLE
[Proposal] Нимфа хочет помочь ботанику.

### ISSUE THREAD

**Issue by BunkyFly** [TauCetiStation/TauCetiClassic#9713]
В вики написано, что нимфы это мелкие помощники, но на самом деле они не играют никакой роли без госта. 

Я предлагаю сделать нимфам маленькими приоритеты, пока они пустые, по типу нимфы занимаются ботаникой и как только появляется сорняк или растению нужно удобрение, нимфа подбегает и начинает жевать сорняки или поливать растения питательными веществами. 

Например, ботаник бросил нимфу в гидропонике и пошел воевать с нюкой, а нимфа как фармбот начинает ухаживать за растениями не давая им погибнуть.

**Comment by BunkyFly** [comment]
@LudwigVonChesterfield  Ну как идея?

**Comment by LudwigVonChesterfield** [comment]
я же лайк поставил, кодь

**Comment by LudwigVonChesterfield** [comment]
заодно мб сделаешь нам с нуля нормальную систему ИИ для мобов :)

**Comment by BunkyFly** [comment]
> заодно мб сделаешь нам с нуля нормальную систему ИИ для мобов :)

Тестирвал на локалке код на помощь ботанику, нашел пару смешных багов.

Диона не умеет различать амброзии от обычных растений, поэтому удобряет все, что растет на плантациях.

Диона не может обходить преграды, я поставил загородку из столов, а она не прошла сквозь них.

Диона триггерится на старую ботанику и упирается в стену и перестает двигаться.

Если взять диону в руки, то она перестанет удобрять растения и кушать сорняки, став снова бесполезной. 

Вообщем, я дропнул попытку ИИ для дион, ведь с моим уровнем кодинга это слишком сложно.

**Comment by BunkyFly** [comment]
А вообще можно просто взять код фармбота и немного переделать его и вуаля
