### ISSUE TITLE
Скролл мага игнорирует девайс на блокировку телепорта

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/TauCetiClassic#9719]
#### Подробное описание проблемы
Скролл мага позволяет телепортироваться в защищенные телепорт джаммером места
@volas

#### Что должно было произойти
Скролл мага не должен телепортировать в защищенные места

#### Что произошло на самом деле
Скролл мага телепортирует в защищенные места

#### Как повторить
Зайти за мага, взять скролл телепортации и выбрать в нем капитанскую.

**Comment by volas** [comment]
Ох, кто это всё писал, почему у нас так много независимых сущностей/методов телепортации

**Comment by Deahaka** [comment]
Абдукторы тоже летают с игнором штуки, которая наверное только для них и нужна была...
