### ISSUE TITLE
Дюп ресурсов шаловливыми ручками

### ISSUE THREAD

**Issue by SiveanBen** [TauCetiStation/TauCetiClassic#9726]
#### Подробное описание проблемы
При нажатии альт клика по стаку ресурсов,с двумя занятыми руками, и попытке вытащить часть из стака, ресурс не уменьшился, разделившись на две части,  а увеличился.
#### Что должно было произойти
Большая часть ресурса остаться в руке меньшая упасть на пол.
#### Что произошло на самом деле
Весь ресурс упал на пол при экзамайне показывая что стало больше на ту величину которую вытаскивали. 
#### Как повторить
Взять в одну руку любой итем, в другую нужный ресурс количество которого от двух и выше. нажать Альт+лкм по ресурсу, и вытащить часть меньше полного количества ресурса. Поднять дюпнутый ресурс с пола под вами. ~~Повторить пока карго не получит 3 морбилиона на счёт~~
#### Дополнительная информация:
Issue reported from  Round ID: 53055 (Tau Ceti Classic (RU))
Testmerges: ```#9592 #9618 #9656 ```
Reporting client version: 514.1571

**Comment by Tobyyyan** [comment]
Это не только на ресурсах. Где стаки есть, там и присутствует дюп.

**Comment by pro100kotah** [comment]
Можно и не занимая руки. Борги могут просто прямо на полу бесконечно дюпать ресурсы, что могут стакаться. Главное чтобы в стаке было хотя бы 2 единицы. Что угодно дюпается.

**Comment by Deahaka** [comment]
Не актуально кстати. Никаких дюпов не обнаружено.
