### ISSUE TITLE
Невидимый обрез двустволки

### ISSUE THREAD

**Issue by Pivo24** [TauCetiStation/TauCetiClassic#9728]
#### Подробное описание проблемы
Двустволка НЕВИДИМАЯ! Не обрезайте её пилой а не то получите НЕВИДИМОЕ ОРУЖИЕ!
#### Что должно было произойти
Не знаю наверное обрез со спрайтом
#### Что произошло на самом деле
X-Files
#### Как повторить
Режьте двустволку пилой
#### Дополнительная информация:
я ещё её слагами зарядил ухахахаха

**Comment by Deahaka** [comment]
Когда в слот брони кладешь или вообще инхенды невидимые?

**Comment by Pivo24** [comment]
Вообще когда спавнится как предмет.

Инхенды видимые.
