### ISSUE TITLE
У большинства профессий навык мelee равен нулю

### ISSUE THREAD

**Issue by simb11** [TauCetiStation/TauCetiClassic#9737]
#### Подробное описание проблемы
У большинства профессий навык мили равен нулю, из-за чего всякие инженеры, медики и ТД наносят оружием ближнего боя лишь 85% урона
#### Что должно было произойти
Нет навыка только у клоуна, мима и голема
#### Что произошло на самом деле
У почти всех проф есть дебаф к урону

**Comment by RONSI7** [comment]
Стоп, так ВСЕ со стандартным навыком наносит лишь определенный процент урон от базового? Если так и задумано, то это полная фигня...А сколько тогда наносит клоун с минусовым навыком, 25% урона от первоначального?

**Comment by simb11** [comment]
0 уровень это минус 15 процентов к урону, 1 уровень как раз таки и должен быть стандартным, ибо не даёт ни бонусов, ни дебафов к урону

**Comment by Mercurialaste** [comment]
Скорее всего, Дюшесс когда делал рефактор скиллов не поменял или не захотел менять.
Или это так и задумано, тогда это не bug, а proposal.
