### ISSUE TITLE
[Proposal] Занерфить урон золотого петушителя

### ISSUE THREAD

**Issue by AirBlack** [TauCetiStation/TauCetiClassic#9751]
#### Подробное описание проблемы
У золотого петушителя высокий урон. В руках того же магуса - 2-3 удара - перелом, крит, иногда артериалка(даже в шлеме). В последнее время не видел магов НЕ пожарных. Ладно бы маги использовали петушитель когда у них цель его спиздить. Но петушитель берут все маги независимо от цели.
Пусть уж берут топор, дамаг тоже высокий, но он блочит вторую руку + может застрять. Вполне норм.
#### Что должно было произойти
Маг занимается магическими штучками. Кастит фаерболы, аркейн багажи, стреляет из стаффов. Таймстоп заварудо кидание ножей. Пусть что-нибудь прикольное придумывают.
#### Что произошло на самом деле
Таймстоп(не обязательно) + петушитель, ничего нового.
#### Как повторить
Взять за мага золотой петушитель и булить бедных кадетиков.
#### Дополнительная информация:
Я сегодня еще не какал. Обновлю информацию как покакаю.

**Comment by Mercurialaste** [comment]
Мб, если проблема только в маге, выкрутить ему скилл мили на 0?
-15 там, все дела. 

Если вообще упоротся, дать неуклюжесть клоуна, чтобы уж точно маг не мог в нормальное мили. С огнестрелом так вроде уже сделали.

**Comment by AirBlack** [comment]
Насколько я помню то во ВСЕХ пушках проверка на мага идет(у базового класса там special_check прок, в котором чекается маг), т.е. маг не может пользоваться любым огнестрелом. А так да, можно скилл понизить на мили, тоже решение.

**Comment by Tap0r** [comment]
В ваульте теледжэмм стоит вроде. Который телепорты блочит. Думаю этого уже более чем достаточно будет, чтобы маги перестали его брать. А нерфить урон бред полный.

**Comment by AirBlack** [comment]
кнок кнок открывает и разболтирует двери, они заходят туда как домой

**Comment by ViDLiathan** [comment]
Заприте ваулт на бластдоры с кнопками с двух сторон и третья в каюте капитана.

**Comment by AirBlack** [comment]
Я пересмотрел свое мнение по этому поводу, магусы берут петушитель потому что видят мало вариантов того как выйграть т.к. сам магус очень хрупкий и легко сливается. Я думаю, лучше больше защитить мага(по типу ПРа о щите), чтобы они не боялись брать разные интересные спеллы и меньше действовать по мете т.к. живучесть больше и шансов слиться меньше, чем отбирать у хрупких магов то, что позволяет им выживать сейчас.
