### ISSUE TITLE
Блобернауты дублируются в титрах

### ISSUE THREAD

**Issue by Akellazp** [TauCetiStation/TauCetiClassic#9772]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/47355061/182850787-c5aa1af8-855d-49e1-87fc-9e0216d7c9e9.png)

#### Что должно было произойти
Не дублируются
#### Что произошло на самом деле
Дублируются
#### Как повторить
Вероятно сделать блобернаутов
#### Дополнительная информация:
Issue reported from  Round ID: 53239 (Tau Ceti Classic (RU))
Testmerges: ```#9656 #9727 #9736 #9756 #9761 #9765 ```
Reporting client version: 514.1569

**Comment by TheLone1y** [comment]
Расскажу что произошло, блоббернауты не умирают, они входят в спячку и если поставить ноду рядом оживут, я просто перезаходил в тело

**Comment by Chip11-n** [comment]
Это фикшено
