### ISSUE TITLE
пропадающие карты из банкомата

### ISSUE THREAD

**Issue by justmaydo** [TauCetiStation/TauCetiClassic#9777]
#### Подробное описание проблемы
 
Когда ты вынимаешь карту из банкомата держа что нибудь в руке - карта пропадает.

#### Что должно было произойти

Карта падает на пол под тобой.

#### Что произошло на самом деле

Карта удаляется.

#### Как повторить

Взять предмет в руку, достать этой рукой карту из банкомата.

#### Дополнительная информация:
Issue reported from  Round ID: 53248 (Tau Ceti Classic (RU))
Testmerges: ```#9656 #9727 #9736 #9756 #9761 #9765 ```
Reporting client version: 514.1584

**Comment by Pirsnya** [comment]
а я голову ломал кто мог спиздить если никого рядом не было
