### ISSUE TITLE
РИПЛИ ломает тени

### ISSUE THREAD

**Issue by WallShrabnic** [TauCetiStation/TauCetiClassic#979]
#### Подробное описание проблемы
При входе/выходе из меха полностью ломаются тени
#### Что должно было произойти
Тени не должны ломаться
#### Что произошло на самом деле
Тени сломались
#### Как повторить
Сесть в РИПЛИ, и, возможно в другого меха
#### Дополнительная информация:
N/A

**Comment by Lancer411** [comment]
Какая версия бйонда?
