### ISSUE TITLE
Абдукторы-не абдукторы(люди?)

### ISSUE THREAD

**Issue by Rahmanio** [TauCetiStation/TauCetiClassic#9807]
#### Подробное описание проблемы
В этом раунде абдукторы стали людьми и ничего не могут делать, а также в одной фракции?
#### Что должно было произойти
Всё нормально
Абдукторы это
 /mob/living/carbon/human/abductor
#### Что произошло на самом деле
Абдукторы это
 /mob/living/carbon/human
#### Как повторить
Режим абдукторов.
#### Дополнительная информация:
Issue reported from  Round ID: 53415 (Tau Ceti Classic (RU))
Testmerges: ```#9656 #9727 #9736 #9755 #9756 #9761 #9765 ```
Reporting client version: 514.1585

**Comment by volas** [comment]
https://github.com/TauCetiStation/TauCetiClassic/pull/9645#discussion_r933420969

как выяснилось, раса важна. Тут

https://github.com/TauCetiStation/TauCetiClassic/blob/2674c2165991fdf94060537f45fed7209b4f423b/code/game/gamemodes/roles/abductor.dm#L33-L36

Выставляется species, но тип не трогается и возможно может остаться старый. Нужно выставлять тип, или поправить сам ``isabductor``, и аннигилировать 5 (!!!) оставшихся отдельных методов ``proc/IsAbductor``. Этот режим писали странные люди.

**Comment by Rahmanio** [comment]
#9808 фиксит данную проблему, вроде больше не было раундов с плохими абдукторами. Сами решите закрыть или нет.
