### ISSUE TITLE
[Bug] Воткни меня в стену помпа!

### ISSUE THREAD

**Issue by TheLone1y** [TauCetiStation/TauCetiClassic#9816]
#### Подробное описание проблемы
При залезании в трубу с зажатым диагональным движением можно пропихнуться в ближайшию стену
#### Что должно было произойти
При залезании в трубу ты идешь по прямой туда, куда ведет труба
#### Что произошло на самом деле
Человечик в стене из-за зажатых двух клавиш
#### Как повторить
![2022-08-13_14-23-58](https://user-images.githubusercontent.com/76026000/184475716-12cb6eec-d9fc-4e25-bce8-f9dfe27ad3a5.png)
![2022-08-13_14-25-21](https://user-images.githubusercontent.com/76026000/184475725-dbc0a8ca-8a96-438b-880a-018c46af2b00.png)

#### Дополнитель
![2022-08-13_14-25-51](https://user-images.githubusercontent.com/76026000/184475737-3db071f1-6c96-4c72-b3fe-8228f0ce5e03.png)
ная информация:

**Comment by TungstenOctopus** [comment]
Как повторить это какие кнопки нажать

**Comment by TheLone1y** [comment]
> Как повторить это какие кнопки нажать

Диагональное движение, угадай какие именно две клавиши нужно зажать что бы двигаться диагонально...

**Comment by Rahmanio** [comment]
#8393
уже было кстати, не заметил.
дубликат получается.

**Comment by Rahmanio** [comment]
накидайте лайков крч на этот ишуй
