### ISSUE TITLE
Armband selection bug

### ISSUE THREAD

**Issue by Elisei24** [TauCetiStation/TauCetiClassic#9818]
#### Подробное описание проблемы
В меню Loadout нельзя выбрать себе нарукавную повязку, если ты не сотрудник СБ, хотя в списке представлены повязки для всех отделов (медики, инженеры, учёные, карго). Получается, СБшник может носить повязку учёного на руке, а сам учёный нет.
#### Что должно было произойти
Игрок выбирает повязку соответствующую его отделу и получает её
#### Что произошло на самом деле
Если игрок не зашёл за СБ - повязку он не получает, вне зависимости от её вида
#### Как повторить
Выбрать повязку в Loadout -> Accesories и зайти в раунд не за сотрудника СБ.
#### Дополнительная информация:
Issue reported from  Round ID: 53472 (Tau Ceti Classic II (RU))
Testmerges: ```#9656 #9727 #9756 #9761 #9765 #9779 #9783 #9808 ```
Reporting client version: 514.1578

**Comment by AndroBetel** [comment]
не баг, повязка показывает, какой отсек офицер защищает

**Comment by Deahaka** [comment]
Это вроде из древнего ПРа, где в каждом чекпоинте был свой закреплённый офицер, отвечающий за охрану отделов. Зачем другим эти повязки?

**Comment by RONSI7** [comment]
> Зачем другим эти повязки?

Единственное, что приходит в голову - сотрудники, что не носят одежду своего отдела, могут надевать повязки, что бы другие без экзейма могли понять из какого отдела сотрудник.

**Comment by TheLone1y** [comment]
Косметика

**Comment by Elisei24** [comment]
В таком случае закрываю, раз не баг :)
