### ISSUE TITLE
Debrain->Rebrain. Педальные тонкости.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#982]
#### Подробное описание проблемы
Если вырезать мозг у одного человека и пересадить в голову иного человека, ему выдается 200 брейндамага на мозг, который невозможно убрать
#### Что должно было произойти
Должно быть выставлено значение - 0/60/120/20000 , а так же должна быть возможность убрать повреждение мозга при помощи операции/химикатов.
#### Что произошло на самом деле
У человека 200 единиц урона на мозг которые не убрать.
#### Как повторить
Произвести пересадку мозга.
#### Дополнительная информация:

![](http://image.prntscr.com/image/3495f5765dd045958ac7674cf64401b3.png)
(Скриншот был сделан до ZVE UPDATE, теперь там красуется значение в 200 единиц урона на мозг)

**Comment by Dennok** [comment]
Да, еще при протезировании конечности на протезе остается урон который был на протезированной конечности до протезирования.

**Comment by Dennok** [comment]
Это вообще очень длинная история про дамаг и потерянные конечности.

**Comment by Skippeer12** [comment]
Спасибо, Зве. Ты таки успел.
Теперь дают 200 брейндамага при пересадке мозга.
![image](https://user-images.githubusercontent.com/18488106/35794108-15361f62-0a5d-11e8-9bbb-2b247786a5fc.png)

Ходят слухи что он не лечится.

**Comment by Skippeer12** [comment]
#1733

**Comment by Motzord** [comment]
Я не знаю как, но оно видимо пофиксилось. Жаль
