### ISSUE TITLE
[Proposal] Skill for dummys

### ISSUE THREAD

**Issue by WatlerJe** [TauCetiStation/TauCetiClassic#9823]
#### Идея
![image](https://user-images.githubusercontent.com/19796920/184536575-8ae371a2-d5be-44fc-b609-a15ae9ea19e2.png)

Книги позволяющие после прочтения повысить скилл до первого уровня.
#### Зачем
В связи с тем, что текущая система скиллов делает упор на внутриигровую кооперацию, привязывая скиллы к профессии и не обладает гибкостью позволяющая игрокам самим распределить навыки в процессе создания персонажа. Возникает потребность в возможности получения базового уровня скиллов в процессе игры. Импланты скиллов от части решают эту проблему, но имеют свои нюансы: 
* Все так же требуют кооперации между игроками которая не всегда возможна; 
* Количество имплантов ограничено; 
* Есть шанс получения урона персонажу, что вынуждает игрока к кооперации c медиками;
* Имплант может быть уничтожен, что ведет к потери умений;
* Непредсказуемость времени затрачиваемого на процесс, все зависит от игроков и рандома.

Книги позволяют обойти обозначенные выше препятствия (Если книги будут в библиотеке в открытом доступе), требуя только лишь время на чтение. 
#### Как это работает
На станции в библиотеке или на стеллажах разных отделов будут лежать книги на каждый скилл который есть на данный момент в игре. Персонажу потребуется время для чтения (от 2х минут), прогресс чтения желательно сохранять (как в Зомбоиде).
Книга не исчезает после прочтения, у нее нету ограничения на использования.
#### Что для этого требуется
* В статье на вики посвященной умениям персонажей, стоит добавить конкретно в цифрах, что дает каждый уровень навыка. Чтобы иметь четкое представление о навыках, исходя из этого возможно потребуется их изменение.
* Нарисовать спрайты книг (могу это сделать).
* Код.

**Comment by volas** [comment]
Можно было бы это не только с книгами, но и на практике. Если несколько раз за раунд тыкаешься в определенную сферу с долгими прогрессбарами - то будет начинать немного разбираться.

**Comment by WatlerJe** [comment]
В варианте с обучением нужно учитывать длительность раунда, в среднем это полтора часа. Исходя из этого надо понимать до какого уровня персонаж сможет натренироваться, есть ли ограничение на прокачку и т.п.

**Comment by volas** [comment]
*до 1 уровня после минут 5 прогрессбаров или что-то такое, не более

**Comment by Lafrien** [comment]
Нужно будет так же разделить время по уровням навыков. Например с 3 по 4 уровень будет занимать времени больше, чем со 2 по 3.
Но что делать теми навыками, что не имеют прогресс-бара как к примеру вождения Экзоскелетами? Добавлять книгу по вождению экзоскелетами и добавить возможность проходить порог книгой, или добавлять уровень по времени затраченному внутри экзоскелета? Одно будет приятнее в игровом процессе, а другое легче закодить.

**Comment by volas** [comment]
> Например с 3 по 4 уровень будет занимать времени больше, чем со 2 по 3.

Стать Novice за раунд ок, Trained уже нет.

**Comment by WatlerJe** [comment]
Читайте внимательно, книги дают только первый уровень "Novice". Для более крутой прокачки подойдут импланты.

**Comment by Mercurialaste** [comment]
> Для более крутой прокачки подойдут импланты.

Импланты накладывают скиллы не учитывая уже имеющиеся.
Т.е. если ставить СЕ макс скилл инженерии, то нужно потратить 5 очков на импланте, а не одно.
*(Если я правильно понял, предполагалось, что чел сможет книгой поднять себе первый уровень чего-либо, а потом уже сможет прокачать скилл дальше.)*

**Comment by volas** [comment]
> Типа нужно суммарно 5 минут делать вещи и тогда апнется скилл?

да, и только от 0 до 1. 

Тут какой-то небольшой мискомуникейшен. Я поддерживаю идею получения ранга Novice от зеро в течении раунда, будь то по книге, или как-то на практике. Это будет реалистично, и кроме небольшого удобства для игрока ни на что больше особо не влиять. А если нужна прокачка дальше - то ищите уже импланты.

**Comment by RONSI7** [comment]
Лучше все развивающие книги разместить в библиотеке, что бы она перестала быть куском карты, где очень удобно прятать или делать трупы, а стала местом для саморазвития вроде качалки. Книги сделать чем-то вроде гантель, я имею ввиду вещами с помощью которых можно улучшать свою куклу, но которые никак не восполнить.

Потерял руководство для чайников? Ну тогда все, второе такое на станции ты нигде не найдешь. Таким образом профессия библиотекаря наконец-то приобретет значимый смысл, ведь будем честными, сейчас его совсем немного... Если тебе нужна какая-то книга, то ты можешь сам ее найти и распечатать себе - библиотекарь во всем этом ненужный посредник.

А так, именно он будет тем, кто следит, что бы никто не выносил эти книги за пределы библиотеки. Подумайте сами, на книги повышающие скиллы, точно будет большой спрос и если отдать кому-то вынести книгу с собой, то в 99% случаев он ее уже не вернет... А другой у тебя нет, что делать? Как же другие читатели?

Поэтому если хочешь повысить себе скилл, то будь добр делать это в библиотеке, а после прочтения вернуть ее на место или библиотекарю в руки.

**Comment by WatlerJe** [comment]
> Импланты накладывают скиллы не учитывая уже имеющиеся.

Bruh.

> (Если я правильно понял, предполагалось, что чел сможет книгой поднять себе первый уровень чего-либо, а потом уже сможет прокачать скилл дальше.)

Да идея заключается именно в получении первого уровня навыка, не углубляясь дальше в специальность. Например шахтерам достаточно иметь первый уровень инженерии ибо они часто работают с машинерией. Или же подготовка эрзац специалиста на какую-либо должность.

**Comment by WatlerJe** [comment]
@Dushess0 Если соберешься притворять эту идею в жизнь, то напиши мне по поводу спрайтов.

**Comment by TungstenOctopus** [comment]
Проблема только в том, что единичный скилл так плох, что не сильно отличается от нулевого по ощущениям.

**Comment by Dushess0** [comment]
> Проблема только в том, что единичный скилл так плох, что не сильно отличается от нулевого по ощущениям.

Это поправим

**Comment by LudwigVonChesterfield** [comment]
#9388
