### ISSUE TITLE
Баго-фича с ID-Консолью.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#983]
#### Подробное описание проблемы
Ввод дополнительных знаков в консоли не возможен.
НО.  Если вводить просто знак " ' ", то имя стирается, если данный знак перед и после слова.
Если же он находится по середине, то после смены имени владельца карты знак меняется на " ` ".
И редактирование карты становится невозможным и консоль протестующе пищит.

![](http://image.prntscr.com/image/08f315dc99004a0ba02ce7c5248d5b32.png)

#### Что должно было произойти
Должно было измениться имя.

#### Что произошло на самом деле
Невозможно его сменить.

#### Как повторить
Ввести любое имя с знаком " ' " внутри имени.

#### Дополнительная информация:
На другие знаки вроде как не распространяется.

**Comment by SpaiR** [comment]
Поигрался с консолью и так, и этак. Вставлял `'` в середине имени, в начале, в конце. Да, заменяется на `, но это необходимо. Во всё остальном всё ок, имя меняется, консоль работает. @P-20 ещё актуально?

**Comment by P-20** [comment]
Пытаюсь изменить/стереть "Polin", консоль пищит.
http://image.prntscr.com/image/eb4ae2fd95d44a65bc05fffe656f26e2.png

**Comment by P-20** [comment]
При попытке изменить/стереть "Polin" консоль пищит. http://image.prntscr.com/image/eb4ae2fd95d44a65bc05fffe656f26e2.png

**Comment by RichardJones1** [comment]
Необходимы тесты

**Comment by volas** [comment]
Проблема скорее всего связанна с санитайзами

**Comment by Motzord** [comment]
Теперь бульон поддерживает юникод и странные символы, баг вроде как отсутствует теперь.
