### ISSUE TITLE
Баг с Антагхудом/Шадоулинги

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#984]
#### Подробное описание проблемы
Если за трелла (Шадоулинга?) перезайти в раунд, то пропадает антаг-худ данного режима у ролей.
Появляется лишь спустя долгое время по неизвестной причине.

#### Что должно было произойти
Вы должны видеть других треллов и шадоулингов после перезахода.

#### Что произошло на самом деле
Нигде и даже на вас не отображается иконка о том что вы трелл.
#### Как повторить
Вы должны стать Треллом/Быть шадоулингом, отключиться от сервера и зайти заного. Вы не будете видеть никого из своих антагов.
#### Дополнительная информация:
Аналогичная проблема с антагхудом гангеров.
После перезахода пропадают иконки

**Comment by Dennok** [comment]
Новых, вроде, можно было видеть.
