### ISSUE TITLE
[bug] ОЧЕРЕДНОЙ БАГ С ЧЕРНЫМ ПОЛОМ

### ISSUE THREAD

**Issue by Pirsnya** [TauCetiStation/TauCetiClassic#9846]
#### Подробное описание проблемы
Есть предмет, так называемый "item" при ПКМе. Если этим айтемом ткнуть по полу, то будет это - скрин в коментах
Проблему с дюпом этого "айтема" с мусором решили, теперь он появился на астероиде. Шахтёр просто копал руду и наткнулся на "item" без спрайта, взял в руку, ткнул в пол и получил СНОВА неПКМищийся пол.
#### Что должно было произойти
Вероятно item не должен давать безэкземайнищийся пол
#### Что произошло на самом деле
Айтем даёт чернющий пол
#### Как повторить
Откопать item в коде и ткнуть в пол
#### Дополнительная информация:
Issue reported from  Round ID: 53546 (Tau Ceti Classic (RU))
Testmerges: ```#9727 #9779 #9783 #9808 ```
Reporting client version: 514.1575

**Comment by Pirsnya** [comment]
![(null)scrnshot1](https://user-images.githubusercontent.com/35347896/184838462-68ed8b76-d37c-452f-bee8-a161b8242b54.png)

**Comment by volas** [comment]
ты не смотрел type итема в vv?

**Comment by Pirsnya** [comment]
> ты не смотрел type итема в vv?

могу искусственно попробовать его создать или найти сейчас пока не поздно

**Comment by Pirsnya** [comment]
> ты не смотрел type итема в vv?

@volas полагаю https://github.com/TauCetiStation/TauCetiClassic/pull/9722/files это имеет место быть здесь, но не уверен, может ли с астероида выпасть этот предмет

**Comment by Pirsnya** [comment]
> https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/mining/mine_turfs.dm В этом вся проблема ![image](https://user-images.githubusercontent.com/89906909/184845584-c6efec60-a6e4-4dbf-a26c-a00abfb524e5.png)

Спасибо, закрываю
