### ISSUE TITLE
В новых ПДА не отображается наличие карты, при осмотре игроков.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#985]
#### Подробное описание проблемы
Если всунуть карту в ПДА то это теперь отображается визаульно, но лишь для самого игрока.
При экзамайне обычный ПДА и с картой, выглядят одинаково.

#### Что должно было произойти
Должно быть видно что в ПДА карты.

#### Что произошло на самом деле
Отображается пустой ПДА

#### Как повторить
Заэкзамайнить игрока  у которого пда без карты, а затем когда пда с картой.

**Comment by DeadOberst** [comment]
Пусть это будет фичей.
