### ISSUE TITLE
[Proposal] Пипетка для рисования

### ISSUE THREAD

**Issue by IlinMihail** [TauCetiStation/TauCetiClassic#9852]
Предложение:  добавить пипетку для рисования, дабы при клике на пиксель в чат выводилась кодировка цвета этого пикселя. В плане кода фича элементарная, а рисование сделает в 150 раз проще

**Comment by KIBORG04** [comment]
> В плане кода фича элементарная,

так сам закодю

**Comment by DarthSidiousPalpatine** [comment]
Фу как тупо, выводить кодировку в чат. Сделайте чтобы выводилось сразу на холст или как там работает рисование.

**Comment by DarthSidiousPalpatine** [comment]
Сделать предмет - ручка для рисования, тыкаешь по любому пикселю в игре и получаешь его цвет. Даже пикселю худа, хммммм, наверное, можно как-то убрать возможность тыкать по худу. Типа: "еггог вы не можете получить цвет воздуха"

**Comment by IlinMihail** [comment]
> > В плане кода фича элементарная,
> 
> так сам закодь

спасибо за совет киборг, обязательно воспользуюсь
