### ISSUE TITLE
[Proposal] Портировать больше растений в ботанику из других билдов

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#9855]
#### Подробное описание проблемы
[Когда говорят о Парадизах, почему-то указывают в плюсах, что там много мутаций](https://forum.taucetistation.org/t/vashe-mnenie-o-serverah-paradaiz-ili-zhe-ss220/35100/25). Чтобы нам не отставать, можно спортировать [разнообразие растений с ТГ](https://github.com/tgstation/tgstation/tree/40d89d11ea4a5cb81d61dc1018b46f4e7d32c62a/code/modules/hydroponics/grown):
![0101010](https://user-images.githubusercontent.com/96499407/185090982-ad5b89d7-a9d9-470d-9e93-bcc720971e4f.png)

Причём не обязательно портировать так же, как и там. Можно взять спрайт и создать совершенно другое растение. А если есть желание, можно нарисовать яблоне новые плоды (например подсолнух на яблоне, прикольно ж наверное?) и сделать это мутацией яблони или подсолнуха, которое даёт в 3 раза больше урожая. Но не нужно делать вот такого рода вещи-заменители:
![qwerq](https://user-images.githubusercontent.com/96499407/185092140-e9f728d1-b79a-4a7b-ba5f-6530a89bcf72.png)
Этим очень часто никто никогда не пользуется. Колличество важнее, чем качество, в этом аспекте игры.

**Comment by BunkyFly** [comment]
Лучше бы семена дион в ботанику вернули

**Comment by Deahaka** [comment]
Я передумал, эта идея бессмысленна так как у нас есть разнообразные спрайты и древнекод тех самых растений других билдов но мы его не используем
