### ISSUE TITLE
Неверное время создания записи в СБ консоли.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#986]
#### Подробное описание проблемы
Сделать запись игроку. Время отображается текущее а не игровое.

#### Что должно было произойти
Должно отображаться игровое время.

#### Что произошло на самом деле
Made by Unknown (Captain) on Mon Jan 09 20:25:20, 2561
bla-bla 
Текущее время на данный момент ИРЛ.
Игровое время - 12:28

#### Как повторить
Сделать запись любому игроку.

**Comment by Dennok** [comment]
Такое наверное со всеми записами.
Заметил такое-же в логах мехов.
