### ISSUE TITLE
Атмос неправильно тащит объекты

### ISSUE THREAD

**Issue by kalazus** [TauCetiStation/TauCetiClassic#9869]
#### Подробное описание проблемы
Сейчас атмос тащит тела в сторону, где зоны соединились, а не из большего давления в меньшее.

#### Что должно было произойти
При фороновом пожаре тела тащат от пожара

#### Что произошло на самом деле
Тела тащат к пожару

#### Как повторить
Устроить фороновый пожар

#### Дополнительная информация:
P.s. сломал я достаточно давно (или кто-то ещё лазил в атмос), но не знаю как скоро освободиться время найти ошибку

**Comment by kalazus** [comment]
Проблема скорее всего в этом проке https://github.com/TauCetiStation/TauCetiClassic/blob/a4a0350ef07f9e75de498e6dddad1267f7821c99/code/modules/atmospheric/ZAS/Airflow.dm#L100

**Comment by Akellazp** [comment]
похожая фигня иногда происходит с высасыванием в космос и тебя телепает туда-сюда
