### ISSUE TITLE
При отключение любого бинда IC-Say - ALT, SHIFT и CTRL работают как бинд для Say. 

### ISSUE THREAD

**Issue by WispOfKind** [TauCetiStation/TauCetiClassic#9871]
#### Подробное описание проблемы
После того, как мы убираем ЛЮБОЙ бинд IC-say, будь то "f3" или "t" -  ALT, SHIFT и CTRL продолжают выполнять свои функции, но при их нажатии ( по отдельности ) возникает окно Say
#### Что должно было произойти
Выбранный бинд должен был отключиться, а Shift, alt и ctrl должны были работать исправно
#### Что произошло на самом деле
Отключенный бинд отключился, но при нажатии указанных кнопок появлялось окно Say
#### Как повторить
Зайти в бинды и удалить любой бинд IC-Say

**Comment by KIBORG04** [comment]
https://github.com/TauCetiStation/TauCetiClassic/issues/8319
