### ISSUE TITLE
После пра с реворком призыва нар-си, он вообще не призывается

### ISSUE THREAD

**Issue by INwirstD** [TauCetiStation/TauCetiClassic#9884]
#### Подробное описание проблемы
После пра https://github.com/TauCetiStation/TauCetiClassic/pull/9767, нар-си не призывается, даже если выполнены все условия.
#### Что должно было произойти
Нар-си начинает призыватся
#### Что произошло на самом деле
You begin preparations for the ritual... и ВСЁ
#### Как повторить
Поставить алтарь, принести кого то в жертву, поставить четыре пилона и четыре культиста

**Comment by Chip11-n** [comment]
Мой проёб, исправляю

**Comment by Pirsnya** [comment]
#9885
