### ISSUE TITLE
Интеркомы склонные к растворению в кислоте и стеклянные предметы.

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#989]
#### Подробное описание проблемы
Кислота разъедает интеркомы, но не разъедает камеры, датчики воздуха и многое иное. Так же разъедает стекло которое лежит, и стеклянные банки, и все что стеклянное целиком, и не должно разъедаться кислотой.

#### Что должно было произойти
Интеркомы должны оставаться целыми как и оборудование созданное целиком из стекла, а так же само стекло.

#### Что произошло на самом деле
Интеркомы растворились. И все что создано из стекла.

#### Как повторить

![](http://image.prntscr.com/image/30b83370305e4eddaca8cba009814a69.png)

**Comment by igigin** [comment]
Почему ты ставишь как проблему уничтожение интеркомов, а не неуничтожение всего остального?

**Comment by P-20** [comment]
Я вообще хотел поставить эту проблему, да. Но не думаю что найдется тот кто этим займется. Сейчас тогда сделаю небольшие коррективы.

**Comment by Dennok** [comment]
Ну, интеркомы невозможно починить. Хотя их никто не использует.

**Comment by DeadOberst** [comment]
А как же ИИ для прослушки?
