### ISSUE TITLE
Уничтожение стен от грибка+Мыла

### ISSUE THREAD

**Issue by 4Donic** [TauCetiStation/TauCetiClassic#9894]
#### Подробное описание проблемы
Если мылом (Я был боргом уборщиком) ударить по грибку на стене - стена вырезается как горелкой.
#### Что должно было произойти
Уйти грибок
#### Что произошло на самом деле
В описании
#### Как повторить
В описании
#### Дополнительная информация:
Issue reported from  Round ID: 53715 (Tau Ceti Classic (RU))
Testmerges: ```#9605 #9727 #9784 #9808 ```
Reporting client version: 514.1585

**Comment by Smalltasty** [comment]
Грибок вроде бы только горелкой выжигается? Это же ржавчина, с чего ей мылом уходить? 
А от мыла оно ломается так же как и от того если его потрогать. 
Вопрос: Баг ли?

**Comment by KIBORG04** [comment]
Первый раз слышу, чтобы это чинилось мылом

**Comment by TheLone1y** [comment]
Ты не можешь бить мылом, ты тронул рукой, обычная стена с грибком ломается и кулачком
