### ISSUE TITLE
[Предложение]Многофункциональный-RCD

### ISSUE THREAD

**Issue by P-20** [TauCetiStation/TauCetiClassic#993]
#### Подробное описание проблемы
RCD делает лишь обычные шлюзы со стандартным доступом, и не можешь делать стеклянные двери, или же выбирать их расцветку.
На TG/Парадайзах у RCD есть возможность строить шлюзы уже с доступом,выбирая расцветку и то стеклянные они, или же обычные, возможность выбирать цвет пола и т.д. на TG функционал RCD упрощен, на билде парадайза открывается полноценное окно РЦД с выбором режима и конфигурации.

#### Что должно было произойти
Paradise
![](http://image.prntscr.com/image/35a5bf9eb795423b9b66e68216b33ab9.png)

![](http://image.prntscr.com/image/6972bcc465a7496fb0615decd5fef805.png)
TG
Выбор режима через ПКМ.

**Comment by Damirrus1** [comment]
Кидай сразу ссылку на ПР

**Comment by P-20** [comment]
https://github.com/ParadiseSS13/Paradise/pull/4638

**Comment by Dennok** [comment]
Воттакто лучше.
