### ISSUE TITLE
Суперматтерия крашит сервера!

### ISSUE THREAD

**Issue by Mercurialaste** [TauCetiStation/TauCetiClassic#9936]
#### Подробное описание проблемы
Если пшикнуть из огнетушителя на суперматтерию, сервер сломается.
#### Что должно было произойти
Ничего.
#### Что произошло на самом деле
Сервер сломался.
#### Как повторить
Взять огнетушитель из сделать пшш пшш...
#### Дополнительная информация:
Причина:
Принятие null в этой строке.
https://vscode.dev/github/Tap0r/TauCetiClassic/blob/7d1e37cd9d094de8bd269a976f9e1b288fd4406f/code/modules/reagents/reagent_containers/spray.dm#L160

**Comment by volas** [comment]
у меня эта ссылка вечность открывается, https://github.com/Tap0r/TauCetiClassic/blob/7d1e37cd9d094de8bd269a976f9e1b288fd4406f/code/modules/reagents/reagent_containers/spray.dm#L160

**Comment by Mercurialaste** [comment]
![image](https://user-images.githubusercontent.com/90282587/187265210-54a48469-a01b-4e1f-9e8e-86af06ea0710.png)

**Comment by volas** [comment]
раунд есть?

**Comment by Mercurialaste** [comment]
> у меня эта ссылка вечность открывается, https://github.com/Tap0r/TauCetiClassic/blob/7d1e37cd9d094de8bd269a976f9e1b288fd4406f/code/modules/reagents/reagent_containers/spray.dm#L160

браузерный ВС код, у меня за секунд 15 открылась

**Comment by Mercurialaste** [comment]
> раунд есть?

Я это делал на локальном сервере

**Comment by Mercurialaste** [comment]
bruh
![image](https://user-images.githubusercontent.com/90282587/187316925-a262f620-d3c6-4e7a-8d26-d6954d3ca997.png)
*(Сервер не крашится, а ВС код приостанавливает сеанс из-за null.)*

**Comment by KIBORG04** [comment]
норм, тогда закрывают?

**Comment by Mercurialaste** [comment]
хз, как понимаю, это исключение, не норм, хотя в игре вроде, работает нормально+не вызывает рантаймы.
*(Пришлось немного побайтить человека на смене, чтобы он попробовал "потушить" суперматтерию, ничего не произошло.)*
