### ISSUE TITLE
Риг не защищает от форона

### ISSUE THREAD

**Issue by Elisei24** [TauCetiStation/TauCetiClassic#9937]
#### Подробное описание проблемы
Сквозь риги одежда (перчатки, джампсьюты, ботинки) заражаются фороном (даже через инженерные и риг СЕ). Следовательно, начинают убивать носящего, следовательно, делают риги при фороновой атмосфере почти бесполезными.
#### Что должно было произойти
Риг защищает от воздействия форона в воздухе
#### Что произошло на самом деле
По бумагам риг должен защищать, по факту механ заражения вещей клал на защиту рига
#### Как повторить
Надеть риг, зайти в форон
#### Дополнительная информация:
Issue reported from  Round ID: 53940 (Tau Ceti Classic (RU))
Testmerges: ```#9673 #9727 #9808 #9875 #9879 #9914 #9930 ```
Reporting client version: 514.1585

**Comment by Deahaka** [comment]
Пожарный костюм кстати тоже не защищает от пожара. Грустно

**Comment by BunkyFly** [comment]
> Пожарный костюм кстати тоже не защищает от пожара. Грустно

Костюмы биоугрозы тоже не защищают от вирусов

**Comment by Elisei24** [comment]
Space Station 13 experience, как говорится

**Comment by Elisei24** [comment]
А, багу уже два года, поняв.

**Comment by Elisei24** [comment]
Я тебя породил, я тебя и убью (с)

**Comment by Deahaka** [comment]
Не баг а фича

**Comment by simb11** [comment]
в эту игру могут играть двое
не фича а баг
