### ISSUE TITLE
[Предложение]Добавить в карго ящики с платами и компонентами для машин определенного отсека.

### ISSUE THREAD

**Issue by Dennok** [TauCetiStation/TauCetiClassic#994]
Добавить в карго ящики с компонентами для машин разных отсеков для отстройки их, или постройки новых, в обход РнД. Компоненты конешно там будут стандартные(можно еще добавить улучшенные компоненты но за большую цену).

Особенно ценно если бомбанули телекомы а РнД или шахтеров нет чтоб создать платы и компоненты на станции.

**Comment by Damirrus1** [comment]
Нет

**Comment by Dennok** [comment]
Причина?

**Comment by Damirrus1** [comment]
Жирно

**Comment by Dennok** [comment]
Чемже? Цену норм поставтиь и норм. У нас материю купить момжно, а платы для автоматов/гриддеров/слиперов нет?

**Comment by P-20** [comment]
Согласен, с этим перебор, ведь для исследования этих плат достаточно пяти минут, а так их будет иметь любой с доступом к карго.

**Comment by Damirrus1** [comment]
Да причем тут цена? Если 20 мусора стоит ~18к. Жирно это

**Comment by Dennok** [comment]
И заплатит за это 2к, или 5к

**Comment by Dennok** [comment]
Ага, вот если ученых нет?

**Comment by Dennok** [comment]
Да и не 18к 20 мусора стоит. вчера продавал два стака еле 7к нагреб

**Comment by Damirrus1** [comment]
Страдай. А ДАВАЙТЕ ВСЕ СДЕЛАЕМ ДЛЯ СЕБЯ, ЗОЧЕМ МЫ ИГРАЕМ В СЕТЕВУЮ ИГРУ? Ученым - астероид рядом и доступ еще, а не, еще полный доступ.

**Comment by Dennok** [comment]
И да. неплохо былобы добавит ьвозможность продавать разработки РнД. или уже ввели?

**Comment by Dennok** [comment]
И да, у ученых уже есть атсероид.

**Comment by Damirrus1** [comment]
http://tauceti.ru/forums/index.php?topic=1574.0

**Comment by Dennok** [comment]
Это не охренительная идея.

**Comment by Dennok** [comment]
и да, можно добавить технику которую невозможно построить.

**Comment by WallShrabnic** [comment]
Обычно, если бомбанули телекоммы, то уже слишком поздно мыть клубнику

**Comment by Dennok** [comment]
Ну. я имел в виду не режим нюцки(даже если победили нюцку всем плевать и рестарт) а триторню(хотя кто щас даст бомбануть).

**Comment by Dennok** [comment]
Дело в том что раньше на спетнике телекомов были запастные части для починки, а щас с переносом их проипли.

**Comment by Skippeer12** [comment]
Как заруинить катку в два клика.
Выкрутить плату деконструктора в РнД.
Забрать запасную плату деконструктора в хранилище плат, куда у ученых по какой либо мне не понятной причине нет доступа.

Катка заруинена, РнД негодует, тритор доволен. Профит..

**Comment by Dennok** [comment]
Таки так.

**Comment by WallShrabnic** [comment]
Максимум кто доволен при подобном раскладе - нюкер или пират. Тритоте просто становятся недоступны халявные платы для ИИ и куча полезной машинерии.

К вопросу о доступе - это же склад запасных плат, которые предназначены для инженерного и специально отгорожены от учёных, которые спят и видят, как эти платы деконструктнуть

**Comment by Dennok** [comment]
А какже уничтожения всех способов легального ингейм вызова/отзыва шаттла

**Comment by Dennok** [comment]
А еще уничтожив РнД можн уничтожить телекомы так чтоб их не починили
