### ISSUE TITLE
Откат настроек и префов каждый раунд

### ISSUE THREAD

**Issue by Udokun** [TauCetiStation/TauCetiClassic#9941]
#### Подробное описание проблемы
Каждый раз, когда я меняю в occupation значение на "Get random job if preferences unavailable", после перезапуска сервера значение возвращается на "Return to lobby if preference unavailable". Закликивание кнопки Save slot не помогает.
Тоже самое относится и к префам. Включил атак лог, в конце раунда выключил и теперь каждый раунд он у меня в включенном состоянии.
#### Что должно было произойти
![Screenshot_2](https://user-images.githubusercontent.com/24526545/187396037-894c11ca-029a-41c2-8a1d-169391e4c115.jpg)
#### Что произошло на самом деле
![Screenshot_1](https://user-images.githubusercontent.com/24526545/187395917-1301b590-3e20-4984-adc7-8f18e51235c3.jpg)
#### Как повторить
Должно повезти так же как и мне.

**Comment by Deahaka** [comment]
Подтверждаю, оно всегда сбрасывается и часто мешает.

**Comment by TauKitty** [comment]
Эта проблема была упомянута в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/reklama-ishuya-i-baga/35966/2
