### ISSUE TITLE
Перманетная глухота после большого колличества флешек

### ISSUE THREAD

**Issue by flying-george** [TauCetiStation/TauCetiClassic#9948]
#### Подробное описание проблемы
Перманентная поломка ушей
#### Что должно было произойти
Уши ломаются на время, и лечатся Ауризином
#### Что произошло на самом деле
После 5 флешек подряд уши перестают слышать напрочь, и чинится только генетикой. При отрубании головы чел мгновенно скис и больше не дефибался, не знаю уж, относится ли это к этому багу 
#### Как повторить
Кинуть в бармена 5 флешек подряд и пытаться лечить Ауризином
#### Дополнительная информация:
Issue reported from  Round ID: 53969 (Tau Ceti Classic (RU))
Testmerges: ```#9673 #9727 #9808 #9875 #9879 #9914 #9930 ```
Reporting client version: 514.1578

**Comment by flying-george** [comment]
Генетикой, всмысле клонированием

**Comment by Motzord** [comment]
Лично в раунде закидал бармена флешками. Маг кстати излечился от глухоты, а вот с барменом пришлось совершать военные преступления
