### ISSUE TITLE
Пневмотрубы разрывают пулл

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#9951]
#### Подробное описание проблемы
Древний бесящий баг который никто не пофиксил: При облете станцию на джетпаке, среднестатистический космонавт, таскает свои пожитки пуллом, однако при переходе через пневмотрубы (ведущие на спутник ИИ), внезапно пулл обрывается.
#### Что должно было произойти
Не обрывается?
#### Что произошло на самом деле
Обрывается
#### Как повторить
Тащите сумку пуллом через пневмотрубу и расстройтесь

**Comment by Fluffy-510** [comment]
Я думал это фича

**Comment by KIBORG04** [comment]
Это хардкод
