### ISSUE TITLE
[Proposal] На кексы больно смотреть

### ISSUE THREAD

**Issue by Deahaka** [TauCetiStation/TauCetiClassic#9962]
## Подробное описание проблемы
Они выглядят как говно из PS1
![11111111111111111](https://user-images.githubusercontent.com/96499407/187975736-b8e39ad4-55b4-4142-a5da-87dc9642c3b1.png)
Зареспрайтите пожалуйста до нормального состояния.

**Comment by Tap0r** [comment]
Кексы ахуенны, не респрайтите нет не надо пжпжпжпжжп бога молю кексы оооо с изюмом 4к ультра хддхдхд

**Comment by Deahaka** [comment]
> 4к ультра хддхдхд

этого всего тут нет

**Comment by Tap0r** [comment]
> > 4к ультра хддхдхд
> 
> этого всего тут нет

Ну на всём кроме кексов, да

**Comment by Tobyyyan** [comment]
У нас с телескопичкой та же история, просто спрайт сам по себе старый.
