### ISSUE TITLE
В бриге бокса нет петушителей

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#9977]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/45365635/188277560-fa8ae10c-ea5e-47e3-a6c1-a2443b295c63.png)

#### Что должно было произойти
Петушители есть в коридоре брига/раздевалке/etc
#### Что произошло на самом деле
Единственный спизженный огнетушитель из лобби брига и коридора в бриг заставляет офицеров паниковать от брошенной бутылочки с топливом
#### Как повторить
Украдите огнетушитель из лобби (или заправьте его топливом)
Разведите костер в бриге при помощи зажигалки и бутылки пива
TROLLED
![image](https://user-images.githubusercontent.com/45365635/188277599-a6cd957c-a113-4989-83c2-2f6518988a82.png)

#### Дополнительная информация:
Раньше петушитель был возле карцеров, но сейчас туда переехала допросная

**Comment by RONSI7** [comment]
> Украдите огнетушитель из лобби

Огнетушитель еще можно заполнить топливом, что бы горящие офицеры туши себя горючим. Я, кстати, один раз за клоуна так и сделал и внес существенный вклад в победу революции.

**Comment by Motzord** [comment]
> > Украдите огнетушитель из лобби
> 
> Огнетушитель еще можно заполнить топливом, что бы горящие офицеры туши себя горючим. Я, кстати, один раз за клоуна так и сделал и внес существенный вклад в победу революции.

>>Украдите огнетушитель из лобби (или заправьте его топливом)

https://youtu.be/6GmIZG-SgqM

**Comment by RONSI7** [comment]
> > > Украдите огнетушитель из лобби
> > 
> > 
> > Огнетушитель еще можно заполнить топливом, что бы горящие офицеры туши себя горючим. Я, кстати, один раз за клоуна так и сделал и внес существенный вклад в победу революции.
> 
> > > Украдите огнетушитель из лобби (или заправьте его топливом)
> 
> https://youtu.be/6GmIZG-SgqM

Газлайтинг.

**Comment by Motzord** [comment]
> Огнетушитель еще можно заполнить топливом, что бы горящие офицеры туши себя горючим. Я, кстати, один раз за клоуна так и сделал и внес существенный вклад в победу революции.

![image](https://user-images.githubusercontent.com/45365635/188283407-098e30fe-9919-458e-973a-64feb7a18037.png)

**Comment by KatoMarika** [comment]
Сейчас в бриге три огнетушителя, плюс один в техах на востоке от него, и один чуть дальше по коридору, наверное можно закрыть.
