### ISSUE TITLE
Некоректное отображение ресурсов в автолате

### ISSUE THREAD

**Issue by Motzord** [TauCetiStation/TauCetiClassic#9984]
#### Подробное описание проблемы
Даже скилловый КМ или кто-то еще очень крутой и разбирающийся в автолатах, вместо корректной картиночки металла и стекла видит это
![image](https://user-images.githubusercontent.com/45365635/188282996-e2ea37bd-705b-4e5b-9cba-ef6571cef89d.png)

#### Что должно было произойти
Видно металл и стекло
#### Что произошло на самом деле
Радужный банан и имплантер
#### Как повторить
Посмотрите в интерфейс автолата

**Comment by Motzord** [comment]
Замечена также пропажа иконок ресурсов в протолате

![image](https://user-images.githubusercontent.com/45365635/188283213-695ef8b2-97a5-42e2-a6ae-a2bf6f3e9afc.png)

**Comment by BlankCringe** [comment]
спустя 3 месяца это кто-то зарепортил

**Comment by kalazus** [comment]
Да не, это уже минимум 2 раз.

**Comment by Fenriros** [comment]
Бананы - это хорошо.
Но работающий интерфейс - еще лучше.
