### ISSUE TITLE
Баг операционной прометея.

### ISSUE THREAD

**Issue by BlankCringe** [TauCetiStation/TauCetiClassic#9995]
#### Подробное описание проблемы
Один из сканеров в хирургии неработает.
#### Что должно было произойти
Сканер работает.
#### Что произошло на самом деле
Сканер не работает (окошка нет), вылазит котик рантайм и говорит что аномалия #170
#### Как повторить
Использовать сканер в правой операционной прометея.

**Comment by Tap0r** [comment]
Вечером гляну пофикшу
